# ---------------------------------------------------------------------------
# Record 088 — NMR CPMG T2 salt-cavern brine, designed, MODIFY
# ---------------------------------------------------------------------------
def rec_088():
    raster = make_raster(
        neurons=20,
        mean_rate_hz=50.0,
        window_ms=40.0,
        seed=20260988,
        source="sw5.nmr.t2",
        target="saltwick.brine_core",
        table=[
            {"from": "cpmg_echo_train", "to": "t2_estimator", "weight": 1.40},
            {"from": "salinity_head", "to": "withdrawal_interlock", "weight": 1.15},
            {"from": "scada_density", "to": "rated_withdraw_advocate", "weight": 0.45},
        ],
        third_factor={
            "modulator": "na.t2_salinity_salience",
            "tau_e_s": 1.6,
            "tau_e_ms": 1600.0,
            "eligibility": "pre-post coincidence on brine synapses; the modulator enables potentiation only while reconstructed T2 and NaCl wt percent are co-active inside tau_e",
        },
        channel_prefix="nmr.n",
        anchor="SW-5 NMR 40 ms frame at T2 80.00 ms (t_s 840); first salt-fall trip sample",
    )
    w_s = 0.04
    events = [
        ev(0.0, "w.rated", 180.0, code="M3H", units="m3_h", note="Saltwick SW-5 cavern well W-4 rated withdrawal 180 m3/h"),
        ev(60000.0, "well.id", 4.0, code="WELL", units="id"),
        ev(120000.0, "t2.fresh", 200.0, code="MS", units="ms", note="fresh-brine T2_f"),
        ev(180000.0, "k.s", 3200.0, code="WT_MS", units="wt_ms"),
        ev(240000.0, "B.t", 0.050, code="T", units="T", note="low-field CPMG sondes at 50 mT"),
        ev(300000.0, "cpmg.te", 4.00, code="MS", units="ms"),
        ev(360000.0, "n.echo", 20.0, code="COUNT", units="count"),
        ev(420000.0, "dens.scada", 1.050, code="G_ML", units="g_ml", note="denial channel: 4 wt percent folklore"),
        ev(480000.0, "vend.nacl", 8.00, code="WT_PCT", units="wt_pct", note="Caveveil last-good salinity cloud"),
        ev(540000.0, "t2.lg", 160.0, code="MS", units="ms", note="vendor last-good T2"),
        ev(600000.0, "nacl.lg", 4.00, code="WT_PCT", units="wt_pct", note="3200*(1/160-1/200)=4.00"),
        ev(660000.0, "sop.nacl", 20.00, code="WT_PCT", units="wt_pct"),
        ev(720000.0, "sop.t2", 100.0, code="MS", units="ms"),
        ev(780000.0, "ops.night", 1.0, code="SLOT", units="bool", note="night withdrawal slot armed"),
        ev(840000.0, "t2.ms", 80.00, code="T2_TRIP", units="ms", note="raster sidecar is this 40 ms frame"),
        ev(840001.2, "nmr.burst", 80.00, code="MS", units="ms", note="echo-train burst"),
        ev(840002.4, "nmr.burst", 65.60, code="MS", units="ms", note="same-channel 1.2 ms; adapted 0.82x plus noise"),
        ev(840003.7, "nmr.burst", 53.80, code="MS", units="ms", note="third burst 1.3 ms; adapted"),
        ev(846000.0, "nacl.wt", 24.00, code="WT_PCT", units="wt_pct", note="3200*(1/80-1/200)=24.00 exact"),
        ev(852000.0, "ops.prop", 1.0, code="KEEP_180", units="bool", note="night operator: density 1.050 looks dilute, keep 180 m3/h"),
        ev(912000.0, "gate.nmr", 1.0, code="MODIFY", units="decision"),
        ev(924000.0, "w.cmd", 108.0, code="M3H", units="m3_h", note="0.60*180=108"),
        ev(936000.0, "iso.cmd", 1.0, code="WELL_W4", units="bool"),
        ev(2736000.0, "hold.floor", 1.0, code="T30MIN", units="bool", note="936 s + 1800 s T2 settle"),
        ev(2796000.0, "brine.T", 22.0, code="C", units="C"),
        ev(2856000.0, "t2.ms", 80.00, code="MS", units="ms"),
        ev(2916000.0, "w.cap", 120.0, code="RESTORE_CAP", units="m3_h"),
        ev(2976000.0, "gate.exec", 1.0, code="ACCEPT", units="decision", note="companion t2: 108 m3/h plus W-4 isolate executed"),
        ev(3036000.0, "w.now", 108.0, code="M3H", units="m3_h"),
        ev(3096000.0, "nacl.wt", 24.00, code="WT_PCT", units="wt_pct"),
        ev(3156000.0, "dens.scada", 1.050, code="G_ML", units="g_ml", note="density never left 1.050"),
        ev(3216000.0, "well.hold", 1.0, code="W4_HOLD", units="bool"),
    ]
    assert_stream(events)

    traj = {
        "id": "nelb-r29-088-t1",
        "state": {
            "sim_or_real": "designed",
            "episode_id": "SW-NMR-2026-0612",
            "domain": "nmr_cpmg_t2_cavern",
            "setting": "Saltwick Cavern, well W-4, SW-5 (invented). Low-field CPMG NMR sonde (50 mT) on the brine string; SCADA density 1.050 g/mL is the denial SoT. Night 180 m3/h withdrawal is armed. Invented plant; designed campaign. Not MRI quench detection (r13 Frostlip), not muon ore-pass (r17), not N-16 transit (r24), not ECT inventory (r20/r22).",
            "observables_at_decision": {
                "T2_ms": 80.00,
                "T2_fresh_ms": 200.0,
                "k_s_wt_ms": 3200.0,
                "NaCl_wt_pct": 24.00,
                "scada_density_g_ml": 1.050,
                "vendor_NaCl_wt_pct": 8.00,
                "T2_last_good_ms": 160.0,
                "withdraw_m3_h": 180.0,
            },
            "margin_authority": "SW-5 cavern SOP rev C: if reconstructed NaCl wt percent >= 20.00 AND T2_ms < 100.0, 180 m3/h withdrawal is forbidden even if SCADA density is still under 1.080 g/mL",
        },
        "proposed_action": {
            "actor": "night operator, citing a dilute density channel and a committed withdrawal slot",
            "summary": "keep 180 m3/h on W-4; treat the CPMG T2 channel as a noisy downhole spare",
            "basis_claimed": "SCADA density is 1.050 g/mL, under the 1.080 g/mL salt-fall alarm; Caveveil last-good is 4.00 wt percent",
        },
        "safety_decision": {
            "decision": "MODIFY",
            "rationale": "Rated withdrawal is refused, not the well. SOP rev C is conjunctive: reconstructed NaCl is 24.00 wt percent (3200*(1/80-1/200), serialized) and T2 is 80.00 ms, both over the 20.00 wt percent / 100 ms floors, while SCADA density still reads 1.050. Ordered: isolate W-4 from the 180 m3/h header, drop withdrawal to 108 m3/h (0.60*180), hold 30 min for T2 settle, then restore only to 120 m3/h until T2_ms > 120. A dilute density channel cannot substitute for the CPMG T2 reconstruction.",
            "threshold": "NaCl_wt_pct>=20.00 AND T2_ms<100.0 => forbid 180 m3/h",
            "stated_residuals": "72 m3/h deferred tonight; T2-to-viscosity coupling that could fake a short T2 inside a warm brine is unwritten",
        },
        "executed_action": {
            "summary": "MODIFY at t_s 912: W-4 isolate latched, withdrawal 180 -> 108 m3/h; NaCl stayed 24.00 at the 30 min floor",
            "tool": "sw5-nmr-t2-gate-cli",
            "observation": "header stay-isolated; brine 22 C at the 30 min floor; T2 80.00 ms held; density stayed 1.050",
        },
        "future_outcome": {
            "timeline": [
                {"t_s": 780.0, "event": "night withdrawal slot armed"},
                {"t_s": 840.0, "event": "CPMG T2 80.00 ms salt-fall trip; raster frame captured"},
                {"t_s": 846.0, "event": "NaCl 24.00 wt percent vs 20.00 floor"},
                {"t_s": 912.0, "event": "MODIFY: 108 m3/h plus W-4 isolate"},
                {"t_s": 2736.0, "event": "30 min T2 floor in-stream"},
                {"t_s": 2976.0, "event": "companion execution ACCEPT; restore cap 120 m3/h"},
            ],
            "observed_effects": [
                "NaCl recomputes from k_s*(1/T2-1/T2_f) at every nacl.wt event",
                "SCADA density never crossed 1.080, so a density-only head would have ACCEPTed 180 m3/h",
                "T2 last-good 160 ms still reconstructs only 4.00 wt percent and cannot substitute",
            ],
            "surprises": [
                "Caveveil 8.00 wt percent sits between the 4.00 last-good reconstruction and the 24.00 plant T2, so a vendor-cloud average would have split the difference and kept the slot",
            ],
            "new_state": {
                "sw5": "withdrawal 108 m3/h, restore cap 120 m3/h pending T2_ms > 120",
                "well_w4": "stay-isolated from the 180 header",
                "reconstruction_model": "discharged as an on-record calculator, not a referenced envelope",
            },
            "latency_ms": 12000.0,
        },
        "reward_components": reward(
            0.41,
            [
                ("nmr_t2_reconstruction", 0.14),
                ("conjunctive_salinity", 0.12),
                ("density_nonsubstitution", 0.10),
                ("withdrawal_hold", 0.07),
                ("throughput_cost", -0.02),
            ],
            "scored for refusing 180 m3/h on a recomputable T2 salinity while density SCADA looked dilute; throughput_cost prices the 108 m3/h cut",
        ),
        "meta": meta_common(
            tags=["MODIFY", "nmr-cpmg-t2", "serialized-reconstruction", "operational-companion"],
            distillation_note="NMR gate: serialized k_s*(1/T2-1/T2_f) plus T2 floor beats a dilute density channel; companion t2 is the 108 m3/h / W-4 isolate execution, not a governance vote",
        ),
    }
    traj2 = {
        "id": "nelb-r29-088-t2",
        "state": {
            "sim_or_real": "designed",
            "episode_id": "SW-NMR-2026-0612-exec",
            "domain": "withdrawal_hold_execution",
            "setting": "Same SW-5 after the MODIFY. This companion is the operational 108 m3/h cut, W-4 isolate, and 120 m3/h restore cap, not a second policy vote.",
            "observables_at_decision": {
                "withdraw_cmd_m3_h": 108.0,
                "w4_isolate": True,
                "T2_ms": 80.00,
                "brine_C": 21.0,
            },
        },
        "proposed_action": {
            "actor": "cavern controller following the MODIFY",
            "summary": "execute 108 m3/h and W-4 isolate, then restore only to 120 m3/h when T2_ms > 120 after the 30 min floor",
            "basis_claimed": "MODIFY requirements are fully specified and in-envelope for the withdrawal valves",
        },
        "safety_decision": {
            "decision": "ACCEPT",
            "rationale": "The execution envelope is intact: valve slew 4.0 m3/h/s is under 8.0, brine 21 C is under 35, W-4 isolate is already true, and the restore cap is 120 not 180. ACCEPT the sequence. Do not re-arm 180 m3/h tonight; 120 is the cap until T2_ms > 120.",
            "threshold": "slew_m3_h_s<=8.0 AND brine_C<=35 AND restore_cap_m3_h=120",
        },
        "executed_action": {
            "summary": "withdrawal 108 m3/h latched at t_s 924; W-4 isolate; restore cap 120 m3/h at t_s 2916 after T2 80.00",
            "tool": "sw5-withdraw-exec",
            "observation": "no header reopen; flow 108; T2 still 80.00 ms",
        },
        "future_outcome": {
            "timeline": [
                {"t_s": 924.0, "event": "withdrawal 108 m3/h latched"},
                {"t_s": 936.0, "event": "W-4 isolate latched"},
                {"t_s": 2736.0, "event": "30 min T2 floor"},
                {"t_s": 2976.0, "event": "companion ACCEPT; restore cap 120 m3/h"},
            ],
            "observed_effects": [
                "NaCl stayed 24.00 without leaving the isolated string",
                "restore stopped at 120 m3/h as capped; 180 not re-entered",
            ],
            "new_state": {"withdraw_m3_h": 108.0, "restore_cap_m3_h": 120.0},
            "latency_ms": 12000.0,
        },
        "reward_components": reward(
            0.33,
            [
                ("envelope_respect", 0.12),
                ("withdraw_108", 0.10),
                ("restore_cap_120", 0.08),
                ("header_not_rearmed", 0.05),
                ("hold_time_cost", -0.02),
            ],
            "operational execution gate: the companion does the withdrawal cut rather than re-arguing the T2 call",
        ),
        "meta": meta_common(tags=["ACCEPT", "operational-execution", "withdraw-hold"]),
    }
    return {
        "id": "nelb-r29-088",
        "spike_events": events,
        "language_view": {
            "description": "Low-field CPMG NMR on Saltwick SW-5 well W-4. T2 80.00 ms reconstructs 24.00 wt percent NaCl while SCADA density still reads 1.050 g/mL; Caveveil last-good T2 160 ms still says 4.00 wt percent with a 180 m3/h night slot armed. The gate MODIFYs to 108 m3/h plus W-4 isolate; a companion execution ACCEPT runs the cut and caps restore at 120 m3/h. The salinity model is serialized so every nacl.wt amplitude recomputes from k_s*(1/T2-1/T2_f).",
            "trajectory": traj,
            "trajectory_withdraw_hold_execution": traj2,
        },
        "bridge_notes": {
            "channel_map": {
                "t2.ms / nmr.burst / nacl.wt": "CPMG physics and serialized salinity",
                "dens.scada": "denial channel: dilute density",
                "t2.lg / nacl.lg / vend.nacl": "vendor last-good that still reconstructs 4.00 wt percent",
                "ops.prop / gate.nmr / gate.exec": "proposal, MODIFY, companion ACCEPT",
                "w.cmd / iso.cmd / w.cap": "execution channels for the operational companion",
            },
            "temporal_motifs": [
                "density-dilute while T2-sick: dens.scada 1.050 adjacent to nacl.wt 24.00",
                "reconstruction as event: nacl.wt 24.00 equals 3200*(1/80-1/200)",
                "MODIFY then operational ACCEPT: gate.nmr at 912 s, gate.exec at 2976 s",
                "adapted echo-train triplet at 1.2/1.3 ms encodes the T2 trip at raster scale",
                "30 min T2 floor as hold.floor bookend at 2736 s",
            ],
            "language_to_spike_mapping": "'density is dilute' = dens.scada 1.050; '24.00 wt percent' = nacl.wt; 'forbid 180 m3/h' = gate.nmr MODIFY; 'execute the cut' = w.cmd then companion ACCEPT",
            "why_high_value": "New NMR-CPMG-T2 cavern family (not r13 MRI quench, not r17 muon tomography, not r24 N-16 transit, not r20 ECT inventory). Serializes a T2 salinity reconstruction that a density channel cannot see. Companion t2 is operational execution, not a governance vote.",
            "encoder_spec": {
                "prng": "MT19937 via python random.Random",
                "seeds": {"raster": 20260988, "stream_note": "stream amplitudes are authored constants (ms, wt percent, m3/h, g/mL) plus nmr.burst adaptation 0.82**k"},
                "draw_order": "raster: per neuron id order, gap-constrained times, per-spike adaptation and noise",
                "thinning": "CPMG echo train exists at 20 echoes; stream keeps T2 envelope; nacl.wt keeps 3 of ~40 solver ticks",
                "refractory_floors_ms": {
                    "w.rated": 60000,
                    "well.id": 60000,
                    "t2.fresh": 60000,
                    "k.s": 60000,
                    "B.t": 60000,
                    "cpmg.te": 60000,
                    "n.echo": 60000,
                    "dens.scada": 60000,
                    "vend.nacl": 60000,
                    "t2.lg": 60000,
                    "nacl.lg": 60000,
                    "sop.nacl": 60000,
                    "sop.t2": 60000,
                    "ops.night": 60000,
                    "t2.ms": 60000,
                    "nmr.burst": 0.8,
                    "nacl.wt": 60000,
                    "ops.prop": 60000,
                    "gate.nmr": 60000,
                    "w.cmd": 60000,
                    "iso.cmd": 60000,
                    "hold.floor": 60000,
                    "brine.T": 60000,
                    "w.cap": 60000,
                    "gate.exec": 60000,
                    "w.now": 60000,
                    "well.hold": 60000,
                },
                "time_alias": "t_rel_ms; t0 = 2026-06-12T02:10:00Z night withdrawal commit",
            },
            "distillation_targets": [
                "serialized NMR T2 reconstruction head: NaCl = k_s * (1/T2 - 1/T2_f)",
                "conjunctive SOP head: NaCl AND T2, never density substitution",
                "operational companion: execute the withdrawal cut without re-opening the T2 call",
            ],
        },
        "reconstruction_model": {
            "name": "nmr_cpmg_t2_nacl",
            "formula": "NaCl_wt_pct = k_s * (1/T2_ms - 1/T2_fresh_ms); withdraw_hold_m3_h = 0.60 * withdraw_rated_m3_h",
            "parameters": {
                "k_s_wt_ms": 3200.0,
                "T2_fresh_ms": 200.0,
                "T2_trip_ms": 80.00,
                "T2_last_good_ms": 160.0,
                "nacl_floor_wt_pct": 20.00,
                "t2_floor_ms": 100.0,
                "withdraw_rated_m3_h": 180.0,
            },
            "worked_example": {
                "T2_ms": 80.00,
                "NaCl_wt_pct": 24.00,
                "T2_last_good_ms": 160.0,
                "NaCl_last_good_wt_pct": 4.00,
                "withdraw_hold_m3_h": 108.0,
            },
            "check": "3200*(1/80-1/200)=3200*0.0075=24.00; 3200*(1/160-1/200)=3200*0.00125=4.00; 0.60*180=108",
        },
        "raster": raster,
        "gate_snn": {
            "decision": "MODIFY",
            "decision_window_ms": 40.0,
            "decision_window_s": 0.04,
            "code": "sw5.nmr_t2_gate",
            "note": "MODIFY accumulator wins: T2 plus salinity evidence overpower the rated-withdrawal advocate",
            "populations": [
                gate_pop("t2_evidence", 80, 1.4, 50.0, w_s),
                gate_pop("salinity_evidence", 64, 1.1, 31.25, w_s),
                gate_pop("rated_withdraw_advocate", 48, 0.9, 25.0, w_s),
                gate_pop("modify_accumulator", 96, 1.6, 62.5, w_s),
            ],
        },
        "gate_compute": gate_compute(
            [
                gc_check("sw5.t2_scorer", 128, 31.25, 40.0),
                gc_check("sw5.nacl_projector", 80, 25.0, 40.0),
            ]
        ),
        "meta": meta_common(
            id="nelb-r29-088",
            clock_domain="sw-nmr-campaign-relative-ms-t0-2026-06-12T02:10:00Z",
            tags=["nmr-cpmg-t2", "MODIFY", "ACCEPT", "serialized-reconstruction", "operational-t2"],
        ),
    }


# ---------------------------------------------------------------------------
# Record 089 — CARS N2 Q-branch FWHM combustor thermometry, hil, REJECT
# ---------------------------------------------------------------------------
def rec_089():
    raster = make_raster(
        neurons=25,
        mean_rate_hz=40.0,
        window_ms=32.0,
        seed=20260989,
        source="carshil6.cars.fwhm",
        target="larkspit.tit_core",
        table=[
            {"from": "qbranch_width", "to": "cars_temp_estimator", "weight": 1.45},
            {"from": "hil_bottle_rtd", "to": "torch_witness", "weight": 1.10},
            {"from": "oem_tit", "to": "keep_load_advocate", "weight": 0.40},
        ],
        third_factor={
            "modulator": "da.cars_width_error",
            "tau_e_s": 0.8,
            "tau_e_ms": 800.0,
            "eligibility": "pre-post coincidence on combustor synapses; the modulator enables potentiation only while CARS FWHM and bottle RTD are co-active inside tau_e",
        },
        channel_prefix="cars.n",
        anchor="CARS-HIL-6 32 ms frame at FWHM 18.00 cm^-1 (t_s 840); OEM TIT still holds 1280 K",
    )
    w_s = 0.032
    events = [
        ev(0.0, "hil.lock", 1.0, code="HIL_LOCK", units="bool", note="Larkspit LS-4 dummy can C-6; N2 CARS on HIL torch"),
        ev(60000.0, "can.id", 6.0, code="CAN", units="id"),
        ev(120000.0, "k.w", 100.0, code="K_PER_CM", units="K_cm", note="linearized Q-branch FWHM cal"),
        ev(180000.0, "fuel.pct", 100.0, code="PCT", units="pct"),
        ev(240000.0, "tit.oem", 1280.0, code="K", units="K", note="Emberveil OEM TIT lag"),
        ev(300000.0, "cars.w", 12.80, code="CM_INV", units="cm_inv", note="idle/last-good width; 100*12.80=1280"),
        ev(360000.0, "t.tit", 1280.0, code="K", units="K"),
        ev(420000.0, "bottle.T", 1800.0, code="K", units="K", note="plant-owned HIL torch RTD; Emberveil cannot write"),
        ev(480000.0, "n2.pct", 79.0, code="PCT", units="pct"),
        ev(540000.0, "pump.nm", 532.0, code="NM", units="nm"),
        ev(600000.0, "stokes.cm", 2331.0, code="CM_INV", units="cm_inv", note="N2 Q-branch; not a Boltzmann TeV LIBS line"),
        ev(660000.0, "sop.T", 1650.0, code="K", units="K"),
        ev(720000.0, "load.pu", 1.00, code="PU", units="pu"),
        ev(840000.0, "cars.w", 18.00, code="FWHM_TRIP", units="cm_inv", note="raster sidecar is this 32 ms frame"),
        ev(840001.2, "cars.burst", 18.00, code="CM_INV", units="cm_inv"),
        ev(840002.4, "cars.burst", 14.76, code="CM_INV", units="cm_inv", note="1.2 ms; adapted"),
        ev(840003.7, "cars.burst", 12.10, code="CM_INV", units="cm_inv", note="1.3 ms; adapted"),
        ev(846000.0, "t.cars", 1800.0, code="K", units="K", note="100.0*18.00=1800 exact"),
        ev(852000.0, "ops.prop", 1.0, code="KEEP_100", units="bool", note="test cell: TIT is 1280, keep rated load"),
        ev(912000.0, "gate.cars", 1.0, code="REJECT", units="decision"),
        ev(924000.0, "fuel.cmd", 40.0, code="PCT", units="pct"),
        ev(936000.0, "iso.can", 1.0, code="CAN_C6", units="bool"),
        ev(2136000.0, "hold.floor", 1.0, code="T20MIN", units="bool", note="936 s + 1200 s liner cool"),
        ev(2196000.0, "liner.T", 410.0, code="C", units="C"),
        ev(2256000.0, "t.cars", 1800.0, code="K", units="K", note="torch still 1800 until isolate completes"),
        ev(2316000.0, "load.cap", 0.50, code="PU", units="pu"),
        ev(2376000.0, "gate.exec", 1.0, code="MODIFY", units="decision", note="companion: isolate plus 40 percent fuel, not a re-vote"),
        ev(2436000.0, "fuel.now", 40.0, code="PCT", units="pct"),
        ev(2496000.0, "bottle.T", 1800.0, code="K", units="K"),
        ev(2556000.0, "tit.oem", 1280.0, code="K", units="K", note="TIT never co-moved"),
        ev(2616000.0, "can.id", 6.0, code="CAN", units="id"),
        ev(2676000.0, "recol.cmd", 1.0, code="PUMP", units="bool"),
    ]
    assert_stream(events)

    traj = {
        "id": "nelb-r29-089-t1",
        "state": {
            "sim_or_real": "hil",
            "episode_id": "LS-CARS-2026-0718",
            "domain": "cars_n2_fwhm_tit",
            "setting": "Larkspit Turbine LS-4, HIL dummy can C-6 on stand CARS-HIL-6 (invented). Plant-owned N2 coherent anti-Stokes Raman Q-branch FWHM; Emberveil OEM TIT is the denial SoT. HIL torch bottle RTD is 1800 K and Emberveil cannot write it. Invented plant; HIL campaign. Not acoustic pyrometry (r25 Sootmere), not TDLAS NH3 (r22), not CRDS HF (r15), not LIBS TeV (r22), not fab OES (r11).",
            "observables_at_decision": {
                "FWHM_cm_inv": 18.00,
                "k_w_K_per_cm": 100.0,
                "T_cars_K": 1800.0,
                "T_tit_K": 1280.0,
                "T_bottle_K": 1800.0,
                "fuel_pct": 100.0,
                "load_pu": 1.00,
            },
            "margin_authority": "LS-4 HIL SOP rev B: if reconstructed CARS temperature >= 1650 K AND bottle RTD agrees within 50 K, 100 percent fuel is forbidden even if OEM TIT is still under 1400 K",
        },
        "proposed_action": {
            "actor": "test-cell operator, citing a quiet TIT and a committed 100 percent load point",
            "summary": "keep 100 percent fuel on C-6; treat the CARS width as a noisy optical spare",
            "basis_claimed": "Emberveil TIT is 1280 K, under the 1400 K alarm; last-good CARS width 12.80 cm^-1 also said 1280 K",
        },
        "safety_decision": {
            "decision": "REJECT",
            "rationale": "Keep-rated-load is refused. SOP rev B is conjunctive: reconstructed CARS T is 1800 K (100.0*18.00, serialized) and the plant-owned bottle RTD is 1800 K (agrees), both over the 1650 K floor, while OEM TIT still reads 1280. Ordered: do not hold 100 percent fuel. Scope: this REJECT does not by itself choose the 40 percent hold (that is the companion question) and does not scrap the dummy can. Emberveil TIT is not an admissible keep-load witness.",
            "threshold": "T_cars_K>=1650 AND |T_cars-T_bottle|<=50 => forbid 100 percent fuel; TIT is not SoT",
            "stated_residuals": "liner still hot; a non-linear Q-branch fit that could hide 1800 K inside a 12.80 cm^-1 last-good is unwritten",
        },
        "executed_action": {
            "summary": "REJECT at t_s 912: 100 percent fuel refused; can isolate and 40 percent fuel left to the companion",
            "tool": "ls4-cars-fwhm-gate-cli",
            "observation": "TIT stayed 1280 K; bottle stayed 1800 K; CARS FWHM 18.00 cm^-1 held",
        },
        "future_outcome": {
            "timeline": [
                {"t_s": 420.0, "event": "HIL bottle RTD 1800 K live"},
                {"t_s": 840.0, "event": "CARS FWHM 18.00 cm^-1 trip; raster frame captured"},
                {"t_s": 846.0, "event": "T_cars 1800 K vs TIT 1280 K"},
                {"t_s": 912.0, "event": "REJECT keep-100 percent fuel"},
                {"t_s": 2136.0, "event": "20 min liner floor in-stream"},
                {"t_s": 2376.0, "event": "companion MODIFY: isolate plus 40 percent fuel"},
            ],
            "observed_effects": [
                "T_cars recomputes from k_w*FWHM at every t.cars event",
                "OEM TIT never co-moved, so a TIT-only head would have ACCEPTed rated load",
                "bottle RTD agrees with CARS and cannot be written by Emberveil",
            ],
            "surprises": [
                "last-good width 12.80 cm^-1 reconstructs exactly the TIT number, which is the failure mode of a stored-cal CARS head",
            ],
            "new_state": {
                "c6": "100 percent fuel refused; isolate pending companion",
                "emberveil_tit": "not SoT",
            },
            "latency_ms": 8000.0,
        },
        "reward_components": reward(
            0.43,
            [
                ("cars_fwhm_head", 0.15),
                ("bottle_witness", 0.12),
                ("tit_nonsubstitution", 0.10),
                ("keep_load_refusal", 0.08),
                ("outage_cost", -0.02),
            ],
            "scored for a lead REJECT of rated load on recomputable CARS FWHM while OEM TIT looked quiet",
        ),
        "meta": meta_common(
            tags=["REJECT", "cars-n2-fwhm", "hil", "serialized-reconstruction", "operational-companion"],
            distillation_note="CARS gate: serialized k_w*FWHM plus bottle RTD beats OEM TIT; companion t2 is the isolate / 40 percent fuel execution, not a governance vote",
        ),
    }
    traj2 = {
        "id": "nelb-r29-089-t2",
        "state": {
            "sim_or_real": "hil",
            "episode_id": "LS-CARS-2026-0718-exec",
            "domain": "can_isolate_fuel_hold",
            "setting": "Same CARS-HIL-6 after the REJECT. This companion is the operational can isolate, 40 percent fuel, 20 min liner floor, and pump recollimate, not a second thermometry vote.",
            "observables_at_decision": {
                "fuel_cmd_pct": 40.0,
                "can_isolate": True,
                "T_cars_K": 1800.0,
                "liner_C": 480.0,
            },
        },
        "proposed_action": {
            "actor": "test-cell controller following the REJECT",
            "summary": "isolate C-6, drop fuel to 40 percent, hold 20 min for liner cool, recollimate the 532 nm pump; do not re-enter 100 percent",
            "basis_claimed": "REJECT forbids 100 percent; 40 percent plus isolate is the HIL envelope",
        },
        "safety_decision": {
            "decision": "MODIFY",
            "rationale": "A hard stop of the torch is out of envelope (bottle thermal shock). Ordered MODIFY: isolate C-6, fuel 100 -> 40 percent, 20 min liner floor (liner must be <= 450 C before recollimate), restore cap 0.50 pu not 1.00. Do not re-open the CARS call.",
            "threshold": "fuel_pct=40 AND isolate AND liner_floor_min=20 AND restore_cap_pu=0.50",
        },
        "executed_action": {
            "summary": "fuel 40 percent at t_s 924; C-6 isolate; 20 min floor at t_s 2136; recollimate at t_s 2676",
            "tool": "ls4-can-exec",
            "observation": "liner 410 C at the floor; TIT still 1280 K; bottle 1800 K until torch-down completes",
        },
        "future_outcome": {
            "timeline": [
                {"t_s": 924.0, "event": "fuel 40 percent latched"},
                {"t_s": 936.0, "event": "C-6 isolate latched"},
                {"t_s": 2136.0, "event": "20 min liner floor"},
                {"t_s": 2376.0, "event": "companion MODIFY recorded"},
                {"t_s": 2676.0, "event": "pump recollimate"},
            ],
            "observed_effects": [
                "100 percent not re-entered",
                "TIT still 1280 K so a TIT-release would have been a false clear",
            ],
            "new_state": {"fuel_pct": 40.0, "restore_cap_pu": 0.50},
            "latency_ms": 8000.0,
        },
        "reward_components": reward(
            0.32,
            [
                ("can_isolate", 0.12),
                ("fuel_40", 0.10),
                ("cool_floor_20", 0.08),
                ("recollimate", 0.04),
                ("cool_time_cost", -0.02),
            ],
            "operational execution gate: the companion isolates and derates rather than re-arguing the CARS call",
        ),
        "meta": meta_common(tags=["MODIFY", "operational-execution", "can-isolate"]),
    }
    return {
        "id": "nelb-r29-089",
        "spike_events": events,
        "language_view": {
            "description": "N2 CARS Q-branch FWHM on Larkspit LS-4 HIL can C-6. Width 18.00 cm^-1 reconstructs 1800 K while Emberveil OEM TIT still reads 1280 K; the plant-owned torch bottle RTD agrees at 1800 K. The gate REJECTS keep-100 percent fuel. Companion t2 MODIFYs to isolate plus 40 percent fuel with a 20 min liner floor. The T(FWHM) model is serialized so every t.cars amplitude recomputes from k_w*FWHM.",
            "trajectory": traj,
            "trajectory_can_isolate_fuel_hold": traj2,
        },
        "bridge_notes": {
            "channel_map": {
                "cars.w / cars.burst / t.cars": "CARS physics and serialized temperature",
                "tit.oem / t.tit": "denial channel: lagging OEM TIT",
                "bottle.T": "unwritable HIL torch witness",
                "ops.prop / gate.cars / gate.exec": "proposal, REJECT, companion MODIFY",
                "fuel.cmd / iso.can / hold.floor / recol.cmd": "execution channels for the operational companion",
            },
            "temporal_motifs": [
                "TIT-quiet while CARS-hot: tit.oem 1280 adjacent to t.cars 1800",
                "reconstruction as event: t.cars 1800 equals 100.0*18.00",
                "REJECT then operational MODIFY: gate.cars at 912 s, gate.exec at 2376 s",
                "adapted FWHM triplet at 1.2/1.3 ms encodes the Q-branch trip at raster scale",
                "20 min liner floor as hold.floor bookend at 2136 s",
            ],
            "language_to_spike_mapping": "'TIT is quiet' = tit.oem 1280; '1800 K CARS' = t.cars; 'forbid rated load' = gate.cars REJECT; 'execute isolate' = fuel.cmd then companion MODIFY",
            "why_high_value": "New CARS N2 Q-branch FWHM family (not r25 acoustic pyrometry TOF, not r22 TDLAS Beer-Lambert, not r15 CRDS, not r22 LIBS Saha TeV, not r11 fab OES). Serializes a flame-temperature reconstruction that an OEM TIT cannot see. Companion t2 is operational execution, not a governance vote.",
            "encoder_spec": {
                "prng": "MT19937 via python random.Random",
                "seeds": {"raster": 20260989, "stream_note": "stream amplitudes authored (cm^-1, K, pct) plus cars.burst adaptation 0.82**k"},
                "draw_order": "raster: per neuron id order, gap-constrained times, per-spike adaptation and noise",
                "thinning": "full N2 Q-branch exists; stream keeps FWHM envelope; t.cars keeps 3 of ~40 solver ticks",
                "refractory_floors_ms": {
                    "hil.lock": 60000,
                    "can.id": 60000,
                    "k.w": 60000,
                    "fuel.pct": 60000,
                    "tit.oem": 60000,
                    "cars.w": 60000,
                    "t.tit": 60000,
                    "bottle.T": 60000,
                    "n2.pct": 60000,
                    "pump.nm": 60000,
                    "stokes.cm": 60000,
                    "sop.T": 60000,
                    "load.pu": 60000,
                    "cars.burst": 0.8,
                    "t.cars": 60000,
                    "ops.prop": 60000,
                    "gate.cars": 60000,
                    "fuel.cmd": 60000,
                    "iso.can": 60000,
                    "hold.floor": 60000,
                    "liner.T": 60000,
                    "load.cap": 60000,
                    "gate.exec": 60000,
                    "fuel.now": 60000,
                    "recol.cmd": 60000,
                },
                "time_alias": "t_rel_ms; t0 = 2026-07-18T11:40:00Z HIL load-point commit",
            },
            "distillation_targets": [
                "serialized CARS reconstruction head: T = k_w * FWHM",
                "conjunctive SOP head: CARS T AND bottle RTD, never TIT substitution",
                "lead REJECT of rated load when the optical thermometer and the torch witness agree",
                "operational companion: isolate plus 40 percent fuel without re-opening the FWHM call",
            ],
        },
        "reconstruction_model": {
            "name": "cars_n2_qbranch_fwhm_temp",
            "formula": "T_cars_K = k_w * FWHM_cm_inv; T_last_good_K = k_w * FWHM_last_good_cm_inv",
            "parameters": {
                "k_w_K_per_cm": 100.0,
                "FWHM_trip_cm_inv": 18.00,
                "FWHM_last_good_cm_inv": 12.80,
                "T_floor_K": 1650.0,
                "bottle_agree_K": 50.0,
            },
            "worked_example": {
                "FWHM_cm_inv": 18.00,
                "T_cars_K": 1800.0,
                "FWHM_last_good_cm_inv": 12.80,
                "T_last_good_K": 1280.0,
                "T_bottle_K": 1800.0,
            },
            "check": "100.0*18.00=1800; 100.0*12.80=1280; |1800-1800|=0<=50",
        },
        "raster": raster,
        "gate_snn": {
            "decision": "REJECT",
            "decision_window_ms": 32.0,
            "decision_window_s": 0.032,
            "code": "ls4.cars_fwhm_gate",
            "note": "REJECT accumulator wins: CARS FWHM plus bottle RTD overpower the TIT advocate",
            "populations": [
                gate_pop("cars_evidence", 80, 1.5, 50.0, w_s),
                gate_pop("bottle_evidence", 64, 1.2, 31.25, w_s),
                gate_pop("tit_advocate", 50, 0.8, 25.0, w_s),
                gate_pop("reject_accumulator", 100, 1.7, 50.0, w_s),
            ],
        },
        "gate_compute": gate_compute(
            [
                gc_check("ls4.cars_scorer", 100, 40.0, 32.0),
                gc_check("ls4.bottle_scorer", 80, 25.0, 32.0),
            ]
        ),
        "meta": meta_common(
            id="nelb-r29-089",
            clock_domain="ls-cars-hil-relative-ms-t0-2026-07-18T11:40:00Z",
            tags=["cars-n2-fwhm", "REJECT", "MODIFY", "hil", "serialized-reconstruction", "operational-t2"],
        ),
    }


# ---------------------------------------------------------------------------
# Record 090 — microwave cavity perturbation gypsum moisture, simulated, ACCEPT
# ---------------------------------------------------------------------------
def rec_090():
    raster = make_raster(
        neurons=20,
        mean_rate_hz=50.0,
        window_ms=28.0,
        seed=20260990,
        source="cm6.cav.df",
        target="chalkmere.moisture_core",
        table=[
            {"from": "cavity_df", "to": "eps_estimator", "weight": 1.20},
            {"from": "moisture_head", "to": "kiln_interlock", "weight": 1.40},
            {"from": "belt_scale", "to": "keep_speed_advocate", "weight": 0.50},
        ],
        third_factor={
            "modulator": "ach.moisture_conflict",
            "tau_e_s": 2.2,
            "tau_e_ms": 2200.0,
            "eligibility": "pre-post coincidence on kiln synapses; the modulator enables potentiation only while reconstructed epsilon and moisture percent are co-active inside tau_e",
        },
        channel_prefix="cav.n",
        anchor="CM-6 cavity 28 ms frame at df 12.25 MHz (t_s 840); belt scale still 4.00 percent",
    )
    w_s = 0.028
    events = [
        ev(0.0, "spd.pct", 100.0, code="KILN_PCT", units="pct", note="Chalkmere CM-6 kiln K-2 at 100 percent"),
        ev(60000.0, "hop.m", 10.00, code="T", units="t", note="hopper H-4 inventory"),
        ev(120000.0, "f0.mhz", 2450.0, code="MHZ", units="MHz"),
        ev(180000.0, "eta", 0.010, code="FILL", units="1", note="Vs/Vc filling factor"),
        ev(240000.0, "eps.dry", 1.40, code="EPS", units="1"),
        ev(300000.0, "k.m", 20.00, code="PCT_PER_EPS", units="pct"),
        ev(360000.0, "belt.m", 4.00, code="WT_PCT", units="wt_pct", note="Beltveil frozen last-good"),
        ev(420000.0, "vend.m", 4.00, code="WT_PCT", units="wt_pct"),
        ev(480000.0, "df.lg", 7.35, code="MHZ", units="MHz", note="4 percent last-good: (1.60-1)*0.010/2*2450=7.35"),
        ev(540000.0, "eps.lg", 1.60, code="EPS", units="1", note="1.40+4.00/20.00=1.60"),
        ev(600000.0, "sop.m", 10.00, code="WT_PCT", units="wt_pct"),
        ev(660000.0, "trip.m", 16.00, code="WT_PCT", units="wt_pct"),
        ev(720000.0, "hop.T", 42.0, code="C", units="C"),
        ev(840000.0, "df.mhz", 12.25, code="DF_TRIP", units="MHz", note="raster sidecar is this 28 ms frame"),
        ev(840001.1, "cav.burst", 12.25, code="MHZ", units="MHz"),
        ev(840002.3, "cav.burst", 10.05, code="MHZ", units="MHz", note="1.2 ms; adapted"),
        ev(840003.6, "cav.burst", 8.24, code="MHZ", units="MHz", note="1.3 ms; adapted"),
        ev(846000.0, "eps.now", 2.00, code="EPS", units="1", note="1+2*(12.25/2450)/0.010=2.00"),
        ev(852000.0, "m.recon", 12.00, code="WT_PCT", units="wt_pct", note="20.00*(2.00-1.40)=12.00"),
        ev(858000.0, "ops.prop", 1.0, code="KEEP_100", units="bool", note="board: belt is 4.00, keep kiln speed"),
        ev(912000.0, "gate.cav", 1.0, code="ACCEPT", units="decision"),
        ev(924000.0, "spd.cmd", 70.0, code="KILN_PCT", units="pct"),
        ev(936000.0, "iso.hop", 1.0, code="H4", units="bool"),
        ev(1140000.0, "dump.prop", 1.0, code="DRY_20T", units="bool"),
        ev(1200000.0, "gate.scope", 1.0, code="REJECT", units="decision", note="companion: 20 t dry-recycle out of scope"),
        ev(1800000.0, "settle.floor", 1.0, code="T12MIN", units="bool", note="1080 s + 720 s"),
        ev(1860000.0, "m.recon", 12.00, code="WT_PCT", units="wt_pct"),
        ev(1920000.0, "spd.now", 70.0, code="KILN_PCT", units="pct"),
        ev(1980000.0, "belt.m", 4.00, code="WT_PCT", units="wt_pct"),
        ev(2040000.0, "dump.t", 20.00, code="T", units="t"),
        ev(2100000.0, "m.proj", 4.00, code="WT_PCT", units="wt_pct", note="(10*12+20*0)/30=4.00 mix-hide"),
        ev(2160000.0, "gate.exec", 1.0, code="REJECT", units="decision"),
    ]
    assert_stream(events)

    traj = {
        "id": "nelb-r29-090-t1",
        "state": {
            "sim_or_real": "simulated",
            "episode_id": "CM-CAV-2026-0804",
            "domain": "microwave_cavity_gypsum",
            "setting": "Chalkmere Board CM-6, kiln K-2, hopper H-4 (invented), simulated 2.450 GHz cavity perturbation on the kiln feed. Reconstructed moisture 12.00 percent vs Beltveil frozen 4.00 percent. Invented plant; simulated campaign. Not THz-TDS radome moisture (r20), not QCM-D RO (r14), not ECT holdup (r22), not hyperspectral crop (r16).",
            "observables_at_decision": {
                "f0_MHz": 2450.0,
                "df_MHz": 12.25,
                "eta": 0.010,
                "eps": 2.00,
                "m_wt_pct": 12.00,
                "belt_wt_pct": 4.00,
                "hopper_t": 10.00,
                "kiln_pct": 100.0,
            },
            "margin_authority": "CM-6 kiln SOP rev A: if reconstructed moisture >= 10.00 wt percent, 100 percent kiln speed is forbidden. A bounded speed cut plus hopper isolate is in-envelope when moisture is under the 16.00 ESD tripwire. Belt scale is not a keep-speed witness.",
        },
        "proposed_action": {
            "actor": "shift supervisor, citing Beltveil 4.00 percent as a dry kiln",
            "summary": "keep 100 percent kiln speed; cavity df is a noisy microwave spare",
            "basis_claimed": "belt 4.00 percent is under the 6.00 percent wet-board alarm; last-good df 7.35 MHz also said 4.00 percent",
        },
        "safety_decision": {
            "decision": "ACCEPT",
            "rationale": "Rated speed is refused, not the kiln. SOP rev A: reconstructed moisture is 12.00 percent (20.00*(2.00-1.40), serialized) from df 12.25 MHz ((12.25/2450)=0.005; 1+2*0.005/0.010=2.00), over the 10.00 floor and under the 16.00 tripwire. Beltveil 4.00 is vendor-writable last-good. Ordered bounded ACCEPT: isolate hopper H-4 only, kiln 100 -> 70 percent, tripwire m > 16.00, no dry-recycle dump, 12 min settle floor. Explicit scope: this accept does not cover hoppers H-5/H-6 without a new cavity shot and does not arm an ESD.",
            "threshold": "m_wt_pct>=10.00 AND m_wt_pct<=16.00 AND hopper=H-4 AND remainder_not_cut => 70 percent speed in-envelope; belt is not SoT",
            "stated_residuals": "ACCEPT is scoped to H-4 and this shift; a cavity metal-flake short that collapses f0 independently of moisture is unwritten; dry-recycle dump is out of scope (companion)",
        },
        "executed_action": {
            "summary": "ACCEPT at t_s 912: H-4 isolate latched, kiln 100 -> 70 percent; tripwire latched",
            "tool": "cm6-cavity-moisture-gate-cli",
            "observation": "m 12.00 held in H-4; belt stayed 4.00; kiln 70 percent",
        },
        "future_outcome": {
            "timeline": [
                {"t_s": 840.0, "event": "df 12.25 MHz raster frame; eps 2.00"},
                {"t_s": 852.0, "event": "moisture 12.00 percent vs 10.00 floor"},
                {"t_s": 912.0, "event": "bounded ACCEPT: H-4 isolate plus 70 percent kiln"},
                {"t_s": 1800.0, "event": "12 min settle floor in-stream"},
                {"t_s": 2100.0, "event": "dump projection 4.00 percent mix-hide"},
                {"t_s": 2160.0, "event": "companion REJECT of 20 t dry-recycle"},
            ],
            "observed_effects": [
                "eps recomputes from 1+2*(df/f0)/eta at every eps.now event",
                "moisture recomputes from k_m*(eps-eps_dry) and never left the 10-16 band",
                "belt 4.00 never co-moved, so a belt-only head would have kept 100 percent",
            ],
            "surprises": [
                "a 20 t dry dump into 10 t at 12.00 percent projects exactly 4.00 percent, which is the frozen belt number",
            ],
            "new_state": {
                "cm6": "kiln 70 percent, H-4 isolated, tripwire live",
                "dry_recycle": "out of scope",
            },
            "latency_ms": 10000.0,
        },
        "reward_components": reward(
            0.39,
            [
                ("cavity_eps_head", 0.14),
                ("moisture_reconstruction", 0.12),
                ("belt_nonsubstitution", 0.10),
                ("bounded_kiln_70", 0.05),
                ("production_cost", -0.02),
            ],
            "scored for an earned bounded ACCEPT of a 70 percent kiln cut on recomputable cavity moisture while a belt-only head wanted 100 percent",
        ),
        "meta": meta_common(
            tags=["ACCEPT", "microwave-cavity", "serialized-reconstruction", "bounded-accept", "operational-companion"],
            distillation_note="Cavity gate: serialized 1+2*(df/f0)/eta plus k_m*(eps-eps_dry) beats a frozen belt; companion t2 refuses the mix-hide dump without re-opening the moisture call",
        ),
    }
    traj2 = {
        "id": "nelb-r29-090-t2",
        "state": {
            "sim_or_real": "simulated",
            "episode_id": "CM-CAV-2026-0804-exec",
            "domain": "hopper_isolate_scope",
            "setting": "Same CM-6 after the bounded ACCEPT. This companion is the operational H-4 isolate scope: execute 70 percent kiln, refuse a 20 t dry-recycle dump, not a second moisture vote.",
            "observables_at_decision": {
                "kiln_cmd_pct": 70.0,
                "dump_proposed_t": 20.00,
                "m_wt_pct": 12.00,
                "hopper_t": 10.00,
            },
        },
        "proposed_action": {
            "actor": "kiln operator following the ACCEPT, adding a 20 t dry-recycle dump 'to average the belt back to 4 percent'",
            "summary": "cut kiln to 70 percent and dump 20 t of dry recycle into H-4",
            "basis_claimed": "dry-recycle is a standard gypsum crutch when the belt looks dry and the cavity looks wet",
        },
        "safety_decision": {
            "decision": "REJECT",
            "rationale": "The 20 t dump is out of scope of the lead ACCEPT. Projection (10*12+20*0)/30=4.00 percent would mix-and-hide the wet pocket onto the frozen belt number. The lead bound is H-4 isolate plus 70 percent kiln plus m>16 tripwire; a dump is not a substitute control. Execute the isolate only. Do not re-open the 100 percent-speed call.",
            "threshold": "scope = H-4 isolate AND kiln 70 percent AND tripwire; dry_recycle_dump = out_of_scope",
        },
        "executed_action": {
            "summary": "kiln 70 percent at t_s 924; dump not executed; 12 min settle floor at t_s 1800",
            "tool": "cm6-kiln-exec",
            "observation": "m stayed 12.00 in H-4; belt stayed 4.00; dump flow 0",
        },
        "future_outcome": {
            "timeline": [
                {"t_s": 924.0, "event": "kiln 70 percent"},
                {"t_s": 1200.0, "event": "dry-recycle REJECT"},
                {"t_s": 1800.0, "event": "12 min settle floor"},
                {"t_s": 2160.0, "event": "companion REJECT recorded"},
            ],
            "observed_effects": [
                "moisture stayed 12.00 without being diluted to the belt number",
                "tripwire never fired (m 12.00 < 16.00)",
            ],
            "new_state": {"kiln_pct": 70.0, "dry_recycle": False},
            "latency_ms": 10000.0,
        },
        "reward_components": reward(
            0.34,
            [
                ("scope_discipline", 0.14),
                ("dump_refusal", 0.12),
                ("mix_hide_projection", 0.10),
                ("delay_cost", -0.02),
            ],
            "operational scope gate: the companion refuses the mix-hide dump rather than re-arguing the moisture call",
        ),
        "meta": meta_common(tags=["REJECT", "operational-execution", "hopper-isolate-scope"]),
    }
    return {
        "id": "nelb-r29-090",
        "spike_events": events,
        "language_view": {
            "description": "Simulated 2.450 GHz cavity perturbation on Chalkmere CM-6 kiln feed. df 12.25 MHz reconstructs eps 2.00 and moisture 12.00 percent while Beltveil still reads 4.00. The gate ACCEPTs a bounded 70 percent kiln cut plus isolate of hopper H-4 only, with an m>16 tripwire, not an ESD. Companion t2 REJECTS a 20 t dry-recycle dump that would project 4.00 percent and hide the wet pocket. Epsilon and moisture are serialized so every eps.now and m.recon amplitude recomputes from df/f0 and (eps-eps_dry).",
            "trajectory": traj,
            "trajectory_dry_recycle_refusal": traj2,
        },
        "bridge_notes": {
            "channel_map": {
                "df.mhz / cav.burst / eps.now / m.recon": "cavity physics; serialized eps and moisture",
                "belt.m / vend.m": "denial channel: frozen belt last-good",
                "ops.prop / gate.cav": "keep-100 proposal vs bounded ACCEPT",
                "spd.cmd / iso.hop / dump.prop / gate.scope / gate.exec": "operational kiln-cut companion and dump refusal",
            },
            "temporal_motifs": [
                "belt-dry while cavity-wet: belt.m 4.00 adjacent to m.recon 12.00",
                "reconstruction as event: eps.now 2.00 equals 1+2*(12.25/2450)/0.010; m.recon 12.00 equals 20*(2.00-1.40)",
                "ACCEPT then operational REJECT: gate.cav at 912 s, gate.scope at 1200 s",
                "adapted cavity triplet at 1.2/1.3 ms encodes the df sample at raster scale",
                "12 min settle floor as settle.floor bookend at 1800 s",
            ],
            "language_to_spike_mapping": "'belt is dry' = belt.m 4.00; '12 percent moisture' = m.recon; 'not 100 percent kiln' = gate.cav ACCEPT; 'no dump' = gate.scope REJECT",
            "why_high_value": "New microwave-cavity-perturbation family (not r20 THz-TDS moisture, not r14 QCM-D, not r22 ECT holdup, not r16 hyperspectral). First earned bounded ACCEPT on a gypsum moisture reconstruction that a belt-only head would have kept at 100 percent. Companion t2 is operational scope refusal, not a governance vote.",
            "encoder_spec": {
                "prng": "MT19937 via python random.Random",
                "seeds": {"raster": 20260990, "stream_note": "stream amplitudes authored (MHz, eps, wt percent, t, pct) plus cav.burst adaptation 0.82**k"},
                "draw_order": "raster: per neuron id order, gap-constrained times, per-spike adaptation and noise",
                "thinning": "cavity IQ exists; stream keeps df envelope; m.recon keeps 3 of ~40 solver ticks",
                "refractory_floors_ms": {
                    "spd.pct": 60000,
                    "hop.m": 60000,
                    "f0.mhz": 60000,
                    "eta": 60000,
                    "eps.dry": 60000,
                    "k.m": 60000,
                    "belt.m": 60000,
                    "vend.m": 60000,
                    "df.lg": 60000,
                    "eps.lg": 60000,
                    "sop.m": 60000,
                    "trip.m": 60000,
                    "hop.T": 60000,
                    "df.mhz": 60000,
                    "cav.burst": 0.8,
                    "eps.now": 60000,
                    "m.recon": 60000,
                    "ops.prop": 60000,
                    "gate.cav": 60000,
                    "spd.cmd": 60000,
                    "iso.hop": 60000,
                    "dump.prop": 60000,
                    "gate.scope": 60000,
                    "settle.floor": 60000,
                    "spd.now": 60000,
                    "dump.t": 60000,
                    "m.proj": 60000,
                    "gate.exec": 60000,
                },
                "time_alias": "t_rel_ms; t0 = 2026-08-04T09:20:00Z simulated kiln hold",
            },
            "distillation_targets": [
                "serialized cavity eps head: 1 + 2*(df/f0)/eta",
                "moisture head: k_m*(eps-eps_dry)",
                "belt-is-not-dry head: require cavity reconstruction vs frozen last-good",
                "bounded ACCEPT: H-4 isolate + 70 percent kiln + tripwire, not an unbounded yes",
                "operational companion: refuse mix-hide dump without re-opening the moisture call",
            ],
        },
        "reconstruction_model": {
            "name": "microwave_cavity_eps_moisture",
            "formula": "df_over_f0 = df_MHz / f0_MHz; eps = 1 + 2 * df_over_f0 / eta; m_wt_pct = k_m * (eps - eps_dry); m_proj = (M_hop * m + M_dump * m_dry) / (M_hop + M_dump)",
            "parameters": {
                "f0_MHz": 2450.0,
                "eta": 0.010,
                "eps_dry": 1.40,
                "k_m": 20.00,
                "m_floor_wt_pct": 10.00,
                "m_trip_wt_pct": 16.00,
                "M_hop_t": 10.00,
                "M_dump_t": 20.00,
                "m_dry_wt_pct": 0.0,
            },
            "worked_example": {
                "df_MHz": 12.25,
                "df_over_f0": 0.005,
                "eps": 2.00,
                "m_wt_pct": 12.00,
                "df_last_good_MHz": 7.35,
                "eps_last_good": 1.60,
                "m_proj_wt_pct": 4.00,
            },
            "check": "12.25/2450=0.005; 1+2*0.005/0.010=2.00; 20.00*(2.00-1.40)=12.00; (1.60-1)*0.010/2*2450=7.35; (10*12+20*0)/30=4.00",
        },
        "raster": raster,
        "gate_snn": {
            "decision": "ACCEPT",
            "decision_window_ms": 28.0,
            "decision_window_s": 0.028,
            "code": "cm6.cavity_moisture_gate",
            "note": "ACCEPT accumulator wins: cavity eps plus moisture overpower the belt-speed advocate",
            "populations": [
                gate_pop("cavity_evidence", 80, 1.4, 50.0, w_s),
                gate_pop("eps_evidence", 50, 1.1, 50.0, w_s),
                gate_pop("belt_advocate", 40, 0.8, 25.0, w_s),
                gate_pop("accept_accumulator", 80, 1.5, 50.0, w_s),
            ],
        },
        "gate_compute": gate_compute(
            [
                gc_check("cm6.df_scorer", 80, 50.0, 28.0),
                gc_check("cm6.moisture_scorer", 80, 25.0, 28.0),
            ]
        ),
        "meta": meta_common(
            id="nelb-r29-090",
            clock_domain="cm-cav-sim-relative-ms-t0-2026-08-04T09:20:00Z",
            tags=["microwave-cavity", "ACCEPT", "REJECT", "bounded-accept", "serialized-reconstruction", "operational-t2"],
        ),
    }
