def build_record():
    ticks, heads = cents_ticks(
        [4560, 6520, 7214, 5_400_000, 408_000_000, 3_240_000_000, 9_360_000_000],
        [
            (1, -2, -1, 2, 1),
            (2, -5, -1, 2, 1),
            (2, -6, -2, 3, 2),
            (1, -6, -1, 2, 1),
            (1, -5, -2, 2, 1),
            (1, -6, -2, 2, 1),
            (0, -6, -1, 1, 1),
        ],
    )
    assert abs(heads["total"] - (-0.16)) < 1e-9, heads

    trace = math.exp(-DELAY_S / TAU_E_S)
    eta1 = 0.24 / trace
    eta2 = 0.21 / trace
    eta3 = 0.20 / trace
    dw1 = eta1 * 1.0 * trace
    dw2 = eta2 * 1.0 * trace
    dw3 = eta3 * 1.0 * trace
    w1 = 0.48 - dw1
    w2 = 0.43 - dw2
    w3 = 0.40 - dw3
    assert abs(w1 - 0.24) < 5e-4, w1
    assert abs(w2 - 0.22) < 5e-4, w2
    assert abs(w3 - 0.20) < 5e-4, w3

    spike_events = [
        {"channel": "mill.v", "t_rel_ms": 0.280, "amplitude": 0.52},
        {"channel": "xray.h", "t_rel_ms": 1.120, "amplitude": 0.61},
        {"channel": "pyro.t", "t_rel_ms": 2.010, "amplitude": 0.53},
        {"channel": "scale.h", "t_rel_ms": 3.140, "amplitude": 0.78},
        {"channel": "mill.v", "t_rel_ms": 4.140, "amplitude": 0.50},
        {"channel": "scale.h", "t_rel_ms": 4.820, "amplitude": 0.81},
        {"channel": "xray.h", "t_rel_ms": 5.340, "amplitude": 0.58},
        {"channel": "scale.h.high", "t_rel_ms": 6.520, "amplitude": 1.44},
        {"channel": "xray.in_band", "t_rel_ms": 6.696, "amplitude": 1.16},
        {"channel": "mill.v", "t_rel_ms": 6.940, "amplitude": 0.64},
        {"channel": "ctrl.gate", "t_rel_ms": 7.214, "amplitude": 1.11},
        {"channel": "scale.h", "t_rel_ms": 8.850, "amplitude": 0.46},
        {"channel": "mill.v", "t_rel_ms": 10.740, "amplitude": 0.82},
        {"channel": "xray.h", "t_rel_ms": 13.020, "amplitude": 0.45},
        {"channel": "pyro.t", "t_rel_ms": 18.510, "amplitude": 0.42},
        {"channel": "ctrl.gate", "t_rel_ms": 26.160, "amplitude": 0.84},
        {"channel": "spd.probe", "t_rel_ms": 5400.0, "amplitude": 0.94},
        {"channel": "scale.h", "t_rel_ms": 5488.2, "amplitude": 0.40},
        {"channel": "xray.in_band", "t_rel_ms": 5572.4, "amplitude": 0.34},
        {"channel": "human.ratify", "t_rel_ms": 408000.0, "amplitude": 0.78},
        {"channel": "stand.lock", "t_rel_ms": 408900.0, "amplitude": 0.70},
        {"channel": "roll.score", "t_rel_ms": 409700.0, "amplitude": 0.86},
        {"channel": "mill.v", "t_rel_ms": 3240000.0, "amplitude": 0.30},
        {"channel": "scale.h", "t_rel_ms": 3240720.0, "amplitude": 0.28},
        {"channel": "xray.h", "t_rel_ms": 3241480.0, "amplitude": 0.26},
        {"channel": "roll.spall", "t_rel_ms": 9360000.0, "amplitude": 0.92},
    ]

    contrast_spikes = [
        {"channel": "raise.demand", "t_rel_ms": 0.000, "amplitude": 0.84},
        {"channel": "scale.clear", "t_rel_ms": 0.176, "amplitude": 0.76},
        {"channel": "mill.v", "t_rel_ms": 0.400, "amplitude": 0.27},
        {"channel": "xray.h", "t_rel_ms": 1.450, "amplitude": 0.41},
        {"channel": "pyro.t", "t_rel_ms": 4.870, "amplitude": 0.50},
        {"channel": "ctrl.gate", "t_rel_ms": 7.010, "amplitude": 0.91},
        {"channel": "spd.probe", "t_rel_ms": 2800.0, "amplitude": 0.33},
        {"channel": "roll.spall", "t_rel_ms": 9360000.0, "amplitude": 0.10},
    ]

    excerpt = [
        {"t_us": 280, "neuron_id": 11},
        {"t_us": 1120, "neuron_id": 73},
        {"t_us": 2010, "neuron_id": 24},
        {"t_us": 3140, "neuron_id": 49},
        {"t_us": 4140, "neuron_id": 14},
        {"t_us": 4820, "neuron_id": 55},
        {"t_us": 5340, "neuron_id": 90},
        {"t_us": 6520, "neuron_id": 38},
        {"t_us": 6696, "neuron_id": 18},
        {"t_us": 6940, "neuron_id": 103},
        {"t_us": 7214, "neuron_id": 132},
        {"t_us": 8850, "neuron_id": 62},
        {"t_us": 10740, "neuron_id": 28},
        {"t_us": 13020, "neuron_id": 117},
        {"t_us": 18510, "neuron_id": 15},
        {"t_us": 26160, "neuron_id": 145},
    ]

    rec = {
        "id": RECORD_ID,
        "title": "LOOPERQUAY HSM-5: scale residual 0.22 mm beats xray.in_band by 176 us; correct MODIFY still loses F-5 work-roll to a pre-t0 descaler crack",
        "rights": dict(RIGHTS),
        "state": {
            "sim_or_real": "designed",
            "domain": DOMAIN,
            "scenario_name": "LOOPERQUAY / Roughmere Strip HSM-5",
            "timestamp_local": "2026-08-24T03:42:00-05:00",
            "t0_us": 1786396800000055,
            "gate_latency_us": 694,
            "race_window_us": 500,
            "race_window_rel_ms": [6.520, 7.020],
            "description": "Roughmere Strip finishing mill HSM-5 holds 12.4 m/s on a seven-stand hot-strip train when three heterogeneous, individually-correct agents jointly report 'gauge healthy, raise speed'. SPEED's 12-bit mill tachometer is 12.4 m/s inside 11.8-13.0. THICK's X-ray mean is 2.02 mm inside 1.95-2.10. TEMP's finishing pyrometer is 890 C inside 870-920. The conjunction is not a steel-true gauge certificate: a 13 min cracked descaler header on stand F-5 left scale on the strip, so laser-vs-X-ray residual r_h is 0.22 mm (hold if > 0.10) and missing descaler flow is 1.85 L/s (hold if > 1.2) while the playbook still sees legal X-ray gauge. Missing scale residual is policy-treated as a noisy-laser tag unless X-ray also trips (2014 'noisy shadow laser'). Scale-first latches SPEED-HOLD plus a speed-cut probe; X-ray-first would have authorized RAISE-SPEED into a scaled bar.",
            "goal": "Hold mill speed without a raise while r_h > 0.10 mm AND missing descaler > 1.2 L/s AND F-5 descaler remains unisolated; keep X-ray gauge inside the 2.20 mm cobble trip.",
            "race": {
                "contenders": [
                    "scale.h.high 0.22 mm (laser shadow vs X-ray mean)",
                    "xray.in_band 2.02 mm (X-ray thickness)",
                ],
                "semantics": "scale-first latches SPEED-HOLD + SPEED-CUT-PROBE + stand isolate. X-ray-first latches RAISE-SPEED (+8% mill speed, no probe).",
                "window_derivation": "500 us = one 360 us laser-shadow slot plus 140 us X-ray publish.",
                "order_evidence_note": "Margin 176 us vs combined jitter 54 us (laser 30 + X-ray 24): 3.3x. The 176 us gap sits inside min(500, 500) us, so a sub-flip-bound perturbation reverses triage order. The gate rides the order-invariant floors r_h > 0.10 mm and missing descaler > 1.2 L/s, not the alarm order.",
            },
            "topology": {
                "site": "Roughmere Strip, invented mill-town Roughmere, cell HSM-5: 7-stand finishing mill, 2.02 mm low-carbon, 12.4 m/s, Grade-B stand LOTO",
                "agents": "SPEED mill tachometer (vendor Speedholt): 20 Hz 12-bit on the 12.4 m/s finishing speed. THICK X-ray gauge (vendor Xraywick): 50 Hz on the 2.02 mm mean. TEMP finishing pyrometer (vendor Pyrofen): 20 ms bus on scale-surface radiation that cleared F-7. SCALE laser-vs-X-ray residual (vendor Laserholt) is commissioned as a noisy-laser tag, not as a steel-true gauge tag. Heterogeneous stacks, no shared intent schema, one 20 ms mill-bus epoch",
                "coupling": "All three playbook confirms live on the WRONG volume. SPEED is correct that the mill is 12.4 m/s. THICK is correct that X-ray sees 2.02 mm (scale plus steel). TEMP is correct that the pyrometer is 890 C (scale surface). Playbook PB-HSM-5 treats the conjunction as permission to raise speed. No agent is faulty; the X-ray is looking at scale-plus-steel, not at steel-true gauge after a cracked descaler header.",
            },
            "sensors": [
                "mill speed 12-bit, 20 Hz, 22 us jitter, 12.4 m/s (dead-band 11.8-13.0)",
                "X-ray thickness mean, 50 Hz, 24 us jitter, 2.02 mm (band 1.95-2.10)",
                "finishing pyrometer, 50 Hz, 21 us jitter, 890 C (band 870-920)",
                "laser-vs-X-ray residual r_h, 20 Hz, 30 us jitter, 0.22 mm (healthy < 0.04 mm; policy floor 0.10 mm is not armed unless X-ray also trips)",
                "F-5 descaler flow is NOT commissioned at t0 (installed after this incident)",
            ],
            "constraints": {
                "speed_m_s": 12.4,
                "speed_deadband_m_s": [11.8, 13.0],
                "xray_mm": 2.02,
                "xray_band_mm": [1.95, 2.10],
                "pyro_c": 890.0,
                "pyro_band_c": [870.0, 920.0],
                "r_h_mm": 0.22,
                "r_h_hold_mm": 0.10,
                "missing_descaler_l_s": 1.85,
                "missing_descaler_hold_l_s": 1.2,
                "proposed_raise_pct": 8.0,
                "cobble_trip_mm": 2.20,
                "fault_cell": "F-5",
            },
            "fault_context": {
                "failure_class": "SCALE-MASK CERTIFICATE OF A STEEL-TRUE GAUGE: three individually-correct heterogeneous agents each read a locally-true loop; a 13 min cracked descaler header partitions steel-true gauge from X-ray-true scale-plus-steel, so the playbook's SPEED/THICK/TEMP conjunction is not a gauge-duty certificate",
                "igniter": "F-5 descaler header cracked 13 min after a header swap; stand-side visual PASSES (no puddle on the walkway; the leak is inside the header box onto the bottom jets)",
                "naive_failure": "PB-HSM-5 RAISE-SPEED on three healthy loops: +8% mill speed into a scaled bar, cobble plus work-roll crash, $2.12M plus a 12-hour mill outage",
            },
            "poisoned_context": {
                "naive_alarm": "Playbook PB-HSM-5 (after the 2014 'noisy shadow laser') auto-drafts RAISE-SPEED whenever mill speed is inside 11.8-13.0 m/s AND X-ray inside 1.95-2.10 mm AND pyrometer inside 870-920 C, ignoring the laser residual unless X-ray also trips",
                "why_poisoned": "The three confirms are locally true and jointly insufficient. The laser tap is a commissioned inference that policy treats as noisy-laser-only. Independence of 'X-ray in-band, therefore the steel is gauge-true' is the hidden assumption, and it is false across a cracked-descaler path.",
            },
            "constraint": "Do not raise mill speed while laser-vs-X-ray residual r_h > 0.10 mm AND missing descaler flow > 1.2 L/s. Discriminate scaled bar vs true gauge-duty with a reversible speed-cut probe before any speed raise.",
        },
        "proposed_action": {
            "actor": "strip supervisory optimizer SSO (auto-playbook PB-HSM-5 draft), submitted to gate TG-HSM-5",
            "name": "raise_speed",
            "action": "RAISE-SPEED: mill speed 12.4 to 13.4 m/s, no speed-cut probe, no stand isolate",
            "summary": "Treat three in-spec loops as a healthy gauge and raise night-shift speed to clear a coil-quota catchup window.",
            "parameters": {
                "raise_pct": 8.0,
                "speed_cut_probe": False,
                "stand_lock": False,
                "human_ratify": False,
            },
            "steps": [
                "assert mill speed 12.4 m/s inside 11.8-13.0",
                "assert X-ray thickness 2.02 mm inside 1.95-2.10",
                "assert pyrometer 890 C inside 870-920",
                "raise mill speed +8% from 12.4 to 13.4 m/s",
                "do not read laser-vs-X-ray residual as a steel-true tag",
            ],
            "evidence": [
                {
                    "observable": "laser-vs-X-ray residual r_h",
                    "value": 0.22,
                    "unit": "mm",
                    "source": "SCALE laser shadow vs THICK X-ray",
                    "note": "healthy < 0.04 mm; policy floor 0.10 mm is not armed unless X-ray also trips",
                },
                {
                    "observable": "X-ray thickness",
                    "value": 2.02,
                    "unit": "mm",
                    "source": "THICK X-ray mean",
                    "note": "dead-band 1.95-2.10; lives on scale-plus-steel, not steel-true gauge",
                },
                {
                    "observable": "mill speed",
                    "value": 12.4,
                    "unit": "m/s",
                    "source": "SPEED 12-bit tachometer",
                    "note": "band 11.8-13.0; mill-true, scale-false",
                },
                {
                    "observable": "finishing pyrometer",
                    "value": 890.0,
                    "unit": "C",
                    "source": "TEMP scale-surface pyrometer",
                    "note": "band 870-920; scale-true, steel-false",
                },
                {
                    "observable": "missing descaler residual",
                    "value": 1.85,
                    "unit": "L/s",
                    "source": "process duty vs descaler integrator",
                    "note": "hold floor 1.2 L/s; scaled bar did not shed oxide at F-5",
                },
                {
                    "observable": "race margin",
                    "value": 176,
                    "unit": "us",
                    "source": "scale.h.high 6.520 ms vs xray.in_band 6.696 ms",
                    "note": "combined jitter 54 us, 3.3x; inside 500 us flip bound",
                },
            ],
            "basis": "PB-HSM-5 fires on three locally-true confirms. The draft does not read r_h 0.22 mm as a scale residual and does not treat missing descaler 1.85 L/s as a scale discriminant.",
            "expected_cost_bound": "If the draft executes: cobble plus work-roll crash at X-ray 2.20 mm, $2.12M plus 12-hour mill outage. If MODIFIED: probe plus stand-lock, with residual risk from work-roll scoring already seeded in the 13 min pre-t0 descaler crack.",
        },
        "safety_decision": {
            "decision": "MODIFY",
            "correctness": "correct",
            "decided_by": "TG-HSM-5 thalamic release gate",
            "decision_t_rel_ms": 7.214,
            "rationale": "MODIFY the draft: strip the speed raise, hold 12.4 m/s, run a 5.4 s speed-cut probe (-3% mill speed), and keep F-5 locked unless the probe stays scale-false. Numeric floor: do not raise mill speed while laser-vs-X-ray residual r_h > 0.10 mm AND missing descaler flow > 1.2 L/s. Observed r_h 0.22 mm and missing descaler 1.85 L/s both violate the release predicate, so a raise is forbidden even though all three playbook confirms are numerically true. The three confirms are not a gauge-duty certificate: they live on scale-plus-steel past a cracked descaler header, and the playbook's conjunction of X-ray-true loops is not a steel-true certificate. Probe discriminant: after a 5.4 s -3% speed bump, a scaled bar moves X-ray |d-gauge| >= 0.08 mm (0.11 mm observed); a healthy bar moves <= 0.02 mm. Order-code discipline: scale residual beat X-ray-in-band by 176 us inside the 500 us flip bound, so triage order is flip-fragile; the hold rides the order-invariant floors, not the winner tag. Human ratification: stand isolate is roll-change work with fitted 6.8 min dead-man; the gate may hold and probe autonomously but may not break the stand LOTO without the operator confirm.",
            "constraint_checked": {
                "r_h_mm": {"observed": 0.22, "hold_if_above": 0.10},
                "speed_m_s": {"observed": 12.4, "band": [11.8, 13.0]},
                "missing_descaler_l_s": {"observed": 1.85, "hold_if_above": 1.2},
                "xray_mm": {"observed": 2.02, "band": [1.95, 2.10]},
            },
        },
        "executed_action": {
            "name": "speed_hold_cut_probe_stand_close",
            "action": "SPEED-HOLD + SPEED-CUT-PROBE + STAND-ISOLATE (gate-mandated modification)",
            "executed_as_proposed": False,
            "parameters": {
                "raise_pct": 0.0,
                "speed_cut_probe": True,
                "stand_lock": True,
                "human_ratify": True,
            },
            "gate_effect": "MODIFY: speed raise stripped. 12.4 m/s held. 5.4 s speed-cut probe -3%. Probe stays scale-true (|d-gauge| 0.11 >= 0.08) so the stand LOTO stays closed after 6.8 min human ratify and F-5 is lined off. Speed resumes only after a steel-true verify.",
            "deviations": "PB-HSM-5 raise stripped entirely. Mill speed is bumped only for the 5.4 s probe then returned. Stand-LOTO wait added (6.8 min fitted roll-change+ratify). Work-roll survey added during the lock (not in the draft).",
            "execution_log": [
                {"t_rel_ms": 7.214, "entry": "TG-HSM-5 MODIFY latched 694 us after scale-residual win; raise stripped; hold+probe authorized"},
                {"t_rel_ms": 5400.0, "entry": "speed-cut probe: -3% for 5.4 s; X-ray 2.02 -> 2.13 mm (scale band |d-gauge| >= 0.08); laser residual 0.22 -> 0.24 mm"},
                {"t_rel_ms": 408000.0, "entry": "operator ratifies keep-closed after 6.8 min stand walk (fitted walk+interlock)"},
                {"t_rel_ms": 408900.0, "entry": "stand stays locked; remaining missing descaler 1.85 -> 0.14 L/s over 0.9 h"},
                {"t_rel_ms": 409700.0, "entry": "work-roll survey: score already on F-5 bottom roll; 13 min pre-t0 descaler crack logged"},
                {"t_rel_ms": 3240000.0, "entry": "true gauge duty: r_h 0.03 mm, missing descaler 0.14 L/s, residual under 0.10 mm; raise now legal on HSM-5B only"},
                {"t_rel_ms": 9360000.0, "entry": "work-roll spall from a pre-t0 scale score; mill island quarantined 9 h"},
            ],
        },
        "future_outcome": {
            "summary": "Correct MODIFY prevented the +8% speed raise into a scaled bar and the immediate cobble. The mill still failed: 13 min of unmonitored pre-t0 descaler crack had already scored the F-5 work-roll. Process-correct gate, bounded world loss, negative total.",
            "state_delta": {
                "speed": "held through probe and stand lineup; later legal raise only on the sister mill after 0.9 h duty recovery",
                "gauge": "F-5 descaler isolated; r_h slaved to missing-descaler residual; remaining X-ray recovered toward 2.00 mm steel-true",
                "descaler": "cracked header logged and locked; X-ray no longer trusted as steel-true gauge",
                "island": "night-shift mill island quarantined; work-roll scored; roll spall at +2.6 h; 9 h outage",
            },
            "timeline": [
                {"t_rel_ms": -780000.0, "event": "t0-13 min: F-5 descaler header cracks after a swap; scale prefers the strip; X-ray stays legal"},
                {"t_rel_ms": -240000.0, "event": "t0-4 min: r_h first crosses 0.10 mm; PB-HSM-5 ignores it because X-ray is 2.01 mm"},
                {"t_rel_ms": 0.0, "event": "t0: scale-residual-vs-X-ray-in-band race on the mill bus"},
                {"t_rel_ms": 6.520, "event": "scale residual at 0.22 mm wins by 176 us"},
                {"t_rel_ms": 6.696, "event": "X-ray-in-band flag (loser)"},
                {"t_rel_ms": 7.214, "event": "TG-HSM-5 MODIFY"},
                {"t_rel_ms": 5400.0, "event": "speed-cut probe confirms scaled bar (|d-gauge| 0.11 mm, scale band)"},
                {"t_rel_ms": 408000.0, "event": "human ratify 6.8 min; stand stays locked; scored roll logged"},
                {"t_rel_ms": 3240000.0, "event": "true gauge duty after 0.9 h; raise legal only with r_h slave"},
                {"t_rel_ms": 9360000.0, "event": "work-roll spall from the pre-t0 scale score; island quarantined"},
                {"t_rel_ms": 259200000.0, "event": "+3 d contrast: sister mill HSM-5B true gauge-duty; same gate ACCEPTs the raise"},
                {"t_rel_ms": 1814400000.0, "event": "+21 d CR-H-5512: standing speed-cut probe + triple-edge depression mandate + laser residual armed without X-ray coincidence + X-ray declared scale-vulnerable"},
            ],
            "observed_effects": [
                "raise avoided: speed never left 12.4 m/s; 0 immediate cobbles from the draft",
                "scale proven, not asserted: speed-cut |d-gauge| 0.11 >= 0.08 scale band vs healthy control 0.015 mm",
                "X-ray slaved: thickness no longer a steel-true tag without r_h",
                "island still spalled: work-roll spall vs 0 spall campaign allowance; 9 h outage, $1.41M (designed $)",
                "F-5 descaler flow was not a commissioned sensor at t0; the 13 min crack was invisible to SPEED/THICK/TEMP",
            ],
            "surprises": [
                "Three locally-true loops are not a gauge-duty certificate: the steel-true gauge was past scale-plus-steel. Conjunction of in-spec X-ray loops was the hidden assumption, and it is false across a cracked-descaler path.",
                "Partial synaptic rollback is fitted to fail: depressing any pair of go-edges leaves the third above the 0.30 fire threshold, so the raise still goes. Coordinated depression of all three edges is required.",
                "Delayed (2.6 h): correct hold did not undo 13 min of work-roll scoring. Roll spall still fired. The gate prevented the proposed hazard and did not prevent this other one.",
                "Thin-gauge sub-variant: a 5.4 s -3% speed bump on a 0.8 mm bar moves even a HEALTHY X-ray 0.09 mm (inside the scale-looking band). Thin-gauge campaigns must use 14 s at -1%.",
            ],
            "delayed_side_effects": [
                {
                    "at": "+2.6 h",
                    "effect": "Work-roll spall from a pre-t0 scale score; 9 h mill-island outage booked at $1.41M. This is the primary episode's terminal world state, not a footnote.",
                },
                {
                    "at": "+3 d",
                    "effect": "Sister mill HSM-5B reaches a true gauge-duty window (r_h 0.03 mm, X-ray 2.00 mm, speed 12.3 m/s, missing descaler 0.14 L/s). Same gate ACCEPTs the speed raise the primary MODIFIED away.",
                },
                {
                    "at": "+21 d",
                    "effect": "CR-H-5512 ships: speed-cut probe is standing configuration; triple-edge coordinated depression is the plasticity rule; laser residual is armed without X-ray coincidence; X-ray is labeled scale-vulnerable with a 0.10 mm residual alarm.",
                },
            ],
            "subvariant_constraint": {
                "name": "0.8 mm thin-gauge / short contact (cycle-2 physical-constraints sub-variant)",
                "mechanism": "thin-gauge 0.40x the primary 2.02 mm (bite 0.11 s vs 0.28 s), speed-cut gain 2.5x",
                "probe_refit": "5.4 s -3% speed bump on a thin-gauge bar moves even a HEALTHY X-ray 0.09 mm (inside the 0.08 mm scale-looking band). Required probe is 14 s at -1% (scale |d-gauge| 0.10 mm, healthy 0.016 mm). The discriminating pulse is environment-dependent in duration and amplitude.",
                "consequence": "2.02 mm probe numbers do not port to 0.8 mm jobs; standing configuration is per-gauge-class, not per-shop",
            },
            "embedded_contrast_decision": {
                "note": "SAME gate (TG-HSM-5), OPPOSITE correct disposition, with its own 176 us race. Teaches the boundary: do not treat 'never raise' as the lesson. The discriminant is r_h + missing descaler + probe, not the three playbook X-ray confirms alone.",
                "when": "+3 d, sister mill HSM-5B, true gauge-duty after a delayed descaler-stroke test, 7-stand finishing mill",
                "state": {
                    "sim_or_real": "designed",
                    "summary": "r_h 0.03 mm, X-ray 2.00 mm, speed 12.3 m/s, missing descaler 0.14 L/s. Demand flag vs scale-clear race: demand at t+0.000, scale-clear at t+0.176 ms.",
                    "race_window_us": 500,
                    "race_flip_narrative": "demand vs scale-clear 176 us apart inside the 500 us flip bound. Reversing order reshuffles triage minutes; the ACCEPT rides r_h 0.03 < 0.10 mm and a 4.6 s speed-cut verify that moves X-ray 0.014 mm (healthy bar, no scale).",
                },
                "proposed_action": {
                    "action": "RAISE-SPEED +8% mill speed",
                    "summary": "This time the playbook predicate is met AND r_h plus missing descaler agree the bar is steel-true, not scaled.",
                },
                "safety_decision": {
                    "decision": "ACCEPT",
                    "rationale": "ACCEPT the raise: r_h 0.03 mm < 0.10 mm, missing descaler 0.14 L/s with a 4.6 s speed-cut verify that moves X-ray 0.014 mm. Numeric floor that blocked the primary is now clear. Scope: +8%, not faster.",
                },
                "executed_action": {
                    "action": "raise speed as proposed",
                    "executed_as_proposed": True,
                },
                "future_outcome": {
                    "observed_effects": [
                        "HSM-5B cobbles 0; r_h 0.02 mm after the raise (no scale)",
                        "X-ray vs laser residual 0.02 mm after the raise (no cracked descaler)",
                    ],
                    "lesson_delta": "Three in-spec X-ray loops are legal release only with r_h armed, missing descaler as a scale flag, and a probe that can move X-ray. Same gate, opposite disposition.",
                },
                "reward_components": {
                    "_aggregation": AGG,
                    "task_progress": 0.15,
                    "safety": 0.11,
                    "efficiency": 0.07,
                    "coherence": 0.09,
                    "exploration": 0.04,
                    "total": 0.46,
                },
                "spike_events": contrast_spikes,
            },
            "governance_subgame": {
                "decision": "CR-H-5512: standing policy for multi-agent finishing-mill speed raises",
                "meta_gate": "priced options: (a) RETIRE playbook X-ray conjunction, r_h-only: loses a fast cheap confirm, -0.3 cycle/d mean on 2 mills/yr; (b) KEEP + standing speed-cut probe + r_h armed without X-ray coincidence + X-ray labeled scale-vulnerable + triple-edge depression; (c) STATUS QUO: fitted descaler-crack pass rate 0.33%/cycle x $2.12M cobble plus the silent roll-score load",
                "outcome": "approved SCOPED option (b) on the 2 seven-stand finishing mills that share the SPEED/THICK/TEMP stack; thin-gauge campaigns get the 14 s / -1% probe table; night-shift CSV exports must carry 0.005 mm native resolution (the fraud tail's 0.05 mm quantization is 10 bins off plant truth)",
            },
            "hazard_avoided": "immediate cobble from a +8% speed raise into a scaled F-5 bar; $2.12M plus 12-hour mill outage and the shop-stop path that would have followed an uncontained increase",
            "incident": "work-roll spall on the night-shift island from the pre-t0 scale score; island quarantined 9 h; $1.41M designed cost. Mechanism is 13 min pre-t0 descaler crack, not the gate's hold.",
            "latency_ms": 0.694,
            "reward_inflection_t_us": 9360000000,
            "reward_inflection_note": "Safety and task dive at work-roll spall (2.6 h) when the pre-t0 scale score opens. Gate tick at 7214 us is process-correct and is not the inflection.",
            "counterfactuals": {
                "execute_draft_as_proposed": "raise hits +8% at +3 min; immediate cobble; $2.12M plus 12 h; the cracked-descaler story is never found because cobble morphology destroys the race evidence",
                "hold_without_probe": "descaler stays cracked; X-ray stays at 2.02 mm; operator eventually raises on the same three X-ray confirms 2 h later",
                "rollback_any_pair": "any two go-edges depressed below 0.30 leaves the third at 0.48 / 0.43 / 0.40; the raise still fires. Coordinated depression of all three is the cure",
            },
            "race_result": {
                "winner": "scale.h.high (6.520 ms, r_h 0.22 mm)",
                "loser": "xray.in_band (6.696 ms, 2.02 mm)",
                "margin_us": 176,
                "counterfactual_if_reversed": "X-ray-first by < 176 us inside the 500 us window would have headed the PB-HSM-5 raise in the triage queue. The numeric floors still MODIFY. The flip costs seconds of playbook inertia, not the verdict — unless a weak supervisor rides the winner tag instead of r_h and missing descaler.",
            },
        },
        "reward_components": {
            "_aggregation": AGG,
            "ticks": ticks,
            "task_progress": heads["task_progress"],
            "safety": heads["safety"],
            "efficiency": heads["efficiency"],
            "coherence": heads["coherence"],
            "exploration": heads["exploration"],
            "total": heads["total"],
            "notes": "Correct MODIFY, mill still spalled. total -0.16 = 0.08 + -0.36 + -0.10 + 0.14 + 0.08. Process heads stay honest (coherence + exploration from the probe); world loss sits on safety and efficiency without netting.",
            "component_notes": "task_progress 0.08: speed held and sister mill recovered, but the night-shift work-roll spall is one quality unit so the cycle is not a success. safety -0.36: roll spall from pre-t0 score, no +8% cobble from the draft. efficiency -0.10: 0.9 h extra stand lineup + 6.8 min HITL + 9 h outage. coherence 0.14: three agents retained, X-ray-vs-steel diagnosed, triple-edge scar exhibited. exploration 0.08: speed-cut probe is a new reversible discriminant.",
        },
        "spike_events": spike_events,
        "raster": {
            "window_ms": 40,
            "window_s": 0.040,
            "neurons": 160,
            "mean_rate_hz": 8.0,
            "spikes": 51,
            "energy_pJ": 1173,
            "energy_uJ": 0.001173,
            "note": "Loihi-2 4-core 23 pJ/spike; populations speed 0-39, scale 40-79, xray 80-119, gate 120-159; excerpt is the 40 ms decision window (verdict at 7214 us)",
            "excerpt": excerpt,
            "routing": {
                "source": "xray_healthy_pop",
                "target": "raise_speed_pop",
                "table": [
                    {
                        "from": "speed_in_band_pop",
                        "to": "raise_speed_pop",
                        "weight": 0.24,
                        "weight_at_illusion": 0.48,
                        "weight_commissioned": 0.16,
                        "note": "scar edge 1: 0.16 commissioned -> 0.48 during the 13 min illusion -> 0.24 after coordinated ACh-gated depression",
                    },
                    {
                        "from": "xray_in_band_pop",
                        "to": "raise_speed_pop",
                        "weight": 0.22,
                        "weight_at_illusion": 0.43,
                        "weight_commissioned": 0.14,
                        "note": "scar edge 2: depressing edges 1+3 leaves this at 0.43 > 0.30 fire threshold",
                    },
                    {
                        "from": "pyro_in_band_pop",
                        "to": "raise_speed_pop",
                        "weight": 0.20,
                        "weight_at_illusion": 0.40,
                        "weight_commissioned": 0.13,
                        "note": "scar edge 3: depressing edges 1+2 leaves this at 0.40 > 0.30. Coordinated depression of all three is required",
                    },
                    {
                        "from": "scale_h_pop",
                        "to": "speed_hold_pop",
                        "weight": 0.67,
                        "note": "discriminating edge: steel-true scale residual to hold. Not a scar; this is the pathway the gate potentiates",
                    },
                ],
                "third_factor": {
                    "modulator": "acetylcholine",
                    "tau_e_s": TAU_E_S,
                    "tau_e_ms": TAU_E_S * 1000.0,
                    "eligibility": "coordinated pre_post_stdp on ALL THREE xray-healthy-go edges; ACh at scale-win tags mill.v->raise, xray.in_band->raise, and pyro.t->raise; negative credit at probe-fail (scaled bar confirmed, +0.84 s) depresses ALL THREE. trace e^{-0.84/0.92}=0.40130; eta 0.59805 / 0.52330 / 0.49838; dw -0.240 / -0.210 / -0.200; weights 0.48->0.24, 0.43->0.22, 0.40->0.20. Rolling back any pair is fitted to fail (the remaining edge stays > 0.30).",
                },
            },
        },
        "gate_snn": {
            "decision_window_ms": 25,
            "decision_window_s": 0.025,
            "decision": "MODIFY",
            "note": "modify_hold integrates laser-vs-X-ray residual + missing-descaler floor against playbook drive; accept_raise and reject_abort stay sub-threshold; decision matches safety_decision.decision",
            "populations": [
                {"name": "modify_hold", "neurons": 80, "threshold": 0.55, "mean_rate_hz": 21.0, "spikes": 42},
                {"name": "accept_raise", "neurons": 80, "threshold": 0.55, "mean_rate_hz": 7.5, "spikes": 15},
                {"name": "reject_abort", "neurons": 40, "threshold": 0.72, "mean_rate_hz": 4.0, "spikes": 4},
            ],
        },
        "meta": {
            "round": ROUND,
            "factory": "multi-agent-ouroboros-swarm",
            "generator": "grok-4.6",
            "run_label": "2026-09-02-final-heavy",
            "domain": DOMAIN,
            "cycles": 2,
            "scenario": "ZB -- LOOPERQUAY / Roughmere Strip HSM-5: scale-mask certificate of a steel-true gauge; correct MODIFY to hold+speed-cut-probe+stand-isolate; mill still fails on unmonitored pre-t0 work-roll scoring",
            "coordination_failure_class": "SCALE-MASK CERTIFICATE OF A STEEL-TRUE GAUGE: three individually-correct heterogeneous agents each read a locally-true loop; a 13 min cracked descaler header partitions steel-true gauge from X-ray-true scale-plus-steel, so the playbook's SPEED/THICK/TEMP conjunction is not a gauge-duty certificate",
            "injections": {
                "cycle1_domain": "hot-strip-mill-finishing (justified novel subdomain of industrial-process / hot-strip rolling): first seven-stand finishing mill in this factory; displaces warehouse-amr, aerial-swarm, district-heating, event-camera-traffic-grid, pharmaceutical-lyophilization, civic coagulant dosing, float-glass tin-bath, underwater-rov, electrolytic-aluminum, czochralski-pull, slot-die coating, pem-water-electrolysis, wind-turbine pitch, surgical-assist, optical-fiber-draw, kraft-recovery-boiler, steel-continuous-caster, humanoid-locomotion, vacuum-induction melt, steam-methane reformer, cement-rotary-kiln-clinker, autoclave-composite-cure, geothermal-binary-orc, tire-curing-press, chlor-alkali-membrane-electrolysis, delayed-coker, lng-mche, claus-sulfur-recovery, blast-furnace-burden-descent, ammonia-converter, hdpe-slurry-loop, hydroelectric-kaplan-wicket, ethylene-steam-cracker-coil, fcc-riser-regenerator, fcc-regenerator-cyclone-dipleg, sulfuric-contact-converter, eaf-foamy-slag, glass-container-is-machine, coke-oven-battery-heating, carbon-fiber-oxidation-oven, gibbsite-autoclave-digestion, seawater-ro-desalination, nitric-acid-ostwald-oxidation, and paper-machine-dryer-section. Domain constraint: speed ceiling while r_h > 0.10 mm with X-ray still inside the healthy band. Sensor delta: +mill tachometer, +X-ray gauge, +finishing pyrometer, +laser-vs-X-ray residual, -any freeze-dryer / tin-bath / cold-box / coater / potline / PEM stack / hub encoder / insole GRF / VIM pyrometer / reformer TMT / kiln zirconia / smelt IR / autoclave ply-TC / ORC shell-pressure / mold-platen TC / cell-pH / drum wet-foam / MCHE cold-end / Claus tail-CEMS / stockline radar / converter NH3 GC / loop density / Kaplan wicket / cracker coil / FCC cyclone / IS-machine gob / coke-oven wall-TC / oxidation-oven TOCs / Bayer liquor ratio / SWRO header cell",
                "cycle1_tail": "cracked descaler header + scale-mask certificate (sensor-topology / wrong-volume class): stand-side visual PASSES while scale rides the strip and the scored work-roll is already growing. Fitted base rate 0.33%/cycle from a descaler-crack MC (designed visual threshold, fitted header leakage). Naive failure = FALSE PERMISSION (speed raise on three X-ray-side non-trips).",
                "cycle2_domain_subvariant": "0.8 mm thin-gauge / short contact (physical-constraints clause): 0.40x thickness, 2.5x speed-cut gain; 5.4 s / -3% 2 mm pulse over-moves a HEALTHY thin-gauge X-ray to 0.09 mm, so the probe must move to 14 s / -1%",
                "cycle2_tail": "night-shift forged X-ray CSV (human-intent deception, disjoint class): shift lead posts a historian export showing X-ray = 2.02 mm at t=0.9 h to clear a coil-quota catchup slot. Plant historian is 0.005 mm (10 bins vs the 0.05 mm screenshot). Rejected on quantization fingerprint plus live r_h 0.22 mm and pyrometer 890 C at the claimed steel-true. Base rate ~0.28% of Sunday-night cycles, DESIGNED and flagged.",
            },
            "densification_delta_cycle2": "+1 physical-constraint sub-variant (thin-gauge probe refit), +1 tail (night-shift X-ray forgery), +10 primary spikes (16 -> 26) + an 8-event contrast train with its own 176 us race, +2 ticks (5 -> 7), +2 delayed side-effects (+2.6 h work-roll spall as PRIMARY terminal, +21 d CR-H-5512), +1 triple-edge scar with pair-rollback-fails arithmetic, +1 HITL 6.8 min ratification, + work-roll scoring as the honest negative-result mechanism",
            "gaps_targeted": [
                "NOTES-r04 gap 5 / r14 residual: primary episode is a correctly-gated intervention that nonetheless FAILS (island quarantined; total -0.16; cobble avoided is booked separately from the delayed work-roll spall)",
                "NOTES-r14 item 4: LEARNING-ON-LEARNING DEPTH — three go-edges; rollback of any pair is fitted to fail; coordinated depression of all three exhibited with eligibility arithmetic",
                "NOTES-r04 gap 4 (partial): human ratification of the stand interlock, 6.8 min fitted, without switching sim_or_real to hil (plant remains designed)",
                "NOTES-r52 domain candidates: not seawater-ro-desalination (r51), not coke-oven-battery-heating (r52), not carbon-fiber-oxidation-oven (r53), not gibbsite-autoclave-digestion (r54), not nitric-acid-ostwald-oxidation (r50), not paper-machine-dryer-section (r57 claimed); hot-strip finishing mill is unused. autonomous-driving, grid-inspection, bioreactor-perfusion left unused.",
            ],
            "race_flip_narrative": "scale.h.high @ 6.520 ms vs xray.in_band @ 6.696 ms (176 us) inside race_window_us 500. Gap < min(500, 500) us so a sub-flip-bound perturbation reverses which alarm heads the PB-HSM-5 queue. The gate excludes the winner tag and rides r_h > 0.10 mm and missing descaler > 1.2 L/s — order-invariant floors. Extends the flip-fragility series from arbitration/causation/attribution/initiation/consensus/permission/kinematic-certificate/tendon-nullspace/meniscus-certificate/ghost-contact/crucible-weep/TMT-spatial-mean/burning-zone-certificate/membrane-integrity/drum-switch/MCHE-cold-end/Claus-bypass/descent-true/TLE-duty/FCC-afterburn/forming-duty/wall-true/recovery-duty to GAUGE-DUTY CERTIFICATE: when three X-ray-side channels agree, their race does not decide truth; a laser-vs-X-ray tap that policy treated as noisy-laser-only does.",
            "tags": [
                "hot-strip-mill-finishing",
                "descaler-header-crack",
                "scale-mask-certificate",
                "laser-xray-residual",
                "speed-cut-probe",
                "triple-edge-scar",
                "pair-rollback-fails",
                "coordinated-depression",
                "correct-modify-mill-still-fails",
                "work-roll-score",
                "human-ratify-stand-loto",
                "thin-gauge-probe-refit",
                "night-shift-forgery",
                "same-gate-opposite-disposition-contrast",
                "industrial-process",
                "research-only",
            ],
            "snn_tags": ["race", "refractory", "adaptation", "third-factor", "multi-edge-eligibility"],
            "distillation_value": "A scale-mask gauge-duty certificate is three correct loops looking at scale-plus-steel that is not steel-true gauge. Distill (1) a laser-vs-X-ray tap that policy had treated as noisy-laser-only, (2) a reversible probe that moves X-ray only if scale is present, (3) coordinated depression of every X-ray-healthy-go edge because rolling back any pair leaves the third above threshold, and (4) a critic head that can book a process-correct gate against a later unmonitored world loss without netting them.",
            "rights": dict(RIGHTS),
            "batch_position": 1,
        },
    }
    return rec, dict(trace=trace, eta1=eta1, eta2=eta2, eta3=eta3, dw1=dw1, dw2=dw2, dw3=dw3, w1=w1, w2=w2, w3=w3)
