#!/usr/bin/env python3
"""DB-mill plant catalog part 1 (30 of 88 plants, AST-extracted).

Canonical regeneration of the legacy ``unique_db_migration_repair_mill``
``PLANTS`` slice: values preserved, formatting canonical. Each entry is a
:func:`plant.make_plant` call with fixed keyword order so diffs are
meaningful. No I/O, no execution on import.
"""

from __future__ import annotations

from .plant import make_plant
from .import_twins import bind_import_twin

__all__ = ["PLANTS_01"]

PLANTS_01 = [
    make_plant(
        engine='mysql',
        slug='mysql-algorithm-inplace-leftover',
        plant='mysql-inplace',
        surface='mysql-algorithm-inplace',
        table='shop.inplace_sku',
        col='sku',
        col_v2='sku_norm',
        leftover='#sql-ib-inplace-sku',
        leftover2='inplace_sku_frm_tmp',
        seed='ALTER TABLE shop.inplace_sku ALGORITHM=INPLACE, LOCK=NONE, CHANGE sku sku VARCHAR(191)',
        fail='ERROR 1846 (0A000): ALGORITHM=INPLACE is not supported. Reason: Cannot CHANGE column type INPLACE. leftover #sql-ib-inplace-sku + inplace_sku_frm_tmp',
        inspect="SELECT NAME, SPACE FROM information_schema.INNODB_TABLESPACES WHERE NAME LIKE 'shop/inplace_sku%'",
        catalog='INPLACE abort leftover #sql-ib tmp; expand sku_norm',
        abort='DROP TABLE IF EXISTS shop.`#sql-ib-inplace-sku`',
        col_type='VARCHAR(191)',
    ),
    make_plant(
        engine='sqlite',
        slug='sqlite-table-rewrite-already-skip',
        plant='sqlite-rewrite-skip',
        surface='sqlite-table-rewrite',
        table='rewrite_item',
        col='body',
        col_v2='body_v2',
        leftover='sqlite_altertab_rewrite_item',
        leftover2='rewrite_item_old',
        seed='ALTER TABLE rewrite_item RENAME COLUMN body TO body_v2',
        fail='NOTICE: already skip: sqlite table rewrite in progress; leftover sqlite_altertab_rewrite_item + rewrite_item_old',
        inspect="SELECT name, sql FROM sqlite_master WHERE name LIKE 'rewrite_item%'",
        catalog='table-rewrite already-skip leftover sqlite_altertab; expand body_v2',
        abort='DROP TABLE IF EXISTS sqlite_altertab_rewrite_item',
        col_type='BLOB',
        lock_fail='Error: database is locked ADD body_v2 on rewrite_item',
        db='rewrite.db',
    ),
    make_plant(
        engine='mssql',
        slug='mssql-online-rebuild-leftover',
        plant='mssql-online',
        surface='mssql-online-rebuild',
        table='sales.online_order',
        col='qty',
        col_v2='qty_v2',
        leftover='online_order_rebuild_tmp',
        leftover2='online_order_iro_row',
        seed='ALTER INDEX IX_online_order_qty ON sales.online_order REBUILD WITH (ONLINE=ON, MAXDOP=1)',
        fail='Msg 608: Cannot rebuild ONLINE while a resumable operation is pending; leftover online_order_rebuild_tmp + online_order_iro_row',
        inspect="SELECT name, is_hypothetical FROM sys.indexes WHERE object_id=OBJECT_ID('sales.online_order')",
        catalog='ONLINE rebuild leftover resumable row; expand qty_v2',
        abort='KILL RESUMABLE INDEX ON sales.online_order; DROP TABLE IF EXISTS sales.online_order_rebuild_tmp',
        col_type='BIGINT',
        lock_fail='Msg 1222: Lock request time out period exceeded ADD qty_v2 on sales.online_order',
    ),
    make_plant(
        engine='oracle',
        slug='oracle-invisible-index-leftover',
        plant='oracle-invis-idx',
        surface='oracle-invisible-index',
        table='hr.inv_idx_emp',
        col='empno',
        col_v2='emp_uuid',
        leftover='INV_IDX_EMP_I',
        leftover2='SYS_IOT_OVER_EMP_TMP',
        seed='ALTER INDEX hr.inv_idx_emp_i INVISIBLE',
        fail='ORA-14147: cannot ALTER INDEX INVISIBLE while DML holds the index; leftover INV_IDX_EMP_I (INVISIBLE) + SYS_IOT_OVER_EMP_TMP',
        inspect="SELECT index_name, visibility FROM user_indexes WHERE table_name='INV_IDX_EMP'",
        catalog='invisible index leftover; expand emp_uuid, do not drop empno',
        abort='ALTER INDEX hr.inv_idx_emp_i VISIBLE; DROP TABLE hr.SYS_IOT_OVER_EMP_TMP',
        col_type='VARCHAR2(36)',
        lock_fail='ORA-00054: resource busy and acquire with NOWAIT specified ADD emp_uuid on hr.inv_idx_emp',
    ),
    make_plant(
        engine='mariadb',
        slug='mariadb-instant-add-leftover',
        plant='maria-instant',
        surface='mariadb-instant-add',
        table='catalog.maria_instant_sku',
        col='sku',
        col_v2='sku_norm',
        leftover='#sql-alter-maria_instant',
        leftover2='maria_instant_sku_instant_tmp',
        seed="ALTER TABLE catalog.maria_instant_sku ALGORITHM=INSTANT, ADD COLUMN sku_pad VARCHAR(8) DEFAULT ''",
        fail='ERROR 1845 (0A000): ALGORITHM=INSTANT not supported with MAX_ROWS/ROW_FORMAT leftover #sql-alter-maria_instant + maria_instant_sku_instant_tmp',
        inspect="SELECT TABLE_NAME, CREATE_OPTIONS FROM information_schema.TABLES WHERE TABLE_NAME='maria_instant_sku'",
        catalog='MariaDB INSTANT abort leftover alter tmp; expand sku_norm',
        abort='DROP TABLE IF EXISTS catalog.`#sql-alter-maria_instant`',
        col_type='VARCHAR(191)',
    ),
    make_plant(
        engine='mysql',
        slug='mysql-algorithm-copy-tmp-leftover',
        plant='mysql-copy-tmp',
        surface='mysql-algorithm-copy',
        table='warehouse.copy_blob',
        col='body',
        col_v2='body_v2',
        leftover='#sql-copy-blob',
        leftover2='copy_blob_new',
        seed='ALTER TABLE warehouse.copy_blob ALGORITHM=COPY, CHANGE body body LONGBLOB',
        fail='ERROR 1795 (HY000): ALGORITHM=COPY killed mid-copy; leftover #sql-copy-blob + copy_blob_new',
        inspect="SELECT NAME FROM information_schema.INNODB_TABLESPACES WHERE NAME LIKE 'warehouse/copy_blob%'",
        catalog='COPY abort leftover tmp table; expand body_v2',
        abort='DROP TABLE IF EXISTS warehouse.`#sql-copy-blob`',
        col_type='LONGBLOB',
        lock_fail='ERROR 1205 (HY000): Lock wait timeout exceeded ADD body_v2 on warehouse.copy_blob',
    ),
    make_plant(
        engine='mysql',
        slug='mysql-fk-checks-off-leftover',
        plant='mysql-fk-off',
        surface='mysql-fk-checks',
        table='auth.fk_session',
        col='user_id',
        col_v2='user_uuid',
        leftover='fk_session_ibfk_tmp',
        leftover2='fk_session_orphan',
        seed='SET FOREIGN_KEY_CHECKS=0; ALTER TABLE auth.fk_session CHANGE user_id user_id BIGINT',
        fail='ERROR 1452 (23000): FOREIGN_KEY_CHECKS=0 left orphans; leftover fk_session_ibfk_tmp + fk_session_orphan',
        inspect="SELECT CONSTRAINT_NAME, REFERENCED_TABLE_NAME FROM information_schema.KEY_COLUMN_USAGE WHERE TABLE_NAME='fk_session'",
        catalog='FK_CHECKS=0 leftover orphans+tmp; expand user_uuid',
        abort='DROP TABLE IF EXISTS auth.fk_session_ibfk_tmp',
        col_type='CHAR(36)',
        lock_fail='ERROR 1205 (HY000): Lock wait timeout exceeded ADD user_uuid on auth.fk_session',
    ),
    make_plant(
        engine='sqlite',
        slug='sqlite-wal-checkpoint-leftover',
        plant='sqlite-wal',
        surface='sqlite-wal-checkpoint',
        table='wal_doc',
        col='payload',
        col_v2='payload_v2',
        leftover='wal_doc-wal',
        leftover2='wal_doc-shm',
        seed='PRAGMA wal_checkpoint(TRUNCATE)',
        fail='SQLITE_BUSY: wal checkpoint leftover wal_doc-wal + wal_doc-shm; skip in-place rewrite',
        inspect='PRAGMA journal_mode; PRAGMA wal_checkpoint(PASSIVE)',
        catalog='WAL/SHM leftover after failed checkpoint; expand payload_v2',
        abort='PRAGMA wal_checkpoint(PASSIVE)',
        col_type='TEXT',
        lock_fail='Error: database is locked ADD payload_v2 on wal_doc',
        db='wal.db',
    ),
    make_plant(
        engine='mssql',
        slug='mssql-resumable-index-leftover',
        plant='mssql-resumable',
        surface='mssql-resumable-index',
        table='finance.resumable_ledger',
        col='amount',
        col_v2='amount_v2',
        leftover='resumable_ledger_ix_tmp',
        leftover2='resumable_ledger_iro_row',
        seed='ALTER INDEX IX_resumable_ledger_amount ON finance.resumable_ledger REBUILD WITH (ONLINE=ON, RESUMABLE=ON)',
        fail='Msg 10637: resumable index already paused; leftover resumable_ledger_ix_tmp + resumable_ledger_iro_row',
        inspect='SELECT object_id, sql_text, state_desc FROM sys.index_resumable_operations',
        catalog='RESUMABLE=ON leftover paused rebuild; expand amount_v2',
        abort='ALTER INDEX IX_resumable_ledger_amount ON finance.resumable_ledger ABORT',
        col_type='DECIMAL(18,4)',
        lock_fail='Msg 1222: Lock request time out period exceeded ADD amount_v2 on finance.resumable_ledger',
    ),
    make_plant(
        engine='oracle',
        slug='oracle-online-redef-interim-leftover',
        plant='oracle-redef',
        surface='oracle-online-redef',
        table='erp.redef_item',
        col='sku',
        col_v2='sku_norm',
        leftover='REDEF_ITEM_INT',
        leftover2='REDEF_ITEM$SNAP',
        seed="BEGIN DBMS_REDEFINITION.FINISH_REDEF_TABLE('ERP','REDEF_ITEM','REDEF_ITEM_INT'); END;",
        fail='ORA-23539: online redefinition interim leftover REDEF_ITEM_INT + REDEF_ITEM$SNAP; skip finish_redef',
        inspect="SELECT * FROM dba_redefinition_status WHERE object_name='REDEF_ITEM'",
        catalog='online redef interim leftover; expand sku_norm',
        abort="BEGIN DBMS_REDEFINITION.ABORT_REDEF_TABLE('ERP','REDEF_ITEM','REDEF_ITEM_INT'); END;",
        col_type='VARCHAR2(191)',
        lock_fail='ORA-00054: resource busy and acquire with NOWAIT specified ADD sku_norm on erp.redef_item',
    ),
    make_plant(
        engine='mysql',
        slug='mysql-generated-stored-leftover',
        plant='mysql-gen-stored',
        surface='mysql-generated-stored',
        table='catalog.gen_stored_price',
        col='amount',
        col_v2='amount_v2',
        leftover='gen_stored_price_gc_tmp',
        leftover2='gen_stored_price_gc_old',
        seed='ALTER TABLE catalog.gen_stored_price MODIFY amount DECIMAL(12,4) GENERATED ALWAYS AS (net+tax) STORED',
        fail='ERROR 3105 (HY000): cannot ALTER STORED generated INPLACE; leftover gen_stored_price_gc_tmp + gen_stored_price_gc_old',
        inspect="SELECT COLUMN_NAME, GENERATION_EXPRESSION, EXTRA FROM information_schema.COLUMNS WHERE TABLE_NAME='gen_stored_price'",
        catalog='STORED generated leftover tmp; expand amount_v2',
        abort='DROP TABLE IF EXISTS catalog.gen_stored_price_gc_tmp',
        col_type='DECIMAL(12,4)',
        lock_fail='ERROR 1205 (HY000): Lock wait timeout exceeded ADD amount_v2 on catalog.gen_stored_price',
    ),
    make_plant(
        engine='sqlite',
        slug='sqlite-strict-table-rewrite-leftover',
        plant='sqlite-strict',
        surface='sqlite-strict-table',
        table='strict_profile',
        col='email',
        col_v2='email_v2',
        leftover='sqlite_strict_profile_new',
        leftover2='sqlite_stat1',
        seed='CREATE TABLE strict_profile_new (id INTEGER PRIMARY KEY, email TEXT) STRICT',
        fail='Parse error: STRICT table rewrite leftover sqlite_strict_profile_new + sqlite_stat1; skip in-place',
        inspect="SELECT name, sql FROM sqlite_master WHERE name LIKE 'strict_profile%'",
        catalog='STRICT rewrite leftover _new; expand email_v2',
        abort='DROP TABLE IF EXISTS sqlite_strict_profile_new',
        col_type='TEXT',
        lock_fail='Error: database is locked ADD email_v2 on strict_profile',
        db='strict.db',
    ),
    make_plant(
        engine='mssql',
        slug='mssql-temporal-history-leftover',
        plant='mssql-temporal',
        surface='mssql-temporal-history',
        table='audit.temporal_claim',
        col='status',
        col_v2='status_v2',
        leftover='temporal_claim_history_tmp',
        leftover2='temporal_claim_sys_time',
        seed='ALTER TABLE audit.temporal_claim SET (SYSTEM_VERSIONING = ON (HISTORY_TABLE=audit.temporal_claim_history))',
        fail='Msg 13591: cannot ALTER SYSTEM_VERSIONING; leftover temporal_claim_history_tmp + temporal_claim_sys_time',
        inspect="SELECT t.name, t.temporal_type_desc FROM sys.tables t WHERE t.name='temporal_claim'",
        catalog='temporal history leftover tmp; expand status_v2',
        abort='ALTER TABLE audit.temporal_claim SET (SYSTEM_VERSIONING = OFF)',
        col_type='NVARCHAR(32)',
        lock_fail='Msg 1222: Lock request time out period exceeded ADD status_v2 on audit.temporal_claim',
    ),
    make_plant(
        engine='oracle',
        slug='oracle-unusable-index-leftover',
        plant='oracle-unusable',
        surface='oracle-unusable-index',
        table='dwh.unusable_fact',
        col='dim_id',
        col_v2='dim_uuid',
        leftover='UNUSABLE_FACT_I',
        leftover2='UNUSABLE_FACT_REBUILD_TMP',
        seed='ALTER INDEX dwh.unusable_fact_i REBUILD ONLINE',
        fail='ORA-01502: index DWH.UNUSABLE_FACT_I or partition of such index is in unusable state; leftover UNUSABLE_FACT_I + UNUSABLE_FACT_REBUILD_TMP',
        inspect="SELECT index_name, status FROM user_indexes WHERE table_name='UNUSABLE_FACT'",
        catalog='UNUSABLE index leftover after failed ONLINE rebuild; expand dim_uuid',
        abort='DROP TABLE dwh.UNUSABLE_FACT_REBUILD_TMP',
        col_type='VARCHAR2(36)',
        lock_fail='ORA-00054: resource busy and acquire with NOWAIT specified ADD dim_uuid on dwh.unusable_fact',
    ),
    make_plant(
        engine='mysql',
        slug='mysql-fulltext-parser-leftover',
        plant='mysql-ft-parser',
        surface='mysql-fulltext-parser',
        table='search.ft_article',
        col='body',
        col_v2='body_v2',
        leftover='ft_article_fts_tmp',
        leftover2='fts_00000_aux',
        seed='ALTER TABLE search.ft_article ADD FULLTEXT INDEX ft_body (body) WITH PARSER ngram',
        fail='ERROR 1795 (HY000): FULLTEXT parser leftover ft_article_fts_tmp + fts_00000_aux after INPLACE abort',
        inspect="SELECT INDEX_NAME, INDEX_TYPE FROM information_schema.STATISTICS WHERE TABLE_NAME='ft_article'",
        catalog='FULLTEXT aux leftover; expand body_v2',
        abort='DROP TABLE IF EXISTS search.ft_article_fts_tmp',
        col_type='LONGTEXT',
        lock_fail='ERROR 1205 (HY000): Lock wait timeout exceeded ADD body_v2 on search.ft_article',
    ),
    make_plant(
        engine='sqlite',
        slug='sqlite-fts5-content-leftover',
        plant='sqlite-fts5',
        surface='sqlite-fts5-content',
        table='fts5_body',
        col='text',
        col_v2='text_v2',
        leftover='fts5_body_content',
        leftover2='fts5_body_docsize',
        seed="INSERT INTO fts5_body(fts5_body) VALUES('rebuild')",
        fail='SQL logic error: FTS5 content leftover fts5_body_content + fts5_body_docsize after failed rebuild; skip rewrite',
        inspect="SELECT name FROM sqlite_master WHERE name LIKE 'fts5_body%'",
        catalog='FTS5 content/docsize leftover; expand text_v2',
        abort='DROP TABLE IF EXISTS fts5_body_content',
        col_type='TEXT',
        lock_fail='Error: database is locked ADD text_v2 on fts5_body',
        db='fts5.db',
    ),
    make_plant(
        engine='mssql',
        slug='mssql-columnstore-rebuild-leftover',
        plant='mssql-columnstore',
        surface='mssql-columnstore-rebuild',
        table='analytics.cs_event',
        col='payload',
        col_v2='payload_v2',
        leftover='cs_event_delta_store',
        leftover2='cs_event_rowgroup_tmp',
        seed='ALTER INDEX CCI_cs_event ON analytics.cs_event REBUILD WITH (ONLINE=ON)',
        fail='Msg 35377: COLUMNSTORE rebuild leftover cs_event_delta_store + cs_event_rowgroup_tmp',
        inspect="SELECT name, type_desc FROM sys.indexes WHERE object_id=OBJECT_ID('analytics.cs_event')",
        catalog='columnstore delta leftover; expand payload_v2',
        abort='DROP TABLE analytics.cs_event_rowgroup_tmp',
        col_type='NVARCHAR(MAX)',
        lock_fail='Msg 1222: Lock request time out period exceeded ADD payload_v2 on analytics.cs_event',
    ),
    make_plant(
        engine='mariadb',
        slug='mariadb-system-versioned-leftover',
        plant='maria-sysver',
        surface='mariadb-system-versioned',
        table='hist.sysver_sku',
        col='sku',
        col_v2='sku_norm',
        leftover='sysver_sku_history',
        leftover2='sysver_sku_vers_tmp',
        seed='ALTER TABLE hist.sysver_sku ADD SYSTEM VERSIONING',
        fail='ERROR 4119 (HY000): SYSTEM VERSIONING leftover sysver_sku_history + sysver_sku_vers_tmp after failed ALTER',
        inspect="SELECT TABLE_NAME, TABLE_TYPE FROM information_schema.TABLES WHERE TABLE_NAME LIKE 'sysver_sku%'",
        catalog='MariaDB system-versioned leftover history; expand sku_norm',
        abort='ALTER TABLE hist.sysver_sku DROP SYSTEM VERSIONING',
        col_type='VARCHAR(191)',
    ),
    make_plant(
        engine='mysql',
        slug='mysql-invisible-column-leftover',
        plant='mysql-invis-col',
        surface='mysql-invisible-column',
        table='users.invisible_email',
        col='email',
        col_v2='email_v2',
        leftover='invisible_email_inv_tmp',
        leftover2='invisible_email_frm',
        seed='ALTER TABLE users.invisible_email ALTER COLUMN email SET INVISIBLE',
        fail='ERROR 3956 (HY000): INVISIBLE column leftover invisible_email_inv_tmp + invisible_email_frm after failed INSTANT; skip in-place',
        inspect="SELECT COLUMN_NAME, EXTRA FROM information_schema.COLUMNS WHERE TABLE_NAME='invisible_email'",
        catalog='INVISIBLE column leftover frm/tmp; expand email_v2',
        abort='DROP TABLE IF EXISTS users.invisible_email_inv_tmp',
        col_type='VARCHAR(320)',
        lock_fail='ERROR 1205 (HY000): Lock wait timeout exceeded ADD email_v2 on users.invisible_email',
    ),
    make_plant(
        engine='sqlite',
        slug='sqlite-without-rowid-rebuild-leftover',
        plant='sqlite-worowid',
        surface='sqlite-without-rowid',
        table='worowid_kv',
        col='val',
        col_v2='val_v2',
        leftover='worowid_kv_new',
        leftover2='sqlite_autoindex_worowid_kv_1',
        seed='CREATE TABLE worowid_kv_new (k TEXT PRIMARY KEY, val TEXT) WITHOUT ROWID',
        fail='NOTICE: already skip: WITHOUT ROWID rebuild leftover worowid_kv_new + sqlite_autoindex_worowid_kv_1',
        inspect="SELECT name, sql FROM sqlite_master WHERE name LIKE 'worowid_kv%'",
        catalog='WITHOUT ROWID leftover _new; expand val_v2',
        abort='DROP TABLE IF EXISTS worowid_kv_new',
        col_type='TEXT',
        lock_fail='Error: database is locked ADD val_v2 on worowid_kv',
        db='worowid.db',
    ),
    make_plant(
        engine='mssql',
        slug='mssql-filtered-index-leftover',
        plant='mssql-filtered',
        surface='mssql-filtered-index',
        table='shop.filtered_ix_order',
        col='sku',
        col_v2='sku_norm',
        leftover='filtered_ix_order_ix_tmp',
        leftover2='filtered_ix_order_flt',
        seed="CREATE INDEX IX_filtered_ix_order_open ON shop.filtered_ix_order(sku) WHERE status='open' WITH (ONLINE=ON)",
        fail='Msg 10609: filtered index leftover filtered_ix_order_ix_tmp + filtered_ix_order_flt after ONLINE rebuild abort',
        inspect="SELECT name, has_filter, filter_definition FROM sys.indexes WHERE object_id=OBJECT_ID('shop.filtered_ix_order')",
        catalog='filtered index leftover; expand sku_norm',
        abort='DROP INDEX IX_filtered_ix_order_open ON shop.filtered_ix_order',
        col_type='NVARCHAR(191)',
        lock_fail='Msg 1222: Lock request time out period exceeded ADD sku_norm on shop.filtered_ix_order',
    ),
    make_plant(
        engine='oracle',
        slug='oracle-virtual-column-leftover',
        plant='oracle-virtcol',
        surface='oracle-virtual-column',
        table='finance.virt_col_invoice',
        col='total',
        col_v2='total_v2',
        leftover='VIRT_COL_INVOICE_VC_TMP',
        leftover2='SYS_C00_VIRT',
        seed='ALTER TABLE finance.virt_col_invoice ADD (total_gen NUMBER GENERATED ALWAYS AS (net+tax) VIRTUAL)',
        fail='ORA-54013: virtual column leftover VIRT_COL_INVOICE_VC_TMP + SYS_C00_VIRT; skip in-place rewrite',
        inspect="SELECT column_name, virtual_column FROM user_tab_cols WHERE table_name='VIRT_COL_INVOICE'",
        catalog='virtual column leftover; expand total_v2',
        abort='DROP TABLE finance.VIRT_COL_INVOICE_VC_TMP',
        col_type='NUMBER(18,4)',
        lock_fail='ORA-00054: resource busy and acquire with NOWAIT specified ADD total_v2 on finance.virt_col_invoice',
    ),
    make_plant(
        engine='mysql',
        slug='mysql-functional-index-leftover',
        plant='mysql-func-idx',
        surface='mysql-functional-index',
        table='catalog.func_idx_sku',
        col='sku',
        col_v2='sku_norm',
        leftover='func_idx_sku_hidden_gc',
        leftover2='func_idx_sku_idx_tmp',
        seed='ALTER TABLE catalog.func_idx_sku ADD INDEX idx_sku_lower ((LOWER(sku)))',
        fail='ERROR 3758 (HY000): functional index hidden generated leftover func_idx_sku_hidden_gc + func_idx_sku_idx_tmp',
        inspect="SELECT INDEX_NAME, EXPRESSION FROM information_schema.STATISTICS WHERE TABLE_NAME='func_idx_sku'",
        catalog='functional index hidden GC leftover; expand sku_norm',
        abort='DROP TABLE IF EXISTS catalog.func_idx_sku_idx_tmp',
        col_type='VARCHAR(191)',
        lock_fail='ERROR 1205 (HY000): Lock wait timeout exceeded ADD sku_norm on catalog.func_idx_sku',
    ),
    make_plant(
        engine='sqlite',
        slug='sqlite-generated-always-leftover',
        plant='sqlite-gen-always',
        surface='sqlite-generated-always',
        table='gen_always_qty',
        col='qty',
        col_v2='qty_v2',
        leftover='sqlite_gen_always_qty_new',
        leftover2='gen_always_qty_old',
        seed='ALTER TABLE gen_always_qty ADD COLUMN qty_gen INTEGER GENERATED ALWAYS AS (qty_base * 2) STORED',
        fail='generated always leftover sqlite_gen_always_qty_new + gen_always_qty_old after table rewrite abort',
        inspect="SELECT name, sql FROM sqlite_master WHERE name LIKE 'gen_always_qty%'",
        catalog='GENERATED ALWAYS leftover rewrite tmp; expand qty_v2',
        abort='DROP TABLE IF EXISTS sqlite_gen_always_qty_new',
        col_type='INTEGER',
        lock_fail='Error: database is locked ADD qty_v2 on gen_always_qty',
        db='genqty.db',
    ),
    make_plant(
        engine='mysql',
        slug='mysql-partition-exchange-leftover',
        plant='mysql-exch-part',
        surface='mysql-partition-exchange',
        table='shop.exch_part_sku',
        col='sku',
        col_v2='sku_norm',
        leftover='exch_part_sku_p2024',
        leftover2='exch_part_sku_ex',
        seed='ALTER TABLE shop.exch_part_sku EXCHANGE PARTITION p2024 WITH TABLE shop.exch_part_sku_ex',
        fail='ERROR 1735 (HY000): EXCHANGE PARTITION leftover exch_part_sku_p2024 + exch_part_sku_ex after failed swap',
        inspect="SELECT PARTITION_NAME, TABLE_ROWS FROM information_schema.PARTITIONS WHERE TABLE_NAME='exch_part_sku'",
        catalog='EXCHANGE PARTITION leftover staging; expand sku_norm',
        abort='DROP TABLE IF EXISTS shop.exch_part_sku_ex',
        col_type='VARCHAR(191)',
        lock_fail='ERROR 1205 (HY000): Lock wait timeout exceeded ADD sku_norm on shop.exch_part_sku',
    ),
    make_plant(
        engine='mssql',
        slug='mssql-partition-switch-leftover',
        plant='mssql-switch',
        surface='mssql-partition-switch',
        table='warehouse.switch_part_fact',
        col='units',
        col_v2='units_v2',
        leftover='switch_part_fact_stg',
        leftover2='switch_part_fact_p2024',
        seed='ALTER TABLE warehouse.switch_part_fact SWITCH PARTITION 2024 TO warehouse.switch_part_fact_stg',
        fail='Msg 4972: SWITCH PARTITION leftover switch_part_fact_stg + switch_part_fact_p2024',
        inspect="SELECT p.partition_number, p.rows FROM sys.partitions p WHERE p.object_id=OBJECT_ID('warehouse.switch_part_fact')",
        catalog='SWITCH leftover staging partition; expand units_v2',
        abort='TRUNCATE TABLE warehouse.switch_part_fact_stg',
        col_type='BIGINT',
        lock_fail='Msg 1222: Lock request time out period exceeded ADD units_v2 on warehouse.switch_part_fact',
    ),
    make_plant(
        engine='mysql',
        slug='mysql-autoinc-counter-leftover',
        plant='mysql-autoinc',
        surface='mysql-autoinc-counter',
        table='catalog.autoinc_ticket',
        col='code',
        col_v2='code_v2',
        leftover='autoinc_ticket_ai_tmp',
        leftover2='autoinc_ticket_ibd',
        seed='ALTER TABLE catalog.autoinc_ticket AUTO_INCREMENT=5000000, ALGORITHM=COPY',
        fail='ERROR 1467 (HY000): AUTO_INCREMENT leftover autoinc_ticket_ai_tmp + autoinc_ticket_ibd after failed COPY',
        inspect="SELECT AUTO_INCREMENT FROM information_schema.TABLES WHERE TABLE_NAME='autoinc_ticket'",
        catalog='AUTO_INCREMENT COPY leftover ibd/tmp; expand code_v2',
        abort='DROP TABLE IF EXISTS catalog.autoinc_ticket_ai_tmp',
        col_type='VARCHAR(64)',
        lock_fail='ERROR 1205 (HY000): Lock wait timeout exceeded ADD code_v2 on catalog.autoinc_ticket',
    ),
    make_plant(
        engine='sqlite',
        slug='sqlite-sqlite-sequence-leftover',
        plant='sqlite-sequence',
        surface='sqlite-sqlite-sequence',
        table='seq_rowid',
        col='label',
        col_v2='label_v2',
        leftover='sqlite_sequence',
        leftover2='seq_rowid_old',
        seed="UPDATE sqlite_sequence SET seq=900000 WHERE name='seq_rowid'",
        fail='UNIQUE constraint sqlite_sequence leftover sqlite_sequence + seq_rowid_old after rewrite abort',
        inspect="SELECT name, seq FROM sqlite_sequence WHERE name='seq_rowid'",
        catalog='sqlite_sequence leftover after rewrite abort; expand label_v2',
        abort="DELETE FROM sqlite_sequence WHERE name='seq_rowid_old'",
        col_type='TEXT',
        lock_fail='Error: database is locked ADD label_v2 on seq_rowid',
        db='seq.db',
    ),
    make_plant(
        engine='mssql',
        slug='mssql-dynamic-data-mask-leftover',
        plant='mssql-mask',
        surface='mssql-dynamic-mask',
        table='pii.masked_ssn',
        col='ssn',
        col_v2='ssn_v2',
        leftover='masked_ssn_mask_tmp',
        leftover2='masked_ssn_sec',
        seed='ALTER TABLE pii.masked_ssn ALTER COLUMN ssn ADD MASKED WITH (FUNCTION=\'partial(0,"XXX-XX-",4)\')',
        fail='Msg 33522: MASKED leftover masked_ssn_mask_tmp + masked_ssn_sec after failed ALTER COLUMN',
        inspect="SELECT c.name, c.is_masked FROM sys.columns c WHERE c.object_id=OBJECT_ID('pii.masked_ssn')",
        catalog='dynamic data mask leftover; expand ssn_v2',
        abort='DROP TABLE pii.masked_ssn_mask_tmp',
        col_type='NVARCHAR(11)',
        lock_fail='Msg 1222: Lock request time out period exceeded ADD ssn_v2 on pii.masked_ssn',
    ),
    make_plant(
        engine='oracle',
        slug='oracle-editioning-view-leftover',
        plant='oracle-edition',
        surface='oracle-editioning-view',
        table='app.edition_view_item',
        col='body',
        col_v2='body_v2',
        leftover='EDITION_VIEW_ITEM_EV',
        leftover2='EDITION_VIEW_ITEM_AE',
        seed='CREATE OR REPLACE EDITIONING VIEW app.edition_view_item_ev AS SELECT * FROM app.edition_view_item',
        fail='ORA-38812: editioning view leftover EDITION_VIEW_ITEM_EV + EDITION_VIEW_ITEM_AE; skip in-place',
        inspect="SELECT view_name, editioning_view FROM user_views WHERE view_name LIKE 'EDITION_VIEW_ITEM%'",
        catalog='editioning view leftover; expand body_v2',
        abort='DROP VIEW app.EDITION_VIEW_ITEM_EV',
        col_type='CLOB',
        lock_fail='ORA-00054: resource busy and acquire with NOWAIT specified ADD body_v2 on app.edition_view_item',
    ),
]

bind_import_twin(__name__)
