#!/usr/bin/env python3
"""DB-mill plant catalog part 2 (30 of 88 plants, AST-extracted).

Canonical regeneration of the legacy ``unique_db_migration_repair_mill``
``PLANTS`` slice: values preserved, formatting canonical. Each entry is a
:func:`plant.make_plant` call with fixed keyword order so diffs are
meaningful. No I/O, no execution on import.
"""

from __future__ import annotations

from .plant import make_plant
from .import_twins import bind_import_twin

__all__ = ["PLANTS_02"]

PLANTS_02 = [
    make_plant(
        engine='mysql',
        slug='mysql-check-constraint-leftover',
        plant='mysql-check',
        surface='mysql-check-constraint',
        table='catalog.check_amount',
        col='amount',
        col_v2='amount_v2',
        leftover='check_amount_chk_tmp',
        leftover2='check_amount_chk1',
        seed='ALTER TABLE catalog.check_amount ADD CONSTRAINT check_amount_chk1 CHECK (amount >= 0)',
        fail='ERROR 3819 (HY000): CHECK leftover check_amount_chk_tmp + check_amount_chk1 after failed ADD CONSTRAINT (existing rows violate)',
        inspect="SELECT CONSTRAINT_NAME, CHECK_CLAUSE FROM information_schema.CHECK_CONSTRAINTS WHERE CONSTRAINT_NAME LIKE 'check_amount%'",
        catalog='CHECK constraint leftover after failed ADD; expand amount_v2',
        abort='ALTER TABLE catalog.check_amount DROP CHECK check_amount_chk1',
        col_type='DECIMAL(12,4)',
        lock_fail='ERROR 1205 (HY000): Lock wait timeout exceeded ADD amount_v2 on catalog.check_amount',
    ),
    make_plant(
        engine='mariadb',
        slug='mariadb-sequence-leftover',
        plant='maria-seq',
        surface='mariadb-sequence',
        table='billing.maria_seq_pay',
        col='ref',
        col_v2='ref_v2',
        leftover='maria_seq_pay_s',
        leftover2='maria_seq_pay_tmp',
        seed='CREATE SEQUENCE billing.maria_seq_pay_s START WITH 1000 INCREMENT BY 1',
        fail='ERROR 4089 (HY000): SEQUENCE leftover maria_seq_pay_s + maria_seq_pay_tmp after failed CREATE SEQUENCE in txn',
        inspect="SELECT SEQUENCE_NAME FROM information_schema.SEQUENCES WHERE SEQUENCE_NAME LIKE 'maria_seq_pay%'",
        catalog='MariaDB SEQUENCE leftover; expand ref_v2',
        abort='DROP SEQUENCE IF EXISTS billing.maria_seq_pay_s',
        col_type='VARCHAR(64)',
    ),
    make_plant(
        engine='mssql',
        slug='mssql-ledger-digest-leftover',
        plant='mssql-ledger',
        surface='mssql-ledger-digest',
        table='audit.ledger_digest',
        col='hash',
        col_v2='hash_v2',
        leftover='ledger_digest_hist',
        leftover2='ledger_digest_view',
        seed='ALTER TABLE audit.ledger_digest SET (LEDGER = ON (APPEND_ONLY = ON))',
        fail='Msg 37319: LEDGER leftover ledger_digest_hist + ledger_digest_view after failed ALTER',
        inspect="SELECT name, is_ledger_on FROM sys.tables WHERE name='ledger_digest'",
        catalog='ledger digest leftover hist/view; expand hash_v2',
        abort='DROP VIEW audit.ledger_digest_view',
        col_type='VARBINARY(32)',
        lock_fail='Msg 1222: Lock request time out period exceeded ADD hash_v2 on audit.ledger_digest',
    ),
    make_plant(
        engine='mysql',
        slug='mysql-srid-spatial-leftover',
        plant='mysql-srid',
        surface='mysql-srid-spatial',
        table='geo.srid_point',
        col='loc',
        col_v2='loc_v2',
        leftover='srid_point_sp_tmp',
        leftover2='srid_point_idx',
        seed='ALTER TABLE geo.srid_point MODIFY loc POINT NOT NULL SRID 4326',
        fail='ERROR 3033 (HY000): SRID mismatch leftover srid_point_sp_tmp + srid_point_idx',
        inspect="SELECT COLUMN_NAME, SRS_ID FROM information_schema.ST_GEOMETRY_COLUMNS WHERE TABLE_NAME='srid_point'",
        catalog='SRID spatial leftover idx/tmp; expand loc_v2',
        abort='DROP TABLE IF EXISTS geo.srid_point_sp_tmp',
        col_type='POINT',
        lock_fail='ERROR 1205 (HY000): Lock wait timeout exceeded ADD loc_v2 on geo.srid_point',
    ),
    make_plant(
        engine='sqlite',
        slug='sqlite-rtree-aux-leftover',
        plant='sqlite-rtree',
        surface='sqlite-rtree-aux',
        table='rtree_box',
        col='geom',
        col_v2='geom_v2',
        leftover='rtree_box_node',
        leftover2='rtree_box_parent',
        seed="INSERT INTO rtree_box(rtree_box, rank) VALUES('rebuild', 0)",
        fail='rtree aux leftover rtree_box_node + rtree_box_parent after failed virtual table rebuild',
        inspect="SELECT name FROM sqlite_master WHERE name LIKE 'rtree_box%'",
        catalog='R-tree node/parent leftover; expand geom_v2',
        abort='DROP TABLE IF EXISTS rtree_box_node',
        col_type='TEXT',
        lock_fail='Error: database is locked ADD geom_v2 on rtree_box',
        db='rtree.db',
    ),
    make_plant(
        engine='oracle',
        slug='oracle-deferred-segment-leftover',
        plant='oracle-defseg',
        surface='oracle-deferred-segment',
        table='dwh.deferred_seg',
        col='payload',
        col_v2='payload_v2',
        leftover='DEFERRED_SEG_TMP',
        leftover2='DEFERRED_SEG_SEG$',
        seed='ALTER TABLE dwh.deferred_seg ALLOCATE EXTENT',
        fail='ORA-14223: deferred segment leftover DEFERRED_SEG_TMP + DEFERRED_SEG_SEG$; skip in-place rewrite',
        inspect="SELECT table_name, segment_created FROM user_tables WHERE table_name='DEFERRED_SEG'",
        catalog='deferred segment leftover SEG$; expand payload_v2',
        abort='DROP TABLE dwh.DEFERRED_SEG_TMP',
        col_type='BLOB',
        lock_fail='ORA-00054: resource busy and acquire with NOWAIT specified ADD payload_v2 on dwh.deferred_seg',
    ),
    make_plant(
        engine='crdb',
        slug='crdb-schema-locked-leftover',
        plant='crdb-schema-lock',
        surface='crdb-schema-locked',
        table='shop.locked_sku',
        col='sku',
        col_v2='sku_norm',
        leftover='locked_sku_schema_locked',
        leftover2='locked_sku_mvcc_tmp',
        seed='ALTER TABLE shop.locked_sku SET (schema_locked = true)',
        fail='ERROR: table shop.locked_sku is schema_locked; leftover locked_sku_schema_locked + locked_sku_mvcc_tmp',
        inspect='SHOW CREATE TABLE shop.locked_sku',
        catalog='schema_locked leftover; expand sku_norm',
        abort='ALTER TABLE shop.locked_sku SET (schema_locked = false)',
        col_type='STRING',
        lock_fail='pq: lock timeout ADD sku_norm on shop.locked_sku',
    ),
    make_plant(
        engine='crdb',
        slug='crdb-not-visible-index-leftover',
        plant='crdb-nvis-idx',
        surface='crdb-not-visible-index',
        table='shop.nvis_order',
        col='qty',
        col_v2='qty_v2',
        leftover='nvis_order_idx_not_visible',
        leftover2='nvis_order_tmp',
        seed='CREATE INDEX nvis_order_idx ON shop.nvis_order (qty) NOT VISIBLE',
        fail='ERROR: NOT VISIBLE index leftover nvis_order_idx_not_visible + nvis_order_tmp after failed CREATE INDEX',
        inspect='SHOW INDEX FROM shop.nvis_order',
        catalog='NOT VISIBLE index leftover; expand qty_v2',
        abort='DROP INDEX IF EXISTS nvis_order_idx',
        col_type='INT8',
        lock_fail='pq: lock timeout ADD qty_v2 on shop.nvis_order',
    ),
    make_plant(
        engine='mysql',
        slug='mysql-ptosc-trigger-leftover',
        plant='mysql-ptosc',
        surface='mysql-ptosc-trigger',
        table='shop.ptosc_item',
        col='sku',
        col_v2='sku_norm',
        leftover='_ptosc_item_new',
        leftover2='pt_osc_ptosc_item_ins',
        seed="pt-online-schema-change --alter 'CHANGE sku sku VARCHAR(191)' D=shop,t=ptosc_item --execute",
        fail='pt-online-schema-change abort leftover _ptosc_item_new + pt_osc_ptosc_item_ins trigger; skip in-place',
        inspect="SHOW TRIGGERS FROM shop LIKE 'ptosc_item%'",
        catalog='pt-osc leftover _new + triggers; expand sku_norm',
        abort='DROP TRIGGER IF EXISTS shop.pt_osc_ptosc_item_ins; DROP TABLE IF EXISTS shop._ptosc_item_new',
        col_type='VARCHAR(191)',
        lock_fail='ERROR 1205 (HY000): Lock wait timeout exceeded ADD sku_norm on shop.ptosc_item',
    ),
    make_plant(
        engine='mysql',
        slug='mysql-ghost-cutover-leftover',
        plant='mysql-ghost',
        surface='mysql-ghost-cutover',
        table='shop.ghost_item',
        col='body',
        col_v2='body_v2',
        leftover='_ghost_item_gho',
        leftover2='_ghost_item_del',
        seed="gh-ost --alter='CHANGE body body LONGBLOB' --database=shop --table=ghost_item --execute",
        fail='gh-ost cutover abort leftover _ghost_item_gho + _ghost_item_del; skip in-place rewrite',
        inspect="SHOW TABLES FROM shop LIKE '%ghost_item%'",
        catalog='gh-ost leftover _gho/_del; expand body_v2',
        abort='DROP TABLE IF EXISTS shop._ghost_item_gho; DROP TABLE IF EXISTS shop._ghost_item_del',
        col_type='LONGBLOB',
        lock_fail='ERROR 1205 (HY000): Lock wait timeout exceeded ADD body_v2 on shop.ghost_item',
    ),
    make_plant(
        engine='mysql',
        slug='mysql-histogram-stats-leftover',
        plant='mysql-histogram',
        surface='mysql-histogram-stats',
        table='catalog.hist_sku',
        col='price',
        col_v2='price_v2',
        leftover='hist_sku_buckets',
        leftover2='hist_sku_stats_tmp',
        seed='ANALYZE TABLE catalog.hist_sku UPDATE HISTOGRAM ON price WITH 64 BUCKETS',
        fail='ERROR 3997 (HY000): histogram leftover hist_sku_buckets + hist_sku_stats_tmp after failed ANALYZE; skip in-place rewrite',
        inspect="SELECT TABLE_NAME, COLUMN_NAME, JSON_LENGTH(HISTOGRAM) FROM information_schema.COLUMN_STATISTICS WHERE TABLE_NAME='hist_sku'",
        catalog='histogram bucket leftover; expand price_v2',
        abort='ANALYZE TABLE catalog.hist_sku DROP HISTOGRAM ON price',
        col_type='DECIMAL(12,4)',
        lock_fail='ERROR 1205 (HY000): Lock wait timeout exceeded ADD price_v2 on catalog.hist_sku',
    ),
    make_plant(
        engine='sqlite',
        slug='sqlite-partial-index-leftover',
        plant='sqlite-partial-idx',
        surface='sqlite-partial-index',
        table='partial_order',
        col='sku',
        col_v2='sku_norm',
        leftover='idx_partial_order_open',
        leftover2='partial_order_idx_tmp',
        seed="CREATE INDEX idx_partial_order_open ON partial_order(sku) WHERE status='open'",
        fail='NOTICE: already skip: partial index leftover idx_partial_order_open + partial_order_idx_tmp after failed CREATE INDEX',
        inspect="SELECT name, sql FROM sqlite_master WHERE name LIKE 'partial_order%'",
        catalog='partial index leftover; expand sku_norm',
        abort='DROP INDEX IF EXISTS idx_partial_order_open',
        col_type='TEXT',
        lock_fail='Error: database is locked ADD sku_norm on partial_order',
        db='partial.db',
    ),
    make_plant(
        engine='mssql',
        slug='mssql-memory-optimized-leftover',
        plant='mssql-memopt',
        surface='mssql-memory-optimized',
        table='hot.memopt_session',
        col='token',
        col_v2='token_v2',
        leftover='memopt_session_xtp_tmp',
        leftover2='memopt_session_hk_file',
        seed='ALTER TABLE hot.memopt_session SET (MEMORY_OPTIMIZED = ON)',
        fail='Msg 12305: MEMORY_OPTIMIZED leftover memopt_session_xtp_tmp + memopt_session_hk_file after failed ALTER',
        inspect="SELECT name, is_memory_optimized FROM sys.tables WHERE name='memopt_session'",
        catalog='In-Memory OLTP leftover XTP file; expand token_v2',
        abort='DROP TABLE hot.memopt_session_xtp_tmp',
        col_type='NVARCHAR(128)',
        lock_fail='Msg 1222: Lock request time out period exceeded ADD token_v2 on hot.memopt_session',
    ),
    make_plant(
        engine='oracle',
        slug='oracle-extended-stats-leftover',
        plant='oracle-extstats',
        surface='oracle-extended-stats',
        table='dwh.ext_stats_dim',
        col='attr',
        col_v2='attr_v2',
        leftover='SYS_STU_EXT_STATS_DIM',
        leftover2='EXT_STATS_DIM_TMP',
        seed="BEGIN DBMS_STATS.CREATE_EXTENDED_STATS('DWH','EXT_STATS_DIM','(ATTR,REGION)'); END;",
        fail='ORA-20000: extended stats leftover SYS_STU_EXT_STATS_DIM + EXT_STATS_DIM_TMP after failed CREATE_EXTENDED_STATS',
        inspect="SELECT extension_name FROM user_stat_extensions WHERE table_name='EXT_STATS_DIM'",
        catalog='extended stats leftover; expand attr_v2',
        abort="BEGIN DBMS_STATS.DROP_EXTENDED_STATS('DWH','EXT_STATS_DIM','(ATTR,REGION)'); END;",
        col_type='VARCHAR2(191)',
        lock_fail='ORA-00054: resource busy and acquire with NOWAIT specified ADD attr_v2 on dwh.ext_stats_dim',
    ),
    make_plant(
        engine='mariadb',
        slug='mariadb-spider-leftover',
        plant='maria-spider',
        surface='mariadb-spider',
        table='fed.spider_sku',
        col='sku',
        col_v2='sku_norm',
        leftover='spider_sku_link',
        leftover2='spider_sku_xa_tmp',
        seed='ALTER TABLE fed.spider_sku ENGINE=SPIDER COMMENT=\'wrapper "mysql", table "sku"\'',
        fail='ERROR 1429 (HY000): SPIDER leftover spider_sku_link + spider_sku_xa_tmp after failed ENGINE swap',
        inspect="SELECT ENGINE, CREATE_OPTIONS FROM information_schema.TABLES WHERE TABLE_NAME='spider_sku'",
        catalog='Spider wrapper leftover XA tmp; expand sku_norm',
        abort='DROP TABLE IF EXISTS fed.spider_sku_xa_tmp',
        col_type='VARCHAR(191)',
    ),
    make_plant(
        engine='mysql',
        slug='mysql-descending-index-leftover',
        plant='mysql-desc-idx',
        surface='mysql-descending-index',
        table='shop.desc_idx_order',
        col='created_at',
        col_v2='created_at_v2',
        leftover='desc_idx_order_desc_tmp',
        leftover2='desc_idx_order_idx',
        seed='ALTER TABLE shop.desc_idx_order ADD INDEX idx_created_desc (created_at DESC)',
        fail='ERROR 1170 (42000): descending index leftover desc_idx_order_desc_tmp + desc_idx_order_idx after failed ADD INDEX',
        inspect="SELECT INDEX_NAME, COLLATION FROM information_schema.STATISTICS WHERE TABLE_NAME='desc_idx_order'",
        catalog='DESC index leftover tmp; expand created_at_v2',
        abort='DROP TABLE IF EXISTS shop.desc_idx_order_desc_tmp',
        col_type='DATETIME(6)',
        lock_fail='ERROR 1205 (HY000): Lock wait timeout exceeded ADD created_at_v2 on shop.desc_idx_order',
    ),
    make_plant(
        engine='sqlite',
        slug='sqlite-trigger-after-leftover',
        plant='sqlite-trig-after',
        surface='sqlite-trigger-after',
        table='trig_audit',
        col='body',
        col_v2='body_v2',
        leftover='trg_trig_audit_ai',
        leftover2='trig_audit_log_tmp',
        seed='CREATE TRIGGER trg_trig_audit_ai AFTER INSERT ON trig_audit BEGIN INSERT INTO trig_audit_log VALUES(new.id); END',
        fail='SQL logic error: AFTER trigger leftover trg_trig_audit_ai + trig_audit_log_tmp after failed CREATE TRIGGER; skip rewrite',
        inspect="SELECT name, sql FROM sqlite_master WHERE type='trigger' AND tbl_name='trig_audit'",
        catalog='AFTER INSERT trigger leftover; expand body_v2',
        abort='DROP TRIGGER IF EXISTS trg_trig_audit_ai',
        col_type='TEXT',
        lock_fail='Error: database is locked ADD body_v2 on trig_audit',
        db='trig.db',
    ),
    make_plant(
        engine='mssql',
        slug='mssql-graph-edge-leftover',
        plant='mssql-graph',
        surface='mssql-graph-edge',
        table='social.graph_follows',
        col='since',
        col_v2='since_v2',
        leftover='graph_follows_edge_tmp',
        leftover2='graph_follows_node_tmp',
        seed='ALTER TABLE social.graph_follows SET (EDGE = ON)',
        fail='Msg 13919: graph EDGE leftover graph_follows_edge_tmp + graph_follows_node_tmp after failed ALTER',
        inspect="SELECT name, is_edge FROM sys.tables WHERE name='graph_follows'",
        catalog='SQL Graph edge leftover; expand since_v2',
        abort='DROP TABLE social.graph_follows_edge_tmp',
        col_type='DATETIME2',
        lock_fail='Msg 1222: Lock request time out period exceeded ADD since_v2 on social.graph_follows',
    ),
    make_plant(
        engine='oracle',
        slug='oracle-matview-rewrite-leftover',
        plant='oracle-mview',
        surface='oracle-matview-rewrite',
        table='dwh.mv_sales_day',
        col='gross',
        col_v2='gross_v2',
        leftover='MV_SALES_DAY_TMP',
        leftover2='MV_SALES_DAY_SNAP$',
        seed='ALTER MATERIALIZED VIEW dwh.mv_sales_day REFRESH FAST ON COMMIT',
        fail='ORA-12034: materialized view log leftover MV_SALES_DAY_TMP + MV_SALES_DAY_SNAP$ after failed REFRESH FAST',
        inspect="SELECT mview_name, rewrite_enabled FROM user_mviews WHERE mview_name='MV_SALES_DAY'",
        catalog='mview rewrite leftover SNAP$; expand gross_v2',
        abort='DROP TABLE dwh.MV_SALES_DAY_TMP',
        col_type='NUMBER(18,4)',
        lock_fail='ORA-00054: resource busy and acquire with NOWAIT specified ADD gross_v2 on dwh.mv_sales_day',
    ),
    make_plant(
        engine='mysql',
        slug='mysql-innodb-encrypt-leftover',
        plant='mysql-encrypt',
        surface='mysql-innodb-encrypt',
        table='pii.encrypt_card',
        col='pan',
        col_v2='pan_v2',
        leftover='encrypt_card_enc_tmp',
        leftover2='encrypt_card_ibd',
        seed="ALTER TABLE pii.encrypt_card ENCRYPTION='Y', ALGORITHM=INPLACE",
        fail='ERROR 3185 (HY000): ENCRYPTION leftover encrypt_card_enc_tmp + encrypt_card_ibd after failed INPLACE',
        inspect="SELECT NAME, ENCRYPTION FROM information_schema.INNODB_TABLESPACES WHERE NAME LIKE 'pii/encrypt_card%'",
        catalog='InnoDB ENCRYPTION leftover ibd/tmp; expand pan_v2',
        abort='DROP TABLE IF EXISTS pii.encrypt_card_enc_tmp',
        col_type='VARBINARY(64)',
        lock_fail='ERROR 1205 (HY000): Lock wait timeout exceeded ADD pan_v2 on pii.encrypt_card',
    ),
    make_plant(
        engine='sqlite',
        slug='sqlite-json-generated-leftover',
        plant='sqlite-json-gen',
        surface='sqlite-json-generated',
        table='json_doc',
        col='doc',
        col_v2='doc_v2',
        leftover='sqlite_json_doc_new',
        leftover2='json_doc_old',
        seed="ALTER TABLE json_doc ADD COLUMN sku TEXT GENERATED ALWAYS AS (json_extract(doc, '$.sku')) VIRTUAL",
        fail='generated json_extract leftover sqlite_json_doc_new + json_doc_old after table rewrite abort; skip in-place',
        inspect="SELECT name, sql FROM sqlite_master WHERE name LIKE 'json_doc%'",
        catalog='JSON generated leftover rewrite tmp; expand doc_v2',
        abort='DROP TABLE IF EXISTS sqlite_json_doc_new',
        col_type='TEXT',
        lock_fail='Error: database is locked ADD doc_v2 on json_doc',
        db='jsondoc.db',
    ),
    make_plant(
        engine='mssql',
        slug='mssql-filestream-leftover',
        plant='mssql-filestream',
        surface='mssql-filestream',
        table='blob.fs_object',
        col='payload',
        col_v2='payload_v2',
        leftover='fs_object_fs_tmp',
        leftover2='fs_object_filetable',
        seed='ALTER TABLE blob.fs_object ADD payload_fs VARBINARY(MAX) FILESTREAM',
        fail='Msg 1969: FILESTREAM leftover fs_object_fs_tmp + fs_object_filetable after failed ADD',
        inspect="SELECT name, is_filestream FROM sys.columns WHERE object_id=OBJECT_ID('blob.fs_object')",
        catalog='FILESTREAM leftover filetable; expand payload_v2',
        abort='DROP TABLE blob.fs_object_fs_tmp',
        col_type='VARBINARY(MAX)',
        lock_fail='Msg 1222: Lock request time out period exceeded ADD payload_v2 on blob.fs_object',
    ),
    make_plant(
        engine='oracle',
        slug='oracle-iot-overflow-leftover',
        plant='oracle-iot',
        surface='oracle-iot-overflow',
        table='erp.iot_overflow_item',
        col='body',
        col_v2='body_v2',
        leftover='SYS_IOT_OVER_ITEM',
        leftover2='IOT_OVERFLOW_ITEM_TMP',
        seed='ALTER TABLE erp.iot_overflow_item MOVE OVERFLOW TABLESPACE overflow_tbs',
        fail='ORA-25191: IOT overflow leftover SYS_IOT_OVER_ITEM + IOT_OVERFLOW_ITEM_TMP after failed MOVE OVERFLOW',
        inspect="SELECT table_name, iot_type FROM user_tables WHERE table_name LIKE 'IOT_OVERFLOW_ITEM%'",
        catalog='IOT overflow leftover; expand body_v2',
        abort='DROP TABLE erp.IOT_OVERFLOW_ITEM_TMP',
        col_type='CLOB',
        lock_fail='ORA-00054: resource busy and acquire with NOWAIT specified ADD body_v2 on erp.iot_overflow_item',
    ),
    make_plant(
        engine='mysql',
        slug='mysql-gtid-purged-leftover',
        plant='mysql-gtid',
        surface='mysql-gtid-purged',
        table='repl.gtid_ticket',
        col='binlog_pos',
        col_v2='binlog_pos_v2',
        leftover='gtid_executed_tmp',
        leftover2='gtid_purged_gap',
        seed="SET GLOBAL gtid_purged='aaaaaaaa-aaaa-aaaa-aaaa-aaaaaaaaaaaa:1-9000'",
        fail='ERROR 3546 (HY000): gtid_purged leftover gtid_executed_tmp + gtid_purged_gap; skip in-place rewrite of binlog_pos',
        inspect='SELECT @@global.gtid_executed, @@global.gtid_purged',
        catalog='gtid_purged leftover gap; expand binlog_pos_v2',
        abort='RESET BINARY LOGS AND GTIDS',
        col_type='VARCHAR(64)',
        lock_fail='ERROR 1205 (HY000): Lock wait timeout exceeded ADD binlog_pos_v2 on repl.gtid_ticket',
    ),
    make_plant(
        engine='sqlite',
        slug='sqlite-pragma-fk-leftover',
        plant='sqlite-pragma-fk',
        surface='sqlite-pragma-fk',
        table='fk_child',
        col='parent_id',
        col_v2='parent_uuid',
        leftover='fk_child_old',
        leftover2='sqlite_autoindex_fk_child_1',
        seed='PRAGMA foreign_keys=OFF; ALTER TABLE fk_child RENAME TO fk_child_old',
        fail='NOTICE: already skip: PRAGMA foreign_keys leftover fk_child_old + sqlite_autoindex_fk_child_1 after rewrite abort',
        inspect='PRAGMA foreign_key_check(fk_child); PRAGMA foreign_keys',
        catalog='PRAGMA foreign_keys leftover old table; expand parent_uuid',
        abort='DROP TABLE IF EXISTS fk_child_old',
        col_type='TEXT',
        lock_fail='Error: database is locked ADD parent_uuid on fk_child',
        db='fkpragma.db',
    ),
    make_plant(
        engine='mssql',
        slug='mssql-change-tracking-leftover',
        plant='mssql-ct',
        surface='mssql-change-tracking',
        table='sync.ct_row',
        col='payload',
        col_v2='payload_v2',
        leftover='change_tracking_ct_row',
        leftover2='ct_row_sys_tmp',
        seed='ALTER TABLE sync.ct_row ENABLE CHANGE_TRACKING WITH (TRACK_COLUMNS_UPDATED = ON)',
        fail='Msg 4997: CHANGE_TRACKING leftover change_tracking_ct_row + ct_row_sys_tmp after failed ENABLE',
        inspect='SELECT t.name, ct.is_track_columns_updated_on FROM sys.change_tracking_tables ct JOIN sys.tables t ON t.object_id=ct.object_id',
        catalog='change tracking leftover; expand payload_v2',
        abort='ALTER TABLE sync.ct_row DISABLE CHANGE_TRACKING',
        col_type='NVARCHAR(MAX)',
        lock_fail='Msg 1222: Lock request time out period exceeded ADD payload_v2 on sync.ct_row',
    ),
    make_plant(
        engine='crdb',
        slug='crdb-hash-sharded-leftover',
        plant='crdb-hashshard',
        surface='crdb-hash-sharded',
        table='shop.hash_sku',
        col='sku',
        col_v2='sku_norm',
        leftover='hash_sku_shard_idx',
        leftover2='hash_sku_crdb_internal_idx',
        seed='CREATE INDEX hash_sku_shard_idx ON shop.hash_sku (sku) USING HASH WITH BUCKET_COUNT = 8',
        fail='ERROR: hash-sharded index leftover hash_sku_shard_idx + hash_sku_crdb_internal_idx after failed CREATE INDEX',
        inspect='SHOW INDEX FROM shop.hash_sku',
        catalog='hash-sharded index leftover; expand sku_norm',
        abort='DROP INDEX IF EXISTS hash_sku_shard_idx',
        col_type='STRING',
        lock_fail='pq: lock timeout ADD sku_norm on shop.hash_sku',
    ),
    make_plant(
        engine='mysql',
        slug='mysql-heatwave-secondary-leftover',
        plant='mysql-heatwave',
        surface='mysql-heatwave-secondary',
        table='analytics.hw_event',
        col='payload',
        col_v2='payload_v2',
        leftover='hw_event_secondary',
        leftover2='hw_event_lakehouse_tmp',
        seed='ALTER TABLE analytics.hw_event SECONDARY_ENGINE=RAPID, SECONDARY_LOAD=1',
        fail='ERROR 3889 (HY000): SECONDARY_ENGINE leftover hw_event_secondary + hw_event_lakehouse_tmp after failed RAPID load',
        inspect="SELECT TABLE_NAME, CREATE_OPTIONS FROM information_schema.TABLES WHERE TABLE_NAME='hw_event'",
        catalog='HeatWave secondary leftover; expand payload_v2',
        abort='ALTER TABLE analytics.hw_event SECONDARY_UNLOAD',
        col_type='JSON',
        lock_fail='ERROR 1205 (HY000): Lock wait timeout exceeded ADD payload_v2 on analytics.hw_event',
    ),
    make_plant(
        engine='sqlite',
        slug='sqlite-schema-cookie-leftover',
        plant='sqlite-schema-ck',
        surface='sqlite-schema-cookie',
        table='cookie_item',
        col='body',
        col_v2='body_v2',
        leftover='cookie_item_old',
        leftover2='sqlite_schema_cookie_bak',
        seed='PRAGMA schema_version=19001',
        fail='NOTICE: already skip: schema cookie leftover cookie_item_old + sqlite_schema_cookie_bak after failed rewrite',
        inspect='PRAGMA schema_version; PRAGMA user_version',
        catalog='schema cookie leftover; expand body_v2',
        abort='DROP TABLE IF EXISTS cookie_item_old',
        col_type='BLOB',
        lock_fail='Error: database is locked ADD body_v2 on cookie_item',
        db='cookie.db',
    ),
    make_plant(
        engine='mssql',
        slug='mssql-cdc-capture-leftover',
        plant='mssql-cdc',
        surface='mssql-cdc-capture',
        table='audit.cdc_event',
        col='payload',
        col_v2='payload_v2',
        leftover='cdc_event_CT',
        leftover2='cdc_capture_job_tmp',
        seed="EXEC sys.sp_cdc_enable_table @source_schema='audit', @source_name='cdc_event', @role_name=NULL",
        fail='Msg 22939: CDC leftover cdc_event_CT + cdc_capture_job_tmp after failed enable_table',
        inspect="SELECT name, is_tracked_by_cdc FROM sys.tables WHERE name='cdc_event'",
        catalog='CDC capture leftover CT table; expand payload_v2',
        abort="EXEC sys.sp_cdc_disable_table @source_schema='audit', @source_name='cdc_event', @capture_instance='audit_cdc_event'",
        col_type='NVARCHAR(MAX)',
        lock_fail='Msg 1222: Lock request time out period exceeded ADD payload_v2 on audit.cdc_event',
    ),
]

bind_import_twin(__name__)
