#!/usr/bin/env python3
"""DB-mill plant catalog part 3 (28 of 88 plants, AST-extracted).

Canonical regeneration of the legacy ``unique_db_migration_repair_mill``
``PLANTS`` slice: values preserved, formatting canonical. Each entry is a
:func:`plant.make_plant` call with fixed keyword order so diffs are
meaningful. No I/O, no execution on import.
"""

from __future__ import annotations

from .plant import make_plant
from .import_twins import bind_import_twin

__all__ = ["PLANTS_03"]

PLANTS_03 = [
    make_plant(
        engine='oracle',
        slug='oracle-invisible-column-leftover',
        plant='oracle-invis-col',
        surface='oracle-invisible-column',
        table='hr.invis_col_emp',
        col='ssn',
        col_v2='ssn_v2',
        leftover='INVIS_COL_EMP_INV_TMP',
        leftover2='SYS_C00_INVIS_EMP',
        seed='ALTER TABLE hr.invis_col_emp MODIFY (ssn INVISIBLE)',
        fail='ORA-54039: invisible column leftover INVIS_COL_EMP_INV_TMP + SYS_C00_INVIS_EMP after failed MODIFY INVISIBLE',
        inspect="SELECT column_name, hidden_column FROM user_tab_cols WHERE table_name='INVIS_COL_EMP'",
        catalog='Oracle invisible column leftover; expand ssn_v2',
        abort='DROP TABLE hr.INVIS_COL_EMP_INV_TMP',
        col_type='VARCHAR2(11)',
        lock_fail='ORA-00054: resource busy and acquire with NOWAIT specified ADD ssn_v2 on hr.invis_col_emp',
    ),
    make_plant(
        engine='mysql',
        slug='mysql-instant-drop-leftover',
        plant='mysql-instant-drop',
        surface='mysql-instant-drop',
        table='shop.instant_drop_sku',
        col='sku',
        col_v2='sku_norm',
        leftover='instant_drop_sku_dropped_cols',
        leftover2='instant_drop_sku_frm_tmp',
        seed='ALTER TABLE shop.instant_drop_sku DROP COLUMN stale_pad, ALGORITHM=INSTANT',
        fail='ERROR 1845 (0A000): INSTANT DROP leftover instant_drop_sku_dropped_cols + instant_drop_sku_frm_tmp; skip in-place rewrite of sku',
        inspect="SELECT NAME, SPACE FROM information_schema.INNODB_TABLESPACES WHERE NAME LIKE 'shop/instant_drop_sku%'",
        catalog='INSTANT DROP leftover hidden cols; expand sku_norm',
        abort='DROP TABLE IF EXISTS shop.instant_drop_sku_frm_tmp',
        col_type='VARCHAR(191)',
        lock_fail='ERROR 1205 (HY000): Lock wait timeout exceeded ADD sku_norm on shop.instant_drop_sku',
    ),
    make_plant(
        engine='sqlite',
        slug='sqlite-autoindex-leftover',
        plant='sqlite-autoindex',
        surface='sqlite-autoindex',
        table='autoindex_sku',
        col='sku',
        col_v2='sku_norm',
        leftover='sqlite_autoindex_autoindex_sku_1',
        leftover2='autoindex_sku_old',
        seed='CREATE UNIQUE INDEX sqlite_autoindex_autoindex_sku_1 ON autoindex_sku(sku)',
        fail='NOTICE: already skip: UNIQUE autoindex leftover sqlite_autoindex_autoindex_sku_1 + autoindex_sku_old after rewrite abort',
        inspect="SELECT name, sql FROM sqlite_master WHERE name LIKE 'autoindex_sku%'",
        catalog='sqlite autoindex leftover; expand sku_norm',
        abort='DROP TABLE IF EXISTS autoindex_sku_old',
        col_type='TEXT',
        lock_fail='Error: database is locked ADD sku_norm on autoindex_sku',
        db='autoindex.db',
    ),
    make_plant(
        engine='mssql',
        slug='mssql-always-encrypted-leftover',
        plant='mssql-ae',
        surface='mssql-always-encrypted',
        table='pii.ae_card',
        col='pan',
        col_v2='pan_v2',
        leftover='ae_card_cek_tmp',
        leftover2='ae_card_cmk',
        seed="ALTER TABLE pii.ae_card ALTER COLUMN pan ADD ENCRYPTED WITH (COLUMN_ENCRYPTION_KEY=cek_ae, ENCRYPTION_TYPE=DETERMINISTIC, ALGORITHM='AEAD_AES_256_CBC_HMAC_SHA_256')",
        fail='Msg 33546: Always Encrypted leftover ae_card_cek_tmp + ae_card_cmk after failed ALTER COLUMN',
        inspect="SELECT name, encryption_type_desc FROM sys.columns WHERE object_id=OBJECT_ID('pii.ae_card')",
        catalog='Always Encrypted leftover CEK; expand pan_v2',
        abort='DROP TABLE pii.ae_card_cek_tmp',
        col_type='NVARCHAR(32)',
        lock_fail='Msg 1222: Lock request time out period exceeded ADD pan_v2 on pii.ae_card',
    ),
    make_plant(
        engine='mysql',
        slug='mysql-row-format-compressed-leftover',
        plant='mysql-rowfmt',
        surface='mysql-row-format-compressed',
        table='cold.rowfmt_blob',
        col='body',
        col_v2='body_v2',
        leftover='rowfmt_blob_cmp_tmp',
        leftover2='rowfmt_blob_ibd',
        seed='ALTER TABLE cold.rowfmt_blob ROW_FORMAT=COMPRESSED, KEY_BLOCK_SIZE=8, ALGORITHM=COPY',
        fail='ERROR 1478 (HY000): ROW_FORMAT=COMPRESSED leftover rowfmt_blob_cmp_tmp + rowfmt_blob_ibd after failed COPY',
        inspect="SELECT NAME, ROW_FORMAT FROM information_schema.INNODB_TABLESPACES WHERE NAME LIKE 'cold/rowfmt_blob%'",
        catalog='compressed row_format leftover ibd/tmp; expand body_v2',
        abort='DROP TABLE IF EXISTS cold.rowfmt_blob_cmp_tmp',
        col_type='LONGBLOB',
        lock_fail='ERROR 1205 (HY000): Lock wait timeout exceeded ADD body_v2 on cold.rowfmt_blob',
    ),
    make_plant(
        engine='sqlite',
        slug='sqlite-check-constraint-leftover',
        plant='sqlite-check',
        surface='sqlite-check-constraint',
        table='check_amt',
        col='amount',
        col_v2='amount_v2',
        leftover='sqlite_check_amt_new',
        leftover2='check_amt_old',
        seed='ALTER TABLE check_amt ADD CONSTRAINT check_amt_pos CHECK (amount >= 0)',
        fail='Parse error: CHECK leftover sqlite_check_amt_new + check_amt_old after table rewrite abort',
        inspect="SELECT name, sql FROM sqlite_master WHERE name LIKE 'check_amt%'",
        catalog='SQLite CHECK leftover rewrite tmp; expand amount_v2',
        abort='DROP TABLE IF EXISTS sqlite_check_amt_new',
        col_type='REAL',
        lock_fail='Error: database is locked ADD amount_v2 on check_amt',
        db='checkamt.db',
    ),
    make_plant(
        engine='mssql',
        slug='mssql-snapshot-isolation-leftover',
        plant='mssql-snapshot',
        surface='mssql-snapshot-isolation',
        table='ops.snap_ticket',
        col='status',
        col_v2='status_v2',
        leftover='snap_ticket_version_chain',
        leftover2='snap_ticket_rowver_tmp',
        seed='ALTER DATABASE ops SET ALLOW_SNAPSHOT_ISOLATION ON',
        fail='Msg 3959: SNAPSHOT leftover snap_ticket_version_chain + snap_ticket_rowver_tmp; skip in-place rewrite of status',
        inspect="SELECT name, snapshot_isolation_state_desc FROM sys.databases WHERE name='ops'",
        catalog='row-version chain leftover; expand status_v2',
        abort='DROP TABLE ops.snap_ticket_rowver_tmp',
        col_type='NVARCHAR(32)',
        lock_fail='Msg 1222: Lock request time out period exceeded ADD status_v2 on ops.snap_ticket',
    ),
    make_plant(
        engine='oracle',
        slug='oracle-result-cache-leftover',
        plant='oracle-rcache',
        surface='oracle-result-cache',
        table='app.rcache_lookup',
        col='payload',
        col_v2='payload_v2',
        leftover='RCACHE_LOOKUP_RC_TMP',
        leftover2='SYS_RC_LOOKUP',
        seed='ALTER TABLE app.rcache_lookup RESULT_CACHE (MODE FORCE)',
        fail='ORA-41365: result cache leftover RCACHE_LOOKUP_RC_TMP + SYS_RC_LOOKUP after failed RESULT_CACHE',
        inspect="SELECT table_name, result_cache FROM user_tables WHERE table_name='RCACHE_LOOKUP'",
        catalog='result cache leftover; expand payload_v2',
        abort='DROP TABLE app.RCACHE_LOOKUP_RC_TMP',
        col_type='CLOB',
        lock_fail='ORA-00054: resource busy and acquire with NOWAIT specified ADD payload_v2 on app.rcache_lookup',
    ),
    make_plant(
        engine='mariadb',
        slug='mariadb-columnstore-plan-leftover',
        plant='maria-cs-plan',
        surface='mariadb-columnstore-plan',
        table='analytics.mcs_event',
        col='payload',
        col_v2='payload_v2',
        leftover='mcs_event_extent',
        leftover2='mcs_event_cpimport_tmp',
        seed='ALTER TABLE analytics.mcs_event ENGINE=ColumnStore',
        fail='ERROR 1815 (HY000): ColumnStore leftover mcs_event_extent + mcs_event_cpimport_tmp after failed ENGINE swap',
        inspect="SELECT ENGINE, CREATE_OPTIONS FROM information_schema.TABLES WHERE TABLE_NAME='mcs_event'",
        catalog='ColumnStore extent leftover; expand payload_v2',
        abort='DROP TABLE IF EXISTS analytics.mcs_event_cpimport_tmp',
        col_type='LONGTEXT',
    ),
    make_plant(
        engine='mysql',
        slug='mysql-ibd-import-leftover',
        plant='mysql-ibd-import',
        surface='mysql-ibd-import',
        table='warehouse.ibd_import_sku',
        col='sku',
        col_v2='sku_norm',
        leftover='ibd_import_sku.cfg',
        leftover2='ibd_import_sku_discard',
        seed='ALTER TABLE warehouse.ibd_import_sku IMPORT TABLESPACE',
        fail='ERROR 1812 (HY000): IMPORT TABLESPACE leftover ibd_import_sku.cfg + ibd_import_sku_discard after failed import',
        inspect="SELECT NAME, SPACE_TYPE FROM information_schema.INNODB_TABLESPACES WHERE NAME LIKE 'warehouse/ibd_import_sku%'",
        catalog='IMPORT TABLESPACE leftover .cfg; expand sku_norm',
        abort='ALTER TABLE warehouse.ibd_import_sku DISCARD TABLESPACE',
        col_type='VARCHAR(191)',
        lock_fail='ERROR 1205 (HY000): Lock wait timeout exceeded ADD sku_norm on warehouse.ibd_import_sku',
    ),
    make_plant(
        engine='sqlite',
        slug='sqlite-wal-autocheckpoint-leftover',
        plant='sqlite-wal-auto',
        surface='sqlite-wal-autocheckpoint',
        table='auto_wal_doc',
        col='payload',
        col_v2='payload_v2',
        leftover='auto_wal_doc-wal',
        leftover2='auto_wal_doc-shm',
        seed='PRAGMA wal_autocheckpoint=100',
        fail='SQLITE_BUSY: wal_autocheckpoint leftover auto_wal_doc-wal + auto_wal_doc-shm; skip in-place rewrite',
        inspect='PRAGMA journal_mode; PRAGMA wal_autocheckpoint',
        catalog='wal_autocheckpoint leftover wal/shm; expand payload_v2',
        abort='PRAGMA wal_checkpoint(PASSIVE)',
        col_type='TEXT',
        lock_fail='Error: database is locked ADD payload_v2 on auto_wal_doc',
        db='autowal.db',
    ),
    make_plant(
        engine='mssql',
        slug='mssql-synonym-target-leftover',
        plant='mssql-synonym',
        surface='mssql-synonym-target',
        table='app.syn_item',
        col='body',
        col_v2='body_v2',
        leftover='syn_item_syn',
        leftover2='syn_item_target_tmp',
        seed='CREATE SYNONYM app.syn_item_syn FOR app.syn_item',
        fail='Msg 2714: synonym leftover syn_item_syn + syn_item_target_tmp after failed CREATE SYNONYM; skip in-place',
        inspect="SELECT name, base_object_name FROM sys.synonyms WHERE name='syn_item_syn'",
        catalog='synonym leftover; expand body_v2',
        abort='DROP SYNONYM app.syn_item_syn',
        col_type='NVARCHAR(MAX)',
        lock_fail='Msg 1222: Lock request time out period exceeded ADD body_v2 on app.syn_item',
    ),
    make_plant(
        engine='crdb',
        slug='crdb-ttl-job-leftover',
        plant='crdb-ttl',
        surface='crdb-ttl-job',
        table='ops.ttl_session',
        col='payload',
        col_v2='payload_v2',
        leftover='ttl_session_job',
        leftover2='ttl_session_span_tmp',
        seed="ALTER TABLE ops.ttl_session SET (ttl = '24h')",
        fail='ERROR: row-level TTL leftover ttl_session_job + ttl_session_span_tmp after failed SET ttl',
        inspect='SHOW CREATE TABLE ops.ttl_session',
        catalog='TTL job leftover; expand payload_v2',
        abort='ALTER TABLE ops.ttl_session RESET (ttl)',
        col_type='BYTES',
        lock_fail='pq: lock timeout ADD payload_v2 on ops.ttl_session',
    ),
    make_plant(
        engine='mysql',
        slug='mysql-generated-virtual-leftover',
        plant='mysql-gen-virt',
        surface='mysql-generated-virtual',
        table='catalog.gen_virt_price',
        col='amount',
        col_v2='amount_v2',
        leftover='gen_virt_price_gc_virt',
        leftover2='gen_virt_price_frm',
        seed='ALTER TABLE catalog.gen_virt_price ADD COLUMN gross DECIMAL(12,4) GENERATED ALWAYS AS (amount*1.2) VIRTUAL',
        fail='ERROR 3105 (HY000): VIRTUAL generated leftover gen_virt_price_gc_virt + gen_virt_price_frm after failed ADD',
        inspect="SELECT COLUMN_NAME, EXTRA FROM information_schema.COLUMNS WHERE TABLE_NAME='gen_virt_price'",
        catalog='VIRTUAL generated leftover frm; expand amount_v2',
        abort='DROP TABLE IF EXISTS catalog.gen_virt_price_frm',
        col_type='DECIMAL(12,4)',
        lock_fail='ERROR 1205 (HY000): Lock wait timeout exceeded ADD amount_v2 on catalog.gen_virt_price',
    ),
    make_plant(
        engine='sqlite',
        slug='sqlite-temp-view-leftover',
        plant='sqlite-temp-view',
        surface='sqlite-temp-view',
        table='view_src',
        col='body',
        col_v2='body_v2',
        leftover='temp.view_src_v',
        leftover2='view_src_old',
        seed='CREATE TEMP VIEW view_src_v AS SELECT * FROM view_src',
        fail='NOTICE: already skip: TEMP VIEW leftover temp.view_src_v + view_src_old after rewrite abort',
        inspect="SELECT name, sql FROM sqlite_temp_master WHERE name LIKE 'view_src%'",
        catalog='TEMP VIEW leftover; expand body_v2',
        abort='DROP VIEW IF EXISTS temp.view_src_v',
        col_type='TEXT',
        lock_fail='Error: database is locked ADD body_v2 on view_src',
        db='tempview.db',
    ),
    make_plant(
        engine='mssql',
        slug='mssql-sparse-column-leftover',
        plant='mssql-sparse',
        surface='mssql-sparse-column',
        table='wide.sparse_attr',
        col='flag',
        col_v2='flag_v2',
        leftover='sparse_attr_set_tmp',
        leftover2='sparse_attr_colset',
        seed='ALTER TABLE wide.sparse_attr ALTER COLUMN flag ADD SPARSE',
        fail='Msg 1919: SPARSE leftover sparse_attr_set_tmp + sparse_attr_colset after failed ALTER COLUMN',
        inspect="SELECT name, is_sparse FROM sys.columns WHERE object_id=OBJECT_ID('wide.sparse_attr')",
        catalog='SPARSE column leftover column_set; expand flag_v2',
        abort='DROP TABLE wide.sparse_attr_set_tmp',
        col_type='BIT',
        lock_fail='Msg 1222: Lock request time out period exceeded ADD flag_v2 on wide.sparse_attr',
    ),
    make_plant(
        engine='oracle',
        slug='oracle-bitmap-join-leftover',
        plant='oracle-bmj',
        surface='oracle-bitmap-join',
        table='dwh.bmj_fact',
        col='dim_id',
        col_v2='dim_uuid',
        leftover='BMJ_FACT_BJX',
        leftover2='BMJ_FACT_BJX_TMP',
        seed='CREATE BITMAP INDEX dwh.bmj_fact_bjx ON dwh.bmj_fact(d.region) FROM dwh.bmj_fact f, dwh.bmj_dim d WHERE f.dim_id=d.id',
        fail='ORA-01408: bitmap join leftover BMJ_FACT_BJX + BMJ_FACT_BJX_TMP after failed CREATE BITMAP INDEX',
        inspect="SELECT index_name, index_type FROM user_indexes WHERE table_name='BMJ_FACT'",
        catalog='bitmap join index leftover; expand dim_uuid',
        abort='DROP INDEX dwh.bmj_fact_bjx',
        col_type='VARCHAR2(36)',
        lock_fail='ORA-00054: resource busy and acquire with NOWAIT specified ADD dim_uuid on dwh.bmj_fact',
    ),
    make_plant(
        engine='mysql',
        slug='mysql-spatial-rtr-leftover',
        plant='mysql-spatial-rtr',
        surface='mysql-spatial-rtr',
        table='geo.rtr_shape',
        col='shape',
        col_v2='shape_v2',
        leftover='rtr_shape_sp_idx',
        leftover2='rtr_shape_mbr_tmp',
        seed='ALTER TABLE geo.rtr_shape ADD SPATIAL INDEX sx_shape (shape)',
        fail='ERROR 3034 (HY000): SPATIAL leftover rtr_shape_sp_idx + rtr_shape_mbr_tmp after failed ADD SPATIAL INDEX',
        inspect="SELECT INDEX_NAME, INDEX_TYPE FROM information_schema.STATISTICS WHERE TABLE_NAME='rtr_shape'",
        catalog='SPATIAL R-tree leftover; expand shape_v2',
        abort='DROP TABLE IF EXISTS geo.rtr_shape_mbr_tmp',
        col_type='GEOMETRY',
        lock_fail='ERROR 1205 (HY000): Lock wait timeout exceeded ADD shape_v2 on geo.rtr_shape',
    ),
    make_plant(
        engine='sqlite',
        slug='sqlite-attach-schema-leftover',
        plant='sqlite-attach',
        surface='sqlite-attach-schema',
        table='main.attach_item',
        col='body',
        col_v2='body_v2',
        leftover='aux.attach_item',
        leftover2='attach_item_old',
        seed="ATTACH DATABASE 'aux.db' AS aux",
        fail='NOTICE: already skip: ATTACH leftover aux.attach_item + attach_item_old after failed rewrite',
        inspect='PRAGMA database_list',
        catalog='ATTACH schema leftover; expand body_v2',
        abort='DETACH DATABASE aux',
        col_type='BLOB',
        lock_fail='Error: database is locked ADD body_v2 on main.attach_item',
        db='attach.db',
    ),
    make_plant(
        engine='mssql',
        slug='mssql-indexed-view-leftover',
        plant='mssql-idxview',
        surface='mssql-indexed-view',
        table='sales.idxview_line',
        col='qty',
        col_v2='qty_v2',
        leftover='idxview_line_v',
        leftover2='idxview_line_v_ix',
        seed='CREATE UNIQUE CLUSTERED INDEX ix_idxview_line_v ON sales.idxview_line_v(line_id)',
        fail='Msg 1934: indexed view leftover idxview_line_v + idxview_line_v_ix after failed CREATE UNIQUE CLUSTERED INDEX',
        inspect="SELECT name, is_indexed_view FROM sys.views WHERE name='idxview_line_v'",
        catalog='indexed view leftover; expand qty_v2',
        abort='DROP INDEX ix_idxview_line_v ON sales.idxview_line_v',
        col_type='BIGINT',
        lock_fail='Msg 1222: Lock request time out period exceeded ADD qty_v2 on sales.idxview_line_v',
    ),
    make_plant(
        engine='mariadb',
        slug='mariadb-atomic-ddl-leftover',
        plant='maria-atomic',
        surface='mariadb-atomic-ddl',
        table='shop.atomic_sku',
        col='sku',
        col_v2='sku_norm',
        leftover='atomic_sku_ddl_log',
        leftover2='atomic_sku_crash_tmp',
        seed='ALTER TABLE shop.atomic_sku FORCE',
        fail='ERROR 1025 (HY000): atomic DDL leftover atomic_sku_ddl_log + atomic_sku_crash_tmp after crash mid-ALTER',
        inspect="SELECT * FROM mysql.innodb_table_stats WHERE table_name='atomic_sku'",
        catalog='atomic DDL crash leftover; expand sku_norm',
        abort='DROP TABLE IF EXISTS shop.atomic_sku_crash_tmp',
        col_type='VARCHAR(191)',
    ),
    make_plant(
        engine='sqlite',
        slug='sqlite-session-changeset-leftover',
        plant='sqlite-session',
        surface='sqlite-session-changeset',
        table='sess_row',
        col='payload',
        col_v2='payload_v2',
        leftover='sess_row_changeset',
        leftover2='sess_row_session_tmp',
        seed="SELECT sqlite3session_changeset('sess_row')",
        fail='SQL logic error: session changeset leftover sess_row_changeset + sess_row_session_tmp after failed apply',
        inspect="SELECT name FROM sqlite_master WHERE name LIKE 'sess_row%'",
        catalog='session changeset leftover; expand payload_v2',
        abort='DROP TABLE IF EXISTS sess_row_session_tmp',
        col_type='BLOB',
        lock_fail='Error: database is locked ADD payload_v2 on sess_row',
        db='session.db',
    ),
    make_plant(
        engine='mssql',
        slug='mssql-security-policy-leftover',
        plant='mssql-rls-pol',
        surface='mssql-security-policy',
        table='tenant.rls_row',
        col='tenant_id',
        col_v2='tenant_uuid',
        leftover='rls_row_policy',
        leftover2='rls_row_pred_fn',
        seed='CREATE SECURITY POLICY tenant.rls_row_policy ADD FILTER PREDICATE tenant.rls_pred(tenant_id) ON tenant.rls_row WITH (STATE = ON)',
        fail='Msg 33224: security policy leftover rls_row_policy + rls_row_pred_fn after failed CREATE SECURITY POLICY',
        inspect="SELECT name, is_enabled FROM sys.security_policies WHERE name='rls_row_policy'",
        catalog='security policy leftover predicate; expand tenant_uuid',
        abort='DROP SECURITY POLICY tenant.rls_row_policy',
        col_type='UNIQUEIDENTIFIER',
        lock_fail='Msg 1222: Lock request time out period exceeded ADD tenant_uuid on tenant.rls_row',
    ),
    make_plant(
        engine='oracle',
        slug='oracle-sql-patch-leftover',
        plant='oracle-sqlpatch',
        surface='oracle-sql-patch',
        table='app.sql_patch_item',
        col='body',
        col_v2='body_v2',
        leftover='SQL_PATCH_ITEM_SP',
        leftover2='SQL_PATCH_ITEM_TMP',
        seed="BEGIN DBMS_SQLDIAG.CREATE_SQL_PATCH(sql_id=>'7xpatch', hint_text=>'INDEX(sql_patch_item)'); END;",
        fail='ORA-13831: SQL patch leftover SQL_PATCH_ITEM_SP + SQL_PATCH_ITEM_TMP after failed CREATE_SQL_PATCH',
        inspect="SELECT name, status FROM dba_sql_patches WHERE name LIKE 'SQL_PATCH_ITEM%'",
        catalog='SQL patch leftover; expand body_v2',
        abort="BEGIN DBMS_SQLDIAG.DROP_SQL_PATCH('SQL_PATCH_ITEM_SP'); END;",
        col_type='CLOB',
        lock_fail='ORA-00054: resource busy and acquire with NOWAIT specified ADD body_v2 on app.sql_patch_item',
    ),
    make_plant(
        engine='crdb',
        slug='crdb-vector-index-leftover',
        plant='crdb-vecidx',
        surface='crdb-vector-index',
        table='search.vec_item',
        col='embed',
        col_v2='embed_v2',
        leftover='vec_item_idx',
        leftover2='vec_item_vec_tmp',
        seed='CREATE VECTOR INDEX vec_item_idx ON search.vec_item (embed)',
        fail='ERROR: vector index leftover vec_item_idx + vec_item_vec_tmp after failed CREATE VECTOR INDEX',
        inspect='SHOW INDEX FROM search.vec_item',
        catalog='vector index leftover; expand embed_v2',
        abort='DROP INDEX IF EXISTS vec_item_idx',
        col_type='VECTOR(768)',
        lock_fail='pq: lock timeout ADD embed_v2 on search.vec_item',
    ),
    make_plant(
        engine='mysql',
        slug='mysql-clone-plugin-leftover',
        plant='mysql-clone',
        surface='mysql-clone-plugin',
        table='ops.clone_ticket',
        col='state',
        col_v2='state_v2',
        leftover='clone_ticket_donor_tmp',
        leftover2='clone_ticket_inprog',
        seed="CLONE INSTANCE FROM 'donor':3306 IDENTIFIED BY 'x' DATA DIRECTORY='/var/lib/mysql-clone'",
        fail='ERROR 3862 (HY000): CLONE leftover clone_ticket_donor_tmp + clone_ticket_inprog; skip in-place rewrite of state',
        inspect='SELECT ID, STATE FROM performance_schema.clone_status',
        catalog='clone plugin leftover in-progress; expand state_v2',
        abort='DROP TABLE IF EXISTS ops.clone_ticket_donor_tmp',
        col_type='VARCHAR(32)',
        lock_fail='ERROR 1205 (HY000): Lock wait timeout exceeded ADD state_v2 on ops.clone_ticket',
    ),
    make_plant(
        engine='sqlite',
        slug='sqlite-rbu-vacuum-leftover',
        plant='sqlite-rbu',
        surface='sqlite-rbu-vacuum',
        table='rbu_item',
        col='body',
        col_v2='body_v2',
        leftover='data_rbu_item',
        leftover2='rbu_state',
        seed="INSERT INTO data_rbu_item(rbu_control, id, body) VALUES(0, 1, X'00')",
        fail='SQL logic error: RBU leftover data_rbu_item + rbu_state after failed incremental vacuum; skip rewrite',
        inspect="SELECT name FROM sqlite_master WHERE name LIKE '%rbu%'",
        catalog='RBU vacuum leftover data_* + rbu_state; expand body_v2',
        abort='DROP TABLE IF EXISTS data_rbu_item',
        col_type='BLOB',
        lock_fail='Error: database is locked ADD body_v2 on rbu_item',
        db='rbu.db',
    ),
    make_plant(
        engine='mssql',
        slug='mssql-external-table-leftover',
        plant='mssql-exttbl',
        surface='mssql-external-table',
        table='lake.ext_fact',
        col='units',
        col_v2='units_v2',
        leftover='ext_fact_ds',
        leftover2='ext_fact_ext',
        seed="CREATE EXTERNAL TABLE lake.ext_fact_ext (units BIGINT) WITH (DATA_SOURCE=ds_lake, LOCATION='/facts')",
        fail='Msg 46526: external table leftover ext_fact_ds + ext_fact_ext after failed CREATE EXTERNAL TABLE',
        inspect="SELECT name, type_desc FROM sys.external_tables WHERE name LIKE 'ext_fact%'",
        catalog='external table leftover; expand units_v2',
        abort='DROP EXTERNAL TABLE lake.ext_fact_ext',
        col_type='BIGINT',
        lock_fail='Msg 1222: Lock request time out period exceeded ADD units_v2 on lake.ext_fact',
    ),
]

bind_import_twin(__name__)
