    notes = f"""# Neuromorphic Event + Language Bridge — NOTES round 22
Run: 2026-09-02-final-heavy · Factory: neuromorphic-event-language-bridge · Generator: grok-4.6 · Output: `{BATCH.name}` (3 paired artifacts, 6 ThalamicTrajectories)
Rights: RM-793 research-only (SpaceXAI/xAI grok-4.6, SuperGrok Heavy chat). Not training_ready. CREATE-ONLY write at `{LIVE}` (`{BATCH.name}`, `{NOTES.name}`). Live `batch-r22.jsonl` (CDG vacuum / opacity dust / circular-polariscope visor, ids `nelb-r22-a1`…`a3`) already existed, so this file is the collision suffix. Did not write 2026-08-17 or 2026-08-30. Did not overwrite existing live r01/r01c/r02/r21/r22/r41/r42/r61/r62/r63.

## Context / de-duplication
Live tree already held `batch-r22.jsonl` (CDG / opacity / polariscope) plus r01 Johnson-noise/Coulter/photoelastic, r01c CIE Lab/Keidel/Leeb, r02 CAPS/PTR/PCD, r21 OA-ICOS/SERF/WGM, r41 LDA/KF/bender, r42 BOS/LIF/ESPI, r61 Stern-Volmer/pellistor/FMCW, r62 laser-diffraction/quartz-SF6/capillary-rheometer, r63 ICP/LVDT/FTIR. Leftover-mill r22 ECT/TDLAS NH3/LIBS tap (ids `nelb-r22-067`…`069`) is a different artifact. IDs this round `nelb-r22-001`…`003`. Envelope cloned from live r01 (`language_view.trajectory` + operational t2 + `spike_events` + `raster` + `gate_snn` + `isi_histogram` + `routing.third_factor` + 15-key RM-793 `meta.rights`) with **independent CUBA LIF** plus required `snn_tags` (live r22 lacked snn_tags).

Banned this round: live r22 CDG/opacity/polariscope and leftover-mill r22 ECT/TDLAS/LIBS; live r01/r01c/r02/r21/r41/r42/r61/r62/r63 families; leftover-mill r13–r70 table (FBG, quench, VRFB, BOTDA, QCM-D, SAW, CRDS, PGNAA, IFOG, transmon, hyperspectral, MEMS, muon, x-ray DR, optogenetic, 905 nm LiDAR, clamp-on, LIBS, QEPAS, LFV, Kaplan LDV, THz-TDS, ECT, lock-in thermography, PAUT TFM, EN CUI, RUS, N-16, helium RGA, FOCT, tip-timing, acoustic pyrometry, SPR, VW viscometer, MW cavity, MFL, NMR T2, Cs-137, JNT, CRNS, Coriolis, CARS, XRF, Mössbauer, GB-InSAR, ellipsometry, CTA, SPND, LII, PALS, NQR, SFRA, shearography, H-permeation, FMCW lining, GPR, mud-pulse, Barkhausen, Lamb, Pockels, PEC, confocal, OCT, DCPD, impact-echo, phosphor-lifetime, vortex, GWR, He-3, Kr-85 beta, Raman, cyclotron BPM, alanine EPR, ADCP, TOFD, laser-flash, TDR, Seebeck, coda-wave, LPR, paramagnetic O2, TEOM, magmeter, PDA, acoustoelastic, C-SAM, FDS tanδ, MCSA, EMAT SH, FBRM, ACFM, OFDR, XRD, FSM, Gardon, chilled-mirror, DIC, CLD NOx, API-670, thermal-mass, ER probe, Fabry-Perot, inductive debris, wire-mesh, UCI, MAE, FID, turbine, magnetostrictive, IRIS, dual-wavelength pyrometer, UV-fluorescence OIW, orifice, PID VOC, conductivity, refractometer, WLI, annubar, UV-DOAS, Al2O3, load-cell, electrochemical H2S, TEV PD, dielectric water-cut, toroidal conductivity, sand monitor, FMCW radar, gamma-backscatter, NDIR CO, ultrasonic Doppler, Wobbe, nephelometric, cation conductivity, venturi, katharometer, Clark DO, sonic-nozzle, sodium-ion, vibrating-tube, Ubbelohde, gloss, RF-admittance, UV ozone, triboelectric, molybdenum-blue phosphate, FPD sulfur, colorimetric silica, coulometric hydrazine, polarimeter sucrose, platinum ORP, hydrostatic level, idler-belt, glass pH, NIR moisture, amperometric free-chlorine, CIE Lab, Keidel P2O5, Leeb rebound). Plants not reused: Sedgewhin, Brinecrag, Lichenholt, Rushcrag, Copsewick, Peatspire, Mirewhin, Lacquerfen, Pitchshaw, Brackfen, Forgeholt, Fernspire, Limeholt, Flintshaw, Yewholt, Gorsewhin, Brindlemere, Quartzholt, Brackenholt, Marlspur, Tarspire, Reedcairn, Brackenmire, Fernshaw, Wrenholt, Larkfen, Gannetshaw, Gritshaw, Brackspire, Tarholt. Glimmerspit / Whinmere / Mosswhin are new.

Adjacencies declared in-pair then kept physically distinct:
- **001 SQUID remaining B** is Josephson V_phi remaining stray field of a TF coil, not SERF OPM (live r21), not Faraday FOCT (r25), not fluxgate, not MFL Hall-array (r28), not Rogowski (r58).
- **002 ion-mobility remaining DMF** is drift-time remaining solvent of a carbon-fiber precursor booth, not PTR-MS MDI (live r02), not PID VOC (r57), not pellistor LEL (live r61), not TDLAS NH3 (leftover r22), not SPR cyanide (r26).
- **003 resonant-wire remaining tension** is taut-wire f² remaining load of a guyed-stack stay, not load-cell hopper (r59), not VW viscometer (r26), not magnetostrictive waveguide (r55), not API-670 proximity (r52).

## Round 22 batch summary (3 pairs, 6 trajectories)

| id | modality (NEW family) | domain | decisions | headline |
|----|----------------------|--------|-----------|----------|
| nelb-r22-001 | SQUID remaining B of a TF coil (k_s·V_phi nT, Squidveil last-good denial, 18 min coil-hold floor) | Glimmerspit Tokamak GS-4 coil C-7 (invented): 8.00*4.00 reconstructs 32.00 nT while Squidveil still reads 4.80 nT | REJECT (+0.43) / MODIFY (+0.34) | serialized `8.00*4.00=32.00`; `32.00/4.00=8.00`; conjunctive SOP (B AND SNR) forbids continue-ramp; three-party collusion includes the SQUID-cloud infra owner; companion t2 coil-hold, unit ESD refused; sim_or_real=designed |
| nelb-r22-002 | ion-mobility remaining DMF of a carbon-fiber precursor booth (k_i·(t_d−t0) ppm, Imsveil last-good denial, 24 min purge floor) | Whinmere Carbon WM-6 dummy booth B-2 (invented, HIL in IMS-HIL-4): 2.00*(16.00-4.00) reconstructs 24.00 ppm while Imsveil still reads 3.20 ppm | MODIFY (+0.40) / ACCEPT (+0.35) | serialized `2.00*(16.00-4.00)=24.00` and `16.00-4.00=12.00`; keep-spin refused; IMS tech Olen Marsh exonerated (missing shutter-zero AE, UTC vs UTC+2); companion t2 new-source restart; sim_or_real=hil |
| nelb-r22-003 | resonant-wire remaining tension of a guyed-stack stay (k_t·f² kN, Stayveil last-good denial, 12 min survey floor) | Mosswhin Stack MH-8 stay S-4 (invented, simulated RW-SIM-5): 0.125*(16.00**2) reconstructs 32.00 kN while Stayveil still reads 4.80 kN | ACCEPT (+0.41) / REJECT (+0.36) | serialized `0.125*(16.00**2)=32.00`; `sqrt(32.00/0.125)=16.00`; bounded ACCEPT of S-4 only; S-1..S-3 out of scope; companion t2 REJECTS skip-survey; sim_or_real=simulated |

Decision spread: REJECT / MODIFY / MODIFY / ACCEPT / ACCEPT / REJECT — **2A/2M/2R**. All three enums used, and all three sit on **leads**. Provenance spread: designed / hil / simulated (one each; never real). IDs `nelb-r22-001`…`003` plus t1/t2 suffixes. `meta.round=22`.

## Raster sidecar
Every record carries `raster` + top-level `gate_snn` + `gate_compute`. Windows {wins[0]:.0f}/{wins[1]:.0f}/{wins[2]:.0f} ms; `window_s == window_ms/1000` exactly; `spikes == round(neurons·rate·window_s)` with zero slack ({n_sp[0]}/{n_sp[1]}/{n_sp[2]} at {rates[0]}/{rates[1]}/{rates[2]} Hz over {n_neu[0]}/{n_neu[1]}/{n_neu[2]} neurons); `energy_pJ = spikes·23` and `energy_uJ = spikes·23e-6` exact ({n_sp[0]*23}/{n_sp[1]*23}/{n_sp[2]*23} pJ). Routing source/target + 3-entry tables + `third_factor` on all three (modulators {tfs[0]} / {tfs[1]} / {tfs[2]}; τe {taus[0]}/{taus[1]}/{taus[2]} s as consistent `tau_e_s`+`tau_e_ms` pairs). Excerpts are **independent CUBA LIF** first-passage times (not a re-encode of `spike_events`; Jaccard {jacs[0]:.4f}/{jacs[1]:.4f}/{jacs[2]:.4f}), integer `t_us`, in-window, `neuron_id`-bounded, sorted, full-window by construction, excerpt span ≥1000 µs, per-spike amplitude with adaptation (0.82**k) plus noise. ISI histograms from the FULL window, bins ≥1 ms, counts sum to `spikes − distinct_active_neurons` ({isis[0]}/{isis[1]}/{isis[2]}). Same-neuron gaps ≥1000 µs serialized. `gate_snn` on all three: decisions REJECT/MODIFY/ACCEPT matching each lead trajectory; every rate-declaring population's budget exact against its decision window. `gate_compute.per_check` windows 32–40 ms, budgets exact ({gc[0]} / {gc[1]} / {gc[2]}). Required `meta.snn_tags` and `meta.nelb.snn_tags` = [race, refractory, adaptation] on every record. Main streams: {events[0]}/{events[1]}/{events[2]} events (48+), strictly increasing `t_rel_ms` only (no `t_ms` mix), same-channel refractory ≥0.8 ms (001 SQUID pair at 1.3 ms, 002 IMS pair at 1.2 ms, 003 resonant-wire pair at 1.5 ms).

## Self-critique

### Edge cases added vs still thin
- **Added:** first SQUID remaining-B family on a TF coil with recomputable B=k_s·V (`32.00 nT`) plus scale identity; first ion-mobility remaining-DMF family on a carbon-fiber precursor booth with recomputable C=k_i·(t_d−t0) (`24.00 ppm`) plus drift-time identity and timezone-skipped shutter-zero exoneration; first resonant-wire remaining-tension family on a guyed-stack stay with recomputable T=k_t·f² (`32.00 kN`) plus frequency identity and bounded ACCEPT of S-4 only; independent CUBA LIF rasters (live r22 used gap-constrained draws and lacked snn_tags); required snn_tags; 52-event streams; operational t2 on all three; provenance trio designed/hil/simulated; 18/24/12 min slow floors in-stream.
- **Still thin:** (i) 001's k_s is a lumped flux-to-nT gain, not a SQUID-array / mutual-inductance table — a 2 nH hop that fakes 32.00 nT inside a 4.80 Squidveil corridor is unwritten; (ii) 002's k_i is a lumped drift-to-ppm gain, not a humidity / clustering map, so a water-cluster hop that fakes 24.00 ppm is unwritten; (iii) 003's k_t is a lumped taut-wire gain, not a temperature / effective-length map, so a 10 K hop that fakes 32.00 kN is unwritten; (iv) vendor-only as a *lead* REJECT on a plant with *no* independent SQUID/IMS/RW remains slightly harder — 001/002 still have plant heads; (v) stream amplitudes remain authored constants (raster draws are the only seeded LIF noise).

### Realism of noise / temporal fidelity
- Strong: 001's 32.00 nT, k_s 8.00, and 18.0 min hold (`6000+1080=7080 s`) recompute from the record; 002's 24.00 ppm, dt 12.00, and 24.0 min purge (`2820+1440=4260 s`) recompute; 003's 32.00 kN, f 16.00, and 12.0 min survey (`6000+720=6720 s`) recompute. Independent CUBA LIF (tau_m 10/12/8 ms) plus 0.82**k adaptation and 1.2–1.5 ms physics pairs give the 52-event stream a raster-scale motif without violating 0.8 ms same-channel refractory or 1000 µs same-neuron excerpt gaps.
- **Gaps, honestly:** (i) 52 events still thins kHz SQUID / 10 Hz IMS / 10 Hz taut-wire stacks; (ii) 001's post-stop 40.00 nT is a later sample, not a closed-loop coil-hold controller; (iii) 002 HIL coupon times an in-service isolate that the stream does not independently witness on a second live booth until the new source starts; (iv) no gate_snn input→output volley pair at raster resolution this round.

### Training value (SNN/LSM + agentic)
Distillation targets: SQUID B=k_s·V head plus scale identity; conjunctive isolate floor vs continue-ramp vs unit ESD; SQUID-infra collusion; IMS C=k_i·(t_d−t0) head plus drift-time identity; isolate-floor booth vs keep-spin vs hall-dump; exoneration against last-to-badge social pressure; resonant-wire T=k_t·f² and frequency identities; bounded ACCEPT with S-1..S-3-out-of-scope; skip-survey refusal under survey takt. Raster value is the independent LIF (race / refractory / adaptation) rather than a 1:1 echo of the language stream. Agentic value concentrates in three patterns: reconstruction-as-SoT on a physical B/C/T the raw corridor cannot see, earned ACCEPT with an explicit physical out-of-scope object (S-1..S-3), and stop-then-hold so a REJECT does not become a hall/dump/stack kill.

## What a later round should add (next densification target)
1. **SQUID-array / mutual-inductance table** on a non-GS-4 coil so a 2 nH hop fakes 32.00 nT inside a 4.80 Squidveil corridor, closing 001's lumped-k_s gap.
2. **Humidity / clustering map** on a non-WM-6 IMS so a water-cluster hop fakes 24.00 ppm while mean t_d looks healthy.
3. **Temperature / effective-length map** on a non-MH-8 stay so a 10 K hop fakes 32.00 kN inside a 4.80 last-good corridor.
4. **Do not restage** live r22 CDG/opacity/polariscope, leftover-mill r22 ECT/TDLAS/LIBS, live r01 Johnson-noise/Coulter/photoelastic, live r01c CIE Lab/Keidel/Leeb, live r02 CAPS/PTR/PCD, live r21 OA-ICOS/SERF/WGM, live r41 LDA/KF/bender, live r42 BOS/LIF/ESPI, live r61 Stern-Volmer/pellistor/FMCW, live r62 laser-diffraction/quartz-SF6/capillary-rheometer, live r63 ICP/LVDT/FTIR, Glimmerspit GS-4, Whinmere IMS-HIL-4, or Mosswhin RW-SIM-5. Do not reuse ids `nelb-r22-001`…`003` or leftover-mill `nelb-r22-067`…`069`.

## Verification
`{BATCH.name}`: 3 lines, `json.loads`-clean (allow_nan=False), {sizes[0]}/{sizes[1]}/{sizes[2]} bytes (file {BATCH.stat().st_size}, sha256 `{file_sha}`). CREATE-ONLY write at `{LIVE}`. Repo gates: `check_records.check_jsonl` with `FactoryStaging(enabled=True)` → 0 errors, 0 warnings, kinds `{{bridge_pair: 3}}`; `curate_bridge.raster_status(..., require_raster=True, require_routing_table=True)` → raster_valid and gate_snn_valid true, empty reason codes; `curate_record(...)` → 3× retain / `BRIDGE_EVENTS_ALREADY_GLOBALLY_ORDERED`; `verify_batch_for_frontier(strict=True)` → 3 verified, 0 inconclusive, 0 failed; `python3 pipelines/spike_probe.py --strict {BATCH}` → loaded 3. Build-time asserts: global time order; same-channel ≥0.8 ms; ≥48 events ({events[0]}/{events[1]}/{events[2]}); excerpt integer bounds, neuron bounds, sort, 1 ms per-neuron floor, span ≥1000 µs; ISI identity {isis[0]}/{isis[1]}/{isis[2]}; spike budgets exact; energy pJ/µJ exact; reward totals equal two-decimal component sums ({reward_s}); gate_snn decisions match lead `safety_decision.decision`; `state.sim_or_real` ∈ {{designed, hil, simulated}}; `meta.round=22`, `meta.factory=neuromorphic-event-language-bridge`, `meta.generator=grok-4.6`, `meta.run_label=2026-09-02-final-heavy`; `meta.snn_tags` and `meta.nelb.snn_tags` include race/refractory/adaptation; `meta.rights` 15-key RM-793 stamp (`intended_use=research_only`, `linear_issue=RM-793`, `generated_at={GENERATED_AT}`); independent CUBA LIF Jaccard {jacs[0]:.4f}/{jacs[1]:.4f}/{jacs[2]:.4f}; no hidden-reasoning keys; no `provenance` objects; no live-plant claims; no `training_ready`; no `real` / `thought` keys; all 9 record/trajectory ids unique vs live r22 a1–a3 and leftover-mill `067`–`069`. Raster seeds 2026092201/2026092202/2026092203, CUBA LIF.

Honest novelty accounting: 3/3 modality families are new versus live r01/r01c/r02/r21/r22/r41/r42/r61/r62/r63 and versus leftover-mill r13–r70 (SQUID ≠ SERF/FOCT/MFL-Hall/Rogowski; IMS ≠ PTR-MS/PID/pellistor/TDLAS; resonant-wire ≠ load-cell/VW/magnetostrictive/API-670). Independent CUBA LIF plus required snn_tags are new raster objects relative to live r22's gap-constrained draw. Against that: reconstruction-as-SoT, operational t2, conjunctive SOP, vendor-nonsubstitution, bounded-accept-with-scope-limit, and 2A/2M/2R are carried vocabulary. Net: a bit under half of the round's scenario/edge mass is genuinely novel.

Novel coverage: 45%
"""
