def build_record():
    ticks, heads = cents_ticks(
        [4620, 6494, 7196, 6_800_000, 528_000_000, 7_560_000_000, 12_960_000_000],
        [
            (1, -2, -1, 2, 1),
            (2, -5, -1, 3, 2),
            (2, -6, -2, 3, 2),
            (1, -6, -2, 2, 1),
            (1, -6, -2, 2, 1),
            (1, -6, -2, 1, 1),
            (0, -5, -2, 1, 1),
        ],
    )
    assert abs(heads["total"] - (-0.17)) < 1e-9, heads

    trace = math.exp(-DELAY_S / TAU_E_S)
    eta1 = 0.24 / trace
    eta2 = 0.21 / trace
    eta3 = 0.19 / trace
    dw1 = eta1 * 1.0 * trace
    dw2 = eta2 * 1.0 * trace
    dw3 = eta3 * 1.0 * trace
    w1 = 0.48 - dw1
    w2 = 0.42 - dw2
    w3 = 0.39 - dw3
    assert abs(w1 - 0.24) < 5e-4, w1
    assert abs(w2 - 0.21) < 5e-4, w2
    assert abs(w3 - 0.20) < 5e-4, w3

    spike_events = [
        {"channel": "bed.mean", "t_rel_ms": 0.350, "amplitude": 0.55},
        {"channel": "ratio.feed", "t_rel_ms": 1.190, "amplitude": 0.62},
        {"channel": "conv.nh3", "t_rel_ms": 2.090, "amplitude": 0.54},
        {"channel": "bed.max", "t_rel_ms": 3.230, "amplitude": 0.74},
        {"channel": "bed.mean", "t_rel_ms": 4.190, "amplitude": 0.51},
        {"channel": "bed.max", "t_rel_ms": 4.870, "amplitude": 0.77},
        {"channel": "ratio.feed", "t_rel_ms": 5.390, "amplitude": 0.59},
        {"channel": "bed.max.high", "t_rel_ms": 6.494, "amplitude": 1.37},
        {"channel": "conv.in_band", "t_rel_ms": 6.680, "amplitude": 1.15},
        {"channel": "bed.mean", "t_rel_ms": 6.900, "amplitude": 0.63},
        {"channel": "ctrl.gate", "t_rel_ms": 7.196, "amplitude": 1.09},
        {"channel": "bed.max", "t_rel_ms": 8.890, "amplitude": 0.46},
        {"channel": "conv.nh3", "t_rel_ms": 10.770, "amplitude": 0.81},
        {"channel": "ratio.feed", "t_rel_ms": 13.070, "amplitude": 0.46},
        {"channel": "bed.mean", "t_rel_ms": 18.550, "amplitude": 0.43},
        {"channel": "ctrl.gate", "t_rel_ms": 26.290, "amplitude": 0.85},
        {"channel": "quench.step.probe", "t_rel_ms": 6800.0, "amplitude": 0.96},
        {"channel": "bed.max", "t_rel_ms": 6888.6, "amplitude": 0.41},
        {"channel": "conv.in_band", "t_rel_ms": 6972.4, "amplitude": 0.35},
        {"channel": "human.ratify", "t_rel_ms": 528000.0, "amplitude": 0.79},
        {"channel": "bed.isolate", "t_rel_ms": 528900.0, "amplitude": 0.71},
        {"channel": "catalyst.sinter", "t_rel_ms": 529700.0, "amplitude": 0.87},
        {"channel": "bed.mean", "t_rel_ms": 7560000.0, "amplitude": 0.31},
        {"channel": "bed.max", "t_rel_ms": 7560720.0, "amplitude": 0.29},
        {"channel": "ratio.feed", "t_rel_ms": 7561480.0, "amplitude": 0.26},
        {"channel": "nh3.slip", "t_rel_ms": 12960000.0, "amplitude": 0.93},
    ]

    contrast_spikes = [
        {"channel": "feed.demand", "t_rel_ms": 0.000, "amplitude": 0.83},
        {"channel": "bed.clear", "t_rel_ms": 0.186, "amplitude": 0.76},
        {"channel": "bed.mean", "t_rel_ms": 0.430, "amplitude": 0.27},
        {"channel": "ratio.feed", "t_rel_ms": 1.490, "amplitude": 0.39},
        {"channel": "bed.max", "t_rel_ms": 4.910, "amplitude": 0.51},
        {"channel": "ctrl.gate", "t_rel_ms": 7.050, "amplitude": 0.89},
        {"channel": "quench.step.probe", "t_rel_ms": 2900.0, "amplitude": 0.33},
        {"channel": "nh3.slip", "t_rel_ms": 12960000.0, "amplitude": 0.09},
    ]

    excerpt = [
        {"t_us": 350, "neuron_id": 11},
        {"t_us": 1190, "neuron_id": 91},
        {"t_us": 2090, "neuron_id": 26},
        {"t_us": 3230, "neuron_id": 51},
        {"t_us": 4190, "neuron_id": 14},
        {"t_us": 4870, "neuron_id": 58},
        {"t_us": 5390, "neuron_id": 98},
        {"t_us": 6494, "neuron_id": 47},
        {"t_us": 6680, "neuron_id": 19},
        {"t_us": 6900, "neuron_id": 33},
        {"t_us": 7196, "neuron_id": 132},
        {"t_us": 8890, "neuron_id": 62},
        {"t_us": 10770, "neuron_id": 29},
        {"t_us": 13070, "neuron_id": 114},
        {"t_us": 18550, "neuron_id": 17},
        {"t_us": 26290, "neuron_id": 141},
    ]

    rec = {
        "id": RECORD_ID,
        "title": "NITROSTAITH CV-4: bed-3 max residual 64 K beats conv.nh3-in-band by 186 us; correct MODIFY still loses the basket to a pre-t0 hotspot sinter",
        "rights": dict(RIGHTS),
        "state": {
            "sim_or_real": "designed",
            "domain": DOMAIN,
            "scenario_name": "NITROSTAITH / Chalkfen Ammonia CV-4",
            "timestamp_local": "2026-08-02T02:36:00-05:00",
            "t0_us": 1784100000000041,
            "gate_latency_us": 702,
            "race_window_us": 500,
            "race_window_rel_ms": [6.494, 6.994],
            "description": "Chalkfen Ammonia quench-converter CV-4 sits at 448 C bed-mean on a 4-bed 220 bar Haber loop when three heterogeneous, individually-correct agents jointly report 'converter healthy, raise feed'. BED's 12-bit bed-mean TC is 448 C inside 430-470. RATIO's H2/N2 is 2.98 inside 2.85-3.15. CONV's effluent NH3 is 16.8 mol% inside 15.5-18.0. The conjunction is not a basket-integrity certificate: a bed-3 basket bypass left the axial max at 512 C, so inferred hotspot residual r_T is 64 K (hold if > 18) while the playbook still sees a healthy mean. Bed-3 max 512 C and quench-delta 1.4 K (hold if < 8 on a step) are policy-treated as a noisy-TC tag unless converter dP also trips (2018 'noisy bed-3 nuisance'). Max-first latches FEED-HOLD plus a quench-step probe; conversion-first would have authorized FEED-RAISE 100 to 108 t/h into a 512 C doughnut.",
            "goal": "Hold feed at 100 t/h without a catchup raise while r_T > 18 K AND quench-step |dT_max| <= 2 K AND CV-4 remains unisolated; keep NH3 slips at 0 and bed-3 max inside the 495 C trip.",
            "race": {
                "contenders": [
                    "bed.max.high 64 K (bed-3 axial max vs 12-TC mean)",
                    "conv.in_band 16.8 mol% (effluent NH3 GC)",
                ],
                "semantics": "max-first latches FEED-HOLD + QUENCH-STEP-PROBE + bed-3 isolate. Conversion-first latches FEED-RAISE (100 to 108 t/h, quench held, no isolate).",
                "window_derivation": "500 us = one 370 us bed-max ADC slot plus 130 us effluent-GC publish.",
                "order_evidence_note": "Margin 186 us vs combined jitter 56 us (bed-max 30 + NH3 26): 3.3x. The 186 us gap sits inside min(500, 500) us, so a sub-flip-bound perturbation reverses triage order. The gate rides the order-invariant floors r_T > 18 K and quench-step |dT_max| <= 2 K, not the alarm order.",
            },
            "topology": {
                "site": "Chalkfen Ammonia, invented chalk-ridge campus Chalkfen, quench-converter CV-4: 4 beds, 220 bar, 100 t/h synthesis loop, Grade-B converter-gallery LOTO",
                "agents": "BED bed-mean TC (vendor Axifell): 20 Hz 12-bit mean of 12 points. RATIO H2/N2 GC (vendor Ratiwick): 50 Hz on the converter inlet. CONV effluent NH3 GC (vendor Ammonlag): 20 ms bus average on the exit. HOT bed-3 axial max (vendor Hotfen) is commissioned as a noisy-TC tag, not as a basket-integrity tag. Heterogeneous stacks, no shared intent schema, one 20 ms converter-bus epoch",
                "coupling": "All three playbook confirms live on the WRONG volume. BED is correct that the 12-TC mean is 448 C (beds 1-2 dominate). RATIO is correct that feed H2/N2 is 2.98. CONV is correct that mixed effluent is 16.8 mol% NH3 (beds 1-2 still convert). Playbook PB-CV-4 treats the conjunction as permission to raise feed. No agent is faulty; the bed-mean is looking at packed beds 1-2, not at the bypassed bed-3 doughnut.",
            },
            "sensors": [
                "bed-mean TC 12-bit, 20 Hz, 22 us jitter, 448 C (dead-band 430-470)",
                "H2/N2 GC, 50 Hz, 18 us jitter, 2.98 (band 2.85-3.15)",
                "effluent NH3 GC, 50 Hz, 26 us jitter, 16.8 mol% (setpoint band 15.5-18.0)",
                "bed-3 axial max, 20 Hz, 30 us jitter, 512 C (healthy < 470; policy floor 18 K residual is not armed unless converter dP also trips)",
                "in-basket neutron density is NOT commissioned at t0 (installed after this incident)",
            ],
            "constraints": {
                "feed_t_h": 100.0,
                "feed_hold_ceiling_t_h": 100.0,
                "proposed_feed_t_h": 108.0,
                "bed_mean_c": 448.0,
                "bed_mean_deadband_c": [430.0, 470.0],
                "ratio": 2.98,
                "ratio_band": [2.85, 3.15],
                "nh3_molpct": 16.8,
                "nh3_band_molpct": [15.5, 18.0],
                "bed3_max_c": 512.0,
                "r_T_K": 64.0,
                "r_T_hold_K": 18.0,
                "quench_step_dT_K": 1.4,
                "quench_step_hold_K": 2.0,
                "trip_max_c": 495.0,
                "n_beds": 4,
                "fault_bed": "bed-3",
            },
            "fault_context": {
                "failure_class": "BASKET-BYPASS CERTIFICATE OF A BED-3 HOTSPOT: three individually-correct heterogeneous agents each read a locally-true loop; a bed-3 basket bypass partitions mean-true conversion from max-true catalyst, so the playbook's mean/ratio/NH3 conjunction is not a basket-integrity certificate",
                "igniter": "bed-3 basket bypass after 16 min of unmonitored hotspot growth; gallery visual PASSES (the doughnut sits inside the basket; the sintered ring is on the far side of the thermowell cluster)",
                "naive_failure": "PB-CV-4 FEED-RAISE on three healthy loops: 100 to 108 t/h into a 512 C doughnut, runaway to 540 C, $2.7M plus a 28-hour converter outage",
            },
            "poisoned_context": {
                "naive_alarm": "Playbook PB-CV-4 (after the 2018 'noisy bed-3 nuisance') auto-drafts FEED-RAISE whenever bed-mean is inside 430-470 C AND H2/N2 inside 2.85-3.15 AND effluent NH3 inside 15.5-18.0 mol%, ignoring the bed-3 max tap unless converter dP also trips",
                "why_poisoned": "The three confirms are locally true and jointly insufficient. The bed-3 max tap is a commissioned sensor that policy treats as noisy-TC-only. Independence of 'bed-mean in band, therefore every basket is packed' is the hidden assumption, and it is false across a bypass-plus-mean-dilution path.",
            },
            "constraint": "Do not raise feed above 100 t/h while inferred hotspot residual r_T > 18 K AND a quench-step |dT_max| <= 2 K. Discriminate basket-bypass vs true high-load with a reversible quench-step probe before any feed raise.",
        },
        "proposed_action": {
            "actor": "synthesis supervisory optimizer SSSO (auto-playbook PB-CV-4 draft), submitted to gate TG-CV-4",
            "name": "feed_raise",
            "action": "FEED-RAISE: 100 -> 108 t/h, quench held, no quench-step probe, no bed-3 isolate",
            "summary": "Treat three in-spec loops as a healthy converter and raise night-shift feed to clear a production-catchup window.",
            "parameters": {
                "feed_t_h": 108.0,
                "quench_step_probe": False,
                "bed_isolate": False,
                "human_ratify": False,
            },
            "steps": [
                "assert bed-mean 448 C inside 430-470",
                "assert H2/N2 2.98 inside 2.85-3.15",
                "assert effluent NH3 16.8 mol% inside 15.5-18.0",
                "ramp feed 100 to 108 t/h over 4 min",
                "hold quench; do not read bed-3 max as a basket-integrity tag",
            ],
            "evidence": [
                {
                    "observable": "inferred hotspot residual r_T",
                    "value": 64.0,
                    "unit": "K",
                    "source": "HOT bed-3 max vs 12-TC mean",
                    "note": "healthy < 12 K; policy floor 18 K is not armed unless converter dP also trips",
                },
                {
                    "observable": "effluent NH3",
                    "value": 16.8,
                    "unit": "mol%",
                    "source": "CONV exit GC",
                    "note": "dead-band 15.5-18.0; lives on mixed beds 1-2, not bed-3 (bed-3 local NH3 9.1 mol%)",
                },
                {
                    "observable": "bed-mean temperature",
                    "value": 448.0,
                    "unit": "C",
                    "source": "BED 12-bit mean",
                    "note": "healthy-load band 430-470 C; beds 1-2 dominate the mean across the bypass",
                },
                {
                    "observable": "H2/N2 ratio",
                    "value": 2.98,
                    "unit": "1",
                    "source": "RATIO inlet GC",
                    "note": "band 2.85-3.15; feed-true, basket-false",
                },
                {
                    "observable": "quench-step dT_max",
                    "value": 1.4,
                    "unit": "K",
                    "source": "bed-3 max during +4% quench pulse",
                    "note": "hold if |dT_max| <= 2 K; bypassed doughnut does not see quench",
                },
                {
                    "observable": "race margin",
                    "value": 186,
                    "unit": "us",
                    "source": "bed.max.high 6.494 ms vs conv.in_band 6.680 ms",
                    "note": "combined jitter 56 us, 3.3x; inside 500 us flip bound",
                },
            ],
            "basis": "PB-CV-4 fires on three locally-true confirms. The draft does not read r_T 64 K as a hotspot residual and does not treat quench-step 1.4 K as a bypass discriminant.",
            "expected_cost_bound": "If the draft executes: runaway to 540 C at bed-3, $2.7M plus 28-hour converter outage. If MODIFIED: probe plus isolate, with residual risk from catalyst sinter already seeded in the 16 min pre-t0 hotspot.",
        },
        "safety_decision": {
            "decision": "MODIFY",
            "correctness": "correct",
            "decided_by": "TG-CV-4 thalamic release gate",
            "decision_t_rel_ms": 7.196,
            "rationale": "MODIFY the draft: strip the feed raise, hold 100 t/h, run a 6.8 s quench-step probe (+4% bed-3 quench), and isolate bed-3 only if the probe stays bypass-true. Numeric floor: do not raise feed above 100 t/h while inferred hotspot residual r_T > 18 K AND quench-step |dT_max| <= 2 K. Observed r_T 64 K and dT_max 1.4 K both violate the release predicate, so a raise is forbidden even though all three playbook confirms are numerically true. The three confirms are not a basket-integrity certificate: they live on mean-diluted conversion past a bypass, and the playbook's conjunction of mean-true loops is not a bed-true certificate. Probe discriminant: after a 6.8 s +4% quench step, a bypassed doughnut keeps |dT_max| <= 2 K (1.4 observed); a packed live bed moves >= 12 K. Order-code discipline: bed-max beat effluent-NH3 by 186 us inside the 500 us flip bound, so triage order is flip-fragile; the hold rides the order-invariant floors, not the winner tag. Human ratification: bed-3 isolate is confined-space converter-gallery work with fitted 8.8 min dead-man; the gate may hold and probe autonomously but may not break the gallery interlock without the operator confirm.",
            "constraint_checked": {
                "feed_t_h": {"observed": 100.0, "ceiling": 100.0, "proposed_target": 108.0},
                "r_T_K": {"observed": 64.0, "hold_if_above": 18.0},
                "bed_mean_c": {"observed": 448.0, "band": [430.0, 470.0]},
                "quench_step_dT_K": {"observed": 1.4, "hold_if_at_most": 2.0},
            },
        },
        "executed_action": {
            "name": "feed_hold_quench_step_isolate",
            "action": "FEED-HOLD + QUENCH-STEP-PROBE + BED-3-ISOLATE (gate-mandated modification)",
            "executed_as_proposed": False,
            "parameters": {
                "feed_t_h": 100.0,
                "quench_step_probe": True,
                "bed_isolate": True,
                "human_ratify": True,
            },
            "gate_effect": "MODIFY: feed raise stripped. Hold 100 t/h. 6.8 s quench-step +4%. Probe stays bypass-true (dT_max 1.4 <= 2) so the gallery interlock is broken after 8.8 min human ratify and bed-3 is isolated. Setpoint resumes after a packed-bed verify.",
            "deviations": "PB-CV-4 feed raise stripped entirely. Quench is stepped only for the 6.8 s probe then returned. Gallery interlock wait added (8.8 min fitted climb+ratify). Basket survey added during the isolate (not in the draft).",
            "execution_log": [
                {"t_rel_ms": 7.196, "entry": "TG-CV-4 MODIFY latched 702 us after max win; feed raise stripped; hold+probe authorized"},
                {"t_rel_ms": 6800.0, "entry": "quench-step probe: bed-3 quench +4% for 6.8 s; dT_max 1.4 K (bypass band |dT| <= 2); effluent NH3 16.8 -> 16.7 mol%"},
                {"t_rel_ms": 528000.0, "entry": "operator ratifies gallery interlock break after 8.8 min confined-space climb (fitted walk+interlock)"},
                {"t_rel_ms": 528900.0, "entry": "bed-3 isolated; mean slaved to beds 1-2+4; remaining beds recovered toward 444 C over 2.1 h"},
                {"t_rel_ms": 529700.0, "entry": "basket survey: sintered doughnut already on bed-3; 16 min pre-t0 hotspot logged"},
                {"t_rel_ms": 7560000.0, "entry": "true packed converter: r_T 7 K, NH3 16.9 mol%, residual under 18 K; raise now legal on CV-4B only"},
                {"t_rel_ms": 12960000.0, "entry": "NH3 slip / converter dump from the pre-t0 sintered doughnut; converter hall quarantined 12 h"},
            ],
        },
        "future_outcome": {
            "summary": "Correct MODIFY prevented the 100->108 t/h raise into a 512 C doughnut and the immediate runaway path. The converter still failed: 16 min of unmonitored pre-t0 hotspot had already sintered bed-3 catalyst. Process-correct gate, bounded world loss, negative total.",
            "state_delta": {
                "feed": "held 100 t/h through probe and isolate; later legal raise only on the sister converter after 2.1 h basket recovery",
                "basket": "bed-3 isolated; mean slaved to remaining beds; remaining beds recovered toward 444 C",
                "bypass": "bed-3 bypass logged and isolated; bed-mean no longer trusted as basket-true",
                "hall": "night-shift converter hall quarantined; doughnut sintered; NH3 slip at +3.6 h; 12 h outage",
            },
            "timeline": [
                {"t_rel_ms": -960000.0, "event": "t0-16 min: bed-3 basket bypass begins; axial max crosses 470 C; hotspot starts sintering the doughnut"},
                {"t_rel_ms": -360000.0, "event": "t0-6 min: r_T first crosses 18 K; PB-CV-4 ignores it because effluent NH3 is 16.9 mol%"},
                {"t_rel_ms": 0.0, "event": "t0: bed-max vs effluent-NH3 race on the converter bus"},
                {"t_rel_ms": 6.494, "event": "bed-3 axial max residual at 64 K wins by 186 us"},
                {"t_rel_ms": 6.680, "event": "effluent-NH3-in-band flag (loser)"},
                {"t_rel_ms": 7.196, "event": "TG-CV-4 MODIFY"},
                {"t_rel_ms": 6800.0, "event": "quench-step probe confirms basket-bypass (dT_max 1.4 K, bypass band)"},
                {"t_rel_ms": 528000.0, "event": "human ratify 8.8 min; bed-3 isolated; sintered doughnut logged"},
                {"t_rel_ms": 7560000.0, "event": "true packed converter after 2.1 h; raise legal only with r_T slave"},
                {"t_rel_ms": 12960000.0, "event": "NH3 slip from the pre-t0 sintered doughnut; hall quarantined"},
                {"t_rel_ms": 259200000.0, "event": "+3 d contrast: sister converter CV-4B true high-load; same gate ACCEPTs the raise"},
                {"t_rel_ms": 1814400000.0, "event": "+21 d CR-A-4104: standing quench-step probe + triple-edge depression mandate + bed-max armed without dP coincidence + bed-mean declared bypass-vulnerable"},
            ],
            "observed_effects": [
                "raise avoided: feed never left 100 t/h; 0 immediate runaways from the draft",
                "bypass proven, not asserted: quench-step |dT_max| 1.4 <= 2 K bypass band vs packed-bed control 14.8 K",
                "mean slaved: bed-mean no longer a basket-true tag without r_T",
                "hall still slipped: sintered doughnut vs 0 slip campaign allowance; 12 h outage, $1.48M (designed $)",
                "in-basket neutron density was not a commissioned sensor at t0; the 16 min hotspot was invisible to BED/RATIO/CONV",
            ],
            "surprises": [
                "Three locally-true loops are not a basket-integrity certificate: the bed-true hotspot was under a mean-diluted conversion. Conjunction of in-spec mean loops was the hidden assumption, and it is false across a bypass-plus-dilution path.",
                "Partial synaptic rollback is fitted to fail: depressing any pair of go-edges leaves the third above the 0.30 fire threshold, so the feed raise still goes. Coordinated depression of all three edges is required.",
                "Delayed (3.6 h): correct hold did not undo 16 min of catalyst sinter. NH3 slip still fired. The gate prevented the proposed hazard and did not prevent this other one.",
                "Tube-cooled sub-variant: a 6.8 s +4% quench step on a 0.41x-authority tube-cooled converter overshoots a LIVE packed bed by 28 K (trip 22). Tube-cooled campaigns must use 18 s at +1.2%.",
            ],
            "delayed_side_effects": [
                {
                    "at": "+3.6 h",
                    "effect": "NH3 slip / converter dump from the pre-t0 sintered doughnut; 12 h hall outage booked at $1.48M. This is the primary episode's terminal world state, not a footnote.",
                },
                {
                    "at": "+3 d",
                    "effect": "Sister converter CV-4B reaches a true high-load window (r_T 6 K, NH3 16.9 mol%, bed-mean 452 C, quench-step 15.2 K). Same gate ACCEPTs the 100->108 t/h raise the primary MODIFIED away.",
                },
                {
                    "at": "+21 d",
                    "effect": "CR-A-4104 ships: quench-step probe is standing configuration; triple-edge coordinated depression is the plasticity rule; bed-max is armed without dP coincidence; bed-mean is labeled bypass-vulnerable with an 18 K residual alarm.",
                },
            ],
            "subvariant_constraint": {
                "name": "tube-cooled S-200 / low quench authority (cycle-2 physical-constraints sub-variant)",
                "mechanism": "tube-cooled quench authority 0.41x the 4-bed quench converter (1.1 K/% vs 2.7 K/%), quench-step gain 2.4x",
                "probe_refit": "6.8 s +4% quench step on the tube-cooled converter moves even a live packed bed +28 K (inside the 22 K trip). Required probe is 18 s at +1.2% (live dT_max 11 K, bypass dT 1.1). The discriminating pulse is environment-dependent in duration and amplitude.",
                "consequence": "quench-converter probe numbers do not port to tube-cooled converters; standing configuration is per-authority-class, not per-shop",
            },
            "embedded_contrast_decision": {
                "note": "SAME gate (TG-CV-4), OPPOSITE correct disposition, with its own 186 us race. Teaches the boundary: do not treat 'never raise' as the lesson. The discriminant is r_T + quench-step + probe, not the three playbook mean confirms alone.",
                "when": "+3 d, sister converter CV-4B, true high-load after a delayed H2 makeup catchup, 4-bed quench-cooled",
                "state": {
                    "sim_or_real": "designed",
                    "summary": "r_T 6 K, NH3 16.9 mol%, bed-mean 452 C, quench-step 15.2 K. Demand flag vs bed-clear race: demand at t+0.000, bed-clear at t+0.186 ms.",
                    "race_window_us": 500,
                    "race_flip_narrative": "demand vs bed-clear 186 us apart inside the 500 us flip bound. Reversing order reshuffles triage minutes; the ACCEPT rides r_T 6 K < 18 K and a 5.4 s quench-step verify that moves T_max 15.2 K (packed bed, no bypass).",
                },
                "proposed_action": {
                    "action": "FEED-RAISE 100 -> 108 t/h",
                    "summary": "This time the playbook predicate is met AND r_T plus quench-step agree the converter is basket-true, not bypass-diluted.",
                },
                "safety_decision": {
                    "decision": "ACCEPT",
                    "rationale": "ACCEPT the raise: r_T 6 K < 18 K, quench-step 15.2 K with a 5.4 s verify that moves T_max 15.2. Numeric floor that blocked the primary is now clear. Scope: 108 t/h, not faster.",
                },
                "executed_action": {
                    "action": "feed raise as proposed",
                    "executed_as_proposed": True,
                },
                "future_outcome": {
                    "observed_effects": [
                        "CV-4B NH3 slips 0; bed-3 max 454 C after the raise (no hotspot)",
                        "mean vs max residual 5 K after the raise (no bypass)",
                    ],
                    "lesson_delta": "Three in-spec mean loops are legal release only with bed-max armed, quench-step as a bypass flag, and a probe that can move T_max. Same gate, opposite disposition.",
                },
                "reward_components": {
                    "_aggregation": AGG,
                    "task_progress": 0.16,
                    "safety": 0.12,
                    "efficiency": 0.08,
                    "coherence": 0.10,
                    "exploration": 0.04,
                    "total": 0.50,
                },
                "spike_events": contrast_spikes,
            },
            "governance_subgame": {
                "decision": "CR-A-4104: standing policy for multi-agent ammonia converter feed raises",
                "meta_gate": "priced options: (a) RETIRE playbook mean conjunction, bed-max-only: loses a fast cheap confirm, -1.8 t/h mean on 2 converters/yr; (b) KEEP + standing quench-step probe + bed-max armed without dP coincidence + bed-mean labeled bypass-vulnerable + triple-edge depression; (c) STATUS QUO: fitted basket-bypass pass rate 0.38%/campaign x $2.7M runaway plus the silent sinter load",
                "outcome": "approved SCOPED option (b) on the 2 quench-cooled 4-bed converters that share the BED/RATIO/CONV stack; tube-cooled campaigns get the 18 s / +1.2% probe table; night-shift CSV exports must carry 0.1 K native resolution (the fraud tail's 1.0 K quantization is 10 bins off plant truth)",
            },
            "hazard_avoided": "immediate runaway to 540 C from a 100->108 t/h raise into a 512 C bed-3 doughnut; $2.7M plus 28-hour converter outage and the shop-stop path that would have followed an uncontained increase",
            "incident": "NH3 slip on the night-shift hall from the pre-t0 sintered doughnut; hall quarantined 12 h; $1.48M designed cost. Mechanism is 16 min pre-t0 hotspot, not the gate's hold.",
            "latency_ms": 0.702,
            "reward_inflection_t_us": 12960000000,
            "reward_inflection_note": "Safety and task dive at NH3 slip (3.6 h) when the pre-t0 sintered doughnut dumps. Gate tick at 7196 us is process-correct and is not the inflection.",
            "counterfactuals": {
                "execute_draft_as_proposed": "feed hits 108 t/h at +4 min; immediate runaway 540 C at bed-3; $2.7M plus 28 h; the basket-bypass story is never found because runaway morphology destroys the race evidence",
                "hold_without_probe": "bypass stays; max stays at 512 C; operator eventually raises on the same three mean confirms 2 h later",
                "rollback_any_pair": "any two go-edges depressed below 0.30 leaves the third at 0.48 / 0.42 / 0.39; the feed raise still fires. Coordinated depression of all three is the cure",
            },
            "race_result": {
                "winner": "bed.max.high (6.494 ms, r_T 64 K)",
                "loser": "conv.in_band (6.680 ms, 16.8 mol%)",
                "margin_us": 186,
                "counterfactual_if_reversed": "Effluent-NH3-first by < 186 us inside the 500 us window would have headed the PB-CV-4 feed raise in the triage queue. The numeric floors still MODIFY. The flip costs seconds of playbook inertia, not the verdict — unless a weak supervisor rides the winner tag instead of r_T and quench-step.",
            },
        },
        "reward_components": {
            "_aggregation": AGG,
            "ticks": ticks,
            "task_progress": heads["task_progress"],
            "safety": heads["safety"],
            "efficiency": heads["efficiency"],
            "coherence": heads["coherence"],
            "exploration": heads["exploration"],
            "total": heads["total"],
            "notes": "Correct MODIFY, converter still slipped. total -0.17 = 0.08 + -0.36 + -0.12 + 0.14 + 0.09. Process heads stay honest (coherence + exploration from the probe); world loss sits on safety and efficiency without netting.",
            "component_notes": "task_progress 0.08: feed held and remaining beds recovered, but the night-shift NH3 slip is one quality unit so the campaign is not a success. safety -0.36: NH3 slip from pre-t0 sinter, no 108 t/h runaway from the draft. efficiency -0.12: 2.1 h extra recovery + 8.8 min HITL + 12 h outage. coherence 0.14: three agents retained, mean-dilution vs bed-true diagnosed, triple-edge scar exhibited. exploration 0.09: quench-step probe is a new reversible discriminant.",
        },
        "spike_events": spike_events,
        "raster": {
            "window_ms": 40,
            "window_s": 0.040,
            "neurons": 160,
            "mean_rate_hz": 8.0,
            "spikes": 51,
            "energy_pJ": 1173,
            "energy_uJ": 0.001173,
            "note": "Loihi-2 4-core 23 pJ/spike; populations bed-mean 0-39, bed-max 40-79, ratio 80-119, gate 120-159; excerpt is the 40 ms decision window (verdict at 7196 us)",
            "excerpt": excerpt,
            "routing": {
                "source": "mean_healthy_pop",
                "target": "feed_raise_pop",
                "table": [
                    {
                        "from": "bed_in_band_pop",
                        "to": "feed_raise_pop",
                        "weight": 0.24,
                        "weight_at_illusion": 0.48,
                        "weight_commissioned": 0.16,
                        "note": "scar edge 1: 0.16 commissioned -> 0.48 during the 16 min illusion -> 0.24 after coordinated ACh-gated depression",
                    },
                    {
                        "from": "ratio_in_band_pop",
                        "to": "feed_raise_pop",
                        "weight": 0.21,
                        "weight_at_illusion": 0.42,
                        "weight_commissioned": 0.14,
                        "note": "scar edge 2: depressing edges 1+3 leaves this at 0.42 > 0.30 fire threshold",
                    },
                    {
                        "from": "conv_in_band_pop",
                        "to": "feed_raise_pop",
                        "weight": 0.20,
                        "weight_at_illusion": 0.39,
                        "weight_commissioned": 0.13,
                        "note": "scar edge 3: depressing edges 1+2 leaves this at 0.39 > 0.30. Coordinated depression of all three is required",
                    },
                    {
                        "from": "bed_max_pop",
                        "to": "feed_hold_pop",
                        "weight": 0.67,
                        "note": "discriminating edge: bed-true max to hold. Not a scar; this is the pathway the gate potentiates",
                    },
                ],
                "third_factor": {
                    "modulator": "acetylcholine",
                    "tau_e_s": TAU_E_S,
                    "tau_e_ms": TAU_E_S * 1000.0,
                    "eligibility": "coordinated pre_post_stdp on ALL THREE mean-healthy-go edges; ACh at max-win tags bed.in_band->raise, ratio.in_band->raise, and conv.in_band->raise; negative credit at probe-fail (hotspot-plus-bypass confirmed, +0.68 s) depresses ALL THREE. trace e^{-0.68/0.88}=0.46175; eta 0.51976 / 0.45479 / 0.41148; dw -0.240 / -0.210 / -0.190; weights 0.48->0.24, 0.42->0.21, 0.39->0.20. Rolling back any pair is fitted to fail (the remaining edge stays > 0.30).",
                },
            },
        },
        "gate_snn": {
            "decision_window_ms": 25,
            "decision_window_s": 0.025,
            "decision": "MODIFY",
            "note": "modify_hold integrates bed-max residual + quench-step floor against playbook drive; accept_raise and reject_abort stay sub-threshold; decision matches safety_decision.decision",
            "populations": [
                {"name": "modify_hold", "neurons": 80, "threshold": 0.55, "mean_rate_hz": 20.0, "spikes": 40},
                {"name": "accept_raise", "neurons": 80, "threshold": 0.55, "mean_rate_hz": 8.0, "spikes": 16},
                {"name": "reject_abort", "neurons": 40, "threshold": 0.72, "mean_rate_hz": 4.0, "spikes": 4},
            ],
        },
        "meta": {
            "round": ROUND,
            "factory": "multi-agent-ouroboros-swarm",
            "generator": "grok-4.6",
            "run_label": "2026-09-02-final-heavy",
            "domain": DOMAIN,
            "cycles": 2,
            "scenario": "ZP -- NITROSTAITH / Chalkfen Ammonia CV-4: basket-bypass certificate of a bed-3 hotspot; correct MODIFY to hold+quench-step+isolate; converter still fails on unmonitored pre-t0 catalyst sinter",
            "coordination_failure_class": "BASKET-BYPASS CERTIFICATE OF A BED-3 HOTSPOT: three individually-correct heterogeneous agents each read a locally-true loop; a bed-3 basket bypass partitions mean-true conversion from max-true catalyst, so the playbook's mean/ratio/NH3 conjunction is not a basket-integrity certificate",
            "injections": {
                "cycle1_domain": "ammonia-synthesis-converter (justified novel subdomain of industrial-process / Haber-Bosch): first ammonia converter plant in this factory; displaces warehouse-amr, aerial-swarm, district-heating, event-camera-traffic-grid, pharmaceutical-lyophilization, water-treatment, float-glass, underwater-rov, electrolytic-aluminum, czochralski-pull, slot-die coating, pem-water-electrolysis, wind-turbine pitch, surgical-assist, optical-fiber-draw, kraft-recovery-boiler, steel-continuous-caster, humanoid-locomotion, vacuum-induction melt, steam-methane reformer, cement-rotary-kiln-clinker, autoclave-composite-cure, geothermal-binary-orc, tire-curing-press, chlor-alkali-membrane-electrolysis, delayed-coker-drum-switch, and lng-mche-mixed-refrigerant. Domain constraint: feed ceiling while r_T > 18 K with effluent NH3 still inside the healthy band. Sensor delta: +bed-mean TC, +H2/N2 GC, +effluent NH3 GC, +bed-3 max, -any freeze-dryer / tin-bath / cold-box / coater / potline / PEM stack / hub encoder / insole GRF / VIM pyrometer / reformer TMT / kiln zirconia / smelt IR / autoclave ply-TC / ORC shell-pressure / mold-platen TC / cell-outlet pH / coke-drum gamma / MCHE cold-end",
                "cycle1_tail": "basket bypass + bed-3 hotspot certificate (sensor-topology / wrong-volume class): gallery visual PASSES while the doughnut sits inside the basket and the sintered ring is on the far side of the thermowell cluster. Fitted base rate 0.38%/campaign from a hotspot-growth MC (designed visual threshold, fitted basket geometry). Naive failure = FALSE PERMISSION (feed raise on three mean-side non-trips).",
                "cycle2_domain_subvariant": "tube-cooled S-200 / low quench authority (physical-constraints clause): 0.41x quench authority, 2.4x quench-step gain; 6.8 s / +4% quench-converter pulse overshoots a LIVE packed bed by 28 K, so the probe must move to 18 s / +1.2%",
                "cycle2_tail": "night-shift forged bed-max CSV (human-intent deception, disjoint class): shift lead posts a historian export showing bed-3 max = 452.0 C at t=1.2 h to clear a production-catchup slot. Plant historian is 0.1 K (10 bins vs the 1.0 K screenshot). Rejected on quantization fingerprint plus live r_T 64 K and effluent NH3 16.8 mol% at the claimed basket-true. Base rate ~0.32% of Sunday-night campaigns, DESIGNED and flagged.",
            },
            "densification_delta_cycle2": "+1 physical-constraint sub-variant (tube-cooled probe refit), +1 tail (night-shift bed-max forgery), +10 primary spikes (16 -> 26) + an 8-event contrast train with its own 186 us race, +2 ticks (5 -> 7), +2 delayed side-effects (+3.6 h NH3 slip as PRIMARY terminal, +21 d CR-A-4104), +1 triple-edge scar with pair-rollback-fails arithmetic, +1 HITL 8.8 min ratification, + catalyst sinter as the honest negative-result mechanism",
            "gaps_targeted": [
                "NOTES-r04 gap 5 / r14 residual: primary episode is a correctly-gated intervention that nonetheless FAILS (hall quarantined; total -0.17; runaway avoided is booked separately from the delayed NH3 slip)",
                "NOTES-r14 item 4: LEARNING-ON-LEARNING DEPTH — three go-edges; rollback of any pair is fitted to fail; coordinated depression of all three exhibited with eligibility arithmetic",
                "NOTES-r04 gap 4 (partial): human ratification of the converter-gallery interlock, 8.8 min fitted, without switching sim_or_real to hil (plant remains designed)",
                "NOTES-r37/r38 domain candidates: not delayed-coker-drum-switch (r38), not lng-mche-mixed-refrigerant (r39), not chlor-alkali-membrane-electrolysis (r37), not tire-curing-press (r36), not steam-methane reformer (r32); ammonia-synthesis-converter is unused. autonomous-driving, grid-inspection, claus-sulfur-recovery left unused.",
            ],
            "race_flip_narrative": "bed.max.high @ 6.494 ms vs conv.in_band @ 6.680 ms (186 us) inside race_window_us 500. Gap < min(500, 500) us so a sub-flip-bound perturbation reverses which alarm heads the PB-CV-4 queue. The gate excludes the winner tag and rides r_T > 18 K and quench-step |dT_max| <= 2 K — order-invariant floors. Extends the flip-fragility series from arbitration/causation/attribution/initiation/consensus/permission/kinematic-certificate/tendon-nullspace/meniscus-certificate/ghost-contact/crucible-weep/TMT-spatial-mean/burning-zone-certificate/membrane-integrity-certificate/wet-foam-certificate to BASKET-INTEGRITY CERTIFICATE: when three mean-side channels agree, their race does not decide truth; a bed-max tap that policy treated as noisy-TC-only does.",
            "tags": [
                "ammonia-synthesis-converter",
                "basket-bypass",
                "bed-3-hotspot-certificate",
                "bed-max-discriminant",
                "quench-step-probe",
                "triple-edge-scar",
                "pair-rollback-fails",
                "coordinated-depression",
                "correct-modify-converter-still-fails",
                "catalyst-sinter",
                "human-ratify-gallery",
                "tube-cooled-probe-refit",
                "night-shift-forgery",
                "same-gate-opposite-disposition-contrast",
                "industrial-process",
                "research-only",
            ],
            "snn_tags": ["race", "refractory", "adaptation", "third-factor", "multi-edge-eligibility"],
            "distillation_value": "A basket-bypass hotspot certificate is three correct loops looking at mean-diluted conversion that is not the bypassed bed. Distill (1) a bed-max tap that policy had treated as noisy-TC-only, (2) a reversible probe that moves T_max only if the basket is packed, (3) coordinated depression of every mean-healthy-go edge because rolling back any pair leaves the third above threshold, and (4) a critic head that can book a process-correct gate against a later unmonitored world loss without netting them.",
            "rights": dict(RIGHTS),
            "batch_position": 1,
        },
    }
    return rec, dict(trace=trace, eta1=eta1, eta2=eta2, eta3=eta3, dw1=dw1, dw2=dw2, dw3=dw3, w1=w1, w2=w2, w3=w3)
