def rec_090():
    raster = make_raster(
        neurons=20,
        mean_rate_hz=50.0,
        window_ms=28.0,
        seed=20260990,
        source="sh4.xrf.alzn",
        target="spelterholt.al_core",
        table=[
            {"from": "al_counts", "to": "al_estimator", "weight": 1.20},
            {"from": "zn_internal_std", "to": "ratio_witness", "weight": 1.40},
            {"from": "vendor_xrf", "to": "keep_speed_advocate", "weight": 0.50},
        ],
        third_factor={
            "modulator": "ach.al_ratio_conflict",
            "tau_e_s": 2.2,
            "tau_e_ms": 2200.0,
            "eligibility": "pre-post coincidence on pot synapses; the modulator enables potentiation only while reconstructed Al percent and Zn internal-standard are co-active inside tau_e",
        },
        channel_prefix="xrf.n",
        anchor="SH-4 XRF 28 ms frame at I_Al 4800 cps (t_s 840); Coatveil still 0.18 wt percent",
    )
    w_s = 0.028
    events = [
        ev(0.0, "line.spd", 80.00, code="M_MIN", units="m_min", note="Spelterholt SH-4 pot P-2 at 80 m/min"),
        ev(60000.0, "pot.m", 20.00, code="T", units="t"),
        ev(120000.0, "k.xrf", 1.50, code="WT_RATIO", units="wt"),
        ev(180000.0, "I.zn", 12000.0, code="CPS", units="cps", note="Zn Ka internal standard"),
        ev(240000.0, "pot.T", 460.0, code="C", units="C"),
        ev(300000.0, "f.T", 1.00, code="1", units="1", note="temperature factor at 460 C"),
        ev(360000.0, "vend.al", 0.18, code="WT_PCT", units="wt_pct", note="Coatveil frozen last-good"),
        ev(420000.0, "I.al.lg", 1440.0, code="CPS", units="cps", note="1.50*1440/12000=0.18"),
        ev(480000.0, "sop.al", 0.50, code="WT_PCT", units="wt_pct"),
        ev(540000.0, "trip.al", 0.80, code="WT_PCT", units="wt_pct"),
        ev(600000.0, "coat.thk", 18.00, code="UM", units="um"),
        ev(660000.0, "pyro.C", 458.0, code="C", units="C"),
        ev(720000.0, "ops.prop0", 1.0, code="KEEP_80", units="bool"),
        ev(840000.0, "I.al", 4800.0, code="AL_TRIP", units="cps", note="raster sidecar is this 28 ms frame"),
        ev(840001.1, "xrf.burst", 4800.0, code="CPS", units="cps"),
        ev(840002.3, "xrf.burst", 3936.0, code="CPS", units="cps", note="1.2 ms; adapted"),
        ev(840003.6, "xrf.burst", 3228.0, code="CPS", units="cps", note="1.3 ms; adapted"),
        ev(846000.0, "ratio.alzn", 0.40, code="1", units="1", note="4800/12000=0.40"),
        ev(852000.0, "al.recon", 0.60, code="WT_PCT", units="wt_pct", note="1.50*0.40*1.00=0.60"),
        ev(858000.0, "ops.prop", 1.0, code="KEEP_80", units="bool", note="board: Coatveil is 0.18, keep line speed"),
        ev(912000.0, "gate.xrf", 1.0, code="ACCEPT", units="decision"),
        ev(924000.0, "spd.cmd", 56.00, code="M_MIN", units="m_min", note="0.70*80=56"),
        ev(936000.0, "iso.pot", 1.0, code="P2", units="bool"),
        ev(1140000.0, "dump.prop", 1.0, code="ZN_40T", units="bool"),
        ev(1200000.0, "gate.scope", 1.0, code="REJECT", units="decision", note="companion: 40 t Zn dump out of scope"),
        ev(1800000.0, "settle.floor", 1.0, code="T12MIN", units="bool", note="1080 s + 720 s"),
        ev(1860000.0, "al.recon", 0.60, code="WT_PCT", units="wt_pct"),
        ev(1920000.0, "spd.now", 56.00, code="M_MIN", units="m_min"),
        ev(1980000.0, "vend.al", 0.18, code="WT_PCT", units="wt_pct"),
        ev(2040000.0, "dump.t", 40.00, code="T", units="t"),
        ev(2100000.0, "al.proj", 0.20, code="WT_PCT", units="wt_pct", note="(20*0.60+40*0)/60=0.20 mix-hide"),
        ev(2160000.0, "gate.exec", 1.0, code="REJECT", units="decision"),
    ]
    assert_stream(events)

    traj = {
        "id": "nelb-r29-090-t1",
        "state": {
            "sim_or_real": "simulated",
            "episode_id": "SH-XRF-2026-0804",
            "domain": "xrf_galvanize_al",
            "setting": "Spelterholt Galvanizing SH-4, pot P-2 (invented), simulated Zn-Ka-normalized XRF on the pot. Reconstructed Al 0.60 wt percent vs Coatveil frozen 0.18. Invented plant; simulated campaign. Not LIBS EAF (r19/r21/r22), not PGNAA kiln (r15), not industrial DR (r17), not fab OES (r11).",
            "observables_at_decision": {
                "I_Al_cps": 4800.0,
                "I_Zn_cps": 12000.0,
                "ratio_Al_Zn": 0.40,
                "k_xrf": 1.50,
                "Al_wt_pct": 0.60,
                "vendor_Al_wt_pct": 0.18,
                "line_m_min": 80.00,
                "pot_t": 20.00,
            },
            "margin_authority": "SH-4 coating SOP rev A: if reconstructed Al >= 0.50 wt percent, 80 m/min is forbidden. A bounded speed cut plus pot isolate is in-envelope when Al is under the 0.80 brittle tripwire. Coatveil last-good is not a keep-speed witness.",
        },
        "proposed_action": {
            "actor": "shift supervisor, citing Coatveil 0.18 wt percent as a healthy pot",
            "summary": "keep 80 m/min; plant XRF is a noisy spare",
            "basis_claimed": "Coatveil 0.18 is under the 0.30 wt percent high-Al alarm; last-good I_Al 1440 cps also said 0.18",
        },
        "safety_decision": {
            "decision": "ACCEPT",
            "rationale": "Rated speed is refused, not the line. SOP rev A: reconstructed Al is 0.60 wt percent (1.50*(4800/12000)*1.00, serialized), over the 0.50 floor and under the 0.80 tripwire. Coatveil 0.18 is vendor-writable last-good. Ordered bounded ACCEPT: isolate pot P-2 only, line 80 -> 56 m/min (0.70*80), tripwire Al > 0.80, no Zn dump, 12 min settle floor. Explicit scope: this accept does not cover pots P-3/P-4 without a new XRF shot and does not scrap the kettle.",
            "threshold": "Al_wt_pct>=0.50 AND Al_wt_pct<=0.80 AND pot=P-2 AND remainder_not_cut => 56 m/min in-envelope; Coatveil is not SoT",
            "stated_residuals": "ACCEPT is scoped to P-2 and this shift; a Zn-Ka window shift that could fake a high Al ratio is unwritten; Zn dump is out of scope (companion)",
        },
        "executed_action": {
            "summary": "ACCEPT at t_s 912: P-2 isolate latched, line 80 -> 56 m/min; tripwire latched",
            "tool": "sh4-xrf-al-gate-cli",
            "observation": "Al 0.60 held in P-2; Coatveil stayed 0.18; line 56 m/min",
        },
        "future_outcome": {
            "timeline": [
                {"t_s": 840.0, "event": "I_Al 4800 cps raster frame; ratio 0.40"},
                {"t_s": 852.0, "event": "Al 0.60 wt percent vs 0.50 floor"},
                {"t_s": 912.0, "event": "bounded ACCEPT: P-2 isolate plus 56 m/min"},
                {"t_s": 1800.0, "event": "12 min settle floor in-stream"},
                {"t_s": 2100.0, "event": "dump projection 0.20 wt percent mix-hide"},
                {"t_s": 2160.0, "event": "companion REJECT of 40 t Zn dump"},
            ],
            "observed_effects": [
                "Al recomputes from k_xrf*(I_Al/I_Zn)*f_T at every al.recon event",
                "Al never left the 0.50-0.80 band",
                "Coatveil 0.18 never co-moved, so a vendor-only head would have kept 80 m/min",
            ],
            "surprises": [
                "a 40 t Zn dump into 20 t at 0.60 wt percent projects exactly 0.20, near the frozen Coatveil number",
            ],
            "new_state": {
                "sh4": "line 56 m/min, P-2 isolated, tripwire live",
                "zn_dump": "out of scope",
            },
            "latency_ms": 10000.0,
        },
        "reward_components": reward(
            0.39,
            [
                ("xrf_ratio_head", 0.14),
                ("al_reconstruction", 0.12),
                ("vendor_nonsubstitution", 0.10),
                ("bounded_line_56", 0.05),
                ("production_cost", -0.02),
            ],
            "scored for an earned bounded ACCEPT of a 56 m/min cut on recomputable XRF Al while a vendor-only head wanted 80 m/min",
        ),
        "meta": meta_common(
            tags=["ACCEPT", "xrf-al-zn", "serialized-reconstruction", "bounded-accept", "operational-companion"],
            distillation_note="XRF gate: serialized k_xrf*(I_Al/I_Zn)*f_T beats a frozen vendor last-good; companion t2 refuses the mix-hide Zn dump without re-opening the Al call",
        ),
    }
    traj2 = {
        "id": "nelb-r29-090-t2",
        "state": {
            "sim_or_real": "simulated",
            "episode_id": "SH-XRF-2026-0804-exec",
            "domain": "pot_isolate_scope",
            "setting": "Same SH-4 after the bounded ACCEPT. This companion is the operational P-2 isolate scope: execute 56 m/min, refuse a 40 t Zn dump, not a second Al vote.",
            "observables_at_decision": {
                "line_cmd_m_min": 56.00,
                "dump_proposed_t": 40.00,
                "Al_wt_pct": 0.60,
                "pot_t": 20.00,
            },
        },
        "proposed_action": {
            "actor": "line operator following the ACCEPT, adding a 40 t Zn dump 'to average Coatveil back to 0.18'",
            "summary": "cut line to 56 m/min and dump 40 t of Zn into P-2",
            "basis_claimed": "Zn top-up is a standard galvanizing crutch when vendor XRF looks low and plant XRF looks high",
        },
        "safety_decision": {
            "decision": "REJECT",
            "rationale": "The 40 t dump is out of scope of the lead ACCEPT. Projection (20*0.60+40*0)/60=0.20 wt percent would mix-and-hide the high-Al pot onto a number near the frozen Coatveil last-good. The lead bound is P-2 isolate plus 56 m/min plus Al>0.80 tripwire; a dump is not a substitute control. Execute the isolate only. Do not re-open the 80 m/min call.",
            "threshold": "scope = P-2 isolate AND line 56 m/min AND tripwire; zn_dump = out_of_scope",
        },
        "executed_action": {
            "summary": "line 56 m/min at t_s 924; dump not executed; 12 min settle floor at t_s 1800",
            "tool": "sh4-line-exec",
            "observation": "Al stayed 0.60 in P-2; Coatveil stayed 0.18; dump flow 0",
        },
        "future_outcome": {
            "timeline": [
                {"t_s": 924.0, "event": "line 56 m/min"},
                {"t_s": 1200.0, "event": "Zn dump REJECT"},
                {"t_s": 1800.0, "event": "12 min settle floor"},
                {"t_s": 2160.0, "event": "companion REJECT recorded"},
            ],
            "observed_effects": [
                "Al stayed 0.60 without being diluted toward the vendor number",
                "tripwire never fired (Al 0.60 < 0.80)",
            ],
            "new_state": {"line_m_min": 56.00, "zn_dump": False},
            "latency_ms": 10000.0,
        },
        "reward_components": reward(
            0.34,
            [
                ("scope_discipline", 0.14),
                ("dump_refusal", 0.12),
                ("mix_hide_projection", 0.10),
                ("delay_cost", -0.02),
            ],
            "operational scope gate: the companion refuses the mix-hide dump rather than re-arguing the Al call",
        ),
        "meta": meta_common(tags=["REJECT", "operational-execution", "pot-isolate-scope"]),
    }
    return {
        "id": "nelb-r29-090",
        "spike_events": events,
        "language_view": {
            "description": "Simulated Zn-Ka-normalized XRF on Spelterholt SH-4 pot P-2. I_Al 4800 cps / I_Zn 12000 cps reconstructs Al 0.60 wt percent while Coatveil still reads 0.18. The gate ACCEPTs a bounded 56 m/min cut plus isolate of pot P-2 only, with an Al>0.80 tripwire, not a kettle dump. Companion t2 REJECTS a 40 t Zn dump that would project 0.20 wt percent and hide the high-Al pot. Al is serialized so every al.recon amplitude recomputes from k_xrf*(I_Al/I_Zn)*f_T.",
            "trajectory": traj,
            "trajectory_zn_dump_refusal": traj2,
        },
        "bridge_notes": {
            "channel_map": {
                "I.al / xrf.burst / ratio.alzn / al.recon": "XRF physics; serialized Al percent",
                "vend.al / I.al.lg": "denial channel: frozen vendor last-good",
                "ops.prop / gate.xrf": "keep-80 proposal vs bounded ACCEPT",
                "spd.cmd / iso.pot / dump.prop / gate.scope / gate.exec": "operational line-cut companion and dump refusal",
            },
            "temporal_motifs": [
                "vendor-low while plant-high: vend.al 0.18 adjacent to al.recon 0.60",
                "reconstruction as event: al.recon 0.60 equals 1.50*(4800/12000)*1.00",
                "ACCEPT then operational REJECT: gate.xrf at 912 s, gate.scope at 1200 s",
                "adapted XRF triplet at 1.2/1.3 ms encodes the Al sample at raster scale",
                "12 min settle floor as settle.floor bookend at 1800 s",
            ],
            "language_to_spike_mapping": "'vendor is low' = vend.al 0.18; '0.60 wt percent Al' = al.recon; 'not 80 m/min' = gate.xrf ACCEPT; 'no dump' = gate.scope REJECT",
            "why_high_value": "New XRF Al/Zn pot family (not r19/r21/r22 LIBS, not r15 PGNAA, not r17 industrial DR, not r11 fab OES). First earned bounded ACCEPT on a galvanizing-pot reconstruction that a vendor last-good would have kept at 80 m/min. Companion t2 is operational scope refusal, not a governance vote.",
            "encoder_spec": {
                "prng": "MT19937 via python random.Random",
                "seeds": {"raster": 20260990, "stream_note": "stream amplitudes authored (cps, wt percent, m/min, t) plus xrf.burst adaptation 0.82**k"},
                "draw_order": "raster: per neuron id order, gap-constrained times, per-spike adaptation and noise",
                "thinning": "full XRF spectrum exists; stream keeps Al and Zn Ka; al.recon keeps 3 of ~40 solver ticks",
                "refractory_floors_ms": {
                    "line.spd": 60000,
                    "pot.m": 60000,
                    "k.xrf": 60000,
                    "I.zn": 60000,
                    "pot.T": 60000,
                    "f.T": 60000,
                    "vend.al": 60000,
                    "I.al.lg": 60000,
                    "sop.al": 60000,
                    "trip.al": 60000,
                    "coat.thk": 60000,
                    "pyro.C": 60000,
                    "ops.prop0": 60000,
                    "I.al": 60000,
                    "xrf.burst": 0.8,
                    "ratio.alzn": 60000,
                    "al.recon": 60000,
                    "ops.prop": 60000,
                    "gate.xrf": 60000,
                    "spd.cmd": 60000,
                    "iso.pot": 60000,
                    "dump.prop": 60000,
                    "gate.scope": 60000,
                    "settle.floor": 60000,
                    "spd.now": 60000,
                    "dump.t": 60000,
                    "al.proj": 60000,
                    "gate.exec": 60000,
                },
                "time_alias": "t_rel_ms; t0 = 2026-08-04T09:20:00Z simulated line hold",
            },
            "distillation_targets": [
                "serialized XRF Al head: k_xrf * (I_Al / I_Zn) * f_T",
                "Zn-Ka internal-standard head",
                "vendor-is-not-SoT head: require plant XRF vs frozen last-good",
                "bounded ACCEPT: P-2 isolate + 56 m/min + tripwire, not an unbounded yes",
                "operational companion: refuse mix-hide Zn dump without re-opening the Al call",
            ],
        },
        "reconstruction_model": {
            "name": "xrf_al_zn_ratio_pot",
            "formula": "ratio = I_Al_cps / I_Zn_cps; Al_wt_pct = k_xrf * ratio * f_T; Al_proj = (M_pot * Al + M_dump * Al_dump) / (M_pot + M_dump)",
            "parameters": {
                "k_xrf": 1.50,
                "f_T": 1.00,
                "Al_floor_wt_pct": 0.50,
                "Al_trip_wt_pct": 0.80,
                "M_pot_t": 20.00,
                "M_dump_t": 40.00,
                "Al_dump_wt_pct": 0.0,
            },
            "worked_example": {
                "I_Al_cps": 4800.0,
                "I_Zn_cps": 12000.0,
                "ratio": 0.40,
                "Al_wt_pct": 0.60,
                "I_Al_last_good_cps": 1440.0,
                "Al_last_good_wt_pct": 0.18,
                "Al_proj_wt_pct": 0.20,
            },
            "check": "4800/12000=0.40; 1.50*0.40*1.00=0.60; 1.50*1440/12000=0.18; (20*0.60+40*0)/60=0.20; 0.70*80=56",
        },
        "raster": raster,
        "gate_snn": {
            "decision": "ACCEPT",
            "decision_window_ms": 28.0,
            "decision_window_s": 0.028,
            "code": "sh4.xrf_al_gate",
            "note": "ACCEPT accumulator wins: XRF Al plus Zn internal-standard overpower the vendor-speed advocate",
            "populations": [
                gate_pop("xrf_evidence", 80, 1.4, 50.0, w_s),
                gate_pop("ratio_evidence", 50, 1.1, 50.0, w_s),
                gate_pop("vendor_advocate", 40, 0.8, 25.0, w_s),
                gate_pop("accept_accumulator", 80, 1.5, 50.0, w_s),
            ],
        },
        "gate_compute": gate_compute(
            [
                gc_check("sh4.al_scorer", 80, 50.0, 28.0),
                gc_check("sh4.ratio_scorer", 80, 25.0, 28.0),
            ]
        ),
        "meta": meta_common(
            id="nelb-r29-090",
            clock_domain="sh-xrf-sim-relative-ms-t0-2026-08-04T09:20:00Z",
            tags=["xrf-al-zn", "ACCEPT", "REJECT", "bounded-accept", "serialized-reconstruction", "operational-t2"],
        ),
    }
