#!/usr/bin/env python3
"""AST-extracted plant pairs for cer_r1901 (legacy-mill-lane cer_r1901_leftover3_mill.py)."""

from __future__ import annotations

MILL_ID = "cer_r1901"
START = 1901
N_ROUNDS = 16

PAIRS: tuple[tuple[dict, dict], ...] = (
    (
        {'slug': 'cache-status-hit-stale', 'mod': 'cache_status', 'caller': 'cdn_edge', 'fn': 'apply_cs', 'rfc': 'RFC 9213 Cache-Status', 'ident': 'Cache-Status', 'bug': 'Cache-Status leftover hit;stale without Age, so downstream treats HIT as fresh', 'naive': 'tests used origin 200 only', 'wrong': 'set Cache-Status: hit without ttl', 'fix': 'emit Cache-Status hit;ttl plus Age from clock', 'payload': 'fwd=cdn;detail=hit leftover Age=0', 'kind': 'silent-truncate', 'n': 11, 'unit': 'stale Cache-Status hits', 'test_naive': 'test_origin200', 'test_gate': 'test_cs', 'hexid': 'cs#1', 'want': "'hit;ttl=60'", 'live': "print(apply_cs('HIT'))", 'live_bad': "'HIT'", 'live_good': "'hit;ttl=60'", 'grep': 'Cache-Status|Age|hit;stale', 'replay': 'Replay', 'success': True},
        {'slug': 'age-header-clock-skew', 'mod': 'age_hdr', 'caller': 'origin_age', 'fn': 'age_of', 'rfc': 'RFC 9111 Age', 'ident': 'Age', 'bug': 'Age leftover computed from Date not date_value, so skew hides freshness', 'naive': 'tests used Date==now', 'wrong': 'set Age: 0 on every 200', 'fix': 'compute Age as now minus date_value', 'payload': 'Age:0 while Date is 90s old', 'kind': 'stale-lock', 'n': 14, 'unit': 'skewed Age headers', 'test_naive': 'test_date_now', 'test_gate': 'test_age', 'hexid': 'age#2', 'want': '90', 'live': 'print(age_of(90))', 'live_bad': '0', 'live_good': '90', 'grep': 'Age|date_value|Date', 'replay': 'Sweep', 'success': False},
    ),
    (
        {'slug': 'proxy-status-error-drop', 'mod': 'proxy_status', 'caller': 'ingress_ps', 'fn': 'ps_hdr', 'rfc': 'RFC 9209 Proxy-Status', 'ident': 'Proxy-Status', 'bug': 'Proxy-Status leftover error;http_request_error dropped so Via looks healthy', 'naive': 'tests used 2xx only', 'wrong': 'append Via hop only', 'fix': 'preserve Proxy-Status error types on 5xx', 'payload': 'error leftover; Next-Hop not listed', 'kind': 'silent-truncate', 'n': 9, 'unit': 'dropped Proxy-Status errors', 'test_naive': 'test_2xx', 'test_gate': 'test_ps', 'hexid': 'ps#1', 'want': "'error;http_request_error'", 'live': 'print(ps_hdr(502))', 'live_bad': "''", 'live_good': "'error;http_request_error'", 'grep': 'Proxy-Status|Via|http_request_error', 'replay': 'Replay', 'success': True},
        {'slug': 'via-hop-count-collapse', 'mod': 'via_hop', 'caller': 'trace_via', 'fn': 'via_add', 'rfc': 'RFC 9110 Via', 'ident': 'Via', 'bug': 'Via leftover collapses received-by so loop detection never fires', 'naive': 'tests used one proxy', 'wrong': 'overwrite Via with last hop', 'fix': 'append each received-by protocol-version', 'payload': 'Via: 1.1 edge leftover hops=1 always', 'kind': 'stale-lock', 'n': 13, 'unit': 'collapsed Via hops', 'test_naive': 'test_onehop', 'test_gate': 'test_via', 'hexid': 'via#2', 'want': "'1.1 a, 1.1 b'", 'live': "print(via_add('1.1 a','1.1 b'))", 'live_bad': "'1.1 b'", 'live_good': "'1.1 a, 1.1 b'", 'grep': 'Via|received-by|hop', 'replay': 'Sweep', 'success': False},
    ),
    (
        {'slug': 'tls-hrr-cookie-ignored', 'mod': 'tls_hrr', 'caller': 'chlo_hrr', 'fn': 'on_hrr', 'rfc': 'RFC 8446 HelloRetryRequest cookie', 'ident': 'HRR cookie', 'bug': 'TLS HRR cookie leftover ignored so ClientHello2 omits cookie extension', 'naive': 'tests used first-try groups', 'wrong': 'retry group only without cookie', 'fix': 'echo cookie on ClientHello2 after HRR', 'payload': 'cookie 0xa1b2 unread; illegal_parameter', 'kind': 'silent-truncate', 'n': 8, 'unit': 'cookie-less ClientHello2s', 'test_naive': 'test_first_group', 'test_gate': 'test_hrr', 'hexid': 'hrr#1', 'want': "'cookie'", 'live': "print(on_hrr(b'\\xa1\\xb2'))", 'live_bad': "b''", 'live_good': "'cookie'", 'grep': 'HRR|cookie|ClientHello2', 'replay': 'Replay', 'success': True},
        {'slug': 'tls-ticket-age-add-skip', 'mod': 'tls_ticket', 'caller': 'psk_binder', 'fn': 'age_add', 'rfc': 'RFC 8446 NewSessionTicket ticket_age_add', 'ident': 'session ticket', 'bug': 'session ticket leftover ticket_age_add unused so obfuscated_ticket_age is raw', 'naive': 'tests used ticket_age=0', 'wrong': 'send ticket identity without age_add', 'fix': 'obfuscated_ticket_age = age + ticket_age_add', 'payload': 'obfuscated leftover 0 while add=0x55aa', 'kind': 'stale-lock', 'n': 10, 'unit': 'raw ticket ages', 'test_naive': 'test_age0', 'test_gate': 'test_ticket', 'hexid': 'nst#2', 'want': '0x55aa', 'live': 'print(hex(age_add(0, 0x55aa)))', 'live_bad': '0x0', 'live_good': '0x55aa', 'grep': 'ticket_age_add|obfuscated|NewSessionTicket', 'replay': 'Sweep', 'success': False},
    ),
    (
        {'slug': 'quic-stop-sending-unread', 'mod': 'quic_ss', 'caller': 'h3_body', 'fn': 'on_ss', 'rfc': 'RFC 9000 STOP_SENDING', 'ident': 'STOP_SENDING', 'bug': 'QUIC STOP_SENDING leftover unread so sender keeps STREAM frames after app abort', 'naive': 'tests used FIN-only streams', 'wrong': 'stop read side only', 'fix': 'reset send and honor STOP_SENDING error code', 'payload': 'STOP_SENDING 0x0104 leftover STREAM 8', 'kind': 'silent-truncate', 'n': 15, 'unit': 'STREAM after STOP_SENDING', 'test_naive': 'test_fin', 'test_gate': 'test_ss', 'hexid': 'ss#1', 'want': "'reset'", 'live': 'print(on_ss(0x104))', 'live_bad': "'stream'", 'live_good': "'reset'", 'grep': 'STOP_SENDING|RESET_STREAM|app_error', 'replay': 'Replay', 'success': True},
        {'slug': 'quic-reset-stream-final-size', 'mod': 'quic_rs', 'caller': 'flow_ctl', 'fn': 'on_rs', 'rfc': 'RFC 9000 RESET_STREAM Final Size', 'ident': 'RESET_STREAM', 'bug': 'RESET_STREAM leftover Final Size ignored so flow credit never returns', 'naive': 'tests used empty streams', 'wrong': 'mark closed without final_size', 'fix': 'apply Final Size to MAX_DATA credit', 'payload': 'final_size leftover 0 vs 4096 sent', 'kind': 'stale-lock', 'n': 12, 'unit': 'stuck flow credits', 'test_naive': 'test_empty', 'test_gate': 'test_rs', 'hexid': 'rs#2', 'want': '4096', 'live': 'print(on_rs(4096))', 'live_bad': '0', 'live_good': '4096', 'grep': 'RESET_STREAM|final_size|MAX_DATA', 'replay': 'Sweep', 'success': False},
    ),
    (
        {'slug': 'h2-window-update-zero', 'mod': 'h2_wu', 'caller': 'h2_flow', 'fn': 'on_wu', 'rfc': 'RFC 9113 WINDOW_UPDATE', 'ident': 'WINDOW_UPDATE 0', 'bug': 'HTTP/2 WINDOW_UPDATE leftover increment 0 treated as ok so PROTOCOL_ERROR never fires', 'naive': 'tests used increment>=1', 'wrong': 'clamp 0 to 1', 'fix': 'PROTOCOL_ERROR on WINDOW_UPDATE increment 0', 'payload': 'WU stream 3 increment leftover 0', 'kind': 'silent-truncate', 'n': 7, 'unit': 'zero WINDOW_UPDATE frames', 'test_naive': 'test_inc1', 'test_gate': 'test_wu0', 'hexid': 'wu#1', 'want': "'PROTOCOL_ERROR'", 'live': 'print(on_wu(0))', 'live_bad': "'ok'", 'live_good': "'PROTOCOL_ERROR'", 'grep': 'WINDOW_UPDATE|increment|PROTOCOL_ERROR', 'replay': 'Replay', 'success': True},
        {'slug': 'h2-settings-ack-skip', 'mod': 'h2_set', 'caller': 'h2_ctrl', 'fn': 'on_set', 'rfc': 'RFC 9113 SETTINGS', 'ident': 'SETTINGS', 'bug': 'HTTP/2 SETTINGS leftover ACK skipped so INITIAL_WINDOW_SIZE never applies', 'naive': 'tests used default 65535', 'wrong': 'ACK empty SETTINGS only', 'fix': 'apply SETTINGS then send ACK', 'payload': 'SETTINGS leftover window still 65535', 'kind': 'stale-lock', 'n': 16, 'unit': 'unacked SETTINGS', 'test_naive': 'test_defwin', 'test_gate': 'test_set', 'hexid': 'set#2', 'want': '1048576', 'live': 'print(on_set(1048576))', 'live_bad': '65535', 'live_good': '1048576', 'grep': 'SETTINGS|ACK|INITIAL_WINDOW_SIZE', 'replay': 'Sweep', 'success': False},
    ),
    (
        {'slug': 'h3-qpack-blocked-streams', 'mod': 'h3_qpack', 'caller': 'h3_dec', 'fn': 'on_blocked', 'rfc': 'RFC 9204 QPACK', 'ident': 'QPACK', 'bug': 'HTTP/3 QPACK leftover blocked streams ignored so decoder never sends STREAM_CANCELLED', 'naive': 'tests used never-blocked tables', 'wrong': 'increase max_table_capacity only', 'fix': 'honor QPACK blocked-streams and cancel excess', 'payload': 'blocked leftover 2 > SETTINGS 1', 'kind': 'silent-truncate', 'n': 6, 'unit': 'blocked QPACK streams', 'test_naive': 'test_unblocked', 'test_gate': 'test_qpack', 'hexid': 'qp#1', 'want': "'cancel'", 'live': 'print(on_blocked(2,1))', 'live_bad': "'ok'", 'live_good': "'cancel'", 'grep': 'QPACK|blocked|STREAM_CANCELLED', 'replay': 'Replay', 'success': True},
        {'slug': 'hpack-never-index-skip', 'mod': 'h2_hpack', 'caller': 'h2_hdr', 'fn': 'on_ni', 'rfc': 'RFC 7541 HPACK never-indexed', 'ident': 'HPACK', 'bug': 'HPACK leftover never-indexed literals still enter dynamic table', 'naive': 'tests used cookie-less requests', 'wrong': 'evict oldest only', 'fix': 'never index Literal never-indexed (0x10)', 'payload': 'cookie leftover in dynamic table idx 62', 'kind': 'stale-lock', 'n': 11, 'unit': 'indexed cookies', 'test_naive': 'test_nocookie', 'test_gate': 'test_hpack', 'hexid': 'hp#2', 'want': "'never'", 'live': "print(on_ni('cookie'))", 'live_bad': "'idx62'", 'live_good': "'never'", 'grep': 'HPACK|never-indexed|0x10', 'replay': 'Sweep', 'success': False},
    ),
    (
        {'slug': 'ws-close-1006-abnormal', 'mod': 'ws_1006', 'caller': 'ws_cli', 'fn': 'on_abn', 'rfc': 'RFC 6455 close 1006', 'ident': 'close 1006', 'bug': 'WebSocket close 1006 leftover mapped to 1000 so clients retry as clean close', 'naive': 'tests used server 1000 only', 'wrong': 'emit 1000 on TCP drop', 'fix': 'surface 1006 abnormal without a close frame', 'payload': 'TCP RST leftover reported 1000', 'kind': 'silent-truncate', 'n': 9, 'unit': 'false clean closes', 'test_naive': 'test_1000', 'test_gate': 'test_1006', 'hexid': 'ws6#1', 'want': '1006', 'live': 'print(on_abn())', 'live_bad': '1000', 'live_good': '1006', 'grep': '1006|abnormal|close', 'replay': 'Replay', 'success': True},
        {'slug': 'ws-close-1011-unexpected', 'mod': 'ws_1011', 'caller': 'ws_srv', 'fn': 'on_err', 'rfc': 'RFC 6455 close 1011', 'ident': 'close 1011', 'bug': 'WebSocket close 1011 leftover collapsed to 1006 so unexpected errors look like network', 'naive': 'tests used RST only', 'wrong': 'always 1006 on exception', 'fix': 'send 1011 unexpected condition then TCP close', 'payload': 'handler leftover 1006 instead of 1011', 'kind': 'stale-lock', 'n': 8, 'unit': 'masked 1011 closes', 'test_naive': 'test_rst', 'test_gate': 'test_1011', 'hexid': 'ws11#2', 'want': '1011', 'live': 'print(on_err(RuntimeError()))', 'live_bad': '1006', 'live_good': '1011', 'grep': '1011|unexpected|close', 'replay': 'Sweep', 'success': False},
    ),
    (
        {'slug': 'smtp-starttls-downgrade', 'mod': 'smtp_tls', 'caller': 'mta_out', 'fn': 'do_starttls', 'rfc': 'RFC 3207 STARTTLS', 'ident': 'STARTTLS', 'bug': 'SMTP leftover STARTTLS EHLO not reset so AUTH leftover from cleartext', 'naive': 'tests used implicit TLS 465', 'wrong': 'send AUTH before second EHLO', 'fix': 'reset EHLO after 220 Ready to start TLS', 'payload': 'AUTH leftover PLAIN pre-TLS', 'kind': 'silent-truncate', 'n': 10, 'unit': 'cleartext AUTH after STARTTLS', 'test_naive': 'test_465', 'test_gate': 'test_starttls', 'hexid': 'smtls#1', 'want': "'ehlo2'", 'live': 'print(do_starttls())', 'live_bad': "'auth'", 'live_good': "'ehlo2'", 'grep': 'STARTTLS|EHLO|AUTH', 'replay': 'Replay', 'success': True},
        {'slug': 'smtp-pipelining-rset', 'mod': 'smtp_pipe', 'caller': 'mta_pipe', 'fn': 'on_pipe', 'rfc': 'RFC 2920 PIPELINING', 'ident': 'PIPELINING', 'bug': 'SMTP leftover PIPELINING sends RSET grouped so 250 grouping desyncs', 'naive': 'tests used one command per RTT', 'wrong': 'pipeline MAIL+RCPT only', 'fix': 'never pipeline RSET or non-groupable verbs', 'payload': 'RSET leftover in pipeline; 503 leftover', 'kind': 'stale-lock', 'n': 12, 'unit': 'desynced SMTP groups', 'test_naive': 'test_serial', 'test_gate': 'test_pipe', 'hexid': 'pipe#2', 'want': "'serial-rset'", 'live': "print(on_pipe('RSET'))", 'live_bad': "'group'", 'live_good': "'serial-rset'", 'grep': 'PIPELINING|RSET|group', 'replay': 'Sweep', 'success': False},
    ),
    (
        {'slug': 'imap-idle-done-skip', 'mod': 'imap_idle', 'caller': 'imap_sync', 'fn': 'on_idle', 'rfc': 'RFC 2177 IDLE', 'ident': 'IDLE', 'bug': 'IMAP leftover IDLE never sends DONE so server holds the connection', 'naive': 'tests used NOOP poll', 'wrong': 'close TCP instead of DONE', 'fix': 'write DONE then tagged OK before next command', 'payload': 'IDLE leftover no DONE; EXISTS unread', 'kind': 'silent-truncate', 'n': 7, 'unit': 'stuck IDLE sessions', 'test_naive': 'test_noop', 'test_gate': 'test_idle', 'hexid': 'idle#1', 'want': "'DONE'", 'live': 'print(on_idle())', 'live_bad': "'tcp-close'", 'live_good': "'DONE'", 'grep': 'IDLE|DONE|EXISTS', 'replay': 'Replay', 'success': True},
        {'slug': 'imap-compress-deflate-reset', 'mod': 'imap_comp', 'caller': 'imap_io', 'fn': 'on_comp', 'rfc': 'RFC 4978 COMPRESS=DEFLATE', 'ident': 'COMPRESS', 'bug': 'IMAP leftover COMPRESS does not reset inflater on literal so mailbox bytes corrupt', 'naive': 'tests used empty FETCH', 'wrong': 'flush compressor only', 'fix': 'SYNC_FLUSH both directions after tagged OK', 'payload': 'COMPRESS leftover Z_DATA_ERROR on FETCH', 'kind': 'stale-lock', 'n': 9, 'unit': 'corrupt IMAP literals', 'test_naive': 'test_empty_fetch', 'test_gate': 'test_comp', 'hexid': 'cmp#2', 'want': "'sync_flush'", 'live': 'print(on_comp())', 'live_bad': "'flush-out'", 'live_good': "'sync_flush'", 'grep': 'COMPRESS|DEFLATE|SYNC_FLUSH', 'replay': 'Sweep', 'success': False},
    ),
    (
        {'slug': 'pop3-stls-capa-stale', 'mod': 'pop3_stls', 'caller': 'pop_cli', 'fn': 'on_stls', 'rfc': 'RFC 2595 STLS', 'ident': 'STLS', 'bug': 'POP3 leftover STLS reuses CAPA from cleartext so USER leftover advertised', 'naive': 'tests used POP3S 995', 'wrong': 'STLS without CAPA refresh', 'fix': 're-CAPA after +OK Begin TLS', 'payload': 'USER leftover on encrypted session', 'kind': 'silent-truncate', 'n': 8, 'unit': 'stale POP3 CAPA', 'test_naive': 'test_995', 'test_gate': 'test_stls', 'hexid': 'stls#1', 'want': "'capa2'", 'live': 'print(on_stls())', 'live_bad': "'user'", 'live_good': "'capa2'", 'grep': 'STLS|CAPA|USER', 'replay': 'Replay', 'success': True},
        {'slug': 'pop3-top-octet-count', 'mod': 'pop3_top', 'caller': 'pop_retr', 'fn': 'on_top', 'rfc': 'RFC 1939 TOP', 'ident': 'TOP', 'bug': 'POP3 leftover TOP n treats n as octets not lines so headers truncate', 'naive': 'tests used TOP 0', 'wrong': 'slice n bytes', 'fix': 'return first n lines after blank line', 'payload': 'TOP leftover 10 bytes of 80-line hdr', 'kind': 'stale-lock', 'n': 11, 'unit': 'truncated TOP headers', 'test_naive': 'test_top0', 'test_gate': 'test_top', 'hexid': 'top#2', 'want': "'10lines'", 'live': 'print(on_top(10))', 'live_bad': "'10bytes'", 'live_good': "'10lines'", 'grep': 'TOP|lines|octet', 'replay': 'Sweep', 'success': False},
    ),
    (
        {'slug': 'ftp-epsv-proto-mismatch', 'mod': 'ftp_epsv', 'caller': 'ftp_pasv', 'fn': 'on_epsv', 'rfc': 'RFC 2428 EPSV', 'ident': 'EPSV', 'bug': 'FTP leftover EPSV parses PASV 227 tuple so IPv6 data conn never opens', 'naive': 'tests used IPv4 PASV', 'wrong': 'regex 227 only', 'fix': 'parse 229 Entering Extended Passive Mode (|||port|)', 'payload': 'EPSV leftover 227 host leftover', 'kind': 'silent-truncate', 'n': 6, 'unit': 'failed EPSV data conns', 'test_naive': 'test_pasv4', 'test_gate': 'test_epsv', 'hexid': 'epsv#1', 'want': '229', 'live': "print(on_epsv('229 (|||2121|)'))", 'live_bad': '0', 'live_good': '229', 'grep': 'EPSV|229|PASV', 'replay': 'Replay', 'success': True},
        {'slug': 'ftp-rest-restart-marker', 'mod': 'ftp_rest', 'caller': 'ftp_retr', 'fn': 'on_rest', 'rfc': 'RFC 3659 REST STREAM', 'ident': 'REST', 'bug': 'FTP leftover REST marker applied as ASCII offset on IMAGE so restart skips bytes', 'naive': 'tests used ASCII TYPE A', 'wrong': 'REST 0 after TYPE I', 'fix': 'apply REST marker as byte offset in IMAGE', 'payload': 'REST leftover 100 as line leftover', 'kind': 'stale-lock', 'n': 14, 'unit': 'misaligned REST RETRs', 'test_naive': 'test_typea', 'test_gate': 'test_rest', 'hexid': 'rest#2', 'want': '100', 'live': "print(on_rest(100, 'I'))", 'live_bad': '0', 'live_good': '100', 'grep': 'REST|STREAM|TYPE I', 'replay': 'Sweep', 'success': False},
    ),
    (
        {'slug': 'dns-edns-cookie-bad-server', 'mod': 'dns_ck', 'caller': 'recursor', 'fn': 'on_cookie', 'rfc': 'RFC 7873 EDNS COOKIE', 'ident': 'EDNS COOKIE', 'bug': 'DNS leftover EDNS COOKIE BADCOOKIE not retried so clients fall to UDP timeout', 'naive': 'tests used cookie-less servers', 'wrong': 'strip OPT on SERVFAIL', 'fix': 'retry UDP with server cookie after BADCOOKIE', 'payload': 'BADCOOKIE leftover RCODE 23 unused', 'kind': 'silent-truncate', 'n': 10, 'unit': 'unretried BADCOOKIE', 'test_naive': 'test_nocookie', 'test_gate': 'test_cookie', 'hexid': 'ck#1', 'want': "'retry'", 'live': 'print(on_cookie(23))', 'live_bad': "'servfail'", 'live_good': "'retry'", 'grep': 'COOKIE|BADCOOKIE|OPT', 'replay': 'Replay', 'success': True},
        {'slug': 'dns-tcp-tc-fallback-skip', 'mod': 'dns_tcp', 'caller': 'stub', 'fn': 'on_tc', 'rfc': 'RFC 7766 DNS over TCP', 'ident': 'DNS TCP', 'bug': 'DNS leftover TCP fallback skipped on TC so answers stay truncated', 'naive': 'tests used small TXT', 'wrong': 'retry UDP only', 'fix': 'open TCP and resend when TC=1', 'payload': 'TC leftover 1; UDP retry leftover', 'kind': 'stale-lock', 'n': 13, 'unit': 'truncated DNS answers', 'test_naive': 'test_smalltxt', 'test_gate': 'test_tcp', 'hexid': 'tcp#2', 'want': "'tcp'", 'live': 'print(on_tc(1))', 'live_bad': "'udp'", 'live_good': "'tcp'", 'grep': 'TC|TCP|fallback', 'replay': 'Sweep', 'success': False},
    ),
    (
        {'slug': 'ntp-kiss-deny-ignored', 'mod': 'ntp_kiss', 'caller': 'ntp_cli', 'fn': 'on_kiss', 'rfc': "RFC 5905 Kiss-o'-Death", 'ident': 'Kiss-o-Death', 'bug': 'NTP leftover Kiss-o-Death DENY ignored so client keeps pounding stratum', 'naive': 'tests used stratum 2 only', 'wrong': 'treat leap 3 as unsync only', 'fix': 'stop querying on KoD DENY/RSTR', 'payload': 'stratum leftover 0 refid DENY', 'kind': 'silent-truncate', 'n': 8, 'unit': 'ignored KoD DENY', 'test_naive': 'test_s2', 'test_gate': 'test_kiss', 'hexid': 'kod#1', 'want': "'stop'", 'live': "print(on_kiss('DENY'))", 'live_bad': "'retry'", 'live_good': "'stop'", 'grep': 'Kiss|DENY|stratum', 'replay': 'Replay', 'success': True},
        {'slug': 'ntp-leap-indicator-smear', 'mod': 'ntp_leap', 'caller': 'chrony', 'fn': 'on_leap', 'rfc': 'RFC 5905 leap indicator', 'ident': 'leap', 'bug': 'NTP leftover leap LI=2 smear skipped so clocks insert a second twice', 'naive': 'tests used LI=0', 'wrong': 'ignore LI!=0', 'fix': 'honor leap 1/2 in timescale', 'payload': 'LI leftover 2; smear leftover 0', 'kind': 'stale-lock', 'n': 5, 'unit': 'double leap seconds', 'test_naive': 'test_li0', 'test_gate': 'test_leap', 'hexid': 'leap#2', 'want': '2', 'live': 'print(on_leap(2))', 'live_bad': '0', 'live_good': '2', 'grep': 'leap|LI|smear', 'replay': 'Sweep', 'success': False},
    ),
    (
        {'slug': 'bgp-graceful-restart-stale', 'mod': 'bgp_gr', 'caller': 'rr_gr', 'fn': 'on_gr', 'rfc': 'RFC 4724 GRACEFUL_RESTART', 'ident': 'GRACEFUL_RESTART', 'bug': 'BGP leftover GRACEFUL_RESTART does not preserve forwarding so stale paths drop', 'naive': 'tests used hard reset', 'wrong': 'keep Adj-RIB-In only', 'fix': 'preserve FIB during Restart Time', 'payload': 'GR leftover End-of-RIB never sent', 'kind': 'silent-truncate', 'n': 9, 'unit': 'dropped GR paths', 'test_naive': 'test_hard', 'test_gate': 'test_gr', 'hexid': 'gr#1', 'want': "'fib-hold'", 'live': 'print(on_gr())', 'live_bad': "'drop-fib'", 'live_good': "'fib-hold'", 'grep': 'GRACEFUL_RESTART|End-of-RIB|Restart Time', 'replay': 'Replay', 'success': True},
        {'slug': 'bgp-hold-timer-keepalive-skip', 'mod': 'bgp_hold', 'caller': 'peer_fsm', 'fn': 'on_hold', 'rfc': 'RFC 4271 Hold Timer', 'ident': 'hold', 'bug': 'BGP leftover hold timer not reset on KEEPALIVE so session flaps at Hold Time', 'naive': 'tests used Hold=0 infinite', 'wrong': 'reset on UPDATE only', 'fix': 'reset Hold Timer on any KEEPALIVE or UPDATE', 'payload': 'KEEPALIVE leftover hold leftover 90s', 'kind': 'stale-lock', 'n': 11, 'unit': 'hold-timer flaps', 'test_naive': 'test_hold0', 'test_gate': 'test_hold', 'hexid': 'hold#2', 'want': "'reset'", 'live': "print(on_hold('KA'))", 'live_bad': "'expire'", 'live_good': "'reset'", 'grep': 'Hold|KEEPALIVE|Hold Time', 'replay': 'Sweep', 'success': False},
    ),
    (
        {'slug': 'grpc-goaway-http2-laststream', 'mod': 'grpc_ga', 'caller': 'grpc_ch', 'fn': 'on_ga', 'rfc': 'gRPC HTTP/2 GOAWAY', 'ident': 'GOAWAY', 'bug': 'gRPC leftover GOAWAY Last-Stream-ID ignored so new RPCs land on draining conn', 'naive': 'tests used unary only', 'wrong': 'close after in-flight 0', 'fix': 'stop new streams after Last-Stream-ID', 'payload': 'GOAWAY leftover last=7; rpc leftover 9', 'kind': 'silent-truncate', 'n': 10, 'unit': 'RPCs after GOAWAY', 'test_naive': 'test_unary', 'test_gate': 'test_ga', 'hexid': 'ga#1', 'want': "'drain'", 'live': 'print(on_ga(7,9))', 'live_bad': "'send9'", 'live_good': "'drain'", 'grep': 'GOAWAY|Last-Stream-ID|drain', 'replay': 'Replay', 'success': True},
        {'slug': 'grpc-rst-stream-trailers', 'mod': 'grpc_rst', 'caller': 'grpc_call', 'fn': 'on_rst', 'rfc': 'gRPC RST_STREAM', 'ident': 'RST_STREAM', 'bug': 'gRPC leftover RST_STREAM maps CANCEL to OK if trailers already sent', 'naive': 'tests used status OK trailers', 'wrong': 'ignore RST after trailers', 'fix': 'surface CANCEL even if trailers raced', 'payload': 'RST leftover CANCEL after grpc-status 0', 'kind': 'stale-lock', 'n': 7, 'unit': 'false OK after RST', 'test_naive': 'test_ok_trailers', 'test_gate': 'test_rst', 'hexid': 'rst#2', 'want': "'CANCEL'", 'live': "print(on_rst('CANCEL', 0))", 'live_bad': "'OK'", 'live_good': "'CANCEL'", 'grep': 'RST_STREAM|CANCEL|grpc-status', 'replay': 'Sweep', 'success': False},
    ),
    (
        {'slug': 'http-103-early-hints-drop', 'mod': 'http_103', 'caller': 'edge_hints', 'fn': 'on_103', 'rfc': 'RFC 8297 103 Early Hints', 'ident': '103 Early Hints', 'bug': 'HTTP leftover 103 Early Hints dropped so Link preload never fires', 'naive': 'tests used final 200 only', 'wrong': 'buffer until 200', 'fix': 'forward 103 with Link before final status', 'payload': '103 leftover swallowed by hop-by-hop', 'kind': 'silent-truncate', 'n': 8, 'unit': 'dropped Early Hints', 'test_naive': 'test_200', 'test_gate': 'test_103', 'hexid': 'h103#1', 'want': "'103'", 'live': 'print(on_103())', 'live_bad': "'wait200'", 'live_good': "'103'", 'grep': '103|Early Hints|Link', 'replay': 'Replay', 'success': True},
        {'slug': 'http-421-misdirected-retry', 'mod': 'http_421', 'caller': 'h2_origin', 'fn': 'on_421', 'rfc': 'RFC 9113 421 Misdirected Request', 'ident': '421 Misdirected', 'bug': 'HTTP leftover 421 Misdirected treated as 404 so coalesced conn never retries origin', 'naive': 'tests used single origin', 'wrong': 'map 421 to 404', 'fix': 'retry on a connection bound to that authority', 'payload': '421 leftover :authority leftover alt', 'kind': 'stale-lock', 'n': 12, 'unit': 'unretried 421s', 'test_naive': 'test_one_origin', 'test_gate': 'test_421', 'hexid': 'h421#2', 'want': "'retry-auth'", 'live': 'print(on_421())', 'live_bad': "'404'", 'live_good': "'retry-auth'", 'grep': '421|Misdirected|:authority', 'replay': 'Sweep', 'success': False},
    ),
)
