#!/usr/bin/env python3
"""Deterministic record-level identity and provenance curation.

``curate_record`` is a pure function: a caller supplies one decoded JSON
record and its immutable source coordinate.  Authority comes from the
reviewed factory registry at ``config/FACTORY-REGISTRY.json`` (exact
``path_id`` then exact ``payload_factory``), not from a hard-coded slug.
Onboard a generator by adding a reviewed row; do not edit this file.

``write_run`` is the tree writer.  A cleaned/curated destination receives
the exact reviewed ``FACTORY-REGISTRY.json`` bytes plus
``IDENTITY-MANIFEST.json`` (a list of mappings).  Pin = SHA-256 of those
sidecar bytes.  Registry version is not stamped onto record payloads.
"""

from __future__ import annotations

import argparse
import copy
import hashlib
import json
import os
import re
import sys
from collections import Counter
from dataclasses import dataclass
from pathlib import Path, PurePosixPath
from typing import Any, Iterable, Mapping

from record_kind import (
    PREFERENCE_SIDE_KINDS,
    SUPPORTED_RECORD_KINDS,
    classify_kind,
    preference_side_kinds,
)
from round_txn import TransactionError, committed_jsonl_paths, marker_mode_path
from validate_run import check_multi_agent, check_safety_case

TRANSFORM_NAME = "curate_identity"
TRANSFORM_VERSION = "identity-provenance-v2"
ID_NAMESPACE = "spikenaut.synthetic-factory.curated-record"

CANONICAL_PROVENANCE = frozenset({"designed", "simulated", "hil"})
CONTRACT_REQUIRE_STATE = "require_state_claim"
CONTRACT_SHAPE_DESIGNED = "synthetic_shape_implies_designed"
ALLOWED_CONTRACTS = frozenset({CONTRACT_REQUIRE_STATE, CONTRACT_SHAPE_DESIGNED})
SHAPE_BASIS = {
    "episode": "synthetic_factory_episode_shape",
    "preference": "synthetic_factory_preference_shape",
    "safety_case": "synthetic_factory_safety_case_shape",
    "multi_agent": "synthetic_factory_multi_agent_shape",
}
LEGACY_ID_KEYS = ("id", "record_id", "trajectory_id", "episode_id", "pair_id")
SHA256_RE = re.compile(r"^[0-9a-f]{64}$")
HIL_RE = re.compile(r"\bhil\b", re.IGNORECASE)
# Standalone 'real'/'live' claims only: 'realistic' and 'real-time' describe a
# simulation and must not be read as a real-world deployment claim.
REAL_WORLD_RE = re.compile(r"^(?:real|live)(?![\w-])", re.IGNORECASE)

FACTORY_REGISTRY_PATH = (
    Path(__file__).resolve().parents[1] / "config" / "FACTORY-REGISTRY.json"
)
FACTORY_REGISTRY_SIDECAR = "FACTORY-REGISTRY.json"
IDENTITY_MANIFEST_SIDECAR = "IDENTITY-MANIFEST.json"
REGISTRY_SCHEMA_VERSION = "factory-registry-v0.1"

_DEFAULT_REGISTRY: FactoryRegistry | None = None


class IdentityCurationError(ValueError):
    """Base class for caller-contract and batch-integrity failures."""


class CanonicalIdCollision(IdentityCurationError):
    """Raised when two retained source records resolve to one canonical ID."""


class IdentityTreeError(IdentityCurationError):
    """Raised when a cleaned tree is missing or mismatched identity sidecars."""


@dataclass(frozen=True)
class SourceRecord:
    """A decoded record paired with its immutable, run-relative source identity.

    When supplied, ``source_sha256`` is the digest of the exact UTF-8 JSONL
    record bytes with the line terminator excluded.  Minimal fixtures may omit
    it; their mapping records that canonical JSON was hashed instead.
    """

    record: Mapping[str, Any]
    source_path: str
    source_line: int
    source_sha256: str | None = None


@dataclass(frozen=True)
class CurationResult:
    """One deterministic retain/exclude decision and its reversible mapping."""

    action: str
    record: dict[str, Any] | None
    mapping: dict[str, Any]


@dataclass(frozen=True)
class _SourceIdentity:
    path: str
    line: int
    factory: str
    sha256: str
    hash_basis: str


@dataclass(frozen=True)
class FactoryRow:
    path_id: str
    payload_factory: str
    generator: str
    generator_version: str
    record_kinds: frozenset[str]
    identity_authoritative: bool
    publication_target: str | None
    training_ready_policy: str
    allowed_curation_lanes: tuple[str, ...]
    provenance_contract_by_kind: Mapping[str, str]
    preference_side_kinds: frozenset[str] = frozenset()


@dataclass(frozen=True)
class FactoryRegistry:
    """Reviewed factory table plus the exact bytes that pin a cleaned tree."""

    schema_version: str
    sha256: str
    raw_bytes: bytes
    by_path_id: Mapping[str, FactoryRow]


def canonical_json(value: Any) -> str:
    """Serialize JSON data byte-stably for hashes, tests, and output sidecars."""

    try:
        return json.dumps(
            value,
            ensure_ascii=False,
            allow_nan=False,
            sort_keys=True,
            separators=(",", ":"),
        )
    except (TypeError, ValueError) as exc:
        raise IdentityCurationError(f"record is not canonical JSON data: {exc}") from exc


def _sha256_json(value: Any) -> str:
    return hashlib.sha256(canonical_json(value).encode("utf-8")).hexdigest()


def _sha256_bytes(payload: bytes) -> str:
    return hashlib.sha256(payload).hexdigest()


def _iter_jsonl_record_bytes(payload: bytes) -> Iterable[tuple[int, bytes]]:
    """Yield records framed only by LF, excluding one CR from a CRLF ending."""

    for line_no, record_bytes in enumerate(payload.split(b"\n"), 1):
        if record_bytes.endswith(b"\r"):
            record_bytes = record_bytes[:-1]
        yield line_no, record_bytes


def _reject_json_constant(value: str) -> None:
    raise ValueError(f"non-standard JSON numeric constant {value}")


def _reject_training_ready_true(value: Any, path: str = "$") -> None:
    if isinstance(value, Mapping):
        if value.get("training_ready"):
            raise IdentityCurationError(
                f"{path} must not contain training_ready: true"
            )
        for key, item in value.items():
            _reject_training_ready_true(item, f"{path}.{key}")
    elif isinstance(value, list):
        for index, item in enumerate(value):
            _reject_training_ready_true(item, f"{path}[{index}]")


def _parse_factory_row(raw: Any, index: int) -> FactoryRow:
    if not isinstance(raw, Mapping):
        raise IdentityCurationError(f"factories[{index}] must be an object")
    required = (
        "path_id",
        "payload_factory",
        "generator",
        "generator_version",
        "record_kinds",
        "identity_authoritative",
        "publication_target",
        "training_ready_policy",
        "allowed_curation_lanes",
        "provenance_contract_by_kind",
    )
    missing = [key for key in required if key not in raw]
    if missing:
        raise IdentityCurationError(
            f"factories[{index}] missing fields: {missing}"
        )
    path_id = raw["path_id"]
    payload_factory = raw["payload_factory"]
    if not isinstance(path_id, str) or not path_id.strip():
        raise IdentityCurationError(f"factories[{index}].path_id must be a string")
    if not isinstance(payload_factory, str) or not payload_factory.strip():
        raise IdentityCurationError(
            f"factories[{index}].payload_factory must be a string"
        )
    kinds_raw = raw["record_kinds"]
    if not isinstance(kinds_raw, list) or not kinds_raw:
        raise IdentityCurationError(
            f"factories[{index}].record_kinds must be a non-empty list"
        )
    if not all(isinstance(kind, str) and kind for kind in kinds_raw):
        raise IdentityCurationError(
            f"factories[{index}].record_kinds must be strings"
        )
    if len(kinds_raw) != len(set(kinds_raw)):
        raise IdentityCurationError(
            f"factories[{index}].record_kinds must not contain duplicates"
        )
    unsupported_kinds = sorted(set(kinds_raw) - SUPPORTED_RECORD_KINDS)
    if unsupported_kinds:
        raise IdentityCurationError(
            f"factories[{index}].record_kinds contains unsupported kinds: "
            f"{unsupported_kinds}"
        )
    kinds = frozenset(kinds_raw)
    if not isinstance(raw["identity_authoritative"], bool):
        raise IdentityCurationError(
            f"factories[{index}].identity_authoritative must be a boolean"
        )
    publication_target = raw["publication_target"]
    if publication_target is not None and not isinstance(publication_target, str):
        raise IdentityCurationError(
            f"factories[{index}].publication_target must be null or a string"
        )
    policy = raw["training_ready_policy"]
    if policy not in {"never", "compose_eligible"}:
        raise IdentityCurationError(
            f"factories[{index}].training_ready_policy must be never or compose_eligible"
        )
    lanes = raw["allowed_curation_lanes"]
    if not isinstance(lanes, list) or not all(isinstance(item, str) for item in lanes):
        raise IdentityCurationError(
            f"factories[{index}].allowed_curation_lanes must be a list of strings"
        )
    contracts = raw["provenance_contract_by_kind"]
    if not isinstance(contracts, Mapping):
        raise IdentityCurationError(
            f"factories[{index}].provenance_contract_by_kind must be an object"
        )
    for kind in kinds:
        contract = contracts.get(kind)
        if contract not in ALLOWED_CONTRACTS:
            raise IdentityCurationError(
                f"factories[{index}] missing allowed provenance_contract for {kind}"
            )
        if contract == CONTRACT_SHAPE_DESIGNED and not raw["identity_authoritative"]:
            raise IdentityCurationError(
                f"factories[{index}] synthetic_shape_implies_designed requires "
                "identity_authoritative"
            )
    preference_kinds_raw = raw.get("preference_side_kinds")
    if "preference" in kinds:
        if not isinstance(preference_kinds_raw, list) or not preference_kinds_raw:
            raise IdentityCurationError(
                f"factories[{index}].preference_side_kinds must be a non-empty list"
            )
        if not all(isinstance(kind, str) for kind in preference_kinds_raw):
            raise IdentityCurationError(
                f"factories[{index}].preference_side_kinds must be strings"
            )
        if len(preference_kinds_raw) != len(set(preference_kinds_raw)):
            raise IdentityCurationError(
                f"factories[{index}].preference_side_kinds must not contain duplicates"
            )
        unsupported_side_kinds = sorted(
            set(preference_kinds_raw) - PREFERENCE_SIDE_KINDS
        )
        if unsupported_side_kinds:
            raise IdentityCurationError(
                f"factories[{index}].preference_side_kinds contains unsupported "
                f"kinds: {unsupported_side_kinds}"
            )
    elif preference_kinds_raw is not None:
        raise IdentityCurationError(
            f"factories[{index}].preference_side_kinds requires preference authority"
        )
    return FactoryRow(
        path_id=path_id,
        payload_factory=payload_factory,
        generator=str(raw["generator"]),
        generator_version=str(raw["generator_version"]),
        record_kinds=kinds,
        identity_authoritative=raw["identity_authoritative"],
        publication_target=publication_target,
        training_ready_policy=policy,
        allowed_curation_lanes=tuple(lanes),
        provenance_contract_by_kind={
            str(key): str(value) for key, value in contracts.items()
        },
        preference_side_kinds=frozenset(preference_kinds_raw or ()),
    )


def load_registry(path: Path | None = None) -> FactoryRegistry:
    """Load reviewed registry bytes. Pin = SHA-256 of those exact bytes."""

    registry_path = Path(FACTORY_REGISTRY_PATH if path is None else path)
    try:
        raw_bytes = registry_path.read_bytes()
    except OSError as exc:
        raise IdentityCurationError(
            f"factory registry is unreadable: {registry_path}: {exc}"
        ) from exc
    try:
        payload = json.loads(
            raw_bytes.decode("utf-8"), parse_constant=_reject_json_constant
        )
    except (UnicodeDecodeError, json.JSONDecodeError, ValueError) as exc:
        raise IdentityCurationError(
            f"factory registry is not UTF-8 JSON: {registry_path}: {exc}"
        ) from exc
    if not isinstance(payload, Mapping):
        raise IdentityCurationError("factory registry must be a JSON object")
    _reject_training_ready_true(payload)
    schema_version = payload.get("schema_version")
    if schema_version != REGISTRY_SCHEMA_VERSION:
        raise IdentityCurationError(
            f"factory registry schema_version must be {REGISTRY_SCHEMA_VERSION}"
        )
    if payload.get("lookup_key") != "path_id":
        raise IdentityCurationError("factory registry lookup_key must be path_id")
    factories = payload.get("factories")
    if not isinstance(factories, list) or not factories:
        raise IdentityCurationError("factory registry factories must be a non-empty list")
    by_path_id: dict[str, FactoryRow] = {}
    for index, raw_row in enumerate(factories):
        row = _parse_factory_row(raw_row, index)
        if row.path_id in by_path_id:
            raise IdentityCurationError(f"duplicate registry path_id: {row.path_id}")
        by_path_id[row.path_id] = row
    return FactoryRegistry(
        schema_version=schema_version,
        sha256=_sha256_bytes(raw_bytes),
        raw_bytes=raw_bytes,
        by_path_id=by_path_id,
    )


def default_registry() -> FactoryRegistry:
    """Return the committed reviewed registry, loaded once per process."""

    global _DEFAULT_REGISTRY
    if _DEFAULT_REGISTRY is None:
        _DEFAULT_REGISTRY = load_registry(FACTORY_REGISTRY_PATH)
    return _DEFAULT_REGISTRY


def _normalize_source_path(value: str) -> tuple[str, str]:
    if not isinstance(value, str) or not value.strip():
        raise IdentityCurationError("source_path must be a non-empty relative path")
    raw = value.strip().replace("\\", "/")
    path = PurePosixPath(raw)
    if path.is_absolute() or any(part in {"", ".", ".."} for part in path.parts):
        raise IdentityCurationError(
            "source_path must be normalized, relative, and contain no '.' or '..'"
        )
    if len(path.parts) < 2:
        raise IdentityCurationError(
            "source_path must include a factory directory and a source filename"
        )
    normalized = path.as_posix()
    if normalized != raw:
        raise IdentityCurationError(
            f"source_path is not normalized: {value!r}; use {normalized!r}"
        )
    return normalized, path.parts[0]


def _source_identity(source: SourceRecord) -> _SourceIdentity:
    if (
        not isinstance(source.source_line, int)
        or isinstance(source.source_line, bool)
        or source.source_line < 1
    ):
        raise IdentityCurationError("source_line must be a positive integer")
    path, factory = _normalize_source_path(source.source_path)
    if source.source_sha256 is None:
        digest = _sha256_json(source.record)
        basis = "canonical-json-sha256"
    else:
        digest = str(source.source_sha256).lower()
        if not SHA256_RE.fullmatch(digest):
            raise IdentityCurationError(
                "source_sha256 must be exactly 64 hexadecimal characters"
            )
        basis = "source-json-line-sha256"
    return _SourceIdentity(path, source.source_line, factory, digest, basis)


def record_kind(record: Mapping[str, Any]) -> str:
    """Classify using the shared census-order classifier.

    Unknown shapes raise so ``curate_record`` can exclude them as
    ``identity.unsupported_record_shape``.
    """

    if not isinstance(record, Mapping):
        raise IdentityCurationError("record must be a JSON object")
    kind = classify_kind(record)
    if kind == "unknown":
        raise IdentityCurationError(
            f"unsupported record shape (keys: {sorted(map(str, record.keys()))[:8]})"
        )
    return kind


def _payload_factory(record: Mapping[str, Any]) -> str | None:
    meta = record.get("meta")
    if not isinstance(meta, Mapping):
        return None
    value = meta.get("factory")
    if not isinstance(value, str) or not value.strip():
        return None
    return value


def _canonical_id(source: _SourceIdentity, kind: str, role: str) -> str:
    preimage = canonical_json(
        {
            "namespace": ID_NAMESPACE,
            "transform_version": TRANSFORM_VERSION,
            "source_path": source.path,
            "source_line": source.line,
            "record_kind": kind,
            "owner_role": role,
        }
    )
    digest = hashlib.sha256(preimage.encode("utf-8")).hexdigest()
    role_name = "record" if role == "/" else "trajectory"
    return f"sfcur-{kind}-{role_name}-{digest}"


def _pointer(base: str, key: str) -> str:
    escaped = key.replace("~", "~0").replace("/", "~1")
    return f"/{escaped}" if base == "/" else f"{base}/{escaped}"


def _legacy_ids(owner: Mapping[str, Any], owner_path: str) -> list[dict[str, Any]]:
    forms: list[dict[str, Any]] = []

    def collect(container: Any, base: str) -> None:
        if not isinstance(container, Mapping):
            return
        for key in LEGACY_ID_KEYS:
            if key in container:
                forms.append({"path": _pointer(base, key), "value": copy.deepcopy(container[key])})

    collect(owner, owner_path)
    collect(owner.get("meta"), _pointer(owner_path, "meta"))
    collect(owner.get("state"), _pointer(owner_path, "state"))
    return forms


def _owner_specs(
    record: Mapping[str, Any],
    kind: str,
    allowed_preference_side_kinds: frozenset[str] | None = None,
) -> list[tuple[str, Mapping[str, Any]]]:
    if kind == "thalamic":
        return [("/", record)]
    if kind == "preference":
        owners = []
        for side in ("chosen", "rejected"):
            owner = record.get(side)
            if not isinstance(owner, Mapping):
                raise IdentityCurationError(f"preference {side} must be an object")
            owners.append((f"/{side}", owner))
        side_kinds = preference_side_kinds(record)
        if (
            side_kinds[0] != side_kinds[1]
            or side_kinds[0] not in PREFERENCE_SIDE_KINDS
        ):
            raise IdentityCurationError(
                "preference sides must be a homogeneous episode or thalamic pair "
                f"(got chosen={side_kinds[0]}, rejected={side_kinds[1]})"
            )
        if (
            allowed_preference_side_kinds is not None
            and side_kinds[0] not in allowed_preference_side_kinds
        ):
            raise IdentityCurationError(
                "preference side kind is not authorized by the factory contract "
                f"(got {side_kinds[0]}, allowed="
                f"{sorted(allowed_preference_side_kinds)})"
            )
        return owners
    if kind == "bridge_pair":
        language_view = record.get("language_view")
        if not isinstance(language_view, Mapping):
            raise IdentityCurationError("bridge language_view must be an object")
        trajectory = language_view.get("trajectory")
        if not isinstance(trajectory, Mapping):
            raise IdentityCurationError("bridge language_view.trajectory must be an object")
        return [("/language_view/trajectory", trajectory)]
    return []


def _provenance_snapshot(owner: Mapping[str, Any], state: Mapping[str, Any]) -> dict[str, Any]:
    return {
        "sim_or_real": {
            "present": "sim_or_real" in state,
            "value": copy.deepcopy(state.get("sim_or_real")),
        },
        "state_provenance": {
            "present": "provenance" in state,
            "value": copy.deepcopy(state.get("provenance")),
        },
        "owner_provenance": {
            "present": "provenance" in owner,
            "value": copy.deepcopy(owner.get("provenance")),
        },
    }


def _map_claim(claimed: Any) -> str | None:
    if not isinstance(claimed, str) or not claimed.strip():
        return None
    value = claimed.strip().lower()
    if value in CANONICAL_PROVENANCE:
        return value
    # Preserve the repository's documented first-match order.  A synthetic
    # narrative claiming live/production use remains designed even if it also
    # mentions simulated or HIL calibration.
    if _is_real_world_claim(value):
        return "designed"
    if "simulation" in value or "simulat" in value or "high-fidelity" in value:
        return "simulated"
    if "hardware-in-the-loop" in value or HIL_RE.search(value):
        return "hil"
    return None


def _existing_claimed(provenance: Any, kind: str) -> Any:
    if not isinstance(provenance, Mapping) or provenance.get("kind") != kind:
        return None
    return copy.deepcopy(provenance.get("claimed"))


def _is_real_world_claim(value: Any) -> bool:
    if not isinstance(value, str) or not value.strip():
        return False
    normalized = value.strip().casefold()
    return bool(
        REAL_WORLD_RE.match(normalized)
        or "actions live" in normalized
        or "production" in normalized
    )


def _resolve_provenance(
    owner: Mapping[str, Any], state: Mapping[str, Any]
) -> tuple[str | None, Any, str]:
    state_value = state.get("sim_or_real") if "sim_or_real" in state else None
    kind = _map_claim(state_value)
    if kind is not None:
        # On a second pass over already-curated output, recover the original
        # claim so normalization remains idempotent rather than replacing it
        # with the canonical state value.
        if isinstance(state_value, str) and state_value.strip().lower() == kind:
            claimed = _existing_claimed(state.get("provenance"), kind)
            if claimed is None:
                claimed = _existing_claimed(owner.get("provenance"), kind)
            if claimed is None:
                claimed = copy.deepcopy(state_value)
        else:
            claimed = copy.deepcopy(state_value)
        return kind, claimed, "state.sim_or_real"

    for basis, provenance in (
        ("state.provenance.kind", state.get("provenance")),
        ("owner.provenance.kind", owner.get("provenance")),
    ):
        if not isinstance(provenance, Mapping):
            continue
        candidate = provenance.get("kind")
        if candidate in CANONICAL_PROVENANCE:
            return str(candidate), copy.deepcopy(provenance.get("claimed")), basis
    return None, copy.deepcopy(state_value), "unresolved"


def _source_mapping(source: _SourceIdentity) -> dict[str, Any]:
    return {
        "path": source.path,
        "line": source.line,
        "sha256": source.sha256,
        "hash_basis": source.hash_basis,
    }


def _base_mapping(
    source: _SourceIdentity,
    kind: str,
    root_original_ids: list[dict[str, Any]],
    registry: FactoryRegistry,
    row: FactoryRow | None,
    contract: str | None,
) -> dict[str, Any]:
    return {
        "transform": {"name": TRANSFORM_NAME, "version": TRANSFORM_VERSION},
        "source": _source_mapping(source),
        "factory": source.factory,
        "record_kind": kind,
        "original_ids": root_original_ids,
        "path_id": source.factory,
        "factory_id": None if row is None else row.payload_factory,
        "identity_authoritative": False if row is None else row.identity_authoritative,
        "provenance_contract": contract,
        "registry": {
            "schema_version": registry.schema_version,
            "sha256": registry.sha256,
        },
    }


def _exclude(mapping: dict[str, Any], reason: str, **extra: Any) -> CurationResult:
    payload = {"action": "exclude", "reason_codes": [reason]}
    payload.update(extra)
    mapping.update(payload)
    return CurationResult("exclude", None, mapping)


def _payload_has_state_claim(
    record: Mapping[str, Any], owner_specs: list[tuple[str, Mapping[str, Any]]]
) -> bool:
    owners = owner_specs if owner_specs else [("/", record)]
    return any(
        isinstance(state := owner.get("state"), Mapping)
        and ("sim_or_real" in state or "provenance" in state)
        for _path, owner in owners
    )


def _training_ready_true_paths(value: Any, path: str = "$") -> list[str]:
    paths: list[str] = []
    if isinstance(value, Mapping):
        if value.get("training_ready"):
            paths.append(f"{path}.training_ready")
        for key, item in value.items():
            paths.extend(_training_ready_true_paths(item, f"{path}.{key}"))
    elif isinstance(value, list):
        for index, item in enumerate(value):
            paths.extend(_training_ready_true_paths(item, f"{path}[{index}]"))
    return paths


def _residual_real_claim_paths(value: Any, path: str = "$") -> list[str]:
    paths: list[str] = []
    if isinstance(value, Mapping):
        sim_or_real = value.get("sim_or_real")
        if _is_real_world_claim(sim_or_real):
            paths.append(f"{path}.sim_or_real")
        provenance = value.get("provenance")
        if isinstance(provenance, Mapping):
            provenance_kind = provenance.get("kind")
            if (
                isinstance(provenance_kind, str)
                and provenance_kind.strip().casefold() == "real"
            ):
                paths.append(f"{path}.provenance.kind")
        for key, item in value.items():
            paths.extend(_residual_real_claim_paths(item, f"{path}.{key}"))
    elif isinstance(value, list):
        for index, item in enumerate(value):
            paths.extend(_residual_real_claim_paths(item, f"{path}[{index}]"))
    return paths


def _shape_validation_errors(
    record: Mapping[str, Any], kind: str
) -> list[str]:
    if kind == "safety_case":
        return check_safety_case(record, "record")
    if kind == "multi_agent":
        return check_multi_agent(record, "record")
    return []


def _collect_state_resolutions(
    owner_specs: list[tuple[str, Mapping[str, Any]]],
) -> tuple[list[dict[str, Any]], list[dict[str, Any]]]:
    provenance_resolutions: list[dict[str, Any]] = []
    unresolved: list[dict[str, Any]] = []
    for owner_path, owner in owner_specs:
        state = owner.get("state")
        state_path = _pointer(owner_path, "state")
        if not isinstance(state, Mapping):
            unresolved.append(
                {
                    "path": state_path,
                    "reason": "missing_or_non_object_state",
                    "original": copy.deepcopy(state),
                }
            )
            continue
        snapshot = _provenance_snapshot(owner, state)
        provenance_kind, claimed, basis = _resolve_provenance(owner, state)
        if provenance_kind is None:
            unresolved.append(
                {
                    "path": state_path,
                    "reason": "unresolved_provenance",
                    "original": snapshot,
                }
            )
            continue
        if provenance_kind == "real":
            raise IdentityCurationError("identity must never emit provenance.kind=real")
        provenance_resolutions.append(
            {
                "owner_path": owner_path,
                "state_path": state_path,
                "kind": provenance_kind,
                "claimed": claimed,
                "basis": basis,
                "original": snapshot,
            }
        )
    return provenance_resolutions, unresolved


def _assign_nested_ids(
    curated: dict[str, Any],
    original: Mapping[str, Any],
    source: _SourceIdentity,
    kind: str,
    owner_specs: list[tuple[str, Mapping[str, Any]]],
    output_id: str,
    root_original_ids: list[dict[str, Any]],
) -> list[dict[str, Any]]:
    id_mappings: list[dict[str, Any]] = [
        {
            "owner_path": "/",
            "original_ids": root_original_ids,
            "output_id": output_id,
        }
    ]
    curated_owners = dict(_owner_specs(curated, kind)) if owner_specs else {}
    for owner_path, _owner in owner_specs:
        if owner_path == "/":
            continue
        nested_id = _canonical_id(source, kind, owner_path)
        curated_owners[owner_path]["id"] = nested_id
        original_owner = dict(_owner_specs(original, kind))[owner_path]
        id_mappings.append(
            {
                "owner_path": owner_path,
                "original_ids": _legacy_ids(original_owner, owner_path),
                "output_id": nested_id,
            }
        )
    return id_mappings


def _curated_resolve_owners(
    curated: dict[str, Any],
    kind: str,
    resolve_owners: list[tuple[str, Mapping[str, Any]]],
) -> list[tuple[str, Mapping[str, Any]]]:
    specs = _owner_specs(curated, kind)
    if specs:
        return specs
    if resolve_owners:
        return [("/", curated)]
    return []


def _apply_resolved_state(
    curated: dict[str, Any],
    original: Mapping[str, Any],
    source: _SourceIdentity,
    kind: str,
    native_owner_specs: list[tuple[str, Mapping[str, Any]]],
    resolve_owners: list[tuple[str, Mapping[str, Any]]],
    resolutions: list[dict[str, Any]],
    output_id: str,
    root_original_ids: list[dict[str, Any]],
) -> tuple[list[dict[str, Any]], list[dict[str, Any]]]:
    id_mappings = _assign_nested_ids(
        curated,
        original,
        source,
        kind,
        native_owner_specs,
        output_id,
        root_original_ids,
    )
    curated_owners = _curated_resolve_owners(curated, kind, resolve_owners)
    provenance_mappings: list[dict[str, Any]] = []
    canonical_provenances: list[dict[str, Any]] = []
    for resolution, (owner_path, owner) in zip(
        resolutions, curated_owners, strict=True
    ):
        state = owner["state"]
        canonical_provenance = {
            "kind": resolution["kind"],
            "claimed": copy.deepcopy(resolution["claimed"]),
        }
        if canonical_provenance["kind"] == "real":
            raise IdentityCurationError("identity must never emit provenance.kind=real")
        state["sim_or_real"] = resolution["kind"]
        state["provenance"] = copy.deepcopy(canonical_provenance)
        owner["provenance"] = copy.deepcopy(canonical_provenance)
        canonical_provenances.append(canonical_provenance)
        provenance_mappings.append(
            {
                "owner_path": owner_path,
                "state_path": resolution["state_path"],
                "basis": resolution["basis"],
                "original": resolution["original"],
                "canonical": copy.deepcopy(canonical_provenance),
            }
        )

    if kind in {"preference", "bridge_pair"}:
        kinds = {item["kind"] for item in canonical_provenances}
        if len(kinds) == 1:
            wrapper_kind = next(iter(kinds))
            claims = [item["claimed"] for item in canonical_provenances]
            wrapper_claimed = claims[0] if all(item == claims[0] for item in claims) else claims
        else:
            wrapper_kind = "unknown"
            wrapper_claimed = [item["claimed"] for item in canonical_provenances]
        curated["provenance"] = {
            "kind": wrapper_kind,
            "claimed": copy.deepcopy(wrapper_claimed),
        }
        provenance_mappings.append(
            {
                "owner_path": "/",
                "basis": "nested_trajectory_aggregate",
                "original": {
                    "owner_provenance": {
                        "present": "provenance" in original,
                        "value": copy.deepcopy(original.get("provenance")),
                    }
                },
                "canonical": copy.deepcopy(curated["provenance"]),
            }
        )
    elif kind in {"episode", "safety_case", "multi_agent"} and resolutions:
        root = {
            "kind": resolutions[0]["kind"],
            "claimed": copy.deepcopy(resolutions[0]["claimed"]),
            "basis": resolutions[0]["basis"],
        }
        curated["provenance"] = root
        provenance_mappings.append(
            {
                "owner_path": "/",
                "basis": resolutions[0]["basis"],
                "original": {
                    "owner_provenance": {
                        "present": "provenance" in original,
                        "value": copy.deepcopy(original.get("provenance")),
                    }
                },
                "canonical": copy.deepcopy(root),
            }
        )
    return id_mappings, provenance_mappings


def _apply_shape_designed(
    curated: dict[str, Any],
    original: Mapping[str, Any],
    source: _SourceIdentity,
    kind: str,
    owner_specs: list[tuple[str, Mapping[str, Any]]],
    output_id: str,
    root_original_ids: list[dict[str, Any]],
) -> tuple[list[dict[str, Any]], list[dict[str, Any]]]:
    basis = SHAPE_BASIS[kind]
    designed = {"kind": "designed", "claimed": None, "basis": basis}
    original_provenance = {
        "present": "provenance" in original,
        "value": copy.deepcopy(original.get("provenance")),
    }
    curated["provenance"] = copy.deepcopy(designed)
    id_mappings = _assign_nested_ids(
        curated, original, source, kind, owner_specs, output_id, root_original_ids
    )
    if owner_specs:
        for _owner_path, owner in _owner_specs(curated, kind):
            owner["provenance"] = {
                "kind": "designed",
                "claimed": None,
                "basis": basis,
            }
    provenance_mappings = [
        {
            "owner_path": "/",
            "original": {"owner_provenance": original_provenance},
            "canonical": copy.deepcopy(designed),
        }
    ]
    return id_mappings, provenance_mappings


def curate_record(
    source_record: SourceRecord,
    registry: FactoryRegistry | None = None,
) -> CurationResult:
    """Curate one source record without mutating the caller's object.

    Kind is classified from the payload first.  Factory authority is the
    reviewed ``path_id`` + ``payload_factory`` row.  Missing or ambiguous
    trajectory provenance returns ``action == 'exclude'``.  Designed is
    never invented from factory membership unless the row's kind contract
    is ``synthetic_shape_implies_designed`` and the payload has no
    ``state.sim_or_real`` claim.
    """

    if not isinstance(source_record, SourceRecord):
        raise IdentityCurationError("curate_record expects a SourceRecord")
    source = _source_identity(source_record)
    original = source_record.record
    registry = default_registry() if registry is None else registry
    row = registry.by_path_id.get(source.factory)
    try:
        kind = record_kind(original)
        kind_error = None
    except IdentityCurationError as exc:
        kind = "unknown"
        kind_error = exc
    root_original_ids = (
        _legacy_ids(original, "/") if isinstance(original, Mapping) else []
    )
    contract = None
    if row is not None and kind != "unknown":
        contract = row.provenance_contract_by_kind.get(kind)
    mapping = _base_mapping(source, kind, root_original_ids, registry, row, contract)
    if kind_error is not None:
        return _exclude(
            mapping,
            "identity.unsupported_record_shape",
            details=[str(kind_error)],
        )
    if row is None:
        return _exclude(mapping, "identity.unknown_factory")
    payload_factory = _payload_factory(original)
    if payload_factory != row.payload_factory:
        return _exclude(
            mapping,
            "identity.factory_path_payload_mismatch",
            details=[
                {
                    "path_id": row.path_id,
                    "expected_payload_factory": row.payload_factory,
                    "payload_factory": payload_factory,
                }
            ],
        )
    if kind not in row.record_kinds:
        return _exclude(
            mapping,
            "identity.factory_not_authorized_for_kind",
            details=[
                {
                    "record_kind": kind,
                    "authorized_kinds": sorted(row.record_kinds),
                }
            ],
        )
    if not row.identity_authoritative:
        return _exclude(mapping, "identity.factory_not_identity_authoritative")
    if contract not in ALLOWED_CONTRACTS:
        return _exclude(
            mapping,
            "identity.factory_contract_invalid",
            details=[{"record_kind": kind, "provenance_contract": contract}],
        )
    if row.training_ready_policy == "never":
        ready_claims = _training_ready_true_paths(original)
        if ready_claims:
            return _exclude(
                mapping,
                "identity.training_ready_policy_violation",
                details=[{"paths": ready_claims, "policy": "never"}],
            )
    if contract == CONTRACT_SHAPE_DESIGNED:
        shape_errors = _shape_validation_errors(original, kind)
        if shape_errors:
            return _exclude(
                mapping,
                "identity.invalid_payload_shape",
                details=shape_errors,
            )

    try:
        owner_specs = _owner_specs(
            original,
            kind,
            row.preference_side_kinds if kind == "preference" else None,
        )
    except IdentityCurationError as exc:
        return _exclude(mapping, "identity.invalid_nested_shape", details=[str(exc)])

    all_original_ids = list(root_original_ids)
    for owner_path, owner in owner_specs:
        if owner_path != "/":
            all_original_ids.extend(_legacy_ids(owner, owner_path))
    mapping["original_ids"] = all_original_ids

    use_state = contract == CONTRACT_REQUIRE_STATE or _payload_has_state_claim(
        original, owner_specs
    )
    state_owners = owner_specs if owner_specs else [("/", original)]
    if use_state:
        resolutions, unresolved = _collect_state_resolutions(state_owners)
        if unresolved:
            return _exclude(
                mapping,
                "identity.unresolved_provenance",
                unresolved_provenance=unresolved,
            )
        apply_owners = state_owners
    else:
        if kind not in SHAPE_BASIS:
            return _exclude(
                mapping,
                "identity.factory_contract_invalid",
                details=[{"record_kind": kind, "provenance_contract": contract}],
            )
        resolutions = []
        apply_owners = owner_specs

    curated: dict[str, Any] = copy.deepcopy(dict(original))
    output_id = _canonical_id(source, kind, "/")
    curated["id"] = output_id

    if use_state:
        id_mappings, provenance_mappings = _apply_resolved_state(
            curated,
            original,
            source,
            kind,
            owner_specs,
            apply_owners,
            resolutions,
            output_id,
            root_original_ids,
        )
    else:
        id_mappings, provenance_mappings = _apply_shape_designed(
            curated,
            original,
            source,
            kind,
            apply_owners,
            output_id,
            root_original_ids,
        )

    residual_real_claims = _residual_real_claim_paths(curated)
    if residual_real_claims:
        return _exclude(
            mapping,
            "identity.unowned_real_claim",
            details=[{"paths": residual_real_claims}],
        )

    mapping.update(
        {
            "action": "retained",
            "reason_codes": ["identity.assigned", "provenance.canonicalized"],
            "output_id": output_id,
            "output_sha256": _sha256_json(curated),
            "id_mappings": id_mappings,
            "provenance_mappings": provenance_mappings,
        }
    )
    return CurationResult("retained", curated, mapping)


def curate_records(
    records: Iterable[SourceRecord],
    registry: FactoryRegistry | None = None,
) -> tuple[CurationResult, ...]:
    """Curate a batch and independently reject any duplicate emitted ID."""

    registry = default_registry() if registry is None else registry
    results: list[CurationResult] = []
    seen: dict[str, tuple[dict[str, Any], str]] = {}
    for source_record in records:
        result = curate_record(source_record, registry=registry)
        if result.action == "retained":
            source = result.mapping["source"]
            for id_mapping in result.mapping["id_mappings"]:
                output_id = id_mapping["output_id"]
                owner_path = id_mapping["owner_path"]
                if output_id in seen:
                    first, first_owner = seen[output_id]
                    raise CanonicalIdCollision(
                        f"canonical ID collision {output_id!r}: "
                        f"{first['path']}:{first['line']}{first_owner} and "
                        f"{source['path']}:{source['line']}{owner_path}"
                    )
                seen[output_id] = (source, owner_path)
        results.append(result)
    return tuple(results)


def _is_under_raw(path: Path) -> bool:
    parts = path.resolve(strict=False).parts
    return any(
        parts[index : index + 2] == ("outputs", "raw")
        for index in range(len(parts) - 1)
    )


def _write_exclusive(path: Path, payload: bytes) -> None:
    descriptor = os.open(path, os.O_WRONLY | os.O_CREAT | os.O_EXCL, 0o644)
    try:
        try:
            handle = os.fdopen(descriptor, "wb")
        except BaseException:
            os.close(descriptor)
            raise
        with handle:
            handle.write(payload)
            handle.flush()
            os.fsync(handle.fileno())
        # Fsync parent directory to ensure durable directory entry
        parent_descriptor = os.open(path.parent, os.O_RDONLY)
        try:
            os.fsync(parent_descriptor)
        finally:
            os.close(parent_descriptor)
    except BaseException:
        path.unlink(missing_ok=True)
        raise


def _pointer_value(value: Any, pointer: str) -> Any:
    if pointer == "/":
        return value
    if not isinstance(pointer, str) or not pointer.startswith("/"):
        raise IdentityTreeError(f"invalid owner_path: {pointer!r}")
    current = value
    for raw_part in pointer[1:].split("/"):
        part = raw_part.replace("~1", "/").replace("~0", "~")
        if isinstance(current, Mapping) and part in current:
            current = current[part]
        else:
            raise IdentityTreeError(f"owner_path does not exist: {pointer}")
    return current


def _validate_manifest_ids(
    mapping: Mapping[str, Any],
    record: Mapping[str, Any],
    index: int,
    registry: FactoryRegistry,
) -> None:
    output_id = mapping.get("output_id")
    if not isinstance(output_id, str) or record.get("id") != output_id:
        raise IdentityTreeError(
            f"IDENTITY-MANIFEST.json[{index}].output_id does not match emitted record"
        )
    kind = mapping.get("record_kind")
    if kind not in SUPPORTED_RECORD_KINDS or classify_kind(record) != kind:
        raise IdentityTreeError(
            f"IDENTITY-MANIFEST.json[{index}].record_kind does not match emitted record"
        )
    source_meta = mapping.get("source")
    if not isinstance(source_meta, Mapping):
        raise IdentityTreeError(
            f"IDENTITY-MANIFEST.json[{index}].source must be an object"
        )
    try:
        source_path, source_factory = _normalize_source_path(source_meta.get("path"))
    except IdentityCurationError as exc:
        raise IdentityTreeError(
            f"IDENTITY-MANIFEST.json[{index}].source.path is invalid: {exc}"
        ) from exc
    source_line = source_meta.get("line")
    source_identity = _SourceIdentity(
        source_path,
        source_line,
        source_factory,
        "",
        "manifest-coordinate",
    )
    if output_id != _canonical_id(source_identity, kind, "/"):
        raise IdentityTreeError(
            f"IDENTITY-MANIFEST.json[{index}].output_id is not canonical"
        )
    row = registry.by_path_id.get(source_factory)
    if row is None or kind not in row.record_kinds or not row.identity_authoritative:
        raise IdentityTreeError(
            f"IDENTITY-MANIFEST.json[{index}] factory authority is invalid"
        )
    contract = row.provenance_contract_by_kind.get(kind)
    if (
        mapping.get("factory") != source_factory
        or mapping.get("path_id") != source_factory
        or mapping.get("factory_id") != row.payload_factory
        or mapping.get("provenance_contract") != contract
        or _payload_factory(record) != row.payload_factory
    ):
        raise IdentityTreeError(
            f"IDENTITY-MANIFEST.json[{index}] factory contract does not match output"
        )
    if row.training_ready_policy == "never" and _training_ready_true_paths(record):
        raise IdentityTreeError(
            f"IDENTITY-MANIFEST.json[{index}] violates training_ready_policy=never"
        )
    if _residual_real_claim_paths(record):
        raise IdentityTreeError(
            f"IDENTITY-MANIFEST.json[{index}] contains a residual real claim"
        )
    if contract == CONTRACT_SHAPE_DESIGNED and _shape_validation_errors(record, kind):
        raise IdentityTreeError(
            f"IDENTITY-MANIFEST.json[{index}] output payload shape is invalid"
        )
    try:
        owner_paths = ["/"]
        for owner_path, _owner in _owner_specs(
            record,
            kind,
            row.preference_side_kinds if kind == "preference" else None,
        ):
            if owner_path not in owner_paths:
                owner_paths.append(owner_path)
    except IdentityCurationError as exc:
        raise IdentityTreeError(
            f"IDENTITY-MANIFEST.json[{index}] emitted nested shape is invalid: {exc}"
        ) from exc
    id_mappings = mapping.get("id_mappings")
    if not isinstance(id_mappings, list):
        raise IdentityTreeError(
            f"IDENTITY-MANIFEST.json[{index}].id_mappings must be a list"
        )
    by_owner: dict[str, str] = {}
    for nested_index, id_mapping in enumerate(id_mappings):
        if not isinstance(id_mapping, Mapping):
            raise IdentityTreeError(
                f"IDENTITY-MANIFEST.json[{index}].id_mappings[{nested_index}] "
                "must be an object"
            )
        owner_path = id_mapping.get("owner_path")
        nested_output_id = id_mapping.get("output_id")
        if not isinstance(owner_path, str) or not isinstance(nested_output_id, str):
            raise IdentityTreeError(
                f"IDENTITY-MANIFEST.json[{index}].id_mappings[{nested_index}] "
                "must contain string owner_path and output_id"
            )
        if owner_path in by_owner:
            raise IdentityTreeError(
                f"IDENTITY-MANIFEST.json[{index}].id_mappings repeats {owner_path}"
            )
        by_owner[owner_path] = nested_output_id
    if set(by_owner) != set(owner_paths):
        raise IdentityTreeError(
            f"IDENTITY-MANIFEST.json[{index}].id_mappings owner paths do not "
            "match emitted record"
        )
    if by_owner["/"] != output_id:
        raise IdentityTreeError(
            f"IDENTITY-MANIFEST.json[{index}] root id mapping does not match output_id"
        )
    for owner_path, nested_output_id in by_owner.items():
        owner = _pointer_value(record, owner_path)
        if not isinstance(owner, Mapping) or owner.get("id") != nested_output_id:
            raise IdentityTreeError(
                f"IDENTITY-MANIFEST.json[{index}] id mapping for {owner_path} "
                "does not match emitted record"
            )
        if nested_output_id != _canonical_id(source_identity, kind, owner_path):
            raise IdentityTreeError(
                f"IDENTITY-MANIFEST.json[{index}] id mapping for {owner_path} "
                "is not canonical"
            )


def _expected_identity_outputs(
    manifest: list[Any], registry: FactoryRegistry
) -> dict[str, dict[int, tuple[int, Mapping[str, Any]]]]:
    expected: dict[str, dict[int, tuple[int, Mapping[str, Any]]]] = {}
    for index, mapping in enumerate(manifest):
        if not isinstance(mapping, Mapping):
            raise IdentityTreeError(f"IDENTITY-MANIFEST.json[{index}] must be an object")
        registry_meta = mapping.get("registry")
        pin = registry_meta.get("sha256") if isinstance(registry_meta, Mapping) else None
        if pin != registry.sha256:
            raise IdentityTreeError(
                f"IDENTITY-MANIFEST.json[{index}] registry.sha256 does not match sidecar pin"
            )
        action = mapping.get("action")
        if action not in {"retained", "exclude"}:
            raise IdentityTreeError(
                f"IDENTITY-MANIFEST.json[{index}].action must be retained or exclude"
            )
        if action != "retained":
            continue
        source_meta = mapping.get("source")
        if not isinstance(source_meta, Mapping):
            raise IdentityTreeError(
                f"IDENTITY-MANIFEST.json[{index}].source must be an object"
            )
        try:
            output_path, _factory = _normalize_source_path(source_meta.get("path"))
        except IdentityCurationError as exc:
            raise IdentityTreeError(
                f"IDENTITY-MANIFEST.json[{index}].source.path is invalid: {exc}"
            ) from exc
        source_line = source_meta.get("line")
        if (
            not isinstance(source_line, int)
            or isinstance(source_line, bool)
            or source_line < 1
        ):
            raise IdentityTreeError(
                f"IDENTITY-MANIFEST.json[{index}].source.line must be positive"
            )
        output_sha256 = mapping.get("output_sha256")
        if not isinstance(output_sha256, str) or not SHA256_RE.fullmatch(output_sha256):
            raise IdentityTreeError(
                f"IDENTITY-MANIFEST.json[{index}].output_sha256 must be a SHA-256"
            )
        by_line = expected.setdefault(output_path, {})
        if source_line in by_line:
            raise IdentityTreeError(
                f"IDENTITY-MANIFEST.json repeats output coordinate "
                f"{output_path}:{source_line}"
            )
        by_line[source_line] = (index, mapping)
    return expected


def _read_identity_output(
    path: Path, rel: str
) -> dict[int, tuple[Mapping[str, Any], bytes]]:
    records: dict[int, tuple[Mapping[str, Any], bytes]] = {}
    try:
        output_bytes = path.read_bytes()
    except OSError as exc:
        raise IdentityTreeError(f"identity output is unreadable: {rel}: {exc}") from exc
    for line_no, record_bytes in _iter_jsonl_record_bytes(output_bytes):
        try:
            line = record_bytes.decode("utf-8")
        except UnicodeDecodeError as exc:
            raise IdentityTreeError(
                f"identity output is not UTF-8 at {rel}:{line_no}: {exc}"
            ) from exc
        if not line.strip():
            continue
        try:
            output_record = json.loads(line, parse_constant=_reject_json_constant)
        except (json.JSONDecodeError, ValueError) as exc:
            raise IdentityTreeError(
                f"identity output JSON parse error at {rel}:{line_no}: {exc}"
            ) from exc
        if not isinstance(output_record, Mapping):
            raise IdentityTreeError(
                f"identity output record at {rel}:{line_no} must be an object"
            )
        records[line_no] = (output_record, record_bytes)
    return records


def validate_identity_tree(
    dest: Path, expected_registry_digest: str | None = None
) -> FactoryRegistry:
    """Validate internal consistency and, when supplied, a reviewed digest pin."""

    dest = Path(dest)
    if dest.is_symlink():
        raise IdentityTreeError("identity tree root must not be a symlink")
    symlinks = [path.relative_to(dest).as_posix() for path in dest.rglob("*") if path.is_symlink()]
    if symlinks:
        raise IdentityTreeError(f"identity tree must not contain symlinks: {symlinks}")
    sidecar = dest / FACTORY_REGISTRY_SIDECAR
    manifest_path = dest / IDENTITY_MANIFEST_SIDECAR
    if not sidecar.is_file():
        raise IdentityTreeError("identity tree missing FACTORY-REGISTRY.json")
    if not manifest_path.is_file():
        raise IdentityTreeError("identity tree missing IDENTITY-MANIFEST.json")
    registry = load_registry(sidecar)
    if expected_registry_digest is not None and registry.sha256 != expected_registry_digest:
        raise IdentityTreeError(
            f"registry digest mismatch: expected {expected_registry_digest}, "
            f"got {registry.sha256}"
        )
    try:
        manifest = json.loads(
            manifest_path.read_text(encoding="utf-8"),
            parse_constant=_reject_json_constant,
        )
    except (OSError, json.JSONDecodeError, ValueError) as exc:
        raise IdentityTreeError(f"IDENTITY-MANIFEST.json is not readable JSON: {exc}") from exc
    if not isinstance(manifest, list):
        raise IdentityTreeError("IDENTITY-MANIFEST.json must be a list of mappings")
    expected_outputs = _expected_identity_outputs(manifest, registry)
    actual_paths = {
        path.relative_to(dest).as_posix(): path
        for path in sorted(dest.rglob("*.jsonl"))
        if path.is_file()
    }
    expected_paths = set(expected_outputs)
    if set(actual_paths) != expected_paths:
        missing = sorted(expected_paths - set(actual_paths))
        extra = sorted(set(actual_paths) - expected_paths)
        raise IdentityTreeError(
            "identity output paths do not match manifest: "
            f"missing={missing}, extra={extra}"
        )
    for rel, expected_by_line in sorted(expected_outputs.items()):
        actual_by_line = _read_identity_output(actual_paths[rel], rel)
        if set(actual_by_line) != set(expected_by_line):
            raise IdentityTreeError(
                f"identity output line coordinates do not match manifest: {rel}"
            )
        for line_no, (index, mapping) in expected_by_line.items():
            output_record, record_bytes = actual_by_line[line_no]
            try:
                canonical_json(output_record)
            except IdentityCurationError as exc:
                raise IdentityTreeError(
                    f"identity output is not canonical JSON data: {rel}:{line_no}: {exc}"
                ) from exc
            actual_hash = _sha256_bytes(record_bytes)
            if actual_hash != mapping["output_sha256"]:
                raise IdentityTreeError(
                    f"identity output hashes do not match manifest: {rel}:{line_no}"
                )
            _validate_manifest_ids(mapping, output_record, index, registry)
    return registry


def _registered_factory_ancestor(
    directory: Path,
    registry: FactoryRegistry,
) -> Path | None:
    for candidate in (directory, *directory.parents):
        if candidate.name in registry.by_path_id:
            return candidate
    return None


def _source_relative_path(
    path: Path,
    source: Path,
    registry: FactoryRegistry,
) -> str:
    factory_dir = _registered_factory_ancestor(path.parent, registry)
    if factory_dir is not None:
        return path.relative_to(factory_dir.parent).as_posix()
    if source.is_file() or path.parent == source:
        return path.relative_to(path.parent.parent).as_posix()
    return path.relative_to(source).as_posix()


def _committed_source_paths(paths: Iterable[Path]) -> list[Path]:
    visible_by_factory: dict[Path, set[Path]] = {}
    enclosing_factory: dict[Path, Path | None] = {}

    def marker_factory(path: Path) -> Path | None:
        visited: list[Path] = []
        current = path.parent
        while True:
            if current in enclosing_factory:
                factory = enclosing_factory[current]
                break
            visited.append(current)
            if marker_mode_path(current) is not None:
                factory = current
                break
            parent = current.parent
            if parent == current:
                factory = None
                break
            current = parent
        for directory in visited:
            enclosing_factory[directory] = factory
        return factory

    visible: list[Path] = []
    for path in paths:
        factory = marker_factory(path)
        if factory is None:
            visible.append(path)
            continue
        if factory not in visible_by_factory:
            visible_by_factory[factory] = {
                candidate.resolve() for candidate in committed_jsonl_paths(factory)
            }
        if path.resolve() in visible_by_factory[factory]:
            visible.append(path)
    return visible


def iter_source_records(
    source: Path,
    registry: FactoryRegistry | None = None,
) -> list[SourceRecord]:
    """Read JSONL records under ``source`` as identity source coordinates."""

    source = Path(source)
    registry = default_registry() if registry is None else registry
    if not source.exists():
        raise IdentityCurationError(f"source does not exist: {source}")
    if source.is_symlink():
        raise IdentityCurationError(f"source must not be a symlink: {source}")
    if source.is_file():
        if source.suffix != ".jsonl":
            raise IdentityCurationError(f"source is not a JSONL file: {source}")
        if not source.parent.name:
            raise IdentityCurationError(
                f"JSONL source must be inside a factory directory: {source}"
            )
        candidates = [source]
    elif source.is_dir():
        candidates = sorted(
            path
            for path in source.rglob("*.jsonl")
            if path.is_file() and not path.is_symlink()
        )
        if not candidates:
            raise IdentityCurationError(f"no JSONL files under source: {source}")
    else:
        raise IdentityCurationError(f"source is not a JSONL file or directory: {source}")
    try:
        files = _committed_source_paths(candidates)
    except TransactionError as exc:
        raise IdentityCurationError(f"invalid source transaction state: {exc}") from exc
    if not files:
        raise IdentityCurationError(f"no committed JSONL files under source: {source}")

    records: list[SourceRecord] = []
    for path in files:
        rel = _source_relative_path(path, source, registry)
        try:
            source_bytes = path.read_bytes()
        except OSError as exc:
            raise IdentityCurationError(
                f"source JSONL is unreadable: {rel}: {exc}"
            ) from exc
        for line_no, record_bytes in _iter_jsonl_record_bytes(source_bytes):
            try:
                line = record_bytes.decode("utf-8")
            except UnicodeDecodeError as exc:
                raise IdentityCurationError(
                    f"source JSONL is not UTF-8 at {rel}:{line_no}: {exc}"
                ) from exc
            if not line.strip():
                continue
            try:
                obj = json.loads(line, parse_constant=_reject_json_constant)
            except (json.JSONDecodeError, ValueError) as exc:
                raise IdentityCurationError(
                    f"JSON parse error at {rel}:{line_no}: {exc}"
                ) from exc
            digest = _sha256_bytes(record_bytes)
            records.append(SourceRecord(obj, rel, line_no, digest))
    return records


def _ensure_output_directory(
    root: Path,
    directory: Path,
    created_directories: list[Path],
) -> None:
    current = root
    for part in directory.relative_to(root).parts:
        current /= part
        try:
            current.mkdir()
        except FileExistsError:
            if current.is_symlink() or not current.is_dir():
                raise IdentityCurationError(
                    f"identity output parent is not a directory: {current}"
                )
        else:
            created_directories.append(current)


def write_run(
    source: Path,
    dest: Path,
    registry: FactoryRegistry | None = None,
) -> tuple[CurationResult, ...]:
    """Curate a source tree into a new destination with identity sidecars."""

    source = Path(source)
    dest = Path(dest)
    if dest.exists():
        raise IdentityCurationError(f"destination already exists: {dest}")
    if _is_under_raw(dest):
        raise IdentityCurationError(
            f"refusing to write inside immutable raw evidence: {dest}"
        )
    registry = default_registry() if registry is None else registry
    results = curate_records(
        iter_source_records(source, registry=registry),
        registry=registry,
    )
    created_files: list[Path] = []
    created_directories: list[Path] = []
    destination_created = False
    try:
        dest.mkdir(parents=True, exist_ok=False)
        destination_created = True
        _write_exclusive(dest / FACTORY_REGISTRY_SIDECAR, registry.raw_bytes)
        created_files.append(dest / FACTORY_REGISTRY_SIDECAR)
        manifest_bytes = (
            json.dumps(
                [result.mapping for result in results],
                ensure_ascii=False,
                allow_nan=False,
                indent=2,
                sort_keys=True,
            )
            + "\n"
        ).encode("utf-8")
        _write_exclusive(dest / IDENTITY_MANIFEST_SIDECAR, manifest_bytes)
        created_files.append(dest / IDENTITY_MANIFEST_SIDECAR)
        retained_by_rel: dict[str, dict[int, dict[str, Any]]] = {}
        for result in results:
            if result.action != "retained" or result.record is None:
                continue
            source_meta = result.mapping["source"]
            by_line = retained_by_rel.setdefault(source_meta["path"], {})
            if source_meta["line"] in by_line:
                raise IdentityCurationError(
                    "retained records repeat source coordinate "
                    f"{source_meta['path']}:{source_meta['line']}"
                )
            by_line[source_meta["line"]] = result.record
        for rel, records_by_line in sorted(retained_by_rel.items()):
            out_path = dest / rel
            _ensure_output_directory(dest, out_path.parent, created_directories)
            output_lines = [""] * max(records_by_line)
            for line_no, record in records_by_line.items():
                output_lines[line_no - 1] = canonical_json(record)
            payload = "\n".join(output_lines) + "\n"
            _write_exclusive(out_path, payload.encode("utf-8"))
            created_files.append(out_path)
        validate_identity_tree(dest, expected_registry_digest=registry.sha256)
    except BaseException:
        if destination_created:
            for path in reversed(created_files):
                try:
                    path.unlink()
                except FileNotFoundError:
                    pass
            for directory in reversed(created_directories):
                try:
                    directory.rmdir()
                except OSError:
                    pass
            try:
                dest.rmdir()
            except OSError:
                pass
        raise
    return results


def _summary(results: Iterable[CurationResult], registry: FactoryRegistry) -> dict[str, Any]:
    results = list(results)
    reasons: Counter[str] = Counter()
    retained = 0
    for result in results:
        if result.action == "retained":
            retained += 1
        for code in result.mapping.get("reason_codes", []):
            reasons[code] += 1
    return {
        "transform": {"name": TRANSFORM_NAME, "version": TRANSFORM_VERSION},
        "registry": {
            "schema_version": registry.schema_version,
            "sha256": registry.sha256,
        },
        "records": len(results),
        "retained": retained,
        "excluded": len(results) - retained,
        "reason_codes": dict(sorted(reasons.items())),
    }


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("source", type=Path, help="JSONL file or run directory")
    parser.add_argument(
        "--out",
        type=Path,
        help="write a NEW cleaned tree with FACTORY-REGISTRY.json and IDENTITY-MANIFEST.json",
    )
    args = parser.parse_args(argv)
    try:
        registry = default_registry()
        if args.out is None:
            results = curate_records(
                iter_source_records(args.source, registry=registry),
                registry=registry,
            )
        else:
            results = write_run(args.source, args.out, registry=registry)
        print(json.dumps(_summary(results, registry), ensure_ascii=False, indent=2))
        return 0
    except (OSError, IdentityCurationError, ValueError) as exc:
        print(f"identity curation failed: {exc}", file=sys.stderr)
        return 1


if __name__ == "__main__":
    raise SystemExit(main())
