#!/usr/bin/env python3
"""Pinned identity for the browser-tool-use family (prefix ``brw``).

Constants are AST-extracted from ``brw-mill-r193`` on ``origin/legacy-mill-lane``
(``experiments/brw-mill-r193.py``). This module is the only place the family
names the factory, generator, catalog window, and banned hosts/CSS. Leftover
mill scripts are not vendored and are never executed.
"""

from __future__ import annotations

if __name__.startswith("pipelines."):
    from ..exact_json import dumps_exact_json
else:
    from exact_json import dumps_exact_json

FAMILY_PREFIX = "brw"
FACTORY = "browser-tool-use-factory"
GENERATOR = "grok-4.6"
GEN = GENERATOR
CATALOG_FIRST = 193
SOURCE_MILL_ID = "brw-mill-r193"
SOURCE_ROUND = CATALOG_FIRST
SOURCE_REF = "origin/legacy-mill-lane"
SOURCE_PATH = "experiments/brw-mill-r193.py"
MIN_STEPS = 13
MAX_STEPS = 16
QUOTA_PER_ROUND = 2
BANNED = (
    "thought",
    "chain_of_thought",
    "scratch",
    "inner_monologue",
)
DECISION_PREFIXES = (
    "Plan",
    "Observation",
    "Reflection",
    "Tool call",
)
MAX_DECISION_BASIS = 240
BANNED_HOSTS = frozenset({
    "quillmarsh",
    "woadholt",
    "zincquay",
    "harrowfen",
    "jutevale",
    "alderfen",
    "ambercairn",
    "ashkeel",
    "ashspit",
    "balsafen",
    "birchfen",
    "birchholt",
    "birchquay",
    "bogstair",
    "brackenspit",
    "bramblecot",
    "brinecot",
    "brinefen",
    "brineholt",
    "brinevale",
    "cinderholt",
    "cinderloom",
    "claycot",
    "clayholm",
    "clayrift",
    "clayspan",
    "coblefen",
    "cobleway",
    "copperfen",
    "copsewharf",
    "corkfen",
    "corkwharf",
    "crowmarsh",
    "dewquay",
    "driftkeel",
    "duneholt",
    "dunevale",
    "duskbar",
    "duskfen",
    "duskholt",
    "duskspit",
    "fenspire",
    "fernquay",
    "fernspit",
    "firnquay",
    "flaxholt",
    "flintbar",
    "flintcopse",
    "flintreed",
    "fogcairn",
    "frostcot",
    "frostpit",
    "frostwharf",
    "gannetbar",
    "gorsebar",
    "gorserift",
    "gritfen",
    "gritspan",
    "gritwharf",
    "gullfen",
    "hailbarrow",
    "hailcot",
    "hailfen",
    "hailspan",
    "harrierfen",
    "hazelquay",
    "hempcairn",
    "ilexholt",
    "irongate",
    "ironspit",
    "ironvale",
    "islecot",
    "ivorycot",
    "ivybarrow",
    "ivykeel",
    "jadebar",
    "jadefen",
    "jadewharf",
    "jasperfen",
    "junipercot",
    "kelpcot",
    "kelpfen",
    "kelpspan",
    "kestrelspit",
    "knapholt",
    "lambholt",
    "larkholm",
    "larkspit",
    "lichenquay",
    "limeholt",
    "limekeel",
    "limewharf",
    "loamquay",
    "mallowquay",
    "marshloom",
    "mistbar",
    "mistreed",
    "mistspan",
    "moorwharf",
    "mosskeel",
    "mossquay",
    "myrrhfen",
    "myrtlecot",
    "nacrebar",
    "nacreholt",
    "nettlebar",
    "nightridge",
    "nimbusquay",
    "oakspit",
    "oatbarrow",
    "orrisvale",
    "ospreyfen",
    "oxbowfen",
    "oxfen",
    "oxspit",
    "peatcot",
    "peatlock",
    "peatspan",
    "pebblewharf",
    "pinebarrow",
    "pinfen",
    "pithfen",
    "pithholt",
    "pithquay",
    "ploverbar",
    "pumiceholt",
    "quartzfen",
    "quernholt",
    "reedholm",
    "reedspit",
    "reeflock",
    "rillspit",
    "rowanfen",
    "rushcairn",
    "russetfen",
    "sablekeel",
    "sandbar",
    "sandkeel",
    "sandrift",
    "seacairn",
    "sedgebar",
    "sedgecot",
    "sedgeholt",
    "sedgewharf",
    "shalebar",
    "siltspan",
    "slagfen",
    "slateholm",
    "slatequay",
    "sloeholt",
    "stormcot",
    "stormholt",
    "stormquay",
    "tawnyfen",
    "tawnyholt",
    "tawnyquay",
    "tealholt",
    "thatchquay",
    "thornvale",
    "tinmarsh",
    "tufaquay",
    "ulmusfen",
    "vellumholt",
    "vetchcot",
    "wadefen",
    "wadeholt",
    "waderift",
    "waderun",
    "wickerfen",
    "willowkeel",
    "woolbarrow",
    "woolholt",
    "woolrift",
    "woolspan",
    "yarrowspit",
    "yewspit",
})
BANNED_CSS = (
    "masonry",
    "align-tracks",
    "anchor-size",
    "light-dark",
    "color-mix",
    "contrast-color",
    "sibling-count",
    "sibling-index",
    "shape-outside",
    "corner-shape",
    "margin-trim",
    "font-size-adjust",
    "mix-blend",
    "initial-letter",
    "safe-area",
    "reading-flow",
    "text-autospace",
    "white-space-collapse",
    "details-content",
    "image-set",
    "hanging-punctuation",
    "ruby-overhang",
    "hyphenate-limit",
    "::highlight",
    "overlay:auto",
    "text-spacing-trim",
    "text-wrap:pretty",
    "field-sizing",
    "position-try",
    "scroll-timeline",
    "interactivity:inert",
    "content-visibility",
    "view-timeline",
    "animation-timeline",
    "clip-path",
    "view-transition",
    "popover",
)

__all__ = [
    "BANNED",
    "BANNED_CSS",
    "BANNED_HOSTS",
    "BrwError",
    "CATALOG_FIRST",
    "DECISION_PREFIXES",
    "FACTORY",
    "FAMILY_PREFIX",
    "GEN",
    "GENERATOR",
    "MAX_DECISION_BASIS",
    "MAX_STEPS",
    "MIN_STEPS",
    "QUOTA_PER_ROUND",
    "SOURCE_MILL_ID",
    "SOURCE_PATH",
    "SOURCE_REF",
    "SOURCE_ROUND",
    "dumps_exact_json",
    "require_round",
]


class BrwError(ValueError):
    """Fail-closed refusal from the browser-tool-use family."""


def require_round(rnd: int) -> int:
    """Accept a positive integer round token. Booleans are not rounds."""

    if type(rnd) is not int or rnd < 1:
        raise BrwError(f"invalid_round: {rnd!r}")
    return rnd
