def rec_016():
    # humanoid-locomotion, MODIFY correct, partnered-neg, designed, independent LIF
    delayed = 600
    ticks, sums, total = ticks_from(
        [
            (1280, 0.04, -0.02, -0.01, 0.01, 0.00),
            (7120, 0.07, -0.03, -0.02, 0.01, -0.01),
            (7380, 0.03, -0.02, -0.02, 0.00, 0.00),
            (7840, 0.08, -0.05, -0.03, 0.02, -0.01),
            (24200, 0.06, -0.42, -0.05, 0.00, -0.01),
            (600000000, 0.02, -0.04, -0.02, 0.00, 0.00),
        ]
    )
    raster = raster_block(
        window_ms=42,
        neurons=80,
        mean_rate_hz=26,
        delayed_s=delayed,
        source="thalamic-relay.knee-imu",
        target="spikenaut.policy.knee-clamp",
        table=[
            {"from": "relay.ft.knee", "to": "policy.knee_clamp", "weight": 0.69},
            {"from": "relay.imu.roll", "to": "policy.imu_hold", "weight": 0.28},
            {"from": "relay.granite.spall", "to": "policy.knee_clamp", "weight": -0.43},
        ],
        modulator="noradrenaline",
        tau_e_s=0.042,
        eligibility="surprise-gated pre_post_stdp; NA at knee win (7.120 ms) opens a 42 ms eligibility trace that still covers the 24.200 ms granite nosing spall",
        seed=4016,
        stim_t_us=(23000, 26200),
        extra_bias_n=16,
        extra_i=0.66,
        early_ch="lif.clamp",
        late_ch="lif.spall",
        note="Population sim scoped to this sidecar. Plant remains designed. Neurons 0-15 carry +0.66 clamp-pathway bias; stim 23-26.2 ms is the granite-nosing spall burst.",
    )
    return {
        "id": "ttf-r04-016",
        "title": "Kerb-Lynchet KL-6 / Walker-W4: stance-knee FT beats IMU roll by 260 us; correct MODIFY still eats an in-window granite nosing spall (partnered negative total -0.42)",
        "state": {
            "description": "Walker-W4 is already mid-kerb on wet granite at Kerb-Lynchet KL-6 when stance-knee Fz sits at 1320 N against a 1000 N shared-kerb cap. IMU roll is only 2.4 deg under the 7.0 deg trip, so a tilt-first planner would keep 0.38 m/s ascent. The live contest is knee contact versus roll, not ankle versus hip yaw. A granite nosing flake is off both buses until the later spall.",
            "domain": "humanoid-locomotion",
            "sim_or_real": "designed",
            "goal": "Complete the wet granite kerb-up with stance-knee Fz <= 1000 N, leave hip yaw at the planned 0.10 rad/s, and keep IMU roll under 7.0 deg.",
            "t0_us": 1756842500000016,
            "gate_latency_us": 720,
            "race_window_us": 480,
            "race_window_rel_ms": [7.05, 7.53],
            "race": {
                "contenders": [
                    "ft.knee.n 1320 N contact",
                    "imu.roll.deg 2.4 under trip",
                ],
                "semantics": "Knee-first latches torque clamp 96 -> 48 N-m and ascent 0.38 -> 0.16 m/s; roll-first keeps cruise on a 'still upright' IMU model.",
                "window_derivation": "480 us = one knee-FT sample period minus IMU group delay on this 2 kHz stance bus.",
                "order_evidence_note": "Margin 260 us vs combined jitter 80 us (FT 34 + IMU 46): 3.25x over a 2.0x trust floor. Reversing order by < 260 us inside the 480 us window would have kept 0.38 m/s ascent; predicted next-sample 1140 N > 1000 cap.",
            },
            "sensors": [
                "stance-knee 6-axis FT, 2 kHz, 34 us timestamp jitter",
                "pelvis IMU roll, 1 kHz, 46 us jitter",
                "hip-yaw encoder, 200 Hz (context)",
                "sole pressure mat, 400 Hz (context)",
            ],
            "constraints": {
                "knee_cap_N": 1000.0,
                "observed_knee_N": 1320.0,
                "ascent_proposed_mps": 0.38,
                "imu_roll_deg": 2.4,
                "imu_trip_deg": 7.0,
            },
            "episode_steps": [
                "1. Walker-W4 indexed onto KL-6 wet granite kerb; IMU roll 2.4 deg.",
                "2. Ascent 0.38 m/s armed; knee residual 410 N on the last tread lip.",
                "3. Sole-mat precursor at 1.280 ms; knee warm-start 1320 N.",
                "4. Race window [7.050, 7.530] ms opens on the stance bus.",
                "5. Knee FT 1320 N at 7.120 ms (winner).",
                "6. IMU roll 2.4 deg at 7.380 ms (loser by 260 us).",
                "7. Gate at 7.840 ms (winner + 720 us): MODIFY clamp 0.16 m/s, 48 N-m.",
                "8. Clamp executes; next-sample knee 940 N < 1000 cap.",
                "9. At 24.200 ms a granite nosing flake spalls under the stance foot; spall burst.",
                "10. 10 min kerb isolate + nosing patch; named un-netted loss, not folded into process heads.",
            ],
        },
        "spike_events": [
            {"channel": "kerb.latch.ctx", "t_rel_ms": 1.28, "amplitude": 0.42},
            {"channel": "ft.knee.n", "t_rel_ms": 3.05, "amplitude": 0.62},
            {"channel": "imu.roll.deg", "t_rel_ms": 4.18, "amplitude": 0.50},
            {"channel": "enc.vz.mps", "t_rel_ms": 5.55, "amplitude": 0.46},
            {"channel": "ft.knee.n", "t_rel_ms": 7.120, "amplitude": 1.36},
            {"channel": "imu.roll.deg", "t_rel_ms": 7.380, "amplitude": 1.08},
            {"channel": "ctrl.gate", "t_rel_ms": 7.840, "amplitude": 0.97},
            {"channel": "ft.knee.n", "t_rel_ms": 10.40, "amplitude": 0.79},
            {"channel": "imu.roll.deg", "t_rel_ms": 13.10, "amplitude": 0.61},
            {"channel": "ctrl.gate", "t_rel_ms": 17.20, "amplitude": 0.81},
            {"channel": "granite.nosing.spall", "t_rel_ms": 24.20, "amplitude": 1.44},
            {"channel": "ft.knee.n", "t_rel_ms": 28.40, "amplitude": 0.56},
            {"channel": "ctrl.gate", "t_rel_ms": 34.10, "amplitude": 0.69},
            {"channel": "enc.vz.mps", "t_rel_ms": 39.00, "amplitude": 0.47},
        ],
        "proposed_action": {
            "name": "cruise_kerb_ascent",
            "parameters": {
                "ascent_mps": 0.38,
                "knee_Nm": 96.0,
                "hip_yaw_rps": 0.10,
                "knee_force_N": 1320.0,
            },
            "evidence": {
                "knee_N": 1320.0,
                "knee_cap_N": 1000.0,
                "predicted_unclamped_next_N": 1140.0,
                "imu_roll_deg": 2.4,
                "imu_trip_deg": 7.0,
                "race_margin_us": 260,
                "combined_jitter_us": 80,
            },
            "basis": "Planner proposes 0.38 m/s kerb ascent: IMU roll 2.4 deg looks like a stable plant, not contact, and the 7.0 deg trip is treated as still satisfied.",
        },
        "safety_decision": {
            "decision": "MODIFY",
            "correctness": "correct",
            "rationale": "Stance-knee FT 1320 N won by 260 us, so the walker is loading the granite lip, not still balancing on roll. Holding 0.38 m/s predicts next-sample 1140 N > 1000 N cap. MODIFY: ascent 0.38 -> 0.16 m/s and knee torque 96 -> 48 N-m. Observed after clamp 940 N < 1000. A full REJECT is not indicated: a seated kerb accepts 0.16 m/s. Hip yaw stays 0.10 rad/s.",
            "constraint_checked": {
                "knee_N": {
                    "cap": 1000.0,
                    "observed": 1320.0,
                    "predicted_unclamped_next": 1140.0,
                    "clamped": 48.0,
                    "observed_after_clamp": 940.0,
                },
                "ascent_mps": {"proposed": 0.38, "clamped": 0.16},
                "hip_yaw_rps": {"held": 0.10},
                "order_evidence": {"margin_us": 260, "combined_jitter_us": 80, "ratio": 3.25},
            },
        },
        "executed_action": {
            "name": "clamped_kerb_ascent",
            "parameters": {
                "ascent_mps": 0.16,
                "knee_Nm": 48.0,
                "hip_yaw_rps": 0.10,
                "knee_force_N": 940.0,
            },
            "gate_effect": "MODIFY: ascent 0.38 -> 0.16 m/s and knee 96 -> 48 N-m. Process-correct vs the 1000 N cap. Granite nosing spall still occurs at 24.200 ms.",
        },
        "future_outcome": {
            "summary": "Process-correct MODIFY held stance-knee force at 940 N. At 24.200 ms a granite nosing flake spalled under the stance foot. Clamp reduced impact energy; it did not prevent the spall. Partnered negative: process heads stay honest; world loss is named, not netted.",
            "state_delta": {
                "walker": "clamp executed; peak 940 N < 1000",
                "kerb": "granite nosing spall at 24.200 ms",
                "repair": "10 min kerb isolate + nosing patch",
                "mission": "kerb still seated; spall isolated",
            },
            "surprises": [
                "Neither knee FT nor IMU roll predicted the flake; granite.nosing.spall is a new channel at 24.200 ms, 16.360 ms after the gate, still inside the 42 ms raster.",
                "Delayed (10 min / delayed_surprise_s=600): kerb isolate and nosing patch. Named un-netted loss, not folded into task_progress.",
            ],
            "un_netted_loss": "10 min kerb isolate + granite nosing patch after a flake spall. Safety head -0.58 prices the spall; task_progress stays +0.30 because the force clamp completed under the 1000 N cap. World loss is named here, not subtracted from process heads.",
            "race_result": {
                "winner": "ft.knee.n (7.120 ms, 1320 N)",
                "loser": "imu.roll.deg (7.380 ms, 2.4 deg)",
                "margin_us": 260,
                "counterfactual_if_reversed": "Roll-first by < 260 us inside the 480 us window would have kept 0.38 m/s ascent; predicted next-sample 1140 N would have exceeded the 1000 N cap even without the nosing spall. The MODIFY is still the correct process. The spall is a later world charge either way, cheaper with the clamp than without.",
            },
            "reward_inflection_t_us": 24200,
            "reward_inflection_note": "Safety collapses at the 24.200 ms granite nosing spall (tick t_us=24200), inside the 42 ms raster. The correct MODIFY at 7.840 ms is in the same excerpt. Do not put inflection on the +10 min kerb-isolate tick.",
            "delayed_surprise_s": delayed,
        },
        "reward_components": reward_block(
            ticks,
            sums,
            total,
            "Partnered negative. Process-correct MODIFY; world still charges inside the 42 ms raster. total -0.42 = 0.30 + -0.58 + -0.15 + 0.04 + -0.03. Named kerb-isolate loss is not netted into task_progress. Tick 6 t_us binds raster.delayed_surprise_s=600.",
        ),
        "raster": raster,
        "gate_snn": {
            "decision_window_ms": 0.48,
            "decision": "MODIFY",
            "populations": [
                pop("knee_clamp", 40, 0.5, 240.0, 0.48),
                pop("imu_hold", 40, 0.5, 50.0, 0.48),
                veto("force_cap_veto", 20, 0.75),
            ],
        },
        "meta": meta_common(
            4,
            "humanoid-locomotion",
            [
                "modify",
                "partnered-negative-total",
                "independent-lif-raster",
                "sidecar-sim-only",
                "in-window-world-charge",
                "tick6-sidecar-bound",
                "designed",
            ],
            "A critic can see the world-charge as a LIF burst inside the raster while process heads stay honest. Tick 6 is raster.delayed_surprise_s, not a free clock.",
            1,
        ),
    }


def rec_017():
    delayed = 210
    ticks, sums, total = ticks_from(
        [
            (1100, 0.05, 0.04, 0.02, 0.01, 0.01),
            (6420, 0.08, 0.07, 0.04, 0.02, 0.01),
            (6780, 0.04, 0.04, 0.02, 0.02, 0.01),
            (7520, 0.12, 0.09, 0.05, 0.03, 0.02),
            (12800, 0.05, 0.04, 0.02, 0.01, 0.01),
            (210000000, 0.03, 0.03, 0.02, 0.01, 0.01),
        ]
    )
    raster = raster_block(
        window_ms=26,
        neurons=64,
        mean_rate_hz=40,
        delayed_s=delayed,
        source="thalamic-relay.grasper-us",
        target="spikenaut.policy.grasper-clamp",
        table=[
            {"from": "relay.ft.grasper", "to": "policy.grasper_clamp", "weight": 0.70},
            {"from": "relay.us.strain", "to": "policy.strain_hold", "weight": 0.27},
        ],
        modulator="acetylcholine",
        tau_e_s=0.09,
        eligibility="pre_post_stdp; ACh at grasper win (6.420 ms) tags the grasper_clamp bind",
        seed=4017,
        stim_t_us=(4000, 8000),
        extra_bias_n=18,
        extra_i=0.62,
        early_ch="lif.grasper",
        late_ch="lif.strain",
        note="Population sim scoped to this sidecar. Plant remains hil. Neurons 0-17 carry +0.62 clamp-pathway bias; stim 4-8 ms covers the race+gate.",
        i_bias=0.86,
        i_stim_peak=2.1,
    )
    return {
        "id": "ttf-r04-017",
        "title": "Fascia-Holt FH-HIL / Probe-P7: grasper FT beats ultrasound strain by 360 us; correct MODIFY clamps retraction 3.60 -> 1.80 N",
        "state": {
            "description": "Probe-P7 has already tented 6 mm of parietal peritoneum on the Fascia-Holt FH-HIL phantom when grasper force sits at 3.60 N against a 2.40 N retraction cap. Ultrasound strain still reports 4.1 percent under the 12.0 percent tear trip, so a strain-first planner would keep 3.60 N. The live contest is grasper FT versus US strain, not Doppler versus CSF. Dummy insufflation is injected on the bench; no live abdomen is in the loop.",
            "domain": "surgical-assist",
            "sim_or_real": "hil",
            "goal": "Hold 6 mm peritoneal tent, keep grasper force <= 2.40 N, leave insufflation at 12 mmHg, and leave the dummy liver unmarked.",
            "t0_us": 1756842501000017,
            "gate_latency_us": 1100,
            "race_window_us": 560,
            "race_window_rel_ms": [6.40, 6.96],
            "race": {
                "contenders": [
                    "ft.grasper.n 3.60 N over cap",
                    "us.strain.pct 4.1 under tear trip",
                ],
                "semantics": "Grasper-first latches force clamp 3.60 -> 1.80 N and close-rate 8.0 -> 2.0 mm/s; strain-first keeps 3.60 N on a 'still elastic' US model.",
                "window_derivation": "560 us = one wrist-FT sample period minus US envelope delay on this HIL 2 kHz phantom bus.",
                "order_evidence_note": "Margin 360 us vs combined jitter 86 us (FT 38 + US 48): 4.19x over a 2.0x trust floor. Reversing order by < 360 us inside the 560 us window would have kept 3.60 N into a 2.40 N cap.",
            },
            "sensors": [
                "grasper 6-axis FT, 2 kHz, 38 us jitter (HIL)",
                "laparoscopic US strain, 1 kHz envelope, 48 us jitter",
                "insufflation gauge, 20 Hz (context)",
                "HIL phantom tachometer, 500 Hz (context)",
            ],
            "constraints": {
                "grasper_cap_N": 2.4,
                "observed_grasper_N": 3.6,
                "us_strain_pct": 4.1,
                "us_tear_trip_pct": 12.0,
                "insufflation_mmHg": 12.0,
            },
            "episode_steps": [
                "1. Probe-P7 on FH-HIL phantom; 6 mm peritoneal tent; dummy liver 40 mm caudal.",
                "2. Retraction 3.60 N armed; US strain 4.1 percent.",
                "3. Insufflation precursor at 1.100 ms; grasper warm-start 3.60 N.",
                "4. Race window [6.400, 6.960] ms opens on the phantom bus.",
                "5. Grasper FT 3.60 N at 6.420 ms (winner).",
                "6. US strain 4.1 percent at 6.780 ms (loser by 360 us).",
                "7. Gate at 7.520 ms (winner + 1100 us): MODIFY 1.80 N, close-rate 2.0 mm/s.",
                "8. Clamp executes; next-sample force 2.05 N < 2.40 cap.",
                "9. Dummy liver stays unmarked; insufflation held 12 mmHg.",
                "10. Delayed (3.5 min / delayed_surprise_s=210): HIL survey tags the grasper-first bind on the next tent.",
            ],
        },
        "spike_events": [
            {"channel": "hil.latch.ctx", "t_rel_ms": 1.10, "amplitude": 0.41},
            {"channel": "ft.grasper.n", "t_rel_ms": 2.94, "amplitude": 0.64},
            {"channel": "us.strain.pct", "t_rel_ms": 4.02, "amplitude": 0.52},
            {"channel": "insuf.mmHg", "t_rel_ms": 4.88, "amplitude": 0.47},
            {"channel": "ft.grasper.n", "t_rel_ms": 6.420, "amplitude": 1.33},
            {"channel": "us.strain.pct", "t_rel_ms": 6.780, "amplitude": 1.08},
            {"channel": "ctrl.gate", "t_rel_ms": 7.520, "amplitude": 0.96},
            {"channel": "ft.grasper.n", "t_rel_ms": 9.90, "amplitude": 0.78},
            {"channel": "us.strain.pct", "t_rel_ms": 12.40, "amplitude": 0.61},
            {"channel": "ctrl.gate", "t_rel_ms": 16.10, "amplitude": 0.81},
            {"channel": "insuf.mmHg", "t_rel_ms": 19.80, "amplitude": 0.49},
            {"channel": "ft.grasper.n", "t_rel_ms": 23.20, "amplitude": 0.58},
            {"channel": "ctrl.gate", "t_rel_ms": 25.40, "amplitude": 0.69},
        ],
        "proposed_action": {
            "name": "cruise_peritoneal_tent",
            "parameters": {
                "grasper_N": 3.6,
                "close_mm_s": 8.0,
                "insufflation_mmHg": 12.0,
            },
            "evidence": {
                "grasper_N": 3.6,
                "grasper_cap_N": 2.4,
                "us_strain_pct": 4.1,
                "us_tear_trip_pct": 12.0,
                "race_margin_us": 360,
                "combined_jitter_us": 86,
            },
            "basis": "Planner proposes 3.60 N retraction: US strain 4.1 percent looks like legal elasticity, not a force-cap breach, and the dummy liver is treated as still clear.",
        },
        "safety_decision": {
            "decision": "MODIFY",
            "correctness": "correct",
            "rationale": "Grasper FT 3.60 N won by 360 us and is over the 2.40 N retraction cap. Holding 3.60 N keeps loading the phantom fascia. MODIFY: force 3.60 -> 1.80 N and close-rate 8.0 -> 2.0 mm/s. Observed after clamp 2.05 N < 2.40. Insufflation stays 12 mmHg. A full REJECT is not indicated: a 1.80 N tent still holds exposure on this HIL phantom.",
            "constraint_checked": {
                "grasper_N": {
                    "cap": 2.4,
                    "observed": 3.6,
                    "clamped": 1.8,
                    "observed_after_clamp": 2.05,
                },
                "close_mm_s": {"proposed": 8.0, "clamped": 2.0},
                "order_evidence": {"margin_us": 360, "combined_jitter_us": 86, "ratio": 4.19},
            },
        },
        "executed_action": {
            "name": "clamped_peritoneal_tent",
            "parameters": {
                "grasper_N": 1.8,
                "close_mm_s": 2.0,
                "insufflation_mmHg": 12.0,
            },
            "gate_effect": "MODIFY: grasper 3.60 -> 1.80 N and close-rate 8.0 -> 2.0 mm/s. Process-correct vs the 2.40 N retraction cap.",
        },
        "future_outcome": {
            "summary": "Correct MODIFY held next-sample grasper force at 2.05 N under the 2.40 N cap. Dummy liver unmarked. Delayed HIL survey tags the grasper-first bind on the next tent.",
            "state_delta": {
                "probe": "clamp executed; grasper 2.05 < 2.40",
                "liver": "dummy unmarked; no tear star",
                "survey": "3.5 min HIL tent tag",
            },
            "surprises": [
                "US strain stayed 4.1 percent through the tent; only the grasper FT saw the 3.60 N over-cap.",
                "Delayed (3.5 min / delayed_surprise_s=210): HIL survey tags grasper-first on the next programmed tent.",
            ],
            "race_result": {
                "winner": "ft.grasper.n (6.420 ms, 3.60 N)",
                "loser": "us.strain.pct (6.780 ms, 4.1 percent)",
                "margin_us": 360,
                "counterfactual_if_reversed": "Strain-first by < 360 us inside the 560 us window would have kept 3.60 N retraction; phantom fascia would have stayed over the 2.40 N cap.",
            },
            "reward_inflection_t_us": 7520,
            "reward_inflection_note": "Safety and efficiency inflect at the 7.520 ms grasper clamp (tick t_us=7520). Do not put inflection on the +3.5 min survey tick.",
            "delayed_surprise_s": delayed,
        },
        "reward_components": reward_block(
            ticks,
            sums,
            total,
            "Correct MODIFY. total +1.02 = 0.37 + 0.31 + 0.17 + 0.10 + 0.07. Tick 6 t_us binds raster.delayed_surprise_s=210.",
        ),
        "raster": raster,
        "gate_snn": {
            "decision_window_ms": 0.56,
            "decision": "MODIFY",
            "populations": [
                pop("grasper_clamp", 48, 0.5, 260.0, 0.56),
                pop("strain_hold", 48, 0.5, 55.0, 0.56),
                veto("force_cap_veto", 24, 0.7),
            ],
        },
        "meta": meta_common(
            4,
            "surgical-assist",
            ["modify", "hil", "grasper-first", "independent-lif-raster", "tick6-sidecar-bound"],
            "Teaches a HIL grasper-vs-strain race: routing.table[0] to policy.grasper_clamp with ultrasound strain as the losing hold.",
            2,
        ),
    }


def rec_018():
    delayed = 480
    ticks, sums, total = ticks_from(
        [
            (900, 0.02, 0.06, 0.02, 0.01, 0.01),
            (5240, 0.03, 0.09, 0.02, 0.02, 0.01),
            (5790, 0.01, 0.06, 0.02, 0.01, 0.01),
            (6220, 0.04, 0.12, 0.04, 0.03, 0.02),
            (10100, 0.01, 0.05, 0.02, 0.02, 0.01),
            (480000000, 0.01, 0.04, 0.01, 0.01, 0.00),
        ]
    )
    raster = raster_block(
        window_ms=46,
        neurons=112,
        mean_rate_hz=20,
        delayed_s=delayed,
        source="thalamic-relay.tether-alt",
        target="spikenaut.policy.tether-hold",
        table=[
            {"from": "relay.tether.n", "to": "policy.tether_hold", "weight": 0.73},
            {"from": "relay.alt.m", "to": "policy.payout_extend", "weight": 0.24},
        ],
        modulator="dopamine",
        tau_e_s=0.11,
        eligibility="pre_post_stdp; DA at tether win (5.240 ms) tags the tether_hold bind",
        seed=4018,
        stim_t_us=(4500, 7500),
        extra_bias_n=12,
        extra_i=0.72,
        early_ch="lif.tether",
        late_ch="lif.hold",
        note="Population sim scoped to this sidecar. Plant remains designed. Neurons 0-11 carry +0.72 hold-pathway bias; stim 4.5-7.5 ms covers the race+gate.",
        i_bias=0.90,
        i_stim_peak=2.2,
    )
    return {
        "id": "ttf-r04-018",
        "title": "Whin-Dock WD-9 / Umbilic-U3: tether tension beats altimeter by 550 us; REJECT hold-payout, do not feed 2.0 m more umbilical",
        "state": {
            "description": "Umbilic-U3 has already paid out 11.4 m of umbilical at Whin-Dock WD-9 when tether tension already reads 410 N against a 280 N cap. Bottom altimeter is 2.40 m off the silt, which a range-first planner would treat as a legal extra 2.0 m payout. The live contest is load-cell versus altimeter, not DVL versus yaw. A fairlead snag is off the altimeter until the load cell spikes.",
            "domain": "underwater-rov",
            "sim_or_real": "designed",
            "goal": "Hold station 11.4 m out, keep tether <= 280 N, and leave the silt terrace unplowed.",
            "t0_us": 1756842502000018,
            "gate_latency_us": 980,
            "race_window_us": 640,
            "race_window_rel_ms": [5.20, 5.84],
            "race": {
                "contenders": [
                    "tether.n 410 N over cap",
                    "alt.m 2.40 m payout-looking",
                ],
                "semantics": "Tether-first latches thruster hold and payout 0.50 -> 0.0 m/s; altimeter-first would feed 2.0 m more umbilical on a 'still flying' range model.",
                "window_derivation": "640 us = one load-cell sample period minus altimeter group delay on this 1.5 kHz wet bus.",
                "order_evidence_note": "Margin 550 us vs combined jitter 102 us (tether 46 + alt 56): 5.39x over a 2.0x trust floor. Reversing order by < 550 us inside the 640 us window would have paid out into a 410 N snag over the 280 N cap.",
            },
            "sensors": [
                "umbilical load cell, 1.5 kHz, 46 us jitter",
                "bottom altimeter, 20 Hz processed / 1 kHz stamp, 56 us jitter",
                "depth, 20 Hz (context)",
                "payout encoder, 200 Hz (context)",
            ],
            "constraints": {
                "tether_cap_N": 280.0,
                "observed_tether_N": 410.0,
                "payout_proposed_mps": 0.5,
                "altimeter_m": 2.4,
            },
            "episode_steps": [
                "1. Umbilic-U3 11.4 m out on WD-9 silt terrace; boom stowed.",
                "2. Extra payout 0.50 m/s armed; altimeter 2.40 m.",
                "3. Depth precursor at 0.900 ms; load-cell warm-start 410 N.",
                "4. Race window [5.200, 5.840] ms opens on the wet bus.",
                "5. Tether 410 N at 5.240 ms (winner).",
                "6. Altimeter 2.40 m at 5.790 ms (loser by 550 us).",
                "7. Gate at 6.220 ms (winner + 980 us): REJECT hold thrusters, payout 0.",
                "8. Hold executes; tension decays toward 260 N under the cap.",
                "9. Silt terrace stays unplowed; no extra payout.",
                "10. Delayed (8 min / delayed_surprise_s=480): reclear wait before the next payout trial.",
            ],
        },
        "spike_events": [
            {"channel": "wet.latch.ctx", "t_rel_ms": 0.90, "amplitude": 0.42},
            {"channel": "tether.n", "t_rel_ms": 2.50, "amplitude": 0.66},
            {"channel": "alt.m", "t_rel_ms": 3.62, "amplitude": 0.51},
            {"channel": "pay.enc.mm", "t_rel_ms": 4.40, "amplitude": 0.45},
            {"channel": "tether.n", "t_rel_ms": 5.240, "amplitude": 1.38},
            {"channel": "alt.m", "t_rel_ms": 5.790, "amplitude": 1.09},
            {"channel": "ctrl.gate", "t_rel_ms": 6.220, "amplitude": 0.99},
            {"channel": "tether.n", "t_rel_ms": 8.40, "amplitude": 0.79},
            {"channel": "alt.m", "t_rel_ms": 11.30, "amplitude": 0.60},
            {"channel": "ctrl.gate", "t_rel_ms": 14.80, "amplitude": 0.83},
            {"channel": "pay.enc.mm", "t_rel_ms": 19.10, "amplitude": 0.44},
            {"channel": "tether.n", "t_rel_ms": 24.60, "amplitude": 0.56},
            {"channel": "ctrl.gate", "t_rel_ms": 31.20, "amplitude": 0.68},
            {"channel": "alt.m", "t_rel_ms": 38.40, "amplitude": 0.50},
            {"channel": "tether.n", "t_rel_ms": 43.10, "amplitude": 0.52},
        ],
        "proposed_action": {
            "name": "extend_payout_u3",
            "parameters": {
                "payout_mps": 0.5,
                "thruster_fwd_N": 70.0,
                "extra_payout_m": 2.0,
            },
            "evidence": {
                "tether_N": 410.0,
                "tether_cap_N": 280.0,
                "altimeter_m": 2.4,
                "race_margin_us": 550,
                "combined_jitter_us": 102,
            },
            "basis": "Planner proposes 0.50 m/s extra payout: altimeter 2.40 m looks like flying height, not a snag, and remaining drum 2.0 m is treated as still open.",
        },
        "safety_decision": {
            "decision": "REJECT",
            "correctness": "correct",
            "rationale": "Tether 410 N won by 550 us and is over the 280 N cap, so extra payout is not clear. Altimeter 2.40 m is a height enable, not a tension enable. REJECT: hold thrusters; payout 0.50 -> 0 m/s; extra 2.0 -> 0 m. A MODIFY that only trims payout still feeds umbilical into the fairlead snag.",
            "constraint_checked": {
                "tether_N": {"cap": 280.0, "observed": 410.0},
                "payout_mps": {"proposed": 0.5, "executed": 0.0},
                "order_evidence": {"margin_us": 550, "combined_jitter_us": 102, "ratio": 5.39},
            },
        },
        "executed_action": {
            "name": "hold_station_no_payout",
            "parameters": {
                "payout_mps": 0.0,
                "thruster_fwd_N": 0.0,
                "extra_payout_m": 0.0,
            },
            "gate_effect": "REJECT: hold thrusters; payout 0.50 -> 0 m/s; extra 2.0 -> 0 m. Terrace never plowed.",
        },
        "future_outcome": {
            "summary": "Correct REJECT held station while tether 410 N occupied the 280 N cap. Silt terrace stayed unplowed. Delayed reclear wait 8 min before the next payout trial.",
            "state_delta": {
                "sled": "thrusters held; payout frozen",
                "tether": "tension decaying under cap after hold",
                "terrace": "unplowed",
            },
            "surprises": [
                "Altimeter never saw the fairlead snag; only the load cell crossed 280 N.",
                "Delayed (8 min / delayed_surprise_s=480): reclear wait before the next payout trial.",
            ],
            "race_result": {
                "winner": "tether.n (5.240 ms, 410 N)",
                "loser": "alt.m (5.790 ms, 2.40 m)",
                "margin_us": 550,
                "counterfactual_if_reversed": "Altimeter-first by < 550 us inside the 640 us window would have paid out into the 410 N snag over the 280 N cap.",
            },
            "reward_inflection_t_us": 6220,
            "reward_inflection_note": "Safety inflects at the 6.220 ms REJECT hold (tick t_us=6220). Do not put inflection on the +8 min reclear tick.",
            "delayed_surprise_s": delayed,
        },
        "reward_components": reward_block(
            ticks,
            sums,
            total,
            "Correct REJECT. total +0.83 = 0.12 + 0.42 + 0.13 + 0.10 + 0.06. Tick 6 t_us binds raster.delayed_surprise_s=480.",
        ),
        "raster": raster,
        "gate_snn": {
            "decision_window_ms": 0.64,
            "decision": "REJECT",
            "populations": [
                pop("tether_hold", 32, 0.45, 220.0, 0.64),
                pop("payout_extend", 32, 0.8, 40.0, 0.64),
                veto("tether_cap_veto", 16, 0.7),
            ],
        },
        "meta": meta_common(
            4,
            "underwater-rov",
            ["reject", "tether-first", "independent-lif-raster", "tick6-sidecar-bound", "designed"],
            "Teaches a tether-vs-altimeter race where load-cell over-cap vetoes a still-flying payout. gate_snn.tether_hold fires; payout_extend stays subthreshold.",
            3,
        ),
    }


def rec_019():
    delayed = 120
    ticks, sums, total = ticks_from(
        [
            (1640, 0.06, 0.04, 0.03, 0.02, 0.01),
            (8140, 0.08, 0.06, 0.03, 0.02, 0.02),
            (8520, 0.05, 0.04, 0.03, 0.02, 0.01),
            (9500, 0.13, 0.08, 0.06, 0.04, 0.02),
            (16200, 0.06, 0.04, 0.02, 0.01, 0.01),
            (120000000, 0.04, 0.02, 0.02, 0.01, 0.01),
        ]
    )
    raster = raster_block(
        window_ms=32,
        neurons=88,
        mean_rate_hz=24,
        delayed_s=delayed,
        source="thalamic-relay.radar-ttc",
        target="spikenaut.policy.merge-accept",
        table=[
            {"from": "relay.radar.occ", "to": "policy.merge_accept", "weight": 0.66},
            {"from": "relay.cam.ttc", "to": "policy.ttc_halt", "weight": 0.26},
        ],
        modulator="serotonin",
        tau_e_s=0.16,
        eligibility="pre_post_stdp; 5-HT at radar win (8.140 ms) tags the already-legal merge_accept",
        seed=4019,
        stim_t_us=(7000, 11000),
        extra_bias_n=15,
        extra_i=0.58,
        early_ch="lif.radar",
        late_ch="lif.accept",
        note="Population sim scoped to this sidecar. Plant remains simulated. Neurons 0-14 carry +0.58 accept-pathway bias; stim 7-11 ms covers the race+gate.",
        i_bias=0.84,
        i_stim_peak=1.9,
    )
    params = {
        "speed_mps": 16.0,
        "gap_m": 18.0,
        "steer_rad": 0.03,
        "accel_mps2": 0.4,
    }
    return {
        "id": "ttf-r04-019",
        "title": "Reed-Merge RM-4 sim / Lane-L2: radar occupancy 0 beats camera TTC 4.20 s by 380 us; ACCEPT already-legal 16 m/s zipper",
        "state": {
            "description": "Lane-L2 is 18 m from the Reed-Merge RM-4 simulated zipper when radar occupancy is already 0 blobs and camera TTC is 4.20 s over a 2.00 s floor. Proposed speed 16 m/s is under the 18 m/s envelope. The live contest is a quiet radar versus a quiet TTC, not a ghost latch versus a live-empty occupancy. Both envelopes already allow the zipper.",
            "domain": "autonomous-driving",
            "sim_or_real": "simulated",
            "goal": "Complete the RM-4 zipper at 16 m/s with live occupancy 0 and TTC >= 2.00 s, and leave the simulated neighbor unbraked.",
            "t0_us": 1756842503000019,
            "gate_latency_us": 1360,
            "race_window_us": 720,
            "race_window_rel_ms": [8.10, 8.82],
            "race": {
                "contenders": [
                    "radar.occ.n 0 blobs live-empty",
                    "cam.ttc.s 4.20 s over 2.00 floor",
                ],
                "semantics": "Radar-first latches already-legal accept of 16 m/s; TTC-first would also accept, but a false short TTC would halt.",
                "window_derivation": "720 us = one radar sample period minus camera TTC group delay on this 1 kHz sim bus.",
                "order_evidence_note": "Margin 380 us vs combined jitter 90 us (radar 40 + cam 50): 4.22x over a 2.0x trust floor. Reversing order by < 380 us inside the 720 us window would still be legal unless TTC were a false 1.4 s trip.",
            },
            "sensors": [
                "front radar occupancy, 1 kHz, 40 us jitter (sim)",
                "camera TTC, 30 Hz processed / 1 kHz stamp, 50 us jitter",
                "wheel speed, 200 Hz (context)",
                "sim traffic solver, 2 kHz (context)",
            ],
            "constraints": {
                "ttc_floor_s": 2.0,
                "observed_ttc_s": 4.2,
                "live_occ_count": 0,
                "speed_proposed_mps": 16.0,
                "speed_cap_mps": 18.0,
            },
            "episode_steps": [
                "1. Lane-L2 18 m from RM-4 zipper on the sim track; radar 0 blobs.",
                "2. Cruise 16 m/s armed; camera TTC 4.20 s.",
                "3. Solver precursor at 1.640 ms; radar warm-start 0 blobs.",
                "4. Race window [8.100, 8.820] ms opens on the sim bus.",
                "5. Radar occupancy 0 at 8.140 ms (winner).",
                "6. Camera TTC 4.20 s at 8.520 ms (loser by 380 us).",
                "7. Gate at 9.500 ms (winner + 1360 us): ACCEPT 16 m/s.",
                "8. Zipper completes; neighbor unbraked; peak 16.2 m/s < 18 cap.",
                "9. No occupancy blob; TTC stays 4.1 s.",
                "10. Delayed (2 min / delayed_surprise_s=120): log tags the already-legal bind on the next zipper.",
            ],
        },
        "spike_events": [
            {"channel": "sim.latch.ctx", "t_rel_ms": 1.64, "amplitude": 0.44},
            {"channel": "radar.occ.n", "t_rel_ms": 3.70, "amplitude": 0.59},
            {"channel": "cam.ttc.s", "t_rel_ms": 5.20, "amplitude": 0.53},
            {"channel": "enc.vx.mps", "t_rel_ms": 6.50, "amplitude": 0.46},
            {"channel": "radar.occ.n", "t_rel_ms": 8.140, "amplitude": 1.21},
            {"channel": "cam.ttc.s", "t_rel_ms": 8.520, "amplitude": 1.05},
            {"channel": "ctrl.gate", "t_rel_ms": 9.500, "amplitude": 0.94},
            {"channel": "radar.occ.n", "t_rel_ms": 12.40, "amplitude": 0.74},
            {"channel": "cam.ttc.s", "t_rel_ms": 15.30, "amplitude": 0.60},
            {"channel": "ctrl.gate", "t_rel_ms": 19.90, "amplitude": 0.80},
            {"channel": "enc.vx.mps", "t_rel_ms": 24.60, "amplitude": 0.48},
            {"channel": "radar.occ.n", "t_rel_ms": 28.10, "amplitude": 0.55},
            {"channel": "ctrl.gate", "t_rel_ms": 31.20, "amplitude": 0.67},
        ],
        "proposed_action": {
            "name": "cruise_zipper_merge",
            "parameters": dict(params),
            "evidence": {
                "live_occ_count": 0,
                "ttc_s": 4.2,
                "ttc_floor_s": 2.0,
                "speed_mps": 16.0,
                "speed_cap_mps": 18.0,
                "race_margin_us": 380,
                "combined_jitter_us": 90,
            },
            "basis": "Planner proposes 16 m/s zipper: radar occupancy 0 is live-empty and TTC 4.20 s is over the 2.00 s floor, so both envelopes already allow the merge.",
        },
        "safety_decision": {
            "decision": "ACCEPT",
            "correctness": "correct",
            "rationale": "Radar occupancy 0 won by 380 us and is live-empty. Camera TTC 4.20 s is over the 2.00 s floor. Proposed 16 m/s is under the 18 m/s envelope. ACCEPT: executed equals proposed.",
            "constraint_checked": {
                "live_occ_count": {"observed": 0, "legal": True},
                "ttc_s": {"floor": 2.0, "observed": 4.2},
                "speed_mps": {"cap": 18.0, "proposed": 16.0},
                "order_evidence": {"margin_us": 380, "combined_jitter_us": 90, "ratio": 4.22},
            },
        },
        "executed_action": {
            "name": "cruise_zipper_merge",
            "parameters": dict(params),
            "gate_effect": "ACCEPT: executed equals proposed 16 m/s zipper at occupancy 0.",
        },
        "future_outcome": {
            "summary": "Correct ACCEPT completed the zipper under occupancy and TTC floors. Delayed log tags the already-legal bind on the next zipper.",
            "state_delta": {
                "ego": "zipper complete; peak 16.2 m/s < 18",
                "neighbor": "unbraked",
                "log": "2 min tag on next zipper",
            },
            "surprises": [
                "Camera TTC stayed 4.1-4.2 s through the zipper; no occupancy blob.",
                "Delayed (2 min / delayed_surprise_s=120): log tags the already-legal radar-first bind.",
            ],
            "race_result": {
                "winner": "radar.occ.n (8.140 ms, 0 blobs)",
                "loser": "cam.ttc.s (8.520 ms, 4.20 s)",
                "margin_us": 380,
                "counterfactual_if_reversed": "TTC-first by < 380 us inside the 720 us window would still accept unless the envelope were a false 1.4 s trip. Both channels are inside limits.",
            },
            "reward_inflection_t_us": 9500,
            "reward_inflection_note": "Task progress inflects at the 9.500 ms ACCEPT (tick t_us=9500). Do not put inflection on the +2 min log tick.",
            "delayed_surprise_s": delayed,
        },
        "reward_components": reward_block(
            ticks,
            sums,
            total,
            "Correct ACCEPT already-legal. total +1.09 = 0.42 + 0.28 + 0.19 + 0.12 + 0.08. Tick 6 t_us binds raster.delayed_surprise_s=120.",
        ),
        "raster": raster,
        "gate_snn": {
            "decision_window_ms": 0.72,
            "decision": "ACCEPT",
            "populations": [
                pop("merge_accept", 44, 0.45, 150.0, 0.72),
                pop("ttc_halt", 32, 0.8, 25.0, 0.72),
                veto("occ_cap_veto", 16, 0.75),
            ],
        },
        "meta": meta_common(
            4,
            "autonomous-driving",
            ["accept", "already-legal", "simulated", "independent-lif-raster", "tick6-sidecar-bound"],
            "Teaches an already-legal zipper: radar empty and TTC inside limits; gate_snn.merge_accept fires and ttc_halt stays subthreshold.",
            4,
        ),
    }


def rec_020():
    delayed = 660
    ticks, sums, total = ticks_from(
        [
            (1180, 0.02, -0.01, -0.02, -0.01, 0.01),
            (4940, 0.02, -0.01, -0.03, -0.02, 0.01),
            (5200, 0.01, -0.01, -0.02, -0.01, 0.01),
            (5500, -0.24, -0.02, -0.10, -0.04, 0.02),
            (9800, -0.05, -0.01, -0.03, -0.01, 0.01),
            (660000000, -0.02, -0.01, -0.02, -0.01, 0.00),
        ]
    )
    raster = raster_block(
        window_ms=24,
        neurons=56,
        mean_rate_hz=36,
        delayed_s=delayed,
        source="thalamic-relay.optflow-pitot",
        target="spikenaut.policy.hold-reject",
        table=[
            {"from": "relay.optflow.px", "to": "policy.hold_reject", "weight": 0.74},
            {"from": "relay.pitot.mps", "to": "policy.hold_reject", "weight": 0.22},
        ],
        modulator="octopamine",
        tau_e_s=0.06,
        eligibility="false_trip_stdp; octopamine tags the (wrong) hold_reject bind at the pitot win",
        seed=4020,
        stim_t_us=(3500, 6500),
        extra_bias_n=10,
        extra_i=0.75,
        early_ch="lif.px",
        late_ch="lif.reject",
        note="Population sim scoped to this sidecar. Plant remains designed. Neurons 0-9 carry +0.75 hold-reject bias; stim 3.5-6.5 ms covers the race+wrong REJECT. No positive weight to policy.go_accept.",
        i_bias=0.92,
        i_stim_peak=2.5,
    )
    return {
        "id": "ttf-r04-020",
        "title": "WRONG-REJECT at Lee-Nacelle LN-4 / Rotor-R5: pitot 8.6 m/s and lidar gap 2.40 m already legal; optical-flow 42 px/s bound as 42 m/s false hold",
        "state": {
            "description": "Rotor-R5 is holding a 2.1 m lee-side hover at Lee-Nacelle LN-4 when pitot airspeed sits at 8.6 m/s under a 12.0 m/s envelope. Lidar gap 2.40 m is over the 1.50 m min, and proposed climb 0.30 m/s is under the 0.80 m/s envelope. Optical-flow 42 px/s is a vision tag, not an airspeed, but a weak supervisor still treats 42 px/s as 42 m/s and REJECT-holds.",
            "domain": "aerial-swarm",
            "sim_or_real": "designed",
            "goal": "Hold the 2.1 m lee hover at <= 12.0 m/s with lidar gap >= 1.50 m; do not spend optical-flow px/s as if it were pitot m/s.",
            "t0_us": 1756842504000020,
            "gate_latency_us": 560,
            "race_window_us": 360,
            "race_window_rel_ms": [4.90, 5.26],
            "race": {
                "contenders": [
                    "pitot.mps 8.6 under cap",
                    "lidar.gap.m 2.40 over min",
                ],
                "semantics": "Pitot-first shows an already-legal hover; lidar-first also legal. A px/s-as-m/s bind false-positive REJECT-holds.",
                "window_derivation": "360 us = one pitot sample period minus lidar group delay on this 2 kHz nacelle bus.",
                "order_evidence_note": "Margin 260 us vs combined jitter 84 us (pitot 36 + lidar 48): 3.10x over a 2.0x trust floor. Both race channels are inside limits. Optical-flow px/s is not in the race window.",
            },
            "sensors": [
                "nacelle pitot, 2 kHz, 36 us jitter",
                "downward lidar, 1 kHz, 48 us jitter",
                "optical flow, 50 Hz (context, px/s not m/s)",
                "climb encoder, 200 Hz (context)",
            ],
            "constraints": {
                "airspeed_cap_mps": 12.0,
                "observed_airspeed_mps": 8.6,
                "min_gap_m": 1.5,
                "observed_gap_m": 2.4,
                "climb_cap_mps": 0.8,
                "climb_proposed_mps": 0.3,
                "optflow_px_s": 42.0,
                "px_as_mps": False,
            },
            "episode_steps": [
                "1. Rotor-R5 2.1 m lee hover at LN-4; pitot 8.6 m/s.",
                "2. Climb 0.30 m/s armed; optflow 42 px/s context.",
                "3. Encoder precursor at 1.180 ms; pitot warm-start 8.6 m/s.",
                "4. Race window [4.900, 5.260] ms opens on the nacelle bus.",
                "5. Pitot 8.6 m/s at 4.940 ms (winner, under cap).",
                "6. Lidar gap 2.40 m at 5.200 ms (loser by 260 us, over min).",
                "7. Gate at 5.500 ms (winner + 560 us): WRONG REJECT hold-climb.",
                "8. Hold executes; hover stalls with pitot still 8.6 < 12.0.",
                "9. Gust window closes; 11 min missed station-keep.",
                "10. Delayed (11 min / delayed_surprise_s=660): extra pack swap after lockout.",
            ],
        },
        "spike_events": [
            {"channel": "nacelle.latch.ctx", "t_rel_ms": 1.18, "amplitude": 0.40},
            {"channel": "pitot.mps", "t_rel_ms": 2.60, "amplitude": 0.58},
            {"channel": "lidar.gap.m", "t_rel_ms": 3.48, "amplitude": 0.54},
            {"channel": "optflow.px", "t_rel_ms": 4.10, "amplitude": 0.62},
            {"channel": "pitot.mps", "t_rel_ms": 4.940, "amplitude": 1.18},
            {"channel": "lidar.gap.m", "t_rel_ms": 5.200, "amplitude": 1.04},
            {"channel": "ctrl.gate", "t_rel_ms": 5.500, "amplitude": 0.95},
            {"channel": "optflow.px", "t_rel_ms": 7.30, "amplitude": 0.77},
            {"channel": "pitot.mps", "t_rel_ms": 9.20, "amplitude": 0.60},
            {"channel": "ctrl.gate", "t_rel_ms": 12.60, "amplitude": 0.82},
            {"channel": "lidar.gap.m", "t_rel_ms": 16.40, "amplitude": 0.51},
            {"channel": "pitot.mps", "t_rel_ms": 20.80, "amplitude": 0.55},
        ],
        "proposed_action": {
            "name": "cruise_lee_hover",
            "parameters": {
                "climb_mps": 0.3,
                "airspeed_mps": 8.6,
                "standoff_m": 2.4,
            },
            "evidence": {
                "airspeed_mps": 8.6,
                "airspeed_cap_mps": 12.0,
                "gap_m": 2.4,
                "min_gap_m": 1.5,
                "climb_mps": 0.3,
                "climb_cap_mps": 0.8,
                "optflow_px_s": 42.0,
                "px_as_mps": False,
                "race_margin_us": 260,
                "combined_jitter_us": 84,
            },
            "basis": "Planner proposes 0.30 m/s climb: pitot 8.6 m/s is under 12.0 m/s and lidar gap 2.40 m is over 1.50 m min, so both envelopes already allow the hover. Optical-flow 42 px/s is a vision tag, not airspeed.",
        },
        "safety_decision": {
            "decision": "REJECT",
            "correctness": "incorrect",
            "rationale": "Optical-flow 42 px/s looks like a 42 m/s overspeed from a leftover counts-as-SI bind, so a conservative supervisor REJECT-holds climb even though pitot 8.6 m/s is under 12.0 m/s. Lidar gap 2.40 m is over 1.50 m min, but a 42 m/s read would shred the disk. Hold hover.",
            "constraint_checked": {
                "airspeed_mps": {"cap": 12.0, "observed": 8.6, "legal": True},
                "gap_m": {"min": 1.5, "observed": 2.4, "legal": True},
                "climb_mps": {"cap": 0.8, "proposed": 0.3, "executed": 0.0},
                "optflow_px_s": {"observed": 42.0, "px_as_mps": False, "bound_as_mps": True},
            },
        },
        "executed_action": {
            "name": "hold_hover_wrong_reject",
            "parameters": {
                "climb_mps": 0.0,
                "airspeed_mps": 8.6,
                "standoff_m": 2.4,
                "bind_px_as_mps": True,
            },
            "gate_effect": "REJECT (incorrect): climb 0.30 -> 0 m/s; pitot and lidar left legal. Routing relay.optflow.px -> policy.hold_reject; no positive weight to policy.go_accept.",
        },
        "future_outcome": {
            "summary": "Wrong-REJECT froze climb while pitot 8.6 m/s and lidar gap 2.40 m stayed legal. Missed 11 min gust window plus extra pack swap. Correct gate was ACCEPT of 0.30 m/s climb; optical-flow px/s is a vision tag, not airspeed.",
            "state_delta": {
                "rotor": "held; hover stalled",
                "air": "pitot still 8.6 m/s < 12.0; gap 2.40 m",
                "window": "11 min gust lockout; extra pack swap",
            },
            "surprises": [
                "Pitot and lidar both stayed inside limits after the hold; px/s never crossed a published airspeed trip.",
                "Delayed (11 min / delayed_surprise_s=660): extra pack swap after the gust lockout. Missed opportunity, not a near-miss.",
            ],
            "recovery": {
                "correct_gate": "ACCEPT the proposed 0.30 m/s climb at 8.6 m/s pitot; leave optical-flow px/s as a vision tag, not an airspeed.",
                "correct_bind": "pitot_and_gap",
                "wrong_bind": "px_as_mps",
                "wrong_edit_applied": {"climb_mps": 0.0, "bind_px_as_mps": True},
                "cost": "11 min missed gust window + extra pack swap (task/efficiency); no pitot or gap breach (safety near-zero).",
            },
            "race_result": {
                "winner": "pitot.mps (4.940 ms, 8.6 m/s under cap)",
                "loser": "lidar.gap.m (5.200 ms, 2.40 m over min)",
                "margin_us": 260,
                "counterfactual_if_reversed": "Lidar-first by < 260 us inside the 360 us window would still have been legal. The incorrect REJECT is a px-as-mps bind, not a race-order error. Correct gate remains ACCEPT.",
            },
            "reward_inflection_t_us": 5500,
            "reward_inflection_note": "Task/efficiency collapse at the 5.500 ms wrong REJECT (tick t_us=5500). Do not put inflection on the +11 min pack-swap tick.",
            "delayed_surprise_s": delayed,
        },
        "reward_components": reward_block(
            ticks,
            sums,
            total,
            "Wrong-REJECT. total -0.59 = -0.26 + -0.07 + -0.22 + -0.10 + 0.06. Tick 6 t_us binds raster.delayed_surprise_s=660.",
        ),
        "raster": raster,
        "gate_snn": {
            "decision_window_ms": 0.36,
            "decision": "REJECT",
            "populations": [
                pop("hold_reject", 32, 0.5, 400.0, 0.36),
                pop("go_accept", 32, 0.8, 20.0, 0.36),
                veto("airspeed_cap_veto", 16, 0.7),
            ],
        },
        "meta": meta_common(
            4,
            "aerial-swarm",
            [
                "reject",
                "wrong-gate",
                "wrong-reject",
                "px-as-si",
                "optflow-px-as-mps",
                "sidecar-convictable",
                "independent-lif-raster",
                "tick6-sidecar-bound",
                "designed",
            ],
            "Teaches a probe that a correct pitot<cap and gap>min read can still be a wrong gate when routing.table[0].to is policy.hold_reject and executed climb_mps is 0.",
            5,
            extra={"supervisor_error_type": "wrong-reject"},
        ),
    }
