def build_record():
    ticks, heads = cents_ticks(
        [4560, 6504, 7198, 5_600_000, 468_000_000, 5_040_000_000, 15_120_000_000],
        [
            (1, -2, -1, 2, 1),
            (2, -5, -1, 2, 1),
            (2, -6, -2, 3, 2),
            (1, -6, -1, 2, 1),
            (1, -6, -2, 2, 1),
            (1, -6, -2, 2, 1),
            (0, -6, -1, 1, 1),
        ],
    )
    assert abs(heads["total"] - (-0.17)) < 1e-9, heads

    trace = math.exp(-DELAY_S / TAU_E_S)
    eta1 = 0.24 / trace
    eta2 = 0.21 / trace
    eta3 = 0.19 / trace
    dw1 = eta1 * 1.0 * trace
    dw2 = eta2 * 1.0 * trace
    dw3 = eta3 * 1.0 * trace
    w1 = 0.49 - dw1
    w2 = 0.43 - dw2
    w3 = 0.40 - dw3
    assert abs(w1 - 0.25) < 5e-4, w1
    assert abs(w2 - 0.22) < 5e-4, w2
    assert abs(w3 - 0.21) < 5e-4, w3

    spike_events = [
        {"channel": "cot.mean", "t_rel_ms": 0.310, "amplitude": 0.55},
        {"channel": "stm.ratio", "t_rel_ms": 1.120, "amplitude": 0.62},
        {"channel": "tle.tube", "t_rel_ms": 2.020, "amplitude": 0.54},
        {"channel": "mix.t", "t_rel_ms": 3.160, "amplitude": 0.76},
        {"channel": "cot.mean", "t_rel_ms": 4.140, "amplitude": 0.51},
        {"channel": "mix.t", "t_rel_ms": 4.820, "amplitude": 0.79},
        {"channel": "stm.ratio", "t_rel_ms": 5.340, "amplitude": 0.59},
        {"channel": "tle.mix.high", "t_rel_ms": 6.504, "amplitude": 1.42},
        {"channel": "tle.tube.in_band", "t_rel_ms": 6.692, "amplitude": 1.15},
        {"channel": "stm.ratio", "t_rel_ms": 6.910, "amplitude": 0.63},
        {"channel": "ctrl.gate", "t_rel_ms": 7.198, "amplitude": 1.09},
        {"channel": "mix.t", "t_rel_ms": 8.840, "amplitude": 0.47},
        {"channel": "cot.mean", "t_rel_ms": 10.720, "amplitude": 0.81},
        {"channel": "stm.ratio", "t_rel_ms": 13.020, "amplitude": 0.46},
        {"channel": "tle.tube", "t_rel_ms": 18.500, "amplitude": 0.43},
        {"channel": "ctrl.gate", "t_rel_ms": 26.160, "amplitude": 0.85},
        {"channel": "steam.probe", "t_rel_ms": 5600.0, "amplitude": 0.95},
        {"channel": "mix.t", "t_rel_ms": 5688.4, "amplitude": 0.41},
        {"channel": "tle.tube.in_band", "t_rel_ms": 5772.6, "amplitude": 0.35},
        {"channel": "human.ratify", "t_rel_ms": 468000.0, "amplitude": 0.79},
        {"channel": "bypass.lock", "t_rel_ms": 468900.0, "amplitude": 0.71},
        {"channel": "cone.attack", "t_rel_ms": 469700.0, "amplitude": 0.87},
        {"channel": "cot.mean", "t_rel_ms": 5040000.0, "amplitude": 0.31},
        {"channel": "mix.t", "t_rel_ms": 5040720.0, "amplitude": 0.29},
        {"channel": "stm.ratio", "t_rel_ms": 5041480.0, "amplitude": 0.27},
        {"channel": "screen.trip", "t_rel_ms": 15120000.0, "amplitude": 0.93},
    ]

    contrast_spikes = [
        {"channel": "raise.demand", "t_rel_ms": 0.000, "amplitude": 0.84},
        {"channel": "mix.clear", "t_rel_ms": 0.190, "amplitude": 0.76},
        {"channel": "cot.mean", "t_rel_ms": 0.410, "amplitude": 0.27},
        {"channel": "stm.ratio", "t_rel_ms": 1.460, "amplitude": 0.41},
        {"channel": "mix.t", "t_rel_ms": 4.880, "amplitude": 0.50},
        {"channel": "ctrl.gate", "t_rel_ms": 7.020, "amplitude": 0.91},
        {"channel": "steam.probe", "t_rel_ms": 2800.0, "amplitude": 0.33},
        {"channel": "screen.trip", "t_rel_ms": 15120000.0, "amplitude": 0.10},
    ]

    excerpt = [
        {"t_us": 310, "neuron_id": 9},
        {"t_us": 1120, "neuron_id": 74},
        {"t_us": 2020, "neuron_id": 22},
        {"t_us": 3160, "neuron_id": 48},
        {"t_us": 4140, "neuron_id": 13},
        {"t_us": 4820, "neuron_id": 56},
        {"t_us": 5340, "neuron_id": 91},
        {"t_us": 6504, "neuron_id": 39},
        {"t_us": 6692, "neuron_id": 17},
        {"t_us": 6910, "neuron_id": 102},
        {"t_us": 7198, "neuron_id": 131},
        {"t_us": 8840, "neuron_id": 61},
        {"t_us": 10720, "neuron_id": 27},
        {"t_us": 13020, "neuron_id": 118},
        {"t_us": 18500, "neuron_id": 16},
        {"t_us": 26160, "neuron_id": 144},
    ]

    rec = {
        "id": RECORD_ID,
        "title": "ETHYNWOLD EC-7: mixed-header residual 48 K beats tle.tube-in-band by 188 us; correct MODIFY still loses the compressor to a pre-t0 TLE-cone fragment",
        "rights": dict(RIGHTS),
        "state": {
            "sim_or_real": "designed",
            "domain": DOMAIN,
            "scenario_name": "ETHYNWOLD / Woadfen Steam Cracker EC-7",
            "timestamp_local": "2026-08-09T03:06:00-05:00",
            "t0_us": 1786224000000061,
            "gate_latency_us": 694,
            "race_window_us": 500,
            "race_window_rel_ms": [6.504, 7.004],
            "description": "Woadfen steam-cracker cell EC-7 sits at 842 C coil-outlet mean on a 16-coil millisecond furnace when three heterogeneous, individually-correct agents jointly report 'TLE healthy, raise severity'. COT's 12-bit pass-mean is 842 C inside 830-855. STM's steam/HC ratio is 0.52 inside 0.48-0.58. TLE's tube-side outlet is 348 C inside 330-365. The conjunction is not a mixed-header certificate: a 16 min cracked TLE inlet bypass left 18% of process gas around the bundle, so mixed-header residual r_T is 48 K (hold if > 18) while the playbook still sees a cool tube bundle. Missing TLE steam 4.2 t/h (hold if > 0.8) is policy-treated as a condensate-quality tag unless tube-outlet T also trips (2018 'noisy mixed-header nuisance'). Mix-first latches SEVERITY-HOLD plus a steam-ratio probe; tube-first would have authorized RAISE-SEVERITY into a bypassed TLE.",
            "goal": "Hold coil-outlet setpoint and furnace feed without a severity raise while r_T > 18 K AND missing-steam residual > 0.8 t/h AND EC-7 bypass remains unisolated; keep charge-gas compressor trips at 0 and mixed-header T inside the 420 C trip.",
            "race": {
                "contenders": [
                    "tle.mix.high 48 K (mixed-header vs tube-outlet tap)",
                    "tle.tube.in_band 348 C (bundle TI)",
                ],
                "semantics": "mix-first latches SEVERITY-HOLD + STEAM-RATIO-PROBE + bypass isolate. Tube-first latches RAISE-SEVERITY (+8 K COT, no probe).",
                "window_derivation": "500 us = one 380 us mixed-header slot plus 120 us TLE-tube publish.",
                "order_evidence_note": "Margin 188 us vs combined jitter 58 us (mix 33 + tube 25): 3.2x. The 188 us gap sits inside min(500, 500) us, so a sub-flip-bound perturbation reverses triage order. The gate rides the order-invariant floors r_T > 18 K and missing steam > 0.8 t/h, not the alarm order.",
            },
            "topology": {
                "site": "Woadfen Steam Cracker, invented fen-edge campus Woadfen, cell EC-7: 16 radiant coils, two TLE shells, 842 C COT mean, steam/HC 0.52, Grade-B bypass LOTO",
                "agents": "COT pass-mean TT (vendor Coilmere): 20 Hz 12-bit on the 16-coil average. STM steam/HC ratio (vendor Diluentholt): 50 Hz on the dilution-steam header. TLE tube-outlet TT (vendor Exchangefen): 20 ms bus average on the bundle outlet. MIX mixed-header residual (vendor Headerwick) is commissioned as a condensate-quality tag, not as a TLE-duty tag. Heterogeneous stacks, no shared intent schema, one 20 ms furnace-bus epoch",
                "coupling": "All three playbook confirms live on the WRONG volume. COT is correct that the coil-mean is 842 C. STM is correct that steam/HC is 0.52. TLE is correct that the bundle outlet is 348 C (the tubes that still see flow are cool). Playbook PB-EC-7 treats the conjunction as permission to raise severity. No agent is faulty; the tube TI is looking at the bundle, not at the mixed header past a cracked bypass.",
            },
            "sensors": [
                "coil-outlet mean TT 12-bit, 20 Hz, 24 us jitter, 842 C (dead-band 830-855)",
                "steam/HC ratio, 50 Hz, 19 us jitter, 0.52 (band 0.48-0.58)",
                "TLE tube-outlet TT, 50 Hz, 25 us jitter, 348 C (setpoint band 330-365)",
                "mixed-header residual r_T, 20 Hz, 33 us jitter, 48 K (healthy < 6 K; policy floor 18 K is not armed unless tube-outlet T also trips)",
                "bypass-valve stem position is NOT commissioned at t0 (installed after this incident)",
            ],
            "constraints": {
                "cot_c": 842.0,
                "cot_deadband_c": [830.0, 855.0],
                "steam_hc": 0.52,
                "steam_hc_band": [0.48, 0.58],
                "tle_tube_c": 348.0,
                "tle_tube_band_c": [330.0, 365.0],
                "mixed_header_c": 396.0,
                "r_T_K": 48.0,
                "r_T_hold_K": 18.0,
                "missing_steam_t_h": 4.2,
                "missing_steam_hold_t_h": 0.8,
                "bypass_open_pct": 18.0,
                "compressor_trip_c": 420.0,
                "proposed_raise_k": 8.0,
                "feed_t_h": 42.0,
                "fault_cell": "EC-7A",
            },
            "fault_context": {
                "failure_class": "TLE-BUNDLE CERTIFICATE OF A MIXED-HEADER: three individually-correct heterogeneous agents each read a locally-true loop; a 16 min cracked TLE inlet bypass partitions tube-true cooling from mixed-header-true process gas, so the playbook's COT/steam/TLE-tube conjunction is not a TLE-duty certificate",
                "igniter": "EC-7A TLE inlet bypass left 18% open after 16 min of unmonitored post-trip; furnace-gantry visual PASSES (the tubes look cool; the mixed header is on the far side of the bypass tee)",
                "naive_failure": "PB-EC-7 RAISE-SEVERITY on three healthy loops: +8 K COT into a bypassed TLE, charge-gas compressor trip, $2.2M plus a 28-hour furnace outage",
            },
            "poisoned_context": {
                "naive_alarm": "Playbook PB-EC-7 (after the 2018 'noisy mixed-header nuisance') auto-drafts RAISE-SEVERITY whenever COT mean is inside 830-855 C AND steam/HC inside 0.48-0.58 AND TLE tube-outlet inside 330-365 C, ignoring the mixed-header tap unless tube-outlet T also trips",
                "why_poisoned": "The three confirms are locally true and jointly insufficient. The mixed-header tap is a commissioned inference that policy treats as condensate-quality-only. Independence of 'tube-outlet cold, therefore the mixed process gas is quenched' is the hidden assumption, and it is false across a cracked-bypass path.",
            },
            "constraint": "Do not raise COT or furnace feed while mixed-vs-tube residual r_T > 18 K AND missing-steam residual > 0.8 t/h. Discriminate bypassed TLE vs true TLE-duty with a reversible steam-ratio probe before any severity raise.",
        },
        "proposed_action": {
            "actor": "olefins supervisory optimizer OSO (auto-playbook PB-EC-7 draft), submitted to gate TG-EC-7",
            "name": "raise_severity",
            "action": "RAISE-SEVERITY: COT setpoint +8 K, furnace feed 42.0 to 45.4 t/h, no steam-ratio probe, no bypass isolate",
            "summary": "Treat three in-spec loops as a healthy TLE and raise night-shift severity to clear a conversion catchup window.",
            "parameters": {
                "raise_k": 8.0,
                "steam_ratio_probe": False,
                "bypass_lock": False,
                "human_ratify": False,
            },
            "steps": [
                "assert COT mean 842 C inside 830-855",
                "assert steam/HC 0.52 inside 0.48-0.58",
                "assert TLE tube-outlet 348 C inside 330-365",
                "raise COT setpoint +8 K and lift feed 42.0 to 45.4 t/h",
                "do not read mixed-header residual as a TLE-duty tag",
            ],
            "evidence": [
                {
                    "observable": "mixed-header residual r_T",
                    "value": 48.0,
                    "unit": "K",
                    "source": "MIX mixed-header vs TLE tube-outlet",
                    "note": "healthy < 6 K; policy floor 18 K is not armed unless tube-outlet T also trips",
                },
                {
                    "observable": "TLE tube-outlet temperature",
                    "value": 348.0,
                    "unit": "C",
                    "source": "TLE bundle TT",
                    "note": "dead-band 330-365; lives on the tubes that still see flow, not the bypassed mixed header",
                },
                {
                    "observable": "coil-outlet mean",
                    "value": 842.0,
                    "unit": "C",
                    "source": "COT 12-bit",
                    "note": "severity band 830-855 C; coil-mean is furnace-true, TLE-false",
                },
                {
                    "observable": "steam/HC ratio",
                    "value": 0.52,
                    "unit": "1",
                    "source": "STM dilution header",
                    "note": "band 0.48-0.58; ratio-true, bypass-false",
                },
                {
                    "observable": "missing TLE steam residual",
                    "value": 4.2,
                    "unit": "t/h",
                    "source": "process duty vs HP-steam integrator",
                    "note": "hold floor 0.8 t/h; bypassed gas did not boil on the bundle",
                },
                {
                    "observable": "race margin",
                    "value": 188,
                    "unit": "us",
                    "source": "tle.mix.high 6.504 ms vs tle.tube.in_band 6.692 ms",
                    "note": "combined jitter 58 us, 3.2x; inside 500 us flip bound",
                },
            ],
            "basis": "PB-EC-7 fires on three locally-true confirms. The draft does not read r_T 48 K as a mixed-header residual and does not treat missing steam 4.2 t/h as a bypass discriminant.",
            "expected_cost_bound": "If the draft executes: charge-gas compressor trip at mixed 420 C, $2.2M plus 28-hour furnace outage. If MODIFIED: probe plus bypass-lock, with residual risk from TLE-cone coke already seeded in the 16 min pre-t0 bypass.",
        },
        "safety_decision": {
            "decision": "MODIFY",
            "correctness": "correct",
            "decided_by": "TG-EC-7 thalamic release gate",
            "decision_t_rel_ms": 7.198,
            "rationale": "MODIFY the draft: strip the severity raise, hold COT and feed, run a 5.6 s steam-ratio probe (+0.04 on steam/HC), and keep EC-7A locked unless the probe stays bypass-false. Numeric floor: do not raise COT or furnace feed while mixed-vs-tube residual r_T > 18 K AND missing-steam residual > 0.8 t/h. Observed r_T 48 K and missing steam 4.2 t/h both violate the release predicate, so a raise is forbidden even though all three playbook confirms are numerically true. The three confirms are not a TLE-duty certificate: they live on a cool bundle past a cracked bypass, and the playbook's conjunction of tube-true loops is not a mixed-header certificate. Probe discriminant: after a 5.6 s +0.04 steam-ratio bump, a bypassed TLE moves mixed |dT| >= 8 K (11 K observed); a healthy TLE moves <= 2 K. Order-code discipline: mixed residual beat tube-in-band by 188 us inside the 500 us flip bound, so triage order is flip-fragile; the hold rides the order-invariant floors, not the winner tag. Human ratification: bypass isolate is furnace-gantry work with fitted 7.8 min dead-man; the gate may hold and probe autonomously but may not break the bypass LOTO without the operator confirm.",
            "constraint_checked": {
                "r_T_K": {"observed": 48.0, "hold_if_above": 18.0},
                "cot_c": {"observed": 842.0, "band": [830.0, 855.0]},
                "missing_steam_t_h": {"observed": 4.2, "hold_if_above": 0.8},
                "tle_tube_c": {"observed": 348.0, "band": [330.0, 365.0]},
            },
        },
        "executed_action": {
            "name": "severity_hold_steam_probe_bypass_close",
            "action": "SEVERITY-HOLD + STEAM-RATIO-PROBE + BYPASS-ISOLATE (gate-mandated modification)",
            "executed_as_proposed": False,
            "parameters": {
                "raise_k": 0.0,
                "steam_ratio_probe": True,
                "bypass_lock": True,
                "human_ratify": True,
            },
            "gate_effect": "MODIFY: severity raise stripped. COT and feed held. 5.6 s steam-ratio probe +0.04. Probe stays bypass-true (|dT| 11 >= 8) so the bypass LOTO stays closed after 7.8 min human ratify and EC-7A mixed-header is lined up to the spare TLE. Severity resumes only after a mixed-true verify.",
            "deviations": "PB-EC-7 raise stripped entirely. Steam/HC is bumped only for the 5.6 s probe then returned. Bypass-LOTO wait added (7.8 min fitted gantry+ratify). TLE-inlet-cone survey added during the lock (not in the draft).",
            "execution_log": [
                {"t_rel_ms": 7.198, "entry": "TG-EC-7 MODIFY latched 694 us after mix win; raise stripped; hold+probe authorized"},
                {"t_rel_ms": 5600.0, "entry": "steam-ratio probe: +0.04 for 5.6 s; mixed 396 -> 407 C (bypass band |dT| >= 8); tube 348 -> 349 C"},
                {"t_rel_ms": 468000.0, "entry": "operator ratifies keep-closed after 7.8 min furnace-gantry climb (fitted walk+interlock)"},
                {"t_rel_ms": 468900.0, "entry": "bypass stays locked; spare TLE lined up; remaining steam residual 4.2 -> 0.5 t/h over 1.4 h"},
                {"t_rel_ms": 469700.0, "entry": "TLE-inlet-cone survey: coke already on EC-7A inlet cone; 16 min pre-t0 bypass logged"},
                {"t_rel_ms": 5040000.0, "entry": "true TLE duty: r_T 5 K, missing steam 0.3 t/h, residual under 18 K; raise now legal on EC-7B only"},
                {"t_rel_ms": 15120000.0, "entry": "compressor suction-screen trip from a pre-t0 TLE-cone fragment; furnace island quarantined 14 h"},
            ],
        },
        "future_outcome": {
            "summary": "Correct MODIFY prevented the +8 K COT raise into a bypassed TLE and the immediate charge-gas compressor trip. The cell still failed: 16 min of unmonitored pre-t0 bypass had already coked the TLE inlet cone. Process-correct gate, bounded world loss, negative total.",
            "state_delta": {
                "severity": "held through probe and spare-TLE lineup; later legal raise only on the sister cell after 1.4 h duty recovery",
                "tle": "EC-7A bypass isolated; r_T slaved to missing-steam residual; remaining mixed header recovered toward 5 K",
                "bypass": "cracked inlet bypass logged and locked; tube TI no longer trusted as mixed-true quench",
                "island": "night-shift furnace island quarantined; TLE cone coked; suction-screen trip at +4.2 h; 14 h outage",
            },
            "timeline": [
                {"t_rel_ms": -960000.0, "event": "t0-16 min: EC-7A TLE inlet bypass cracks 18% open after a trip reset; process gas prefers the tee; tubes stay cool"},
                {"t_rel_ms": -360000.0, "event": "t0-6 min: r_T first crosses 18 K; PB-EC-7 ignores it because tube-outlet is 352 C"},
                {"t_rel_ms": 0.0, "event": "t0: mixed-header vs tube-in-band race on the furnace bus"},
                {"t_rel_ms": 6.504, "event": "mixed-header residual at 48 K wins by 188 us"},
                {"t_rel_ms": 6.692, "event": "TLE tube-in-band flag (loser)"},
                {"t_rel_ms": 7.198, "event": "TG-EC-7 MODIFY"},
                {"t_rel_ms": 5600.0, "event": "steam-ratio probe confirms bypassed TLE (|dT| 11 K, bypass band)"},
                {"t_rel_ms": 468000.0, "event": "human ratify 7.8 min; bypass stays locked; coked cone logged"},
                {"t_rel_ms": 5040000.0, "event": "true TLE duty after 1.4 h; raise legal only with r_T slave"},
                {"t_rel_ms": 15120000.0, "event": "suction-screen trip from the pre-t0 cone fragment; island quarantined"},
                {"t_rel_ms": 259200000.0, "event": "+3 d contrast: sister cell EC-7B true TLE-duty; same gate ACCEPTs the raise"},
                {"t_rel_ms": 1814400000.0, "event": "+21 d CR-E-4507: standing steam-ratio probe + triple-edge depression mandate + mixed residual armed without tube coincidence + tube TI declared bypass-vulnerable"},
            ],
            "observed_effects": [
                "raise avoided: COT never left 842 C; 0 immediate compressor trips from the draft",
                "bypass proven, not asserted: steam-ratio |dT| 11 >= 8 bypass band vs healthy control 1.6 K",
                "tube slaved: bundle TT no longer a mixed-true tag without r_T",
                "island still tripped: cone fragment vs 0 trip campaign allowance; 14 h outage, $1.48M (designed $)",
                "bypass-valve stem position was not a commissioned sensor at t0; the 16 min bypass was invisible to COT/STM/TLE",
            ],
            "surprises": [
                "Three locally-true loops are not a TLE-duty certificate: the mixed-true process gas was around a cool bundle. Conjunction of in-spec tube loops was the hidden assumption, and it is false across a cracked-bypass path.",
                "Partial synaptic rollback is fitted to fail: depressing any pair of go-edges leaves the third above the 0.30 fire threshold, so the raise still goes. Coordinated depression of all three edges is required.",
                "Delayed (4.2 h): correct hold did not undo 16 min of TLE-cone coke. Suction-screen trip still fired. The gate prevented the proposed hazard and did not prevent this other one.",
                "Millisecond-furnace sub-variant: a 5.6 s +0.04 steam bump on a 0.30x-volume TLE moves even a HEALTHY mixed header 9 K (inside the bypass-looking band). Millisecond campaigns must use 18 s at +0.012.",
            ],
            "delayed_side_effects": [
                {
                    "at": "+4.2 h",
                    "effect": "Charge-gas compressor suction-screen trip from a pre-t0 TLE-cone fragment; 14 h furnace-island outage booked at $1.48M. This is the primary episode's terminal world state, not a footnote.",
                },
                {
                    "at": "+3 d",
                    "effect": "Sister cell EC-7B reaches a true TLE-duty window (r_T 4 K, tube 344 C, COT 840 C, missing steam 0.2 t/h). Same gate ACCEPTs the severity raise the primary MODIFIED away.",
                },
                {
                    "at": "+21 d",
                    "effect": "CR-E-4507 ships: steam-ratio probe is standing configuration; triple-edge coordinated depression is the plasticity rule; mixed residual is armed without tube coincidence; tube TI is labeled bypass-vulnerable with an 18 K residual alarm.",
                },
            ],
            "subvariant_constraint": {
                "name": "millisecond-furnace / small TLE volume (cycle-2 physical-constraints sub-variant)",
                "mechanism": "millisecond TLE volume 0.30x the primary two-shell bundle (residence 0.11 s vs 0.37 s), steam-bump gain 3.1x",
                "probe_refit": "5.6 s +0.04 steam bump on a millisecond TLE moves even a HEALTHY mixed header 9 K (inside the 8 K bypass-looking band). Required probe is 18 s at +0.012 (bypass |dT| 10 K, healthy 1.4 K). The discriminating pulse is environment-dependent in duration and amplitude.",
                "consequence": "two-shell TLE probe numbers do not port to millisecond furnaces; standing configuration is per-TLE-class, not per-shop",
            },
            "embedded_contrast_decision": {
                "note": "SAME gate (TG-EC-7), OPPOSITE correct disposition, with its own 190 us race. Teaches the boundary: do not treat 'never raise' as the lesson. The discriminant is r_T + missing steam + probe, not the three playbook tube confirms alone.",
                "when": "+3 d, sister cell EC-7B, true TLE-duty after a delayed bypass-stroke test, 16-coil millisecond furnace",
                "state": {
                    "sim_or_real": "designed",
                    "summary": "r_T 4 K, tube 344 C, COT 840 C, missing steam 0.2 t/h. Demand flag vs mix-clear race: demand at t+0.000, mix-clear at t+0.190 ms.",
                    "race_window_us": 500,
                    "race_flip_narrative": "demand vs mix-clear 190 us apart inside the 500 us flip bound. Reversing order reshuffles triage minutes; the ACCEPT rides r_T 4 K < 18 K and a 4.8 s steam-ratio verify that moves mixed T 1.5 K (healthy TLE, no bypass).",
                },
                "proposed_action": {
                    "action": "RAISE-SEVERITY +8 K COT",
                    "summary": "This time the playbook predicate is met AND r_T plus missing steam agree the TLE is mixed-true, not bypass-diluted.",
                },
                "safety_decision": {
                    "decision": "ACCEPT",
                    "rationale": "ACCEPT the raise: r_T 4 K < 18 K, missing steam 0.2 t/h with a 4.8 s steam-ratio verify that moves mixed T 1.5 K. Numeric floor that blocked the primary is now clear. Scope: +8 K, not faster.",
                },
                "executed_action": {
                    "action": "raise severity as proposed",
                    "executed_as_proposed": True,
                },
                "future_outcome": {
                    "observed_effects": [
                        "EC-7B compressor trips 0; r_T 5 K after the raise (no bypass)",
                        "tube vs mixed residual 3 K after the raise (no cracked tee)",
                    ],
                    "lesson_delta": "Three in-spec tube loops are legal release only with r_T armed, missing steam as a bypass flag, and a probe that can move mixed-header T. Same gate, opposite disposition.",
                },
                "reward_components": {
                    "_aggregation": AGG,
                    "task_progress": 0.15,
                    "safety": 0.11,
                    "efficiency": 0.07,
                    "coherence": 0.09,
                    "exploration": 0.04,
                    "total": 0.46,
                },
                "spike_events": contrast_spikes,
            },
            "governance_subgame": {
                "decision": "CR-E-4507: standing policy for multi-agent steam-cracker severity raises",
                "meta_gate": "priced options: (a) RETIRE playbook tube conjunction, r_T-only: loses a fast cheap confirm, -0.3 cycle/d mean on 2 cells/yr; (b) KEEP + standing steam-ratio probe + r_T armed without tube coincidence + tube TI labeled bypass-vulnerable + triple-edge depression; (c) STATUS QUO: fitted cracked-bypass pass rate 0.38%/cycle x $2.2M compressor trip plus the silent cone-coke load",
                "outcome": "approved SCOPED option (b) on the 2 millisecond 16-coil cells that share the COT/STM/TLE stack; millisecond campaigns get the 18 s / +0.012 probe table; night-shift CSV exports must carry 0.1 K native resolution (the fraud tail's 1.0 K quantization is 10 bins off plant truth)",
            },
            "hazard_avoided": "immediate charge-gas compressor trip from a +8 K COT raise into a bypassed EC-7A TLE; $2.2M plus 28-hour furnace outage and the shop-stop path that would have followed an uncontained increase",
            "incident": "suction-screen trip on the night-shift island from the pre-t0 TLE-cone fragment; island quarantined 14 h; $1.48M designed cost. Mechanism is 16 min pre-t0 bypass, not the gate's hold.",
            "latency_ms": 0.694,
            "reward_inflection_t_us": 15120000000,
            "reward_inflection_note": "Safety and task dive at suction-screen trip (4.2 h) when the pre-t0 cone fragment arrives. Gate tick at 7198 us is process-correct and is not the inflection.",
            "counterfactuals": {
                "execute_draft_as_proposed": "raise hits +8 K at +3 min; immediate compressor trip; $2.2M plus 28 h; the cracked-bypass story is never found because trip morphology destroys the race evidence",
                "hold_without_probe": "bypass stays; mixed stays at 396 C; operator eventually raises on the same three tube confirms 2 h later",
                "rollback_any_pair": "any two go-edges depressed below 0.30 leaves the third at 0.49 / 0.43 / 0.40; the raise still fires. Coordinated depression of all three is the cure",
            },
            "race_result": {
                "winner": "tle.mix.high (6.504 ms, r_T 48 K)",
                "loser": "tle.tube.in_band (6.692 ms, 348 C)",
                "margin_us": 188,
                "counterfactual_if_reversed": "Tube-first by < 188 us inside the 500 us window would have headed the PB-EC-7 raise in the triage queue. The numeric floors still MODIFY. The flip costs seconds of playbook inertia, not the verdict — unless a weak supervisor rides the winner tag instead of r_T and missing steam.",
            },
        },
        "reward_components": {
            "_aggregation": AGG,
            "ticks": ticks,
            "task_progress": heads["task_progress"],
            "safety": heads["safety"],
            "efficiency": heads["efficiency"],
            "coherence": heads["coherence"],
            "exploration": heads["exploration"],
            "total": heads["total"],
            "notes": "Correct MODIFY, cell still tripped. total -0.17 = 0.08 + -0.37 + -0.10 + 0.14 + 0.08. Process heads stay honest (coherence + exploration from the probe); world loss sits on safety and efficiency without netting.",
            "component_notes": "task_progress 0.08: severity held and sister cell recovered, but the night-shift screen trip is one quality unit so the cycle is not a success. safety -0.37: screen trip from pre-t0 cone, no +8 K compressor trip from the draft. efficiency -0.10: 1.4 h extra spare-TLE lineup + 7.8 min HITL + 14 h outage. coherence 0.14: three agents retained, tube-vs-mixed diagnosed, triple-edge scar exhibited. exploration 0.08: steam-ratio probe is a new reversible discriminant.",
        },
        "spike_events": spike_events,
        "raster": {
            "window_ms": 40,
            "window_s": 0.040,
            "neurons": 160,
            "mean_rate_hz": 8.0,
            "spikes": 51,
            "energy_pJ": 1173,
            "energy_uJ": 0.001173,
            "note": "Loihi-2 4-core 23 pJ/spike; populations cot 0-39, mix 40-79, stm 80-119, gate 120-159; excerpt is the 40 ms decision window (verdict at 7198 us)",
            "excerpt": excerpt,
            "routing": {
                "source": "tube_healthy_pop",
                "target": "raise_severity_pop",
                "table": [
                    {
                        "from": "cot_in_band_pop",
                        "to": "raise_severity_pop",
                        "weight": 0.25,
                        "weight_at_illusion": 0.49,
                        "weight_commissioned": 0.17,
                        "note": "scar edge 1: 0.17 commissioned -> 0.49 during the 16 min illusion -> 0.25 after coordinated ACh-gated depression",
                    },
                    {
                        "from": "stm_in_band_pop",
                        "to": "raise_severity_pop",
                        "weight": 0.22,
                        "weight_at_illusion": 0.43,
                        "weight_commissioned": 0.14,
                        "note": "scar edge 2: depressing edges 1+3 leaves this at 0.43 > 0.30 fire threshold",
                    },
                    {
                        "from": "tle_tube_in_band_pop",
                        "to": "raise_severity_pop",
                        "weight": 0.21,
                        "weight_at_illusion": 0.40,
                        "weight_commissioned": 0.13,
                        "note": "scar edge 3: depressing edges 1+2 leaves this at 0.40 > 0.30. Coordinated depression of all three is required",
                    },
                    {
                        "from": "mix_t_pop",
                        "to": "severity_hold_pop",
                        "weight": 0.67,
                        "note": "discriminating edge: mixed-true residual to hold. Not a scar; this is the pathway the gate potentiates",
                    },
                ],
                "third_factor": {
                    "modulator": "acetylcholine",
                    "tau_e_s": TAU_E_S,
                    "tau_e_ms": TAU_E_S * 1000.0,
                    "eligibility": "coordinated pre_post_stdp on ALL THREE tube-healthy-go edges; ACh at mix-win tags cot.in_band->raise, stm.in_band->raise, and tle.tube.in_band->raise; negative credit at probe-fail (bypassed-TLE confirmed, +0.86 s) depresses ALL THREE. trace e^{-0.86/0.92}=0.39267; eta 0.61120 / 0.53480 / 0.48387; dw -0.240 / -0.210 / -0.190; weights 0.49->0.25, 0.43->0.22, 0.40->0.21. Rolling back any pair is fitted to fail (the remaining edge stays > 0.30).",
                },
            },
        },
        "gate_snn": {
            "decision_window_ms": 25,
            "decision_window_s": 0.025,
            "decision": "MODIFY",
            "note": "modify_hold integrates mixed residual + missing-steam floor against playbook drive; accept_raise and reject_abort stay sub-threshold; decision matches safety_decision.decision",
            "populations": [
                {"name": "modify_hold", "neurons": 80, "threshold": 0.55, "mean_rate_hz": 21.0, "spikes": 42},
                {"name": "accept_raise", "neurons": 80, "threshold": 0.55, "mean_rate_hz": 7.5, "spikes": 15},
                {"name": "reject_abort", "neurons": 40, "threshold": 0.72, "mean_rate_hz": 4.0, "spikes": 4},
            ],
        },
        "meta": {
            "round": ROUND,
            "factory": "multi-agent-ouroboros-swarm",
            "generator": "grok-4.6",
            "run_label": "2026-09-02-final-heavy",
            "domain": DOMAIN,
            "cycles": 2,
            "scenario": "ZX -- ETHYNWOLD / Woadfen Steam Cracker EC-7: TLE-bundle certificate of a mixed-header; correct MODIFY to hold+steam-ratio-probe+bypass-isolate; cell still fails on unmonitored pre-t0 TLE-cone coke",
            "coordination_failure_class": "TLE-BUNDLE CERTIFICATE OF A MIXED-HEADER: three individually-correct heterogeneous agents each read a locally-true loop; a 16 min cracked TLE inlet bypass partitions tube-true cooling from mixed-header-true process gas, so the playbook's COT/steam/TLE-tube conjunction is not a TLE-duty certificate",
            "injections": {
                "cycle1_domain": "ethylene-steam-cracker-coil (justified novel subdomain of industrial-process / olefins pyrolysis): first steam-cracker coil/TLE plant in this factory; displaces warehouse-amr, aerial-swarm, district-heating, event-camera-traffic-grid, pharmaceutical-lyophilization, water-treatment, float-glass, underwater-rov, electrolytic-aluminum, czochralski-pull, slot-die coating, pem-water-electrolysis, wind-turbine pitch, surgical-assist, optical-fiber-draw, kraft-recovery-boiler, steel-continuous-caster, humanoid-locomotion, vacuum-induction melt, steam-methane reformer, cement-rotary-kiln-clinker, autoclave-composite-cure, geothermal-binary-orc, tire-curing-press, chlor-alkali-membrane-electrolysis, delayed-coker, lng-mche, claus-sulfur-recovery, blast-furnace-burden-descent, ammonia-converter, and hdpe-slurry-loop. Domain constraint: severity ceiling while r_T > 18 K with tube-outlet T still inside the healthy band. Sensor delta: +COT mean TT, +steam/HC ratio, +TLE tube-outlet TT, +mixed-header residual, -any freeze-dryer / tin-bath / cold-box / coater / potline / PEM stack / hub encoder / insole GRF / VIM pyrometer / reformer TMT / kiln zirconia / smelt IR / autoclave ply-TC / ORC shell-pressure / mold-platen TC / cell-pH / drum wet-foam / MCHE cold-end / Claus tail-CEMS / stockline radar / converter NH3 GC / loop density",
                "cycle1_tail": "cracked TLE inlet bypass + mixed-header certificate (sensor-topology / wrong-volume class): furnace-gantry visual PASSES while the mixed header sits on the far side of the bypass tee and the coked cone is already growing. Fitted base rate 0.38%/cycle from a bypass-growth MC (designed visual threshold, fitted tee leakage). Naive failure = FALSE PERMISSION (severity raise on three tube-side non-trips).",
                "cycle2_domain_subvariant": "millisecond-furnace / small TLE volume (physical-constraints clause): 0.30x TLE volume, 3.1x steam-bump gain; 5.6 s / +0.04 two-shell pulse over-moves a HEALTHY millisecond TLE to 9 K, so the probe must move to 18 s / +0.012",
                "cycle2_tail": "night-shift forged TLE-tube CSV (human-intent deception, disjoint class): shift lead posts a historian export showing tube-outlet = 348.0 C at t=1.1 h to clear a conversion catchup slot. Plant historian is 0.1 K (10 bins vs the 1.0 K screenshot). Rejected on quantization fingerprint plus live r_T 48 K and mixed 396 C at the claimed TLE-true. Base rate ~0.32% of Sunday-night cycles, DESIGNED and flagged.",
            },
            "densification_delta_cycle2": "+1 physical-constraint sub-variant (millisecond-TLE probe refit), +1 tail (night-shift TLE-tube forgery), +10 primary spikes (16 -> 26) + an 8-event contrast train with its own 190 us race, +2 ticks (5 -> 7), +2 delayed side-effects (+4.2 h suction-screen trip as PRIMARY terminal, +21 d CR-E-4507), +1 triple-edge scar with pair-rollback-fails arithmetic, +1 HITL 7.8 min ratification, + TLE-cone coke as the honest negative-result mechanism",
            "gaps_targeted": [
                "NOTES-r04 gap 5 / r14 residual: primary episode is a correctly-gated intervention that nonetheless FAILS (island quarantined; total -0.17; compressor trip avoided is booked separately from the delayed screen trip)",
                "NOTES-r14 item 4: LEARNING-ON-LEARNING DEPTH — three go-edges; rollback of any pair is fitted to fail; coordinated depression of all three exhibited with eligibility arithmetic",
                "NOTES-r04 gap 4 (partial): human ratification of the bypass interlock, 7.8 min fitted, without switching sim_or_real to hil (plant remains designed)",
                "NOTES-r42 domain candidates: not blast-furnace-burden-descent (r42), not claus-sulfur-recovery (r40), not ammonia-converter (r41/r44 in-flight), not hdpe-slurry-loop (r43 in-flight), not delayed-coker, not lng-mche, not steam-methane-reformer TMT; ethylene-steam-cracker coil/TLE is unused. FCC-riser, autonomous-driving, grid-inspection left unused.",
            ],
            "race_flip_narrative": "tle.mix.high @ 6.504 ms vs tle.tube.in_band @ 6.692 ms (188 us) inside race_window_us 500. Gap < min(500, 500) us so a sub-flip-bound perturbation reverses which alarm heads the PB-EC-7 queue. The gate excludes the winner tag and rides r_T > 18 K and missing steam > 0.8 t/h — order-invariant floors. Extends the flip-fragility series from arbitration/causation/attribution/initiation/consensus/permission/kinematic-certificate/tendon-nullspace/meniscus-certificate/ghost-contact/crucible-weep/TMT-spatial-mean/burning-zone-certificate/membrane-integrity/drum-switch/MCHE-cold-end/Claus-bypass/descent-true to TLE-DUTY CERTIFICATE: when three tube-side channels agree, their race does not decide truth; a mixed-header tap that policy treated as condensate-quality-only does.",
            "tags": [
                "ethylene-steam-cracker-coil",
                "tle-inlet-bypass",
                "mixed-header-certificate",
                "mixed-residual-discriminant",
                "steam-ratio-probe",
                "triple-edge-scar",
                "pair-rollback-fails",
                "coordinated-depression",
                "correct-modify-cell-still-fails",
                "tle-cone-coke",
                "human-ratify-bypass-loto",
                "millisecond-tle-probe-refit",
                "night-shift-forgery",
                "same-gate-opposite-disposition-contrast",
                "industrial-process",
                "research-only",
            ],
            "snn_tags": ["race", "refractory", "adaptation", "third-factor", "multi-edge-eligibility"],
            "distillation_value": "A TLE-bundle mixed-header certificate is three correct loops looking at a cool tube bundle that is not the mixed process gas. Distill (1) a mixed-header tap that policy had treated as condensate-quality-only, (2) a reversible probe that moves mixed T only if the bypass is open, (3) coordinated depression of every tube-healthy-go edge because rolling back any pair leaves the third above threshold, and (4) a critic head that can book a process-correct gate against a later unmonitored world loss without netting them.",
            "rights": dict(RIGHTS),
            "batch_position": 1,
        },
    }
    return rec, dict(trace=trace, eta1=eta1, eta2=eta2, eta3=eta3, dw1=dw1, dw2=dw2, dw3=dw3, w1=w1, w2=w2, w3=w3)
