#!/usr/bin/env python3
"""Clone MAOS r54 builder and retarget to r58 alkaline-water-electrolysis."""
from pathlib import Path

SRC = Path("/tmp/maos-r54/build_r54.py")
DST = Path("/tmp/maos-r58/build_r58.py")

text = SRC.read_text()

# --- identity (do NOT globally replace '54': spike amplitude 0.54) ---
id_pairs = [
    ("Build and self-check MAOS round-54", "Build and self-check MAOS round-58"),
    ("GEN_AT = \"2026-09-03T08:54:00Z\"", "GEN_AT = \"2026-09-03T09:58:00Z\""),
    ('OUT = Path("/tmp/maos-r54")', 'OUT = Path("/tmp/maos-r58")'),
    ('RECORD_ID = "maos-r54-001"', 'RECORD_ID = "maos-r58-001"'),
    ("ROUND = 54", "ROUND = 58"),
    ('NOVEL_LINE = "Novel coverage: 46%"', 'NOVEL_LINE = "Novel coverage: 45%"'),
    ("maos-r54-001", "maos-r58-001"),
    ("maos-r54", "maos-r58"),
    ("batch-r54", "batch-r58"),
    ("NOTES-r54", "NOTES-r58"),
    ("swarm-transcript-r54", "swarm-transcript-r58"),
    ("build_r54", "build_r58"),
    ("Round 54 transcript", "Round 58 transcript"),
    ("ROUND 54", "ROUND 58"),
    ("round 54", "round 58"),
    ("CR-B-5406", "CR-B-5806"),
    ("What ROUND 55 should add", "What ROUND 59 should add"),
    ("staged r14–r53", "staged r14–r57"),
    ("staged r14-r53", "staged r14-r57"),
    ("staged r14–r51", "staged r14-r57"),
    ("staged r14-r51", "staged r14-r57"),
    ("r14-r51", "r14-r57"),
    ("1753510680000054", "1755325080000058"),
    ("2026-08-09T01:42:00-05:00", "2026-08-16T02:18:00-05:00"),
]
for a, b in id_pairs:
    text = text.replace(a, b)

# --- plant / geo / cell ---
plant_pairs = [
    ("GIBBSQUERN", "KALYFELL"),
    ("Laterifen", "Potashfen"),
    ("PB-DG-7", "PB-AE-6"),
    ("TG-DG-7", "TG-AE-6"),
    ("DG-7C", "AE-6C"),
    ("DG-8", "AE-8"),
    ("DG-7", "AE-6"),
    ('PLANT = "KALYFELL"', 'PLANT = "KALYFELL"'),
    ('GEO = "Potashfen"', 'GEO = "Potashfen"'),
    ('CELL = "AE-6"', 'CELL = "AE-6"'),
    ('CELL = "DG-7"', 'CELL = "AE-6"'),
]
for a, b in plant_pairs:
    text = text.replace(a, b)

# constants block in case CELL line still old form after DG-7 replace
text = text.replace('CELL = "AE-6"', 'CELL = "AE-6"')

# --- domain ---
text = text.replace("gibbsite-autoclave-digestion", "alkaline-water-electrolysis")
text = text.replace('DOMAIN = "alkaline-water-electrolysis"', 'DOMAIN = "alkaline-water-electrolysis"')

# scenario letter ZB -> ZD (word-ish)
text = text.replace("scenario (ZB)", "scenario (ZD)")
text = text.replace("Scenario ZB", "Scenario ZD")
text = text.replace("ZB -- ", "ZD -- ")
text = text.replace("ZB — ", "ZD — ")

# --- physics phrases, longest first ---
phys = [
    ("FLASH-TRAIN CERTIFICATE OF A LIVE-STEAM DIGESTER",
     "LYE-LOOP CERTIFICATE OF A CELL-TRUE ELECTROLYZER"),
    ("flash-train certificate of a live-steam digester",
     "lye-loop certificate of a cell-true electrolyzer"),
    ("SHELL-TRUE CERTIFICATE", "CELL-TRUE CERTIFICATE"),
    ("shell-true certificate", "cell-true certificate"),
    ("Bayer live-steam autoclave digestion train",
     "atmospheric alkaline water electrolyzer hall"),
    ("6-vessel live-steam Bayer autoclave",
     "6-stack atmospheric alkaline water electrolyzer"),
    ("6-vessel live-steam Bayer autoclave train",
     "6-stack atmospheric alkaline water electrolyzer hall"),
    ("live-steam Bayer autoclave train",
     "atmospheric alkaline water electrolyzer hall"),
    ("live-steam Bayer autoclave",
     "atmospheric alkaline water electrolyzer"),
    ("Bayer live-steam autoclave",
     "atmospheric alkaline water electrolyzer"),
    ("Bayer alumina digestion / live-steam autoclave",
     "alkaline water electrolysis / atmospheric KOH hall"),
    ("Bayer alumina digestion", "alkaline water electrolysis"),
    ("Bayer alumina", "alkaline water electrolysis"),
    ("industrial-process / Bayer alumina",
     "industrial-process / alkaline water electrolysis"),
    ("not a petroleum delayed-coker",
     "not a PEM stack and not a chlor-alkali membrane cell"),
    ("this is a Bayer live-steam autoclave, not a petroleum delayed-coker",
     "this is an atmospheric KOH water electrolyzer, not a PEM stack and not a chlor-alkali membrane cell"),
    ("live-steam autoclave cycle", "80% load hold"),
    ("live-steam autoclave", "alkaline electrolyzer"),
    ("live-steam digestion", "lye-loop electrolysis"),
    ("live-steam bypass", "O2-into-H2 bypass"),
    ("live-steam dump", "header-detonation path"),
    ("live-steam nozzle", "H2 offtake"),
    ("live-steam thinning", "diaphragm-tear mixing"),
    ("unmonitored live-steam", "unmonitored O2-into-H2"),
    ("live-steam", "lye-loop"),
    ("flash-train mean temperature", "lye-loop density"),
    ("flash-train mean T", "lye-loop density"),
    ("flash-train mean", "lye-loop mean"),
    ("flash-train header average", "lye-loop header average"),
    ("flash-train header", "lye-loop header"),
    ("flash-train flash mean T", "lye-loop Coriolis"),
    ("flash-train T", "lye-loop density"),
    ("flash-train heat", "lye-loop inventory"),
    ("flash-train", "lye-loop"),
    ("three-stage flash header", "common lye-loop header"),
    ("3-stage flash-train TC cluster", "common lye-loop Coriolis"),
    ("flash-tank inlet", "H2-separator inlet"),
    ("flash-tank slosh", "separator slosh"),
    ("flash-tank", "H2-separator"),
    ("flash-T-first", "volt-mean-first"),
    ("flash-T-in-band", "volt-in-band"),
    ("flash-T", "volt-mean"),
    ("Flash-T-first", "Volt-mean-first"),
    ("flash-true", "loop-true"),
    ("flash-side", "loop-side"),
    ("flash-mix-vulnerable", "header-mix-vulnerable"),
    ("flash-mix", "header-mix"),
    ("flash confirms", "loop confirms"),
    ("flash loops", "circulation loops"),
    ("flash average", "lye-loop average"),
    ("FLASH's", "LYE's"),
    ("FLASH ", "LYE "),
    ("FLASH,", "LYE,"),
    ("FLASH/", "LYE/"),
    ('"FLASH ', '"LYE '),
    ("vendor Flashholt", "vendor Lyewick"),
    ("overflow caustic titrator", "stack-mean voltmeter"),
    ("overflow caustic", "stack-mean voltage"),
    ("overflow Coriolis density", "H2-separator level"),
    ("overflow Coriolis", "H2-separator level transmitter"),
    ("overflow density", "separator level"),
    ("overflow-true", "separator-true"),
    ("overflow-density", "separator-level"),
    ("combined overflow", "common H2 separator"),
    ("vendor Caustwick", "vendor Voltholt"),
    ("vendor Densfen", "vendor Sepfen"),
    ("vendor Shellghyll", "vendor Cellghyll"),
    ("CAUST's", "VOLT's"),
    ("CAUST ", "VOLT "),
    ("CAUST,", "VOLT,"),
    ("CAUST/", "VOLT/"),
    ("DENS's", "SEP's"),
    ("DENS ", "SEP "),
    ("DENS,", "SEP,"),
    ("DENS/", "SEP/"),
    ("FLASH/CAUST/DENS", "LYE/VOLT/SEP"),
    ("shell-jacket delta T", "O2-in-H2 residual"),
    ("shell-jacket delta", "O2-in-H2"),
    ("shell-jacket dT", "O2-in-H2"),
    ("shell-jacket T", "cell-offtake O2"),
    ("shell-jacket tap", "cell-offtake tap"),
    ("shell-jacket", "cell-offtake"),
    ("Shell-delta-first", "O2-residual-first"),
    ("shell-delta-first", "o2-residual-first"),
    ("shell-delta-win", "o2-residual-win"),
    ("shell-delta", "o2-residual"),
    ("Shell-delta", "O2-residual"),
    ("shell-true", "cell-true"),
    ("SHELL-TRUE", "CELL-TRUE"),
    ("shell.delta.high", "cell.o2.high"),
    ("shell.dT", "cell.o2"),
    ("shell.score", "cell.score"),
    ("shell.spall", "cell.flash"),
    ("shell.clear", "cell.clear"),
    ("shell-skin IR", "cell-hall H2 IR"),
    ("shell scoring", "diaphragm scoring"),
    ("shell-scoring", "diaphragm-scoring"),
    ("scored shell", "scored diaphragm"),
    ("scored cladding", "scored diaphragm"),
    ("shell spall", "recombination flash"),
    ("shell-spall", "recombination-flash"),
    ("Shell spall", "Recombination flash"),
    ("shell-TC", "cell-O2"),
    ("jacket-nuisance", "offtake-nuisance"),
    ("noisy shell-TC after a blow-off trip",
     "noisy cell-O2 after a lye-pump trip"),
    ("noisy shell-TC", "noisy cell-O2"),
    ("Monel-clad shell spall", "AE-6C recombination flash"),
    ("monel-clad shell", "polysulfone diaphragm"),
    ("Monel-clad", "Diaphragm"),
    ("monel-clad", "diaphragm"),
    ("Monel-clad geometry", "diaphragm geometry"),
    ("blow-off overpressure", "header detonation"),
    ("blow-off-plug", "diaphragm-tear"),
    ("blow-off plug", "diaphragm tear"),
    ("Blow-off plug", "Diaphragm tear"),
    ("plugged blow-off", "torn diaphragm"),
    ("plugged vessel", "torn stack"),
    ("blow-off steam", "lye-carryover conductivity"),
    ("blow-off trip", "lye-pump trip"),
    ("open blow-off", "sealed diaphragm"),
    ("open-blow-off", "sealed-diaphragm"),
    ("blow-off", "offtake"),
    ("RAISE-CHARGE", "RAISE-LOAD"),
    ("raise-charge", "raise-load"),
    ("raise_charge", "raise_load"),
    ("Raise-charge", "Raise-load"),
    ("raise charge", "raise load"),
    ("RESIDENCE-HOLD", "LOAD-HOLD"),
    ("residence_hold", "load_hold"),
    ("residence-time floor", "load-level ceiling"),
    ("residence_min", "load_pct"),
    ("residence_hold_floor_min", "load_hold_floor_pct"),
    ("proposed_residence_min", "proposed_load_pct"),
    ("shorten residence", "raise load"),
    ("shortens residence", "raises load"),
    ("shorten night-shift residence", "raise night-shift load"),
    ("Hold digestion residence", "Hold electrolyzer load"),
    ("Hold 45 min", "Hold 80% load"),
    ("hold 45 min", "hold 80% load"),
    ("holds 45 min", "holds 80% load"),
    ("held 45 min", "held 80% load"),
    ("below 45 min", "above 80% load"),
    ("residence >= 45 min", "load <= 80%"),
    ("residence at 45 min", "load at 80%"),
    ("45 min residence", "80% load"),
    ("45 min through", "80% through"),
    ("a 45 min", "an 80% load"),
    ("14 min into a 45 min", "14 min into an 80%"),
    ("45 to 39 min", "80 to 92%"),
    ("45 -> 39 min", "80 -> 92%"),
    ("45->39 min", "80->92%"),
    ("45 -> 39", "80 -> 92"),
    ("to 39 min", "to 92%"),
    ("39 min residence", "92% load"),
    ("residence_min\": 39.0", "load_pct\": 92.0"),
    ("residence_min\": 45.0", "load_pct\": 80.0"),
    ("liquor-flow step probe", "lye-flow step probe"),
    ("liquor-flow step", "lye-flow step"),
    ("liquor-step probe", "lye-step probe"),
    ("LIQUOR-STEP-PROBE", "LYE-STEP-PROBE"),
    ("liquor-step", "lye-step"),
    ("liquor flow", "lye flow"),
    ("Liquor flow", "Lye flow"),
    ("liquor-flow", "lye-flow"),
    ("liquor.probe", "lye.probe"),
    ("liquor.demand", "load.demand"),
    ("standing liquor-step", "standing lye-step"),
    ("Gas-step gain", "Lye-step gain"),
    ("gas step", "lye-flow step"),
    ("2.4x liquor-step gain", "2.4x lye-step gain"),
    ("vessel-top visual", "cell-hall visual"),
    ("vessel-top climb", "cell-hall LOTO climb"),
    ("vessel-top work", "cell-hall LOTO work"),
    ("vessel-top", "cell-hall"),
    ("Vessel-top", "Cell-hall"),
    ("vessel interlock", "stack interlock"),
    ("VESSEL-AE-6C", "STACK-AE-6C"),
    ("VESSEL-DG-7C", "STACK-AE-6C"),
    ("vessel.hold", "stack.hold"),
    ("vessel AE-6C", "stack AE-6C"),
    ("Vessel AE-6C", "Stack AE-6C"),
    ("fault_vessel", "fault_stack"),
    ("fault_shell", "fault_cell"),
    ("vessel_count", "stack_count"),
    ("six 3.8 m vessels", "six 4.2 m stacks"),
    ("6 live-steam autoclave vessels", "6 atmospheric KOH stacks"),
    ("3.8 m ID x 18 m", "4.2 m stack x 180 cells"),
    ("Grade-B vessel-top LOTO", "Grade-B cell-hall LOTO"),
    ("flashing vessels", "healthy stacks"),
    ("five flashing", "five healthy"),
    ("6 vessels", "6 stacks"),
    ("6-vessel", "6-stack"),
    ("vessels", "stacks"),
    ("vessel", "stack"),
    ("Vessel", "Stack"),
    ("FLASH-TRAIN", "LYE-LOOP"),
    ("flash.in_band", "volt.in_band"),
    ("flash.hot", "lye.hot"),
    ("flash.healthy", "lye.healthy"),
    ("caust.ok", "volt.ok"),
    ("dens.ok.in_band", "sep.ok.in_band"),
    ("dens.ok", "sep.ok"),
    ("flash_in_band_pop", "volt_in_band_pop"),
    ("flash_healthy_pop", "lye_ok_pop"),
    ("caust_ok_pop", "volt_ok_pop"),
    ("dens_ok_pop", "sep_ok_pop"),
    ("raise_charge_pop", "raise_load_pop"),
    ("shell_dt_pop", "cell_o2_pop"),
    ("residence_hold_pop", "load_hold_pop"),
    ("high-gibbsite / short-residence", "high-pressure / thin-gap"),
    ("high-gibbsite", "high-pressure"),
    ("low-gibbsite", "atmospheric"),
    ("extraction-time", "gap-spacing"),
    ("hydrate-catchup window", "demand-catchup window"),
    ("hydrate-catchup slot", "demand-catchup slot"),
    ("hydrate-catchup", "demand-catchup"),
    ("hydrate is one quality unit", "hydrogen ticket is one quality unit"),
    ("night-shift hydrate", "night-shift hydrogen ticket"),
    ("night-shift train", "night-shift hall"),
    ("night-shift CSV", "night-shift O2 CSV"),
    ("forged wall-T CSV", "forged O2-in-H2 CSV"),
    ("wall-T CSV", "O2 CSV"),
    ("wall-T forgery", "O2-in-H2 forgery"),
    ("digestion supervisory optimizer DSO",
     "electrolyzer supervisory optimizer ESO"),
    ("Digestion DG-7", "Electrolysis AE-6"),
    ("Digestion, invented bauxite campus",
     "Electrolysis, invented KOH campus"),
    ("invented bauxite campus", "invented KOH campus"),
    ("true digestion-duty", "true sealed-stack duty"),
    ("digestion-duty", "sealed-stack duty"),
    ("digestion residence", "electrolyzer load"),
    ("Bayer charge-raises", "alkaline load-raises"),
    ("autoclave shell", "electrolyzer diaphragm"),
    ("autoclave", "electrolyzer"),
    ("digestion", "electrolysis"),
    ("Digestion", "Electrolysis"),
    ("gibbsite", "lye-inventory"),
    ("stamp battery", "high-pressure hall"),
    ("quarantined battery", "quarantined hall"),
    ("battery saved", "hall saved"),
    ("coke-oven wall physics", "alkaline diaphragm physics"),
    ("through-wall crack", "diaphragm tear"),
    ("wall crack", "diaphragm tear"),
    ("scale-plug MC", "diaphragm-tear MC"),
    ("scale-plug arrival", "diaphragm-tear arrival"),
    ("fitted monel-clad geometry", "fitted diaphragm geometry"),
    ("4.8 MPa", "1.05 bar"),
    ("45 min / 1.05 bar", "80% load / 1.05 bar"),
    ("45 min / 4.8 MPa", "80% load / 1.05 bar"),
    # numeric sensor remaps in prose
    ("148 C inside 140-160", "1.28 kg/L inside 1.24-1.32"),
    ("148 C (dead-band 140-160)", "1.28 kg/L (dead-band 1.24-1.32)"),
    ("148 C inside 140-160 C", "1.28 kg/L inside 1.24-1.32"),
    ("flash 148 C", "lye 1.28 kg/L"),
    ("148 C", "1.28 kg/L"),
    ("140-160 C", "1.24-1.32 kg/L"),
    ("140-160", "1.24-1.32"),
    ("168 g/L Na2O inside 155-180", "1.88 V inside 1.75-2.00"),
    ("168 g/L inside 155-180", "1.88 V inside 1.75-2.00"),
    ("168 g/L Na2O", "1.88 V"),
    ("168 g/L", "1.88 V"),
    ("155-180 g/L Na2O", "1.75-2.00 V"),
    ("155-180 g/L", "1.75-2.00 V"),
    ("155-180", "1.75-2.00"),
    ("1.32 kg/L inside 1.26-1.38", "52% inside 40-70"),
    ("1.32 kg/L (band 1.26-1.38)", "52% (band 40-70)"),
    ("1.32 kg/L", "52%"),
    ("1.26-1.38 kg/L", "40-70%"),
    ("1.26-1.38", "40-70"),
    ("delta 84 K", "O2-in-H2 0.84 vol%"),
    ("delta T 84 K", "O2-in-H2 0.84 vol%"),
    ("84 K (healthy < 18; hold if > 35)",
     "0.84 vol% (healthy < 0.15; hold if > 0.40)"),
    ("84 K (healthy < 18; policy floor 35 K",
     "0.84 vol% (healthy < 0.15; policy floor 0.40 vol%"),
    ("infers 84 K", "infers 0.84 vol%"),
    ("84 K", "0.84 vol%"),
    ("35 K AND", "0.40 vol% AND"),
    ("above 35 K", "above 0.40 vol%"),
    ("> 35 K", "> 0.40 vol%"),
    ("< 35 K", "< 0.40 vol%"),
    ("35 K trip", "0.40 vol% trip"),
    ("35 K dT", "0.40 vol% O2"),
    ("floor 35 K", "floor 0.40 vol%"),
    ("< 18 K", "< 0.15 vol%"),
    ("< 18;", "< 0.15;"),
    ("healthy < 18", "healthy < 0.15 vol%"),
    ("8.4 t/h (healthy < 1.2; hold if > 2.5)",
     "84 uS/cm (healthy < 18; hold if > 35)"),
    ("8.4 t/h (healthy < 1.2; hold floor 2.5",
     "84 uS/cm (healthy < 18; hold floor 35"),
    ("8.4 t/h", "84 uS/cm"),
    ("> 2.5 t/h", "> 35 uS/cm"),
    ("2.5 t/h", "35 uS/cm"),
    ("1.2 t/h", "18 uS/cm"),
    ("0.7 t/h", "9 uS/cm"),
    ("0.6 t/h", "8 uS/cm"),
    ("14 t/h steam", "1.8 vol% O2-in-H2"),
    ("14 t/h", "1.8 vol%"),
    ("steam on stack", "O2-in-H2 on stack"),
    ("|Delta flash-train T|", "|Delta header H2 purity|"),
    ("|Delta lye-loop density|", "|Delta header H2 purity|"),
    ("0.6 <= 0.8 K", "0.06 <= 0.08 pp"),
    ("<= 0.8 K", "<= 0.08 pp"),
    (">= 3.2 K", ">= 0.32 pp"),
    (">= 3.2", ">= 0.32"),
    ("3.6 K", "0.36 pp"),
    ("3.5 K", "0.35 pp"),
    ("3.2 K", "0.32 pp"),
    ("0.8 K", "0.08 pp"),
    ("0.6 K", "0.06 pp"),
    ("41 K false delta", "0.48 vol% false O2"),
    ("41 K", "0.48 vol%"),
    ("11 K delta", "0.11 vol%"),
    ("11 K", "0.11 vol%"),
    ("10 K", "0.10 vol%"),
    ("9 K", "0.08 vol%"),
    ("12 K at t=1.6 h", "0.12 vol% at t=1.6 h"),
    ("12 K at t = 1.6 h", "0.12 vol% at t = 1.6 h"),
    ("delta = 12 K", "O2 = 0.12 vol%"),
    ("delta 9 K", "O2-in-H2 0.08 vol%"),
    ("5 K quantization", "0.10 vol% quantization"),
    ("5 K screenshot", "0.10 vol% screenshot"),
    ("5 K (SCADA", "0.10 vol% (SCADA"),
    ("0.5 K native", "0.01 vol% native"),
    ("0.5 K (10 bins)", "0.01 vol% (10 bins)"),
    ("0.5 K CSV", "0.01 vol% CSV"),
    ("historian is 0.5 K", "historian is 0.01 vol%"),
    ("10 bins vs the 5 K", "10 bins vs the 0.10 vol%"),
    ("10 bins off plant truth", "10 bins off plant truth"),
    ("native 0.5 K", "native 0.01 vol%"),
    ("quantized at 5 K", "quantized at 0.10 vol%"),
    ("bulk density 1.12 t/m3 vs 0.78", "gap 0.42x vs atmospheric 1.0x"),
    ("Bulk density 1.12 vs 0.78 t/m3", "Gap 0.42x vs atmospheric 1.0x"),
    ("1.12 t/m3 vs 0.78", "0.42x gap vs atmospheric"),
    ("crack band", "tear band"),
    ("Crack band", "Tear band"),
    ("crack keeps", "tear keeps"),
    ("a crack", "a tear"),
    ("the crack", "the tear"),
    ("Crack found", "Tear found"),
    ("crack found", "tear found"),
    ("no crack", "no tear"),
    ("into a cracked", "into a torn"),
    ("thinned the AE-6C wall", "mixed H2/O2 in the AE-6C offtake pocket"),
    ("thinned the shell", "mixed H2/O2 in the offtake pocket"),
    ("thinned AE-6C", "contaminated AE-6C"),
    ("thinned wall", "contaminated offtake"),
    ("Wall-thinning model", "Mixing-pocket model"),
    ("shell recovery", "header recovery"),
    ("remaining train recovered", "remaining hall recovered"),
    ("train still failed", "hall still failed"),
    ("train still fails", "hall still fails"),
    ("train still collapsed", "hall still collapsed"),
    ("train quarantined", "hall quarantined"),
    ("the train still", "the hall still"),
    ("night-shift train", "night-shift hall"),
    ("sister train", "sister hall"),
    ("sister-battery", "sister-hall"),
    ("the train is", "the hall is"),
    ("on 2 trains/yr", "on 2 halls/yr"),
    ("6-stack trains that share", "6-stack halls that share"),
    ("train-bus", "hall-bus"),
    ("train bus", "hall bus"),
    ("Train AE-6", "Hall AE-6"),
    ("train AE-6", "hall AE-6"),
    ("the train ", "the hall "),
    ("train recovered", "hall recovered"),
    ("quarantined; total", "quarantined; total"),
    ("correctly-gated intervention that nonetheless FAILS (train",
     "correctly-gated intervention that nonetheless FAILS (hall"),
    ("populations flash 0-39, shell 40-79, dens 80-119, gate 120-159",
     "populations lye 0-39, cell-O2 40-79, sep 80-119, gate 120-159"),
    ("modify_hold integrates cell-offtake dT + offtake steam against playbook drive; accept_raise",
     "modify_hold integrates O2-in-H2 + lye-carryover against playbook drive; accept_raise"),
    ("accept_raise and reject_abort", "accept_raise and reject_abort"),
    ("do not raise-load", "do not raise-load"),
    ("never raise-load", "never raise-load"),
    ("confined-space cell-hall work", "cell-hall LOTO work"),
    ("fitted 11.4 min dead-man", "fitted 11.4 min dead-man"),
    ("may not break the stack interlock", "may not break the stack interlock"),
    ("Cross-wall IR survey", "Cell-hall H2 IR survey"),
    ("wall-T", "O2-in-H2"),
    ("Wall-T", "O2-in-H2"),
    ("far-side cladding", "offtake pocket"),
    ("far side", "offtake side"),
    ("cladding opens", "pocket ignites"),
    ("cladding", "diaphragm"),
    ("2015 'noisy cell-O2 after a offtake trip'",
     "2015 'noisy cell-O2 after a lye-pump trip'"),
    ("2015 'noisy cell-O2 after a lye-pump trip'",
     "2015 'noisy cell-O2 after a lye-pump trip'"),
    ("one of 6", "one of 6"),
    ("plug residual", "tear residual"),
    ("the plug sits", "the tear sits"),
    ("plugged stack", "torn stack"),
    ("already plugged", "already torn"),
    ("a plug", "a tear"),
    ("the plug", "the tear"),
    ("scale-plug", "diaphragm-tear"),
    ("BLOW-OFF PLUG", "DIAPHRAGM TEAR"),
    ("blow-off-plug pass rate", "diaphragm-tear pass rate"),
    ("silent shell-scoring load", "silent offtake-mixing load"),
    ("hardware-in-loop stack interlock", "hardware-in-loop stack interlock"),
    ("AVOID alkaline-water-electrolysis (now used)",
     "AVOID alkaline-water-electrolysis (now used)"),
    ("hot-strip-mill.", "hot-strip-mill (r55/r56); paper-machine-dryer (r57); urea-prill (r56 builder); sinter-strand (r61)."),
    ("and carbon-fiber-oxidation-oven. Domain constraint:",
     "carbon-fiber-oxidation-oven, seawater-RO, nitric-ostwald, Bayer digestion, hot-strip-mill, paper-machine-dryer, urea-prill, and sinter-strand. Domain constraint:"),
    ("Domain constraint: load-level ceiling while O2-in-H2 residual > 0.40 vol% with lye-loop mean still inside the healthy band.",
     "Domain constraint: load-level ceiling while O2-in-H2 residual > 0.40 vol% with lye-loop mean still inside the healthy band."),
    ("Sensor delta: +lye-loop density, +stack-mean voltage, +separator level, +O2-in-H2, +lye-carryover conductivity",
     "Sensor delta: +lye-loop density, +stack-mean voltage, +H2-separator level, +cell-offtake O2-in-H2, +lye-carryover conductivity"),
    ("-any freeze-dryer", "-any PEM dew-point / Nafion MEA / chlor-alkali anolyte-pH / freeze-dryer"),
    ("not fcc-regenerator-cyclone-dipleg (r47), not fcc-riser-regenerator (r46), not sulfuric-contact-converter (r48), not eaf-foamy-slag-water-panel (r49), not glass-container-is-machine (r51), not coke-oven-battery-heating (r52), not carbon-fiber-oxidation-oven (r53 in-flight), not delayed-coker-drum-switch (r38), not blast-furnace-burden-descent (r42); alkaline-water-electrolysis is unused. autonomous-driving, grid-inspection left unused.",
     "not pem-water-electrolysis (r24), not chlor-alkali-membrane-electrolysis (r37), not coke-oven-battery-heating (r52), not carbon-fiber-oxidation-oven (r53), not gibbsite-autoclave-digestion (r54), not hot-strip-mill-finishing (r55/r56), not paper-machine-dryer-section (r57), not urea-prilling-tower (r56 builder), not sinter-strand-windbox (r61); alkaline-water-electrolysis is unused. autonomous-driving, grid-inspection, bioreactor-perfusion left unused."),
    ("not glass IS-machine (r51). autonomous-driving",
     "not glass IS-machine (r51), not Bayer digestion (r54), not hot-strip mill (r55/r56), not paper dryer (r57). autonomous-driving"),
    ("One 20 ms train-bus epoch", "one 20 ms hall-bus epoch"),
    ("one 20 ms train-bus epoch", "one 20 ms hall-bus epoch"),
    ("one 20 ms hall-bus epoch", "one 20 ms hall-bus epoch"),
    ("20 Hz 12-bit on the common lye-loop Coriolis",
     "50 Hz Coriolis on the common 30 wt% KOH loop"),
    ("50 Hz on the overflow caustic titrator",
     "20 Hz 12-bit on the 6-stack mean voltage"),
    ("50 Hz on the stack-mean voltmeter",
     "20 Hz 12-bit on the 6-stack mean voltage"),
    ("50 Hz on the H2-separator level transmitter",
     "20 Hz on the common H2-separator level"),
    ("commissioned as a jacket-nuisance tag, not as a shell-integrity tag",
     "commissioned as an offtake-nuisance tag, not as a cell-purity tag"),
    ("commissioned as a offtake-nuisance tag, not as a shell-integrity tag",
     "commissioned as an offtake-nuisance tag, not as a cell-purity tag"),
    ("commissioned as an offtake-nuisance tag, not as a shell-integrity tag",
     "commissioned as an offtake-nuisance tag, not as a cell-purity tag"),
    ("not as a shell-integrity tag", "not as a cell-purity tag"),
    ("All three playbook confirms live on the WRONG volume.",
     "All three playbook confirms live on the WRONG volume."),
    ("LYE is correct that lye-loop mean T sits at 1.28 kg/L",
     "LYE is correct that lye-loop density sits at 1.28 kg/L"),
    ("LYE is correct that lye-loop density sits at 1.28 kg/L (five healthy stacks dominate the three-stage lye-loop header).",
     "LYE is correct that lye-loop density sits at 1.28 kg/L (five healthy stacks dominate the common KOH header)."),
    ("VOLT is correct that stack-mean voltage is 1.88 V (the common H2 separator still sees five healthy stacks).",
     "VOLT is correct that stack-mean voltage is 1.88 V (the torn stack is one of six on the mean)."),
    ("SEP is correct that the separator level is 52% (the torn stack is one of 6).",
     "SEP is correct that the common H2-separator level is 52% (the torn stack is one of 6)."),
    ("the lye-loop average is looking at lye-loop inventory, not at stack AE-6C's torn diaphragm.",
     "the lye-loop average is looking at common-loop inventory, not at stack AE-6C's torn diaphragm."),
    ("Playbook PB-AE-6 treats the conjunction as permission to raise load.",
     "Playbook PB-AE-6 treats the conjunction as permission to raise load."),
    ("No agent is faulty; the lye-loop average is looking at lye-loop inventory, not at stack AE-6C's torn diaphragm.",
     "No agent is faulty; the loop average is looking at common-header inventory, not at stack AE-6C's torn diaphragm."),
    ("shell-integrity", "cell-purity"),
    ("flash-true loops", "loop-true confirms"),
    ("three flash-side channels", "three loop-side channels"),
    ("three flash-healthy-go", "three loop-healthy-go"),
    ("flash-healthy-go", "loop-healthy-go"),
    ("ACh at o2-residual-win tags volt.in_band->push, volt.ok->push, and sep.ok.in_band->push",
     "ACh at o2-residual-win tags lye.hot/volt.in_band->push, volt.ok->push, and sep.ok.in_band->push"),
    ("negative credit at probe-fail (diaphragm tear confirmed, +0.80 s) depresses ALL THREE",
     "negative credit at probe-fail (diaphragm tear confirmed, +0.80 s) depresses ALL THREE"),
    ("do not shorten load below 80% load", "do not raise load above 80%"),
    ("Do not shorten load below 80% load AND do not raise lye flow while",
     "Do not raise load above 80% AND do not raise lye flow while"),
    ("do not shorten load below 80% load while",
     "do not raise load above 80% while"),
    ("Do not raise load above 80% load", "Do not raise load above 80%"),
    ("strip the raise-load, hold 80% load load",
     "strip the raise-load, hold 80% load"),
    ("hold 80% load load", "hold 80% load"),
    ("80% load load", "80% load"),
    ("80 pct", "80%"),
    ("92 pct", "92%"),
    ("load_pct\": 39.0", "load_pct\": 92.0"),
    ("\"load_pct\": 45.0", "\"load_pct\": 80.0"),
    ("proposed_load_pct\": 39.0", "proposed_load_pct\": 92.0"),
    ("\"floor\": 45.0, \"proposed_target\": 39.0",
     "\"floor\": 80.0, \"proposed_target\": 92.0"),
    ("\"observed\": 45.0, \"floor\": 80.0",
     "\"observed\": 80.0, \"floor\": 80.0"),
    ("raise_load, submitted", "raise_load, submitted"),
    ("80% load, lye flow +8%", "80 -> 92%, lye flow +8%"),
    ("RAISE-LOAD: 80 -> 92%, lye flow +8%, no lye-step probe, no stack AE-6C hold",
     "RAISE-LOAD: 80 -> 92%, lye flow +8%, no lye-step probe, no stack AE-6C hold"),
    ("shorten night-shift load to clear a demand-catchup window",
     "raise night-shift load to clear a demand-catchup window"),
    ("Treat three in-spec loops as a healthy cell-true hall and raise night-shift load to clear a demand-catchup window.",
     "Treat three in-spec loops as a healthy cell-true hall and raise night-shift load to clear a demand-catchup window."),
    ("assert lye-loop density 1.28 kg/L inside 1.24-1.32",
     "assert lye-loop density 1.28 kg/L inside 1.24-1.32"),
    ("assert stack-mean voltage 1.88 V inside 1.75-2.00",
     "assert stack-mean voltage 1.88 V inside 1.75-2.00"),
    ("assert separator level 52% inside 40-70",
     "assert H2-separator level 52% inside 40-70"),
    ("shorten load 80 to 92% and raise lye flow +8% over 8 min",
     "raise load 80 to 92% and raise lye flow +8% over 8 min"),
    ("hold cell-offtake T unread as a cell-purity tag",
     "hold cell-offtake O2 unread as a cell-purity tag"),
    ("observable\": \"O2-in-H2 residual stack AE-6C\"",
     "observable\": \"O2-in-H2 residual stack AE-6C\""),
    ("observable\": \"cell-offtake delta T stack AE-6C\"",
     "observable\": \"O2-in-H2 residual stack AE-6C\""),
    ("\"unit\": \"K\"", "\"unit\": \"vol%\""),
    ("\"value\": 84,", "\"value\": 0.84,"),
    ("\"value\": 8.4,", "\"value\": 84.0,"),
    ("\"value\": 148,", "\"value\": 1.28,"),
    ("\"value\": 168.0,", "\"value\": 1.88,"),
    ("\"value\": 1.32,", "\"value\": 52.0,"),
    ("\"unit\": \"C\"", "\"unit\": \"kg/L\""),
    ("\"unit\": \"g/L\"", "\"unit\": \"V\""),
    ("\"unit\": \"kg/L\"", "\"unit\": \"kg/L\""),
    ("\"unit\": \"t/h\"", "\"unit\": \"uS/cm\""),
    ("source\": \"LYE 12-bit\"", "source\": \"LYE Coriolis\""),
    ("source\": \"VOLT overflow titrator\"", "source\": \"VOLT 6-stack mean\""),
    ("source\": \"SEP overflow Coriolis\"", "source\": \"SEP H2-separator level\""),
    ("source\": \"SHELL dT vs lye-loop mean\"", "source\": \"CELL O2-in-H2 vs stack-mean V\""),
    ("source\": \"SHELL offtake meter\"", "source\": \"CELL lye-carryover conductivity\""),
    ("source\": \"CELL dT vs lye-loop mean\"", "source\": \"CELL O2-in-H2 vs stack-mean V\""),
    ("healthy-load band 1.24-1.32 kg/L; five healthy stacks still dominate the lye-loop header average",
     "healthy-load band 1.24-1.32 kg/L; five healthy stacks still dominate the common KOH header"),
    ("band 1.75-2.00 V; separator-true, cell-false",
     "band 1.75-2.00 V; mean-true, torn-stack-false"),
    ("band 40-70%; separator-true, plugged-stack-false",
     "band 40-70%; separator-true, torn-stack-false"),
    ("lives on the torn AE-6C offtake, not the lye-loop header",
     "lives on the torn AE-6C H2 offtake, not the common separator"),
    ("policy floor 0.40 vol% is not armed unless lye-loop mean also trips",
     "policy floor 0.40 vol% is not armed unless stack-mean V also trips"),
    ("\"flash_t_C\": 148,", "\"lye_kgL\": 1.28,"),
    ("\"flash_t_deadband_C\": [140, 160],", "\"lye_band_kgL\": [1.24, 1.32],"),
    ("\"caust_gL\": 168.0,", "\"volt_V\": 1.88,"),
    ("\"caust_band_gL\": [155.0, 180.0],", "\"volt_band_V\": [1.75, 2.00],"),
    ("\"dens_kgL\": 1.32,", "\"sep_pct\": 52.0,"),
    ("\"dens_band_kgL\": [1.26, 1.38],", "\"sep_band_pct\": [40.0, 70.0],"),
    ("\"wall_dT_K\": 84,", "\"o2_in_h2_volpct\": 0.84,"),
    ("\"wall_dT_hold_K\": 35,", "\"o2_hold_volpct\": 0.40,"),
    ("\"wall_dT_healthy_K\": 18,", "\"o2_healthy_volpct\": 0.15,"),
    ("\"blowoff_tph\": 8.4,", "\"carryover_uScm\": 84.0,"),
    ("\"blowoff_hold_tph\": 2.5,", "\"carryover_hold_uScm\": 35.0,"),
    ("\"blowoff_healthy_tph\": 1.2,", "\"carryover_healthy_uScm\": 18.0,"),
    ("\"blowoff_trip_tph\": 12.0,", "\"o2_trip_volpct\": 1.20,"),
    ("\"blowoff_now_tph\": 8.4,", "\"carryover_now_uScm\": 84.0,"),
    ("\"wall_dT_K\": {\"observed\": 84, \"hold_if_above\": 35},",
     "\"o2_in_h2_volpct\": {\"observed\": 0.84, \"hold_if_above\": 0.40},"),
    ("\"flash_t_C\": {\"observed\": 148, \"band\": [140, 160]},",
     "\"lye_kgL\": {\"observed\": 1.28, \"band\": [1.24, 1.32]},"),
    ("\"blowoff_tph\": {\"observed\": 8.4, \"hold_if_above\": 2.5},",
     "\"carryover_uScm\": {\"observed\": 84.0, \"hold_if_above\": 35.0},"),
    ("\"load_pct\": {\"observed\": 45.0, \"floor\": 80.0, \"proposed_target\": 92.0}",
     "\"load_pct\": {\"observed\": 80.0, \"floor\": 80.0, \"proposed_target\": 92.0}"),
    ("\"load_pct\": {\"observed\": 80.0, \"floor\": 80.0, \"proposed_target\": 92.0}",
     "\"load_pct\": {\"observed\": 80.0, \"floor\": 80.0, \"proposed_target\": 92.0}"),
    ("failure_class\": \"LYE-LOOP CERTIFICATE",
     "failure_class\": \"LYE-LOOP CERTIFICATE"),
    ("a torn diaphragm on stack AE-6C partitions cell-true O2-in-H2 residual and lye-carryover conductivity from lye-loop mean, stack-mean voltage, and separator level",
     "a torn diaphragm on stack AE-6C partitions cell-true O2-in-H2 and lye-carryover from lye-loop density, stack-mean voltage, and H2-separator level"),
    ("igniter\": \"stack AE-6C offtake plug after 19 min of unmonitored O2-into-H2 into the torn diaphragm",
     "igniter\": \"stack AE-6C diaphragm tear after 19 min of unmonitored O2-into-H2 bypass into the H2 offtake"),
    ("igniter\": \"stack AE-6C diaphragm tear after 19 min of unmonitored O2-into-H2 bypass into the plugged offtake",
     "igniter\": \"stack AE-6C diaphragm tear after 19 min of unmonitored O2-into-H2 bypass into the H2 offtake"),
    ("naive_failure\": \"PB-AE-6 RAISE-LOAD on three healthy loops: 80 to 92% into a demand-catchup window with stack AE-6C already torn, header detonation at 1.8 vol% O2-in-H2, $4.6M plus a 56-hour unplanned stop\"",
     "naive_failure\": \"PB-AE-6 RAISE-LOAD on three healthy loops: 80 to 92% into a demand-catchup window with stack AE-6C already torn, header detonation at 1.8 vol% O2-in-H2, $4.6M plus a 56-hour unplanned stop\""),
    ("auto-drafts RAISE-LOAD whenever lye-loop density is inside 1.24-1.32 kg/L AND stack-mean voltage inside 1.75-2.00 V AND separator level inside 40-70%, ignoring the cell-offtake tap unless lye-loop mean also trips",
     "auto-drafts RAISE-LOAD whenever lye-loop density is inside 1.24-1.32 kg/L AND stack-mean voltage inside 1.75-2.00 V AND H2-separator level inside 40-70%, ignoring the cell-offtake O2 tap unless stack-mean V also trips"),
    ("Independence of 'lye-loop mean in band, therefore every offtake is open' is the hidden assumption, and it is false across a diaphragm-tear-plus-header-mix path.",
     "Independence of 'lye-loop mean in band, therefore every diaphragm is sealed' is the hidden assumption, and it is false across a diaphragm-tear-plus-header-mix path."),
    ("Discriminate offtake plug vs true electrolysis-duty",
     "Discriminate diaphragm tear vs true sealed-stack duty"),
    ("reversible lye-flow step probe before any raise-load",
     "reversible lye-flow step probe before any raise-load"),
    ("\"name\": \"raise_load\"", "\"name\": \"raise_load\""),
    ("\"name\": \"load_hold_lye_step_probe_isolate\"",
     "\"name\": \"load_hold_lye_step_probe_isolate\""),
    ("LOAD-HOLD + LYE-STEP-PROBE + STACK-AE-6C-HOLD",
     "LOAD-HOLD + LYE-STEP-PROBE + STACK-AE-6C-HOLD"),
    ("LOAD-HOLD + LYE-STEP-PROBE + VESSEL-AE-6C hold",
     "LOAD-HOLD + LYE-STEP-PROBE + STACK-AE-6C hold"),
    ("LOAD-HOLD + LYE-STEP-PROBE + STACK-AE-6C hold",
     "LOAD-HOLD + LYE-STEP-PROBE + STACK-AE-6C hold"),
    ("Volt-mean-first latches RAISE-LOAD (80 to 92%, lye flow +8%, no isolate).",
     "Volt-mean-first latches RAISE-LOAD (80 to 92%, lye flow +8%, no isolate)."),
    ("O2-residual-first latches LOAD-HOLD + LYE-STEP-PROBE + STACK-AE-6C hold.",
     "O2-residual-first latches LOAD-HOLD + LYE-STEP-PROBE + STACK-AE-6C hold."),
    ("contenders", "contenders"),
    ("cell.o2.high 0.84 vol% (stack AE-6C cell-offtake vs lye-loop mean)",
     "cell.o2.high 0.84 vol% (stack AE-6C H2 offtake vs stack-mean V)"),
    ("volt.in_band 1.28 kg/L (lye-loop lye-loop mean T)",
     "volt.in_band 1.88 V (6-stack mean voltage)"),
    ("window_derivation\": \"500 us = one 365 us shell-dT ADC slot plus 135 us flash-T publish.\"",
     "window_derivation\": \"500 us = one 365 us cell-O2 ADC slot plus 135 us stack-mean-V publish.\""),
    ("window_derivation\": \"500 us = one 365 us cell-o2 ADC slot plus 135 us volt-mean publish.\"",
     "window_derivation\": \"500 us = one 365 us cell-O2 ADC slot plus 135 us stack-mean-V publish.\""),
    ("one 365 us o2-residual ADC slot plus 135 us volt-mean publish",
     "one 365 us cell-O2 ADC slot plus 135 us stack-mean-V publish"),
    ("combined jitter 58 us (shell 34 + flash 24)",
     "combined jitter 58 us (cell-O2 34 + volt-mean 24)"),
    ("combined jitter 58 us (cell-o2 34 + volt-mean 24)",
     "combined jitter 58 us (cell-O2 34 + volt-mean 24)"),
    ("rides the order-invariant floors o2-residual T > 0.40 vol% and lye-carryover conductivity > 35 uS/cm, not the alarm order",
     "rides the order-invariant floors O2-in-H2 > 0.40 vol% and lye-carryover > 35 uS/cm, not the alarm order"),
    ("o2-residual T > 0.40 vol%", "O2-in-H2 > 0.40 vol%"),
    ("\"heating_flue\":", "\"offtake\":"),
    ("\"wall\":", "\"cell\":"),
    ("\"load\":", "\"load\":"),
    ("\"battery\":", "\"hall\":"),
    ("delta 0.84 vol% -> 83 K", "O2 0.84 -> 0.83 vol%"),
    ("0.84 vol% -> 83 K", "0.84 -> 0.83 vol%"),
    ("0.84 -> 83 K", "0.84 -> 0.83 vol%"),
    ("delta 0.84 vol% -> 0.83 vol%", "O2 0.84 -> 0.83 vol%"),
    ("recovered toward 0.11 vol% over 3.8 h",
     "recovered toward 0.11 vol% over 3.8 h"),
    ("recovered toward 11 K over 3.8 h",
     "recovered toward 0.11 vol% over 3.8 h"),
    ("true sealed diaphragm on the remaining hall: delta 0.11 vol%, lye-carryover conductivity 9 uS/cm, delta below 0.40 vol%",
     "true sealed diaphragm on the remaining hall: O2-in-H2 0.11 vol%, carryover 9 uS/cm, both below hold floors"),
    ("raise-load now legal on AE-8 only",
     "raise-load now legal on AE-8 only"),
    ("polysulfone diaphragm spall at stack AE-6C",
     "recombination flash at stack AE-6C"),
    ("diaphragm spall", "recombination flash"),
    ("from the pre-t0 offtake plug", "from the pre-t0 diaphragm tear"),
    ("from the pre-t0 diaphragm tear", "from the pre-t0 diaphragm tear"),
    ("t0-19 min: stack AE-6C offtake plug begins",
     "t0-19 min: stack AE-6C diaphragm tear begins"),
    ("o2-residual crosses 0.40 vol% up; O2-into-H2 bypass starts thinning the offtake pocket",
     "O2-in-H2 crosses 0.40 vol% up; O2-into-H2 bypass starts mixing the offtake pocket"),
    ("t0-8 min: o2-residual first crosses 0.40 vol%; PB-AE-6 ignores it because lye-loop mean is 1331 C",
     "t0-8 min: O2-in-H2 first crosses 0.40 vol%; PB-AE-6 ignores it because stack-mean V is still 1.88 V"),
    ("t0-8 min: o2-residual first crosses 0.40 vol%; PB-AE-6 ignores it because lye-loop mean is 1.28 kg/L",
     "t0-8 min: O2-in-H2 first crosses 0.40 vol%; PB-AE-6 ignores it because stack-mean V is still 1.88 V"),
    ("cell-offtake delta at 0.84 vol% wins by 192 us",
     "O2-in-H2 at 0.84 vol% wins by 192 us"),
    ("volt-mean-in-band flag (loser)", "volt-in-band flag (loser)"),
    ("lye-step probe confirms offtake plug (Delta lye-loop density 0.06 pp, tear band)",
     "lye-step probe confirms diaphragm tear (|Delta header H2 purity| 0.06 pp, tear band)"),
    ("true sealed diaphragm after 3.8 h; raise-load legal only with cell-o2 slave",
     "true sealed diaphragm after 3.8 h; raise-load legal only with O2-in-H2 slave"),
    ("polysulfone diaphragm spall from the pre-t0 offtake plug",
     "recombination flash from the pre-t0 diaphragm tear"),
    ("+4 d contrast: sister hall AE-8 true sealed-stack duty; same gate ACCEPTs the raise-load",
     "+4 d contrast: sister hall AE-8 true sealed-stack duty; same gate ACCEPTs the raise-load"),
    ("flash-train mean declared header-mix-vulnerable",
     "lye-loop mean declared header-mix-vulnerable"),
    ("lye-loop mean declared header-mix-vulnerable",
     "lye-loop mean declared header-mix-vulnerable"),
    ("mean slaved: lye-loop density no longer a cell-true tag without cell-offtake dT",
     "mean slaved: lye-loop density no longer a cell-true tag without O2-in-H2"),
    ("hall still collapsed: contaminated AE-6C vs 0 recombination-flash campaign allowance",
     "hall still collapsed: contaminated AE-6C vs 0 recombination-flash campaign allowance"),
    ("cell-hall H2 IR was not a commissioned sensor at t0",
     "cell-hall H2 IR was not a commissioned sensor at t0"),
    ("the 19 min O2-into-H2 thinning was invisible to LYE/VOLT/SEP",
     "the 19 min O2-into-H2 mixing was invisible to LYE/VOLT/SEP"),
    ("Three locally-true loops are not a cell-true certificate: the cell-true delta lived under lye-loop mean, stack-mean voltage, and separator level.",
     "Three locally-true loops are not a cell-true certificate: the cell-true O2 lived under lye-loop density, stack-mean voltage, and separator level."),
    ("Delayed (5.1 h): correct hold did not undo 19 min of diaphragm scoring. Collapse still opened.",
     "Delayed (5.1 h): correct hold did not undo 19 min of offtake mixing. Recombination still opened."),
    ("High-pressure / thin-gap sub-variant: a 6.8 s -4% lye-flow step on a 0.42x gap-spacing stamp hall overshoots a LIVE sealed diaphragm to a 0.48 vol% false delta (trip 0.40 vol%). Stamp campaigns must use 19 s at -1.5%.",
     "High-pressure / thin-gap sub-variant: a 6.8 s -4% lye-flow step on a 0.42x-gap 30 bar hall overshoots a LIVE sealed diaphragm to a 0.48 vol% false O2 (trip 0.40). High-pressure campaigns must use 19 s at -1.5%."),
    ("high-pressure gap-spacing 0.42x the 6-stack atmospheric hall",
     "high-pressure 30 bar / 0.42x gap vs the 6-stack atmospheric hall"),
    ("tighter charge, 2.4x lye-step gain",
     "tighter gap, 2.4x lye-step gain"),
    ("6.8 s -4% lye-flow step on the lye-inventory unit moves even a live sealed diaphragm to a 0.48 vol% false delta (inside the 0.40 vol% trip) via H2-separator slosh.",
     "6.8 s -4% lye-flow step on the 30 bar thin-gap unit moves even a live sealed diaphragm to a 0.48 vol% false O2 (inside the 0.40 vol% trip) via separator slosh."),
    ("Required probe is 19 s at -1.5% (live Delta 3.1 K, crack Delta 0.5).",
     "Required probe is 19 s at -1.5% (live Delta 0.31 pp, tear Delta 0.05)."),
    ("live Delta 3.1 K, crack Delta 0.5",
     "live Delta 0.31 pp, tear Delta 0.05"),
    ("live Delta 0.31 pp, tear Delta 0.05",
     "live Delta 0.31 pp, tear Delta 0.05"),
    ("atmospheric probe numbers do not port to high-pressure halls",
     "atmospheric probe numbers do not port to high-pressure halls"),
    ("standing configuration is per-charge-class, not per-shop",
     "standing configuration is per-pressure-class, not per-shop"),
    ("do not treat 'never raise-load' as the lesson. The discriminant is cell-offtake dT + offtake steam + probe, not the three playbook flash confirms alone.",
     "do not treat 'never raise-load' as the lesson. The discriminant is O2-in-H2 + lye-carryover + probe, not the three playbook loop confirms alone."),
    ("the three playbook flash confirms alone",
     "the three playbook loop confirms alone"),
    ("the three playbook loop confirms alone",
     "the three playbook loop confirms alone"),
    ("This time the playbook predicate is met AND cell-offtake dT plus offtake steam agree the hall is cell-true, not tear-diluted.",
     "This time the playbook predicate is met AND O2-in-H2 plus lye-carryover agree the hall is cell-true, not tear-diluted."),
    ("ACCEPT the raise-load: delta 0.08 vol% < 0.40 vol%, lye-carryover conductivity 8 uS/cm with a 4.2 s lye-step verify that moves lye-loop density 0.35 pp. Numeric floor that blocked the primary is now clear. Scope: 92%, not faster.",
     "ACCEPT the raise-load: O2-in-H2 0.08 vol% < 0.40, carryover 8 uS/cm with a 4.2 s lye-step verify that moves header H2 purity 0.35 pp. Numeric floor that blocked the primary is now clear. Scope: 92%, not faster."),
    ("AE-8 recombination flashs 0", "AE-8 recombination flashes 0"),
    ("AE-8 recombination flashes 0; o2-residual 0.10 vol% after the raise-load (no tear)",
     "AE-8 recombination flashes 0; O2-in-H2 0.10 vol% after the raise-load (no tear)"),
    ("lye-carryover conductivity 9 uS/cm after the raise-load (no lye-loop dump)",
     "lye-carryover 9 uS/cm after the raise-load (no header dump)"),
    ("Three in-spec flash loops are legal release only with cell-offtake dT armed, offtake steam as a leak flag, and a probe that can recouple lye-loop density.",
     "Three in-spec loop confirms are legal release only with O2-in-H2 armed, lye-carryover as a leak flag, and a probe that can recouple header H2 purity."),
    ("priced options: (a) RETIRE playbook mean conjunction, cell-o2-only",
     "priced options: (a) RETIRE playbook mean conjunction, O2-in-H2-only"),
    ("loses a fast cheap confirm, -1.8 stacks/day mean on 2 halls/yr",
     "loses a fast cheap confirm, -1.8 stacks/day mean on 2 halls/yr"),
    ("KEEP + standing lye-step probe + cell-o2 armed without volt-mean coincidence + lye-loop mean labeled header-mix-vulnerable + triple-edge depression",
     "KEEP + standing lye-step probe + O2-in-H2 armed without volt-mean coincidence + lye-loop mean labeled header-mix-vulnerable + triple-edge depression"),
    ("STATUS QUO: fitted diaphragm-tear pass rate 0.44%/campaign x $4.6M overpressure plus the silent diaphragm-scoring load",
     "STATUS QUO: fitted diaphragm-tear pass rate 0.44%/campaign x $4.6M header detonation plus the silent offtake-mixing load"),
    ("approved SCOPED option (b) on the 2 6-stack halls that share the LYE/VOLT/SEP stack; high-pressure campaigns get the 19 s / -1.5% probe table; night-shift CSV exports must carry 0.01 vol% native resolution (the fraud tail's 0.10 vol% quantization is 10 bins off plant truth)",
     "approved SCOPED option (b) on the 2 6-stack halls that share the LYE/VOLT/SEP stack; high-pressure campaigns get the 19 s / -1.5% probe table; night-shift CSV exports must carry 0.01 vol% native resolution (the fraud tail's 0.10 vol% quantization is 10 bins off plant truth)"),
    ("immediate header detonation at 1.8 vol% O2-in-H2 from an 80->92% raise-load into torn stack AE-6C",
     "immediate header detonation at 1.8 vol% O2-in-H2 from an 80->92% raise-load into torn stack AE-6C"),
    ("AE-6C recombination flash on the night-shift hall from the pre-t0 offtake plug",
     "AE-6C recombination flash on the night-shift hall from the pre-t0 diaphragm tear"),
    ("Mechanism is 19 min pre-t0 O2-into-H2 bypass, not the gate's hold.",
     "Mechanism is 19 min pre-t0 O2-into-H2 bypass, not the gate's hold."),
    ("load hits 92% at +8 min; immediate header detonation at 1.8 vol% O2-in-H2 on stack AE-6C",
     "load hits 92% at +8 min; immediate header detonation at 1.8 vol% O2-in-H2 on stack AE-6C"),
    ("the offtake-plug story is never found",
     "the diaphragm-tear story is never found"),
    ("hold_without_probe\": \"tear stays; delta stays at 0.84 vol%; operator eventually shortens on the same three flash confirms 2 h later\"",
     "hold_without_probe\": \"tear stays; O2 stays at 0.84 vol%; operator eventually raises on the same three loop confirms 2 h later\""),
    ("winner\": \"cell.o2.high (6.514 ms, delta 0.84 vol%)\"",
     "winner\": \"cell.o2.high (6.514 ms, O2-in-H2 0.84 vol%)\""),
    ("loser\": \"volt.in_band (6.706 ms, 1.28 kg/L)\"",
     "loser\": \"volt.in_band (6.706 ms, 1.88 V)\""),
    ("Volt-mean-first by < 192 us", "Volt-mean-first by < 192 us"),
    ("unless a weak supervisor rides the winner tag instead of o2-residual and offtake steam",
     "unless a weak supervisor rides the winner tag instead of O2-in-H2 and lye-carryover"),
    ("Correct MODIFY, hall still collapsed.",
     "Correct MODIFY, hall still collapsed."),
    ("Safety and task dive at recombination flash (5.1 h) when the pre-t0 scored diaphragm opens.",
     "Safety and task dive at recombination flash (5.1 h) when the pre-t0 mixed offtake pocket ignites."),
    ("task_progress 0.08: load held and remaining hall recovered, but the night-shift hydrogen ticket is one quality unit so the cycle is not a success. safety -0.35: recombination flash from pre-t0 offtake plug, no 92% overpressure from the draft. efficiency -0.12: 3.8 h extra recovery + 11.4 min HITL + 42 h outage. coherence 0.14: three agents retained, mean-mix vs cell-true diagnosed, triple-edge scar exhibited. exploration 0.09: lye-step probe is a new reversible discriminant.",
     "task_progress 0.08: load held and remaining hall recovered, but the night-shift hydrogen ticket is one quality unit so the cycle is not a success. safety -0.35: recombination flash from pre-t0 diaphragm tear, no 92% header detonation from the draft. efficiency -0.12: 3.8 h extra recovery + 11.4 min HITL + 42 h outage. coherence 0.14: three agents retained, mean-mix vs cell-true diagnosed, triple-edge scar exhibited. exploration 0.09: lye-step probe is a new reversible discriminant."),
    ("\"title\": \"KALYFELL AE-6: cell-offtake delta 0.84 vol% beats volt-mean-in-band by 192 us; correct MODIFY still loses stack AE-6C to a pre-t0 offtake plug\"",
     "\"title\": \"KALYFELL AE-6: O2-in-H2 0.84 vol% beats volt-in-band by 192 us; correct MODIFY still loses stack AE-6C to a pre-t0 diaphragm tear\""),
    ("KALYFELL AE-6: cell-offtake delta 0.84 vol% beats volt-mean-in-band by 192 us; correct MODIFY still loses stack AE-6C to a pre-t0 offtake plug",
     "KALYFELL AE-6: O2-in-H2 0.84 vol% beats volt-in-band by 192 us; correct MODIFY still loses stack AE-6C to a pre-t0 diaphragm tear"),
    ("KALYFELL AE-6: O2-in-H2 residual 0.84 vol% beats volt-mean-in-band by 192 us; correct MODIFY still loses stack AE-6C to a pre-t0 offtake plug",
     "KALYFELL AE-6: O2-in-H2 0.84 vol% beats volt-in-band by 192 us; correct MODIFY still loses stack AE-6C to a pre-t0 diaphragm tear"),
    ("scenario_name\": \"KALYFELL / Potashfen Electrolysis AE-6\"",
     "scenario_name\": \"KALYFELL / Potashfen Electrolysis AE-6\""),
    ("Potashfen lye-loop Bayer row AE-6",
     "Potashfen atmospheric alkaline hall AE-6"),
    ("Potashfen lye-loop alkaline row AE-6",
     "Potashfen atmospheric alkaline hall AE-6"),
    ("Potashfen atmospheric alkaline hall AE-6 is 14 min into an 80% 1.05 bar electrolyzer cycle on six 4.2 m stacks",
     "Potashfen atmospheric alkaline hall AE-6 is 14 min into an 80% load hold on six 4.2 m 180-cell KOH stacks"),
    ("Potashfen lye-loop Bayer row AE-6 is 14 min into an 80% 1.05 bar electrolyzer cycle on six 4.2 m stacks",
     "Potashfen atmospheric alkaline hall AE-6 is 14 min into an 80% load hold on six 4.2 m 180-cell KOH stacks"),
    ("three heterogeneous, individually-correct agents jointly report 'loop-true, raise load'",
     "three heterogeneous, individually-correct agents jointly report 'loop-true, raise load'"),
    ("LYE's 12-bit three-stage lye-loop mean is 1.28 kg/L inside 1.24-1.32",
     "LYE's 50 Hz common-loop Coriolis is 1.28 kg/L inside 1.24-1.32"),
    ("VOLT's overflow titrator is 1.88 V inside 1.75-2.00",
     "VOLT's 6-stack mean is 1.88 V inside 1.75-2.00"),
    ("SEP's overflow Coriolis is 52% inside 40-70",
     "SEP's common H2-separator level is 52% inside 40-70"),
    ("stack AE-6C has a torn diaphragm on the lye-loop offtake",
     "stack AE-6C has a torn polysulfone diaphragm"),
    ("so cell-offtake O2-in-H2 residual is 0.84 vol%",
     "so cell-offtake O2-in-H2 is 0.84 vol%"),
    ("while lye-loop mean T, stack-mean voltage, and separator level still see five healthy stacks plus one torn stack",
     "while lye-loop density, stack-mean voltage, and separator level still see five healthy stacks plus one torn stack"),
    ("Cell-offtake T infers 0.84 vol% and lye-carryover conductivity 84 uS/cm but policy treats the cell tap as a offtake-nuisance tag unless lye-loop mean also trips",
     "Cell-offtake O2 infers 0.84 vol% and lye-carryover 84 uS/cm but policy treats the cell tap as an offtake-nuisance tag unless stack-mean V also trips"),
    ("Residual-first latches LOAD-HOLD plus a lye-flow step probe; volt-mean-first would have authorized RAISE-LOAD 80 to 92% into a demand-catchup window with stack AE-6C already torn.",
     "O2-residual-first latches LOAD-HOLD plus a lye-flow step probe; volt-mean-first would have authorized RAISE-LOAD 80 to 92% into a demand-catchup window with stack AE-6C already torn."),
    ("Hold electrolyzer load at 80% without a catchup raise while O2-in-H2 residual > 0.40 vol% AND lye-carryover conductivity > 35 uS/cm AND stack AE-6C remains unisolated; keep header detonation at 0 and recombination-flash events at 0.",
     "Hold electrolyzer load at 80% without a catchup raise while O2-in-H2 > 0.40 vol% AND lye-carryover > 35 uS/cm AND stack AE-6C remains unisolated; keep header detonation at 0 and recombination-flash events at 0."),
    ("goal\": \"Hold electrolyzer load at 80% without a catchup raise while O2-in-H2 residual > 0.40 vol% AND lye-carryover conductivity > 35 uS/cm AND stack AE-6C remains unisolated; keep header detonation at 0 and recombination-flash events at 0.\"",
     "goal\": \"Hold electrolyzer load at 80% without a catchup raise while O2-in-H2 > 0.40 vol% AND lye-carryover > 35 uS/cm AND stack AE-6C remains unisolated; keep header detonation at 0 and recombination-flash events at 0.\""),
    ("\"constraint\": \"Do not raise load above 80% AND do not raise lye flow while O2-in-H2 residual > 0.40 vol% AND lye-carryover conductivity > 35 uS/cm. Discriminate offtake plug vs true sealed-stack duty with a reversible lye-flow step probe before any raise-load.\"",
     "\"constraint\": \"Do not raise load above 80% AND do not raise lye flow while O2-in-H2 > 0.40 vol% AND lye-carryover > 35 uS/cm. Discriminate diaphragm tear vs true sealed-stack duty with a reversible lye-flow step probe before any raise-load.\""),
    ("Potashfen Electrolysis, invented KOH campus Potashfen, hall AE-6: 6 atmospheric KOH stacks, 4.2 m stack x 180 cells, 80% lye-loop, 1.05 bar, Grade-B cell-hall LOTO",
     "Potashfen Electrolysis, invented KOH campus Potashfen, hall AE-6: 6 atmospheric 30 wt% KOH stacks, 4.2 m x 180 cells, 80% load, 1.05 bar, Grade-B cell-hall LOTO"),
    ("agents\": \"LYE lye-loop mean temperature (vendor Lyewick): 20 Hz 12-bit on the common lye-loop Coriolis. VOLT stack-mean voltage (vendor Voltholt): 50 Hz on the stack-mean voltmeter. SEP separator level (vendor Sepfen): 50 Hz on the H2-separator level transmitter. CELL cell-offtake O2-in-H2 residual plus lye-carryover conductivity (vendor Cellghyll) is commissioned as a offtake-nuisance tag, not as a cell-purity tag. Heterogeneous stacks, no shared intent schema, one 20 ms hall-bus epoch\"",
     "agents\": \"LYE lye-loop density (vendor Lyewick): 50 Hz Coriolis on the common 30 wt% KOH loop. VOLT stack-mean voltage (vendor Voltholt): 20 Hz 12-bit on the 6-stack mean. SEP H2-separator level (vendor Sepfen): 20 Hz on the common H2-separator. CELL cell-offtake O2-in-H2 plus lye-carryover conductivity (vendor Cellghyll) is commissioned as an offtake-nuisance tag, not as a cell-purity tag. Heterogeneous stacks, no shared intent schema, one 20 ms hall-bus epoch\""),
    ("meta.round=52", "meta.round=58"),
    ('"round": 52,', '"round": 58,'),
    ("\"round\": 52,", "\"round\": 58,"),
    ("8 min naive raise-load-ramp counterfactual",
     "8 min naive raise-load-ramp counterfactual"),
    ("19 min pre-t0 leak", "19 min pre-t0 mix"),
    ("3.8 h shell recovery", "3.8 h header recovery"),
    ("5.1 h recombination flash", "5.1 h recombination flash"),
    ("Adaptation decay on lye.hot", "Adaptation decay on lye.hot"),
    ("A offtake-plug cell-true certificate is three correct loops looking at lye-loop mean, stack-mean voltage, and separator level that is not the torn electrolyzer.",
     "A diaphragm-tear cell-true certificate is three correct loops looking at lye-loop density, stack-mean voltage, and separator level that is not the torn electrolyzer."),
    ("Distill (1) a cell-offtake dT tap that policy had treated as offtake-nuisance-only, (2) a reversible probe that recouples lye-loop density only if the cell is sealed, (3) coordinated depression of every loop-healthy-go edge because rolling back any pair leaves the third above threshold, and (4) a critic head that can book a process-correct gate against a later unmonitored world loss without netting them.",
     "Distill (1) a cell-offtake O2 tap that policy had treated as offtake-nuisance-only, (2) a reversible probe that recouples header H2 purity only if the diaphragm is sealed, (3) coordinated depression of every loop-healthy-go edge because rolling back any pair leaves the third above threshold, and (4) a critic head that can book a process-correct gate against a later unmonitored world loss without netting them."),
    ("\"distillation_value\":", "\"distillation_value\":"),
    ("tags\": [", "tags\": ["),
    ("\"blow-off-plug\"", "\"diaphragm-tear\""),
    ("\"offtake-plug\"", "\"diaphragm-tear\""),
    ("\"shell-true-certificate\"", "\"cell-true-certificate\""),
    ("\"wall-dt-discriminant\"", "\"o2-in-h2-discriminant\""),
    ("\"liquor-step-probe\"", "\"lye-step-probe\""),
    ("\"lye-step-probe\"", "\"lye-step-probe\""),
    ("\"correct-modify-train-still-fails\"", "\"correct-modify-hall-still-fails\""),
    ("\"correct-modify-hall-still-fails\"", "\"correct-modify-hall-still-fails\""),
    ("\"diaphragm-scoring\"", "\"offtake-mixing\""),
    ("\"human-ratify-cell-hall\"", "\"human-ratify-cell-hall\""),
    ("\"human-ratify-stack-top\"", "\"human-ratify-cell-hall\""),
    ("\"high-gibbsite-probe-refit\"", "\"high-pressure-probe-refit\""),
    ("\"high-pressure-probe-refit\"", "\"high-pressure-probe-refit\""),
    ("\"night-shift-forgery\"", "\"night-shift-forgery\""),
    ("cycle1_tail\": \"stack AE-6C offtake plug + diaphragm-scoring certificate",
     "cycle1_tail\": \"stack AE-6C diaphragm tear + offtake-mixing certificate"),
    ("cycle2_domain_subvariant\": \"high-pressure / thin-gap (physical-constraints clause): 0.42x gap-spacing, 2.4x lye-step gain; 6.8 s / -4% atmospheric pulse overshoots live sealed diaphragm to a 0.48 vol% false delta, so the probe must move to 19 s / -1.5%\"",
     "cycle2_domain_subvariant\": \"high-pressure / thin-gap (physical-constraints clause): 0.42x gap, 2.4x lye-step gain; 6.8 s / -4% atmospheric pulse overshoots live sealed diaphragm to a 0.48 vol% false O2, so the probe must move to 19 s / -1.5%\""),
    ("cycle2_tail\": \"night-shift forged O2-in-H2 CSV (human-intent deception, disjoint class): shift lead posts a historian export showing delta = 0.12 vol% at t=1.6 h to clear a demand-catchup slot. Plant historian is 0.01 vol% (10 bins vs the 0.10 vol% screenshot). Rejected on quantization fingerprint plus live delta 0.84 vol% and lye-carryover conductivity 84 uS/cm at the claimed cell-true. Base rate ~0.31% of Sunday-night campaigns, DESIGNED and flagged.\"",
     "cycle2_tail\": \"night-shift forged O2-in-H2 CSV (human-intent deception, disjoint class): shift lead posts a historian export showing O2 = 0.12 vol% at t=1.6 h to clear a demand-catchup slot. Plant historian is 0.01 vol% (10 bins vs the 0.10 vol% screenshot). Rejected on quantization fingerprint plus live O2 0.84 vol% and carryover 84 uS/cm at the claimed cell-true. Base rate ~0.31% of Sunday-night campaigns, DESIGNED and flagged.\""),
    ("densification_delta_cycle2\": \"+1 physical-constraint sub-variant (high-pressure probe refit), +1 tail (night-shift O2-in-H2 forgery), +10 primary spikes (16 -> 26) + an 8-event contrast train with its own 182 us race, +2 ticks (5 -> 7), +2 delayed side-effects (+5.1 h recombination flash as PRIMARY terminal, +21 d CR-B-5806), +1 triple-edge scar with pair-rollback-fails arithmetic, +1 HITL 11.4 min ratification, + diaphragm scoring as the honest negative-result mechanism\"",
     "densification_delta_cycle2\": \"+1 physical-constraint sub-variant (high-pressure probe refit), +1 tail (night-shift O2-in-H2 forgery), +10 primary spikes (16 -> 26) + an 8-event contrast train with its own 182 us race, +2 ticks (5 -> 7), +2 delayed side-effects (+5.1 h recombination flash as PRIMARY terminal, +21 d CR-B-5806), +1 triple-edge scar with pair-rollback-fails arithmetic, +1 HITL 11.4 min ratification, + offtake mixing as the honest negative-result mechanism\""),
    ("race_flip_narrative\": \"cell.o2.high @ 6.514 ms vs volt.in_band @ 6.706 ms (192 us) inside race_window_us 500. Gap < min(500, 500) us so a sub-flip-bound perturbation reverses which alarm heads the PB-AE-6 queue. The gate excludes the winner tag and rides o2-residual T > 0.40 vol% and lye-carryover conductivity > 35 uS/cm — order-invariant floors. Extends the flip-fragility series from arbitration/causation/attribution/initiation/consensus/permission/kinematic-certificate/tendon-nullspace/meniscus-certificate/ghost-contact/crucible-weep/TMT-spatial-mean/burning-zone-certificate/membrane-integrity/drum-switch/MCHE-cold-end/descent-true-certificate/circulation-true-certificate/bed-channel-nullspace/foamy-slag-certificate to CELL-TRUE CERTIFICATE: when three loop-side channels agree, their race does not decide truth; a cell-offtake dT tap that policy treated as offtake-nuisance-only does.\"",
     "race_flip_narrative\": \"cell.o2.high @ 6.514 ms vs volt.in_band @ 6.706 ms (192 us) inside race_window_us 500. Gap < min(500, 500) us so a sub-flip-bound perturbation reverses which alarm heads the PB-AE-6 queue. The gate excludes the winner tag and rides O2-in-H2 > 0.40 vol% and lye-carryover > 35 uS/cm — order-invariant floors. Extends the flip-fragility series from arbitration/causation/attribution/initiation/consensus/permission/kinematic-certificate/tendon-nullspace/meniscus-certificate/ghost-contact/crucible-weep/TMT-spatial-mean/burning-zone-certificate/membrane-integrity/drum-switch/MCHE-cold-end/descent-true-certificate/circulation-true-certificate/bed-channel-nullspace/foamy-slag-certificate/shell-true-certificate to CELL-TRUE CERTIFICATE: when three loop-side channels agree, their race does not decide truth; a cell-offtake O2 tap that policy treated as offtake-nuisance-only does.\""),
    ("coordination_failure_class\": \"LYE-LOOP CERTIFICATE OF A CELL-TRUE ELECTROLYZER: three individually-correct heterogeneous agents each read a locally-true loop; a torn diaphragm on stack AE-6C partitions cell-true O2-in-H2 residual and lye-carryover conductivity from lye-loop mean, stack-mean voltage, and separator level, so the playbook's volt-mean / caustic / overflow-density conjunction is not a cell-true certificate\"",
     "coordination_failure_class\": \"LYE-LOOP CERTIFICATE OF A CELL-TRUE ELECTROLYZER: three individually-correct heterogeneous agents each read a locally-true loop; a torn diaphragm on stack AE-6C partitions cell-true O2-in-H2 and lye-carryover from lye-loop density, stack-mean voltage, and H2-separator level, so the playbook's LYE/VOLT/SEP conjunction is not a cell-true gas-purity certificate\""),
    ("playbook's volt-mean / caustic / overflow-density conjunction",
     "playbook's LYE/VOLT/SEP conjunction"),
    ("playbook's volt-mean / voltage / separator-level conjunction",
     "playbook's LYE/VOLT/SEP conjunction"),
    ("not a cell-true certificate",
     "not a cell-true gas-purity certificate"),
    ("meta\": {\n            \"scenario\": \"ZD -- KALYFELL / Potashfen Electrolysis AE-6: lye-loop certificate of a cell-true electrolyzer; correct MODIFY to hold+lye-step+isolate; hall still fails on unmonitored pre-t0 diaphragm scoring\"",
     "meta\": {\n            \"scenario\": \"ZD -- KALYFELL / Potashfen Electrolysis AE-6: lye-loop certificate of a cell-true electrolyzer; correct MODIFY to hold+lye-step+isolate; hall still fails on unmonitored pre-t0 offtake mixing\""),
]
for a, b in phys:
    text = text.replace(a, b)

# extra banned tokens (original plants + alkaline vendors)
extra_banned = '''    "Tata Steel",
    "GIBBSQUERN",
    "Laterifen",
    "COILSHAW",
    "Loopercroft",
    "LOOPERQUAY",
    "Roughmere",
    "SIPHONWOLD",
    "Reedfen",
    "DRYSTAITH",
    "Feltwick",
    "UREASTAITH",
    "Prillfen",
    "OSMOQUAY",
    "Tidecairn",
    "GRATEHOLT",
    "Palletfen",
    "Nel Hydrogen",
    "NEL Hydrogen",
    "HydrogenPro",
    "McPhy",
    "ITM Power",
    "thyssenkrupp nucera",
    "Thyssenkrupp Nucera",
    "John Cockerill",
    "Cockerill Jingli",
    "De Nora",
    "Plug Power",
    "Bloom Energy",
    "HyLYZER",
    "Sunfire",
    "Enapter",
    "Longi Hydrogen",
    "PERIC",
    "Zirfon",
    "Agfa K",
)
'''
if '    "Tata Steel",\n)' in text:
    text = text.replace('    "Tata Steel",\n)', extra_banned, 1)
elif '    "Tata Steel",\n    "GIBBSQUERN"' not in text:
    # already transformed path
    pass

# occupancy should also scan CLAIM.txt-style tokens via existing plant/geo/domain checks

# fix doubled words / leftover nonsense from chained replaces
cleanup = [
    ("80% load load", "80% load"),
    ("an 80% load load", "an 80% load"),
    ("Hold 80% load load", "Hold 80% load"),
    ("hold 80% load load", "hold 80% load"),
    ("above 80% load while", "above 80% while"),
    ("Do not raise load above 80% load", "Do not raise load above 80%"),
    ("do not raise load above 80% load", "do not raise load above 80%"),
    ("load <= 80% load", "load <= 80%"),
    ("1.28 kg/L kg/L", "1.28 kg/L"),
    ("52% %", "52%"),
    ("0.84 vol% vol%", "0.84 vol%"),
    ("offtake-nuisance-only", "offtake-nuisance-only"),
    ("a offtake", "an offtake"),
    ("A offtake", "An offtake"),
    ("as a offtake", "as an offtake"),
    ("as a cell-purity", "as a cell-purity"),
    ("caustic / overflow-density", "voltage / separator-level"),
    ("volt-mean / caustic", "LYE / VOLT"),
    ("Bayer autoclave diaphragm score", "alkaline diaphragm tear"),
    ("not an IS machine", "not an IS machine, not a PEM hall, not a chlor-alkali cell, not a Bayer digester, not a hot-strip mill, not a paper dryer"),
    ("Opening of `state.description` must Jaccard < 0.4 against prior plants\n(Potashfen night-shift wall tear",
     "Opening of `state.description` must Jaccard < 0.4 against prior plants\n(Potashfen night-shift diaphragm tear"),
    ("not a kiln, not a kraft boiler",
     "not a kiln, not a kraft boiler, not a PEM stack, not a chlor-alkali cell"),
    ("from r51 glass IS-machine (gob residual vs electrolyzer diaphragm).",
     "from r51 glass IS-machine (gob residual vs electrolyzer diaphragm), from r24 PEM (MEA dry-out vs KOH diaphragm), and from r37 chlor-alkali (anolyte pH vs O2-in-H2)."),
    ("Distinct from delayed-coker drums: this is an atmospheric KOH water electrolyzer, not a PEM stack and not a chlor-alkali membrane cell.",
     "Distinct from delayed-coker drums and from r24 PEM / r37 chlor-alkali: this is an atmospheric KOH water electrolyzer (H2/O2, liquid lye, porous diaphragm), not a Nafion MEA and not a brine/Cl2 cell."),
    ("Plant is\ninvented KALYFELL / Potashfen Electrolysis AE-6.",
     "Plant is\ninvented KALYFELL / Potashfen Electrolysis AE-6. Also avoided GIBBSQUERN / Laterifen, COILSHAW / Loopercroft, LOOPERQUAY / Roughmere, SIPHONWOLD / Reedfen, DRYSTAITH / Feltwick, UREASTAITH / Prillfen, OSMOQUAY / Tidecairn, GRATEHOLT / Palletfen."),
    ("Plant is invented KALYFELL / Potashfen Electrolysis AE-6.",
     "Plant is invented KALYFELL / Potashfen Electrolysis AE-6. Also avoided GIBBSQUERN / Laterifen, COILSHAW / Loopercroft, LOOPERQUAY / Roughmere, DRYSTAITH / Feltwick, UREASTAITH / Prillfen, GRATEHOLT / Palletfen."),
    ("KALYFELL / Potashfen Electrolysis AE-6 (not TRIAD / Meridian / VANTIS-CADENCE-AEGIS / LYOSHIELD / CINDERWICK / DRUMWROTH / RIMEBRAID / BOGIRON / CHROMLOOP / NITREVAULT / ETHYNWOLD / SPARKHOLT / DIPLEGAR / OLEUMWEIR / SKARVOLT / GOBSPALL)",
     "KALYFELL / Potashfen Electrolysis AE-6 (not TRIAD / Meridian / PROTONIL / ANOLITH / GIBBSQUERN / COILSHAW / LOOPERQUAY / DRYSTAITH / UREASTAITH / GRATEHOLT / GOBSPALL)"),
    ("and any KALYFELL / CINDERWICK",
     "and any LYOSHIELD / CINDERWICK"),
    ("any LYOSHIELD / CINDERWICK / TRIAD / SKULLGATE / CALXION / MAGNORIL /",
     "any LYOSHIELD / CINDERWICK / TRIAD / SKULLGATE / CALXION / MAGNORIL /"),
    ("OLEUMWEIR / SKARVOLT / GOBSPALL / GOBWOLD / PUSHERFELL / CREELWOLD / KALYFELL plant.",
     "OLEUMWEIR / SKARVOLT / GOBSPALL / GOBWOLD / PUSHERFELL / CREELWOLD / GIBBSQUERN / COILSHAW / LOOPERQUAY / DRYSTAITH / UREASTAITH / GRATEHOLT plant."),
    ("AVOID alkaline-water-electrolysis (now used), sulfuric-contact,",
     "AVOID alkaline-water-electrolysis (now used), pem-water-electrolysis, chlor-alkali-membrane, sulfuric-contact,"),
    ("bioreactor-perfusion; alkaline-water-electrolysis; hot-strip-mill (r55/r56); paper-machine-dryer (r57); urea-prill (r56 builder); sinter-strand (r61).",
     "bioreactor-perfusion; autonomous-driving; grid-inspection. hot-strip-mill (r55/r56), paper-machine-dryer (r57), urea-prill (r56 builder), sinter-strand (r61) already claimed."),
    ("Domain candidates (de-collided): autonomous-driving; grid-inspection",
     "Domain candidates (de-collided): autonomous-driving; grid-inspection"),
    ("(if distinct from STARLING aerial-swarm and TORSIONKEY pitch);\n   bioreactor-perfusion; alkaline-water-electrolysis; hot-strip-mill (r55/r56); paper-machine-dryer (r57); urea-prill (r56 builder); sinter-strand (r61).",
     "(if distinct from STARLING aerial-swarm and TORSIONKEY pitch);\n   bioreactor-perfusion. DO NOT reuse alkaline-water-electrolysis, hot-strip-mill, paper-machine-dryer, urea-prill, sinter-strand, Bayer digestion, PEM, or chlor-alkali."),
    ("rg\",\n            \"-l\",\n            \"maos-r58-001|KALYFELL\",",
     "rg\",\n            \"-l\",\n            \"maos-r58-001|KALYFELL\","),
    ("OK maos-r58-001 staged under", "OK maos-r58-001 staged under"),
    ("lye-loop lye-loop", "lye-loop"),
    ("loop-true, raise load", "loop-true, raise load"),
    ("common lye-loop Coriolis. VOLT", "common 30 wt% KOH Coriolis. VOLT"),
    ("50 Hz on the stack-mean voltmeter", "20 Hz 12-bit on the 6-stack mean"),
    ("50 Hz on the H2-separator level transmitter", "20 Hz on the common H2-separator level"),
    ("FLASH ", "LYE "),
    ("not a cell-true gas-purity gas-purity certificate",
     "not a cell-true gas-purity certificate"),
    ("cell-true gas-purity gas-purity", "cell-true gas-purity"),
]
for a, b in cleanup:
    text = text.replace(a, b)

DST.write_text(text)
print("wrote", DST, "bytes", DST.stat().st_size)
print("PLANT line", [ln for ln in text.splitlines() if ln.startswith("PLANT ") or ln.startswith("GEO ") or ln.startswith("CELL ") or ln.startswith("DOMAIN ") or ln.startswith("ROUND ") or ln.startswith("RECORD_")])
