#!/usr/bin/env python3
"""Clone MAOS r54 builder → r58 carbon-anode ring furnace (PACKFLUE)."""
from pathlib import Path

text = Path("/tmp/maos-r54/build_r54.py").read_text()

# identity — never globally replace '54' (spike amplitude 0.54)
for a, b in [
    ("Build and self-check MAOS round-54", "Build and self-check MAOS round-58"),
    ('GEN_AT = "2026-09-03T08:54:00Z"', 'GEN_AT = "2026-09-03T09:58:00Z"'),
    ('OUT = Path("/tmp/maos-r54")', 'OUT = Path("/tmp/maos-r58")'),
    ('RECORD_ID = "maos-r54-001"', 'RECORD_ID = "maos-r58-001"'),
    ("ROUND = 54", "ROUND = 58"),
    ('NOVEL_LINE = "Novel coverage: 46%"', 'NOVEL_LINE = "Novel coverage: 45%"'),
    ("maos-r54-001", "maos-r58-001"),
    ("maos-r54", "maos-r58"),
    ("batch-r54", "batch-r58"),
    ("NOTES-r54", "NOTES-r58"),
    ("swarm-transcript-r54", "swarm-transcript-r58"),
    ("build_r54", "build_r58"),
    ("Round 54 transcript", "Round 58 transcript"),
    ("ROUND 54", "ROUND 58"),
    ("round 54", "round 58"),
    ("CR-B-5406", "CR-B-5806"),
    ("What ROUND 55 should add", "What ROUND 59 should add"),
    ("staged r14–r53", "staged r14–r61"),
    ("staged r14-r53", "staged r14-r61"),
    ("staged r14–r51", "staged r14-r61"),
    ("staged r14-r51", "staged r14-r61"),
    ("r14-r51", "r14-r61"),
    ("1753510680000054", "1755325080000058"),
    ("2026-08-09T01:42:00-05:00", "2026-08-16T02:18:00-05:00"),
    ("scenario (ZB)", "scenario (ZG)"),
    ("Scenario ZB", "Scenario ZG"),
    ("ZB -- ", "ZG -- "),
    ("ZB — ", "ZG — "),
]:
    text = text.replace(a, b)

for a, b in [
    ("GIBBSQUERN", "PACKFLUE"),
    ("Laterifen", "Greenfen"),
    ("PB-DG-7", "PB-AB-7"),
    ("TG-DG-7", "TG-AB-7"),
    ("DG-7C", "AB-7C"),
    ("DG-8", "AB-8"),
    ("DG-7", "AB-7"),
    ("gibbsite-autoclave-digestion", "carbon-anode-ring-furnace"),
]:
    text = text.replace(a, b)

# extra BANNED (prior plants + real vendors)
extra = '''    "Tata Steel",
    "GIBBSQUERN",
    "Laterifen",
    "COILSHAW",
    "Loopercroft",
    "LOOPERQUAY",
    "Roughmere",
    "SIPHONWOLD",
    "Reedfen",
    "DRYSTAITH",
    "Feltwick",
    "UREASTAITH",
    "Prillfen",
    "OSMOQUAY",
    "Tidecairn",
    "GRATEHOLT",
    "Palletfen",
    "LANCEQUAY",
    "Boffmere",
    "KALYFELL",
    "Potashfen",
    "KALYCIRQUE",
    "Alkalfen",
    "TITERWEIR",
    "Spargeholt",
    "WINDBOXHOLT",
    "Gratecroft",
    "Riedhammer",
    "Innovatherm",
    "Tokai Carbon",
    "GrafTech",
    "SGL Carbon",
    "Showa Denko",
    "SEC Carbon",
    "Alcoa",
)
'''
if '    "Tata Steel",\n)' in text:
    text = text.replace('    "Tata Steel",\n)', extra, 1)

phys = [
    ("FLASH-TRAIN CERTIFICATE OF A LIVE-STEAM DIGESTER",
     "FIRE-GROUP CERTIFICATE OF A PIT-TRUE RING FURNACE"),
    ("flash-train certificate of a live-steam digester",
     "fire-group certificate of a pit-true ring furnace"),
    ("6-vessel live-steam Bayer autoclave",
     "6-pit open-ring anode-baking furnace"),
    ("live-steam Bayer autoclave train",
     "open-ring anode-baking fire group"),
    ("live-steam Bayer autoclave", "open-ring anode-baking furnace"),
    ("Bayer live-steam autoclave", "open-ring anode-baking furnace"),
    ("Bayer alumina digestion / live-steam autoclave",
     "carbon-anode ring-furnace baking / packing-coke pits"),
    ("Bayer alumina digestion", "carbon-anode ring-furnace baking"),
    ("Bayer alumina", "carbon-anode baking"),
    ("industrial-process / Bayer alumina",
     "industrial-process / carbon-anode baking"),
    ("this is a Bayer live-steam autoclave, not a petroleum delayed-coker",
     "this is an open-ring packing-coke anode furnace, not a coke-oven battery and not a PAN oxidation oven"),
    ("live-steam autoclave cycle", "fire-advance soak"),
    ("live-steam autoclave", "ring-furnace"),
    ("live-steam digestion", "ring-furnace baking"),
    ("live-steam bypass", "flue-into-pit bypass"),
    ("live-steam dump", "packing-fire path"),
    ("live-steam nozzle", "pit peephole"),
    ("live-steam thinning", "packing-coke scoring"),
    ("unmonitored live-steam", "unmonitored flue-into-pit"),
    ("live-steam", "underfire"),
    ("flash-train mean temperature", "fire-group flue mean T"),
    ("flash-train mean T", "fire-group flue mean T"),
    ("flash-train mean", "fire-group mean"),
    ("flash-train header average", "fire-group header average"),
    ("flash-train header", "fire-group header"),
    ("flash-train flash mean T", "fire-group flue mean T"),
    ("flash-train T", "fire-group flue T"),
    ("flash-train heat", "fire-group heat"),
    ("flash-train", "fire-group"),
    ("three-stage flash header", "common fire-group flue"),
    ("3-stage flash-train TC cluster", "fire-group flue TC cluster"),
    ("flash-tank inlet", "crossover-flue inlet"),
    ("flash-tank slosh", "packing slump"),
    ("flash-tank", "crossover flue"),
    ("flash-T-first", "flue-mean-first"),
    ("flash-T-in-band", "flue-in-band"),
    ("flash-T", "flue-mean"),
    ("Flash-T-first", "Flue-mean-first"),
    ("flash-true", "flue-true"),
    ("flash-side", "flue-side"),
    ("flash-mix-vulnerable", "flue-mix-vulnerable"),
    ("flash-mix", "flue-mix"),
    ("flash confirms", "flue confirms"),
    ("flash loops", "flue loops"),
    ("flash average", "fire-group average"),
    ("FLASH's", "FLUE's"),
    ("FLASH ", "FLUE "),
    ("FLASH,", "FLUE,"),
    ("FLASH/", "FLUE/"),
    ("vendor Flashholt", "vendor Fluewick"),
    ("overflow caustic titrator", "ring-draft transmitter"),
    ("overflow caustic", "ring draft"),
    ("overflow Coriolis density", "packing-coke IR mean"),
    ("overflow Coriolis", "packing IR"),
    ("overflow density", "packing IR"),
    ("overflow-true", "packing-true"),
    ("overflow-density", "packing-IR"),
    ("combined overflow", "common packing mean"),
    ("vendor Caustwick", "vendor Draftfen"),
    ("vendor Densfen", "vendor Packholt"),
    ("vendor Shellghyll", "vendor Pitghyll"),
    ("CAUST's", "DRAFT's"),
    ("CAUST ", "DRAFT "),
    ("CAUST,", "DRAFT,"),
    ("CAUST/", "DRAFT/"),
    ("DENS's", "PACK's"),
    ("DENS ", "PACK "),
    ("DENS,", "PACK,"),
    ("DENS/", "PACK/"),
    ("FLASH/CAUST/DENS", "FLUE/DRAFT/PACK"),
    ("shell-jacket delta T", "pit-wall delta T"),
    ("shell-jacket delta", "pit-wall delta"),
    ("shell-jacket dT", "pit-wall dT"),
    ("shell-jacket T", "pit-wall T"),
    ("shell-jacket tap", "pit-wall tap"),
    ("shell-jacket", "pit-wall"),
    ("Shell-delta-first", "Pit-delta-first"),
    ("shell-delta-first", "pit-delta-first"),
    ("shell-delta-win", "pit-delta-win"),
    ("shell-delta", "pit-delta"),
    ("Shell-delta", "Pit-delta"),
    ("shell-true", "pit-true"),
    ("SHELL-TRUE", "PIT-TRUE"),
    ("shell.delta.high", "pit.delta.high"),
    ("shell.dT", "pit.dT"),
    ("shell.score", "pit.score"),
    ("shell.spall", "pit.flash"),
    ("shell.clear", "pit.clear"),
    ("shell-skin IR", "pit-wall IR"),
    ("shell scoring", "packing scoring"),
    ("shell-scoring", "packing-scoring"),
    ("scored shell", "scored packing"),
    ("scored cladding", "scored packing"),
    ("shell spall", "packing fire"),
    ("shell-spall", "packing-fire"),
    ("Shell spall", "Packing fire"),
    ("shell-TC", "pit-TC"),
    ("jacket-nuisance", "pit-nuisance"),
    ("noisy shell-TC after a blow-off trip",
     "noisy pit-TC after a damper trip"),
    ("noisy shell-TC", "noisy pit-TC"),
    ("Monel-clad shell spall", "AB-7C packing fire"),
    ("monel-clad shell", "packing-coke cover"),
    ("Monel-clad", "Packing-coke"),
    ("monel-clad", "packing-coke"),
    ("blow-off overpressure", "packing fire"),
    ("blow-off-plug", "flue-wall-leak"),
    ("blow-off plug", "flue-wall leak"),
    ("Blow-off plug", "Flue-wall leak"),
    ("plugged blow-off", "leaking flue wall"),
    ("plugged vessel", "leaking pit"),
    ("blow-off steam", "peephole CO"),
    ("blow-off trip", "damper trip"),
    ("open blow-off", "sealed flue wall"),
    ("open-blow-off", "sealed-flue"),
    ("blow-off", "peephole"),
    ("RAISE-CHARGE", "ADVANCE-FIRE"),
    ("raise-charge", "advance-fire"),
    ("raise_charge", "advance_fire"),
    ("Raise-charge", "Advance-fire"),
    ("raise charge", "advance fire"),
    ("RESIDENCE-HOLD", "SOAK-HOLD"),
    ("residence_hold", "soak_hold"),
    ("residence-time floor", "soak-time floor"),
    ("residence_min", "soak_min"),
    ("residence_hold_floor_min", "soak_hold_floor_min"),
    ("proposed_residence_min", "proposed_soak_min"),
    ("shorten residence", "advance fire"),
    ("shortens residence", "advances fire"),
    ("shorten night-shift residence", "advance night-shift fire"),
    ("Hold digestion residence", "Hold fire-advance soak"),
    ("Hold 45 min", "Hold 45 min soak"),
    ("hold 45 min", "hold 45 min soak"),
    ("holds 45 min", "holds 45 min soak"),
    ("held 45 min", "held 45 min soak"),
    ("below 45 min", "below 45 min soak"),
    ("residence >= 45 min", "soak >= 45 min"),
    ("residence at 45 min", "soak at 45 min"),
    ("45 min residence", "45 min soak"),
    ("a 45 min", "a 45 min soak"),
    ("14 min into a 45 min", "14 min into a 45 min"),
    ("45 to 39 min", "45 to 39 min soak"),
    ("45 -> 39 min", "45 -> 39 min"),
    ("45->39 min", "45->39 min"),
    ("to 39 min", "to 39 min soak"),
    ("39 min residence", "39 min soak"),
    ("liquor-flow step probe", "draft-step probe"),
    ("liquor-flow step", "draft-step"),
    ("liquor-step probe", "draft-step probe"),
    ("LIQUOR-STEP-PROBE", "DRAFT-STEP-PROBE"),
    ("liquor-step", "draft-step"),
    ("liquor flow", "ring draft"),
    ("Liquor flow", "Ring draft"),
    ("liquor-flow", "draft-step"),
    ("liquor.probe", "draft.probe"),
    ("liquor.demand", "fire.demand"),
    ("standing liquor-step", "standing draft-step"),
    ("Gas-step gain", "Draft-step gain"),
    ("gas step", "draft-step"),
    ("2.4x liquor-step gain", "2.4x draft-step gain"),
    ("vessel-top visual", "pit-deck visual"),
    ("vessel-top climb", "pit-deck climb"),
    ("vessel-top work", "pit-deck work"),
    ("vessel-top", "pit-deck"),
    ("Vessel-top", "Pit-deck"),
    ("vessel interlock", "pit interlock"),
    ("VESSEL-AB-7C", "PIT-AB-7C"),
    ("vessel.hold", "pit.hold"),
    ("vessel AB-7C", "pit AB-7C"),
    ("Vessel AB-7C", "Pit AB-7C"),
    ("fault_vessel", "fault_pit"),
    ("fault_shell", "fault_pitwall"),
    ("vessel_count", "pit_count"),
    ("six 3.8 m vessels", "six 4.2 m pits"),
    ("6 live-steam autoclave vessels", "6 open-ring baking pits"),
    ("3.8 m ID x 18 m", "4.2 m pit x 14 anode columns"),
    ("Grade-B vessel-top LOTO", "Grade-B pit-deck LOTO"),
    ("flashing vessels", "healthy pits"),
    ("five flashing", "five healthy"),
    ("6 vessels", "6 pits"),
    ("6-vessel", "6-pit"),
    ("vessels", "pits"),
    ("vessel", "pit"),
    ("Vessel", "Pit"),
    ("flash.in_band", "flue.in_band"),
    ("flash.hot", "flue.hot"),
    ("caust.ok", "draft.ok"),
    ("dens.ok.in_band", "pack.ok.in_band"),
    ("dens.ok", "pack.ok"),
    ("flash_in_band_pop", "flue_in_band_pop"),
    ("flash_healthy_pop", "flue_ok_pop"),
    ("caust_ok_pop", "draft_ok_pop"),
    ("dens_ok_pop", "pack_ok_pop"),
    ("raise_charge_pop", "advance_fire_pop"),
    ("shell_dt_pop", "pit_dt_pop"),
    ("residence_hold_pop", "soak_hold_pop"),
    ("high-gibbsite / short-residence", "high-pitch / short-soak"),
    ("high-gibbsite", "high-pitch"),
    ("low-gibbsite", "standard-pitch"),
    ("extraction-time", "fire-travel"),
    ("hydrate-catchup window", "fire-catchup window"),
    ("hydrate-catchup slot", "fire-catchup slot"),
    ("hydrate-catchup", "fire-catchup"),
    ("hydrate is one quality unit", "fire-group is one quality unit"),
    ("night-shift hydrate", "night-shift fire-group"),
    ("night-shift train", "night-shift ring"),
    ("forged wall-T CSV", "forged pit-T CSV"),
    ("wall-T CSV", "pit-T CSV"),
    ("wall-T forgery", "pit-T forgery"),
    ("digestion supervisory optimizer DSO",
     "ring-furnace supervisory optimizer RSO"),
    ("Digestion AB-7", "Baking AB-7"),
    ("Digestion, invented bauxite campus",
     "Baking, invented anode campus"),
    ("invented bauxite campus", "invented anode campus"),
    ("true digestion-duty", "true sealed-flue duty"),
    ("digestion-duty", "sealed-flue duty"),
    ("digestion residence", "fire-advance soak"),
    ("Bayer charge-raises", "anode fire-advances"),
    ("autoclave shell", "ring-furnace pit wall"),
    ("autoclave", "ring-furnace"),
    ("digestion", "baking"),
    ("Digestion", "Baking"),
    ("gibbsite", "green-anode"),
    ("stamp battery", "high-pitch ring"),
    ("quarantined battery", "quarantined ring"),
    ("battery saved", "ring saved"),
    ("coke-oven wall physics", "ring-furnace pit physics"),
    ("through-wall crack", "flue-wall leak"),
    ("wall crack", "flue-wall leak"),
    ("scale-plug MC", "flue-leak MC"),
    ("scale-plug arrival", "flue-leak arrival"),
    ("4.8 MPa", "1.02 bar"),
    ("148 C", "1148 C"),
    ("140-160", "1140-1160"),
    ("168 g/L Na2O", "16.8 mmH2O"),
    ("168 g/L", "16.8 mmH2O"),
    ("155-180 g/L Na2O", "15.5-18.0 mmH2O"),
    ("155-180 g/L", "15.5-18.0 mmH2O"),
    ("155-180", "15.5-18.0"),
    ("1.32 kg/L", "1.32 t/m3"),
    ("1.26-1.38 kg/L", "1.26-1.38 t/m3"),
    ("1.26-1.38", "1.26-1.38"),
    ("8.4 t/h", "8.4 vol%"),
    ("2.5 t/h", "2.5 vol%"),
    ("1.2 t/h", "1.2 vol%"),
    ("0.7 t/h", "0.7 vol%"),
    ("0.6 t/h", "0.6 vol%"),
    ("14 t/h steam", "14 vol% CO"),
    ("14 t/h", "14 vol%"),
    ("\"unit\": \"g/L\"", "\"unit\": \"mmH2O\""),
    ("\"unit\": \"kg/L\"", "\"unit\": \"t/m3\""),
    ("\"unit\": \"t/h\"", "\"unit\": \"vol%\""),
    ("\"caust_gL\"", "\"draft_mmH2O\""),
    ("\"caust_band_gL\"", "\"draft_band_mmH2O\""),
    ("\"dens_kgL\"", "\"pack_tm3\""),
    ("\"dens_band_kgL\"", "\"pack_band_tm3\""),
    ("\"flash_t_C\"", "\"flue_t_C\""),
    ("\"flash_t_deadband_C\"", "\"flue_t_deadband_C\""),
    ("\"wall_dT_K\"", "\"pit_dT_K\""),
    ("\"wall_dT_hold_K\"", "\"pit_dT_hold_K\""),
    ("\"wall_dT_healthy_K\"", "\"pit_dT_healthy_K\""),
    ("\"blowoff_tph\"", "\"peephole_co_volpct\""),
    ("\"blowoff_hold_tph\"", "\"peephole_co_hold_volpct\""),
    ("\"blowoff_healthy_tph\"", "\"peephole_co_healthy_volpct\""),
    ("\"blowoff_trip_tph\"", "\"peephole_co_trip_volpct\""),
    ("\"blowoff_now_tph\"", "\"peephole_co_now_volpct\""),
    ("\"name\": \"raise_charge\"", "\"name\": \"advance_fire\""),
    ("\"name\": \"advance_fire\"", "\"name\": \"advance_fire\""),
    ("load_hold_liquor_step_probe_isolate", "soak_hold_draft_step_probe_isolate"),
    ("\"liquor_step_probe\"", "\"draft_step_probe\""),
    ("populations flash 0-39, shell 40-79, dens 80-119, gate 120-159",
     "populations flue 0-39, pit 40-79, pack 80-119, gate 120-159"),
    ("\"title\": \"PACKFLUE AB-7: pit-wall delta 84 K beats flue-T-in-band by 192 us; correct MODIFY still loses pit AB-7C to a pre-t0 flue-wall leak\"",
     "\"title\": \"PACKFLUE AB-7: pit-wall delta 84 K beats flue-T-in-band by 192 us; correct MODIFY still loses pit AB-7C to a pre-t0 flue-wall leak\""),
    ("scenario_name\": \"PACKFLUE / Greenfen Baking AB-7\"",
     "scenario_name\": \"PACKFLUE / Greenfen Baking AB-7\""),
    ("Greenfen underfire Bayer row AB-7",
     "Greenfen open-ring anode hall AB-7"),
    ("Greenfen underfire alkaline row AB-7",
     "Greenfen open-ring anode hall AB-7"),
    ("meta.round=52", "meta.round=58"),
    ('"round": 52,', '"round": 58,'),
    ("\"round\": 52,", "\"round\": 58,"),
    ("electrolyzer-composite-cure", "autoclave-composite-cure"),
    ("electrolyzer ply-TC", "autoclave ply-TC"),
    ("Nafion MEA", "PEM MEA"),
    ("not fcc-regenerator-cyclone-dipleg (r47), not fcc-riser-regenerator (r46), not sulfuric-contact-converter (r48), not eaf-foamy-slag-water-panel (r49), not glass-container-is-machine (r51), not coke-oven-battery-heating (r52), not carbon-fiber-oxidation-oven (r53 in-flight), not delayed-coker-drum-switch (r38), not blast-furnace-burden-descent (r42); carbon-anode-ring-furnace is unused. autonomous-driving, grid-inspection left unused.",
     "not coke-oven-battery-heating (r52), not carbon-fiber-oxidation-oven (r53), not electrolytic-aluminum-potline (r21), not gibbsite-autoclave-digestion (r54), not bof-oxygen-lance-blow (r55), not urea-prilling-tower (r56), not paper-machine-dryer-section (r57), not alkaline-water-electrolysis (r59), not sinter-strand-windbox (r61), not mammalian-perfusion-bioreactor (r60 in-flight); carbon-anode-ring-furnace is unused. autonomous-driving, grid-inspection left unused."),
    ("Plant is\ninvented PACKFLUE / Greenfen Baking AB-7.",
     "Plant is invented PACKFLUE / Greenfen Baking AB-7. Also avoided GIBBSQUERN, LANCEQUAY, UREASTAITH, DRYSTAITH, KALYCIRQUE, TITERWEIR, WINDBOXHOLT, KALYFELL, COILSHAW, LOOPERQUAY."),
    ("Plant is invented PACKFLUE / Greenfen Baking AB-7.",
     "Plant is invented PACKFLUE / Greenfen Baking AB-7. Also avoided GIBBSQUERN, LANCEQUAY, UREASTAITH, DRYSTAITH, KALYCIRQUE, TITERWEIR, WINDBOXHOLT."),
    ("PACKFLUE / Greenfen Baking AB-7 (not TRIAD / Meridian / VANTIS-CADENCE-AEGIS / LYOSHIELD / CINDERWICK / DRUMWROTH / RIMEBRAID / BOGIRON / CHROMLOOP / NITREVAULT / ETHYNWOLD / SPARKHOLT / DIPLEGAR / OLEUMWEIR / SKARVOLT / GOBSPALL)",
     "PACKFLUE / Greenfen Baking AB-7 (not TRIAD / PUSHERFELL / CREELWOLD / REDHALL / GIBBSQUERN / LANCEQUAY / UREASTAITH / DRYSTAITH / KALYCIRQUE / WINDBOXHOLT / GOBSPALL)"),
    ("OLEUMWEIR / SKARVOLT / GOBSPALL / GOBWOLD / PUSHERFELL / CREELWOLD / PACKFLUE plant.",
     "OLEUMWEIR / SKARVOLT / GOBSPALL / GOBWOLD / PUSHERFELL / CREELWOLD / GIBBSQUERN / LANCEQUAY / UREASTAITH / DRYSTAITH / KALYCIRQUE / WINDBOXHOLT plant."),
    ("AVOID carbon-anode-ring-furnace (now used)",
     "AVOID carbon-anode-ring-furnace (now used), alkaline-water-electrolysis, hot-strip-mill, paper-machine-dryer, urea-prill, sinter-strand, BOF lance, Bayer digestion, PEM, chlor-alkali, coke-oven, carbon-fiber oxidation"),
    ("bioreactor-perfusion; alkaline-water-electrolysis; hot-strip-mill.",
     "bioreactor-perfusion (r60 in-flight); autonomous-driving; grid-inspection."),
    ("\"value\": 168.0,", "\"value\": 16.8,"),
    ("\"draft_mmH2O\": 168.0,", "\"draft_mmH2O\": 16.8,"),
    ("\"draft_band_mmH2O\": [15.5-18.0, 180.0],",
     "\"draft_band_mmH2O\": [15.5, 18.0],"),
    ("\"draft_band_mmH2O\": [15.5, 18.0],",
     "\"draft_band_mmH2O\": [15.5, 18.0],"),
    ("\"caust_gL\": 168.0,", "\"draft_mmH2O\": 16.8,"),
    ("hold 45 min soak soak", "hold 45 min soak"),
    ("Hold 45 min soak soak", "Hold 45 min soak"),
    ("45 min soak soak", "45 min soak"),
    ("below 45 min soak soak", "below 45 min soak"),
    ("to 39 min soak soak", "to 39 min soak"),
    ("a 45 min soak soak", "a 45 min soak"),
    ("fire-group fire-group", "fire-group"),
    ("FLUE/DRAFT/PACK", "FLUE/DRAFT/PACK"),
    ("advance_fire_pop", "advance_fire_pop"),
]
for a, b in phys:
    text = text.replace(a, b)

# occupancy: skip substring DOMAIN in other batches (leftover mentions);
# keep exact domain field + plant/geo/cell + builder assignments.
old_occ = '''        tokens = (PLANT, GEO, CELL, DOMAIN)
        for p in sorted(Path("/tmp").glob("maos-r*/batch-r*.jsonl")):
            if p.parent.name == "maos-r58":
                continue
            try:
                rec = json.loads(p.read_text().splitlines()[0])
            except (OSError, json.JSONDecodeError, IndexError):
                continue
            blob = json.dumps(rec)
            domain = (rec.get("state") or {}).get("domain")
            if domain == DOMAIN:
                hits.append(f"{p}: domain {domain}")
            for tok in tokens:
                if tok in blob:
                    hits.append(f"{p}: token {tok}")
'''
new_occ = '''        tokens = (PLANT, GEO, CELL)
        for p in sorted(Path("/tmp").glob("maos-r*/batch-r*.jsonl")):
            if p.parent.name == "maos-r58":
                continue
            try:
                rec = json.loads(p.read_text().splitlines()[0])
            except (OSError, json.JSONDecodeError, IndexError):
                continue
            blob = json.dumps(rec)
            domain = (rec.get("state") or {}).get("domain")
            if domain == DOMAIN:
                hits.append(f"{p}: domain {domain}")
            for tok in tokens:
                if tok in blob:
                    hits.append(f"{p}: token {tok}")
        for p in sorted(Path("/tmp").glob("maos-r*/CLAIM.txt")):
            if p.parent.name == "maos-r58":
                continue
            try:
                blob = p.read_text()
            except OSError:
                continue
            if f"PLANT={PLANT}" in blob or f"DOMAIN={DOMAIN}" in blob.replace(" ", ""):
                hits.append(f"{p}: claimed {PLANT}/{DOMAIN}")
'''
if old_occ in text:
    text = text.replace(old_occ, new_occ)
else:
    print("WARN occupancy block not found exact")

Path("/tmp/maos-r58/build_r58.py").write_text(text)
print("wrote", len(text), "chars")
print([ln for ln in text.splitlines() if ln.startswith(("PLANT ","GEO ","CELL ","DOMAIN ","RECORD_","ROUND ","GEN_AT ","OUT ","NOVEL_"))])
