"""Payment-idempotency provider pairs for the pay lane (r330).

AST-extracted from the legacy ``mill_leftover_leftover_leftover_pay_r330``
staging script on ``origin/legacy-mill-lane`` and cleaned into this package.
The 16 provider pairs each drive a success/failure episode pair in
:mod:`pipelines.pay.episodes`; the staging/execution machinery that drove
``round_txn.py`` is intentionally not vendored (the file is never executed
on this branch).

Distinct from r324-r329; no ``sir-``/``dbc-`` ids.
"""

from __future__ import annotations

FAC = "payment-idempotency-factory"
GEN = "grok-4.6"
PREFIX = "pay"

PAIRS = [
    dict(slug="adyen-pspref-leftover-vs-merchantref", fail="adyen-drop-pspref-handoff", mod="adypp", drop="adymr", keep="pspReference", naive="merchantReference", stack="Adyen leftover leftover leftover pspReference", drop_stack="Adyen merchantReference", doc="https://docs.adyen.com/api-explorer/Checkout/latest/post/payments", doc2="https://docs.adyen.com/development-resources/webhooks", domain="adyen-pspref-leftover-vs-merchantref", ticket="ADY-PP-330", test_ok="test_adypp", test_fail="test_adymr", short="adypp", dshort="adymr", first_wrong="skip_psp"),
    dict(slug="stripe-pi-leftover-vs-charge", fail="stripe-drop-pi-handoff", mod="stpi", drop="stch", keep="payment_intent", naive="charge", stack="Stripe leftover leftover leftover payment_intent", drop_stack="Stripe charge", doc="https://docs.stripe.com/api/payment_intents", doc2="https://docs.stripe.com/webhooks", domain="stripe-pi-leftover-vs-charge", ticket="ST-PI-331", test_ok="test_stpi", test_fail="test_stch", short="stpi", dshort="stch", first_wrong="charge_only"),
    dict(slug="braintree-txn-leftover-vs-orderid", fail="braintree-drop-txn-handoff", mod="bttxn", drop="btord", keep="transaction_id", naive="orderId", stack="Braintree leftover leftover leftover transaction", drop_stack="Braintree orderId", doc="https://developer.paypal.com/braintree/docs/reference/response/transaction", doc2="https://developer.paypal.com/braintree/docs/guides/webhooks/overview", domain="braintree-txn-leftover-vs-orderid", ticket="BT-TX-332", test_ok="test_bttxn", test_fail="test_btord", short="bttxn", dshort="btord", first_wrong="order_only"),
    dict(slug="square-payment-leftover-vs-idemkey", fail="square-drop-payment-handoff", mod="sqpay", drop="sqidk", keep="payment_id", naive="idempotency_key", stack="Square leftover leftover leftover payment_id", drop_stack="Square idempotency_key", doc="https://developer.squareup.com/reference/square/payments-api/create-payment", doc2="https://developer.squareup.com/docs/webhooks/overview", domain="square-payment-leftover-vs-idemkey", ticket="SQ-PAY-333", test_ok="test_sqpay", test_fail="test_sqidk", short="sqpay", dshort="sqidk", first_wrong="key_only"),
    dict(slug="cko-payment-leftover-vs-reference", fail="cko-drop-id-handoff", mod="ckoid", drop="ckoref", keep="id", naive="reference", stack="Checkout leftover leftover leftover payment id", drop_stack="Checkout reference", doc="https://www.checkout.com/docs/payments/accept-payments", doc2="https://www.checkout.com/docs/developer-resources/webhooks", domain="cko-payment-leftover-vs-reference", ticket="CKO-ID-334", test_ok="test_ckoid", test_fail="test_ckoref", short="ckoid", dshort="ckoref", first_wrong="ref_only"),
    dict(slug="worldpay-ordercode-leftover-vs-txn", fail="worldpay-drop-ordercode-handoff", mod="wpoc", drop="wptxn", keep="orderCode", naive="transactionId", stack="Worldpay leftover leftover leftover orderCode", drop_stack="Worldpay transactionId", doc="https://developer.worldpay.com/products/access/payments", doc2="https://developer.worldpay.com/products/access/webhooks", domain="worldpay-ordercode-leftover-vs-txn", ticket="WP-OC-335", test_ok="test_wpoc", test_fail="test_wptxn", short="wpoc", dshort="wptxn", first_wrong="txn_only"),
    dict(slug="authnet-transid-leftover-vs-refid", fail="authnet-drop-transid-handoff", mod="antr", drop="anref", keep="transId", naive="refId", stack="Authorize.Net leftover leftover leftover transId", drop_stack="Authorize.Net refId", doc="https://developer.authorize.net/api/reference/index.html", doc2="https://developer.authorize.net/api/reference/features/webhooks.html", domain="authnet-transid-leftover-vs-refid", ticket="AN-TR-336", test_ok="test_antr", test_fail="test_anref", short="antr", dshort="anref", first_wrong="ref_only"),
    dict(slug="paypal-capture-leftover-vs-order", fail="paypal-drop-capture-handoff", mod="ppcap", drop="ppord", keep="capture_id", naive="order_id", stack="PayPal leftover leftover leftover capture", drop_stack="PayPal order_id", doc="https://developer.paypal.com/docs/api/payments/v2/", doc2="https://developer.paypal.com/api/rest/webhooks/", domain="paypal-capture-leftover-vs-order", ticket="PP-CAP-337", test_ok="test_ppcap", test_fail="test_ppord", short="ppcap", dshort="ppord", first_wrong="order_only"),
    dict(slug="klarna-session-leftover-vs-order", fail="klarna-drop-session-handoff", mod="klses", drop="klord", keep="session_id", naive="order_id", stack="Klarna leftover leftover leftover session", drop_stack="Klarna order_id", doc="https://docs.klarna.com/klarna-payments/api/payments-api/", doc2="https://docs.klarna.com/api/kp/", domain="klarna-session-leftover-vs-order", ticket="KL-SES-338", test_ok="test_klses", test_fail="test_klord", short="klses", dshort="klord", first_wrong="order_only"),
    dict(slug="afterpay-token-leftover-vs-order", fail="afterpay-drop-token-handoff", mod="aptok", drop="apord", keep="token", naive="orderId", stack="Afterpay leftover leftover leftover token", drop_stack="Afterpay orderId", doc="https://developers.afterpay.com/afterpay-online/reference/create-checkout", doc2="https://developers.afterpay.com/afterpay-online/docs/webhooks", domain="afterpay-token-leftover-vs-order", ticket="AP-TK-339", test_ok="test_aptok", test_fail="test_apord", short="aptok", dshort="apord", first_wrong="order_only"),
    dict(slug="alipay-tradeno-leftover-vs-outtrade", fail="alipay-drop-tradeno-handoff", mod="alitn", drop="aliot", keep="trade_no", naive="out_trade_no", stack="Alipay leftover leftover leftover trade_no", drop_stack="Alipay out_trade_no", doc="https://opendocs.alipay.com/open/270/105898", doc2="https://opendocs.alipay.com/open/203/105286", domain="alipay-tradeno-leftover-vs-outtrade", ticket="ALI-TN-340", test_ok="test_alitn", test_fail="test_aliot", short="alitn", dshort="aliot", first_wrong="out_only"),
    dict(slug="wechat-txid-leftover-vs-outtrade", fail="wechat-drop-txid-handoff", mod="wxtx", drop="wxot", keep="transaction_id", naive="out_trade_no", stack="WeChat leftover leftover leftover transaction_id", drop_stack="WeChat out_trade_no", doc="https://pay.weixin.qq.com/wiki/doc/apiv3/apis/chapter3_1_1.shtml", doc2="https://pay.weixin.qq.com/wiki/doc/apiv3/apis/chapter3_1_5.shtml", domain="wechat-txid-leftover-vs-outtrade", ticket="WX-TX-341", test_ok="test_wxtx", test_fail="test_wxot", short="wxtx", dshort="wxot", first_wrong="out_only"),
    dict(slug="nuvei-txn-leftover-vs-clientreq", fail="nuvei-drop-txn-handoff", mod="nvtxn", drop="nvcr", keep="transactionId", naive="clientRequestId", stack="Nuvei leftover leftover leftover transactionId", drop_stack="Nuvei clientRequestId", doc="https://docs.nuvei.com/documentation/accept-payment/", doc2="https://docs.nuvei.com/documentation/features/webhooks/", domain="nuvei-txn-leftover-vs-clientreq", ticket="NV-TX-342", test_ok="test_nvtxn", test_fail="test_nvcr", short="nvtxn", dshort="nvcr", first_wrong="client_only"),
    dict(slug="airwallex-intent-leftover-vs-req", fail="airwallex-drop-intent-handoff", mod="awint", drop="awreq", keep="payment_intent_id", naive="request_id", stack="Airwallex leftover leftover leftover intent", drop_stack="Airwallex request_id", doc="https://www.airwallex.com/docs/api#/Payment_Acceptance/Payment_Intents/_api_v1_pa_payment_intents_create/post", doc2="https://www.airwallex.com/docs/payments__webhooks", domain="airwallex-intent-leftover-vs-req", ticket="AW-INT-343", test_ok="test_awint", test_fail="test_awreq", short="awint", dshort="awreq", first_wrong="req_only"),
    dict(slug="mollie-payment-leftover-vs-seq", fail="mollie-drop-payment-handoff", mod="mlpay", drop="mlseq", keep="id", naive="sequenceType", stack="Mollie leftover leftover leftover payment id", drop_stack="Mollie sequenceType", doc="https://docs.mollie.com/reference/create-payment", doc2="https://docs.mollie.com/docs/webhooks", domain="mollie-payment-leftover-vs-seq", ticket="ML-PAY-344", test_ok="test_mlpay", test_fail="test_mlseq", short="mlpay", dshort="mlseq", first_wrong="seq_only"),
    dict(slug="gocardless-payment-leftover-vs-idem", fail="gocardless-drop-payment-handoff", mod="gcpay", drop="gcidk", keep="payment", naive="Idempotency-Key", stack="GoCardless leftover leftover leftover payment", drop_stack="GoCardless Idempotency-Key", doc="https://developer.gocardless.com/api-reference/#payments-create-a-payment", doc2="https://developer.gocardless.com/getting-started/api/making-requests/#idempotency-keys", domain="gocardless-payment-leftover-vs-idem", ticket="GC-PAY-345", test_ok="test_gcpay", test_fail="test_gcidk", short="gcpay", dshort="gcidk", first_wrong="key_only"),
]

__all__ = ["FAC", "GEN", "PREFIX", "PAIRS"]
