#!/usr/bin/env python3
"""AST-extracted plant pairs for pbc_r803 (legacy-mill-lane pbc-mill-r803.py)."""

from __future__ import annotations

from .record_builder import plant

MILL_ID = 'pbc_r803'
CATALOG_FIRST = 803
START = 803
N_ROUNDS = 16
NOTES_EXTRA = ''
NOTES_FOOTER = ''

PAIRS: tuple[tuple[dict, dict], ...] = (
    (
        plant(
            slug='http-copy-parent-path',
            short='cpyp',
            decl_old='rpc Copy(CopyHeat) returns (Heat) { option (google.api.http) = { post: "/v1/{name=heats/*}:copy" body: "*" }; }',
            decl_new='rpc Copy(CopyHeat) returns (Heat) { option (google.api.http) = { post: "/v1/{parent=mills/*}/heats:copy" body: "*" }; }',
            syntax='syntax = "proto3";',
            imports=('google/api/annotations.proto',),
            extra_msgs='message CopyHeat { string name = 1; string parent = 2; string dest_id = 3; }\n',
            buf_rule='HTTP_PATH / FILE',
            wire_old='POST /v1/heats/{heat}:copy',
            wire_new='POST /v1/mills/{mill}/heats:copy',
            freeze='TS freeze POST /v1/heats/H-1:copy 404',
            ticket='TS-CPYP-143',
            lang='TypeScript',
            vs='r688 http-clone-collection-path (AIP-136 :copy parent path, not :clone)',
            avoid='r688 :clone / r695 :commit/:apply / pause/resume/archive cartesian',
            json_name='copyDest',
            debug='debug_cpyp',
            compat='Dual-route heats/{name}:copy and mills/{mill}/heats:copy',
            grep_pat='heats/\\*:copy|mills/\\*/heats:copy|rpc Copy',
            goal_bit='AIP-136 :copy resource path → mills/{mill}/heats:copy so freeze :copy 404s',
            dead_desc='additional_bindings mills path leaving heats/:copy off',
            dead_old='rpc Copy(CopyHeat) returns (Heat) { option (google.api.http) = { post: "/v1/{parent=mills/*}/heats:copy" body: "*" }; }',
            dead_new='rpc Copy(CopyHeat) returns (Heat) { option (google.api.http) = { post: "/v1/{parent=mills/*}/heats:copy" body: "*" additional_bindings { post: "/v2/{name=heats/*}:copy" } }; }',
            dead_obs='v2 :copy does not restore /v1/heats/{name}:copy; freeze still 404',
        ),
        plant(
            slug='parent-field-rename',
            short='prn',
            decl_old='string parent = 3;',
            decl_new='string mill = 3;',
            syntax='syntax = "proto3";',
            buf_rule='FIELD_SAME_NAME / FILE',
            wire_old='parent=3 UTF-8',
            wire_new='mill=3; freeze parent JSON ignored',
            freeze='Go freeze List parent=mills/M-1 ignored',
            ticket='GO-PRN-144',
            lang='Go',
            vs='r696 resource-name-field-rename (AIP-122 parent→mill, not name field)',
            avoid='r696 name field rename / r04 json_name / r752 skip drop',
            json_name='parent',
            debug='debug_prn',
            compat='Dual-read parent=3 and mill=3',
            grep_pat='string parent = 3|string mill = 3',
            goal_bit='AIP-122 parent=3 → mill=3 so freeze parent= JSON is ignored',
            dead_desc='json_name parent on mill as a rename substitute',
            dead_old='string mill = 3;',
            dead_new='string mill = 3 [json_name = "parent"];',
            dead_obs='json_name parent does not restore field parent=3; freeze proto field is mill',
        ),
    ),
    (
        plant(
            slug='http-merge-parent',
            short='mrgp',
            decl_old='rpc Merge(MergeHeat) returns (Heat) { option (google.api.http) = { post: "/v1/{name=heats/*}:merge" body: "*" }; }',
            decl_new='rpc Merge(MergeHeat) returns (Heat) { option (google.api.http) = { post: "/v1/{parent=mills/*}/heats:merge" body: "*" }; }',
            syntax='syntax = "proto3";',
            imports=('google/api/annotations.proto',),
            extra_msgs='message MergeHeat { string name = 1; string parent = 2; repeated string sources = 3; }\n',
            buf_rule='HTTP_PATH / FILE',
            wire_old='POST /v1/heats/{heat}:merge',
            wire_new='POST /v1/mills/{mill}/heats:merge',
            freeze='Go freeze POST /v1/heats/H-1:merge 404',
            ticket='GO-MRGP-145',
            lang='Go',
            vs='r688 http-clone-collection-path / r803 :copy parent (AIP-136 :merge, not :clone/:copy)',
            avoid='r688 :clone / copy mill / pause/resume/archive cartesian',
            json_name='mergeSrc',
            debug='debug_mrgp',
            compat='Dual-route heats/{name}:merge and mills/{mill}/heats:merge',
            grep_pat='heats/\\*:merge|mills/\\*/heats:merge|rpc Merge',
            goal_bit='AIP-136 :merge resource path → mills/{mill}/heats:merge so freeze :merge 404s',
        ),
        plant(
            slug='aip157-view-to-string',
            short='viewt',
            decl_old='View view = 6;',
            decl_new='string view = 6;',
            syntax='syntax = "proto3";',
            extra_msgs='enum View { VIEW_UNSPECIFIED = 0; BASIC = 1; FULL = 2; }\n',
            buf_rule='FIELD_TYPE / WIRE',
            wire_old='VARINT View enum',
            wire_new='LEN utf8 view',
            freeze='Java freeze View.FULL vs string',
            ticket='JAVA-VIEWT-146',
            lang='Java',
            vs='r722 enum-to-string-grade / r789 aip216-state-to-string (AIP-157 Get view, not Grade/lifecycle)',
            avoid='r722 grade / r789 state / r735 enum-to-int32',
            json_name='viewName',
            debug='debug_viewt',
            compat='Dual-read view as View enum or string',
            grep_pat='View view|string view = 6',
            goal_bit='AIP-157 View view=6 → string so freeze closed view enum fails',
            dead_desc='json_name viewName as a type substitute',
            dead_old='string view = 6;',
            dead_new='string view = 6 [json_name = "viewName"];',
            dead_obs='json_name does not restore View enum; freeze still string',
        ),
    ),
    (
        plant(
            slug='rpc-put-deleted',
            short='pdel',
            decl_old='rpc Put(Heat) returns (Heat);',
            decl_new='// rpc Put deleted',
            syntax='syntax = "proto3";',
            buf_rule='RPC_DELETED / FILE',
            wire_old='/S/Put unary',
            wire_new='rpc Put gone',
            freeze='Go freeze /pdel.v1.S/Put UNIMPLEMENTED',
            ticket='GO-PDEL-147',
            lang='Go',
            vs='r765 rpc-get-deleted / r792 rpc-create-deleted / r793 rpc-update-deleted (Put, not Get/Create/Update)',
            avoid='r765 Get / r792 Create / r793 Update / r698 List',
            json_name='putHeat',
            debug='debug_pdel',
            compat='Dual-route Put leftover for freeze',
            grep_pat='rpc Put|// rpc Put deleted',
            goal_bit='rpc Put deleted so freeze /S/Put UNIMPLEMENTED',
        ),
        plant(
            slug='field-behavior-optional-sku',
            short='fbopt',
            decl_old='string sku = 7;',
            decl_new='string sku = 7 [(google.api.field_behavior) = OPTIONAL];',
            syntax='syntax = "proto3";',
            imports=('google/api/field_behavior.proto',),
            buf_rule='FIELD_BEHAVIOR / FILE',
            wire_old='sku unlabeled',
            wire_new='OPTIONAL annotation; GAPIC treat-as-optional vs implicit',
            freeze='TS freeze sku required-by-client vs OPTIONAL',
            ticket='TS-FBOPT-148',
            lang='TypeScript',
            vs='r785 field-behavior-required-sku / r793 IDENTIFIER (OPTIONAL leftover, not REQUIRED/IDENTIFIER)',
            avoid='r785 REQUIRED / r793 IDENTIFIER / field-behavior-output / field-behavior-immutable',
            json_name='skuCode',
            debug='debug_fbopt',
            compat='Treat unlabeled sku and OPTIONAL sku as dual',
            grep_pat='field_behavior|OPTIONAL|string sku',
            goal_bit='field_behavior OPTIONAL on sku=7 so freeze implicit-required sku fails',
            dead_desc='json_name skuCode as an OPTIONAL substitute',
            dead_old='string sku = 7 [(google.api.field_behavior) = OPTIONAL];',
            dead_new='string sku = 7 [(google.api.field_behavior) = OPTIONAL, json_name = "skuCode"];',
            dead_obs='json_name does not drop OPTIONAL; freeze still OPTIONAL sku',
        ),
    ),
    (
        plant(
            slug='duration-to-int64-millis',
            short='d2ms',
            decl_old='google.protobuf.Duration hold = 20;',
            decl_new='int64 hold_ms = 20;',
            syntax='syntax = "proto3";',
            imports=('google/protobuf/duration.proto',),
            buf_rule='FIELD_TYPE / WIRE',
            wire_old='LEN Duration seconds+nanos',
            wire_new='VARINT hold_ms; freeze Duration JSON fails',
            freeze='Go freeze durationpb.Duration vs int64 ms',
            ticket='GO-D2MS-149',
            lang='Go',
            vs='r720 duration-to-string-hold / r727 duration-to-bytes-hold / r744 duration-to-timestamp (Duration→int64 millis, not string/bytes/Timestamp)',
            avoid='r720/r727/r744 Duration plants / r802 int64-to-string scalar cartesian',
            json_name='holdMs',
            debug='debug_d2ms',
            compat='Dual-read hold as Duration or int64 millis',
            grep_pat='Duration hold|int64 hold_ms',
            goal_bit='Duration hold=20 → int64 hold_ms so freeze seconds+nanos Duration fails',
        ),
        plant(
            slug='empty-to-timestamp-ack',
            short='e2ts',
            decl_old='google.protobuf.Empty ack = 21;',
            decl_new='google.protobuf.Timestamp ack = 21;',
            syntax='syntax = "proto3";',
            imports=('google/protobuf/empty.proto', 'google/protobuf/timestamp.proto'),
            buf_rule='FIELD_TYPE / WIRE',
            wire_old='LEN empty 0-length',
            wire_new='LEN Timestamp seconds+nanos',
            freeze='Python freeze Empty vs Timestamp',
            ticket='PY-E2TS-150',
            lang='Python',
            vs='r796 empty-to-bool-ack / r769 empty-to-string-ack (Empty→Timestamp, not bool/string/bytes/message)',
            avoid='r717/r742/r769/r796 Empty plants / r713 timestamp-to-string',
            json_name='ackedAt',
            debug='debug_e2ts',
            compat='Dual-read ack as Empty or Timestamp',
            grep_pat='protobuf.Empty ack|protobuf.Timestamp ack',
            goal_bit='Empty ack=21 → Timestamp so freeze 0-length Empty fails',
            dead_desc='json_name ackedAt as an Empty-type substitute',
            dead_old='google.protobuf.Timestamp ack = 21;',
            dead_new='google.protobuf.Timestamp ack = 21 [json_name = "ackedAt"];',
            dead_obs='json_name does not restore Empty; freeze still Timestamp',
        ),
    ),
    (
        plant(
            slug='oneof-enum-to-str',
            short='oe2s',
            decl_old='oneof ref { Grade grade = 4; }',
            decl_new='oneof ref { string grade = 4; }',
            syntax='syntax = "proto3";',
            extra_msgs='enum Grade { GRADE_UNSPECIFIED = 0; A = 1; B = 2; }\n',
            buf_rule='FIELD_TYPE / WIRE',
            wire_old='VARINT Grade in oneof',
            wire_new='LEN utf8 in oneof',
            freeze='Java freeze Grade vs String oneof',
            ticket='JAVA-OE2S-151',
            lang='Java',
            vs='r756 oneof-enum-to-int / r722 enum-to-string-grade (oneof enum→string, not →int; not scalar grade)',
            avoid='r756 oneof enum→int / r797 oneof-bool-to-str / r722 grade scalar',
            json_name='gradeCode',
            debug='debug_oe2s',
            compat='Dual-read oneof grade as Grade or string',
            grep_pat='Grade grade|string grade|oneof ref',
            goal_bit='oneof Grade grade=4 → string so freeze VARINT enum fails',
        ),
        plant(
            slug='listvalue-to-struct-tags',
            short='lv2st',
            decl_old='google.protobuf.ListValue tags = 22;',
            decl_new='google.protobuf.Struct tags = 22;',
            syntax='syntax = "proto3";',
            imports=('google/protobuf/struct.proto',),
            buf_rule='FIELD_TYPE / WIRE',
            wire_old='LEN ListValue values[]',
            wire_new='LEN Struct fields map',
            freeze='Python freeze ListValue vs Struct',
            ticket='PY-LV2ST-152',
            lang='Python',
            vs='r795 listvalue-to-value-tags / r768 listvalue-to-string (ListValue→Struct, not Value/string/bytes)',
            avoid='r718/r730/r768/r795 ListValue plants / r770 value-to-struct',
            json_name='tagStruct',
            debug='debug_lv2st',
            compat='Dual-read tags as ListValue or Struct',
            grep_pat='ListValue tags|Struct tags',
            goal_bit='ListValue tags=22 → Struct so freeze values[] fails',
            dead_desc='json_name tagStruct as a ListValue substitute',
            dead_old='google.protobuf.Struct tags = 22;',
            dead_new='google.protobuf.Struct tags = 22 [json_name = "tagStruct"];',
            dead_obs='json_name does not restore ListValue; freeze still Struct',
        ),
    ),
    (
        plant(
            slug='proto2-ext-msg-to-bytes',
            short='x2b',
            decl_old='optional Chip ext = 99;',
            decl_new='optional bytes ext = 99;',
            syntax='syntax = "proto2";',
            extra_msgs='message Chip { string id = 1; int32 n = 2; }\n',
            buf_rule='FIELD_TYPE / WIRE',
            wire_old='LEN nested Chip',
            wire_new='LEN raw bytes',
            freeze='C++ freeze Chip vs bytes on extend field 99',
            ticket='CPP-X2B-153',
            lang='Cpp',
            vs='r763 proto2-ext-int-to-str / r664 proto2-extend-msg-99 (extension message→bytes, not int→str)',
            avoid='r763 ext int→str / r664 extend msg / r705 message-to-bytes',
            json_name='extBin',
            debug='debug_x2b',
            compat='Dual-read ext as Chip or bytes',
            grep_pat='optional Chip ext|optional bytes ext',
            goal_bit='proto2 optional Chip ext=99 → bytes so freeze nested Chip fails',
        ),
        plant(
            slug='proto2-to-editions',
            short='p2ed',
            decl_old='syntax = "proto2";',
            decl_new='edition = "2023";',
            syntax='// file-level syntax is the plant',
            buf_rule='SYNTAX / FILE',
            wire_old='proto2 required/optional/defaults',
            wire_new='edition 2023 features; freeze proto2 codegen',
            freeze='Java freeze proto2 HasField vs editions',
            ticket='JAVA-P2ED-154',
            lang='Java',
            vs='r794 proto3-to-editions / r798 proto2-req-to-proto3-lot (proto2→edition, not proto3→edition or required drop)',
            avoid='r794 proto3→edition / r635 legacy-required / unpacked/EXPANDED cartesian',
            json_name='syntaxTag',
            debug='debug_p2ed',
            compat='Dual-generate proto2 and edition 2023',
            grep_pat='syntax = "proto2"|edition = "2023"',
            goal_bit='syntax proto2 → edition 2023 so freeze proto2 HasField codegen fails',
            dead_desc='edition 2024 as a proto2-restore substitute',
            dead_old='edition = "2023";',
            dead_new='edition = "2024";',
            dead_obs='edition 2024 does not restore proto2; freeze still editions',
        ),
    ),
    (
        plant(
            slug='http-get-list-to-post',
            short='gl2p',
            decl_old='rpc List(ListHeats) returns (ListHeatsResponse) { option (google.api.http) = { get: "/v1/heats" }; }',
            decl_new='rpc List(ListHeats) returns (ListHeatsResponse) { option (google.api.http) = { post: "/v1/heats:search" body: "*" }; }',
            syntax='syntax = "proto3";',
            imports=('google/api/annotations.proto',),
            extra_msgs='message ListHeats { string parent = 1; }\nmessage ListHeatsResponse { repeated Heat heats = 1; }\n',
            buf_rule='HTTP_METHOD / FILE',
            wire_old='GET /v1/heats',
            wire_new='POST /v1/heats:search',
            freeze='TS freeze GET /v1/heats 404',
            ticket='TS-GL2P-155',
            lang='TypeScript',
            vs='r778 http-search-custom GET :search→POST :query / r698 rpc-list-deleted (List GET→POST :search, not rpc deleted)',
            avoid='r778 :search→:query / r698 List deleted / r697 GET body',
            json_name='listParent',
            debug='debug_gl2p',
            compat='Dual-route GET /v1/heats and POST :search',
            grep_pat='get: \\"/v1/heats\\"|heats:search|rpc List',
            goal_bit='AIP-132 List GET /v1/heats → POST :search so freeze GET 404s',
        ),
        plant(
            slug='resource-ref-type-heat-to-pour',
            short='rrtp',
            decl_old='string heat = 9 [(google.api.resource_reference) = { type: "mill.example.com/Heat" }];',
            decl_new='string heat = 9 [(google.api.resource_reference) = { type: "mill.example.com/Pour" }];',
            syntax='syntax = "proto3";',
            imports=('google/api/resource.proto',),
            buf_rule='RESOURCE_REFERENCE / FILE',
            wire_old='resource_reference Heat',
            wire_new='resource_reference Pour; freeze GAPIC parse Heat',
            freeze='Go freeze heats/H-1 vs pours/P-1 reference',
            ticket='GO-RRTP-156',
            lang='Go',
            vs='r642 gapic-resource-type-dross / r660 resource-ref-child-type (type Heat→Pour, not child_type)',
            avoid='r642 resource type / r660 child_type / r784 pattern heats→pours',
            json_name='heatName',
            debug='debug_rrtp',
            compat='Dual-accept Heat and Pour resource_reference',
            grep_pat='mill.example.com/Heat|mill.example.com/Pour|resource_reference',
            goal_bit='resource_reference type Heat → Pour so freeze heats/ parse fails',
            dead_desc='json_name heatName as a type-URL substitute',
            dead_old='string heat = 9 [(google.api.resource_reference) = { type: "mill.example.com/Pour" }];',
            dead_new='string heat = 9 [(google.api.resource_reference) = { type: "mill.example.com/Pour" }, json_name = "heatName"];',
            dead_obs='json_name does not restore Heat type; freeze still Pour',
        ),
    ),
    (
        plant(
            slug='lro-http-binding-drop',
            short='lrohb',
            decl_old='rpc Cast(CastHeat) returns (google.longrunning.Operation) { option (google.api.http) = { post: "/v1/heats/{name}:cast" body: "*" additional_bindings { get: "/v1/operations/{name}" } }; option (google.longrunning.operation_info) = { response_type: "Heat" metadata_type: "CastMeta" }; }',
            decl_new='rpc Cast(CastHeat) returns (google.longrunning.Operation) { option (google.api.http) = { post: "/v1/heats/{name}:cast" body: "*" }; option (google.longrunning.operation_info) = { response_type: "Heat" metadata_type: "CastMeta" }; }',
            syntax='syntax = "proto3";',
            imports=('google/api/annotations.proto', 'google/longrunning/operations.proto'),
            extra_msgs='message CastHeat { string name = 1; }\nmessage CastMeta { int32 pct = 1; }\n',
            buf_rule='HTTP_ADDITIONAL_BINDINGS / FILE',
            wire_old='GET /v1/operations/{name} poll binding',
            wire_new='poll binding dropped; freeze GET operation 404',
            freeze='Go freeze GET /v1/operations/op-1 404',
            ticket='GO-LROHB-157',
            lang='Go',
            vs='r696 http-addl-bind-drop-export / r685 lro-opinfo-metadata-cast (drop Operation GET poll, not :export / metadata_type)',
            avoid='r696 :export drop / r685 metadata_type / r676 unary-to-lro',
            json_name='opName',
            debug='debug_lrohb',
            compat='Dual-route :cast and GET /v1/operations/{name}',
            grep_pat='operations/\\{name\\}|rpc Cast|:cast',
            goal_bit='LRO additional_bindings GET /operations/{name} dropped so freeze poll 404s',
        ),
        plant(
            slug='aip122-uid-segment',
            short='uidseg',
            decl_old='option (google.api.resource) = { type: "mill.example.com/Heat" pattern: "heats/{heat}" }; string name = 10;',
            decl_new='option (google.api.resource) = { type: "mill.example.com/Heat" pattern: "heats/{heat_id}" }; string name = 10;',
            syntax='syntax = "proto3";',
            imports=('google/api/resource.proto',),
            buf_rule='RESOURCE_PATTERN / FILE',
            wire_old='heats/{heat}',
            wire_new='heats/{heat_id}; freeze GAPIC {heat} parse',
            freeze='Go freeze parse heats/H-1 id segment heat vs heat_id',
            ticket='GO-UIDSEG-158',
            lang='Go',
            vs='r784 resource-pattern-heats-to-pours (AIP-122 UID segment rename, not collection heats→pours)',
            avoid='r784 heats→pours / r681 multi-pattern / r696 name field',
            json_name='resourceName',
            debug='debug_uidseg',
            compat='Dual-parse {heat} and {heat_id}',
            grep_pat='heats/\\{heat\\}|heats/\\{heat_id\\}|google.api.resource',
            goal_bit='AIP-122 pattern heats/{heat} → heats/{heat_id} so freeze GAPIC id segment fails',
            dead_desc='json_name resourceName as a pattern substitute',
            dead_old='option (google.api.resource) = { type: "mill.example.com/Heat" pattern: "heats/{heat_id}" }; string name = 10;',
            dead_new='option (google.api.resource) = { type: "mill.example.com/Heat" pattern: "heats/{heat_id}" }; string name = 10 [json_name = "resourceName"];',
            dead_obs='json_name does not restore {heat}; freeze still {heat_id}',
        ),
    ),
    (
        plant(
            slug='any-to-timestamp-event',
            short='a2ts',
            decl_old='google.protobuf.Any event = 23;',
            decl_new='google.protobuf.Timestamp event = 23;',
            syntax='syntax = "proto3";',
            imports=('google/protobuf/any.proto', 'google/protobuf/timestamp.proto'),
            buf_rule='FIELD_TYPE / WIRE',
            wire_old='LEN Any type_url+value',
            wire_new='LEN Timestamp',
            freeze='Python freeze Any vs Timestamp',
            ticket='PY-A2TS-159',
            lang='Python',
            vs='r796 any-to-typed-event / r712 any-to-bytes-event (Any→Timestamp, not Event/bytes/Struct/string)',
            avoid='r712/r724/r740/r796 Any plants / r713 timestamp-to-string',
            json_name='eventAt',
            debug='debug_a2ts',
            compat='Dual-read event as Any or Timestamp',
            grep_pat='protobuf.Any event|protobuf.Timestamp event',
            goal_bit='Any event=23 → Timestamp so freeze type_url/value Any fails',
        ),
        plant(
            slug='required-bool-add',
            short='rqba',
            decl_old='optional bool armed = 12;',
            decl_new='required bool armed = 12;',
            syntax='syntax = "proto2";',
            buf_rule='FIELD_REQUIRED / FILE',
            wire_old='optional armed may omit',
            wire_new='required; freeze omit IsInitialized false',
            freeze='Java freeze omitted armed now required',
            ticket='JAVA-RQBA-160',
            lang='Java',
            vs='r635 proto2-req-lotid-drop / r798 proto2-req-to-proto3-lot (add required on bool, not drop/migrate)',
            avoid='r635 required drop / r798 required→bare / proto2 default leftover',
            json_name='isArmed',
            debug='debug_rqba',
            compat='Accept omitted armed on freeze; required on new writers',
            grep_pat='optional bool armed|required bool armed',
            goal_bit='proto2 optional bool armed=12 → required so freeze omit IsInitialized fails',
            dead_desc='json_name isArmed as a required substitute',
            dead_old='required bool armed = 12;',
            dead_new='required bool armed = 12 [json_name = "isArmed"];',
            dead_obs='json_name does not drop required; freeze omit still fails',
        ),
    ),
    (
        plant(
            slug='backend-deadline-ms',
            short='bddl',
            decl_old='option (google.api.backend) = { rules { selector: "*.Put" deadline: 10.0 } };',
            decl_new='option (google.api.backend) = { rules { selector: "*.Put" deadline: 0.05 } };',
            syntax='syntax = "proto3";',
            imports=('google/api/backend.proto',),
            buf_rule='BACKEND_DEADLINE / FILE',
            wire_old='deadline 10s',
            wire_new='deadline 50ms; freeze long Put DEADLINE_EXCEEDED',
            freeze='Go freeze Put 2s now DEADLINE_EXCEEDED',
            ticket='GO-BDDL-161',
            lang='Go',
            vs='r650 methodopt-51377-timeout / r654 method-settings-retry (backend deadline, not custom option/retry)',
            avoid='r650 timeout option / r654 retry settings / r685 debug-redact',
            json_name='deadlineSec',
            debug='debug_bddl',
            compat='Dual-accept 10s and 50ms backend deadlines',
            grep_pat='deadline: 10.0|deadline: 0.05|google.api.backend',
            goal_bit='backend deadline 10.0s → 0.05s so freeze long Put DEADLINE_EXCEEDED',
        ),
        plant(
            slug='usage-rule-unregistered',
            short='usgr',
            decl_old='option (google.api.usage) = { rules { selector: "*.Put" allow_unregistered_calls: true } };',
            decl_new='option (google.api.usage) = { rules { selector: "*.Put" allow_unregistered_calls: false } };',
            syntax='syntax = "proto3";',
            imports=('google/api/usage.proto',),
            buf_rule='USAGE / FILE',
            wire_old='unregistered Put allowed',
            wire_new='API key required; freeze unregistered 403',
            freeze='TS freeze unregistered Put 403',
            ticket='TS-USGR-162',
            lang='TypeScript',
            vs='r649 api-visibility-internal (usage unregistered, not visibility INTERNAL)',
            avoid='r649 visibility / r671 openapiv2-security / SSG sunset',
            json_name='usageRule',
            debug='debug_usgr',
            compat='Dual-allow registered and unregistered Put',
            grep_pat='allow_unregistered_calls: true|allow_unregistered_calls: false',
            goal_bit='usage allow_unregistered_calls true→false so freeze unregistered Put 403s',
            dead_desc='json_name usageRule as a usage-rule substitute',
            dead_old='option (google.api.usage) = { rules { selector: "*.Put" allow_unregistered_calls: false } };',
            dead_new='option (google.api.usage) = { rules { selector: "*.Put" allow_unregistered_calls: false } }; // json_name leftover',
            dead_obs='comment does not restore unregistered calls; freeze still 403',
        ),
    ),
    (
        plant(
            slug='monitored-resource-type',
            short='mrtype',
            decl_old='option (google.api.monitored_resource_types) = "mill.googleapis.com/Heat";',
            decl_new='option (google.api.monitored_resource_types) = "mill.googleapis.com/Pour";',
            syntax='syntax = "proto3";',
            imports=('google/api/monitored_resource.proto',),
            buf_rule='MONITORED_RESOURCE / FILE',
            wire_old='monitored resource Heat',
            wire_new='Pour; freeze Heat resource type rejected',
            freeze='Go freeze metric resource type mill.googleapis.com/Heat 400',
            ticket='GO-MRTYPE-163',
            lang='Go',
            vs='r642 gapic-resource-type-dross (monitored_resource_types, not GAPIC resource type)',
            avoid='r642 GAPIC type / r784 pattern / openapiv2 cartesian',
            json_name='mrType',
            debug='debug_mrtype',
            compat='Dual-accept Heat and Pour monitored resource types',
            grep_pat='mill.googleapis.com/Heat|mill.googleapis.com/Pour|monitored_resource',
            goal_bit='monitored_resource_types Heat → Pour so freeze Heat metrics 400',
        ),
        plant(
            slug='logging-producer-dest',
            short='logpd',
            decl_old='option (google.api.logging) = { producer_destinations { monitored_resource: "heat" logs: "write" } };',
            decl_new='option (google.api.logging) = { producer_destinations { monitored_resource: "pour" logs: "audit" } };',
            syntax='syntax = "proto3";',
            imports=('google/api/logging.proto',),
            buf_rule='LOGGING / FILE',
            wire_old='producer log heat/write',
            wire_new='pour/audit; freeze write log dest gone',
            freeze='Go freeze producer log heat/write dropped',
            ticket='GO-LOGPD-164',
            lang='Go',
            vs='r685 debug-redact-heat-id (logging dest, not debug_redact)',
            avoid='r685 debug-redact / r42 field-deprecated / SSG sunset',
            json_name='logDest',
            debug='debug_logpd',
            compat='Dual-route heat/write and pour/audit producer logs',
            grep_pat='monitored_resource: \\"heat\\"|monitored_resource: \\"pour\\"|google.api.logging',
            goal_bit='logging producer dest heat/write → pour/audit so freeze write logs drop',
            dead_desc='json_name logDest as a logging-dest substitute',
            dead_old='option (google.api.logging) = { producer_destinations { monitored_resource: "pour" logs: "audit" } };',
            dead_new='option (google.api.logging) = { producer_destinations { monitored_resource: "pour" logs: "audit" } }; // json_name leftover',
            dead_obs='comment does not restore heat/write; freeze still pour/audit',
        ),
    ),
    (
        plant(
            slug='context-rule-drop',
            short='ctxr',
            decl_old='option (google.api.context) = { rules { selector: "*.Put" requested { "google.rpc.context.AttributeContext.Request" } } };',
            decl_new='option (google.api.context) = { rules { selector: "*.Put" } };',
            syntax='syntax = "proto3";',
            imports=('google/api/context.proto',),
            buf_rule='CONTEXT / FILE',
            wire_old='AttributeContext.Request requested',
            wire_new='requested dropped; freeze context header ignored',
            freeze='Go freeze x-goog-request-context dropped',
            ticket='GO-CTXR-165',
            lang='Go',
            vs='r786 routing-header-heat-to-pour (context requested, not routing header)',
            avoid='r786 routing header / r649 path var / r74 api-routing',
            json_name='ctxReq',
            debug='debug_ctxr',
            compat='Dual-accept AttributeContext.Request leftover',
            grep_pat='AttributeContext.Request|google.api.context',
            goal_bit='context requested AttributeContext.Request dropped so freeze context header is ignored',
        ),
        plant(
            slug='system-param-header',
            short='sysph',
            decl_old='option (google.api.system_parameters) = { rules { selector: "*" parameters { name: "api_key" http_header: "x-api-key" } } };',
            decl_new='option (google.api.system_parameters) = { rules { selector: "*" parameters { name: "api_key" http_header: "x-mill-key" } } };',
            syntax='syntax = "proto3";',
            imports=('google/api/system_parameter.proto',),
            buf_rule='SYSTEM_PARAM / FILE',
            wire_old='x-api-key header',
            wire_new='x-mill-key; freeze x-api-key ignored',
            freeze='TS freeze x-api-key 401',
            ticket='TS-SYSPH-166',
            lang='TypeScript',
            vs='r671 openapiv2-security-rename (system_parameters header, not OpenAPI security)',
            avoid='r671 openapiv2 security / openapiv2 consumes/produces BAN / SSG sunset',
            json_name='apiKey',
            debug='debug_sysph',
            compat='Dual-accept x-api-key and x-mill-key',
            grep_pat='x-api-key|x-mill-key|system_parameters',
            goal_bit='system_parameters api_key header x-api-key → x-mill-key so freeze x-api-key 401s',
            dead_desc='json_name apiKey as a header substitute',
            dead_old='option (google.api.system_parameters) = { rules { selector: "*" parameters { name: "api_key" http_header: "x-mill-key" } } };',
            dead_new='option (google.api.system_parameters) = { rules { selector: "*" parameters { name: "api_key" http_header: "x-mill-key" url_query_parameter: "key" } } };',
            dead_obs='query key does not restore x-api-key; freeze still 401',
        ),
    ),
    (
        plant(
            slug='endpoint-target-rename',
            short='eptr',
            decl_old='option (google.api.endpoint) = { name: "mill.googleapis.com" target: "mill.example.net:443" };',
            decl_new='option (google.api.endpoint) = { name: "pour.googleapis.com" target: "pour.example.net:443" };',
            syntax='syntax = "proto3";',
            imports=('google/api/endpoint.proto',),
            buf_rule='ENDPOINT / FILE',
            wire_old='mill.googleapis.com',
            wire_new='pour.googleapis.com; freeze mill host 404',
            freeze='Go freeze mill.googleapis.com DNS/host fail',
            ticket='GO-EPTR-167',
            lang='Go',
            vs='default-host-rename (endpoint name+target, not default_host only)',
            avoid='default-host-rename / SSG sunset / r665 v1-to-v2 path',
            json_name='apiHost',
            debug='debug_eptr',
            compat='Dual-route mill.googleapis.com and pour.googleapis.com',
            grep_pat='mill.googleapis.com|pour.googleapis.com|google.api.endpoint',
            goal_bit='endpoint mill.googleapis.com → pour.googleapis.com so freeze mill host fails',
        ),
        plant(
            slug='quota-metric-rename',
            short='qmet',
            decl_old='option (google.api.quota) = { metric_rules { selector: "*" metric_costs { key: "heats.write" value: 1 } } };',
            decl_new='option (google.api.quota) = { metric_rules { selector: "*" metric_costs { key: "pours.write" value: 1 } } };',
            syntax='syntax = "proto3";',
            imports=('google/api/quota.proto',),
            buf_rule='QUOTA / FILE',
            wire_old='quota metric heats.write',
            wire_new='pours.write; freeze heats.write unknown',
            freeze='Go freeze quota metric heats.write 400',
            ticket='GO-QMET-168',
            lang='Go',
            vs='r650 methodopt timeout (quota metric, not timeout option)',
            avoid='r650 timeout / openapiv2 cartesian / SSG sunset',
            json_name='quotaMetric',
            debug='debug_qmet',
            compat='Dual-bill heats.write and pours.write',
            grep_pat='heats.write|pours.write|google.api.quota',
            goal_bit='quota metric heats.write → pours.write so freeze heats.write 400s',
            dead_desc='json_name quotaMetric as a metric substitute',
            dead_old='option (google.api.quota) = { metric_rules { selector: "*" metric_costs { key: "pours.write" value: 1 } } };',
            dead_new='option (google.api.quota) = { metric_rules { selector: "*" metric_costs { key: "pours.write" value: 1 } } }; // json_name leftover',
            dead_obs='comment does not restore heats.write; freeze still pours.write',
        ),
    ),
    (
        plant(
            slug='documentation-rule-drop',
            short='docr',
            decl_old='option (google.api.documentation) = { rules { selector: "*.Put" description: "Put a heat." } };',
            decl_new='option (google.api.documentation) = { summary: "Mill API" };',
            syntax='syntax = "proto3";',
            imports=('google/api/documentation.proto',),
            buf_rule='DOCUMENTATION / FILE',
            wire_old='Put description rule',
            wire_new='rule dropped; freeze GAPIC comment gone',
            freeze='Java freeze javadoc Put a heat missing',
            ticket='JAVA-DOCR-169',
            lang='Java',
            vs='r698 file-option-deprecated (documentation rule drop, not deprecated)',
            avoid='r698 deprecated / r54 rpc-deprecated / SSG sunset',
            json_name='docRule',
            debug='debug_docr',
            compat='Keep Put description rule for freeze docs',
            grep_pat='Put a heat|google.api.documentation',
            goal_bit='documentation rules Put description dropped so freeze GAPIC javadoc missing',
        ),
        plant(
            slug='authentication-jwt-aud',
            short='jwaud',
            decl_old='option (google.api.auth) = { rules { selector: "*" requirements { provider_id: "mill_jwt" audiences: "https://mill.example.com" } } };',
            decl_new='option (google.api.auth) = { rules { selector: "*" requirements { provider_id: "pour_jwt" audiences: "https://pour.example.com" } } };',
            syntax='syntax = "proto3";',
            imports=('google/api/auth.proto',),
            buf_rule='AUTH / FILE',
            wire_old='aud https://mill.example.com',
            wire_new='aud https://pour.example.com; freeze mill JWT 401',
            freeze='Go freeze mill JWT aud 401',
            ticket='GO-JWAUD-170',
            lang='Go',
            vs='r671 openapiv2-security-rename (auth JWT aud, not OpenAPI security name)',
            avoid='r671 openapiv2 security / openapiv2 consumes BAN / SSG sunset',
            json_name='jwtAud',
            debug='debug_jwaud',
            compat='Dual-accept mill and pour JWT audiences',
            grep_pat='mill.example.com|pour.example.com|google.api.auth',
            goal_bit='auth JWT audience mill.example.com → pour.example.com so freeze mill JWT 401s',
            dead_desc='json_name jwtAud as an audience substitute',
            dead_old='option (google.api.auth) = { rules { selector: "*" requirements { provider_id: "pour_jwt" audiences: "https://pour.example.com" } } };',
            dead_new='option (google.api.auth) = { rules { selector: "*" requirements { provider_id: "pour_jwt" audiences: "https://pour.example.com" } } }; // json_name leftover',
            dead_obs='comment does not restore mill aud; freeze still pour JWT',
        ),
    ),
    (
        plant(
            slug='billing-dest-drop',
            short='billd',
            decl_old='option (google.api.billing) = { consumer_destinations { monitored_resource: "heat" metrics: "heats.write" } };',
            decl_new='option (google.api.billing) = {};',
            syntax='syntax = "proto3";',
            imports=('google/api/billing.proto',),
            buf_rule='BILLING / FILE',
            wire_old='consumer dest heat/heats.write',
            wire_new='billing dest dropped; freeze billable metrics gone',
            freeze='Go freeze billing dest heat missing',
            ticket='GO-BILLD-171',
            lang='Go',
            vs='quota-metric-rename mill (billing dest drop, not quota metric rename)',
            avoid='openapiv2 cartesian / SSG sunset / r685 debug-redact',
            json_name='billDest',
            debug='debug_billd',
            compat='Keep consumer billing dest for freeze',
            grep_pat='google.api.billing|heats.write|consumer_destinations',
            goal_bit='billing consumer_destinations dropped so freeze billable heats.write gone',
        ),
        plant(
            slug='control-env-rename',
            short='cenv',
            decl_old='option (google.api.control) = { environment: "servicecontrol.googleapis.com" };',
            decl_new='option (google.api.control) = { environment: "pourcontrol.googleapis.com" };',
            syntax='syntax = "proto3";',
            imports=('google/api/control.proto',),
            buf_rule='CONTROL / FILE',
            wire_old='servicecontrol.googleapis.com',
            wire_new='pourcontrol; freeze servicecontrol 404',
            freeze='Go freeze servicecontrol.googleapis.com 404',
            ticket='GO-CENV-172',
            lang='Go',
            vs='endpoint-target-rename mill (control environment, not API endpoint)',
            avoid='endpoint mill / default-host-rename / SSG sunset',
            json_name='ctrlEnv',
            debug='debug_cenv',
            compat='Dual-route servicecontrol and pourcontrol',
            grep_pat='servicecontrol.googleapis.com|pourcontrol.googleapis.com|google.api.control',
            goal_bit='control environment servicecontrol → pourcontrol so freeze servicecontrol 404s',
            dead_desc='json_name ctrlEnv as an environment substitute',
            dead_old='option (google.api.control) = { environment: "pourcontrol.googleapis.com" };',
            dead_new='option (google.api.control) = { environment: "pourcontrol.googleapis.com" }; // json_name leftover',
            dead_obs='comment does not restore servicecontrol; freeze still pourcontrol',
        ),
    ),
    (
        plant(
            slug='child-type-heats-to-pours',
            short='chld',
            decl_old='string parent = 24 [(google.api.resource_reference) = { child_type: "mill.example.com/Heat" }];',
            decl_new='string parent = 24 [(google.api.resource_reference) = { child_type: "mill.example.com/Pour" }];',
            syntax='syntax = "proto3";',
            imports=('google/api/resource.proto',),
            buf_rule='RESOURCE_REFERENCE / FILE',
            wire_old='child_type Heat',
            wire_new='child_type Pour; freeze Heat child parse',
            freeze='Go freeze parent child_type Heat vs Pour',
            ticket='GO-CHLD-173',
            lang='Go',
            vs='r660 resource-ref-child-type (Heat→Pour child_type, not a first child_type plant)',
            avoid='r660 child_type add / r642 resource type / r784 pattern',
            json_name='parentName',
            debug='debug_chld',
            compat='Dual-accept Heat and Pour child_type',
            grep_pat='child_type: \\"mill.example.com/Heat\\"|child_type: \\"mill.example.com/Pour\\"',
            goal_bit='resource_reference child_type Heat → Pour so freeze Heat child parse fails',
        ),
        plant(
            slug='rpc-run-deleted',
            short='rund',
            decl_old='rpc Run(RunHeat) returns (google.longrunning.Operation) { option (google.api.http) = { post: "/v1/{name=heats/*}:run" body: "*" }; option (google.longrunning.operation_info) = { response_type: "Heat" metadata_type: "RunMeta" }; }',
            decl_new='// rpc Run deleted',
            syntax='syntax = "proto3";',
            imports=('google/api/annotations.proto', 'google/longrunning/operations.proto'),
            extra_msgs='message RunHeat { string name = 1; }\nmessage RunMeta { int32 pct = 1; }\n',
            buf_rule='RPC_DELETED / HTTP',
            wire_old='POST :run LRO',
            wire_new='rpc Run gone',
            freeze='TS freeze POST :run 404',
            ticket='TS-RUND-174',
            lang='TypeScript',
            vs='r765 rpc-get-deleted / r801 rpc-watch-deleted (AIP-364 Run, not Get/Watch)',
            avoid='r765 Get / r801 Watch / r676 unary-to-lro',
            json_name='runName',
            debug='debug_rund',
            compat='Dual-route :run leftover for freeze',
            grep_pat='rpc Run|:run|RunHeat',
            goal_bit='AIP-364 rpc Run deleted so freeze :run 404s',
            dead_desc='rename Run→Execute as a delete substitute',
            dead_old='// rpc Run deleted',
            dead_new='rpc Execute(RunHeat) returns (google.longrunning.Operation) { option (google.api.http) = { post: "/v1/{name=heats/*}:execute" }; }',
            dead_obs='Execute does not restore Run; freeze still 404',
        ),
    ),
)
