#!/usr/bin/env python3
"""AST-extracted plant pairs for pbc_r966 (legacy-mill-lane pbc-mill-r966.py)."""

from __future__ import annotations

from .record_builder import plant

MILL_ID = 'pbc_r966'
CATALOG_FIRST = 966
START = 966
N_ROUNDS = 8
NOTES_EXTRA = ''
NOTES_FOOTER = ''

PAIRS: tuple[tuple[dict, dict], ...] = (
    (
        plant(
            slug='timestamp-to-unix-seconds',
            short='tsux',
            decl_old='google.protobuf.Timestamp poured_at = 8;',
            decl_new='int64 poured_unix = 8;',
            syntax='syntax = "proto3";',
            imports=('google/protobuf/timestamp.proto',),
            extra_msgs='',
            buf_rule='FIELD_TYPE / WIRE',
            wire_old='LEN Timestamp seconds+nanos',
            wire_new='VARINT unix seconds',
            freeze='Go freeze timestamppb.Timestamp vs int64',
            ticket='GO-TSUX-966',
            lang='Go',
            vs='r964 precondfail-to-string / r701 float-to-double (Timestamp message → unix seconds, not rpc.Status)',
            avoid='r964/r965 google.rpc *→string / r701 float width',
            json_name='pouredAt',
            debug='debug_tsux',
            compat='Dual-read poured_at Timestamp or poured_unix int64',
            grep_pat='Timestamp poured_at|int64 poured_unix',
            goal_bit='Timestamp poured_at=8 → int64 poured_unix so freeze LEN Timestamp fails',
            dead_desc='json_name pouredAt as a type substitute',
            dead_old='int64 poured_unix = 8;',
            dead_new='int64 poured_unix = 8 [json_name = "pouredAt"];',
            dead_obs='json_name does not restore Timestamp; freeze still VARINT',
        ),
        plant(
            slug='duration-to-nanos-int64',
            short='durn',
            decl_old='google.protobuf.Duration dwell = 9;',
            decl_new='int64 dwell_nanos = 9;',
            syntax='syntax = "proto3";',
            imports=('google/protobuf/duration.proto',),
            buf_rule='FIELD_TYPE / WIRE',
            wire_old='LEN Duration seconds+nanos',
            wire_new='VARINT nanos',
            freeze='Python freeze timedelta vs int64 nanos',
            ticket='PY-DURN-967',
            lang='Python',
            vs='r966 timestamp-to-unix-seconds (Duration, not Timestamp)',
            avoid='r966 Timestamp / r701 float-to-double',
            json_name='dwellTime',
            debug='debug_durn',
            compat='Dual-read Duration or nanos int64',
            grep_pat='Duration dwell|int64 dwell_nanos',
            goal_bit='Duration dwell=9 → int64 dwell_nanos so freeze LEN Duration fails',
            dead_desc='json_name dwellTime as a type substitute',
            dead_old='int64 dwell_nanos = 9;',
            dead_new='int64 dwell_nanos = 9 [json_name = "dwellTime"];',
            dead_obs='json_name does not restore Duration; freeze still VARINT',
        ),
    ),
    (
        plant(
            slug='any-to-struct-payload',
            short='any2s',
            decl_old='google.protobuf.Any detail = 10;',
            decl_new='google.protobuf.Struct detail = 10;',
            syntax='syntax = "proto3";',
            imports=('google/protobuf/any.proto', 'google/protobuf/struct.proto'),
            buf_rule='FIELD_TYPE / WIRE',
            wire_old='LEN Any type_url+value',
            wire_new='LEN Struct fields map',
            freeze='Java freeze Any.pack vs Struct fields',
            ticket='JAVA-ANY2S-968',
            lang='Java',
            vs='r965 localizedmsg-to-string (Any→Struct, not rpc.LocalizedMessage→string)',
            avoid='r965 LocalizedMessage / r964 PreconditionFailure',
            json_name='detailAny',
            debug='debug_any2s',
            compat='Dual-read Any or Struct',
            grep_pat='protobuf.Any detail|protobuf.Struct detail',
            goal_bit='Any detail=10 → Struct so freeze type_url pack fails',
            dead_desc='json_name detailAny as a type substitute',
            dead_old='google.protobuf.Struct detail = 10;',
            dead_new='google.protobuf.Struct detail = 10 [json_name = "detailAny"];',
            dead_obs='json_name does not restore Any type_url; freeze still Struct',
        ),
        plant(
            slug='struct-to-string-json',
            short='st2s',
            decl_old='google.protobuf.Struct attrs = 11;',
            decl_new='string attrs_json = 11;',
            syntax='syntax = "proto3";',
            imports=('google/protobuf/struct.proto',),
            buf_rule='FIELD_TYPE / WIRE',
            wire_old='LEN Struct fields',
            wire_new='LEN utf8 json',
            freeze='Go freeze structpb.Struct vs string JSON',
            ticket='GO-ST2S-969',
            lang='Go',
            vs='r968 any-to-struct (Struct→string, not Any→Struct)',
            avoid='r968 Any / r965 LocalizedMessage→string',
            json_name='attrs',
            debug='debug_st2s',
            compat='Dual-read Struct or JSON string',
            grep_pat='Struct attrs|string attrs_json',
            goal_bit='Struct attrs=11 → string attrs_json so freeze Struct fields fail',
            dead_desc='json_name attrs as a type substitute',
            dead_old='string attrs_json = 11;',
            dead_new='string attrs_json = 11 [json_name = "attrs"];',
            dead_obs='json_name does not restore Struct; freeze still LEN utf8',
        ),
    ),
    (
        plant(
            slug='fieldmask-to-paths',
            short='fmp',
            decl_old='google.protobuf.FieldMask update_mask = 12;',
            decl_new='repeated string update_paths = 12;',
            syntax='syntax = "proto3";',
            imports=('google/protobuf/field_mask.proto',),
            buf_rule='FIELD_TYPE / WIRE',
            wire_old='LEN FieldMask paths[]',
            wire_new='LEN packed strings',
            freeze='TS freeze FieldMask vs string[]',
            ticket='TS-FMP-970',
            lang='TypeScript',
            vs='r803 aip157-view-to-string (FieldMask→paths, not View enum)',
            avoid='r803 View / r722 grade enum-to-string',
            json_name='updateMask',
            debug='debug_fmp',
            compat='Dual-read FieldMask or repeated string',
            grep_pat='FieldMask update_mask|repeated string update_paths',
            goal_bit='FieldMask update_mask=12 → repeated string so freeze FieldMask paths fail',
            dead_desc='json_name updateMask as a type substitute',
            dead_old='repeated string update_paths = 12;',
            dead_new='repeated string update_paths = 12 [json_name = "updateMask"];',
            dead_obs='json_name does not restore FieldMask; freeze still repeated string',
        ),
        plant(
            slug='empty-to-bool-ok',
            short='e2b',
            decl_old='google.protobuf.Empty ack = 13;',
            decl_new='bool ack = 13;',
            syntax='syntax = "proto3";',
            imports=('google/protobuf/empty.proto',),
            buf_rule='FIELD_TYPE / WIRE',
            wire_old='LEN Empty {}',
            wire_new='VARINT bool',
            freeze='Go freeze emptypb.Empty vs bool',
            ticket='GO-E2B-971',
            lang='Go',
            vs='r765 rpc-get-deleted (Empty field type, not RPC delete)',
            avoid='r765 Get deleted / r964 Status wrappers',
            json_name='acked',
            debug='debug_e2b',
            compat='Dual-read Empty or bool',
            grep_pat='Empty ack|bool ack = 13',
            goal_bit='Empty ack=13 → bool so freeze LEN Empty fails',
            dead_desc='json_name acked as a type substitute',
            dead_old='bool ack = 13;',
            dead_new='bool ack = 13 [json_name = "acked"];',
            dead_obs='json_name does not restore Empty; freeze still VARINT',
        ),
    ),
    (
        plant(
            slug='bytes-to-hex-string',
            short='bhex',
            decl_old='bytes digest = 14;',
            decl_new='string digest_hex = 14;',
            syntax='syntax = "proto3";',
            buf_rule='FIELD_TYPE / WIRE',
            wire_old='LEN raw bytes',
            wire_new='LEN utf8 hex',
            freeze='Python freeze bytes vs hex str',
            ticket='PY-BHEX-972',
            lang='Python',
            vs='r629 optional-bytes-drop (type change bytes→hex string, not optional drop)',
            avoid='optional-bytes-drop / r965 string wrappers',
            json_name='digest',
            debug='debug_bhex',
            compat='Dual-read raw bytes or hex string',
            grep_pat='bytes digest|string digest_hex',
            goal_bit='bytes digest=14 → string digest_hex so freeze raw LEN bytes fail',
            dead_desc='json_name digest as a type substitute',
            dead_old='string digest_hex = 14;',
            dead_new='string digest_hex = 14 [json_name = "digest"];',
            dead_obs='json_name does not restore bytes; freeze still hex utf8',
        ),
        plant(
            slug='sint32-to-int32-count',
            short='s32i',
            decl_old='sint32 delta = 15;',
            decl_new='int32 delta = 15;',
            syntax='syntax = "proto3";',
            buf_rule='FIELD_TYPE / WIRE',
            wire_old='VARINT zigzag',
            wire_new="VARINT two's complement",
            freeze='Go freeze protowire.DecodeZigZag vs int32',
            ticket='GO-S32I-973',
            lang='Go',
            vs='r691 map-key-i32-to-i64 (sint32 zigzag→int32, not map key width)',
            avoid='r691/r700 map-key / r701 float width',
            json_name='deltaN',
            debug='debug_s32i',
            compat='Dual-read zigzag or int32',
            grep_pat='sint32 delta|int32 delta = 15',
            goal_bit='sint32 delta=15 → int32 so freeze zigzag decode fails',
            dead_desc='json_name deltaN as a type substitute',
            dead_old='int32 delta = 15;',
            dead_new='int32 delta = 15 [json_name = "deltaN"];',
            dead_obs='json_name does not restore zigzag; freeze still int32',
        ),
    ),
    (
        plant(
            slug='http-undelete-parent-path',
            short='undp',
            decl_old='rpc Undelete(UndeleteHeat) returns (Heat) { option (google.api.http) = { post: "/v1/{name=heats/*}:undelete" body: "*" }; }',
            decl_new='rpc Undelete(UndeleteHeat) returns (Heat) { option (google.api.http) = { post: "/v1/{parent=mills/*}/heats:undelete" body: "*" }; }',
            syntax='syntax = "proto3";',
            imports=('google/api/annotations.proto',),
            extra_msgs='message UndeleteHeat { string name = 1; string parent = 2; }\n',
            buf_rule='HTTP_PATH / FILE',
            wire_old='POST /v1/heats/{heat}:undelete',
            wire_new='POST /v1/mills/{mill}/heats:undelete',
            freeze='TS freeze POST /v1/heats/H-1:undelete 404',
            ticket='TS-UNDP-974',
            lang='TypeScript',
            vs='r803 http-copy-parent-path (AIP-164 :undelete, not :copy/:merge)',
            avoid='r803 :copy / r804 :merge / pause/resume/archive',
            json_name='undeleteName',
            debug='debug_undp',
            compat='Dual-route heats/:undelete and mills/.../heats:undelete',
            grep_pat='heats/\\*:undelete|mills/\\*/heats:undelete|rpc Undelete',
            goal_bit='AIP-164 :undelete path → mills/{mill}/heats:undelete so freeze :undelete 404s',
            dead_desc='additional_bindings v2 undelete leaving v1 heats/:undelete off',
            dead_old='rpc Undelete(UndeleteHeat) returns (Heat) { option (google.api.http) = { post: "/v1/{parent=mills/*}/heats:undelete" body: "*" }; }',
            dead_new='rpc Undelete(UndeleteHeat) returns (Heat) { option (google.api.http) = { post: "/v1/{parent=mills/*}/heats:undelete" body: "*" additional_bindings { post: "/v2/{name=heats/*}:undelete" } }; }',
            dead_obs='v2 :undelete does not restore /v1/heats/{name}:undelete; freeze still 404',
        ),
        plant(
            slug='rpc-batchcreate-deleted',
            short='bcrd',
            decl_old='rpc BatchCreate(BatchCreateHeats) returns (BatchCreateHeatsResponse);',
            decl_new='// rpc BatchCreate deleted',
            syntax='syntax = "proto3";',
            extra_msgs='message BatchCreateHeats { repeated Heat heats = 1; }\nmessage BatchCreateHeatsResponse { repeated Heat heats = 1; }\n',
            buf_rule='RPC_DELETED / FILE',
            wire_old='/S/BatchCreate unary',
            wire_new='rpc BatchCreate gone',
            freeze='Go freeze /bcrd.v1.S/BatchCreate UNIMPLEMENTED',
            ticket='GO-BCRD-975',
            lang='Go',
            vs='r792 rpc-create-deleted (BatchCreate, not Create/Get/Update/Put)',
            avoid='r765 Get / r792 Create / r793 Update / r803 Put',
            json_name='batchHeats',
            debug='debug_bcrd',
            compat='Dual-route BatchCreate leftover for freeze',
            grep_pat='rpc BatchCreate|// rpc BatchCreate deleted',
            goal_bit='rpc BatchCreate deleted so freeze /S/BatchCreate UNIMPLEMENTED',
            dead_desc='rename BatchCreate→BulkInsert as a delete substitute',
            dead_old='// rpc BatchCreate deleted',
            dead_new='rpc BulkInsert(BatchCreateHeats) returns (BatchCreateHeatsResponse);',
            dead_obs='BulkInsert does not restore BatchCreate; freeze still UNIMPLEMENTED',
        ),
    ),
    (
        plant(
            slug='http-purge-custom-verb',
            short='purg',
            decl_old='rpc Purge(PurgeHeat) returns (Heat) { option (google.api.http) = { post: "/v1/{name=heats/*}:purge" body: "*" }; }',
            decl_new='rpc Purge(PurgeHeat) returns (Heat) { option (google.api.http) = { post: "/v1/{name=heats/*}:expunge" body: "*" }; }',
            syntax='syntax = "proto3";',
            imports=('google/api/annotations.proto',),
            extra_msgs='message PurgeHeat { string name = 1; bool force = 2; }\n',
            buf_rule='HTTP_PATH / FILE',
            wire_old='POST :purge',
            wire_new='POST :expunge',
            freeze='Java freeze POST :purge 404',
            ticket='JAVA-PURG-976',
            lang='Java',
            vs='r803 pause/resume/archive ban (AIP-custom :purge→:expunge, not pause/resume/archive)',
            avoid='pause/resume/archive cartesian / r803 :copy/:merge',
            json_name='purgeForce',
            debug='debug_purg',
            compat='Dual-route :purge and :expunge',
            grep_pat=':purge|:expunge|rpc Purge',
            goal_bit=':purge → :expunge so freeze :purge 404s',
            dead_desc='additional_bindings :flush leaving :purge off',
            dead_old='rpc Purge(PurgeHeat) returns (Heat) { option (google.api.http) = { post: "/v1/{name=heats/*}:expunge" body: "*" }; }',
            dead_new='rpc Purge(PurgeHeat) returns (Heat) { option (google.api.http) = { post: "/v1/{name=heats/*}:expunge" body: "*" additional_bindings { post: "/v1/{name=heats/*}:flush" } }; }',
            dead_obs=':flush does not restore :purge; freeze still 404',
        ),
        plant(
            slug='routing-header-sku-to-lot',
            short='rskl',
            decl_old='rpc Get(GetHeat) returns (Heat) { option (google.api.routing) = { routing_parameters { field: "sku" path_template: "{sku=**}" } }; }',
            decl_new='rpc Get(GetHeat) returns (Heat) { option (google.api.routing) = { routing_parameters { field: "lot" path_template: "{lot=**}" } }; }',
            syntax='syntax = "proto3";',
            imports=('google/api/routing.proto',),
            extra_msgs='message GetHeat { string name = 1; string sku = 2; string lot = 3; }\n',
            buf_rule='ROUTING / FILE',
            wire_old='x-goog-request-params sku=',
            wire_new='x-goog-request-params lot=',
            freeze='Go freeze routing header sku= vs lot=',
            ticket='GO-RSKL-977',
            lang='Go',
            vs='r786 routing-header-heat-to-pour (sku→lot, not heat→pour)',
            avoid='r786 heat-to-pour / r803 HTTP path copy',
            json_name='skuKey',
            debug='debug_rskl',
            compat='Dual-read sku and lot routing params',
            grep_pat='field: \\"sku\\"|field: \\"lot\\"',
            goal_bit='routing field sku → lot so freeze x-goog-request-params sku= fails',
            dead_desc='json_name skuKey as a routing substitute',
            dead_old='routing_parameters { field: "lot" path_template: "{lot=**}" }',
            dead_new='routing_parameters { field: "lot" path_template: "{lot=**}" } // json_name sku',
            dead_obs='comment does not restore sku routing; freeze still lot=',
        ),
    ),
    (
        plant(
            slug='client-stream-to-unary-ingest',
            short='cs2u',
            decl_old='rpc Ingest(stream Heat) returns (Heat);',
            decl_new='rpc Ingest(Heat) returns (Heat);',
            syntax='syntax = "proto3";',
            buf_rule='RPC_STREAMING / WIRE',
            wire_old='client-stream frames',
            wire_new='unary single Heat',
            freeze='TS freeze client-stream Ingest vs unary',
            ticket='TS-CS2U-978',
            lang='TypeScript',
            vs='r676 unary-to-lro (client-stream→unary, not unary→LRO)',
            avoid='r676 LRO / r801 Watch stream delete',
            json_name='ingestBatch',
            debug='debug_cs2u',
            compat='Dual-accept stream or unary Ingest',
            grep_pat='rpc Ingest\\(stream Heat\\)|rpc Ingest\\(Heat\\)',
            goal_bit='rpc Ingest(stream Heat) → unary so freeze client-stream frames fail',
            dead_desc='server-stream leftover as a client-stream substitute',
            dead_old='rpc Ingest(Heat) returns (Heat);',
            dead_new='rpc Ingest(Heat) returns (stream Heat);',
            dead_obs='server-stream does not restore client-stream; freeze still unary request',
        ),
        plant(
            slug='edition2023-utf8-validate',
            short='u8v',
            decl_old='string note = 16;',
            decl_new='string note = 16 [features.(pb.cpp).string_type = VIEW];',
            syntax='edition = "2023";',
            file_opts='option features.utf8_validation = VERIFY;\n',
            buf_rule='EDITION_FEATURE / FILE',
            wire_old='LEN utf8 unchecked',
            wire_new='LEN utf8 VERIFY + C++ VIEW',
            freeze='C++ freeze string vs absl::string_view utf8 VERIFY',
            ticket='CC-U8V-979',
            lang='C++',
            vs='r635 edition-2023 required feature (utf8_validation VERIFY, not required fields)',
            avoid='r635 edition required feature / r44 explicit presence',
            json_name='noteText',
            debug='debug_u8v',
            compat='Dual-accept unchecked or VERIFY utf8',
            grep_pat='utf8_validation|string_type = VIEW|string note',
            goal_bit='edition 2023 utf8_validation VERIFY + string VIEW so freeze raw bytes fail',
            dead_desc='json_name noteText as a feature substitute',
            dead_old='string note = 16 [features.(pb.cpp).string_type = VIEW];',
            dead_new='string note = 16 [features.(pb.cpp).string_type = VIEW, json_name = "noteText"];',
            dead_obs='json_name does not disable VERIFY; freeze still rejects non-utf8',
        ),
    ),
    (
        plant(
            slug='resource-singular-heat-to-ingot',
            short='rsng',
            decl_old='option (google.api.resource) = { type: "mill.example.com/Heat" pattern: "heats/{heat}" singular: "heat" plural: "heats" };',
            decl_new='option (google.api.resource) = { type: "mill.example.com/Ingot" pattern: "ingots/{ingot}" singular: "ingot" plural: "ingots" };',
            syntax='syntax = "proto3";',
            imports=('google/api/resource.proto',),
            buf_rule='RESOURCE / FILE',
            wire_old='resource heat/heats',
            wire_new='resource ingot/ingots',
            freeze='Go freeze heats/{heat} vs ingots/{ingot}',
            ticket='GO-RSNG-980',
            lang='Go',
            vs='r784 resource pattern / r642 resource type (singular+plural heat→ingot, not child_type)',
            avoid='r660 child_type / r784 pattern-only / r642 type-only',
            json_name='heatName',
            debug='debug_rsng',
            compat='Dual-accept heats/ and ingots/ resource names',
            grep_pat='singular: \\"heat\\"|singular: \\"ingot\\"|ingots/',
            goal_bit='resource singular heat → ingot so freeze heats/{heat} parse fails',
            dead_desc='pattern alias heats without singular change',
            dead_old='option (google.api.resource) = { type: "mill.example.com/Ingot" pattern: "ingots/{ingot}" singular: "ingot" plural: "ingots" };',
            dead_new='option (google.api.resource) = { type: "mill.example.com/Ingot" pattern: "ingots/{ingot}" pattern: "heats/{heat}" singular: "ingot" plural: "ingots" };',
            dead_obs='extra pattern does not restore singular heat; freeze still Ingot',
        ),
        plant(
            slug='httpbody-to-bytes-blob',
            short='h2b',
            decl_old='google.api.HttpBody blob = 17;',
            decl_new='bytes blob = 17;',
            syntax='syntax = "proto3";',
            imports=('google/api/httpbody.proto',),
            buf_rule='FIELD_TYPE / WIRE',
            wire_old='LEN HttpBody content_type+data',
            wire_new='LEN raw bytes',
            freeze='Java freeze HttpBody vs bytes',
            ticket='JAVA-H2B-981',
            lang='Java',
            vs='r972 bytes-to-hex-string (HttpBody→bytes, not bytes→hex)',
            avoid='r972 hex string / r968 Any',
            json_name='blobBody',
            debug='debug_h2b',
            compat='Dual-read HttpBody or raw bytes',
            grep_pat='HttpBody blob|bytes blob = 17',
            goal_bit='HttpBody blob=17 → bytes so freeze content_type+data fails',
            dead_desc='json_name blobBody as a type substitute',
            dead_old='bytes blob = 17;',
            dead_new='bytes blob = 17 [json_name = "blobBody"];',
            dead_obs='json_name does not restore HttpBody; freeze still raw bytes',
        ),
    ),
)
