#!/usr/bin/env python3
"""AST-extracted plant pairs for pbc_r731 (legacy-mill-lane pbc-mill-r731.py)."""

from __future__ import annotations

from .record_builder import plant

MILL_ID = 'pbc_r731'
CATALOG_FIRST = 731
START = 731
N_ROUNDS = 20
NOTES_EXTRA = ''
NOTES_FOOTER = ''

PAIRS: tuple[tuple[dict, dict], ...] = (
    (
        plant(
            slug='map-key-fixed64-to-uint64',
            short='f64k',
            decl_old='map<fixed64, string> bins = 3;',
            decl_new='map<uint64, string> bins = 3;',
            syntax='syntax = "proto3";',
            buf_rule='MAP_KEY_TYPE / WIRE',
            wire_old='FIXED64 key 0x09',
            wire_new='VARINT key 0x08',
            freeze='Go freeze map[uint64]string still encodes fixed64 key',
            ticket='GO-F64KEY-33',
            lang='Go',
            vs='r704 map-key-uint64-to-fixed64 (opposite direction)',
            avoid='r700/r704/r715/r691 map-key plants',
            json_name='binMap',
            debug='debug_f64k',
            compat='Dual-read map key as fixed64 or uint64 varint',
            grep_pat='map<fixed64|map<uint64|bins',
            goal_bit='map<fixed64,string>→map<uint64,string> bins=3 so freeze FIXED64 keys fail',
        ),
        plant(
            slug='wrappers-int32-to-scalar',
            short='wi32',
            decl_old='google.protobuf.Int32Value tap = 52;',
            decl_new='int32 tap = 52;',
            syntax='syntax = "proto3";',
            imports=('google/protobuf/wrappers.proto',),
            buf_rule='FIELD_TYPE / WIRE',
            wire_old='LEN wrapper 0xa2 0x03',
            wire_new='VARINT 0xa0 0x03',
            freeze='Java freeze Int32Value vs int',
            ticket='JAVA-WI32-34',
            lang='Java',
            vs='r706 wrappers-int64-to-scalar (Int32Value, not Int64Value)',
            avoid='r706/r704/r714 wrapper unwraps',
            json_name='tapN',
            debug='debug_wi32',
            compat='Dual-read tap as Int32Value or raw int32',
            grep_pat='Int32Value tap|int32 tap',
            goal_bit='Int32Value tap=52 → int32 so freeze wrapper LEN fails',
            dead_desc='json_name tapN as a wrapper-unwrap substitute',
            dead_old='int32 tap = 52;',
            dead_new='int32 tap = 52 [json_name = "tapN"];',
            dead_obs='json_name does not restore Int32Value; freeze still int',
        ),
    ),
    (
        plant(
            slug='sint32-to-int32-zigzag',
            short='zz32',
            decl_old='sint32 delta = 53;',
            decl_new='int32 delta = 53;',
            syntax='syntax = "proto3";',
            buf_rule='FIELD_TYPE / WIRE',
            wire_old='zigzag VARINT',
            wire_new="two's-complement VARINT (negatives differ)",
            freeze='Go freeze protowire.DecodeZigZag vs int32',
            ticket='GO-ZZ32-35',
            lang='Go',
            vs='r707 proto3-sint32-unpacked (scalar encoding, not packed=false)',
            avoid='r707/r690 sint pack/expanded',
            json_name='deltaN',
            debug='debug_zz32',
            compat='Dual-read delta as zigzag sint32 or int32',
            grep_pat='sint32 delta|int32 delta',
            goal_bit='sint32 delta=53 → int32 so freeze zigzag negatives fail',
        ),
        plant(
            slug='string-to-bytes-lot',
            short='s2b',
            decl_old='string lot = 54;',
            decl_new='bytes lot = 54;',
            syntax='syntax = "proto3";',
            buf_rule='FIELD_TYPE / WIRE_JSON',
            wire_old='LEN utf8 0xb2 0x03',
            wire_new='LEN bytes (JSON string vs base64)',
            freeze='Python freeze str vs bytes',
            ticket='PY-S2B-36',
            lang='Python',
            vs='r729 oneof-string-to-bytes (scalar field, not oneof)',
            avoid='r729 oneof string→bytes / r710 msg→string',
            json_name='lotCode',
            debug='debug_s2b',
            compat='Dual-read lot as utf8 string or raw bytes',
            grep_pat='string lot|bytes lot',
            goal_bit='string lot=54 → bytes so freeze utf8 vs base64 fails',
            dead_desc='json_name lotCode as a type substitute',
            dead_old='bytes lot = 54;',
            dead_new='bytes lot = 54 [json_name = "lotCode"];',
            dead_obs='json_name does not restore utf8 string; freeze still bytes',
        ),
    ),
    (
        plant(
            slug='float-to-int32-temp',
            short='f2i',
            decl_old='float temp_c = 55;',
            decl_new='int32 temp_c = 55;',
            syntax='syntax = "proto3";',
            buf_rule='FIELD_TYPE / WIRE',
            wire_old='FIXED32 0xbd 0x03',
            wire_new='VARINT 0xb8 0x03',
            freeze='C++ freeze float bits vs varint int',
            ticket='CXX-F2I-37',
            lang='C++',
            vs='r701 float-to-double-temp (float→int32, not float→double)',
            avoid='r701 f2d / r709 int32→float',
            json_name='tempC',
            debug='debug_f2i',
            compat='Dual-read temp_c as float32 or varint int32',
            grep_pat='float temp_c|int32 temp_c',
            goal_bit='float temp_c=55 → int32 so freeze FIXED32 bits fail',
        ),
        plant(
            slug='ed2023-expanded-repeated-int32',
            short='exi32',
            decl_old='repeated int32 taps = 56;',
            decl_new='repeated int32 taps = 56 [features.repeated_field_encoding = EXPANDED];',
            syntax='edition = "2023";',
            buf_rule='FIELD_WIRE / WIRE',
            wire_old='packed LEN 0xc2 0x03',
            wire_new='expanded VARINT 0xc0 0x03 repeats',
            freeze='Go freeze packed int32 on expanded tags',
            ticket='GO-EXI32-38',
            lang='Go',
            vs='r702 proto3-int32-unpacked (edition EXPANDED, not proto3 packed=false)',
            avoid='r702 i32 unpacked / r711/r714/r729 expanded',
            json_name='tapList',
            debug='debug_exi32',
            compat='Dual-read taps as packed LEN or expanded varint',
            grep_pat='repeated int32 taps|EXPANDED',
            goal_bit='edition EXPANDED on repeated int32 taps=56 so freeze packed 0xc2 fails',
            dead_desc='json_name tapList as an encoding substitute',
            dead_old='repeated int32 taps = 56 [features.repeated_field_encoding = EXPANDED];',
            dead_new='repeated int32 taps = 56 [features.repeated_field_encoding = EXPANDED, json_name = "tapList"];',
            dead_obs='json_name does not restore packed LEN; freeze still expanded 0xc0',
        ),
    ),
    (
        plant(
            slug='double-to-int64-peak',
            short='d2i',
            decl_old='double peak = 57;',
            decl_new='int64 peak = 57;',
            syntax='syntax = "proto3";',
            buf_rule='FIELD_TYPE / WIRE',
            wire_old='FIXED64 0xc9 0x03',
            wire_new='VARINT 0xc8 0x03',
            freeze='Rust freeze f64 bits vs i64 varint',
            ticket='RUST-D2I-39',
            lang='Rust',
            vs='r716 double-to-float-celsius (double→int64, not double→float)',
            avoid='r716 d2f / r701 f2d',
            json_name='peakN',
            debug='debug_d2i',
            compat='Dual-read peak as float64 or varint int64',
            grep_pat='double peak|int64 peak',
            goal_bit='double peak=57 → int64 so freeze FIXED64 bits fail',
        ),
        plant(
            slug='bytes-to-string-sku',
            short='b2s',
            decl_old='bytes sku = 58;',
            decl_new='string sku = 58;',
            syntax='syntax = "proto3";',
            buf_rule='FIELD_TYPE / WIRE_JSON',
            wire_old='LEN bytes (JSON base64)',
            wire_new='LEN utf8 (JSON string)',
            freeze='Go freeze []byte vs string; invalid utf8',
            ticket='GO-B2S-40',
            lang='Go',
            vs='r705 bytes-to-message-blob (bytes→string, not bytes→message)',
            avoid='r705 b2m / r729 oneof string→bytes',
            json_name='skuCode',
            debug='debug_b2s',
            compat='Dual-read sku as raw bytes or utf8 string',
            grep_pat='bytes sku|string sku',
            goal_bit='bytes sku=58 → string so freeze base64 vs utf8 fails',
            dead_desc='json_name skuCode as a type substitute',
            dead_old='string sku = 58;',
            dead_new='string sku = 58 [json_name = "skuCode"];',
            dead_obs='json_name does not restore bytes; freeze still string',
        ),
    ),
    (
        plant(
            slug='enum-to-int32-grade',
            short='e2i',
            decl_old='Grade grade = 59;',
            decl_new='int32 grade = 59;',
            syntax='syntax = "proto3";',
            extra_msgs='enum Grade { GRADE_UNSPECIFIED = 0; GRADE_A = 1; }\n',
            buf_rule='FIELD_TYPE / FILE',
            wire_old='VARINT enum',
            wire_new='VARINT int32 (no closed check)',
            freeze='Java freeze Grade vs int; unknown 9 now legal',
            ticket='JAVA-E2I-41',
            lang='Java',
            vs='r722 enum-to-string-grade (enum→int32, not enum→string)',
            avoid='r722 e2s / r693 field-enum-closed',
            json_name='gradeN',
            debug='debug_e2i',
            compat='Dual-read grade as enum or int32',
            grep_pat='Grade grade|int32 grade',
            goal_bit='Grade grade=59 → int32 so freeze enum closed check fails',
        ),
        plant(
            slug='ed2023-expanded-repeated-uint32',
            short='exu32',
            decl_old='repeated uint32 ports = 60;',
            decl_new='repeated uint32 ports = 60 [features.repeated_field_encoding = EXPANDED];',
            syntax='edition = "2023";',
            buf_rule='FIELD_WIRE / WIRE',
            wire_old='packed LEN 0xe2 0x03',
            wire_new='expanded VARINT 0xe0 0x03 repeats',
            freeze='Go freeze packed uint32 on expanded tags',
            ticket='GO-EXU32-42',
            lang='Go',
            vs='r727 proto3-uint32-unpacked (edition EXPANDED, not proto3 packed=false)',
            avoid='r727 u32 unpacked / r711/r714 expanded',
            json_name='portList',
            debug='debug_exu32',
            compat='Dual-read ports as packed LEN or expanded varint',
            grep_pat='repeated uint32 ports|EXPANDED',
            goal_bit='edition EXPANDED on repeated uint32 ports=60 so freeze packed 0xe2 fails',
            dead_desc='json_name portList as an encoding substitute',
            dead_old='repeated uint32 ports = 60 [features.repeated_field_encoding = EXPANDED];',
            dead_new='repeated uint32 ports = 60 [features.repeated_field_encoding = EXPANDED, json_name = "portList"];',
            dead_obs='json_name does not restore packed LEN; freeze still expanded 0xe0',
        ),
    ),
    (
        plant(
            slug='map-value-string-to-int32',
            short='mvsi',
            decl_old='map<string, string> notes = 9;',
            decl_new='map<string, int32> notes = 9;',
            syntax='syntax = "proto3";',
            buf_rule='MAP_VALUE_TYPE / WIRE',
            wire_old='value LEN 0x12',
            wire_new='value VARINT 0x10',
            freeze='Go freeze map[string]string vs int32',
            ticket='GO-MVSI-43',
            lang='Go',
            vs='r642 map-value-str-bytes (string→int32, not string→bytes)',
            avoid='r642/r711/r713/r721 map-value plants',
            json_name='noteMap',
            debug='debug_mvsi',
            compat='Dual-read map value as string or int32',
            grep_pat='map<string, string>|map<string, int32>|notes',
            goal_bit='map<string,string>→map<string,int32> notes=9 so freeze LEN values fail',
        ),
        plant(
            slug='oneof-bytes-to-string',
            short='ob2s',
            decl_old='oneof body { bytes blob = 61; }',
            decl_new='oneof body { string note = 61; }',
            syntax='syntax = "proto3";',
            buf_rule='FIELD_TYPE / WIRE_JSON',
            wire_old='LEN bytes (JSON base64)',
            wire_new='LEN utf8 string',
            freeze='Dart freeze Uint8List vs String',
            ticket='DART-OB2S-44',
            lang='Dart',
            vs='r729 oneof-string-to-bytes (opposite direction)',
            avoid='r729/r706/r703 oneof type plants',
            json_name='bodyBlob',
            debug='debug_ob2s',
            compat='Dual-read oneof 61 as bytes or utf8 string',
            grep_pat='oneof body|bytes blob|string note',
            goal_bit='oneof body bytes blob=61 → string note=61 so freeze bytes vs utf8',
            dead_desc='json_name bodyBlob as a oneof-type substitute',
            dead_old='oneof body { string note = 61; }',
            dead_new='oneof body { string note = 61 [json_name = "bodyBlob"]; }',
            dead_obs='json_name does not restore bytes; freeze still String',
        ),
    ),
    (
        plant(
            slug='sint64-to-int64-zigzag',
            short='zz64',
            decl_old='sint64 offset = 62;',
            decl_new='int64 offset = 62;',
            syntax='syntax = "proto3";',
            buf_rule='FIELD_TYPE / WIRE',
            wire_old='zigzag VARINT',
            wire_new="two's-complement VARINT",
            freeze='Go freeze DecodeZigZag64 vs int64',
            ticket='GO-ZZ64-45',
            lang='Go',
            vs='r717 proto3-sint64-unpacked (scalar encoding, not packed=false)',
            avoid='r717/r690 sint64 pack/expanded',
            json_name='offsetN',
            debug='debug_zz64',
            compat='Dual-read offset as zigzag sint64 or int64',
            grep_pat='sint64 offset|int64 offset',
            goal_bit='sint64 offset=62 → int64 so freeze zigzag negatives fail',
        ),
        plant(
            slug='ed2023-expanded-repeated-int64',
            short='exi64',
            decl_old='repeated int64 seqs = 63;',
            decl_new='repeated int64 seqs = 63 [features.repeated_field_encoding = EXPANDED];',
            syntax='edition = "2023";',
            buf_rule='FIELD_WIRE / WIRE',
            wire_old='packed LEN 0xfa 0x03',
            wire_new='expanded VARINT 0xf8 0x03 repeats',
            freeze='Java freeze packed Int64 on expanded tags',
            ticket='JAVA-EXI64-46',
            lang='Java',
            vs='r721 proto3-int64-unpacked (edition EXPANDED, not proto3 packed=false)',
            avoid='r721 i64 unpacked / r690 sint64 expanded',
            json_name='seqList',
            debug='debug_exi64',
            compat='Dual-read seqs as packed LEN or expanded varint',
            grep_pat='repeated int64 seqs|EXPANDED',
            goal_bit='edition EXPANDED on repeated int64 seqs=63 so freeze packed 0xfa fails',
            dead_desc='json_name seqList as an encoding substitute',
            dead_old='repeated int64 seqs = 63 [features.repeated_field_encoding = EXPANDED];',
            dead_new='repeated int64 seqs = 63 [features.repeated_field_encoding = EXPANDED, json_name = "seqList"];',
            dead_obs='json_name does not restore packed LEN; freeze still expanded 0xf8',
        ),
    ),
    (
        plant(
            slug='message-to-string-payload',
            short='m2s',
            decl_old='Payload payload = 64;',
            decl_new='string payload = 64;',
            syntax='syntax = "proto3";',
            extra_msgs='message Payload { string kind = 1; int32 n = 2; }\n',
            buf_rule='FIELD_TYPE / WIRE',
            wire_old='LEN nested Payload',
            wire_new='LEN utf8 string',
            freeze='TS freeze Payload.decode vs string',
            ticket='TS-M2S-47',
            lang='TypeScript',
            vs='r705 message-to-bytes-payload (message→string, not message→bytes)',
            avoid='r705 m2b / r710 nested-msg-to-string',
            json_name='payloadText',
            debug='debug_m2s',
            compat='Dual-read payload as nested Payload or raw string',
            grep_pat='Payload payload|string payload',
            goal_bit='Payload payload=64 → string so freeze nested decode fails',
        ),
        plant(
            slug='wrappers-float-to-scalar',
            short='wflt',
            decl_old='google.protobuf.FloatValue slope = 65;',
            decl_new='float slope = 65;',
            syntax='syntax = "proto3";',
            imports=('google/protobuf/wrappers.proto',),
            buf_rule='FIELD_TYPE / WIRE',
            wire_old='LEN wrapper 0x8a 0x04',
            wire_new='FIXED32 0x8d 0x04',
            freeze='JS freeze FloatValue vs number (null vs 0)',
            ticket='JS-WFLT-48',
            lang='JavaScript',
            vs='r719 wrappers-double-to-scalar (FloatValue, not DoubleValue)',
            avoid='r719/r706 wrapper unwraps',
            json_name='slopeN',
            debug='debug_wflt',
            compat='Dual-read slope as FloatValue or raw float',
            grep_pat='FloatValue slope|float slope',
            goal_bit='FloatValue slope=65 → float so freeze wrapper LEN fails',
            dead_desc='json_name slopeN as a wrapper-unwrap substitute',
            dead_old='float slope = 65;',
            dead_new='float slope = 65 [json_name = "slopeN"];',
            dead_obs='json_name does not restore FloatValue; freeze still number',
        ),
    ),
    (
        plant(
            slug='map-key-sfixed32-to-int32',
            short='sf32k',
            decl_old='map<sfixed32, string> lots = 4;',
            decl_new='map<int32, string> lots = 4;',
            syntax='syntax = "proto3";',
            buf_rule='MAP_KEY_TYPE / WIRE',
            wire_old='FIXED32 key 0x0d',
            wire_new='VARINT key 0x08',
            freeze='Go freeze map[int32]string still encodes sfixed32',
            ticket='GO-SF32K-49',
            lang='Go',
            vs='r701 map-key-sfixed32-to-uint32 (sfixed32→int32, not →uint32)',
            avoid='r700/r701/r728 map-key plants',
            json_name='lotMap',
            debug='debug_sf32k',
            compat='Dual-read map key as sfixed32 or int32 varint',
            grep_pat='map<sfixed32|map<int32|lots',
            goal_bit='map<sfixed32,string>→map<int32,string> lots=4 so freeze FIXED32 keys fail',
        ),
        plant(
            slug='timestamp-to-duration',
            short='ts2d',
            decl_old='google.protobuf.Timestamp poured_at = 66;',
            decl_new='google.protobuf.Duration poured_at = 66;',
            syntax='syntax = "proto3";',
            imports=('google/protobuf/timestamp.proto', 'google/protobuf/duration.proto'),
            buf_rule='FIELD_TYPE / FILE',
            wire_old='LEN Timestamp seconds+nanos',
            wire_new='LEN Duration seconds+nanos (same layout, different type)',
            freeze='Python freeze datetime vs timedelta',
            ticket='PY-TS2D-50',
            lang='Python',
            vs='r713 timestamp-to-string-poured (Timestamp→Duration, not →string)',
            avoid='r713/r722/r632 Timestamp plants',
            json_name='pouredAt',
            debug='debug_ts2d',
            compat='Dual-read poured_at as Timestamp or Duration',
            grep_pat='Timestamp poured_at|Duration poured_at',
            goal_bit='Timestamp poured_at=66 → Duration so freeze datetime vs timedelta',
            dead_desc='json_name pouredAt as a well-known-type substitute',
            dead_old='google.protobuf.Duration poured_at = 66;',
            dead_new='google.protobuf.Duration poured_at = 66 [json_name = "pouredAt"];',
            dead_obs='json_name does not restore Timestamp; freeze still Duration',
        ),
    ),
    (
        plant(
            slug='any-to-string-event',
            short='a2s',
            decl_old='google.protobuf.Any event = 67;',
            decl_new='string event = 67;',
            syntax='syntax = "proto3";',
            imports=('google/protobuf/any.proto',),
            buf_rule='FIELD_TYPE / WIRE',
            wire_old='LEN Any type_url+value',
            wire_new='LEN utf8 string',
            freeze='Java freeze Any.unpack vs String',
            ticket='JAVA-A2S-51',
            lang='Java',
            vs='r712 any-to-bytes-event (Any→string, not Any→bytes)',
            avoid='r712/r724/r634 Any plants',
            json_name='eventText',
            debug='debug_a2s',
            compat='Dual-read event as Any or raw string',
            grep_pat='protobuf.Any event|string event',
            goal_bit='Any event=67 → string so freeze type_url unpack fails',
        ),
        plant(
            slug='ed2023-expanded-repeated-sint32',
            short='exs32',
            decl_old='repeated sint32 deltas = 68;',
            decl_new='repeated sint32 deltas = 68 [features.repeated_field_encoding = EXPANDED];',
            syntax='edition = "2023";',
            buf_rule='FIELD_WIRE / WIRE',
            wire_old='packed LEN 0xa2 0x04',
            wire_new='expanded zigzag VARINT 0xa0 0x04 repeats',
            freeze='Go freeze packed zigzag on expanded tags',
            ticket='GO-EXS32-52',
            lang='Go',
            vs='r707 proto3-sint32-unpacked (edition EXPANDED, not proto3 packed=false)',
            avoid='r707 s32 unpacked / r690 sint64 expanded',
            json_name='deltaList',
            debug='debug_exs32',
            compat='Dual-read deltas as packed LEN or expanded zigzag',
            grep_pat='repeated sint32 deltas|EXPANDED',
            goal_bit='edition EXPANDED on repeated sint32 deltas=68 so freeze packed 0xa2 fails',
            dead_desc='json_name deltaList as an encoding substitute',
            dead_old='repeated sint32 deltas = 68 [features.repeated_field_encoding = EXPANDED];',
            dead_new='repeated sint32 deltas = 68 [features.repeated_field_encoding = EXPANDED, json_name = "deltaList"];',
            dead_obs='json_name does not restore packed LEN; freeze still expanded 0xa0',
        ),
    ),
    (
        plant(
            slug='int32-to-sint32-tap',
            short='i2zz',
            decl_old='int32 tap_n = 69;',
            decl_new='sint32 tap_n = 69;',
            syntax='syntax = "proto3";',
            buf_rule='FIELD_TYPE / WIRE',
            wire_old="two's-complement VARINT",
            wire_new='zigzag VARINT',
            freeze='Go freeze int32 vs DecodeZigZag',
            ticket='GO-I2ZZ-53',
            lang='Go',
            vs='r709 int32-to-float-tap (int32→sint32, not int32→float)',
            avoid='r709 i2f / r732 zz32 opposite',
            json_name='tapN',
            debug='debug_i2zz',
            compat='Dual-read tap_n as int32 or zigzag sint32',
            grep_pat='int32 tap_n|sint32 tap_n',
            goal_bit="int32 tap_n=69 → sint32 so freeze two's-complement negatives fail",
        ),
        plant(
            slug='value-to-bytes-kind',
            short='val2b',
            decl_old='google.protobuf.Value kind = 70;',
            decl_new='bytes kind = 70;',
            syntax='syntax = "proto3";',
            imports=('google/protobuf/struct.proto',),
            buf_rule='FIELD_TYPE / WIRE',
            wire_old='LEN Value oneof',
            wire_new='LEN opaque bytes',
            freeze='Python freeze struct_pb2.Value vs bytes',
            ticket='PY-VAL2B-54',
            lang='Python',
            vs='r720 value-to-string-kind (Value→bytes, not Value→string)',
            avoid='r720 val2s / well-known type catalog',
            json_name='kindBin',
            debug='debug_val2b',
            compat='Dual-read kind as Value or raw bytes',
            grep_pat='protobuf.Value kind|bytes kind',
            goal_bit='Value kind=70 → bytes so freeze Value oneof fails',
            dead_desc='json_name kindBin as a Value-type substitute',
            dead_old='bytes kind = 70;',
            dead_new='bytes kind = 70 [json_name = "kindBin"];',
            dead_obs='json_name does not restore Value; freeze still bytes',
        ),
    ),
    (
        plant(
            slug='map-value-double-to-float',
            short='mvdf',
            decl_old='map<string, double> gauges = 5;',
            decl_new='map<string, float> gauges = 5;',
            syntax='syntax = "proto3";',
            buf_rule='MAP_VALUE_TYPE / WIRE',
            wire_old='value FIXED64 0x11',
            wire_new='value FIXED32 0x15',
            freeze='Go freeze map[string]float64 vs float32',
            ticket='GO-MVDF-55',
            lang='Go',
            vs='r711 map-value-float-to-double (opposite direction)',
            avoid='r711/r642/r713 map-value plants',
            json_name='gaugeMap',
            debug='debug_mvdf',
            compat='Dual-read map value as float64 or float32',
            grep_pat='map<string, double>|map<string, float>|gauges',
            goal_bit='map<string,double>→map<string,float> gauges=5 so freeze FIXED64 values fail',
        ),
        plant(
            slug='empty-to-bytes-ack',
            short='e2b',
            decl_old='google.protobuf.Empty ack = 71;',
            decl_new='bytes ack = 71;',
            syntax='syntax = "proto3";',
            imports=('google/protobuf/empty.proto',),
            buf_rule='FIELD_TYPE / WIRE',
            wire_old='LEN empty 0-length',
            wire_new='LEN opaque bytes',
            freeze='Go freeze emptypb.Empty vs []byte',
            ticket='GO-E2B-56',
            lang='Go',
            vs='r717 empty-to-message-ack (Empty→bytes, not Empty→Ack)',
            avoid='r717 e2m',
            json_name='ackBin',
            debug='debug_e2b',
            compat='Dual-read ack as Empty or raw bytes',
            grep_pat='protobuf.Empty ack|bytes ack',
            goal_bit='Empty ack=71 → bytes so freeze 0-length Empty fails',
            dead_desc='json_name ackBin as an Empty-type substitute',
            dead_old='bytes ack = 71;',
            dead_new='bytes ack = 71 [json_name = "ackBin"];',
            dead_obs='json_name does not restore Empty; freeze still []byte',
        ),
    ),
    (
        plant(
            slug='proto2-required-string-to-bytes',
            short='req2b',
            decl_old='required string sku = 2;',
            decl_new='required bytes sku = 2;',
            syntax='syntax = "proto2";',
            buf_rule='FIELD_TYPE / WIRE_JSON',
            wire_old='LEN utf8',
            wire_new='LEN bytes (JSON base64)',
            freeze='Java freeze String sku vs ByteString',
            ticket='JAVA-REQ2B-57',
            lang='Java',
            vs='r710 proto2-required-int-to-string (string→bytes, not int→string)',
            avoid='r710 req2s / r635 required drop',
            json_name='skuCode',
            debug='debug_req2b',
            compat='Dual-read sku as utf8 string or raw bytes',
            grep_pat='required string sku|required bytes sku',
            goal_bit='proto2 required string sku=2 → required bytes so freeze utf8 fails',
        ),
        plant(
            slug='ed2023-expanded-repeated-fixed32',
            short='exf32',
            decl_old='repeated fixed32 crcs = 72;',
            decl_new='repeated fixed32 crcs = 72 [features.repeated_field_encoding = EXPANDED];',
            syntax='edition = "2023";',
            buf_rule='FIELD_WIRE / WIRE',
            wire_old='packed LEN 0xc2 0x04',
            wire_new='expanded FIXED32 0xc5 0x04 repeats',
            freeze='Go freeze packed fixed32 on expanded tags',
            ticket='GO-EXF32-58',
            lang='Go',
            vs='r719 proto3-fixed32-unpacked (edition EXPANDED, not proto3 packed=false)',
            avoid='r719 f32 unpacked / r707 expanded float',
            json_name='crcList',
            debug='debug_exf32',
            compat='Dual-read crcs as packed LEN or expanded fixed32',
            grep_pat='repeated fixed32 crcs|EXPANDED',
            goal_bit='edition EXPANDED on repeated fixed32 crcs=72 so freeze packed 0xc2 fails',
            dead_desc='json_name crcList as an encoding substitute',
            dead_old='repeated fixed32 crcs = 72 [features.repeated_field_encoding = EXPANDED];',
            dead_new='repeated fixed32 crcs = 72 [features.repeated_field_encoding = EXPANDED, json_name = "crcList"];',
            dead_obs='json_name does not restore packed LEN; freeze still expanded 0xc5',
        ),
    ),
    (
        plant(
            slug='map-value-bytes-to-string',
            short='mvbs2',
            decl_old='map<string, bytes> blobs = 10;',
            decl_new='map<string, string> blobs = 10;',
            syntax='syntax = "proto3";',
            buf_rule='MAP_VALUE_TYPE / WIRE_JSON',
            wire_old='value LEN bytes (JSON base64)',
            wire_new='value LEN utf8',
            freeze='Go freeze map[string][]byte vs string',
            ticket='GO-MVBS2-59',
            lang='Go',
            vs='r642 map-value-str-bytes (opposite direction)',
            avoid='r642/r721 map-value plants',
            json_name='blobMap',
            debug='debug_mvbs2',
            compat='Dual-read map value as bytes or utf8 string',
            grep_pat='map<string, bytes>|map<string, string>|blobs',
            goal_bit='map<string,bytes>→map<string,string> blobs=10 so freeze base64 values fail',
        ),
        plant(
            slug='duration-to-timestamp',
            short='d2ts',
            decl_old='google.protobuf.Duration hold_for = 73;',
            decl_new='google.protobuf.Timestamp hold_for = 73;',
            syntax='syntax = "proto3";',
            imports=('google/protobuf/duration.proto', 'google/protobuf/timestamp.proto'),
            buf_rule='FIELD_TYPE / FILE',
            wire_old='LEN Duration seconds+nanos',
            wire_new='LEN Timestamp seconds+nanos',
            freeze='Go freeze durationpb vs timestamppb',
            ticket='GO-D2TS-60',
            lang='Go',
            vs='r720 duration-to-string-hold (Duration→Timestamp, not →string)',
            avoid='r720/r727/r643 Duration plants',
            json_name='holdFor',
            debug='debug_d2ts',
            compat='Dual-read hold_for as Duration or Timestamp',
            grep_pat='Duration hold_for|Timestamp hold_for',
            goal_bit='Duration hold_for=73 → Timestamp so freeze timedelta vs datetime',
            dead_desc='json_name holdFor as a well-known-type substitute',
            dead_old='google.protobuf.Timestamp hold_for = 73;',
            dead_new='google.protobuf.Timestamp hold_for = 73 [json_name = "holdFor"];',
            dead_obs='json_name does not restore Duration; freeze still Timestamp',
        ),
    ),
    (
        plant(
            slug='int32-to-enum-mode',
            short='i2e',
            decl_old='int32 mode = 74;',
            decl_new='Mode mode = 74;',
            syntax='syntax = "proto3";',
            extra_msgs='enum Mode { MODE_UNSPECIFIED = 0; MODE_RUN = 1; }\n',
            buf_rule='FIELD_TYPE / FILE',
            wire_old='VARINT int32',
            wire_new='VARINT enum (unknown 9 rejected if closed client)',
            freeze='Java freeze int vs Mode; 9 now UNRECOGNIZED',
            ticket='JAVA-I2E-61',
            lang='Java',
            vs='r735 enum-to-int32-grade (opposite direction)',
            avoid='r722 e2s / r693 enum closed',
            json_name='modeN',
            debug='debug_i2e',
            compat='Dual-read mode as int32 or Mode enum',
            grep_pat='int32 mode|Mode mode',
            goal_bit='int32 mode=74 → Mode so freeze open int vs enum fails',
        ),
        plant(
            slug='ed2023-expanded-repeated-uint64',
            short='exu64',
            decl_old='repeated uint64 seqs = 75;',
            decl_new='repeated uint64 seqs = 75 [features.repeated_field_encoding = EXPANDED];',
            syntax='edition = "2023";',
            buf_rule='FIELD_WIRE / WIRE',
            wire_old='packed LEN 0xda 0x04',
            wire_new='expanded VARINT 0xd8 0x04 repeats',
            freeze='Rust freeze packed u64 on expanded tags',
            ticket='RUST-EXU64-62',
            lang='Rust',
            vs='r715 proto3-uint64-unpacked (edition EXPANDED, not proto3 packed=false)',
            avoid='r715 u64 unpacked / r645 fixed64 expanded',
            json_name='seqList',
            debug='debug_exu64',
            compat='Dual-read seqs as packed LEN or expanded varint',
            grep_pat='repeated uint64 seqs|EXPANDED',
            goal_bit='edition EXPANDED on repeated uint64 seqs=75 so freeze packed 0xda fails',
            dead_desc='json_name seqList as an encoding substitute',
            dead_old='repeated uint64 seqs = 75 [features.repeated_field_encoding = EXPANDED];',
            dead_new='repeated uint64 seqs = 75 [features.repeated_field_encoding = EXPANDED, json_name = "seqList"];',
            dead_obs='json_name does not restore packed LEN; freeze still expanded 0xd8',
        ),
    ),
    (
        plant(
            slug='map-key-f32-to-u32',
            short='f32k',
            decl_old='map<fixed32, string> bins = 3;',
            decl_new='map<uint32, string> bins = 3;',
            syntax='syntax = "proto3";',
            buf_rule='MAP_KEY_TYPE / WIRE',
            wire_old='FIXED32 key 0x0d',
            wire_new='VARINT key 0x08',
            freeze='Go freeze map[uint32]string still encodes fixed32',
            ticket='GO-F32KEY-63',
            lang='Go',
            vs='r715 map-key-uint32-to-fixed32 (opposite direction) and r700 int32→fixed32',
            avoid='r700 map-key-fixed32 (that was int32→fixed32, this is fixed32→uint32 restore)',
            json_name='binMap',
            debug='debug_f32k',
            compat='Dual-read map key as fixed32 or uint32 varint',
            grep_pat='map<fixed32|map<uint32|bins',
            goal_bit='map<fixed32,string>→map<uint32,string> bins=3 so freeze FIXED32 keys fail',
        ),
        plant(
            slug='struct-to-any-attrs',
            short='st2a',
            decl_old='google.protobuf.Struct attrs = 76;',
            decl_new='google.protobuf.Any attrs = 76;',
            syntax='syntax = "proto3";',
            imports=('google/protobuf/struct.proto', 'google/protobuf/any.proto'),
            buf_rule='FIELD_TYPE / WIRE',
            wire_old='LEN Struct fields map',
            wire_new='LEN Any type_url+value',
            freeze='Python freeze Struct vs Any',
            ticket='PY-ST2A-64',
            lang='Python',
            vs='r724 any-to-struct-event (opposite direction)',
            avoid='r724/r716/r726 Struct/Any plants',
            json_name='attrObj',
            debug='debug_st2a',
            compat='Dual-read attrs as Struct or Any',
            grep_pat='protobuf.Struct attrs|protobuf.Any attrs',
            goal_bit='Struct attrs=76 → Any so freeze fields map vs type_url',
            dead_desc='json_name attrObj as a well-known-type substitute',
            dead_old='google.protobuf.Any attrs = 76;',
            dead_new='google.protobuf.Any attrs = 76 [json_name = "attrObj"];',
            dead_obs='json_name does not restore Struct; freeze still Any',
        ),
    ),
    (
        plant(
            slug='sfixed32-to-fixed32-crc',
            short='sf2f',
            decl_old='sfixed32 crc = 77;',
            decl_new='fixed32 crc = 77;',
            syntax='syntax = "proto3";',
            buf_rule='FIELD_TYPE / FILE',
            wire_old='FIXED32 signed',
            wire_new='FIXED32 unsigned (Go int32 vs uint32)',
            freeze='Go freeze int32 vs uint32 on same 4 bytes',
            ticket='GO-SF2F-65',
            lang='Go',
            vs='r725 proto3-sfixed32-unpacked (scalar signedness, not pack)',
            avoid='r725/r630 sfixed32 pack',
            json_name='crcN',
            debug='debug_sf2f',
            compat='Dual-read crc as sfixed32 or fixed32',
            grep_pat='sfixed32 crc|fixed32 crc',
            goal_bit='sfixed32 crc=77 → fixed32 so freeze signed vs unsigned',
        ),
        plant(
            slug='fieldmask-to-repeated-string',
            short='fm2r',
            decl_old='google.protobuf.FieldMask update_mask = 78;',
            decl_new='repeated string update_mask = 78;',
            syntax='syntax = "proto3";',
            imports=('google/protobuf/field_mask.proto',),
            buf_rule='FIELD_TYPE / WIRE',
            wire_old='LEN FieldMask paths nested',
            wire_new='repeated LEN string 0xf2 0x04',
            freeze='Go freeze fieldmaskpb vs []string',
            ticket='GO-FM2R-66',
            lang='Go',
            vs='r712 fieldmask-to-string (FieldMask→repeated string, not singular string)',
            avoid='r712/r728 FieldMask plants / r676 update_mask REQUIRED',
            json_name='updatePaths',
            debug='debug_fm2r',
            compat='Dual-read update_mask as FieldMask or repeated string',
            grep_pat='FieldMask update_mask|repeated string update_mask',
            goal_bit='FieldMask update_mask=78 → repeated string so freeze paths[] envelope fails',
            dead_desc='json_name updatePaths as a FieldMask-type substitute',
            dead_old='repeated string update_mask = 78;',
            dead_new='repeated string update_mask = 78 [json_name = "updatePaths"];',
            dead_obs='json_name does not restore FieldMask; freeze still []string',
        ),
    ),
    (
        plant(
            slug='oneof-msg-to-int',
            short='om2i',
            decl_old='oneof body { Note note = 79; }',
            decl_new='oneof body { int32 code = 79; }',
            syntax='syntax = "proto3";',
            extra_msgs='message Note { string text = 1; }\n',
            buf_rule='FIELD_TYPE / WIRE',
            wire_old='LEN nested Note 0xfa 0x04',
            wire_new='VARINT 0xf8 0x04',
            freeze='Swift freeze Note vs Int32',
            ticket='SWIFT-OM2I-67',
            lang='Swift',
            vs='r703 oneof-bool-to-msg (opposite: msg→int, not bool→msg)',
            avoid='r699/r703/r706 oneof plants',
            json_name='bodyNote',
            debug='debug_om2i',
            compat='Dual-read oneof 79 as nested Note or varint int32',
            grep_pat='oneof body|Note note|int32 code',
            goal_bit='oneof body Note note=79 → int32 code=79 so freeze nested LEN fails',
        ),
        plant(
            slug='ed2023-expanded-repeated-sfixed32',
            short='exsf32',
            decl_old='repeated sfixed32 ticks = 80;',
            decl_new='repeated sfixed32 ticks = 80 [features.repeated_field_encoding = EXPANDED];',
            syntax='edition = "2023";',
            buf_rule='FIELD_WIRE / WIRE',
            wire_old='packed LEN 0x82 0x05',
            wire_new='expanded FIXED32 0x85 0x05 repeats',
            freeze='Kotlin freeze packed sfixed32 on expanded tags',
            ticket='KT-EXSF32-68',
            lang='Kotlin',
            vs='r725 proto3-sfixed32-unpacked (edition EXPANDED, not proto3 packed=false)',
            avoid='r725/r630 sfixed32 pack',
            json_name='tickList',
            debug='debug_exsf32',
            compat='Dual-read ticks as packed LEN or expanded sfixed32',
            grep_pat='repeated sfixed32 ticks|EXPANDED',
            goal_bit='edition EXPANDED on repeated sfixed32 ticks=80 so freeze packed 0x82 fails',
            dead_desc='json_name tickList as an encoding substitute',
            dead_old='repeated sfixed32 ticks = 80 [features.repeated_field_encoding = EXPANDED];',
            dead_new='repeated sfixed32 ticks = 80 [features.repeated_field_encoding = EXPANDED, json_name = "tickList"];',
            dead_obs='json_name does not restore packed LEN; freeze still expanded 0x85',
        ),
    ),
    (
        plant(
            slug='bytes-to-any-blob',
            short='b2a',
            decl_old='bytes blob = 81;',
            decl_new='google.protobuf.Any blob = 81;',
            syntax='syntax = "proto3";',
            imports=('google/protobuf/any.proto',),
            buf_rule='FIELD_TYPE / WIRE',
            wire_old='LEN raw bytes',
            wire_new='LEN Any type_url+value',
            freeze='Go freeze []byte vs anypb.Any',
            ticket='GO-B2A-69',
            lang='Go',
            vs='r712 any-to-bytes-event (opposite direction)',
            avoid='r712/r724/r634 Any plants',
            json_name='blobAny',
            debug='debug_b2a',
            compat='Dual-read blob as raw bytes or Any',
            grep_pat='bytes blob|protobuf.Any blob',
            goal_bit='bytes blob=81 → Any so freeze raw LEN vs type_url',
        ),
        plant(
            slug='proto2-optional-int-to-string',
            short='opt2s',
            decl_old='optional int32 soak = 3;',
            decl_new='optional string soak = 3;',
            syntax='syntax = "proto2";',
            buf_rule='FIELD_TYPE / WIRE',
            wire_old='VARINT 0x18',
            wire_new='LEN 0x1a',
            freeze='Java freeze Integer soak vs String; hasSoak stays',
            ticket='JAVA-OPT2S-70',
            lang='Java',
            vs='r710 proto2-required-int-to-string (optional, not required) and not r629 optional drop',
            avoid='r629 optional drop / r710 required int→string',
            json_name='soakSecs',
            debug='debug_opt2s',
            compat='Dual-read soak as varint int32 or LEN string',
            grep_pat='optional int32 soak|optional string soak',
            goal_bit='proto2 optional int32 soak=3 → optional string so freeze VARINT fails',
            dead_desc='json_name soakSecs as a type substitute (not optional drop)',
            dead_old='optional string soak = 3;',
            dead_new='optional string soak = 3 [json_name = "soakSecs"];',
            dead_obs='json_name does not restore varint; freeze still String soak',
        ),
    ),
    (
        plant(
            slug='map-key-sfixed64-to-fixed64',
            short='sf64f',
            decl_old='map<sfixed64, string> lots = 4;',
            decl_new='map<fixed64, string> lots = 4;',
            syntax='syntax = "proto3";',
            buf_rule='MAP_KEY_TYPE / FILE',
            wire_old='FIXED64 signed key',
            wire_new='FIXED64 unsigned key (Go int64 vs uint64)',
            freeze='Go freeze map[int64]string vs uint64',
            ticket='GO-SF64F-71',
            lang='Go',
            vs='r718 map-key-sfixed64-to-int64 (sfixed64→fixed64, not →int64)',
            avoid='r718/r704/r700 map-key plants',
            json_name='lotMap',
            debug='debug_sf64f',
            compat='Dual-read map key as sfixed64 or fixed64',
            grep_pat='map<sfixed64|map<fixed64|lots',
            goal_bit='map<sfixed64,string>→map<fixed64,string> lots=4 so freeze signed keys fail',
        ),
        plant(
            slug='ed2023-expanded-repeated-sfixed64',
            short='exsf64',
            decl_old='repeated sfixed64 coords = 82;',
            decl_new='repeated sfixed64 coords = 82 [features.repeated_field_encoding = EXPANDED];',
            syntax='edition = "2023";',
            buf_rule='FIELD_WIRE / WIRE',
            wire_old='packed LEN 0x92 0x05',
            wire_new='expanded FIXED64 0x91 0x05 repeats',
            freeze='C++ freeze packed sfixed64 on expanded tags',
            ticket='CXX-EXSF64-72',
            lang='C++',
            vs='r723 proto3-sfixed64-unpacked (edition EXPANDED, not proto3 packed=false)',
            avoid='r723 sf64 unpacked / r645 fixed64 expanded',
            json_name='coordList',
            debug='debug_exsf64',
            compat='Dual-read coords as packed LEN or expanded sfixed64',
            grep_pat='repeated sfixed64 coords|EXPANDED',
            goal_bit='edition EXPANDED on repeated sfixed64 coords=82 so freeze packed 0x92 fails',
            dead_desc='json_name coordList as an encoding substitute',
            dead_old='repeated sfixed64 coords = 82 [features.repeated_field_encoding = EXPANDED];',
            dead_new='repeated sfixed64 coords = 82 [features.repeated_field_encoding = EXPANDED, json_name = "coordList"];',
            dead_obs='json_name does not restore packed LEN; freeze still expanded 0x91',
        ),
    ),
)
