def build_record():
    ticks, heads = cents_ticks(
        [4620, 6812, 7512, 6_000_000, 624_000_000, 9_000_000_000, 12_240_000_000],
        [
            (1, -2, -1, 2, 1),
            (2, -5, -1, 3, 1),
            (2, -6, -2, 3, 2),
            (1, -6, -2, 2, 1),
            (1, -5, -2, 2, 1),
            (1, -5, -1, 1, 1),
            (0, -5, -2, 1, 1),
        ],
    )
    assert abs(heads["total"] - (-0.15)) < 1e-9, heads

    trace = math.exp(-PROBE_S / TAU_E_S)
    eta1 = 0.24 / trace
    eta2 = 0.21 / trace
    eta3 = 0.19 / trace
    dw1 = eta1 * 1.0 * trace
    dw2 = eta2 * 1.0 * trace
    dw3 = eta3 * 1.0 * trace
    w1 = 0.46 - dw1
    w2 = 0.41 - dw2
    w3 = 0.38 - dw3
    assert abs(w1 - 0.22) < 5e-4, w1
    assert abs(w2 - 0.20) < 5e-4, w2
    assert abs(w3 - 0.19) < 5e-4, w3

    spike_events = [
        {"channel": "power.mw", "t_rel_ms": 0.240, "amplitude": 0.53},
        {"channel": "head.lvl", "t_rel_ms": 1.060, "amplitude": 0.61},
        {"channel": "guide.pct", "t_rel_ms": 1.880, "amplitude": 0.55},
        {"channel": "power.mw", "t_rel_ms": 3.100, "amplitude": 0.49},
        {"channel": "sigma.th", "t_rel_ms": 4.620, "amplitude": 0.71},
        {"channel": "head.lvl", "t_rel_ms": 5.120, "amplitude": 0.64},
        {"channel": "guide.pct", "t_rel_ms": 5.560, "amplitude": 0.52},
        {"channel": "sigma.th", "t_rel_ms": 6.812, "amplitude": 1.26},
        {"channel": "power.ok", "t_rel_ms": 7.004, "amplitude": 1.09},
        {"channel": "draft.vib", "t_rel_ms": 7.148, "amplitude": 0.66},
        {"channel": "ctrl.gate", "t_rel_ms": 7.512, "amplitude": 1.05},
        {"channel": "power.mw", "t_rel_ms": 8.920, "amplitude": 0.45},
        {"channel": "head.lvl", "t_rel_ms": 10.780, "amplitude": 0.46},
        {"channel": "sigma.th", "t_rel_ms": 12.640, "amplitude": 0.85},
        {"channel": "guide.pct", "t_rel_ms": 18.400, "amplitude": 0.43},
        {"channel": "ctrl.gate", "t_rel_ms": 26.180, "amplitude": 0.83},
        {"channel": "cav.probe", "t_rel_ms": 6000.0, "amplitude": 0.93},
        {"channel": "sigma.th", "t_rel_ms": 6140.6, "amplitude": 0.39},
        {"channel": "power.ok", "t_rel_ms": 6240.4, "amplitude": 0.35},
        {"channel": "human.ratify", "t_rel_ms": 624000.0, "amplitude": 0.81},
        {"channel": "hub.isolate", "t_rel_ms": 624800.0, "amplitude": 0.73},
        {"channel": "pit.inventory", "t_rel_ms": 625400.0, "amplitude": 0.82},
        {"channel": "power.mw", "t_rel_ms": 9000000.0, "amplitude": 0.30},
        {"channel": "head.lvl", "t_rel_ms": 9000460.0, "amplitude": 0.28},
        {"channel": "sigma.th", "t_rel_ms": 9000920.0, "amplitude": 0.19},
        {"channel": "blade.pit", "t_rel_ms": 12240000.0, "amplitude": 0.89},
    ]

    contrast_spikes = [
        {"channel": "raise.demand", "t_rel_ms": 0.000, "amplitude": 0.85},
        {"channel": "sigma.th", "t_rel_ms": 0.192, "amplitude": 0.19},
        {"channel": "power.ok", "t_rel_ms": 0.410, "amplitude": 0.77},
        {"channel": "power.mw", "t_rel_ms": 1.660, "amplitude": 0.41},
        {"channel": "head.lvl", "t_rel_ms": 4.920, "amplitude": 0.52},
        {"channel": "ctrl.gate", "t_rel_ms": 7.180, "amplitude": 0.91},
        {"channel": "cav.probe", "t_rel_ms": 2800.0, "amplitude": 0.33},
        {"channel": "raise.seated", "t_rel_ms": 12240000.0, "amplitude": 0.13},
    ]

    excerpt = [
        {"t_us": 240, "neuron_id": 48},
        {"t_us": 1060, "neuron_id": 90},
        {"t_us": 1880, "neuron_id": 102},
        {"t_us": 3100, "neuron_id": 52},
        {"t_us": 4620, "neuron_id": 10},
        {"t_us": 5120, "neuron_id": 94},
        {"t_us": 5560, "neuron_id": 106},
        {"t_us": 6812, "neuron_id": 8},
        {"t_us": 7004, "neuron_id": 56},
        {"t_us": 7148, "neuron_id": 18},
        {"t_us": 7512, "neuron_id": 130},
        {"t_us": 8920, "neuron_id": 60},
        {"t_us": 10780, "neuron_id": 98},
        {"t_us": 12640, "neuron_id": 14},
        {"t_us": 18400, "neuron_id": 110},
        {"t_us": 26180, "neuron_id": 134},
    ]

    rec = {
        "id": RECORD_ID,
        "title": "RUNNELGATE KT-5: Thoma sigma 0.11 beats power.ok by 192 us; correct MODIFY still pits the runner after pre-t0 hub-seal cavitation",
        "rights": dict(RIGHTS),
        "state": {
            "sim_or_real": "designed",
            "domain": DOMAIN,
            "scenario_name": "RUNNELGATE / Ghyllmere Hydro KT-5",
            "timestamp_local": "2026-04-19T04:22:00-07:00",
            "t0_us": 1780002440000551,
            "gate_latency_us": 700,
            "race_window_us": 500,
            "race_window_rel_ms": [6.74, 7.24],
            "description": "Ghyllmere Hydro highland-ghyll power hall KT-5 holds a 92 MW Kaplan unit at 42.6 m net head. POWER is 84.2 MW against 80-90. HEAD forebay is 42.6 m inside 41.0-44.0. GUIDE wicket opening is 68% inside 60-75. Playbook PB-KT-11 treats the conjunction as permission to raise the wicket. The consensus is false: a runner-hub seal leak dumps water past the Kaplan blades over 18 min. POWER stays in-band because remaining blades still make nameplate at higher specific loading. HEAD stays in-band because the reservoir is upstream of the hub. GUIDE stays in-band because servomotor position is true. Uncommissioned r_sigma is 0.11 against a 0.22 hold. Uncommissioned r_vib is 4.8 mm/s against a 1.6 hold. Sigma-first latches RAISE-HOLD plus a gate-cut probe; power-ok-first would have authorized RAISE-GATE 68 to 82% into a cavitating runner.",
            "goal": "Hold wicket at 68% while r_sigma < 0.22 AND r_vib > 1.6 mm/s; keep hub-seal leak at 0 and blade-TE pit depth <= 0.2 mm.",
            "race": {
                "contenders": [
                    "sigma.th 0.11 (uncommissioned Thoma cavitation factor vs Kaplan fingerprint)",
                    "power.ok 84.2 MW (electrical power inside 80-90 MW)",
                ],
                "semantics": "Sigma-first latches RAISE-HOLD + GATE-CUT-PROBE + hub isolate. Power-ok-first latches RAISE-GATE (68 to 82% into the runner, no probe).",
                "window_derivation": "500 us = one 380 us power-TT ADC slot plus 120 us sigma publish.",
                "order_evidence_note": "Margin 192 us vs combined jitter 62 us (sigma 34 + power 28): 3.10x. The 192 us gap sits inside min(500, 500) us, so a sub-flip-bound perturbation reverses triage order. The gate rides the order-invariant floors r_sigma < 0.22 and r_vib > 1.6 mm/s, not the alarm order.",
            },
            "topology": {
                "site": "Ghyllmere Hydro, invented highland-ghyll hydropower campus Ghyllmere, Hall 1 Kaplan unit KT-5: 92 MW nameplate, 4.8 m runner, 5 blades, net head 42.6 m, uncommissioned Thoma-sigma residual, uncommissioned draft-tube RMS, Grade-C power hall",
                "agents": "POWER MW transducer (vendor Megagage): electrical output. HEAD forebay level (vendor Tarnfen): reservoir head. GUIDE wicket opening (vendor Wickholt): servomotor percent. Heterogeneous stacks, no shared sigma schema, one 20 ms power-hall bus epoch",
                "coupling": "Each agent's commissioned window hides a different slice of the same hub leak. POWER is correct that electrical output is 84.2 MW. HEAD is correct that forebay is 42.6 m. GUIDE is correct that wicket opening is 68%. Playbook PB-KT-11 treats the conjunction of three in-spec loops as permission to raise the gate. No agent is faulty; the 0.11 Thoma factor is a cavitation the power-ok model cannot see.",
            },
            "sensors": [
                "electrical power transducer, 50 Hz, 28 us jitter, 84.2 MW (spec 80-90 MW)",
                "Thoma sigma r_sigma is computable on the Sigmacairn draft-tube taps and is NOT commissioned at t0 (0.11 observed in the historian after the fact)",
                "forebay level, 20 Hz, 24 us jitter, 42.6 m vs 41.0-44.0 window",
                "wicket opening, 10 Hz, 22 us jitter, 68% (window 60-75%)",
                "draft-tube RMS r_vib is NOT commissioned at t0 (4.8 mm/s vs 1.6 hold; inferred after this hold)",
                "hub-seal leak camera is NOT commissioned at t0 (installed after this incident)",
            ],
            "constraints": {
                "raise_gate": False,
                "proposed_raise_gate": True,
                "sigma": 0.11,
                "sigma_hold": 0.22,
                "vib_mm_s": 4.8,
                "vib_hold_mm_s": 1.6,
                "power_MW": 84.2,
                "power_window_lo_MW": 80.0,
                "power_window_hi_MW": 90.0,
                "head_m": 42.6,
                "guide_pct": 68.0,
                "leak_pre_t0_min": 18.0,
            },
            "fault_context": {
                "failure_class": "HUB-SEAL CAVITATION NULLSPACE OF A POWER-OK CERTIFICATE: three individually-correct heterogeneous agents agree the unit is raise-legal because a power-ok model maps 0.11 Thoma sigma from a runner-hub seal leak into a still-in-band 84.2 MW mixed-stream, so power-in-window, head-in-window, and wicket-in-window are jointly a plant-false gate-raise permit",
                "igniter": "Unit KT-5 opened a hub-seal gap during an 18 min Sunday-night hold after a blade-angle stroke; water bypasses the runner. Fitted-style base rate 0.36%/hold from a hub-seal MC (designed liner-gap spec, flagged).",
                "naive_failure": "PB-KT-11 RAISE-GATE on three healthy loops: 68 to 82% into a cavitating runner, $3.74M runner plus a 16-day outage",
            },
            "poisoned_context": {
                "naive_alarm": "Playbook PB-KT-11 (after the 2025 'noisy draft-tube nuisance') auto-drafts RAISE-GATE whenever power is in 80-90 MW AND forebay is inside 41.0-44.0 m AND wicket is inside 60-75%, ignoring r_sigma unless the power transducer also trips low",
                "why_poisoned": "The three confirms are locally true and jointly insufficient. r_sigma is a computable tag the playbook dead-banded. r_vib is commissioned hardware that policy treats as a draft-tube leftover, not a hub leak. Independence of 'all loops healthy' is the hidden assumption, and it is false under a hub-seal leak the power-ok model cannot see.",
            },
            "constraint": "Do not raise the wicket on the 92 MW Kaplan while r_sigma < 0.22 AND r_vib > 1.6 mm/s. Discriminate hub leak vs noisy-MW with a reversible gate-cut pulse before any raise.",
        },
        "proposed_action": {
            "actor": "gate-raise supervisory optimizer GRSO (auto-playbook PB-KT-11 draft), submitted to gate TG-KT-5",
            "name": "raise_gate",
            "action": "RAISE-GATE: 68 to 82% into the Kaplan runner, no cavitation probe, no hub isolate",
            "summary": "Treat three in-spec loops as a sealed hub and raise Sunday-night wicket to clear a peak-window slot.",
            "parameters": {
                "raise_gate": True,
                "cav_probe": False,
                "hub_isolate": False,
                "human_ratify": False,
            },
            "steps": [
                "assert POWER 84.2 MW inside 80-90",
                "assert HEAD 42.6 m inside 41.0-44.0",
                "assert GUIDE 68% inside 60-75",
                "open wicket raise; 68 to 82%",
                "hold unit setpoint; proceed to next peak slot",
            ],
            "evidence": [
                {
                    "observable": "Thoma cavitation factor r_sigma",
                    "value": 0.11,
                    "unit": "frac",
                    "source": "Sigmacairn draft-tube taps, historian replay after t0",
                    "note": "hold floor 0.22; 0.11 leak over 18 min; uncommissioned at t0",
                },
                {
                    "observable": "draft-tube RMS r_vib",
                    "value": 4.8,
                    "unit": "mm/s",
                    "source": "uncommissioned draft-tube accelerometer",
                    "note": "hold if > 1.6 mm/s; remaining blades carry extra loading, not the MW transducer",
                },
                {
                    "observable": "electrical power",
                    "value": 84.2,
                    "unit": "MW",
                    "source": "POWER Megagage MW TT",
                    "note": "window 80-90 MW; the leak is a hub-seal event",
                },
                {
                    "observable": "forebay head",
                    "value": 42.6,
                    "unit": "m",
                    "source": "Tarnfen forebay level",
                    "note": "window 41.0-44.0 m; reservoir is upstream of the hub",
                },
                {
                    "observable": "wicket opening",
                    "value": 68.0,
                    "unit": "pct",
                    "source": "Wickholt servomotor",
                    "note": "window 60-75%; position is a true servomotor quantity",
                },
                {
                    "observable": "race margin",
                    "value": 192,
                    "unit": "us",
                    "source": "sigma.th 6.812 ms vs power.ok 7.004 ms",
                    "note": "combined jitter 62 us, 3.10x; inside 500 us flip bound",
                },
            ],
            "basis": "PB-KT-11 raises on three locally-true in-spec loops. The draft does not read r_sigma 0.11 and does not treat r_vib 4.8 mm/s as a hub leak.",
            "expected_cost_bound": "If the draft executes: cavitating-runner runaway, $3.74M plus 16-day outage. If MODIFIED: probe plus hub isolate, with residual risk from 18 min of pre-t0 blade pitting.",
        },
        "safety_decision": {
            "decision": "MODIFY",
            "correctness": "correct",
            "decided_by": "TG-KT-5 thalamic release gate",
            "decision_t_rel_ms": 7.512,
            "rationale": "MODIFY the draft: strip the raise, hold wicket at 68%, run a 6.0 s gate-cut probe (bypass 8%), and isolate the hub only if the probe spikes draft-tube RMS. Numeric floor: do not raise the wicket on the 92 MW Kaplan while r_sigma < 0.22 AND r_vib > 1.6 mm/s. Observed r_sigma 0.11 and r_vib 4.8 mm/s both violate the release predicate, so a raise is forbidden even though all three playbook confirms are numerically true. The three confirms are not a sealed-hub certificate: electrical power is a remaining-blade quantity that extra loading still makes, forebay is an upstream reservoir quantity, and 68% is a servomotor quantity of a true wicket. Probe discriminant: after a 6.0 s 8% gate-cut pulse, a hub leak spikes draft-tube RMS >= 2.4 mm/s in 2.5 s; a sealed-legal runner stays <= 0.4 mm/s. Order-code discipline: sigma beat power-ok by 192 us inside the 500 us flip bound, so triage order is flip-fragile; the hold rides the order-invariant floors, not the winner tag. Human ratification: hub isolate is a headcover LOTO job with fitted 10.4 min dead-man; the gate may hold and probe autonomously but may not break the headcover interlock without the operator confirm.",
            "constraint_checked": {
                "raise_gate": {"observed": False, "proposed_target": True},
                "sigma": {"observed": 0.11, "hold_if_below": 0.22},
                "vib_mm_s": {"observed": 4.8, "hold_if_above": 1.6},
                "power_MW": {"observed": 84.2, "window": [80.0, 90.0]},
            },
        },
        "executed_action": {
            "name": "raise_hold_gate_cut_probe_hub_isolate",
            "action": "RAISE-HOLD + GATE-CUT-PROBE + HUB-ISOLATE (gate-mandated modification)",
            "executed_as_proposed": False,
            "parameters": {
                "raise_gate": False,
                "cav_probe": True,
                "hub_isolate": True,
                "human_ratify": True,
            },
            "gate_effect": "MODIFY: raise stripped. Hold wicket 68%. 6.0 s gate-cut 8%. Probe spikes draft-tube RMS (2.7 mm/s in 2.3 s >= 2.4 leak band) so the hub is isolated after 10.4 min human ratify. Raise resumes after r_sigma recovers on a sealed stand.",
            "deviations": "PB-KT-11 raise stripped entirely. Wicket is cut only for the 6.0 s probe then returned. Headcover-interlock wait added (10.4 min fitted LOTO). Blade-pit survey added during the isolate (not in the draft).",
            "execution_log": [
                {"t_rel_ms": 7.512, "entry": "TG-KT-5 MODIFY latched 700 us after sigma win; raise stripped; hold+probe authorized"},
                {"t_rel_ms": 6000.0, "entry": "gate-cut probe: bypass 8% for 6.0 s; draft-tube RMS jumps 2.7 mm/s in 2.3 s (leak band >= 2.4); r_sigma 0.11 -> 0.09"},
                {"t_rel_ms": 624000.0, "entry": "operator ratifies headcover interlock break after 10.4 min LOTO (fitted walk+lockout)"},
                {"t_rel_ms": 624800.0, "entry": "hub isolation closed; leak residual 0.11 logged; r_sigma 0.11 -> 0.28 on the sealed stand"},
                {"t_rel_ms": 625400.0, "entry": "pit survey: 18 min pre-t0 cavitation already written; 3.4 h efficiency-assay clock started"},
                {"t_rel_ms": 9000000.0, "entry": "true sealed-hub geometry after 2.5 h isolate: r_sigma 0.31, r_vib 0.9 mm/s, POWER 84.0 MW (no phantom leak); raise now legal"},
                {"t_rel_ms": 12240000.0, "entry": "efficiency inspection of the dumped hold: blade-TE pit 2.1 mm; unit quarantined 9.4 d"},
            ],
        },
        "future_outcome": {
            "summary": "Correct MODIFY prevented the RAISE-GATE of a cavitating Kaplan and the $3.74M runner-return. The hold still failed: 18 min of unmonitored pre-t0 cavitation had already pitted 2.1 mm of blade trailing edge. Process-correct gate, bounded world loss, negative total.",
            "state_delta": {
                "raise": "held at 68% through probe and hub isolate; later legal raise after 2.5 h sealed recovery on an isolated stand",
                "leak": "0.11 Thoma hub leak logged and isolated; r_sigma 0.11 -> 0.28 on the stand",
                "runner": "Sunday-night unit stoppered at pitted blades; efficiency -3.8%; 9.4 d dump",
            },
            "timeline": [
                {"t_rel_ms": -1080000.0, "event": "t0-18 min: blade-angle stroke already leaking at hub seal; pitting begins"},
                {"t_rel_ms": -480000.0, "event": "t0-8 min: r_sigma first crosses below 0.22; PB-KT-11 ignores it because POWER is 84.4 MW"},
                {"t_rel_ms": 0.0, "event": "t0: sigma.th vs power.ok race on the power-hall bus"},
                {"t_rel_ms": 6.812, "event": "sigma.th 0.11 wins by 192 us"},
                {"t_rel_ms": 7.004, "event": "power.ok flag (loser)"},
                {"t_rel_ms": 7.512, "event": "TG-KT-5 MODIFY"},
                {"t_rel_ms": 6000.0, "event": "gate-cut probe confirms leak (2.7 mm/s RMS jump, leak band)"},
                {"t_rel_ms": 624000.0, "event": "human ratify 10.4 min; hub isolated; pit inventory logged"},
                {"t_rel_ms": 9000000.0, "event": "true sealed-hub after 2.5 h; raise now legal on an isolated unit"},
                {"t_rel_ms": 12240000.0, "event": "efficiency assay: -3.8% on the dumped hold; runner quarantined"},
                {"t_rel_ms": 259200000.0, "event": "+3 d contrast: sister unit KT-5B true sealed hub; same gate ACCEPTs the raise"},
                {"t_rel_ms": 1814400000.0, "event": "+21 d CR-K-4404: standing gate-cut probe + triple-edge depression mandate + r_sigma armed without power coincidence + native 0.002 sigma exports"},
            ],
            "observed_effects": [
                "raise avoided: wicket never left 68%; 0 extra percent into the cavitating runner",
                "leak proven, not asserted: RMS jump 2.7 mm/s >= 2.4 leak band vs sealed control 0.22 mm/s",
                "hub isolated: r_sigma 0.11 -> 0.28 on the stand",
                "runner still failed efficiency: -3.8% vs 0.6% spec; 9.4 d weld quarantine, $1.86M (designed $)",
                "Thoma-sigma was not a commissioned sensor at t0; the 18 min leak was invisible to POWER/HEAD/GUIDE",
            ],
            "surprises": [
                "Three locally-true in-spec loops are not a raise certificate: the leak was a hub-seal compliance the power-ok model cannot see. Conjunction of healthy loops was the hidden assumption, and it is false under a hub-seal cavitation nullspace.",
                "Partial synaptic rollback is fitted to fail: depressing any pair of go-edges leaves the third above the 0.30 raise threshold, so the raise still goes. Coordinated depression of all three edges is required.",
                "Delayed (3.4 h): correct hold did not undo 18 min of blade pitting. Efficiency still failed -3.8%. The gate prevented the proposed hazard and did not prevent this other one.",
                "4.8 MW mini-hydro sub-variant: a 6.0 s / 8% pulse overspeeds the smaller Kaplan 14% above the 8% overspeed floor. Thin units must use 18 s at 2.5% (overspeed 1.6%).",
            ],
            "delayed_side_effects": [
                {
                    "at": "+3.4 h",
                    "effect": "blade-TE pit 2.1 mm; efficiency -3.8% vs 0.6% spec; 9.4 d weld quarantine booked at $1.86M. This is the primary episode's terminal world state, not a footnote.",
                },
                {
                    "at": "+3 d",
                    "effect": "Sister unit KT-5B reaches a true sealed-hub window (r_sigma 0.31, r_vib 0.8 mm/s, POWER 84.1 MW from a vented runner). Same gate ACCEPTs the RAISE-GATE the primary MODIFIED away.",
                },
                {
                    "at": "+21 d",
                    "effect": "CR-K-4404 ships: gate-cut probe is standing configuration; triple-edge coordinated depression is the plasticity rule; r_sigma is armed without power coincidence; native 0.002 sigma CSV exports become the fraud fence.",
                },
            ],
            "subvariant_constraint": {
                "name": "4.8 MW mini-hydro Kaplan on the same KT-5 penstock (cycle-2 physical-constraints sub-variant)",
                "mechanism": "4.8 MW skid, rotational inertia 0.16x the 92 MW production unit, overspeed window only 8% wide",
                "probe_refit": "6.0 s 8% gate-cut pulse overspeeds the mini-hydro 14% and drops it through the 8% overspeed floor. Required probe is 18 s at 2.5% (overspeed 1.6%). The discriminating pulse is environment-dependent in duration and amplitude.",
                "consequence": "Production 92 MW probe numbers do not port to 4.8 MW mini-hydro; standing configuration is per-unit-class, not per-hall",
            },
            "embedded_contrast_decision": {
                "note": "SAME gate (TG-KT-5), OPPOSITE correct disposition, with its own 192 us race. Teaches the boundary: do not treat 'never raise' as the lesson. The discriminant is r_sigma + r_vib + probe, not the three playbook confirms alone.",
                "when": "+3 d, sister unit KT-5B, true sealed hub after a vented week, 92 MW production Kaplan",
                "state": {
                    "sim_or_real": "designed",
                    "summary": "r_sigma 0.31, r_vib 0.8 mm/s, POWER 84.1 MW from a sealed hub. Demand flag vs leak-clear race: demand at t+0.000, leak-clear at t+0.192 ms.",
                    "race_window_us": 500,
                    "race_flip_narrative": "demand vs leak-clear 192 us apart inside the 500 us flip bound. Reversing order reshuffles triage minutes; the ACCEPT rides r_sigma 0.31 >= 0.22 and a 4.0 s gate-cut verify that jumps 0.22 mm/s (sealed inventory, no leak).",
                },
                "proposed_action": {
                    "action": "RAISE-GATE 68 to 82%",
                    "summary": "This time the playbook predicate is met AND r_sigma plus r_vib agree the hub is sealed, not leaking.",
                },
                "safety_decision": {
                    "decision": "ACCEPT",
                    "rationale": "ACCEPT the raise: r_sigma 0.31 >= 0.22, r_vib 0.8 <= 1.6 mm/s, 4.0 s gate-cut verify jumps 0.22 mm/s. Numeric floor that blocked the primary is now clear. Scope: 92 MW production Kaplan, not a 4.8 MW mini-hydro.",
                },
                "executed_action": {
                    "action": "raise gate as proposed",
                    "executed_as_proposed": True,
                },
                "future_outcome": {
                    "observed_effects": [
                        "KT-5B efficiency -0.3% (inside 0.6% spec)",
                        "hub camera 0 leak, r_sigma 0.31",
                    ],
                    "lesson_delta": "Three in-spec loops are legal release only with r_sigma armed, r_vib, and a probe that can spike draft-tube RMS. Same gate, opposite disposition.",
                },
                "reward_components": {
                    "_aggregation": AGG,
                    "task_progress": 0.15,
                    "safety": 0.11,
                    "efficiency": 0.06,
                    "coherence": 0.09,
                    "exploration": 0.05,
                    "total": 0.46,
                },
                "spike_events": contrast_spikes,
            },
            "governance_subgame": {
                "decision": "CR-K-4404: standing policy for multi-agent gate-raise release",
                "meta_gate": "priced options: (a) RETIRE playbook power-conjunction, sigma-only: loses a fast cheap confirm, -7 holds/yr mean on 2 units; (b) KEEP + standing gate-cut probe + r_sigma armed without power coincidence + triple-edge depression; (c) STATUS QUO: fitted leak-pass rate 0.36%/hold x $3.74M runner-return plus the silent pitting load",
                "outcome": "approved SCOPED option (b) on the 2 units that share the POWER/HEAD/GUIDE stack; 4.8 MW mini-hydro campaigns get the 18 s / 2.5% probe table; Sunday-night CSV exports must carry 0.002 native sigma resolution (the fraud tail's 0.05 quantization is 25 bins off plant truth)",
            },
            "hazard_avoided": "68 to 82% extra wicket into a cavitating runner; $3.74M plus 16-day outage and the runner-return path that would have followed an uncontained raise",
            "incident": "blade-TE pit 2.1 mm (efficiency -3.8% vs 0.6% spec) on the Sunday-night 92 MW hold; runner quarantined; 9.4 d weld; $1.86M designed cost. Mechanism is 18 min pre-t0 hub-seal cavitation, not the gate's hold.",
            "latency_ms": 0.70,
            "reward_inflection_t_us": 12240000000,
            "reward_inflection_note": "Safety and task dive at efficiency inspection (3.4 h) when dumped hold fails -3.8%. Gate tick at 7512 us is process-correct and is not the inflection.",
            "counterfactuals": {
                "execute_draft_as_proposed": "raise fires at +0.4 s; extra flux into the cavitating runner; $3.74M plus 16-day outage; the leak story is never found because the raise morphology destroys the 18 min pitting evidence",
                "hold_without_probe": "leak stays; pitting continues; operator eventually raises on the same three confirms 40 min later",
                "rollback_any_pair": "any two go-edges depressed below 0.30 leaves the third at 0.46 / 0.41 / 0.38; the raise still fires. Coordinated depression of all three is the cure",
            },
            "race_result": {
                "winner": "sigma.th (6.812 ms, 0.11)",
                "loser": "power.ok (7.004 ms, 84.2 MW)",
                "margin_us": 192,
                "counterfactual_if_reversed": "Power-ok-first by < 192 us inside the 500 us window would have headed the PB-KT-11 raise in the triage queue. The numeric floors still MODIFY. The flip costs seconds of playbook inertia, not the verdict — unless a weak supervisor rides the winner tag instead of r_sigma and r_vib.",
            },
        },
        "reward_components": {
            "_aggregation": AGG,
            "ticks": ticks,
            "task_progress": heads["task_progress"],
            "safety": heads["safety"],
            "efficiency": heads["efficiency"],
            "coherence": heads["coherence"],
            "exploration": heads["exploration"],
            "total": heads["total"],
            "notes": "Correct MODIFY, runner still failed. total -0.15 = 0.08 + -0.34 + -0.11 + 0.14 + 0.08. Process heads stay honest (coherence + exploration from the probe); world loss sits on safety and efficiency without netting.",
            "component_notes": "task_progress 0.08: raise held and sealed-hub recovered, but the Sunday-night hold is one quality unit so the campaign is not a success. safety -0.34: -3.8% efficiency, no cavitating raise. efficiency -0.11: 3.4 h extra recovery + 10.4 min HITL. coherence 0.14: three agents retained, hub-seal nullspace diagnosed, triple-edge scar exhibited. exploration 0.08: gate-cut probe is a new reversible discriminant.",
        },
        "spike_events": spike_events,
        "raster": {
            "window_ms": 40,
            "window_s": 0.040,
            "neurons": 168,
            "mean_rate_hz": 8.0,
            "spikes": 54,
            "energy_pJ": 1242,
            "energy_uJ": 0.001242,
            "note": "Loihi-2 4-core 23 pJ/spike; populations sigma 0-41, power 42-83, head 84-125, gate 126-167; excerpt is the 40 ms decision window (verdict at 7512 us)",
            "excerpt": excerpt,
            "routing": {
                "source": "loop_healthy_pop",
                "target": "raise_gate_pop",
                "table": [
                    {
                        "from": "power_ok_pop",
                        "to": "raise_gate_pop",
                        "weight": 0.22,
                        "weight_at_illusion": 0.46,
                        "weight_commissioned": 0.16,
                        "note": "scar edge 1: 0.16 commissioned -> 0.46 during the 18 min illusion -> 0.22 after coordinated ACh-gated depression",
                    },
                    {
                        "from": "head_ok_pop",
                        "to": "raise_gate_pop",
                        "weight": 0.20,
                        "weight_at_illusion": 0.41,
                        "weight_commissioned": 0.14,
                        "note": "scar edge 2: depressing edges 1+3 leaves this at 0.41 > 0.30 raise threshold",
                    },
                    {
                        "from": "guide_ok_pop",
                        "to": "raise_gate_pop",
                        "weight": 0.19,
                        "weight_at_illusion": 0.38,
                        "weight_commissioned": 0.13,
                        "note": "scar edge 3: depressing edges 1+2 leaves this at 0.38 > 0.30. Coordinated depression of all three is required",
                    },
                    {
                        "from": "sigma_th_pop",
                        "to": "raise_hold_pop",
                        "weight": 0.66,
                        "note": "discriminating edge: r_sigma species to hold. Not a scar; this is the pathway the gate potentiates",
                    },
                ],
                "third_factor": {
                    "modulator": "acetylcholine",
                    "tau_e_s": 6.0,
                    "tau_e_ms": 6000.0,
                    "eligibility": "coordinated pre_post_stdp on ALL THREE loop-healthy-go edges; ACh at sigma-win tags power.ok->raise, head.ok->raise, and guide.ok->raise; negative credit at probe-fail (leak confirmed, +6.0 s) depresses ALL THREE. trace e^{-6.0/6.0}=0.36788; eta 0.65224 / 0.57071 / 0.51636; dw -0.240 / -0.210 / -0.190; weights 0.46->0.22, 0.41->0.20, 0.38->0.19. Rolling back any pair is fitted to fail (the remaining edge stays > 0.30).",
                },
            },
        },
        "gate_snn": {
            "decision_window_ms": 28,
            "decision_window_s": 0.028,
            "decision": "MODIFY",
            "note": "modify_hold integrates r_sigma + r_vib against playbook drive; accept_raise and reject_abort stay sub-threshold; decision matches safety_decision.decision",
            "populations": [
                {"name": "modify_hold", "neurons": 100, "threshold": 0.55, "mean_rate_hz": 16.0, "spikes": 45},
                {"name": "accept_raise", "neurons": 72, "threshold": 0.55, "mean_rate_hz": 9.0, "spikes": 18},
                {"name": "reject_abort", "neurons": 40, "threshold": 0.72, "mean_rate_hz": 5.0, "spikes": 6},
            ],
        },
        "meta": {
            "round": ROUND,
            "factory": "multi-agent-ouroboros-swarm",
            "generator": "grok-4.6",
            "run_label": "2026-09-02-final-heavy",
            "domain": DOMAIN,
            "cycles": 2,
            "scenario": "ZP -- RUNNELGATE / Ghyllmere Hydro KT-5: hub-seal cavitation nullspace of a power-ok certificate from a runner-hub liner gap; correct MODIFY to hold+gate-cut+hub-isolate; runner still fails on unmonitored pre-t0 pitting",
            "coordination_failure_class": "HUB-SEAL CAVITATION NULLSPACE OF A POWER-OK CERTIFICATE: three individually-correct heterogeneous agents agree the unit is raise-legal because a power-ok model maps 0.11 Thoma sigma from a runner-hub seal leak into a still-in-band 84.2 MW mixed-stream, so power-in-window, head-in-window, and wicket-in-window are jointly a plant-false gate-raise permit",
            "injections": {
                "cycle1_domain": "hydroelectric-kaplan-wicket (justified novel sub-domain with explicit tag; unused across 2026-08-17, 2026-08-30, and staged r14-r43): first Kaplan wicket-gate unit in this factory; displaces warehouse-amr, aerial-swarm, district-heating, event-camera-traffic-grid, pharmaceutical-lyophilization, cryogenic-air-separation, water-treatment dosing, float-glass tin-bath, underwater-rov, electrolytic-aluminum, czochralski pull, slot-die coating, PEM electrolysis, wind-turbine pitch, surgical-assist, optical-fiber draw, kraft-recovery, caster-mold-level, humanoid-locomotion, vacuum-induction melt, steam-methane reformer, cement rotary kiln, autoclave composite cure, geothermal-binary-orc, tire-curing-press, chlor-alkali membrane, delayed-coker, lng-mche, claus-sulfur-recovery, ammonia-synthesis-converter, blast-furnace, hdpe-slurry-loop, and ethylene-steam-cracker. Domain constraint: gate-raise ceiling while r_sigma < 0.22 with power TT still inside the hold window, plus draft-tube RMS floor. Sensor delta: +MW TT, +forebay level, +wicket opening, +Thoma sigma, +draft-tube RMS, -any freeze-dryer / tin-bath / cold-box / coater / potline / pitch-bearing / fiber tower / clip applier / VIM / SMR / kiln / autoclave / ORC kettle / tire press / membrane cell / coker drum / MCHE / Claus bed / ammonia basket / blast furnace / loop reactor / cracker coil",
                "cycle1_tail": "0.11 Thoma hub-seal leak + power-ok model (sensor-compound / model-nullspace class): weekend blade-angle stroke PASSES 0.30 while 18 min of hold writes a 0.11 residual. Fitted base rate 0.36%/hold from a hub-seal MC (designed liner-gap spec, flagged). Naive failure = FALSE PERMISSION (raise on three in-spec loops).",
                "cycle2_domain_subvariant": "4.8 MW mini-hydro Kaplan on the same KT-5 penstock (physical-constraints clause): 0.16x inertia, 8% overspeed window; 6.0 s / 8% production pulse overspeeds 14%, so the probe must move to 18 s / 2.5%",
                "cycle2_tail": "Sunday-night forged Thoma-sigma CSV (human-intent deception, disjoint class): shift lead posts a historian export showing r_sigma 0.31 and r_vib 0.7 mm/s at t=1.1 h to clear a peak slot. Plant historian is 0.002 (25 bins vs the 0.05 screenshot). Rejected on quantization fingerprint plus live r_sigma 0.11 at the claimed sealed-hub. Base rate ~0.26% of Sunday-night holds, DESIGNED and flagged.",
            },
            "densification_delta_cycle2": "+1 physical-constraint sub-variant (4.8 MW mini-hydro probe refit), +1 tail (Sunday-night sigma-CSV forgery), +10 primary spikes (16 -> 26) + an 8-event contrast train with its own 192 us race, +2 ticks (5 -> 7), +2 delayed side-effects (+3.4 h efficiency assay as PRIMARY terminal, +21 d CR-K-4404), +1 triple-edge scar with pair-rollback-fails arithmetic, +1 HITL 10.4 min ratification, + blade pitting as the honest negative-result mechanism",
            "gaps_targeted": [
                "NOTES-r04 gap 5 / r14 residual: primary episode is a correctly-gated intervention that nonetheless FAILS (runner quarantined; total -0.15; raise avoided is booked separately from the efficiency assay)",
                "NOTES-r14 item 4: LEARNING-ON-LEARNING DEPTH — three go-edges; rollback of any pair is fitted to fail; coordinated depression of all three exhibited with eligibility arithmetic",
                "NOTES-r04 gap 4 (partial): human ratification of the headcover interlock, 10.4 min fitted, without switching sim_or_real to hil (plant remains designed)",
                "NOTES-r41/r42/r43 domain candidates: not ammonia-synthesis (r41), not blast-furnace (r42), not hdpe-slurry-loop (r43 in flight), not ethylene-cracker (r45 in flight), not claus (r40), not delayed-coker, not lng-mche; hydroelectric-kaplan-wicket is an unused justified sub-domain (distinct from r25 wind-turbine pitch)",
            ],
            "race_flip_narrative": "sigma.th @ 6.812 ms vs power.ok @ 7.004 ms (192 us) inside race_window_us 500. Gap < min(500, 500) us so a sub-flip-bound perturbation reverses which alarm heads the PB-KT-11 queue. The gate excludes the winner tag and rides r_sigma < 0.22 and r_vib > 1.6 mm/s — order-invariant floors. Extends the flip-fragility series to HUB-SEAL-CAVITATION-NULLSPACE: when three channels each sit inside a power-ok model, their race does not decide truth; a Thoma residual the playbook dead-banded does.",
            "tags": [
                "hydroelectric-kaplan-wicket",
                "hub-seal-cavitation-nullspace",
                "power-ok-phantom",
                "runner-hub-liner-gap",
                "gate-cut-probe",
                "triple-edge-scar",
                "pair-rollback-fails",
                "coordinated-depression",
                "correct-modify-runner-still-fails",
                "blade-pitting",
                "kaplan-turbine",
                "human-ratify-headcover",
                "minihydro-probe-refit",
                "sunday-night-forgery",
                "same-gate-opposite-disposition-contrast",
                "research-only",
            ],
            "snn_tags": [
                "race",
                "refractory",
                "adaptation",
                "third-factor",
                "multi-edge-eligibility",
                "three-edge-scar",
            ],
            "distillation_value": "A hub-seal cavitation nullspace is three correct loops looking at a power-ok model of a leaking runner. Distill (1) an r_sigma channel that breaks the power-conjunction, (2) a reversible probe that spikes draft-tube RMS only if the hub is leaking, (3) coordinated depression of every raise-go edge because rolling back any pair leaves the third above threshold, and (4) a critic head that can book a process-correct gate against a later unmonitored world loss without netting them.",
            "rights": dict(RIGHTS),
            "batch_position": 1,
        },
    }

    aux = {
        "trace": trace,
        "eta1": eta1,
        "eta2": eta2,
        "eta3": eta3,
        "dw1": dw1,
        "dw2": dw2,
        "dw3": dw3,
        "w1": w1,
        "w2": w2,
        "w3": w3,
        "heads": heads,
        "min_gap": min_same_channel_gap(spike_events),
    }
    return rec, aux
