#!/usr/bin/env python3
from pathlib import Path

p = Path("/tmp/ttf-r105/gen_r105.py")
t = p.read_text()

t = t.replace("ttf-r105-541..495", "ttf-r105-541..545")
t = t.replace('if ids != [f"ttf-r95-{n}" for n in range(541, 546)]:',
              'if ids != [f"ttf-r105-{n}" for n in range(541, 546)]:')

# THIS_DOMAINS / PLANTS
old_dom = '''THIS_DOMAINS = {
    "arsenic-trioxide-sublimer",
    "cyclohexanone-oxime-rearranger",
    "gadolinium-electrorefiner",
    "tetrahydrofuran-dehydrator",
    "indium-phosphide-mbe",
}
THIS_PLANTS = (
    "Arsenolite-Gair",
    "Ketoxime-Dene",
    "Gadolinia-Voe",
    "Oxolane-Reen",
    "Phosphide-Cairn",
)'''
new_dom = '''THIS_DOMAINS = {
    "osmium-tetroxide-absorber",
    "hexamethylene-diisocyanate-phosgenator",
    "nylon-12-laurolactam-cracker",
    "pvdf-emulsion-kettle",
    "peek-polycondensation-still",
}
THIS_PLANTS = (
    "Osmyl-Haugh",
    "Diisocyan-Sike",
    "Dodecalact-Ing",
    "Difluorene-Wath",
    "Nucleo-Peek",
)'''
if old_dom not in t:
    raise SystemExit("THIS_DOMAINS block missing")
t = t.replace(old_dom, new_dom, 1)

extra_ban = '''
BANNED_DOMAINS |= {
    "bismuth-oxychloride-precipitator",
    "antimony-trioxide-furnace",
    "tungsten-blue-oxide-kiln",
    "rhenium-heptoxide-scrubber",
    "palladium-sponge-reducer",
    "caprolactone-baeyer-villiger",
    "polyether-polyol-alkoxylation",
    "indium-phosphide-lpe",
    "boron-nitride-hotpress",
    "potassium-permanganate-oxidizer",
    "hexamethylenediamine-hydrogenator",
    "ethyl-acetate-tishchenko",
    "precipitated-silica-reactor",
    "nmc-precursor-coprecip",
    "copper-foil-electrodeposition",
    "hexamethylene-diamine-hydrogenator",
    "mek-dehydrogenation-bed",
    "zirconium-kroll-retort",
    "linear-alkylbenzene-hf-alkylation",
    "lactide-ring-opening",
    "arsenic-trioxide-sublimer",
    "cyclohexanone-oxime-rearranger",
    "gadolinium-electrorefiner",
    "tetrahydrofuran-dehydrator",
    "indium-phosphide-mbe",
    "ldpe-autoclave",
    "ethylene-oxide-tubular",
    "float-glass-tin-bath",
    "polybutadiene-solution-kettle",
    "cobalt-electrowin-cell",
    "nitrogen-trifluoride-cell",
    "toluene-diisocyanate-phosgenator",
    "synthetic-cryolite-kettle",
    "ammonium-perchlorate-crystallizer",
    "trimethylaluminum-still",
    "sodium-dithionite-reducer",
    "methyl-isobutyl-ketone-still",
    "lithium-cobalt-oxide-calciner",
    "gamma-butyrolactone-dehydro",
    "ppta-polymerizer",
}
BANNED_PLANT_FRAGMENTS = BANNED_PLANT_FRAGMENTS + (
    "Bismite-Scaur",
    "Stibine-Tosson",
    "Blueox-Kaim",
    "Perrhen-Hopehead",
    "Pallad-Wapentake",
    "Caprol-Stang",
    "Alkoxyl-Nab",
    "Indphos-Lythe",
    "Nitridex-Dike",
    "Permang-Edge",
    "Diamine-Law",
    "Acetate-Glen",
    "Silica-Leat",
    "Precursor-Moss",
    "Foil-Crag",
    "Adnamine-Wray",
    "Mekone-Howe",
    "Zirconia-Yair",
    "Alkylate-Naze",
    "Polylact-Eyot",
    "Arsenolite-Gair",
    "Ketoxime-Dene",
    "Gadolinia-Voe",
    "Oxolane-Reen",
    "Phosphide-Cairn",
    "Ldpe-Grain",
    "Oxirane-Clough",
    "Tinbath-Howe",
    "Diene-Riggs",
    "Cobalt-Wyke",
    "Trifluor-Yett",
    "Tolylene-Swale",
    "Cryolith-Brae",
    "Ammperch-Stoup",
    "Alkylal-Voe",
    "Dithion-Hawse",
    "Mibk-Grain",
    "Lithcox-Beck",
    "Gbl-Reen",
    "Ppta-Slack",
    "Dimcarb-Twine",
    "Etherbut-Lynns",
    "Perchlate-Meres",
    "Pentaol-Croftle",
    "Fluoropl-Staithe",
)

'''
marker = "def energy(spikes: int)"
if marker not in t:
    raise SystemExit("energy marker missing")
t = t.replace(marker, extra_ban + marker, 1)

# longest-first unique token swaps for 541/543/544/545 (and leftover 542 nouns until rewrite)
pairs = [
    ("arsenic-trioxide-sublimer", "osmium-tetroxide-absorber"),
    ("cyclohexanone-oxime-rearranger", "hexamethylene-diisocyanate-phosgenator"),
    ("gadolinium-electrorefiner", "nylon-12-laurolactam-cracker"),
    ("tetrahydrofuran-dehydrator", "pvdf-emulsion-kettle"),
    ("indium-phosphide-mbe", "peek-polycondensation-still"),
    ("simulated-thf-dehydrator", "simulated-pvdf-kettle"),
    ("Arsenolite-Gair", "Osmyl-Haugh"),
    ("Ketoxime-Dene", "Diisocyan-Sike"),
    ("Gadolinia-Voe", "Dodecalact-Ing"),
    ("Oxolane-Reen", "Difluorene-Wath"),
    ("Phosphide-Cairn", "Nucleo-Peek"),
    ("AG-7", "OH-8"),
    ("KD-4", "DS-5"),
    ("GV-HIL", "DI-HIL"),
    ("OR-6", "DW-2"),
    ("PC-4", "NP-6"),
    ("Sublimer S-3", "Absorber A-4"),
    ("sublimer S-3", "absorber A-4"),
    ("sublimer pass", "absorber pass"),
    ("white-arsenic sublimer bus", "osmium-tetroxide absorber bus"),
    ("white-arsenic pass", "tetroxide-scrubber pass"),
    ("white arsenic", "OsO4-wet packing"),
    ("White-arsenic", "Osmium-tetroxide"),
    ("white-arsenic", "tetroxide-wet packing"),
    ("retort-shell crack", "packing-bed dump"),
    ("retort-shell", "packing-bed"),
    ("retort rupture", "packing collapse"),
    ("retort shell", "packing bed"),
    ("torn retort shell", "collapsed packing bed"),
    ("Condenser-boot AE", "Packing-bed AE"),
    ("condenser boot", "packing bed"),
    ("condenser-boot", "packing-bed"),
    ("boot isolate", "packing isolate"),
    ("ae.shell.crack", "ae.pack.dump"),
    ("relay.ae.shell", "relay.ae.pack"),
    ("lif.shell", "lif.pack"),
    ("as.vapor.gNm3", "oso4.vapor.gNm3"),
    ("relay.as.vapor", "relay.oso4.vapor"),
    ("thalamic-relay.as2o3-vapor", "thalamic-relay.oso4-vapor"),
    ("spikenaut.policy.air-clamp", "spikenaut.policy.liquor-clamp"),
    ("policy.air_clamp", "policy.liquor_clamp"),
    ("pop_budget(\"air_clamp\"", "pop_budget(\"liquor_clamp\""),
    ("relay.pt.air", "relay.pt.liquor"),
    ("pt.air.bar", "pt.liquor.bar"),
    ("cruise_air_flow", "cruise_liquor_flow"),
    ("clamped_air_flow", "clamped_liquor_flow"),
    ("as2o3-vapor", "oso4-vapor"),
    ("As2O3 vapor", "OsO4 vapor"),
    ("As2O3", "OsO4"),
    ("as_cap_gNm3", "oso4_cap_gNm3"),
    ("observed_as_gNm3", "observed_oso4_gNm3"),
    ("as_gNm3", "oso4_gNm3"),
    ("as_cap", "oso4_cap"),
    ("predicted_unclamped_next_gNm3", "predicted_unclamped_next_gNm3"),
    ("air-header PT", "liquor-header PT"),
    ("air header PT", "liquor header PT"),
    ("air-header", "liquor-header"),
    ("air header", "liquor header"),
    ("Combustion air PT", "Liquor header PT"),
    ("combustion header", "liquor header"),
    ("compressor lock", "liquor-pump lock"),
    ("header_hold", "header_hold"),
    ("air_tph", "liquor_tph"),
    ("air_bar", "liquor_bar"),
    ("air_cap_bar", "liquor_cap_bar"),
    ("air_clamp", "liquor_clamp"),
    ("clamped_air_tph", "clamped_liquor_tph"),
    ("t/h air", "t/h liquor"),
    ("air 16.0", "liquor 16.0"),
    ("air 9.2", "liquor 9.2"),
    ("Holding 16.0 t/h", "Holding 16.0 t/h liquor"),
    ("UV-absorption vapor slot versus the air-header PT publisher",
     "UV-absorption tetroxide slot versus the liquor-header PT publisher"),
    ("vapor cell", "tetroxide UV cell"),
    ("off-gas UV OsO4 vapor cell", "off-gas UV OsO4 cell"),
    ("off-gas UV As2O3 vapor cell", "off-gas UV OsO4 cell"),
    ("feed-screw Coriolis", "liquor Coriolis"),
    ("finish the sublimer pass", "finish the absorber pass"),
    ("dumping tetroxide-wet packing dust", "dumping OsO4-wet packing"),
    ("AG-7 absorber pass incomplete", "OH-8 absorber pass incomplete"),
    ("mission", "mission"),
    # 543 nylon-12
    ("gadolinium-refiner bus", "laurolactam-cracker bus"),
    ("gadolinium cell", "laurolactam cracker"),
    ("gadolinium refiner", "laurolactam cracker"),
    ("ae.gd.pps", "ae.l12.pps"),
    ("relay.ae.gd", "relay.ae.l12"),
    ("thalamic-relay.gd-ae", "thalamic-relay.l12-ae"),
    ("spikenaut.policy.gd-hold", "spikenaut.policy.l12-hold"),
    ("policy.gd_hold", "policy.l12_hold"),
    ("pop_budget(\"gd_hold\"", "pop_budget(\"l12_hold\""),
    ("i.cell.kA", "p.crack.MW"),
    ("relay.i.cell", "relay.p.crack"),
    ("policy.ka_go", "policy.mw_go"),
    ('pop("ka_go"', 'pop("mw_go"'),
    ("Cell Gd-2", "Cracker L-3"),
    ("cell Gd-2", "cracker L-3"),
    ("Gd-2", "L-3"),
    ("cathode puck", "lining AE puck"),
    ("Cathode AE", "Lining AE"),
    ("cathode AE", "lining AE"),
    ("growling cathode", "growling lining"),
    ("growling-cathode", "growling-lining"),
    ("Hall ammeters do not outrank the puck.", "Cracker kW meters do not outrank the puck."),
    ("cell CT", "cracker CT"),
    ("Cell CT", "Cracker CT"),
    ("cell-CT", "cracker-CT"),
    ("cell current", "cracker power"),
    ("cell-current", "cracker-power"),
    ("legal cell current", "legal cracker power"),
    ("cell reset", "cracker reset"),
    ("electrorefiner stand", "cracker HIL stand"),
    ("HIL gadolinium", "HIL laurolactam"),
    ("dispatch_tap", "dispatch_cracker"),
    ("hold_cell", "hold_cracker"),
    ("cell_kA", "cracker_MW"),
    ("cell_cap_kA", "cracker_cap_MW"),
    ("ae-vs-ka", "ae-vs-mw"),
    ("kA still legal", "MW still legal"),
    ("trims kA", "trims MW"),
    ("Current was legal", "Power was legal"),
    ("the cathode was not", "the lining was not"),
    ("HIL slip not dispatched", "HIL cracker not dispatched"),
    ("11 MW tap", "3.4 MW tap"),
    ("11 MW", "3.4 MW"),
    ("mw\", 11.0", "mw\", 3.4"),
    ("proposed_mw", "proposed_mw"),
    # keep 11.0 in parameters? will set below via more specific
    ("Rectifier CT remains 36 kA, 14 kA shy of the 50 kA trip",
     "Cracker CT remains 2.8 MW, 1.7 shy of the 4.5 MW trip"),
    ("36 kA", "2.8 MW"),
    ("50 kA", "4.5 MW"),
    ("50 cap", "4.5 cap"),
    ("current-first", "power-first"),
    ("Current-first", "Power-first"),
    ("energize a noisy cathode", "energize a noisy lining"),
    ("Keep Gd-2 from dispatching", "Keep L-3 from dispatching"),
    ("noisy cathode while cell current remains under",
     "noisy lining while cracker power remains under"),
    ("its own cap.", "its own cap."),
    ("tap-to-tap encoder", "lactam-feed encoder"),
    ("electrolyte TC", "cracker wall TC"),
    ("ae_cap_pps", "ae_cap_pps"),
    # 544 PVDF
    ("packed dehydrator C-9", "emulsion kettle K-9"),
    ("Column C-9", "Kettle K-9"),
    ("C-9", "K-9"),
    ("wet-THF", "VDF-monomer"),
    ("wet THF", "VDF monomer"),
    ("THF-dehydrator", "PVDF-emulsion"),
    ("THF dehydration", "PVDF emulsion"),
    ("THF feed", "VDF feed"),
    ("legal THF", "legal VDF"),
    ("thf_tph", "vdf_tph"),
    ("feed_thf_14", "feed_vdf_86"),
    ("dens.bed.m", "dens.latex.wt"),
    ("relay.dens.bed", "relay.dens.latex"),
    ("thalamic-relay.thf-level", "thalamic-relay.pvdf-level"),
    ("spikenaut.policy.bed-go", "spikenaut.policy.latex-go"),
    ("policy.bed_go", "policy.latex_go"),
    ("pop_budget(\"bed_go\"", "pop_budget(\"latex_go\""),
    ("policy.skin_hold", "policy.jacket_hold"),
    ('pop("skin_hold"', 'pop("jacket_hold"'),
    ('pop("bed_veto"', 'pop("latex_veto"'),
    ("tc.skin.C", "tc.jacket.C"),
    ("relay.tc.skin", "relay.tc.jacket"),
    ("nuclear densitometer on packed bed", "nuclear densitometer on latex kettle"),
    ("nuclear gauge reads 11.2 m versus a", "nuclear gauge reads 28.4 wt% versus a"),
    ("15.0 m flood trip", "36.0 wt% coagulum trip"),
    ("bed 11.2 m", "latex 28.4 wt%"),
    ("Bed level 11.2 m", "Latex solids 28.4 wt%"),
    ("bed 15.0 m", "latex 36.0 wt%"),
    ("skin 72 C", "jacket 62 C"),
    ("Skin 72 C", "Jacket 62 C"),
    ("90 C", "85 C"),
    ("skin TC", "jacket TC"),
    ("Skin TC", "Jacket TC"),
    ("skin-first", "jacket-first"),
    ("Skin-first", "Jacket-first"),
    ("skin-TC", "jacket-TC"),
    ("idle a dry column", "idle a quiet PVDF train"),
    ("dehydration pass", "emulsion pass"),
    ("bed <= 15.0 m and skin <= 90 C", "latex <= 36.0 wt% and jacket <= 85 C"),
    ("bed_m", "latex_wt"),
    ("bed_cap_m", "latex_cap_wt"),
    ("observed_bed_m", "observed_latex_wt"),
    ("skin_C", "jacket_C"),
    ("skin_cap_C", "jacket_cap_C"),
    ("observed_skin_C", "observed_jacket_C"),
    ("water_wt_pct", "emulsifier_wt_pct"),
    ("water_cap_wt_pct", "emulsifier_cap_wt_pct"),
    ("proposed_thf_tph", "proposed_vdf_tph"),
    ("14.0 t/h wet", "8.6 t/h VDF"),
    ("14.0 t/h", "8.6 t/h"),
    ("legal_thf_stdp", "legal_vdf_stdp"),
    ("dens-vs-tc", "latex-vs-jacket"),
    ("already-legal wet-THF dehydration feed", "already-legal VDF emulsion feed"),
    ("restacks C-9", "restacks K-9"),
    ("delta-P bed", "delta-P kettle"),
    ("wet-THF Coriolis", "VDF Coriolis"),
    # 545 PEEK
    ("MBE chamber M-2", "PEEK still S-1"),
    ("Chamber M-2", "Still S-1"),
    ("chamber M-2", "still S-1"),
    ("M-2", "S-1"),
    ("substrate well is 482 C, 28 K shy of the", "melt well is 318 C, 27 K shy of the"),
    ("510 C stack limit", "345 C stack limit"),
    ("InP beam flux is 1.62 ML/s versus a 1.90 ML/s trip",
     "oligomer viscosity is 2.14 Pa·s versus a 2.80 Pa·s trip"),
    ("Keeping 1.62 ML/s is lawful; a flux-first veto would shutter a quiet epi stack.",
     "Keeping 3.2 t/h is lawful; a visc-first veto would idle a quiet PEEK stack."),
    ("Run S-1 at 1.62 ML/s, keep substrate <= 510 C and flux <= 1.90 ML/s, and leave",
     "Run S-1 at 3.2 t/h, keep melt <= 345 C and oligomer <= 2.80 Pa·s, and leave"),
    ("the epi stack on schedule.", "the polycondensation on schedule."),
    ("flux.inp.MLs", "visc.olig.Pas"),
    ("tc.sub.C", "tc.melt.C"),
    ("relay.flux.inp", "relay.visc.olig"),
    ("relay.tc.sub", "relay.tc.melt"),
    ("thalamic-relay.inp-sub", "thalamic-relay.peek-melt"),
    ("spikenaut.policy.mbe-go", "spikenaut.policy.peek-go"),
    ("policy.mbe_go", "policy.peek_go"),
    ("policy.mbe_hold", "policy.peek_hold"),
    ("pop_budget(\"mbe_go\"", "pop_budget(\"peek_go\""),
    ('pop("mbe_hold"', 'pop("peek_hold"'),
    ('pop("sub_veto"', 'pop("melt_veto"'),
    ("hold_growth_MLs", "hold_peek_tph"),
    ("growth_MLs", "peek_tph"),
    ("sub_C", "melt_C"),
    ("sub_cap_C", "melt_cap_C"),
    ("observed_sub_C", "observed_melt_C"),
    ("flux_MLs", "olig_Pas"),
    ("flux_cap_MLs", "olig_cap_Pas"),
    ("executed_growth_MLs", "executed_peek_tph"),
    ("1.62 ML/s", "3.2 t/h"),
    ("1.90 ML/s", "2.80 Pa·s"),
    ("482 C", "318 C"),
    ("510 C", "345 C"),
    ("InP flux", "oligomer visc"),
    ("InP beam-flux ion gauge", "oligomer in-line viscometer"),
    ("substrate TC well", "melt TC well"),
    ("Substrate TC", "Melt TC"),
    ("substrate TC", "melt TC"),
    ("RHEED streak camera", "reboiler PT"),
    ("cracker PT (context)", "diphenylsulfone feed (context)"),
    ("this MBE bus", "this PEEK still bus"),
    ("beam-flux publisher", "viscometer publisher"),
    ("Temp-first confirms the already-legal 3.2 t/h run; flux-first would",
     "Melt-first confirms the already-legal 3.2 t/h run; visc-first would"),
    ("have treated the substrate TC as a hitch echo and looked for an extra hold.",
     "have treated the melt TC as a hitch echo and looked for an extra hold."),
    ("shutter reseq", "reboiler reseq"),
    ("Epi stack on-spec", "PEEK still on-spec"),
    ("already-legal-growth", "already-legal-peek"),
    ("sub-vs-flux", "melt-vs-visc"),
    ("legal MBE", "legal PEEK"),
    ("MBE run", "PEEK run"),
    ("MBE stack", "PEEK stack"),
    ("accept_stdp; adenosine tags the substrate-TC win as an already-legal MBE run",
     "accept_stdp; adenosine tags the melt-TC win as an already-legal PEEK run"),
    ("a legal beam-flux header can lose to substrate TC",
     "a legal viscometer header can lose to melt TC"),
    ("REJECTED an already-legal MBE run", "REJECTED an already-legal PEEK run"),
    ("idle a legal MBE stack", "idle a legal PEEK still"),
    ("Flux 3.2 t/h is under 2.80 Pa·s", "Oligomer 2.14 Pa·s is under 2.80"),
    ("flux 3.2 t/h is under 2.80 Pa·s", "oligomer 2.14 Pa·s is under 2.80"),
    ("S-1 on-spec", "S-1 on-spec"),
    ("chamber is already legal", "still is already legal"),
    ("dwell_s=240", "dwell_s=240"),
]
# apply unique replacements; skip no-ops
seen = set()
for a, b in pairs:
    if a == b:
        continue
    if a in seen:
        continue
    seen.add(a)
    t = t.replace(a, b)

p.write_text(t)
print("phase1 bytes", len(t), "plants", t.count("Osmyl-Haugh"), t.count("Arsenolite-Gair"))
print("domains", t.count("osmium-tetroxide-absorber"), t.count("arsenic-trioxide-sublimer"))
