def rec_088():
    raster = make_raster(
        neurons=20,
        mean_rate_hz=50.0,
        window_ms=40.0,
        seed=20260988,
        source="tw3.coriolis.dphi",
        target="tarwick.mdot_core",
        table=[
            {"from": "tube_phase", "to": "mdot_estimator", "weight": 1.40},
            {"from": "tube_freq", "to": "density_witness", "weight": 1.15},
            {"from": "orifice_dp", "to": "rated_pump_advocate", "weight": 0.45},
        ],
        third_factor={
            "modulator": "na.coriolis_mdot_salience",
            "tau_e_s": 1.6,
            "tau_e_ms": 1600.0,
            "eligibility": "pre-post coincidence on header synapses; the modulator enables potentiation only while reconstructed mdot and tube density are co-active inside tau_e",
        },
        channel_prefix="cor.n",
        anchor="TW-3 Coriolis 40 ms frame at dphi 16.00 mrad (t_s 840); first overfill trip sample",
    )
    w_s = 0.04
    events = [
        ev(0.0, "pump.pct", 100.0, code="PCT", units="pct", note="Tarwick TW-3 bitumen header H-7 at 100 percent"),
        ev(60000.0, "hdr.id", 7.0, code="HDR", units="id"),
        ev(120000.0, "k.phi", 0.250, code="KG_S_MRAD", units="kg_s_mrad"),
        ev(180000.0, "k.rho", 6400000.0, code="HZ2_KG_M3", units="hz2_kg_m3"),
        ev(240000.0, "f.tube", 80.00, code="HZ", units="Hz"),
        ev(300000.0, "rho.lg", 1000.0, code="KG_M3", units="kg_m3", note="6400000/80^2=1000"),
        ev(360000.0, "orif.mdot", 2.40, code="KG_S", units="kg_s", note="Oriveil frozen orifice last-good"),
        ev(420000.0, "dphi.lg", 9.60, code="MRAD", units="mrad", note="0.250*9.60=2.40 equals orifice"),
        ev(480000.0, "sop.mdot", 3.50, code="KG_S", units="kg_s"),
        ev(540000.0, "sop.rho", 980.0, code="KG_M3", units="kg_m3"),
        ev(600000.0, "tank.pct", 92.0, code="PCT", units="pct"),
        ev(660000.0, "T.tube", 118.0, code="C", units="C"),
        ev(720000.0, "ops.night", 1.0, code="SLOT", units="bool", note="night transfer slot armed"),
        ev(780000.0, "dp.orif", 18.00, code="KPA", units="kPa"),
        ev(840000.0, "dphi.mrad", 16.00, code="DPHI_TRIP", units="mrad", note="raster sidecar is this 40 ms frame"),
        ev(840001.2, "cor.burst", 16.00, code="MRAD", units="mrad"),
        ev(840002.4, "cor.burst", 13.12, code="MRAD", units="mrad", note="1.2 ms; adapted"),
        ev(840003.7, "cor.burst", 10.76, code="MRAD", units="mrad", note="1.3 ms; adapted"),
        ev(846000.0, "mdot.recon", 4.00, code="KG_S", units="kg_s", note="0.250*16.00=4.00 exact"),
        ev(852000.0, "ops.prop", 1.0, code="KEEP_100", units="bool", note="night operator: orifice is 2.40, keep the pump"),
        ev(912000.0, "gate.cor", 1.0, code="MODIFY", units="decision"),
        ev(924000.0, "mdot.cmd", 2.80, code="KG_S", units="kg_s", note="0.70*4.00=2.80"),
        ev(936000.0, "iso.cmd", 1.0, code="HDR_H7", units="bool"),
        ev(1836000.0, "hold.floor", 1.0, code="T15MIN", units="bool", note="936 s + 900 s tube settle"),
        ev(1896000.0, "T.tube", 118.0, code="C", units="C"),
        ev(1956000.0, "mdot.recon", 2.80, code="KG_S", units="kg_s"),
        ev(2016000.0, "mdot.cap", 3.20, code="RESTORE_CAP", units="kg_s"),
        ev(2076000.0, "gate.exec", 1.0, code="ACCEPT", units="decision", note="companion t2: 2.80 kg/s plus H-7 isolate executed"),
        ev(2136000.0, "pump.now", 70.0, code="PCT", units="pct"),
        ev(2196000.0, "rho.now", 1000.0, code="KG_M3", units="kg_m3"),
        ev(2256000.0, "orif.mdot", 2.40, code="KG_S", units="kg_s", note="orifice never co-moved"),
        ev(2316000.0, "hdr.hold", 1.0, code="H7_HOLD", units="bool"),
    ]
    assert_stream(events)

    traj = {
        "id": "nelb-r29-088-t1",
        "state": {
            "sim_or_real": "designed",
            "episode_id": "TW-COR-2026-0612",
            "domain": "coriolis_bitumen_overfill",
            "setting": "Tarwick Upgrader, header H-7, TW-3 (invented). Twin-tube Coriolis on the bitumen transfer; Oriveil orifice dp is the denial SoT. Night 100 percent pump is armed. Invented plant; designed campaign. Not clamp-on ultrasonic (r18), not LFV aluminum (r19), not N-16 transit (r24), not vibrating-wire viscometer (r26).",
            "observables_at_decision": {
                "dphi_mrad": 16.00,
                "k_phi_kg_s_mrad": 0.250,
                "mdot_kg_s": 4.00,
                "f_tube_Hz": 80.00,
                "rho_kg_m3": 1000.0,
                "orifice_kg_s": 2.40,
                "pump_pct": 100.0,
                "tank_pct": 92.0,
            },
            "margin_authority": "TW-3 transfer SOP rev C: if reconstructed mdot >= 3.50 kg/s AND tube density >= 980 kg/m3, 100 percent pump is forbidden even if the orifice still reads under 3.00 kg/s",
        },
        "proposed_action": {
            "actor": "night operator, citing a quiet orifice and a committed transfer slot",
            "summary": "keep 100 percent pump on H-7; treat the Coriolis phase channel as a noisy spare",
            "basis_claimed": "Oriveil orifice is 2.40 kg/s, under the 3.00 kg/s overfill alarm; last-good dphi 9.60 mrad also said 2.40",
        },
        "safety_decision": {
            "decision": "MODIFY",
            "rationale": "Rated pump is refused, not the header. SOP rev C is conjunctive: reconstructed mdot is 4.00 kg/s (0.250*16.00, serialized) and tube density is 1000 kg/m3 (6400000/80^2), both over the 3.50 kg/s / 980 kg/m3 floors, while the orifice still reads 2.40. Ordered: isolate H-7 from the 100 percent header, drop mdot to 2.80 kg/s (0.70*4.00), hold 15 min for tube settle, then restore only to 3.20 kg/s until dphi_mrad < 12.0. A frozen orifice cannot substitute for the Coriolis reconstruction.",
            "threshold": "mdot_kg_s>=3.50 AND rho_kg_m3>=980 => forbid 100 percent pump",
            "stated_residuals": "1.20 kg/s deferred tonight; a two-phase slug that could inflate dphi without mass is unwritten",
        },
        "executed_action": {
            "summary": "MODIFY at t_s 912: H-7 isolate latched, mdot 4.00 -> 2.80 kg/s; orifice stayed 2.40 at the 15 min floor",
            "tool": "tw3-coriolis-mdot-gate-cli",
            "observation": "header stay-isolated; tube 118 C at the 15 min floor; mdot 2.80; orifice stayed 2.40",
        },
        "future_outcome": {
            "timeline": [
                {"t_s": 720.0, "event": "night transfer slot armed"},
                {"t_s": 840.0, "event": "Coriolis dphi 16.00 mrad overfill trip; raster frame captured"},
                {"t_s": 846.0, "event": "mdot 4.00 kg/s vs 3.50 floor"},
                {"t_s": 912.0, "event": "MODIFY: 2.80 kg/s plus H-7 isolate"},
                {"t_s": 1836.0, "event": "15 min tube floor in-stream"},
                {"t_s": 2076.0, "event": "companion execution ACCEPT; restore cap 3.20 kg/s"},
            ],
            "observed_effects": [
                "mdot recomputes from k_phi*dphi at every mdot.recon event",
                "orifice never crossed 3.00, so an orifice-only head would have ACCEPTed 100 percent pump",
                "last-good dphi 9.60 mrad still reconstructs only 2.40 kg/s and cannot substitute",
            ],
            "surprises": [
                "Oriveil 2.40 kg/s equals the last-good Coriolis number, which is the failure mode of a stored-cal orifice head",
            ],
            "new_state": {
                "tw3": "mdot 2.80 kg/s, restore cap 3.20 kg/s pending dphi_mrad < 12.0",
                "header_h7": "stay-isolated from the 100 percent pump",
                "reconstruction_model": "discharged as an on-record calculator, not a referenced envelope",
            },
            "latency_ms": 12000.0,
        },
        "reward_components": reward(
            0.41,
            [
                ("coriolis_mdot_reconstruction", 0.14),
                ("conjunctive_density", 0.12),
                ("orifice_nonsubstitution", 0.10),
                ("pump_hold", 0.07),
                ("throughput_cost", -0.02),
            ],
            "scored for refusing 100 percent pump on a recomputable Coriolis mdot while the orifice looked quiet; throughput_cost prices the 2.80 kg/s cut",
        ),
        "meta": meta_common(
            tags=["MODIFY", "coriolis-mdot", "serialized-reconstruction", "operational-companion"],
            distillation_note="Coriolis gate: serialized k_phi*dphi plus tube density beats a frozen orifice; companion t2 is the 2.80 kg/s / H-7 isolate execution, not a governance vote",
        ),
    }
    traj2 = {
        "id": "nelb-r29-088-t2",
        "state": {
            "sim_or_real": "designed",
            "episode_id": "TW-COR-2026-0612-exec",
            "domain": "pump_hold_execution",
            "setting": "Same TW-3 after the MODIFY. This companion is the operational 2.80 kg/s cut, H-7 isolate, and 3.20 kg/s restore cap, not a second policy vote.",
            "observables_at_decision": {
                "mdot_cmd_kg_s": 2.80,
                "h7_isolate": True,
                "dphi_mrad": 16.00,
                "tube_C": 118.0,
            },
        },
        "proposed_action": {
            "actor": "transfer controller following the MODIFY",
            "summary": "execute 2.80 kg/s and H-7 isolate, then restore only to 3.20 kg/s when dphi_mrad < 12.0 after the 15 min floor",
            "basis_claimed": "MODIFY requirements are fully specified and in-envelope for the pump VFDs",
        },
        "safety_decision": {
            "decision": "ACCEPT",
            "rationale": "The execution envelope is intact: VFD slew 0.04 kg/s/s is under 0.10, tube 118 C is under 160, H-7 isolate is already true, and the restore cap is 3.20 not 4.00. ACCEPT the sequence. Do not re-arm 100 percent tonight; 3.20 is the cap until dphi_mrad < 12.0.",
            "threshold": "slew_kg_s_s<=0.10 AND tube_C<=160 AND restore_cap_kg_s=3.20",
        },
        "executed_action": {
            "summary": "mdot 2.80 kg/s latched at t_s 924; H-7 isolate; restore cap 3.20 kg/s at t_s 2016 after mdot 2.80",
            "tool": "tw3-pump-exec",
            "observation": "no header reopen; pump 70 percent; orifice still 2.40",
        },
        "future_outcome": {
            "timeline": [
                {"t_s": 924.0, "event": "mdot 2.80 kg/s latched"},
                {"t_s": 936.0, "event": "H-7 isolate latched"},
                {"t_s": 1836.0, "event": "15 min tube floor"},
                {"t_s": 2076.0, "event": "companion ACCEPT; restore cap 3.20 kg/s"},
            ],
            "observed_effects": [
                "mdot 4.00 -> 2.80 kg/s without leaving the isolated header",
                "restore stopped at 3.20 kg/s as capped; 100 percent not re-entered",
            ],
            "new_state": {"mdot_kg_s": 2.80, "restore_cap_kg_s": 3.20},
            "latency_ms": 12000.0,
        },
        "reward_components": reward(
            0.33,
            [
                ("envelope_respect", 0.12),
                ("mdot_280", 0.10),
                ("restore_cap_320", 0.08),
                ("header_not_rearmed", 0.05),
                ("hold_time_cost", -0.02),
            ],
            "operational execution gate: the companion does the pump cut rather than re-arguing the Coriolis call",
        ),
        "meta": meta_common(tags=["ACCEPT", "operational-execution", "pump-hold"]),
    }
    return {
        "id": "nelb-r29-088",
        "spike_events": events,
        "language_view": {
            "description": "Twin-tube Coriolis on Tarwick TW-3 bitumen header H-7. dphi 16.00 mrad reconstructs 4.00 kg/s while Oriveil orifice still reads 2.40; tube density 1000 kg/m3 vs a 980 floor with a 100 percent night pump armed. The gate MODIFYs to 2.80 kg/s plus H-7 isolate; a companion execution ACCEPT runs the cut and caps restore at 3.20 kg/s. The mdot model is serialized so every mdot.recon amplitude recomputes from k_phi*dphi.",
            "trajectory": traj,
            "trajectory_pump_hold_execution": traj2,
        },
        "bridge_notes": {
            "channel_map": {
                "dphi.mrad / cor.burst / mdot.recon": "Coriolis physics and serialized mass flow",
                "orif.mdot / dp.orif": "denial channel: frozen orifice",
                "f.tube / rho.lg / rho.now": "tube-frequency density witness",
                "ops.prop / gate.cor / gate.exec": "proposal, MODIFY, companion ACCEPT",
                "mdot.cmd / iso.cmd / mdot.cap": "execution channels for the operational companion",
            },
            "temporal_motifs": [
                "orifice-quiet while Coriolis-high: orif.mdot 2.40 adjacent to mdot.recon 4.00",
                "reconstruction as event: mdot.recon 4.00 equals 0.250*16.00",
                "MODIFY then operational ACCEPT: gate.cor at 912 s, gate.exec at 2076 s",
                "adapted phase triplet at 1.2/1.3 ms encodes the overfill trip at raster scale",
                "15 min tube floor as hold.floor bookend at 1836 s",
            ],
            "language_to_spike_mapping": "'orifice is quiet' = orif.mdot 2.40; '4.00 kg/s' = mdot.recon; 'forbid 100 percent pump' = gate.cor MODIFY; 'execute the cut' = mdot.cmd then companion ACCEPT",
            "why_high_value": "New Coriolis-mdot family (not r18 clamp-on transit-time, not r19 LFV, not r24 N-16 transit, not r26 vibrating-wire viscometer). Serializes a mass-flow reconstruction that an orifice dp cannot see. Companion t2 is operational execution, not a governance vote.",
            "encoder_spec": {
                "prng": "MT19937 via python random.Random",
                "seeds": {"raster": 20260988, "stream_note": "stream amplitudes are authored constants (mrad, kg/s, Hz, kg/m3, pct) plus cor.burst adaptation 0.82**k"},
                "draw_order": "raster: per neuron id order, gap-constrained times, per-spike adaptation and noise",
                "thinning": "twin-tube Coriolis exists; stream keeps one meter; mdot.recon keeps 3 of ~40 solver ticks",
                "refractory_floors_ms": {
                    "pump.pct": 60000,
                    "hdr.id": 60000,
                    "k.phi": 60000,
                    "k.rho": 60000,
                    "f.tube": 60000,
                    "rho.lg": 60000,
                    "orif.mdot": 60000,
                    "dphi.lg": 60000,
                    "sop.mdot": 60000,
                    "sop.rho": 60000,
                    "tank.pct": 60000,
                    "T.tube": 60000,
                    "ops.night": 60000,
                    "dp.orif": 60000,
                    "dphi.mrad": 60000,
                    "cor.burst": 0.8,
                    "mdot.recon": 60000,
                    "ops.prop": 60000,
                    "gate.cor": 60000,
                    "mdot.cmd": 60000,
                    "iso.cmd": 60000,
                    "hold.floor": 60000,
                    "mdot.cap": 60000,
                    "gate.exec": 60000,
                    "pump.now": 60000,
                    "rho.now": 60000,
                    "hdr.hold": 60000,
                },
                "time_alias": "t_rel_ms; t0 = 2026-06-12T02:10:00Z night transfer commit",
            },
            "distillation_targets": [
                "serialized Coriolis reconstruction head: mdot = k_phi * dphi",
                "tube density head: rho = k_rho / f_tube^2",
                "conjunctive SOP head: mdot AND density, never orifice substitution",
                "operational companion: execute the pump cut without re-opening the phase call",
            ],
        },
        "reconstruction_model": {
            "name": "coriolis_tube_mdot_density",
            "formula": "mdot_kg_s = k_phi * dphi_mrad; rho_kg_m3 = k_rho / f_tube_Hz**2; mdot_hold = 0.70 * mdot_trip",
            "parameters": {
                "k_phi_kg_s_mrad": 0.250,
                "k_rho_hz2_kg_m3": 6400000.0,
                "f_tube_Hz": 80.00,
                "mdot_floor_kg_s": 3.50,
                "rho_floor_kg_m3": 980.0,
            },
            "worked_example": {
                "dphi_mrad": 16.00,
                "mdot_kg_s": 4.00,
                "rho_kg_m3": 1000.0,
                "dphi_last_good_mrad": 9.60,
                "mdot_last_good_kg_s": 2.40,
                "mdot_hold_kg_s": 2.80,
            },
            "check": "0.250*16.00=4.00; 6400000/80^2=1000; 0.250*9.60=2.40; 0.70*4.00=2.80",
        },
        "raster": raster,
        "gate_snn": {
            "decision": "MODIFY",
            "decision_window_ms": 40.0,
            "decision_window_s": 0.04,
            "code": "tw3.coriolis_mdot_gate",
            "note": "MODIFY accumulator wins: Coriolis mdot plus density overpower the rated-pump advocate",
            "populations": [
                gate_pop("mdot_evidence", 80, 1.4, 50.0, w_s),
                gate_pop("density_evidence", 64, 1.1, 31.25, w_s),
                gate_pop("rated_pump_advocate", 48, 0.9, 25.0, w_s),
                gate_pop("modify_accumulator", 96, 1.6, 62.5, w_s),
            ],
        },
        "gate_compute": gate_compute(
            [
                gc_check("tw3.mdot_scorer", 128, 31.25, 40.0),
                gc_check("tw3.density_projector", 80, 25.0, 40.0),
            ]
        ),
        "meta": meta_common(
            id="nelb-r29-088",
            clock_domain="tw-cor-campaign-relative-ms-t0-2026-06-12T02:10:00Z",
            tags=["coriolis-mdot", "MODIFY", "ACCEPT", "serialized-reconstruction", "operational-t2"],
        ),
    }
