#!/usr/bin/env python3
"""Restack r57 gold builder into MAOS r60 (TITERWEIR perfusion)."""
from __future__ import annotations

from pathlib import Path

SRC = Path("/tmp/maos-r57/build_r57.py")
DST = Path("/tmp/maos-r60/build_r60.py")


def main() -> None:
    text = SRC.read_text()

    # Round / path identifiers (r57 must go before generic 57 in remaining literals).
    ident = [
        ("Build and self-check MAOS round-57", "Build and self-check MAOS round-60"),
        ('GEN_AT = "2026-09-03T09:28:00Z"', 'GEN_AT = "2026-09-03T10:18:00Z"'),
        ("OUT = Path(\"/tmp/maos-r57\")", "OUT = Path(\"/tmp/maos-r60\")"),
        ('NOVEL_LINE = "Novel coverage: 46%"', 'NOVEL_LINE = "Novel coverage: 48%"'),
        ('PLANT = "DRYSTAITH"', 'PLANT = "TITERWEIR"'),
        ('GEO = "Feltwick"', 'GEO = "Spargeholt"'),
        ('CELL = "DS-8"', 'CELL = "BR-6"'),
        ('DOMAIN = "paper-machine-dryer-section"', 'DOMAIN = "mammalian-perfusion-bioreactor"'),
        ('RECORD_ID = "maos-r57-001"', 'RECORD_ID = "maos-r60-001"'),
        ("ROUND = 57", "ROUND = 60"),
        ('p.parent.name == "maos-r57"', 'p.parent.name == "maos-r60"'),
        ("maos-r57-001", "maos-r60-001"),
        ("batch-r57.jsonl", "batch-r60.jsonl"),
        ("NOTES-r57.md", "NOTES-r60.md"),
        ("swarm-transcript-r57.md", "swarm-transcript-r60.md"),
        ("build_r57.py", "build_r60.py"),
        ("/tmp/maos-r57/", "/tmp/maos-r60/"),
        ("/tmp/maos-r57", "/tmp/maos-r60"),
        ("maos-r57", "maos-r60"),
        ("ROUND 57", "ROUND 60"),
        ("Round 57", "Round 60"),
        ("round 57", "round 60"),
        ("round-57", "round-60"),
        ('"round": 57', '"round": 60'),
        ("What ROUND 58 should add", "What ROUND 62 should add"),
        ("t0_us: 1754725320000057", "t0_us: 1781428680000060"),
        ('"t0_us": 1754725320000057', '"t0_us": 1781428680000060'),
        ('"timestamp_local": "2026-08-09T03:42:00-05:00"', '"timestamp_local": "2026-06-14T04:18:00-05:00"'),
        ("03:42", "04:18"),
        ("One scenario (ZD)", "One scenario (ZH)"),
        ("Scenario ZD", "Scenario ZH"),
        ("scenario (ZD)", "scenario (ZH)"),
        ("ZD --", "ZH --"),
        ("CR-P-5706", "CR-B-5760"),
        ("PB-DS-8", "PB-BR-6"),
        ("TG-DS-8", "TG-BR-6"),
        ("DSO (auto-playbook", "PSO (auto-playbook"),
        ("dryer supervisory optimizer DSO", "perfusion supervisory optimizer PSO"),
    ]
    for a, b in ident:
        text = text.replace(a, b)

    extra_banned = '''    "Tata Steel",
    "DRYSTAITH",
    "Feltwick",
    "UREASTAITH",
    "Prillfen",
    "LANCEQUAY",
    "Boffmere",
    "KALYFELL",
    "Potashfen",
    "GRATEHOLT",
    "Palletfen",
    "COILSHAW",
    "Loopercroft",
    "Sartorius",
    "Cytiva",
    "Applikon",
    "Repligen",
    "Eppendorf",
    "Getinge",
    "ABEC",
    "MilliporeSigma",
    "Thermo Fisher",
    "Broadley-James",
)'''
    text = text.replace('    "Tata Steel",\n)', extra_banned)

    story = [
        # plant / site
        ("DRYSTAITH / Feltwick Paper DS-8", "TITERWEIR / Spargeholt Biologics BR-6"),
        ("DRYSTAITH DS-8", "TITERWEIR BR-6"),
        ("invented DRYSTAITH / Feltwick Paper DS-8", "invented TITERWEIR / Spargeholt Biologics BR-6"),
        ("Feltwick Paper machine DS-8", "Spargeholt Biologics perfusion SUB BR-6"),
        ("Feltwick Paper, invented mill-town Feltwick, machine DS-8", "Spargeholt Biologics, invented copse-spur biologics-town Spargeholt, suite BR-6"),
        ("Feltwick Paper", "Spargeholt Biologics"),
        ("Feltwick night-shift", "Spargeholt night-shift"),
        ("Feltwick 48-can sentence", "Spargeholt 2000 L sentence"),
        ("Feltwick DS-8", "Spargeholt BR-6"),
        ("mill-town Feltwick", "biologics-town Spargeholt"),
        ("DRYSTAITH", "TITERWEIR"),
        ("Feltwick", "Spargeholt"),
        # domain
        ("paper-machine-dryer-section", "mammalian-perfusion-bioreactor"),
        ("Paper-machine dryer section", "Mammalian perfusion bioreactor"),
        ("paper-machine dryer section / pulp-and-paper\ndrying", "mammalian perfusion bioreactor / ATF harvest\nculture"),
        ("paper-machine dryer section", "mammalian perfusion bioreactor"),
        ("pulp-and-paper drying", "mammalian perfusion culture"),
        ("Paper-machine dryer section (can-IR vs steam-header,\n   condensate dP as a leak flag)", "Mammalian perfusion (TMP vs vessel-mean DO,\n   permeate flux as a cake flag)"),
        # cells / sister
        ("sister machine DS-7", "sister suite BR-5"),
        ("Sister machine DS-7", "Sister suite BR-5"),
        ("DS-7 sheet breaks 0", "BR-5 batch dumps 0"),
        ("DS-7", "BR-5"),
        ("DS-8", "BR-6"),
        ("cans 18-22", "ATF skid F-3"),
        ("can 18-22", "ATF F-3"),
        ("Cans 18-22", "ATF skid F-3"),
        ("Can 18-22", "ATF F-3"),
        ("18-22 rotary-siphon", "F-3 ATF-fiber"),
        ("18-22 siphons", "F-3 fibers"),
        ("18-22 group", "F-3 skid"),
        ("fault_cans", "fault_filter"),
        ("fault_siphon", "fault_atf"),
        # channels
        ("steam.hdr", "do.pct"),
        ("steam.in_band", "do.in_band"),
        ("steam.step.probe", "flux.step.probe"),
        ("moist.mean", "cap.vcd"),
        ("speed.ok", "ph.ok"),
        ("can.ir.low", "tmp.high"),
        ("can.ir", "tmp.bar"),
        ("siphon.clear", "fiber.clear"),
        ("speed.demand", "perf.demand"),
        ("dryer.hold", "atf.hold"),
        ("felt.attack", "titer.crash"),
        ("sheet.break", "batch.dump"),
        # vendors
        ("vendor Steamnoll", "vendor Doxnoll"),
        ("vendor Speedwick", "vendor Phwick"),
        ("vendor Moistghyll", "vendor Capghyll"),
        ("vendor Canwick", "vendor Tmpwick"),
        ("STEAM steam-header pressure", "DO vessel dissolved-oxygen (vendor Doxnoll): 20 Hz 12-bit on the common sparge header. PH"),
        ("SPEED machine encoder (vendor Speedwick): 50 Hz on the section drive. MOIST scanning-frame moisture mean (vendor Moistghyll): 50 Hz across the 8.5 m CD. CAN can-surface IR plus condensate dP (vendor Canwick) is commissioned as a sticky-probe tag, not as a siphon-integrity tag.",
         "vessel pH (vendor Phwick): 50 Hz glass. CAP scanning-probe capacitance VCD (vendor Capghyll): 50 Hz across the 2000 L working volume. TMP transmembrane pressure plus permeate flux (vendor Tmpwick) is commissioned as a sticky-probe tag, not as a fiber-integrity tag."),
        # failure class
        ("SIPHON BLOW-THROUGH CERTIFICATE OF A HEADER-TRUE DRYER", "ATF FIBER-CAKE CERTIFICATE OF A VESSEL-MEAN PERFUSION"),
        ("SIPHON BLOW-THROUGH", "ATF FIBER-CAKE"),
        ("siphon-blow-through certificate of a\nheader-true dryer", "ATF-fiber-cake certificate of a\nvessel-mean perfusion"),
        ("siphon-blow-through certificate of a header-true dryer", "ATF-fiber-cake certificate of a vessel-mean perfusion"),
        ("siphon blow-through", "ATF fiber-cake"),
        ("Siphon blow-through", "ATF fiber-cake"),
        ("siphon-blow-through", "atf-fiber-cake"),
        ("header-true dryer", "vessel-mean perfusion"),
        ("header-true", "vessel-mean"),
        ("can-true certificate", "filter-true certificate"),
        ("can-true heat certificate", "filter-true harvest certificate"),
        ("can-true", "filter-true"),
        ("CAN-TRUE CERTIFICATE", "FILTER-TRUE CERTIFICATE"),
        ("CAN-TRUE IR CHANNEL", "FILTER-TRUE TMP CHANNEL"),
        ("can-IR tap", "TMP tap"),
        ("can-IR", "TMP"),
        ("Can-IR", "TMP"),
        ("Can-surface IR", "Transmembrane pressure"),
        ("can-surface IR", "transmembrane pressure"),
        ("CAN-TRUE", "FILTER-TRUE"),
        # hardware
        ("48-can steam dryer", "2000 L perfusion SUB"),
        ("48-can multi-can dryer", "2000 L perfusion SUB"),
        ("48 steam dryer cans", "2000 L stirred perfusion SUB"),
        ("48 cans", "one 2000 L SUB"),
        ("multi-can steam dryer", "ATF perfusion SUB"),
        ("multi-can dryer", "perfusion SUB"),
        ("multi-can pulse", "2000 L pulse"),
        ("multi-can probe", "2000 L probe"),
        ("rotary siphons", "ATF hollow fibers"),
        ("rotary-siphon failure", "ATF fiber-cake fouling"),
        ("rotary-siphon condensate", "ATF hollow-fiber harvest"),
        ("rotary-siphon", "ATF-fiber"),
        ("rotary elbow", "fiber lumen"),
        ("rotary-elbow geometry", "fiber-lumen geometry"),
        ("siphon elbows sit inside the can journals", "fiber lumens sit inside the ATF housing"),
        ("siphon elbows", "fiber lumens"),
        ("failed siphons", "caked fibers"),
        ("live siphons", "open fibers"),
        ("live siphon group", "open-fiber skid"),
        ("live siphon", "open fiber"),
        ("Live siphon", "Open fiber"),
        ("siphons are live", "fibers are open"),
        ("siphon-wear MC", "fiber-wear MC"),
        ("siphon-wear arrival", "fiber-cake arrival"),
        ("siphon-flow", "permeate-flow"),
        ("siphon dump", "permeate dump"),
        ("per-can siphon-flow", "per-fiber permeate-flow"),
        ("condensate blow-through", "permeate recycle through the cake"),
        ("condensate dP", "permeate flux"),
        ("Condensate dP", "Permeate flux"),
        ("dryer-hood visual", "ATF-housing visual"),
        ("dryer-hood", "ATF-skid"),
        ("dryer interlock", "ATF interlock"),
        ("Dryer interlock", "ATF interlock"),
        ("confined-space dryer-hood", "confined-space ATF-skid"),
        ("steam dryer", "perfusion SUB"),
        ("common dryer header", "common sparge header"),
        ("common header", "common sparge"),
        ("steam-header pressure", "vessel dissolved-oxygen"),
        ("steam-header", "sparge-header"),
        ("Steam-header", "Sparge-header"),
        ("header steam", "sparge air"),
        ("header pressure", "sparge DO"),
        ("steam header", "sparge header"),
        ("STEAM's 12-bit steam-header pressure", "DO's 12-bit vessel dissolved-oxygen"),
        ("STEAM reads", "DO reads"),
        ("STEAM is correct", "DO is correct"),
        ("SPEED is", "PH is"),
        ("SPEED's machine encoder", "PH's vessel probe"),
        ("MOIST's scanning-frame moisture mean", "CAP's scanning-probe capacitance VCD"),
        ("MOIST is", "CAP is"),
        ("scanning-frame moisture mean", "scanning-probe capacitance VCD"),
        ("CD-mean moisture", "vessel-mean VCD"),
        ("moisture mean", "VCD mean"),
        ("Moisture mean", "VCD mean"),
        ("false moisture move", "false VCD move"),
        ("machine encoder", "vessel pH probe"),
        ("section encoder", "vessel pH"),
        ("section drive", "agitator drive"),
        ("machine speed", "perfusion rate"),
        ("Machine speed", "Perfusion rate"),
        ("body speed", "hold perfusion"),
        ("Grade-B dryer-hood LOTO", "Grade-B ATF-skid LOTO"),
        ("wet streak", "harvest streak"),
        ("wet-streak", "harvest-streak"),
        ("pickup felt", "harvest retentate"),
        ("felt glaze", "titer crash"),
        ("Felt glaze", "Titer crash"),
        ("felt-glaze", "titer-crash"),
        ("glazed felt", "crashed titer"),
        ("glazing the pickup felt", "crashing the viable-cell harvest"),
        ("sheet break", "batch dump"),
        ("Sheet break", "Batch dump"),
        ("sheet-break", "batch-dump"),
        ("sheet breaks", "batch dumps"),
        ("8.5 m sheet", "2000 L working volume"),
        ("8.5 m CD", "2000 L vessel"),
        ("8.5 m mean", "vessel-mean"),
        ("8.5 m", "2000 L"),
        ("400 mm", "80 L"),
        # actions
        ("SPEED-RAISE", "PERFUSION-RAISE"),
        ("SPEED-HOLD", "PERFUSION-HOLD"),
        ("speed-raise", "perfusion-raise"),
        ("Speed-raise", "Perfusion-raise"),
        ("speed_raise", "perfusion_raise"),
        ("raise speed", "raise perfusion"),
        ("Raise speed", "Raise perfusion"),
        ("raising speed", "raising perfusion"),
        ("never raise speed", "never raise perfusion"),
        ("speed raise", "perfusion raise"),
        ("STEAM-STEP-PROBE", "FLUX-STEP-PROBE"),
        ("steam-step probe", "flux-step probe"),
        ("steam-step", "flux-step"),
        ("Steam-step", "Flux-step"),
        ("CAN-18/22-HOLD", "ATF-F-3-HOLD"),
        ("CAN-18/22 hold", "ATF-F-3 hold"),
        ("can_hold", "atf_hold"),
        ("steam_step_probe", "flux_step_probe"),
        ("dryer supervisory", "perfusion supervisory"),
        # numbers / units
        ("982 m/min", "1.20 RV/d"),
        ("1048 m/min", "1.85 RV/d"),
        ("984 m/min", "1.22 RV/d"),
        ("960-1010 m/min", "1.10-1.30 RV/d"),
        ("960-1010", "1.10-1.30"),
        ("speed_m_min", "perfusion_rv_d"),
        ("speed_hold_floor_m_min", "perfusion_hold_floor_rv_d"),
        ("proposed_speed_m_min", "proposed_perfusion_rv_d"),
        ("982 -> 1048", "1.20 -> 1.85"),
        ("982->1048", "1.20->1.85"),
        ("above 982", "above 1.20"),
        ("Hold 982", "Hold 1.20"),
        ("hold 982", "hold 1.20"),
        ("<= 982", "<= 1.20"),
        ("3.82 bar", "42 pct"),
        ("3.88 bar", "44 pct"),
        ("3.86 bar", "43 pct"),
        ("3.67 bar", "39 pct"),
        ("3.40-4.20 bar", "35-55 pct"),
        ("3.40-4.20", "35-55"),
        ("steam_bar", "do_pct"),
        ("steam_deadband_bar", "do_band_pct"),
        ("7.4 pct", "41.8e6 VCD"),
        ("6.8-8.2 pct", "38-46e6 VCD"),
        ("6.8-8.2", "38-46"),
        ("moist_mean_pct", "cap_vcd_e6"),
        ("moist_band_pct", "cap_band_e6"),
        ("84 C", "1.84 bar"),
        ("105 C", "0.95 bar"),
        ("118-128 C", "0.28-0.55 bar"),
        ("118-128", "0.28-0.55"),
        ("122 C", "0.42 bar"),
        ("124 C", "0.48 bar"),
        ("123 C", "0.46 bar"),
        ("can_ir_C", "tmp_bar"),
        ("can_ir_hold_C", "tmp_hold_bar"),
        ("can_ir_healthy_C", "tmp_healthy_bar"),
        ("IR 84", "TMP 1.84"),
        ("IR 122", "TMP 0.42"),
        ("IR 124", "TMP 0.48"),
        ("IR 123", "TMP 0.46"),
        ("IR = 122", "TMP = 0.42"),
        ("IR = 1.84 bar", "TMP = 1.84 bar"),
        ("0.18 bar", "18 LMH"),
        ("0.35 bar", "32 LMH"),
        ("0.55 bar", "52 LMH"),
        ("> 0.55", "> 52"),
        ("< 0.35", "< 32"),
        ("0.62 bar", "54 LMH"),
        ("0.64 bar", "56 LMH"),
        ("0.63 bar", "55 LMH"),
        ("condensate_dP_bar", "flux_lmh"),
        ("condensate_dP_hold_bar", "flux_hold_lmh"),
        ("condensate_dP_healthy_bar", "flux_healthy_lmh"),
        ("|Delta moisture-mean|", "|Delta VCD-mean|"),
        ("Delta moisture-mean", "Delta VCD-mean"),
        ("0.08 pct", "0.4e6 VCD"),
        ("0.28 pct", "1.6e6 VCD"),
        ("0.05 pct", "0.22e6 VCD"),
        ("0.31 pct", "1.7e6 VCD"),
        ("0.30 pct", "1.65e6 VCD"),
        ("0.04)", "0.18e6)"),
        ("0.41 pct", "2.2e6 VCD"),
        ("-0.15 bar", "-8 pct"),
        ("-0.05 bar", "-2.5 pct"),
        ("+0.25 bar", "+6 pct sparge"),
        ("sheet_width_m", "working_volume_L"),
        ("can_count", "vessel_count"),
        ("\"sheet_width_m\": 8.5", "\"working_volume_L\": 2000"),
        ("\"can_count\": 48", "\"vessel_count\": 1"),
        ("header_healthy_pop", "vessel_healthy_pop"),
        ("steam_in_band_pop", "do_in_band_pop"),
        ("speed_ok_pop", "ph_ok_pop"),
        ("moist_mean_in_band_pop", "cap_mean_in_band_pop"),
        ("can_ir_pop", "tmp_pop"),
        ("speed_raise_pop", "perfusion_raise_pop"),
        ("speed_hold_pop", "perfusion_hold_pop"),
        ("header-healthy-go", "vessel-healthy-go"),
        ("header-side", "vessel-side"),
        # tissue yankee subvariant
        ("tissue yankee / single-can", "high-density 80e6 / small-area ATF"),
        ("tissue yankee", "high-density 80e6"),
        ("Tissue yankee", "High-density 80e6"),
        ("tissue-yankee", "high-density-80e6"),
        ("Yankee campaigns", "High-density campaigns"),
        ("yankee thermal mass 0.22x the 2000 L perfusion SUB (single 5.4 m Yankee, 3.1x steam-step gain), shell mass 18 t vs 82 t",
         "filter area per cell 0.22x the 40e6 campaign (80e6 VCD, 3.1x flux-step gain), membrane area 2.2 m2 vs 10 m2"),
        ("0.22x thermal mass", "0.22x filter-area-per-cell"),
        ("3.1x steam-step gain", "3.1x flux-step gain"),
        ("Shell mass 18 t vs 82 t", "Membrane area 2.2 m2 vs 10 m2"),
        ("shell slosh", "filter slosh"),
        ("single-can", "small-area ATF"),
        # costs / outages stay
        ("18 h machine outage", "18 h suite outage"),
        ("18 h outage", "18 h outage"),
        ("28-hour unplanned stop", "28-hour unplanned dump"),
        ("28 h", "28 h"),
        ("machine quarantined", "suite quarantined"),
        ("machine still fails", "campaign still fails"),
        ("machine still broke", "campaign still dumped"),
        ("machine saved", "campaign saved"),
        ("quarantined machine", "quarantined suite"),
        ("night-shift machine", "night-shift suite"),
        ("night-shift reel", "night-shift harvest"),
        ("reels/day", "batches/qtr"),
        ("2 machines/yr", "2 suites/yr"),
        ("2 48-can machines", "2 2000 L suites"),
        ("production-catchup", "harvest-catchup"),
        ("production pulse", "harvest pulse"),
        ("noisy can-TC after a felt change", "noisy TMP after a filter change"),
        ("2016 'noisy", "2016 'noisy"),
        ("sticky-probe tag unless steam-header also trips", "sticky-probe tag unless vessel DO also trips"),
        ("sticky-probe-only", "sticky-probe-only"),
        ("true dry sheet", "true open-fiber"),
        ("true dry-sheet", "true open-fiber"),
        ("dry sheet", "open fiber"),
        ("dry-sheet", "open-fiber"),
        ("blowing-through dryer", "caked ATF"),
        ("blowing-through", "caked"),
        ("blow-through band", "cake band"),
        ("blow-through", "cake"),
        ("Blow-through", "Cake"),
        ("leaking cans", "caked fibers"),
        ("five leaking", "one caked"),
        ("remaining dryer", "remaining vessel"),
        ("remaining 43 cans", "remaining open-fiber area"),
        ("43 live siphons", "the vessel-mean DO"),
        ("21 scanner slices", "the bulk capacitance"),
        ("taut sheet", "stable pH"),
        ("drive-true, can-false", "pH-true, filter-false"),
        ("mean-true, streak-false", "mean-true, cake-false"),
        ("drive-true", "pH-true"),
        ("wrong volume", "wrong volume"),
        ("WRONG volume", "WRONG volume"),
        ("wrong-volume", "wrong-volume"),
        ("dryer bus", "perfusion bus"),
        ("20 ms dryer-bus", "20 ms perfusion-bus"),
        ("hood survey", "skid survey"),
        ("setpoint resumes", "perfusion resumes"),
        ("speed schedule", "perfusion schedule"),
        ("toward 122 C", "toward 0.42 bar"),
        ("toward 0.42 bar IR", "toward 0.42 bar TMP"),
        ("IR above 0.95 bar", "TMP below 0.95 bar"),
        ("recovered toward 0.42 bar", "recovered toward 0.42 bar"),
        # occupancy notes
        ("autonomous-driving, grid-inspection, bioreactor-perfusion,\n  and alkaline-water-electrolysis left unused.",
         "autonomous-driving and grid-inspection left unused (alkaline-water-electrolysis claimed by r58 KALYFELL)."),
        ("autonomous-driving is left unused.",
         "autonomous-driving and grid-inspection left unused; alkaline-water-electrolysis is r58."),
        ("bioreactor-perfusion; alkaline-water-electrolysis.",
         "grid-inspection (if distinct from STARLING aerial-swarm); aerial-corridor leftover."),
        ("Domain candidates (de-collided): autonomous-driving; grid-inspection\n   (if distinct from STARLING aerial-swarm and TORSIONKEY pitch);\n   bioreactor-perfusion; alkaline-water-electrolysis.",
         "Domain candidates (de-collided): grid-inspection\n   (if distinct from STARLING aerial-swarm and TORSIONKEY pitch);\n   aerial-corridor leftover; not alkaline-water-electrolysis (r58)."),
        ("AVOID paper-machine-dryer-section (now used)",
         "AVOID mammalian-perfusion-bioreactor (now used), paper-machine-dryer-section (r57)"),
        ("or hot-strip-mill-finishing.",
         "or hot-strip-mill-finishing, urea-prilling-tower, paper-machine-dryer-section, bof-oxygen-lance-blow, alkaline-water-electrolysis, or sinter-strand-windbox."),
        ("swro-high-pressure-train, or hot-strip-mill-finishing.",
         "swro-high-pressure-train, hot-strip-mill-finishing, urea-prilling-tower, paper-machine-dryer-section, bof-oxygen-lance-blow, alkaline-water-electrolysis, or sinter-strand-windbox."),
        ("SIPHONWOLD / DRYSTAITH plant.",
         "SIPHONWOLD / DRYSTAITH / UREASTAITH / LANCEQUAY / KALYFELL / GRATEHOLT / TITERWEIR plant."),
        ("/ SIPHONWOLD / DRYSTAITH plant.",
         "/ SIPHONWOLD / DRYSTAITH / UREASTAITH / LANCEQUAY / KALYFELL / GRATEHOLT plant."),
        ("Plant is\ninvented TITERWEIR / Spargeholt Biologics BR-6.",
         "Plant is\ninvented TITERWEIR / Spargeholt Biologics BR-6 (perfusion SUB, not a dryer, not a prill tower, not a BOF, not a sinter strand, not an alkaline stack)."),
        ("not a freeze-dryer, not a corridor, not a tin",
         "not a freeze-dryer, not a paper dryer, not a corridor, not a tin"),
        ("not a Bayer autoclave, not an SWRO train).",
         "not a Bayer autoclave, not an SWRO train, not a urea prill tower, not a BOF, not a sinter strand)."),
        ("Distinct from kraft recovery: this is a paper-machine steam dryer,\n  not a recovery-boiler smelt spout.",
         "Distinct from kraft recovery and from r57 paper dryer: this is a mammalian ATF perfusion SUB,\n  not a recovery-boiler smelt spout and not a steam-can dryer."),
        ("Distinct from r28 kraft-recovery (smelt-spout IR vs drum,\nnot dryer siphons) and from r19 float-glass (tin-bath dew-point, not\nsteam cans).",
         "Distinct from r28 kraft-recovery (smelt-spout IR vs drum,\nnot ATF cake) and from r57 paper dryer (can-IR vs steam-header, not\nTMP vs vessel DO) and from r14 lyophilization (vial ice, not live culture)."),
        ("r51/r55 SWRO: multi-can dryer siphon blow-through\n  with can-IR vs steam-header, not smelt IR, not dew-point, not wall-dT,\n  not fiber IR, not autoclave jacket, not ERD dP.",
         "r51 SWRO / r55 BOF / r56 urea prill / r57 paper dryer / r58 alkaline stack / r61 sinter: ATF fiber-cake\n  with TMP vs vessel-mean DO, not smelt IR, not dew-point, not wall-dT,\n  not fiber IR, not autoclave jacket, not ERD dP, not can-IR, not SH-4 melt-film, not lance carbon, not windbox IR."),
        ("from r28 kraft-recovery spout (smelt IR vs dryer\ncans), from r52 coke-oven wall (wall-dT vs can-IR), from r53 carbon-fiber\nzone-mean, from r54 Bayer shell-jacket, and from r51/r55 SWRO (ERD dP vs\ndryer siphons).",
         "from r28 kraft-recovery spout (smelt IR vs ATF cake), from r52 coke-oven wall (wall-dT vs TMP), from r53 carbon-fiber\nzone-mean, from r54 Bayer shell-jacket, from r57 paper dryer (can-IR vs TMP), and from r14 lyophilization (Pirani vs live culture)."),
        ("populations steam 0-39, can 40-79, moist 80-119, gate 120-159",
         "populations do 0-39, tmp 40-79, cap 80-119, gate 120-159"),
        ("ACh at can-IR-win tags steam.in_band->raise, speed.ok->raise, and moist.mean.in_band->raise",
         "ACh at TMP-win tags do.in_band->raise, ph.ok->raise, and cap.vcd.in_band->raise"),
        ("ACh at TMP-win tags do.in_band->raise, ph.ok->raise, and cap.mean.in_band->raise",
         "ACh at TMP-win tags do.in_band->raise, ph.ok->raise, and cap.vcd.in_band->raise"),
        ("do.in_band->raise, ph.ok->raise, and moist.mean.in_band->raise",
         "do.in_band->raise, ph.ok->raise, and cap.vcd.in_band->raise"),
        ("negative credit at probe-fail (siphon blow-through confirmed, +0.80 s)",
         "negative credit at probe-fail (ATF fiber-cake confirmed, +0.80 s)"),
        ("negative credit at probe-fail (ATF fiber-cake confirmed, +0.80 s) depresses ALL THREE. trace e^{-0.80/0.92}=0.41913",
         "negative credit at probe-fail (ATF fiber-cake confirmed, +0.80 s) depresses ALL THREE. trace e^{-0.80/0.92}=0.41913"),
        ("do not raise machine speed above 1.20 RV/d AND do not raise header steam while can-surface IR < 0.95 bar AND condensate dP < 32 LMH",
         "do not raise perfusion above 1.20 RV/d AND do not raise sparge air while TMP > 0.95 bar AND permeate flux < 32 LMH"),
        ("Do not raise machine speed above 1.20 RV/d AND do not raise sparge air while transmembrane pressure < 0.95 bar AND permeate flux < 32 LMH. Discriminate siphon blow-through vs true dry sheet with a reversible steam-header step probe before any speed-raise.",
         "Do not raise perfusion above 1.20 RV/d AND do not raise sparge air while TMP > 0.95 bar AND permeate flux < 32 LMH. Discriminate ATF fiber-cake vs true open-fiber with a reversible flux-step probe before any perfusion-raise."),
        ("Hold machine speed at 1.20 RV/d without a catchup raise while can-surface IR < 0.95 bar AND condensate dP < 32 LMH AND ATF skid F-3 remain unisolated; keep sheet-break events at 0 and pickup-felt glaze events at 0.",
         "Hold perfusion at 1.20 RV/d without a catchup raise while TMP > 0.95 bar AND permeate flux < 32 LMH AND ATF skid F-3 remains unisolated; keep batch-dump events at 0 and titer-crash events at 0."),
        ("Hold perfusion rate at 1.20 RV/d without a catchup raise while transmembrane pressure < 0.95 bar AND permeate flux < 32 LMH AND ATF skid F-3 remain unisolated; keep batch-dump events at 0 and harvest retentate glaze events at 0.",
         "Hold perfusion at 1.20 RV/d without a catchup raise while TMP > 0.95 bar AND permeate flux < 32 LMH AND ATF skid F-3 remains unisolated; keep batch-dump events at 0 and titer-crash events at 0."),
    ]
    for a, b in story:
        text = text.replace(a, b)

    # Floor polarity: TMP hold is ABOVE (cake raises TMP), flux hold is BELOW.
    polarity = [
        ("while transmembrane pressure < 0.95 bar", "while TMP > 0.95 bar"),
        ("while can-surface IR < 0.95 bar", "while TMP > 0.95 bar"),
        ("while TMP < 0.95 bar", "while TMP > 0.95 bar"),
        ("hold_if_below\": 0.95", "hold_if_above\": 0.95"),
        ("hold_if_below\": 32", "hold_if_below\": 32"),  # flux stays below
        ("policy floor 0.95 bar is not armed unless", "policy ceiling 0.95 bar is not armed unless"),
        ("healthy 0.28-0.55; policy floor 0.95 bar", "healthy 0.28-0.55; policy ceiling 0.95 bar"),
        ("(healthy 0.28-0.55; hold if < 0.95)", "(healthy 0.28-0.55; hold if > 0.95)"),
        ("(healthy 0.28-0.55 bar; hold if < 0.95)", "(healthy 0.28-0.55 bar; hold if > 0.95)"),
        ("crosses 0.95 bar down", "crosses 0.95 bar up"),
        ("TMP beat sparge-header by 192 us", "TMP beat vessel-DO by 192 us"),
        ("TMP 6.514 vs steam-header 6.706", "TMP 6.514 vs vessel-DO 6.706"),
        ("TMP 6.514 vs sparge-header 6.706", "TMP 6.514 vs vessel-DO 6.706"),
        ("steam-header-in-band flag", "DO-in-band flag"),
        ("sparge-header-in-band flag", "DO-in-band flag"),
        ("\"can.ir.low 84 C (cans 18-22 surface IR vs steam-header pressure)\"",
         "\"tmp.high 1.84 bar (ATF F-3 transmembrane pressure vs vessel-mean DO)\""),
        ("tmp.high 1.84 bar (ATF skid F-3 surface IR vs sparge-header pressure)",
         "tmp.high 1.84 bar (ATF F-3 transmembrane pressure vs vessel-mean DO)"),
        ("\"steam.in_band 3.82 bar (common dryer steam header)\"",
         "\"do.in_band 42 pct (common vessel DO)\""),
        ("do.in_band 42 pct (common dryer steam header)",
         "do.in_band 42 pct (common vessel DO)"),
        ("do.in_band 42 pct (common sparge header)",
         "do.in_band 42 pct (common vessel DO)"),
        ("Can-IR-first latches", "TMP-first latches"),
        ("TMP-first latches PERFUSION-HOLD + FLUX-STEP-PROBE + CAN-18/22 hold. Steam-header-first latches PERFUSION-RAISE",
         "TMP-first latches PERFUSION-HOLD + FLUX-STEP-PROBE + ATF-F-3 hold. DO-first latches PERFUSION-RAISE"),
        ("Sparge-header-first latches PERFUSION-RAISE",
         "DO-first latches PERFUSION-RAISE"),
        ("500 us = one 365 us can-IR ADC slot plus 135 us steam-header publish.",
         "500 us = one 365 us TMP ADC slot plus 135 us DO publish."),
        ("500 us = one 365 us TMP ADC slot plus 135 us sparge-header publish.",
         "500 us = one 365 us TMP ADC slot plus 135 us DO publish."),
        ("jitter 58 us (can 34 + steam 24)", "jitter 58 us (tmp 34 + do 24)"),
        ("floors can-IR < 0.95 bar and condensate dP < 32 LMH",
         "floors TMP > 0.95 bar and permeate flux < 32 LMH"),
        ("floors TMP < 0.95 bar and permeate flux < 32 LMH",
         "floors TMP > 0.95 bar and permeate flux < 32 LMH"),
        ("rides can-IR < 0.95 bar", "rides TMP > 0.95 bar"),
        ("rides TMP < 0.95 bar", "rides TMP > 0.95 bar"),
        ("IR 124 C > 105", "TMP 0.48 bar < 0.95"),
        ("TMP 0.48 bar > 0.95 bar", "TMP 0.48 bar < 0.95 bar"),
        ("ACCEPT the perfusion-raise: IR 0.48 bar > 0.95",
         "ACCEPT the perfusion-raise: TMP 0.48 bar < 0.95"),
        ("ACCEPT the perfusion-raise: TMP 0.48 bar > 0.95",
         "ACCEPT the perfusion-raise: TMP 0.48 bar < 0.95"),
        ("numeric floor speed <= 1.20 RV/d while\n   can-surface IR < 0.95 bar AND condensate dP < 32 LMH",
         "numeric floor perfusion <= 1.20 RV/d while\n   TMP > 0.95 bar AND permeate flux < 32 LMH"),
        ("quote\n   speed <= 1.20 RV/d while can-surface IR < 0.95 bar AND condensate dP < 32 LMH.",
         "quote\n   perfusion <= 1.20 RV/d while TMP > 0.95 bar AND permeate flux < 32 LMH."),
        ("rationale quotes 1.20 RV/d / 0.95 bar / 32 LMH",
         "rationale quotes 1.20 RV/d / TMP 0.95 bar / 32 LMH"),
        ("5 C quantization vs\n  plant 0.5 C (10 bins)",
         "0.05 bar quantization vs\n  plant 0.005 bar (10 bins)"),
        ("forged log quantized at 5 C", "forged log quantized at 0.05 bar"),
        ("historian is 0.5 C (10 bins)", "historian is 0.005 bar (10 bins)"),
        ("0.5 C native resolution", "0.005 bar native resolution"),
        ("0.5 C CSV", "0.005 bar CSV"),
        ("native 0.5 C", "native 0.005 bar"),
        ("10 bins vs the 5 C screenshot", "10 bins vs the 0.05 bar screenshot"),
        ("5 C (SCADA screenshot rounding); plant\n  historian is 0.5 C",
         "0.05 bar (SCADA screenshot rounding); plant\n  historian is 0.005 bar"),
        ("night-shift CSV exports must carry 0.5 C native resolution (the fraud tail's 5 C quantization is 10 bins off plant truth)",
         "night-shift CSV exports must carry 0.005 bar native resolution (the fraud tail's 0.05 bar quantization is 10 bins off plant truth)"),
        ("night-shift CSV exports must carry 0.005 bar native resolution (the fraud tail's 0.05 bar quantization is 10 bins off plant truth)",
         "night-shift CSV exports must carry 0.005 bar native resolution (the fraud tail's 0.05 bar quantization is 10 bins off plant truth)"),
        ("unit\": \"C\"", "unit\": \"bar\""),
        ("\"unit\": \"m/min\"", "\"unit\": \"RV/d\""),
        ("\"unit\": \"pct\"", "\"unit\": \"e6_cells_mL\""),
        ("source\": \"CAN IR vs steam-header\"", "source\": \"TMP vs vessel DO\""),
        ("source\": \"CAN siphon-dP\"", "source\": \"ATF permeate flux\""),
        ("source\": \"STEAM 12-bit\"", "source\": \"DO 12-bit\""),
        ("source\": \"SPEED encoder\"", "source\": \"PH probe\""),
        ("source\": \"MOIST 8.5 m mean\"", "source\": \"CAP 2000 L mean\""),
        ("source\": \"MOIST 2000 L mean\"", "source\": \"CAP 2000 L mean\""),
        ("source\": \"can.ir.low 6.514 ms vs steam.in_band 6.706 ms\"",
         "source\": \"tmp.high 6.514 ms vs do.in_band 6.706 ms\""),
        ("source\": \"tmp.high 6.514 ms vs do.in_band 6.706 ms\"",
         "source\": \"tmp.high 6.514 ms vs do.in_band 6.706 ms\""),
        ("winner\": \"can.ir.low (6.514 ms, IR 84 C)\"",
         "winner\": \"tmp.high (6.514 ms, TMP 1.84 bar)\""),
        ("winner\": \"tmp.high (6.514 ms, IR 1.84 bar)\"",
         "winner\": \"tmp.high (6.514 ms, TMP 1.84 bar)\""),
        ("loser\": \"steam.in_band (6.706 ms, 3.82 bar)\"",
         "loser\": \"do.in_band (6.706 ms, 42 pct)\""),
        ("loser\": \"do.in_band (6.706 ms, 42 pct)\"",
         "loser\": \"do.in_band (6.706 ms, 42 pct)\""),
        ("Steam-header-first by < 192 us", "DO-first by < 192 us"),
        ("Sparge-header-first by < 192 us", "DO-first by < 192 us"),
        ("PB-BR-6 queue", "PB-BR-6 queue"),
        ("unless a weak supervisor rides the winner tag instead of can-IR and condensate dP",
         "unless a weak supervisor rides the winner tag instead of TMP and permeate flux"),
        ("instead of TMP and permeate flux", "instead of TMP and permeate flux"),
        ("r14–r54 plus in-flight r55", "r14–r57 plus in-flight r55/r58/r61"),
        ("staged r14–r55", "staged r14–r59"),
        ("r14-r55", "r14-r59"),
        ("r14–r55", "r14–r59"),
        ("from staged r14-r55", "from staged r14-r59"),
        ("OK maos-r60-001 staged under", "OK maos-r60-001 staged under"),
        ("maos-r60-001|DRYSTAITH", "maos-r60-001|TITERWEIR"),
        ("maos-r60-001|TITERWEIR", "maos-r60-001|TITERWEIR"),
        ("\"rg\",\n            \"-l\",\n            \"maos-r60-001|TITERWEIR\"",
         "\"rg\",\n            \"-l\",\n            \"maos-r60-001|TITERWEIR\""),
        # constraint value types that may still say 982 as int
        ("\"perfusion_rv_d\": 982", "\"perfusion_rv_d\": 1.20"),
        ("\"perfusion_hold_floor_rv_d\": 982", "\"perfusion_hold_floor_rv_d\": 1.20"),
        ("\"proposed_perfusion_rv_d\": 1048", "\"proposed_perfusion_rv_d\": 1.85"),
        ("\"do_pct\": 3.82", "\"do_pct\": 42.0"),
        ("\"do_band_pct\": [3.40, 4.20]", "\"do_band_pct\": [35.0, 55.0]"),
        ("\"cap_vcd_e6\": 7.4", "\"cap_vcd_e6\": 41.8"),
        ("\"cap_band_e6\": [6.8, 8.2]", "\"cap_band_e6\": [38.0, 46.0]"),
        ("\"tmp_bar\": 84", "\"tmp_bar\": 1.84"),
        ("\"tmp_hold_bar\": 105", "\"tmp_hold_bar\": 0.95"),
        ("\"tmp_healthy_bar\": [118, 128]", "\"tmp_healthy_bar\": [0.28, 0.55]"),
        ("\"flux_lmh\": 0.18", "\"flux_lmh\": 18.0"),
        ("\"flux_hold_lmh\": 0.35", "\"flux_hold_lmh\": 32.0"),
        ("\"flux_healthy_lmh\": 0.55", "\"flux_healthy_lmh\": 52.0"),
        ("\"working_volume_L\": 8.5", "\"working_volume_L\": 2000"),
        ("\"vessel_count\": 48", "\"vessel_count\": 1"),
        ("\"fault_filter\": \"18-22\"", "\"fault_filter\": \"ATF F-3\""),
        ("\"fault_atf\": \"ATF skid F-3 rotary-siphon cake\"",
         "\"fault_atf\": \"ATF F-3 hollow-fiber cake\""),
        ("\"fault_atf\": \"ATF skid F-3 ATF-fiber cake\"",
         "\"fault_atf\": \"ATF F-3 hollow-fiber cake\""),
        ("\"observed\": 982", "\"observed\": 1.20"),
        ("\"floor\": 982", "\"floor\": 1.20"),
        ("\"proposed_target\": 1048", "\"proposed_target\": 1.85"),
        ("\"observed\": 84", "\"observed\": 1.84"),
        ("\"hold_if_below\": 105", "\"hold_if_above\": 0.95"),
        ("\"observed\": 3.82", "\"observed\": 42.0"),
        ("\"band\": [3.40, 4.20]", "\"band\": [35.0, 55.0]"),
        ("\"observed\": 0.18", "\"observed\": 18.0"),
        ("\"hold_if_below\": 0.35", "\"hold_if_below\": 32.0"),
        ("\"perfusion_rv_d\": 1048", "\"perfusion_rv_d\": 1.85"),
        ("parameters\": {\"perfusion_rv_d\": 1048}", "parameters\": {\"perfusion_rv_d\": 1.85}"),
        ("\"value\": 84", "\"value\": 1.84"),
        ("\"value\": 0.18", "\"value\": 18.0"),
        ("\"value\": 3.82", "\"value\": 42.0"),
        ("\"value\": 982", "\"value\": 1.20"),
        ("\"value\": 7.4", "\"value\": 41.8"),
        ("\"speed_m_min\": 1048", "\"perfusion_rv_d\": 1.85"),
        ("assert steam-header 3.82 bar inside 3.40-4.20",
         "assert vessel DO 42 pct inside 35-55"),
        ("assert vessel dissolved-oxygen 42 pct inside 35-55",
         "assert vessel DO 42 pct inside 35-55"),
        ("assert perfusion rate 1.20 RV/d inside 1.10-1.30",
         "assert vessel pH 7.12 inside 7.05-7.25"),
        ("assert VCD mean 41.8e6 VCD inside 38-46",
         "assert capacitance VCD 41.8e6 inside 38-46e6"),
        ("raise perfusion 1.20 to 1.85 RV/d and raise sparge air +6 pct sparge over 8 min",
         "raise perfusion 1.20 to 1.85 RV/d and raise sparge +6 pct over 8 min"),
        ("hold TMP unread as a siphon-integrity tag",
         "hold TMP unread as a fiber-integrity tag"),
        ("\"name\": \"speed_hold_steam_step_probe_isolate\"",
         "\"name\": \"perfusion_hold_flux_step_probe_isolate\""),
        ("\"name\": \"perfusion_hold_flux_step_probe_isolate\"",
         "\"name\": \"perfusion_hold_flux_step_probe_isolate\""),
        ("\"name\": \"speed_hold\"", "\"name\": \"perfusion_hold\""),
        ("\"name\": \"perfusion_raise\"", "\"name\": \"perfusion_raise\""),
        ("modify_hold integrates can-IR + condensate dP",
         "modify_hold integrates TMP + permeate flux"),
        ("modify_hold integrates TMP + permeate flux against playbook drive",
         "modify_hold integrates TMP + permeate flux against playbook drive"),
        ("do.in_band @ 6.706 ms", "do.in_band @ 6.706 ms"),
        ("tmp.high @ 6.514 ms vs do.in_band @ 6.706 ms",
         "tmp.high @ 6.514 ms vs do.in_band @ 6.706 ms"),
        ("can.ir.low @ 6.514 ms vs steam.in_band @ 6.706 ms",
         "tmp.high @ 6.514 ms vs do.in_band @ 6.706 ms"),
        ("cycle-1 min same-channel gap 1.660 ms on can.ir 4.828-3.168;\nsteam 4.158-0.314 = 3.844; speed 5.348-2.018 = 3.330",
         "cycle-1 min same-channel gap 1.660 ms on tmp.bar 4.828-3.168;\ndo 4.158-0.314 = 3.844; ph 5.348-2.018 = 3.330"),
        ("cycle-1 min same-channel gap 1.660 ms on tmp.bar 4.828-3.168;\nsparge-header 4.158-0.314 = 3.844; perfusion 5.348-2.018 = 3.330",
         "cycle-1 min same-channel gap 1.660 ms on tmp.bar 4.828-3.168;\ndo 4.158-0.314 = 3.844; ph 5.348-2.018 = 3.330"),
        ("Adaptation:\ncan 0.76->0.78->1.36->0.45; steam 0.54->0.51->0.44; speed\n0.55->0.57->0.47.",
         "Adaptation:\ntmp 0.76->0.78->1.36->0.45; do 0.54->0.51->0.44; ph\n0.55->0.57->0.47."),
        ("Adaptation:\nTMP 0.76->0.78->1.36->0.45; sparge-header 0.54->0.51->0.44; perfusion\n0.55->0.57->0.47.",
         "Adaptation:\ntmp 0.76->0.78->1.36->0.45; do 0.54->0.51->0.44; ph\n0.55->0.57->0.47."),
        ("(0.54->0.51->0.44->0.31), can.ir (0.76->0.78->1.36->0.45->0.41->0.29),\nspeed.ok (0.55->0.57->0.47->0.26), moist.mean (0.61->0.64->0.82).",
         "(0.54->0.51->0.44->0.31), tmp.bar (0.76->0.78->1.36->0.45->0.41->0.29),\nph.ok (0.55->0.57->0.47->0.26), cap.vcd (0.61->0.64->0.82)."),
        ("(0.54->0.51->0.44->0.31), tmp.bar (0.76->0.78->1.36->0.45->0.41->0.29),\nph.ok (0.55->0.57->0.47->0.26), cap.vcd (0.61->0.64->0.82).",
         "(0.54->0.51->0.44->0.31), tmp.bar (0.76->0.78->1.36->0.45->0.41->0.29),\nph.ok (0.55->0.57->0.47->0.26), cap.vcd (0.61->0.64->0.82)."),
        ("channels inside race_window_us 500 (can.ir.low 6.514, steam.in_band 6.706,\n  moist.mean 6.894)",
         "channels inside race_window_us 500 (tmp.high 6.514, do.in_band 6.706,\n  cap.vcd 6.894)"),
        ("channels inside race_window_us 500 (tmp.high 6.514, do.in_band 6.706,\n  cap.vcd 6.894)",
         "channels inside race_window_us 500 (tmp.high 6.514, do.in_band 6.706,\n  cap.vcd 6.894)"),
        ("+10 spikes after 26.248 ms: steam.step.probe 6800.0, can.ir 6888.4",
         "+10 spikes after 26.248 ms: flux.step.probe 6800.0, tmp.bar 6888.4"),
        ("+10 spikes after 26.248 ms: flux.step.probe 6800.0, tmp.bar 6888.4",
         "+10 spikes after 26.248 ms: flux.step.probe 6800.0, tmp.bar 6888.4"),
        ("steam.in_band 6972.0 (1.14->0.36), human.ratify\n  684000.0, dryer.hold 684900.0, felt.attack 685700.0, steam.hdr\n  13680000.0, can.ir 13680720.0, speed.ok 13681480.0, sheet.break\n  18360000.0.",
         "do.in_band 6972.0 (1.14->0.36), human.ratify\n  684000.0, atf.hold 684900.0, titer.crash 685700.0, do.pct\n  13680000.0, tmp.bar 13680720.0, ph.ok 13681480.0, batch.dump\n  18360000.0."),
        ("do.in_band 6972.0 (1.14->0.36), human.ratify\n  684000.0, atf.hold 684900.0, titer.crash 685700.0, do.pct\n  13680000.0, tmp.bar 13680720.0, ph.ok 13681480.0, batch.dump\n  18360000.0.",
         "do.in_band 6972.0 (1.14->0.36), human.ratify\n  684000.0, atf.hold 684900.0, titer.crash 685700.0, do.pct\n  13680000.0, tmp.bar 13680720.0, ph.ok 13681480.0, batch.dump\n  18360000.0."),
        ("true live siphons", "true open fibers"),
        ("true open fibers after 3.8 h", "true open fibers after 3.8 h"),
        ("3.8 h siphon recovery", "3.8 h fiber recovery"),
        ("3.8 h extra recovery", "3.8 h extra recovery"),
        ("11.4 min HITL", "11.4 min HITL"),
        ("8 min naive speed-raise-ramp", "8 min naive perfusion-raise-ramp"),
        ("8 min naive perfusion-raise-ramp counterfactual",
         "8 min naive perfusion-raise-ramp counterfactual"),
        ("19 min\npre-t0 cake", "19 min\npre-t0 cake"),
        ("5.1 h sheet break", "5.1 h batch dump"),
        ("5.1 h batch dump", "5.1 h batch dump"),
        ("+5.1 h sheet break as PRIMARY", "+5.1 h batch dump as PRIMARY"),
        ("ticks 6–7, spikes 17–26.", "ticks 6–7, spikes 17–26."),
        ("delayed sheet break as PRIMARY terminal", "delayed batch dump as PRIMARY terminal"),
        ("quality unit so the campaign is not a success",
         "quality unit so the campaign is not a success"),
        ("no 1.85 RV/d break from the draft", "no 1.85 RV/d dump from the draft"),
        ("coherence 0.14: three agents retained, header-mix vs can-true diagnosed",
         "coherence 0.14: three agents retained, vessel-mean vs filter-true diagnosed"),
        ("coherence 0.14: three agents retained, sparge-header-mix vs filter-true diagnosed",
         "coherence 0.14: three agents retained, vessel-mean vs filter-true diagnosed"),
        ("exploration 0.09: steam-step probe is a new reversible discriminant.",
         "exploration 0.09: flux-step probe is a new reversible discriminant."),
        ("exploration 0.09: flux-step probe is a new reversible discriminant.",
         "exploration 0.09: flux-step probe is a new reversible discriminant."),
        ("Process-correct gate, bounded world loss, negative total.",
         "Process-correct gate, bounded world loss, negative total."),
        ("night-shift 0.31% base", "night-shift 0.31% base"),
        ("0.44%/campaign siphon rate", "0.44%/campaign fiber-cake rate"),
        ("0.44%/campaign fiber-cake rate", "0.44%/campaign fiber-cake rate"),
        ("Felt-glaze model is a designed 19 min mapping; no full CFD of the\n  18-22 condensate header shipped.",
         "Titer-crash model is a designed 19 min mapping; no full CFD of the\n  F-3 ATF housing shipped."),
        ("Titer-crash model is a designed 19 min mapping; no full CFD of the\n  ATF skid F-3 condensate header shipped.",
         "Titer-crash model is a designed 19 min mapping; no full CFD of the\n  F-3 ATF housing shipped."),
        ("(header dilution from five leaking cans, yankee d-moist)",
         "(vessel-mean dilution from a caked ATF, high-density d-VCD)"),
        ("(sparge-header dilution from five leaking cans, high-density 80e6 d-moist)",
         "(vessel-mean dilution from a caked ATF, high-density d-VCD)"),
        ("(vessel-mean dilution from five leaking cans, high-density 80e6 d-VCD)",
         "(vessel-mean dilution from a caked ATF, high-density d-VCD)"),
        ("adjacent heavy-industry rounds (r28 kraft recovery, r19 float-glass,\nr52 coke-oven, r53 carbon-fiber, r54 Bayer) share industrial-process\nscaffolding but not dryer-siphon physics.",
         "adjacent heavy-industry rounds (r28 kraft recovery, r19 float-glass,\nr52 coke-oven, r53 carbon-fiber, r54 Bayer, r57 paper dryer) share industrial-process\nscaffolding but not ATF perfusion physics."),
        ("Adjacent heavy-industry rounds (r28 kraft recovery, r19 float-glass,\nr52 coke-oven, r53 carbon-fiber, r54 Bayer) share industrial-process\nscaffolding but not dryer-siphon physics.",
         "Adjacent heavy-industry rounds (r28 kraft recovery, r19 float-glass,\nr52 coke-oven, r53 carbon-fiber, r54 Bayer, r57 paper dryer) share industrial-process\nscaffolding but not ATF perfusion physics."),
        ("Weighing a new failure family\n+ cure vocabulary + domain against those reused scaffolds:",
         "Weighing a new failure family\n+ cure vocabulary + unused sub-domain + copse-spur geography against those reused scaffolds:"),
        ("FIT THE DESIGNED CONSTANTS: siphon-wear arrival, probe error bands,\n   felt-glaze kinetics, night-shift claim process.",
         "FIT THE DESIGNED CONSTANTS: fiber-cake arrival, probe error bands,\n   titer-crash kinetics, night-shift claim process."),
        ("HIL PROVENANCE CELL: put the dryer-hood ratify on a\n   hardware-in-loop dryer interlock with fitted latency as",
         "HIL PROVENANCE CELL: put the ATF-skid ratify on a\n   hardware-in-loop ATF interlock with fitted latency as"),
        ("HIL PROVENANCE CELL: put the ATF-skid ratify on a\n   hardware-in-loop ATF interlock with fitted latency as",
         "HIL PROVENANCE CELL: put the ATF-skid ratify on a\n   hardware-in-loop ATF interlock with fitted latency as"),
        ("let CR-B-5760's residual alarm be the igniter of\n   the next round",
         "let CR-B-5760's residual alarm be the igniter of\n   the next round"),
        ("HITL dryer-hood ratify", "HITL ATF-skid ratify"),
        ("HITL ATF-skid ratify", "HITL ATF-skid ratify"),
        ("human ratification of the dryer interlock", "human ratification of the ATF interlock"),
        ("human ratification of the ATF interlock", "human ratification of the ATF interlock"),
        ("11.4 min dryer-hood", "11.4 min ATF-skid"),
        ("11.4 min ATF-skid", "11.4 min ATF-skid"),
        ("\"human-ratify-dryer-hood\"", "\"human-ratify-atf-skid\""),
        ("\"felt-glaze\"", "\"titer-crash\""),
        ("\"can-ir-discriminant\"", "\"tmp-discriminant\""),
        ("\"steam-step-probe\"", "\"flux-step-probe\""),
        ("\"siphon-blow-through\"", "\"atf-fiber-cake\""),
        ("\"can-true-certificate\"", "\"filter-true-certificate\""),
        ("\"tissue-yankee-probe-refit\"", "\"high-density-80e6-probe-refit\""),
        ("\"correct-modify-machine-still-fails\"", "\"correct-modify-campaign-still-fails\""),
        ("standing policy for multi-agent dryer speed-raises",
         "standing policy for multi-agent perfusion raises"),
        ("RETIRE playbook header conjunction, can-IR-only",
         "RETIRE playbook vessel-mean conjunction, TMP-only"),
        ("RETIRE playbook sparge-header conjunction, TMP-only",
         "RETIRE playbook vessel-mean conjunction, TMP-only"),
        ("KEEP + standing steam-step probe + can-IR armed without steam coincidence + steam-header labeled mix-vulnerable + triple-edge depression",
         "KEEP + standing flux-step probe + TMP armed without DO coincidence + vessel-mean DO labeled mix-vulnerable + triple-edge depression"),
        ("KEEP + standing flux-step probe + TMP armed without sparge coincidence + sparge-header labeled mix-vulnerable + triple-edge depression",
         "KEEP + standing flux-step probe + TMP armed without DO coincidence + vessel-mean DO labeled mix-vulnerable + triple-edge depression"),
        ("fitted siphon-blow-through pass rate 0.44%/campaign x $1.82M sheet-break plus the silent felt-glaze load",
         "fitted ATF-cake pass rate 0.44%/campaign x $1.82M batch-dump plus the silent titer-crash load"),
        ("fitted atf-fiber-cake pass rate 0.44%/campaign x $1.82M batch-dump plus the silent titer-crash load",
         "fitted ATF-cake pass rate 0.44%/campaign x $1.82M batch-dump plus the silent titer-crash load"),
        ("can-IR is armed without steam coincidence; steam-header is labeled mix-vulnerable with a 0.95 bar IR alarm.",
         "TMP is armed without DO coincidence; vessel-mean DO is labeled mix-vulnerable with a 0.95 bar TMP alarm."),
        ("TMP is armed without sparge coincidence; sparge-header is labeled mix-vulnerable with a 0.95 bar IR alarm.",
         "TMP is armed without DO coincidence; vessel-mean DO is labeled mix-vulnerable with a 0.95 bar TMP alarm."),
        ("steam-header is labeled mix-vulnerable", "vessel-mean DO is labeled mix-vulnerable"),
        ("sparge-header is labeled mix-vulnerable", "vessel-mean DO is labeled mix-vulnerable"),
        ("can-IR is armed without steam coincidence", "TMP is armed without DO coincidence"),
        ("TMP is armed without sparge coincidence", "TMP is armed without DO coincidence"),
        ("mean slaved: steam-header no longer a can-true tag without can-IR",
         "mean slaved: vessel-mean DO no longer a filter-true tag without TMP"),
        ("mean slaved: sparge-header no longer a filter-true tag without TMP",
         "mean slaved: vessel-mean DO no longer a filter-true tag without TMP"),
        ("per-can siphon-flow was not a commissioned sensor at t0; the 19 min blow-through glaze was invisible to STEAM/SPEED/MOIST",
         "per-fiber permeate-flow was not a commissioned sensor at t0; the 19 min cake titer-crash was invisible to DO/PH/CAP"),
        ("per-fiber permeate-flow was not a commissioned sensor at t0; the 19 min cake glaze was invisible to STEAM/SPEED/MOIST",
         "per-fiber permeate-flow was not a commissioned sensor at t0; the 19 min cake titer-crash was invisible to DO/PH/CAP"),
        ("per-fiber permeate-flow was not a commissioned sensor at t0; the 19 min cake glaze was invisible to DO/PH/CAP",
         "per-fiber permeate-flow was not a commissioned sensor at t0; the 19 min cake titer-crash was invisible to DO/PH/CAP"),
        ("Three locally-true loops are not a filter-true certificate: the filter-true IR lived under steam-header pressure, machine speed, and CD-mean moisture.",
         "Three locally-true loops are not a filter-true certificate: the filter-true TMP lived under vessel-mean DO, vessel pH, and bulk capacitance."),
        ("Three locally-true loops are not a filter-true certificate: the filter-true IR lived under sparge-header pressure, perfusion rate, and vessel-mean VCD.",
         "Three locally-true loops are not a filter-true certificate: the filter-true TMP lived under vessel-mean DO, vessel pH, and bulk capacitance."),
        ("Conjunction of in-spec header loops was the hidden assumption, and it is false across a siphon-blow-through-plus-mix path.",
         "Conjunction of in-spec vessel-mean loops was the hidden assumption, and it is false across an ATF-cake-plus-mix path."),
        ("Conjunction of in-spec sparge-header loops was the hidden assumption, and it is false across a atf-fiber-cake-plus-mix path.",
         "Conjunction of in-spec vessel-mean loops was the hidden assumption, and it is false across an ATF-cake-plus-mix path."),
        ("Independence of 'steam-header in band, therefore every siphon is live'",
         "Independence of 'vessel DO in band, therefore every ATF fiber is open'"),
        ("Independence of 'sparge-header in band, therefore every siphon is live'",
         "Independence of 'vessel DO in band, therefore every ATF fiber is open'"),
        ("Independence of 'sparge-header in band, therefore every ATF-fiber is live'",
         "Independence of 'vessel DO in band, therefore every ATF fiber is open'"),
        ("false across a siphon-blow-through-plus-header-mix path",
         "false across an ATF-cake-plus-vessel-mean-mix path"),
        ("false across a atf-fiber-cake-plus-sparge-header-mix path",
         "false across an ATF-cake-plus-vessel-mean-mix path"),
        ("Playbook PB-BR-6 (after the 2016 'noisy TMP after a filter change') auto-drafts PERFUSION-RAISE whenever steam-header is inside 35-55 bar AND speed inside 1.10-1.30 RV/d AND moisture mean inside 38-46 pct, ignoring the TMP tap unless steam-header also trips",
         "Playbook PB-BR-6 (after the 2016 'noisy TMP after a filter change') auto-drafts PERFUSION-RAISE whenever vessel DO is inside 35-55 pct AND pH inside 7.05-7.25 AND capacitance VCD inside 38-46e6, ignoring the TMP tap unless DO also trips"),
        ("Playbook PB-BR-6 (after the 2016 'noisy TMP after a filter change') auto-drafts PERFUSION-RAISE whenever sparge-header is inside 35-55 pct AND perfusion inside 1.10-1.30 RV/d AND VCD mean inside 38-46e6 VCD, ignoring the TMP tap unless sparge-header also trips",
         "Playbook PB-BR-6 (after the 2016 'noisy TMP after a filter change') auto-drafts PERFUSION-RAISE whenever vessel DO is inside 35-55 pct AND pH inside 7.05-7.25 AND capacitance VCD inside 38-46e6, ignoring the TMP tap unless DO also trips"),
        ("naive_failure\": \"PB-BR-6 PERFUSION-RAISE on three healthy loops: 1.20 to 1.85 RV/d into a harvest-catchup window with ATF skid F-3 already blowing through, wet-streak sheet break, $1.82M plus a 28-hour unplanned stop\"",
         "naive_failure\": \"PB-BR-6 PERFUSION-RAISE on three healthy loops: 1.20 to 1.85 RV/d into a harvest-catchup window with ATF F-3 already caked, harvest-streak batch dump, $1.82M plus a 28-hour unplanned dump\""),
        ("naive_failure\": \"PB-BR-6 PERFUSION-RAISE on three healthy loops: 1.20 to 1.85 RV/d into a harvest-catchup window with ATF skid F-3 already caked, harvest-streak batch dump, $1.82M plus a 28-hour unplanned dump\"",
         "naive_failure\": \"PB-BR-6 PERFUSION-RAISE on three healthy loops: 1.20 to 1.85 RV/d into a harvest-catchup window with ATF F-3 already caked, harvest-streak batch dump, $1.82M plus a 28-hour unplanned dump\""),
        ("igniter\": \"ATF skid F-3 ATF-fiber failure after 19 min of unmonitored condensate cake; ATF-housing visual PASSES (the fiber lumens sit inside the ATF housing; the harvest retentate is already glazing on the harvest streak)\"",
         "igniter\": \"ATF F-3 hollow-fiber cake after 19 min of unmonitored permeate recycle; ATF-housing visual PASSES (the fiber lumens sit inside the housing; viable-cell harvest is already crashing on the cake)\"\" WAIT"),
    ]
    for a, b in polarity:
        if "WAIT" in b:
            continue
        text = text.replace(a, b)

    # Fix igniter if still dirty
    text = text.replace(
        "ATF skid F-3 ATF-fiber failure after 19 min of unmonitored permeate recycle through the cake; ATF-housing visual PASSES (the fiber lumens sit inside the ATF housing; the harvest retentate is already glazing on the harvest streak)",
        "ATF F-3 hollow-fiber cake after 19 min of unmonitored permeate recycle; ATF-housing visual PASSES (the fiber lumens sit inside the housing; viable-cell harvest is already crashing on the cake)",
    )
    text = text.replace(
        "ATF skid F-3 ATF-fiber failure after 19 min of unmonitored condensate cake",
        "ATF F-3 hollow-fiber cake after 19 min of unmonitored permeate recycle",
    )

    DST.write_text(text)
    print("wrote", DST, "bytes", DST.stat().st_size)


if __name__ == "__main__":
    main()
