"""Observability plants r183-r190."""

from mill_plants import _fail, _ok

MORE = []

# r183 Grafana Beyla vs OTel auto-instrument double spans
MORE.append(
    (
        _ok(
            slug="beyla-vs-otel-auto-double",
            service="boarding-pass-svc",
            dashboard_uid="board-beyla-1",
            panel="span rate",
            query='sum(rate(traces_span_metrics_calls_total{service_name="boarding-pass-svc"}[5m]))',
            lie="Beyla eBPF HTTP spans plus OTel javaagent on the same process double-count calls; SLO 2x actual",
            false_lead="spanmetrics connector vs processor double export",
            config_path="otelcol/board-collector.yaml",
            lie_path="k8s/beyla/boarding.yaml",
            truth_name="Tempo span names beyla vs javaagent",
            reload_name="beyla",
            side="javaagent-only services unchanged",
            surfaces="Grafana Beyla vs OTel auto-instrument",
            avoided="r166 connector vs processor; Pyroscope eBPF mix",
            this_is="Beyla + javaagent double HTTP spans",
            step_note="False lead connector 4-5; two span scopes 6-8; drop Beyla HTTP 9-12.",
            search_cmd="curl -sS $GRAFANA/api/search?query=board-beyla-1 | jq -c '.[]|{uid,title}'",
            dash_cmd="curl -sS $GRAFANA/api/dashboards/uid/board-beyla-1 | jq '.dashboard.panels[0]'",
            query_cmd="curl -sS -G $MIMIR/prometheus/api/v1/query --data-urlencode 'query=sum(rate(traces_span_metrics_calls_total{service_name=\"boarding-pass-svc\"}[5m]))'",
            false_cmd="yq '.connectors.spanmetrics,.processors.spanmetrics' otelcol/board-collector.yaml",
            truth_cmd="curl -sS $TEMPO/api/traces/bb11cc22dd33ee44ff556677889900aa | jq '[.batches[].scopeSpans[]|{scope:.scope.name,n:(.spans|length)}]'",
            confirm_cmd="yq '.openPorts,.instrumentation' k8s/beyla/boarding.yaml",
            reload_cmd="kubectl -n beyla rollout restart daemonset/beyla && kubectl -n beyla rollout status daemonset/beyla --timeout=90s",
            requery_cmd="curl -sS -G $MIMIR/prometheus/api/v1/query --data-urlencode 'query=sum(rate(traces_span_metrics_calls_total{service_name=\"boarding-pass-svc\"}[5m]))'",
            grafana_ok_cmd="curl -sS $GRAFANA/api/ds/query -d @/tmp/board-rate.json | jq '.results.A.frames[0].data.values'",
            side_cmd="curl -sS -G $MIMIR/prometheus/api/v1/query --data-urlencode 'query=sum(rate(traces_span_metrics_calls_total{service_name=\"ssr-meal-svc\"}[5m]))' | jq '.data.result[0].value'",
            final_cmd="yq '.discovery.exclude_service_name' k8s/beyla/boarding.yaml",
            patch_old="instrumentation: [http, grpc]",
            patch_new="instrumentation: [grpc]\n  discovery:\n    exclude_service_name: [boarding-pass-svc]",
            runbook_path="runbooks/boarding-beyla-double.md",
            runbook="# boarding-pass-svc Beyla vs javaagent\nBeyla HTTP + OTel javaagent double-count. Exclude this service from Beyla HTTP.\nNot connector+processor dual export.\n",
            goal="boarding-pass-svc dashboard board-beyla-1 span rate is 2x load-test QPS. Find the double-instrument lie.",
            plan="2x rate → connector+processor (only connector) → two scopes in Tempo → exclude Beyla HTTP.",
            outcome="Beyla HTTP excluded for boarding-pass-svc. Rate matches QPS. grpc Beyla remains. javaagent-only services unchanged.",
            obs1='[{"uid":"board-beyla-1","title":"boarding pass spans"}]',
            obs2='{"title":"span rate","targets":[{"expr":"sum(rate(traces_span_metrics_calls_total{service_name=\\"boarding-pass-svc\\"}[5m]))"}]}',
            obs3='{"status":"success","data":{"result":[{"value":[1710000000,"84.0"]}]}}\n# load test QPS is 42',
            obs4="spanmetrics: {namespace: traces.span.metrics}\nnull\n# processor absent — not r166",
            obs5="only connector; no processor dual export",
            obs6="openPorts: [8080]\ninstrumentation: [http, grpc]",
            obs7='[{"scope":"io.opentelemetry.tomcat-10.0","n":12},{"scope":"beyla","n":12}]',
            obs8="Beyla HTTP on 8080 plus javaagent tomcat — double",
            obs9="patched Beyla HTTP off for this service; grpc remains",
            obs10='daemonset "beyla" successfully rolled out',
            obs11='{"status":"success","data":{"result":[{"value":[1710000600,"42.1"]}]}}',
            obs12="[[1710000600],[42.1]]",
            obs13='["1710000600","19.4"]',
            obs14="wrote runbooks/boarding-beyla-double.md",
            obs15="[boarding-pass-svc]",
        ),
        _fail(
            slug="beyla-disable-spanmetrics-conn",
            service="gate-reader-svc",
            dashboard_uid="gate-beyla-conn",
            panel="reader rate",
            query='sum(rate(traces_span_metrics_calls_total{service_name="gate-reader-svc"}[5m]))',
            lie="Removing the spanmetrics connector does not stop Beyla+javaagent double spans; it only hides the 2x in metrics",
            false_lead="spanmetrics connector double-export",
            config_path="otelcol/gate-collector.yaml",
            lie_path="k8s/beyla/gate-reader.yaml",
            wrong_path="otelcol/gate-collector.yaml",
            reload_name="otelcol-gate",
            ticket="OBS-4443",
            xfail="tests/test_gate_beyla.py",
            surfaces="connector leftover vs Beyla+javaagent",
            avoided="r166 as actual RCA",
            this_is="fail/handoff: dropped connector, Tempo still double spans",
            step_note="connector 6-10; metrics empty 11; late Beyla 12; handoff 14-15.",
            next_note="Next: New Relic span.id vs Tempo.",
            search_cmd="curl -sS $GRAFANA/api/search?query=gate-beyla-conn | jq -c '.[]|{uid,title}'",
            dash_cmd="curl -sS $GRAFANA/api/dashboards/uid/gate-beyla-conn | jq '.dashboard.panels[0]'",
            query_cmd="curl -sS -G $MIMIR/prometheus/api/v1/query --data-urlencode 'query=sum(rate(traces_span_metrics_calls_total{service_name=\"gate-reader-svc\"}[5m]))'",
            false_cmd="yq '.service.pipelines.metrics' otelcol/gate-collector.yaml",
            reload_cmd="kubectl -n otel rollout restart deploy/otelcol-gate && kubectl -n otel rollout status deploy/otelcol-gate --timeout=90s",
            requery_cmd="curl -sS -G $MIMIR/prometheus/api/v1/query --data-urlencode 'query=sum(rate(traces_span_metrics_calls_total{service_name=\"gate-reader-svc\"}[5m]))'",
            denied_cmd="kubectl -n beyla auth can-i patch daemonset/beyla --as=sre-bot",
            xfail_cmd="printf '%s\\n' '@pytest.mark.xfail(reason=\"beyla ds owned by ebpf-platform\")\\ndef test_gate_beyla():\\n    assert False' > tests/test_gate_beyla.py",
            wrong_old="receivers: [spanmetrics]",
            wrong_new="receivers: []",
            wrong2_old="exporters: [otlp/tempo, spanmetrics]",
            wrong2_new="exporters: [otlp/tempo]",
            ticket_path="tickets/OBS-4443.md",
            ticket_body="OBS-4443: gate-reader-svc still has beyla+tomcat scopes in Tempo. Connector removal hid metrics. Need Beyla exclude. No RBAC.\n",
            goal="gate-reader-svc dashboard gate-beyla-conn reader rate is 2x QPS. Stop the double count.",
            plan="Remove spanmetrics connector so the 2x metric goes away.",
            outcome="Connector removed; panel empty; Tempo still two scopes. Late beyla yaml. Handoff OBS-4443.",
            obs1='[{"uid":"gate-beyla-conn","title":"gate reader spans"}]',
            obs2='{"title":"reader rate","targets":[{"expr":"sum(rate(traces_span_metrics_calls_total{service_name=\\"gate-reader-svc\\"}[5m]))"}]}',
            obs3='{"status":"success","data":{"result":[{"value":[1710000000,"60"]}]}}',
            obs4="receivers: [spanmetrics]  # treated as r166",
            obs5="metrics pipeline has connector",
            obs6="otelcol/gate-collector.yaml",
            obs7="patched metrics receivers []",
            obs8='deployment "otelcol-gate" successfully rolled out',
            obs9='{"status":"success","data":{"result":[]}}',
            obs10="patched traces exporters without spanmetrics",
            obs11='{"status":"success","data":{"result":[]}}',
            obs12="k8s/beyla/gate-reader.yaml instrumentation [http]; Tempo scopes io.opentelemetry.tomcat + beyla",
            obs13="no",
            obs14="wrote tickets/OBS-4443.md",
            obs15="xfail tests/test_gate_beyla.py",
        ),
    )
)

# r184 New Relic span vs Tempo
MORE.append(
    (
        _ok(
            slug="nr-spanid-vs-tempo",
            service="lounge-wifi-svc",
            dashboard_uid="lounge-nr-2",
            panel="wifi traces",
            query='{resource.service.name="lounge-wifi-svc"}',
            lie="Grafana traces panel looks up New Relic spanId (16 hex of span) as Tempo traceId (32 hex)",
            false_lead="Datadog _dd.p.tid width",
            config_path="k8s/nr-agent/lounge.env",
            lie_path="grafana/dashboards/lounge-nr-2.json",
            truth_name="NR distributedTrace.traceId",
            reload_name="grafana",
            side="NR APM UI still uses spanId",
            surfaces="New Relic spanId vs Tempo traceId",
            avoided="r163 DD tid128; r162 Sentry event_id; r175 Faro session",
            this_is="NR spanId used as Tempo traceId",
            step_note="False lead DD tid 4-5; NR spanId vs traceId 6-8; dashboard var 9-12.",
            search_cmd="curl -sS $GRAFANA/api/search?query=lounge-nr-2 | jq -c '.[]|{uid,title}'",
            dash_cmd="curl -sS $GRAFANA/api/dashboards/uid/lounge-nr-2 | jq '.dashboard.templating.list[]|{name,query}'",
            query_cmd="curl -sS $TEMPO/api/traces/a1b2c3d4e5f60718 | jq .message",
            false_cmd="kubectl -n lounge exec deploy/lounge-wifi-svc -- env | rg 'DD_TRACE|NEW_RELIC'",
            truth_cmd="curl -sS $NR/v1/traces?app=lounge-wifi-svc | jq '.[0].{spanId,traceId}'",
            confirm_cmd="jq '.dashboard.panels[]|select(.type==\"traces\")' grafana/dashboards/lounge-nr-2.json",
            reload_cmd="kubectl -n grafana rollout restart deploy/grafana && kubectl -n grafana rollout status deploy/grafana --timeout=90s",
            requery_cmd="curl -sS $TEMPO/api/traces/4bf92f3577b34da6a3ce929d0e0e4736 | jq '{rootServiceName,spanCount}'",
            grafana_ok_cmd="curl -sS $GRAFANA/api/ds/query -d @/tmp/nr-join.json | jq '.results.A.frames[0].schema'",
            side_cmd="curl -sS $NR/v1/spans/a1b2c3d4e5f60718 | jq '{id,traceId}'",
            final_cmd="jq '.dashboard.templating.list[]|{name}' grafana/dashboards/lounge-nr-2.json",
            patch_old='"query": "nr_span_id"',
            patch_new='"query": "nr_trace_id"',
            runbook_path="runbooks/lounge-nr-tempo.md",
            runbook="# lounge-wifi-svc NR vs Tempo\nUse NR distributedTrace.traceId (32 hex), not spanId, as Tempo traceId.\nNot Datadog tid width.\n",
            goal="lounge-wifi-svc dashboard lounge-nr-2 wifi traces is empty. NR shows spans. Fix the id join.",
            plan="Tempo 404 on 16-hex → not DD env → NR spanId vs traceId → switch var.",
            outcome="Templating nr_trace_id. Tempo tree loads. NR UI still span-centric.",
            obs1='[{"uid":"lounge-nr-2","title":"lounge wifi NR join"}]',
            obs2='{"name":"nr_span_id","query":"nr_span_id"}',
            obs3='"trace not found"',
            obs4="NEW_RELIC_APP_NAME=lounge-wifi-svc\n# no DD_TRACE_* — not r163",
            obs5="k8s/nr-agent/lounge.env is New Relic, not Datadog",
            obs6='traces panel query=${nr_span_id}',
            obs7='{"spanId":"a1b2c3d4e5f60718","traceId":"4bf92f3577b34da6a3ce929d0e0e4736"}',
            obs8='{"type":"traces","targets":[{"query":"${nr_span_id}"}]}',
            obs9="patched templating nr_span_id → nr_trace_id",
            obs10='deployment "grafana" successfully rolled out',
            obs11='{"rootServiceName":"lounge-wifi-svc","spanCount":18}',
            obs12='{"name":"Trace"}',
            obs13='{"id":"a1b2c3d4e5f60718","traceId":"4bf92f3577b34da6a3ce929d0e0e4736"}',
            obs14="wrote runbooks/lounge-nr-tempo.md",
            obs15='{"name":"nr_trace_id"}',
        ),
        _fail(
            slug="nr-enable-dd-128bit",
            service="spa-pass-svc",
            dashboard_uid="spa-nr-dd",
            panel="spa traces",
            query='{resource.service.name="spa-pass-svc"}',
            lie="Enabling DD 128-bit flags on a New Relic app does not change Grafana looking up nr_span_id in Tempo",
            false_lead="Datadog 64-bit tid",
            config_path="k8s/spa-pass/env.yaml",
            lie_path="grafana/dashboards/spa-nr-dd.json",
            wrong_path="k8s/spa-pass/env.yaml",
            reload_name="spa-pass-svc",
            ticket="OBS-4444",
            xfail="tests/test_spa_nr.py",
            surfaces="DD 128-bit leftover vs NR spanId",
            avoided="r163 as actual RCA",
            this_is="fail/handoff: DD flags on NR app, Tempo still 404s spanId",
            step_note="DD flags 6-10; still 404 11; late dashboard 12; handoff 14-15.",
            next_note="Next: Loki pattern ingester vs bloom skip.",
            search_cmd="curl -sS $GRAFANA/api/search?query=spa-nr-dd | jq -c '.[]|{uid,title}'",
            dash_cmd="curl -sS $GRAFANA/api/dashboards/uid/spa-nr-dd | jq '.dashboard.panels[0]'",
            query_cmd="curl -sS $TEMPO/api/traces/f00dfacef00dface | jq .message",
            false_cmd="rg -n 'DD_TRACE|NEW_RELIC' k8s/spa-pass/env.yaml",
            reload_cmd="kubectl -n spa rollout restart deploy/spa-pass-svc && kubectl -n spa rollout status deploy/spa-pass-svc --timeout=90s",
            requery_cmd="curl -sS $TEMPO/api/traces/f00dfacef00dface | jq .message",
            denied_cmd="kubectl -n grafana auth can-i patch configmap/grafana-dashboards --as=sre-bot",
            xfail_cmd="printf '%s\\n' '@pytest.mark.xfail(reason=\"spa dashboard owned by loyalty-obs\")\\ndef test_spa_nr():\\n    assert False' > tests/test_spa_nr.py",
            wrong_old="NEW_RELIC_APP_NAME=spa-pass-svc",
            wrong_new="NEW_RELIC_APP_NAME=spa-pass-svc\n  DD_TRACE_128_BIT_TRACEID_GENERATION_ENABLED=true",
            wrong2_old="NEW_RELIC_DISTRIBUTED_TRACING_ENABLED=true",
            wrong2_new="NEW_RELIC_DISTRIBUTED_TRACING_ENABLED=true\n  DD_TRACE_PROPAGATION_STYLE=tracecontext",
            ticket_path="tickets/OBS-4444.md",
            ticket_body="OBS-4444: spa-pass-svc Tempo 404s nr_span_id. DD flags irrelevant on a NR app. Need dashboard var nr_trace_id. No RBAC.\n",
            goal="spa-pass-svc dashboard spa-nr-dd spa traces is empty. Restore Tempo join.",
            plan="Enable DD 128-bit so Tempo accepts 16-hex as 32-hex (r163 leftover).",
            outcome="DD flags set on NR app; Tempo still 404s spanId. Late dashboard var. Handoff OBS-4444.",
            obs1='[{"uid":"spa-nr-dd","title":"spa pass NR"}]',
            obs2='{"title":"spa traces","targets":[{"query":"${nr_span_id}"}]}',
            obs3='"trace not found"',
            obs4="NEW_RELIC_APP_NAME=spa-pass-svc\n# no DD flags — treated as r163",
            obs5="k8s/spa-pass/env.yaml NR only",
            obs6="same env — treated as RCA",
            obs7="patched added DD 128-bit",
            obs8='deployment "spa-pass-svc" successfully rolled out',
            obs9='"trace not found"',
            obs10="patched DD_TRACE_PROPAGATION_STYLE",
            obs11='"trace not found"',
            obs12="grafana/dashboards/spa-nr-dd.json query=${nr_span_id}",
            obs13="no",
            obs14="wrote tickets/OBS-4444.md",
            obs15="xfail tests/test_spa_nr.py",
        ),
    )
)

# r185 Loki pattern ingester vs bloom
MORE.append(
    (
        _ok(
            slug="loki-pattern-vs-bloom-skip",
            service="tarmac-cam-svc",
            dashboard_uid="tarmac-pattern-3",
            panel="pattern rate",
            query='sum by (detected_pattern) (rate({app="tarmac-cam-svc"}[5m]))',
            lie="pattern_ingester enabled but bloom-gateway skip_factor skips the same chunks pattern-ingester needs so Grafana detected_level empty",
            false_lead="bloom skip_on_error / stale skip_factor as sole RCA without pattern_ingester",
            config_path="loki/tarmac-bloom.yaml",
            lie_path="loki/tarmac-pattern.yaml",
            truth_name="pattern-ingester vs querier",
            reload_name="loki-pattern-ingester",
            side="raw log lines still queryable with skip_factor 0",
            surfaces="Loki pattern ingester vs bloom skip",
            avoided="r165 stale skip_factor alone; r173 SkipOnError",
            this_is="pattern_ingester starved by bloom skip on its read path",
            step_note="False lead bloom-only 4-5; pattern_ingester 6-8; dedicated pattern store 9-12.",
            search_cmd="curl -sS $GRAFANA/api/search?query=tarmac-pattern-3 | jq -c '.[]|{uid,title}'",
            dash_cmd="curl -sS $GRAFANA/api/dashboards/uid/tarmac-pattern-3 | jq '.dashboard.panels[0]'",
            query_cmd="curl -sS -G http://loki-gateway.obs/loki/api/v1/query --data-urlencode 'query=sum by (detected_pattern) (rate({app=\"tarmac-cam-svc\"}[5m]))'",
            false_cmd="yq '.bloom_gateway.skip_factor,.bloom_gateway.skip_on_error' loki/tarmac-bloom.yaml",
            truth_cmd="kubectl -n loki logs deploy/pattern-ingester --tail=20 | rg 'bloom|skip|tarmac-cam'",
            confirm_cmd="yq '.pattern_ingester,.querier.query_pattern_ingester' loki/tarmac-pattern.yaml",
            reload_cmd="kubectl -n loki rollout restart deploy/pattern-ingester && kubectl -n loki rollout status deploy/pattern-ingester --timeout=90s",
            requery_cmd="curl -sS -G http://loki-gateway.obs/loki/api/v1/query --data-urlencode 'query=sum by (detected_pattern) (rate({app=\"tarmac-cam-svc\"}[5m]))'",
            grafana_ok_cmd="curl -sS $GRAFANA/api/ds/query -d @/tmp/tarmac-pat.json | jq '.results.A.frames[0].schema.fields'",
            side_cmd="curl -sS -G http://loki-gateway.obs/loki/api/v1/query --data-urlencode 'query={app=\"tarmac-cam-svc\"}' | jq '.data.result|length'",
            final_cmd="yq '.pattern_ingester.metric_aggregation,.querier.query_pattern_ingester' loki/tarmac-pattern.yaml",
            patch_old="query_pattern_ingester: false",
            patch_new="query_pattern_ingester: true\n  pattern_ingester:\n    metric_aggregation:\n      enabled: true\n      bypass_blooms: true",
            runbook_path="runbooks/tarmac-pattern-bloom.md",
            runbook="# tarmac-cam-svc pattern vs bloom\npattern_ingester must bypass blooms; skip_factor starves detected_pattern.\nNot SkipOnError-only and not SM allowlist.\n",
            goal="tarmac-cam-svc dashboard tarmac-pattern-3 pattern rate is empty. Raw logs exist. Fix pattern vs bloom.",
            plan="Empty detected_pattern → bloom skip (already 0 / skip_on_error false) → pattern_ingester not queried → enable + bypass_blooms.",
            outcome="query_pattern_ingester true, bypass_blooms. Panel has 4 patterns. Raw logs still query.",
            obs1='[{"uid":"tarmac-pattern-3","title":"tarmac cam patterns"}]',
            obs2='{"title":"pattern rate","targets":[{"expr":"sum by (detected_pattern) (rate({app=\\"tarmac-cam-svc\\"}[5m]))"}]}',
            obs3='{"status":"success","data":{"result":[]}}',
            obs4="0\nfalse\n# r165/r173 already fixed on this tenant",
            obs5="bloom skip_factor 0 skip_on_error false — not those plants",
            obs6="pattern_ingester enabled: true\nquerier.query_pattern_ingester: false",
            obs7='msg="pattern sample skipped bloom" app=tarmac-cam-svc  # pattern reader still hits bloom-gateway',
            obs8="query_pattern_ingester false so Grafana detected_pattern never hits the ingester",
            obs9="patched query_pattern_ingester true; bypass_blooms true",
            obs10='deployment "pattern-ingester" successfully rolled out',
            obs11='{"status":"success","data":{"result":[{"metric":{"detected_pattern":"cam timeout <*>"},"value":[1710000600,"3.1"]}]}}',
            obs12='[{"name":"detected_pattern"},{"name":"Value"}]',
            obs13="20",
            obs14="wrote runbooks/tarmac-pattern-bloom.md",
            obs15="true\ntrue",
        ),
        _fail(
            slug="loki-pattern-rebuild-blooms",
            service="ramp-light-svc",
            dashboard_uid="ramp-pattern-bloom",
            panel="light patterns",
            query='sum by (detected_pattern) (rate({app="ramp-light-svc"}[5m]))',
            lie="Rebuilding blooms does not enable querier.query_pattern_ingester so detected_pattern stays empty",
            false_lead="stale blooms starving patterns",
            config_path="loki/ramp-bloom.yaml",
            lie_path="loki/ramp-pattern.yaml",
            wrong_path="loki/ramp-bloom.yaml",
            reload_name="loki-bloom-gateway",
            ticket="OBS-4445",
            xfail="tests/test_ramp_pattern.py",
            surfaces="bloom rebuild leftover vs pattern_ingester flag",
            avoided="r165/r173 as actual RCA",
            this_is="fail/handoff: rebuilt blooms, pattern query still off",
            step_note="bloom rebuild 6-10; still empty 11; late pattern yaml 12; handoff 14-15.",
            next_note="Next: OTel k8sattributes vs resource service.name.",
            search_cmd="curl -sS $GRAFANA/api/search?query=ramp-pattern-bloom | jq -c '.[]|{uid,title}'",
            dash_cmd="curl -sS $GRAFANA/api/dashboards/uid/ramp-pattern-bloom | jq '.dashboard.panels[0]'",
            query_cmd="curl -sS -G http://loki-gateway.obs/loki/api/v1/query --data-urlencode 'query=sum by (detected_pattern) (rate({app=\"ramp-light-svc\"}[5m]))'",
            false_cmd="yq '.bloom_gateway' loki/ramp-bloom.yaml",
            reload_cmd="kubectl -n loki rollout restart deploy/bloom-gateway && kubectl -n loki rollout status deploy/bloom-gateway --timeout=90s",
            requery_cmd="curl -sS -G http://loki-gateway.obs/loki/api/v1/query --data-urlencode 'query=sum by (detected_pattern) (rate({app=\"ramp-light-svc\"}[5m]))'",
            denied_cmd="kubectl -n loki auth can-i patch deploy/pattern-ingester --as=sre-bot",
            xfail_cmd="printf '%s\\n' '@pytest.mark.xfail(reason=\"pattern-ingester owned by logging-platform\")\\ndef test_ramp_pattern():\\n    assert False' > tests/test_ramp_pattern.py",
            wrong_old="skip_factor: 2",
            wrong_new="skip_factor: 0",
            wrong2_old="skip_on_error: true",
            wrong2_new="skip_on_error: false",
            ticket_path="tickets/OBS-4445.md",
            ticket_body="OBS-4445: ramp-light-svc detected_pattern empty. querier.query_pattern_ingester=false. Bloom knobs are r165/r173 leftovers. No pattern-ingester RBAC.\n",
            goal="ramp-light-svc dashboard ramp-pattern-bloom light patterns is empty. Restore detected_pattern.",
            plan="Rebuild/disable bloom skip so pattern ingester can read chunks.",
            outcome="skip_factor 0 skip_on_error false; detected_pattern still empty. Late query_pattern_ingester false. Handoff OBS-4445.",
            obs1='[{"uid":"ramp-pattern-bloom","title":"ramp light patterns"}]',
            obs2='{"title":"light patterns","targets":[{"expr":"sum by (detected_pattern) (rate({app=\\"ramp-light-svc\\"}[5m]))"}]}',
            obs3='{"status":"success","data":{"result":[]}}',
            obs4="skip_factor: 2  # treated as r165",
            obs5="loki/ramp-bloom.yaml",
            obs6="same bloom yaml",
            obs7="patched skip_factor 2→0",
            obs8='deployment "bloom-gateway" successfully rolled out',
            obs9='{"status":"success","data":{"result":[]}}',
            obs10="patched skip_on_error false",
            obs11='{"status":"success","data":{"result":[]}}',
            obs12="loki/ramp-pattern.yaml querier.query_pattern_ingester: false",
            obs13="no",
            obs14="wrote tickets/OBS-4445.md",
            obs15="xfail tests/test_ramp_pattern.py",
        ),
    )
)

# r186 OTel k8sattributes vs resource service.name
MORE.append(
    (
        _ok(
            slug="k8sattributes-vs-resource-svc",
            service="crew-badge-svc",
            dashboard_uid="crew-k8sattr-4",
            panel="by service",
            query='{resource.service.name="crew-badge-svc"}',
            lie="k8sattributes processor overwrites resource.service.name with k8s.deployment.name crew-badge (no -svc) so Tempo search by crew-badge-svc is empty",
            false_lead="OTTL truncate_all on service.name",
            config_path="otelcol/crew-transform.yaml",
            lie_path="otelcol/crew-collector.yaml",
            truth_name="resource after k8sattributes",
            reload_name="otelcol-crew",
            side="k8s.pod.name still added",
            surfaces="OTel k8sattributes vs resource service.name",
            avoided="r109-r158 OTTL truncate_all; r172 DD inferred",
            this_is="k8sattributes overwrites service.name with deployment name",
            step_note="False lead OTTL 4-5; k8sattributes extract 6-8; from_context only pod 9-12.",
            search_cmd="curl -sS $GRAFANA/api/search?query=crew-k8sattr-4 | jq -c '.[]|{uid,title}'",
            dash_cmd="curl -sS $GRAFANA/api/dashboards/uid/crew-k8sattr-4 | jq '.dashboard.panels[0]'",
            query_cmd="curl -sS -G $TEMPO/api/search --data-urlencode 'q={resource.service.name=\"crew-badge-svc\"}' | jq '.traces|length'",
            false_cmd="rg -n 'truncate_all|service.name' otelcol/crew-transform.yaml",
            truth_cmd="curl -sS -G $TEMPO/api/search --data-urlencode 'q={resource.service.name=\"crew-badge\"}' | jq '.traces|length'",
            confirm_cmd="yq '.processors.k8sattributes' otelcol/crew-collector.yaml",
            reload_cmd="kubectl -n crew rollout restart deploy/otelcol-crew && kubectl -n crew rollout status deploy/otelcol-crew --timeout=90s",
            requery_cmd="curl -sS -G $TEMPO/api/search --data-urlencode 'q={resource.service.name=\"crew-badge-svc\"}' | jq '.traces|length'",
            grafana_ok_cmd="curl -sS $GRAFANA/api/ds/query -d @/tmp/crew-tr.json | jq '.results.A.frames[0].schema'",
            side_cmd="curl -sS -G $TEMPO/api/search --data-urlencode 'q={k8s.pod.name=~\"crew-badge-.*\"}' | jq '.traces|length'",
            final_cmd="yq '.processors.k8sattributes.extract' otelcol/crew-collector.yaml",
            patch_old='metadata:\n          - k8s.deployment.name\n          - k8s.pod.name\n        labels:\n          - tag_name: service.name\n            key: app.kubernetes.io/name',
            patch_new="metadata:\n          - k8s.pod.name\n          - k8s.namespace.name",
            runbook_path="runbooks/crew-k8sattributes.md",
            runbook="# crew-badge-svc k8sattributes\nDo not map deployment name onto service.name. App already sets crew-badge-svc.\nNot OTTL truncate.\n",
            goal="crew-badge-svc dashboard crew-k8sattr-4 by service is empty after collector k8sattributes. Restore the name.",
            plan="Empty search → OTTL (none) → traces under crew-badge → stop overwriting service.name.",
            outcome="k8sattributes only pod/namespace. Tempo finds crew-badge-svc. Pod name still present.",
            obs1='[{"uid":"crew-k8sattr-4","title":"crew badge traces"}]',
            obs2='{"title":"by service","targets":[{"query":"{resource.service.name=\\"crew-badge-svc\\"}"}]}',
            obs3="0",
            obs4="# no truncate_all",
            obs5="transform empty — not banned OTTL plant",
            obs6="extract metadata [k8s.deployment.name, k8s.pod.name]\nlabels tag_name service.name key app.kubernetes.io/name  # value crew-badge",
            obs7="41\n# traces exist under overwritten name crew-badge",
            obs8="k8sattributes overwrites service.name",
            obs9="patched extract to pod+namespace only; no service.name overwrite",
            obs10='deployment "otelcol-crew" successfully rolled out',
            obs11="38",
            obs12='{"name":"Traces"}',
            obs13="38",
            obs14="wrote runbooks/crew-k8sattributes.md",
            obs15="- k8s.pod.name\n- k8s.namespace.name",
        ),
        _fail(
            slug="k8sattributes-ottl-restore",
            service="crew-brief-svc",
            dashboard_uid="crew-k8s-ottl",
            panel="brief traces",
            query='{resource.service.name="crew-brief-svc"}',
            lie="OTTL set(service.name) runs before k8sattributes which overwrites it again from deployment name",
            false_lead="missing OTTL set of service.name",
            config_path="otelcol/brief-transform.yaml",
            lie_path="otelcol/brief-collector.yaml",
            wrong_path="otelcol/brief-transform.yaml",
            reload_name="otelcol-brief",
            ticket="OBS-4446",
            xfail="tests/test_crew_brief_k8s.py",
            surfaces="OTTL leftover vs k8sattributes order",
            avoided="OTTL truncate as RCA; r172",
            this_is="fail/handoff: OTTL set then k8sattributes overwrites",
            step_note="OTTL set 6-10; still crew-brief 11; late processor order 12; handoff 14-15.",
            next_note="Next: Prom classic vs native histograms in Grafana.",
            search_cmd="curl -sS $GRAFANA/api/search?query=crew-k8s-ottl | jq -c '.[]|{uid,title}'",
            dash_cmd="curl -sS $GRAFANA/api/dashboards/uid/crew-k8s-ottl | jq '.dashboard.panels[0]'",
            query_cmd="curl -sS -G $TEMPO/api/search --data-urlencode 'q={resource.service.name=\"crew-brief-svc\"}' | jq '.traces|length'",
            false_cmd="cat otelcol/brief-transform.yaml",
            reload_cmd="kubectl -n crew rollout restart deploy/otelcol-brief && kubectl -n crew rollout status deploy/otelcol-brief --timeout=90s",
            requery_cmd="curl -sS -G $TEMPO/api/search --data-urlencode 'q={resource.service.name=\"crew-brief-svc\"}' | jq '.traces|length'",
            denied_cmd="kubectl -n crew auth can-i patch deploy/otelcol-brief --as=sre-bot",
            xfail_cmd="printf '%s\\n' '@pytest.mark.xfail(reason=\"brief collector owned by crew-obs\")\\ndef test_crew_brief_k8s():\\n    assert False' > tests/test_crew_brief_k8s.py",
            wrong_old="statements: []",
            wrong_new='statements:\n            - set(resource.attributes["service.name"], "crew-brief-svc")',
            wrong2_old="error_mode: ignore",
            wrong2_new="error_mode: propagate",
            ticket_path="tickets/OBS-4446.md",
            ticket_body="OBS-4446: crew-brief-svc still stored as crew-brief. Pipeline is transform, k8sattributes, batch so k8sattributes wins. Need extract without service.name. Handoff.\n",
            goal="crew-brief-svc dashboard crew-k8s-ottl brief traces is empty. Restore service.name.",
            plan="OTTL set service.name so Tempo search matches.",
            outcome="OTTL set added; traces still under crew-brief. Late k8sattributes after transform. Handoff OBS-4446.",
            obs1='[{"uid":"crew-k8s-ottl","title":"crew brief traces"}]',
            obs2='{"title":"brief traces","targets":[{"query":"{resource.service.name=\\"crew-brief-svc\\"}"}]}',
            obs3="0",
            obs4="statements: []",
            obs5="otelcol/brief-transform.yaml empty — treated as missing set",
            obs6="same transform yaml",
            obs7="patched set service.name crew-brief-svc",
            obs8='deployment "otelcol-brief" successfully rolled out',
            obs9="0",
            obs10="patched error_mode propagate",
            obs11="0",
            obs12="pipelines.traces.processors: [transform, k8sattributes, batch]\nk8sattributes extract tag_name service.name from app.kubernetes.io/name=crew-brief",
            obs13="no",
            obs14="wrote tickets/OBS-4446.md",
            obs15="xfail tests/test_crew_brief_k8s.py",
        ),
    )
)

# r187 Prom classic vs native histograms in Grafana
MORE.append(
    (
        _ok(
            slug="prom-native-hist-vs-classic",
            service="bag-sort-svc",
            dashboard_uid="bagsort-nhist-5",
            panel="sort p99",
            query='histogram_quantile(0.99, rate(sort_seconds_bucket{service="bag-sort-svc"}[5m]))',
            lie="scrape native-histogram only so _bucket series gone; Grafana still uses classic histogram_quantile on _bucket",
            false_lead="Prometheus agent empty TSDB",
            config_path="k8s/prom-agent-sort/statefulset.yaml",
            lie_path="grafana/dashboards/bagsort-nhist-5.json",
            truth_name="native histogram series",
            reload_name="grafana",
            side="classic histograms on other jobs still work",
            surfaces="Prom native vs classic histogram in Grafana",
            avoided="r160 agent TSDB; remote_write queue",
            this_is="native histogram scrape vs classic _bucket PromQL",
            step_note="False lead agent 4-5; native series 6-8; heatmap/nh PromQL 9-12.",
            search_cmd="curl -sS $GRAFANA/api/search?query=bagsort-nhist-5 | jq -c '.[]|{uid,title}'",
            dash_cmd="curl -sS $GRAFANA/api/dashboards/uid/bagsort-nhist-5 | jq '.dashboard.panels[0].targets'",
            query_cmd="curl -sS -G $MIMIR/prometheus/api/v1/query --data-urlencode 'query=histogram_quantile(0.99, rate(sort_seconds_bucket{service=\"bag-sort-svc\"}[5m]))'",
            false_cmd="kubectl -n obs get pod prom-agent-sort-0 --ignore-not-found",
            truth_cmd="curl -sS -G $MIMIR/prometheus/api/v1/label/__name__/values | jq '.data[]|select(test(\"sort_seconds\"))'",
            confirm_cmd="rg -n 'scrape_native|histogram' alloy/bagsort.alloy grafana/dashboards/bagsort-nhist-5.json",
            reload_cmd="kubectl -n grafana rollout restart deploy/grafana && kubectl -n grafana rollout status deploy/grafana --timeout=90s",
            requery_cmd="curl -sS -G $MIMIR/prometheus/api/v1/query --data-urlencode 'query=histogram_quantile(0.99, rate(sort_seconds{service=\"bag-sort-svc\"}[5m]))'",
            grafana_ok_cmd="curl -sS $GRAFANA/api/ds/query -d @/tmp/sort-p99.json | jq '.results.A.frames[0].data.values'",
            side_cmd="curl -sS -G $MIMIR/prometheus/api/v1/query --data-urlencode 'query=histogram_quantile(0.99, rate(print_seconds_bucket{service=\"bagtag-print-svc\"}[5m]))' | jq '.data.result[0].value'",
            final_cmd="jq '.dashboard.panels[0].targets[0].expr' grafana/dashboards/bagsort-nhist-5.json",
            patch_old="histogram_quantile(0.99, rate(sort_seconds_bucket{service=\"bag-sort-svc\"}[5m]))",
            patch_new="histogram_quantile(0.99, rate(sort_seconds{service=\"bag-sort-svc\"}[5m]))",
            runbook_path="runbooks/bagsort-native-hist.md",
            runbook="# bag-sort-svc native histograms\nAfter scrape_native_histograms, use sort_seconds not sort_seconds_bucket.\nNot agent-mode empty TSDB.\n",
            goal="bag-sort-svc dashboard bagsort-nhist-5 sort p99 is empty after native-histogram scrape. Restore p99.",
            plan="Empty _bucket → no leftover agent → native name sort_seconds → patch PromQL.",
            outcome="Panel uses sort_seconds native quantile. p99 0.22s. Classic print_seconds_bucket still works.",
            obs1='[{"uid":"bagsort-nhist-5","title":"bag sort p99"}]',
            obs2='[{"expr":"histogram_quantile(0.99, rate(sort_seconds_bucket{service=\\"bag-sort-svc\\"}[5m]))"}]',
            obs3='{"status":"success","data":{"result":[]}}',
            obs4="No resources found\n# no prom-agent-sort — not r160",
            obs5="no agent pod",
            obs6='"sort_seconds"\n# no sort_seconds_bucket',
            obs7="alloy scrape_native_histograms = true for job bagsort",
            obs8="dashboard still classic _bucket",
            obs9="patched expr sort_seconds_bucket → sort_seconds",
            obs10='deployment "grafana" successfully rolled out',
            obs11='{"status":"success","data":{"result":[{"value":[1710000600,"0.22"]}]}}',
            obs12="[[1710000600],[0.22]]",
            obs13='["1710000600","0.18"]',
            obs14="wrote runbooks/bagsort-native-hist.md",
            obs15='"histogram_quantile(0.99, rate(sort_seconds{service=\\"bag-sort-svc\\"}[5m]))"',
        ),
        _fail(
            slug="prom-native-retarget-agent",
            service="chutes-plc-svc",
            dashboard_uid="chutes-nhist-agent",
            panel="chute p95",
            query='histogram_quantile(0.95, rate(chute_seconds_bucket{service="chutes-plc-svc"}[5m]))',
            lie="Pointing Grafana at a Prom agent does not bring back classic _bucket after native-histogram scrape to Mimir",
            false_lead="Grafana querying Mimir which 'lost' buckets because of agent",
            config_path="grafana/datasources/prom-chutes.yaml",
            lie_path="grafana/dashboards/chutes-nhist-agent.json",
            wrong_path="grafana/datasources/prom-chutes.yaml",
            reload_name="grafana",
            ticket="OBS-4447",
            xfail="tests/test_chutes_nhist.py",
            surfaces="agent URL leftover vs native histogram PromQL",
            avoided="r160 as actual RCA",
            this_is="fail/handoff: Grafana→agent, _bucket still gone",
            step_note="datasource 6-10; still empty 11; late native name 12; handoff 14-15.",
            next_note="Next: Grafana Incident vs IRM.",
            search_cmd="curl -sS $GRAFANA/api/search?query=chutes-nhist-agent | jq -c '.[]|{uid,title}'",
            dash_cmd="curl -sS $GRAFANA/api/dashboards/uid/chutes-nhist-agent | jq '.dashboard.panels[0]'",
            query_cmd="curl -sS -G $MIMIR/prometheus/api/v1/query --data-urlencode 'query=histogram_quantile(0.95, rate(chute_seconds_bucket{service=\"chutes-plc-svc\"}[5m]))'",
            false_cmd="cat grafana/datasources/prom-chutes.yaml",
            reload_cmd="kubectl -n grafana rollout restart deploy/grafana && kubectl -n grafana rollout status deploy/grafana --timeout=90s",
            requery_cmd="curl -sS -G http://prom-agent-chutes.obs:9090/api/v1/query --data-urlencode 'query=histogram_quantile(0.95, rate(chute_seconds_bucket{service=\"chutes-plc-svc\"}[5m]))'",
            denied_cmd="kubectl -n grafana auth can-i patch configmap/grafana-dashboards --as=sre-bot",
            xfail_cmd="printf '%s\\n' '@pytest.mark.xfail(reason=\"chutes dashboard owned by ramp-obs\")\\ndef test_chutes_nhist():\\n    assert False' > tests/test_chutes_nhist.py",
            wrong_old="url: http://mimir-query.obs:8080/prometheus",
            wrong_new="url: http://prom-agent-chutes.obs:9090",
            wrong2_old="httpMethod: POST",
            wrong2_new="httpMethod: GET",
            ticket_path="tickets/OBS-4447.md",
            ticket_body="OBS-4447: chutes-plc-svc _bucket gone because scrape is native histogram chute_seconds. Agent URL is r160 leftover. Need PromQL change. No dashboard RBAC.\n",
            goal="chutes-plc-svc dashboard chutes-nhist-agent chute p95 is empty. Restore p95.",
            plan="Point Grafana at leftover Prom agent to get classic buckets.",
            outcome="Grafana hits agent (empty). Late native series chute_seconds. Handoff OBS-4447.",
            obs1='[{"uid":"chutes-nhist-agent","title":"chutes p95"}]',
            obs2='{"title":"chute p95","targets":[{"expr":"histogram_quantile(0.95, rate(chute_seconds_bucket{service=\\"chutes-plc-svc\\"}[5m]))"}]}',
            obs3='{"status":"success","data":{"result":[]}}',
            obs4="url: http://mimir-query.obs:8080/prometheus  # treated as r160",
            obs5="grafana/datasources/prom-chutes.yaml Mimir",
            obs6="same datasource",
            obs7="patched url → agent",
            obs8='deployment "grafana" successfully rolled out',
            obs9='{"status":"success","data":{"result":[]}}',
            obs10="patched httpMethod GET",
            obs11='{"status":"success","data":{"result":[]}}',
            obs12="Mimir __name__ chute_seconds (native); no chute_seconds_bucket; alloy scrape_native_histograms=true",
            obs13="no",
            obs14="wrote tickets/OBS-4447.md",
            obs15="xfail tests/test_chutes_nhist.py",
        ),
    )
)

# r188 Grafana Incident vs IRM (not AM, not heartbeat)
MORE.append(
    (
        _ok(
            slug="grafana-incident-vs-irm",
            service="runway-lights-svc",
            dashboard_uid="runway-incident-6",
            panel="open incidents",
            query='grafana_incident_open{service="runway-lights-svc"}',
            lie="Grafana Incident auto-create from IRM uses title template without service so dashboard {service=} join is empty while incidents exist",
            false_lead="IRM grouping key vs AM silence",
            config_path="helm/grafana-irm/runway-escalation.yaml",
            lie_path="helm/grafana-incident/runway.yaml",
            truth_name="Incident API titles",
            reload_name="grafana-incident",
            side="IRM pages still grouped by service",
            surfaces="Grafana Incident title vs IRM service label",
            avoided="r159 IRM group_by; r168 wait; r182 heartbeat",
            this_is="Incident title template drops service label",
            step_note="False lead IRM group_by 4-5; incident title 6-8; template {{service}} 9-12.",
            search_cmd="curl -sS $GRAFANA/api/search?query=runway-incident-6 | jq -c '.[]|{uid,title}'",
            dash_cmd="curl -sS $GRAFANA/api/dashboards/uid/runway-incident-6 | jq '.dashboard.panels[0]'",
            query_cmd="curl -sS -G $MIMIR/prometheus/api/v1/query --data-urlencode 'query=grafana_incident_open{service=\"runway-lights-svc\"}'",
            false_cmd="yq '.escalation.group_by' helm/grafana-irm/runway-escalation.yaml",
            truth_cmd="curl -sS $INCIDENT/api/v1/incidents?query=runway | jq '.[:3]|.[].{title,labels}'",
            confirm_cmd="yq '.incident.autoCreate.title' helm/grafana-incident/runway.yaml",
            reload_cmd="kubectl -n irm rollout restart deploy/grafana-incident && kubectl -n irm rollout status deploy/grafana-incident --timeout=90s",
            requery_cmd="curl -sS -G $MIMIR/prometheus/api/v1/query --data-urlencode 'query=grafana_incident_open{service=\"runway-lights-svc\"}'",
            grafana_ok_cmd="curl -sS $GRAFANA/api/ds/query -d @/tmp/runway-inc.json | jq '.results.A.frames[0].data.values'",
            side_cmd="curl -sS $IRM/api/v1/notifications?service=runway-lights-svc | jq 'length'",
            final_cmd="yq '.incident.autoCreate.title' helm/grafana-incident/runway.yaml",
            patch_old='title: "{{ .AlertName }} in {{ .Cluster }}"',
            patch_new='title: "{{ .AlertName }} {{ .Service }} {{ .Cluster }}"\n    labels:\n      service: "{{ .Service }}"',
            runbook_path="runbooks/runway-incident-title.md",
            runbook="# runway-lights-svc Grafana Incident vs IRM\nAuto-create title/labels must include service. IRM group_by already has service.\nNot silences, wait, or heartbeat.\n",
            goal="runway-lights-svc dashboard runway-incident-6 open incidents is 0 while IRM paged. Fix Incident labels.",
            plan="0 series → IRM group_by (includes service) → Incident title without service → add label.",
            outcome="Incidents labeled service=runway-lights-svc. Panel 2. IRM pages unchanged.",
            obs1='[{"uid":"runway-incident-6","title":"runway incidents"}]',
            obs2='{"title":"open incidents","targets":[{"expr":"grafana_incident_open{service=\\"runway-lights-svc\\"}"}]}',
            obs3='{"status":"success","data":{"result":[]}}',
            obs4="[alertname, cluster, service]\n# r159 already fixed here",
            obs5="IRM group_by includes service — not r159",
            obs6='title: "{{ .AlertName }} in {{ .Cluster }}"  # no Service',
            obs7='[{"title":"RunwayDark in iad-obs-a","labels":{"cluster":"iad-obs-a"}}]',
            obs8="Incident autoCreate omits service label",
            obs9="patched title + labels.service",
            obs10='deployment "grafana-incident" successfully rolled out',
            obs11='{"status":"success","data":{"result":[{"value":[1710000600,"2"]}]}}',
            obs12="[[1710000600],[2]]",
            obs13="4",
            obs14="wrote runbooks/runway-incident-title.md",
            obs15='"{{ .AlertName }} {{ .Service }} {{ .Cluster }}"',
        ),
        _fail(
            slug="grafana-incident-patch-irm-group",
            service="windsock-svc",
            dashboard_uid="windsock-incident-grp",
            panel="open incidents",
            query='grafana_incident_open{service="windsock-svc"}',
            lie="Adding service to IRM group_by does not label Grafana Incident records that omit service in autoCreate",
            false_lead="IRM group_by missing service",
            config_path="helm/grafana-irm/windsock-escalation.yaml",
            lie_path="helm/grafana-incident/windsock.yaml",
            wrong_path="helm/grafana-irm/windsock-escalation.yaml",
            reload_name="grafana-irm",
            ticket="OBS-4448",
            xfail="tests/test_windsock_incident.py",
            surfaces="IRM group_by leftover vs Incident title",
            avoided="r159 as actual RCA",
            this_is="fail/handoff: IRM group_by+=service, Incident still unlabeled",
            step_note="group_by 6-10; still 0 11; late incident yaml 12; handoff 14-15.",
            next_note="Next: ClickHouse Grafana SQL vs Tempo (not stale uid).",
            search_cmd="curl -sS $GRAFANA/api/search?query=windsock-incident-grp | jq -c '.[]|{uid,title}'",
            dash_cmd="curl -sS $GRAFANA/api/dashboards/uid/windsock-incident-grp | jq '.dashboard.panels[0]'",
            query_cmd="curl -sS -G $MIMIR/prometheus/api/v1/query --data-urlencode 'query=grafana_incident_open{service=\"windsock-svc\"}'",
            false_cmd="yq '.escalation.group_by' helm/grafana-irm/windsock-escalation.yaml",
            reload_cmd="kubectl -n irm rollout restart deploy/grafana-oncall && kubectl -n irm rollout status deploy/grafana-oncall --timeout=90s",
            requery_cmd="curl -sS -G $MIMIR/prometheus/api/v1/query --data-urlencode 'query=grafana_incident_open{service=\"windsock-svc\"}'",
            denied_cmd="kubectl -n irm auth can-i patch deploy/grafana-incident --as=sre-bot",
            xfail_cmd="printf '%s\\n' '@pytest.mark.xfail(reason=\"grafana-incident owned by irm-platform\")\\ndef test_windsock_incident():\\n    assert False' > tests/test_windsock_incident.py",
            wrong_old="group_by: [alertname, cluster]",
            wrong_new="group_by: [alertname, cluster, service]",
            wrong2_old="source: grafana_alerting",
            wrong2_new="source: alertmanager",
            ticket_path="tickets/OBS-4448.md",
            ticket_body="OBS-4448: windsock-svc incidents still unlabeled. autoCreate title has no Service. IRM group_by change is r159 leftover. No incident RBAC.\n",
            goal="windsock-svc dashboard windsock-incident-grp open incidents is 0 while IRM paged. Label incidents.",
            plan="Add service to IRM group_by so Incident inherits it (r159 leftover).",
            outcome="IRM group_by includes service; grafana_incident_open{service=} still empty. Late incident title. Handoff OBS-4448.",
            obs1='[{"uid":"windsock-incident-grp","title":"windsock incidents"}]',
            obs2='{"title":"open incidents","targets":[{"expr":"grafana_incident_open{service=\\"windsock-svc\\"}"}]}',
            obs3='{"status":"success","data":{"result":[]}}',
            obs4="[alertname, cluster]  # treated as r159",
            obs5="helm/grafana-irm/windsock-escalation.yaml",
            obs6="same escalation yaml",
            obs7="patched group_by += service",
            obs8='deployment "grafana-oncall" successfully rolled out',
            obs9='{"status":"success","data":{"result":[]}}',
            obs10="patched source alertmanager",
            obs11='{"status":"success","data":{"result":[]}}',
            obs12='helm/grafana-incident/windsock.yaml title: "{{ .AlertName }} in {{ .Cluster }}"  # no service label',
            obs13="no",
            obs14="wrote tickets/OBS-4448.md",
            obs15="xfail tests/test_windsock_incident.py",
        ),
    )
)

# r189 ClickHouse Grafana SQL vs Tempo (NOT stale uid)
MORE.append(
    (
        _ok(
            slug="clickhouse-sql-vs-tempo-db",
            service="ops-audit-svc",
            dashboard_uid="audit-ch-sql-7",
            panel="trace join",
            query="SELECT trace_id FROM otel_traces WHERE service_name = 'ops-audit-svc'",
            lie="Grafana SQL panel hits ClickHouse otel.traces but collector writes to otel_traces_dist; table name lie not stale dashboard uid",
            false_lead="Grafana SQL expr stale dashboard uid",
            config_path="grafana/dashboards/audit-ch-sql-7.json",
            lie_path="grafana/dashboards/audit-ch-sql-7.json",
            truth_name="ClickHouse tables",
            reload_name="grafana",
            side="uid audit-ch-sql-7 unchanged",
            surfaces="ClickHouse otel_traces vs otel_traces_dist",
            avoided="r109-r158 Grafana SQL expr stale uid; provisioned uid collision",
            this_is="CH table name vs distributed table, uid is stable",
            step_note="False lead stale uid 4-5; table list 6-8; SQL 9-12.",
            search_cmd="curl -sS $GRAFANA/api/search?query=audit-ch-sql-7 | jq -c '.[]|{uid,title}'",
            dash_cmd="curl -sS $GRAFANA/api/dashboards/uid/audit-ch-sql-7 | jq '.dashboard.uid,.dashboard.panels[0].targets[0].rawSql'",
            query_cmd="curl -sS $GRAFANA/api/ds/query -d @/tmp/audit-ch.json | jq '.results.A.error'",
            false_cmd="curl -sS $GRAFANA/api/dashboards/uid/audit-ch-sql-7 | jq '{uid:.dashboard.uid,version:.dashboard.version,id:.dashboard.id}'",
            truth_cmd="clickhouse-client -q 'SHOW TABLES FROM otel'",
            confirm_cmd="jq '.dashboard.panels[0].datasource' grafana/dashboards/audit-ch-sql-7.json",
            reload_cmd="kubectl -n grafana rollout restart deploy/grafana && kubectl -n grafana rollout status deploy/grafana --timeout=90s",
            requery_cmd="curl -sS $GRAFANA/api/ds/query -d @/tmp/audit-ch-dist.json | jq '.results.A.frames[0].schema.fields'",
            grafana_ok_cmd="curl -sS $GRAFANA/api/ds/query -d @/tmp/audit-ch-dist.json | jq '.results.A.frames[0].data.values[0]|length'",
            side_cmd="curl -sS $GRAFANA/api/dashboards/uid/audit-ch-sql-7 | jq '.dashboard.uid'",
            final_cmd="jq '.dashboard.panels[0].targets[0].rawSql' grafana/dashboards/audit-ch-sql-7.json",
            patch_old="SELECT trace_id FROM otel_traces WHERE service_name = 'ops-audit-svc'",
            patch_new="SELECT trace_id FROM otel_traces_dist WHERE service_name = 'ops-audit-svc'",
            runbook_path="runbooks/ops-audit-ch-table.md",
            runbook="# ops-audit-svc ClickHouse vs Tempo\nUse otel_traces_dist not otel_traces. Dashboard uid is stable (not the stale-uid plant).\n",
            goal="ops-audit-svc dashboard audit-ch-sql-7 trace join errors. Tempo has traces. Fix the ClickHouse table lie, not uid.",
            plan="SQL error → uid/version stable → SHOW TABLES otel_traces_dist → patch SQL.",
            outcome="SQL uses otel_traces_dist. 15 trace ids. uid audit-ch-sql-7 unchanged.",
            obs1='[{"uid":"audit-ch-sql-7","title":"ops audit traces SQL"}]',
            obs2='"audit-ch-sql-7"\n"SELECT trace_id FROM otel_traces WHERE service_name = \'ops-audit-svc\'"',
            obs3='"code: 60, Table otel.otel_traces does not exist"',
            obs4='{"uid":"audit-ch-sql-7","version":12,"id":448}\n# uid matches provisioned file — not stale uid',
            obs5="dashboard uid stable; banned SQL stale uid plant is not this",
            obs6="otel_traces_dist\notel_traces_local\n# no otel_traces",
            obs7="datasource uid=clickhouse-otel type=grafana-clickhouse-datasource",
            obs8="local table name in SQL; cluster uses _dist",
            obs9="patched FROM otel_traces → otel_traces_dist",
            obs10='deployment "grafana" successfully rolled out',
            obs11='[{"name":"trace_id","type":"string"}]',
            obs12="15",
            obs13='"audit-ch-sql-7"',
            obs14="wrote runbooks/ops-audit-ch-table.md",
            obs15='"SELECT trace_id FROM otel_traces_dist WHERE service_name = \'ops-audit-svc\'"',
        ),
        _fail(
            slug="clickhouse-reprovision-uid",
            service="ops-policy-svc",
            dashboard_uid="policy-ch-uid",
            panel="policy traces",
            query="SELECT trace_id FROM otel_traces WHERE service_name = 'ops-policy-svc'",
            lie="Re-provisioning a new dashboard uid does not create otel_traces; ClickHouse still only has _dist",
            false_lead="stale dashboard uid after provisioner rewrite",
            config_path="grafana/dashboards/policy-ch-uid.json",
            lie_path="grafana/dashboards/policy-ch-uid.json",
            wrong_path="grafana/dashboards/policy-ch-uid.json",
            reload_name="grafana",
            ticket="OBS-4449",
            xfail="tests/test_policy_ch.py",
            surfaces="uid leftover vs CH table name",
            avoided="stale uid as actual RCA",
            this_is="fail/handoff: new uid, table still missing",
            step_note="uid 6-10; still code 60 11; late SHOW TABLES 12; handoff 14-15.",
            next_note="Next: Datadog unified service tagging vs OTel service.namespace.",
            search_cmd="curl -sS $GRAFANA/api/search?query=policy-ch-uid | jq -c '.[]|{uid,title}'",
            dash_cmd="curl -sS $GRAFANA/api/dashboards/uid/policy-ch-uid | jq '.dashboard.uid,.dashboard.panels[0].targets[0].rawSql'",
            query_cmd="curl -sS $GRAFANA/api/ds/query -d @/tmp/policy-ch.json | jq '.results.A.error'",
            false_cmd="jq '.dashboard.uid' grafana/dashboards/policy-ch-uid.json",
            reload_cmd="kubectl -n grafana rollout restart deploy/grafana && kubectl -n grafana rollout status deploy/grafana --timeout=90s",
            requery_cmd="curl -sS $GRAFANA/api/ds/query -d @/tmp/policy-ch.json | jq '.results.A.error'",
            denied_cmd="clickhouse-client -q 'EXISTS TABLE otel.otel_traces'",
            xfail_cmd="printf '%s\\n' '@pytest.mark.xfail(reason=\"clickhouse schema owned by tracing-sql\")\\ndef test_policy_ch():\\n    assert False' > tests/test_policy_ch.py",
            wrong_old='"uid": "policy-ch-uid"',
            wrong_new='"uid": "policy-ch-uid-v2"',
            wrong2_old='"id": 449',
            wrong2_new='"id": null',
            ticket_path="tickets/OBS-4449.md",
            ticket_body="OBS-4449: ops-policy-svc SQL still Table otel_traces does not exist. Need otel_traces_dist. uid rewrite is the banned leftover. Handoff tracing-sql.\n",
            goal="ops-policy-svc dashboard policy-ch-uid policy traces SQL errors. Restore the join.",
            plan="Mint a new dashboard uid because provisioner stale uid broke the panel.",
            outcome="uid v2; SQL still code 60. Late SHOW TABLES _dist only. Handoff OBS-4449.",
            obs1='[{"uid":"policy-ch-uid","title":"ops policy SQL"}]',
            obs2='"policy-ch-uid"\n"SELECT trace_id FROM otel_traces WHERE service_name = \'ops-policy-svc\'"',
            obs3='"code: 60, Table otel.otel_traces does not exist"',
            obs4='"policy-ch-uid"  # treated as stale uid',
            obs5="grafana/dashboards/policy-ch-uid.json uid",
            obs6="same dashboard json",
            obs7="patched uid policy-ch-uid-v2",
            obs8='deployment "grafana" successfully rolled out',
            obs9='"code: 60, Table otel.otel_traces does not exist"',
            obs10="patched id null for re-provision",
            obs11='"code: 60, Table otel.otel_traces does not exist"',
            obs12="SHOW TABLES: otel_traces_dist, otel_traces_local — no otel_traces",
            obs13="0\n# EXISTS TABLE otel.otel_traces → 0; cannot CREATE (tracing-sql owns schema)",
            obs14="wrote tickets/OBS-4449.md",
            obs15="xfail tests/test_policy_ch.py",
        ),
    )
)

# r190 Datadog unified service tagging vs OTel service.namespace
MORE.append(
    (
        _ok(
            slug="dd-ust-vs-otel-namespace",
            service="reaccom-svc",
            dashboard_uid="reaccom-ust-8",
            panel="by namespace",
            query='{resource.service.namespace="airline-reaccom"}',
            lie="DD unified service tagging env:service:version does not set OTel service.namespace so Tempo {service.namespace} is empty",
            false_lead="Datadog inferred postgres resource",
            config_path="otelcol/reaccom-collector.yaml",
            lie_path="k8s/dd-agent/reaccom.env",
            truth_name="OTel resource keys",
            reload_name="reaccom-svc",
            side="service.name still reaccom-svc",
            surfaces="DD unified service tagging vs OTel service.namespace",
            avoided="r163 tid128; r172 inferred db",
            this_is="DD env:service:version vs OTel service.namespace",
            step_note="False lead inferred db 4-5; UST vs namespace 6-8; OTEL_SERVICE_NAMESPACE 9-12.",
            search_cmd="curl -sS $GRAFANA/api/search?query=reaccom-ust-8 | jq -c '.[]|{uid,title}'",
            dash_cmd="curl -sS $GRAFANA/api/dashboards/uid/reaccom-ust-8 | jq '.dashboard.panels[0]'",
            query_cmd="curl -sS -G $TEMPO/api/search --data-urlencode 'q={resource.service.namespace=\"airline-reaccom\"}' | jq '.traces|length'",
            false_cmd="curl -sS -G $TEMPO/api/search --data-urlencode 'q={resource.service.name=\"postgres-reaccom\"}' | jq '.traces|length'",
            truth_cmd="curl -sS $TEMPO/api/traces/aa99bb88cc77dd66ee55ff4433221100 | jq '.batches[0].resource.attributes'",
            confirm_cmd="kubectl -n reaccom exec deploy/reaccom-svc -- env | rg 'DD_ENV|DD_SERVICE|OTEL_SERVICE'",
            reload_cmd="kubectl -n reaccom rollout restart deploy/reaccom-svc && kubectl -n reaccom rollout status deploy/reaccom-svc --timeout=90s",
            requery_cmd="curl -sS -G $TEMPO/api/search --data-urlencode 'q={resource.service.namespace=\"airline-reaccom\"}' | jq '.traces|length'",
            grafana_ok_cmd="curl -sS $GRAFANA/api/ds/query -d @/tmp/reaccom-ns.json | jq '.results.A.frames[0].schema'",
            side_cmd="curl -sS -G $TEMPO/api/search --data-urlencode 'q={resource.service.name=\"reaccom-svc\"}' | jq '.traces|length'",
            final_cmd="kubectl -n reaccom exec deploy/reaccom-svc -- env | rg 'OTEL_SERVICE_NAMESPACE'",
            patch_old="DD_ENV=prod\nDD_SERVICE=reaccom-svc\nDD_VERSION=9.4.1",
            patch_new="DD_ENV=prod\nDD_SERVICE=reaccom-svc\nDD_VERSION=9.4.1\nOTEL_SERVICE_NAMESPACE=airline-reaccom\nOTEL_RESOURCE_ATTRIBUTES=service.namespace=airline-reaccom",
            runbook_path="runbooks/reaccom-ust-namespace.md",
            runbook="# reaccom-svc DD UST vs OTel namespace\nUST env:service:version is not service.namespace. Set OTEL_SERVICE_NAMESPACE.\nNot inferred DB and not tid width.\n",
            goal="reaccom-svc dashboard reaccom-ust-8 by namespace is empty. DD APM shows env prod. Fix the namespace lie.",
            plan="Empty namespace search → not inferred db → resource has deployment.environment not service.namespace → set OTEL_SERVICE_NAMESPACE.",
            outcome="OTEL_SERVICE_NAMESPACE set. Tempo search 27 traces. service.name still reaccom-svc.",
            obs1='[{"uid":"reaccom-ust-8","title":"reaccom namespace"}]',
            obs2='{"title":"by namespace","targets":[{"query":"{resource.service.namespace=\\"airline-reaccom\\"}"}]}',
            obs3="0",
            obs4="0\n# no postgres-reaccom — not r172",
            obs5="no inferred DB entity",
            obs6='[{"key":"service.name","value":"reaccom-svc"},{"key":"deployment.environment","value":"prod"},{"key":"service.version","value":"9.4.1"}]\n# no service.namespace',
            obs7="DD_ENV=prod\nDD_SERVICE=reaccom-svc\n# no OTEL_SERVICE_NAMESPACE",
            obs8="UST maps to deployment.environment not service.namespace",
            obs9="patched OTEL_SERVICE_NAMESPACE + resource attributes",
            obs10='deployment "reaccom-svc" successfully rolled out',
            obs11="27",
            obs12='{"name":"Traces"}',
            obs13="27",
            obs14="wrote runbooks/reaccom-ust-namespace.md",
            obs15="OTEL_SERVICE_NAMESPACE=airline-reaccom",
        ),
        _fail(
            slug="dd-ust-copy-peer-namespace",
            service="irrops-svc",
            dashboard_uid="irrops-ust-peer",
            panel="irrops namespace",
            query='{resource.service.namespace="airline-irrops"}',
            lie="Copying peer.service into service.namespace yields DB names not airline-irrops",
            false_lead="missing peer.service on OTel resource",
            config_path="otelcol/irrops-collector.yaml",
            lie_path="k8s/dd-agent/irrops.env",
            wrong_path="otelcol/irrops-collector.yaml",
            reload_name="otelcol-irrops",
            ticket="OBS-4450",
            xfail="tests/test_irrops_ust.py",
            surfaces="peer.service leftover vs UST namespace",
            avoided="r172 as actual RCA",
            this_is="fail/handoff: peer.service→namespace, still no airline-irrops",
            step_note="peer.service 6-10; still 0 11; late DD env 12; handoff 14-15.",
            next_note="Catalog closed r159-r190. Next mill: OpenSearch vs Loki, k6 vs Tempo.",
            search_cmd="curl -sS $GRAFANA/api/search?query=irrops-ust-peer | jq -c '.[]|{uid,title}'",
            dash_cmd="curl -sS $GRAFANA/api/dashboards/uid/irrops-ust-peer | jq '.dashboard.panels[0]'",
            query_cmd="curl -sS -G $TEMPO/api/search --data-urlencode 'q={resource.service.namespace=\"airline-irrops\"}' | jq '.traces|length'",
            false_cmd="yq '.processors' otelcol/irrops-collector.yaml",
            reload_cmd="kubectl -n irrops rollout restart deploy/otelcol-irrops && kubectl -n irrops rollout status deploy/otelcol-irrops --timeout=90s",
            requery_cmd="curl -sS -G $TEMPO/api/search --data-urlencode 'q={resource.service.namespace=\"airline-irrops\"}' | jq '.traces|length'",
            denied_cmd="kubectl -n irrops auth can-i patch deploy/irrops-svc --as=sre-bot",
            xfail_cmd="printf '%s\\n' '@pytest.mark.xfail(reason=\"irrops env owned by ops-platform\")\\ndef test_irrops_ust():\\n    assert False' > tests/test_irrops_ust.py",
            wrong_old="processors:\n  batch: {}",
            wrong_new=(
                "processors:\n  batch: {}\n"
                "  resource/ns:\n    attributes:\n"
                "      - key: service.namespace\n        from_attribute: peer.service\n        action: insert"
            ),
            wrong2_old="processors: [resource/ns, batch]",
            wrong2_new="processors: [resource/ns, k8sattributes, batch]",
            ticket_path="tickets/OBS-4450.md",
            ticket_body="OBS-4450: irrops-svc namespace still empty/wrong (peer.service=postgres). Need OTEL_SERVICE_NAMESPACE=airline-irrops on the app. No app RBAC.\n",
            goal="irrops-svc dashboard irrops-ust-peer by namespace is empty. Restore airline-irrops.",
            plan="Insert service.namespace from peer.service (r172 leftover).",
            outcome="peer.service copied (postgres). airline-irrops still 0. Late DD UST env without OTEL_SERVICE_NAMESPACE. Handoff OBS-4450.",
            obs1='[{"uid":"irrops-ust-peer","title":"irrops namespace"}]',
            obs2='{"title":"irrops namespace","targets":[{"query":"{resource.service.namespace=\\"airline-irrops\\"}"}]}',
            obs3="0",
            obs4="batch: {}",
            obs5="no resource processor — treated as r172",
            obs6="otelcol/irrops-collector.yaml",
            obs7="patched resource/ns from peer.service",
            obs8='deployment "otelcol-irrops" successfully rolled out',
            obs9="0",
            obs10="patched added k8sattributes",
            obs11="0",
            obs12="k8s/dd-agent/irrops.env DD_ENV=prod DD_SERVICE=irrops-svc — no OTEL_SERVICE_NAMESPACE; peer.service=postgres",
            obs13="no",
            obs14="wrote tickets/OBS-4450.md",
            obs15="xfail tests/test_irrops_ust.py",
        ),
    )
)
