"""Observability leftover13 plants r1212+.

BAN r1211 vagrant-machine-index-drop / leftover12 lock-basin, leftover11 slip-mole,
leftover10 pier-berth, leftover9 quay-wharf, leftover8 dock-apron,
r875 tempo, r384 otel-forward, PagerDuty, Opsgenie, Rootly.
"""

from mill_plants_t import _leftover_pair

MORE = []
ROUND_PAIRS = {}


def _emit(round_n, **kwargs):
    dest = []
    _leftover_pair(n=str(round_n), dest=dest, **kwargs)
    MORE.extend(dest)
    ROUND_PAIRS[round_n] = dest[0]


def _l13(n, **kw):
    vendor, noun, prefix = kw["vendor"], kw["noun"], kw["prefix"]
    ok_svc, bad_svc = f"dam-{noun}-svc", f"weir-{noun}-svc"
    tag = noun.replace("-", "")[:8]
    vtag = prefix.replace("-", "")[:5]
    ok_dash, bad_dash = f"{tag}-{vtag}-{n}", f"d{tag[:7]}-{vtag}-fl"
    lie_core = kw["lie_core"]
    _emit(
        n,
        kind="grafana",
        ok_slug=kw["ok_slug"],
        bad_slug=kw["bad_slug"],
        ok_svc=ok_svc,
        bad_svc=bad_svc,
        ok_dash=ok_dash,
        bad_dash=bad_dash,
        panel=kw["panel"],
        metric="",
        needle=kw["needle"],
        lie=(
            f"{vendor} leftover leftover leftover leftover leftover leftover leftover leftover leftover leftover leftover leftover leftover {lie_core} "
            f"so Grafana dashboard {ok_dash} is empty while the source still 202"
        ),
        bad_lie=(
            f"{kw['false_lead']} does not restore leftover leftover leftover leftover leftover leftover leftover leftover leftover leftover leftover leftover leftover {lie_core}"
        ),
        false_lead=kw["false_lead"],
        avoided=kw["avoided"],
        this_is=f"{vendor} leftover leftover leftover leftover leftover leftover leftover leftover leftover leftover leftover leftover leftover {lie_core}",
        ticket=f"OBS-{9100 + (n - 1212)}",
        knob=kw["knob"],
        old=kw["old"],
        new=kw["new"],
        wrong_knob=kw["wrong_knob"],
        wrong_old=kw["wrong_old"],
        wrong_new=kw["wrong_new"],
        wrong2_old=kw["wrong2_old"],
        wrong2_new=kw["wrong2_new"],
        reload="grafana",
        config_path=f"{prefix}/{tag}-false.yaml",
        lie_path=f"{prefix}/{tag}-lie.yaml",
        bad_config=f"{prefix}/d{tag[:7]}-false.yaml",
        bad_lie_path=f"{prefix}/d{tag[:7]}-lie.yaml",
    )


BAN = (
    "r1211 vagrant-machine-index-drop-leftover; leftover12 lock/basin r1188-r1211; "
    "r875 tempo-ingester-max-traces-per-user-one; r384 otel-forward-connector; "
    "PagerDuty orch; Opsgenie alias; r515 Rootly urgency"
)

SPECS = [
    dict(vendor="Lens Desktop", ok_slug="lens-metrics-proxy-off-leftover", bad_slug="lens-prox-raise-kube-not-enable", noun="aquifer", panel="Lens metrics", needle="lens_up", lie_core="proxy leftover enableMetrics=false so Grafana is empty while Lens still lists clusters", false_lead="Lens kubeconfig leftover", avoided=BAN+"; leftover12 Headlamp metrics", knob=".enableMetrics", old="enableMetrics: false", new="enableMetrics: true", wrong_knob=".kubeconfig", wrong_old="kubeconfig: sandbox", wrong_new="kubeconfig: hangar", wrong2_old="cluster: sandbox", wrong2_new="cluster: hangar", prefix="lens"),
    dict(vendor="Octant", ok_slug="octant-listener-drop-leftover", bad_slug="oct-list-raise-ns-not-listen", noun="spring", panel="Octant listener", needle="oct_up", lie_core="listener leftover --listener-addr 127.0.0.1 so Grafana is empty while the UI still 7777", false_lead="Octant ns leftover", avoided=BAN+"; leftover13 Lens metrics", knob=".listener-addr", old="listener-addr: 127.0.0.1:7777", new="listener-addr: 0.0.0.0:7777", wrong_knob=".namespace", wrong_old="namespace: sandbox", wrong_new="namespace: hangar", wrong2_old="kubeconfig: sandbox", wrong2_new="kubeconfig: hangar", prefix="oct"),
    dict(vendor="kubefwd", ok_slug="kubefwd-log-drop-leftover", bad_slug="kfwd-log-raise-ns-not-log", noun="geyser", panel="kubefwd log", needle="kfwd_fwd", lie_core="log leftover -log /dev/null so Grafana is empty while forwards still bind", false_lead="kubefwd ns leftover", avoided=BAN+"; leftover11 Telepresence metrics", knob=".log", old="log: /dev/null", new="log: /var/log/kubefwd.log", wrong_knob=".namespace", wrong_old="namespace: sandbox", wrong_new="namespace: hangar", wrong2_old="context: sandbox", wrong2_new="context: hangar", prefix="kfwd"),
    dict(vendor="AppImage", ok_slug="appimage-update-info-drop-leftover", bad_slug="aimg-upd-raise-arch-not-info", noun="delta", panel="AppImage update", needle="aimg_upd", lie_core="update leftover UPDATE_INFORMATION empty so Grafana is empty while the AppImage still runs", false_lead="AppImage arch leftover", avoided=BAN+"; leftover11 snapcraft store", knob=".UPDATE_INFORMATION", old="UPDATE_INFORMATION: ", new="UPDATE_INFORMATION: gh-releases-zsync|hangar|app|*", wrong_knob=".ARCH", wrong_old="ARCH: i386", wrong_new="ARCH: x86_64", wrong2_old="NAME: sandbox", wrong2_new="NAME: hangar", prefix="aimg"),
    dict(vendor="fpm", ok_slug="fpm-output-drop-leftover", bad_slug="fpm-out-raise-type-not-output", noun="oxbow", panel="fpm output", needle="fpm_pkg", lie_core="output leftover -p /dev/null so Grafana is empty while packages still build", false_lead="fpm type leftover", avoided=BAN+"; leftover11 nfpm apk", knob=".package", old="package: /dev/null", new="package: /var/lib/fpm/hangar.deb", wrong_knob=".input-type", wrong_old="input-type: dir", wrong_new="input-type: gem", wrong2_old="name: sandbox", wrong2_new="name: hangar", prefix="fpm"),
    dict(vendor="rpmbuild", ok_slug="rpmbuild-topdir-drop-leftover", bad_slug="rpmb-top-raise-arch-not-topdir", noun="meander", panel="rpmbuild", needle="rpmb_rpm", lie_core="topdir leftover _topdir /tmp/empty so Grafana is empty while specs still parse", false_lead="rpmbuild arch leftover", avoided=BAN+"; leftover13 fpm output", knob="._topdir", old="_topdir: /tmp/empty", new="_topdir: /var/lib/rpmbuild", wrong_knob="._arch", wrong_old="_arch: noarch", wrong_new="_arch: x86_64", wrong2_old="Name: sandbox", wrong2_new="Name: hangar", prefix="rpmb"),
    dict(vendor="debuild", ok_slug="debuild-changelog-drop-leftover", bad_slug="debu-chg-raise-dist-not-changelog", noun="riffle", panel="debuild", needle="debu_deb", lie_core="changelog leftover Distribution sandbox so Grafana is the wrong dashboard while debs still build", false_lead="debuild dist leftover", avoided=BAN+"; leftover13 rpmbuild topdir", knob=".Distribution", old="Distribution: sandbox", new="Distribution: unstable", wrong_knob=".DEB_BUILD_OPTIONS", wrong_old="DEB_BUILD_OPTIONS: nocheck", wrong_new="DEB_BUILD_OPTIONS: parallel=4", wrong2_old="Source: sandbox", wrong2_new="Source: hangar", prefix="debu"),
    dict(vendor="createrepo", ok_slug="createrepo-outputdir-drop-leftover", bad_slug="crepo-out-raise-comp-not-dir", noun="thalweg", panel="createrepo", needle="crepo_xml", lie_core="output leftover --outputdir /tmp/empty so Grafana is empty while rpms still sit", false_lead="createrepo compress leftover", avoided=BAN+"; leftover12 reprepro log", knob=".outputdir", old="outputdir: /tmp/empty", new="outputdir: /var/lib/yum/hangar", wrong_knob=".compress-type", wrong_old="compress-type: none", wrong_new="compress-type: xz", wrong2_old="revision: sandbox", wrong2_new="revision: hangar", prefix="crepo"),
    dict(vendor="Spacewalk", ok_slug="spacewalk-osa-off-leftover", bad_slug="swalk-osa-raise-sat-not-enable", noun="levee", panel="Spacewalk OSA", needle="swalk_up", lie_core="osa leftover jabberd disabled so Grafana is empty while the web UI still 443", false_lead="Spacewalk satellite leftover", avoided=BAN+"; leftover12 Uyuni tomcat", knob=".osa.jabberd", old="jabberd: false", new="jabberd: true", wrong_knob=".satellite.fqdn", wrong_old="fqdn: sandbox", wrong_new="fqdn: hangar", wrong2_old="db_host: sandbox", wrong2_new="db_host: hangar", prefix="swalk"),
    dict(vendor="Flatcar", ok_slug="flatcar-update-engine-off-leftover", bad_slug="fcar-upd-raise-ch-not-enable", noun="dike", panel="Flatcar update", needle="fcar_upd", lie_core="update leftover UPDATE_DISABLED=true so Grafana is empty while the node still boots", false_lead="Flatcar channel leftover", avoided=BAN+"; leftover11 Bottlerocket metrics", knob=".UPDATE_DISABLED", old="UPDATE_DISABLED: true", new="UPDATE_DISABLED: false", wrong_knob=".GROUP", wrong_old="GROUP: sandbox", wrong_new="GROUP: stable", wrong2_old="SERVER: https://sandbox", wrong2_new="SERVER: https://public.update.flatcar-linux.net", prefix="fcar"),
    dict(vendor="Guix", ok_slug="guix-substitute-off-leftover", bad_slug="guix-sub-raise-url-not-enable", noun="sluice", panel="Guix substitute", needle="guix_pkg", lie_core="substitute leftover --no-substitutes so Grafana is empty while builds still compile", false_lead="Guix url leftover", avoided=BAN+"; leftover11 NixOS prometheus", knob=".substitutes", old="substitutes: false", new="substitutes: true", wrong_knob=".substitute-urls", wrong_old="substitute-urls: https://sandbox", wrong_new="substitute-urls: https://ci.guix.gnu.org", wrong2_old="GUIX_PROFILE: /tmp", wrong2_new="GUIX_PROFILE: ~/.guix-profile", prefix="guix"),
    dict(vendor="Podman", ok_slug="podman-events-logger-drop-leftover", bad_slug="pod-evt-raise-graph-not-logger", noun="spillway", panel="Podman events", needle="pod_evt", lie_core="events leftover events_logger=none so Grafana is empty while containers still run", false_lead="Podman graph leftover", avoided=BAN+"; leftover8 Docker leftover clones", knob=".events_logger", old="events_logger: none", new="events_logger: journald", wrong_knob=".graphroot", wrong_old="graphroot: /tmp", wrong_new="graphroot: /var/lib/containers/storage", wrong2_old="cgroup_manager: cgroupfs", wrong2_new="cgroup_manager: systemd", prefix="pod"),
    dict(vendor="Buildah", ok_slug="buildah-log-drop-leftover", bad_slug="blda-log-raise-isol-not-log", noun="penstock", panel="Buildah log", needle="blda_img", lie_core="log leftover BUILDAH_LOG_LEVEL=panic so Grafana is empty while images still build", false_lead="Buildah isolation leftover", avoided=BAN+"; leftover13 Podman events", knob=".BUILDAH_LOG_LEVEL", old="BUILDAH_LOG_LEVEL: panic", new="BUILDAH_LOG_LEVEL: info", wrong_knob=".isolation", wrong_old="isolation: chroot", wrong_new="isolation: oci", wrong2_old="root: /tmp", wrong2_new="root: /var/lib/containers/storage", prefix="blda"),
    dict(vendor="Skopeo", ok_slug="skopeo-tls-verify-drop-leftover", bad_slug="skop-tls-raise-auth-not-verify", noun="tailrace", panel="Skopeo copy", needle="skop_img", lie_core="tls leftover --tls-verify=false plus dest sandbox so Grafana is the wrong dashboard", false_lead="Skopeo auth leftover", avoided=BAN+"; leftover13 Buildah log", knob=".tls-verify", old="tls-verify: false", new="tls-verify: true", wrong_knob=".authfile", wrong_old="authfile: /tmp/empty", wrong_new="authfile: /run/containers/0/auth.json", wrong2_old="dest: docker://sandbox", wrong2_new="dest: docker://hangar", prefix="skop"),
    dict(vendor="nerdctl", ok_slug="nerdctl-namespace-remap-leftover", bad_slug="nerd-ns-raise-addr-not-remap", noun="forebay", panel="nerdctl ns", needle="nerd_ctr", lie_core="namespace leftover NERDCTL_NAMESPACE sandbox so Grafana is the wrong dashboard while containers still run", false_lead="nerdctl addr leftover", avoided=BAN+"; leftover13 Podman events", knob=".NERDCTL_NAMESPACE", old="NERDCTL_NAMESPACE: sandbox", new="NERDCTL_NAMESPACE: hangar", wrong_knob=".CONTAINERD_ADDRESS", wrong_old="CONTAINERD_ADDRESS: /tmp/missing.sock", wrong_new="CONTAINERD_ADDRESS: /run/containerd/containerd.sock", wrong2_old="CNI_PATH: /tmp", wrong2_new="CNI_PATH: /opt/cni/bin", prefix="nerd"),
    dict(vendor="CRI-O", ok_slug="crio-metrics-bind-drop-leftover", bad_slug="crio-bind-raise-pause-not-addr", noun="surge", panel="CRI-O metrics", needle="crio_up", lie_core="metrics leftover listen 127.0.0.1 so Grafana is empty while pods still run", false_lead="CRI-O pause leftover", avoided=BAN+"; leftover13 nerdctl ns", knob=".metrics.listen", old="listen: 127.0.0.1:9090", new="listen: 0.0.0.0:9090", wrong_knob=".pause_image", wrong_old="pause_image: sandbox", wrong_new="pause_image: registry.k8s.io/pause:3.9", wrong2_old="conmon: /tmp/conmon", wrong2_new="conmon: /usr/libexec/crio/conmon", prefix="crio"),
    dict(vendor="Firecracker", ok_slug="fc-metrics-fifo-drop-leftover", bad_slug="fc-fifo-raise-kernel-not-fifo", noun="draft", panel="Firecracker metrics", needle="fc_vm", lie_core="metrics leftover metrics_fifo /dev/null so Grafana is empty while the VM still boots", false_lead="Firecracker kernel leftover", avoided=BAN+"; leftover11 Talos metrics", knob=".metrics_fifo", old="metrics_fifo: /dev/null", new="metrics_fifo: /var/log/firecracker.fifo", wrong_knob=".kernel_image_path", wrong_old="kernel_image_path: /tmp/empty", wrong_new="kernel_image_path: /var/lib/firecracker/vmlinux", wrong2_old="boot_args: console=none", wrong2_new="boot_args: console=ttyS0 reboot=k panic=1", prefix="fc"),
    dict(vendor="Cloud Hypervisor", ok_slug="chv-api-bind-drop-leftover", bad_slug="chv-api-raise-kernel-not-addr", noun="wicket", panel="CHV API", needle="chv_vm", lie_core="api leftover --api-socket /tmp/empty so Grafana is empty while the VM still runs", false_lead="CHV kernel leftover", avoided=BAN+"; leftover13 Firecracker fifo", knob=".api-socket", old="api-socket: /tmp/empty", new="api-socket: /run/cloud-hypervisor/api.sock", wrong_knob=".kernel", wrong_old="kernel: /tmp/empty", wrong_new="kernel: /var/lib/chv/vmlinux", wrong2_old="cpus: 0", wrong2_new="cpus: 2", prefix="chv"),
    dict(vendor="QEMU", ok_slug="qemu-qmp-off-leftover", bad_slug="qemu-qmp-raise-nogr-not-enable", noun="runner", panel="QEMU QMP", needle="qemu_vm", lie_core="qmp leftover -qmp none so Grafana is empty while the guest still boots", false_lead="QEMU nographic leftover", avoided=BAN+"; leftover13 Cloud Hypervisor API", knob=".qmp", old="qmp: none", new="qmp: unix:/run/qemu/qmp.sock,server,nowait", wrong_knob=".nographic", wrong_old="nographic: true", wrong_new="nographic: false", wrong2_old="name: sandbox", wrong2_new="name: hangar", prefix="qemu"),
    dict(vendor="libvirt", ok_slug="libvirt-listen-drop-leftover", bad_slug="lvirt-list-raise-tls-not-listen", noun="scroll", panel="libvirt listen", needle="lvirt_up", lie_core="listen leftover listen_tcp=0 so Grafana is empty while virsh still works locally", false_lead="libvirt tls leftover", avoided=BAN+"; leftover13 QEMU qmp", knob=".listen_tcp", old="listen_tcp: 0", new="listen_tcp: 1", wrong_knob=".listen_tls", wrong_old="listen_tls: 0", wrong_new="listen_tls: 1", wrong2_old="unix_sock_group: sandbox", wrong2_new="unix_sock_group: libvirt", prefix="lvirt"),
    dict(vendor="oVirt", ok_slug="ovirt-engine-metrics-off-leftover", bad_slug="ovirt-met-raise-dwh-not-enable", noun="stayring", panel="oVirt engine", needle="ovirt_up", lie_core="metrics leftover ENGINE_LOG_TO_CONSOLE=false plus collectd off so Grafana is empty", false_lead="oVirt DWH leftover", avoided=BAN+"; leftover13 libvirt listen", knob=".ENGINE_METRICS", old="ENGINE_METRICS: false", new="ENGINE_METRICS: true", wrong_knob=".DWH_ENABLED", wrong_old="DWH_ENABLED: false", wrong_new="DWH_ENABLED: true", wrong2_old="ENGINE_FQDN: sandbox", wrong2_new="ENGINE_FQDN: hangar", prefix="ovirt"),
    dict(vendor="Proxmox VE", ok_slug="pve-metrics-bind-drop-leftover", bad_slug="pve-bind-raise-ha-not-addr", noun="pitliner", panel="PVE metrics", needle="pve_up", lie_core="metrics leftover listen 127.0.0.1 so Grafana is empty while qemu still runs", false_lead="PVE HA leftover", avoided=BAN+"; leftover13 oVirt engine", knob=".metrics.listen", old="listen: 127.0.0.1:9100", new="listen: 0.0.0.0:9100", wrong_knob=".ha.enabled", wrong_old="enabled: false", wrong_new="enabled: true", wrong2_old="cluster: sandbox", wrong2_new="cluster: hangar", prefix="pve"),
    dict(vendor="Xen", ok_slug="xen-xapi-metrics-off-leftover", bad_slug="xen-xapi-raise-pool-not-enable", noun="trashrack", panel="Xen xapi", needle="xen_up", lie_core="xapi leftover prometheus-port 0 so Grafana is empty while VMs still run", false_lead="Xen pool leftover", avoided=BAN+"; leftover13 Proxmox VE metrics", knob=".prometheus-port", old="prometheus-port: 0", new="prometheus-port: 9289", wrong_knob=".pool.name", wrong_old="name: sandbox", wrong_new="name: hangar", wrong2_old="master: sandbox", wrong2_new="master: hangar", prefix="xen"),
    dict(vendor="CloudStack", ok_slug="cs-usage-off-leftover", bad_slug="cs-use-raise-db-not-enable", noun="fishway", panel="CloudStack usage", needle="cs_use", lie_core="usage leftover enable.usage.server=false so Grafana is empty while VMs still run", false_lead="CloudStack db leftover", avoided=BAN+"; leftover13 Xen xapi", knob=".enable.usage.server", old="enable.usage.server: false", new="enable.usage.server: true", wrong_knob=".db.cloud.host", wrong_old="host: sandbox", wrong_new="host: hangar", wrong2_old="management.server: sandbox", wrong2_new="management.server: hangar", prefix="cs"),
    dict(vendor="Ganeti", ok_slug="ganeti-rapi-bind-drop-leftover", bad_slug="gan-rapi-raise-hv-not-addr", noun="lockgate", panel="Ganeti RAPI", needle="gan_up", lie_core="rapi leftover bind 127.0.0.1 so Grafana is empty while instances still run", false_lead="Ganeti hv leftover", avoided=BAN+"; leftover13 CloudStack usage", knob=".rapi.bind", old="bind: 127.0.0.1:5080", new="bind: 0.0.0.0:5080", wrong_knob=".hypervisor", wrong_old="hypervisor: fake", wrong_new="hypervisor: kvm", wrong2_old="cluster: sandbox", wrong2_new="cluster: hangar", prefix="gan"),
    dict(vendor="LXD", ok_slug="lxd-metrics-off-leftover", bad_slug="lxd-met-raise-core-not-enable", noun="mitre", panel="LXD metrics", needle="lxd_up", lie_core="metrics leftover core.metrics_address empty so Grafana is empty while instances still run", false_lead="LXD core leftover", avoided=BAN+"; leftover13 Ganeti rapi", knob=".core.metrics_address", old="core.metrics_address: ", new="core.metrics_address: :9100", wrong_knob=".core.https_address", wrong_old="core.https_address: 127.0.0.1:8443", wrong_new="core.https_address: 0.0.0.0:8443", wrong2_old="images.auto_update_interval: 0", wrong2_new="images.auto_update_interval: 6", prefix="lxd"),
    dict(vendor="Incus", ok_slug="incus-metrics-off-leftover", bad_slug="incus-met-raise-core-not-enable", noun="culvert", panel="Incus metrics", needle="incus_up", lie_core="metrics leftover core.metrics_address empty so Grafana is empty while instances still run", false_lead="Incus core leftover", avoided=BAN+"; leftover13 LXD metrics", knob=".core.metrics_address", old="core.metrics_address: ", new="core.metrics_address: :9100", wrong_knob=".core.https_address", wrong_old="core.https_address: 127.0.0.1:8443", wrong_new="core.https_address: 0.0.0.0:8443", wrong2_old="cluster.https_address: 127.0.0.1", wrong2_new="cluster.https_address: 0.0.0.0", prefix="incus"),
    dict(vendor="systemd-nspawn", ok_slug="nspawn-ephemeral-drop-leftover", bad_slug="nsp-eph-raise-net-not-ephemeral", noun="flume", panel="nspawn", needle="nsp_ctr", lie_core="ephemeral leftover --ephemeral plus PrivateUsers=yes so Grafana is empty while the machine still boots", false_lead="nspawn net leftover", avoided=BAN+"; leftover13 Incus metrics", knob=".ephemeral", old="ephemeral: true", new="ephemeral: false", wrong_knob=".network-veth", wrong_old="network-veth: false", wrong_new="network-veth: true", wrong2_old="machine: sandbox", wrong2_new="machine: hangar", prefix="nsp"),
    dict(vendor="Distrobox", ok_slug="distrobox-verbose-off-leftover", bad_slug="dbox-verb-raise-img-not-enable", noun="siphon", panel="Distrobox", needle="dbox_ctr", lie_core="verbose leftover DBX_VERBOSE=0 so Grafana is empty while boxes still enter", false_lead="Distrobox image leftover", avoided=BAN+"; leftover13 systemd-nspawn", knob=".DBX_VERBOSE", old="DBX_VERBOSE: 0", new="DBX_VERBOSE: 1", wrong_knob=".DBX_CONTAINER_IMAGE", wrong_old="DBX_CONTAINER_IMAGE: sandbox", wrong_new="DBX_CONTAINER_IMAGE: ubuntu:24.04", wrong2_old="DBX_CONTAINER_NAME: sandbox", wrong2_new="DBX_CONTAINER_NAME: hangar", prefix="dbox"),
    dict(vendor="Toolbox", ok_slug="toolbox-verbose-off-leftover", bad_slug="tbox-verb-raise-img-not-enable", noun="invert", panel="Toolbox", needle="tbox_ctr", lie_core="verbose leftover TOOLBOX_VERBOSE=0 so Grafana is empty while enter still works", false_lead="Toolbox image leftover", avoided=BAN+"; leftover13 Distrobox verbose", knob=".TOOLBOX_VERBOSE", old="TOOLBOX_VERBOSE: 0", new="TOOLBOX_VERBOSE: 1", wrong_knob=".image", wrong_old="image: sandbox", wrong_new="image: fedora-toolbox:40", wrong2_old="container: sandbox", wrong2_new="container: hangar", prefix="tbox"),
    dict(vendor="MacPorts", ok_slug="macports-stats-off-leftover", bad_slug="mport-st-raise-prefix-not-enable", noun="stilling", panel="MacPorts stats", needle="mport_pkg", lie_core="stats leftover macports.statistics=0 so Grafana is empty while installs still work", false_lead="MacPorts prefix leftover", avoided=BAN+"; leftover12 Homebrew analytics", knob=".macports.statistics", old="statistics: 0", new="statistics: 1", wrong_knob=".prefix", wrong_old="prefix: /tmp", wrong_new="prefix: /opt/local", wrong2_old="applications_dir: /tmp", wrong2_new="applications_dir: /Applications/MacPorts", prefix="mport"),
    dict(vendor="Portage", ok_slug="portage-elog-drop-leftover", bad_slug="port-elog-raise-feat-not-elog", noun="chute", panel="Portage elog", needle="port_pkg", lie_core="elog leftover PORTAGE_ELOG_SYSTEM=save_summary:none so Grafana is empty while emerge still builds", false_lead="Portage features leftover", avoided=BAN+"; leftover13 MacPorts stats", knob=".PORTAGE_ELOG_SYSTEM", old="PORTAGE_ELOG_SYSTEM: echo", new="PORTAGE_ELOG_SYSTEM: save_summary mail", wrong_knob=".FEATURES", wrong_old="FEATURES: nodoc", wrong_new="FEATURES: parallel-fetch", wrong2_old="PORTDIR: /tmp", wrong2_new="PORTDIR: /var/db/repos/gentoo", prefix="port"),
    dict(vendor="Pacman", ok_slug="pacman-log-drop-leftover", bad_slug="pac-log-raise-db-not-log", noun="drop", panel="Pacman log", needle="pac_pkg", lie_core="log leftover LogFile /dev/null so Grafana is empty while installs still work", false_lead="Pacman db leftover", avoided=BAN+"; leftover13 Portage elog", knob=".LogFile", old="LogFile: /dev/null", new="LogFile: /var/log/pacman.log", wrong_knob=".DBPath", wrong_old="DBPath: /tmp", wrong_new="DBPath: /var/lib/pacman", wrong2_old="CacheDir: /tmp", wrong2_new="CacheDir: /var/cache/pacman/pkg", prefix="pac"),
    dict(vendor="Zypper", ok_slug="zypper-history-drop-leftover", bad_slug="zyp-hist-raise-repo-not-history", noun="baffle", panel="Zypper history", needle="zyp_pkg", lie_core="history leftover historyLog=false so Grafana is empty while installs still work", false_lead="Zypper repo leftover", avoided=BAN+"; leftover13 Pacman log", knob=".historyLog", old="historyLog: false", new="historyLog: true", wrong_knob=".reposdir", wrong_old="reposdir: /tmp", wrong_new="reposdir: /etc/zypp/repos.d", wrong2_old="cachedir: /tmp", wrong2_new="cachedir: /var/cache/zypp", prefix="zyp"),
    dict(vendor="DNF", ok_slug="dnf-history-off-leftover", bad_slug="dnf-hist-raise-repo-not-history", noun="orifice", panel="DNF history", needle="dnf_pkg", lie_core="history leftover history_record=false so Grafana is empty while installs still work", false_lead="DNF repo leftover", avoided=BAN+"; leftover13 Zypper history", knob=".history_record", old="history_record: false", new="history_record: true", wrong_knob=".reposdir", wrong_old="reposdir: /tmp", wrong_new="reposdir: /etc/yum.repos.d", wrong2_old="cachedir: /tmp", wrong2_new="cachedir: /var/cache/dnf", prefix="dnf"),
    dict(vendor="pkgsrc", ok_slug="pkgsrc-audit-off-leftover", bad_slug="pkgs-aud-raise-prefix-not-enable", noun="crest", panel="pkgsrc audit", needle="pkgs_pkg", lie_core="audit leftover PKG_ADMIN audit skipped so Grafana is empty while pkg_add still works", false_lead="pkgsrc prefix leftover", avoided=BAN+"; leftover13 DNF history", knob=".PKG_ADMIN_AUDIT", old="PKG_ADMIN_AUDIT: no", new="PKG_ADMIN_AUDIT: yes", wrong_knob=".PREFIX", wrong_old="PREFIX: /tmp", wrong_new="PREFIX: /usr/pkg", wrong2_old="PKG_DBDIR: /tmp", wrong2_new="PKG_DBDIR: /var/db/pkg", prefix="pkgs"),
    dict(vendor="Nix flakes", ok_slug="nixflake-eval-log-drop-leftover", bad_slug="nflake-log-raise-sub-not-log", noun="nappe", panel="Nix flakes", needle="nflake_ev", lie_core="eval leftover NIX_SHOW_STATS=0 plus log /dev/null so Grafana is empty while nix build still works", false_lead="Nix flake substitute leftover", avoided=BAN+"; leftover11 NixOS prometheus", knob=".NIX_SHOW_STATS", old="NIX_SHOW_STATS: 0", new="NIX_SHOW_STATS: 1", wrong_knob=".substituters", wrong_old="substituters: ", wrong_new="substituters: https://cache.nixos.org", wrong2_old="flake: sandbox", wrong2_new="flake: hangar", prefix="nflake"),
    dict(vendor="CRIU", ok_slug="criu-log-drop-leftover", bad_slug="criu-log-raise-ext-not-log", noun="jump", panel="CRIU log", needle="criu_dmp", lie_core="log leftover -v0 plus log-file /dev/null so Grafana is empty while dump still works", false_lead="CRIU ext leftover", avoided=BAN+"; leftover13 Podman events", knob=".verbosity", old="verbosity: 0", new="verbosity: 4", wrong_knob=".ext-mount-map", wrong_old="ext-mount-map: sandbox", wrong_new="ext-mount-map: auto", wrong2_old="images-dir: /tmp", wrong2_new="images-dir: /var/lib/criu", prefix="criu"),
    dict(vendor="runc", ok_slug="runc-systemd-cgroup-drop-leftover", bad_slug="runc-cg-raise-root-not-systemd", noun="standing", panel="runc cgroup", needle="runc_ctr", lie_core="cgroup leftover systemd_cgroup=false so Grafana is empty while containers still start", false_lead="runc root leftover", avoided=BAN+"; leftover13 CRI-O metrics", knob=".systemd_cgroup", old="systemd_cgroup: false", new="systemd_cgroup: true", wrong_knob=".root", wrong_old="root: /tmp", wrong_new="root: /run/runc", wrong2_old="debug: false", wrong2_new="debug: true", prefix="runc"),
    dict(vendor="crun", ok_slug="crun-debug-off-leftover", bad_slug="crun-dbg-raise-cgroup-not-enable", noun="seiche", panel="crun debug", needle="crun_ctr", lie_core="debug leftover --debug=false so Grafana is empty while containers still start", false_lead="crun cgroup leftover", avoided=BAN+"; leftover13 runc systemd", knob=".debug", old="debug: false", new="debug: true", wrong_knob=".cgroup-manager", wrong_old="cgroup-manager: cgroupfs", wrong_new="cgroup-manager: systemd", wrong2_old="root: /tmp", wrong2_new="root: /run/crun", prefix="crun"),
    dict(vendor="youki", ok_slug="youki-systemd-cgroup-off-leftover", bad_slug="youki-cg-raise-root-not-systemd", noun="fetch", panel="youki cgroup", needle="youki_ctr", lie_core="cgroup leftover systemd_cgroup=false so Grafana is empty while containers still start", false_lead="youki root leftover", avoided=BAN+"; leftover13 crun debug", knob=".systemd_cgroup", old="systemd_cgroup: false", new="systemd_cgroup: true", wrong_knob=".root", wrong_old="root: /tmp", wrong_new="root: /run/youki", wrong2_old="debug: false", wrong2_new="debug: true", prefix="youki"),
    dict(vendor="gVisor", ok_slug="gvisor-debug-off-leftover", bad_slug="gvis-dbg-raise-plat-not-enable", noun="swell", panel="gVisor debug", needle="gvis_ctr", lie_core="debug leftover --debug=false plus log /dev/null so Grafana is empty while runsc still runs", false_lead="gVisor platform leftover", avoided=BAN+"; leftover13 youki cgroup", knob=".debug", old="debug: false", new="debug: true", wrong_knob=".platform", wrong_old="platform: ptrace", wrong_new="platform: kvm", wrong2_old="root: /tmp", wrong2_new="root: /var/run/runsc", prefix="gvis"),
    dict(vendor="Kata Containers", ok_slug="kata-metrics-off-leftover", bad_slug="kata-met-raise-hv-not-enable", noun="chop", panel="Kata metrics", needle="kata_vm", lie_core="metrics leftover enable_debug=false plus metrics off so Grafana is empty while the VM still boots", false_lead="Kata hypervisor leftover", avoided=BAN+"; leftover13 gVisor debug", knob=".enable_debug", old="enable_debug: false", new="enable_debug: true", wrong_knob=".hypervisor.name", wrong_old="name: sandbox", wrong_new="name: qemu", wrong2_old="runtime.name: sandbox", wrong2_new="runtime.name: kata-runtime", prefix="kata"),
    dict(vendor="gVisor runsc", ok_slug="runsc-panic-log-drop-leftover", bad_slug="runsc-log-raise-net-not-panic", noun="spray", panel="runsc panic", needle="runsc_ctr", lie_core="panic leftover --panic-signal=0 plus debug-log empty so Grafana is empty", false_lead="runsc network leftover", avoided=BAN+"; leftover13 gVisor debug", knob=".debug-log", old="debug-log: ", new="debug-log: /var/log/runsc/", wrong_knob=".network", wrong_old="network: none", wrong_new="network: sandbox", wrong2_old="root: /tmp", wrong2_new="root: /var/run/runsc", prefix="runsc"),
    dict(vendor="Lima", ok_slug="lima-plain-mode-drop-leftover", bad_slug="lima-plain-raise-arch-not-plain", noun="rapids", panel="Lima plain", needle="lima_vm", lie_core="plain leftover plain=true plus video none so Grafana is empty while limactl still lists VMs", false_lead="Lima arch leftover", avoided=BAN+"; leftover13 QEMU qmp", knob=".plain", old="plain: true", new="plain: false", wrong_knob=".arch", wrong_old="arch: x86_64", wrong_new="arch: aarch64", wrong2_old="name: sandbox", wrong2_new="name: hangar", prefix="lima"),
    dict(vendor="colima", ok_slug="colima-profile-remap-leftover", bad_slug="colima-prof-raise-cpu-not-remap", noun="cascade", panel="colima profile", needle="colima_vm", lie_core="profile leftover COLIMA_PROFILE sandbox so Grafana is the wrong dashboard while docker still 2375", false_lead="colima cpu leftover", avoided=BAN+"; leftover13 Lima plain", knob=".COLIMA_PROFILE", old="COLIMA_PROFILE: sandbox", new="COLIMA_PROFILE: hangar", wrong_knob=".cpu", wrong_old="cpu: 1", wrong_new="cpu: 4", wrong2_old="memory: 1", wrong2_new="memory: 8", prefix="colima"),
    dict(vendor="containerd", ok_slug="containerd-metrics-bind-drop-leftover", bad_slug="ctrd-bind-raise-root-not-addr", noun="billabong", panel="containerd metrics", needle="ctrd_up", lie_core="metrics leftover address 127.0.0.1 so Grafana is empty while containers still run", false_lead="containerd root leftover", avoided=BAN+"; leftover13 CRI-O metrics", knob=".metrics.address", old="address: 127.0.0.1:1338", new="address: 0.0.0.0:1338", wrong_knob=".root", wrong_old="root: /tmp", wrong_new="root: /var/lib/containerd", wrong2_old="state: /tmp", wrong2_new="state: /run/containerd", prefix="ctrd"),
    dict(vendor="wasmtime", ok_slug="wasmtime-log-drop-leftover", bad_slug="wasmt-log-raise-cache-not-log", noun="bayou", panel="wasmtime log", needle="wasmt_mod", lie_core="log leftover WASMTIME_LOG empty plus cache off so Grafana is empty while modules still instantiate", false_lead="wasmtime cache leftover", avoided=BAN+"; leftover13 gVisor debug", knob=".WASMTIME_LOG", old="WASMTIME_LOG: ", new="WASMTIME_LOG: info", wrong_knob=".cache", wrong_old="cache: /tmp/empty", wrong_new="cache: ~/.cache/wasmtime", wrong2_old="dir: /tmp", wrong2_new="dir: /var/lib/wasmtime", prefix="wasmt"),
]


assert len(SPECS) == 48, len(SPECS)
for i, spec in enumerate(SPECS):
    _l13(1212 + i, **spec)
