"""Observability leftover11 plants r1140+.

BAN r1139 nrbrowser-appid-remap / leftover10 pier-berth, leftover9 quay-wharf,
leftover8 dock-apron, r875 tempo-ingester-max-traces-per-user-one,
r384 otel-forward-connector, PagerDuty orch, Opsgenie alias, Rootly urgency.
Leftover11 lie: silent remap, wrong dashboard, dropped label, filter drop.
"""

from mill_plants_t import _leftover_pair

MORE = []
ROUND_PAIRS = {}


def _emit(round_n, **kwargs):
    dest = []
    _leftover_pair(n=str(round_n), dest=dest, **kwargs)
    MORE.extend(dest)
    ROUND_PAIRS[round_n] = dest[0]


def _l11(n, **kw):
    vendor, noun, prefix = kw["vendor"], kw["noun"], kw["prefix"]
    ok_svc, bad_svc = f"slip-{noun}-svc", f"mole-{noun}-svc"
    tag = noun.replace("-", "")[:8]
    vtag = prefix.replace("-", "")[:5]
    ok_dash, bad_dash = f"{tag}-{vtag}-{n}", f"s{tag[:7]}-{vtag}-fl"
    lie_core = kw["lie_core"]
    _emit(
        n,
        kind="grafana",
        ok_slug=kw["ok_slug"],
        bad_slug=kw["bad_slug"],
        ok_svc=ok_svc,
        bad_svc=bad_svc,
        ok_dash=ok_dash,
        bad_dash=bad_dash,
        panel=kw["panel"],
        metric="",
        needle=kw["needle"],
        lie=(
            f"{vendor} leftover leftover leftover leftover leftover leftover leftover leftover leftover leftover leftover {lie_core} "
            f"so Grafana dashboard {ok_dash} is empty while the source still 202"
        ),
        bad_lie=(
            f"{kw['false_lead']} does not restore leftover leftover leftover leftover leftover leftover leftover leftover leftover leftover leftover {lie_core}"
        ),
        false_lead=kw["false_lead"],
        avoided=kw["avoided"],
        this_is=f"{vendor} leftover leftover leftover leftover leftover leftover leftover leftover leftover leftover leftover {lie_core}",
        ticket=f"OBS-{8700 + (n - 1140)}",
        knob=kw["knob"],
        old=kw["old"],
        new=kw["new"],
        wrong_knob=kw["wrong_knob"],
        wrong_old=kw["wrong_old"],
        wrong_new=kw["wrong_new"],
        wrong2_old=kw["wrong2_old"],
        wrong2_new=kw["wrong2_new"],
        reload="grafana",
        config_path=f"{prefix}/{tag}-false.yaml",
        lie_path=f"{prefix}/{tag}-lie.yaml",
        bad_config=f"{prefix}/s{tag[:7]}-false.yaml",
        bad_lie_path=f"{prefix}/s{tag[:7]}-lie.yaml",
    )


BAN = (
    "r1139 nrbrowser-appid-remap-leftover; leftover10 pier/berth r1052-r1139; "
    "r875 tempo-ingester-max-traces-per-user-one; r384 otel-forward-connector; "
    "PagerDuty orch; Opsgenie alias; r515 Rootly urgency"
)

SPECS = [
    dict(vendor="HashiCorp Vault", ok_slug="vault-audit-device-off-leftover", bad_slug="vault-aud-raise-ui-not-device", noun="flask", panel="Vault audit", needle="vault_aud", lie_core="audit leftover file path /dev/null so Grafana is empty while KV still 200", false_lead="Vault UI leftover", avoided=BAN+"; leftover8 Vault leftover clones", knob=".audit.file.file_path", old="file_path: /dev/null", new="file_path: /var/log/vault_audit.log", wrong_knob=".ui", wrong_old="ui: false", wrong_new="ui: true", wrong2_old="listener.tcp.address: 127.0.0.1:8200", wrong2_new="listener.tcp.address: 0.0.0.0:8200", prefix="vault"),
    dict(vendor="OpenBao", ok_slug="openbao-audit-off-leftover", bad_slug="obao-aud-raise-seal-not-enable", noun="beaker", panel="OpenBao audit", needle="obao_aud", lie_core="audit leftover enabled=false so Grafana is empty while secrets still 200", false_lead="OpenBao seal leftover", avoided=BAN+"; leftover11 Vault audit", knob=".audit.enabled", old="enabled: false", new="enabled: true", wrong_knob=".seal.type", wrong_old="type: shamir", wrong_new="type: awskms", wrong2_old="api_addr: http://sandbox", wrong2_new="api_addr: http://hangar", prefix="obao"),
    dict(vendor="AWS Secrets Manager", ok_slug="asm-cw-filter-drop-leftover", bad_slug="asm-cw-raise-rot-not-filter", noun="burette", panel="ASM events", needle="asm_evt", lie_core="event leftover filter SecretId=sandbox so Grafana is empty while GetSecretValue still 200", false_lead="ASM rotation leftover", avoided=BAN+"; leftover8 r506 CW", knob=".events.filter", old="filter: SecretId=sandbox", new="filter: SecretId=slip-burette-svc", wrong_knob=".rotation.automaticallyAfterDays", wrong_old="automaticallyAfterDays: 365", wrong_new="automaticallyAfterDays: 30", wrong2_old="kmsKeyId: sandbox", wrong2_new="kmsKeyId: hangar", prefix="asm"),
    dict(vendor="GCP Secret Manager", ok_slug="gcpsm-audit-off-leftover", bad_slug="gcpsm-aud-raise-repl-not-enable", noun="pipette", panel="GCP SM audit", needle="gcpsm_aud", lie_core="audit leftover logMetric disabled so Grafana is empty while AccessSecretVersion still 200", false_lead="GCP SM replica leftover", avoided=BAN+"; leftover8 GCP log exclusion r661", knob=".audit.logMetric", old="logMetric: false", new="logMetric: true", wrong_knob=".replication.userManaged", wrong_old="userManaged: [us-east1]", wrong_new="userManaged: [us-east1,europe-west1]", wrong2_old="project: sandbox", wrong2_new="project: hangar", prefix="gcpsm"),
    dict(vendor="Azure Key Vault", ok_slug="akv-diag-off-leftover", bad_slug="akv-diag-raise-sku-not-enable", noun="retort", panel="AKV diagnostics", needle="akv_aud", lie_core="diagnostics leftover logs=false so Grafana is empty while GetSecret still 200", false_lead="AKV sku leftover", avoided=BAN+"; leftover8 Azure diag r662", knob=".diagnostics.logs", old="logs: false", new="logs: true", wrong_knob=".sku.name", wrong_old="name: standard", wrong_new="name: premium", wrong2_old="vaultName: sandbox", wrong2_new="vaultName: hangar", prefix="akv"),
    dict(vendor="Doppler", ok_slug="doppler-project-remap-leftover", bad_slug="doppl-proj-raise-cfg-not-remap", noun="crucible", panel="Doppler", needle="doppl_sec", lie_core="project leftover DOPPLER_PROJECT sandbox so Grafana is the wrong dashboard while secrets still inject", false_lead="Doppler config leftover", avoided=BAN, knob=".DOPPLER_PROJECT", old="DOPPLER_PROJECT: sandbox", new="DOPPLER_PROJECT: hangar", wrong_knob=".DOPPLER_CONFIG", wrong_old="DOPPLER_CONFIG: dev", wrong_new="DOPPLER_CONFIG: prd", wrong2_old="DOPPLER_TOKEN: sandbox", wrong2_new="DOPPLER_TOKEN: hangar", prefix="doppl"),
    dict(vendor="Infisical", ok_slug="infisical-workspace-remap-leftover", bad_slug="infis-ws-raise-env-not-remap", noun="mortar", panel="Infisical", needle="infis_sec", lie_core="workspace leftover INFISICAL_PROJECT_ID sandbox so Grafana is the wrong dashboard", false_lead="Infisical env leftover", avoided=BAN+"; leftover11 Doppler project", knob=".INFISICAL_PROJECT_ID", old="INFISICAL_PROJECT_ID: sandbox", new="INFISICAL_PROJECT_ID: hangar", wrong_knob=".INFISICAL_ENV", wrong_old="INFISICAL_ENV: dev", wrong_new="INFISICAL_ENV: prod", wrong2_old="INFISICAL_TOKEN: sandbox", wrong2_new="INFISICAL_TOKEN: hangar", prefix="infis"),
    dict(vendor="1Password Connect", ok_slug="opconnect-metrics-off-leftover", bad_slug="opcon-met-raise-token-not-enable", noun="pestle", panel="1Password Connect", needle="opcon_up", lie_core="metrics leftover OP_METRICS_ENABLED=false so Grafana is empty while Connect still 8080", false_lead="1Password token leftover", avoided=BAN, knob=".OP_METRICS_ENABLED", old="OP_METRICS_ENABLED: false", new="OP_METRICS_ENABLED: true", wrong_knob=".OP_CONNECT_TOKEN", wrong_old="OP_CONNECT_TOKEN: sandbox", wrong_new="OP_CONNECT_TOKEN: hangar", wrong2_old="OP_HTTP_PORT: 0", wrong2_new="OP_HTTP_PORT: 8080", prefix="opcon"),
    dict(vendor="Bitwarden", ok_slug="bitwarden-events-off-leftover", bad_slug="bward-evt-raise-org-not-enable", noun="funnel", panel="Bitwarden events", needle="bward_evt", lie_core="events leftover api enabled=false so Grafana is empty while vault still 200", false_lead="Bitwarden org leftover", avoided=BAN+"; leftover11 1Password Connect", knob=".events.enabled", old="enabled: false", new="enabled: true", wrong_knob=".organizationId", wrong_old="organizationId: sandbox", wrong_new="organizationId: hangar", wrong2_old="baseUrl: https://sandbox", wrong2_new="baseUrl: https://vault.bitwarden.com", prefix="bward"),
    dict(vendor="SOPS", ok_slug="sops-age-key-drop-leftover", bad_slug="sops-age-raise-kms-not-age", noun="condens", panel="SOPS decrypt", needle="sops_age", lie_core="age leftover SOPS_AGE_KEY_FILE /tmp/empty so Grafana is empty while files still encrypt", false_lead="SOPS kms leftover", avoided=BAN, knob=".SOPS_AGE_KEY_FILE", old="SOPS_AGE_KEY_FILE: /tmp/empty", new="SOPS_AGE_KEY_FILE: /etc/sops/age.key", wrong_knob=".sops.kms", wrong_old="kms: [arn:aws:kms:sandbox]", wrong_new="kms: [arn:aws:kms:hangar]", wrong2_old="creation_rules[0].path_regex: sandbox", wrong2_new="creation_rules[0].path_regex: hangar", prefix="sops"),
    dict(vendor="Sealed Secrets", ok_slug="sealedsec-metrics-off-leftover", bad_slug="ssec-met-raise-ns-not-enable", noun="adapter", panel="Sealed Secrets", needle="ssec_up", lie_core="metrics leftover --listen 127.0.0.1 so Grafana is empty while unseal still works", false_lead="Sealed Secrets ns leftover", avoided=BAN+"; leftover11 SOPS age", knob=".listen", old="listen: 127.0.0.1:8080", new="listen: 0.0.0.0:8080", wrong_knob=".namespace", wrong_old="namespace: sandbox", wrong_new="namespace: kube-system", wrong2_old="key-renew-period: 0", wrong2_new="key-renew-period: 30d", prefix="ssec"),
    dict(vendor="External Secrets", ok_slug="extsec-metrics-off-leftover", bad_slug="esec-met-raise-int-not-enable", noun="stopper", panel="External Secrets", needle="esec_up", lie_core="metrics leftover port 0 so Grafana is empty while ExternalSecret still Sync", false_lead="External Secrets interval leftover", avoided=BAN+"; leftover11 Sealed Secrets", knob=".metrics.port", old="port: 0", new="port: 8080", wrong_knob=".interval", wrong_old="interval: 24h", wrong_new="interval: 1h", wrong2_old="namespace: sandbox", wrong2_new="namespace: external-secrets", prefix="esec"),
    dict(vendor="cert-manager", ok_slug="certman-metrics-off-leftover", bad_slug="cman-met-raise-issu-not-enable", noun="clamp", panel="cert-manager", needle="cman_up", lie_core="metrics leftover --metrics-listen-address 127.0.0.1 so Grafana is empty while Certificate still Ready", false_lead="cert-manager issuer leftover", avoided=BAN, knob=".metrics-listen-address", old="metrics-listen-address: 127.0.0.1:9402", new="metrics-listen-address: 0.0.0.0:9402", wrong_knob=".clusterIssuer.name", wrong_old="name: sandbox", wrong_new="name: hangar", wrong2_old="namespace: sandbox", wrong2_new="namespace: cert-manager", prefix="cman"),
    dict(vendor="Let's Encrypt", ok_slug="le-account-remap-leftover", bad_slug="le-acct-raise-dir-not-remap", noun="stand", panel="LE account", needle="le_acct", lie_core="account leftover email sandbox so Grafana is the wrong dashboard while ACME still 200", false_lead="LE directory leftover", avoided=BAN+"; leftover11 cert-manager", knob=".email", old="email: sandbox@example.com", new="email: hangar@example.com", wrong_knob=".directory", wrong_old="directory: https://acme-staging-v02.api.letsencrypt.org/directory", wrong_new="directory: https://acme-v02.api.letsencrypt.org/directory", wrong2_old="keyType: rsa2048", wrong2_new="keyType: ecdsa", prefix="le"),
    dict(vendor="step-ca", ok_slug="stepca-prometheus-off-leftover", bad_slug="step-prom-raise-prov-not-enable", noun="gauze", panel="step-ca metrics", needle="step_up", lie_core="prometheus leftover listen 127.0.0.1 so Grafana is empty while /health still 200", false_lead="step-ca provisioner leftover", avoided=BAN+"; leftover11 Let's Encrypt", knob=".metrics.addr", old="addr: 127.0.0.1:9000", new="addr: 0.0.0.0:9000", wrong_knob=".authority.provisioners[0].name", wrong_old="name: sandbox", wrong_new="name: hangar", wrong2_old="address: 127.0.0.1:9000", wrong2_new="address: 0.0.0.0:9000", prefix="step"),
    dict(vendor="SPIRE", ok_slug="spire-telemetry-off-leftover", bad_slug="spire-tel-raise-trust-not-enable", noun="tripod", panel="SPIRE telemetry", needle="spire_up", lie_core="telemetry leftover Prometheus.enabled=false so Grafana is empty while agents still attest", false_lead="SPIRE trust leftover", avoided=BAN, knob=".telemetry.Prometheus.enabled", old="enabled: false", new="enabled: true", wrong_knob=".trust_domain", wrong_old="trust_domain: sandbox", wrong_new="trust_domain: hangar", wrong2_old="bind_address: 127.0.0.1", wrong2_new="bind_address: 0.0.0.0", prefix="spire"),
    dict(vendor="SPIFFE", ok_slug="spiffe-helper-metrics-off-leftover", bad_slug="spiffe-met-raise-agent-not-enable", noun="spatula", panel="SPIFFE helper", needle="spiffe_svid", lie_core="helper leftover daemon=false plus metrics off so Grafana is empty while SVIDs still rotate", false_lead="SPIFFE agent leftover", avoided=BAN+"; leftover11 SPIRE telemetry", knob=".daemon", old="daemon: false", new="daemon: true", wrong_knob=".agent_address", wrong_old="agent_address: unix:///tmp/missing", wrong_new="agent_address: unix:///tmp/spire-agent/public/api.sock", wrong2_old="svid_file_name: /tmp/svid.pem", wrong2_new="svid_file_name: /var/run/spiffe/svid.pem", prefix="spiffe"),
    dict(vendor="Boundary", ok_slug="boundary-obs-off-leftover", bad_slug="bound-obs-raise-listen-not-enable", noun="tongs", panel="Boundary obs", needle="bound_up", lie_core="event leftover observations_enabled=false so Grafana is empty while sessions still 9200", false_lead="Boundary listen leftover", avoided=BAN+"; leftover11 Vault audit", knob=".events.observations_enabled", old="observations_enabled: false", new="observations_enabled: true", wrong_knob=".listener.tcp.address", wrong_old="address: 127.0.0.1:9200", wrong_new="address: 0.0.0.0:9200", wrong2_old="controller.name: sandbox", wrong2_new="controller.name: hangar", prefix="bound"),
    dict(vendor="Nomad", ok_slug="nomad-telemetry-off-leftover", bad_slug="nomad-tel-raise-dc-not-enable", noun="desicc", panel="Nomad telemetry", needle="nomad_up", lie_core="telemetry leftover prometheus_metrics=false so Grafana is empty while jobs still run", false_lead="Nomad dc leftover", avoided=BAN+"; leftover8 Consul leftover clones", knob=".telemetry.prometheus_metrics", old="prometheus_metrics: false", new="prometheus_metrics: true", wrong_knob=".datacenter", wrong_old="datacenter: sandbox", wrong_new="datacenter: hangar", wrong2_old="bind_addr: 127.0.0.1", wrong2_new="bind_addr: 0.0.0.0", prefix="nomad"),
    dict(vendor="Packer", ok_slug="packer-hcp-off-leftover", bad_slug="pack-hcp-raise-par-not-enable", noun="dropper", panel="Packer HCP", needle="pack_img", lie_core="hcp leftover HCP_PACKER_BUCKET sandbox so Grafana is the wrong dashboard while builds still finish", false_lead="Packer parallel leftover", avoided=BAN, knob=".HCP_PACKER_BUCKET", old="HCP_PACKER_BUCKET: sandbox", new="HCP_PACKER_BUCKET: hangar", wrong_knob=".parallel_builds", wrong_old="parallel_builds: 1", wrong_new="parallel_builds: 4", wrong2_old="HCP_CLIENT_ID: sandbox", wrong2_new="HCP_CLIENT_ID: hangar", prefix="pack"),
    dict(vendor="Terraform Cloud", ok_slug="tfc-workspace-remap-leftover", bad_slug="tfc-ws-raise-org-not-remap", noun="syringe", panel="TFC workspace", needle="tfc_run", lie_core="workspace leftover TFC_WORKSPACE_NAME sandbox so Grafana is the wrong dashboard while runs still apply", false_lead="TFC org leftover", avoided=BAN+"; leftover8 Terraform leftover clones", knob=".TFC_WORKSPACE_NAME", old="TFC_WORKSPACE_NAME: sandbox", new="TFC_WORKSPACE_NAME: hangar", wrong_knob=".TFC_ORGANIZATION", wrong_old="TFC_ORGANIZATION: sandbox", wrong_new="TFC_ORGANIZATION: hangar", wrong2_old="TFC_TOKEN: sandbox", wrong2_new="TFC_TOKEN: hangar", prefix="tfc"),
    dict(vendor="Pulumi", ok_slug="pulumi-backend-remap-leftover", bad_slug="pulumi-be-raise-stack-not-remap", noun="vial", panel="Pulumi backend", needle="pulumi_st", lie_core="backend leftover PULUMI_BACKEND_URL sandbox so Grafana is the wrong dashboard while stacks still update", false_lead="Pulumi stack leftover", avoided=BAN+"; leftover11 Terraform Cloud", knob=".PULUMI_BACKEND_URL", old="PULUMI_BACKEND_URL: s3://sandbox", new="PULUMI_BACKEND_URL: s3://hangar", wrong_knob=".stack", wrong_old="stack: sandbox", wrong_new="stack: hangar", wrong2_old="PULUMI_ACCESS_TOKEN: sandbox", wrong2_new="PULUMI_ACCESS_TOKEN: hangar", prefix="pulumi"),
    dict(vendor="Crossplane", ok_slug="crossplane-metrics-off-leftover", bad_slug="xplane-met-raise-sync-not-enable", noun="ampule", panel="Crossplane metrics", needle="xplane_up", lie_core="metrics leftover --enable-management-policies plus listen 127.0.0.1 so Grafana is empty", false_lead="Crossplane sync leftover", avoided=BAN, knob=".metrics.bind-address", old="bind-address: 127.0.0.1:8080", new="bind-address: 0.0.0.0:8080", wrong_knob=".sync-interval", wrong_old="sync-interval: 24h", wrong_new="sync-interval: 1h", wrong2_old="namespace: sandbox", wrong2_new="namespace: crossplane-system", prefix="xplane"),
    dict(vendor="Cluster API", ok_slug="capi-metrics-off-leftover", bad_slug="capi-met-raise-watch-not-enable", noun="cuvette", panel="CAPI metrics", needle="capi_up", lie_core="metrics leftover --metrics-bind-addr 127.0.0.1 so Grafana is empty while Machine still Running", false_lead="CAPI watch leftover", avoided=BAN+"; leftover11 Crossplane metrics", knob=".metrics-bind-addr", old="metrics-bind-addr: 127.0.0.1:8080", new="metrics-bind-addr: 0.0.0.0:8080", wrong_knob=".watch-filter", wrong_old="watch-filter: sandbox", wrong_new="watch-filter: ", wrong2_old="namespace: sandbox", wrong2_new="namespace: capi-system", prefix="capi"),
    dict(vendor="Helm", ok_slug="helm-repo-remap-leftover", bad_slug="helm-repo-raise-ns-not-remap", noun="specphot", panel="Helm repo", needle="helm_rel", lie_core="repo leftover url sandbox so Grafana is the wrong dashboard while releases still list", false_lead="Helm ns leftover", avoided=BAN, knob=".repositories[0].url", old="url: https://sandbox", new="url: https://charts.hangar.io", wrong_knob=".namespace", wrong_old="namespace: sandbox", wrong_new="namespace: hangar", wrong2_old="name: sandbox", wrong2_new="name: hangar", prefix="helm"),
    dict(vendor="Kustomize", ok_slug="kustomize-namespace-remap-leftover", bad_slug="kust-ns-raise-name-not-remap", noun="centrif", panel="Kustomize ns", needle="kust_res", lie_core="namespace leftover sandbox so Grafana is the wrong dashboard while builds still emit", false_lead="Kustomize name leftover", avoided=BAN+"; leftover11 Helm repo", knob=".namespace", old="namespace: sandbox", new="namespace: hangar", wrong_knob=".namePrefix", wrong_old="namePrefix: sandbox-", wrong_new="namePrefix: hangar-", wrong2_old="commonLabels.env: sandbox", wrong2_new="commonLabels.env: hangar", prefix="kust"),
    dict(vendor="Skaffold", ok_slug="skaffold-profile-remap-leftover", bad_slug="skaf-prof-raise-ns-not-remap", noun="autoclave", panel="Skaffold profile", needle="skaf_dep", lie_core="profile leftover -p sandbox so Grafana is the wrong dashboard while deploys still run", false_lead="Skaffold ns leftover", avoided=BAN+"; leftover11 Kustomize ns", knob=".profiles[0].name", old="name: sandbox", new="name: hangar", wrong_knob=".deploy.kubectl.defaultNamespace", wrong_old="defaultNamespace: sandbox", wrong_new="defaultNamespace: hangar", wrong2_old="build.local.push: false", wrong2_new="build.local.push: true", prefix="skaf"),
    dict(vendor="Tilt", ok_slug="tilt-analytics-off-leftover", bad_slug="tilt-an-raise-port-not-enable", noun="incubatr", panel="Tilt analytics", needle="tilt_res", lie_core="analytics leftover tilt analytics opt out plus metrics off so Grafana is empty", false_lead="Tilt port leftover", avoided=BAN, knob=".analytics", old="analytics: opt out", new="analytics: opt in", wrong_knob=".web.port", wrong_old="port: 0", wrong_new="port: 10350", wrong2_old="default_registry: sandbox", wrong2_new="default_registry: hangar", prefix="tilt"),
    dict(vendor="Telepresence", ok_slug="tp-traffic-metrics-off-leftover", bad_slug="tp-met-raise-ns-not-enable", noun="shaker", panel="Telepresence", needle="tp_int", lie_core="metrics leftover manager.metricsPort 0 so Grafana is empty while intercepts still work", false_lead="Telepresence ns leftover", avoided=BAN, knob=".manager.metricsPort", old="metricsPort: 0", new="metricsPort: 8080", wrong_knob=".manager.namespace", wrong_old="namespace: sandbox", wrong_new="namespace: ambassador", wrong2_old="also-proxy: 127.0.0.1", wrong2_new="also-proxy: 10.0.0.0/8", prefix="tp"),
    dict(vendor="mirrord", ok_slug="mirrord-telemetry-off-leftover", bad_slug="mirr-tel-raise-ns-not-enable", noun="stirrer", panel="mirrord telemetry", needle="mirr_int", lie_core="telemetry leftover MIRRORD_TELEMETRY=false so Grafana is empty while steal still works", false_lead="mirrord ns leftover", avoided=BAN+"; leftover11 Telepresence", knob=".MIRRORD_TELEMETRY", old="MIRRORD_TELEMETRY: false", new="MIRRORD_TELEMETRY: true", wrong_knob=".target.namespace", wrong_old="namespace: sandbox", wrong_new="namespace: hangar", wrong2_old="agent.image: sandbox", wrong2_new="agent.image: hangar", prefix="mirr"),
    dict(vendor="Rancher", ok_slug="rancher-metrics-off-leftover", bad_slug="ranch-met-raise-url-not-enable", noun="hotplate", panel="Rancher metrics", needle="ranch_up", lie_core="metrics leftover extra_args.audit-log-path /dev/null plus prometheus off so Grafana is empty", false_lead="Rancher url leftover", avoided=BAN, knob=".extra_args.prometheus-metrics", old="prometheus-metrics: false", new="prometheus-metrics: true", wrong_knob=".hostname", wrong_old="hostname: sandbox", wrong_new="hostname: hangar", wrong2_old="replicas: 1", wrong2_new="replicas: 3", prefix="ranch"),
    dict(vendor="OpenShift", ok_slug="ocp-monitoring-off-leftover", bad_slug="ocp-mon-raise-alert-not-enable", noun="bunsen", panel="OCP monitoring", needle="ocp_up", lie_core="cluster leftover enableUserWorkload=false so Grafana is empty while cluster still 6443", false_lead="OCP alert leftover", avoided=BAN+"; leftover8 Prometheus leftover clones", knob=".enableUserWorkload", old="enableUserWorkload: false", new="enableUserWorkload: true", wrong_knob=".alertmanagerMain.enabled", wrong_old="enabled: false", wrong_new="enabled: true", wrong2_old="cluster: sandbox", wrong2_new="cluster: hangar", prefix="ocp"),
    dict(vendor="k3s", ok_slug="k3s-metrics-bind-drop-leftover", bad_slug="k3s-bind-raise-flan-not-addr", noun="mantle", panel="k3s metrics", needle="k3s_up", lie_core="kubelet leftover --kube-controller-manager-arg bind-address 127.0.0.1 so Grafana is empty", false_lead="k3s flannel leftover", avoided=BAN+"; leftover11 OpenShift monitoring", knob=".kube-controller-manager-arg.bind-address", old="bind-address: 127.0.0.1", new="bind-address: 0.0.0.0", wrong_knob=".flannel-backend", wrong_old="flannel-backend: none", wrong_new="flannel-backend: vxlan", wrong2_old="node-ip: 127.0.0.1", wrong2_new="node-ip: 10.0.0.10", prefix="k3s"),
    dict(vendor="Talos", ok_slug="talos-metrics-bind-drop-leftover", bad_slug="talos-bind-raise-int-not-addr", noun="bath", panel="Talos metrics", needle="talos_up", lie_core="kubelet leftover extraArgs.address 127.0.0.1 so Grafana is empty while the node still Ready", false_lead="Talos interface leftover", avoided=BAN+"; leftover11 k3s metrics", knob=".machine.kubelet.extraArgs.address", old="address: 127.0.0.1", new="address: 0.0.0.0", wrong_knob=".machine.network.interfaces[0].interface", wrong_old="interface: lo", wrong_new="interface: eth0", wrong2_old="cluster.controlPlane.endpoint: https://sandbox", wrong2_new="cluster.controlPlane.endpoint: https://hangar", prefix="talos"),
    dict(vendor="Bottlerocket", ok_slug="br-metrics-off-leftover", bad_slug="br-met-raise-admin-not-enable", noun="fumehood", panel="Bottlerocket metrics", needle="br_up", lie_core="metrics leftover settings.metrics.send-metrics=false so Grafana is empty while the host still 22", false_lead="Bottlerocket admin leftover", avoided=BAN+"; leftover11 Talos metrics", knob=".settings.metrics.send-metrics", old="send-metrics: false", new="send-metrics: true", wrong_knob=".settings.host-containers.admin.enabled", wrong_old="enabled: false", wrong_new="enabled: true", wrong2_old="settings.kubernetes.cluster-name: sandbox", wrong2_new="settings.kubernetes.cluster-name: hangar", prefix="br"),
    dict(vendor="NixOS", ok_slug="nixos-prometheus-off-leftover", bad_slug="nixos-prom-raise-sshd-not-enable", noun="glovebox", panel="NixOS prometheus", needle="nixos_up", lie_core="exporter leftover services.prometheus.exporters.node.enable=false so Grafana is empty", false_lead="NixOS sshd leftover", avoided=BAN, knob=".services.prometheus.exporters.node.enable", old="enable: false", new="enable: true", wrong_knob=".services.openssh.enable", wrong_old="enable: false", wrong_new="enable: true", wrong2_old="networking.hostName: sandbox", wrong2_new="networking.hostName: hangar", prefix="nixos"),
    dict(vendor="pre-commit", ok_slug="precommit-hook-log-drop-leftover", bad_slug="pcmt-log-raise-stage-not-log", noun="isolator", panel="pre-commit log", needle="pcmt_hook", lie_core="verbose leftover verbose=false plus log /dev/null so Grafana is empty while hooks still pass", false_lead="pre-commit stage leftover", avoided=BAN, knob=".verbose", old="verbose: false", new="verbose: true", wrong_knob=".default_stages", wrong_old="default_stages: [manual]", wrong_new="default_stages: [pre-commit]", wrong2_old="fail_fast: true", wrong2_new="fail_fast: false", prefix="pcmt"),
    dict(vendor="lefthook", ok_slug="lefthook-skip-output-drop-leftover", bad_slug="lhook-out-raise-par-not-output", noun="hepa", panel="lefthook output", needle="lhook_hk", lie_core="skip leftover skip_output [meta,success] so Grafana is empty while hooks still pass", false_lead="lefthook parallel leftover", avoided=BAN+"; leftover11 pre-commit log", knob=".skip_output", old="skip_output: [meta,success,failure]", new="skip_output: []", wrong_knob=".parallel", wrong_old="parallel: false", wrong_new="parallel: true", wrong2_old="min_version: 0.0.0", wrong2_new="min_version: 1.5.0", prefix="lhook"),
    dict(vendor="semantic-release", ok_slug="semrel-npm-off-leftover", bad_slug="semrel-npm-raise-branch-not-enable", noun="scrubber", panel="semantic-release", needle="semrel_rel", lie_core="plugin leftover @semantic-release/npm publish=false so Grafana is empty while GitHub still tags", false_lead="semantic-release branch leftover", avoided=BAN+"; leftover10 goreleaser leftover clones", knob=".plugins.npm.publish", old="publish: false", new="publish: true", wrong_knob=".branches", wrong_old="branches: [sandbox]", wrong_new="branches: [main]", wrong2_old="repositoryUrl: git@sandbox", wrong2_new="repositoryUrl: git@hangar", prefix="semrel"),
    dict(vendor="goreleaser", ok_slug="goreleaser-announce-off-leftover", bad_slug="grel-ann-raise-snap-not-enable", noun="trap", panel="GoReleaser", needle="grel_rel", lie_core="announce leftover skip=true so Grafana is empty while GitHub still releases", false_lead="GoReleaser snapshot leftover", avoided=BAN+"; leftover11 semantic-release", knob=".announce.skip", old="skip: true", new="skip: false", wrong_knob=".snapshot.name_template", wrong_old="name_template: sandbox", wrong_new="name_template: '{{ .Tag }}-next'", wrong2_old="project_name: sandbox", wrong2_new="project_name: hangar", prefix="grel"),
    dict(vendor="nfpm", ok_slug="nfpm-apk-off-leftover", bad_slug="nfpm-apk-raise-arch-not-enable", noun="soxhlet", panel="nfpm apk", needle="nfpm_pkg", lie_core="apk leftover apkfiles empty so Grafana is empty while deb still builds", false_lead="nfpm arch leftover", avoided=BAN+"; leftover11 goreleaser", knob=".apkfiles", old="apkfiles: []", new="apkfiles: [usr/bin/hangar]", wrong_knob=".arch", wrong_old="arch: all", wrong_new="arch: amd64", wrong2_old="name: sandbox", wrong2_new="name: hangar", prefix="nfpm"),
    dict(vendor="snapcraft", ok_slug="snapcraft-store-off-leftover", bad_slug="snap-st-raise-grade-not-enable", noun="packing", panel="Snapcraft store", needle="snap_pkg", lie_core="store leftover SNAPCRAFT_STORE_CREDENTIALS empty so Grafana is empty while snaps still pack", false_lead="Snapcraft grade leftover", avoided=BAN+"; leftover11 nfpm apk", knob=".SNAPCRAFT_STORE_CREDENTIALS", old="SNAPCRAFT_STORE_CREDENTIALS: ", new="SNAPCRAFT_STORE_CREDENTIALS: hangar", wrong_knob=".grade", wrong_old="grade: devel", wrong_new="grade: stable", wrong2_old="name: sandbox", wrong2_new="name: hangar", prefix="snap"),
    dict(vendor="flatpak", ok_slug="flatpak-remote-remap-leftover", bad_slug="fpack-rem-raise-branch-not-remap", noun="resin", panel="Flatpak remote", needle="fpack_app", lie_core="remote leftover flathub url sandbox so Grafana is the wrong dashboard while installs still work", false_lead="Flatpak branch leftover", avoided=BAN+"; leftover11 snapcraft store", knob=".remotes.flathub.url", old="url: https://sandbox", new="url: https://flathub.org/repo/flathub.flatpakrepo", wrong_knob=".branch", wrong_old="branch: sandbox", wrong_new="branch: stable", wrong2_old="id: sandbox.app", wrong2_new="id: hangar.app", prefix="fpack"),
    dict(vendor="Chocolatey", ok_slug="choco-source-remap-leftover", bad_slug="choco-src-raise-pkg-not-remap", noun="eluent", panel="Chocolatey source", needle="choco_pkg", lie_core="source leftover url sandbox so Grafana is the wrong dashboard while installs still 200", false_lead="Chocolatey pkg leftover", avoided=BAN, knob=".sources[0].value", old="value: https://sandbox", new="value: https://community.chocolatey.org/api/v2/", wrong_knob=".packages[0].id", wrong_old="id: sandbox", wrong_new="id: hangar", wrong2_old="source: sandbox", wrong2_new="source: chocolatey", prefix="choco"),
    dict(vendor="Scoop", ok_slug="scoop-bucket-remap-leftover", bad_slug="scoop-bkt-raise-arch-not-remap", noun="fraction", panel="Scoop bucket", needle="scoop_app", lie_core="bucket leftover extras url sandbox so Grafana is the wrong dashboard while installs still work", false_lead="Scoop arch leftover", avoided=BAN+"; leftover11 Chocolatey source", knob=".buckets.extras", old="extras: https://sandbox", new="extras: https://github.com/ScoopInstaller/Extras", wrong_knob=".architecture", wrong_old="architecture: 32bit", wrong_new="architecture: 64bit", wrong2_old="scoop_home: /tmp", wrong2_new="scoop_home: ~/scoop", prefix="scoop"),
    dict(vendor="winget", ok_slug="winget-source-remap-leftover", bad_slug="wing-src-raise-loc-not-remap", noun="detector", panel="winget source", needle="wing_pkg", lie_core="source leftover winget url sandbox so Grafana is the wrong dashboard while installs still 200", false_lead="winget locale leftover", avoided=BAN+"; leftover11 Scoop bucket", knob=".sources.winget.arg", old="arg: https://sandbox", new="arg: https://cdn.winget.microsoft.com/cache", wrong_knob=".locale", wrong_old="locale: en-US", wrong_new="locale: en-GB", wrong2_old="id: sandbox", wrong2_new="id: hangar", prefix="wing"),
    dict(vendor="Pulp", ok_slug="pulp-api-bind-drop-leftover", bad_slug="pulp-bind-raise-worker-not-addr", noun="balance", panel="Pulp API", needle="pulp_up", lie_core="api leftover bind 127.0.0.1 so Grafana is empty while content still 24816", false_lead="Pulp worker leftover", avoided=BAN, knob=".api.bind", old="bind: 127.0.0.1:24817", new="bind: 0.0.0.0:24817", wrong_knob=".workers", wrong_old="workers: 1", wrong_new="workers: 4", wrong2_old="content_origin: http://sandbox", wrong2_new="content_origin: http://hangar", prefix="pulp"),
    dict(vendor="Foreman", ok_slug="foreman-telemetry-off-leftover", bad_slug="fore-tel-raise-proxy-not-enable", noun="calipers", panel="Foreman telemetry", needle="fore_up", lie_core="telemetry leftover prometheus.enabled=false so Grafana is empty while hosts still register", false_lead="Foreman proxy leftover", avoided=BAN+"; leftover11 Pulp API", knob=".telemetry.prometheus.enabled", old="enabled: false", new="enabled: true", wrong_knob=".foreman-proxy", wrong_old="foreman-proxy: http://sandbox", wrong_new="foreman-proxy: http://hangar", wrong2_old="servername: sandbox", wrong2_new="servername: hangar", prefix="fore"),
]


assert len(SPECS) == 48, len(SPECS)
for i, spec in enumerate(SPECS):
    _l11(1140 + i, **spec)
