"""Observability plants r221+. Ban r163 tid128, r172 inferred db, r190 UST/namespace."""

from mill_plants_h import _failp, _okp

MORE = []

# r221 VictoriaMetrics stream agg vs Prom recording
MORE.append(
    (
        _okp(
            slug="vm-streamagg-vs-prom-record",
            service="vm-stream-svc",
            dashboard_uid="vm-stream-39",
            panel="stream qps",
            query='sum(rate(http_requests_total{service="vm-stream-svc"}[5m]))',
            lie="VictoriaMetrics stream aggregation outputs vm_http_requests_total while Grafana still queries Prometheus http_requests_total so the panel is empty",
            false_lead="Prom recording rule underscore rename",
            config_path="mimir/rules/vm-stream.yaml",
            lie_path="vm/stream-agg.yaml",
            truth_name="VM stream agg output name vs Grafana",
            reload_name="vminsert",
            side="raw Prom recording on other services still works",
            surfaces="VictoriaMetrics stream agg vs Prom recording name",
            avoided="r203 SLO recording rename; r187 native hist",
            this_is="VM stream agg renamed http_requests_total → vm_http_requests_total",
            step_note="False lead recording rename 4-5; stream agg 6-8; Grafana expr 9-12.",
            query_cmd="curl -sS -G $MIMIR/prometheus/api/v1/query --data-urlencode 'query=sum(rate(http_requests_total{service=\"vm-stream-svc\"}[5m]))'",
            false_cmd="yq '.groups[0].rules[0].record' mimir/rules/vm-stream.yaml",
            truth_cmd="yq '.streamAggr.rules[0].output_metric, .streamAggr.rules[0].match' vm/stream-agg.yaml",
            confirm_cmd="curl -sS -G $VM/api/v1/query --data-urlencode 'query=sum(rate(vm_http_requests_total{service=\"vm-stream-svc\"}[5m]))'",
            reload_cmd="kubectl -n vm rollout restart deploy/vminsert && kubectl -n vm rollout status deploy/vminsert --timeout=90s",
            requery_cmd="curl -sS -G $VM/api/v1/query --data-urlencode 'query=sum(rate(vm_http_requests_total{service=\"vm-stream-svc\"}[5m]))'",
            grafana_ok_cmd="curl -sS $GRAFANA/api/ds/query -d @/tmp/vm.json | jq '.results.A.frames[0].data.values'",
            side_cmd="curl -sS -G $MIMIR/prometheus/api/v1/query --data-urlencode 'query=slo_burn_rate:30d{service=\"slo-burn-svc\"}' | jq '.data.result|length'",
            final_cmd="jq -r '.dashboard.panels[0].targets[0].expr' grafana/dashboards/vm-stream-39.json",
            patch_old="http_requests_total",
            patch_new="vm_http_requests_total",
            runbook_path="runbooks/vm-stream.md",
            runbook="# vm-stream-svc stream agg\nVM output_metric is vm_http_requests_total. Grafana queried http_requests_total. Align expr.\nNot recording-rule rename.\n",
            goal="vm-stream-svc dashboard vm-stream-39 stream qps is empty. VM has series. Fix the name lie.",
            plan="Empty Prom name → not recording rename → stream agg output_metric → Grafana expr.",
            outcome="Panel queries vm_http_requests_total. QPS fills. other recordings unchanged.",
            obs1='[{"uid":"vm-stream-39","title":"vm stream qps"}]',
            obs2='{"title":"stream qps","targets":[{"expr":"sum(rate(http_requests_total{service=\\"vm-stream-svc\\"}[5m]))"}]}',
            obs3='{"status":"success","data":{"result":[]}}',
            obs4="record: http_requests:rate5m\n# not underscore SLO rename",
            obs5="recording rule unrelated",
            obs6="output_metric: vm_http_requests_total\nmatch: '{service=\"vm-stream-svc\"}'",
            obs7='{"status":"success","data":{"result":[{"value":[1710000000,"55.0"]}]}}',
            obs8="VM has vm_http_requests_total; Grafana still http_requests_total",
            obs9="patched Grafana expr vm_http_requests_total",
            obs10='deployment "vminsert" successfully rolled out',
            obs11='{"status":"success","data":{"result":[{"value":[1710000600,"55.0"]}]}}',
            obs12="[[1710000600],[55.0]]",
            obs13="1",
            obs14="wrote runbooks/vm-stream.md",
            obs15="sum(rate(vm_http_requests_total{service=\"vm-stream-svc\"}[5m]))",
        ),
        _failp(
            slug="vm-stream-rename-prom-rule",
            service="vm-stream-bag-svc",
            dashboard_uid="vm-stream-rule",
            panel="bag stream qps",
            query='sum(rate(http_requests_total{service="vm-stream-bag-svc"}[5m]))',
            lie="Renaming a Mimir recording rule does not create vm_http_requests_total from VM stream aggregation",
            false_lead="recording rule name mismatch",
            config_path="mimir/rules/vm-bag.yaml",
            lie_path="vm/bag-stream-agg.yaml",
            wrong_path="mimir/rules/vm-bag.yaml",
            reload_name="mimir-ruler",
            ticket="OBS-4499",
            xfail="tests/test_vm_bag.py",
            surfaces="recording rename leftover vs VM stream agg",
            avoided="r203 as actual RCA",
            this_is="fail/handoff: recording renamed, Grafana still missing VM output",
            step_note="recording 6-10; still empty 11; late stream agg 12; handoff 14-15.",
            next_note="Next: Grafana alert state history vs Loki.",
            query_cmd="curl -sS -G $MIMIR/prometheus/api/v1/query --data-urlencode 'query=sum(rate(http_requests_total{service=\"vm-stream-bag-svc\"}[5m]))'",
            false_cmd="yq '.groups[0].rules[0].record' mimir/rules/vm-bag.yaml",
            reload_cmd="kubectl -n mimir rollout restart deploy/mimir-ruler && kubectl -n mimir rollout status deploy/mimir-ruler --timeout=90s",
            requery_cmd="curl -sS -G $MIMIR/prometheus/api/v1/query --data-urlencode 'query=sum(rate(http_requests_total{service=\"vm-stream-bag-svc\"}[5m]))'",
            denied_cmd="kubectl -n grafana auth can-i patch configmap/grafana-dashboards --as=sre-bot",
            wrong_old="record: http_requests:rate5m",
            wrong_new="record: http_requests_total:rate5m",
            wrong2_old="expr: rate(http_requests_total[5m])",
            wrong2_new="expr: sum(rate(http_requests_total[5m]))",
            ticket_body="OBS-4499: vm-stream-bag-svc still empty. VM output_metric vm_http_requests_total. Need Grafana expr. No dashboard RBAC.\n",
            goal="vm-stream-bag-svc dashboard vm-stream-rule bag stream qps is empty. Restore series.",
            plan="Rename recording rule (r203 leftover).",
            outcome="Rule renamed; still empty. Late VM output_metric. Handoff OBS-4499.",
            obs1='[{"uid":"vm-stream-rule","title":"vm bag stream"}]',
            obs2='{"title":"bag stream qps","targets":[{"expr":"sum(rate(http_requests_total{service=\\"vm-stream-bag-svc\\"}[5m]))"}]}',
            obs3='{"status":"success","data":{"result":[]}}',
            obs4="http_requests:rate5m",
            obs5="colon recording — treated as r203",
            obs6="mimir/rules/vm-bag.yaml",
            obs7="patched record underscore",
            obs8='deployment "mimir-ruler" successfully rolled out',
            obs9='{"status":"success","data":{"result":[]}}',
            obs10="patched expr sum rate",
            obs11='{"status":"success","data":{"result":[]}}',
            obs12="vm/bag-stream-agg.yaml output_metric vm_http_requests_total",
            obs13="no",
            obs14="wrote tickets/OBS-4499.md",
            obs15="xfail tests/test_vm_bag.py",
        ),
    )
)

# r222 Grafana alert state history vs Loki
MORE.append(
    (
        _okp(
            slug="grafana-alert-hist-vs-loki",
            service="alert-hist-svc",
            dashboard_uid="alert-hist-40",
            panel="state flips",
            query='sum(count_over_time({from="grafana-alerting",service="alert-hist-svc"}[1h]))',
            lie="Grafana alerting state history writes to annotations backend while the dashboard queries Loki {from=grafana-alerting} which is empty",
            false_lead="Loki ruler tenant header / AM inhibit",
            config_path="loki/ruler-alert-hist.yaml",
            lie_path="grafana/grafana.ini",
            truth_name="unified alerting state history backend",
            reload_name="grafana",
            side="Loki ruler alerts in airline-obs still fire",
            surfaces="Grafana alert state history vs Loki",
            avoided="r206 Loki ruler tenant; AM inhibit",
            this_is="state history is annotations not Loki",
            step_note="False lead ruler/AM 4-5; grafana.ini backend 6-8; loki backend 9-12.",
            query_cmd="curl -sS -G $LOKI/loki/api/v1/query --data-urlencode 'query=sum(count_over_time({from=\"grafana-alerting\",service=\"alert-hist-svc\"}[1h]))'",
            false_cmd="yq '.ruler.remote_write.client.headers' loki/ruler-alert-hist.yaml; amtool inhibit query service=alert-hist-svc --alertmanager.url=$AM",
            truth_cmd="yq '.unified_alerting.state_history' grafana/grafana.ini",
            confirm_cmd="curl -sS $GRAFANA/api/v1/rules/history?dashboardUID=alert-hist-40 | jq '.values|length'",
            reload_cmd="kubectl -n grafana rollout restart deploy/grafana && kubectl -n grafana rollout status deploy/grafana --timeout=90s",
            requery_cmd="curl -sS -G $LOKI/loki/api/v1/query --data-urlencode 'query=sum(count_over_time({from=\"grafana-alerting\",service=\"alert-hist-svc\"}[1h]))'",
            grafana_ok_cmd="curl -sS $GRAFANA/api/ds/query -d @/tmp/ah.json | jq '.results.A.frames[0].data.values'",
            side_cmd="curl -sS -H 'X-Scope-OrgID: airline-obs' $MIMIR/prometheus/api/v1/query --data-urlencode 'query=ALERTS{alertname=\"LokiRulerErrorBurst\"}' | jq '.data.result|length'",
            final_cmd="yq '.unified_alerting.state_history.backend, .unified_alerting.state_history.loki_target' grafana/grafana.ini",
            patch_old="backend = annotations",
            patch_new="backend = loki\nloki_target = http://loki.obs:3100",
            runbook_path="runbooks/alert-hist.md",
            runbook="# alert-hist-svc state history\nbackend was annotations. Dashboard queries Loki. Set backend loki.\nNot ruler tenant and not inhibit.\n",
            goal="alert-hist-svc dashboard alert-hist-40 state flips is empty. Alerting UI has history. Fix backend.",
            plan="Empty Loki → not ruler/AM → annotations backend → loki.",
            outcome="backend loki. Panel fills. ruler alerts unchanged.",
            obs1='[{"uid":"alert-hist-40","title":"alert state history"}]',
            obs2='{"title":"state flips","targets":[{"expr":"sum(count_over_time({from=\\"grafana-alerting\\",service=\\"alert-hist-svc\\"}[1h]))"}]}',
            obs3='{"status":"success","data":{"result":[]}}',
            obs4="X-Scope-OrgID: airline-obs\n0 inhibit rows",
            obs5="ruler/AM fine",
            obs6="[unified_alerting.state_history]\nbackend = annotations",
            obs7="24",
            obs8="history in annotations; dashboard queries Loki",
            obs9="patched backend loki",
            obs10='deployment "grafana" successfully rolled out',
            obs11='{"status":"success","data":{"result":[{"value":[1710000600,"24"]}]}}',
            obs12="[[1710000600],[24]]",
            obs13="1",
            obs14="wrote runbooks/alert-hist.md",
            obs15="loki\nhttp://loki.obs:3100",
        ),
        _failp(
            slug="alert-hist-patch-ruler-tenant",
            service="alert-hist-bag-svc",
            dashboard_uid="alert-hist-ruler",
            panel="bag state flips",
            query='sum(count_over_time({from="grafana-alerting",service="alert-hist-bag-svc"}[1h]))',
            lie="Fixing Loki ruler X-Scope-OrgID does not write Grafana state history that is still on the annotations backend",
            false_lead="Loki ruler tenant fake",
            config_path="loki/bag-ruler.yaml",
            lie_path="grafana/grafana.ini",
            wrong_path="loki/bag-ruler.yaml",
            reload_name="loki-ruler",
            ticket="OBS-4500",
            xfail="tests/test_alert_hist_bag.py",
            surfaces="ruler tenant leftover vs state history backend",
            avoided="r206 as actual RCA",
            this_is="fail/handoff: ruler tenant patched, history still annotations",
            step_note="ruler 6-10; still empty 11; late grafana.ini 12; handoff 14-15.",
            next_note="Next: Prom WAL replay vs remote_write.",
            query_cmd="curl -sS -G $LOKI/loki/api/v1/query --data-urlencode 'query=sum(count_over_time({from=\"grafana-alerting\",service=\"alert-hist-bag-svc\"}[1h]))'",
            false_cmd="yq '.ruler.remote_write.client.headers.X-Scope-OrgID' loki/bag-ruler.yaml",
            reload_cmd="kubectl -n loki rollout restart deploy/loki-ruler && kubectl -n loki rollout status deploy/loki-ruler --timeout=90s",
            requery_cmd="curl -sS -G $LOKI/loki/api/v1/query --data-urlencode 'query=sum(count_over_time({from=\"grafana-alerting\",service=\"alert-hist-bag-svc\"}[1h]))'",
            denied_cmd="kubectl -n grafana auth can-i patch configmap/grafana-ini --as=sre-bot",
            wrong_old="X-Scope-OrgID: fake",
            wrong_new="X-Scope-OrgID: airline-obs",
            wrong2_old="url: http://mimir.obs:9009/api/v1/push",
            wrong2_new="url: http://mimir.obs:9009/api/v1/push\n    send_exemplars: true",
            ticket_body="OBS-4500: alert-hist-bag-svc Loki still empty. state_history backend annotations. Need loki backend. No ini RBAC.\n",
            goal="alert-hist-bag-svc dashboard alert-hist-ruler bag state flips is empty. Restore Loki hits.",
            plan="Patch ruler tenant (r206 leftover).",
            outcome="tenant airline-obs; still empty. Late annotations backend. Handoff OBS-4500.",
            obs1='[{"uid":"alert-hist-ruler","title":"alert bag hist"}]',
            obs2='{"title":"bag state flips","targets":[{"expr":"sum(count_over_time({from=\\"grafana-alerting\\",service=\\"alert-hist-bag-svc\\"}[1h]))"}]}',
            obs3='{"status":"success","data":{"result":[]}}',
            obs4="fake",
            obs5="tenant fake — treated as r206",
            obs6="loki/bag-ruler.yaml",
            obs7="patched airline-obs",
            obs8='deployment "loki-ruler" successfully rolled out',
            obs9='{"status":"success","data":{"result":[]}}',
            obs10="patched send_exemplars",
            obs11='{"status":"success","data":{"result":[]}}',
            obs12="grafana.ini state_history backend = annotations",
            obs13="no",
            obs14="wrote tickets/OBS-4500.md",
            obs15="xfail tests/test_alert_hist_bag.py",
        ),
    )
)

# r223 Prom WAL replay vs remote_write (not queue, not relabel drop)
MORE.append(
    (
        _okp(
            slug="prom-wal-replay-vs-rw",
            service="prom-wal-svc",
            dashboard_uid="prom-wal-41",
            panel="fresh samples",
            query='sum(rate(http_requests_total{service="prom-wal-svc"}[5m]))',
            lie="Prom agent WAL is truncated (min-WAL) so after restart remote_write has a gap and Grafana 5m rate is empty while /metrics is live",
            false_lead="remote_write queue full / write_relabel drop __name__",
            config_path="prom/wal-relabel.yaml",
            lie_path="prom/wal-agent.yaml",
            truth_name="WAL size vs remote_write lag",
            reload_name="prom-agent-wal",
            side="agents with full WAL still catch up",
            surfaces="Prom WAL truncate vs remote_write gap",
            avoided="remote_write queue; r194 write_relabel drop",
            this_is="min-WAL truncate leaves a remote_write gap after restart",
            step_note="False lead queue/relabel 4-5; WAL flags 6-8; disable truncate 9-12.",
            query_cmd="curl -sS -G $MIMIR/prometheus/api/v1/query --data-urlencode 'query=sum(rate(http_requests_total{service=\"prom-wal-svc\"}[5m]))'",
            false_cmd="curl -sS localhost:9090/metrics | rg 'prometheus_remote_storage_samples_pending|queue_capacity'; yq '.remote_write[0].write_relabel_configs' prom/wal-relabel.yaml",
            truth_cmd="yq '.storage.tsdb.wal_compression, .storage.tsdb.min_block_duration, .agent.wal_truncate_frequency' prom/wal-agent.yaml",
            confirm_cmd="curl -sS $AGENT_WAL/metrics | rg 'http_requests_total' | head",
            reload_cmd="kubectl -n wal rollout restart deploy/prom-agent-wal && kubectl -n wal rollout status deploy/prom-agent-wal --timeout=90s",
            requery_cmd="curl -sS -G $MIMIR/prometheus/api/v1/query --data-urlencode 'query=sum(rate(http_requests_total{service=\"prom-wal-svc\"}[5m]))'",
            grafana_ok_cmd="curl -sS $GRAFANA/api/ds/query -d @/tmp/wal.json | jq '.results.A.frames[0].data.values'",
            side_cmd="curl -sS -G $MIMIR/prometheus/api/v1/query --data-urlencode 'query=sum(rate(http_requests_total{service=\"fare-cache-svc\"}[5m]))' | jq '.data.result[0].value'",
            final_cmd="yq '.agent.wal_truncate_frequency' prom/wal-agent.yaml",
            patch_old="wal_truncate_frequency: 30s",
            patch_new="wal_truncate_frequency: 2h",
            runbook_path="runbooks/prom-wal.md",
            runbook="# prom-wal-svc WAL truncate\nwal_truncate_frequency 30s dropped unflushed samples on restart. Set 2h.\nNot queue and not write_relabel.\n",
            goal="prom-wal-svc dashboard prom-wal-41 fresh samples empty after agent restart. /metrics is live. Fix WAL truncate.",
            plan="Empty Mimir → not queue/relabel → wal_truncate 30s → 2h.",
            outcome="truncate 2h. 5m rate fills. other agents unchanged.",
            obs1='[{"uid":"prom-wal-41","title":"prom wal samples"}]',
            obs2='{"title":"fresh samples","targets":[{"expr":"sum(rate(http_requests_total{service=\\"prom-wal-svc\\"}[5m]))"}]}',
            obs3='{"status":"success","data":{"result":[]}}',
            obs4="prometheus_remote_storage_samples_pending 0\nqueue_capacity 10000\nwrite_relabel: []",
            obs5="queue/relabel healthy",
            obs6="wal_truncate_frequency: 30s\nwal_compression: true",
            obs7="http_requests_total 88420  # local /metrics live",
            obs8="local metrics live; WAL truncate dropped remote_write catch-up",
            obs9="patched wal_truncate_frequency 2h",
            obs10='deployment "prom-agent-wal" successfully rolled out',
            obs11='{"status":"success","data":{"result":[{"value":[1710000600,"12.4"]}]}}',
            obs12="[[1710000600],[12.4]]",
            obs13='["1710000600","0.916"]',
            obs14="wrote runbooks/prom-wal.md",
            obs15="2h",
        ),
        _failp(
            slug="prom-wal-raise-queue-not-truncate",
            service="prom-wal-bag-svc",
            dashboard_uid="prom-wal-queue",
            panel="bag fresh samples",
            query='sum(rate(http_requests_total{service="prom-wal-bag-svc"}[5m]))',
            lie="Raising remote_write queue capacity does not restore samples dropped by wal_truncate_frequency 30s",
            false_lead="remote_write queue full",
            config_path="prom/bag-wal-agent.yaml",
            lie_path="prom/bag-wal-agent.yaml",
            wrong_path="prom/bag-wal-agent.yaml",
            reload_name="prom-agent-wal-bag",
            ticket="OBS-4501",
            xfail="tests/test_prom_wal_bag.py",
            surfaces="queue leftover vs WAL truncate",
            avoided="remote_write queue as actual RCA; r194 relabel",
            this_is="fail/handoff: queue raised, WAL still truncates 30s",
            step_note="queue 6-10; still empty 11; late truncate 12; handoff 14-15.",
            next_note="Next: ClickHouse keeper vs distributed table.",
            query_cmd="curl -sS -G $MIMIR/prometheus/api/v1/query --data-urlencode 'query=sum(rate(http_requests_total{service=\"prom-wal-bag-svc\"}[5m]))'",
            false_cmd="yq '.remote_write[0].queue_config' prom/bag-wal-agent.yaml",
            reload_cmd="kubectl -n wal rollout restart deploy/prom-agent-wal-bag && kubectl -n wal rollout status deploy/prom-agent-wal-bag --timeout=90s",
            requery_cmd="curl -sS -G $MIMIR/prometheus/api/v1/query --data-urlencode 'query=sum(rate(http_requests_total{service=\"prom-wal-bag-svc\"}[5m]))'",
            denied_cmd="kubectl -n wal auth can-i patch configmap/bag-wal-agent --as=sre-bot",
            wrong_old="capacity: 10000",
            wrong_new="capacity: 100000",
            wrong2_old="max_shards: 4",
            wrong2_new="max_shards: 16",
            ticket_body="OBS-4501: prom-wal-bag-svc still empty after restart. wal_truncate_frequency 30s. Need 2h. No agent CM RBAC for truncate key... wait we denied patch of same file. Need platform.\n",
            goal="prom-wal-bag-svc dashboard prom-wal-queue bag fresh samples empty after restart. Restore Mimir.",
            plan="Raise remote_write queue (banned queue RCA).",
            outcome="Queue 100k; still empty. Late truncate 30s. Handoff OBS-4501.",
            obs1='[{"uid":"prom-wal-queue","title":"prom bag wal"}]',
            obs2='{"title":"bag fresh samples","targets":[{"expr":"sum(rate(http_requests_total{service=\\"prom-wal-bag-svc\\"}[5m]))"}]}',
            obs3='{"status":"success","data":{"result":[]}}',
            obs4="capacity: 10000",
            obs5="queue 10k — treated as RCA",
            obs6="prom/bag-wal-agent.yaml",
            obs7="patched capacity 100000",
            obs8='deployment "prom-agent-wal-bag" successfully rolled out',
            obs9='{"status":"success","data":{"result":[]}}',
            obs10="patched max_shards 16",
            obs11='{"status":"success","data":{"result":[]}}',
            obs12="prom/bag-wal-agent.yaml wal_truncate_frequency 30s",
            obs13="no",
            obs14="wrote tickets/OBS-4501.md",
            obs15="xfail tests/test_prom_wal_bag.py",
        ),
    )
)

# r224 ClickHouse keeper vs distributed (not r189 table name vs uid)
MORE.append(
    (
        _okp(
            slug="ch-keeper-vs-dist-table",
            service="ch-keeper-svc",
            dashboard_uid="ch-keeper-42",
            panel="sql traces",
            query="SELECT count() FROM otel.otel_traces_dist WHERE ServiceName = 'ch-keeper-svc'",
            lie="ClickHouse keeper quorum lost so distributed table otel_traces_dist is read-only empty while local otel_traces on replica 1 has rows",
            false_lead="Grafana SQL hits local table vs _dist / stale dashboard uid",
            config_path="grafana/dashboards/ch-keeper-42.json",
            lie_path="clickhouse/keeper.xml",
            truth_name="keeper mntr vs local vs dist",
            reload_name="clickhouse-keeper",
            side="SQL on other CH clusters with healthy keeper still works",
            surfaces="ClickHouse keeper quorum vs distributed table",
            avoided="r189 CH table name vs _dist; provisioned uid",
            this_is="keeper quorum lost, _dist empty, local has rows",
            step_note="False lead table/uid 4-5; keeper mntr 6-8; restore replica 9-12.",
            query_cmd="clickhouse-client -q \"SELECT count() FROM otel.otel_traces_dist WHERE ServiceName='ch-keeper-svc'\"",
            false_cmd="jq '.dashboard.uid, .dashboard.panels[0].targets[0].rawSql' grafana/dashboards/ch-keeper-42.json",
            truth_cmd="echo mntr | nc clickhouse-keeper 2181; clickhouse-client -q \"SELECT count() FROM otel.otel_traces WHERE ServiceName='ch-keeper-svc'\"",
            confirm_cmd="yq '.clickhouse_keeper.raft_configuration.server' clickhouse/keeper.xml",
            reload_cmd="kubectl -n ch rollout restart sts/clickhouse-keeper && kubectl -n ch rollout status sts/clickhouse-keeper --timeout=180s",
            requery_cmd="clickhouse-client -q \"SELECT count() FROM otel.otel_traces_dist WHERE ServiceName='ch-keeper-svc'\"",
            grafana_ok_cmd="curl -sS $GRAFANA/api/ds/query -d @/tmp/chk.json | jq '.results.A.frames[0].data.values'",
            side_cmd="clickhouse-client --host ch-b -q \"SELECT count() FROM otel.otel_traces_dist WHERE ServiceName='ops-audit-svc'\"",
            final_cmd="echo mntr | nc clickhouse-keeper 2181 | rg 'zk_synced_followers|zk_server_state'",
            patch_old="<id>2</id><hostname>keeper-1</hostname> <!-- down -->",
            patch_new="<id>2</id><hostname>keeper-1</hostname>\n        <id>3</id><hostname>keeper-2</hostname>",
            runbook_path="runbooks/ch-keeper.md",
            runbook="# ch-keeper-svc keeper quorum\n_dist empty because keeper quorum lost. Local table has rows. Restore keeper replica.\nNot wrong table name and not uid.\n",
            goal="ch-keeper-svc dashboard ch-keeper-42 sql traces is 0 on _dist. Local table has rows. Fix keeper.",
            plan="Empty _dist → SQL already on _dist, uid stable → keeper mntr → restore replica.",
            outcome="keeper quorum. _dist count matches local. other clusters unchanged.",
            obs1='[{"uid":"ch-keeper-42","title":"ch keeper traces"}]',
            obs2='{"title":"sql traces","targets":[{"rawSql":"SELECT count() FROM otel.otel_traces_dist WHERE ServiceName = \'ch-keeper-svc\'"}]}',
            obs3="0",
            obs4='"ch-keeper-42"\n"SELECT count() FROM otel.otel_traces_dist ..."\n# already _dist and stable uid — not r189',
            obs5="query already distributed; uid stable",
            obs6="zk_server_state\tleading\nzk_synced_followers\t0",
            obs7="18420\n# local has rows",
            obs8="keeper no followers; _dist cannot merge",
            obs9="patched raft_configuration + keeper-2",
            obs10='statefulset "clickhouse-keeper" successfully rolled out',
            obs11="18420",
            obs12="[[18420]]",
            obs13="310",
            obs14="wrote runbooks/ch-keeper.md",
            obs15="zk_synced_followers\t2",
        ),
        _failp(
            slug="ch-keeper-switch-local-table",
            service="ch-keeper-bag-svc",
            dashboard_uid="ch-keeper-local",
            panel="bag sql traces",
            query="SELECT count() FROM otel.otel_traces_dist WHERE ServiceName = 'ch-keeper-bag-svc'",
            lie="Pointing Grafana SQL at the local otel_traces table does not restore keeper quorum so other replicas stay empty",
            false_lead="SQL hits _dist instead of local",
            config_path="grafana/dashboards/ch-keeper-local.json",
            lie_path="clickhouse/bag-keeper.xml",
            wrong_path="grafana/dashboards/ch-keeper-local.json",
            reload_name="grafana",
            ticket="OBS-4502",
            xfail="tests/test_ch_keeper_bag.py",
            surfaces="table-name leftover vs keeper quorum",
            avoided="r189 as actual RCA",
            this_is="fail/handoff: SQL switched to local, keeper still no followers",
            step_note="SQL table 6-10; local fills one replica 11; late keeper 12; handoff 14-15.",
            next_note="Catalog open r225+: VM stream done. Next mill: Alloy prometheus.relabel vs discovery.",
            query_cmd="clickhouse-client -q \"SELECT count() FROM otel.otel_traces_dist WHERE ServiceName='ch-keeper-bag-svc'\"",
            false_cmd="jq '.dashboard.panels[0].targets[0].rawSql' grafana/dashboards/ch-keeper-local.json",
            reload_cmd="kubectl -n grafana rollout restart deploy/grafana && kubectl -n grafana rollout status deploy/grafana --timeout=90s",
            requery_cmd="clickhouse-client -q \"SELECT count() FROM otel.otel_traces_dist WHERE ServiceName='ch-keeper-bag-svc'\"",
            denied_cmd="kubectl -n ch auth can-i patch sts/clickhouse-keeper --as=sre-bot",
            wrong_old="FROM otel.otel_traces_dist",
            wrong_new="FROM otel.otel_traces",
            wrong2_old="ServiceName = 'ch-keeper-bag-svc'",
            wrong2_new="ServiceName = 'ch-keeper-bag-svc' SETTINGS distributed_product_mode = 'allow'",
            ticket_body="OBS-4502: ch-keeper-bag-svc _dist still 0. keeper zk_synced_followers 0. Need raft replica. No keeper RBAC.\n",
            goal="ch-keeper-bag-svc dashboard ch-keeper-local bag sql traces is 0 on _dist. Restore distributed reads.",
            plan="Switch SQL to local table (r189 leftover).",
            outcome="Local SQL on one replica; _dist still 0. Late keeper quorum. Handoff OBS-4502.",
            obs1='[{"uid":"ch-keeper-local","title":"ch bag keeper"}]',
            obs2='{"title":"bag sql traces","targets":[{"rawSql":"SELECT count() FROM otel.otel_traces_dist WHERE ServiceName = \'ch-keeper-bag-svc\'"}]}',
            obs3="0",
            obs4='"SELECT count() FROM otel.otel_traces_dist ..."',
            obs5="_dist query — treated as r189",
            obs6="grafana/dashboards/ch-keeper-local.json",
            obs7="patched FROM otel.otel_traces",
            obs8='deployment "grafana" successfully rolled out',
            obs9="0",
            obs10="patched SETTINGS",
            obs11="0",
            obs12="clickhouse/bag-keeper.xml zk_synced_followers 0",
            obs13="no",
            obs14="wrote tickets/OBS-4502.md",
            obs15="xfail tests/test_ch_keeper_bag.py",
        ),
    )
)
