"""Observability plants r285-r292. Do not clone r109-r284.

BAN r163 tid128, r172 inferred db, r190 DD UST,
r244 loki-querier-max-concurrent / loki-qconc-rebuild-blooms.
"""

from mill_plants_h import _failp
from mill_plants_l import _okx

MORE = []

# r285 OTel filter error_mode ignore
MORE.append(
    (
        _okx(
            slug="otel-filter-error-mode-ignore",
            service="grey-water-svc",
            dashboard_uid="gwater-filter-1",
            panel="grey traces",
            query='{resource.service.name="grey-water-svc" && status=error}',
            lie="filter processor error_mode ignore plus bad OTTL drop(span.attributes[\"http.route\"] == nil) drops every error span so Grafana error search is empty while 200s remain",
            false_lead="probabilisticsampler 0 / memory_limiter",
            config_path="otelcol/gwater-prob.yaml",
            lie_path="otelcol/gwater-filter.yaml",
            truth_name="filter error_mode vs sent spans",
            reload_name="otelcol-gwater",
            side="collectors without the bad OTTL still keep errors",
            surfaces="OTel filter error_mode ignore vs Grafana error traces empty",
            avoided="r275 probabilisticsampler; r224 memory_limiter; tail wait ban",
            this_is="error_mode ignore plus bad OTTL silently drops error spans",
            step_note="False lead sampler/limiter 4-5; filter OTTL 6-8; drop processor 9-12.",
            query_cmd="curl -sS -G $TEMPO/api/search --data-urlencode 'q={resource.service.name=\"grey-water-svc\" && status=error}' | jq '.traces|length'",
            false_cmd="yq '.processors.probabilisticsampler, .processors.memory_limiter' otelcol/gwater-prob.yaml",
            truth_cmd="curl -sS -G $TEMPO/api/search --data-urlencode 'q={resource.service.name=\"grey-water-svc\" && status=ok}' | jq '.traces|length'",
            confirm_cmd="yq '.processors.filter' otelcol/gwater-filter.yaml",
            reload_cmd="kubectl -n otel rollout restart deploy/otelcol-gwater && kubectl -n otel rollout status deploy/otelcol-gwater --timeout=90s",
            requery_cmd="curl -sS -G $TEMPO/api/search --data-urlencode 'q={resource.service.name=\"grey-water-svc\" && status=error}' | jq '.traces|length'",
            side_cmd="curl -sS -G $TEMPO/api/search --data-urlencode 'q={resource.service.name=\"ssr-meal-svc\" && status=error}' | jq '.traces|length'",
            final_cmd="yq -r '.service.pipelines.traces.processors[]' otelcol/gwater-filter.yaml",
            patch_old="processors:\n      - filter\n      - batch",
            patch_new="processors:\n      - batch",
            runbook_path="runbooks/gwater-filter.md",
            runbook="# grey-water-svc filter error_mode\nignore plus bad OTTL drops errors. Drop filter. Not probabilisticsampler.\n",
            goal="grey-water-svc dashboard gwater-filter-1 grey traces errors empty. 200s exist. Find the filter lie.",
            plan="Empty errors → sampler/limiter (false) → filter error_mode ignore → drop filter.",
            outcome="filter dropped. 11 error traces. ssr-meal-svc unchanged.",
            obs1='[{"uid":"gwater-filter-1","title":"grey traces"}]',
            obs2='{"title":"grey traces","targets":[{"query":"{resource.service.name=\\"grey-water-svc\\" && status=error}"}]}',
            obs3="0",
            obs4="sampling_percentage: 100\nlimit_mib: 512  # not r275/r224",
            obs5="sampler 100; limiter healthy",
            obs6="error_mode: ignore\ntraces:\n  span:\n    - 'attributes[\"http.route\"] == nil'",
            obs7="14",
            obs8="200s kept; OTTL on nil route dropped errors under ignore",
            obs9="patched drop filter",
            obs10='deployment "otelcol-gwater" successfully rolled out',
            obs11="11",
            obs12='{"name":"Traces"}',
            obs13="4",
            obs14="wrote runbooks/gwater-filter.md",
            obs15="batch",
        ),
        _failp(
            slug="otel-filter-raise-sampler-not-ottl",
            service="galley-bus-svc",
            dashboard_uid="gbus-filter-prob",
            panel="galley bus traces",
            query='{resource.service.name="galley-bus-svc" && status=error}',
            lie="Raising probabilisticsampler to 100 does not keep error spans when filter error_mode ignore still drops the bad OTTL",
            false_lead="probabilisticsampler sampling_percentage 0",
            config_path="otelcol/gbus-prob.yaml",
            lie_path="otelcol/gbus-filter.yaml",
            wrong_path="otelcol/gbus-prob.yaml",
            reload_name="otelcol-gbus",
            ticket="OBS-5353",
            xfail="tests/test_gbus_filter.py",
            surfaces="sampler leftover vs filter error_mode ignore",
            avoided="r275 as actual RCA",
            this_is="fail/handoff: sampler 100, filter still drops errors",
            step_note="sampler 6-10; still 0 11; late filter 12; handoff 14-15.",
            next_note="Next: Loki align_queries_with_step.",
            query_cmd="curl -sS -G $TEMPO/api/search --data-urlencode 'q={resource.service.name=\"galley-bus-svc\" && status=error}' | jq '.traces|length'",
            false_cmd="yq '.processors.probabilisticsampler.sampling_percentage' otelcol/gbus-prob.yaml",
            reload_cmd="kubectl -n otel rollout restart deploy/otelcol-gbus && kubectl -n otel rollout status deploy/otelcol-gbus --timeout=90s",
            requery_cmd="curl -sS -G $TEMPO/api/search --data-urlencode 'q={resource.service.name=\"galley-bus-svc\" && status=error}' | jq '.traces|length'",
            denied_cmd="kubectl -n otel auth can-i patch configmap/gbus-filter --as=sre-bot",
            wrong_old="sampling_percentage: 0",
            wrong_new="sampling_percentage: 100",
            wrong2_old="limit_mib: 32",
            wrong2_new="limit_mib: 1024",
            ticket_body="OBS-5353: galley-bus-svc errors still 0. sampler leftover. filter error_mode ignore. Need drop filter. No filter RBAC.\n",
            goal="galley-bus-svc dashboard gbus-filter-prob galley bus traces errors empty. Restore errors.",
            plan="Raise sampler (r275 leftover).",
            outcome="sampler 100; still 0. Late filter ignore. Handoff OBS-5353.",
            obs1='[{"uid":"gbus-filter-prob","title":"galley bus traces"}]',
            obs2='{"title":"galley bus traces","targets":[{"query":"{resource.service.name=\\"galley-bus-svc\\" && status=error}"}]}',
            obs3="0",
            obs4="sampling_percentage: 0",
            obs5="treated as r275",
            obs6="otelcol/gbus-prob.yaml",
            obs7="patched 100",
            obs8='deployment "otelcol-gbus" successfully rolled out',
            obs9="0",
            obs10="patched limiter 1024",
            obs11="0",
            obs12="otelcol/gbus-filter.yaml error_mode ignore OTTL http.route==nil; 200s=9",
            obs13="no",
            obs14="wrote tickets/OBS-5353.md",
            obs15="xfail tests/test_gbus_filter.py",
        ),
    )
)

# r286 Loki align_queries_with_step
MORE.append(
    (
        _okx(
            slug="loki-align-queries-with-step",
            service="reading-lt-svc",
            dashboard_uid="rlt-align-2",
            panel="reading light errors",
            query='sum(rate({job="reading-lt-svc"} |= "ballast_fail"[1m]))',
            lie="query_range align_queries_with_step true plus Grafana 7s step shifts the 1m window off the burst so the Stat is 0 while unaligned 1m has 12",
            false_lead="pattern metric_aggregation / max_query_parallelism 1",
            config_path="loki/rlt-patagg.yaml",
            lie_path="loki/rlt-align.yaml",
            truth_name="align_queries_with_step vs unaligned",
            reload_name="loki-query-frontend",
            side="unaligned 1m still shows the burst",
            surfaces="Loki align_queries_with_step vs Grafana 7s Stat 0",
            avoided="r282 pattern metric_aggregation; r271 max_query_parallelism; r270 split instant",
            this_is="align_queries_with_step plus 7s step misses the 1m burst",
            step_note="False lead patagg/qpar 4-5; align true 6-8; false 9-12.",
            query_cmd="curl -sS -G $LOKI/loki/api/v1/query --data-urlencode 'query=sum(rate({job=\"reading-lt-svc\"} |= \"ballast_fail\"[1m]))' | jq '{status,v:(.data.result[0].value[1]//empty)}'",
            false_cmd="yq '.pattern_ingester.metric_aggregation.enabled, .limits_config.max_query_parallelism' loki/rlt-patagg.yaml",
            truth_cmd="curl -sS -G $LOKI/loki/api/v1/query --data-urlencode 'query=sum(rate({job=\"reading-lt-svc\"} |= \"ballast_fail\"[1m]))' --data-urlencode 'time=now' | jq '.data.result'",
            confirm_cmd="yq '.query_range.align_queries_with_step' loki/rlt-align.yaml",
            reload_cmd="kubectl -n loki rollout restart deploy/query-frontend && kubectl -n loki rollout status deploy/query-frontend --timeout=90s",
            requery_cmd="curl -sS -G $LOKI/loki/api/v1/query --data-urlencode 'query=sum(rate({job=\"reading-lt-svc\"} |= \"ballast_fail\"[1m]))' | jq '.data.result[0].value[1]'",
            side_cmd="curl -sS -G $LOKI/loki/api/v1/query --data-urlencode 'query=sum(rate({job=\"ssr-meal-svc\"} |= \"error\"[1m]))' | jq '.data.result|length'",
            final_cmd="yq -r '.query_range.align_queries_with_step' loki/rlt-align.yaml",
            patch_old="align_queries_with_step: true",
            patch_new="align_queries_with_step: false",
            runbook_path="runbooks/rlt-align-step.md",
            runbook="# reading-lt-svc align_queries_with_step\ntrue plus 7s step misses 1m bursts. Set false. Not pattern aggregation.\n",
            goal="reading-lt-svc dashboard rlt-align-2 reading light errors Stat 0. unaligned 1m=12. Find the align-step lie.",
            plan="Stat 0 → patagg/qpar (false) → align true → false.",
            outcome="align false. rate=12. ssr-meal-svc unchanged.",
            obs1='[{"uid":"rlt-align-2","title":"reading light errors"}]',
            obs2='{"title":"reading light errors","targets":[{"expr":"sum(rate({job=\\"reading-lt-svc\\"} |= \\"ballast_fail\\"[1m]))"}]}',
            obs3='{"status":"success","v":"0"}',
            obs4="enabled: false\nmax_query_parallelism: 32  # not r282/r271",
            obs5="aggregation off; parallelism 32",
            obs6="align_queries_with_step: true",
            obs7='[{"value":[1710000000,"12"]}]',
            obs8="unaligned 12; aligned 7s window empty",
            obs9="patched false",
            obs10='deployment "query-frontend" successfully rolled out',
            obs11="12",
            obs12='{"name":"Number"}',
            obs13="1",
            obs14="wrote runbooks/rlt-align-step.md",
            obs15="false",
        ),
        _failp(
            slug="loki-align-disable-patagg-not-step",
            service="vhf-databus-svc",
            dashboard_uid="vhfd-align-patagg",
            panel="VHF bus errors",
            query='sum(rate({job="vhf-databus-svc"} |= "bus_fault"[1m]))',
            lie="Disabling pattern metric_aggregation does not restore Grafana Stat when align_queries_with_step still shifts the 1m window",
            false_lead="pattern metric_aggregation byte_size 0",
            config_path="loki/vhfd-patagg.yaml",
            lie_path="loki/vhfd-align.yaml",
            wrong_path="loki/vhfd-patagg.yaml",
            reload_name="loki-pattern-ingester",
            ticket="OBS-5354",
            xfail="tests/test_vhfd_align.py",
            surfaces="patagg leftover vs align_queries_with_step",
            avoided="r282 as actual RCA",
            this_is="fail/handoff: aggregation off, align still true",
            step_note="patagg 6-10; still 0 11; late align 12; handoff 14-15.",
            next_note="Next: Tempo spanmetrics exponential histogram.",
            query_cmd="curl -sS -G $LOKI/loki/api/v1/query --data-urlencode 'query=sum(rate({job=\"vhf-databus-svc\"} |= \"bus_fault\"[1m]))' | jq '{status,v:(.data.result[0].value[1]//empty)}'",
            false_cmd="yq '.pattern_ingester.metric_aggregation' loki/vhfd-patagg.yaml",
            reload_cmd="kubectl -n loki rollout restart deploy/pattern-ingester && kubectl -n loki rollout status deploy/pattern-ingester --timeout=90s",
            requery_cmd="curl -sS -G $LOKI/loki/api/v1/query --data-urlencode 'query=sum(rate({job=\"vhf-databus-svc\"} |= \"bus_fault\"[1m]))' | jq '{status,v:(.data.result[0].value[1]//empty)}'",
            denied_cmd="kubectl -n loki auth can-i patch deploy/query-frontend --as=sre-bot",
            wrong_old="enabled: true\n    byte_size: 0",
            wrong_new="enabled: false",
            wrong2_old="max_query_parallelism: 1",
            wrong2_new="max_query_parallelism: 32",
            ticket_body="OBS-5354: vhf-databus-svc Stat still 0. patagg leftover. align_queries_with_step true. Need false. No frontend RBAC.\n",
            goal="vhf-databus-svc dashboard vhfd-align-patagg VHF bus errors Stat 0. Restore burst.",
            plan="Disable pattern aggregation (r282 leftover).",
            outcome="aggregation off; still 0. Late align true. Handoff OBS-5354.",
            obs1='[{"uid":"vhfd-align-patagg","title":"vhf bus errors"}]',
            obs2='{"title":"VHF bus errors","targets":[{"expr":"sum(rate({job=\\"vhf-databus-svc\\"} |= \\"bus_fault\\"[1m]))"}]}',
            obs3='{"status":"success","v":"0"}',
            obs4="enabled: true\nbyte_size: 0",
            obs5="treated as r282",
            obs6="loki/vhfd-patagg.yaml",
            obs7="patched enabled false",
            obs8='deployment "pattern-ingester" successfully rolled out',
            obs9='{"status":"success","v":"0"}',
            obs10="patched parallelism 32",
            obs11='{"status":"success","v":"0"}',
            obs12="loki/vhfd-align.yaml align_queries_with_step true; unaligned 1m=9",
            obs13="no",
            obs14="wrote tickets/OBS-5354.md",
            obs15="xfail tests/test_vhfd_align.py",
        ),
    )
)

# r287 Tempo MG histogram exponential vs explicit
MORE.append(
    (
        _okx(
            slug="tempo-mg-hist-exponential-vs-bucket",
            service="transponder-s-svc",
            dashboard_uid="xpdrs-exp-3",
            panel="xpdr latency heatmap",
            query='histogram_quantile(0.99, rate(traces_spanmetrics_latency_bucket{service="transponder-s-svc"}[5m]))',
            lie="metrics_generator span_metrics histogram type exponential so Grafana still queries _bucket classic series and the heatmap is empty",
            false_lead="MG native hist vs bucket / classic scrape",
            config_path="tempo/xpdrs-native.yaml",
            lie_path="tempo/xpdrs-hist.yaml",
            truth_name="histogram type vs _bucket",
            reload_name="tempo-metrics-generator",
            side="tenants with type explicit still have _bucket",
            surfaces="Tempo MG exponential histogram vs Grafana _bucket heatmap",
            avoided="r218 MG native hist; r187 native vs classic; r262 bucket_limit",
            this_is="exponential hist has no _bucket; Grafana still uses classic",
            step_note="False lead native/classic 4-5; type exponential 6-8; explicit 9-12.",
            query_cmd="curl -sS -G $MIMIR/prometheus/api/v1/query --data-urlencode 'query=histogram_quantile(0.99, rate(traces_spanmetrics_latency_bucket{service=\"transponder-s-svc\"}[5m]))'",
            false_cmd="yq '.metrics_generator.processor.span_metrics.histogram' tempo/xpdrs-native.yaml",
            truth_cmd="curl -sS -G $MIMIR/prometheus/api/v1/label/__name__/values | rg spanmetrics_latency",
            confirm_cmd="yq '.metrics_generator.processor.span_metrics.histogram.type' tempo/xpdrs-hist.yaml",
            reload_cmd="kubectl -n tempo rollout restart deploy/metrics-generator && kubectl -n tempo rollout status deploy/metrics-generator --timeout=90s",
            requery_cmd="curl -sS -G $MIMIR/prometheus/api/v1/query --data-urlencode 'query=histogram_quantile(0.99, rate(traces_spanmetrics_latency_bucket{service=\"transponder-s-svc\"}[5m]))'",
            side_cmd="curl -sS -G $MIMIR/prometheus/api/v1/query --data-urlencode 'query=histogram_quantile(0.99, rate(traces_spanmetrics_latency_bucket{service=\"ssr-meal-svc\"}[5m]))' | jq '.data.result|length'",
            final_cmd="yq -r '.metrics_generator.processor.span_metrics.histogram.type' tempo/xpdrs-hist.yaml",
            patch_old="type: exponential",
            patch_new="type: explicit\n      buckets: [0.005, 0.01, 0.025, 0.05, 0.1, 0.25, 0.5, 1]",
            runbook_path="runbooks/xpdrs-exp-hist.md",
            runbook="# transponder-s-svc MG histogram type\nexponential has no _bucket. Use explicit. Not native-hist scrape.\n",
            goal="transponder-s-svc dashboard xpdrs-exp-3 xpdr latency heatmap empty. Find the exponential-hist lie.",
            plan="Empty heatmap → native scrape (false) → type exponential → explicit buckets.",
            outcome="type explicit. p99=0.08. ssr-meal-svc unchanged.",
            obs1='[{"uid":"xpdrs-exp-3","title":"xpdr latency"}]',
            obs2='{"title":"xpdr latency heatmap","targets":[{"expr":"histogram_quantile(0.99, rate(traces_spanmetrics_latency_bucket{service=\\"transponder-s-svc\\"}[5m]))"}]}',
            obs3='{"status":"success","data":{"result":[]}}',
            obs4="histogram:\n  type: explicit  # not r218 as RCA for this tenant",
            obs5="comment only; live type is exponential",
            obs6="type: exponential",
            obs7="traces_spanmetrics_latency (native)  # no _bucket",
            obs8="exponential native; Grafana _bucket miss",
            obs9="patched explicit buckets",
            obs10='deployment "metrics-generator" successfully rolled out',
            obs11='{"status":"success","data":{"result":[{"value":[1710000600,"0.08"]}]}}',
            obs12='{"name":"Heatmap"}',
            obs13="1",
            obs14="wrote runbooks/xpdrs-exp-hist.md",
            obs15="explicit",
        ),
        _failp(
            slug="tempo-exphist-enable-classic-not-type",
            service="tcas-adv-svc",
            dashboard_uid="tcasadv-exp-classic",
            panel="TA latency heatmap",
            query='histogram_quantile(0.99, rate(traces_spanmetrics_latency_bucket{service="tcas-adv-svc"}[5m]))',
            lie="Enabling classic histogram scrape does not create _bucket series when Tempo MG histogram type is exponential",
            false_lead="native-histogram-only scrape dropped classic _bucket",
            config_path="prom/tcasadv-classic.yaml",
            lie_path="tempo/tcasadv-hist.yaml",
            wrong_path="prom/tcasadv-classic.yaml",
            reload_name="prom-scrape",
            ticket="OBS-5355",
            xfail="tests/test_tcasadv_exphist.py",
            surfaces="classic leftover vs MG exponential hist",
            avoided="r187 as actual RCA",
            this_is="fail/handoff: classic on, MG type still exponential",
            step_note="classic 6-10; still empty 11; late type exponential 12; handoff 14-15.",
            next_note="Next: Mimir ruler evaluation_delay.",
            query_cmd="curl -sS -G $MIMIR/prometheus/api/v1/query --data-urlencode 'query=histogram_quantile(0.99, rate(traces_spanmetrics_latency_bucket{service=\"tcas-adv-svc\"}[5m]))'",
            false_cmd="yq '.scrape_configs[]|select(.job_name==\"tcas-adv-svc\").always_scrape_classic_histograms' prom/tcasadv-classic.yaml",
            reload_cmd="kubectl -n prom rollout restart deploy/prom-scrape && kubectl -n prom rollout status deploy/prom-scrape --timeout=90s",
            requery_cmd="curl -sS -G $MIMIR/prometheus/api/v1/query --data-urlencode 'query=histogram_quantile(0.99, rate(traces_spanmetrics_latency_bucket{service=\"tcas-adv-svc\"}[5m]))'",
            denied_cmd="kubectl -n tempo auth can-i patch deploy/metrics-generator --as=sre-bot",
            wrong_old="always_scrape_classic_histograms: false",
            wrong_new="always_scrape_classic_histograms: true",
            wrong2_old="scrape_native_histograms: true",
            wrong2_new="scrape_native_histograms: true  # keep both",
            ticket_body="OBS-5355: tcas-adv-svc heatmap still empty. classic leftover. MG histogram type exponential. Need explicit. No MG RBAC.\n",
            goal="tcas-adv-svc dashboard tcasadv-exp-classic TA latency heatmap empty. Restore _bucket.",
            plan="Enable classic histograms (r187 leftover).",
            outcome="classic on; still empty. Late type exponential. Handoff OBS-5355.",
            obs1='[{"uid":"tcasadv-exp-classic","title":"ta latency"}]',
            obs2='{"title":"TA latency heatmap","targets":[{"expr":"histogram_quantile(0.99, rate(traces_spanmetrics_latency_bucket{service=\\"tcas-adv-svc\\"}[5m]))"}]}',
            obs3='{"status":"success","data":{"result":[]}}',
            obs4="always_scrape_classic_histograms: false",
            obs5="treated as r187",
            obs6="prom/tcasadv-classic.yaml",
            obs7="patched classic true",
            obs8='deployment "prom-scrape" successfully rolled out',
            obs9='{"status":"success","data":{"result":[]}}',
            obs10="patched keep native true",
            obs11='{"status":"success","data":{"result":[]}}',
            obs12="tempo/tcasadv-hist.yaml histogram type exponential; no _bucket series",
            obs13="no",
            obs14="wrote tickets/OBS-5355.md",
            obs15="xfail tests/test_tcasadv_exphist.py",
        ),
    )
)

# r288 Mimir ruler evaluation_delay
MORE.append(
    (
        _okx(
            slug="mimir-ruler-evaluation-delay",
            service="gpws-flap-svc",
            dashboard_uid="gpwsf-evaldelay-4",
            panel="GPWS flap burn",
            query='gpws_flap_error_burn:ratio5m{job="gpws-flap-svc"}',
            lie="ruler evaluation_delay 15m plus Grafana Stat on the recording rule is empty for the last 10m while raw rate still shows the spike",
            false_lead="max_query_lookback / split_instant_queries",
            config_path="mimir/gpwsf-lookback.yaml",
            lie_path="mimir/gpwsf-ruler.yaml",
            truth_name="evaluation_delay vs raw rate",
            reload_name="mimir-ruler",
            side="raw rate panels still spike",
            surfaces="Mimir ruler evaluation_delay vs Grafana recording-rule Stat lag",
            avoided="r210 lookback; r270 split instant; r99 rule group interval 1h",
            this_is="evaluation_delay 15m hides the last 10m on the recording rule",
            step_note="False lead lookback/split 4-5; evaluation_delay 6-8; 0s 9-12.",
            query_cmd="curl -sS -G $MIMIR/prometheus/api/v1/query --data-urlencode 'query=gpws_flap_error_burn:ratio5m{job=\"gpws-flap-svc\"}'",
            false_cmd="yq '.limits.max_query_lookback, .limits.split_instant_queries_by_interval' mimir/gpwsf-lookback.yaml",
            truth_cmd="curl -sS -G $MIMIR/prometheus/api/v1/query --data-urlencode 'query=rate(gpws_flap_errors_total{job=\"gpws-flap-svc\"}[5m])' | jq '.data.result'",
            confirm_cmd="yq '.ruler.evaluation_delay' mimir/gpwsf-ruler.yaml",
            reload_cmd="kubectl -n mimir rollout restart deploy/ruler && kubectl -n mimir rollout status deploy/ruler --timeout=90s",
            requery_cmd="curl -sS -G $MIMIR/prometheus/api/v1/query --data-urlencode 'query=gpws_flap_error_burn:ratio5m{job=\"gpws-flap-svc\"}'",
            side_cmd="curl -sS -G $MIMIR/prometheus/api/v1/query --data-urlencode 'query=rate(gpws_flap_errors_total{job=\"ssr-meal-svc\"}[5m])' | jq '.data.result|length'",
            final_cmd="yq -r '.ruler.evaluation_delay' mimir/gpwsf-ruler.yaml",
            patch_old="evaluation_delay: 15m",
            patch_new="evaluation_delay: 0s",
            runbook_path="runbooks/gpwsf-eval-delay.md",
            runbook="# gpws-flap-svc ruler evaluation_delay\n15m hides last 10m on the recording rule. Set 0s. Not lookback.\n",
            goal="gpws-flap-svc dashboard gpwsf-evaldelay-4 GPWS flap burn empty last 10m. raw rate spikes. Find the evaluation_delay lie.",
            plan="Empty rule → lookback/split (false) → evaluation_delay 15m → 0s.",
            outcome="delay 0s. burn=0.04. raw jobs unchanged.",
            obs1='[{"uid":"gpwsf-evaldelay-4","title":"gpws flap burn"}]',
            obs2='{"title":"GPWS flap burn","targets":[{"expr":"gpws_flap_error_burn:ratio5m{job=\\"gpws-flap-svc\\"}"}]}',
            obs3='{"status":"success","data":{"result":[]}}',
            obs4="max_query_lookback: 30d\nsplit_instant_queries_by_interval: 0  # not r210/r270",
            obs5="lookback 30d; split off",
            obs6="evaluation_delay: 15m",
            obs7='[{"value":[1710000000,"0.04"]}]',
            obs8="raw rate has spike; rule lags 15m",
            obs9="patched 0s",
            obs10='deployment "ruler" successfully rolled out',
            obs11='{"status":"success","data":{"result":[{"value":[1710000600,"0.04"]}]}}',
            obs12='{"name":"Number"}',
            obs13="1",
            obs14="wrote runbooks/gpwsf-eval-delay.md",
            obs15="0s",
        ),
        _failp(
            slug="mimir-evaldelay-raise-lookback-not-delay",
            service="windshear-inop-svc",
            dashboard_uid="wsinop-evaldelay-lookback",
            panel="WS inop burn",
            query='ws_inop_error_burn:ratio5m{job="windshear-inop-svc"}',
            lie="Raising max_query_lookback does not fill a recording-rule Stat delayed by evaluation_delay 15m",
            false_lead="query-frontend max_query_lookback 7d",
            config_path="mimir/wsinop-lookback.yaml",
            lie_path="mimir/wsinop-ruler.yaml",
            wrong_path="mimir/wsinop-lookback.yaml",
            reload_name="mimir-query-frontend",
            ticket="OBS-5356",
            xfail="tests/test_wsinop_evaldelay.py",
            surfaces="lookback leftover vs ruler evaluation_delay",
            avoided="r210 as actual RCA",
            this_is="fail/handoff: lookback 30d, evaluation_delay still 15m",
            step_note="lookback 6-10; still empty 11; late evaluation_delay 12; handoff 14-15.",
            next_note="Catalog r285-r288. Keep unique vs r109-r284.",
            query_cmd="curl -sS -G $MIMIR/prometheus/api/v1/query --data-urlencode 'query=ws_inop_error_burn:ratio5m{job=\"windshear-inop-svc\"}'",
            false_cmd="yq '.limits.max_query_lookback' mimir/wsinop-lookback.yaml",
            reload_cmd="kubectl -n mimir rollout restart deploy/query-frontend && kubectl -n mimir rollout status deploy/query-frontend --timeout=90s",
            requery_cmd="curl -sS -G $MIMIR/prometheus/api/v1/query --data-urlencode 'query=ws_inop_error_burn:ratio5m{job=\"windshear-inop-svc\"}'",
            denied_cmd="kubectl -n mimir auth can-i patch deploy/ruler --as=sre-bot",
            wrong_old="max_query_lookback: 7d",
            wrong_new="max_query_lookback: 30d",
            wrong2_old="split_instant_queries_by_interval: 1s",
            wrong2_new="split_instant_queries_by_interval: 0",
            ticket_body="OBS-5356: windshear-inop-svc rule Stat still empty last 10m. lookback leftover. evaluation_delay 15m. Need 0s. No ruler RBAC.\n",
            goal="windshear-inop-svc dashboard wsinop-evaldelay-lookback WS inop burn empty last 10m. Restore rule.",
            plan="Raise max_query_lookback (r210 leftover).",
            outcome="lookback 30d; still empty. Late evaluation_delay 15m. Handoff OBS-5356.",
            obs1='[{"uid":"wsinop-evaldelay-lookback","title":"ws inop burn"}]',
            obs2='{"title":"WS inop burn","targets":[{"expr":"ws_inop_error_burn:ratio5m{job=\\"windshear-inop-svc\\"}"}]}',
            obs3='{"status":"success","data":{"result":[]}}',
            obs4="max_query_lookback: 7d",
            obs5="treated as r210",
            obs6="mimir/wsinop-lookback.yaml",
            obs7="patched 30d",
            obs8='deployment "query-frontend" successfully rolled out',
            obs9='{"status":"success","data":{"result":[]}}',
            obs10="patched split instant 0",
            obs11='{"status":"success","data":{"result":[]}}',
            obs12="mimir/wsinop-ruler.yaml evaluation_delay 15m; raw rate 0.03",
            obs13="no",
            obs14="wrote tickets/OBS-5356.md",
            obs15="xfail tests/test_wsinop_evaldelay.py",
        ),
    )
)
