"""Observability plants r277-r288. Do not clone r109-r276.

BAN r163 tid128, r172 inferred db, r190 DD UST,
r244 loki-querier-max-concurrent / loki-qconc-rebuild-blooms.
"""

from mill_plants_h import _failp
from mill_plants_l import _okx

MORE = []

# r277 Loki frontend_worker parallelism 0
MORE.append(
    (
        _okx(
            slug="loki-frontend-worker-parallelism-zero",
            service="spoiler-panel-svc",
            dashboard_uid="spanel-fwpar-1",
            panel="spoiler panel logs",
            query='{job="spoiler-panel-svc"} |= "panel_jam"',
            lie="frontend_worker parallelism 0 never pulls scheduler work so Grafana LogQL hangs empty while queriers are Ready",
            false_lead="querier_forget_delay 0s / max_query_parallelism 1",
            config_path="loki/spanel-forget.yaml",
            lie_path="loki/spanel-worker.yaml",
            truth_name="frontend_worker parallelism vs ring",
            reload_name="loki-querier",
            side="workers with parallelism 10 still query",
            surfaces="Loki frontend_worker parallelism 0 vs Grafana hang",
            avoided="r272 querier_forget_delay; r271 max_query_parallelism; r244 max_concurrent",
            this_is="parallelism 0 never dequeues scheduler jobs",
            step_note="False lead forget/qpar 4-5; worker 0 6-8; 10 9-12.",
            query_cmd="curl -sS -G $LOKI/loki/api/v1/query_range --data-urlencode 'query={job=\"spoiler-panel-svc\"} |= \"panel_jam\"' --max-time 5 | jq '{status,error}'",
            false_cmd="yq '.query_scheduler.querier_forget_delay, .limits_config.max_query_parallelism' loki/spanel-forget.yaml",
            truth_cmd="kubectl -n loki get pods -l app=loki-querier -o wide",
            confirm_cmd="yq '.frontend_worker.parallelism' loki/spanel-worker.yaml",
            reload_cmd="kubectl -n loki rollout restart deploy/loki-querier && kubectl -n loki rollout status deploy/loki-querier --timeout=90s",
            requery_cmd="curl -sS -G $LOKI/loki/api/v1/query_range --data-urlencode 'query={job=\"spoiler-panel-svc\"} |= \"panel_jam\"' | jq '.data.result|length'",
            side_cmd="curl -sS -G $LOKI/loki/api/v1/query_range --data-urlencode 'query={job=\"ssr-meal-svc\"} |= \"error\"' | jq '.data.result|length'",
            final_cmd="yq -r '.frontend_worker.parallelism' loki/spanel-worker.yaml",
            patch_old="parallelism: 0",
            patch_new="parallelism: 10",
            runbook_path="runbooks/spanel-fw-parallel.md",
            runbook="# spoiler-panel-svc frontend_worker.parallelism\n0 never pulls scheduler work. Raise 10. Not querier_forget_delay.\n",
            goal="spoiler-panel-svc dashboard spanel-fwpar-1 spoiler panel logs hang. queriers Ready. Find the worker-parallelism lie.",
            plan="Hang → forget/qpar (false) → parallelism 0 → 10.",
            outcome="parallelism 10. 8 streams. ssr-meal-svc unchanged.",
            obs1='[{"uid":"spanel-fwpar-1","title":"spoiler panel logs"}]',
            obs2='{"title":"spoiler panel logs","targets":[{"expr":"{job=\\"spoiler-panel-svc\\"} |= \\"panel_jam\\""}]}',
            obs3='{"status":"error","error":"context deadline exceeded"}',
            obs4="querier_forget_delay: 5m\nmax_query_parallelism: 32  # not r272/r271",
            obs5="forget 5m; parallelism 32",
            obs6="parallelism: 0",
            obs7="loki-querier-0 Ready 1/1",
            obs8="queriers Ready; worker pulls 0 jobs",
            obs9="patched 10",
            obs10='deployment "loki-querier" successfully rolled out',
            obs11="8",
            obs12='{"name":"Logs"}',
            obs13="1",
            obs14="wrote runbooks/spanel-fw-parallel.md",
            obs15="10",
        ),
        _failp(
            slug="loki-fwpar-raise-forget-not-worker",
            service="aileron-lock-svc",
            dashboard_uid="alock-fwpar-forget",
            panel="aileron lock logs",
            query='{job="aileron-lock-svc"} |= "lock_fail"',
            lie="Raising querier_forget_delay does not dequeue Loki queries when frontend_worker parallelism is 0",
            false_lead="querier_forget_delay 0s drops restarted queriers",
            config_path="loki/alock-forget.yaml",
            lie_path="loki/alock-worker.yaml",
            wrong_path="loki/alock-forget.yaml",
            reload_name="loki-query-scheduler",
            ticket="OBS-5345",
            xfail="tests/test_alock_fwpar.py",
            surfaces="forget leftover vs frontend_worker parallelism 0",
            avoided="r272 as actual RCA",
            this_is="fail/handoff: forget 5m, worker still 0",
            step_note="forget 6-10; still hang 11; late worker 0 12; handoff 14-15.",
            next_note="Next: Tempo max_block_bytes.",
            query_cmd="curl -sS -G $LOKI/loki/api/v1/query_range --data-urlencode 'query={job=\"aileron-lock-svc\"} |= \"lock_fail\"' --max-time 5 | jq '{status,error}'",
            false_cmd="yq '.query_scheduler.querier_forget_delay' loki/alock-forget.yaml",
            reload_cmd="kubectl -n loki rollout restart deploy/query-scheduler && kubectl -n loki rollout status deploy/query-scheduler --timeout=90s",
            requery_cmd="curl -sS -G $LOKI/loki/api/v1/query_range --data-urlencode 'query={job=\"aileron-lock-svc\"} |= \"lock_fail\"' --max-time 5 | jq '{status,error}'",
            denied_cmd="kubectl -n loki auth can-i patch deploy/loki-querier --as=sre-bot",
            wrong_old="querier_forget_delay: 0s",
            wrong_new="querier_forget_delay: 5m",
            wrong2_old="max_query_parallelism: 1",
            wrong2_new="max_query_parallelism: 32",
            ticket_body="OBS-5345: aileron-lock-svc still hangs. forget leftover. frontend_worker parallelism 0. Need 10. No querier RBAC.\n",
            goal="aileron-lock-svc dashboard alock-fwpar-forget aileron lock logs hang. Restore queries.",
            plan="Raise querier_forget_delay (r272 leftover).",
            outcome="forget 5m; still hang. Late worker 0. Handoff OBS-5345.",
            obs1='[{"uid":"alock-fwpar-forget","title":"aileron lock logs"}]',
            obs2='{"title":"aileron lock logs","targets":[{"expr":"{job=\\"aileron-lock-svc\\"} |= \\"lock_fail\\""}]}',
            obs3='{"status":"error","error":"context deadline exceeded"}',
            obs4="querier_forget_delay: 0s",
            obs5="treated as r272",
            obs6="loki/alock-forget.yaml",
            obs7="patched 5m",
            obs8='deployment "query-scheduler" successfully rolled out',
            obs9='{"status":"error","error":"context deadline exceeded"}',
            obs10="patched max_query_parallelism 32",
            obs11='{"status":"error","error":"context deadline exceeded"}',
            obs12="loki/alock-worker.yaml frontend_worker parallelism 0; queriers Ready",
            obs13="no",
            obs14="wrote tickets/OBS-5345.md",
            obs15="xfail tests/test_alock_fwpar.py",
        ),
    )
)

# r278 Tempo max_block_bytes
MORE.append(
    (
        _okx(
            slug="tempo-max-block-bytes-1kib",
            service="rudder-travel-svc",
            dashboard_uid="rtravel-blkbytes-2",
            panel="rudder traces",
            query='{resource.service.name="rudder-travel-svc"}',
            lie="ingester max_block_bytes 1024 cuts traces mid-span so Grafana Search is empty while live WAL lists ids",
            false_lead="trace_idle_period 50ms / complete_block_timeout 10s",
            config_path="tempo/rtravel-idle.yaml",
            lie_path="tempo/rtravel-block.yaml",
            truth_name="max_block_bytes vs WAL ids",
            reload_name="tempo-ingester",
            side="tenants with max_block_bytes 1GiB still searchable",
            surfaces="Tempo max_block_bytes 1KiB vs Grafana empty",
            avoided="r257 trace_idle_period; r236 complete_block_timeout; r250 max_traces",
            this_is="max_block_bytes 1KiB cuts traces before flush",
            step_note="False lead idle/block-timeout 4-5; max_block_bytes 6-8; 1GiB 9-12.",
            query_cmd="curl -sS -G $TEMPO/api/search --data-urlencode 'q={resource.service.name=\"rudder-travel-svc\"}' | jq '.traces|length'",
            false_cmd="yq '.ingester.trace_idle_period, .ingester.complete_block_timeout' tempo/rtravel-idle.yaml",
            truth_cmd="curl -sS $TEMPO/status | rg 'wal|live_traces|block_bytes'",
            confirm_cmd="yq '.ingester.max_block_bytes' tempo/rtravel-block.yaml",
            reload_cmd="kubectl -n tempo rollout restart sts/tempo-ingester && kubectl -n tempo rollout status sts/tempo-ingester --timeout=120s",
            requery_cmd="curl -sS -G $TEMPO/api/search --data-urlencode 'q={resource.service.name=\"rudder-travel-svc\"}' | jq '.traces|length'",
            side_cmd="curl -sS -G $TEMPO/api/search --data-urlencode 'q={resource.service.name=\"ssr-meal-svc\"}' | jq '.traces|length'",
            final_cmd="yq -r '.ingester.max_block_bytes' tempo/rtravel-block.yaml",
            patch_old="max_block_bytes: 1024",
            patch_new="max_block_bytes: 1073741824",
            runbook_path="runbooks/rtravel-block-bytes.md",
            runbook="# rudder-travel-svc max_block_bytes\n1KiB cuts traces mid-span. Raise 1GiB. Not trace_idle_period.\n",
            goal="rudder-travel-svc dashboard rtravel-blkbytes-2 rudder traces empty. WAL has ids. Find the max_block_bytes lie.",
            plan="Empty Search → idle/timeout (false) → max_block_bytes 1KiB → 1GiB.",
            outcome="max_block_bytes 1GiB. 18 traces. ssr-meal-svc unchanged.",
            obs1='[{"uid":"rtravel-blkbytes-2","title":"rudder traces"}]',
            obs2='{"title":"rudder traces","targets":[{"query":"{resource.service.name=\\"rudder-travel-svc\\"}"}]}',
            obs3="0",
            obs4="trace_idle_period: 30s\ncomplete_block_timeout: 15m  # not r257/r236",
            obs5="idle 30s; block timeout 15m",
            obs6="max_block_bytes: 1024",
            obs7="wal ids=18 live_traces 0 last_block 1024B",
            obs8="1KiB blocks cut traces",
            obs9="patched 1GiB",
            obs10='statefulset "tempo-ingester" successfully rolled out',
            obs11="18",
            obs12='{"name":"Traces"}',
            obs13="19",
            obs14="wrote runbooks/rtravel-block-bytes.md",
            obs15="1073741824",
        ),
        _failp(
            slug="tempo-blkbytes-raise-idle-not-bytes",
            service="stab-trim-motor-svc",
            dashboard_uid="strim-blkbytes-idle",
            panel="stab trim traces",
            query='{resource.service.name="stab-trim-motor-svc"}',
            lie="Raising trace_idle_period does not keep traces cut by max_block_bytes 1024",
            false_lead="ingester trace_idle_period 50ms cuts traces",
            config_path="tempo/strim-idle.yaml",
            lie_path="tempo/strim-block.yaml",
            wrong_path="tempo/strim-idle.yaml",
            reload_name="tempo-ingester",
            ticket="OBS-5346",
            xfail="tests/test_strim_blkbytes.py",
            surfaces="idle leftover vs max_block_bytes 1KiB",
            avoided="r257 as actual RCA",
            this_is="fail/handoff: idle 30s, max_block_bytes still 1024",
            step_note="idle 6-10; still 0 11; late max_block_bytes 12; handoff 14-15.",
            next_note="Next: Loki max_chunks_per_query.",
            query_cmd="curl -sS -G $TEMPO/api/search --data-urlencode 'q={resource.service.name=\"stab-trim-motor-svc\"}' | jq '.traces|length'",
            false_cmd="yq '.ingester.trace_idle_period' tempo/strim-idle.yaml",
            reload_cmd="kubectl -n tempo rollout restart sts/tempo-ingester && kubectl -n tempo rollout status sts/tempo-ingester --timeout=120s",
            requery_cmd="curl -sS -G $TEMPO/api/search --data-urlencode 'q={resource.service.name=\"stab-trim-motor-svc\"}' | jq '.traces|length'",
            denied_cmd="kubectl -n tempo auth can-i patch configmap/strim-block --as=sre-bot",
            wrong_old="trace_idle_period: 50ms",
            wrong_new="trace_idle_period: 30s",
            wrong2_old="complete_block_timeout: 10s",
            wrong2_new="complete_block_timeout: 15m",
            ticket_body="OBS-5346: stab-trim-motor-svc Tempo still 0. idle leftover. max_block_bytes 1024. Need 1GiB. No block RBAC.\n",
            goal="stab-trim-motor-svc dashboard strim-blkbytes-idle stab trim traces empty. Land traces.",
            plan="Raise trace_idle_period (r257 leftover).",
            outcome="idle 30s; still 0. Late max_block_bytes 1024. Handoff OBS-5346.",
            obs1='[{"uid":"strim-blkbytes-idle","title":"stab trim traces"}]',
            obs2='{"title":"stab trim traces","targets":[{"query":"{resource.service.name=\\"stab-trim-motor-svc\\"}"}]}',
            obs3="0",
            obs4="trace_idle_period: 50ms",
            obs5="treated as r257",
            obs6="tempo/strim-idle.yaml",
            obs7="patched 30s",
            obs8='statefulset "tempo-ingester" successfully rolled out',
            obs9="0",
            obs10="patched complete_block 15m",
            obs11="0",
            obs12="tempo/strim-block.yaml max_block_bytes 1024 wal ids=11",
            obs13="no",
            obs14="wrote tickets/OBS-5346.md",
            obs15="xfail tests/test_strim_blkbytes.py",
        ),
    )
)

# r279 Loki max_chunks_per_query
MORE.append(
    (
        _okx(
            slug="loki-max-chunks-per-query-one",
            service="flap-load-relief-svc",
            dashboard_uid="flaplr-chunks-3",
            panel="flap relief logs",
            query='{job="flap-load-relief-svc"} |= "relief_open"',
            lie="limits_config max_chunks_per_query 1 returns a partial empty frame so Grafana 6h is blank while 1m still hits one chunk",
            false_lead="max_entries_limit_per_query 0 / max_query_length 30m",
            config_path="loki/flaplr-entries.yaml",
            lie_path="loki/flaplr-chunks.yaml",
            truth_name="max_chunks_per_query vs 1m",
            reload_name="loki-querier",
            side="1m panels still return",
            surfaces="Loki max_chunks_per_query 1 vs Grafana 6h blank",
            avoided="r246 max_entries 0; r255 max_query_length; r271 parallelism",
            this_is="max_chunks_per_query 1 blanks 6h multi-chunk queries",
            step_note="False lead entries/qlen 4-5; max_chunks 1 6-8; 2e6 9-12.",
            query_cmd="curl -sS -G $LOKI/loki/api/v1/query_range --data-urlencode 'query={job=\"flap-load-relief-svc\"} |= \"relief_open\"' --data-urlencode 'start=-6h' | jq '{status,error,n:(.data.result|length)}'",
            false_cmd="yq '.limits_config.max_entries_limit_per_query, .limits_config.max_query_length' loki/flaplr-entries.yaml",
            truth_cmd="curl -sS -G $LOKI/loki/api/v1/query_range --data-urlencode 'query={job=\"flap-load-relief-svc\"} |= \"relief_open\"' --data-urlencode 'start=-1m' | jq '.data.result|length'",
            confirm_cmd="yq '.limits_config.max_chunks_per_query' loki/flaplr-chunks.yaml",
            reload_cmd="kubectl -n loki rollout restart deploy/loki-querier && kubectl -n loki rollout status deploy/loki-querier --timeout=90s",
            requery_cmd="curl -sS -G $LOKI/loki/api/v1/query_range --data-urlencode 'query={job=\"flap-load-relief-svc\"} |= \"relief_open\"' --data-urlencode 'start=-6h' | jq '.data.result|length'",
            side_cmd="curl -sS -G $LOKI/loki/api/v1/query_range --data-urlencode 'query={job=\"ssr-meal-svc\"} |= \"error\"' --data-urlencode 'start=-1m' | jq '.data.result|length'",
            final_cmd="yq -r '.limits_config.max_chunks_per_query' loki/flaplr-chunks.yaml",
            patch_old="max_chunks_per_query: 1",
            patch_new="max_chunks_per_query: 2000000",
            runbook_path="runbooks/flaplr-max-chunks.md",
            runbook="# flap-load-relief-svc max_chunks_per_query\n1 blanks 6h. Raise 2e6. Not max_entries 0.\n",
            goal="flap-load-relief-svc dashboard flaplr-chunks-3 flap relief logs empty on 6h. 1m works. Find the chunks-cap lie.",
            plan="Empty 6h → entries/qlen (false) → max_chunks 1 → 2e6.",
            outcome="max_chunks 2e6. 9 streams. 1m jobs unchanged.",
            obs1='[{"uid":"flaplr-chunks-3","title":"flap relief logs"}]',
            obs2='{"title":"flap relief logs","targets":[{"expr":"{job=\\"flap-load-relief-svc\\"} |= \\"relief_open\\""}]}',
            obs3='{"status":"success","error":null,"n":0}',
            obs4="max_entries_limit_per_query: 5000\nmax_query_length: 24h  # not r246/r255",
            obs5="entries 5000; length 24h",
            obs6="max_chunks_per_query: 1",
            obs7="1",
            obs8="1m one chunk; 6h many chunks capped to empty",
            obs9="patched 2000000",
            obs10='deployment "loki-querier" successfully rolled out',
            obs11="9",
            obs12='{"name":"Logs"}',
            obs13="1",
            obs14="wrote runbooks/flaplr-max-chunks.md",
            obs15="2000000",
        ),
        _failp(
            slug="loki-chunks-raise-entries-not-cap",
            service="slat-skew-det-svc",
            dashboard_uid="slatsk-chunks-entries",
            panel="slat skew logs",
            query='{job="slat-skew-det-svc"} |= "skew_warn"',
            lie="Raising max_entries_limit_per_query does not fill Grafana 6h when max_chunks_per_query is 1",
            false_lead="max_entries_limit_per_query 0 empties Grafana",
            config_path="loki/slatsk-entries.yaml",
            lie_path="loki/slatsk-chunks.yaml",
            wrong_path="loki/slatsk-entries.yaml",
            reload_name="loki-querier",
            ticket="OBS-5347",
            xfail="tests/test_slatsk_chunks.py",
            surfaces="max_entries leftover vs max_chunks_per_query",
            avoided="r246 as actual RCA",
            this_is="fail/handoff: max_entries 5000, max_chunks still 1",
            step_note="entries 6-10; still 0 11; late max_chunks 12; handoff 14-15.",
            next_note="Next: OTel logstransform.",
            query_cmd="curl -sS -G $LOKI/loki/api/v1/query_range --data-urlencode 'query={job=\"slat-skew-det-svc\"} |= \"skew_warn\"' --data-urlencode 'start=-6h' | jq '{status,n:(.data.result|length)}'",
            false_cmd="yq '.limits_config.max_entries_limit_per_query' loki/slatsk-entries.yaml",
            reload_cmd="kubectl -n loki rollout restart deploy/loki-querier && kubectl -n loki rollout status deploy/loki-querier --timeout=90s",
            requery_cmd="curl -sS -G $LOKI/loki/api/v1/query_range --data-urlencode 'query={job=\"slat-skew-det-svc\"} |= \"skew_warn\"' --data-urlencode 'start=-6h' | jq '{status,n:(.data.result|length)}'",
            denied_cmd="kubectl -n loki auth can-i patch configmap/slatsk-chunks --as=sre-bot",
            wrong_old="max_entries_limit_per_query: 0",
            wrong_new="max_entries_limit_per_query: 5000",
            wrong2_old="max_query_length: 30m",
            wrong2_new="max_query_length: 24h",
            ticket_body="OBS-5347: slat-skew-det-svc 6h still 0. entries leftover. max_chunks_per_query 1. Need 2e6. No chunks RBAC.\n",
            goal="slat-skew-det-svc dashboard slatsk-chunks-entries slat skew logs empty on 6h. Restore range.",
            plan="Raise max_entries (r246 leftover).",
            outcome="max_entries 5000; still 0. Late max_chunks 1. Handoff OBS-5347.",
            obs1='[{"uid":"slatsk-chunks-entries","title":"slat skew logs"}]',
            obs2='{"title":"slat skew logs","targets":[{"expr":"{job=\\"slat-skew-det-svc\\"} |= \\"skew_warn\\""}]}',
            obs3='{"status":"success","n":0}',
            obs4="max_entries_limit_per_query: 0",
            obs5="treated as r246",
            obs6="loki/slatsk-entries.yaml",
            obs7="patched 5000",
            obs8='deployment "loki-querier" successfully rolled out',
            obs9='{"status":"success","n":0}',
            obs10="patched max_query_length 24h",
            obs11='{"status":"success","n":0}',
            obs12="loki/slatsk-chunks.yaml max_chunks_per_query 1; 1m query returns 1",
            obs13="no",
            obs14="wrote tickets/OBS-5347.md",
            obs15="xfail tests/test_slatsk_chunks.py",
        ),
    )
)

# r280 OTel logstransform vs filelog
MORE.append(
    (
        _okx(
            slug="otel-logstransform-vs-filelog",
            service="hyd-sys3-svc",
            dashboard_uid="hsys3-ltform-4",
            panel="hyd3 logs",
            query='{job="hyd-sys3-svc"} |= "pump_fail"',
            lie="logstransform statements set body to severity only so Grafana Loki {job} |= pump_fail is empty while filelog still tails the file",
            false_lead="filelog vs Loki push / filestats include []",
            config_path="otelcol/hsys3-filelog.yaml",
            lie_path="otelcol/hsys3-ltform.yaml",
            truth_name="logstransform body vs file",
            reload_name="otelcol-hsys3",
            side="pipelines without logstransform still match pump_fail",
            surfaces="OTel logstransform vs Grafana Loki body",
            avoided="r215 filelog vs Loki; r261 filestats include; r223 envoy parser",
            this_is="logstransform overwrites body with severity",
            step_note="False lead filelog/filestats 4-5; logstransform 6-8; drop it 9-12.",
            query_cmd="curl -sS -G $LOKI/loki/api/v1/query_range --data-urlencode 'query={job=\"hyd-sys3-svc\"} |= \"pump_fail\"' | jq '{status,n:(.data.result|length)}'",
            false_cmd="yq '.receivers.filelog, .receivers.filestats' otelcol/hsys3-filelog.yaml",
            truth_cmd="tail -2 /var/log/hyd3/pump.log",
            confirm_cmd="yq '.processors.logstransform' otelcol/hsys3-ltform.yaml",
            reload_cmd="kubectl -n otel rollout restart deploy/otelcol-hsys3 && kubectl -n otel rollout status deploy/otelcol-hsys3 --timeout=90s",
            requery_cmd="curl -sS -G $LOKI/loki/api/v1/query_range --data-urlencode 'query={job=\"hyd-sys3-svc\"} |= \"pump_fail\"' | jq '.data.result|length'",
            side_cmd="curl -sS -G $LOKI/loki/api/v1/query_range --data-urlencode 'query={job=\"ssr-meal-svc\"} |= \"error\"' | jq '.data.result|length'",
            final_cmd="yq -r '.service.pipelines.logs.processors[]' otelcol/hsys3-ltform.yaml",
            patch_old="processors:\n      - logstransform\n      - batch",
            patch_new="processors:\n      - batch",
            runbook_path="runbooks/hsys3-logstransform.md",
            runbook="# hyd-sys3-svc logstransform\nset body = severity drops pump_fail. Drop processor. Not filelog vs Loki.\n",
            goal="hyd-sys3-svc dashboard hsys3-ltform-4 hyd3 logs empty. file has pump_fail. Find the logstransform lie.",
            plan="Empty |= → filelog/filestats (false) → logstransform body=severity → drop it.",
            outcome="logstransform dropped. 7 streams. ssr-meal-svc unchanged.",
            obs1='[{"uid":"hsys3-ltform-4","title":"hyd3 logs"}]',
            obs2='{"title":"hyd3 logs","targets":[{"expr":"{job=\\"hyd-sys3-svc\\"} |= \\"pump_fail\\""}]}',
            obs3='{"status":"success","n":0}',
            obs4="include: [/var/log/hyd3/**]  # not r215/r261",
            obs5="filelog tails the file",
            obs6="statements:\n  - set(body, attributes[\"severity\"])",
            obs7="2026-08-19T18:00:01Z pump_fail pressure=0",
            obs8="file has pump_fail; Loki body is INFO",
            obs9="patched drop logstransform",
            obs10='deployment "otelcol-hsys3" successfully rolled out',
            obs11="7",
            obs12='{"name":"Logs"}',
            obs13="1",
            obs14="wrote runbooks/hsys3-logstransform.md",
            obs15="batch",
        ),
        _failp(
            slug="otel-ltform-fix-filestats-not-body",
            service="brake-accum-svc",
            dashboard_uid="baccum-ltform-stats",
            panel="accum logs",
            query='{job="brake-accum-svc"} |= "accum_low"',
            lie="Setting filestats include does not restore Loki |= accum_low when logstransform still overwrites body with severity",
            false_lead="filestats include [] matches no files",
            config_path="otelcol/baccum-filestats.yaml",
            lie_path="otelcol/baccum-ltform.yaml",
            wrong_path="otelcol/baccum-filestats.yaml",
            reload_name="otelcol-baccum",
            ticket="OBS-5348",
            xfail="tests/test_baccum_ltform.py",
            surfaces="filestats leftover vs logstransform body",
            avoided="r261 as actual RCA",
            this_is="fail/handoff: filestats include set, body still severity",
            step_note="filestats 6-10; still 0 11; late logstransform 12; handoff 14-15.",
            next_note="Next: Tempo search default_result_limit 0.",
            query_cmd="curl -sS -G $LOKI/loki/api/v1/query_range --data-urlencode 'query={job=\"brake-accum-svc\"} |= \"accum_low\"' | jq '{status,n:(.data.result|length)}'",
            false_cmd="yq '.receivers.filestats.include' otelcol/baccum-filestats.yaml",
            reload_cmd="kubectl -n otel rollout restart deploy/otelcol-baccum && kubectl -n otel rollout status deploy/otelcol-baccum --timeout=90s",
            requery_cmd="curl -sS -G $LOKI/loki/api/v1/query_range --data-urlencode 'query={job=\"brake-accum-svc\"} |= \"accum_low\"' | jq '{status,n:(.data.result|length)}'",
            denied_cmd="kubectl -n otel auth can-i patch configmap/baccum-ltform --as=sre-bot",
            wrong_old="include: []",
            wrong_new="include:\n      - /var/log/accum/**",
            wrong2_old="exclude: ['**/*.tmp']",
            wrong2_new="exclude: []",
            ticket_body="OBS-5348: brake-accum-svc |= still 0. filestats leftover. logstransform set body=severity. Need drop processor. No transform RBAC.\n",
            goal="brake-accum-svc dashboard baccum-ltform-stats accum logs empty. Restore |= accum_low.",
            plan="Set filestats include (r261 leftover).",
            outcome="include set; still 0. Late logstransform. Handoff OBS-5348.",
            obs1='[{"uid":"baccum-ltform-stats","title":"accum logs"}]',
            obs2='{"title":"accum logs","targets":[{"expr":"{job=\\"brake-accum-svc\\"} |= \\"accum_low\\""}]}',
            obs3='{"status":"success","n":0}',
            obs4="include: []",
            obs5="treated as r261",
            obs6="otelcol/baccum-filestats.yaml",
            obs7="patched include /var/log/accum/**",
            obs8='deployment "otelcol-baccum" successfully rolled out',
            obs9='{"status":"success","n":0}',
            obs10="patched exclude []",
            obs11='{"status":"success","n":0}',
            obs12="otelcol/baccum-ltform.yaml set(body, attributes[\"severity\"]); file accum_low line present",
            obs13="no",
            obs14="wrote tickets/OBS-5348.md",
            obs15="xfail tests/test_baccum_ltform.py",
        ),
    )
)

# r281 Tempo search default_result_limit 0
MORE.append(
    (
        _okx(
            slug="tempo-search-default-result-limit-zero",
            service="nws-tillers-svc",
            dashboard_uid="nws-dlimit-5",
            panel="NWS traces",
            query='{resource.service.name="nws-tillers-svc"}',
            lie="query_frontend.search.default_result_limit 0 returns zero traces so Grafana Search is empty while GET /api/traces/{id} works",
            false_lead="search.enabled false / concurrent_jobs 0",
            config_path="tempo/nws-searchoff.yaml",
            lie_path="tempo/nws-dlimit.yaml",
            truth_name="default_result_limit vs by-id",
            reload_name="tempo-query-frontend",
            side="frontends with default_result_limit 20 still list",
            surfaces="Tempo search.default_result_limit 0 vs Grafana empty list",
            avoided="r247 search.enabled; r265 concurrent_jobs; r82 search limit 3",
            this_is="default_result_limit 0 returns an empty Search list",
            step_note="False lead enabled/jobs 4-5; default_result_limit 0 6-8; 20 9-12.",
            query_cmd="curl -sS -G $TEMPO/api/search --data-urlencode 'q={resource.service.name=\"nws-tillers-svc\"}' | jq '{n:(.traces|length),error}'",
            false_cmd="yq '.query_frontend.search.enabled, .query_frontend.search.concurrent_jobs' tempo/nws-searchoff.yaml",
            truth_cmd="curl -sS $TEMPO/api/traces/c60789abcdef012345670123456789ab | jq '.batches|length'",
            confirm_cmd="yq '.query_frontend.search.default_result_limit' tempo/nws-dlimit.yaml",
            reload_cmd="kubectl -n tempo rollout restart deploy/query-frontend && kubectl -n tempo rollout status deploy/query-frontend --timeout=90s",
            requery_cmd="curl -sS -G $TEMPO/api/search --data-urlencode 'q={resource.service.name=\"nws-tillers-svc\"}' | jq '.traces|length'",
            side_cmd="curl -sS -G $TEMPO/api/search --data-urlencode 'q={resource.service.name=\"ssr-meal-svc\"}' | jq '.traces|length'",
            final_cmd="yq -r '.query_frontend.search.default_result_limit' tempo/nws-dlimit.yaml",
            patch_old="default_result_limit: 0",
            patch_new="default_result_limit: 20",
            runbook_path="runbooks/nws-dlimit.md",
            runbook="# nws-tillers-svc search.default_result_limit\n0 returns empty lists. Raise 20. Not search.enabled false.\n",
            goal="nws-tillers-svc dashboard nws-dlimit-5 NWS traces empty. by-id works. Find the default_result_limit lie.",
            plan="Empty Search → enabled/jobs (false) → default_result_limit 0 → 20.",
            outcome="limit 20. 13 traces. ssr-meal-svc unchanged.",
            obs1='[{"uid":"nws-dlimit-5","title":"nws traces"}]',
            obs2='{"title":"NWS traces","targets":[{"query":"{resource.service.name=\\"nws-tillers-svc\\"}"}]}',
            obs3='{"n":0,"error":null}',
            obs4="enabled: true\nconcurrent_jobs: 1000  # not r247/r265",
            obs5="search on; jobs 1000",
            obs6="default_result_limit: 0",
            obs7="2",
            obs8="by-id works; Search limit 0",
            obs9="patched 20",
            obs10='deployment "query-frontend" successfully rolled out',
            obs11="13",
            obs12='{"name":"Traces"}',
            obs13="19",
            obs14="wrote runbooks/nws-dlimit.md",
            obs15="20",
        ),
        _failp(
            slug="tempo-dlimit-enable-search-not-limit",
            service="pack-flow-svc",
            dashboard_uid="pflow-dlimit-search",
            panel="pack flow traces",
            query='{resource.service.name="pack-flow-svc"}',
            lie="Flipping search.enabled true does not list traces when default_result_limit is 0",
            false_lead="query_frontend.search.enabled false",
            config_path="tempo/pflow-searchoff.yaml",
            lie_path="tempo/pflow-dlimit.yaml",
            wrong_path="tempo/pflow-searchoff.yaml",
            reload_name="tempo-query-frontend",
            ticket="OBS-5349",
            xfail="tests/test_pflow_dlimit.py",
            surfaces="search.enabled leftover vs default_result_limit 0",
            avoided="r247 as actual RCA",
            this_is="fail/handoff: search on, default_result_limit still 0",
            step_note="search.enabled 6-10; still 0 11; late default_result_limit 12; handoff 14-15.",
            next_note="Next: Loki pattern metric_aggregation.",
            query_cmd="curl -sS -G $TEMPO/api/search --data-urlencode 'q={resource.service.name=\"pack-flow-svc\"}' | jq '{n:(.traces|length),error}'",
            false_cmd="yq '.query_frontend.search.enabled' tempo/pflow-searchoff.yaml",
            reload_cmd="kubectl -n tempo rollout restart deploy/query-frontend && kubectl -n tempo rollout status deploy/query-frontend --timeout=90s",
            requery_cmd="curl -sS -G $TEMPO/api/search --data-urlencode 'q={resource.service.name=\"pack-flow-svc\"}' | jq '{n:(.traces|length),error}'",
            denied_cmd="kubectl -n tempo auth can-i patch configmap/pflow-dlimit --as=sre-bot",
            wrong_old="enabled: false",
            wrong_new="enabled: true",
            wrong2_old="concurrent_jobs: 0",
            wrong2_new="concurrent_jobs: 1000",
            ticket_body="OBS-5349: pack-flow-svc Search still 0. search.enabled leftover. default_result_limit 0. Need 20. No limit RBAC.\n",
            goal="pack-flow-svc dashboard pflow-dlimit-search pack flow traces empty. Restore Search list.",
            plan="Enable search (r247 leftover).",
            outcome="search on; still 0. Late default_result_limit 0. Handoff OBS-5349.",
            obs1='[{"uid":"pflow-dlimit-search","title":"pack flow traces"}]',
            obs2='{"title":"pack flow traces","targets":[{"query":"{resource.service.name=\\"pack-flow-svc\\"}"}]}',
            obs3='{"n":0,"error":null}',
            obs4="enabled: false",
            obs5="treated as r247",
            obs6="tempo/pflow-searchoff.yaml",
            obs7="patched enabled true",
            obs8='deployment "query-frontend" successfully rolled out',
            obs9='{"n":0,"error":null}',
            obs10="patched concurrent_jobs 1000",
            obs11='{"n":0,"error":null}',
            obs12="tempo/pflow-dlimit.yaml default_result_limit 0; GET by-id 2 batches",
            obs13="no",
            obs14="wrote tickets/OBS-5349.md",
            obs15="xfail tests/test_pflow_dlimit.py",
        ),
    )
)

# r282 Loki pattern metric_aggregation
MORE.append(
    (
        _okx(
            slug="loki-pattern-metric-aggregation",
            service="recirc-filter-svc",
            dashboard_uid="rfilt-patagg-6",
            panel="filter error rate",
            query='sum(rate({job="recirc-filter-svc"} |= "clogged"[5m]))',
            lie="pattern_ingester metric_aggregation enabled with byte_size 0 so Grafana metric query is empty while LogQL lines still exist",
            false_lead="pattern vs bloom skip / max_entries 0",
            config_path="loki/rfilt-bloom.yaml",
            lie_path="loki/rfilt-pattern.yaml",
            truth_name="metric_aggregation vs log lines",
            reload_name="loki-pattern-ingester",
            side="log panels still return lines",
            surfaces="Loki pattern metric_aggregation vs Grafana metric empty",
            avoided="r185 pattern vs bloom; r246 max_entries; r165 bloom",
            this_is="metric_aggregation byte_size 0 emits no pattern metrics",
            step_note="False lead bloom/entries 4-5; metric_aggregation 6-8; disable 9-12.",
            query_cmd="curl -sS -G $LOKI/loki/api/v1/query --data-urlencode 'query=sum(rate({job=\"recirc-filter-svc\"} |= \"clogged\"[5m]))' | jq '{status,n:(.data.result|length)}'",
            false_cmd="yq '.bloom_gateway.enabled, .limits_config.max_entries_limit_per_query' loki/rfilt-bloom.yaml",
            truth_cmd="curl -sS -G $LOKI/loki/api/v1/query_range --data-urlencode 'query={job=\"recirc-filter-svc\"} |= \"clogged\"' --data-urlencode 'start=-15m' | jq '.data.result|length'",
            confirm_cmd="yq '.pattern_ingester.metric_aggregation' loki/rfilt-pattern.yaml",
            reload_cmd="kubectl -n loki rollout restart deploy/pattern-ingester && kubectl -n loki rollout status deploy/pattern-ingester --timeout=90s",
            requery_cmd="curl -sS -G $LOKI/loki/api/v1/query --data-urlencode 'query=sum(rate({job=\"recirc-filter-svc\"} |= \"clogged\"[5m]))' | jq '.data.result|length'",
            side_cmd="curl -sS -G $LOKI/loki/api/v1/query_range --data-urlencode 'query={job=\"ssr-meal-svc\"} |= \"error\"' | jq '.data.result|length'",
            final_cmd="yq -r '.pattern_ingester.metric_aggregation.enabled' loki/rfilt-pattern.yaml",
            patch_old="enabled: true\n    byte_size: 0",
            patch_new="enabled: false",
            runbook_path="runbooks/rfilt-pat-agg.md",
            runbook="# recirc-filter-svc pattern metric_aggregation\nbyte_size 0 emits no metrics. Disable aggregation; use log metric queries. Not bloom.\n",
            goal="recirc-filter-svc dashboard rfilt-patagg-6 filter error rate empty. log lines exist. Find the metric_aggregation lie.",
            plan="Empty metric → bloom/entries (false) → metric_aggregation byte_size 0 → disable.",
            outcome="aggregation off. rate=0.3. log lines unchanged.",
            obs1='[{"uid":"rfilt-patagg-6","title":"filter error rate"}]',
            obs2='{"title":"filter error rate","targets":[{"expr":"sum(rate({job=\\"recirc-filter-svc\\"} |= \\"clogged\\"[5m]))"}]}',
            obs3='{"status":"success","n":0}',
            obs4="bloom_gateway.enabled: false\nmax_entries_limit_per_query: 5000  # not r185/r246",
            obs5="blooms off; entries 5000",
            obs6="enabled: true\nbyte_size: 0",
            obs7="4",
            obs8="log lines exist; metric_aggregation emits nothing",
            obs9="patched enabled false",
            obs10='deployment "pattern-ingester" successfully rolled out',
            obs11="1",
            obs12='{"name":"Timeseries"}',
            obs13="1",
            obs14="wrote runbooks/rfilt-pat-agg.md",
            obs15="false",
        ),
        _failp(
            slug="loki-patagg-rebuild-blooms-not-agg",
            service="cabin-co2-svc",
            dashboard_uid="cco2-patagg-bloom",
            panel="CO2 error rate",
            query='sum(rate({job="cabin-co2-svc"} |= "co2_high"[5m]))',
            lie="Rebuilding blooms does not emit Loki pattern metrics when metric_aggregation byte_size is 0",
            false_lead="bloom-gateway skip_factor stale blooms",
            config_path="loki/cco2-bloom.yaml",
            lie_path="loki/cco2-pattern.yaml",
            wrong_path="loki/cco2-bloom.yaml",
            reload_name="loki-bloom-gateway",
            ticket="OBS-5350",
            xfail="tests/test_cco2_patagg.py",
            surfaces="bloom leftover vs pattern metric_aggregation",
            avoided="r165 as actual RCA",
            this_is="fail/handoff: blooms off, metric_aggregation still byte_size 0",
            step_note="blooms 6-10; still 0 11; late metric_aggregation 12; handoff 14-15.",
            next_note="Next: OTel spanmetrics dimensions_cache_size.",
            query_cmd="curl -sS -G $LOKI/loki/api/v1/query --data-urlencode 'query=sum(rate({job=\"cabin-co2-svc\"} |= \"co2_high\"[5m]))' | jq '{status,n:(.data.result|length)}'",
            false_cmd="yq '.bloom_gateway' loki/cco2-bloom.yaml",
            reload_cmd="kubectl -n loki rollout restart deploy/bloom-gateway && kubectl -n loki rollout status deploy/bloom-gateway --timeout=90s",
            requery_cmd="curl -sS -G $LOKI/loki/api/v1/query --data-urlencode 'query=sum(rate({job=\"cabin-co2-svc\"} |= \"co2_high\"[5m]))' | jq '{status,n:(.data.result|length)}'",
            denied_cmd="kubectl -n loki auth can-i patch deploy/pattern-ingester --as=sre-bot",
            wrong_old="skip_factor: 3",
            wrong_new="skip_factor: 0",
            wrong2_old="enabled: true",
            wrong2_new="enabled: false",
            ticket_body="OBS-5350: cabin-co2-svc metric still empty. bloom leftover. pattern metric_aggregation byte_size 0. Need disable. No pattern RBAC.\n",
            goal="cabin-co2-svc dashboard cco2-patagg-bloom CO2 error rate empty. Restore metric.",
            plan="Disable blooms (r165 leftover).",
            outcome="blooms off; still 0. Late metric_aggregation. Handoff OBS-5350.",
            obs1='[{"uid":"cco2-patagg-bloom","title":"co2 error rate"}]',
            obs2='{"title":"CO2 error rate","targets":[{"expr":"sum(rate({job=\\"cabin-co2-svc\\"} |= \\"co2_high\\"[5m]))"}]}',
            obs3='{"status":"success","n":0}',
            obs4="skip_factor: 3",
            obs5="treated as r165",
            obs6="loki/cco2-bloom.yaml",
            obs7="patched skip 0",
            obs8='deployment "bloom-gateway" successfully rolled out',
            obs9='{"status":"success","n":0}',
            obs10="patched bloom enabled false",
            obs11='{"status":"success","n":0}',
            obs12="loki/cco2-pattern.yaml metric_aggregation enabled byte_size 0; log lines 3",
            obs13="no",
            obs14="wrote tickets/OBS-5350.md",
            obs15="xfail tests/test_cco2_patagg.py",
        ),
    )
)

# r283 OTel spanmetrics dimensions_cache_size
MORE.append(
    (
        _okx(
            slug="otel-spanmetrics-dim-cache-one",
            service="ozone-cat-svc",
            dashboard_uid="ozone-dimcache-7",
            panel="ozone calls",
            query='rate(traces_spanmetrics_calls_total{service="ozone-cat-svc",http_route="/ozone/status"}[5m])',
            lie="spanmetrics connector dimensions_cache_size 1 evicts http.route so Grafana {http_route=/ozone/status} is empty while the unfiltered calls_total exists",
            false_lead="spanmetrics connector name / MG filter skip",
            config_path="otelcol/ozone-conn.yaml",
            lie_path="otelcol/ozone-dimcache.yaml",
            truth_name="dimensions_cache_size vs unfiltered",
            reload_name="otelcol-ozone",
            side="unfiltered calls_total still present",
            surfaces="OTel spanmetrics dimensions_cache_size vs Grafana route empty",
            avoided="r166 connector name; r164 MG filter; r248 groupbyattrs",
            this_is="dimensions_cache_size 1 evicts http.route series",
            step_note="False lead connector/MG 4-5; cache 1 6-8; 1000 9-12.",
            query_cmd="curl -sS -G $MIMIR/prometheus/api/v1/query --data-urlencode 'query=rate(traces_spanmetrics_calls_total{service=\"ozone-cat-svc\",http_route=\"/ozone/status\"}[5m])'",
            false_cmd="yq '.connectors.spanmetrics' otelcol/ozone-conn.yaml",
            truth_cmd="curl -sS -G $MIMIR/prometheus/api/v1/query --data-urlencode 'query=rate(traces_spanmetrics_calls_total{service=\"ozone-cat-svc\"}[5m])' | jq '.data.result|length'",
            confirm_cmd="yq '.connectors.spanmetrics.dimensions_cache_size' otelcol/ozone-dimcache.yaml",
            reload_cmd="kubectl -n otel rollout restart deploy/otelcol-ozone && kubectl -n otel rollout status deploy/otelcol-ozone --timeout=90s",
            requery_cmd="curl -sS -G $MIMIR/prometheus/api/v1/query --data-urlencode 'query=rate(traces_spanmetrics_calls_total{service=\"ozone-cat-svc\",http_route=\"/ozone/status\"}[5m])'",
            side_cmd="curl -sS -G $MIMIR/prometheus/api/v1/query --data-urlencode 'query=rate(traces_spanmetrics_calls_total{service=\"ssr-meal-svc\"}[5m])' | jq '.data.result|length'",
            final_cmd="yq -r '.connectors.spanmetrics.dimensions_cache_size' otelcol/ozone-dimcache.yaml",
            patch_old="dimensions_cache_size: 1",
            patch_new="dimensions_cache_size: 1000",
            runbook_path="runbooks/ozone-dim-cache.md",
            runbook="# ozone-cat-svc spanmetrics dimensions_cache_size\n1 evicts http.route. Raise 1000. Not connector name.\n",
            goal="ozone-cat-svc dashboard ozone-dimcache-7 ozone calls empty on route. unfiltered exists. Find the dim-cache lie.",
            plan="Empty route → connector/MG (false) → cache 1 → 1000.",
            outcome="cache 1000. route rate=0.5. ssr-meal-svc unchanged.",
            obs1='[{"uid":"ozone-dimcache-7","title":"ozone calls"}]',
            obs2='{"title":"ozone calls","targets":[{"expr":"rate(traces_spanmetrics_calls_total{service=\\"ozone-cat-svc\\",http_route=\\"/ozone/status\\"}[5m])"}]}',
            obs3='{"status":"success","data":{"result":[]}}',
            obs4="namespace: traces.spanmetrics  # not r166",
            obs5="connector name correct",
            obs6="dimensions_cache_size: 1",
            obs7="1",
            obs8="unfiltered exists; route dim evicted",
            obs9="patched 1000",
            obs10='deployment "otelcol-ozone" successfully rolled out',
            obs11='{"status":"success","data":{"result":[{"value":[1710000600,"0.5"]}]}}',
            obs12='{"name":"Timeseries"}',
            obs13="1",
            obs14="wrote runbooks/ozone-dim-cache.md",
            obs15="1000",
        ),
        _failp(
            slug="otel-dimcache-rename-connector-not-size",
            service="humid-ctrl-svc",
            dashboard_uid="humid-dimcache-conn",
            panel="humid calls",
            query='rate(traces_spanmetrics_calls_total{service="humid-ctrl-svc",http_route="/humid/set"}[5m])',
            lie="Renaming the spanmetrics connector does not restore http.route series when dimensions_cache_size is 1",
            false_lead="spanmetrics processor vs connector name",
            config_path="otelcol/humid-conn.yaml",
            lie_path="otelcol/humid-dimcache.yaml",
            wrong_path="otelcol/humid-conn.yaml",
            reload_name="otelcol-humid",
            ticket="OBS-5351",
            xfail="tests/test_humid_dimcache.py",
            surfaces="connector-name leftover vs dimensions_cache_size",
            avoided="r166 as actual RCA",
            this_is="fail/handoff: connector renamed, cache still 1",
            step_note="connector 6-10; still empty 11; late cache 12; handoff 14-15.",
            next_note="Next: Prom native_histogram_min_bucket_factor.",
            query_cmd="curl -sS -G $MIMIR/prometheus/api/v1/query --data-urlencode 'query=rate(traces_spanmetrics_calls_total{service=\"humid-ctrl-svc\",http_route=\"/humid/set\"}[5m])'",
            false_cmd="yq '.connectors.spanmetrics.namespace' otelcol/humid-conn.yaml",
            reload_cmd="kubectl -n otel rollout restart deploy/otelcol-humid && kubectl -n otel rollout status deploy/otelcol-humid --timeout=90s",
            requery_cmd="curl -sS -G $MIMIR/prometheus/api/v1/query --data-urlencode 'query=rate(traces_spanmetrics_calls_total{service=\"humid-ctrl-svc\",http_route=\"/humid/set\"}[5m])'",
            denied_cmd="kubectl -n otel auth can-i patch configmap/humid-dimcache --as=sre-bot",
            wrong_old="namespace: calls_total",
            wrong_new="namespace: traces.spanmetrics",
            wrong2_old="dimensions: []",
            wrong2_new="dimensions: [http.route]",
            ticket_body="OBS-5351: humid-ctrl-svc route still empty. connector leftover. dimensions_cache_size 1. Need 1000. No cache RBAC.\n",
            goal="humid-ctrl-svc dashboard humid-dimcache-conn humid calls empty on route. Restore series.",
            plan="Rename spanmetrics connector (r166 leftover).",
            outcome="namespace traces.spanmetrics; still empty. Late cache 1. Handoff OBS-5351.",
            obs1='[{"uid":"humid-dimcache-conn","title":"humid calls"}]',
            obs2='{"title":"humid calls","targets":[{"expr":"rate(traces_spanmetrics_calls_total{service=\\"humid-ctrl-svc\\",http_route=\\"/humid/set\\"}[5m])"}]}',
            obs3='{"status":"success","data":{"result":[]}}',
            obs4="namespace: calls_total",
            obs5="treated as r166",
            obs6="otelcol/humid-conn.yaml",
            obs7="patched namespace",
            obs8='deployment "otelcol-humid" successfully rolled out',
            obs9='{"status":"success","data":{"result":[]}}',
            obs10="patched dimensions http.route",
            obs11='{"status":"success","data":{"result":[]}}',
            obs12="otelcol/humid-dimcache.yaml dimensions_cache_size 1; unfiltered calls_total exists",
            obs13="no",
            obs14="wrote tickets/OBS-5351.md",
            obs15="xfail tests/test_humid_dimcache.py",
        ),
    )
)

# r284 Prom native_histogram_min_bucket_factor
MORE.append(
    (
        _okx(
            slug="prom-nh-min-bucket-factor",
            service="cargo-smoke-svc",
            dashboard_uid="csmoke-nhfactor-8",
            panel="smoke heatmap",
            query='histogram_quantile(0.99, rate(cargo_smoke_ppm_bucket{job="cargo-smoke-svc"}[5m]))',
            lie="scrape native_histogram_min_bucket_factor 8 merges custom le bounds so Grafana heatmap is empty while /metrics still has 10 buckets",
            false_lead="native_histogram_bucket_limit 1 / native-only scrape",
            config_path="prom/csmoke-nhlimit.yaml",
            lie_path="prom/csmoke-factor.yaml",
            truth_name="min_bucket_factor vs /metrics le",
            reload_name="prom-scrape",
            side="jobs with min_bucket_factor 0 still quantile",
            surfaces="Prometheus native_histogram_min_bucket_factor vs Grafana heatmap",
            avoided="r262 bucket_limit; r187 native vs classic; r238 body_size",
            this_is="min_bucket_factor 8 merges custom buckets away",
            step_note="False lead bucket_limit/native 4-5; factor 8 6-8; 0 9-12.",
            query_cmd="curl -sS -G $MIMIR/prometheus/api/v1/query --data-urlencode 'query=histogram_quantile(0.99, rate(cargo_smoke_ppm_bucket{job=\"cargo-smoke-svc\"}[5m]))'",
            false_cmd="yq '.scrape_configs[]|select(.job_name==\"cargo-smoke-svc\").native_histogram_bucket_limit' prom/csmoke-nhlimit.yaml",
            truth_cmd="curl -sS http://cargo-smoke-svc:8080/metrics | rg cargo_smoke_ppm_bucket | wc -l",
            confirm_cmd="yq '.scrape_configs[]|select(.job_name==\"cargo-smoke-svc\").native_histogram_min_bucket_factor' prom/csmoke-factor.yaml",
            reload_cmd="kubectl -n prom rollout restart deploy/prom-scrape && kubectl -n prom rollout status deploy/prom-scrape --timeout=90s",
            requery_cmd="curl -sS -G $MIMIR/prometheus/api/v1/query --data-urlencode 'query=histogram_quantile(0.99, rate(cargo_smoke_ppm_bucket{job=\"cargo-smoke-svc\"}[5m]))'",
            side_cmd="curl -sS -G $MIMIR/prometheus/api/v1/query --data-urlencode 'query=histogram_quantile(0.99, rate(cargo_smoke_ppm_bucket{job=\"ssr-meal-svc\"}[5m]))' | jq '.data.result|length'",
            final_cmd="yq -r '.scrape_configs[]|select(.job_name==\"cargo-smoke-svc\").native_histogram_min_bucket_factor' prom/csmoke-factor.yaml",
            patch_old="native_histogram_min_bucket_factor: 8",
            patch_new="native_histogram_min_bucket_factor: 0",
            runbook_path="runbooks/csmoke-nh-factor.md",
            runbook="# cargo-smoke-svc native_histogram_min_bucket_factor\n8 merges custom le. Set 0. Not bucket_limit 1.\n",
            goal="cargo-smoke-svc dashboard csmoke-nhfactor-8 smoke heatmap empty. /metrics has 10 le. Find the min_bucket_factor lie.",
            plan="Empty quantile → bucket_limit (false) → factor 8 → 0.",
            outcome="factor 0. p99=12. ssr-meal-svc unchanged.",
            obs1='[{"uid":"csmoke-nhfactor-8","title":"smoke heatmap"}]',
            obs2='{"title":"smoke heatmap","targets":[{"expr":"histogram_quantile(0.99, rate(cargo_smoke_ppm_bucket{job=\\"cargo-smoke-svc\\"}[5m]))"}]}',
            obs3='{"status":"success","data":{"result":[]}}',
            obs4="native_histogram_bucket_limit: 0  # not r262",
            obs5="bucket_limit unlimited",
            obs6="native_histogram_min_bucket_factor: 8",
            obs7="10",
            obs8="/metrics 10 le; scrape merged to schema",
            obs9="patched 0",
            obs10='deployment "prom-scrape" successfully rolled out',
            obs11='{"status":"success","data":{"result":[{"value":[1710000600,"12"]}]}}',
            obs12='{"name":"Heatmap"}',
            obs13="1",
            obs14="wrote runbooks/csmoke-nh-factor.md",
            obs15="0",
        ),
        _failp(
            slug="prom-nhfactor-raise-bucket-limit-not-factor",
            service="lav-waste-svc",
            dashboard_uid="lwaste-nhfactor-limit",
            panel="waste heatmap",
            query='histogram_quantile(0.99, rate(lav_waste_level_bucket{job="lav-waste-svc"}[5m]))',
            lie="Raising native_histogram_bucket_limit does not restore custom buckets when min_bucket_factor is 8",
            false_lead="native_histogram_bucket_limit 1 collapses buckets",
            config_path="prom/lwaste-nhlimit.yaml",
            lie_path="prom/lwaste-factor.yaml",
            wrong_path="prom/lwaste-nhlimit.yaml",
            reload_name="prom-scrape",
            ticket="OBS-5352",
            xfail="tests/test_lwaste_nhfactor.py",
            surfaces="bucket_limit leftover vs min_bucket_factor 8",
            avoided="r262 as actual RCA",
            this_is="fail/handoff: bucket_limit 0, factor still 8",
            step_note="bucket_limit 6-10; still empty 11; late factor 12; handoff 14-15.",
            next_note="Catalog r277-r284. Keep unique vs r109-r276.",
            query_cmd="curl -sS -G $MIMIR/prometheus/api/v1/query --data-urlencode 'query=histogram_quantile(0.99, rate(lav_waste_level_bucket{job=\"lav-waste-svc\"}[5m]))'",
            false_cmd="yq '.scrape_configs[]|select(.job_name==\"lav-waste-svc\").native_histogram_bucket_limit' prom/lwaste-nhlimit.yaml",
            reload_cmd="kubectl -n prom rollout restart deploy/prom-scrape && kubectl -n prom rollout status deploy/prom-scrape --timeout=90s",
            requery_cmd="curl -sS -G $MIMIR/prometheus/api/v1/query --data-urlencode 'query=histogram_quantile(0.99, rate(lav_waste_level_bucket{job=\"lav-waste-svc\"}[5m]))'",
            denied_cmd="kubectl -n prom auth can-i patch configmap/lwaste-factor --as=sre-bot",
            wrong_old="native_histogram_bucket_limit: 1",
            wrong_new="native_histogram_bucket_limit: 0",
            wrong2_old="always_scrape_classic_histograms: false",
            wrong2_new="always_scrape_classic_histograms: true",
            ticket_body="OBS-5352: lav-waste-svc heatmap still empty. bucket_limit leftover. min_bucket_factor 8. Need 0. No factor RBAC.\n",
            goal="lav-waste-svc dashboard lwaste-nhfactor-limit waste heatmap empty. Restore quantile.",
            plan="Raise bucket_limit (r262 leftover).",
            outcome="bucket_limit 0; still empty. Late factor 8. Handoff OBS-5352.",
            obs1='[{"uid":"lwaste-nhfactor-limit","title":"waste heatmap"}]',
            obs2='{"title":"waste heatmap","targets":[{"expr":"histogram_quantile(0.99, rate(lav_waste_level_bucket{job=\\"lav-waste-svc\\"}[5m]))"}]}',
            obs3='{"status":"success","data":{"result":[]}}',
            obs4="native_histogram_bucket_limit: 1",
            obs5="treated as r262",
            obs6="prom/lwaste-nhlimit.yaml",
            obs7="patched 0",
            obs8='deployment "prom-scrape" successfully rolled out',
            obs9='{"status":"success","data":{"result":[]}}',
            obs10="patched classic true",
            obs11='{"status":"success","data":{"result":[]}}',
            obs12="prom/lwaste-factor.yaml native_histogram_min_bucket_factor 8; /metrics 10 le",
            obs13="no",
            obs14="wrote tickets/OBS-5352.md",
            obs15="xfail tests/test_lwaste_nhfactor.py",
        ),
    )
)
