"""Observability leftover leftover leftover leftover leftover leftover plants r683+.

BAN r515 rootly-urgency-filter, r384 otel-forward-connector, PagerDuty orch,
Opsgenie alias, r163-r682 clones including mill_plants_w leftover4 and mill_plants_x leftover5.
"""

from mill_plants_t import _leftover_pair

MORE = []
ROUND_PAIRS = {}


def _emit(round_n, **kwargs):
    dest = []
    _leftover_pair(n=str(round_n), dest=dest, **kwargs)
    MORE.extend(dest)
    ROUND_PAIRS[round_n] = dest[0]


def _l6(n, **kw):
    vendor = kw["vendor"]
    noun = kw["noun"]
    prefix = kw["prefix"]
    ok_svc = f"hang-{noun}-svc"
    bad_svc = f"shop-{noun}-svc"
    tag = noun.replace("-", "")[:8]
    vtag = prefix.replace("-", "")[:5]
    ok_dash = f"{tag}-{vtag}-{n}"
    bad_dash = f"s{tag[:7]}-{vtag}-fl"
    lie_core = kw["lie_core"]
    _emit(
        n,
        kind="grafana",
        ok_slug=kw["ok_slug"],
        bad_slug=kw["bad_slug"],
        ok_svc=ok_svc,
        bad_svc=bad_svc,
        ok_dash=ok_dash,
        bad_dash=bad_dash,
        panel=kw["panel"],
        metric="",
        needle=kw["needle"],
        lie=(
            f"{vendor} leftover {lie_core} so Grafana dashboard {ok_dash} is empty "
            f"while the source still 202"
        ),
        bad_lie=(
            f"{kw['false_lead']} does not restore leftover leftover leftover leftover leftover leftover "
            f"{lie_core}"
        ),
        false_lead=kw["false_lead"],
        avoided=kw["avoided"],
        this_is=f"{vendor} leftover leftover leftover leftover leftover leftover {lie_core}",
        ticket=f"OBS-{7900 + (n - 683)}",
        knob=kw["knob"],
        old=kw["old"],
        new=kw["new"],
        wrong_knob=kw["wrong_knob"],
        wrong_old=kw["wrong_old"],
        wrong_new=kw["wrong_new"],
        wrong2_old=kw["wrong2_old"],
        wrong2_new=kw["wrong2_new"],
        reload="grafana",
        config_path=f"{prefix}/{tag}-false.yaml",
        lie_path=f"{prefix}/{tag}-lie.yaml",
        bad_config=f"{prefix}/s{tag[:7]}-false.yaml",
        bad_lie_path=f"{prefix}/s{tag[:7]}-lie.yaml",
    )


SPECS = [
    dict(vendor="postgres_exporter", ok_slug="pgexp-query-disable-drop-leftover", bad_slug="pgexp-q-raise-int-not-enable", noun="hdoor", panel="postgres exporter", needle="pg_up", lie_core="custom query leftover disable hang-hdoor-svc so Grafana is empty", false_lead="postgres_exporter interval leftover", avoided="prometheus-adapter r580; leftover3 VM relabel; PagerDuty orch; Opsgenie alias", knob=".queries.disable", old="disable: [hang-hdoor-svc]", new="disable: []", wrong_knob=".scrape.interval", wrong_old="interval: 5m", wrong_new="interval: 15s", wrong2_old="dsn: postgres://sandbox", wrong2_new="dsn: postgres://hangar", prefix="pgexp"),
    dict(vendor="mysqld_exporter", ok_slug="mysqlexp-collector-disable-leftover", bad_slug="myexp-col-raise-lockwait-not-enable", noun="hlight", panel="mysqld exporter", needle="mysql_up", lie_core="collector leftover collect.info_schema.processlist=false so Grafana is empty", false_lead="mysqld_exporter lock wait leftover", avoided="postgres_exporter plant; leftover3 VM relabel; PagerDuty orch; Opsgenie alias", knob=".collect.info_schema.processlist", old="processlist: false", new="processlist: true", wrong_knob=".collect.info_schema.innodb_metrics", wrong_old="innodb_metrics: false", wrong_new="innodb_metrics: true", wrong2_old="lock_wait_timeout: 1", wrong2_new="lock_wait_timeout: 2", prefix="myexp"),
    dict(vendor="redis_exporter", ok_slug="redisexp-check-keys-drop-leftover", bad_slug="rdexp-keys-raise-timeout-not-check", noun="hhvac", panel="redis exporter", needle="redis_up", lie_core="check-keys leftover empty so Grafana is empty while redis-cli still PONG", false_lead="redis_exporter timeout leftover", avoided="mysqld_exporter plant; leftover3 VM relabel; PagerDuty orch; Opsgenie alias", knob=".check-keys", old="check-keys: ", new="check-keys: hang-hhvac-svc:*", wrong_knob=".connection-timeout", wrong_old="connection-timeout: 1ms", wrong_new="connection-timeout: 5s", wrong2_old="redis.addr: localhost:0", wrong2_new="redis.addr: redis:6379", prefix="rdexp"),
    dict(vendor="mongodb_exporter", ok_slug="mongodexp-collstats-disable-leftover", bad_slug="mgexp-coll-raise-disc-not-enable", noun="hfire", panel="mongodb exporter", needle="mongo_up", lie_core="collstats leftover compatible-mode false plus collect.collstats=false so Grafana is empty", false_lead="mongodb_exporter discover leftover", avoided="redis_exporter plant; leftover3 VM relabel; PagerDuty orch; Opsgenie alias", knob=".collect.collstats", old="collstats: false", new="collstats: true", wrong_knob=".discovering-mode", wrong_old="discovering-mode: false", wrong_new="discovering-mode: true", wrong2_old="mongodb.uri: mongodb://sandbox", wrong2_new="mongodb.uri: mongodb://hangar", prefix="mgexp"),
    dict(vendor="elasticsearch_exporter", ok_slug="esexp-cluster-info-disable-leftover", bad_slug="esexp-info-raise-timeout-not-enable", noun="foamdel", panel="ES exporter", needle="es_up", lie_core="clusterinfo leftover es.clusterinfo.interval=0 so Grafana is empty while _cluster/health still 200", false_lead="elasticsearch_exporter timeout leftover", avoided="leftover3 OpenSearch blocks; leftover3 elastic-apm; PagerDuty orch; Opsgenie alias", knob=".es.clusterinfo.interval", old="interval: 0", new="interval: 5m", wrong_knob=".es.timeout", wrong_old="timeout: 1ms", wrong_new="timeout: 10s", wrong2_old="es.uri: http://sandbox:9200", wrong2_new="es.uri: http://es:9200", prefix="esexp"),
    dict(vendor="kafka_exporter", ok_slug="kafkaexp-topic-filter-drop-leftover", bad_slug="kexp-topic-raise-offset-not-filter", noun="dockpwr", panel="kafka exporter", needle="kafka_lag", lie_core="topic leftover filter=sandbox so Grafana is empty while kafka-topics still lists hang-dockpwr-svc", false_lead="kafka_exporter offset leftover", avoided="leftover3 zipkin kafka topic; leftover3 VM relabel; PagerDuty orch; Opsgenie alias", knob=".topic.filter", old="filter: sandbox", new="filter: hang-dockpwr-svc", wrong_knob=".offset.show-all", wrong_old="show-all: false", wrong_new="show-all: true", wrong2_old="kafka.server: sandbox:9092", wrong2_new="kafka.server: kafka:9092", prefix="kexp"),
    dict(vendor="jmx_exporter", ok_slug="jmxexp-whitelist-drop-leftover", bad_slug="jmxexp-wl-raise-port-not-list", noun="hz400", panel="JMX exporter", needle="jmx_up", lie_core="whitelistObjectNames leftover empty so Grafana is empty while jolokia still 200", false_lead="jmx_exporter port leftover", avoided="kafka_exporter plant; leftover3 VM relabel; PagerDuty orch; Opsgenie alias", knob=".whitelistObjectNames", old="whitelistObjectNames: []", new="whitelistObjectNames: [java.lang:*]", wrong_knob=".startDelaySeconds", wrong_old="startDelaySeconds: 3600", wrong_new="startDelaySeconds: 0", wrong2_old="hostPort: sandbox:0", wrong2_new="hostPort: hangar:9010", prefix="jmxexp"),
    dict(vendor="nginx-prometheus-exporter", ok_slug="nginxexp-stub-status-drop-leftover", bad_slug="ngxexp-stub-raise-int-not-uri", noun="vdc28", panel="nginx exporter", needle="ngx_up", lie_core="stub_status leftover uri /stub_status_missing so Grafana is empty while nginx still 200", false_lead="nginx exporter interval leftover", avoided="jmx_exporter plant; leftover3 VM relabel; PagerDuty orch; Opsgenie alias", knob=".nginx.scrape-uri", old="scrape-uri: http://localhost/missing", new="scrape-uri: http://localhost/stub_status", wrong_knob=".nginx.timeout", wrong_old="timeout: 1ms", wrong_new="timeout: 5s", wrong2_old="nginx.plus: true", wrong2_new="nginx.plus: false", prefix="ngxexp"),
    dict(vendor="haproxy_exporter", ok_slug="haproxyexp-pid-file-drop-leftover", bad_slug="hapexp-pid-raise-timeout-not-file", noun="vac115", panel="haproxy exporter", needle="hap_up", lie_core="haproxy.pid-file leftover /tmp/empty so Grafana is empty while stats socket still works", false_lead="haproxy_exporter timeout leftover", avoided="nginx exporter plant; leftover3 VM relabel; PagerDuty orch; Opsgenie alias", knob=".haproxy.pid-file", old="pid-file: /tmp/empty", new="pid-file: /run/haproxy.pid", wrong_knob=".haproxy.timeout", wrong_old="timeout: 1ms", wrong_new="timeout: 5s", wrong2_old="haproxy.scrape-uri: unix:/tmp/none", wrong2_new="haproxy.scrape-uri: unix:/run/haproxy.sock", prefix="hapexp"),
    dict(vendor="CoreDNS", ok_slug="coredns-prometheus-plugin-off-leftover", bad_slug="cdns-prom-raise-ready-not-plugin", noun="airstart", panel="CoreDNS metrics", needle="dns_up", lie_core="plugin leftover prometheus off so Grafana is empty while CoreDNS still answers", false_lead="CoreDNS ready leftover", avoided="leftover3 VM relabel; prometheus-operator r671; PagerDuty orch; Opsgenie alias", knob=".plugins.prometheus", old="prometheus: off", new="prometheus: :9153", wrong_knob=".plugins.ready", wrong_old="ready: off", wrong_new="ready: on", wrong2_old="cache: 0", wrong2_new="cache: 30", prefix="cdns"),
    dict(vendor="etcd", ok_slug="etcd-metrics-listen-drop-leftover", bad_slug="etcd-ml-raise-quota-not-listen", noun="pcahang", panel="etcd metrics", needle="etcd_up", lie_core="listen-metrics-urls leftover empty so Grafana is empty while etcd still 2379", false_lead="etcd quota leftover", avoided="CoreDNS prometheus plant; leftover3 VM relabel; PagerDuty orch; Opsgenie alias", knob=".listen-metrics-urls", old="listen-metrics-urls: ", new="listen-metrics-urls: http://0.0.0.0:2381", wrong_knob=".quota-backend-bytes", wrong_old="quota-backend-bytes: 1", wrong_new="quota-backend-bytes: 2147483648", wrong2_old="metrics: none", wrong2_new="metrics: extensive", prefix="etcd"),
    dict(vendor="kube-scheduler", ok_slug="ksched-bind-address-drop-leftover", bad_slug="ksched-bind-raise-qps-not-addr", noun="pothang", panel="scheduler metrics", needle="sched_up", lie_core="bind-address leftover 127.0.0.1 so Grafana scrape is empty while scheduling still works", false_lead="kube-scheduler QPS leftover", avoided="etcd metrics plant; prometheus-operator r671; PagerDuty orch; Opsgenie alias", knob=".bind-address", old="bind-address: 127.0.0.1", new="bind-address: 0.0.0.0", wrong_knob=".kube-api-qps", wrong_old="kube-api-qps: 1", wrong_new="kube-api-qps: 50", wrong2_old="profiling: false", wrong2_new="profiling: true", prefix="ksched"),
    dict(vendor="kube-controller-manager", ok_slug="kcm-secure-port-drop-leftover", bad_slug="kcm-port-raise-qps-not-bind", noun="lavhang", panel="controller metrics", needle="kcm_up", lie_core="bind-address leftover 127.0.0.1 so Grafana scrape is empty while controllers still reconcile", false_lead="kube-controller-manager QPS leftover", avoided="kube-scheduler bind plant; prometheus-operator r671; PagerDuty orch; Opsgenie alias", knob=".bind-address", old="bind-address: 127.0.0.1", new="bind-address: 0.0.0.0", wrong_knob=".kube-api-qps", wrong_old="kube-api-qps: 1", wrong_new="kube-api-qps: 50", wrong2_old="controllers: [-*]", wrong2_new="controllers: [*]", prefix="kcm"),
    dict(vendor="kube-proxy", ok_slug="kubeproxy-metrics-bind-drop-leftover", bad_slug="kproxy-bind-raise-mode-not-addr", noun="waterhtr", panel="kube-proxy metrics", needle="proxy_up", lie_core="metricsBindAddress leftover 127.0.0.1:0 so Grafana is empty while kube-proxy still forwards", false_lead="kube-proxy mode leftover", avoided="kube-scheduler bind plant; leftover3 VM relabel; PagerDuty orch; Opsgenie alias", knob=".metricsBindAddress", old="metricsBindAddress: 127.0.0.1:0", new="metricsBindAddress: 0.0.0.0:10249", wrong_knob=".mode", wrong_old="mode: userspace", wrong_new="mode: iptables", wrong2_old="clusterCIDR: ", wrong2_new="clusterCIDR: 10.0.0.0/8", prefix="kproxy"),
    dict(vendor="kubelet", ok_slug="kubelet-read-only-port-drop-leftover", bad_slug="kubelet-rop-raise-evict-not-port", noun="wastehang", panel="kubelet metrics", needle="kubelet_up", lie_core="readOnlyPort leftover 0 plus auth so Grafana cadvisor scrape is empty", false_lead="kubelet eviction leftover", avoided="cAdvisor docker_only r582; prometheus-operator r671; PagerDuty orch; Opsgenie alias", knob=".readOnlyPort", old="readOnlyPort: 0", new="readOnlyPort: 10255", wrong_knob=".evictionHard.memory.available", wrong_old="memory.available: 1%", wrong_new="memory.available: 100Mi", wrong2_old="authentication.anonymous.enabled: false", wrong2_new="authentication.anonymous.enabled: true", prefix="kubelet"),
    dict(vendor="windows_exporter", ok_slug="winexp-collector-disable-leftover", bad_slug="winexp-col-raise-timeout-not-enable", noun="aogdesk", panel="windows exporter", needle="win_up", lie_core="collectors leftover enabled=cpu-only so Grafana service hang-aogdesk-svc is empty", false_lead="windows_exporter timeout leftover", avoided="node_exporter r582; leftover3 VM relabel; PagerDuty orch; Opsgenie alias", knob=".collectors.enabled", old="enabled: cpu", new="enabled: cpu,cs,logical_disk,net,os,service,system", wrong_knob=".scrape.timeout", wrong_old="timeout: 1ms", wrong_new="timeout: 10s", wrong2_old="telemetry.path: /debug", wrong2_new="telemetry.path: /metrics", prefix="winexp"),
    dict(vendor="systemd_exporter", ok_slug="systemdexp-unit-include-drop-leftover", bad_slug="sysexp-unit-raise-timeout-not-include", noun="planbd", panel="systemd exporter", needle="sysd_up", lie_core="unit-include leftover sandbox.service so Grafana is empty while systemctl still shows hang-planbd-svc", false_lead="systemd_exporter timeout leftover", avoided="journald unit drop r530; leftover3 Falco; PagerDuty orch; Opsgenie alias", knob=".systemd.unit-include", old="unit-include: sandbox.service", new="unit-include: hang-planbd-svc.service", wrong_knob=".web.timeout", wrong_old="timeout: 1ms", wrong_new="timeout: 10s", wrong2_old="systemd.enable-restarts: false", wrong2_new="systemd.enable-restarts: true", prefix="sysexp"),
    dict(vendor="ipmi_exporter", ok_slug="ipmiexp-module-drop-leftover", bad_slug="ipmiexp-mod-raise-timeout-not-module", noun="shiftho", panel="IPMI exporter", needle="ipmi_up", lie_core="modules leftover default collectors empty so Grafana is empty while ipmitool still sdr", false_lead="ipmi_exporter timeout leftover", avoided="snmp_exporter r584; leftover3 VM relabel; PagerDuty orch; Opsgenie alias", knob=".modules.default.collectors", old="collectors: []", new="collectors: [bmc, ipmi, dcmi, bmc-watchdog]", wrong_knob=".modules.default.timeout", wrong_old="timeout: 1ms", wrong_new="timeout: 10s", wrong2_old="privilege: USER", wrong2_new="privilege: ADMIN", prefix="ipmiexp"),
    dict(vendor="smartctl_exporter", ok_slug="smartexp-device-exclude-leftover", bad_slug="smexp-dev-raise-int-not-exclude", noun="consum", panel="smartctl exporter", needle="smart_up", lie_core="smartctl.device_exclude leftover /dev/sd so Grafana is empty while smartctl still -a", false_lead="smartctl_exporter interval leftover", avoided="ipmi_exporter plant; leftover3 VM relabel; PagerDuty orch; Opsgenie alias", knob=".smartctl.device_exclude", old="device_exclude: /dev/sd", new="device_exclude: ", wrong_knob=".smartctl.interval", wrong_old="interval: 1h", wrong_new="interval: 60s", wrong2_old="smartctl.path: /bin/false", wrong2_new="smartctl.path: /usr/sbin/smartctl", prefix="smexp"),
    dict(vendor="bind_exporter", ok_slug="bindexp-stats-url-drop-leftover", bad_slug="bdexp-url-raise-timeout-not-stats", noun="toolcage", panel="bind exporter", needle="bind_up", lie_core="bind.stats-url leftover /json/v1 missing so Grafana is empty while named still answers", false_lead="bind_exporter timeout leftover", avoided="CoreDNS prometheus plant; leftover3 VM relabel; PagerDuty orch; Opsgenie alias", knob=".bind.stats-url", old="stats-url: http://localhost:0/json", new="stats-url: http://localhost:8053/json", wrong_knob=".bind.timeout", wrong_old="timeout: 1ms", wrong_new="timeout: 10s", wrong2_old="bind.pid-file: /tmp/empty", wrong2_new="bind.pid-file: /run/named.pid", prefix="bdexp"),
    dict(vendor="postfix_exporter", ok_slug="postfixexp-logfile-drop-leftover", bad_slug="pfexp-log-raise-showq-not-file", noun="calcage", panel="postfix exporter", needle="pf_up", lie_core="postfix.logfile leftover /dev/null so Grafana is empty while mailq still has hang-calcage-svc", false_lead="postfix_exporter showq leftover", avoided="systemd_exporter plant; leftover3 VM relabel; PagerDuty orch; Opsgenie alias", knob=".postfix.logfile", old="logfile: /dev/null", new="logfile: /var/log/mail.log", wrong_knob=".postfix.showq_path", wrong_old="showq_path: /bin/false", wrong_new="showq_path: /usr/sbin/postqueue", wrong2_old="systemd.enable: false", wrong2_new="systemd.enable: true", prefix="pfexp"),
    dict(vendor="apache_exporter", ok_slug="apacheexp-scrape-uri-drop-leftover", bad_slug="apexp-uri-raise-timeout-not-uri", noun="quarcage2", panel="apache exporter", needle="httpd_up", lie_core="scrape_uri leftover /server-status-missing so Grafana is empty while httpd still 200", false_lead="apache_exporter timeout leftover", avoided="nginx exporter plant; leftover3 VM relabel; PagerDuty orch; Opsgenie alias", knob=".scrape_uri", old="scrape_uri: http://localhost/missing", new="scrape_uri: http://localhost/server-status?auto", wrong_knob=".timeout", wrong_old="timeout: 1ms", wrong_new="timeout: 5s", wrong2_old="insecure: true", wrong2_new="insecure: false", prefix="apexp"),
    dict(vendor="memcached_exporter", ok_slug="memcacheexp-addr-drop-leftover", bad_slug="mcexp-addr-raise-timeout-not-addr", noun="bondstore", panel="memcached exporter", needle="mc_up", lie_core="memcached.address leftover localhost:0 so Grafana is empty while memcached still 11211", false_lead="memcached_exporter timeout leftover", avoided="redis_exporter plant; leftover3 VM relabel; PagerDuty orch; Opsgenie alias", knob=".memcached.address", old="address: localhost:0", new="address: memcached:11211", wrong_knob=".memcached.timeout", wrong_old="timeout: 1ms", wrong_new="timeout: 5s", wrong2_old="web.listen-address: 127.0.0.1:9150", wrong2_new="web.listen-address: 0.0.0.0:9150", prefix="mcexp"),
    dict(vendor="varnish_exporter", ok_slug="varnishexp-n-arg-drop-leftover", bad_slug="vnexp-n-raise-timeout-not-name", noun="rotarack", panel="varnish exporter", needle="varnish_up", lie_core="varnish.n leftover sandbox so Grafana is empty while varnishstat still 200", false_lead="varnish_exporter timeout leftover", avoided="haproxy_exporter plant; leftover3 VM relabel; PagerDuty orch; Opsgenie alias", knob=".varnish.n", old="n: sandbox", new="n: hang-rotarack-svc", wrong_knob=".varnish.timeout", wrong_old="timeout: 1ms", wrong_new="timeout: 5s", wrong2_old="varnish.host: sandbox", wrong2_new="varnish.host: hangar", prefix="vnexp"),
    dict(vendor="Traefik", ok_slug="traefik-metrics-entry-drop-leftover", bad_slug="traefik-ent-raise-ping-not-entry", noun="consbin", panel="Traefik metrics", needle="tr_up", lie_core="metrics.prometheus.entryPoint leftover none so Grafana is empty while Traefik still 80", false_lead="Traefik ping leftover", avoided="haproxy_exporter plant; leftover3 VM relabel; PagerDuty orch; Opsgenie alias", knob=".metrics.prometheus.entryPoint", old="entryPoint: none", new="entryPoint: metrics", wrong_knob=".ping.entryPoint", wrong_old="entryPoint: none", wrong_new="entryPoint: ping", wrong2_old="log.level: ERROR", wrong2_new="log.level: INFO", prefix="traefik"),
    dict(vendor="Contour", ok_slug="contour-metrics-addr-drop-leftover", bad_slug="contour-addr-raise-debug-not-bind", noun="igloorep", panel="Contour metrics", needle="contour_up", lie_core="metrics.address leftover 127.0.0.1 so Grafana scrape is empty while HTTPProxy still 200", false_lead="Contour debug leftover", avoided="Traefik metrics plant; prometheus-operator r671; PagerDuty orch; Opsgenie alias", knob=".metrics.address", old="address: 127.0.0.1", new="address: 0.0.0.0", wrong_knob=".debug.address", wrong_old="address: 127.0.0.1", wrong_new="address: 0.0.0.0", wrong2_old="httpport: 0", wrong2_new="httpport: 8080", prefix="contour"),
    dict(vendor="Calico", ok_slug="calico-felix-prometheus-off-leftover", bad_slug="calico-prom-raise-typha-not-felix", noun="firebot", panel="Calico Felix", needle="felix_up", lie_core="Felix leftover PrometheusMetricsEnabled=false so Grafana is empty while policy still works", false_lead="Calico Typha leftover", avoided="leftover3 Hubble clones; leftover3 eBPF map; PagerDuty orch; Opsgenie alias", knob=".FelixConfiguration.PrometheusMetricsEnabled", old="PrometheusMetricsEnabled: false", new="PrometheusMetricsEnabled: true", wrong_knob=".typha.enabled", wrong_old="enabled: false", wrong_new="enabled: true", wrong2_old="bpfEnabled: false", wrong2_new="bpfEnabled: true", prefix="calico"),
    dict(vendor="MetalLB", ok_slug="metallb-speaker-metrics-drop-leftover", bad_slug="mlb-spk-raise-bgp-not-metrics", noun="hydrocyl", panel="MetalLB speaker", needle="mlb_up", lie_core="speaker leftover --metrics-bind-address 127.0.0.1 so Grafana is empty while L2 still announces", false_lead="MetalLB BGP leftover", avoided="Calico Felix plant; leftover3 VM relabel; PagerDuty orch; Opsgenie alias", knob=".speaker.metricsBindAddress", old="metricsBindAddress: 127.0.0.1:7472", new="metricsBindAddress: 0.0.0.0:7472", wrong_knob=".bgpStartupHoldTime", wrong_old="bgpStartupHoldTime: 24h", wrong_new="bgpStartupHoldTime: 30s", wrong2_old="frr.enabled: false", wrong2_new="frr.enabled: true", prefix="mlb"),
    dict(vendor="cert-manager", ok_slug="certman-metrics-listen-drop-leftover", bad_slug="cman-listen-raise-renew-not-bind", noun="vestpack", panel="cert-manager metrics", needle="cm_up", lie_core="metrics leftover --metrics-listen-address 127.0.0.1 so Grafana is empty while Certificate still Ready", false_lead="cert-manager renew leftover", avoided="prometheus-operator r671; leftover3 VM relabel; PagerDuty orch; Opsgenie alias", knob=".metrics.listen-address", old="listen-address: 127.0.0.1:9402", new="listen-address: 0.0.0.0:9402", wrong_knob=".renewBefore", wrong_old="renewBefore: 1h", wrong_new="renewBefore: 360h", wrong2_old="enable-certificate-owner-ref: false", wrong2_new="enable-certificate-owner-ref: true", prefix="cman"),
    dict(vendor="external-dns", ok_slug="extdns-txt-owner-drop-leftover", bad_slug="edns-own-raise-int-not-owner", noun="maskpack", panel="external-dns", needle="edns_up", lie_core="txt-owner-id leftover sandbox so Grafana is the wrong dashboard while Route53 still has hang-maskpack-svc", false_lead="external-dns interval leftover", avoided="CoreDNS prometheus plant; leftover3 VM relabel; PagerDuty orch; Opsgenie alias", knob=".txt-owner-id", old="txt-owner-id: sandbox", new="txt-owner-id: hang-maskpack-svc", wrong_knob=".interval", wrong_old="interval: 24h", wrong_new="interval: 1m", wrong2_old="policy: upsert-only", wrong2_new="policy: sync", prefix="edns"),
    dict(vendor="ingress-nginx", ok_slug="ingnginx-metrics-bind-drop-leftover", bad_slug="ingx-bind-raise-probe-not-addr", noun="megapack", panel="ingress-nginx", needle="ingx_up", lie_core="controller leftover metrics-bind-address 127.0.0.1 so Grafana is empty while Ingress still 200", false_lead="ingress-nginx probe leftover", avoided="Traefik metrics plant; prometheus-operator r671; PagerDuty orch; Opsgenie alias", knob=".controller.metrics.bind-address", old="bind-address: 127.0.0.1", new="bind-address: 0.0.0.0", wrong_knob=".controller.healthzPort", wrong_old="healthzPort: 0", wrong_new="healthzPort: 10254", wrong2_old="enable-metrics: false", wrong2_new="enable-metrics: true", prefix="ingx"),
    dict(vendor="Argo CD", ok_slug="argocd-metrics-disable-leftover", bad_slug="argocd-met-raise-repo-not-enable", noun="axepack", panel="Argo CD metrics", needle="argo_up", lie_core="server leftover --disable-metrics so Grafana is empty while Application still Synced", false_lead="Argo CD repo leftover", avoided="prometheus-operator r671; leftover3 VM relabel; PagerDuty orch; Opsgenie alias", knob=".server.disableMetrics", old="disableMetrics: true", new="disableMetrics: false", wrong_knob=".repoServer.replicas", wrong_old="replicas: 0", wrong_new="replicas: 2", wrong2_old="application.instanceLabelKey: sandbox", wrong2_new="application.instanceLabelKey: hangar", prefix="argocd"),
    dict(vendor="Argo Workflows", ok_slug="argowf-metrics-disable-leftover", bad_slug="argowf-met-raise-ttl-not-enable", noun="aidpack", panel="Argo Workflows", needle="wf_up", lie_core="controller leftover metricsConfig.enabled=false so Grafana is empty while Workflow still Succeeded", false_lead="Argo Workflows TTL leftover", avoided="Argo CD metrics plant; leftover3 VM relabel; PagerDuty orch; Opsgenie alias", knob=".metricsConfig.enabled", old="enabled: false", new="enabled: true", wrong_knob=".ttlStrategy.secondsAfterCompletion", wrong_old="secondsAfterCompletion: 1", wrong_new="secondsAfterCompletion: 86400", wrong2_old="parallelism: 0", wrong2_new="parallelism: 20", prefix="argowf"),
    dict(vendor="Flux", ok_slug="flux-source-metrics-drop-leftover", bad_slug="flux-src-raise-int-not-metrics", noun="aedpack", panel="Flux source", needle="flux_up", lie_core="source-controller leftover --metrics-addr 127.0.0.1 so Grafana is empty while GitRepository still Ready", false_lead="Flux interval leftover", avoided="Argo CD metrics plant; leftover3 VM relabel; PagerDuty orch; Opsgenie alias", knob=".metrics-addr", old="metrics-addr: 127.0.0.1:8080", new="metrics-addr: 0.0.0.0:8080", wrong_knob=".interval", wrong_old="interval: 24h", wrong_new="interval: 1m", wrong2_old="concurrent: 1", wrong2_new="concurrent: 10", prefix="flux"),
    dict(vendor="Tekton", ok_slug="tekton-metrics-backend-none-leftover", bad_slug="tekton-be-raise-pruner-not-backend", noun="pbepack", panel="Tekton metrics", needle="tekton_up", lie_core="config-observability leftover metrics.backend-destination=none so Grafana is empty while TaskRun still 200", false_lead="Tekton pruner leftover", avoided="Argo Workflows metrics; leftover3 VM relabel; PagerDuty orch; Opsgenie alias", knob=".metrics.backend-destination", old="backend-destination: none", new="backend-destination: prometheus", wrong_knob=".pruner.keep", wrong_old="keep: 0", wrong_new="keep: 100", wrong2_old="running-in-environment: sandbox", wrong2_new="running-in-environment: hangar", prefix="tekton"),
    dict(vendor="Harbor", ok_slug="harbor-metrics-disable-leftover", bad_slug="harbor-met-raise-quota-not-enable", noun="torchpack", panel="Harbor metrics", needle="harbor_up", lie_core="metric leftover enabled=false so Grafana is empty while /v2/ still 200", false_lead="Harbor quota leftover", avoided="leftover3 OpenSearch blocks; leftover3 VM relabel; PagerDuty orch; Opsgenie alias", knob=".metric.enabled", old="enabled: false", new="enabled: true", wrong_knob=".quota.default.storage", wrong_old="storage: 1", wrong_new="storage: -1", wrong2_old="internalTLS.enabled: false", wrong2_new="internalTLS.enabled: true", prefix="harbor"),
    dict(vendor="Artifactory", ok_slug="artifactory-metrics-token-drop-leftover", bad_slug="arty-tok-raise-ha-not-token", noun="calpress2", panel="Artifactory metrics", needle="arty_up", lie_core="metrics leftover token=sandbox so Grafana is the wrong dashboard while /artifactory still 200", false_lead="Artifactory HA leftover", avoided="Harbor metrics plant; leftover3 VM relabel; PagerDuty orch; Opsgenie alias", knob=".metrics.token", old="token: sandbox", new="token: hang-calpress2-svc", wrong_knob=".ha.enabled", wrong_old="enabled: false", wrong_new="enabled: true", wrong2_old="database.type: derby", wrong2_new="database.type: postgresql", prefix="arty"),
    dict(vendor="Jenkins", ok_slug="jenkins-metrics-plugin-off-leftover", bad_slug="jenkins-met-raise-exec-not-plugin", noun="torqpress2", panel="Jenkins metrics", needle="jk_up", lie_core="prometheus plugin leftover disabled so Grafana is empty while the job still built", false_lead="Jenkins executors leftover", avoided="Tekton metrics plant; leftover3 VM relabel; PagerDuty orch; Opsgenie alias", knob=".prometheus.enabled", old="enabled: false", new="enabled: true", wrong_knob=".numExecutors", wrong_old="numExecutors: 0", wrong_new="numExecutors: 4", wrong2_old="mode: EXCLUSIVE", wrong2_new="mode: NORMAL", prefix="jenkins"),
    dict(vendor="GitLab Runner", ok_slug="gitlabrunner-metrics-listen-drop-leftover", bad_slug="glr-listen-raise-conc-not-addr", noun="presslab2", panel="GitLab Runner", needle="glr_up", lie_core="listen_address leftover empty so Grafana is empty while jobs still run", false_lead="GitLab Runner concurrency leftover", avoided="Jenkins metrics plant; leftover3 VM relabel; PagerDuty orch; Opsgenie alias", knob=".listen_address", old="listen_address: ", new="listen_address: 0.0.0.0:9252", wrong_knob=".concurrent", wrong_old="concurrent: 0", wrong_new="concurrent: 10", wrong2_old="check_interval: 3600", wrong2_new="check_interval: 3", prefix="glr"),
    dict(vendor="Buildkite agent", ok_slug="buildkite-metrics-disable-leftover", bad_slug="bkite-met-raise-spawn-not-enable", noun="templab2", panel="Buildkite agent", needle="bk_up", lie_core="metrics leftover disable-metrics so Grafana is empty while builds still run", false_lead="Buildkite spawn leftover", avoided="GitLab Runner plant; leftover3 VM relabel; PagerDuty orch; Opsgenie alias", knob=".disable-metrics", old="disable-metrics: true", new="disable-metrics: false", wrong_knob=".spawn", wrong_old="spawn: 0", wrong_new="spawn: 4", wrong2_old="tags: sandbox", wrong2_new="tags: hangar", prefix="bkite"),
    dict(vendor="CircleCI runner", ok_slug="circleci-runner-task-filter-drop-leftover", bad_slug="cci-task-raise-conc-not-filter", noun="eleclab2", panel="CircleCI runner", needle="cci_up", lie_core="task leftover filter=sandbox so Grafana is empty while the runner still idle", false_lead="CircleCI concurrency leftover", avoided="Buildkite metrics plant; leftover3 VM relabel; PagerDuty orch; Opsgenie alias", knob=".runner.task_filter", old="task_filter: sandbox", new="task_filter: hang-eleclab2-svc", wrong_knob=".runner.max_concurrent", wrong_old="max_concurrent: 0", wrong_new="max_concurrent: 4", wrong2_old="resource_class: sandbox", wrong2_new="resource_class: hangar", prefix="cci"),
    dict(vendor="Concourse", ok_slug="concourse-prometheus-bind-drop-leftover", bad_slug="conc-bind-raise-workers-not-addr", noun="avilab2", panel="Concourse metrics", needle="conc_up", lie_core="prometheus leftover bind-ip 127.0.0.1 so Grafana is empty while the pipeline still green", false_lead="Concourse workers leftover", avoided="Tekton metrics plant; leftover3 VM relabel; PagerDuty orch; Opsgenie alias", knob=".prometheus.bind-ip", old="bind-ip: 127.0.0.1", new="bind-ip: 0.0.0.0", wrong_knob=".tsa.garden-request-timeout", wrong_old="garden-request-timeout: 1ms", wrong_new="garden-request-timeout: 5m", wrong2_old="worker.healthcheck-timeout: 1ms", wrong2_new="worker.healthcheck-timeout: 5s", prefix="conc"),
    dict(vendor="Drone", ok_slug="drone-prometheus-disable-leftover", bad_slug="drone-prom-raise-rpc-not-enable", noun="swload2", panel="Drone metrics", needle="drone_up", lie_core="DRONE_PROMETHEUS leftover false so Grafana is empty while builds still 200", false_lead="Drone RPC leftover", avoided="Concourse prometheus plant; leftover3 VM relabel; PagerDuty orch; Opsgenie alias", knob=".DRONE_PROMETHEUS", old="DRONE_PROMETHEUS: false", new="DRONE_PROMETHEUS: true", wrong_knob=".DRONE_RPC_SECRET", wrong_old="DRONE_RPC_SECRET: sandbox", wrong_new="DRONE_RPC_SECRET: hangar", wrong2_old="DRONE_SERVER_HOST: sandbox", wrong2_new="DRONE_SERVER_HOST: hangar.local", prefix="drone"),
    dict(vendor="Woodpecker", ok_slug="woodpecker-metrics-token-drop-leftover", bad_slug="wpeck-tok-raise-agent-not-token", noun="pinprog2", panel="Woodpecker metrics", needle="wp_up", lie_core="WOODPECKER_PROMETHEUS_AUTH_TOKEN leftover sandbox so Grafana is the wrong dashboard", false_lead="Woodpecker agent leftover", avoided="Drone prometheus plant; leftover3 VM relabel; PagerDuty orch; Opsgenie alias", knob=".WOODPECKER_PROMETHEUS_AUTH_TOKEN", old="WOODPECKER_PROMETHEUS_AUTH_TOKEN: sandbox", new="WOODPECKER_PROMETHEUS_AUTH_TOKEN: hang-pinprog2-svc", wrong_knob=".WOODPECKER_MAX_WORKFLOWS", wrong_old="WOODPECKER_MAX_WORKFLOWS: 0", wrong_new="WOODPECKER_MAX_WORKFLOWS: 4", wrong2_old="WOODPECKER_FILTER_LABELS: sandbox", wrong2_new="WOODPECKER_FILTER_LABELS: hangar", prefix="wpeck"),
    dict(vendor="Nexus", ok_slug="nexus-metrics-security-drop-leftover", bad_slug="nexus-sec-raise-blob-not-metrics", noun="magload2", panel="Nexus metrics", needle="nx_up", lie_core="metrics leftover nexus.scripts.allowCreation false plus /service/metrics dropped so Grafana is empty", false_lead="Nexus blob leftover", avoided="Harbor metrics plant; leftover3 VM relabel; PagerDuty orch; Opsgenie alias", knob=".nexus.metrics.enabled", old="enabled: false", new="enabled: true", wrong_knob=".blobstore.file.path", wrong_old="path: /tmp", wrong_new="path: /nexus-data", wrong2_old="admin.password: sandbox", wrong2_new="admin.password: hangar", prefix="nexus"),
    dict(vendor="GHCR", ok_slug="ghcr-package-visibility-drop-leftover", bad_slug="ghcr-vis-raise-retain-not-vis", noun="usbload2", panel="GHCR packages", needle="ghcr_up", lie_core="visibility leftover private plus org filter sandbox so Grafana is the wrong dashboard", false_lead="GHCR retain leftover", avoided="Harbor metrics plant; leftover3 VM relabel; PagerDuty orch; Opsgenie alias", knob=".packages.visibility", old="visibility: internal-sandbox", new="visibility: hang-usbload2-svc", wrong_knob=".packages.retention", wrong_old="retention: 1", wrong_new="retention: 90", wrong2_old="org: sandbox", wrong2_new="org: hangar", prefix="ghcr"),
    dict(vendor="ECR", ok_slug="ecr-lifecycle-expire-drop-leftover", bad_slug="ecr-life-raise-scan-not-policy", noun="pmdt2", panel="ECR images", needle="ecr_up", lie_core="lifecycle leftover expire countNumber=0 so Grafana is empty while PutImage still 200", false_lead="ECR scan leftover", avoided="GHCR visibility plant; leftover3 VM relabel; PagerDuty orch; Opsgenie alias", knob=".lifecycle.expire.countNumber", old="countNumber: 0", new="countNumber: 30", wrong_knob=".imageScanning.enabled", wrong_old="enabled: false", wrong_new="enabled: true", wrong2_old="encryption: AES256", wrong2_new="encryption: KMS", prefix="ecr"),
    dict(vendor="GCR", ok_slug="gcr-cleanup-policy-drop-leftover", bad_slug="gcr-clean-raise-scan-not-policy", noun="ammview2", panel="GCR images", needle="gcr_up", lie_core="cleanup leftover condition=always so Grafana is empty while docker push still 200", false_lead="GCR scan leftover", avoided="ECR lifecycle plant; leftover3 VM relabel; PagerDuty orch; Opsgenie alias", knob=".cleanup.condition", old="condition: always", new="condition: older_than_30d", wrong_knob=".vulnerabilityScanning", wrong_old="vulnerabilityScanning: false", wrong_new="vulnerabilityScanning: true", wrong2_old="location: us", wrong2_new="location: eu", prefix="gcr"),
    dict(vendor="ACR", ok_slug="acr-retention-policy-drop-leftover", bad_slug="acr-ret-raise-scan-not-days", noun="ipcview2", panel="ACR images", needle="acr_up", lie_core="retention leftover days=0 so Grafana is empty while docker push still 200", false_lead="ACR scan leftover", avoided="GCR cleanup plant; leftover3 VM relabel; PagerDuty orch; Opsgenie alias", knob=".retention.days", old="days: 0", new="days: 30", wrong_knob=".trustPolicy.status", wrong_old="status: disabled", wrong_new="status: enabled", wrong2_old="sku: Basic", wrong2_new="sku: Premium", prefix="acr"),
    dict(vendor="Quay", ok_slug="quay-prometheus-disable-leftover", bad_slug="quay-prom-raise-repomirror-not-enable", noun="taskcard2", panel="Quay metrics", needle="quay_up", lie_core="FEATURE leftover PROMETHEUS=false so Grafana is empty while /v2/ still 200", false_lead="Quay repo mirror leftover", avoided="Harbor metrics plant; leftover3 VM relabel; PagerDuty orch; Opsgenie alias", knob=".FEATURE_PROMETHEUS", old="FEATURE_PROMETHEUS: false", new="FEATURE_PROMETHEUS: true", wrong_knob=".FEATURE_REPO_MIRROR", wrong_old="FEATURE_REPO_MIRROR: false", wrong_new="FEATURE_REPO_MIRROR: true", wrong2_old="SERVER_HOSTNAME: sandbox", wrong2_new="SERVER_HOSTNAME: hangar.local", prefix="quay"),
    dict(vendor="ChartMuseum", ok_slug="chartmuseum-index-disable-leftover", bad_slug="cmuse-idx-raise-depth-not-index", noun="jobprint2", panel="ChartMuseum", needle="cm_up", lie_core="DISABLE leftover INDEX=true so Grafana is empty while helm push still 201", false_lead="ChartMuseum depth leftover", avoided="Harbor metrics plant; leftover3 VM relabel; PagerDuty orch; Opsgenie alias", knob=".DISABLE_API", old="DISABLE_API: true", new="DISABLE_API: false", wrong_knob=".DEPTH", wrong_old="DEPTH: 0", wrong_new="DEPTH: 2", wrong2_old="STORAGE: local", wrong2_new="STORAGE: amazon", prefix="cmuse"),
    dict(vendor="Spinnaker", ok_slug="spinnaker-metric-store-none-leftover", bad_slug="spin-store-raise-echo-not-store", noun="toolcrib2", panel="Spinnaker metrics", needle="spin_up", lie_core="metricStores leftover [] so Grafana is empty while the pipeline still SUCCEEDED", false_lead="Spinnaker echo leftover", avoided="Tekton metrics plant; leftover3 VM relabel; PagerDuty orch; Opsgenie alias", knob=".metricStores", old="metricStores: []", new="metricStores: [prometheus]", wrong_knob=".echo.enabled", wrong_old="enabled: false", wrong_new="enabled: true", wrong2_old="halyard.timezone: UTC", wrong2_new="halyard.timezone: America/New_York", prefix="spin"),
    dict(vendor="TeamCity", ok_slug="teamcity-diagnostics-off-leftover", bad_slug="tcity-diag-raise-agent-not-enable", noun="caltool2", panel="TeamCity metrics", needle="tc_up", lie_core="diagnostics leftover teamcity.metrics=false so Grafana is empty while the build still SUCCESS", false_lead="TeamCity agent leftover", avoided="Jenkins metrics plant; leftover3 VM relabel; PagerDuty orch; Opsgenie alias", knob=".teamcity.metrics", old="teamcity.metrics: false", new="teamcity.metrics: true", wrong_knob=".agents.max", wrong_old="max: 0", wrong_new="max: 8", wrong2_old="server.url: http://sandbox", wrong2_new="server.url: http://hangar", prefix="tcity"),
    dict(vendor="Bamboo", ok_slug="bamboo-jmx-disable-leftover", bad_slug="bamboo-jmx-raise-agent-not-enable", noun="quarcell2", panel="Bamboo JMX", needle="bamboo_up", lie_core="jmx leftover disabled so Grafana is empty while the plan still SUCCESS", false_lead="Bamboo agent leftover", avoided="TeamCity diagnostics plant; leftover3 VM relabel; PagerDuty orch; Opsgenie alias", knob=".jmx.enabled", old="enabled: false", new="enabled: true", wrong_knob=".agents.remote.max", wrong_old="max: 0", wrong_new="max: 8", wrong2_old="broker.url: sandbox", wrong2_new="broker.url: hangar", prefix="bamboo"),
    dict(vendor="Gateway API", ok_slug="gwapi-status-filter-drop-leftover", bad_slug="gwapi-st-raise-class-not-filter", noun="bondcell2", panel="Gateway API", needle="gw_up", lie_core="status leftover Accepted=False filter so Grafana is empty while HTTPRoute still 200", false_lead="Gateway API class leftover", avoided="ingress-nginx metrics plant; leftover3 VM relabel; PagerDuty orch; Opsgenie alias", knob=".status.accepted", old="accepted: False", new="accepted: True", wrong_knob=".gatewayClassName", wrong_old="gatewayClassName: sandbox", wrong_new="gatewayClassName: hangar", wrong2_old="listeners.port: 0", wrong2_new="listeners.port: 80", prefix="gwapi"),
    dict(vendor="kube-vip", ok_slug="kubevip-metrics-path-drop-leftover", bad_slug="kvip-path-raise-arp-not-path", noun="rotcell2", panel="kube-vip", needle="kvip_up", lie_core="prometheusHTTP leftover /missing so Grafana is empty while VIP still announced", false_lead="kube-vip ARP leftover", avoided="MetalLB speaker plant; leftover3 VM relabel; PagerDuty orch; Opsgenie alias", knob=".prometheusHTTP", old="prometheusHTTP: /missing", new="prometheusHTTP: /metrics", wrong_knob=".vip_arp", wrong_old="vip_arp: false", wrong_new="vip_arp: true", wrong2_old="svc_election: false", wrong2_new="svc_election: true", prefix="kvip"),
    dict(vendor="Flannel", ok_slug="flannel-cni-metrics-off-leftover", bad_slug="flannel-met-raise-backend-not-enable", noun="conscell2", panel="Flannel", needle="flan_up", lie_core="cni leftover metricsPort=0 so Grafana is empty while pods still have IPs", false_lead="Flannel backend leftover", avoided="Calico Felix plant; leftover3 VM relabel; PagerDuty orch; Opsgenie alias", knob=".metricsPort", old="metricsPort: 0", new="metricsPort: 9091", wrong_knob=".Backend.Type", wrong_old="Type: alloc", wrong_new="Type: vxlan", wrong2_old="hairpinMode: false", wrong2_new="hairpinMode: true", prefix="flannel"),
    dict(vendor="Weave Net", ok_slug="weave-metrics-addr-drop-leftover", bad_slug="weave-addr-raise-npc-not-bind", noun="aogcell2", panel="Weave Net", needle="weave_up", lie_core="metrics leftover --metrics-addr 127.0.0.1 so Grafana is empty while weave still 6783", false_lead="Weave NPC leftover", avoided="Flannel metrics plant; leftover3 VM relabel; PagerDuty orch; Opsgenie alias", knob=".metrics-addr", old="metrics-addr: 127.0.0.1:6782", new="metrics-addr: 0.0.0.0:6782", wrong_knob=".npc", wrong_old="npc: off", wrong_new="npc: on", wrong2_old="encryption: off", wrong2_new="encryption: on", prefix="weave"),
]


assert len(SPECS) == 58, len(SPECS)
for i, spec in enumerate(SPECS):
    _l6(683 + i, **spec)
