"""Observability leftover7 plants r741+. BAN r515 Rootly, r384 OTel forward, PagerDuty orch, Opsgenie alias, r163-r740 clones."""

from mill_plants_t import _leftover_pair

MORE = []
ROUND_PAIRS = {}


def _emit(round_n, **kwargs):
    dest = []
    _leftover_pair(n=str(round_n), dest=dest, **kwargs)
    MORE.extend(dest)
    ROUND_PAIRS[round_n] = dest[0]


def _l7(n, **kw):
    vendor, noun, prefix = kw["vendor"], kw["noun"], kw["prefix"]
    ok_svc, bad_svc = f"pad-{noun}-svc", f"bay2-{noun}-svc"
    tag = noun.replace("-", "")[:8]
    vtag = prefix.replace("-", "")[:5]
    ok_dash, bad_dash = f"{tag}-{vtag}-{n}", f"y{tag[:7]}-{vtag}-fl"
    lie_core = kw["lie_core"]
    _emit(
        n,
        kind="grafana",
        ok_slug=kw["ok_slug"],
        bad_slug=kw["bad_slug"],
        ok_svc=ok_svc,
        bad_svc=bad_svc,
        ok_dash=ok_dash,
        bad_dash=bad_dash,
        panel=kw["panel"],
        metric="",
        needle=kw["needle"],
        lie=f"{vendor} leftover {lie_core} so Grafana dashboard {ok_dash} is empty while the source still 202",
        bad_lie=f"{kw['false_lead']} does not restore leftover leftover leftover leftover leftover leftover leftover {lie_core}",
        false_lead=kw["false_lead"],
        avoided=kw["avoided"],
        this_is=f"{vendor} leftover leftover leftover leftover leftover leftover leftover {lie_core}",
        ticket=f"OBS-{8000 + (n - 741)}",
        knob=kw["knob"],
        old=kw["old"],
        new=kw["new"],
        wrong_knob=kw["wrong_knob"],
        wrong_old=kw["wrong_old"],
        wrong_new=kw["wrong_new"],
        wrong2_old=kw["wrong2_old"],
        wrong2_new=kw["wrong2_new"],
        reload="grafana",
        config_path=f"{prefix}/{tag}-false.yaml",
        lie_path=f"{prefix}/{tag}-lie.yaml",
        bad_config=f"{prefix}/y{tag[:7]}-false.yaml",
        bad_lie_path=f"{prefix}/y{tag[:7]}-lie.yaml",
    )


BAN = "PagerDuty orch; Opsgenie alias; r515 Rootly urgency; r384 OTel forward"
SPECS = [
    dict(vendor="Karpenter", ok_slug="karpenter-metrics-bind-drop-leftover", bad_slug="karp-bind-raise-ttl-not-addr", noun="n2pad", panel="Karpenter metrics", needle="karp_up", lie_core="metrics leftover --metrics-bind-address 127.0.0.1 so Grafana is empty while NodeClaims still Ready", false_lead="Karpenter TTL leftover", avoided=BAN+"; cluster-autoscaler later", knob=".metrics-bind-address", old="metrics-bind-address: 127.0.0.1:8080", new="metrics-bind-address: 0.0.0.0:8080", wrong_knob=".ttlSecondsAfterEmpty", wrong_old="ttlSecondsAfterEmpty: 1", wrong_new="ttlSecondsAfterEmpty: 30", wrong2_old="consolidationPolicy: WhenEmpty", wrong2_new="consolidationPolicy: WhenEmptyOrUnderutilized", prefix="karp"),
    dict(vendor="Descheduler", ok_slug="desched-metrics-addr-drop-leftover", bad_slug="desch-addr-raise-int-not-bind", noun="oxypad", panel="Descheduler metrics", needle="desch_up", lie_core="metrics leftover --bind-address 127.0.0.1 so Grafana is empty while evictions still happen", false_lead="Descheduler interval leftover", avoided=BAN+"; Karpenter metrics plant", knob=".bind-address", old="bind-address: 127.0.0.1", new="bind-address: 0.0.0.0", wrong_knob=".deschedulingInterval", wrong_old="deschedulingInterval: 24h", wrong_new="deschedulingInterval: 5m", wrong2_old="dryRun: true", wrong2_new="dryRun: false", prefix="desch"),
    dict(vendor="node-problem-detector", ok_slug="npd-prometheus-addr-drop-leftover", bad_slug="npd-addr-raise-period-not-bind", noun="hydpad", panel="NPD metrics", needle="npd_up", lie_core="prometheus leftover --prometheus-address 127.0.0.1 so Grafana is empty while NodeCondition still Ready", false_lead="NPD period leftover", avoided=BAN+"; kubelet metrics plant", knob=".prometheus-address", old="prometheus-address: 127.0.0.1:20257", new="prometheus-address: 0.0.0.0:20257", wrong_knob=".system-log-monitor.period", wrong_old="period: 1h", wrong_new="period: 10s", wrong2_old="enable-k8s-exporter: false", wrong2_new="enable-k8s-exporter: true", prefix="npd"),
    dict(vendor="HPA", ok_slug="hpa-metrics-selector-drop-leftover", bad_slug="hpa-sel-raise-min-not-selector", noun="idgpad", panel="HPA replicas", needle="hpa_up", lie_core="metric leftover selector never-matches pad-idgpad-svc so Grafana is empty while /metrics still 200", false_lead="HPA minReplicas leftover", avoided=BAN+"; KEDA pause plant; prometheus-adapter r580", knob=".metrics.pods.selector", old="selector: {app: sandbox}", new="selector: {app: pad-idgpad-svc}", wrong_knob=".minReplicas", wrong_old="minReplicas: 0", wrong_new="minReplicas: 1", wrong2_old="maxReplicas: 1", wrong2_new="maxReplicas: 10", prefix="hpa"),
    dict(vendor="PDB", ok_slug="pdb-selector-drop-leftover", bad_slug="pdb-sel-raise-min-not-selector", noun="tenpad", panel="PDB disruptions", needle="pdb_up", lie_core="selector leftover matchLabels sandbox so Grafana is empty while the Deployment still Ready", false_lead="PDB minAvailable leftover", avoided=BAN+"; HPA selector plant", knob=".selector.matchLabels", old="matchLabels: {app: sandbox}", new="matchLabels: {app: pad-tenpad-svc}", wrong_knob=".minAvailable", wrong_old="minAvailable: 100%", wrong_new="minAvailable: 1", wrong2_old="unhealthyPodEvictionPolicy: AlwaysAllow", wrong2_new="unhealthyPodEvictionPolicy: IfHealthyBudget", prefix="pdb"),
    dict(vendor="Istio Gateway", ok_slug="istiogw-telemetry-off-leftover", bad_slug="istgw-tel-raise-sds-not-enable", noun="tqwpad", panel="Istio Gateway", needle="istgw_up", lie_core="telemetry leftover prometheus.disabled so Grafana is empty while the Gateway still 200", false_lead="Istio SDS leftover", avoided=BAN+"; leftover3 Istio/Hubble; Linkerd tap r592", knob=".telemetry.prometheus.disabled", old="disabled: true", new="disabled: false", wrong_knob=".sds.enabled", wrong_old="enabled: false", wrong_new="enabled: true", wrong2_old="pilot.traceSampling: 0", wrong2_new="pilot.traceSampling: 100", prefix="istgw"),
    dict(vendor="Consul Connect", ok_slug="consconnect-proxy-metrics-drop-leftover", bad_slug="cconn-met-raise-intent-not-proxy", noun="boropad", panel="Consul Connect", needle="cconn_up", lie_core="proxy leftover prometheus.addr 127.0.0.1 so Grafana is empty while Connect still mTLS", false_lead="Consul intentions leftover", avoided=BAN+"; Consul telemetry r590", knob=".proxy.prometheus.addr", old="addr: 127.0.0.1:20200", new="addr: 0.0.0.0:20200", wrong_knob=".intentions.default", wrong_old="default: deny", wrong_new="default: allow", wrong2_old="mesh_gateway.mode: none", wrong2_new="mesh_gateway.mode: local", prefix="cconn"),
    dict(vendor="Vault Agent", ok_slug="vaultagent-telemetry-off-leftover", bad_slug="vagnt-tel-raise-auth-not-enable", noun="ndtpad", panel="Vault Agent", needle="vagnt_up", lie_core="telemetry leftover disable_hostname plus prometheus retention 0 so Grafana is empty", false_lead="Vault Agent auth leftover", avoided=BAN+"; Vault audit r591", knob=".telemetry.prometheus_retention_time", old="prometheus_retention_time: 0", new="prometheus_retention_time: 24h", wrong_knob=".auto_auth.method", wrong_old="method: none", wrong_new="method: kubernetes", wrong2_old="cache.enabled: false", wrong2_new="cache.enabled: true", prefix="vagnt"),
    dict(vendor="External Secrets", ok_slug="eso-metrics-bind-drop-leftover", bad_slug="eso-bind-raise-int-not-addr", noun="mixpad", panel="ESO metrics", needle="eso_up", lie_core="metrics leftover --metrics-addr 127.0.0.1 so Grafana is empty while ExternalSecret still Synced", false_lead="ESO interval leftover", avoided=BAN+"; Vault Agent plant", knob=".metrics-addr", old="metrics-addr: 127.0.0.1:8080", new="metrics-addr: 0.0.0.0:8080", wrong_knob=".interval", wrong_old="interval: 24h", wrong_new="interval: 1m", wrong2_old="refreshInterval: 24h", wrong2_new="refreshInterval: 1h", prefix="eso"),
    dict(vendor="Sealed Secrets", ok_slug="sealedsecrets-metrics-off-leftover", bad_slug="ssec-met-raise-key-not-enable", noun="bathpad", panel="SealedSecrets", needle="ssec_up", lie_core="controller leftover --disable-metrics so Grafana is empty while SealedSecret still Unsealed", false_lead="Sealed Secrets key leftover", avoided=BAN+"; External Secrets plant", knob=".disable-metrics", old="disable-metrics: true", new="disable-metrics: false", wrong_knob=".key-renew-period", wrong_old="key-renew-period: 1h", wrong_new="key-renew-period: 720h", wrong2_old="update-status: false", wrong2_new="update-status: true", prefix="ssec"),
    dict(vendor="SOPS", ok_slug="sops-age-key-remap-leftover", bad_slug="sops-age-raise-kms-not-key", noun="presspad", panel="SOPS secrets", needle="sops_up", lie_core="creation_rules leftover age key sandbox so Grafana is the wrong dashboard while the file still decrypts elsewhere", false_lead="SOPS KMS leftover", avoided=BAN+"; Sealed Secrets plant", knob=".creation_rules.age", old="age: sandbox", new="age: pad-presspad-svc", wrong_knob=".creation_rules.kms", wrong_old="kms: arn:aws:kms:us-east-1:0:key/sandbox", wrong_new="kms: arn:aws:kms:us-east-1:1:key/hangar", wrong2_old="encrypted_regex: none", wrong2_new="encrypted_regex: ^(data|stringData)$", prefix="sops"),
    dict(vendor="trust-manager", ok_slug="trustman-metrics-bind-drop-leftover", bad_slug="tman-bind-raise-bundle-not-addr", noun="foampad", panel="trust-manager", needle="tman_up", lie_core="metrics leftover --metrics-bind-address 127.0.0.1 so Grafana is empty while Bundle still Ready", false_lead="trust-manager bundle leftover", avoided=BAN+"; cert-manager metrics r711", knob=".metrics-bind-address", old="metrics-bind-address: 127.0.0.1:9402", new="metrics-bind-address: 0.0.0.0:9402", wrong_knob=".defaultPackage.enabled", wrong_old="enabled: false", wrong_new="enabled: true", wrong2_old="secretTargets.enabled: false", wrong2_new="secretTargets.enabled: true", prefix="tman"),
    dict(vendor="Reflector", ok_slug="reflector-metrics-addr-drop-leftover", bad_slug="refl-addr-raise-sync-not-bind", noun="cartpad", panel="Reflector", needle="refl_up", lie_core="metrics leftover --metrics-address 127.0.0.1 so Grafana is empty while the Secret still mirrored", false_lead="Reflector sync leftover", avoided=BAN+"; External Secrets plant", knob=".metrics-address", old="metrics-address: 127.0.0.1:8080", new="metrics-address: 0.0.0.0:8080", wrong_knob=".sync-period", wrong_old="sync-period: 24h", wrong_new="sync-period: 10s", wrong2_old="reflection.allowed: false", wrong2_new="reflection.allowed: true", prefix="refl"),
    dict(vendor="Reloader", ok_slug="reloader-metrics-port-drop-leftover", bad_slug="reload-port-raise-watch-not-port", noun="headpad", panel="Reloader", needle="reload_up", lie_core="metrics leftover --metrics-port 0 so Grafana is empty while rollouts still happen", false_lead="Reloader watch leftover", avoided=BAN+"; Reflector metrics plant", knob=".metrics-port", old="metrics-port: 0", new="metrics-port: 9090", wrong_knob=".auto-reload-all", wrong_old="auto-reload-all: false", wrong_new="auto-reload-all: true", wrong2_old="reload-on-create: false", wrong2_new="reload-on-create: true", prefix="reload"),
    dict(vendor="Kustomize", ok_slug="kustomize-commonlabels-drop-leftover", bad_slug="kust-lbl-raise-ns-not-labels", noun="rtstpad", panel="Kustomize labels", needle="kust_up", lie_core="commonLabels leftover drop app so Grafana is the wrong dashboard while kubectl still applies", false_lead="Kustomize namespace leftover", avoided=BAN+"; r177 Alloy relabel", knob=".commonLabels", old="commonLabels: {}", new="commonLabels: {app: pad-rtstpad-svc}", wrong_knob=".namespace", wrong_old="namespace: sandbox", wrong_new="namespace: hangar", wrong2_old="namePrefix: sandbox-", wrong2_new="namePrefix: hangar-", prefix="kust"),
    dict(vendor="Helm", ok_slug="helm-hook-delete-drop-leftover", bad_slug="helm-hook-raise-wait-not-delete", noun="gcalpad", panel="Helm hooks", needle="helm_up", lie_core="hook leftover helm.sh/hook-delete-policy hook-succeeded plus weight -1 so Grafana test pod is empty", false_lead="Helm wait leftover", avoided=BAN+"; Flux source plant", knob=".hooks.delete-policy", old="delete-policy: hook-succeeded", new="delete-policy: before-hook-creation", wrong_knob=".atomic", wrong_old="atomic: true", wrong_new="atomic: false", wrong2_old="wait: false", wrong2_new="wait: true", prefix="helm"),
    dict(vendor="Jsonnet", ok_slug="jsonnet-extvar-drop-leftover", bad_slug="jnet-var-raise-tla-not-ext", noun="acalpad", panel="Jsonnet", needle="jnet_up", lie_core="extVar leftover service=sandbox so Grafana is the wrong dashboard while jsonnet still renders", false_lead="Jsonnet TLA leftover", avoided=BAN+"; Kustomize labels plant", knob=".extVar.service", old="service: sandbox", new="service: pad-acalpad-svc", wrong_knob=".tla.namespace", wrong_old="namespace: sandbox", wrong_new="namespace: hangar", wrong2_old="max_stack: 1", wrong2_new="max_stack: 500", prefix="jnet"),
    dict(vendor="CUE", ok_slug="cue-tag-filter-drop-leftover", bad_slug="cue-tag-raise-pkg-not-filter", noun="xcalpad", panel="CUE tags", needle="cue_up", lie_core="tag leftover @tag(service=sandbox) so Grafana is the wrong dashboard while cue eval still 0", false_lead="CUE package leftover", avoided=BAN+"; Jsonnet extVar plant", knob=".tags.service", old="service: sandbox", new="service: pad-xcalpad-svc", wrong_knob=".package", wrong_old="package: sandbox", wrong_new="package: hangar", wrong2_old="inject: none", wrong2_new="inject: env", prefix="cue"),
    dict(vendor="Crossplane", ok_slug="crossplane-metrics-bind-drop-leftover", bad_slug="xplane-bind-raise-sync-not-addr", noun="tcalpad", panel="Crossplane metrics", needle="xp_up", lie_core="metrics leftover --metrics-bind-address 127.0.0.1 so Grafana is empty while XR still Ready", false_lead="Crossplane sync leftover", avoided=BAN+"; External Secrets plant", knob=".metrics-bind-address", old="metrics-bind-address: 127.0.0.1:8080", new="metrics-bind-address: 0.0.0.0:8080", wrong_knob=".sync-interval", wrong_old="sync-interval: 24h", wrong_new="sync-interval: 1m", wrong2_old="enable-composition-webhook: false", wrong2_new="enable-composition-webhook: true", prefix="xplane"),
    dict(vendor="Pulumi", ok_slug="pulumi-stack-remap-wrong-dash-leftover", bad_slug="pulumi-stk-raise-esc-not-remap", noun="wcalpad", panel="Pulumi stacks", needle="pulumi_up", lie_core="stack leftover remaps pad-wcalpad-svc into sandbox so Grafana is the wrong dashboard", false_lead="Pulumi ESC leftover", avoided=BAN+"; Crossplane metrics plant", knob=".stack.remap", old="remap: sandbox", new="remap: pad-wcalpad-svc", wrong_knob=".esc.enabled", wrong_old="enabled: false", wrong_new="enabled: true", wrong2_old="backend: http://sandbox", wrong2_new="backend: s3://hangar", prefix="pulumi"),
    dict(vendor="Terraform", ok_slug="terraform-backend-remap-leftover", bad_slug="tf-be-raise-lock-not-remap", noun="ecalpad", panel="Terraform state", needle="tf_up", lie_core="backend leftover key=sandbox so Grafana is the wrong dashboard while apply still 0", false_lead="Terraform lock leftover", avoided=BAN+"; Pulumi stack plant", knob=".backend.key", old="key: sandbox", new="key: pad-ecalpad-svc", wrong_knob=".backend.dynamodb_table", wrong_old="dynamodb_table: none", wrong_new="dynamodb_table: hangar-lock", wrong2_old="workspace: default", wrong2_new="workspace: hangar", prefix="tf"),
    dict(vendor="Ansible", ok_slug="ansible-callback-metrics-off-leftover", bad_slug="ans-cb-raise-forks-not-enable", noun="cylpad", panel="Ansible metrics", needle="ans_up", lie_core="callback leftover prometheus disabled so Grafana is empty while the play still ok=1", false_lead="Ansible forks leftover", avoided=BAN+"; Terraform backend plant", knob=".callback_whitelist", old="callback_whitelist: []", new="callback_whitelist: [prometheus]", wrong_knob=".forks", wrong_old="forks: 1", wrong_new="forks: 20", wrong2_old="host_key_checking: True", wrong2_new="host_key_checking: False", prefix="ans"),
    dict(vendor="Salt", ok_slug="salt-stats-disable-leftover", bad_slug="salt-st-raise-job-not-enable", noun="cutpad", panel="Salt stats", needle="salt_up", lie_core="stats leftover enable_stats=False so Grafana is empty while the highstate still True", false_lead="Salt job leftover", avoided=BAN+"; Ansible callback plant", knob=".enable_stats", old="enable_stats: False", new="enable_stats: True", wrong_knob=".keep_jobs", wrong_old="keep_jobs: 1", wrong_new="keep_jobs: 24", wrong2_old="worker_threads: 1", wrong2_new="worker_threads: 10", prefix="salt"),
    dict(vendor="Puppet", ok_slug="puppet-metrics-port-drop-leftover", bad_slug="ppt-port-raise-runint-not-port", noun="bendpad", panel="Puppet metrics", needle="ppt_up", lie_core="puppetserver leftover metrics-webservice-port 0 so Grafana is empty while the catalog still compiled", false_lead="Puppet runinterval leftover", avoided=BAN+"; Salt stats plant", knob=".metrics-webservice-port", old="metrics-webservice-port: 0", new="metrics-webservice-port: 8140", wrong_knob=".runinterval", wrong_old="runinterval: 86400", wrong_new="runinterval: 1800", wrong2_old="splay: false", wrong2_new="splay: true", prefix="ppt"),
    dict(vendor="Chef", ok_slug="chef-reporting-off-leftover", bad_slug="chef-rep-raise-int-not-enable", noun="cncpad", panel="Chef reporting", needle="chef_up", lie_core="reporting leftover enable_reporting false so Grafana is empty while chef-client still 0", false_lead="Chef interval leftover", avoided=BAN+"; Puppet metrics plant", knob=".enable_reporting", old="enable_reporting: false", new="enable_reporting: true", wrong_knob=".interval", wrong_old="interval: 86400", wrong_new="interval: 1800", wrong2_old="log_level: error", wrong2_new="log_level: info", prefix="chef"),
    dict(vendor="cluster-autoscaler", ok_slug="cas-metrics-bind-drop-leftover", bad_slug="cas-bind-raise-scan-not-addr", noun="tigpad", panel="cluster-autoscaler", needle="cas_up", lie_core="metrics leftover --address 127.0.0.1 so Grafana is empty while nodes still scale", false_lead="cluster-autoscaler scan leftover", avoided=BAN+"; Karpenter metrics plant", knob=".address", old="address: 127.0.0.1:8085", new="address: 0.0.0.0:8085", wrong_knob=".scan-interval", wrong_old="scan-interval: 1h", wrong_new="scan-interval: 10s", wrong2_old="scale-down-enabled: false", wrong2_new="scale-down-enabled: true", prefix="cas"),
    dict(vendor="Thanos sidecar", ok_slug="thanossidecar-http-bind-drop-leftover", bad_slug="tside-http-raise-upload-not-bind", noun="tankpad", panel="Thanos sidecar", needle="tside_up", lie_core="http leftover --http-address 127.0.0.1 so Grafana is empty while TSDB still ships", false_lead="Thanos sidecar upload leftover", avoided=BAN+"; leftover3 Thanos store denylist; Thanos Ruler r677", knob=".http-address", old="http-address: 127.0.0.1:10902", new="http-address: 0.0.0.0:10902", wrong_knob=".min-time", wrong_old="min-time: 24h", wrong_new="min-time: 0s", wrong2_old="shipper.upload-compacted: false", wrong2_new="shipper.upload-compacted: true", prefix="tside"),
    dict(vendor="Mimir ruler", ok_slug="mimirruler-api-disable-leftover", bad_slug="mruler-api-raise-eval-not-enable", noun="coilpad", panel="Mimir ruler", needle="mruler_up", lie_core="ruler leftover enable_api false so Grafana is empty while Mimir still ready", false_lead="Mimir ruler eval leftover", avoided=BAN+"; r499 Mimir remote_timeout; leftover3 HA", knob=".ruler.enable_api", old="enable_api: false", new="enable_api: true", wrong_knob=".ruler.evaluation_interval", wrong_old="evaluation_interval: 1h", wrong_new="evaluation_interval: 1m", wrong2_old="ruler.alertmanager_url: ", wrong2_new="ruler.alertmanager_url: http://am:9093", prefix="mruler"),
    dict(vendor="Loki ingester", ok_slug="lokiing-lifecycler-addr-drop-leftover", bad_slug="ling-addr-raise-chunk-not-bind", noun="probepad", panel="Loki ingester", needle="ling_up", lie_core="lifecycler leftover address 127.0.0.1 so Grafana is empty while WAL still grows", false_lead="Loki ingester chunk leftover", avoided=BAN+"; leftover3 Loki max_query_series; r244 Loki max_concurrent", knob=".ingester.lifecycler.address", old="address: 127.0.0.1", new="address: 0.0.0.0", wrong_knob=".ingester.chunk_idle_period", wrong_old="chunk_idle_period: 24h", wrong_new="chunk_idle_period: 30m", wrong2_old="wal.enabled: false", wrong2_new="wal.enabled: true", prefix="ling"),
    dict(vendor="Tempo distributor", ok_slug="tempodist-receivers-off-leftover", bad_slug="tdist-recv-raise-ring-not-otlp", noun="standpad", panel="Tempo distributor", needle="tdist_up", lie_core="receivers leftover otlp disabled so Grafana is empty while Jaeger still 14250", false_lead="Tempo distributor ring leftover", avoided=BAN+"; r384 OTel forward; leftover3 jaeger memory", knob=".distributor.receivers.otlp", old="otlp: disabled", new="otlp: enabled", wrong_knob=".distributor.ring.instance_addr", wrong_old="instance_addr: 127.0.0.1", wrong_new="instance_addr: 0.0.0.0", wrong2_old="log_received_spans.enabled: false", wrong2_new="log_received_spans.enabled: true", prefix="tdist"),
    dict(vendor="Kyverno", ok_slug="kyverno-metrics-port-drop-leftover", bad_slug="kyv-port-raise-bgscan-not-port", noun="cellpad", panel="Kyverno metrics", needle="kyv_up", lie_core="metrics leftover --metricsPort 0 so Grafana is empty while Policy still Ready", false_lead="Kyverno background scan leftover", avoided=BAN+"; leftover3 Falco; Gatekeeper later", knob=".metricsPort", old="metricsPort: 0", new="metricsPort: 8000", wrong_knob=".backgroundScan", wrong_old="backgroundScan: false", wrong_new="backgroundScan: true", wrong2_old="validationFailureAction: audit", wrong2_new="validationFailureAction: Enforce", prefix="kyv"),
    dict(vendor="OPA", ok_slug="opa-decision-logs-drop-leftover", bad_slug="opa-dlog-raise-bundle-not-log", noun="apu2pad", panel="OPA decisions", needle="opa_up", lie_core="decision_logs leftover console=false plus service drop so Grafana is empty while /v1/data still 200", false_lead="OPA bundle leftover", avoided=BAN+"; Kyverno metrics plant", knob=".decision_logs.console", old="console: false", new="console: true", wrong_knob=".bundles.auth.service", wrong_old="service: sandbox", wrong_new="service: hangar", wrong2_old="default_decision: /deny", wrong2_new="default_decision: /allow", prefix="opa"),
    dict(vendor="Gatekeeper", ok_slug="gatekeeper-metrics-bind-drop-leftover", bad_slug="gkeep-bind-raise-audit-not-addr", noun="idg2pad", panel="Gatekeeper metrics", needle="gkeep_up", lie_core="metrics leftover --metrics-addr 127.0.0.1 so Grafana is empty while Constraint still Enforced", false_lead="Gatekeeper audit leftover", avoided=BAN+"; Kyverno metrics plant; leftover3 Falco", knob=".metrics-addr", old="metrics-addr: 127.0.0.1:8888", new="metrics-addr: 0.0.0.0:8888", wrong_knob=".audit-interval", wrong_old="audit-interval: 86400", wrong_new="audit-interval: 60", wrong2_old="log-denies: false", wrong2_new="log-denies: true", prefix="gkeep"),
    dict(vendor="falcosidekick", ok_slug="falcoside-output-drop-leftover", bad_slug="fside-out-raise-prio-not-output", noun="pump2pad", panel="falcosidekick", needle="fside_up", lie_core="output leftover grafana.enabled=false so Grafana is empty while Falco still 202", false_lead="falcosidekick priority leftover", avoided=BAN+"; leftover3 Falco priority; Sysdig r596", knob=".grafana.enabled", old="enabled: false", new="enabled: true", wrong_knob=".priority", wrong_old="priority: emergency", wrong_new="priority: warning", wrong2_old="debug: false", wrong2_new="debug: true", prefix="fside"),
    dict(vendor="Cilium NetworkPolicy", ok_slug="ciliumpol-metrics-off-leftover", bad_slug="cilpol-met-raise-hubble-not-enable", noun="act2pad", panel="Cilium policy", needle="cilpol_up", lie_core="prometheus leftover enable=false so Grafana is empty while NetworkPolicy still drops", false_lead="Cilium Hubble leftover", avoided=BAN+"; leftover3 Hubble; Tetragon r605", knob=".prometheus.enabled", old="enabled: false", new="enabled: true", wrong_knob=".hubble.enabled", wrong_old="enabled: false", wrong_new="enabled: true", wrong2_old="policyEnforcementMode: default", wrong2_new="policyEnforcementMode: always", prefix="cilpol"),
    dict(vendor="Istio telemetry", ok_slug="istiotel-meshconfig-drop-leftover", bad_slug="istel-mesh-raise-access-not-prom", noun="cbl2pad", panel="Istio telemetry", needle="istel_up", lie_core="meshConfig leftover enablePrometheusMerge false plus extensionProviders drop so Grafana is empty", false_lead="Istio access log leftover", avoided=BAN+"; Istio Gateway plant; leftover3 Istio/Hubble", knob=".meshConfig.enablePrometheusMerge", old="enablePrometheusMerge: false", new="enablePrometheusMerge: true", wrong_knob=".meshConfig.accessLogFile", wrong_old="accessLogFile: /dev/null", wrong_new="accessLogFile: /dev/stdout", wrong2_old="defaultConfig.tracing.zipkin.address: ", wrong2_new="defaultConfig.tracing.zipkin.address: zipkin:9411", prefix="istel"),
    dict(vendor="KEDA HTTP", ok_slug="kedahttp-interceptor-metrics-drop-leftover", bad_slug="khttp-int-raise-pending-not-metrics", noun="fc2pad", panel="KEDA HTTP", needle="khttp_up", lie_core="interceptor leftover --metrics-bind-addr 127.0.0.1 so Grafana is empty while ScaledObject still Ready", false_lead="KEDA HTTP pending leftover", avoided=BAN+"; KEDA pause r611", knob=".metrics-bind-addr", old="metrics-bind-addr: 127.0.0.1:8080", new="metrics-bind-addr: 0.0.0.0:8080", wrong_knob=".pendingRequests", wrong_old="pendingRequests: 0", wrong_new="pendingRequests: 100", wrong2_old="targetPendingRequests: 0", wrong2_new="targetPendingRequests: 100", prefix="khttp"),
]


assert len(SPECS) == 37, len(SPECS)
for i, spec in enumerate(SPECS):
    _l7(741 + i, **spec)
