"""Observability plants r233-r244. Do not clone r109-r232."""

from mill_plants_h import _failp, _okp

MORE = []


# r233 Prometheus scrape timeout >= interval
MORE.append(
    (
        _okp(
            slug="prom-scrape-timeout-vs-interval",
            service="apu-start-svc",
            dashboard_uid="apu-scrape-1",
            panel="up",
            query='up{job="apu-start-svc"}',
            lie="scrape_timeout 15s >= scrape_interval 15s so scrapes abort; Grafana up is 0 while /metrics is fast",
            false_lead="Prom agent no local TSDB / scrape body size",
            config_path="prom/apu-agent.yaml",
            lie_path="prom/apu-scrape.yaml",
            truth_name="scrape duration vs timeout",
            reload_name="prom-scrape",
            side="other jobs with timeout < interval still up=1",
            surfaces="Prometheus scrape_timeout >= scrape_interval",
            avoided="r160 Prom agent TSDB; r238 body size; remote_write queue",
            this_is="timeout equal interval aborts every scrape",
            step_note="False lead agent 4-5; timeout=interval 6-8; timeout 10s 9-12.",
            query_cmd="curl -sS -G $MIMIR/prometheus/api/v1/query --data-urlencode 'query=up{job=\"apu-start-svc\"}'",
            false_cmd="rg 'enable-feature=agent|storage.tsdb' prom/apu-agent.yaml",
            truth_cmd="curl -sS -G $MIMIR/prometheus/api/v1/query --data-urlencode 'query=scrape_duration_seconds{job=\"apu-start-svc\"}'",
            confirm_cmd="yq '.scrape_configs[]|select(.job_name==\"apu-start-svc\")' prom/apu-scrape.yaml",
            reload_cmd="kubectl -n prom rollout restart deploy/prom-scrape && kubectl -n prom rollout status deploy/prom-scrape --timeout=90s",
            requery_cmd="curl -sS -G $MIMIR/prometheus/api/v1/query --data-urlencode 'query=up{job=\"apu-start-svc\"}'",
            grafana_ok_cmd="curl -sS $GRAFANA/api/ds/query -d @/tmp/apu.json | jq '.results.A.frames[0].schema'",
            side_cmd="curl -sS -G $MIMIR/prometheus/api/v1/query --data-urlencode 'query=up{job=\"ssr-meal-svc\"}' | jq '.data.result[0].value'",
            final_cmd="yq -r '.scrape_configs[]|select(.job_name==\"apu-start-svc\").scrape_timeout' prom/apu-scrape.yaml",
            patch_old="scrape_interval: 15s\n    scrape_timeout: 15s",
            patch_new="scrape_interval: 15s\n    scrape_timeout: 10s",
            runbook_path="runbooks/apu-scrape-timeout.md",
            runbook="# apu-start-svc scrape timeout\ntimeout must be < interval. 15s=15s aborted. Not agent TSDB.\n",
            goal="apu-start-svc dashboard apu-scrape-1 up is 0. /metrics is 8ms. Find the timeout lie.",
            plan="up=0 → agent TSDB (false) → timeout=interval → timeout 10s.",
            outcome="timeout 10s. up=1. other jobs unchanged.",
            obs1='[{"uid":"apu-scrape-1","title":"apu start up"}]',
            obs2='{"title":"up","targets":[{"expr":"up{job=\\"apu-start-svc\\"}"}]}',
            obs3='{"status":"success","data":{"result":[{"value":[1710000000,"0"]}]}}',
            obs4="enable-feature: []\n# server mode — not r160",
            obs5="not agent",
            obs6="scrape_interval: 15s\nscrape_timeout: 15s",
            obs7='{"status":"success","data":{"result":[{"value":[1710000000,"0.014"]}]}}\n# last success 14ms then timeout",',
            obs8="timeout==interval; scrape never completes before next",
            obs9="patched timeout 10s",
            obs10='deployment "prom-scrape" successfully rolled out',
            obs11='{"status":"success","data":{"result":[{"value":[1710000600,"1"]}]}}',
            obs12='{"name":"Timeseries"}',
            obs13='["1710000600","1"]',
            obs14="wrote runbooks/apu-scrape-timeout.md",
            obs15="10s",
        ),
        _failp(
            slug="prom-timeout-enable-agent-tsdb",
            service="oil-qty-svc",
            dashboard_uid="oil-scrape-agent",
            panel="oil up",
            query='up{job="oil-qty-svc"}',
            lie="Enabling Prom agent TSDB does not stop scrape_timeout==scrape_interval from aborting oil-qty scrapes",
            false_lead="Prom agent has no local TSDB",
            config_path="prom/oil-agent.yaml",
            lie_path="prom/oil-scrape.yaml",
            wrong_path="prom/oil-agent.yaml",
            reload_name="prom-agent",
            ticket="OBS-5301",
            xfail="tests/test_oil_scrape.py",
            surfaces="Prom agent leftover vs scrape timeout==interval",
            avoided="r160 as actual RCA",
            this_is="fail/handoff: agent TSDB on, timeout still 15s=15s",
            step_note="agent 6-10; still up=0 11; late timeout 12; handoff 14-15.",
            next_note="Next: honor_timestamps future samples.",
            query_cmd="curl -sS -G $MIMIR/prometheus/api/v1/query --data-urlencode 'query=up{job=\"oil-qty-svc\"}'",
            false_cmd="rg 'enable-feature=agent' prom/oil-agent.yaml",
            reload_cmd="kubectl -n prom rollout restart deploy/prom-agent && kubectl -n prom rollout status deploy/prom-agent --timeout=90s",
            requery_cmd="curl -sS -G $MIMIR/prometheus/api/v1/query --data-urlencode 'query=up{job=\"oil-qty-svc\"}'",
            denied_cmd="kubectl -n prom auth can-i patch configmap/oil-scrape --as=sre-bot",
            wrong_old="enable-feature: [agent]",
            wrong_new="enable-feature: []",
            wrong2_old="storage.tsdb.path: /dev/null",
            wrong2_new="storage.tsdb.path: /prometheus",
            ticket_body="OBS-5301: oil-qty-svc still up=0. Agent leftover. scrape_timeout=15s==interval. Need timeout 10s. No scrape RBAC.\n",
            goal="oil-qty-svc dashboard oil-scrape-agent oil up is 0. Restore up=1.",
            plan="Disable Prom agent (r160 leftover).",
            outcome="agent off; still up=0. Late timeout=interval. Handoff OBS-5301.",
            obs1='[{"uid":"oil-scrape-agent","title":"oil qty up"}]',
            obs2='{"title":"oil up","targets":[{"expr":"up{job=\\"oil-qty-svc\\"}"}]}',
            obs3='{"status":"success","data":{"result":[{"value":[1710000000,"0"]}]}}',
            obs4="enable-feature: [agent]",
            obs5="agent — treated as r160",
            obs6="prom/oil-agent.yaml",
            obs7="patched feature []",
            obs8='deployment "prom-agent" successfully rolled out',
            obs9='{"status":"success","data":{"result":[{"value":[1710000600,"0"]}]}}',
            obs10="patched tsdb path",
            obs11='{"status":"success","data":{"result":[{"value":[1710000900,"0"]}]}}',
            obs12="prom/oil-scrape.yaml scrape_timeout 15s scrape_interval 15s",
            obs13="no",
            obs14="wrote tickets/OBS-5301.md",
            obs15="xfail tests/test_oil_scrape.py",
        ),
    )
)

# r234 honor_timestamps future samples
MORE.append(
    (
        _okp(
            slug="prom-honor-ts-future-drop",
            service="mag-plug-svc",
            dashboard_uid="mag-honorts-2",
            panel="plug ohms",
            query='avg(mag_plug_ohms{job="mag-plug-svc"})',
            lie="honor_timestamps true plus app clock +90s drops samples as future; Grafana No data while /metrics shows ohms",
            false_lead="clock skew between collector and Tempo / scrape timeout",
            config_path="prom/mag-timeout.yaml",
            lie_path="prom/mag-scrape.yaml",
            truth_name="honor_timestamps vs sample ts",
            reload_name="prom-scrape",
            side="jobs without honor_timestamps still ingest",
            surfaces="Prometheus honor_timestamps future-sample drop",
            avoided="r02 clock skew; r233 timeout=interval; TSDB retention.size",
            this_is="honor_timestamps keeps app ts 90s in the future",
            step_note="False lead timeout/skew 4-5; honor_timestamps 6-8; false 9-12.",
            query_cmd="curl -sS -G $MIMIR/prometheus/api/v1/query --data-urlencode 'query=avg(mag_plug_ohms{job=\"mag-plug-svc\"})'",
            false_cmd="yq '.scrape_configs[]|select(.job_name==\"mag-plug-svc\").scrape_timeout' prom/mag-timeout.yaml",
            truth_cmd="curl -sS http://mag-plug-svc:8080/metrics | rg mag_plug_ohms",
            confirm_cmd="yq '.scrape_configs[]|select(.job_name==\"mag-plug-svc\").honor_timestamps' prom/mag-scrape.yaml",
            reload_cmd="kubectl -n prom rollout restart deploy/prom-scrape && kubectl -n prom rollout status deploy/prom-scrape --timeout=90s",
            requery_cmd="curl -sS -G $MIMIR/prometheus/api/v1/query --data-urlencode 'query=avg(mag_plug_ohms{job=\"mag-plug-svc\"})'",
            grafana_ok_cmd="curl -sS $GRAFANA/api/ds/query -d @/tmp/mag.json | jq '.results.A.frames[0].schema'",
            side_cmd="curl -sS -G $MIMIR/prometheus/api/v1/query --data-urlencode 'query=avg(mag_plug_ohms{job=\"ssr-meal-svc\"})' | jq '.data.result|length'",
            final_cmd="yq -r '.scrape_configs[]|select(.job_name==\"mag-plug-svc\").honor_timestamps' prom/mag-scrape.yaml",
            patch_old="honor_timestamps: true",
            patch_new="honor_timestamps: false  # scrape time; app NTP is +90s",
            runbook_path="runbooks/mag-honor-ts.md",
            runbook="# mag-plug-svc honor_timestamps\nApp clock +90s. honor_timestamps dropped future samples. Use scrape time.\nNot scrape timeout.\n",
            goal="mag-plug-svc dashboard mag-honorts-2 plug ohms empty. /metrics has 12.4. Find the future-ts lie.",
            plan="Empty → timeout (false) → honor_timestamps + future ts → honor false.",
            outcome="honor_timestamps false. ohms=12.4. other jobs unchanged.",
            obs1='[{"uid":"mag-honorts-2","title":"mag plug ohms"}]',
            obs2='{"title":"plug ohms","targets":[{"expr":"avg(mag_plug_ohms{job=\\"mag-plug-svc\\"})"}]}',
            obs3='{"status":"success","data":{"result":[]}}',
            obs4="scrape_timeout: 10s\nscrape_interval: 15s  # not r233",
            obs5="timeout < interval",
            obs6="honor_timestamps: true",
            obs7="mag_plug_ohms 12.4 1710000090  # +90s vs scrape now",
            obs8="future timestamps dropped",
            obs9="patched honor_timestamps false",
            obs10='deployment "prom-scrape" successfully rolled out',
            obs11='{"status":"success","data":{"result":[{"value":[1710000600,"12.4"]}]}}',
            obs12='{"name":"Timeseries"}',
            obs13="1",
            obs14="wrote runbooks/mag-honor-ts.md",
            obs15="false",
        ),
        _failp(
            slug="prom-honor-lower-timeout-not-ts",
            service="pitot-heat-svc",
            dashboard_uid="pitot-honor-timeout",
            panel="pitot ohms",
            query='avg(pitot_ohms{job="pitot-heat-svc"})',
            lie="Lowering scrape_timeout does not ingest samples whose timestamps are 90s in the future under honor_timestamps",
            false_lead="scrape_timeout >= scrape_interval",
            config_path="prom/pitot-timeout.yaml",
            lie_path="prom/pitot-scrape.yaml",
            wrong_path="prom/pitot-timeout.yaml",
            reload_name="prom-scrape",
            ticket="OBS-5302",
            xfail="tests/test_pitot_honor.py",
            surfaces="timeout leftover vs honor_timestamps",
            avoided="r233 as actual RCA",
            this_is="fail/handoff: timeout 8s, future ts still dropped",
            step_note="timeout 6-10; still empty 11; late honor_timestamps 12; handoff 14-15.",
            next_note="Next: Loki max_chunk_age.",
            query_cmd="curl -sS -G $MIMIR/prometheus/api/v1/query --data-urlencode 'query=avg(pitot_ohms{job=\"pitot-heat-svc\"})'",
            false_cmd="yq '.scrape_configs[]|select(.job_name==\"pitot-heat-svc\")|{scrape_timeout,scrape_interval}' prom/pitot-timeout.yaml",
            reload_cmd="kubectl -n prom rollout restart deploy/prom-scrape && kubectl -n prom rollout status deploy/prom-scrape --timeout=90s",
            requery_cmd="curl -sS -G $MIMIR/prometheus/api/v1/query --data-urlencode 'query=avg(pitot_ohms{job=\"pitot-heat-svc\"})'",
            denied_cmd="kubectl -n prom auth can-i patch configmap/pitot-scrape --as=sre-bot",
            wrong_old="scrape_timeout: 15s",
            wrong_new="scrape_timeout: 8s",
            wrong2_old="scrape_interval: 15s",
            wrong2_new="scrape_interval: 30s",
            ticket_body="OBS-5302: pitot-heat-svc still empty. timeout leftover. honor_timestamps true + app NTP +90s. Need honor false. No scrape RBAC.\n",
            goal="pitot-heat-svc dashboard pitot-honor-timeout pitot ohms empty. Restore series.",
            plan="Lower scrape_timeout (r233 leftover).",
            outcome="timeout 8s; still empty. Late honor_timestamps. Handoff OBS-5302.",
            obs1='[{"uid":"pitot-honor-timeout","title":"pitot heat"}]',
            obs2='{"title":"pitot ohms","targets":[{"expr":"avg(pitot_ohms{job=\\"pitot-heat-svc\\"})"}]}',
            obs3='{"status":"success","data":{"result":[]}}',
            obs4="scrape_timeout: 15s",
            obs5="treated as r233",
            obs6="prom/pitot-timeout.yaml",
            obs7="patched timeout 8s",
            obs8='deployment "prom-scrape" successfully rolled out',
            obs9='{"status":"success","data":{"result":[]}}',
            obs10="patched interval 30s",
            obs11='{"status":"success","data":{"result":[]}}',
            obs12="prom/pitot-scrape.yaml honor_timestamps true; sample ts +90s",
            obs13="no",
            obs14="wrote tickets/OBS-5302.md",
            obs15="xfail tests/test_pitot_honor.py",
        ),
    )
)

# r235 Loki max_chunk_age
MORE.append(
    (
        _okp(
            slug="loki-max-chunk-age-idle",
            service="stall-vane-svc",
            dashboard_uid="stall-chunk-3",
            panel="vane errors",
            query='{job="stall-vane-svc"} |= "angle_disagree"',
            lie="ingester max_chunk_age 1m plus idle 30s closes chunks before flush so Grafana tails empty while pod logs have angle_disagree",
            false_lead="bloom skip / structured metadata matcher",
            config_path="loki/stall-bloom.yaml",
            lie_path="loki/stall-ingester.yaml",
            truth_name="ingester chunk flush metrics",
            reload_name="loki-ingester",
            side="high-volume jobs still flush",
            surfaces="Loki max_chunk_age vs Grafana tail",
            avoided="r165 bloom; r225 smeta label matcher; r191 OS URL",
            this_is="max_chunk_age 1m closes chunks before WAL flush on sparse logs",
            step_note="False lead bloom/smeta 4-5; max_chunk_age 6-8; 2h 9-12.",
            query_cmd="curl -sS -G $LOKI/loki/api/v1/query_range --data-urlencode 'query={job=\"stall-vane-svc\"} |= \"angle_disagree\"' | jq '.data.result|length'",
            false_cmd="yq '.bloom_gateway,.limits_config.allow_structured_metadata' loki/stall-bloom.yaml",
            truth_cmd="curl -sS $MIMIR/api/v1/query --data-urlencode 'query=loki_ingester_chunks_flushed_total{job=\"stall-vane-svc\"}'",
            confirm_cmd="yq '.ingester.max_chunk_age, .ingester.chunk_idle_period' loki/stall-ingester.yaml",
            reload_cmd="kubectl -n loki rollout restart sts/loki-ingester && kubectl -n loki rollout status sts/loki-ingester --timeout=120s",
            requery_cmd="curl -sS -G $LOKI/loki/api/v1/query_range --data-urlencode 'query={job=\"stall-vane-svc\"} |= \"angle_disagree\"' | jq '.data.result|length'",
            grafana_ok_cmd="curl -sS $GRAFANA/api/ds/query -d @/tmp/stall.json | jq '.results.A.frames[0].schema'",
            side_cmd="curl -sS -G $LOKI/loki/api/v1/query_range --data-urlencode 'query={job=\"ssr-meal-svc\"} |= \"error\"' | jq '.data.result|length'",
            final_cmd="yq -r '.ingester.max_chunk_age' loki/stall-ingester.yaml",
            patch_old="max_chunk_age: 1m\n  chunk_idle_period: 30s",
            patch_new="max_chunk_age: 2h\n  chunk_idle_period: 30m",
            runbook_path="runbooks/stall-chunk-age.md",
            runbook="# stall-vane-svc max_chunk_age\nSparse logs never flushed at 1m/30s. Raise ages. Not bloom.\n",
            goal="stall-vane-svc dashboard stall-chunk-3 vane errors empty. Pod logs have angle_disagree. Find the chunk-age lie.",
            plan="Empty Loki → bloom/smeta (false) → max_chunk_age 1m → 2h.",
            outcome="max_chunk_age 2h. 9 streams. high-volume jobs unchanged.",
            obs1='[{"uid":"stall-chunk-3","title":"stall vane logs"}]',
            obs2='{"title":"vane errors","targets":[{"expr":"{job=\\"stall-vane-svc\\"} |= \\"angle_disagree\\""}]}',
            obs3="0",
            obs4="bloom_gateway.enabled: false\nallow_structured_metadata: true  # not r165/r225",
            obs5="blooms off",
            obs6="max_chunk_age: 1m\nchunk_idle_period: 30s",
            obs7='{"status":"success","data":{"result":[{"value":[1710000000,"0"]}]}}\n# chunks_flushed=0',
            obs8="chunks closed idle never flushed to store",
            obs9="patched 2h / 30m",
            obs10='statefulset "loki-ingester" successfully rolled out',
            obs11="9",
            obs12='{"name":"Logs"}',
            obs13="14",
            obs14="wrote runbooks/stall-chunk-age.md",
            obs15="2h",
        ),
        _failp(
            slug="loki-chunk-rebuild-blooms",
            service="tcas-ra-svc",
            dashboard_uid="tcas-chunk-bloom",
            panel="RA logs",
            query='{job="tcas-ra-svc"} |= "resolution_advisory"',
            lie="Rebuilding blooms does not flush Loki chunks closed by max_chunk_age 1m",
            false_lead="Loki bloom-gateway skip_factor",
            config_path="loki/tcas-bloom.yaml",
            lie_path="loki/tcas-ingester.yaml",
            wrong_path="loki/tcas-bloom.yaml",
            reload_name="loki-bloom-gateway",
            ticket="OBS-5303",
            xfail="tests/test_tcas_chunk.py",
            surfaces="bloom leftover vs max_chunk_age",
            avoided="r165 as actual RCA",
            this_is="fail/handoff: blooms off, chunks still unflushed",
            step_note="blooms 6-10; still 0 11; late max_chunk_age 12; handoff 14-15.",
            next_note="Next: Tempo complete_block_timeout.",
            query_cmd="curl -sS -G $LOKI/loki/api/v1/query_range --data-urlencode 'query={job=\"tcas-ra-svc\"} |= \"resolution_advisory\"' | jq '.data.result|length'",
            false_cmd="yq '.bloom_gateway' loki/tcas-bloom.yaml",
            reload_cmd="kubectl -n loki rollout restart deploy/bloom-gateway && kubectl -n loki rollout status deploy/bloom-gateway --timeout=90s",
            requery_cmd="curl -sS -G $LOKI/loki/api/v1/query_range --data-urlencode 'query={job=\"tcas-ra-svc\"} |= \"resolution_advisory\"' | jq '.data.result|length'",
            denied_cmd="kubectl -n loki auth can-i patch sts/loki-ingester --as=sre-bot",
            wrong_old="skip_factor: 3",
            wrong_new="skip_factor: 0",
            wrong2_old="enabled: true",
            wrong2_new="enabled: false",
            ticket_body="OBS-5303: tcas-ra-svc Loki still 0. bloom leftover. max_chunk_age 1m. Need 2h. No ingester RBAC.\n",
            goal="tcas-ra-svc dashboard tcas-chunk-bloom RA logs empty. Restore streams.",
            plan="Disable blooms (r165 leftover).",
            outcome="blooms off; still 0. Late max_chunk_age 1m. Handoff OBS-5303.",
            obs1='[{"uid":"tcas-chunk-bloom","title":"tcas ra logs"}]',
            obs2='{"title":"RA logs","targets":[{"expr":"{job=\\"tcas-ra-svc\\"} |= \\"resolution_advisory\\""}]}',
            obs3="0",
            obs4="skip_factor: 3",
            obs5="treated as r165",
            obs6="loki/tcas-bloom.yaml",
            obs7="patched skip 0",
            obs8='deployment "bloom-gateway" successfully rolled out',
            obs9="0",
            obs10="patched bloom enabled false",
            obs11="0",
            obs12="loki/tcas-ingester.yaml max_chunk_age 1m chunk_idle_period 30s flushed=0",
            obs13="no",
            obs14="wrote tickets/OBS-5303.md",
            obs15="xfail tests/test_tcas_chunk.py",
        ),
    )
)

# r236 Tempo complete_block_timeout
MORE.append(
    (
        _okp(
            slug="tempo-complete-block-timeout",
            service="gpws-tone-svc",
            dashboard_uid="gpws-block-4",
            panel="GPWS traces",
            query='{resource.service.name="gpws-tone-svc"}',
            lie="ingester complete_block_timeout 10s plus max_block_duration 10s cuts traces before flush; Grafana search empty while live spans exist in WAL",
            false_lead="metrics-generator filter_policies / loadbalancing jaeger",
            config_path="tempo/gpws-mg.yaml",
            lie_path="tempo/gpws-ingester.yaml",
            truth_name="ingester traces_created vs flushed",
            reload_name="tempo-ingester",
            side="long-lived jobs with 30m block duration still searchable",
            surfaces="Tempo complete_block_timeout vs search",
            avoided="r164 MG filter; r204 loadbalancing; Tempo MG missing dim",
            this_is="complete_block_timeout 10s drops incomplete traces",
            step_note="False lead MG/lb 4-5; block timeout 6-8; 30m 9-12.",
            query_cmd="curl -sS -G $TEMPO/api/search --data-urlencode 'q={resource.service.name=\"gpws-tone-svc\"}' | jq '.traces|length'",
            false_cmd="yq '.metrics_generator.processor.span_metrics.filter_policies' tempo/gpws-mg.yaml",
            truth_cmd="curl -sS $MIMIR/api/v1/query --data-urlencode 'query=tempo_ingester_traces_created_total{job=\"gpws-tone-svc\"}'",
            confirm_cmd="yq '.ingester.complete_block_timeout, .ingester.max_block_duration' tempo/gpws-ingester.yaml",
            reload_cmd="kubectl -n tempo rollout restart sts/tempo-ingester && kubectl -n tempo rollout status sts/tempo-ingester --timeout=120s",
            requery_cmd="curl -sS -G $TEMPO/api/search --data-urlencode 'q={resource.service.name=\"gpws-tone-svc\"}' | jq '.traces|length'",
            grafana_ok_cmd="curl -sS $GRAFANA/api/ds/query -d @/tmp/gpws.json | jq '.results.A.frames[0].schema'",
            side_cmd="curl -sS -G $TEMPO/api/search --data-urlencode 'q={resource.service.name=\"ssr-meal-svc\"}' | jq '.traces|length'",
            final_cmd="yq -r '.ingester.complete_block_timeout' tempo/gpws-ingester.yaml",
            patch_old="complete_block_timeout: 10s\n  max_block_duration: 10s",
            patch_new="complete_block_timeout: 15m\n  max_block_duration: 30m",
            runbook_path="runbooks/gpws-block-timeout.md",
            runbook="# gpws-tone-svc complete_block_timeout\n10s blocks cut traces before flush. Raise duration. Not MG filter.\n",
            goal="gpws-tone-svc dashboard gpws-block-4 GPWS traces empty. Live WAL has spans. Find the block-timeout lie.",
            plan="Empty search → MG/lb (false) → complete_block_timeout 10s → 15m.",
            outcome="timeout 15m. 24 traces. ssr-meal-svc unchanged.",
            obs1='[{"uid":"gpws-block-4","title":"gpws traces"}]',
            obs2='{"title":"GPWS traces","targets":[{"query":"{resource.service.name=\\"gpws-tone-svc\\"}"}]}',
            obs3="0",
            obs4="filter_policies: []\n# not r164",
            obs5="MG clean",
            obs6="complete_block_timeout: 10s\nmax_block_duration: 10s",
            obs7='{"status":"success","data":{"result":[{"value":[1710000000,"24"]}]}}\n# created 24 flushed 0',
            obs8="blocks complete before flush",
            obs9="patched 15m / 30m",
            obs10='statefulset "tempo-ingester" successfully rolled out',
            obs11="24",
            obs12='{"name":"Traces"}',
            obs13="19",
            obs14="wrote runbooks/gpws-block-timeout.md",
            obs15="15m",
        ),
        _failp(
            slug="tempo-block-add-mg-dim",
            service="elt-test-svc",
            dashboard_uid="elt-block-mg",
            panel="ELT traces",
            query='{resource.service.name="elt-test-svc"}',
            lie="Adding Tempo metrics-generator dimensions does not flush traces cut by complete_block_timeout 10s",
            false_lead="Tempo MG missing dim / filter_policies skip",
            config_path="tempo/elt-mg.yaml",
            lie_path="tempo/elt-ingester.yaml",
            wrong_path="tempo/elt-mg.yaml",
            reload_name="tempo-mg",
            ticket="OBS-5304",
            xfail="tests/test_elt_block.py",
            surfaces="MG dim leftover vs complete_block_timeout",
            avoided="r164 as actual RCA",
            this_is="fail/handoff: MG dim added, traces still unflushed",
            step_note="MG dim 6-10; still 0 11; late block timeout 12; handoff 14-15.",
            next_note="Next: OTel batch timeout.",
            query_cmd="curl -sS -G $TEMPO/api/search --data-urlencode 'q={resource.service.name=\"elt-test-svc\"}' | jq '.traces|length'",
            false_cmd="yq '.metrics_generator.processor.span_metrics.dimensions' tempo/elt-mg.yaml",
            reload_cmd="kubectl -n tempo rollout restart deploy/metrics-generator && kubectl -n tempo rollout status deploy/metrics-generator --timeout=90s",
            requery_cmd="curl -sS -G $TEMPO/api/search --data-urlencode 'q={resource.service.name=\"elt-test-svc\"}' | jq '.traces|length'",
            denied_cmd="kubectl -n tempo auth can-i patch sts/tempo-ingester --as=sre-bot",
            wrong_old="dimensions:\n      - http.method",
            wrong_new="dimensions:\n      - http.method\n      - http.route",
            wrong2_old="filter_policies: []",
            wrong2_new="filter_policies: []\n    # keep 200s",
            ticket_body="OBS-5304: elt-test-svc Tempo still 0. MG leftover. complete_block_timeout 10s. Need 15m. No ingester RBAC.\n",
            goal="elt-test-svc dashboard elt-block-mg ELT traces empty. Land traces.",
            plan="Add MG http.route dim (r164 leftover).",
            outcome="MG dim on; still 0. Late complete_block_timeout 10s. Handoff OBS-5304.",
            obs1='[{"uid":"elt-block-mg","title":"elt traces"}]',
            obs2='{"title":"ELT traces","targets":[{"query":"{resource.service.name=\\"elt-test-svc\\"}"}]}',
            obs3="0",
            obs4="- http.method",
            obs5="treated as r164",
            obs6="tempo/elt-mg.yaml",
            obs7="patched +http.route",
            obs8='deployment "metrics-generator" successfully rolled out',
            obs9="0",
            obs10="patched keep 200s comment",
            obs11="0",
            obs12="tempo/elt-ingester.yaml complete_block_timeout 10s flushed 0 created 11",
            obs13="no",
            obs14="wrote tickets/OBS-5304.md",
            obs15="xfail tests/test_elt_block.py",
        ),
    )
)

# r237 OTel batch timeout
MORE.append(
    (
        _okp(
            slug="otel-batch-timeout-vs-tempo",
            service="cvrs-dl-svc",
            dashboard_uid="cvrs-batch-5",
            panel="CVR traces",
            query='{resource.service.name="cvrs-dl-svc"}',
            lie="batch processor timeout 1ms plus send_batch_size 8192 never fills so traces sit in the collector; Tempo search empty",
            false_lead="memory_limiter drop / tail_sampling decision_wait",
            config_path="otelcol/cvrs-mem.yaml",
            lie_path="otelcol/cvrs-batch.yaml",
            truth_name="batch processor size vs timeout",
            reload_name="otelcol-cvrs",
            side="collectors with timeout 200ms still export",
            surfaces="OTel batch timeout vs Tempo empty",
            avoided="r224 memory_limiter; tail wait ban; r204 loadbalancing",
            this_is="batch timeout 1ms with huge send_batch_size never sends",
            step_note="False lead limiter/tail 4-5; batch 1ms 6-8; timeout 200ms 9-12.",
            query_cmd="curl -sS -G $TEMPO/api/search --data-urlencode 'q={resource.service.name=\"cvrs-dl-svc\"}' | jq '.traces|length'",
            false_cmd="yq '.processors.memory_limiter,.processors.tail_sampling' otelcol/cvrs-mem.yaml",
            truth_cmd="curl -sS $MIMIR/api/v1/query --data-urlencode 'query=otelcol_processor_batch_batch_send_size_sum{processor=\"batch\"}'",
            confirm_cmd="yq '.processors.batch' otelcol/cvrs-batch.yaml",
            reload_cmd="kubectl -n otel rollout restart deploy/otelcol-cvrs && kubectl -n otel rollout status deploy/otelcol-cvrs --timeout=90s",
            requery_cmd="curl -sS -G $TEMPO/api/search --data-urlencode 'q={resource.service.name=\"cvrs-dl-svc\"}' | jq '.traces|length'",
            grafana_ok_cmd="curl -sS $GRAFANA/api/ds/query -d @/tmp/cvrs.json | jq '.results.A.frames[0].schema'",
            side_cmd="curl -sS -G $TEMPO/api/search --data-urlencode 'q={resource.service.name=\"ssr-meal-svc\"}' | jq '.traces|length'",
            final_cmd="yq -r '.processors.batch.timeout' otelcol/cvrs-batch.yaml",
            patch_old="timeout: 1ms\n    send_batch_size: 8192",
            patch_new="timeout: 200ms\n    send_batch_size: 256",
            runbook_path="runbooks/cvrs-batch-timeout.md",
            runbook="# cvrs-dl-svc batch timeout\n1ms timeout + 8192 size never sends. Use 200ms/256. Not memory_limiter.\n",
            goal="cvrs-dl-svc dashboard cvrs-batch-5 CVR traces empty. Collector has spans in batch. Find the timeout lie.",
            plan="Empty Tempo → limiter/tail (false) → batch 1ms/8192 → 200ms/256.",
            outcome="batch 200ms. 17 traces. other collectors unchanged.",
            obs1='[{"uid":"cvrs-batch-5","title":"cvr traces"}]',
            obs2='{"title":"CVR traces","targets":[{"query":"{resource.service.name=\\"cvrs-dl-svc\\"}"}]}',
            obs3="0",
            obs4="memory_limiter: {limit_mib: 512}\ntail_sampling: null  # not r224 / not tail wait",
            obs5="limiter healthy; no tail",
            obs6="timeout: 1ms\nsend_batch_size: 8192",
            obs7='{"status":"success","data":{"result":[{"value":[1710000000,"0"]}]}}\n# send_size_sum 0',
            obs8="batch never reaches 8192 in 1ms",
            obs9="patched 200ms/256",
            obs10='deployment "otelcol-cvrs" successfully rolled out',
            obs11="17",
            obs12='{"name":"Traces"}',
            obs13="19",
            obs14="wrote runbooks/cvrs-batch-timeout.md",
            obs15="200ms",
        ),
        _failp(
            slug="otel-batch-raise-memlimiter",
            service="fdr-offload-svc",
            dashboard_uid="fdr-batch-mem",
            panel="FDR traces",
            query='{resource.service.name="fdr-offload-svc"}',
            lie="Raising memory_limiter does not flush an OTel batch processor stuck at timeout 1ms / send_batch_size 8192",
            false_lead="memory_limiter too small",
            config_path="otelcol/fdr-mem.yaml",
            lie_path="otelcol/fdr-batch.yaml",
            wrong_path="otelcol/fdr-mem.yaml",
            reload_name="otelcol-fdr",
            ticket="OBS-5305",
            xfail="tests/test_fdr_batch.py",
            surfaces="limiter leftover vs batch timeout",
            avoided="r224 as actual RCA",
            this_is="fail/handoff: limiter 1024, batch still 1ms/8192",
            step_note="limiter 6-10; still 0 11; late batch yaml 12; handoff 14-15.",
            next_note="Next: scrape body size limit.",
            query_cmd="curl -sS -G $TEMPO/api/search --data-urlencode 'q={resource.service.name=\"fdr-offload-svc\"}' | jq '.traces|length'",
            false_cmd="yq '.processors.memory_limiter.limit_mib' otelcol/fdr-mem.yaml",
            reload_cmd="kubectl -n otel rollout restart deploy/otelcol-fdr && kubectl -n otel rollout status deploy/otelcol-fdr --timeout=90s",
            requery_cmd="curl -sS -G $TEMPO/api/search --data-urlencode 'q={resource.service.name=\"fdr-offload-svc\"}' | jq '.traces|length'",
            denied_cmd="kubectl -n otel auth can-i patch configmap/fdr-batch --as=sre-bot",
            wrong_old="limit_mib: 32",
            wrong_new="limit_mib: 1024",
            wrong2_old="spike_limit_mib: 1",
            wrong2_new="spike_limit_mib: 256",
            ticket_body="OBS-5305: fdr-offload-svc Tempo still 0. limiter leftover. batch timeout 1ms size 8192. Need 200ms/256. No batch RBAC.\n",
            goal="fdr-offload-svc dashboard fdr-batch-mem FDR traces empty. Land traces.",
            plan="Raise memory_limiter (r224 leftover).",
            outcome="limiter 1024; still 0. Late batch 1ms. Handoff OBS-5305.",
            obs1='[{"uid":"fdr-batch-mem","title":"fdr traces"}]',
            obs2='{"title":"FDR traces","targets":[{"query":"{resource.service.name=\\"fdr-offload-svc\\"}"}]}',
            obs3="0",
            obs4="limit_mib: 32",
            obs5="treated as r224",
            obs6="otelcol/fdr-mem.yaml",
            obs7="patched 1024",
            obs8='deployment "otelcol-fdr" successfully rolled out',
            obs9="0",
            obs10="patched spike 256",
            obs11="0",
            obs12="otelcol/fdr-batch.yaml timeout 1ms send_batch_size 8192 send_size_sum 0",
            obs13="no",
            obs14="wrote tickets/OBS-5305.md",
            obs15="xfail tests/test_fdr_batch.py",
        ),
    )
)

# r238 scrape body size
MORE.append(
    (
        _okp(
            slug="prom-scrape-body-size-limit",
            service="adiru-align-svc",
            dashboard_uid="adiru-body-6",
            panel="align state",
            query='adiru_align_state{job="adiru-align-svc"}',
            lie="scrape body_size_limit 256KB drops a 1.1MB /metrics with 40k series; Grafana No data while curl /metrics works",
            false_lead="scrape_timeout == interval / native histogram",
            config_path="prom/adiru-timeout.yaml",
            lie_path="prom/adiru-scrape.yaml",
            truth_name="body_size_limit vs Content-Length",
            reload_name="prom-scrape",
            side="small /metrics jobs still scraped",
            surfaces="Prometheus scrape body_size_limit vs Grafana empty",
            avoided="r233 timeout=interval; r187 native hist; r160 agent",
            this_is="body_size_limit 256KB vs 1.1MB exposition",
            step_note="False lead timeout/nhist 4-5; body_size_limit 6-8; 4MB 9-12.",
            query_cmd="curl -sS -G $MIMIR/prometheus/api/v1/query --data-urlencode 'query=adiru_align_state{job=\"adiru-align-svc\"}'",
            false_cmd="yq '.scrape_configs[]|select(.job_name==\"adiru-align-svc\")|{scrape_timeout,scrape_protocols}' prom/adiru-timeout.yaml",
            truth_cmd="curl -sS -D- -o /tmp/adiru.prom http://adiru-align-svc:8080/metrics | rg -i content-length",
            confirm_cmd="yq '.scrape_configs[]|select(.job_name==\"adiru-align-svc\").body_size_limit' prom/adiru-scrape.yaml",
            reload_cmd="kubectl -n prom rollout restart deploy/prom-scrape && kubectl -n prom rollout status deploy/prom-scrape --timeout=90s",
            requery_cmd="curl -sS -G $MIMIR/prometheus/api/v1/query --data-urlencode 'query=adiru_align_state{job=\"adiru-align-svc\"}'",
            grafana_ok_cmd="curl -sS $GRAFANA/api/ds/query -d @/tmp/adiru.json | jq '.results.A.frames[0].schema'",
            side_cmd="curl -sS -G $MIMIR/prometheus/api/v1/query --data-urlencode 'query=up{job=\"ssr-meal-svc\"}' | jq '.data.result[0].value'",
            final_cmd="yq -r '.scrape_configs[]|select(.job_name==\"adiru-align-svc\").body_size_limit' prom/adiru-scrape.yaml",
            patch_old="body_size_limit: 256KB",
            patch_new="body_size_limit: 4MB",
            runbook_path="runbooks/adiru-body-size.md",
            runbook="# adiru-align-svc body_size_limit\n256KB limit vs 1.1MB /metrics. Raise to 4MB. Not timeout=interval.\n",
            goal="adiru-align-svc dashboard adiru-body-6 align state empty. curl /metrics is 1.1MB. Find the body-size lie.",
            plan="Empty → timeout/nhist (false) → body_size_limit 256KB → 4MB.",
            outcome="limit 4MB. align_state=3. small jobs unchanged.",
            obs1='[{"uid":"adiru-body-6","title":"adiru align"}]',
            obs2='{"title":"align state","targets":[{"expr":"adiru_align_state{job=\\"adiru-align-svc\\"}"}]}',
            obs3='{"status":"success","data":{"result":[]}}',
            obs4="scrape_timeout: 10s\nscrape_protocols: [OpenMetricsText1.0.0]  # not r233/r187",
            obs5="timeout ok; classic+OM",
            obs6="body_size_limit: 256KB",
            obs7="Content-Length: 1153433",
            obs8="1.1MB > 256KB; scrape rejected",
            obs9="patched 4MB",
            obs10='deployment "prom-scrape" successfully rolled out',
            obs11='{"status":"success","data":{"result":[{"value":[1710000600,"3"]}]}}',
            obs12='{"name":"Timeseries"}',
            obs13='["1710000600","1"]',
            obs14="wrote runbooks/adiru-body-size.md",
            obs15="4MB",
        ),
        _failp(
            slug="prom-body-lower-timeout-not-size",
            service="iru-align-svc",
            dashboard_uid="iru-body-timeout",
            panel="IRU state",
            query='iru_align_state{job="iru-align-svc"}',
            lie="Lowering scrape_timeout does not ingest a 1.1MB /metrics blocked by body_size_limit 256KB",
            false_lead="scrape_timeout >= scrape_interval",
            config_path="prom/iru-timeout.yaml",
            lie_path="prom/iru-scrape.yaml",
            wrong_path="prom/iru-timeout.yaml",
            reload_name="prom-scrape",
            ticket="OBS-5306",
            xfail="tests/test_iru_body.py",
            surfaces="timeout leftover vs body_size_limit",
            avoided="r233 as actual RCA",
            this_is="fail/handoff: timeout 8s, body still 256KB",
            step_note="timeout 6-10; still empty 11; late body_size_limit 12; handoff 14-15.",
            next_note="Next: StatsD mapping vs Grafana.",
            query_cmd="curl -sS -G $MIMIR/prometheus/api/v1/query --data-urlencode 'query=iru_align_state{job=\"iru-align-svc\"}'",
            false_cmd="yq '.scrape_configs[]|select(.job_name==\"iru-align-svc\").scrape_timeout' prom/iru-timeout.yaml",
            reload_cmd="kubectl -n prom rollout restart deploy/prom-scrape && kubectl -n prom rollout status deploy/prom-scrape --timeout=90s",
            requery_cmd="curl -sS -G $MIMIR/prometheus/api/v1/query --data-urlencode 'query=iru_align_state{job=\"iru-align-svc\"}'",
            denied_cmd="kubectl -n prom auth can-i patch configmap/iru-scrape --as=sre-bot",
            wrong_old="scrape_timeout: 15s",
            wrong_new="scrape_timeout: 8s",
            wrong2_old="scrape_interval: 15s",
            wrong2_new="scrape_interval: 30s",
            ticket_body="OBS-5306: iru-align-svc still empty. timeout leftover. body_size_limit 256KB vs 1.1MB. Need 4MB. No scrape RBAC.\n",
            goal="iru-align-svc dashboard iru-body-timeout IRU state empty. Restore series.",
            plan="Lower scrape_timeout (r233 leftover).",
            outcome="timeout 8s; still empty. Late body_size_limit. Handoff OBS-5306.",
            obs1='[{"uid":"iru-body-timeout","title":"iru align"}]',
            obs2='{"title":"IRU state","targets":[{"expr":"iru_align_state{job=\\"iru-align-svc\\"}"}]}',
            obs3='{"status":"success","data":{"result":[]}}',
            obs4="scrape_timeout: 15s",
            obs5="treated as r233",
            obs6="prom/iru-timeout.yaml",
            obs7="patched 8s",
            obs8='deployment "prom-scrape" successfully rolled out',
            obs9='{"status":"success","data":{"result":[]}}',
            obs10="patched interval 30s",
            obs11='{"status":"success","data":{"result":[]}}',
            obs12="prom/iru-scrape.yaml body_size_limit 256KB; Content-Length 1100000",
            obs13="no",
            obs14="wrote tickets/OBS-5306.md",
            obs15="xfail tests/test_iru_body.py",
        ),
    )
)

# r239 StatsD mapping vs Grafana
MORE.append(
    (
        _okp(
            slug="statsd-mapping-vs-grafana-name",
            service="rat-deploy-svc",
            dashboard_uid="rat-statsd-7",
            panel="RAT count",
            query='sum(rate(rat_deploy_total{job="rat-deploy-svc"}[5m]))',
            lie="statsd_exporter mapping writes statsd_rat_deploy_count while Grafana queries rat_deploy_total",
            false_lead="Prom recording rule rename / VM stream agg",
            config_path="mimir/rules/rat-record.yaml",
            lie_path="statsd/rat-mapping.yml",
            truth_name="statsd_exporter metric names",
            reload_name="statsd-exporter",
            side="unmapped statsd metrics still original names",
            surfaces="statsd_exporter mapping vs Grafana metric name",
            avoided="r229 VM stream agg rename; Prom recording leftover",
            this_is="statsd mapping name != Grafana PromQL",
            step_note="False lead recording/VM 4-5; mapping 6-8; align name 9-12.",
            query_cmd="curl -sS -G $MIMIR/prometheus/api/v1/query --data-urlencode 'query=sum(rate(rat_deploy_total{job=\"rat-deploy-svc\"}[5m]))'",
            false_cmd="yq '.groups[0].rules[0].record' mimir/rules/rat-record.yaml",
            truth_cmd="curl -sS http://statsd-exporter:9102/metrics | rg 'rat_deploy'",
            confirm_cmd="yq '.mappings[]|{match,name}' statsd/rat-mapping.yml",
            reload_cmd="kubectl -n statsd rollout restart deploy/statsd-exporter && kubectl -n statsd rollout status deploy/statsd-exporter --timeout=90s",
            requery_cmd="curl -sS -G $MIMIR/prometheus/api/v1/query --data-urlencode 'query=sum(rate(rat_deploy_total{job=\"rat-deploy-svc\"}[5m]))'",
            grafana_ok_cmd="curl -sS $GRAFANA/api/ds/query -d @/tmp/rat.json | jq '.results.A.frames[0].schema'",
            side_cmd="curl -sS -G $MIMIR/prometheus/api/v1/query --data-urlencode 'query=statsd_exporter_events_total' | jq '.data.result|length'",
            final_cmd="yq -r '.mappings[]|select(.match==\"rat.deploy\").name' statsd/rat-mapping.yml",
            patch_old="name: statsd_rat_deploy_count",
            patch_new="name: rat_deploy_total",
            runbook_path="runbooks/rat-statsd-map.md",
            runbook="# rat-deploy-svc statsd mapping\nmapping name statsd_rat_deploy_count vs Grafana rat_deploy_total. Align mapping.\nNot VM stream agg.\n",
            goal="rat-deploy-svc dashboard rat-statsd-7 RAT count empty. statsd_exporter has series. Fix the mapping lie.",
            plan="Empty → recording/VM (false) → mapping name → rat_deploy_total.",
            outcome="mapping name rat_deploy_total. rate=0.4. exporter events unchanged.",
            obs1='[{"uid":"rat-statsd-7","title":"rat deploy"}]',
            obs2='{"title":"RAT count","targets":[{"expr":"sum(rate(rat_deploy_total{job=\\"rat-deploy-svc\\"}[5m]))"}]}',
            obs3='{"status":"success","data":{"result":[]}}',
            obs4="record: null\n# no recording — not r229",
            obs5="no Prom recording",
            obs6="match: rat.deploy\nname: statsd_rat_deploy_count",
            obs7="statsd_rat_deploy_count 12",
            obs8="Grafana queries rat_deploy_total; exporter emits statsd_*",
            obs9="patched name rat_deploy_total",
            obs10='deployment "statsd-exporter" successfully rolled out',
            obs11='{"status":"success","data":{"result":[{"value":[1710000600,"0.4"]}]}}',
            obs12='{"name":"Timeseries"}',
            obs13="1",
            obs14="wrote runbooks/rat-statsd-map.md",
            obs15="rat_deploy_total",
        ),
        _failp(
            slug="statsd-vm-stream-not-mapping",
            service="hyd-qty-svc",
            dashboard_uid="hyd-statsd-vm",
            panel="hyd count",
            query='sum(rate(hyd_qty_total{job="hyd-qty-svc"}[5m]))',
            lie="Renaming a VM stream-agg output does not change statsd_exporter mapping name statsd_hyd_qty_count",
            false_lead="VictoriaMetrics stream agg renamed the series",
            config_path="vm/hyd-stream-agg.yaml",
            lie_path="statsd/hyd-mapping.yml",
            wrong_path="vm/hyd-stream-agg.yaml",
            reload_name="vminsert",
            ticket="OBS-5307",
            xfail="tests/test_hyd_statsd.py",
            surfaces="VM stream leftover vs statsd mapping",
            avoided="r229 as actual RCA",
            this_is="fail/handoff: VM output renamed, statsd still statsd_*",
            step_note="VM agg 6-10; still empty 11; late mapping 12; handoff 14-15.",
            next_note="Next: Influx Flux vs PromQL.",
            query_cmd="curl -sS -G $MIMIR/prometheus/api/v1/query --data-urlencode 'query=sum(rate(hyd_qty_total{job=\"hyd-qty-svc\"}[5m]))'",
            false_cmd="yq '.streamAggr.rules[0].output_metric' vm/hyd-stream-agg.yaml",
            reload_cmd="kubectl -n vm rollout restart deploy/vminsert && kubectl -n vm rollout status deploy/vminsert --timeout=90s",
            requery_cmd="curl -sS -G $MIMIR/prometheus/api/v1/query --data-urlencode 'query=sum(rate(hyd_qty_total{job=\"hyd-qty-svc\"}[5m]))'",
            denied_cmd="kubectl -n statsd auth can-i patch configmap/hyd-mapping --as=sre-bot",
            wrong_old="output_metric: vm_hyd_qty_total",
            wrong_new="output_metric: hyd_qty_total",
            wrong2_old="match: hyd.qty",
            wrong2_new="match: hyd.qty\n      # keep",
            ticket_body="OBS-5307: hyd-qty-svc still empty. VM leftover. statsd mapping name=statsd_hyd_qty_count. Need hyd_qty_total. No statsd RBAC.\n",
            goal="hyd-qty-svc dashboard hyd-statsd-vm hyd count empty. Restore rate.",
            plan="Rename VM stream agg output (r229 leftover).",
            outcome="VM output hyd_qty_total; still empty. Late statsd mapping. Handoff OBS-5307.",
            obs1='[{"uid":"hyd-statsd-vm","title":"hyd qty"}]',
            obs2='{"title":"hyd count","targets":[{"expr":"sum(rate(hyd_qty_total{job=\\"hyd-qty-svc\\"}[5m]))"}]}',
            obs3='{"status":"success","data":{"result":[]}}',
            obs4="output_metric: vm_hyd_qty_total",
            obs5="treated as r229",
            obs6="vm/hyd-stream-agg.yaml",
            obs7="patched output hyd_qty_total",
            obs8='deployment "vminsert" successfully rolled out',
            obs9='{"status":"success","data":{"result":[]}}',
            obs10="patched match comment",
            obs11='{"status":"success","data":{"result":[]}}',
            obs12="statsd/hyd-mapping.yml name statsd_hyd_qty_count",
            obs13="no",
            obs14="wrote tickets/OBS-5307.md",
            obs15="xfail tests/test_hyd_statsd.py",
        ),
    )
)

# r240 Influx Flux vs PromQL
MORE.append(
    (
        _okp(
            slug="influx-flux-vs-promql",
            service="brake-temp-svc",
            dashboard_uid="brake-flux-8",
            panel="brake C",
            query='avg(brake_temp_c{job="brake-temp-svc"})',
            lie="Grafana Prometheus datasource URL rewritten to Influx 2.x which speaks Flux not PromQL",
            false_lead="Mimir ingest-storage Kafka / Prom agent TSDB",
            config_path="mimir/brake.yaml",
            lie_path="grafana/provisioning/datasources/brake-prom.yaml",
            truth_name="Influx Flux query vs PromQL",
            reload_name="grafana",
            side="Influx bucket still has points",
            surfaces="Influx Flux vs PromQL datasource URL",
            avoided="r203 Mimir Kafka ingest; r160 Prom agent; r189 ClickHouse SQL",
            this_is="Prom datasource type pointed at Influx :8086",
            step_note="False lead Kafka/agent 4-5; Influx URL 6-8; retarget Mimir 9-12.",
            query_cmd="curl -sS -G $MIMIR/prometheus/api/v1/query --data-urlencode 'query=avg(brake_temp_c{job=\"brake-temp-svc\"})' | jq '{status,error}'",
            false_cmd="yq '.ingest_storage.enabled' mimir/brake.yaml",
            truth_cmd="influx query 'from(bucket:\"brake\") |> range(start:-5m) |> filter(fn:(r)=> r._measurement==\"brake_temp_c\")' | wc -l",
            confirm_cmd="yq -r '.datasources[]|{name,type,url}' grafana/provisioning/datasources/brake-prom.yaml",
            reload_cmd="kubectl -n grafana rollout restart deploy/grafana && kubectl -n grafana rollout status deploy/grafana --timeout=90s",
            requery_cmd="curl -sS -G $MIMIR/prometheus/api/v1/query --data-urlencode 'query=avg(brake_temp_c{job=\"brake-temp-svc\"})'",
            grafana_ok_cmd="curl -sS $GRAFANA/api/ds/query -d @/tmp/brake.json | jq '.results.A.frames[0].schema'",
            side_cmd="influx query 'from(bucket:\"brake\") |> count()' | tail -1",
            final_cmd="yq -r '.datasources[]|select(.name==\"brake-prom\")|{type,url}' grafana/provisioning/datasources/brake-prom.yaml",
            patch_old="url: http://influxdb:8086\n  type: prometheus",
            patch_new="url: http://mimir.obs.svc:9009/prometheus\n  type: prometheus",
            runbook_path="runbooks/brake-influx-prom.md",
            runbook="# brake-temp-svc Influx vs PromQL\nGrafana Prom type pointed at Influx :8086. Flux ≠ PromQL. Retarget Mimir.\nNot Kafka ingest-storage.\n",
            goal="brake-temp-svc dashboard brake-flux-8 brake C errors. Influx has points. Find the Flux-vs-PromQL lie.",
            plan="PromQL error → Kafka/agent (false) → URL Influx → Mimir.",
            outcome="URL is Mimir. avg=412. Influx bucket unchanged.",
            obs1='[{"uid":"brake-flux-8","title":"brake temp"}]',
            obs2='{"title":"brake C","targets":[{"expr":"avg(brake_temp_c{job=\\"brake-temp-svc\\"})"}]}',
            obs3='{"status":"error","error":"invalid Flux: avg("}',
            obs4="ingest_storage.enabled: false  # not r203",
            obs5="classic Mimir",
            obs6='{"name":"brake-prom","type":"prometheus","url":"http://influxdb:8086"}',
            obs7="88",
            obs8="Prom type + Influx URL — Flux only",
            obs9="patched url mimir /prometheus",
            obs10='deployment "grafana" successfully rolled out',
            obs11='{"status":"success","data":{"result":[{"value":[1710000600,"412"]}]}}',
            obs12='{"name":"Timeseries"}',
            obs13="88",
            obs14="wrote runbooks/brake-influx-prom.md",
            obs15='{"type":"prometheus","url":"http://mimir.obs.svc:9009/prometheus"}',
        ),
        _failp(
            slug="influx-enable-kafka-ingest",
            service="tire-press-svc",
            dashboard_uid="tire-flux-kafka",
            panel="tire PSI",
            query='avg(tire_psi{job="tire-press-svc"})',
            lie="Enabling Mimir Kafka ingest-storage does not make PromQL work against an Influx 2.x URL",
            false_lead="Mimir ingest-storage Kafka vs store-gateway",
            config_path="mimir/tire.yaml",
            lie_path="grafana/provisioning/datasources/tire-prom.yaml",
            wrong_path="mimir/tire.yaml",
            reload_name="mimir-query-frontend",
            ticket="OBS-5308",
            xfail="tests/test_tire_influx.py",
            surfaces="Kafka ingest leftover vs Influx URL",
            avoided="r203 as actual RCA",
            this_is="fail/handoff: ingest_query true, PromQL still hits Influx",
            step_note="Kafka ingest 6-10; still Flux error 11; late Influx URL 12; handoff 14-15.",
            next_note="Next: Graphite tags vs Prom labels.",
            query_cmd="curl -sS -G $MIMIR/prometheus/api/v1/query --data-urlencode 'query=avg(tire_psi{job=\"tire-press-svc\"})' | jq '{error}'",
            false_cmd="yq '.ingest_storage.enabled, .query_engine.ingest_query' mimir/tire.yaml",
            reload_cmd="kubectl -n mimir rollout restart deploy/query-frontend && kubectl -n mimir rollout status deploy/query-frontend --timeout=90s",
            requery_cmd="curl -sS -G $MIMIR/prometheus/api/v1/query --data-urlencode 'query=avg(tire_psi{job=\"tire-press-svc\"})' | jq '{error}'",
            denied_cmd="kubectl -n grafana auth can-i patch configmap/grafana-datasources --as=sre-bot",
            wrong_old="ingest_storage:\n    enabled: false",
            wrong_new="ingest_storage:\n    enabled: true",
            wrong2_old="ingest_query: false",
            wrong2_new="ingest_query: true",
            ticket_body="OBS-5308: tire-press-svc still Flux error. Kafka leftover. tire-prom url=influxdb:8086. Need Mimir. No Grafana RBAC.\n",
            goal="tire-press-svc dashboard tire-flux-kafka tire PSI errors. Restore PromQL.",
            plan="Enable Mimir ingest_query (r203 leftover).",
            outcome="ingest_query true; still Flux error. Late Influx URL. Handoff OBS-5308.",
            obs1='[{"uid":"tire-flux-kafka","title":"tire press"}]',
            obs2='{"title":"tire PSI","targets":[{"expr":"avg(tire_psi{job=\\"tire-press-svc\\"})"}]}',
            obs3='{"error":"invalid Flux"}',
            obs4="ingest_storage.enabled: false",
            obs5="treated as r203",
            obs6="mimir/tire.yaml",
            obs7="patched ingest_storage true",
            obs8='deployment "query-frontend" successfully rolled out',
            obs9='{"error":"invalid Flux"}',
            obs10="patched ingest_query true",
            obs11='{"error":"invalid Flux"}',
            obs12="tire-prom type=prometheus url=http://influxdb:8086",
            obs13="no",
            obs14="wrote tickets/OBS-5308.md",
            obs15="xfail tests/test_tire_influx.py",
        ),
    )
)

# r241 Graphite tags vs Prom labels
MORE.append(
    (
        _okp(
            slug="graphite-tag-vs-prom-label",
            service="oxygen-crew-svc",
            dashboard_uid="oxy-graphite-9",
            panel="crew O2",
            query='avg(oxygen_psi{job="oxygen-crew-svc"})',
            lie="Grafana PromQL {job=} hits Graphite tag series that use semicolon tags oxygen_psi;job=oxygen-crew-svc not Prom labels",
            false_lead="Influx Flux URL / Adaptive Metrics drop job",
            config_path="grafana/provisioning/datasources/oxy-prom.yaml",
            lie_path="graphite/oxy-relay.conf",
            truth_name="Graphite tagged name vs Prom",
            reload_name="graphite-relay",
            side="native Prom jobs still labeled",
            surfaces="Graphite semicolon tags vs Prom labels",
            avoided="r240 Influx Flux; r176 Adaptive Metrics; r228 kminion job",
            this_is="Graphite tag format not Prom labels; carbon-relay without graph-explorer mapping",
            step_note="False lead Influx/AM 4-5; Graphite tags 6-8; carbon-relay Prom map 9-12.",
            query_cmd="curl -sS -G $MIMIR/prometheus/api/v1/query --data-urlencode 'query=avg(oxygen_psi{job=\"oxygen-crew-svc\"})'",
            false_cmd="yq -r '.datasources[]|{name,type,url}' grafana/provisioning/datasources/oxy-prom.yaml",
            truth_cmd="curl -sS $GRAPHITE/metrics/find?query=oxygen_psi* | jq '.[0].id'",
            confirm_cmd="rg 'tag-support|prometheus' graphite/oxy-relay.conf",
            reload_cmd="kubectl -n graphite rollout restart deploy/carbon-relay && kubectl -n graphite rollout status deploy/carbon-relay --timeout=90s",
            requery_cmd="curl -sS -G $MIMIR/prometheus/api/v1/query --data-urlencode 'query=avg(oxygen_psi{job=\"oxygen-crew-svc\"})'",
            grafana_ok_cmd="curl -sS $GRAFANA/api/ds/query -d @/tmp/oxy.json | jq '.results.A.frames[0].schema'",
            side_cmd="curl -sS -G $MIMIR/prometheus/api/v1/query --data-urlencode 'query=up{job=\"ssr-meal-svc\"}' | jq '.data.result[0].value'",
            final_cmd="rg 'prometheus_conversion' graphite/oxy-relay.conf",
            patch_old="ENABLE_TAGS = False",
            patch_new="ENABLE_TAGS = True\nPROMETHEUS_CONVERSION = True",
            runbook_path="runbooks/oxy-graphite-tags.md",
            runbook="# oxygen-crew-svc Graphite vs Prom\nSeries stored as oxygen_psi;job=…. Enable Prometheus conversion on carbon-relay.\nNot Influx Flux.\n",
            goal="oxygen-crew-svc dashboard oxy-graphite-9 crew O2 empty. Graphite has tagged series. Fix the tag lie.",
            plan="Empty PromQL → Influx/AM (false) → Graphite ;tags → PROMETHEUS_CONVERSION.",
            outcome="conversion on. avg=1800. native Prom jobs unchanged.",
            obs1='[{"uid":"oxy-graphite-9","title":"crew oxygen"}]',
            obs2='{"title":"crew O2","targets":[{"expr":"avg(oxygen_psi{job=\\"oxygen-crew-svc\\"})"}]}',
            obs3='{"status":"success","data":{"result":[]}}',
            obs4='{"name":"oxy-prom","type":"prometheus","url":"http://mimir.obs.svc:9009/prometheus"}\n# real Mimir — not r240',
            obs5="datasource is Mimir",
            obs6="ENABLE_TAGS = False",
            obs7='"oxygen_psi;job=oxygen-crew-svc;deck=fd"',
            obs8="Graphite tags not Prom labels",
            obs9="patched ENABLE_TAGS + PROMETHEUS_CONVERSION",
            obs10='deployment "carbon-relay" successfully rolled out',
            obs11='{"status":"success","data":{"result":[{"value":[1710000600,"1800"]}]}}',
            obs12='{"name":"Timeseries"}',
            obs13='["1710000600","1"]',
            obs14="wrote runbooks/oxy-graphite-tags.md",
            obs15="PROMETHEUS_CONVERSION = True",
        ),
        _failp(
            slug="graphite-retarget-influx",
            service="oxygen-pax-svc",
            dashboard_uid="oxypax-graphite-influx",
            panel="pax O2",
            query='avg(oxygen_pax_psi{job="oxygen-pax-svc"})',
            lie="Pointing Grafana at Influx does not convert Graphite semicolon tags into Prom labels",
            false_lead="Grafana Prom datasource is Influx Flux",
            config_path="grafana/provisioning/datasources/oxypax-prom.yaml",
            lie_path="graphite/oxypax-relay.conf",
            wrong_path="grafana/provisioning/datasources/oxypax-prom.yaml",
            reload_name="grafana",
            ticket="OBS-5309",
            xfail="tests/test_oxypax_graphite.py",
            surfaces="Influx leftover vs Graphite tags",
            avoided="r240 as actual RCA",
            this_is="fail/handoff: Influx URL, Graphite still untagged for Prom",
            step_note="Influx URL 6-10; still empty 11; late Graphite tags 12; handoff 14-15.",
            next_note="Next: kube-state-metrics labels.",
            query_cmd="curl -sS -G $MIMIR/prometheus/api/v1/query --data-urlencode 'query=avg(oxygen_pax_psi{job=\"oxygen-pax-svc\"})'",
            false_cmd="yq -r '.datasources[]|{name,url}' grafana/provisioning/datasources/oxypax-prom.yaml",
            reload_cmd="kubectl -n grafana rollout restart deploy/grafana && kubectl -n grafana rollout status deploy/grafana --timeout=90s",
            requery_cmd="curl -sS -G $MIMIR/prometheus/api/v1/query --data-urlencode 'query=avg(oxygen_pax_psi{job=\"oxygen-pax-svc\"})'",
            denied_cmd="kubectl -n graphite auth can-i patch configmap/oxypax-relay --as=sre-bot",
            wrong_old="url: http://mimir.obs.svc:9009/prometheus",
            wrong_new="url: http://influxdb:8086",
            wrong2_old="type: prometheus",
            wrong2_new="type: prometheus\n  jsonData:\n    timeInterval: 15s",
            ticket_body="OBS-5309: oxygen-pax-svc still empty. Influx leftover. Graphite ENABLE_TAGS False. Need PROMETHEUS_CONVERSION. No carbon RBAC.\n",
            goal="oxygen-pax-svc dashboard oxypax-graphite-influx pax O2 empty. Restore series.",
            plan="Point Grafana at Influx (r240 leftover).",
            outcome="Influx URL; still empty/Flux error. Late Graphite tags. Handoff OBS-5309.",
            obs1='[{"uid":"oxypax-graphite-influx","title":"pax oxygen"}]',
            obs2='{"title":"pax O2","targets":[{"expr":"avg(oxygen_pax_psi{job=\\"oxygen-pax-svc\\"})"}]}',
            obs3='{"status":"success","data":{"result":[]}}',
            obs4='{"name":"oxypax-prom","url":"http://mimir.obs.svc:9009/prometheus"}',
            obs5="already Mimir — treated as maybe Influx",
            obs6="grafana/provisioning/datasources/oxypax-prom.yaml",
            obs7="patched url influxdb",
            obs8='deployment "grafana" successfully rolled out',
            obs9='{"status":"success","data":{"result":[]}}',
            obs10="patched timeInterval",
            obs11='{"status":"success","data":{"result":[]}}',
            obs12="graphite/oxypax-relay.conf ENABLE_TAGS False; series oxygen_pax_psi;job=oxygen-pax-svc",
            obs13="no",
            obs14="wrote tickets/OBS-5309.md",
            obs15="xfail tests/test_oxypax_graphite.py",
        ),
    )
)

# r242 kube-state-metrics labels
MORE.append(
    (
        _okp(
            slug="ksm-pod-labels-vs-grafana",
            service="pack-valve-svc",
            dashboard_uid="pack-ksm-1",
            panel="ready pods",
            query='kube_pod_labels{label_app="pack-valve-svc"}',
            lie="kube-state-metrics metric_labels_allowlist omits app so kube_pod_labels has no label_app; Grafana join is empty",
            false_lead="k8sattributes overwrite / Adaptive Metrics drop",
            config_path="otelcol/pack-k8sattr.yaml",
            lie_path="ksm/pack-values.yaml",
            truth_name="KSM allowlist vs kube_pod_labels",
            reload_name="kube-state-metrics",
            side="kube_pod_status_ready still labeled by namespace",
            surfaces="kube-state-metrics label allowlist vs Grafana label_app",
            avoided="r186 k8sattributes; r176 Adaptive Metrics; r222 Istio name",
            this_is="KSM metric_labels_allowlist dropped app",
            step_note="False lead k8sattr/AM 4-5; allowlist 6-8; add app 9-12.",
            query_cmd="curl -sS -G $MIMIR/prometheus/api/v1/query --data-urlencode 'query=kube_pod_labels{label_app=\"pack-valve-svc\"}'",
            false_cmd="yq '.processors.k8sattributes' otelcol/pack-k8sattr.yaml",
            truth_cmd="curl -sS http://kube-state-metrics:8080/metrics | rg 'kube_pod_labels{.*pack-valve'",
            confirm_cmd="yq '.metricLabelsAllowlist' ksm/pack-values.yaml",
            reload_cmd="kubectl -n kube-system rollout restart deploy/kube-state-metrics && kubectl -n kube-system rollout status deploy/kube-state-metrics --timeout=90s",
            requery_cmd="curl -sS -G $MIMIR/prometheus/api/v1/query --data-urlencode 'query=kube_pod_labels{label_app=\"pack-valve-svc\"}'",
            grafana_ok_cmd="curl -sS $GRAFANA/api/ds/query -d @/tmp/pack.json | jq '.results.A.frames[0].schema'",
            side_cmd="curl -sS -G $MIMIR/prometheus/api/v1/query --data-urlencode 'query=kube_pod_status_ready{namespace=\"pack\"}' | jq '.data.result|length'",
            final_cmd="yq -r '.metricLabelsAllowlist[]' ksm/pack-values.yaml",
            patch_old="metricLabelsAllowlist:\n  - pods=[env,version]",
            patch_new="metricLabelsAllowlist:\n  - pods=[app,env,version]",
            runbook_path="runbooks/pack-ksm-labels.md",
            runbook="# pack-valve-svc KSM allowlist\nlabel_app missing because allowlist omitted app. Add app.\nNot k8sattributes.\n",
            goal="pack-valve-svc dashboard pack-ksm-1 ready pods empty. Pods exist. Find the allowlist lie.",
            plan="Empty label_app → k8sattr (false) → KSM allowlist env,version → add app.",
            outcome="allowlist includes app. 3 series. status_ready unchanged.",
            obs1='[{"uid":"pack-ksm-1","title":"pack valve pods"}]',
            obs2='{"title":"ready pods","targets":[{"expr":"kube_pod_labels{label_app=\\"pack-valve-svc\\"}"}]}',
            obs3='{"status":"success","data":{"result":[]}}',
            obs4="k8sattributes: {passthrough: true}  # not r186",
            obs5="k8sattr passthrough",
            obs6="metricLabelsAllowlist:\n  - pods=[env,version]",
            obs7='kube_pod_labels{namespace="pack",label_env="prod"} 1  # no label_app',
            obs8="allowlist omitted app",
            obs9="patched pods=[app,env,version]",
            obs10='deployment "kube-state-metrics" successfully rolled out',
            obs11='{"status":"success","data":{"result":[{"metric":{"label_app":"pack-valve-svc"},"value":[1710000600,"1"]}]}}',
            obs12='{"name":"Timeseries"}',
            obs13="3",
            obs14="wrote runbooks/pack-ksm-labels.md",
            obs15="pods=[app,env,version]",
        ),
        _failp(
            slug="ksm-ottl-set-label-app",
            service="recirc-fan-svc",
            dashboard_uid="recirc-ksm-ottl",
            panel="fan pods",
            query='kube_pod_labels{label_app="recirc-fan-svc"}',
            lie="OTTL set(label_app) on the collector does not add kube_pod_labels series that KSM never exported",
            false_lead="k8sattributes/OTTL overwrite of service.name",
            config_path="otelcol/recirc-k8sattr.yaml",
            lie_path="ksm/recirc-values.yaml",
            wrong_path="otelcol/recirc-k8sattr.yaml",
            reload_name="otelcol-recirc",
            ticket="OBS-5310",
            xfail="tests/test_recirc_ksm.py",
            surfaces="OTTL leftover vs KSM allowlist",
            avoided="r186 as actual RCA",
            this_is="fail/handoff: OTTL set label_app, KSM still omits app",
            step_note="OTTL 6-10; still empty 11; late KSM allowlist 12; handoff 14-15.",
            next_note="Next: OTel resourcedetection vs service.name.",
            query_cmd="curl -sS -G $MIMIR/prometheus/api/v1/query --data-urlencode 'query=kube_pod_labels{label_app=\"recirc-fan-svc\"}'",
            false_cmd="yq '.processors.transform' otelcol/recirc-k8sattr.yaml",
            reload_cmd="kubectl -n otel rollout restart deploy/otelcol-recirc && kubectl -n otel rollout status deploy/otelcol-recirc --timeout=90s",
            requery_cmd="curl -sS -G $MIMIR/prometheus/api/v1/query --data-urlencode 'query=kube_pod_labels{label_app=\"recirc-fan-svc\"}'",
            denied_cmd="kubectl -n kube-system auth can-i patch deploy/kube-state-metrics --as=sre-bot",
            wrong_old="processors: [k8sattributes, batch]",
            wrong_new="processors: [k8sattributes, transform, batch]",
            wrong2_old="transform: {}",
            wrong2_new="transform:\n    metric_statements:\n      - set(datapoint.attributes[\"label_app\"], \"recirc-fan-svc\")",
            ticket_body="OBS-5310: recirc-fan-svc label_app still empty. OTTL leftover. KSM allowlist pods=[env]. Need app. No KSM RBAC.\n",
            goal="recirc-fan-svc dashboard recirc-ksm-ottl fan pods empty. Restore label_app.",
            plan="OTTL set label_app (r186 leftover).",
            outcome="OTTL on; still empty. Late KSM allowlist. Handoff OBS-5310.",
            obs1='[{"uid":"recirc-ksm-ottl","title":"recirc fan pods"}]',
            obs2='{"title":"fan pods","targets":[{"expr":"kube_pod_labels{label_app=\\"recirc-fan-svc\\"}"}]}',
            obs3='{"status":"success","data":{"result":[]}}',
            obs4="processors: [k8sattributes, batch]",
            obs5="treated as r186",
            obs6="otelcol/recirc-k8sattr.yaml",
            obs7="patched add transform",
            obs8='deployment "otelcol-recirc" successfully rolled out',
            obs9='{"status":"success","data":{"result":[]}}',
            obs10="patched set label_app",
            obs11='{"status":"success","data":{"result":[]}}',
            obs12="ksm/recirc-values.yaml metricLabelsAllowlist pods=[env]  # no app",
            obs13="no",
            obs14="wrote tickets/OBS-5310.md",
            obs15="xfail tests/test_recirc_ksm.py",
        ),
    )
)

# r243 OTel resourcedetection vs service.name
MORE.append(
    (
        _okp(
            slug="otel-resourcedetector-vs-svcname",
            service="galley-power-svc",
            dashboard_uid="galley-rd-2",
            panel="app traces",
            query='{resource.service.name="galley-power-svc"}',
            lie="resourcedetection processor gcp detector overwrites service.name with gce.instance.name so Tempo search by app is empty",
            false_lead="k8sattributes overwrite from deployment / Istio sidecar name",
            config_path="otelcol/galley-k8sattr.yaml",
            lie_path="otelcol/galley-rd.yaml",
            truth_name="resource.service.name after detectors",
            reload_name="otelcol-galley",
            side="detectors still set cloud.provider",
            surfaces="OTel resourcedetection gcp vs service.name",
            avoided="r186 k8sattributes; r222 Istio sidecar; r174 routing filter",
            this_is="gcp detector overwrites service.name with instance name",
            step_note="False lead k8sattr/Istio 4-5; gcp detector 6-8; override=false 9-12.",
            query_cmd="curl -sS -G $TEMPO/api/search --data-urlencode 'q={resource.service.name=\"galley-power-svc\"}' | jq '.traces|length'",
            false_cmd="yq '.processors.k8sattributes' otelcol/galley-k8sattr.yaml",
            truth_cmd="curl -sS -G $TEMPO/api/search --data-urlencode 'q={resource.service.name=\"gce-galley-power-0\"}' | jq '{n:(.traces|length),name:.traces[0].rootServiceName}'",
            confirm_cmd="yq '.processors.resourcedetection' otelcol/galley-rd.yaml",
            reload_cmd="kubectl -n otel rollout restart deploy/otelcol-galley && kubectl -n otel rollout status deploy/otelcol-galley --timeout=90s",
            requery_cmd="curl -sS -G $TEMPO/api/search --data-urlencode 'q={resource.service.name=\"galley-power-svc\"}' | jq '.traces|length'",
            grafana_ok_cmd="curl -sS $GRAFANA/api/ds/query -d @/tmp/galley.json | jq '.results.A.frames[0].schema'",
            side_cmd="curl -sS -G $TEMPO/api/search --data-urlencode 'q={resource.cloud.provider=\"gcp\"}' | jq '.traces|length'",
            final_cmd="yq -r '.processors.resourcedetection.detectors, .processors.resourcedetection.override' otelcol/galley-rd.yaml",
            patch_old="detectors: [gcp, env]\n    override: true",
            patch_new="detectors: [gcp, env]\n    override: false",
            runbook_path="runbooks/galley-resourcedetector.md",
            runbook="# galley-power-svc resourcedetection\ngcp detector override true replaced service.name with GCE instance. override false.\nNot k8sattributes.\n",
            goal="galley-power-svc dashboard galley-rd-2 app traces empty. GCP instance name has spans. Fix the detector lie.",
            plan="Empty app search → k8sattr (false) → gcp override true → override false.",
            outcome="override false. 22 traces under galley-power-svc. cloud.provider still gcp.",
            obs1='[{"uid":"galley-rd-2","title":"galley power traces"}]',
            obs2='{"title":"app traces","targets":[{"query":"{resource.service.name=\\"galley-power-svc\\"}"}]}',
            obs3="0",
            obs4="k8sattributes: {passthrough: true}  # not r186",
            obs5="k8sattr passthrough",
            obs6="detectors: [gcp, env]\noverride: true",
            obs7='{"n":22,"name":"gce-galley-power-0"}',
            obs8="gcp detector overwrote service.name",
            obs9="patched override false",
            obs10='deployment "otelcol-galley" successfully rolled out',
            obs11="22",
            obs12='{"name":"Traces"}',
            obs13="22",
            obs14="wrote runbooks/galley-resourcedetector.md",
            obs15="[gcp, env] false",
        ),
        _failp(
            slug="otel-rd-istio-customtags",
            service="seat-motor-svc",
            dashboard_uid="seat-rd-istio",
            panel="seat traces",
            query='{resource.service.name="seat-motor-svc"}',
            lie="Istio Telemetry customTags does not stop resourcedetection gcp override from replacing service.name with the GCE instance",
            false_lead="Istio sidecar service.name=istio-proxy",
            config_path="istio/seat-telemetry.yaml",
            lie_path="otelcol/seat-rd.yaml",
            wrong_path="istio/seat-telemetry.yaml",
            reload_name="istiod",
            ticket="OBS-5311",
            xfail="tests/test_seat_rd.py",
            surfaces="Istio leftover vs gcp resourcedetection override",
            avoided="r222 as actual RCA",
            this_is="fail/handoff: Istio tags on, gcp override still true",
            step_note="Istio tags 6-10; still 0 11; late gcp override 12; handoff 14-15.",
            next_note="Next: Loki querier max_concurrent.",
            query_cmd="curl -sS -G $TEMPO/api/search --data-urlencode 'q={resource.service.name=\"seat-motor-svc\"}' | jq '.traces|length'",
            false_cmd="yq '.spec.tracing' istio/seat-telemetry.yaml",
            reload_cmd="kubectl -n istio-system rollout restart deploy/istiod && kubectl -n istio-system rollout status deploy/istiod --timeout=90s",
            requery_cmd="curl -sS -G $TEMPO/api/search --data-urlencode 'q={resource.service.name=\"seat-motor-svc\"}' | jq '.traces|length'",
            denied_cmd="kubectl -n otel auth can-i patch deploy/otelcol-seat --as=sre-bot",
            wrong_old="customTags: {}",
            wrong_new="customTags:\n        service.name:\n          value: seat-motor-svc",
            wrong2_old="providers: []",
            wrong2_new="providers: [otel]",
            ticket_body="OBS-5311: seat-motor-svc Tempo still 0 on app name. Istio leftover. resourcedetection override true → gce-seat-motor-0. Need override false. No collector RBAC.\n",
            goal="seat-motor-svc dashboard seat-rd-istio seat traces empty. Restore app search.",
            plan="Set Istio customTags (r222 leftover).",
            outcome="Istio tags; still 0. Late gcp override true. Handoff OBS-5311.",
            obs1='[{"uid":"seat-rd-istio","title":"seat motor traces"}]',
            obs2='{"title":"seat traces","targets":[{"query":"{resource.service.name=\\"seat-motor-svc\\"}"}]}',
            obs3="0",
            obs4="customTags: {}",
            obs5="treated as r222",
            obs6="istio/seat-telemetry.yaml",
            obs7="patched customTags",
            obs8='deployment "istiod" successfully rolled out',
            obs9="0",
            obs10="patched providers otel",
            obs11="0",
            obs12="otelcol/seat-rd.yaml detectors [gcp] override true; rootServiceName gce-seat-motor-0",
            obs13="no",
            obs14="wrote tickets/OBS-5311.md",
            obs15="xfail tests/test_seat_rd.py",
        ),
    )
)

# r244 Loki querier max_concurrent
MORE.append(
    (
        _okp(
            slug="loki-querier-max-concurrent",
            service="cabin-press-svc",
            dashboard_uid="press-qconc-3",
            panel="press errors",
            query='{job="cabin-press-svc"} |= "outflow_fault"',
            lie="querier max_concurrent 1 plus frontend max_outstanding_per_tenant 1 429s Grafana; logs exist when queried with limit=1",
            false_lead="bloom skip / max_chunk_age unflushed",
            config_path="loki/press-bloom.yaml",
            lie_path="loki/press-querier.yaml",
            truth_name="querier inflight vs 429",
            reload_name="loki-querier",
            side="single-panel dashboards still work",
            surfaces="Loki querier max_concurrent vs Grafana 429",
            avoided="r165 bloom; r235 max_chunk_age; r191 OS URL",
            this_is="max_concurrent 1 429s the dashboard's 8 panels",
            step_note="False lead bloom/chunk 4-5; 429 max_concurrent 6-8; raise 16 9-12.",
            query_cmd="curl -sS -G $LOKI/loki/api/v1/query_range --data-urlencode 'query={job=\"cabin-press-svc\"} |= \"outflow_fault\"' | jq '{status,error}'",
            false_cmd="yq '.bloom_gateway,.ingester.max_chunk_age' loki/press-bloom.yaml",
            truth_cmd="curl -sS -G $LOKI/loki/api/v1/query_range --data-urlencode 'query={job=\"cabin-press-svc\"} |= \"outflow_fault\"' --data-urlencode 'limit=1' | jq '.data.result|length'",
            confirm_cmd="yq '.querier.max_concurrent, .query_range.max_outstanding_per_tenant' loki/press-querier.yaml",
            reload_cmd="kubectl -n loki rollout restart deploy/loki-querier && kubectl -n loki rollout status deploy/loki-querier --timeout=90s",
            requery_cmd="curl -sS -G $LOKI/loki/api/v1/query_range --data-urlencode 'query={job=\"cabin-press-svc\"} |= \"outflow_fault\"' | jq '.data.result|length'",
            grafana_ok_cmd="curl -sS $GRAFANA/api/ds/query -d @/tmp/press.json | jq '.results.A.frames[0].schema'",
            side_cmd="curl -sS -G $LOKI/loki/api/v1/query_range --data-urlencode 'query={job=\"ssr-meal-svc\"} |= \"error\"' --data-urlencode 'limit=1' | jq '.data.result|length'",
            final_cmd="yq -r '.querier.max_concurrent' loki/press-querier.yaml",
            patch_old="max_concurrent: 1\n  max_outstanding_per_tenant: 1",
            patch_new="max_concurrent: 16\n  max_outstanding_per_tenant: 32",
            runbook_path="runbooks/press-qconc.md",
            runbook="# cabin-press-svc querier max_concurrent\nDashboard 8 panels vs max_concurrent 1 → 429. Raise. Not bloom.\n",
            goal="cabin-press-svc dashboard press-qconc-3 press errors 429s. limit=1 works. Find the concurrency lie.",
            plan="429 → bloom/chunk (false) → max_concurrent 1 → 16.",
            outcome="max_concurrent 16. 11 streams. limit=1 jobs unchanged.",
            obs1='[{"uid":"press-qconc-3","title":"cabin press logs"}]',
            obs2='{"title":"press errors","targets":[{"expr":"{job=\\"cabin-press-svc\\"} |= \\"outflow_fault\\""}]}',
            obs3='{"status":"error","error":"429 too many outstanding requests"}',
            obs4="bloom_gateway.enabled: false\nmax_chunk_age: 2h  # not r165/r235",
            obs5="blooms off; chunks flush",
            obs6="max_concurrent: 1\nmax_outstanding_per_tenant: 1",
            obs7="1",
            obs8="limit=1 works; dashboard 8 panels 429",
            obs9="patched 16 / 32",
            obs10='deployment "loki-querier" successfully rolled out',
            obs11="11",
            obs12='{"name":"Logs"}',
            obs13="1",
            obs14="wrote runbooks/press-qconc.md",
            obs15="16",
        ),
        _failp(
            slug="loki-qconc-rebuild-blooms",
            service="outflow-valve-svc",
            dashboard_uid="outflow-qconc-bloom",
            panel="outflow errors",
            query='{job="outflow-valve-svc"} |= "stuck_open"',
            lie="Rebuilding blooms does not clear Loki querier 429s from max_concurrent 1",
            false_lead="Loki bloom-gateway skip_factor",
            config_path="loki/outflow-bloom.yaml",
            lie_path="loki/outflow-querier.yaml",
            wrong_path="loki/outflow-bloom.yaml",
            reload_name="loki-bloom-gateway",
            ticket="OBS-5312",
            xfail="tests/test_outflow_qconc.py",
            surfaces="bloom leftover vs querier max_concurrent",
            avoided="r165 as actual RCA",
            this_is="fail/handoff: blooms off, still 429",
            step_note="blooms 6-10; still 429 11; late max_concurrent 12; handoff 14-15.",
            next_note="Catalog r233-r244. Keep unique vs r109-r232.",
            query_cmd="curl -sS -G $LOKI/loki/api/v1/query_range --data-urlencode 'query={job=\"outflow-valve-svc\"} |= \"stuck_open\"' | jq '{status,error}'",
            false_cmd="yq '.bloom_gateway' loki/outflow-bloom.yaml",
            reload_cmd="kubectl -n loki rollout restart deploy/bloom-gateway && kubectl -n loki rollout status deploy/bloom-gateway --timeout=90s",
            requery_cmd="curl -sS -G $LOKI/loki/api/v1/query_range --data-urlencode 'query={job=\"outflow-valve-svc\"} |= \"stuck_open\"' | jq '{status,error}'",
            denied_cmd="kubectl -n loki auth can-i patch deploy/loki-querier --as=sre-bot",
            wrong_old="skip_factor: 3",
            wrong_new="skip_factor: 0",
            wrong2_old="enabled: true",
            wrong2_new="enabled: false",
            ticket_body="OBS-5312: outflow-valve-svc still 429. bloom leftover. querier max_concurrent 1. Need 16. No querier RBAC.\n",
            goal="outflow-valve-svc dashboard outflow-qconc-bloom outflow errors 429s. Restore logs.",
            plan="Disable blooms (r165 leftover).",
            outcome="blooms off; still 429. Late max_concurrent 1. Handoff OBS-5312.",
            obs1='[{"uid":"outflow-qconc-bloom","title":"outflow logs"}]',
            obs2='{"title":"outflow errors","targets":[{"expr":"{job=\\"outflow-valve-svc\\"} |= \\"stuck_open\\""}]}',
            obs3='{"status":"error","error":"429 too many outstanding requests"}',
            obs4="skip_factor: 3",
            obs5="treated as r165",
            obs6="loki/outflow-bloom.yaml",
            obs7="patched skip 0",
            obs8='deployment "bloom-gateway" successfully rolled out',
            obs9='{"status":"error","error":"429 too many outstanding requests"}',
            obs10="patched bloom enabled false",
            obs11='{"status":"error","error":"429 too many outstanding requests"}',
            obs12="loki/outflow-querier.yaml max_concurrent 1 max_outstanding_per_tenant 1",
            obs13="no",
            obs14="wrote tickets/OBS-5312.md",
            obs15="xfail tests/test_outflow_qconc.py",
        ),
    )
)
