"""Observability leftover16 plants r1436+.

BAN r1435 es-http-bind-drop-leftover, leftover15 prior mill, leftover12 lock-basin,
r875 tempo-ingester-max-traces-per-user-one, r384 otel-forward-connector,
PagerDuty orch, Opsgenie alias, Rootly urgency.
"""

from mill_plants_t import _leftover_pair

MORE = []
ROUND_PAIRS = {}


def _emit(round_n, **kwargs):
    dest = []
    _leftover_pair(n=str(round_n), dest=dest, **kwargs)
    MORE.extend(dest)
    ROUND_PAIRS[round_n] = dest[0]


def _l16(n, **kw):
    vendor, noun, prefix = kw["vendor"], kw["noun"], kw["prefix"]
    ok_svc, bad_svc = f"leat-{noun}-svc", f"lade-{noun}-svc"
    tag = noun.replace("-", "")[:8]
    vtag = prefix.replace("-", "")[:5]
    ok_dash, bad_dash = f"{tag}-{vtag}-{n}", f"e{tag[:7]}-{vtag}-fl"
    lie_core = kw["lie_core"]
    _emit(
        n,
        kind="grafana",
        ok_slug=kw["ok_slug"],
        bad_slug=kw["bad_slug"],
        ok_svc=ok_svc,
        bad_svc=bad_svc,
        ok_dash=ok_dash,
        bad_dash=bad_dash,
        panel=kw["panel"],
        metric="",
        needle=kw["needle"],
        lie=(
            f"{vendor} leftover leftover leftover leftover leftover leftover leftover leftover leftover leftover leftover leftover leftover leftover leftover leftover {lie_core} "
            f"so Grafana dashboard {ok_dash} is empty while the source still 202"
        ),
        bad_lie=(
            f"{kw['false_lead']} does not restore leftover leftover leftover leftover leftover leftover leftover leftover leftover leftover leftover leftover leftover leftover leftover leftover {lie_core}"
        ),
        false_lead=kw["false_lead"],
        avoided=kw["avoided"],
        this_is=f"{vendor} leftover leftover leftover leftover leftover leftover leftover leftover leftover leftover leftover leftover leftover leftover leftover leftover {lie_core}",
        ticket=f"OBS-{ 9700 + (n - 1436) }",
        knob=kw["knob"],
        old=kw["old"],
        new=kw["new"],
        wrong_knob=kw["wrong_knob"],
        wrong_old=kw["wrong_old"],
        wrong_new=kw["wrong_new"],
        wrong2_old=kw["wrong2_old"],
        wrong2_new=kw["wrong2_new"],
        reload="grafana",
        config_path=f"{prefix}/{tag}-false.yaml",
        lie_path=f"{prefix}/{tag}-lie.yaml",
        bad_config=f"{prefix}/e{tag[:7]}-false.yaml",
        bad_lie_path=f"{prefix}/e{tag[:7]}-lie.yaml",
    )


BAN = (
    "r1435 es-http-bind-drop-leftover; leftover15 ford/creek r1348-r1435; leftover14 canal/reach; leftover13 dam/weir; r875 tempo; r384 otel-forward; PagerDuty orch; Opsgenie alias; r515 Rootly urgency"
)

SPECS = [
    dict(vendor='Heartbeat', ok_slug='hbeat-http-bind-drop-leftover', bad_slug='hbeat-bind-raise-mon-not-addr', noun='millpond', panel='Heartbeat', needle='hbeat_up', lie_core='http leftover http.host 127.0.0.1 so Grafana is empty while monitors still up', false_lead='Heartbeat monitor leftover', avoided=BAN, knob='.http.host', old='host: 127.0.0.1', new='host: 0.0.0.0', wrong_knob='.monitors[0].name', wrong_old='name: sandbox', wrong_new='name: hangar', wrong2_old='path.data: /tmp', wrong2_new='path.data: /var/lib/heartbeat', prefix='hbeat'),
    dict(vendor='Packetbeat', ok_slug='pbeat-interface-drop-leftover', bad_slug='pbeat-ifc-raise-prot-not-iface', noun='goit', panel='Packetbeat', needle='pbeat_up', lie_core='iface leftover packetbeat.interfaces.device any plus procs off so Grafana is empty', false_lead='Packetbeat proto leftover', avoided=BAN, knob='.packetbeat.interfaces.device', old='device: lo', new='device: any', wrong_knob='.protocols.http.ports', wrong_old='ports: []', wrong_new='ports: [80, 443]', wrong2_old='path.data: /tmp', wrong2_new='path.data: /var/lib/packetbeat', prefix='pbeat'),
    dict(vendor='Auditbeat', ok_slug='abeat-audit-off-leftover', bad_slug='abeat-aud-raise-rule-not-enable', noun='pentrough', panel='Auditbeat', needle='abeat_up', lie_core='audit leftover auditd.enabled=false so Grafana is empty while file_integrity still runs', false_lead='Auditbeat rule leftover', avoided=BAN, knob='.auditd.enabled', old='enabled: false', new='enabled: true', wrong_knob='.auditd.rules', wrong_old='rules: []', wrong_new='rules: [-w /etc -p wa]', wrong2_old='path.data: /tmp', wrong2_new='path.data: /var/lib/auditbeat', prefix='abeat'),
    dict(vendor='Winlogbeat', ok_slug='wbeat-event-log-off-leftover', bad_slug='wbeat-evt-raise-name-not-enable', noun='launder3', panel='Winlogbeat', needle='wbeat_up', lie_core='event leftover winlogbeat.event_logs empty so Grafana is empty while the agent still runs', false_lead='Winlogbeat name leftover', avoided=BAN, knob='.winlogbeat.event_logs', old='event_logs: []', new='event_logs: [{name: Application}]', wrong_knob='.name', wrong_old='name: sandbox', wrong_new='name: hangar', wrong2_old='path.data: /tmp', wrong2_new='path.data: /var/lib/winlogbeat', prefix='wbeat'),
    dict(vendor='Elastic Agent', ok_slug='eagent-http-bind-drop-leftover', bad_slug='eagent-bind-raise-fleet-not-addr', noun='forebay3', panel='Elastic Agent', needle='eagent_up', lie_core='http leftover agent.monitoring.http.host 127.0.0.1 so Grafana is empty while enroll still 200', false_lead='Elastic Agent fleet leftover', avoided=BAN, knob='.agent.monitoring.http.host', old='host: 127.0.0.1', new='host: 0.0.0.0', wrong_knob='.fleet.host', wrong_old='host: https://sandbox', wrong_new='host: https://hangar', wrong2_old='agent.id: sandbox', wrong2_new='agent.id: hangar', prefix='eagent'),
    dict(vendor='ZooKeeper', ok_slug='zkpr-metrics-provider-off-leftover', bad_slug='zkpr-met-raise-data-not-enable', noun='fosse', panel='ZK metrics', needle='zkpr_up', lie_core='metrics leftover metricsProvider.className null so Grafana is empty while quorum still votes', false_lead='ZooKeeper data leftover', avoided=BAN, knob='.metricsProvider.className', old='className: ', new='className: org.apache.zookeeper.metrics.prometheus.PrometheusMetricsProvider', wrong_knob='.dataDir', wrong_old='dataDir: /tmp', wrong_new='dataDir: /var/lib/zookeeper', wrong2_old='clientPort: 0', wrong2_new='clientPort: 2181', prefix='zkpr'),
    dict(vendor='Unbound', ok_slug='unbnd-extended-stats-off-leftover', bad_slug='unbnd-stat-raise-if-not-enable', noun='race2', panel='Unbound stats', needle='unbnd_up', lie_core='stats leftover statistics-interval 0 so Grafana is empty while queries still resolve', false_lead='Unbound interface leftover', avoided=BAN, knob='.statistics-interval', old='statistics-interval: 0', new='statistics-interval: 60', wrong_knob='.interface', wrong_old='interface: 127.0.0.1', wrong_new='interface: 0.0.0.0', wrong2_old='logfile: /dev/null', wrong2_new='logfile: /var/log/unbound.log', prefix='unbnd'),
    dict(vendor='BIND', ok_slug='bindx-statistics-off-leftover', bad_slug='bindx-stat-raise-acl-not-enable', noun='wheelpit', panel='BIND stats', needle='bindx_up', lie_core='stats leftover statistics-channels empty so Grafana is empty while named still 53', false_lead='BIND acl leftover', avoided=BAN, knob='.statistics-channels', old='statistics-channels: []', new='statistics-channels: [{inet: 0.0.0.0 port 8053}]', wrong_knob='.allow-query', wrong_old='allow-query: {localhost;}', wrong_new='allow-query: {any;}', wrong2_old='directory: /tmp', wrong2_new='directory: /var/cache/bind', prefix='bindx'),
    dict(vendor='Knot', ok_slug='knotx-stats-mod-off-leftover', bad_slug='knotx-mod-raise-listen-not-enable', noun='stonefloor', panel='Knot stats', needle='knotx_up', lie_core='mod leftover mod-stats off so Grafana is empty while DNS still 53', false_lead='Knot listen leftover', avoided=BAN, knob='.mod-stats', old='mod-stats: off', new='mod-stats: on', wrong_knob='.listen', wrong_old='listen: 127.0.0.1@53', wrong_new='listen: 0.0.0.0@53', wrong2_old='rundir: /tmp', wrong2_new='rundir: /var/run/knot', prefix='knotx'),
    dict(vendor='PowerDNS', ok_slug='pdns-webserver-off-leftover', bad_slug='pdns-web-raise-api-not-enable', noun='hurst', panel='PowerDNS', needle='pdns_up', lie_core='web leftover webserver=no so Grafana is empty while DNS still 53', false_lead='PowerDNS api leftover', avoided=BAN, knob='.webserver', old='webserver: no', new='webserver: yes', wrong_knob='.api', wrong_old='api: no', wrong_new='api: yes', wrong2_old='local-address: 127.0.0.1', wrong2_new='local-address: 0.0.0.0', prefix='pdns'),
    dict(vendor='Kea', ok_slug='keax-ctrl-bind-drop-leftover', bad_slug='keax-ctrl-raise-sub-not-addr', noun='cogpit', panel='Kea ctrl', needle='keax_up', lie_core='ctrl leftover http-host 127.0.0.1 so Grafana is empty while DHCP still 67', false_lead='Kea subnet leftover', avoided=BAN, knob='.http-host', old='http-host: 127.0.0.1', new='http-host: 0.0.0.0', wrong_knob='.subnet4[0].subnet', wrong_old='subnet: 10.0.0.0/24', wrong_new='subnet: 10.8.0.0/24', wrong2_old='lease-database.name: /tmp/kea.csv', wrong2_new='lease-database.name: /var/lib/kea/leases.csv', prefix='keax'),
    dict(vendor='dnsmasq', ok_slug='dnsmq-log-queries-off-leftover', bad_slug='dnsmq-log-raise-if-not-enable', noun='lantern', panel='dnsmasq log', needle='dnsmq_up', lie_core='log leftover log-queries omitted so Grafana is empty while DNS still 53', false_lead='dnsmasq iface leftover', avoided=BAN, knob='.log-queries', old='log-queries: false', new='log-queries: true', wrong_knob='.interface', wrong_old='interface: lo', wrong_new='interface: eth0', wrong2_old='log-facility: /dev/null', wrong2_new='log-facility: /var/log/dnsmasq.log', prefix='dnsmq'),
    dict(vendor='HAProxy', ok_slug='haprox-stats-bind-drop-leftover', bad_slug='haprox-stat-raise-be-not-addr', noun='wallower', panel='HAProxy stats', needle='haprox_up', lie_core='stats leftover bind 127.0.0.1:8404 so Grafana is empty while backends still up', false_lead='HAProxy backend leftover', avoided=BAN, knob='.stats.bind', old='bind: 127.0.0.1:8404', new='bind: 0.0.0.0:8404', wrong_knob='.backend', wrong_old='backend: sandbox', wrong_new='backend: hangar', wrong2_old='nbproc: 1', wrong2_new='nbthread: 4', prefix='haprox'),
    dict(vendor='NGINX', ok_slug='nginx-stub-status-off-leftover', bad_slug='nginx-stub-raise-srv-not-enable', noun='spurwh', panel='NGINX stub', needle='nginx_up', lie_core='stub leftover stub_status off so Grafana is empty while 80 still 200', false_lead='NGINX server leftover', avoided=BAN, knob='.stub_status', old='stub_status: off', new='stub_status: on', wrong_knob='.server_name', wrong_old='server_name: sandbox', wrong_new='server_name: hangar', wrong2_old='access_log: /dev/null', wrong2_new='access_log: /var/log/nginx/access.log', prefix='nginx'),
    dict(vendor='Ambassador', ok_slug='ambss-diag-bind-drop-leftover', bad_slug='ambss-diag-raise-ns-not-addr', noun='crownwh', panel='Ambassador', needle='ambss_up', lie_core='diag leftover diagnostics.bind 127.0.0.1 so Grafana is empty while mappings still 200', false_lead='Ambassador ns leftover', avoided=BAN, knob='.diagnostics.enabled', old='enabled: false', new='enabled: true', wrong_knob='.namespace', wrong_old='namespace: sandbox', wrong_new='namespace: ambassador', wrong2_old='AMBASSADOR_ID: sandbox', wrong2_new='AMBASSADOR_ID: hangar', prefix='ambss'),
    dict(vendor='Gloo Edge', ok_slug='gloox-admin-bind-drop-leftover', bad_slug='gloox-adm-raise-ns-not-addr', noun='stonenut', panel='Gloo metrics', needle='gloox_up', lie_core='admin leftover bindAddress 127.0.0.1 so Grafana is empty while gateways still Serving', false_lead='Gloo ns leftover', avoided=BAN, knob='.bindAddress', old='bindAddress: 127.0.0.1:9091', new='bindAddress: 0.0.0.0:9091', wrong_knob='.namespace', wrong_old='namespace: sandbox', wrong_new='namespace: gloo-system', wrong2_old='cluster: sandbox', wrong2_new='cluster: hangar', prefix='gloox'),
    dict(vendor='Pomerium', ok_slug='pomrx-metrics-addr-drop-leftover', bad_slug='pomrx-met-raise-idp-not-addr', noun='quant', panel='Pomerium', needle='pomrx_up', lie_core='metrics leftover metrics_address 127.0.0.1 so Grafana is empty while proxy still 443', false_lead='Pomerium idp leftover', avoided=BAN, knob='.metrics_address', old='metrics_address: 127.0.0.1:9090', new='metrics_address: 0.0.0.0:9090', wrong_knob='.idp_provider', wrong_old='idp_provider: sandbox', wrong_new='idp_provider: oidc', wrong2_old='authenticate_service_url: https://sandbox', wrong2_new='authenticate_service_url: https://hangar', prefix='pomrx'),
    dict(vendor='oauth2-proxy', ok_slug='o2prx-metrics-off-leftover', bad_slug='o2prx-met-raise-up-not-enable', noun='rynd', panel='oauth2-proxy', needle='o2prx_up', lie_core='metrics leftover metrics-address empty so Grafana is empty while /oauth2 still 302', false_lead='oauth2-proxy upstream leftover', avoided=BAN, knob='.metrics-address', old='metrics-address: ', new='metrics-address: 0.0.0.0:44180', wrong_knob='.upstreams', wrong_old='upstreams: [http://sandbox]', wrong_new='upstreams: [http://hangar]', wrong2_old='http-address: 127.0.0.1:4180', wrong2_new='http-address: 0.0.0.0:4180', prefix='o2prx'),
    dict(vendor='Keycloak', ok_slug='keycl-metrics-off-leftover', bad_slug='keycl-met-raise-realm-not-enable', noun='mace', panel='Keycloak metrics', needle='keycl_up', lie_core='metrics leftover KC_METRICS_ENABLED=false so Grafana is empty while login still 200', false_lead='Keycloak realm leftover', avoided=BAN, knob='.KC_METRICS_ENABLED', old='KC_METRICS_ENABLED: false', new='KC_METRICS_ENABLED: true', wrong_knob='.KC_HOSTNAME', wrong_old='KC_HOSTNAME: sandbox', wrong_new='KC_HOSTNAME: hangar', wrong2_old='KC_HTTP_HOST: 127.0.0.1', wrong2_new='KC_HTTP_HOST: 0.0.0.0', prefix='keycl'),
    dict(vendor='Authentik', ok_slug='authk-listen-bind-drop-leftover', bad_slug='authk-list-raise-out-not-addr', noun='damsel', panel='Authentik', needle='authk_up', lie_core='listen leftover AUTHENTIK_LISTEN__HTTP 127.0.0.1 so Grafana is empty while login still 9000', false_lead='Authentik outpost leftover', avoided=BAN, knob='.AUTHENTIK_LISTEN__HTTP', old='AUTHENTIK_LISTEN__HTTP: 127.0.0.1:9000', new='AUTHENTIK_LISTEN__HTTP: 0.0.0.0:9000', wrong_knob='.AUTHENTIK_OUTPOSTS', wrong_old='AUTHENTIK_OUTPOSTS: sandbox', wrong_new='AUTHENTIK_OUTPOSTS: hangar', wrong2_old='AUTHENTIK_SECRET_KEY: sandbox', wrong2_new='AUTHENTIK_SECRET_KEY: hangar', prefix='authk'),
    dict(vendor='Authelia', ok_slug='authl-telemetry-off-leftover', bad_slug='authl-tel-raise-domain-not-enable', noun='shoe', panel='Authelia', needle='authl_up', lie_core='telemetry leftover telemetry.metrics.enabled=false so Grafana is empty while /api/verify still 200', false_lead='Authelia domain leftover', avoided=BAN, knob='.telemetry.metrics.enabled', old='enabled: false', new='enabled: true', wrong_knob='.default_redirection_url', wrong_old='default_redirection_url: https://sandbox', wrong_new='default_redirection_url: https://hangar', wrong2_old='server.host: 127.0.0.1', wrong2_new='server.host: 0.0.0.0', prefix='authl'),
    dict(vendor='Dex', ok_slug='dex-telemetry-off-leftover', bad_slug='dex-tel-raise-iss-not-enable', noun='hopper', panel='Dex', needle='dexx_up', lie_core='telemetry leftover telemetry.http 127.0.0.1 so Grafana is empty while /dex still 5556', false_lead='Dex issuer leftover', avoided=BAN, knob='.telemetry.http', old='http: 127.0.0.1:5558', new='http: 0.0.0.0:5558', wrong_knob='.issuer', wrong_old='issuer: https://sandbox', wrong_new='issuer: https://hangar', wrong2_old='web.http: 127.0.0.1:5556', wrong2_new='web.http: 0.0.0.0:5556', prefix='dexx'),
    dict(vendor='ORY Hydra', ok_slug='hydra-metrics-off-leftover', bad_slug='hydra-met-raise-url-not-enable', noun='tun', panel='Hydra metrics', needle='hydra_up', lie_core='metrics leftover serve.metrics.port 0 so Grafana is empty while /oauth2 still 4444', false_lead='Hydra url leftover', avoided=BAN, knob='.serve.metrics.port', old='port: 0', new='port: 4445', wrong_knob='.urls.self.issuer', wrong_old='issuer: https://sandbox', wrong_new='issuer: https://hangar', wrong2_old='serve.public.host: 127.0.0.1', wrong2_new='serve.public.host: 0.0.0.0', prefix='hydra'),
    dict(vendor='ORY Keto', ok_slug='keto-metrics-off-leftover', bad_slug='keto-met-raise-ns-not-enable', noun='stone', panel='Keto metrics', needle='ketox_up', lie_core='metrics leftover serve.metrics.port 0 so Grafana is empty while check still 4466', false_lead='Keto ns leftover', avoided=BAN, knob='.serve.metrics.port', old='port: 0', new='port: 4468', wrong_knob='.namespaces[0].name', wrong_old='name: sandbox', wrong_new='name: hangar', wrong2_old='serve.read.host: 127.0.0.1', wrong2_new='serve.read.host: 0.0.0.0', prefix='ketox'),
    dict(vendor='Casdoor', ok_slug='casdr-origin-remap-leftover', bad_slug='casdr-orig-raise-org-not-remap', noun='skirt', panel='Casdoor', needle='casdr_up', lie_core='origin leftover origin sandbox so Grafana is the wrong dashboard while login still 8000', false_lead='Casdoor org leftover', avoided=BAN, knob='.origin', old='origin: https://sandbox', new='origin: https://hangar', wrong_knob='.organization', wrong_old='organization: sandbox', wrong_new='organization: hangar', wrong2_old='httpport: 0', wrong2_new='httpport: 8000', prefix='casdr'),
    dict(vendor='SuperTokens', ok_slug='stokn-core-bind-drop-leftover', bad_slug='stokn-core-raise-api-not-addr', noun='husk', panel='SuperTokens', needle='stokn_up', lie_core='core leftover API_LISTEN 127.0.0.1 so Grafana is empty while /auth still 3567', false_lead='SuperTokens api leftover', avoided=BAN, knob='.API_LISTEN', old='API_LISTEN: 127.0.0.1:3567', new='API_LISTEN: 0.0.0.0:3567', wrong_knob='.apiDomain', wrong_old='apiDomain: https://sandbox', wrong_new='apiDomain: https://hangar', wrong2_old='SUPERTOKENS_CONNECTION_URI: http://sandbox', wrong2_new='SUPERTOKENS_CONNECTION_URI: http://hangar', prefix='stokn'),
    dict(vendor='Auth0', ok_slug='auth0-domain-remap-leftover', bad_slug='auth0-dom-raise-cli-not-remap', noun='mealspout', panel='Auth0', needle='auth0_up', lie_core='domain leftover AUTH0_DOMAIN sandbox so Grafana is the wrong dashboard while /oauth/token still 200', false_lead='Auth0 client leftover', avoided=BAN, knob='.AUTH0_DOMAIN', old='AUTH0_DOMAIN: sandbox.auth0.com', new='AUTH0_DOMAIN: hangar.auth0.com', wrong_knob='.AUTH0_CLIENT_ID', wrong_old='AUTH0_CLIENT_ID: sandbox', wrong_new='AUTH0_CLIENT_ID: hangar', wrong2_old='AUTH0_AUDIENCE: sandbox', wrong2_new='AUTH0_AUDIENCE: hangar', prefix='auth0'),
    dict(vendor='Okta', ok_slug='okta-org-remap-leftover', bad_slug='okta-org-raise-cli-not-remap', noun='bolter', panel='Okta', needle='oktax_up', lie_core='org leftover OKTA_ORG_URL sandbox so Grafana is the wrong dashboard while /oauth2 still 200', false_lead='Okta client leftover', avoided=BAN, knob='.OKTA_ORG_URL', old='OKTA_ORG_URL: https://sandbox.okta.com', new='OKTA_ORG_URL: https://hangar.okta.com', wrong_knob='.OKTA_CLIENT_ID', wrong_old='OKTA_CLIENT_ID: sandbox', wrong_new='OKTA_CLIENT_ID: hangar', wrong2_old='OKTA_AUTH_SERVER_ID: sandbox', wrong2_new='OKTA_AUTH_SERVER_ID: hangar', prefix='oktax'),
    dict(vendor='Cognito', ok_slug='cognito-pool-remap-leftover', bad_slug='cognt-pool-raise-cli-not-remap', noun='sifter', panel='Cognito', needle='cognt_up', lie_core='pool leftover COGNITO_USER_POOL_ID sandbox so Grafana is the wrong dashboard while InitiateAuth still 200', false_lead='Cognito client leftover', avoided=BAN, knob='.COGNITO_USER_POOL_ID', old='COGNITO_USER_POOL_ID: sandbox', new='COGNITO_USER_POOL_ID: hangar', wrong_knob='.COGNITO_CLIENT_ID', wrong_old='COGNITO_CLIENT_ID: sandbox', wrong_new='COGNITO_CLIENT_ID: hangar', wrong2_old='COGNITO_REGION: us-east-1', wrong2_new='COGNITO_REGION: eu-central-1', prefix='cognt'),
    dict(vendor='Firebase Auth', ok_slug='fbauth-project-remap-leftover', bad_slug='fbauth-proj-raise-key-not-remap', noun='wiremach', panel='Firebase Auth', needle='fbauth_up', lie_core='project leftover FIREBASE_PROJECT_ID sandbox so Grafana is the wrong dashboard while signIn still 200', false_lead='Firebase key leftover', avoided=BAN, knob='.FIREBASE_PROJECT_ID', old='FIREBASE_PROJECT_ID: sandbox', new='FIREBASE_PROJECT_ID: hangar', wrong_knob='.FIREBASE_API_KEY', wrong_old='FIREBASE_API_KEY: sandbox', wrong_new='FIREBASE_API_KEY: hangar', wrong2_old='FIREBASE_AUTH_DOMAIN: sandbox.firebaseapp.com', wrong2_new='FIREBASE_AUTH_DOMAIN: hangar.firebaseapp.com', prefix='fbauth'),
    dict(vendor='WorkOS', ok_slug='workos-apikey-remap-leftover', bad_slug='workos-key-raise-org-not-remap', noun='middlings', panel='WorkOS', needle='workos_up', lie_core='key leftover WORKOS_API_KEY sandbox so Grafana is the wrong dashboard while SSO still 200', false_lead='WorkOS org leftover', avoided=BAN, knob='.WORKOS_API_KEY', old='WORKOS_API_KEY: sandbox', new='WORKOS_API_KEY: hangar', wrong_knob='.WORKOS_ORG_ID', wrong_old='WORKOS_ORG_ID: sandbox', wrong_new='WORKOS_ORG_ID: hangar', wrong2_old='WORKOS_CLIENT_ID: sandbox', wrong2_new='WORKOS_CLIENT_ID: hangar', prefix='workos'),
    dict(vendor='Clerk', ok_slug='clerk-publishable-remap-leftover', bad_slug='clerk-pub-raise-sec-not-remap', noun='bran', panel='Clerk', needle='clerk_up', lie_core='key leftover CLERK_PUBLISHABLE_KEY sandbox so Grafana is the wrong dashboard while sessions still 200', false_lead='Clerk secret leftover', avoided=BAN, knob='.CLERK_PUBLISHABLE_KEY', old='CLERK_PUBLISHABLE_KEY: sandbox', new='CLERK_PUBLISHABLE_KEY: hangar', wrong_knob='.CLERK_SECRET_KEY', wrong_old='CLERK_SECRET_KEY: sandbox', wrong_new='CLERK_SECRET_KEY: hangar', wrong2_old='CLERK_FRONTEND_API: sandbox', wrong2_new='CLERK_FRONTEND_API: hangar', prefix='clerk'),
    dict(vendor='Stytch', ok_slug='stytch-project-remap-leftover', bad_slug='stytch-proj-raise-sec-not-remap', noun='shorts', panel='Stytch', needle='stytch_up', lie_core='project leftover STYTCH_PROJECT_ID sandbox so Grafana is the wrong dashboard while magic still 200', false_lead='Stytch secret leftover', avoided=BAN, knob='.STYTCH_PROJECT_ID', old='STYTCH_PROJECT_ID: sandbox', new='STYTCH_PROJECT_ID: hangar', wrong_knob='.STYTCH_SECRET', wrong_old='STYTCH_SECRET: sandbox', wrong_new='STYTCH_SECRET: hangar', wrong2_old='STYTCH_ENV: test', wrong2_new='STYTCH_ENV: live', prefix='stytch'),
    dict(vendor='AppDynamics', ok_slug='appd-account-remap-leftover', bad_slug='appd-acct-raise-app-not-remap', noun='patent', panel='AppDynamics', needle='appd_up', lie_core='account leftover APPDYNAMICS_AGENT_ACCOUNT_NAME sandbox so Grafana is the wrong dashboard while BT still 200', false_lead='AppDynamics app leftover', avoided=BAN, knob='.APPDYNAMICS_AGENT_ACCOUNT_NAME', old='APPDYNAMICS_AGENT_ACCOUNT_NAME: sandbox', new='APPDYNAMICS_AGENT_ACCOUNT_NAME: hangar', wrong_knob='.APPDYNAMICS_AGENT_APPLICATION_NAME', wrong_old='APPDYNAMICS_AGENT_APPLICATION_NAME: sandbox', wrong_new='APPDYNAMICS_AGENT_APPLICATION_NAME: hangar', wrong2_old='APPDYNAMICS_CONTROLLER_HOST_NAME: sandbox', wrong2_new='APPDYNAMICS_CONTROLLER_HOST_NAME: hangar', prefix='appd'),
    dict(vendor='Elastic APM', ok_slug='eapm-server-url-remap-leftover', bad_slug='eapm-url-raise-svc-not-remap', noun='firsts', panel='Elastic APM', needle='eapm_up', lie_core='url leftover ELASTIC_APM_SERVER_URL sandbox so Grafana is the wrong dashboard while transactions still 202', false_lead='Elastic APM service leftover', avoided=BAN, knob='.ELASTIC_APM_SERVER_URL', old='ELASTIC_APM_SERVER_URL: https://sandbox', new='ELASTIC_APM_SERVER_URL: https://hangar', wrong_knob='.ELASTIC_APM_SERVICE_NAME', wrong_old='ELASTIC_APM_SERVICE_NAME: sandbox', wrong_new='ELASTIC_APM_SERVICE_NAME: hangar', wrong2_old='ELASTIC_APM_ENVIRONMENT: sandbox', wrong2_new='ELASTIC_APM_ENVIRONMENT: hangar', prefix='eapm'),
    dict(vendor='Pinpoint', ok_slug='pinpt-collector-ip-remap-leftover', bad_slug='pinpt-ip-raise-app-not-remap', noun='superfine', panel='Pinpoint', needle='pinpt_up', lie_core='collector leftover profiler.collector.ip sandbox so Grafana is the wrong dashboard while spans still send', false_lead='Pinpoint app leftover', avoided=BAN, knob='.profiler.collector.ip', old='ip: sandbox', new='ip: hangar', wrong_knob='.profiler.applications.name', wrong_old='name: sandbox', wrong_new='name: hangar', wrong2_old='profiler.transport.grpc: false', wrong2_new='profiler.transport.grpc: true', prefix='pinpt'),
    dict(vendor='CAT', ok_slug='cat-server-remap-leftover', bad_slug='cat-srv-raise-dom-not-remap', noun='groat', panel='CAT', needle='catx_up', lie_core='server leftover CAT_SERVER sandbox so Grafana is the wrong dashboard while transactions still 200', false_lead='CAT domain leftover', avoided=BAN, knob='.CAT_SERVER', old='CAT_SERVER: sandbox', new='CAT_SERVER: hangar', wrong_knob='.domain', wrong_old='domain: sandbox', wrong_new='domain: hangar', wrong2_old='cat.client.enabled: false', wrong2_new='cat.client.enabled: true', prefix='catx'),
    dict(vendor='Kibana', ok_slug='kibana-ops-bind-drop-leftover', bad_slug='kibana-ops-raise-es-not-addr', noun='grist', panel='Kibana metrics', needle='kibana_up', lie_core='ops leftover ops.metrics.interval 0 plus server.host 127.0.0.1 so Grafana is empty', false_lead='Kibana es leftover', avoided=BAN, knob='.server.host', old='host: 127.0.0.1', new='host: 0.0.0.0', wrong_knob='.elasticsearch.hosts', wrong_old='hosts: [https://sandbox]', wrong_new='hosts: [https://hangar]', wrong2_old='ops.cGroup.enabled: false', wrong2_new='ops.cGroup.enabled: true', prefix='kibana'),
    dict(vendor='Syslog-ng', ok_slug='sysng-stats-freq-drop-leftover', bad_slug='sysng-stat-raise-dest-not-freq', noun='chop2', panel='syslog-ng', needle='sysng_up', lie_core='stats leftover stats-freq 0 so Grafana is empty while syslog still 514', false_lead='syslog-ng dest leftover', avoided=BAN, knob='.stats-freq', old='stats-freq: 0', new='stats-freq: 60', wrong_knob='.destination', wrong_old='destination: sandbox', wrong_new='destination: hangar', wrong2_old='options.chain_hostnames: no', wrong2_new='options.chain_hostnames: yes', prefix='sysng'),
    dict(vendor='nxlog', ok_slug='nxlog-loglevel-drop-leftover', bad_slug='nxlog-lvl-raise-mod-not-level', noun='provend', panel='nxlog', needle='nxlog_up', lie_core='log leftover LogLevel CRITICAL plus LogFile /dev/null so Grafana is empty', false_lead='nxlog module leftover', avoided=BAN, knob='.LogLevel', old='LogLevel: CRITICAL', new='LogLevel: INFO', wrong_knob='.Module', wrong_old='Module: sandbox', wrong_new='Module: im_file', wrong2_old='LogFile: /dev/null', wrong2_new='LogFile: /var/log/nxlog/nxlog.log', prefix='nxlog'),
    dict(vendor='VictoriaLogs', ok_slug='vlcan-http-listen-drop-leftover', bad_slug='vlcan-http-raise-ret-not-addr', noun='oilcake', panel='VictoriaLogs', needle='vlcan_up', lie_core='http leftover httpListenAddr 127.0.0.1 so Grafana is empty while insert still 9428', false_lead='VictoriaLogs retention leftover', avoided=BAN, knob='.httpListenAddr', old='httpListenAddr: 127.0.0.1:9428', new='httpListenAddr: 0.0.0.0:9428', wrong_knob='.retentionPeriod', wrong_old='retentionPeriod: 1d', wrong_new='retentionPeriod: 30d', wrong2_old='storageDataPath: /tmp', wrong2_new='storageDataPath: /var/lib/victorialogs', prefix='vlcan'),
    dict(vendor='Quickwit', ok_slug='qwit-rest-listen-drop-leftover', bad_slug='qwit-rest-raise-idx-not-addr', noun='tallow', panel='Quickwit', needle='qwit_up', lie_core='rest leftover rest.listen 127.0.0.1 so Grafana is empty while search still 7280', false_lead='Quickwit index leftover', avoided=BAN, knob='.rest.listen_address', old='listen_address: 127.0.0.1', new='listen_address: 0.0.0.0', wrong_knob='.default_index_root_uri', wrong_old='default_index_root_uri: s3://sandbox', wrong_new='default_index_root_uri: s3://hangar', wrong2_old='data_dir: /tmp', wrong2_new='data_dir: /var/lib/quickwit', prefix='qwit'),
    dict(vendor='ZincSearch', ok_slug='zincx-server-bind-drop-leftover', bad_slug='zincx-srv-raise-data-not-addr', noun='fullon', panel='ZincSearch', needle='zincx_up', lie_core='server leftover ZINC_SERVER_ADDRESS 127.0.0.1 so Grafana is empty while search still 4080', false_lead='ZincSearch data leftover', avoided=BAN, knob='.ZINC_SERVER_ADDRESS', old='ZINC_SERVER_ADDRESS: 127.0.0.1:4080', new='ZINC_SERVER_ADDRESS: 0.0.0.0:4080', wrong_knob='.ZINC_DATA_PATH', wrong_old='ZINC_DATA_PATH: /tmp', wrong_new='ZINC_DATA_PATH: /data', wrong2_old='ZINC_FIRST_ADMIN_USER: sandbox', wrong2_new='ZINC_FIRST_ADMIN_USER: hangar', prefix='zincx'),
    dict(vendor='Sonic', ok_slug='sonic-inet-bind-drop-leftover', bad_slug='sonic-inet-raise-auth-not-addr', noun='waulk', panel='Sonic', needle='sonic_up', lie_core='inet leftover inet 127.0.0.1 so Grafana is empty while search still 1491', false_lead='Sonic auth leftover', avoided=BAN, knob='.inet', old='inet: 127.0.0.1:1491', new='inet: 0.0.0.0:1491', wrong_knob='.auth_password', wrong_old='auth_password: sandbox', wrong_new='auth_password: hangar', wrong2_old='store: /tmp', wrong2_new='store: /var/lib/sonic', prefix='sonic'),
    dict(vendor='RediSearch', ok_slug='redise-maxsearch-drop-leftover', bad_slug='redise-max-raise-idx-not-results', noun='tenter', panel='RediSearch', needle='redise_up', lie_core='max leftover MAXSEARCHRESULTS 0 so Grafana is empty while FT.SEARCH still 0', false_lead='RediSearch index leftover', avoided=BAN, knob='.MAXSEARCHRESULTS', old='MAXSEARCHRESULTS: 0', new='MAXSEARCHRESULTS: 10000', wrong_knob='.index', wrong_old='index: sandbox', wrong_new='index: hangar', wrong2_old='TIMEOUT: 1', wrong2_new='TIMEOUT: 500', prefix='redise'),
    dict(vendor='Manticore', ok_slug='manti-listen-drop-leftover', bad_slug='manti-list-raise-idx-not-addr', noun='teasel', panel='Manticore', needle='manti_up', lie_core='listen leftover listen 127.0.0.1 so Grafana is empty while searchd still 9308', false_lead='Manticore index leftover', avoided=BAN, knob='.listen', old='listen: 127.0.0.1:9308', new='listen: 0.0.0.0:9308', wrong_knob='.index', wrong_old='index: sandbox', wrong_new='index: hangar', wrong2_old='data_dir: /tmp', wrong2_new='data_dir: /var/lib/manticore', prefix='manti'),
    dict(vendor='Sphinx', ok_slug='sphinx-listen-drop-leftover', bad_slug='sphinx-list-raise-idx-not-addr', noun='carder', panel='Sphinx', needle='sphinx_up', lie_core='listen leftover listen 127.0.0.1 so Grafana is empty while searchd still 9312', false_lead='Sphinx index leftover', avoided=BAN, knob='.listen', old='listen: 127.0.0.1:9312', new='listen: 0.0.0.0:9312', wrong_knob='.index', wrong_old='index: sandbox', wrong_new='index: hangar', wrong2_old='binlog_path: /tmp', wrong2_new='binlog_path: /var/lib/sphinx', prefix='sphinx'),
    dict(vendor='Xapian', ok_slug='xapian-db-path-remap-leftover', bad_slug='xapian-db-raise-stem-not-remap', noun='scribbler', panel='Xapian', needle='xapian_up', lie_core='db leftover XAPIAN_DB sandbox so Grafana is the wrong dashboard while enquire still runs', false_lead='Xapian stem leftover', avoided=BAN, knob='.XAPIAN_DB', old='XAPIAN_DB: /tmp/sandbox', new='XAPIAN_DB: /var/lib/xapian/hangar', wrong_knob='.stemmer', wrong_old='stemmer: none', wrong_new='stemmer: english', wrong2_old='flags: 0', wrong2_new='flags: DB_CREATE_OR_OPEN', prefix='xapian'),
    dict(vendor='Whoosh', ok_slug='whoosh-indexdir-remap-leftover', bad_slug='whoosh-dir-raise-schema-not-remap', noun='slubbing', panel='Whoosh', needle='whoosh_up', lie_core='dir leftover WHOOSH_INDEXDIR sandbox so Grafana is the wrong dashboard while search still runs', false_lead='Whoosh schema leftover', avoided=BAN, knob='.WHOOSH_INDEXDIR', old='WHOOSH_INDEXDIR: /tmp/sandbox', new='WHOOSH_INDEXDIR: /var/lib/whoosh/hangar', wrong_knob='.schema', wrong_old='schema: sandbox', wrong_new='schema: hangar', wrong2_old='writer.limitmb: 1', wrong2_new='writer.limitmb: 256', prefix='whoosh'),
    dict(vendor='Tika', ok_slug='tika-host-bind-drop-leftover', bad_slug='tika-host-raise-ocr-not-addr', noun='mulejenny', panel='Tika', needle='tikax_up', lie_core='host leftover TIKA_SERVER_ENDPOINT 127.0.0.1 so Grafana is empty while /tika still 200', false_lead='Tika ocr leftover', avoided=BAN, knob='.TIKA_SERVER_ENDPOINT', old='TIKA_SERVER_ENDPOINT: http://127.0.0.1:9998', new='TIKA_SERVER_ENDPOINT: http://0.0.0.0:9998', wrong_knob='.ocr', wrong_old='ocr: noocr', wrong_new='ocr: tesseract', wrong2_old='fork.pool: 1', wrong2_new='fork.pool: 8', prefix='tikax'),
    dict(vendor='Grobid', ok_slug='grobid-host-bind-drop-leftover', bad_slug='grobid-host-raise-conc-not-addr', noun='throstle', panel='Grobid', needle='grobid_up', lie_core='host leftover grobid.host 127.0.0.1 so Grafana is empty while /api/process still 200', false_lead='Grobid conc leftover', avoided=BAN, knob='.grobid.host', old='host: 127.0.0.1', new='host: 0.0.0.0', wrong_knob='.grobid.concurrency', wrong_old='concurrency: 1', wrong_new='concurrency: 8', wrong2_old='grobid.port: 0', wrong2_new='grobid.port: 8070', prefix='grobid'),
    dict(vendor='Unstructured', ok_slug='unstr-api-url-remap-leftover', bad_slug='unstr-url-raise-key-not-remap', noun='flyer', panel='Unstructured', needle='unstr_up', lie_core='api leftover UNSTRUCTURED_API_URL sandbox so Grafana is the wrong dashboard while partition still 200', false_lead='Unstructured key leftover', avoided=BAN, knob='.UNSTRUCTURED_API_URL', old='UNSTRUCTURED_API_URL: https://sandbox', new='UNSTRUCTURED_API_URL: https://api.unstructured.io', wrong_knob='.UNSTRUCTURED_API_KEY', wrong_old='UNSTRUCTURED_API_KEY: sandbox', wrong_new='UNSTRUCTURED_API_KEY: hangar', wrong2_old='strategy: fast', wrong2_new='strategy: hi_res', prefix='unstr'),
    dict(vendor='Docling', ok_slug='docling-artifacts-drop-leftover', bad_slug='doclng-art-raise-ocr-not-path', noun='bobbin', panel='Docling', needle='doclng_up', lie_core='artifacts leftover DOCLING_ARTIFACTS_PATH /tmp/empty so Grafana is empty while convert still runs', false_lead='Docling ocr leftover', avoided=BAN, knob='.DOCLING_ARTIFACTS_PATH', old='DOCLING_ARTIFACTS_PATH: /tmp/empty', new='DOCLING_ARTIFACTS_PATH: /var/lib/docling', wrong_knob='.ocr', wrong_old='ocr: false', wrong_new='ocr: true', wrong2_old='do_table_structure: false', wrong2_new='do_table_structure: true', prefix='doclng'),
    dict(vendor='Marker', ok_slug='marker-output-dir-drop-leftover', bad_slug='markr-out-raise-lang-not-dir', noun='cop', panel='Marker', needle='markr_up', lie_core='output leftover MARKER_OUTPUT_DIR /dev/null so Grafana is empty while convert still writes', false_lead='Marker lang leftover', avoided=BAN, knob='.MARKER_OUTPUT_DIR', old='MARKER_OUTPUT_DIR: /dev/null', new='MARKER_OUTPUT_DIR: /var/lib/marker', wrong_knob='.langs', wrong_old='langs: []', wrong_new='langs: [en]', wrong2_old='batch_multiplier: 1', wrong2_new='batch_multiplier: 4', prefix='markr'),
    dict(vendor='Nougat', ok_slug='nougat-out-drop-leftover', bad_slug='nougat-out-raise-ckpt-not-dir', noun='pirn', panel='Nougat', needle='nougat_up', lie_core='out leftover NOUGAT_OUT /dev/null so Grafana is empty while pdf still parses', false_lead='Nougat ckpt leftover', avoided=BAN, knob='.NOUGAT_OUT', old='NOUGAT_OUT: /dev/null', new='NOUGAT_OUT: /var/lib/nougat', wrong_knob='.checkpoint', wrong_old='checkpoint: sandbox', wrong_new='checkpoint: 0.1.0-small', wrong2_old='batchsize: 1', wrong2_new='batchsize: 8', prefix='nougat'),
    dict(vendor='PaddleOCR', ok_slug='paddle-use-gpu-log-drop-leftover', bad_slug='paddle-gpu-raise-lang-not-enable', noun='shuttle', panel='PaddleOCR', needle='paddle_up', lie_core='log leftover show_log=False plus rec empty so Grafana is empty while ocr still runs', false_lead='PaddleOCR lang leftover', avoided=BAN, knob='.show_log', old='show_log: false', new='show_log: true', wrong_knob='.lang', wrong_old='lang: sandbox', wrong_new='lang: en', wrong2_old='use_angle_cls: false', wrong2_new='use_angle_cls: true', prefix='paddle'),
    dict(vendor='Tesseract', ok_slug='tessr-tessdata-remap-leftover', bad_slug='tessr-data-raise-lang-not-remap', noun='heald', panel='Tesseract', needle='tessr_up', lie_core='tessdata leftover TESSDATA_PREFIX sandbox so Grafana is the wrong dashboard while tesseract still prints', false_lead='Tesseract lang leftover', avoided=BAN, knob='.TESSDATA_PREFIX', old='TESSDATA_PREFIX: /tmp/sandbox', new='TESSDATA_PREFIX: /usr/share/tesseract-ocr/5/tessdata', wrong_knob='.lang', wrong_old='lang: osd', wrong_new='lang: eng', wrong2_old='oem: 0', wrong2_new='oem: 3', prefix='tessr'),
    dict(vendor='EasyOCR', ok_slug='easyocr-model-storage-remap-leftover', bad_slug='easyocr-mod-raise-lang-not-remap', noun='reed', panel='EasyOCR', needle='easyocr_up', lie_core='storage leftover EASYOCR_MODULE_PATH sandbox so Grafana is the wrong dashboard while readtext still runs', false_lead='EasyOCR lang leftover', avoided=BAN, knob='.EASYOCR_MODULE_PATH', old='EASYOCR_MODULE_PATH: /tmp/sandbox', new='EASYOCR_MODULE_PATH: ~/.EasyOCR', wrong_knob='.lang_list', wrong_old='lang_list: [sandbox]', wrong_new='lang_list: [en]', wrong2_old='gpu: false', wrong2_new='gpu: true', prefix='easyocr'),
    dict(vendor='docTR', ok_slug='doctr-cache-dir-remap-leftover', bad_slug='doctr-cache-raise-det-not-remap', noun='temple', panel='docTR', needle='doctr_up', lie_core='cache leftover DOCTR_CACHE_DIR sandbox so Grafana is the wrong dashboard while ocr_predictor still runs', false_lead='docTR det leftover', avoided=BAN, knob='.DOCTR_CACHE_DIR', old='DOCTR_CACHE_DIR: /tmp/sandbox', new='DOCTR_CACHE_DIR: ~/.cache/doctr', wrong_knob='.det_arch', wrong_old='det_arch: sandbox', wrong_new='det_arch: db_resnet50', wrong2_old='reco_arch: sandbox', wrong2_new='reco_arch: crnn_vgg16_bn', prefix='doctr'),
    dict(vendor='LayoutParser', ok_slug='laypar-model-path-remap-leftover', bad_slug='laypar-mod-raise-cfg-not-remap', noun='selvage', panel='LayoutParser', needle='laypar_up', lie_core='model leftover LAYOUTPARSER_MODEL sandbox so Grafana is the wrong dashboard while detect still runs', false_lead='LayoutParser cfg leftover', avoided=BAN, knob='.LAYOUTPARSER_MODEL', old='LAYOUTPARSER_MODEL: /tmp/sandbox', new='LAYOUTPARSER_MODEL: ~/.layoutparser/hangar', wrong_knob='.config_path', wrong_old='config_path: sandbox', wrong_new='config_path: lp://PubLayNet/faster_rcnn_R_50_FPN_3x/config', wrong2_old='label_map: sandbox', wrong2_new='label_map: hangar', prefix='laypar'),
    dict(vendor='Detectron2', ok_slug='detectron-output-dir-drop-leftover', bad_slug='detct-out-raise-cfg-not-dir', noun='picker', panel='Detectron2', needle='detct_up', lie_core='output leftover OUTPUT_DIR /dev/null so Grafana is empty while inference still runs', false_lead='Detectron2 cfg leftover', avoided=BAN, knob='.OUTPUT_DIR', old='OUTPUT_DIR: /dev/null', new='OUTPUT_DIR: /var/lib/detectron2', wrong_knob='.config_file', wrong_old='config_file: sandbox.yaml', wrong_new='config_file: COCO-Detection/faster_rcnn_R_50_FPN_3x.yaml', wrong2_old='MODEL.WEIGHTS: sandbox', wrong2_new='MODEL.WEIGHTS: hangar', prefix='detct'),
    dict(vendor='Calico', ok_slug='calico-typha-metrics-off-leftover', bad_slug='calic-typh-raise-as-not-enable', noun='swell2', panel='Calico metrics', needle='calic_up', lie_core='typha leftover prometheusMetricsEnabled=false so Grafana is empty while Felix still Ready', false_lead='Calico as leftover', avoided=BAN, knob='.prometheusMetricsEnabled', old='prometheusMetricsEnabled: false', new='prometheusMetricsEnabled: true', wrong_knob='.asNumber', wrong_old='asNumber: 64512', wrong_new='asNumber: 65000', wrong2_old='felix.prometheusReporterPort: 0', wrong2_new='felix.prometheusReporterPort: 9091', prefix='calic'),
    dict(vendor='Antrea', ok_slug='antrea-metrics-bind-drop-leftover', bad_slug='antre-bind-raise-enc-not-addr', noun='box2', panel='Antrea metrics', needle='antre_up', lie_core='metrics leftover metricsPort 0 so Grafana is empty while agents still Ready', false_lead='Antrea enc leftover', avoided=BAN, knob='.metricsPort', old='metricsPort: 0', new='metricsPort: 10350', wrong_knob='.trafficEncryptionMode', wrong_old='trafficEncryptionMode: none', wrong_new='trafficEncryptionMode: ipsec', wrong2_old='featureGates.FlowExporter: false', wrong2_new='featureGates.FlowExporter: true', prefix='antre'),
    dict(vendor='Flannel', ok_slug='flannel-kube-subnet-drop-leftover', bad_slug='flanl-sub-raise-be-not-path', noun='lay2', panel='Flannel', needle='flanl_up', lie_core='subnet leftover FLANNEL_SUBNET_FILE /dev/null so Grafana is empty while vxlan still runs', false_lead='Flannel backend leftover', avoided=BAN, knob='.FLANNEL_SUBNET_FILE', old='FLANNEL_SUBNET_FILE: /dev/null', new='FLANNEL_SUBNET_FILE: /run/flannel/subnet.env', wrong_knob='.Backend.Type', wrong_old='Type: sandbox', wrong_new='Type: vxlan', wrong2_old='Network: 10.0.0.0/8', wrong2_new='Network: 10.244.0.0/16', prefix='flanl'),
    dict(vendor='Weave Net', ok_slug='weavenet-metrics-bind-drop-leftover', bad_slug='weavenet-met-raise-nick-not-addr', noun='sley', panel='Weave', needle='weave_up', lie_core='metrics leftover WEAVE_METRICS_ADDR 127.0.0.1 so Grafana is empty while peers still Established', false_lead='Weave nick leftover', avoided=BAN, knob='.WEAVE_METRICS_ADDR', old='WEAVE_METRICS_ADDR: 127.0.0.1:6782', new='WEAVE_METRICS_ADDR: 0.0.0.0:6782', wrong_knob='.NICKNAME', wrong_old='NICKNAME: sandbox', wrong_new='NICKNAME: hangar', wrong2_old='IPALLOC_RANGE: 10.0.0.0/8', wrong2_new='IPALLOC_RANGE: 10.32.0.0/12', prefix='weave'),
    dict(vendor='Multus', ok_slug='multus-log-level-drop-leftover', bad_slug='multus-log-raise-kube-not-level', noun='treadle', panel='Multus', needle='multus_up', lie_core='log leftover logLevel=error plus logFile /dev/null so Grafana is empty while NAD still attach', false_lead='Multus kube leftover', avoided=BAN, knob='.logLevel', old='logLevel: error', new='logLevel: verbose', wrong_knob='.kubeconfig', wrong_old='kubeconfig: /tmp/empty', wrong_new='kubeconfig: /etc/cni/net.d/multus.d/multus.kubeconfig', wrong2_old='namespaceIsolation: true', wrong2_new='namespaceIsolation: false', prefix='multus'),
    dict(vendor='MetalLB', ok_slug='metallb-metrics-bind-drop-leftover', bad_slug='mlbx-bind-raise-pool-not-addr', noun='lam', panel='MetalLB', needle='mlbx_up', lie_core='metrics leftover metricsPort 0 so Grafana is empty while speakers still Ready', false_lead='MetalLB pool leftover', avoided=BAN, knob='.metricsPort', old='metricsPort: 0', new='metricsPort: 7472', wrong_knob='.address-pools[0].name', wrong_old='name: sandbox', wrong_new='name: hangar', wrong2_old='protocol: layer2', wrong2_new='protocol: bgp', prefix='mlbx'),
    dict(vendor='kube-vip', ok_slug='kubevip-metrics-off-leftover', bad_slug='kvip-met-raise-iface-not-enable', noun='jack', panel='kube-vip', needle='kvip_up', lie_core='metrics leftover prometheus_server=false so Grafana is empty while VIP still ARP', false_lead='kube-vip iface leftover', avoided=BAN, knob='.prometheus_server', old='prometheus_server: false', new='prometheus_server: true', wrong_knob='.vip_interface', wrong_old='vip_interface: lo', wrong_new='vip_interface: eth0', wrong2_old='address: 127.0.0.1', wrong2_new='address: 10.8.0.10', prefix='kvip'),
    dict(vendor='Keepalived', ok_slug='keepalived-snmp-off-leftover', bad_slug='keepa-snmp-raise-vrid-not-enable', noun='dobby', panel='Keepalived', needle='keepa_up', lie_core='snmp leftover enable_snmp_keepalived=false so Grafana is empty while VRRP still MASTER', false_lead='Keepalived vrid leftover', avoided=BAN, knob='.enable_snmp_keepalived', old='enable_snmp_keepalived: false', new='enable_snmp_keepalived: true', wrong_knob='.virtual_router_id', wrong_old='virtual_router_id: 0', wrong_new='virtual_router_id: 51', wrong2_old='interface: lo', wrong2_new='interface: eth0', prefix='keepa'),
    dict(vendor='FRR', ok_slug='frr-zebra-bind-drop-leftover', bad_slug='frr-zeb-raise-as-not-addr', noun='jacquard', panel='FRR', needle='frrx_up', lie_core='zebra leftover zebra.socket /tmp/empty so Grafana is empty while BGP still Established', false_lead='FRR as leftover', avoided=BAN, knob='.zebra.socket', old='socket: /tmp/empty', new='socket: /var/run/frr/zserv.api', wrong_knob='.router-bgp', wrong_old='as: 64512', wrong_new='as: 65000', wrong2_old='log file: /dev/null', wrong2_new='log file: /var/log/frr/frr.log', prefix='frrx'),
    dict(vendor='BIRD', ok_slug='bird-debug-off-leftover', bad_slug='bird-dbg-raise-as-not-enable', noun='warbeam', panel='BIRD', needle='birdx_up', lie_core='debug leftover debug protocols off plus log /dev/null so Grafana is empty while BGP still Established', false_lead='BIRD as leftover', avoided=BAN, knob='.debug protocols', old='debug protocols: off', new='debug protocols: all', wrong_knob='.local as', wrong_old='as: 64512', wrong_new='as: 65000', wrong2_old='log: /dev/null', wrong2_new='log: /var/log/bird.log', prefix='birdx'),
    dict(vendor='GoBGP', ok_slug='gobgp-api-bind-drop-leftover', bad_slug='gobgp-api-raise-as-not-addr', noun='clothbeam', panel='GoBGP', needle='gobgp_up', lie_core='api leftover api-hosts 127.0.0.1 so Grafana is empty while BGP still Established', false_lead='GoBGP as leftover', avoided=BAN, knob='.api-hosts', old='api-hosts: 127.0.0.1:50051', new='api-hosts: 0.0.0.0:50051', wrong_knob='.global.as', wrong_old='as: 64512', wrong_new='as: 65000', wrong2_old='global.router-id: 127.0.0.1', wrong2_new='global.router-id: 10.8.0.1', prefix='gobgp'),
    dict(vendor='ExaBGP', ok_slug='exabgp-log-drop-leftover', bad_slug='exabgp-log-raise-as-not-level', noun='temple2', panel='ExaBGP', needle='exabgp_up', lie_core='log leftover exabgp.log.level ERR plus destination /dev/null so Grafana is empty', false_lead='ExaBGP as leftover', avoided=BAN, knob='.exabgp.log.level', old='level: ERR', new='level: INFO', wrong_knob='.neighbor.local-as', wrong_old='local-as: 64512', wrong_new='local-as: 65000', wrong2_old='exabgp.log.destination: /dev/null', wrong2_new='exabgp.log.destination: syslog', prefix='exabgp'),
    dict(vendor='Suricata', ok_slug='suricata-eve-off-leftover', bad_slug='suric-eve-raise-iface-not-enable', noun='breastbeam', panel='Suricata', needle='suric_up', lie_core='eve leftover eve-log.enabled=no so Grafana is empty while detect still runs', false_lead='Suricata iface leftover', avoided=BAN, knob='.eve-log.enabled', old='enabled: no', new='enabled: yes', wrong_knob='.af-packet.interface', wrong_old='interface: lo', wrong_new='interface: eth0', wrong2_old='stats.enabled: no', wrong2_new='stats.enabled: yes', prefix='suric'),
    dict(vendor='Zeek', ok_slug='zeek-json-logs-off-leftover', bad_slug='zeek-json-raise-iface-not-enable', noun='lease', panel='Zeek', needle='zeek_up', lie_core='json leftover LogAscii::use_json=F so Grafana is empty while conn.log still writes', false_lead='Zeek iface leftover', avoided=BAN, knob='.LogAscii::use_json', old='use_json: F', new='use_json: T', wrong_knob='.interface', wrong_old='interface: lo', wrong_new='interface: eth0', wrong2_old='Log::default_logdir: /tmp', wrong2_new='Log::default_logdir: /opt/zeek/logs', prefix='zeekx'),
    dict(vendor='Snort', ok_slug='snort-alert-syslog-off-leftover', bad_slug='snort-sys-raise-iface-not-enable', noun='raddle', panel='Snort', needle='snort_up', lie_core='alert leftover output alert_syslog omitted so Grafana is empty while detect still runs', false_lead='Snort iface leftover', avoided=BAN, knob='.output.alert_syslog', old='alert_syslog: false', new='alert_syslog: true', wrong_knob='.ipvar HOME_NET', wrong_old='HOME_NET: 127.0.0.0/8', wrong_new='HOME_NET: 10.0.0.0/8', wrong2_old='interface: lo', wrong2_new='interface: eth0', prefix='snort'),
    dict(vendor='Wazuh', ok_slug='wazuh-jsonout-off-leftover', bad_slug='wazuh-json-raise-mgr-not-enable', noun='heck', panel='Wazuh', needle='wazuh_up', lie_core='json leftover logall_json=no so Grafana is empty while ossec still runs', false_lead='Wazuh mgr leftover', avoided=BAN, knob='.logall_json', old='logall_json: no', new='logall_json: yes', wrong_knob='.manager', wrong_old='manager: sandbox', wrong_new='manager: hangar', wrong2_old='jsonout_output: no', wrong2_new='jsonout_output: yes', prefix='wazuh'),
    dict(vendor='OSSEC', ok_slug='ossec-jsonout-off-leftover', bad_slug='ossec-json-raise-email-not-enable', noun='flyers', panel='OSSEC', needle='ossec_up', lie_core='json leftover jsonout_output=no so Grafana is empty while analysisd still runs', false_lead='OSSEC email leftover', avoided=BAN, knob='.jsonout_output', old='jsonout_output: no', new='jsonout_output: yes', wrong_knob='.email_to', wrong_old='email_to: sandbox', wrong_new='email_to: hangar', wrong2_old='logall: no', wrong2_new='logall: yes', prefix='ossec'),
    dict(vendor='TheHive', ok_slug='thehive-http-bind-drop-leftover', bad_slug='thive-http-raise-es-not-addr', noun='flyer2', panel='TheHive', needle='thive_up', lie_core='http leftover http.address 127.0.0.1 so Grafana is empty while /api still 9000', false_lead='TheHive es leftover', avoided=BAN, knob='.http.address', old='address: 127.0.0.1', new='address: 0.0.0.0', wrong_knob='.db.addresses', wrong_old='addresses: [sandbox:9200]', wrong_new='addresses: [hangar:9200]', wrong2_old='application.baseUrl: https://sandbox', wrong2_new='application.baseUrl: https://hangar', prefix='thive'),
    dict(vendor='MISP', ok_slug='misp-baseurl-remap-leftover', bad_slug='misp-url-raise-org-not-remap', noun='heald2', panel='MISP', needle='mispx_up', lie_core='base leftover MISP.baseurl sandbox so Grafana is the wrong dashboard while events still 200', false_lead='MISP org leftover', avoided=BAN, knob='.MISP.baseurl', old='baseurl: https://sandbox', new='baseurl: https://hangar', wrong_knob='.MISP.org', wrong_old='org: sandbox', wrong_new='org: hangar', wrong2_old='MISP.redis_host: sandbox', wrong2_new='MISP.redis_host: hangar', prefix='mispx'),
    dict(vendor='Velociraptor', ok_slug='velociraptor-bind-drop-leftover', bad_slug='veloci-bind-raise-org-not-addr', noun='reed2', panel='Velociraptor', needle='veloci_up', lie_core='bind leftover bind_address 127.0.0.1 so Grafana is empty while GUI still 8889', false_lead='Velociraptor org leftover', avoided=BAN, knob='.bind_address', old='bind_address: 127.0.0.1', new='bind_address: 0.0.0.0', wrong_knob='.org_id', wrong_old='org_id: sandbox', wrong_new='org_id: hangar', wrong2_old='monitoring.bind_address: 127.0.0.1', wrong2_new='monitoring.bind_address: 0.0.0.0', prefix='veloci'),
    dict(vendor='GRR', ok_slug='grr-admin-bind-drop-leftover', bad_slug='grr-adm-raise-fleetspeak-not-addr', noun='temple3', panel='GRR', needle='grrx_up', lie_core='admin leftover AdminUI.url 127.0.0.1 so Grafana is empty while hunts still run', false_lead='GRR fleetspeak leftover', avoided=BAN, knob='.AdminUI.url', old='url: http://127.0.0.1:8000', new='url: http://0.0.0.0:8000', wrong_knob='.FleetspeakEnabled', wrong_old='FleetspeakEnabled: false', wrong_new='FleetspeakEnabled: true', wrong2_old='Monitoring.http_port: 0', wrong2_new='Monitoring.http_port: 50051', prefix='grrx'),
    dict(vendor='osquery', ok_slug='osquery-logger-drop-leftover', bad_slug='osqry-log-raise-enroll-not-plugin', noun='selvage2', panel='osquery', needle='osqry_up', lie_core='logger leftover --disable_logging=true plus logger_plugin empty so Grafana is empty', false_lead='osquery enroll leftover', avoided=BAN, knob='.disable_logging', old='disable_logging: true', new='disable_logging: false', wrong_knob='.enroll_secret_path', wrong_old='enroll_secret_path: /tmp/empty', wrong_new='enroll_secret_path: /etc/osquery/enroll_secret', wrong2_old='logger_plugin: ', wrong2_new='logger_plugin: filesystem', prefix='osqry'),
    dict(vendor='Kolide', ok_slug='kolide-pack-remap-leftover', bad_slug='kolid-pack-raise-enroll-not-remap', noun='picker2', panel='Kolide', needle='kolid_up', lie_core='pack leftover KOLIDE_PACK sandbox so Grafana is the wrong dashboard while live queries still run', false_lead='Kolide enroll leftover', avoided=BAN, knob='.KOLIDE_PACK', old='KOLIDE_PACK: sandbox', new='KOLIDE_PACK: hangar', wrong_knob='.enroll_secret', wrong_old='enroll_secret: sandbox', wrong_new='enroll_secret: hangar', wrong2_old='KOLIDE_CLOUD: https://sandbox', wrong2_new='KOLIDE_CLOUD: https://k2.kolide.com', prefix='kolid'),
    dict(vendor='Fleet DM', ok_slug='fleet-prometheus-off-leftover', bad_slug='fleetx-prom-raise-mysql-not-enable', noun='swell3', panel='Fleet', needle='fleetx_up', lie_core='prometheus leftover FLEET_PROMETHEUS=false so Grafana is empty while hosts still online', false_lead='Fleet mysql leftover', avoided=BAN, knob='.FLEET_PROMETHEUS', old='FLEET_PROMETHEUS: false', new='FLEET_PROMETHEUS: true', wrong_knob='.FLEET_MYSQL_ADDRESS', wrong_old='FLEET_MYSQL_ADDRESS: sandbox:3306', wrong_new='FLEET_MYSQL_ADDRESS: hangar:3306', wrong2_old='FLEET_SERVER_ADDRESS: 127.0.0.1:8080', wrong2_new='FLEET_SERVER_ADDRESS: 0.0.0.0:8080', prefix='fleetx'),
    dict(vendor='Santa', ok_slug='santa-eventlog-off-leftover', bad_slug='santa-evt-raise-mode-not-enable', noun='box3', panel='Santa', needle='santa_up', lie_core='event leftover EventLogType none so Grafana is empty while santa still blocks', false_lead='Santa mode leftover', avoided=BAN, knob='.EventLogType', old='EventLogType: none', new='EventLogType: syslog', wrong_knob='.ClientMode', wrong_old='ClientMode: 0', wrong_new='ClientMode: 2', wrong2_old='FileChangesRegex: sandbox', wrong2_new='FileChangesRegex: hangar', prefix='santa'),
    dict(vendor='Cilium Hubble UI', ok_slug='hubble-ui-listen-drop-leftover', bad_slug='hubui-list-raise-relay-not-addr', noun='lay3', panel='Hubble UI', needle='hubui_up', lie_core='listen leftover listen 127.0.0.1 so Grafana is empty while Hubble still 80', false_lead='Hubble relay leftover', avoided=BAN, knob='.listen', old='listen: 127.0.0.1:8081', new='listen: 0.0.0.0:8081', wrong_knob='.relay-addr', wrong_old='relay-addr: sandbox:4245', wrong_new='relay-addr: hangar:4245', wrong2_old='base-url: https://sandbox', wrong2_new='base-url: https://hangar', prefix='hubui'),
    dict(vendor='Cilium Tetragon', ok_slug='tetragon-export-drop-leftover', bad_slug='tetrax-exp-raise-ns-not-file', noun='sley2', panel='Tetragon', needle='tetrax_up', lie_core='export leftover export-filename empty so Grafana is empty while tracing policies still run', false_lead='Tetragon ns leftover', avoided=BAN, knob='.export-filename', old='export-filename: ', new='export-filename: /var/log/tetragon/tetragon.log', wrong_knob='.namespace', wrong_old='namespace: sandbox', wrong_new='namespace: kube-system', wrong2_old='metrics-address: 127.0.0.1:2112', wrong2_new='metrics-address: 0.0.0.0:2112', prefix='tetrax'),
]

assert len(SPECS) == 88, len(SPECS)
for i, spec in enumerate(SPECS):
    _l16(1436 + i, **spec)
