"""Observability plants r217-r228. Do not clone r109-r216."""

from mill_plants_h import _failp, _okp

MORE = []


# r217 Azure App Insights operation_Id vs Tempo W3C
MORE.append(
    (
        _okp(
            slug="az-ai-operationid-vs-tempo",
            service="snow-desk-svc",
            dashboard_uid="snow-azai-1",
            panel="AI paste",
            query="GET /api/traces/{operation_Id}",
            lie="Grafana Tempo lookup of Azure App Insights operation_Id (GUID) as W3C 32-hex traceId",
            false_lead="Sentry event_id / NR spanId as Tempo traceId",
            config_path="grafana/dashboards/snow-azai-1.json",
            lie_path="k8s/snow-desk/appinsights.env",
            truth_name="AI operation_Id vs W3C trace_id",
            reload_name="snow-desk-svc",
            side="App Insights UI still shows GUID operation_Id",
            surfaces="Azure App Insights operation_Id vs Tempo W3C",
            avoided="r162 Sentry event_id; r184 NR spanId; r175 Faro; r198 X-Ray",
            this_is="AI operation_Id GUID pasted into Tempo",
            step_note="False lead Sentry/NR 4-5; GUID 6-8; W3C export 9-12.",
            query_cmd="curl -sS $TEMPO/api/traces/3d8c8a9e-1b2a-4c3d-9e0f-112233445566 | jq '{error}'",
            false_cmd="jq '.templating.list[]|{name}' grafana/dashboards/snow-azai-1.json",
            truth_cmd="curl -sS $APPINSIGHTS/v1/apps/snow/query -d 'traces | take 1' | jq '{operation_Id,w3c}'",
            confirm_cmd="rg 'APPLICATIONINSIGHTS|OTEL_TRACES' k8s/snow-desk/appinsights.env",
            reload_cmd="kubectl -n snow rollout restart deploy/snow-desk-svc && kubectl -n snow rollout status deploy/snow-desk-svc --timeout=90s",
            requery_cmd="curl -sS $TEMPO/api/traces/3d8c8a9e1b2a4c3d9e0f112233445566 | jq '.batches|length'",
            grafana_ok_cmd="curl -sS $GRAFANA/api/ds/query -d @/tmp/snow-azai.json | jq '.results.A.frames[0].schema'",
            side_cmd="curl -sS $APPINSIGHTS/v1/apps/snow/operations/3d8c8a9e-1b2a-4c3d-9e0f-112233445566 | jq '{id}'",
            final_cmd="rg 'OTEL_TRACES_EXPORTER|APPLICATIONINSIGHTS_CONNECTION_STRING' k8s/snow-desk/appinsights.env",
            patch_old="APPLICATIONINSIGHTS_CONNECTION_STRING=InstrumentationKey=…\nOTEL_TRACES_EXPORTER=none",
            patch_new="APPLICATIONINSIGHTS_CONNECTION_STRING=InstrumentationKey=…\nOTEL_TRACES_EXPORTER=otlp\nOTEL_EXPORTER_OTLP_ENDPOINT=http://tempo:4318",
            runbook_path="runbooks/snow-azai-w3c.md",
            runbook="# snow-desk-svc App Insights vs Tempo\noperation_Id is a GUID with hyphens. Tempo wants 32-hex. Dual-export OTLP.\nNot Sentry event_id.\n",
            goal="snow-desk-svc dashboard snow-azai-1 AI paste 404s in Tempo. App Insights has the request. Fix the GUID lie.",
            plan="404 → Sentry/NR vars (false) → operation_Id GUID → OTLP dual-export.",
            outcome="OTLP export on. Hyphen-stripped 32-hex opens Tempo. AI UI unchanged.",
            obs1='[{"uid":"snow-azai-1","title":"snow desk AI"}]',
            obs2='{"title":"AI paste","targets":[{"query":"${operation_Id}"}]}',
            obs3='{"error":"trace not found"}',
            obs4='{"name":"sentry_event_id"}\n{"name":"operation_Id"}\n# sentry unused',
            obs5="sentry var empty",
            obs6="APPLICATIONINSIGHTS_CONNECTION_STRING=…\nOTEL_TRACES_EXPORTER=none",
            obs7='{"operation_Id":"3d8c8a9e-1b2a-4c3d-9e0f-112233445566","w3c":null}',
            obs8="GUID with hyphens; Tempo never ingested OTLP",
            obs9="patched OTEL_TRACES_EXPORTER=otlp",
            obs10='deployment "snow-desk-svc" successfully rolled out',
            obs11="1",
            obs12='{"name":"Traces"}',
            obs13='{"id":"3d8c8a9e-1b2a-4c3d-9e0f-112233445566"}',
            obs14="wrote runbooks/snow-azai-w3c.md",
            obs15="OTEL_TRACES_EXPORTER=otlp",
        ),
        _failp(
            slug="az-ai-sentry-event-not-guid",
            service="glycol-mix-svc",
            dashboard_uid="glycol-azai-sentry",
            panel="glycol AI",
            query="GET /api/traces/{operation_Id}",
            lie="Looking up Sentry event_id does not turn Azure App Insights operation_Id GUIDs into Tempo W3C traces",
            false_lead="Sentry event_id as Tempo traceId",
            config_path="grafana/dashboards/glycol-azai-sentry.json",
            lie_path="k8s/glycol/appinsights.env",
            wrong_path="grafana/dashboards/glycol-azai-sentry.json",
            reload_name="grafana",
            ticket="OBS-5201",
            xfail="tests/test_glycol_azai.py",
            surfaces="Sentry leftover vs App Insights GUID",
            avoided="r162 as actual RCA",
            this_is="fail/handoff: Sentry var, AI GUID still 404",
            step_note="Sentry var 6-10; still 404 11; late GUID 12; handoff 14-15.",
            next_note="Next: Dynatrace traceId vs Tempo.",
            query_cmd="curl -sS $TEMPO/api/traces/aaaaaaaa-bbbb-cccc-dddd-eeeeffffffff | jq '{error}'",
            false_cmd="jq '.templating.list[]|{name}' grafana/dashboards/glycol-azai-sentry.json",
            reload_cmd="kubectl -n grafana rollout restart deploy/grafana && kubectl -n grafana rollout status deploy/grafana --timeout=90s",
            requery_cmd="curl -sS $TEMPO/api/traces/aaaaaaaa-bbbb-cccc-dddd-eeeeffffffff | jq '{error}'",
            denied_cmd="kubectl -n glycol auth can-i patch deploy/glycol-mix-svc --as=sre-bot",
            wrong_old='query: "${operation_Id}"',
            wrong_new='query: "${sentry_event_id}"',
            wrong2_old='name: sentry_event_id',
            wrong2_new='name: sentry_event_id\n      regex: "[0-9a-f-]+"',
            ticket_body="OBS-5201: glycol-mix-svc Tempo still 404 on AI GUID. Need OTLP export + strip hyphens. No app RBAC.\n",
            goal="glycol-mix-svc dashboard glycol-azai-sentry AI paste 404s. Open Tempo.",
            plan="Point query at Sentry event_id (r162 leftover).",
            outcome="Sentry var; still 404. Late AI GUID + exporter none. Handoff OBS-5201.",
            obs1='[{"uid":"glycol-azai-sentry","title":"glycol AI"}]',
            obs2='{"title":"glycol AI","targets":[{"query":"${operation_Id}"}]}',
            obs3='{"error":"trace not found"}',
            obs4='{"name":"sentry_event_id"}',
            obs5="sentry var present — treated as r162",
            obs6="grafana/dashboards/glycol-azai-sentry.json",
            obs7="patched query ${sentry_event_id}",
            obs8='deployment "grafana" successfully rolled out',
            obs9='{"error":"trace not found"}',
            obs10="patched sentry regex",
            obs11='{"error":"trace not found"}',
            obs12="appinsights.env OTEL_TRACES_EXPORTER=none; operation_Id GUID",
            obs13="no",
            obs14="wrote tickets/OBS-5201.md",
            obs15="xfail tests/test_glycol_azai.py",
        ),
    )
)

# r218 Dynatrace traceId vs Tempo
MORE.append(
    (
        _okp(
            slug="dt-traceid-vs-tempo-w3c",
            service="navaid-dme-svc",
            dashboard_uid="dme-dt-2",
            panel="DT paste",
            query="GET /api/traces/{dt.trace_id}",
            lie="Grafana Tempo lookup of Dynatrace traceId (32 hex UPPERCASE with 0x prefix in UI) as lowercase W3C",
            false_lead="Lightstep x-ot-span-context / NR spanId",
            config_path="grafana/dashboards/dme-dt-2.json",
            lie_path="k8s/dme/dynatrace.env",
            truth_name="DT traceId vs OTel trace_id",
            reload_name="navaid-dme-svc",
            side="Dynatrace PurePath UI unchanged",
            surfaces="Dynatrace traceId vs Tempo W3C",
            avoided="r194 Lightstep ot-span-context; r184 NR; r163 DD 128",
            this_is="DT UI 0x-prefixed uppercase hex pasted into Tempo",
            step_note="False lead LS/NR 4-5; 0x prefix 6-8; lowercase strip 9-12.",
            query_cmd="curl -sS $TEMPO/api/traces/0xAABBCCDDEEFF00112233445566778899 | jq '{error}'",
            false_cmd="jq '.templating.list[]|{name}' grafana/dashboards/dme-dt-2.json",
            truth_cmd="curl -sS $DT/api/v2/traces?service=navaid-dme-svc | jq '.[0].{traceId,otel}'",
            confirm_cmd="rg 'DT_TRACE|OTEL_' k8s/dme/dynatrace.env",
            reload_cmd="kubectl -n navaid rollout restart deploy/navaid-dme-svc && kubectl -n navaid rollout status deploy/navaid-dme-svc --timeout=90s",
            requery_cmd="curl -sS $TEMPO/api/traces/aabbccddeeff00112233445566778899 | jq '.batches|length'",
            grafana_ok_cmd="curl -sS $GRAFANA/api/ds/query -d @/tmp/dme-dt.json | jq '.results.A.frames[0].schema'",
            side_cmd="curl -sS $DT/api/v2/traces?service=navaid-dme-svc | jq 'length'",
            final_cmd="jq -r '.panels[0].targets[0].query' grafana/dashboards/dme-dt-2.json",
            patch_old='query: "${dt_trace_id}"',
            patch_new='query: "${dt_trace_id_w3c}"  # lower, strip 0x',
            runbook_path="runbooks/dme-dt-w3c.md",
            runbook="# navaid-dme-svc Dynatrace vs Tempo\nDT UI shows 0x + uppercase. Tempo wants lowercase 32-hex.\nNot Lightstep ot-span-context.\n",
            goal="navaid-dme-svc dashboard dme-dt-2 DT paste 404s. Dynatrace has PurePath. Fix the 0x/case lie.",
            plan="404 → LS/NR (false) → 0xAABBCC… → lowercase strip.",
            outcome="Dashboard uses dt_trace_id_w3c. Tempo 1 batch. DT UI unchanged.",
            obs1='[{"uid":"dme-dt-2","title":"dme dynatrace"}]',
            obs2='{"title":"DT paste","targets":[{"query":"${dt_trace_id}"}]}',
            obs3='{"error":"trace not found"}',
            obs4='{"name":"ot_span_context"}\n{"name":"dt_trace_id"}',
            obs5="LS var unused",
            obs6="DT_CLUSTER_ID=airline\nOTEL_PROPAGATORS=tracecontext",
            obs7='{"traceId":"0xAABBCCDDEEFF00112233445566778899","otel":"aabbccddeeff00112233445566778899"}',
            obs8="Tempo stores lowercase without 0x",
            obs9="patched query ${dt_trace_id_w3c}",
            obs10='deployment "navaid-dme-svc" successfully rolled out',
            obs11="1",
            obs12='{"name":"Traces"}',
            obs13="9",
            obs14="wrote runbooks/dme-dt-w3c.md",
            obs15="${dt_trace_id_w3c}",
        ),
        _failp(
            slug="dt-enable-ls-otctx-not-case",
            service="ils-glideslope-svc",
            dashboard_uid="ils-dt-ls",
            panel="ILS DT",
            query="GET /api/traces/{dt.trace_id}",
            lie="Pasting Lightstep x-ot-span-context does not decode Dynatrace 0x-uppercase traceIds for Tempo",
            false_lead="Lightstep x-ot-span-context as Tempo traceId",
            config_path="grafana/dashboards/ils-dt-ls.json",
            lie_path="k8s/ils/dynatrace.env",
            wrong_path="grafana/dashboards/ils-dt-ls.json",
            reload_name="grafana",
            ticket="OBS-5202",
            xfail="tests/test_ils_dt.py",
            surfaces="LS ot-span-context leftover vs DT 0x case",
            avoided="r194 as actual RCA",
            this_is="fail/handoff: LS header var, DT 0x still 404",
            step_note="LS var 6-10; still 404 11; late 0x 12; handoff 14-15.",
            next_note="Next: Instana trace vs Tempo.",
            query_cmd="curl -sS $TEMPO/api/traces/0xFFEEDDCCBBAA99887766554433221100 | jq '{error}'",
            false_cmd="jq '.templating.list[]|{name}' grafana/dashboards/ils-dt-ls.json",
            reload_cmd="kubectl -n grafana rollout restart deploy/grafana && kubectl -n grafana rollout status deploy/grafana --timeout=90s",
            requery_cmd="curl -sS $TEMPO/api/traces/0xFFEEDDCCBBAA99887766554433221100 | jq '{error}'",
            denied_cmd="kubectl -n grafana auth can-i patch configmap/grafana-dashboards --as=sre-bot",
            wrong_old='query: "${dt_trace_id}"',
            wrong_new='query: "${ot_span_context}"',
            wrong2_old='name: ot_span_context',
            wrong2_new='name: ot_span_context\n      regex: ".*"',
            ticket_body="OBS-5202: ils-glideslope-svc Tempo 404 on DT 0x id. Need lowercase strip. No Grafana RBAC.\n",
            goal="ils-glideslope-svc dashboard ils-dt-ls DT paste 404s. Open Tempo.",
            plan="Point query at Lightstep ot-span-context (r194 leftover).",
            outcome="LS var; still 404. Late 0x AABB. Handoff OBS-5202.",
            obs1='[{"uid":"ils-dt-ls","title":"ils dynatrace"}]',
            obs2='{"title":"ILS DT","targets":[{"query":"${dt_trace_id}"}]}',
            obs3='{"error":"trace not found"}',
            obs4='{"name":"ot_span_context"}',
            obs5="LS var present — treated as r194",
            obs6="grafana/dashboards/ils-dt-ls.json",
            obs7="patched query ${ot_span_context}",
            obs8='deployment "grafana" successfully rolled out',
            obs9='{"error":"trace not found"}',
            obs10="patched regex",
            obs11='{"error":"trace not found"}',
            obs12="dt_trace_id=0xFFEEDDCCBBAA99887766554433221100; Tempo has ffeeddccbbaa99887766554433221100",
            obs13="no",
            obs14="wrote tickets/OBS-5202.md",
            obs15="xfail tests/test_ils_dt.py",
        ),
    )
)

# r219 Instana trace vs Tempo
MORE.append(
    (
        _okp(
            slug="instana-trace-vs-tempo-w3c",
            service="asr-radar-svc",
            dashboard_uid="asr-instana-3",
            panel="Instana paste",
            query="GET /api/traces/{instana.traceId}",
            lie="Grafana Tempo lookup of Instana 16-hex traceId (internal) while OTel export used 32-hex W3C",
            false_lead="Zipkin B3 16-hex / Sentry event_id",
            config_path="grafana/dashboards/asr-instana-3.json",
            lie_path="k8s/asr/instana.env",
            truth_name="Instana long trace id vs W3C",
            reload_name="asr-radar-svc",
            side="Instana UI still 16-hex",
            surfaces="Instana 16-hex traceId vs Tempo W3C 32-hex",
            avoided="r199 Zipkin B3 pad; r162 Sentry; r184 NR",
            this_is="Instana internal 16-hex pasted; Tempo has 32-hex OTel",
            step_note="False lead B3/Sentry 4-5; Instana 16 6-8; longTraceId 9-12.",
            query_cmd="curl -sS $TEMPO/api/traces/c0ffee1234aabbcc | jq '{error}'",
            false_cmd="jq '.templating.list[]|{name}' grafana/dashboards/asr-instana-3.json",
            truth_cmd="curl -sS $INSTANA/api/traces/c0ffee1234aabbcc | jq '{id,longTraceId}'",
            confirm_cmd="rg 'INSTANA_|OTEL_' k8s/asr/instana.env",
            reload_cmd="kubectl -n asr rollout restart deploy/asr-radar-svc && kubectl -n asr rollout status deploy/asr-radar-svc --timeout=90s",
            requery_cmd="curl -sS $TEMPO/api/traces/0000000000000000c0ffee1234aabbcc | jq '.batches|length'",
            grafana_ok_cmd="curl -sS $GRAFANA/api/ds/query -d @/tmp/asr-in.json | jq '.results.A.frames[0].schema'",
            side_cmd="curl -sS $INSTANA/api/traces?service=asr-radar-svc | jq 'length'",
            final_cmd="jq -r '.panels[0].targets[0].query' grafana/dashboards/asr-instana-3.json",
            patch_old='query: "${instana_trace_id}"',
            patch_new='query: "${instana_long_trace_id}"  # 32-hex W3C',
            runbook_path="runbooks/asr-instana-w3c.md",
            runbook="# asr-radar-svc Instana vs Tempo\nInstana UI 16-hex. OTel/Tempo 32-hex longTraceId.\nNot Zipkin B3 pad.\n",
            goal="asr-radar-svc dashboard asr-instana-3 Instana paste 404s. Instana has the call. Fix the 16-hex lie.",
            plan="404 → B3/Sentry (false) → Instana 16 vs longTraceId → 32-hex var.",
            outcome="Panel uses longTraceId. Tempo 1 batch. Instana UI still 16-hex.",
            obs1='[{"uid":"asr-instana-3","title":"asr instana"}]',
            obs2='{"title":"Instana paste","targets":[{"query":"${instana_trace_id}"}]}',
            obs3='{"error":"trace not found"}',
            obs4='{"name":"b3_trace_id"}\n{"name":"instana_trace_id"}',
            obs5="B3 var unused — not r199",
            obs6="INSTANA_AGENT_HOST=instana-agent\nOTEL_TRACES_EXPORTER=otlp",
            obs7='{"id":"c0ffee1234aabbcc","longTraceId":"0000000000000000c0ffee1234aabbcc"}',
            obs8="Tempo has longTraceId; 16-hex exact miss",
            obs9="patched ${instana_long_trace_id}",
            obs10='deployment "asr-radar-svc" successfully rolled out',
            obs11="1",
            obs12='{"name":"Traces"}',
            obs13="11",
            obs14="wrote runbooks/asr-instana-w3c.md",
            obs15="${instana_long_trace_id}",
        ),
        _failp(
            slug="instana-pad-b3-not-longid",
            service="metar-ingest-svc",
            dashboard_uid="metar-instana-b3",
            panel="METAR Instana",
            query="GET /api/traces/{instana.traceId}",
            lie="Left-padding Zipkin B3 16-hex does not map Instana internal ids that Tempo stored as a different 32-hex OTel id",
            false_lead="Zipkin B3 16-hex needs left-pad",
            config_path="grafana/dashboards/metar-instana-b3.json",
            lie_path="k8s/metar/instana.env",
            wrong_path="grafana/dashboards/metar-instana-b3.json",
            reload_name="grafana",
            ticket="OBS-5203",
            xfail="tests/test_metar_instana.py",
            surfaces="B3 pad leftover vs Instana longTraceId",
            avoided="r199 as actual RCA",
            this_is="fail/handoff: B3 pad, Instana still 404",
            step_note="B3 pad 6-10; still 404 11; late Instana 12; handoff 14-15.",
            next_note="Next: Splunk HEC vs Loki.",
            query_cmd="curl -sS $TEMPO/api/traces/aabbccddeeff0011 | jq '{error}'",
            false_cmd="jq '.templating.list[]|{name}' grafana/dashboards/metar-instana-b3.json",
            reload_cmd="kubectl -n grafana rollout restart deploy/grafana && kubectl -n grafana rollout status deploy/grafana --timeout=90s",
            requery_cmd="curl -sS $TEMPO/api/traces/0000000000000000aabbccddeeff0011 | jq '{error}'",
            denied_cmd="kubectl -n grafana auth can-i patch configmap/grafana-dashboards --as=sre-bot",
            wrong_old='query: "${instana_trace_id}"',
            wrong_new='query: "${b3_trace_id_padded}"',
            wrong2_old='name: b3_trace_id_padded',
            wrong2_new='name: b3_trace_id_padded\n      regex: "0{16}(.*)"',
            ticket_body="OBS-5203: metar-ingest-svc Tempo still 404. B3 pad leftover. Need Instana longTraceId from API. No RBAC.\n",
            goal="metar-ingest-svc dashboard metar-instana-b3 Instana paste 404s. Open Tempo.",
            plan="Left-pad as Zipkin B3 (r199 leftover).",
            outcome="Padded 32-hex still 404 (OTel id differs). Late Instana API. Handoff OBS-5203.",
            obs1='[{"uid":"metar-instana-b3","title":"metar instana"}]',
            obs2='{"title":"METAR Instana","targets":[{"query":"${instana_trace_id}"}]}',
            obs3='{"error":"trace not found"}',
            obs4='{"name":"b3_trace_id_padded"}',
            obs5="B3 pad var — treated as r199",
            obs6="grafana/dashboards/metar-instana-b3.json",
            obs7="patched query padded B3",
            obs8='deployment "grafana" successfully rolled out',
            obs9='{"error":"trace not found"}',
            obs10="patched regex 0{16}",
            obs11='{"error":"trace not found"}',
            obs12="Instana longTraceId=ffeeddccbbaa0011aabbccddeeff0011 not zero-pad of 16-hex",
            obs13="no",
            obs14="wrote tickets/OBS-5203.md",
            obs15="xfail tests/test_metar_instana.py",
        ),
    )
)

# r220 Splunk HEC vs Loki (NOT Fluent Bit ES, NOT Vector, NOT OS URL)
MORE.append(
    (
        _okp(
            slug="splunk-hec-vs-loki-push",
            service="notam-parse-svc",
            dashboard_uid="notam-hec-4",
            panel="notam errors",
            query='{job="notam-parse-svc"} |= "parse_fail"',
            lie="OTel filelog/fluent forwarding uses Splunk HEC; Grafana Loki {job=notam-parse-svc} never ingested",
            false_lead="Loki datasource URL rewritten to OpenSearch / Fluent Bit es output",
            config_path="grafana/provisioning/datasources/notam-logs.yaml",
            lie_path="otelcol/notam-filelog.yaml",
            truth_name="Splunk HEC index notam",
            reload_name="otelcol-notam",
            side="Splunk still searchable",
            surfaces="Splunk HEC exporter vs Loki push",
            avoided="r191 OS URL; r206 Fluent Bit es; r200 Vector del job; r215 OTel filelog vs Loki",
            this_is="filelog → splunk_hec exporter, no Loki exporter",
            step_note="False lead OS/FB 4-5; HEC exporter 6-8; add Loki exporter 9-12.",
            query_cmd="curl -sS -G $LOKI/loki/api/v1/query_range --data-urlencode 'query={job=\"notam-parse-svc\"} |= \"parse_fail\"' | jq '.data.result|length'",
            false_cmd="yq -r '.datasources[]|{name,type,url}' grafana/provisioning/datasources/notam-logs.yaml",
            truth_cmd="curl -sS $SPLUNK/services/search/jobs -d 'search=index=notam parse_fail' | jq '{n}'",
            confirm_cmd="yq '.exporters,.service.pipelines.logs' otelcol/notam-filelog.yaml",
            reload_cmd="kubectl -n otel rollout restart deploy/otelcol-notam && kubectl -n otel rollout status deploy/otelcol-notam --timeout=90s",
            requery_cmd="curl -sS -G $LOKI/loki/api/v1/query_range --data-urlencode 'query={job=\"notam-parse-svc\"} |= \"parse_fail\"' | jq '.data.result|length'",
            grafana_ok_cmd="curl -sS $GRAFANA/api/ds/query -d @/tmp/notam-hec.json | jq '.results.A.frames[0].schema'",
            side_cmd="curl -sS $SPLUNK/services/search/jobs -d 'search=index=notam | stats count' | jq '.count'",
            final_cmd="yq -r '.service.pipelines.logs.exporters[]' otelcol/notam-filelog.yaml",
            patch_old="exporters: [splunk_hec]",
            patch_new="exporters: [splunk_hec, loki]\n    loki:\n      endpoint: http://loki:3100/loki/api/v1/push",
            runbook_path="runbooks/notam-hec-loki.md",
            runbook="# notam-parse-svc Splunk HEC vs Loki\nfilelog pipeline exporters=[splunk_hec] only. Add Loki exporter.\nNot OS URL rewrite and not Fluent Bit Name es.\n",
            goal="notam-parse-svc dashboard notam-hec-4 notam errors empty. Splunk has parse_fail. Find the HEC lie.",
            plan="Empty Loki → OS/FB URL (false) → HEC-only exporter → add Loki.",
            outcome="Loki exporter added. 44 streams. Splunk index unchanged.",
            obs1='[{"uid":"notam-hec-4","title":"notam parse logs"}]',
            obs2='{"title":"notam errors","targets":[{"expr":"{job=\\"notam-parse-svc\\"} |= \\"parse_fail\\""}]}',
            obs3="0",
            obs4='{"name":"notam-logs","type":"loki","url":"http://loki.obs.svc:3100"}\n# real Loki — not r191',
            obs5="datasource is Loki",
            obs6="receivers: [filelog]\nexporters: [splunk_hec]\npipelines.logs.exporters: [splunk_hec]",
            obs7='{"n":44}',
            obs8="HEC only; Loki never pushed",
            obs9="patched exporters + loki",
            obs10='deployment "otelcol-notam" successfully rolled out',
            obs11="44",
            obs12='{"name":"Logs"}',
            obs13="44",
            obs14="wrote runbooks/notam-hec-loki.md",
            obs15="loki",
        ),
        _failp(
            slug="splunk-recreate-os-index-not-hec",
            service="curfew-gate-svc",
            dashboard_uid="curfew-hec-os",
            panel="curfew errors",
            query='{job="curfew-gate-svc"} |= "curfew_breach"',
            lie="Recreating an OpenSearch index does not pull Splunk HEC events into Loki",
            false_lead="OpenSearch index missing / Fluent Bit es leftover",
            config_path="opensearch/curfew-index.json",
            lie_path="otelcol/curfew-filelog.yaml",
            wrong_path="opensearch/curfew-index.json",
            reload_name="opensearch",
            ticket="OBS-5204",
            xfail="tests/test_curfew_hec.py",
            surfaces="OS index leftover vs Splunk HEC exporter",
            avoided="r191 / r206 as actual RCA",
            this_is="fail/handoff: OS index recreated, HEC still only sink",
            step_note="OS index 6-10; still 0 11; late HEC 12; handoff 14-15.",
            next_note="Next: Thanos Receive vs Query.",
            query_cmd="curl -sS -G $LOKI/loki/api/v1/query_range --data-urlencode 'query={job=\"curfew-gate-svc\"} |= \"curfew_breach\"' | jq '.data.result|length'",
            false_cmd="jq '.index' opensearch/curfew-index.json",
            reload_cmd="kubectl -n os rollout restart deploy/opensearch && kubectl -n os rollout status deploy/opensearch --timeout=90s",
            requery_cmd="curl -sS -G $LOKI/loki/api/v1/query_range --data-urlencode 'query={job=\"curfew-gate-svc\"} |= \"curfew_breach\"' | jq '.data.result|length'",
            denied_cmd="kubectl -n otel auth can-i patch deploy/otelcol-curfew --as=sre-bot",
            wrong_old='"index": "curfew-v1"',
            wrong_new='"index": "curfew-v2"',
            wrong2_old='"number_of_shards": 1',
            wrong2_new='"number_of_shards": 3',
            ticket_body="OBS-5204: curfew-gate-svc Loki still 0. OS index irrelevant. otelcol exporters=[splunk_hec]. Need Loki exporter. No RBAC.\n",
            goal="curfew-gate-svc dashboard curfew-hec-os curfew errors empty. Restore Loki rows.",
            plan="Recreate OpenSearch index (r191 leftover).",
            outcome="OS v2; Loki still 0. Late HEC-only exporter. Handoff OBS-5204.",
            obs1='[{"uid":"curfew-hec-os","title":"curfew logs"}]',
            obs2='{"title":"curfew errors","targets":[{"expr":"{job=\\"curfew-gate-svc\\"} |= \\"curfew_breach\\""}]}',
            obs3="0",
            obs4='"index": "curfew-v1"',
            obs5="OS index present — treated as r191",
            obs6="opensearch/curfew-index.json",
            obs7="patched curfew-v2",
            obs8='deployment "opensearch" successfully rolled out',
            obs9="0",
            obs10="patched shards 3",
            obs11="0",
            obs12="otelcol/curfew-filelog.yaml exporters [splunk_hec] only",
            obs13="no",
            obs14="wrote tickets/OBS-5204.md",
            obs15="xfail tests/test_curfew_hec.py",
        ),
    )
)

# r221 Thanos Receive vs Query (NOT compact overlap)
MORE.append(
    (
        _okp(
            slug="thanos-receive-vs-query",
            service="noise-monitor-svc",
            dashboard_uid="noise-thanos-5",
            panel="noise dB",
            query='avg(noise_db{job="noise-monitor-svc"})',
            lie="Grafana Prom datasource URL is Thanos Receive :19291 (write path); queries must hit Query frontend :10902",
            false_lead="Thanos compact overlap / Prom agent no TSDB",
            config_path="thanos/noise-compact.yaml",
            lie_path="grafana/provisioning/datasources/noise-prom.yaml",
            truth_name="Thanos Query vs Receive",
            reload_name="grafana",
            side="Receive still accepts remote_write",
            surfaces="Thanos Receive write URL vs Query frontend",
            avoided="Thanos compact overlap ban; r160 Prom agent; r203 Mimir Kafka ingest",
            this_is="Grafana queries Receive HTTP, not Query",
            step_note="False lead compact/agent 4-5; Receive URL 6-8; Query :10902 9-12.",
            query_cmd="curl -sS -G $THANOS_RECEIVE:19291/api/v1/query --data-urlencode 'query=avg(noise_db{job=\"noise-monitor-svc\"})' | jq '{status,error}'",
            false_cmd="yq '.compact.consistency_delay, .dedup' thanos/noise-compact.yaml",
            truth_cmd="curl -sS -G $THANOS_QUERY:10902/api/v1/query --data-urlencode 'query=avg(noise_db{job=\"noise-monitor-svc\"})'",
            confirm_cmd="yq -r '.datasources[]|{name,url}' grafana/provisioning/datasources/noise-prom.yaml",
            reload_cmd="kubectl -n grafana rollout restart deploy/grafana && kubectl -n grafana rollout status deploy/grafana --timeout=90s",
            requery_cmd="curl -sS -G $THANOS_QUERY:10902/api/v1/query --data-urlencode 'query=avg(noise_db{job=\"noise-monitor-svc\"})'",
            grafana_ok_cmd="curl -sS $GRAFANA/api/ds/query -d @/tmp/noise.json | jq '.results.A.frames[0].schema'",
            side_cmd="curl -sS $THANOS_RECEIVE:19291/-/ready",
            final_cmd="yq -r '.datasources[]|select(.name==\"noise-prom\").url' grafana/provisioning/datasources/noise-prom.yaml",
            patch_old="url: http://thanos-receive.obs.svc:19291",
            patch_new="url: http://thanos-query.obs.svc:10902",
            runbook_path="runbooks/noise-thanos-receive.md",
            runbook="# noise-monitor-svc Thanos Receive vs Query\nGrafana pointed at Receive write port. Use Query frontend.\nNot compact overlap.\n",
            goal="noise-monitor-svc dashboard noise-thanos-5 noise dB empty/errors. Receive has samples. Fix the write-path URL.",
            plan="Query error → compact/agent (false) → URL :19291 → Query :10902.",
            outcome="Datasource is Query. avg=71.2. Receive still ready for writes.",
            obs1='[{"uid":"noise-thanos-5","title":"noise monitor"}]',
            obs2='{"title":"noise dB","targets":[{"expr":"avg(noise_db{job=\\"noise-monitor-svc\\"})"}]}',
            obs3='{"status":"error","error":"method GET not allowed on receive"}',
            obs4="consistency_delay: 30m\n# no overlap block — not compact ban",
            obs5="compact healthy",
            obs6='{"name":"noise-prom","url":"http://thanos-receive.obs.svc:19291"}',
            obs7='{"status":"success","data":{"result":[{"value":[1710000000,"71.2"]}]}}',
            obs8="Receive is write-only; Query has series",
            obs9="patched url thanos-query:10902",
            obs10='deployment "grafana" successfully rolled out',
            obs11='{"status":"success","data":{"result":[{"value":[1710000600,"71.2"]}]}}',
            obs12='{"name":"Timeseries"}',
            obs13="ok",
            obs14="wrote runbooks/noise-thanos-receive.md",
            obs15="http://thanos-query.obs.svc:10902",
        ),
        _failp(
            slug="thanos-enable-agent-tsdb-not-query",
            service="wildlife-alert-svc",
            dashboard_uid="wild-thanos-agent",
            panel="wildlife dB",
            query='avg(wildlife_hits{job="wildlife-alert-svc"})',
            lie="Enabling Prom agent TSDB / pointing at agent does not make Thanos Receive answer PromQL",
            false_lead="Prom agent has no local TSDB",
            config_path="prom/wild-agent.yaml",
            lie_path="grafana/provisioning/datasources/wild-prom.yaml",
            wrong_path="prom/wild-agent.yaml",
            reload_name="prom-agent",
            ticket="OBS-5205",
            xfail="tests/test_wild_thanos.py",
            surfaces="Prom agent leftover vs Thanos Receive URL",
            avoided="r160 as actual RCA",
            this_is="fail/handoff: agent TSDB on, Grafana still on Receive",
            step_note="agent TSDB 6-10; still GET not allowed 11; late Receive URL 12; handoff 14-15.",
            next_note="Next: Istio sidecar service.name vs app.",
            query_cmd="curl -sS -G $THANOS_RECEIVE:19291/api/v1/query --data-urlencode 'query=avg(wildlife_hits{job=\"wildlife-alert-svc\"})' | jq '{error}'",
            false_cmd="rg 'enable-feature=agent|storage.tsdb' prom/wild-agent.yaml",
            reload_cmd="kubectl -n prom rollout restart deploy/prom-agent && kubectl -n prom rollout status deploy/prom-agent --timeout=90s",
            requery_cmd="curl -sS -G $THANOS_RECEIVE:19291/api/v1/query --data-urlencode 'query=avg(wildlife_hits{job=\"wildlife-alert-svc\"})' | jq '{error}'",
            denied_cmd="kubectl -n grafana auth can-i patch configmap/grafana-datasources --as=sre-bot",
            wrong_old="enable-feature: [agent]",
            wrong_new="enable-feature: []  # try server TSDB",
            wrong2_old="storage.tsdb.path: /dev/null",
            wrong2_new="storage.tsdb.path: /prometheus",
            ticket_body="OBS-5205: wildlife-alert-svc still GET not allowed. Grafana url=thanos-receive:19291. Need Query :10902. No RBAC.\n",
            goal="wildlife-alert-svc dashboard wild-thanos-agent wildlife dB errors. Restore PromQL.",
            plan="Turn off Prom agent feature (r160 leftover).",
            outcome="Agent server mode; Receive still rejects GET. Late ds URL. Handoff OBS-5205.",
            obs1='[{"uid":"wild-thanos-agent","title":"wildlife thanos"}]',
            obs2='{"title":"wildlife dB","targets":[{"expr":"avg(wildlife_hits{job=\\"wildlife-alert-svc\\"})"}]}',
            obs3='{"error":"method GET not allowed on receive"}',
            obs4="enable-feature: [agent]  # treated as r160",
            obs5="agent mode",
            obs6="prom/wild-agent.yaml",
            obs7="patched feature []",
            obs8='deployment "prom-agent" successfully rolled out',
            obs9='{"error":"method GET not allowed on receive"}',
            obs10="patched tsdb path",
            obs11='{"error":"method GET not allowed on receive"}',
            obs12="wild-prom url http://thanos-receive.obs.svc:19291",
            obs13="no",
            obs14="wrote tickets/OBS-5205.md",
            obs15="xfail tests/test_wild_thanos.py",
        ),
    )
)

# r222 Istio sidecar service.name vs app
MORE.append(
    (
        _okp(
            slug="istio-proxy-svcname-vs-app",
            service="bird-radar-svc",
            dashboard_uid="bird-istio-6",
            panel="app traces",
            query='{resource.service.name="bird-radar-svc"}',
            lie="Istio sidecar OTel stats export sets resource.service.name=istio-proxy so Tempo search by app name is empty",
            false_lead="k8sattributes overwrite of service.name from deployment",
            config_path="otelcol/bird-k8sattr.yaml",
            lie_path="istio/bird-telemetry.yaml",
            truth_name="Tempo service.name values",
            reload_name="istiod",
            side="mesh metrics still on istio-proxy",
            surfaces="Istio sidecar service.name vs app",
            avoided="r186 k8sattributes overwrite; r174 routing filter",
            this_is="Istio Telemetry API resource service.name=istio-proxy",
            step_note="False lead k8sattr 4-5; Telemetry API 6-8; customTags service 9-12.",
            query_cmd="curl -sS -G $TEMPO/api/search --data-urlencode 'q={resource.service.name=\"bird-radar-svc\"}' | jq '.traces|length'",
            false_cmd="yq '.processors.k8sattributes' otelcol/bird-k8sattr.yaml",
            truth_cmd="curl -sS -G $TEMPO/api/search --data-urlencode 'q={resource.service.name=\"istio-proxy\"}' | jq '{n:(.traces|length),svc:.traces[0].rootServiceName}'",
            confirm_cmd="yq '.spec.tracing[].providers, .spec.tracing[].customTags' istio/bird-telemetry.yaml",
            reload_cmd="kubectl -n istio-system rollout restart deploy/istiod && kubectl -n istio-system rollout status deploy/istiod --timeout=90s",
            requery_cmd="curl -sS -G $TEMPO/api/search --data-urlencode 'q={resource.service.name=\"bird-radar-svc\"}' | jq '.traces|length'",
            grafana_ok_cmd="curl -sS $GRAFANA/api/ds/query -d @/tmp/bird-istio.json | jq '.results.A.frames[0].schema'",
            side_cmd="curl -sS -G $TEMPO/api/search --data-urlencode 'q={resource.service.name=\"istio-proxy\"}' | jq '.traces|length'",
            final_cmd="yq -r '.spec.tracing[0].customTags.service.name.value' istio/bird-telemetry.yaml",
            patch_old="customTags: {}",
            patch_new="customTags:\n        service.name:\n          environment:\n            name: APP_SERVICE_NAME\n            defaultValue: bird-radar-svc",
            runbook_path="runbooks/bird-istio-svcname.md",
            runbook="# bird-radar-svc Istio vs Tempo\nSidecar resource.service.name=istio-proxy. Set Telemetry customTags from APP_SERVICE_NAME.\nNot k8sattributes overwrite.\n",
            goal="bird-radar-svc dashboard bird-istio-6 app traces empty. Mesh has spans under istio-proxy. Fix the service.name lie.",
            plan="Empty app search → k8sattr (false) → istio-proxy name → customTags.",
            outcome="Traces under bird-radar-svc. istio-proxy still has mesh spans.",
            obs1='[{"uid":"bird-istio-6","title":"bird radar traces"}]',
            obs2='{"title":"app traces","targets":[{"query":"{resource.service.name=\\"bird-radar-svc\\"}"}]}',
            obs3="0",
            obs4="k8sattributes: {passthrough: true}\n# does not overwrite — not r186",
            obs5="k8sattr passthrough",
            obs6="providers: [otel]\ncustomTags: {}",
            obs7='{"n":40,"svc":"istio-proxy"}',
            obs8="all app hops labeled istio-proxy",
            obs9="patched customTags service.name",
            obs10='deployment "istiod" successfully rolled out',
            obs11="40",
            obs12='{"name":"Traces"}',
            obs13="12",
            obs14="wrote runbooks/bird-istio-svcname.md",
            obs15="bird-radar-svc",
        ),
        _failp(
            slug="istio-ottl-restore-not-sidecar",
            service="arff-dispatch-svc",
            dashboard_uid="arff-istio-ottl",
            panel="arff traces",
            query='{resource.service.name="arff-dispatch-svc"}',
            lie="OTTL set(service.name) on the collector does not retag Istio sidecar spans that already exported as istio-proxy",
            false_lead="k8sattributes/OTTL overwrite of service.name",
            config_path="otelcol/arff-k8sattr.yaml",
            lie_path="istio/arff-telemetry.yaml",
            wrong_path="otelcol/arff-k8sattr.yaml",
            reload_name="otelcol-arff",
            ticket="OBS-5206",
            xfail="tests/test_arff_istio.py",
            surfaces="OTTL leftover vs Istio sidecar name",
            avoided="r186 as actual RCA",
            this_is="fail/handoff: OTTL set name, sidecars still istio-proxy",
            step_note="OTTL 6-10; still 0 11; late Telemetry API 12; handoff 14-15.",
            next_note="Next: Envoy access log vs Loki parser.",
            query_cmd="curl -sS -G $TEMPO/api/search --data-urlencode 'q={resource.service.name=\"arff-dispatch-svc\"}' | jq '.traces|length'",
            false_cmd="yq '.processors.transform' otelcol/arff-k8sattr.yaml",
            reload_cmd="kubectl -n otel rollout restart deploy/otelcol-arff && kubectl -n otel rollout status deploy/otelcol-arff --timeout=90s",
            requery_cmd="curl -sS -G $TEMPO/api/search --data-urlencode 'q={resource.service.name=\"arff-dispatch-svc\"}' | jq '.traces|length'",
            denied_cmd="kubectl -n istio-system auth can-i patch telemetry/arff --as=sre-bot",
            wrong_old="processors: [k8sattributes, batch]",
            wrong_new="processors: [k8sattributes, transform, batch]",
            wrong2_old="transform: {}",
            wrong2_new="transform:\n    traces:\n      statements:\n        - set(resource.attributes[\"service.name\"], \"arff-dispatch-svc\")",
            ticket_body="OBS-5206: arff-dispatch-svc Tempo still 0. OTTL cannot retag already-exported istio-proxy spans. Need Istio Telemetry customTags. No istiod RBAC.\n",
            goal="arff-dispatch-svc dashboard arff-istio-ottl arff traces empty. Restore app search.",
            plan="OTTL set service.name (r186 leftover).",
            outcome="OTTL on; still 0 on app name. Late Istio Telemetry {}. Handoff OBS-5206.",
            obs1='[{"uid":"arff-istio-ottl","title":"arff traces"}]',
            obs2='{"title":"arff traces","targets":[{"query":"{resource.service.name=\\"arff-dispatch-svc\\"}"}]}',
            obs3="0",
            obs4="processors: [k8sattributes, batch]",
            obs5="no transform — treated as r186",
            obs6="otelcol/arff-k8sattr.yaml",
            obs7="patched add transform",
            obs8='deployment "otelcol-arff" successfully rolled out',
            obs9="0",
            obs10="patched set service.name",
            obs11="0",
            obs12="istio/arff-telemetry.yaml customTags {} providers [otel]; spans resource.service.name=istio-proxy",
            obs13="no",
            obs14="wrote tickets/OBS-5206.md",
            obs15="xfail tests/test_arff_istio.py",
        ),
    )
)

# r223 Envoy access log JSON vs Loki parser
MORE.append(
    (
        _okp(
            slug="envoy-accesslog-vs-loki-parser",
            service="medlink-svc",
            dashboard_uid="medlink-envoy-7",
            panel="5xx",
            query='{job="medlink-svc"} | json | response_code >= 500',
            lie="Envoy access logs are text/plain combined format; Grafana Loki | json parser yields empty while files have 5xx",
            false_lead="Loki | json leftover / VL LogsQL",
            config_path="grafana/dashboards/medlink-envoy-7.json",
            lie_path="istio/medlink-accesslog.yaml",
            truth_name="Envoy log format",
            reload_name="istiod",
            side="text panels still grep 5xx",
            surfaces="Envoy combined access log vs Loki json parser",
            avoided="r161 VL | json; r170 VL stream; r215 filelog vs Loki",
            this_is="Envoy TEXT format + Loki | json",
            step_note="False lead | json 4-5; Envoy format 6-8; JSON format 9-12.",
            query_cmd="curl -sS -G $LOKI/loki/api/v1/query_range --data-urlencode 'query={job=\"medlink-svc\"} | json | response_code >= 500' | jq '.data.result|length'",
            false_cmd="jq '.panels[0].targets[0].expr' grafana/dashboards/medlink-envoy-7.json",
            truth_cmd="kubectl -n medlink logs ds/istio-proxy --tail=2",
            confirm_cmd="yq '.spec.accessLogging[].providers' istio/medlink-accesslog.yaml",
            reload_cmd="kubectl -n istio-system rollout restart deploy/istiod && kubectl -n istio-system rollout status deploy/istiod --timeout=90s",
            requery_cmd="curl -sS -G $LOKI/loki/api/v1/query_range --data-urlencode 'query={job=\"medlink-svc\"} | json | response_code >= 500' | jq '.data.result|length'",
            grafana_ok_cmd="curl -sS $GRAFANA/api/ds/query -d @/tmp/medlink.json | jq '.results.A.frames[0].schema'",
            side_cmd="curl -sS -G $LOKI/loki/api/v1/query_range --data-urlencode 'query={job=\"medlink-svc\"} |= \" 500 \"' | jq '.data.result|length'",
            final_cmd="yq -r '.spec.accessLogging[0].providers[0].name' istio/medlink-accesslog.yaml",
            patch_old="providers:\n      - name: envoy\n        envoyFileAccessLog:\n          path: /dev/stdout",
            patch_new="providers:\n      - name: envoy-json\n        envoyFileAccessLog:\n          path: /dev/stdout\n          logFormat:\n            labels: {}\n            json: {}\n            text: null",
            runbook_path="runbooks/medlink-envoy-json.md",
            runbook="# medlink-svc Envoy vs Loki json\nAccess log is combined text. Panel | json needs Envoy JSON format.\nNot VL LogsQL.\n",
            goal="medlink-svc dashboard medlink-envoy-7 5xx empty. Pod logs show 500s. Fix the format lie.",
            plan="Empty | json → VL leftover (false) → combined text → Envoy JSON format.",
            outcome="Envoy JSON access logs. | json returns 18. Text grep still works.",
            obs1='[{"uid":"medlink-envoy-7","title":"medlink 5xx"}]',
            obs2='{"title":"5xx","targets":[{"expr":"{job=\\"medlink-svc\\"} | json | response_code >= 500"}]}',
            obs3="0",
            obs4='"{job=\\"medlink-svc\\"} | json | response_code >= 500"',
            obs5="panel already has | json — not missing parser",
            obs6="providers: [envoy] path /dev/stdout  # default combined text",
            obs7='[2026-08-19T00:00:01Z] "GET /link HTTP/1.1" 500',
            obs8="text combined; | json no fields",
            obs9="patched envoy JSON logFormat",
            obs10='deployment "istiod" successfully rolled out',
            obs11="18",
            obs12='{"name":"Logs"}',
            obs13="18",
            obs14="wrote runbooks/medlink-envoy-json.md",
            obs15="envoy-json",
        ),
        _failp(
            slug="envoy-vl-logsql-not-format",
            service="stretcher-svc",
            dashboard_uid="stretcher-envoy-vl",
            panel="stretcher 5xx",
            query='{job="stretcher-svc"} | json | response_code >= 500',
            lie="Rewriting the panel to VictoriaLogs LogsQL does not parse Envoy combined-text access logs",
            false_lead="VictoriaLogs LogsQL vs Loki LogQL",
            config_path="grafana/dashboards/stretcher-envoy-vl.json",
            lie_path="istio/stretcher-accesslog.yaml",
            wrong_path="grafana/dashboards/stretcher-envoy-vl.json",
            reload_name="grafana",
            ticket="OBS-5207",
            xfail="tests/test_stretcher_envoy.py",
            surfaces="VL LogsQL leftover vs Envoy text format",
            avoided="r161 as actual RCA",
            this_is="fail/handoff: LogsQL rewrite, Envoy still combined text",
            step_note="LogsQL 6-10; still 0 11; late envoy format 12; handoff 14-15.",
            next_note="Next: OTel memory_limiter vs Tempo.",
            query_cmd="curl -sS -G $LOKI/loki/api/v1/query_range --data-urlencode 'query={job=\"stretcher-svc\"} | json | response_code >= 500' | jq '.data.result|length'",
            false_cmd="jq '.panels[0].targets[0].expr' grafana/dashboards/stretcher-envoy-vl.json",
            reload_cmd="kubectl -n grafana rollout restart deploy/grafana && kubectl -n grafana rollout status deploy/grafana --timeout=90s",
            requery_cmd="curl -sS $VL/select/logsql/query -d 'q=_stream:stretcher-svc' | jq 'length'",
            denied_cmd="kubectl -n istio-system auth can-i patch telemetry/stretcher --as=sre-bot",
            wrong_old='{job="stretcher-svc"} | json | response_code >= 500',
            wrong_new='_stream:stretcher-svc response_code:>=500',
            wrong2_old="datasource: loki",
            wrong2_new="datasource: loki\n      # maybe VL",
            ticket_body="OBS-5207: stretcher-svc still 0. LogsQL leftover. Envoy combined text. Need JSON access log. No istiod RBAC.\n",
            goal="stretcher-svc dashboard stretcher-envoy-vl 5xx empty. Restore parsed 5xx.",
            plan="Rewrite to VictoriaLogs LogsQL (r161 leftover).",
            outcome="LogsQL; still 0. Late Envoy text. Handoff OBS-5207.",
            obs1='[{"uid":"stretcher-envoy-vl","title":"stretcher 5xx"}]',
            obs2='{"title":"stretcher 5xx","targets":[{"expr":"{job=\\"stretcher-svc\\"} | json | response_code >= 500"}]}',
            obs3="0",
            obs4='"{job=\\"stretcher-svc\\"} | json | response_code >= 500"',
            obs5="treated as LogQL vs LogsQL",
            obs6="grafana/dashboards/stretcher-envoy-vl.json",
            obs7="patched LogsQL",
            obs8='deployment "grafana" successfully rolled out',
            obs9="0",
            obs10="patched maybe VL comment",
            obs11="0",
            obs12="istio/stretcher-accesslog.yaml envoyFileAccessLog default text",
            obs13="no",
            obs14="wrote tickets/OBS-5207.md",
            obs15="xfail tests/test_stretcher_envoy.py",
        ),
    )
)

# r224 OTel memory_limiter vs Tempo
MORE.append(
    (
        _okp(
            slug="otel-memlimiter-drop-vs-tempo",
            service="umnr-desk-svc",
            dashboard_uid="umnr-mem-8",
            panel="umnr traces",
            query='{resource.service.name="umnr-desk-svc"}',
            lie="OTel memory_limiter spike_limit_mib 1 plus limit_mib 32 drops bursts; Tempo search empty while app QPS is fine",
            false_lead="tail_sampling decision_wait / loadbalancing jaeger static",
            config_path="otelcol/umnr-tail.yaml",
            lie_path="otelcol/umnr-mem.yaml",
            truth_name="memory_limiter refused metric",
            reload_name="otelcol-umnr",
            side="low-QPS services still in Tempo",
            surfaces="OTel memory_limiter drop vs Tempo empty",
            avoided="OTel tail wait ban; r204 loadbalancing jaeger; r174 routing filter",
            this_is="memory_limiter dropping bursts before Tempo",
            step_note="False lead tail/lb 4-5; limiter refused 6-8; raise limits 9-12.",
            query_cmd="curl -sS -G $TEMPO/api/search --data-urlencode 'q={resource.service.name=\"umnr-desk-svc\"}' | jq '.traces|length'",
            false_cmd="yq '.processors.tail_sampling,.exporters.loadbalancing' otelcol/umnr-tail.yaml",
            truth_cmd="curl -sS $MIMIR/api/v1/query --data-urlencode 'query=otelcol_processor_refused_spans{processor=\"memory_limiter\"}'",
            confirm_cmd="yq '.processors.memory_limiter' otelcol/umnr-mem.yaml",
            reload_cmd="kubectl -n otel rollout restart deploy/otelcol-umnr && kubectl -n otel rollout status deploy/otelcol-umnr --timeout=90s",
            requery_cmd="curl -sS -G $TEMPO/api/search --data-urlencode 'q={resource.service.name=\"umnr-desk-svc\"}' | jq '.traces|length'",
            grafana_ok_cmd="curl -sS $GRAFANA/api/ds/query -d @/tmp/umnr.json | jq '.results.A.frames[0].schema'",
            side_cmd="curl -sS -G $TEMPO/api/search --data-urlencode 'q={resource.service.name=\"ssr-meal-svc\"}' | jq '.traces|length'",
            final_cmd="yq -r '.processors.memory_limiter.limit_mib' otelcol/umnr-mem.yaml",
            patch_old="limit_mib: 32\n    spike_limit_mib: 1",
            patch_new="limit_mib: 512\n    spike_limit_mib: 128",
            runbook_path="runbooks/umnr-memlimiter.md",
            runbook="# umnr-desk-svc memory_limiter vs Tempo\nspike_limit_mib 1 drops bursts. Raise limiter. Not tail wait.\n",
            goal="umnr-desk-svc dashboard umnr-mem-8 umnr traces empty under load. Find the limiter lie.",
            plan="Empty Tempo → tail/lb (false) → refused_spans → raise limit_mib.",
            outcome="Limiter 512/128. 51 traces. ssr-meal-svc unchanged.",
            obs1='[{"uid":"umnr-mem-8","title":"umnr traces"}]',
            obs2='{"title":"umnr traces","targets":[{"query":"{resource.service.name=\\"umnr-desk-svc\\"}"}]}',
            obs3="0",
            obs4="tail_sampling: null\nloadbalancing: null\n# not r204 / not tail wait",
            obs5="no tail, no lb",
            obs6="limit_mib: 32\nspike_limit_mib: 1",
            obs7='{"status":"success","data":{"result":[{"value":[1710000000,"840"]}]}}',
            obs8="refused_spans 840 from memory_limiter",
            obs9="patched 512/128",
            obs10='deployment "otelcol-umnr" successfully rolled out',
            obs11="51",
            obs12='{"name":"Traces"}',
            obs13="19",
            obs14="wrote runbooks/umnr-memlimiter.md",
            obs15="512",
        ),
        _failp(
            slug="otel-mem-raise-tail-wait",
            service="pax-assist-svc",
            dashboard_uid="assist-mem-tail",
            panel="assist traces",
            query='{resource.service.name="pax-assist-svc"}',
            lie="Raising tail_sampling decision_wait does not stop memory_limiter spike_limit_mib 1 from dropping bursts",
            false_lead="OTel tail_sampling decision_wait too low",
            config_path="otelcol/assist-tail.yaml",
            lie_path="otelcol/assist-mem.yaml",
            wrong_path="otelcol/assist-tail.yaml",
            reload_name="otelcol-assist",
            ticket="OBS-5208",
            xfail="tests/test_assist_mem.py",
            surfaces="tail wait leftover vs memory_limiter",
            avoided="tail wait as actual RCA",
            this_is="fail/handoff: decision_wait 30s, limiter still 32/1",
            step_note="tail wait 6-10; still 0 11; late limiter 12; handoff 14-15.",
            next_note="Next: Loki structured metadata vs label matcher.",
            query_cmd="curl -sS -G $TEMPO/api/search --data-urlencode 'q={resource.service.name=\"pax-assist-svc\"}' | jq '.traces|length'",
            false_cmd="yq '.processors.tail_sampling.decision_wait' otelcol/assist-tail.yaml",
            reload_cmd="kubectl -n otel rollout restart deploy/otelcol-assist && kubectl -n otel rollout status deploy/otelcol-assist --timeout=90s",
            requery_cmd="curl -sS -G $TEMPO/api/search --data-urlencode 'q={resource.service.name=\"pax-assist-svc\"}' | jq '.traces|length'",
            denied_cmd="kubectl -n otel auth can-i patch configmap/assist-mem --as=sre-bot",
            wrong_old="decision_wait: 2s",
            wrong_new="decision_wait: 30s",
            wrong2_old="expected_new_traces_per_sec: 10",
            wrong2_new="expected_new_traces_per_sec: 200",
            ticket_body="OBS-5208: pax-assist-svc Tempo still 0. tail wait leftover. memory_limiter spike_limit_mib=1. Need raise limiter. No RBAC.\n",
            goal="pax-assist-svc dashboard assist-mem-tail assist traces empty under load. Land traces.",
            plan="Raise tail_sampling decision_wait (banned leftover).",
            outcome="wait 30s; still 0. Late limiter 32/1. Handoff OBS-5208.",
            obs1='[{"uid":"assist-mem-tail","title":"pax assist traces"}]',
            obs2='{"title":"assist traces","targets":[{"query":"{resource.service.name=\\"pax-assist-svc\\"}"}]}',
            obs3="0",
            obs4="decision_wait: 2s",
            obs5="tail present — treated as leftover",
            obs6="otelcol/assist-tail.yaml",
            obs7="patched 30s",
            obs8='deployment "otelcol-assist" successfully rolled out',
            obs9="0",
            obs10="patched expected_new_traces 200",
            obs11="0",
            obs12="otelcol/assist-mem.yaml limit_mib 32 spike_limit_mib 1; refused_spans 610",
            obs13="no",
            obs14="wrote tickets/OBS-5208.md",
            obs15="xfail tests/test_assist_mem.py",
        ),
    )
)

# r225 Loki structured metadata vs label matcher
MORE.append(
    (
        _okp(
            slug="loki-smeta-vs-label-matcher",
            service="lost-found-svc",
            dashboard_uid="lost-smeta-9",
            panel="detected_level",
            query='{job="lost-found-svc", detected_level="error"}',
            lie="detected_level is Loki structured metadata not an index label; {detected_level=} matcher is empty while | detected_level finds rows",
            false_lead="Loki bloom skip / SM allowlist / pattern_ingester",
            config_path="loki/lost-bloom.yaml",
            lie_path="grafana/dashboards/lost-smeta-9.json",
            truth_name="structured metadata keys",
            reload_name="grafana",
            side="label job still indexed",
            surfaces="Loki structured metadata vs index label matcher",
            avoided="r165 bloom skip; Loki SM allowlist ban; r185 pattern vs bloom",
            this_is="detected_level is structured metadata, queried as label",
            step_note="False lead bloom/SM 4-5; smeta keys 6-8; pipe matcher 9-12.",
            query_cmd="curl -sS -G $LOKI/loki/api/v1/query_range --data-urlencode 'query={job=\"lost-found-svc\", detected_level=\"error\"}' | jq '.data.result|length'",
            false_cmd="yq '.bloom_gateway,.limits_config.allow_structured_metadata' loki/lost-bloom.yaml",
            truth_cmd="curl -sS -G $LOKI/loki/api/v1/query_range --data-urlencode 'query={job=\"lost-found-svc\"} | detected_level=\"error\"' | jq '.data.result|length'",
            confirm_cmd="jq '.panels[0].targets[0].expr' grafana/dashboards/lost-smeta-9.json",
            reload_cmd="kubectl -n grafana rollout restart deploy/grafana && kubectl -n grafana rollout status deploy/grafana --timeout=90s",
            requery_cmd="curl -sS -G $LOKI/loki/api/v1/query_range --data-urlencode 'query={job=\"lost-found-svc\"} | detected_level=\"error\"' | jq '.data.result|length'",
            grafana_ok_cmd="curl -sS $GRAFANA/api/ds/query -d @/tmp/lost.json | jq '.results.A.frames[0].schema'",
            side_cmd="curl -sS -G $LOKI/loki/api/v1/label/job/values | jq 'index(\"lost-found-svc\")'",
            final_cmd="jq -r '.panels[0].targets[0].expr' grafana/dashboards/lost-smeta-9.json",
            patch_old='{job="lost-found-svc", detected_level="error"}',
            patch_new='{job="lost-found-svc"} | detected_level="error"',
            runbook_path="runbooks/lost-smeta.md",
            runbook="# lost-found-svc structured metadata\ndetected_level is smeta. Use | detected_level not {} matcher.\nNot bloom skip.\n",
            goal="lost-found-svc dashboard lost-smeta-9 detected_level empty. Loki has error lines. Fix the smeta lie.",
            plan="Empty {} matcher → bloom/SM (false) → | detected_level works → patch panel.",
            outcome="Panel uses pipe matcher. 62 streams. job label unchanged.",
            obs1='[{"uid":"lost-smeta-9","title":"lost found logs"}]',
            obs2='{"title":"detected_level","targets":[{"expr":"{job=\\"lost-found-svc\\", detected_level=\\"error\\"}"}]}',
            obs3="0",
            obs4="bloom_gateway.enabled: false\nallow_structured_metadata: true\n# not r165 / not SM allowlist deny",
            obs5="blooms off; smeta allowed",
            obs6='"{job=\\"lost-found-svc\\", detected_level=\\"error\\"}"',
            obs7="62",
            obs8="{} matcher on smeta always empty; pipe works",
            obs9="patched | detected_level",
            obs10='deployment "grafana" successfully rolled out',
            obs11="62",
            obs12='{"name":"Logs"}',
            obs13="lost-found-svc",
            obs14="wrote runbooks/lost-smeta.md",
            obs15='{job="lost-found-svc"} | detected_level="error"',
        ),
        _failp(
            slug="loki-smeta-rebuild-blooms",
            service="customs-kiosk-svc",
            dashboard_uid="customs-smeta-bloom",
            panel="kiosk level",
            query='{job="customs-kiosk-svc", detected_level="error"}',
            lie="Rebuilding Loki blooms does not make structured metadata matchable as an index label",
            false_lead="Loki bloom-gateway skip_factor / stale bloom",
            config_path="loki/customs-bloom.yaml",
            lie_path="grafana/dashboards/customs-smeta-bloom.json",
            wrong_path="loki/customs-bloom.yaml",
            reload_name="loki-bloom-gateway",
            ticket="OBS-5209",
            xfail="tests/test_customs_smeta.py",
            surfaces="bloom leftover vs structured metadata matcher",
            avoided="r165 as actual RCA",
            this_is="fail/handoff: blooms rebuilt, {} detected_level still empty",
            step_note="blooms 6-10; still 0 11; late smeta 12; handoff 14-15.",
            next_note="Next: Pixie protocol traces vs Tempo.",
            query_cmd="curl -sS -G $LOKI/loki/api/v1/query_range --data-urlencode 'query={job=\"customs-kiosk-svc\", detected_level=\"error\"}' | jq '.data.result|length'",
            false_cmd="yq '.bloom_gateway' loki/customs-bloom.yaml",
            reload_cmd="kubectl -n loki rollout restart deploy/bloom-gateway && kubectl -n loki rollout status deploy/bloom-gateway --timeout=90s",
            requery_cmd="curl -sS -G $LOKI/loki/api/v1/query_range --data-urlencode 'query={job=\"customs-kiosk-svc\", detected_level=\"error\"}' | jq '.data.result|length'",
            denied_cmd="kubectl -n grafana auth can-i patch configmap/grafana-dashboards --as=sre-bot",
            wrong_old="skip_factor: 3",
            wrong_new="skip_factor: 0",
            wrong2_old="enabled: true",
            wrong2_new="enabled: false",
            ticket_body="OBS-5209: customs-kiosk-svc {} detected_level still 0. Need | detected_level (smeta). No Grafana RBAC.\n",
            goal="customs-kiosk-svc dashboard customs-smeta-bloom kiosk level empty. Restore error lines.",
            plan="Rebuild/disable blooms (r165 leftover).",
            outcome="skip_factor 0 / disabled; still 0. Late smeta. Handoff OBS-5209.",
            obs1='[{"uid":"customs-smeta-bloom","title":"customs kiosk logs"}]',
            obs2='{"title":"kiosk level","targets":[{"expr":"{job=\\"customs-kiosk-svc\\", detected_level=\\"error\\"}"}]}',
            obs3="0",
            obs4="skip_factor: 3  # treated as r165",
            obs5="bloom skip_factor 3",
            obs6="loki/customs-bloom.yaml",
            obs7="patched skip_factor 0",
            obs8='deployment "bloom-gateway" successfully rolled out',
            obs9="0",
            obs10="patched bloom enabled false",
            obs11="0",
            obs12="| detected_level=error returns 21; {} matcher empty (smeta)",
            obs13="no",
            obs14="wrote tickets/OBS-5209.md",
            obs15="xfail tests/test_customs_smeta.py",
        ),
    )
)

# r226 Pixie protocol traces vs Tempo
MORE.append(
    (
        _okp(
            slug="pixie-upid-vs-tempo-w3c",
            service="immigration-queue-svc",
            dashboard_uid="imm-pixie-1",
            panel="Pixie paste",
            query="GET /api/traces/{upid}",
            lie="Grafana Tempo lookup of Pixie UPID (uint64 process id) as W3C traceId; Pixie HTTP traces never exported to Tempo",
            false_lead="Beyla eBPF double spans / Faro session",
            config_path="k8s/beyla/imm.yaml",
            lie_path="grafana/dashboards/imm-pixie-1.json",
            truth_name="Pixie pxtrace vs Tempo",
            reload_name="grafana",
            side="Pixie Live UI still has UPID traces",
            surfaces="Pixie UPID vs Tempo W3C trace_id",
            avoided="r183 Beyla+javaagent; r175 Faro session; pprof vs eBPF",
            this_is="Pixie UPID pasted; no OTLP to Tempo",
            step_note="False lead Beyla/Faro 4-5; Pixie UPID 6-8; px OTLP export 9-12.",
            query_cmd="curl -sS $TEMPO/api/traces/1234567890123456789 | jq '{error}'",
            false_cmd="yq '.instrumentation' k8s/beyla/imm.yaml",
            truth_cmd="px trace -p px/http_trace -- --upid 1234567890123456789 | head",
            confirm_cmd="jq '.templating.list[]|{name}' grafana/dashboards/imm-pixie-1.json",
            reload_cmd="kubectl -n grafana rollout restart deploy/grafana && kubectl -n grafana rollout status deploy/grafana --timeout=90s",
            requery_cmd="curl -sS -G $TEMPO/api/search --data-urlencode 'q={resource.service.name=\"immigration-queue-svc\"}' | jq '.traces|length'",
            grafana_ok_cmd="curl -sS $GRAFANA/api/ds/query -d @/tmp/imm-px.json | jq '.results.A.frames[0].schema'",
            side_cmd="px run px/http_trace -- --service immigration-queue-svc | wc -l",
            final_cmd="yq -r '.otel.exporter.endpoint' pixie/imm-otel.yaml",
            patch_old="otel:\n  enabled: false",
            patch_new="otel:\n  enabled: true\n  exporter:\n    endpoint: tempo:4317",
            runbook_path="runbooks/imm-pixie-tempo.md",
            runbook="# immigration-queue-svc Pixie vs Tempo\nUPID is not W3C. Enable Pixie OTel export to Tempo.\nNot Beyla double-count.\n",
            goal="immigration-queue-svc dashboard imm-pixie-1 Pixie paste 404s. Pixie Live has HTTP. Fix the UPID lie.",
            plan="404 → Beyla/Faro (false) → UPID uint64 → enable Pixie OTLP.",
            outcome="Pixie OTel export on. Tempo 28 traces. Pixie Live unchanged.",
            obs1='[{"uid":"imm-pixie-1","title":"immigration pixie"}]',
            obs2='{"title":"Pixie paste","targets":[{"query":"${pixie_upid}"}]}',
            obs3='{"error":"trace not found"}',
            obs4="instrumentation: []  # Beyla not on this ns — not r183",
            obs5="no Beyla",
            obs6='{"name":"pixie_upid"}',
            obs7="upid=1234567890123456789 http traces 28 in Pixie",
            obs8="UPID is process id; Tempo has no export",
            obs9="patched pixie otel enabled endpoint tempo:4317",
            obs10='deployment "grafana" successfully rolled out',
            obs11="28",
            obs12='{"name":"Traces"}',
            obs13="28",
            obs14="wrote runbooks/imm-pixie-tempo.md",
            obs15="tempo:4317",
        ),
        _failp(
            slug="pixie-disable-beyla-not-upid",
            service="aep-badge-svc",
            dashboard_uid="aep-pixie-beyla",
            panel="aep Pixie",
            query="GET /api/traces/{upid}",
            lie="Disabling Beyla does not turn Pixie UPIDs into Tempo W3C trace ids or export Pixie HTTP to Tempo",
            false_lead="Beyla+javaagent double spans",
            config_path="k8s/beyla/aep.yaml",
            lie_path="pixie/aep-otel.yaml",
            wrong_path="k8s/beyla/aep.yaml",
            reload_name="beyla",
            ticket="OBS-5210",
            xfail="tests/test_aep_pixie.py",
            surfaces="Beyla leftover vs Pixie UPID",
            avoided="r183 as actual RCA",
            this_is="fail/handoff: Beyla off, Pixie still not exporting",
            step_note="Beyla 6-10; still 404 11; late pixie otel false 12; handoff 14-15.",
            next_note="Next: Hubble L7 vs Tempo.",
            query_cmd="curl -sS $TEMPO/api/traces/987650123498765 | jq '{error}'",
            false_cmd="yq '.instrumentation' k8s/beyla/aep.yaml",
            reload_cmd="kubectl -n beyla rollout restart daemonset/beyla && kubectl -n beyla rollout status daemonset/beyla --timeout=90s",
            requery_cmd="curl -sS $TEMPO/api/traces/987650123498765 | jq '{error}'",
            denied_cmd="kubectl -n pl auth can-i patch configmap/pl-otel --as=sre-bot",
            wrong_old="instrumentation: [http]",
            wrong_new="instrumentation: []",
            wrong2_old="openPorts: [8080]",
            wrong2_new="openPorts: []",
            ticket_body="OBS-5210: aep-badge-svc Tempo still 404 on Pixie UPID. Need pixie otel.enabled. No pl RBAC.\n",
            goal="aep-badge-svc dashboard aep-pixie-beyla Pixie paste 404s. Land traces in Tempo.",
            plan="Disable Beyla HTTP (r183 leftover).",
            outcome="Beyla off; still 404. Late pixie otel.enabled false. Handoff OBS-5210.",
            obs1='[{"uid":"aep-pixie-beyla","title":"aep pixie"}]',
            obs2='{"title":"aep Pixie","targets":[{"query":"${pixie_upid}"}]}',
            obs3='{"error":"trace not found"}',
            obs4="instrumentation: [http]  # treated as r183",
            obs5="Beyla HTTP on",
            obs6="k8s/beyla/aep.yaml",
            obs7="patched instrumentation []",
            obs8='daemonset "beyla" successfully rolled out',
            obs9='{"error":"trace not found"}',
            obs10="patched openPorts []",
            obs11='{"error":"trace not found"}',
            obs12="pixie/aep-otel.yaml otel.enabled false",
            obs13="no",
            obs14="wrote tickets/OBS-5210.md",
            obs15="xfail tests/test_aep_pixie.py",
        ),
    )
)

# r227 Hubble L7 vs Tempo
MORE.append(
    (
        _okp(
            slug="hubble-l7-vs-tempo-w3c",
            service="airside-bus-svc",
            dashboard_uid="bus-hubble-2",
            panel="Hubble flows",
            query='{resource.service.name="airside-bus-svc"}',
            lie="Grafana Tempo traces-from-Hubble panel queries TraceQL; Hubble L7 flows live in Hubble timescape not Tempo",
            false_lead="Istio sidecar service.name / loadbalancing jaeger",
            config_path="istio/bus-telemetry.yaml",
            lie_path="grafana/dashboards/bus-hubble-2.json",
            truth_name="Hubble observe HTTP",
            reload_name="hubble-relay",
            side="Cilium identities still in Hubble UI",
            surfaces="Cilium Hubble L7 flows vs Tempo TraceQL",
            avoided="r222 Istio sidecar name; r204 loadbalancing; Beyla eBPF",
            this_is="Hubble L7 HTTP never exported to Tempo",
            step_note="False lead Istio/lb 4-5; Hubble only 6-8; hubble-otel 9-12.",
            query_cmd="curl -sS -G $TEMPO/api/search --data-urlencode 'q={resource.service.name=\"airside-bus-svc\"}' | jq '.traces|length'",
            false_cmd="yq '.spec.tracing' istio/bus-telemetry.yaml",
            truth_cmd="hubble observe --http -n airside --since 5m | wc -l",
            confirm_cmd="jq '.panels[0].datasource' grafana/dashboards/bus-hubble-2.json",
            reload_cmd="kubectl -n kube-system rollout restart deploy/hubble-relay && kubectl -n kube-system rollout status deploy/hubble-relay --timeout=90s",
            requery_cmd="curl -sS -G $TEMPO/api/search --data-urlencode 'q={resource.service.name=\"airside-bus-svc\"}' | jq '.traces|length'",
            grafana_ok_cmd="curl -sS $GRAFANA/api/ds/query -d @/tmp/bus-hub.json | jq '.results.A.frames[0].schema'",
            side_cmd="hubble observe --from-service airside-bus-svc --since 5m | wc -l",
            final_cmd="yq -r '.otel.enabled, .otel.endpoint' cilium/hubble-otel.yaml",
            patch_old="otel:\n  enabled: false",
            patch_new="otel:\n  enabled: true\n  endpoint: tempo:4317\n  traces: true",
            runbook_path="runbooks/bus-hubble-tempo.md",
            runbook="# airside-bus-svc Hubble vs Tempo\nL7 flows in Hubble. Enable hubble-otel traces to Tempo.\nNot Istio service.name.\n",
            goal="airside-bus-svc dashboard bus-hubble-2 Hubble flows empty in Tempo. Hubble CLI has HTTP. Fix the export lie.",
            plan="Empty Tempo → Istio/lb (false) → Hubble observe 77 → enable hubble-otel.",
            outcome="hubble-otel traces on. Tempo 77. Hubble UI unchanged.",
            obs1='[{"uid":"bus-hubble-2","title":"airside hubble"}]',
            obs2='{"title":"Hubble flows","targets":[{"query":"{resource.service.name=\\"airside-bus-svc\\"}"}]}',
            obs3="0",
            obs4="tracing: []  # no Istio telemetry — not r222",
            obs5="no Istio tracing",
            obs6='{"uid":"tempo"}',
            obs7="77",
            obs8="Hubble has L7; Tempo datasource has none",
            obs9="patched hubble-otel enabled",
            obs10='deployment "hubble-relay" successfully rolled out',
            obs11="77",
            obs12='{"name":"Traces"}',
            obs13="77",
            obs14="wrote runbooks/bus-hubble-tempo.md",
            obs15="true",
        ),
        _failp(
            slug="hubble-istio-customtags-not-otel",
            service="staff-canteen-svc",
            dashboard_uid="canteen-hubble-istio",
            panel="canteen Hubble",
            query='{resource.service.name="staff-canteen-svc"}',
            lie="Adding Istio Telemetry customTags does not export Cilium Hubble L7 flows into Tempo",
            false_lead="Istio sidecar service.name=istio-proxy",
            config_path="istio/canteen-telemetry.yaml",
            lie_path="cilium/hubble-otel.yaml",
            wrong_path="istio/canteen-telemetry.yaml",
            reload_name="istiod",
            ticket="OBS-5211",
            xfail="tests/test_canteen_hubble.py",
            surfaces="Istio leftover vs Hubble-otel export",
            avoided="r222 as actual RCA",
            this_is="fail/handoff: Istio tags on, Hubble still not exporting",
            step_note="Istio tags 6-10; still 0 11; late hubble-otel 12; handoff 14-15.",
            next_note="Next: Kafka lag exporter vs Grafana.",
            query_cmd="curl -sS -G $TEMPO/api/search --data-urlencode 'q={resource.service.name=\"staff-canteen-svc\"}' | jq '.traces|length'",
            false_cmd="yq '.spec.tracing' istio/canteen-telemetry.yaml",
            reload_cmd="kubectl -n istio-system rollout restart deploy/istiod && kubectl -n istio-system rollout status deploy/istiod --timeout=90s",
            requery_cmd="curl -sS -G $TEMPO/api/search --data-urlencode 'q={resource.service.name=\"staff-canteen-svc\"}' | jq '.traces|length'",
            denied_cmd="kubectl -n kube-system auth can-i patch configmap/hubble-otel --as=sre-bot",
            wrong_old="customTags: {}",
            wrong_new="customTags:\n        service.name:\n          value: staff-canteen-svc",
            wrong2_old="providers: []",
            wrong2_new="providers: [otel]",
            ticket_body="OBS-5211: staff-canteen-svc Tempo still 0. Istio tags leftover. Need hubble-otel.enabled. No Hubble RBAC.\n",
            goal="staff-canteen-svc dashboard canteen-hubble-istio Hubble flows empty in Tempo. Land L7 traces.",
            plan="Set Istio customTags service.name (r222 leftover).",
            outcome="Istio tags; still 0. Late hubble-otel false. Handoff OBS-5211.",
            obs1='[{"uid":"canteen-hubble-istio","title":"canteen hubble"}]',
            obs2='{"title":"canteen Hubble","targets":[{"query":"{resource.service.name=\\"staff-canteen-svc\\"}"}]}',
            obs3="0",
            obs4="customTags: {}",
            obs5="Istio telemetry empty — treated as r222",
            obs6="istio/canteen-telemetry.yaml",
            obs7="patched customTags",
            obs8='deployment "istiod" successfully rolled out',
            obs9="0",
            obs10="patched providers otel",
            obs11="0",
            obs12="cilium/hubble-otel.yaml otel.enabled false; hubble observe 31 HTTP",
            obs13="no",
            obs14="wrote tickets/OBS-5211.md",
            obs15="xfail tests/test_canteen_hubble.py",
        ),
    )
)

# r228 Kafka lag exporter vs Grafana (NOT Prom agent, NOT Adaptive Metrics)
MORE.append(
    (
        _okp(
            slug="kminion-lag-vs-grafana-job",
            service="crew-rest-svc",
            dashboard_uid="rest-kminion-3",
            panel="consumer lag",
            query='kafka_consumergroup_lag{job="crew-rest-svc"}',
            lie="Grafana queries kafka_consumergroup_lag{job=crew-rest-svc} but kminion exports job=kminion and group=crew-rest",
            false_lead="Adaptive Metrics dropped job / Prom agent no TSDB",
            config_path="mimir/rest-adaptive.yaml",
            lie_path="grafana/dashboards/rest-kminion-3.json",
            truth_name="kminion metric labels",
            reload_name="grafana",
            side="other kminion groups still labeled group=",
            surfaces="kminion lag labels vs Grafana job matcher",
            avoided="r176 Adaptive Metrics drop instance; r160 Prom agent; r187 native hist",
            this_is="kminion job=kminion group=crew-rest, panel matches job=service",
            step_note="False lead AM/agent 4-5; kminion labels 6-8; match group 9-12.",
            query_cmd="curl -sS -G $MIMIR/prometheus/api/v1/query --data-urlencode 'query=kafka_consumergroup_lag{job=\"crew-rest-svc\"}'",
            false_cmd="yq '.adaptive_metrics.aggregation_rules' mimir/rest-adaptive.yaml",
            truth_cmd="curl -sS -G $MIMIR/prometheus/api/v1/query --data-urlencode 'query=kafka_consumergroup_lag{group=\"crew-rest\"}'",
            confirm_cmd="jq '.panels[0].targets[0].expr' grafana/dashboards/rest-kminion-3.json",
            reload_cmd="kubectl -n grafana rollout restart deploy/grafana && kubectl -n grafana rollout status deploy/grafana --timeout=90s",
            requery_cmd="curl -sS -G $MIMIR/prometheus/api/v1/query --data-urlencode 'query=kafka_consumergroup_lag{group=\"crew-rest\"}'",
            grafana_ok_cmd="curl -sS $GRAFANA/api/ds/query -d @/tmp/rest-km.json | jq '.results.A.frames[0].schema'",
            side_cmd="curl -sS -G $MIMIR/prometheus/api/v1/query --data-urlencode 'query=kafka_consumergroup_lag{group=\"ssr-meal\"}' | jq '.data.result|length'",
            final_cmd="jq -r '.panels[0].targets[0].expr' grafana/dashboards/rest-kminion-3.json",
            patch_old='kafka_consumergroup_lag{job="crew-rest-svc"}',
            patch_new='kafka_consumergroup_lag{group="crew-rest"}',
            runbook_path="runbooks/rest-kminion-lag.md",
            runbook="# crew-rest-svc kminion vs Grafana\nkminion job=kminion, consumer group=crew-rest. Match group not job=service.\nNot Adaptive Metrics.\n",
            goal="crew-rest-svc dashboard rest-kminion-3 consumer lag empty. Kafka has lag. Fix the label lie.",
            plan="Empty job matcher → Adaptive/agent (false) → group=crew-rest series → patch panel.",
            outcome="Panel matches group. lag=842. other groups unchanged.",
            obs1='[{"uid":"rest-kminion-3","title":"crew rest lag"}]',
            obs2='{"title":"consumer lag","targets":[{"expr":"kafka_consumergroup_lag{job=\\"crew-rest-svc\\"}"}]}',
            obs3='{"status":"success","data":{"result":[]}}',
            obs4="aggregation_rules: []  # Adaptive Metrics off — not r176",
            obs5="no Adaptive drop",
            obs6='kafka_consumergroup_lag{job="crew-rest-svc"}',
            obs7='{"status":"success","data":{"result":[{"metric":{"job":"kminion","group":"crew-rest"},"value":[1710000000,"842"]}]}}',
            obs8="job=kminion not crew-rest-svc",
            obs9="patched group=crew-rest",
            obs10='deployment "grafana" successfully rolled out',
            obs11='{"status":"success","data":{"result":[{"value":[1710000600,"842"]}]}}',
            obs12='{"name":"Timeseries"}',
            obs13="1",
            obs14="wrote runbooks/rest-kminion-lag.md",
            obs15='kafka_consumergroup_lag{group="crew-rest"}',
        ),
        _failp(
            slug="kminion-raise-adaptive-not-group",
            service="etops-plan-svc",
            dashboard_uid="etops-kminion-am",
            panel="etops lag",
            query='kafka_consumergroup_lag{job="etops-plan-svc"}',
            lie="Raising Adaptive Metrics label cap does not create kafka_consumergroup_lag{job=etops-plan-svc}; kminion still exports job=kminion group=etops-plan",
            false_lead="Adaptive Metrics dropped job label",
            config_path="mimir/etops-adaptive.yaml",
            lie_path="grafana/dashboards/etops-kminion-am.json",
            wrong_path="mimir/etops-adaptive.yaml",
            reload_name="mimir-adaptive",
            ticket="OBS-5212",
            xfail="tests/test_etops_kminion.py",
            surfaces="Adaptive leftover vs kminion group label",
            avoided="r176 as actual RCA",
            this_is="fail/handoff: Adaptive cap raised, job matcher still empty",
            step_note="Adaptive 6-10; still 0 11; late kminion labels 12; handoff 14-15.",
            next_note="Catalog r217-r228. Keep unique vs r109-r216.",
            query_cmd="curl -sS -G $MIMIR/prometheus/api/v1/query --data-urlencode 'query=kafka_consumergroup_lag{job=\"etops-plan-svc\"}'",
            false_cmd="yq '.adaptive_metrics' mimir/etops-adaptive.yaml",
            reload_cmd="kubectl -n mimir rollout restart deploy/adaptive-metrics && kubectl -n mimir rollout status deploy/adaptive-metrics --timeout=90s",
            requery_cmd="curl -sS -G $MIMIR/prometheus/api/v1/query --data-urlencode 'query=kafka_consumergroup_lag{job=\"etops-plan-svc\"}'",
            denied_cmd="kubectl -n grafana auth can-i patch configmap/grafana-dashboards --as=sre-bot",
            wrong_old="keep_labels: [job]",
            wrong_new="keep_labels: [job, group, topic]",
            wrong2_old="max_series: 10000",
            wrong2_new="max_series: 100000",
            ticket_body="OBS-5212: etops-plan-svc lag still empty on job=. kminion job=kminion group=etops-plan. Need panel group=. No Grafana RBAC.\n",
            goal="etops-plan-svc dashboard etops-kminion-am etops lag empty. Restore lag series.",
            plan="Keep more Adaptive Metrics labels (r176 leftover).",
            outcome="Adaptive cap up; job= still empty. Late kminion labels. Handoff OBS-5212.",
            obs1='[{"uid":"etops-kminion-am","title":"etops lag"}]',
            obs2='{"title":"etops lag","targets":[{"expr":"kafka_consumergroup_lag{job=\\"etops-plan-svc\\"}"}]}',
            obs3='{"status":"success","data":{"result":[]}}',
            obs4="keep_labels: [job]  # treated as r176 drop",
            obs5="Adaptive keep job only",
            obs6="mimir/etops-adaptive.yaml",
            obs7="patched keep group topic",
            obs8='deployment "adaptive-metrics" successfully rolled out',
            obs9='{"status":"success","data":{"result":[]}}',
            obs10="patched max_series 100000",
            obs11='{"status":"success","data":{"result":[]}}',
            obs12="kafka_consumergroup_lag{job=kminion,group=etops-plan}=210; panel still job=etops-plan-svc",
            obs13="no",
            obs14="wrote tickets/OBS-5212.md",
            obs15="xfail tests/test_etops_kminion.py",
        ),
    )
)
