"""Observability leftover leftover leftover leftover plants r516+.

BAN r515 rootly-urgency-filter-silent-drop-leftover / rootly-urg-raise-page-not-filter,
r384 otel-forward-connector-drop-pipeline / otel-fwd-restore-otlp-not-forward,
PagerDuty orch, Opsgenie alias, r163-r515 clones.
Leftover4 lie: silent remap, wrong index, dropped attribute, filter drop.
Not a 1ms integer knob. Not Grafana dataproxy timeout. Not DD env-tag.
"""

from mill_plants_t import _leftover_pair

MORE = []
ROUND_PAIRS = {}


def _emit(round_n, **kwargs):
    dest = []
    _leftover_pair(n=str(round_n), dest=dest, **kwargs)
    MORE.extend(dest)
    ROUND_PAIRS[round_n] = dest[0]


def _l4(
    n,
    *,
    vendor,
    ok_slug,
    bad_slug,
    noun,
    panel,
    needle,
    lie_core,
    false_lead,
    avoided,
    knob,
    old,
    new,
    wrong_knob,
    wrong_old,
    wrong_new,
    wrong2_old,
    wrong2_new,
    prefix,
    kind="grafana",
):
    ok_svc = f"mro-{noun}-svc"
    bad_svc = f"bay-{noun}-svc"
    tag = noun.replace("-", "")[:8]
    vtag = prefix.replace("-", "")[:5]
    ok_dash = f"{tag}-{vtag}-{n}"
    bad_dash = f"b{tag[:7]}-{vtag}-fl"
    _emit(
        n,
        kind=kind,
        ok_slug=ok_slug,
        bad_slug=bad_slug,
        ok_svc=ok_svc,
        bad_svc=bad_svc,
        ok_dash=ok_dash,
        bad_dash=bad_dash,
        panel=panel,
        metric="",
        needle=needle,
        lie=(
            f"{vendor} leftover {lie_core} so Grafana dashboard {ok_dash} is empty "
            f"while the source still 202"
        ),
        bad_lie=(
            f"{false_lead} does not restore leftover leftover leftover leftover "
            f"{lie_core}"
        ),
        false_lead=false_lead,
        avoided=avoided,
        this_is=f"{vendor} leftover leftover leftover leftover {lie_core}",
        ticket=f"OBS-{7700 + (n - 516)}",
        knob=knob,
        old=old,
        new=new,
        wrong_knob=wrong_knob,
        wrong_old=wrong_old,
        wrong_new=wrong_new,
        wrong2_old=wrong2_old,
        wrong2_new=wrong2_new,
        reload="grafana",
        config_path=f"{prefix}/{tag}-false.yaml",
        lie_path=f"{prefix}/{tag}-lie.yaml",
        bad_config=f"{prefix}/b{tag[:7]}-false.yaml",
        bad_lie_path=f"{prefix}/b{tag[:7]}-lie.yaml",
    )


SPECS = [
    dict(
        vendor="Cribl",
        ok_slug="cribl-pipeline-drop-fields-leftover",
        bad_slug="cribl-dropf-raise-workers-not-fields",
        noun="winch",
        panel="Cribl events",
        needle="winch_stall",
        lie_core="pipeline drop_fields strips service",
        false_lead="Cribl worker count leftover",
        avoided="r398 Vector drop_on_error; r177 Alloy relabel; PagerDuty orch; Opsgenie alias; r515 Rootly urgency",
        knob=".pipelines[].drop_fields",
        old="drop_fields: [service]",
        new="drop_fields: []",
        wrong_knob=".workers.count",
        wrong_old="count: 2",
        wrong_new="count: 16",
        wrong2_old="cpu: 1",
        wrong2_new="cpu: 4",
        prefix="cribl",
    ),
    dict(
        vendor="Mezmo",
        ok_slug="mezmo-exclusion-silent-drop-leftover",
        bad_slug="mezmo-excl-raise-retention-not-filter",
        noun="leveler",
        panel="Mezmo logs",
        needle="leveler_jam",
        lie_core="exclusion leftover silently drops mro-leveler-svc",
        false_lead="Mezmo retention leftover",
        avoided="r395 Splunk frozenTime; r399 OpenSearch blocks; PagerDuty orch; Opsgenie alias",
        knob=".exclusions.service",
        old="service: mro-leveler-svc",
        new="service: none",
        wrong_knob=".retention.days",
        wrong_old="days: 3",
        wrong_new="days: 30",
        wrong2_old="index: default",
        wrong2_new="index: hangar",
        prefix="mezmo",
    ),
    dict(
        vendor="Graylog",
        ok_slug="graylog-stream-rule-drop-leftover",
        bad_slug="graylog-stream-raise-shards-not-rule",
        noun="sling",
        panel="Graylog streams",
        needle="sling_overload",
        lie_core="stream rule leftover drops facility hangar so the dashboard is the wrong stream",
        false_lead="Graylog shard count leftover",
        avoided="r399 OpenSearch index-blocks; r511 Kibana index-pattern; r515 Rootly urgency",
        knob=".streams.rules[].drop",
        old="drop: facility:hangar",
        new="drop: none",
        wrong_knob=".elasticsearch.shards",
        wrong_old="shards: 1",
        wrong_new="shards: 5",
        wrong2_old="replicas: 0",
        wrong2_new="replicas: 1",
        prefix="graylog",
    ),
    dict(
        vendor="Sumo Logic",
        ok_slug="sumo-field-extraction-drop-leftover",
        bad_slug="sumo-fe-raise-partition-not-extract",
        noun="boroscope",
        panel="Sumo logs",
        needle="scope_dark",
        lie_core="FER leftover drops field service so Grafana groups the wrong dashboard",
        false_lead="Sumo partition leftover",
        avoided="r500 DD log pipeline remap; r511 Kibana index-pattern; PagerDuty orch",
        knob=".fer.drop_fields",
        old="drop_fields: [service]",
        new="drop_fields: []",
        wrong_knob=".partitions.retention",
        wrong_old="retention: 1d",
        wrong_new="retention: 30d",
        wrong2_old="routing: default",
        wrong2_new="routing: hangar",
        prefix="sumo",
    ),
    dict(
        vendor="Coralogix",
        ok_slug="coralogix-parsing-rule-drop-leftover",
        bad_slug="cxlog-parse-raise-quota-not-rule",
        noun="mule",
        panel="Coralogix logs",
        needle="mule_leak",
        lie_core="parsing rule leftover drops json.service so the panel query matches nothing",
        false_lead="Coralogix quota leftover",
        avoided="r389 Cortex chunks; leftover3 coralogix none; PagerDuty orch; Opsgenie alias",
        knob=".parsing.rules[].drop",
        old="drop: json.service",
        new="drop: none",
        wrong_knob=".quota.daily_gb",
        wrong_old="daily_gb: 1",
        wrong_new="daily_gb: 50",
        wrong2_old="severity: ERROR",
        wrong2_new="severity: INFO",
        prefix="coralogix",
    ),
    dict(
        vendor="Better Stack",
        ok_slug="betterstack-source-filter-drop-leftover",
        bad_slug="bstack-src-raise-retention-not-filter",
        noun="autoclave",
        panel="Better Stack logs",
        needle="autoclave_overtemp",
        lie_core="source filter leftover silently drops mro-autoclave-svc",
        false_lead="Better Stack retention leftover",
        avoided="r521 clone none; r395 Splunk frozen; r515 Rootly urgency; Opsgenie alias",
        knob=".sources[].exclude",
        old="exclude: mro-autoclave-svc",
        new="exclude: none",
        wrong_knob=".retention.hours",
        wrong_old="hours: 24",
        wrong_new="hours: 720",
        wrong2_old="team: default",
        wrong2_new="team: mro",
        prefix="bstack",
    ),
    dict(
        vendor="Logz.io",
        ok_slug="logz-drop-filter-silent-leftover",
        bad_slug="logz-dropf-raise-shards-not-filter",
        noun="eddy",
        panel="Logz logs",
        needle="eddy_fail",
        lie_core="drop filter leftover matches job=mro-eddy-svc so Grafana is empty while ingest still 202",
        false_lead="Logz shard leftover",
        avoided="r399 OpenSearch blocks; r511 Kibana pattern; PagerDuty orch; r515 Rootly",
        knob=".filters.drop.query",
        old='query: job:mro-eddy-svc',
        new="query: none",
        wrong_knob=".index.shards",
        wrong_old="shards: 1",
        wrong_new="shards: 3",
        wrong2_old="refresh: 60s",
        wrong2_new="refresh: 1s",
        prefix="logz",
    ),
    dict(
        vendor="Sematext",
        ok_slug="sematext-token-remap-wrong-dash-leftover",
        bad_slug="smtxt-token-raise-plan-not-remap",
        noun="ultrasonic",
        panel="Sematext logs",
        needle="ut_skip",
        lie_core="token leftover remaps mro-ultrasonic-svc into sandbox-app so Grafana is the wrong dashboard",
        false_lead="Sematext plan leftover",
        avoided="r500 DD pipeline remap; r502 Honeycomb dataset alias; Opsgenie alias",
        knob=".apps.token_map",
        old="token_map: sandbox-app",
        new="token_map: mro-ultrasonic-svc",
        wrong_knob=".plan.max_gb",
        wrong_old="max_gb: 1",
        wrong_new="max_gb: 40",
        wrong2_old="region: us",
        wrong2_new="region: eu",
        prefix="sematext",
    ),
    dict(
        vendor="Papertrail",
        ok_slug="papertrail-system-filter-drop-leftover",
        bad_slug="ptrail-sys-raise-search-not-filter",
        noun="xray",
        panel="Papertrail logs",
        needle="xray_blank",
        lie_core="system filter leftover drops host hangar-xray so the dashboard is empty",
        false_lead="Papertrail search window leftover",
        avoided="r395 Splunk frozen; r398 Vector drop; PagerDuty orch; r515 Rootly urgency",
        knob=".systems.exclude",
        old="exclude: hangar-xray",
        new="exclude: none",
        wrong_knob=".search.hours",
        wrong_old="hours: 1",
        wrong_new="hours: 48",
        wrong2_old="saved_search: default",
        wrong2_new="saved_search: mro",
        prefix="papertrail",
    ),
    dict(
        vendor="Loggly",
        ok_slug="loggly-tag-drop-silent-leftover",
        bad_slug="loggly-tag-raise-retention-not-drop",
        noun="paintbooth",
        panel="Loggly events",
        needle="booth_overtemp",
        lie_core="tag leftover strips service so Grafana dashboard groups the wrong tag",
        false_lead="Loggly retention leftover",
        avoided="r500 DD remap; r177 Alloy relabel; Opsgenie alias; r515 Rootly urgency",
        knob=".tags.drop",
        old="drop: [service]",
        new="drop: []",
        wrong_knob=".retention.days",
        wrong_old="days: 7",
        wrong_new="days: 90",
        wrong2_old="source: syslog",
        wrong2_new="source: json",
        prefix="loggly",
    ),
    dict(
        vendor="Fluentd",
        ok_slug="fluentd-match-rewrite-drop-leftover",
        bad_slug="fluentd-match-raise-buffer-not-rewrite",
        noun="striptank",
        panel="Fluentd logs",
        needle="tank_empty",
        lie_core="match rewrite leftover rewrites job to archive so Grafana is the wrong dashboard",
        false_lead="Fluentd buffer leftover",
        avoided="r398 fluentbit mem-buf; r177 Alloy relabel; PagerDuty orch; r384 OTel forward",
        knob=".match.rewrite.job",
        old="job: archive",
        new="job: mro-striptank-svc",
        wrong_knob=".buffer.chunk_limit_size",
        wrong_old="chunk_limit_size: 1k",
        wrong_new="chunk_limit_size: 8m",
        wrong2_old="flush_interval: 60s",
        wrong2_new="flush_interval: 1s",
        prefix="fluentd",
    ),
    dict(
        vendor="Logstash",
        ok_slug="logstash-mutate-drop-field-leftover",
        bad_slug="lstash-mut-raise-workers-not-drop",
        noun="compoven",
        panel="Logstash events",
        needle="oven_hold",
        lie_core="mutate drop leftover removes [service] so Grafana LogQL matches nothing",
        false_lead="Logstash pipeline workers leftover",
        avoided="r398 Vector drop_on_error; r177 Alloy relabel; r384 OTel forward; Opsgenie alias",
        knob=".filter.mutate.drop",
        old="drop => [service]",
        new="drop => []",
        wrong_knob=".pipeline.workers",
        wrong_old="workers: 1",
        wrong_new="workers: 8",
        wrong2_old="batch_size: 1",
        wrong2_new="batch_size: 125",
        prefix="logstash",
    ),
    dict(
        vendor="Filebeat",
        ok_slug="filebeat-drop-event-contains-leftover",
        bad_slug="fbeat-drop-raise-harvester-not-event",
        noun="wheeljig",
        panel="Filebeat logs",
        needle="jig_slip",
        lie_core="drop_event contains leftover silently drops lines with mro-wheeljig-svc",
        false_lead="Filebeat harvester leftover",
        avoided="r398 fluentbit mem-buf; r177 Alloy relabel; PagerDuty orch; r515 Rootly",
        knob=".processors.drop_event.contains",
        old="contains: mro-wheeljig-svc",
        new="contains: none",
        wrong_knob=".filebeat.harvester.limit",
        wrong_old="limit: 1",
        wrong_new="limit: 32",
        wrong2_old="scan_frequency: 1h",
        wrong2_new="scan_frequency: 10s",
        prefix="filebeat",
    ),
    dict(
        vendor="Metricbeat",
        ok_slug="metricbeat-module-disable-leftover",
        bad_slug="mbeat-mod-raise-period-not-enable",
        noun="brakelathe",
        panel="Metricbeat series",
        needle="lathe_bind",
        lie_core="module leftover enabled:false so Grafana is empty while /metrics still 200",
        false_lead="Metricbeat period leftover",
        avoided="r504 Prom honor_labels; r190 DD UST; r163 tid128; Opsgenie alias",
        knob=".metricbeat.modules[].enabled",
        old="enabled: false",
        new="enabled: true",
        wrong_knob=".metricbeat.modules[].period",
        wrong_old="period: 5m",
        wrong_new="period: 10s",
        wrong2_old="hosts: []",
        wrong2_new="hosts: [localhost]",
        prefix="metricbeat",
    ),
    dict(
        vendor="journald",
        ok_slug="journald-unit-drop-filter-leftover",
        bad_slug="journald-unit-raise-storage-not-filter",
        noun="battbench",
        panel="journald units",
        needle="batt_open",
        lie_core="Units leftover drop mro-battbench-svc.service so Grafana is empty while journalctl still has lines",
        false_lead="journald storage leftover",
        avoided="r398 fluentbit; r395 Splunk frozen; PagerDuty orch; r515 Rootly urgency",
        knob=".journald.drop_units",
        old="drop_units: [mro-battbench-svc.service]",
        new="drop_units: []",
        wrong_knob=".journald.storage",
        wrong_old="storage: volatile",
        wrong_new="storage: persistent",
        wrong2_old="max_use: 1M",
        wrong2_new="max_use: 1G",
        prefix="journald",
    ),
    dict(
        vendor="rsyslog",
        ok_slug="rsyslog-property-filter-drop-leftover",
        bad_slug="rsyslog-prop-raise-queue-not-filter",
        noun="seatbench",
        panel="rsyslog lines",
        needle="seat_track",
        lie_core="property filter leftover drops msg containing mro-seatbench-svc",
        false_lead="rsyslog queue leftover",
        avoided="r398 Vector drop; fluentd rewrite plant; PagerDuty orch; Opsgenie alias",
        knob=".filters.property.drop",
        old="drop: mro-seatbench-svc",
        new="drop: none",
        wrong_knob=".queue.size",
        wrong_old="size: 100",
        wrong_new="size: 100000",
        wrong2_old="discardMark: 1",
        wrong2_new="discardMark: 80000",
        prefix="rsyslog",
    ),
    dict(
        vendor="syslog-ng",
        ok_slug="syslogng-rewrite-set-host-leftover",
        bad_slug="syslogng-rw-raise-window-not-host",
        noun="galleybench",
        panel="syslog-ng hosts",
        needle="galley_trip",
        lie_core="rewrite leftover sets host=archive so Grafana is the wrong dashboard",
        false_lead="syslog-ng log fifo leftover",
        avoided="r177 Alloy relabel; fluentd match rewrite; r384 OTel forward; r515 Rootly",
        knob=".rewrite.set.host",
        old="host: archive",
        new="host: mro-galleybench-svc",
        wrong_knob=".log.fifo_size",
        wrong_old="fifo_size: 10",
        wrong_new="fifo_size: 10000",
        wrong2_old="flush_lines: 1000",
        wrong2_new="flush_lines: 1",
        prefix="syslogng",
    ),
    dict(
        vendor="Telegraf",
        ok_slug="telegraf-namepass-drop-metric-leftover",
        bad_slug="telegraf-np-raise-interval-not-namepass",
        noun="ifebench",
        panel="Telegraf metrics",
        needle="ife_blank",
        lie_core="namepass leftover keeps only cpu so Grafana job=mro-ifebench-svc is empty",
        false_lead="Telegraf interval leftover",
        avoided="r504 Prom honor_labels; leftover3 VM relabel; r177 Alloy relabel",
        knob=".outputs.prometheus_client.namepass",
        old="namepass: [cpu]",
        new="namepass: [*]",
        wrong_knob=".agent.interval",
        wrong_old="interval: 5m",
        wrong_new="interval: 10s",
        wrong2_old="hostname: telegraf",
        wrong2_new="hostname: mro-ifebench-svc",
        prefix="telegraf",
    ),
    dict(
        vendor="collectd",
        ok_slug="collectd-plugin-filter-drop-leftover",
        bad_slug="collectd-plug-raise-interval-not-filter",
        noun="radiobench",
        panel="collectd metrics",
        needle="radio_mute",
        lie_core="plugin filter leftover Ignore mro-radiobench-svc so Grafana is empty",
        false_lead="collectd Interval leftover",
        avoided="r504 Prom honor_labels; telegraf namepass plant; leftover3 VM relabel",
        knob=".Filter.Ignore",
        old="Ignore: mro-radiobench-svc",
        new="Ignore: none",
        wrong_knob=".Interval",
        wrong_old="Interval: 300",
        wrong_new="Interval: 10",
        wrong2_old="FQDNLookup: false",
        wrong2_new="FQDNLookup: true",
        prefix="collectd",
    ),
    dict(
        vendor="Graphite carbon",
        ok_slug="carbon-rewrite-drop-metric-leftover",
        bad_slug="carbon-rw-raise-cache-not-rewrite",
        noun="gyrostool",
        panel="Carbon metrics",
        needle="gyro_drift",
        lie_core="rewrite leftover drops ^mro-gyrostool so Grafana is empty while whisper still has files",
        false_lead="carbon cache leftover",
        avoided="r387 chrono drop metric name; leftover3 graphite none; r515 Rootly urgency",
        knob=".rewrite.rules[].drop",
        old="drop: ^mro-gyrostool",
        new="drop: none",
        wrong_knob=".cache.max_updates",
        wrong_old="max_updates: 1",
        wrong_new="max_updates: 500",
        wrong2_old="whisper: false",
        wrong2_new="whisper: true",
        prefix="carbon",
    ),
    dict(
        vendor="Netdata",
        ok_slug="netdata-chart-hide-silent-leftover",
        bad_slug="netdata-hide-raise-update-not-chart",
        noun="compasswing",
        panel="Netdata charts",
        needle="swing_off",
        lie_core="chart hide leftover enabled=no for mro-compasswing-svc so Grafana is empty",
        false_lead="Netdata update every leftover",
        avoided="r536 clone none; r504 Prom honor_labels; PagerDuty orch; Opsgenie alias",
        knob=".charts.mro-compasswing.enabled",
        old="enabled: no",
        new="enabled: yes",
        wrong_knob=".global.update every",
        wrong_old="update every: 60",
        wrong_new="update every: 1",
        wrong2_old="memory mode: ram",
        wrong2_new="memory mode: dbengine",
        prefix="netdata",
    ),
    dict(
        vendor="Zabbix",
        ok_slug="zabbix-preprocessing-drop-leftover",
        bad_slug="zabbix-prep-raise-history-not-drop",
        noun="pitotset",
        panel="Zabbix items",
        needle="pitot_leak",
        lie_core="preprocessing leftover Discard value on match so Grafana item is empty while agent still 200",
        false_lead="Zabbix history leftover",
        avoided="r542 SolarWinds plant later; PagerDuty orch; Opsgenie alias; r515 Rootly",
        knob=".items.preprocessing.discard",
        old="discard: match mro-pitotset-svc",
        new="discard: none",
        wrong_knob=".items.history",
        wrong_old="history: 1h",
        wrong_new="history: 90d",
        wrong2_old="trends: 0d",
        wrong2_new="trends: 365d",
        prefix="zabbix",
    ),
    dict(
        vendor="Nagios",
        ok_slug="nagios-servicegroup-remap-leftover",
        bad_slug="nagios-sg-raise-interval-not-group",
        noun="rvsmset",
        panel="Nagios services",
        needle="rvsm_fail",
        lie_core="servicegroup leftover remaps mro-rvsmset-svc into archive-group so Grafana is the wrong dashboard",
        false_lead="Nagios check_interval leftover",
        avoided="r505 AM continue wrong receiver; PagerDuty orch; Opsgenie alias; r515 Rootly",
        knob=".servicegroups.members",
        old="members: archive-group",
        new="members: mro-rvsmset-svc",
        wrong_knob=".services.check_interval",
        wrong_old="check_interval: 60",
        wrong_new="check_interval: 1",
        wrong2_old="max_check_attempts: 1",
        wrong2_new="max_check_attempts: 3",
        prefix="nagios",
    ),
    dict(
        vendor="Icinga",
        ok_slug="icinga-notification-filter-drop-leftover",
        bad_slug="icinga-notif-raise-period-not-filter",
        noun="alttest",
        panel="Icinga notifications",
        needle="alt_drift",
        lie_core="notification filter leftover states=OK so Grafana incident panel is empty while checks still CRITICAL",
        false_lead="Icinga period leftover",
        avoided="r505 AM continue; r515 Rootly urgency; PagerDuty orch; Opsgenie alias",
        knob=".notifications.states",
        old="states: [OK]",
        new="states: [OK, Warning, Critical]",
        wrong_knob=".notifications.period",
        wrong_old="period: never",
        wrong_new="period: 24x7",
        wrong2_old="users: []",
        wrong2_new="users: [mro]",
        prefix="icinga",
    ),
    dict(
        vendor="Checkmk",
        ok_slug="checkmk-host-label-drop-leftover",
        bad_slug="checkmk-label-raise-cache-not-drop",
        noun="xpdrset",
        panel="Checkmk hosts",
        needle="xpdr_mute",
        lie_core="host label leftover drops job so Grafana dashboard is the wrong host group",
        false_lead="Checkmk cache leftover",
        avoided="r177 Alloy relabel; r504 Prom honor_labels; Opsgenie alias; r515 Rootly",
        knob=".host_labels.drop",
        old="drop: [job]",
        new="drop: []",
        wrong_knob=".cache.ttl",
        wrong_old="ttl: 1d",
        wrong_new="ttl: 60s",
        wrong2_old="site: default",
        wrong2_new="site: hangar",
        prefix="checkmk",
    ),
    dict(
        vendor="PRTG",
        ok_slug="prtg-channel-hide-silent-leftover",
        bad_slug="prtg-ch-raise-interval-not-hide",
        noun="tcastest",
        panel="PRTG channels",
        needle="tcas_blank",
        lie_core="channel hide leftover Show=0 so Grafana is empty while the sensor still Up",
        false_lead="PRTG scanning interval leftover",
        avoided="netdata chart hide plant; PagerDuty orch; Opsgenie alias; r515 Rootly urgency",
        knob=".channels.show",
        old="show: 0",
        new="show: 1",
        wrong_knob=".sensors.interval",
        wrong_old="interval: 3600",
        wrong_new="interval: 30",
        wrong2_old="priority: 1",
        wrong2_new="priority: 4",
        prefix="prtg",
    ),
    dict(
        vendor="SolarWinds",
        ok_slug="solarwinds-custom-property-drop-leftover",
        bad_slug="swinds-cp-raise-poll-not-property",
        noun="wxtest",
        panel="SolarWinds nodes",
        needle="wx_blank",
        lie_core="custom property leftover drops service so Grafana SWQL is the wrong dashboard",
        false_lead="SolarWinds poll leftover",
        avoided="zabbix preprocessing plant; r177 Alloy relabel; PagerDuty orch; Opsgenie alias",
        knob=".nodes.custom_properties.drop",
        old="drop: [service]",
        new="drop: []",
        wrong_knob=".polling.interval",
        wrong_old="interval: 3600",
        wrong_new="interval: 60",
        wrong2_old="engine: default",
        wrong2_new="engine: hangar",
        prefix="solarwinds",
    ),
    dict(
        vendor="VictorOps",
        ok_slug="victorops-routing-key-drop-leftover",
        bad_slug="vops-rk-raise-timeout-not-key",
        noun="elttest",
        panel="VictorOps incidents",
        needle="elt_fail",
        lie_core="routing_key leftover team=none silently drops pages so Grafana is empty while webhooks still 202",
        false_lead="VictorOps timeout leftover",
        avoided="PagerDuty orch; Opsgenie alias; r515 Rootly urgency; r512 Grafana OnCall team",
        knob=".routing_keys.team",
        old="team: none",
        new="team: mro-elttest-svc",
        wrong_knob=".pages.timeout_seconds",
        wrong_old="timeout_seconds: 300",
        wrong_new="timeout_seconds: 0",
        wrong2_old="escalation: skip",
        wrong2_new="escalation: default",
        prefix="victorops",
    ),
    dict(
        vendor="Squadcast",
        ok_slug="squadcast-service-map-wrong-dash-leftover",
        bad_slug="scast-map-raise-sla-not-service",
        noun="oxyshop",
        panel="Squadcast alerts",
        needle="oxy_low",
        lie_core="service map leftover binds mro-oxyshop-svc to sandbox-service so Grafana is the wrong dashboard",
        false_lead="Squadcast SLA leftover",
        avoided="PagerDuty orch; Opsgenie alias; r512 OnCall team; r515 Rootly urgency",
        knob=".services.map",
        old="map: sandbox-service",
        new="map: mro-oxyshop-svc",
        wrong_knob=".sla.ack_minutes",
        wrong_old="ack_minutes: 60",
        wrong_new="ack_minutes: 5",
        wrong2_old="escalation: none",
        wrong2_new="escalation: mro",
        prefix="squadcast",
    ),
    dict(
        vendor="Zenduty",
        ok_slug="zenduty-event-filter-drop-leftover",
        bad_slug="zduty-ev-raise-dedup-not-filter",
        noun="slideshop",
        panel="Zenduty events",
        needle="slide_pack",
        lie_core="event filter leftover severity=info-only silently drops crit so Grafana is empty",
        false_lead="Zenduty dedup leftover",
        avoided="PagerDuty orch; Opsgenie alias; r515 Rootly urgency filter; r505 AM continue",
        knob=".events.severity_filter",
        old="severity_filter: info",
        new="severity_filter: info,warning,critical",
        wrong_knob=".dedup.window_seconds",
        wrong_old="window_seconds: 3600",
        wrong_new="window_seconds: 60",
        wrong2_old="service: default",
        wrong2_new="service: mro",
        prefix="zenduty",
    ),
    dict(
        vendor="ilert",
        ok_slug="ilert-alert-source-filter-drop-leftover",
        bad_slug="ilert-src-raise-escalation-not-filter",
        noun="raftshop",
        panel="ilert alerts",
        needle="raft_leak",
        lie_core="alert source leftover filter=heartbeat-only silently drops Grafana so the panel is empty",
        false_lead="ilert escalation leftover",
        avoided="PagerDuty orch; Opsgenie alias; r513 incidentio source; r515 Rootly urgency",
        knob=".alert_sources.filter",
        old="filter: heartbeat",
        new="filter: all",
        wrong_knob=".escalation.delay_minutes",
        wrong_old="delay_minutes: 30",
        wrong_new="delay_minutes: 0",
        wrong2_old="policy: default",
        wrong2_new="policy: mro",
        prefix="ilert",
    ),
    dict(
        vendor="BigPanda",
        ok_slug="bigpanda-enrichment-drop-tag-leftover",
        bad_slug="bpanda-enr-raise-corr-not-tag",
        noun="fabricshop",
        panel="BigPanda incidents",
        needle="fabric_tear",
        lie_core="enrichment leftover drops tag service so Grafana correlation is the wrong dashboard",
        false_lead="BigPanda correlation leftover",
        avoided="PagerDuty orch; Opsgenie alias; r514 FireHydrant signal labels; r177 Alloy relabel",
        knob=".enrichment.drop_tags",
        old="drop_tags: [service]",
        new="drop_tags: []",
        wrong_knob=".correlation.window",
        wrong_old="window: 1h",
        wrong_new="window: 5m",
        wrong2_old="source: generic",
        wrong2_new="source: grafana",
        prefix="bigpanda",
    ),
    dict(
        vendor="Moogsoft",
        ok_slug="moogsoft-clustering-algo-drop-leftover",
        bad_slug="moog-cl-raise-cookbook-not-algo",
        noun="sheetmetal",
        panel="Moogsoft situations",
        needle="sheet_crack",
        lie_core="clustering leftover algorithm=none so Grafana situations panel is empty while events still 202",
        false_lead="Moogsoft cookbook leftover",
        avoided="PagerDuty orch; Opsgenie alias; BigPanda enrichment plant; r515 Rootly",
        knob=".clustering.algorithm",
        old="algorithm: none",
        new="algorithm: vertex_entropy",
        wrong_knob=".cookbooks.active",
        wrong_old="active: false",
        wrong_new="active: true",
        wrong2_old="resolver: default",
        wrong2_new="resolver: mro",
        prefix="moogsoft",
    ),
    dict(
        vendor="xMatters",
        ok_slug="xmatters-form-filter-drop-leftover",
        bad_slug="xmatters-form-raise-delay-not-filter",
        noun="millshop",
        panel="xMatters forms",
        needle="mill_bind",
        lie_core="form filter leftover status=TEST silently drops prod events so Grafana is empty",
        false_lead="xMatters delay leftover",
        avoided="PagerDuty orch; Opsgenie alias; r515 Rootly page delay; r512 OnCall team",
        knob=".forms.status_filter",
        old="status_filter: TEST",
        new="status_filter: ACTIVE",
        wrong_knob=".notify.delay_seconds",
        wrong_old="delay_seconds: 300",
        wrong_new="delay_seconds: 0",
        wrong2_old="recipients: []",
        wrong2_new="recipients: [mro]",
        prefix="xmatters",
    ),
    dict(
        vendor="ServiceNow EM",
        ok_slug="snowem-transform-drop-ci-leftover",
        bad_slug="snowem-xf-raise-priority-not-ci",
        noun="weldbooth",
        panel="ServiceNow events",
        needle="weld_gas",
        lie_core="transform leftover drops cmdb_ci so Grafana EM dashboard is the wrong CI",
        false_lead="ServiceNow priority leftover",
        avoided="PagerDuty orch; Opsgenie alias; r513 incidentio source; r515 Rootly urgency",
        knob=".em.transform.drop_fields",
        old="drop_fields: [cmdb_ci]",
        new="drop_fields: []",
        wrong_knob=".em.priority",
        wrong_old="priority: 5",
        wrong_new="priority: 2",
        wrong2_old="source: generic",
        wrong2_new="source: grafana",
        prefix="snowem",
    ),
    dict(
        vendor="Bugsnag",
        ok_slug="bugsnag-release-stage-filter-drop-leftover",
        bad_slug="bugsnag-stage-raise-quota-not-filter",
        noun="heattreat",
        panel="Bugsnag errors",
        needle="oven_trip",
        lie_core="releaseStage leftover notify=development so Grafana is empty while /notify still 200",
        false_lead="Bugsnag quota leftover",
        avoided="r501 Sentry inbound-filter; r386 Sentry ignore-errors; PagerDuty orch; Opsgenie alias",
        knob=".notify.releaseStage",
        old="releaseStage: development",
        new="releaseStage: production",
        wrong_knob=".quota.max_events",
        wrong_old="max_events: 100",
        wrong_new="max_events: 100000",
        wrong2_old="autoNotify: false",
        wrong2_new="autoNotify: true",
        prefix="bugsnag",
    ),
    dict(
        vendor="Rollbar",
        ok_slug="rollbar-person-tracking-drop-leftover",
        bad_slug="rollbar-person-raise-rate-not-drop",
        noun="plating",
        panel="Rollbar items",
        needle="plate_peel",
        lie_core="person tracking leftover captureIp=anonymize plus filter drops server.service so Grafana is empty",
        false_lead="Rollbar rate leftover",
        avoided="r501 Sentry inbound-filter; r386 Sentry ignore-errors; Opsgenie alias; r515 Rootly",
        knob=".person.filter.service",
        old="service: drop",
        new="service: keep",
        wrong_knob=".rate.max_items",
        wrong_old="max_items: 10",
        wrong_new="max_items: 5000",
        wrong2_old="environment: test",
        wrong2_new="environment: production",
        prefix="rollbar",
    ),
    dict(
        vendor="Airbrake",
        ok_slug="airbrake-environment-filter-drop-leftover",
        bad_slug="airbrake-env-raise-project-not-filter",
        noun="nitaletch",
        panel="Airbrake errors",
        needle="etch_over",
        lie_core="environment leftover ignore=production so Grafana is empty while the notifier still 201",
        false_lead="Airbrake project leftover",
        avoided="r501 Sentry inbound-filter; Bugsnag releaseStage plant; PagerDuty orch; Opsgenie alias",
        knob=".ignore_environments",
        old="ignore_environments: [production]",
        new="ignore_environments: []",
        wrong_knob=".project_id",
        wrong_old="project_id: 1",
        wrong_new="project_id: 88421",
        wrong2_old="performance_stats: false",
        wrong2_new="performance_stats: true",
        prefix="airbrake",
    ),
    dict(
        vendor="Raygun",
        ok_slug="raygun-tagging-drop-service-leftover",
        bad_slug="raygun-tag-raise-pulse-not-drop",
        noun="fpibooth",
        panel="Raygun crashes",
        needle="fpi_dark",
        lie_core="tagging leftover strips service so Grafana crash dashboard is the wrong app",
        false_lead="Raygun Pulse leftover",
        avoided="r501 Sentry inbound-filter; r177 Alloy relabel; Opsgenie alias; r515 Rootly",
        knob=".tags.drop",
        old="drop: [service]",
        new="drop: []",
        wrong_knob=".pulse.enabled",
        wrong_old="enabled: false",
        wrong_new="enabled: true",
        wrong2_old="apm: off",
        wrong2_new="apm: on",
        prefix="raygun",
    ),
    dict(
        vendor="GlitchTip",
        ok_slug="glitchtip-project-remap-wrong-dash-leftover",
        bad_slug="gtip-proj-raise-dsn-not-remap",
        noun="mpibench",
        panel="GlitchTip issues",
        needle="mpi_skip",
        lie_core="project leftover remaps DSN to sandbox so Grafana is the wrong dashboard",
        false_lead="GlitchTip DSN leftover",
        avoided="r501 Sentry inbound-filter; r386 Sentry ignore-errors; Honeycomb dataset alias; Opsgenie alias",
        knob=".projects.remap",
        old="remap: sandbox",
        new="remap: mro-mpibench-svc",
        wrong_knob=".dsn.rate",
        wrong_old="rate: 1",
        wrong_new="rate: 100",
        wrong2_old="platform: python",
        wrong2_new="platform: go",
        prefix="glitchtip",
    ),
    dict(
        vendor="Highlight",
        ok_slug="highlight-session-filter-drop-leftover",
        bad_slug="highlight-sess-raise-sample-not-filter",
        noun="cmmroom",
        panel="Highlight sessions",
        needle="cmm_crash",
        lie_core="session filter leftover environment=dev silently drops prod so Grafana is empty",
        false_lead="Highlight sampling leftover",
        avoided="r168 Faro session; r501 Sentry inbound-filter; PagerDuty orch; Opsgenie alias",
        knob=".sessions.environment",
        old="environment: dev",
        new="environment: production",
        wrong_knob=".sampling.rate",
        wrong_old="rate: 0.01",
        wrong_new="rate: 1.0",
        wrong2_old="backend_url: staging",
        wrong2_new="backend_url: https://pub.highlight.io",
        prefix="highlight",
    ),
    dict(
        vendor="OpenReplay",
        ok_slug="openreplay-project-drop-leftover",
        bad_slug="oreplay-proj-raise-ingest-not-drop",
        noun="lasertrack",
        panel="OpenReplay sessions",
        needle="track_loss",
        lie_core="project leftover disabled=true silently drops sessions so Grafana is empty while ingest still 202",
        false_lead="OpenReplay ingest leftover",
        avoided="r168 Faro session; Highlight session plant; PagerDuty orch; Opsgenie alias",
        knob=".projects.disabled",
        old="disabled: true",
        new="disabled: false",
        wrong_knob=".ingest.workers",
        wrong_old="workers: 1",
        wrong_new="workers: 8",
        wrong2_old="storage: minio-dev",
        wrong2_new="storage: minio-prod",
        prefix="openreplay",
    ),
    dict(
        vendor="Axiom",
        ok_slug="axiom-dataset-remap-wrong-dash-leftover",
        bad_slug="axiom-ds-raise-query-not-remap",
        noun="engcell",
        panel="Axiom datasets",
        needle="cell_trip",
        lie_core="dataset leftover remaps mro-engcell-svc into sandbox so Grafana is the wrong dashboard",
        false_lead="Axiom query limit leftover",
        avoided="r502 Honeycomb dataset alias; r500 DD pipeline remap; r511 Kibana pattern",
        knob=".datasets.remap",
        old="remap: sandbox",
        new="remap: mro-engcell-svc",
        wrong_knob=".query.max_rows",
        wrong_old="max_rows: 1",
        wrong_new="max_rows: 100000",
        wrong2_old="token: ingest-only",
        wrong2_new="token: query",
        prefix="axiom",
    ),
    dict(
        vendor="Hydrolix",
        ok_slug="hydrolix-transform-drop-column-leftover",
        bad_slug="hdrolix-xf-raise-view-not-drop",
        noun="apucell",
        panel="Hydrolix columns",
        needle="apu_hung",
        lie_core="transform leftover drops column service so Grafana is the wrong dashboard",
        false_lead="Hydrolix view leftover",
        avoided="r400 ClickHouse max_result_rows; r189 CH SQL vs Tempo; PagerDuty orch",
        knob=".transforms.drop_columns",
        old="drop_columns: [service]",
        new="drop_columns: []",
        wrong_knob=".views.default",
        wrong_old="default: sandbox",
        wrong_new="default: hangar",
        wrong2_old="merge: off",
        wrong2_new="merge: on",
        prefix="hydrolix",
    ),
    dict(
        vendor="Tinybird",
        ok_slug="tinybird-pipe-filter-drop-leftover",
        bad_slug="tinybird-pipe-raise-qps-not-filter",
        noun="idgstand",
        panel="Tinybird pipes",
        needle="idg_trip",
        lie_core="pipe filter leftover WHERE service!='mro-idgstand-svc' so Grafana is empty",
        false_lead="Tinybird QPS leftover",
        avoided="r400 ClickHouse rows; Hydrolix transform plant; Opsgenie alias; r515 Rootly",
        knob=".pipes.filter",
        old="filter: service != 'mro-idgstand-svc'",
        new="filter: 1=1",
        wrong_knob=".workspace.qps",
        wrong_old="qps: 1",
        wrong_new="qps: 100",
        wrong2_old="token: read",
        wrong2_new="token: admin",
        prefix="tinybird",
    ),
    dict(
        vendor="Last9",
        ok_slug="last9-drop-rule-metric-leftover",
        bad_slug="last9-drop-raise-cardinality-not-rule",
        noun="pumpstand",
        panel="Last9 metrics",
        needle="pump_cavitation",
        lie_core="drop_rule leftover matches job=mro-pumpstand-svc so Grafana is empty while remote_write still 204",
        false_lead="Last9 cardinality leftover",
        avoided="r387 chrono drop metric; leftover3 VM relabel; r504 Prom honor_labels",
        knob=".drop_rules[].match",
        old="match: job=mro-pumpstand-svc",
        new="match: none",
        wrong_knob=".limits.cardinality",
        wrong_old="cardinality: 100",
        wrong_new="cardinality: 1000000",
        wrong2_old="retention: 1d",
        wrong2_new="retention: 13m",
        prefix="last9",
    ),
    dict(
        vendor="groundcover",
        ok_slug="groundcover-ebpf-filter-drop-leftover",
        bad_slug="gcover-ebpf-raise-sample-not-filter",
        noun="actrig",
        panel="groundcover traces",
        needle="act_bind",
        lie_core="eBPF filter leftover drop mro-actrig-svc so Grafana is empty while the sensor still 202",
        false_lead="groundcover sampling leftover",
        avoided="leftover3 eBPF map_max_entries; leftover3 Beyla exclude; r384 OTel forward",
        knob=".ebpf.drop_services",
        old="drop_services: [mro-actrig-svc]",
        new="drop_services: []",
        wrong_knob=".sampling.ratio",
        wrong_old="ratio: 0.01",
        wrong_new="ratio: 1.0",
        wrong2_old="cluster: sandbox",
        wrong2_new="cluster: hangar",
        prefix="groundcover",
    ),
    dict(
        vendor="Coroot",
        ok_slug="coroot-recording-drop-leftover",
        bad_slug="coroot-rec-raise-scrape-not-drop",
        noun="cablerig",
        panel="Coroot services",
        needle="cable_slack",
        lie_core="recording leftover skip mro-cablerig-svc so Grafana SLO panel is empty",
        false_lead="Coroot scrape leftover",
        avoided="r504 Prom honor_labels; leftover3 VM relabel; PagerDuty orch; Opsgenie alias",
        knob=".recordings.skip",
        old="skip: [mro-cablerig-svc]",
        new="skip: []",
        wrong_knob=".scrape.interval",
        wrong_old="interval: 5m",
        wrong_new="interval: 15s",
        wrong2_old="clickhouse: off",
        wrong2_new="clickhouse: on",
        prefix="coroot",
    ),
    dict(
        vendor="qryn",
        ok_slug="qryn-ingest-drop-tenant-leftover",
        bad_slug="qryn-ing-raise-timeout-not-drop",
        noun="fcrig",
        panel="qryn tenants",
        needle="fc_bind",
        lie_core="ingest leftover drop_tenant=mro-fcrig-svc so Grafana is empty while Loki push still 204",
        false_lead="qryn timeout leftover",
        avoided="r399 Loki max_query_series; leftover3 ClickHouse rows; r384 OTel forward",
        knob=".ingest.drop_tenants",
        old="drop_tenants: [mro-fcrig-svc]",
        new="drop_tenants: []",
        wrong_knob=".query.timeout",
        wrong_old="timeout: 1s",
        wrong_new="timeout: 30s",
        wrong2_old="clickhouse: local",
        wrong2_new="clickhouse: cluster",
        prefix="qryn",
    ),
    dict(
        vendor="Dash0",
        ok_slug="dash0-attribute-drop-service-leftover",
        bad_slug="dash0-attr-raise-export-not-drop",
        noun="gearjig",
        panel="Dash0 traces",
        needle="jig_offset",
        lie_core="attribute leftover drops resource.service.name so Grafana is the wrong dashboard",
        false_lead="Dash0 export leftover",
        avoided="r177 Alloy relabel; leftover3 k8sattributes; r384 OTel forward; Opsgenie alias",
        knob=".attributes.drop",
        old="drop: [service.name]",
        new="drop: []",
        wrong_knob=".export.endpoint",
        wrong_old="endpoint: https://sandbox.dash0.com",
        wrong_new="endpoint: https://api.dash0.com",
        wrong2_old="protocol: http",
        wrong2_new="protocol: grpc",
        prefix="dash0",
    ),
    dict(
        vendor="KloudMate",
        ok_slug="kloudmate-source-remap-wrong-dash-leftover",
        bad_slug="kmate-src-raise-retention-not-remap",
        noun="strutcharge",
        panel="KloudMate sources",
        needle="strut_low",
        lie_core="source leftover remaps mro-strutcharge-svc into demo so Grafana is the wrong dashboard",
        false_lead="KloudMate retention leftover",
        avoided="r502 Honeycomb dataset alias; r500 DD pipeline remap; PagerDuty orch",
        knob=".sources.remap",
        old="remap: demo",
        new="remap: mro-strutcharge-svc",
        wrong_knob=".retention.days",
        wrong_old="days: 1",
        wrong_new="days: 30",
        wrong2_old="region: us",
        wrong2_new="region: eu",
        prefix="kloudmate",
    ),
    dict(
        vendor="SignalFx",
        ok_slug="signalfx-metric-exclude-drop-leftover",
        bad_slug="sfx-excl-raise-resolution-not-exclude",
        noun="n2cart",
        panel="SignalFx metrics",
        needle="n2_low",
        lie_core="metric exclude leftover drops job:mro-n2cart-svc so Grafana is empty while ingest still 200",
        false_lead="SignalFx resolution leftover",
        avoided="r387 chrono drop metric; leftover3 VM relabel; r394 Dynatrace mgmt zone",
        knob=".sfx.metric_excludes",
        old="metric_excludes: [job:mro-n2cart-svc]",
        new="metric_excludes: []",
        wrong_knob=".sfx.resolution",
        wrong_old="resolution: 300s",
        wrong_new="resolution: 10s",
        wrong2_old="token: ingest",
        wrong2_new="token: org",
        prefix="signalfx",
    ),
    dict(
        vendor="Wavefront",
        ok_slug="wavefront-point-tag-drop-leftover",
        bad_slug="wfront-tag-raise-pps-not-drop",
        noun="tireinflate",
        panel="Wavefront points",
        needle="tire_flat",
        lie_core="point tag leftover drops service so Grafana ts() is the wrong dashboard",
        false_lead="Wavefront PPS leftover",
        avoided="r177 Alloy relabel; SignalFx exclude plant; leftover3 VM relabel; Opsgenie alias",
        knob=".proxy.dropTags",
        old="dropTags: [service]",
        new="dropTags: []",
        wrong_knob=".proxy.preprocessor.rate",
        wrong_old="rate: 1",
        wrong_new="rate: 100000",
        wrong2_old="pushFlushMaxPoints: 1",
        wrong2_new="pushFlushMaxPoints: 40000",
        prefix="wavefront",
    ),
    dict(
        vendor="AppOptics",
        ok_slug="appoptics-metric-alias-wrong-dash-leftover",
        bad_slug="aopt-alias-raise-period-not-alias",
        noun="wheelbal",
        panel="AppOptics metrics",
        needle="balance_off",
        lie_core="metric alias leftover remaps mro-wheelbal-svc into sandbox.cpu so Grafana is the wrong dashboard",
        false_lead="AppOptics period leftover",
        avoided="r502 Honeycomb dataset alias; SignalFx exclude; leftover3 VM relabel",
        knob=".metrics.alias",
        old="alias: sandbox.cpu",
        new="alias: mro-wheelbal-svc",
        wrong_knob=".agent.period",
        wrong_old="period: 300",
        wrong_new="period: 10",
        wrong2_old="prefix: sandbox",
        wrong2_new="prefix: hangar",
        prefix="appoptics",
    ),
    dict(
        vendor="Checkly",
        ok_slug="checkly-check-tag-drop-leftover",
        bad_slug="checkly-tag-raise-freq-not-drop",
        noun="carbonlathe",
        panel="Checkly checks",
        needle="lathe_web",
        lie_core="check tag leftover drops service so Grafana is the wrong dashboard while checks still 200",
        false_lead="Checkly frequency leftover",
        avoided="r158 Grafana SM allowlist ban; k6 cloud later; PagerDuty orch; Opsgenie alias",
        knob=".checks.tags.drop",
        old="drop: [service]",
        new="drop: []",
        wrong_knob=".checks.frequency",
        wrong_old="frequency: 60",
        wrong_new="frequency: 1",
        wrong2_old="locations: [us-east-1]",
        wrong2_new="locations: [eu-west-1, us-east-1]",
        prefix="checkly",
    ),
    dict(
        vendor="Pingdom",
        ok_slug="pingdom-check-tag-filter-leftover",
        bad_slug="pingdom-tag-raise-reso-not-filter",
        noun="heatpack",
        panel="Pingdom checks",
        needle="pack_down",
        lie_core="check tag leftover include=legacy so Grafana is the wrong dashboard",
        false_lead="Pingdom resolution leftover",
        avoided="Checkly tag plant; Grafana SM allowlist ban; PagerDuty orch; Opsgenie alias",
        knob=".checks.tags.include",
        old="include: [legacy]",
        new="include: [mro-heatpack-svc]",
        wrong_knob=".checks.resolution",
        wrong_old="resolution: 30",
        wrong_new="resolution: 1",
        wrong2_old="paused: true",
        wrong2_new="paused: false",
        prefix="pingdom",
    ),
    dict(
        vendor="StatusCake",
        ok_slug="statuscake-group-remap-wrong-dash-leftover",
        bad_slug="scake-grp-raise-contact-not-group",
        noun="uldrepair",
        panel="StatusCake tests",
        needle="uld_web",
        lie_core="group leftover remaps mro-uldrepair-svc into sandbox-group so Grafana is the wrong dashboard",
        false_lead="StatusCake contact leftover",
        avoided="Pingdom tag plant; Checkly tag plant; PagerDuty orch; Opsgenie alias",
        knob=".tests.group",
        old="group: sandbox-group",
        new="group: mro-uldrepair-svc",
        wrong_knob=".contacts.email",
        wrong_old="email: none",
        wrong_new="email: mro@hangar.local",
        wrong2_old="paused: 1",
        wrong2_new="paused: 0",
        prefix="statuscake",
    ),
    dict(
        vendor="UptimeRobot",
        ok_slug="uptimerobot-type-filter-drop-leftover",
        bad_slug="urobot-type-raise-int-not-filter",
        noun="palletjig",
        panel="UptimeRobot monitors",
        needle="jig_http",
        lie_core="monitor type leftover keyword-only silently drops HTTP so Grafana is empty",
        false_lead="UptimeRobot interval leftover",
        avoided="StatusCake group plant; Pingdom tag; PagerDuty orch; Opsgenie alias; r515 Rootly",
        knob=".monitors.type_filter",
        old="type_filter: keyword",
        new="type_filter: http,keyword,ping",
        wrong_knob=".monitors.interval",
        wrong_old="interval: 300",
        wrong_new="interval: 60",
        wrong2_old="alert_contacts: []",
        wrong2_new="alert_contacts: [mro]",
        prefix="uptimerobot",
    ),
    dict(
        vendor="Catchpoint",
        ok_slug="catchpoint-node-filter-drop-leftover",
        bad_slug="cpoint-node-raise-freq-not-filter",
        noun="iglooshop",
        panel="Catchpoint nodes",
        needle="igloo_rtt",
        lie_core="node filter leftover include=lab-only so Grafana prod nodes are empty",
        false_lead="Catchpoint frequency leftover",
        avoided="ThousandEyes later; Grafana SM allowlist ban; PagerDuty orch; Opsgenie alias",
        knob=".nodes.include",
        old="include: [lab]",
        new="include: [lab, prod]",
        wrong_knob=".tests.frequency",
        wrong_old="frequency: 60",
        wrong_new="frequency: 5",
        wrong2_old="product: internet",
        wrong2_new="product: web",
        prefix="catchpoint",
    ),
    dict(
        vendor="ThousandEyes",
        ok_slug="thousandeyes-agent-label-drop-leftover",
        bad_slug="teyes-agent-raise-interval-not-label",
        noun="firebottle",
        panel="ThousandEyes agents",
        needle="bottle_rtt",
        lie_core="agent label leftover drops service so Grafana is the wrong dashboard",
        false_lead="ThousandEyes interval leftover",
        avoided="Catchpoint node plant; Grafana SM allowlist ban; r177 Alloy relabel",
        knob=".agents.labels.drop",
        old="drop: [service]",
        new="drop: []",
        wrong_knob=".tests.interval",
        wrong_old="interval: 120",
        wrong_new="interval: 15",
        wrong2_old="agents: [enterprise-lab]",
        wrong2_new="agents: [enterprise-lab, cloud]",
        prefix="thousandeyes",
    ),
    dict(
        vendor="SpeedCurve",
        ok_slug="speedcurve-beacon-filter-drop-leftover",
        bad_slug="scurve-bcn-raise-budget-not-filter",
        noun="hydrotest",
        panel="SpeedCurve beacons",
        needle="hydro_lcp",
        lie_core="beacon filter leftover site=staging so Grafana is empty while RUM still 204",
        false_lead="SpeedCurve budget leftover",
        avoided="r168 Faro session; Checkly tag plant; PagerDuty orch; Opsgenie alias",
        knob=".beacons.site",
        old="site: staging",
        new="site: production",
        wrong_knob=".budgets.lcp_ms",
        wrong_old="lcp_ms: 10000",
        wrong_new="lcp_ms: 2500",
        wrong2_old="synthetic: off",
        wrong2_new="synthetic: on",
        prefix="speedcurve",
    ),
    dict(
        vendor="Calibre",
        ok_slug="calibre-profile-remap-wrong-dash-leftover",
        bad_slug="calibre-prof-raise-assert-not-remap",
        noun="vestshop",
        panel="Calibre profiles",
        needle="vest_lcp",
        lie_core="profile leftover remaps mro-vestshop-svc into sandbox-profile so Grafana is the wrong dashboard",
        false_lead="Calibre assertion leftover",
        avoided="SpeedCurve beacon plant; Grafana SM allowlist ban; PagerDuty orch",
        knob=".profiles.remap",
        old="remap: sandbox-profile",
        new="remap: mro-vestshop-svc",
        wrong_knob=".assertions.lcp",
        wrong_old="lcp: 20000",
        wrong_new="lcp: 2500",
        wrong2_old="device: nexus",
        wrong2_new="device: mote4g",
        prefix="calibre",
    ),
    dict(
        vendor="sitespeed.io",
        ok_slug="sitespeed-budget-filter-drop-leftover",
        bad_slug="sspeed-budg-raise-iter-not-filter",
        noun="maskshop",
        panel="sitespeed budgets",
        needle="mask_tbt",
        lie_core="budget leftover skip mro-maskshop-svc so Grafana is empty while the run still 0",
        false_lead="sitespeed iterations leftover",
        avoided="Calibre profile plant; SpeedCurve beacon; Grafana SM allowlist ban",
        knob=".budget.skip",
        old="skip: [mro-maskshop-svc]",
        new="skip: []",
        wrong_knob=".browsertime.iterations",
        wrong_old="iterations: 1",
        wrong_new="iterations: 5",
        wrong2_old="connectivity: native",
        wrong2_new="connectivity: 4g",
        prefix="sitespeed",
    ),
    dict(
        vendor="k6 Cloud",
        ok_slug="k6cloud-test-remap-wrong-dash-leftover",
        bad_slug="k6cloud-test-raise-vus-not-remap",
        noun="megashop",
        panel="k6 Cloud tests",
        needle="mega_http",
        lie_core="test leftover remaps mro-megashop-svc into sandbox-test so Grafana is the wrong dashboard",
        false_lead="k6 Cloud VUs leftover",
        avoided="r k6 prefix clones; Grafana SM allowlist ban; PagerDuty orch; Opsgenie alias",
        knob=".tests.remap",
        old="remap: sandbox-test",
        new="remap: mro-megashop-svc",
        wrong_knob=".cloud.vus",
        wrong_old="vus: 1",
        wrong_new="vus: 50",
        wrong2_old="project_id: 0",
        wrong2_new="project_id: 8842",
        prefix="k6cloud",
    ),
    dict(
        vendor="Grafana Agent",
        ok_slug="grafagent-positions-stale-drop-leftover",
        bad_slug="gagent-pos-raise-wal-not-positions",
        noun="axeshop",
        panel="Grafana Agent logs",
        needle="axe_miss",
        lie_core="positions leftover file points past EOF so Grafana is empty while the log still grows",
        false_lead="Grafana Agent WAL leftover",
        avoided="r177 Alloy relabel; r398 fluentbit mem-buf; r496 Grafana dataproxy timeout",
        knob=".logs.positions.ignore_invalid",
        old="ignore_invalid: true",
        new="ignore_invalid: false",
        wrong_knob=".wal.truncate_frequency",
        wrong_old="truncate_frequency: 24h",
        wrong_new="truncate_frequency: 1h",
        wrong2_old="positions_directory: /tmp",
        wrong2_new="positions_directory: /var/lib/agent",
        prefix="grafagent",
    ),
    dict(
        vendor="prometheus-adapter",
        ok_slug="promadapter-rule-drop-metric-leftover",
        bad_slug="padapter-rule-raise-res-not-drop",
        noun="aidshop",
        panel="custom metrics",
        needle="aid_hpa",
        lie_core="adapter rule leftover seriesQuery never-matches mro-aidshop-svc so Grafana HPA panel is empty",
        false_lead="prometheus-adapter resources leftover",
        avoided="r504 Prom honor_labels; leftover3 VM relabel; PagerDuty orch; Opsgenie alias",
        knob=".rules[].seriesQuery",
        old='seriesQuery: {job="none"}',
        new='seriesQuery: {job="mro-aidshop-svc"}',
        wrong_knob=".resources.overrides",
        wrong_old="overrides: {}",
        wrong_new="overrides: {service: {group: core}}",
        wrong2_old="metricsRelistInterval: 24h",
        wrong2_new="metricsRelistInterval: 1m",
        prefix="promadapter",
    ),
    dict(
        vendor="cAdvisor",
        ok_slug="cadvisor-docker-only-drop-leftover",
        bad_slug="cadvisor-dkr-raise-housekeep-not-docker",
        noun="aedshop",
        panel="cAdvisor containers",
        needle="aed_cpu",
        lie_core="docker_only leftover true drops containerd pods so Grafana is empty while crictl still has mro-aedshop-svc",
        false_lead="cAdvisor housekeeping leftover",
        avoided="r504 Prom honor_labels; leftover3 Beyla; leftover3 eBPF map; r177 Alloy relabel",
        knob=".cadvisor.docker_only",
        old="docker_only: true",
        new="docker_only: false",
        wrong_knob=".housekeeping_interval",
        wrong_old="housekeeping_interval: 5m",
        wrong_new="housekeeping_interval: 10s",
        wrong2_old="store_container_labels: false",
        wrong2_new="store_container_labels: true",
        prefix="cadvisor",
    ),
    dict(
        vendor="node_exporter",
        ok_slug="nodeexp-collector-disable-leftover",
        bad_slug="nodeexp-col-raise-web-not-collector",
        noun="pbeshop",
        panel="node exporter",
        needle="pbe_cpu",
        lie_core="collector leftover --no-collector.netdev so Grafana net panel is empty while /metrics still 200",
        false_lead="node_exporter web leftover",
        avoided="r504 Prom honor_labels; cAdvisor docker_only plant; leftover3 VM relabel",
        knob=".collectors.netdev",
        old="netdev: false",
        new="netdev: true",
        wrong_knob=".web.listen-address",
        wrong_old="listen-address: 127.0.0.1:9100",
        wrong_new="listen-address: 0.0.0.0:9100",
        wrong2_old="telemetry.path: /debug",
        wrong2_new="telemetry.path: /metrics",
        prefix="nodeexp",
    ),
    dict(
        vendor="blackbox_exporter",
        ok_slug="blackbox-module-timeout-drop-leftover",
        bad_slug="bbox-mod-raise-probe-not-timeout",
        noun="torchshop",
        panel="blackbox probes",
        needle="torch_http",
        lie_core="module leftover timeout:1ms so Grafana probe_success is empty while curl still 200",
        false_lead="blackbox probe leftover",
        avoided="Grafana SM allowlist ban; Pingdom tag plant; r370 Prom query.timeout; r496 dataproxy",
        knob=".modules.http_2xx.timeout",
        old="timeout: 1ms",
        new="timeout: 10s",
        wrong_knob=".modules.http_2xx.prober",
        wrong_old="prober: tcp",
        wrong_new="prober: http",
        wrong2_old="valid_status_codes: [500]",
        wrong2_new="valid_status_codes: [200]",
        prefix="blackbox",
    ),
    dict(
        vendor="snmp_exporter",
        ok_slug="snmpexp-module-drop-oid-leftover",
        bad_slug="snmp-mod-raise-walk-not-oid",
        noun="calab",
        panel="SNMP OIDs",
        needle="lab_if",
        lie_core="generator leftover walk drops ifDescr so Grafana is empty while snmpwalk still has mro-calab-svc",
        false_lead="snmp_exporter walk leftover",
        avoided="blackbox module plant; r504 Prom honor_labels; leftover3 VM relabel",
        knob=".modules.if_mib.overrides.ifDescr",
        old="ifDescr: drop",
        new="ifDescr: keep",
        wrong_knob=".modules.if_mib.walk",
        wrong_old="walk: []",
        wrong_new="walk: [1.3.6.1.2.1.2]",
        wrong2_old="auth.community: public",
        wrong2_new="auth.community: hangar",
        prefix="snmpexp",
    ),
    dict(
        vendor="process-exporter",
        ok_slug="processexp-namer-drop-leftover",
        bad_slug="pexporter-namer-raise-procfs-not-drop",
        noun="torqlab",
        panel="process exporter",
        needle="torq_cpu",
        lie_core="namer leftover cmdline drop mro-torqlab-svc so Grafana is empty while ps still shows the process",
        false_lead="process-exporter procfs leftover",
        avoided="node_exporter collector plant; r504 Prom honor_labels; leftover3 VM relabel",
        knob=".process_names[].cmdline",
        old="cmdline: [drop-mro-torqlab]",
        new="cmdline: [mro-torqlab-svc]",
        wrong_knob=".procfs.path",
        wrong_old="path: /tmp/proc",
        wrong_new="path: /proc",
        wrong2_old="children: false",
        wrong2_new="children: true",
        prefix="processexp",
    ),
    dict(
        vendor="DCGM",
        ok_slug="dcgm-field-group-drop-leftover",
        bad_slug="dcgm-fg-raise-interval-not-drop",
        noun="presslab",
        panel="DCGM fields",
        needle="gpu_xid",
        lie_core="field group leftover drops DCGM_FI_DEV_XID_ERRORS so Grafana is empty while nvidia-smi still 200",
        false_lead="DCGM interval leftover",
        avoided="node_exporter collector; leftover3 eBPF map; PagerDuty orch; Opsgenie alias",
        knob=".fieldGroups.drop",
        old="drop: [DCGM_FI_DEV_XID_ERRORS]",
        new="drop: []",
        wrong_knob=".collectInterval",
        wrong_old="collectInterval: 300000",
        wrong_new="collectInterval: 10000",
        wrong2_old="kubernetes: false",
        wrong2_new="kubernetes: true",
        prefix="dcgm",
    ),
    dict(
        vendor="kubernetes-event-exporter",
        ok_slug="kubeevents-drop-reason-leftover",
        bad_slug="kevents-drop-raise-sink-not-reason",
        noun="templab",
        panel="k8s events",
        needle="temp_backoff",
        lie_core="drop leftover reason=CrashLoopBackOff so Grafana is empty while kubectl events still has mro-templab-svc",
        false_lead="event-exporter sink leftover",
        avoided="leftover3 Falco priority; r505 AM continue; PagerDuty orch; Opsgenie alias",
        knob=".route.drop.reason",
        old="reason: [CrashLoopBackOff]",
        new="reason: []",
        wrong_knob=".receivers.sink",
        wrong_old="sink: /dev/null",
        wrong_new="sink: stdout",
        wrong2_old="maxEventAgeSeconds: 1",
        wrong2_new="maxEventAgeSeconds: 3600",
        prefix="kubeevents",
    ),
    dict(
        vendor="Pushgateway",
        ok_slug="pushgw-grouping-drop-job-leftover",
        bad_slug="pushgw-grp-raise-persist-not-job",
        noun="eleclab",
        panel="Pushgateway jobs",
        needle="elec_push",
        lie_core="grouping leftover drops job so Grafana is the wrong dashboard while POST /metrics still 200",
        false_lead="Pushgateway persistence leftover",
        avoided="r504 Prom honor_labels; leftover3 VM relabel; r177 Alloy relabel",
        knob=".push.grouping.drop",
        old="drop: [job]",
        new="drop: []",
        wrong_knob=".persistence.file",
        wrong_old="file: /tmp/empty",
        wrong_new="file: /data/pushgw",
        wrong2_old="web.enable-admin-api: false",
        wrong2_new="web.enable-admin-api: true",
        prefix="pushgw",
    ),
    dict(
        vendor="Consul",
        ok_slug="consul-telemetry-prefix-drop-leftover",
        bad_slug="consul-tel-raise-retain-not-prefix",
        noun="avilab",
        panel="Consul telemetry",
        needle="avi_serf",
        lie_core="telemetry leftover filter_default=false plus prefix drop consul. so Grafana is empty",
        false_lead="Consul retain leftover",
        avoided="r504 Prom honor_labels; leftover3 VM relabel; PagerDuty orch; Opsgenie alias",
        knob=".telemetry.prefix_filter",
        old="prefix_filter: [-consul.]",
        new="prefix_filter: [+consul.]",
        wrong_knob=".telemetry.metrics_retention",
        wrong_old="metrics_retention: 1s",
        wrong_new="metrics_retention: 1h",
        wrong2_old="disable_hostname: true",
        wrong2_new="disable_hostname: false",
        prefix="consul",
    ),
    dict(
        vendor="Nomad",
        ok_slug="nomad-telemetry-publish-drop-leftover",
        bad_slug="nomad-tel-raise-interval-not-publish",
        noun="swload",
        panel="Nomad telemetry",
        needle="sw_alloc",
        lie_core="telemetry leftover publish_allocation_metrics=false so Grafana is empty while nomad alloc still running",
        false_lead="Nomad collection interval leftover",
        avoided="Consul telemetry plant; r504 Prom honor_labels; leftover3 VM relabel",
        knob=".telemetry.publish_allocation_metrics",
        old="publish_allocation_metrics: false",
        new="publish_allocation_metrics: true",
        wrong_knob=".telemetry.collection_interval",
        wrong_old="collection_interval: 5m",
        wrong_new="collection_interval: 10s",
        wrong2_old="disable_hostname: true",
        wrong2_new="disable_hostname: false",
        prefix="nomad",
    ),
    dict(
        vendor="Vault",
        ok_slug="vault-audit-filter-drop-leftover",
        bad_slug="vault-audit-raise-log-not-filter",
        noun="pinprog",
        panel="Vault audit",
        needle="pin_deny",
        lie_core="audit leftover filter drop request.path=/v1/ so Grafana is empty while vault audit still 200",
        false_lead="Vault log leftover",
        avoided="leftover3 Falco priority; kubeevents drop plant; PagerDuty orch; Opsgenie alias",
        knob=".audit.file.filter",
        old="filter: drop request.path=/v1/",
        new="filter: none",
        wrong_knob=".log_level",
        wrong_old="log_level: err",
        wrong_new="log_level: info",
        wrong2_old="log_format: standard",
        wrong2_new="log_format: json",
        prefix="vault",
    ),
    dict(
        vendor="Linkerd",
        ok_slug="linkerd-tap-disable-drop-leftover",
        bad_slug="linkerd-tap-raise-proxy-not-tap",
        noun="magload",
        panel="Linkerd tap",
        needle="mag_rst",
        lie_core="tap leftover disabled so Grafana tap panel is empty while the proxy still 200",
        false_lead="Linkerd proxy leftover",
        avoided="leftover3 Istio/Hubble clones; r384 OTel forward; leftover3 Beyla exclude",
        knob=".tap.disabled",
        old="disabled: true",
        new="disabled: false",
        wrong_knob=".proxy.inbound.connectTimeout",
        wrong_old="connectTimeout: 1ms",
        wrong_new="connectTimeout: 1s",
        wrong2_old="opaquePorts: [*]",
        wrong2_new="opaquePorts: [25,443]",
        prefix="linkerd",
    ),
    dict(
        vendor="Wazuh",
        ok_slug="wazuh-rule-level-drop-leftover",
        bad_slug="wazuh-rule-raise-email-not-level",
        noun="usbload",
        panel="Wazuh alerts",
        needle="usb_deny",
        lie_core="rule leftover level=16 so Grafana is empty while ossec still logged mro-usbload-svc",
        false_lead="Wazuh email leftover",
        avoided="leftover3 Falco priority; kubeevents drop; PagerDuty orch; Opsgenie alias; r515 Rootly",
        knob=".rules.level_filter",
        old="level_filter: 16",
        new="level_filter: 3",
        wrong_knob=".global.email_notification",
        wrong_old="email_notification: no",
        wrong_new="email_notification: yes",
        wrong2_old="logall: no",
        wrong2_new="logall: yes",
        prefix="wazuh",
    ),
    dict(
        vendor="osquery",
        ok_slug="osquery-pack-disable-drop-leftover",
        bad_slug="osquery-pack-raise-interval-not-enable",
        noun="pmdt",
        panel="osquery packs",
        needle="pmdt_proc",
        lie_core="pack leftover discovery_zero plus disabled=true so Grafana is empty while osqueryi still returns rows",
        false_lead="osquery interval leftover",
        avoided="leftover3 Falco priority; Wazuh rule plant; PagerDuty orch; Opsgenie alias",
        knob=".packs.hangar.disabled",
        old="disabled: true",
        new="disabled: false",
        wrong_knob=".schedule.interval",
        wrong_old="interval: 86400",
        wrong_new="interval: 60",
        wrong2_old="logger_plugin: filesystem",
        wrong2_new="logger_plugin: tls",
        prefix="osquery",
    ),
    dict(
        vendor="Sysdig",
        ok_slug="sysdig-falco-filter-drop-leftover",
        bad_slug="sysdig-filt-raise-priority-not-filter",
        noun="ammview",
        panel="Sysdig events",
        needle="amm_exec",
        lie_core="Sysdig leftover filter not container.image contains hangar so Grafana is empty while Falco still 202",
        false_lead="Sysdig priority leftover",
        avoided="leftover3 Falco priority emergency; leftover3 eBPF map; PagerDuty orch; Opsgenie alias",
        knob=".falco.filter",
        old='filter: container.image contains "sandbox"',
        new='filter: container.image contains "hangar"',
        wrong_knob=".falco.priority",
        wrong_old="priority: EMERGENCY",
        wrong_new="priority: WARNING",
        wrong2_old="output: none",
        wrong2_new="output: syslog",
        prefix="sysdig",
    ),
    dict(
        vendor="Aqua",
        ok_slug="aqua-runtime-event-drop-leftover",
        bad_slug="aqua-evt-raise-scan-not-drop",
        noun="ipcview",
        panel="Aqua runtime",
        needle="ipc_exec",
        lie_core="runtime leftover event_drop mro-ipcview-svc so Grafana is empty while the enforcer still 202",
        false_lead="Aqua scan leftover",
        avoided="Sysdig filter plant; leftover3 Falco; PagerDuty orch; Opsgenie alias; r515 Rootly",
        knob=".runtime.event_drop",
        old="event_drop: [mro-ipcview-svc]",
        new="event_drop: []",
        wrong_knob=".scanner.interval",
        wrong_old="interval: 24h",
        wrong_new="interval: 1h",
        wrong2_old="enforce: off",
        wrong2_new="enforce: on",
        prefix="aqua",
    ),
    dict(
        vendor="Observe Inc",
        ok_slug="observeinc-dataset-token-remap-leftover",
        bad_slug="observe-tok-raise-ingest-not-remap",
        noun="taskcard",
        panel="Observe datasets",
        needle="card_drop",
        lie_core="dataset token leftover remaps mro-taskcard-svc into demo so Grafana is the wrong dashboard",
        false_lead="Observe ingest leftover",
        avoided="r502 Honeycomb dataset alias; Axiom dataset plant; r500 DD pipeline remap",
        knob=".datasets.token_map",
        old="token_map: demo",
        new="token_map: mro-taskcard-svc",
        wrong_knob=".ingest.max_gb",
        wrong_old="max_gb: 1",
        wrong_new="max_gb: 50",
        wrong2_old="customer: sandbox",
        wrong2_new="customer: hangar",
        prefix="observeinc",
    ),
    dict(
        vendor="Baselime",
        ok_slug="baselime-query-alias-wrong-dash-leftover",
        bad_slug="baselime-alias-raise-retain-not-query",
        noun="jobprint",
        panel="Baselime queries",
        needle="print_jam",
        lie_core="query alias leftover remaps mro-jobprint-svc into sandbox so Grafana is the wrong dashboard",
        false_lead="Baselime retain leftover",
        avoided="Axiom dataset plant; Honeycomb dataset alias; r511 Kibana pattern; Opsgenie alias",
        knob=".queries.alias",
        old="alias: sandbox",
        new="alias: mro-jobprint-svc",
        wrong_knob=".retain.days",
        wrong_old="days: 1",
        wrong_new="days: 30",
        wrong2_old="dataset: default",
        wrong2_new="dataset: hangar",
        prefix="baselime",
    ),
    dict(
        vendor="Logflare",
        ok_slug="logflare-source-drop-filter-leftover",
        bad_slug="lflare-src-raise-plan-not-drop",
        noun="toolcrib",
        panel="Logflare sources",
        needle="crib_deny",
        lie_core="source leftover drop_filter mro-toolcrib-svc so Grafana is empty while ingest still 201",
        false_lead="Logflare plan leftover",
        avoided="Better Stack source plant; Mezmo exclusion; r395 Splunk frozen; Opsgenie alias",
        knob=".sources.drop_filter",
        old="drop_filter: mro-toolcrib-svc",
        new="drop_filter: none",
        wrong_knob=".plan.max_rps",
        wrong_old="max_rps: 1",
        wrong_new="max_rps: 500",
        wrong2_old="backend: bigquery-dev",
        wrong2_new="backend: bigquery",
        prefix="logflare",
    ),
    dict(
        vendor="PostHog",
        ok_slug="posthog-project-filter-drop-leftover",
        bad_slug="phog-proj-raise-quota-not-filter",
        noun="caltool",
        panel="PostHog events",
        needle="cal_event",
        lie_core="project leftover filter drop mro-caltool-svc so Grafana is empty while /capture still 200",
        false_lead="PostHog quota leftover",
        avoided="r168 Faro session; Highlight session plant; PagerDuty orch; Opsgenie alias",
        knob=".projects.filter.drop",
        old="drop: mro-caltool-svc",
        new="drop: none",
        wrong_knob=".quota.events",
        wrong_old="events: 100",
        wrong_new="events: 1000000",
        wrong2_old="token: project-sandbox",
        wrong2_new="token: project-hangar",
        prefix="posthog",
    ),
    dict(
        vendor="FullStory",
        ok_slug="fullstory-org-remap-wrong-dash-leftover",
        bad_slug="fstory-org-raise-sample-not-remap",
        noun="quarcage",
        panel="FullStory sessions",
        needle="cage_fs",
        lie_core="org leftover remaps mro-quarcage-svc into sandbox-org so Grafana is the wrong dashboard",
        false_lead="FullStory sampling leftover",
        avoided="r168 Faro session; Highlight session; OpenReplay project; Opsgenie alias",
        knob=".org.remap",
        old="remap: sandbox-org",
        new="remap: mro-quarcage-svc",
        wrong_knob=".sampling.rate",
        wrong_old="rate: 0.01",
        wrong_new="rate: 1.0",
        wrong2_old="record: false",
        wrong2_new="record: true",
        prefix="fullstory",
    ),
    dict(
        vendor="LogRocket",
        ok_slug="logrocket-release-filter-drop-leftover",
        bad_slug="lrocket-rel-raise-ingest-not-filter",
        noun="bonded",
        panel="LogRocket sessions",
        needle="bond_lr",
        lie_core="release leftover filter=dev so Grafana is empty while ingest still 202",
        false_lead="LogRocket ingest leftover",
        avoided="r168 Faro session; FullStory org plant; Highlight session; PagerDuty orch",
        knob=".releases.filter",
        old="filter: dev",
        new="filter: production",
        wrong_knob=".ingest.max_sessions",
        wrong_old="max_sessions: 10",
        wrong_new="max_sessions: 10000",
        wrong2_old="appID: sandbox",
        wrong2_new="appID: hangar",
        prefix="logrocket",
    ),
    dict(
        vendor="Middle",
        ok_slug="middle-pipeline-drop-label-leftover",
        bad_slug="middle-pipe-raise-worker-not-label",
        noun="rotablerack",
        panel="Middle events",
        needle="rack_miss",
        lie_core="pipeline leftover drop_labels [service] so Grafana is the wrong dashboard",
        false_lead="Middle worker leftover",
        avoided="Cribl drop_fields plant; r177 Alloy relabel; r398 Vector drop; Opsgenie alias",
        knob=".pipelines.drop_labels",
        old="drop_labels: [service]",
        new="drop_labels: []",
        wrong_knob=".workers.replicas",
        wrong_old="replicas: 1",
        wrong_new="replicas: 6",
        wrong2_old="batch: 1",
        wrong2_new="batch: 500",
        prefix="middle",
    ),
]


assert len(SPECS) == 89, len(SPECS)
for i, spec in enumerate(SPECS):
    _l4(516 + i, **spec)
