"""Observability leftover15 plants r1348+.

BAN r1347 beamx-metrics-off-leftover, leftover14 prior mill, leftover12 lock-basin,
r875 tempo-ingester-max-traces-per-user-one, r384 otel-forward-connector,
PagerDuty orch, Opsgenie alias, Rootly urgency.
"""

from mill_plants_t import _leftover_pair

MORE = []
ROUND_PAIRS = {}


def _emit(round_n, **kwargs):
    dest = []
    _leftover_pair(n=str(round_n), dest=dest, **kwargs)
    MORE.extend(dest)
    ROUND_PAIRS[round_n] = dest[0]


def _l15(n, **kw):
    vendor, noun, prefix = kw["vendor"], kw["noun"], kw["prefix"]
    ok_svc, bad_svc = f"ford-{noun}-svc", f"creek-{noun}-svc"
    tag = noun.replace("-", "")[:8]
    vtag = prefix.replace("-", "")[:5]
    ok_dash, bad_dash = f"{tag}-{vtag}-{n}", f"f{tag[:7]}-{vtag}-fl"
    lie_core = kw["lie_core"]
    _emit(
        n,
        kind="grafana",
        ok_slug=kw["ok_slug"],
        bad_slug=kw["bad_slug"],
        ok_svc=ok_svc,
        bad_svc=bad_svc,
        ok_dash=ok_dash,
        bad_dash=bad_dash,
        panel=kw["panel"],
        metric="",
        needle=kw["needle"],
        lie=(
            f"{vendor} leftover leftover leftover leftover leftover leftover leftover leftover leftover leftover leftover leftover leftover leftover leftover {lie_core} "
            f"so Grafana dashboard {ok_dash} is empty while the source still 202"
        ),
        bad_lie=(
            f"{kw['false_lead']} does not restore leftover leftover leftover leftover leftover leftover leftover leftover leftover leftover leftover leftover leftover leftover leftover {lie_core}"
        ),
        false_lead=kw["false_lead"],
        avoided=kw["avoided"],
        this_is=f"{vendor} leftover leftover leftover leftover leftover leftover leftover leftover leftover leftover leftover leftover leftover leftover leftover {lie_core}",
        ticket=f"OBS-{ 9500 + (n - 1348) }",
        knob=kw["knob"],
        old=kw["old"],
        new=kw["new"],
        wrong_knob=kw["wrong_knob"],
        wrong_old=kw["wrong_old"],
        wrong_new=kw["wrong_new"],
        wrong2_old=kw["wrong2_old"],
        wrong2_new=kw["wrong2_new"],
        reload="grafana",
        config_path=f"{prefix}/{tag}-false.yaml",
        lie_path=f"{prefix}/{tag}-lie.yaml",
        bad_config=f"{prefix}/f{tag[:7]}-false.yaml",
        bad_lie_path=f"{prefix}/f{tag[:7]}-lie.yaml",
    )


BAN = (
    "r1347 apache-beam leftover14 canal/reach r1260-r1347; leftover13 dam/weir; r875 tempo; r384 otel-forward; PagerDuty orch; Opsgenie alias; r515 Rootly urgency"
)

SPECS = [
    dict(vendor='Apache Storm', ok_slug='stormx-nimbus-metrics-off-leftover', bad_slug='stormx-met-raise-zk-not-enable', noun='knick', panel='Storm metrics', needle='stormx_up', lie_core='metrics leftover topology.enable_metrics=false so Grafana is empty while topologies still ACTIVE', false_lead='Storm zk leftover', avoided=BAN, knob='.topology.enable_metrics', old='enable_metrics: false', new='enable_metrics: true', wrong_knob='.storm.zookeeper.servers', wrong_old='servers: [sandbox]', wrong_new='servers: [hangar]', wrong2_old='nimbus.host: sandbox', wrong2_new='nimbus.host: hangar', prefix='stormx'),
    dict(vendor='Samza', ok_slug='samza-reporters-drop-leftover', bad_slug='samza-rep-raise-zk-not-reporter', noun='hangingv', panel='Samza metrics', needle='samza_up', lie_core='reporter leftover metrics.reporters empty so Grafana is empty while jobs still RUNNING', false_lead='Samza zk leftover', avoided=BAN, knob='.metrics.reporters', old='reporters: ', new='reporters: snapshot', wrong_knob='.job.coordinator.system', wrong_old='system: sandbox', wrong_new='system: hangar', wrong2_old='job.name: sandbox', wrong2_new='job.name: hangar', prefix='samza'),
    dict(vendor='Heron', ok_slug='heronx-metricsmgr-off-leftover', bad_slug='heronx-mgr-raise-zk-not-enable', noun='cirque', panel='Heron metrics', needle='heronx_up', lie_core='metrics leftover heron.metricsmgr=false so Grafana is empty while topologies still RUNNING', false_lead='Heron zk leftover', avoided=BAN, knob='.heron.metricsmgr', old='metricsmgr: false', new='metricsmgr: true', wrong_knob='.heron.statemgr.connection.string', wrong_old='string: sandbox', wrong_new='string: hangar', wrong2_old='heron.topology.name: sandbox', wrong2_new='heron.topology.name: hangar', prefix='heronx'),
    dict(vendor='Solr', ok_slug='solr-metrics-off-leftover', bad_slug='solr-met-raise-zk-not-enable', noun='tarn', panel='Solr metrics', needle='solr_up', lie_core='metrics leftover metricsEnabled=false so Grafana is empty while collections still active', false_lead='Solr zk leftover', avoided=BAN, knob='.metricsEnabled', old='metricsEnabled: false', new='metricsEnabled: true', wrong_knob='.zkHost', wrong_old='zkHost: sandbox:2181', wrong_new='zkHost: hangar:2181', wrong2_old='solr.host: 127.0.0.1', wrong2_new='solr.host: 0.0.0.0', prefix='solr'),
    dict(vendor='OpenSearch', ok_slug='osrch-http-bind-drop-leftover', bad_slug='osrch-bind-raise-cluster-not-addr', noun='paternost', panel='OpenSearch metrics', needle='osrch_up', lie_core='http leftover network.host 127.0.0.1 so Grafana is empty while search still 9200', false_lead='OpenSearch cluster leftover', avoided=BAN, knob='.network.host', old='network.host: 127.0.0.1', new='network.host: 0.0.0.0', wrong_knob='.cluster.name', wrong_old='name: sandbox', wrong_new='name: hangar', wrong2_old='path.data: /tmp', wrong2_new='path.data: /var/lib/opensearch', prefix='osrch'),
    dict(vendor='Typesense', ok_slug='tsense-metrics-off-leftover', bad_slug='tsense-met-raise-api-not-enable', noun='fjord', panel='Typesense metrics', needle='tsense_up', lie_core='metrics leftover enable-cors plus metrics off so Grafana is empty while search still 8108', false_lead='Typesense api leftover', avoided=BAN, knob='.enable-metrics', old='enable-metrics: false', new='enable-metrics: true', wrong_knob='.api-address', wrong_old='api-address: 127.0.0.1', wrong_new='api-address: 0.0.0.0', wrong2_old='data-dir: /tmp', wrong2_new='data-dir: /var/lib/typesense', prefix='tsense'),
    dict(vendor='Meilisearch', ok_slug='meili-http-addr-drop-leftover', bad_slug='meili-addr-raise-env-not-addr', noun='ria', panel='Meilisearch metrics', needle='meili_up', lie_core='http leftover MEILI_HTTP_ADDR 127.0.0.1 so Grafana is empty while search still 7700', false_lead='Meilisearch env leftover', avoided=BAN, knob='.MEILI_HTTP_ADDR', old='MEILI_HTTP_ADDR: 127.0.0.1:7700', new='MEILI_HTTP_ADDR: 0.0.0.0:7700', wrong_knob='.MEILI_ENV', wrong_old='MEILI_ENV: sandbox', wrong_new='MEILI_ENV: production', wrong2_old='MEILI_DB_PATH: /tmp', wrong2_new='MEILI_DB_PATH: /var/lib/meili', prefix='meili'),
    dict(vendor='Vespa', ok_slug='vespa-metrics-proxy-off-leftover', bad_slug='vespa-prox-raise-cfg-not-enable', noun='estuary', panel='Vespa metrics', needle='vespa_up', lie_core='proxy leftover metrics-proxy disabled so Grafana is empty while query still 8080', false_lead='Vespa config leftover', avoided=BAN, knob='.metrics-proxy.enabled', old='enabled: false', new='enabled: true', wrong_knob='.configserver.host', wrong_old='host: sandbox', wrong_new='host: hangar', wrong2_old='vespa.config.id: sandbox', wrong2_new='vespa.config.id: hangar', prefix='vespa'),
    dict(vendor='ActiveMQ', ok_slug='amq-jmx-off-leftover', bad_slug='amq-jmx-raise-broker-not-enable', noun='lagoon', panel='ActiveMQ JMX', needle='amq_up', lie_core='jmx leftover useJmx=false so Grafana is empty while OpenWire still 61616', false_lead='ActiveMQ broker leftover', avoided=BAN, knob='.useJmx', old='useJmx: false', new='useJmx: true', wrong_knob='.brokerName', wrong_old='brokerName: sandbox', wrong_new='brokerName: hangar', wrong2_old='dataDirectory: /tmp', wrong2_new='dataDirectory: /var/lib/activemq', prefix='amq'),
    dict(vendor='IBM MQ', ok_slug='ibmmq-prom-off-leftover', bad_slug='ibmmq-prom-raise-qmgr-not-enable', noun='soundw', panel='IBM MQ metrics', needle='ibmmq_up', lie_core='prometheus leftover mq_prometheus disabled so Grafana is empty while queues still open', false_lead='IBM MQ qmgr leftover', avoided=BAN, knob='.mq_prometheus', old='mq_prometheus: false', new='mq_prometheus: true', wrong_knob='.QMGR', wrong_old='QMGR: SANDBOX', wrong_new='QMGR: HANGAR', wrong2_old='MQ_ADMIN_PASSWORD: sandbox', wrong2_new='MQ_ADMIN_PASSWORD: hangar', prefix='ibmmq'),
    dict(vendor='ZeroMQ', ok_slug='zmq-monitor-off-leftover', bad_slug='zmq-mon-raise-bind-not-enable', noun='strait', panel='ZeroMQ', needle='zmq_up', lie_core='monitor leftover ZMQ_EVENT_MONITOR off so Grafana is empty while sockets still bind', false_lead='ZeroMQ bind leftover', avoided=BAN, knob='.ZMQ_MONITOR', old='ZMQ_MONITOR: false', new='ZMQ_MONITOR: true', wrong_knob='.bind', wrong_old='bind: ipc:///tmp/empty', wrong_new='bind: tcp://0.0.0.0:5555', wrong2_old='identity: sandbox', wrong2_new='identity: hangar', prefix='zmq'),
    dict(vendor='Kafka Connect', ok_slug='kconn-jmx-port-drop-leftover', bad_slug='kconn-jmx-raise-grp-not-port', noun='channel2', panel='Connect metrics', needle='kconn_up', lie_core='jmx leftover KAFKA_JMX_PORT 0 so Grafana is empty while connectors still RUNNING', false_lead='Kafka Connect group leftover', avoided=BAN, knob='.KAFKA_JMX_PORT', old='KAFKA_JMX_PORT: 0', new='KAFKA_JMX_PORT: 9101', wrong_knob='.group.id', wrong_old='group.id: sandbox', wrong_new='group.id: hangar', wrong2_old='bootstrap.servers: sandbox:9092', wrong2_new='bootstrap.servers: hangar:9092', prefix='kconn'),
    dict(vendor='Schema Registry', ok_slug='schemar-listeners-drop-leftover', bad_slug='schemar-list-raise-kaf-not-addr', noun='pass2', panel='Schema Registry', needle='schemar_up', lie_core='listeners leftover http://127.0.0.1 so Grafana is empty while schemas still 8081', false_lead='Schema Registry kafka leftover', avoided=BAN, knob='.listeners', old='listeners: http://127.0.0.1:8081', new='listeners: http://0.0.0.0:8081', wrong_knob='.kafkastore.bootstrap.servers', wrong_old='bootstrap.servers: sandbox:9092', wrong_new='bootstrap.servers: hangar:9092', wrong2_old='schema.registry.group.id: sandbox', wrong2_new='schema.registry.group.id: hangar', prefix='schemar'),
    dict(vendor='ksqlDB', ok_slug='ksqldb-metrics-off-leftover', bad_slug='ksqldb-met-raise-ks-not-enable', noun='inlet', panel='ksqlDB metrics', needle='ksqldb_up', lie_core='metrics leftover ksql.metrics.tags empty plus jmx off so Grafana is empty', false_lead='ksqlDB kafka leftover', avoided=BAN, knob='.ksql.metrics.extension', old='extension: ', new='extension: io.confluent.ksql.metrics.MetricCollectors', wrong_knob='.ksql.streams.bootstrap.servers', wrong_old='bootstrap.servers: sandbox:9092', wrong_new='bootstrap.servers: hangar:9092', wrong2_old='ksql.service.id: sandbox', wrong2_new='ksql.service.id: hangar', prefix='ksqldb'),
    dict(vendor='Debezium', ok_slug='debez-metrics-reporters-off-leftover', bad_slug='debez-rep-raise-slot-not-reporter', noun='cove', panel='Debezium metrics', needle='debez_up', lie_core='jmx leftover kafka.metrics.reporters empty so Grafana is empty while snapshots still run', false_lead='Debezium slot leftover', avoided=BAN, knob='.kafka.metrics.reporters', old='reporters: ', new='reporters: org.apache.kafka.common.metrics.JmxReporter', wrong_knob='.slot.name', wrong_old='slot.name: sandbox', wrong_new='slot.name: hangar', wrong2_old='database.server.name: sandbox', wrong2_new='database.server.name: hangar', prefix='debez'),
    dict(vendor='Maxwell', ok_slug='maxw-metrics-off-leftover', bad_slug='maxw-met-raise-kafka-not-enable', noun='bight', panel='Maxwell', needle='maxw_up', lie_core='metrics leftover metrics_type empty so Grafana is empty while binlog still tails', false_lead='Maxwell kafka leftover', avoided=BAN, knob='.metrics_type', old='metrics_type: ', new='metrics_type: http', wrong_knob='.kafka.bootstrap.servers', wrong_old='bootstrap.servers: sandbox:9092', wrong_new='bootstrap.servers: hangar:9092', wrong2_old='producer: sandbox', wrong2_new='producer: hangar', prefix='maxw'),
    dict(vendor='Canal CDC', ok_slug='canalx-metrics-off-leftover', bad_slug='canalx-met-raise-dest-not-enable', noun='gulflet', panel='Canal metrics', needle='canalx_up', lie_core='metrics leftover canal.metrics.pull.port 0 so Grafana is empty while dump still runs', false_lead='Canal dest leftover', avoided=BAN, knob='.canal.metrics.pull.port', old='port: 0', new='port: 11112', wrong_knob='.canal.destinations', wrong_old='destinations: sandbox', wrong_new='destinations: hangar', wrong2_old='canal.zkServers: sandbox:2181', wrong2_new='canal.zkServers: hangar:2181', prefix='canalx'),
    dict(vendor='MLflow', ok_slug='mlflow-host-bind-drop-leftover', bad_slug='mlflow-host-raise-store-not-addr', noun='seamount', panel='MLflow', needle='mlflow_up', lie_core='host leftover MLFLOW_HOST 127.0.0.1 so Grafana is empty while runs still finish', false_lead='MLflow store leftover', avoided=BAN, knob='.MLFLOW_HOST', old='MLFLOW_HOST: 127.0.0.1', new='MLFLOW_HOST: 0.0.0.0', wrong_knob='.BACKEND_STORE_URI', wrong_old='BACKEND_STORE_URI: sqlite:////tmp/empty', wrong_new='BACKEND_STORE_URI: postgresql://hangar', wrong2_old='default_artifact_root: /tmp', wrong2_new='default_artifact_root: s3://hangar', prefix='mlflow'),
    dict(vendor='Kubeflow', ok_slug='kflow-central-metrics-off-leftover', bad_slug='kflow-met-raise-prof-not-enable', noun='guyot', panel='Kubeflow metrics', needle='kflow_up', lie_core='metrics leftover centraldashboard metrics off so Grafana is empty while notebooks still Running', false_lead='Kubeflow profile leftover', avoided=BAN, knob='.metrics.enabled', old='enabled: false', new='enabled: true', wrong_knob='.profile', wrong_old='profile: sandbox', wrong_new='profile: hangar', wrong2_old='namespace: sandbox', wrong2_new='namespace: hangar', prefix='kflow'),
    dict(vendor='Feast', ok_slug='feastx-registry-remap-leftover', bad_slug='feastx-reg-raise-proj-not-remap', noun='atoll', panel='Feast', needle='feastx_up', lie_core='registry leftover registry path sandbox so Grafana is the wrong dashboard while materialize still runs', false_lead='Feast project leftover', avoided=BAN, knob='.registry', old='registry: /tmp/sandbox.db', new='registry: /var/lib/feast/hangar.db', wrong_knob='.project', wrong_old='project: sandbox', wrong_new='project: hangar', wrong2_old='provider: local', wrong2_new='provider: gcp', prefix='feastx'),
    dict(vendor='Seldon', ok_slug='seldon-executor-metrics-off-leftover', bad_slug='seldon-met-raise-ns-not-enable', noun='reef', panel='Seldon metrics', needle='seldon_up', lie_core='executor leftover SELDON_EXECUTOR_SERVER_METRICS=false so Grafana is empty while models still Available', false_lead='Seldon ns leftover', avoided=BAN, knob='.SELDON_EXECUTOR_SERVER_METRICS', old='SELDON_EXECUTOR_SERVER_METRICS: false', new='SELDON_EXECUTOR_SERVER_METRICS: true', wrong_knob='.namespace', wrong_old='namespace: sandbox', wrong_new='namespace: seldon', wrong2_old='engine.server.port: 0', wrong2_new='engine.server.port: 8000', prefix='seldon'),
    dict(vendor='BentoML', ok_slug='bentom-metrics-off-leftover', bad_slug='bentom-met-raise-port-not-enable', noun='cay', panel='BentoML metrics', needle='bentom_up', lie_core='metrics leftover BENTOML_CONFIG metrics.enabled=false so Grafana is empty while /predict still 200', false_lead='BentoML port leftover', avoided=BAN, knob='.metrics.enabled', old='enabled: false', new='enabled: true', wrong_knob='.http.port', wrong_old='port: 0', wrong_new='port: 3000', wrong2_old='bentoml.deployment: sandbox', wrong2_new='bentoml.deployment: hangar', prefix='bentom'),
    dict(vendor='KServe', ok_slug='kserv-prometheus-off-leftover', bad_slug='kserv-prom-raise-ns-not-enable', noun='keylet', panel='KServe metrics', needle='kserv_up', lie_core='prometheus leftover metricsAggregator off so Grafana is empty while InferenceService still Ready', false_lead='KServe ns leftover', avoided=BAN, knob='.metricsAggregator.enablePrometheusScraping', old='enablePrometheusScraping: false', new='enablePrometheusScraping: true', wrong_knob='.namespace', wrong_old='namespace: sandbox', wrong_new='namespace: kserve', wrong2_old='ingressGateway: sandbox', wrong2_new='ingressGateway: hangar', prefix='kserv'),
    dict(vendor='Triton', ok_slug='triton-metrics-off-leftover', bad_slug='triton-met-raise-repo-not-enable', noun='spitbar', panel='Triton metrics', needle='triton_up', lie_core='metrics leftover --allow-metrics=false so Grafana is empty while infer still 200', false_lead='Triton repo leftover', avoided=BAN, knob='.allow-metrics', old='allow-metrics: false', new='allow-metrics: true', wrong_knob='.model-repository', wrong_old='model-repository: /tmp', wrong_new='model-repository: /models', wrong2_old='http-port: 0', wrong2_new='http-port: 8000', prefix='triton'),
    dict(vendor='TorchServe', ok_slug='tserve-metrics-off-leftover', bad_slug='tserve-met-raise-model-not-enable', noun='tombolo', panel='TorchServe metrics', needle='tserve_up', lie_core='metrics leftover enable_metrics_api=false so Grafana is empty while predictions still 200', false_lead='TorchServe model leftover', avoided=BAN, knob='.enable_metrics_api', old='enable_metrics_api: false', new='enable_metrics_api: true', wrong_knob='.model_store', wrong_old='model_store: /tmp', wrong_new='model_store: /home/model-server/model-store', wrong2_old='metrics_mode: log', wrong2_new='metrics_mode: prometheus', prefix='tserve'),
    dict(vendor='TF Serving', ok_slug='tfserv-monitoring-off-leftover', bad_slug='tfserv-mon-raise-model-not-enable', noun='cuspate', panel='TF Serving', needle='tfserv_up', lie_core='monitoring leftover monitoring_config_file empty so Grafana is empty while Predict still 200', false_lead='TF Serving model leftover', avoided=BAN, knob='.monitoring_config_file', old='monitoring_config_file: ', new='monitoring_config_file: /etc/tf/monitoring.config', wrong_knob='.model_base_path', wrong_old='model_base_path: /tmp', wrong_new='model_base_path: /models', wrong2_old='rest_api_port: 0', wrong2_new='rest_api_port: 8501', prefix='tfserv'),
    dict(vendor='vLLM', ok_slug='vllm-metrics-off-leftover', bad_slug='vllm-met-raise-model-not-enable', noun='chenier', panel='vLLM metrics', needle='vllm_up', lie_core='metrics leftover disable_log_stats plus prometheus off so Grafana is empty while /v1 still 200', false_lead='vLLM model leftover', avoided=BAN, knob='.disable_log_stats', old='disable_log_stats: true', new='disable_log_stats: false', wrong_knob='.model', wrong_old='model: sandbox', wrong_new='model: hangar', wrong2_old='host: 127.0.0.1', wrong2_new='host: 0.0.0.0', prefix='vllm'),
    dict(vendor='TGI', ok_slug='tgi-json-output-off-leftover', bad_slug='tgi-json-raise-model-not-enable', noun='washover', panel='TGI metrics', needle='tgi_up', lie_core='json leftover --json-output=false plus log empty so Grafana is empty while generate still 200', false_lead='TGI model leftover', avoided=BAN, knob='.json-output', old='json-output: false', new='json-output: true', wrong_knob='.MODEL_ID', wrong_old='MODEL_ID: sandbox', wrong_new='MODEL_ID: hangar', wrong2_old='HOSTNAME: 127.0.0.1', wrong2_new='HOSTNAME: 0.0.0.0', prefix='tgi'),
    dict(vendor='Ollama', ok_slug='ollama-host-bind-drop-leftover', bad_slug='ollama-host-raise-model-not-addr', noun='inletbar', panel='Ollama', needle='ollama_up', lie_core='host leftover OLLAMA_HOST 127.0.0.1 so Grafana is empty while generate still 200', false_lead='Ollama model leftover', avoided=BAN, knob='.OLLAMA_HOST', old='OLLAMA_HOST: 127.0.0.1:11434', new='OLLAMA_HOST: 0.0.0.0:11434', wrong_knob='.OLLAMA_MODELS', wrong_old='OLLAMA_MODELS: /tmp', wrong_new='OLLAMA_MODELS: /usr/share/ollama', wrong2_old='OLLAMA_DEBUG: 0', wrong2_new='OLLAMA_DEBUG: 1', prefix='ollama'),
    dict(vendor='llama.cpp', ok_slug='llamac-metrics-off-leftover', bad_slug='llamac-met-raise-model-not-enable', noun='floodtide', panel='llama.cpp', needle='llamac_up', lie_core='metrics leftover --metrics omitted so Grafana is empty while completion still 200', false_lead='llama.cpp model leftover', avoided=BAN, knob='.metrics', old='metrics: false', new='metrics: true', wrong_knob='.model', wrong_old='model: /tmp/empty.gguf', wrong_new='model: /models/hangar.gguf', wrong2_old='host: 127.0.0.1', wrong2_new='host: 0.0.0.0', prefix='llamac'),
    dict(vendor='LocalAI', ok_slug='locai-metrics-off-leftover', bad_slug='locai-met-raise-model-not-enable', noun='ebbdelta', panel='LocalAI metrics', needle='locai_up', lie_core='metrics leftover LOCALAI_METRICS=false so Grafana is empty while /v1 still 200', false_lead='LocalAI model leftover', avoided=BAN, knob='.LOCALAI_METRICS', old='LOCALAI_METRICS: false', new='LOCALAI_METRICS: true', wrong_knob='.MODELS_PATH', wrong_old='MODELS_PATH: /tmp', wrong_new='MODELS_PATH: /models', wrong2_old='ADDRESS: 127.0.0.1:8080', wrong2_new='ADDRESS: 0.0.0.0:8080', prefix='locai'),
    dict(vendor='W&B', ok_slug='wandb-mode-offline-leftover', bad_slug='wandb-mode-raise-proj-not-online', noun='swash', panel='W&B', needle='wandb_run', lie_core='mode leftover WANDB_MODE=offline so Grafana is empty while runs still finish', false_lead='W&B project leftover', avoided=BAN, knob='.WANDB_MODE', old='WANDB_MODE: offline', new='WANDB_MODE: online', wrong_knob='.WANDB_PROJECT', wrong_old='WANDB_PROJECT: sandbox', wrong_new='WANDB_PROJECT: hangar', wrong2_old='WANDB_BASE_URL: https://sandbox', wrong2_new='WANDB_BASE_URL: https://api.wandb.ai', prefix='wandb'),
    dict(vendor='Neptune', ok_slug='neptun-mode-debug-leftover', bad_slug='neptun-mode-raise-proj-not-async', noun='bermcrest', panel='Neptune', needle='neptun_run', lie_core='mode leftover NEPTUNE_MODE=debug so Grafana is empty while runs still finish', false_lead='Neptune project leftover', avoided=BAN, knob='.NEPTUNE_MODE', old='NEPTUNE_MODE: debug', new='NEPTUNE_MODE: async', wrong_knob='.NEPTUNE_PROJECT', wrong_old='NEPTUNE_PROJECT: sandbox', wrong_new='NEPTUNE_PROJECT: hangar', wrong2_old='NEPTUNE_API_TOKEN: sandbox', wrong2_new='NEPTUNE_API_TOKEN: hangar', prefix='neptun'),
    dict(vendor='Comet', ok_slug='cometx-disabled-leftover', bad_slug='cometx-dis-raise-proj-not-enable', noun='dune', panel='Comet', needle='cometx_run', lie_core='disabled leftover COMET_DISABLED=1 so Grafana is empty while training still finishes', false_lead='Comet project leftover', avoided=BAN, knob='.COMET_DISABLED', old='COMET_DISABLED: 1', new='COMET_DISABLED: 0', wrong_knob='.COMET_PROJECT_NAME', wrong_old='COMET_PROJECT_NAME: sandbox', wrong_new='COMET_PROJECT_NAME: hangar', wrong2_old='COMET_WORKSPACE: sandbox', wrong2_new='COMET_WORKSPACE: hangar', prefix='cometx'),
    dict(vendor='ClearML', ok_slug='clrml-offline-mode-leftover', bad_slug='clrml-off-raise-proj-not-online', noun='foredune', panel='ClearML', needle='clrml_run', lie_core='offline leftover CLEARML_OFFLINE_MODE=1 so Grafana is empty while tasks still complete', false_lead='ClearML project leftover', avoided=BAN, knob='.CLEARML_OFFLINE_MODE', old='CLEARML_OFFLINE_MODE: 1', new='CLEARML_OFFLINE_MODE: 0', wrong_knob='.CLEARML_PROJECT', wrong_old='CLEARML_PROJECT: sandbox', wrong_new='CLEARML_PROJECT: hangar', wrong2_old='CLEARML_API_HOST: https://sandbox', wrong2_new='CLEARML_API_HOST: https://api.clear.ml', prefix='clrml'),
    dict(vendor='Determined', ok_slug='determ-bind-drop-leftover', bad_slug='determ-bind-raise-master-not-addr', noun='backdune', panel='Determined', needle='determ_up', lie_core='bind leftover master bind 127.0.0.1 so Grafana is empty while trials still COMPLETED', false_lead='Determined master leftover', avoided=BAN, knob='.bind_address', old='bind_address: 127.0.0.1', new='bind_address: 0.0.0.0', wrong_knob='.master', wrong_old='master: sandbox:8080', wrong_new='master: hangar:8080', wrong2_old='checkpoint_storage.path: /tmp', wrong2_new='checkpoint_storage.path: /var/lib/determined', prefix='determ'),
    dict(vendor='Horovod', ok_slug='horovd-timeline-off-leftover', bad_slug='horovd-tl-raise-np-not-enable', noun='slacks', panel='Horovod', needle='horovd_up', lie_core='timeline leftover HOROVOD_TIMELINE empty so Grafana is empty while training still finishes', false_lead='Horovod np leftover', avoided=BAN, knob='.HOROVOD_TIMELINE', old='HOROVOD_TIMELINE: ', new='HOROVOD_TIMELINE: /var/log/horovod.json', wrong_knob='.np', wrong_old='np: 1', wrong_new='np: 8', wrong2_old='HOROVOD_FUSION_THRESHOLD: 0', wrong2_new='HOROVOD_FUSION_THRESHOLD: 67108864', prefix='horovd'),
    dict(vendor='DeepSpeed', ok_slug='dpeed-tensorboard-off-leftover', bad_slug='dpeed-tb-raise-ds-not-enable', noun='machair', panel='DeepSpeed', needle='dpeed_up', lie_core='tensorboard leftover tensorboard.enabled=false so Grafana is empty while steps still run', false_lead='DeepSpeed ds leftover', avoided=BAN, knob='.tensorboard.enabled', old='enabled: false', new='enabled: true', wrong_knob='.ds_config', wrong_old='ds_config: /tmp/empty.json', wrong_new='ds_config: /etc/deepspeed/ds.json', wrong2_old='output_path: /tmp', wrong2_new='output_path: /var/lib/deepspeed', prefix='dpeed'),
    dict(vendor='Optuna', ok_slug='optuna-storage-remap-leftover', bad_slug='optuna-st-raise-study-not-remap', noun='saltmarsh', panel='Optuna', needle='optuna_tr', lie_core='storage leftover RDB sandbox so Grafana is the wrong dashboard while trials still COMPLETE', false_lead='Optuna study leftover', avoided=BAN, knob='.storage', old='storage: sqlite:////tmp/sandbox.db', new='storage: postgresql://hangar', wrong_knob='.study_name', wrong_old='study_name: sandbox', wrong_new='study_name: hangar', wrong2_old='load_if_exists: false', wrong2_new='load_if_exists: true', prefix='optuna'),
    dict(vendor='Airbyte', ok_slug='airb-metrics-off-leftover', bad_slug='airb-met-raise-ws-not-enable', noun='mudflat', panel='Airbyte metrics', needle='airb_up', lie_core='metrics leftover MICROMETER_METRICS=false so Grafana is empty while syncs still succeeded', false_lead='Airbyte workspace leftover', avoided=BAN, knob='.MICROMETER_METRICS', old='MICROMETER_METRICS: false', new='MICROMETER_METRICS: true', wrong_knob='.WORKSPACE_ID', wrong_old='WORKSPACE_ID: sandbox', wrong_new='WORKSPACE_ID: hangar', wrong2_old='AIRBYTE_VERSION: sandbox', wrong2_new='AIRBYTE_VERSION: hangar', prefix='airb'),
    dict(vendor='Fivetran', ok_slug='fivetr-group-remap-leftover', bad_slug='fivetr-grp-raise-dest-not-remap', noun='tidalflat', panel='Fivetran', needle='fivetr_up', lie_core='group leftover FIVETRAN_GROUP sandbox so Grafana is the wrong dashboard while syncs still 200', false_lead='Fivetran dest leftover', avoided=BAN, knob='.FIVETRAN_GROUP', old='FIVETRAN_GROUP: sandbox', new='FIVETRAN_GROUP: hangar', wrong_knob='.destination', wrong_old='destination: sandbox', wrong_new='destination: hangar', wrong2_old='FIVETRAN_API_KEY: sandbox', wrong2_new='FIVETRAN_API_KEY: hangar', prefix='fivetr'),
    dict(vendor='Meltano', ok_slug='meltan-send-anonymous-off-leftover', bad_slug='meltan-anon-raise-env-not-enable', noun='mangrove', panel='Meltano', needle='meltan_up', lie_core='telemetry leftover MELTANO_SEND_ANONYMOUS_USAGE_STATS=0 so Grafana is empty while ELT still success', false_lead='Meltano env leftover', avoided=BAN, knob='.MELTANO_SEND_ANONYMOUS_USAGE_STATS', old='MELTANO_SEND_ANONYMOUS_USAGE_STATS: 0', new='MELTANO_SEND_ANONYMOUS_USAGE_STATS: 1', wrong_knob='.MELTANO_ENVIRONMENT', wrong_old='MELTANO_ENVIRONMENT: sandbox', wrong_new='MELTANO_ENVIRONMENT: hangar', wrong2_old='MELTANO_PROJECT_ROOT: /tmp', wrong2_new='MELTANO_PROJECT_ROOT: /project', prefix='meltan'),
    dict(vendor='Singer', ok_slug='singer-state-drop-leftover', bad_slug='singer-st-raise-tap-not-state', noun='swamp', panel='Singer', needle='singer_up', lie_core='state leftover --state /dev/null so Grafana is empty while tap still emits', false_lead='Singer tap leftover', avoided=BAN, knob='.state', old='state: /dev/null', new='state: /var/lib/singer/state.json', wrong_knob='.tap', wrong_old='tap: sandbox', wrong_new='tap: hangar', wrong2_old='catalog: /tmp/empty.json', wrong2_new='catalog: /var/lib/singer/catalog.json', prefix='singer'),
    dict(vendor='Stitch', ok_slug='stitch-client-id-remap-leftover', bad_slug='stitch-id-raise-src-not-remap', noun='bog', panel='Stitch', needle='stitch_up', lie_core='client leftover STITCH_CLIENT_ID sandbox so Grafana is the wrong dashboard while syncs still 200', false_lead='Stitch source leftover', avoided=BAN, knob='.STITCH_CLIENT_ID', old='STITCH_CLIENT_ID: sandbox', new='STITCH_CLIENT_ID: hangar', wrong_knob='.source', wrong_old='source: sandbox', wrong_new='source: hangar', wrong2_old='STITCH_ACCESS_TOKEN: sandbox', wrong2_new='STITCH_ACCESS_TOKEN: hangar', prefix='stitch'),
    dict(vendor='Hevo', ok_slug='hevo-pipeline-remap-leftover', bad_slug='hevo-pipe-raise-dest-not-remap', noun='fen', panel='Hevo', needle='hevox_up', lie_core='pipeline leftover HEVO_PIPELINE_ID sandbox so Grafana is the wrong dashboard while syncs still 200', false_lead='Hevo dest leftover', avoided=BAN, knob='.HEVO_PIPELINE_ID', old='HEVO_PIPELINE_ID: sandbox', new='HEVO_PIPELINE_ID: hangar', wrong_knob='.destination', wrong_old='destination: sandbox', wrong_new='destination: hangar', wrong2_old='HEVO_API_KEY: sandbox', wrong2_new='HEVO_API_KEY: hangar', prefix='hevox'),
    dict(vendor='Rivery', ok_slug='rivery-env-remap-leftover', bad_slug='rivery-env-raise-tok-not-remap', noun='peatland', panel='Rivery', needle='rivery_up', lie_core='env leftover RIVERY_ENVIRONMENT sandbox so Grafana is the wrong dashboard while rivers still 200', false_lead='Rivery token leftover', avoided=BAN, knob='.RIVERY_ENVIRONMENT', old='RIVERY_ENVIRONMENT: sandbox', new='RIVERY_ENVIRONMENT: hangar', wrong_knob='.RIVERY_API_TOKEN', wrong_old='RIVERY_API_TOKEN: sandbox', wrong_new='RIVERY_API_TOKEN: hangar', wrong2_old='account: sandbox', wrong2_new='account: hangar', prefix='rivery'),
    dict(vendor='Matillion', ok_slug='matill-project-remap-leftover', bad_slug='matill-proj-raise-env-not-remap', noun='mire', panel='Matillion', needle='matill_up', lie_core='project leftover MATILLION_PROJECT sandbox so Grafana is the wrong dashboard while jobs still success', false_lead='Matillion env leftover', avoided=BAN, knob='.MATILLION_PROJECT', old='MATILLION_PROJECT: sandbox', new='MATILLION_PROJECT: hangar', wrong_knob='.environment', wrong_old='environment: sandbox', wrong_new='environment: hangar', wrong2_old='MATILLION_GROUP: sandbox', wrong2_new='MATILLION_GROUP: hangar', prefix='matill'),
    dict(vendor='Informatica', ok_slug='infmc-domain-remap-leftover', bad_slug='infmc-dom-raise-repo-not-remap', noun='muskeg', panel='Informatica', needle='infmc_up', lie_core='domain leftover INFA_DOMAINS_FILE sandbox so Grafana is the wrong dashboard while mappings still succeed', false_lead='Informatica repo leftover', avoided=BAN, knob='.INFA_DOMAINS_FILE', old='INFA_DOMAINS_FILE: /tmp/sandbox', new='INFA_DOMAINS_FILE: /opt/infa/hangar', wrong_knob='.INFA_REPOSITORY', wrong_old='INFA_REPOSITORY: sandbox', wrong_new='INFA_REPOSITORY: hangar', wrong2_old='INFA_HOME: /tmp', wrong2_new='INFA_HOME: /opt/infa', prefix='infmc'),
    dict(vendor='Census', ok_slug='census-workspace-remap-leftover', bad_slug='census-ws-raise-dest-not-remap', noun='pocosin', panel='Census', needle='censx_up', lie_core='workspace leftover CENSUS_WORKSPACE sandbox so Grafana is the wrong dashboard while syncs still 200', false_lead='Census dest leftover', avoided=BAN, knob='.CENSUS_WORKSPACE', old='CENSUS_WORKSPACE: sandbox', new='CENSUS_WORKSPACE: hangar', wrong_knob='.destination', wrong_old='destination: sandbox', wrong_new='destination: hangar', wrong2_old='CENSUS_API_KEY: sandbox', wrong2_new='CENSUS_API_KEY: hangar', prefix='censx'),
    dict(vendor='Hightouch', ok_slug='htouch-workspace-remap-leftover', bad_slug='htouch-ws-raise-dest-not-remap', noun='baygall', panel='Hightouch', needle='htouch_up', lie_core='workspace leftover HIGHTOUCH_WORKSPACE sandbox so Grafana is the wrong dashboard while syncs still 200', false_lead='Hightouch dest leftover', avoided=BAN, knob='.HIGHTOUCH_WORKSPACE', old='HIGHTOUCH_WORKSPACE: sandbox', new='HIGHTOUCH_WORKSPACE: hangar', wrong_knob='.destination', wrong_old='destination: sandbox', wrong_new='destination: hangar', wrong2_old='HIGHTOUCH_API_KEY: sandbox', wrong2_new='HIGHTOUCH_API_KEY: hangar', prefix='htouch'),
    dict(vendor='RudderStack', ok_slug='rudder-writekey-remap-leftover', bad_slug='rudder-key-raise-dp-not-remap', noun='hammock', panel='RudderStack', needle='rudder_up', lie_core='write leftover RUDDERSTACK_WRITE_KEY sandbox so Grafana is the wrong dashboard while events still 200', false_lead='RudderStack dataplane leftover', avoided=BAN, knob='.RUDDERSTACK_WRITE_KEY', old='RUDDERSTACK_WRITE_KEY: sandbox', new='RUDDERSTACK_WRITE_KEY: hangar', wrong_knob='.RUDDERSTACK_DATA_PLANE_URL', wrong_old='RUDDERSTACK_DATA_PLANE_URL: https://sandbox', wrong_new='RUDDERSTACK_DATA_PLANE_URL: https://hangar', wrong2_old='RUDDERSTACK_CONTROL_PLANE: sandbox', wrong2_new='RUDDERSTACK_CONTROL_PLANE: hangar', prefix='rudder'),
    dict(vendor='Segment', ok_slug='segment-writekey-remap-leftover', bad_slug='segmnt-key-raise-src-not-remap', noun='everglade', panel='Segment', needle='segmnt_up', lie_core='write leftover SEGMENT_WRITE_KEY sandbox so Grafana is the wrong dashboard while track still 200', false_lead='Segment source leftover', avoided=BAN, knob='.SEGMENT_WRITE_KEY', old='SEGMENT_WRITE_KEY: sandbox', new='SEGMENT_WRITE_KEY: hangar', wrong_knob='.source', wrong_old='source: sandbox', wrong_new='source: hangar', wrong2_old='SEGMENT_HOST: https://sandbox', wrong2_new='SEGMENT_HOST: https://api.segment.io', prefix='segmnt'),
    dict(vendor='Snowplow', ok_slug='splow-collector-bind-drop-leftover', bad_slug='splow-bind-raise-app-not-addr', noun='wetprairie', panel='Snowplow', needle='splow_up', lie_core='collector leftover interface 127.0.0.1 so Grafana is empty while events still 80', false_lead='Snowplow app leftover', avoided=BAN, knob='.interface', old='interface: 127.0.0.1', new='interface: 0.0.0.0', wrong_knob='.appId', wrong_old='appId: sandbox', wrong_new='appId: hangar', wrong2_old='cookieDomain: sandbox', wrong2_new='cookieDomain: hangar', prefix='splow'),
    dict(vendor='Amplitude', ok_slug='ampli-apikey-remap-leftover', bad_slug='ampli-key-raise-srv-not-remap', noun='vernal', panel='Amplitude', needle='ampli_up', lie_core='key leftover AMPLITUDE_API_KEY sandbox so Grafana is the wrong dashboard while events still 200', false_lead='Amplitude server leftover', avoided=BAN, knob='.AMPLITUDE_API_KEY', old='AMPLITUDE_API_KEY: sandbox', new='AMPLITUDE_API_KEY: hangar', wrong_knob='.serverUrl', wrong_old='serverUrl: https://sandbox', wrong_new='serverUrl: https://api2.amplitude.com', wrong2_old='AMPLITUDE_SECRET_KEY: sandbox', wrong2_new='AMPLITUDE_SECRET_KEY: hangar', prefix='ampli'),
    dict(vendor='Mixpanel', ok_slug='mixp-token-remap-leftover', bad_slug='mixp-tok-raise-host-not-remap', noun='playa', panel='Mixpanel', needle='mixp_up', lie_core='token leftover MIXPANEL_TOKEN sandbox so Grafana is the wrong dashboard while track still 200', false_lead='Mixpanel host leftover', avoided=BAN, knob='.MIXPANEL_TOKEN', old='MIXPANEL_TOKEN: sandbox', new='MIXPANEL_TOKEN: hangar', wrong_knob='.MIXPANEL_HOST', wrong_old='MIXPANEL_HOST: https://sandbox', wrong_new='MIXPANEL_HOST: https://api.mixpanel.com', wrong2_old='project: sandbox', wrong2_new='project: hangar', prefix='mixp'),
    dict(vendor='Heap', ok_slug='heap-appid-remap-leftover', bad_slug='heap-id-raise-env-not-remap', noun='salina', panel='Heap', needle='heapx_up', lie_core='app leftover HEAP_APP_ID sandbox so Grafana is the wrong dashboard while track still 200', false_lead='Heap env leftover', avoided=BAN, knob='.HEAP_APP_ID', old='HEAP_APP_ID: sandbox', new='HEAP_APP_ID: hangar', wrong_knob='.environment', wrong_old='environment: sandbox', wrong_new='environment: hangar', wrong2_old='HEAP_HOST: https://sandbox', wrong2_new='HEAP_HOST: https://heapanalytics.com', prefix='heapx'),
    dict(vendor='PostHog', ok_slug='phog-host-remap-leftover', bad_slug='phog-host-raise-key-not-remap', noun='alkali', panel='PostHog', needle='phog_up', lie_core='host leftover POSTHOG_HOST sandbox so Grafana is the wrong dashboard while capture still 200', false_lead='PostHog key leftover', avoided=BAN, knob='.POSTHOG_HOST', old='POSTHOG_HOST: https://sandbox', new='POSTHOG_HOST: https://us.i.posthog.com', wrong_knob='.POSTHOG_API_KEY', wrong_old='POSTHOG_API_KEY: sandbox', wrong_new='POSTHOG_API_KEY: hangar', wrong2_old='POSTHOG_DISABLED: true', wrong2_new='POSTHOG_DISABLED: false', prefix='phog'),
    dict(vendor='FullStory', ok_slug='fstory-orgid-remap-leftover', bad_slug='fstory-org-raise-host-not-remap', noun='sinkhole', panel='FullStory', needle='fstory_up', lie_core='org leftover FULLSTORY_ORG_ID sandbox so Grafana is the wrong dashboard while sessions still 200', false_lead='FullStory host leftover', avoided=BAN, knob='.FULLSTORY_ORG_ID', old='FULLSTORY_ORG_ID: sandbox', new='FULLSTORY_ORG_ID: hangar', wrong_knob='.FULLSTORY_HOST', wrong_old='FULLSTORY_HOST: https://sandbox', wrong_new='FULLSTORY_HOST: https://fullstory.com', wrong2_old='FULLSTORY_DEBUG: true', wrong2_new='FULLSTORY_DEBUG: false', prefix='fstory'),
    dict(vendor='LogRocket', ok_slug='lrock-appid-remap-leftover', bad_slug='lrock-id-raise-host-not-remap', noun='cenote', panel='LogRocket', needle='lrock_up', lie_core='app leftover LOGROCKET_APP_ID sandbox so Grafana is the wrong dashboard while sessions still 200', false_lead='LogRocket host leftover', avoided=BAN, knob='.LOGROCKET_APP_ID', old='LOGROCKET_APP_ID: sandbox', new='LOGROCKET_APP_ID: hangar', wrong_knob='.LOGROCKET_SERVER_URL', wrong_old='LOGROCKET_SERVER_URL: https://sandbox', wrong_new='LOGROCKET_SERVER_URL: https://r.logr-in.com', wrong2_old='LOGROCKET_RELEASE: sandbox', wrong2_new='LOGROCKET_RELEASE: hangar', prefix='lrock'),
    dict(vendor='Databricks', ok_slug='dbrx-host-remap-leftover', bad_slug='dbrx-host-raise-wh-not-remap', noun='karst', panel='Databricks', needle='dbrx_up', lie_core='host leftover DATABRICKS_HOST sandbox so Grafana is the wrong dashboard while jobs still SUCCESS', false_lead='Databricks warehouse leftover', avoided=BAN, knob='.DATABRICKS_HOST', old='DATABRICKS_HOST: https://sandbox', new='DATABRICKS_HOST: https://hangar', wrong_knob='.DATABRICKS_SQL_WAREHOUSE', wrong_old='DATABRICKS_SQL_WAREHOUSE: sandbox', wrong_new='DATABRICKS_SQL_WAREHOUSE: hangar', wrong2_old='DATABRICKS_TOKEN: sandbox', wrong2_new='DATABRICKS_TOKEN: hangar', prefix='dbrx'),
    dict(vendor='Snowflake', ok_slug='snowfl-account-remap-leftover', bad_slug='snowfl-acct-raise-wh-not-remap', noun='polje', panel='Snowflake', needle='snowfl_up', lie_core='account leftover SNOWFLAKE_ACCOUNT sandbox so Grafana is the wrong dashboard while queries still SUCCESS', false_lead='Snowflake warehouse leftover', avoided=BAN, knob='.SNOWFLAKE_ACCOUNT', old='SNOWFLAKE_ACCOUNT: sandbox', new='SNOWFLAKE_ACCOUNT: hangar', wrong_knob='.SNOWFLAKE_WAREHOUSE', wrong_old='SNOWFLAKE_WAREHOUSE: sandbox', wrong_new='SNOWFLAKE_WAREHOUSE: hangar', wrong2_old='SNOWFLAKE_DATABASE: sandbox', wrong2_new='SNOWFLAKE_DATABASE: hangar', prefix='snowfl'),
    dict(vendor='BigQuery', ok_slug='bqry-project-remap-leftover', bad_slug='bqry-proj-raise-ds-not-remap', noun='uvala', panel='BigQuery', needle='bqry_up', lie_core='project leftover GOOGLE_CLOUD_PROJECT sandbox so Grafana is the wrong dashboard while jobs still DONE', false_lead='BigQuery dataset leftover', avoided=BAN, knob='.GOOGLE_CLOUD_PROJECT', old='GOOGLE_CLOUD_PROJECT: sandbox', new='GOOGLE_CLOUD_PROJECT: hangar', wrong_knob='.dataset', wrong_old='dataset: sandbox', wrong_new='dataset: hangar', wrong2_old='location: US', wrong2_new='location: EU', prefix='bqry'),
    dict(vendor='Redshift', ok_slug='rshift-cluster-remap-leftover', bad_slug='rshift-cl-raise-db-not-remap', noun='doline', panel='Redshift', needle='rshift_up', lie_core='cluster leftover PGHOST sandbox so Grafana is the wrong dashboard while queries still FINISHED', false_lead='Redshift db leftover', avoided=BAN, knob='.PGHOST', old='PGHOST: sandbox.redshift.amazonaws.com', new='PGHOST: hangar.redshift.amazonaws.com', wrong_knob='.PGDATABASE', wrong_old='PGDATABASE: sandbox', wrong_new='PGDATABASE: hangar', wrong2_old='PGPORT: 0', wrong2_new='PGPORT: 5439', prefix='rshift'),
    dict(vendor='Synapse', ok_slug='synap-workspace-remap-leftover', bad_slug='synap-ws-raise-pool-not-remap', noun='ponor', panel='Synapse', needle='synap_up', lie_core='workspace leftover SYNAPSE_WORKSPACE sandbox so Grafana is the wrong dashboard while pipelines still Succeeded', false_lead='Synapse pool leftover', avoided=BAN, knob='.SYNAPSE_WORKSPACE', old='SYNAPSE_WORKSPACE: sandbox', new='SYNAPSE_WORKSPACE: hangar', wrong_knob='.sql_pool', wrong_old='sql_pool: sandbox', wrong_new='sql_pool: hangar', wrong2_old='SYNAPSE_ENDPOINT: https://sandbox', wrong2_new='SYNAPSE_ENDPOINT: https://hangar', prefix='synap'),
    dict(vendor='Fabric', ok_slug='fabrx-workspace-remap-leftover', bad_slug='fabrx-ws-raise-cap-not-remap', noun='resurgence', panel='Fabric', needle='fabrx_up', lie_core='workspace leftover FABRIC_WORKSPACE sandbox so Grafana is the wrong dashboard while pipelines still Succeeded', false_lead='Fabric capacity leftover', avoided=BAN, knob='.FABRIC_WORKSPACE', old='FABRIC_WORKSPACE: sandbox', new='FABRIC_WORKSPACE: hangar', wrong_knob='.capacity', wrong_old='capacity: sandbox', wrong_new='capacity: hangar', wrong2_old='FABRIC_TENANT: sandbox', wrong2_new='FABRIC_TENANT: hangar', prefix='fabrx'),
    dict(vendor='Materialize', ok_slug='matlz-listen-drop-leftover', bad_slug='matlz-list-raise-cluster-not-addr', noun='vaucluse', panel='Materialize', needle='matlz_up', lie_core='listen leftover listen_addr 127.0.0.1 so Grafana is empty while SQL still 6875', false_lead='Materialize cluster leftover', avoided=BAN, knob='.listen_addr', old='listen_addr: 127.0.0.1:6875', new='listen_addr: 0.0.0.0:6875', wrong_knob='.cluster', wrong_old='cluster: sandbox', wrong_new='cluster: hangar', wrong2_old='mz_sql: sandbox', wrong2_new='mz_sql: hangar', prefix='matlz'),
    dict(vendor='RisingWave', ok_slug='rwave-prom-bind-drop-leftover', bad_slug='rwave-prom-raise-meta-not-addr', noun='artesian', panel='RisingWave', needle='rwave_up', lie_core='prometheus leftover prometheus_listener_addr 127.0.0.1 so Grafana is empty while SQL still 4566', false_lead='RisingWave meta leftover', avoided=BAN, knob='.prometheus_listener_addr', old='prometheus_listener_addr: 127.0.0.1:1222', new='prometheus_listener_addr: 0.0.0.0:1222', wrong_knob='.meta_addr', wrong_old='meta_addr: sandbox:5690', wrong_new='meta_addr: hangar:5690', wrong2_old='listen_addr: 127.0.0.1', wrong2_new='listen_addr: 0.0.0.0', prefix='rwave'),
    dict(vendor='Timeplus', ok_slug='tplus-http-bind-drop-leftover', bad_slug='tplus-http-raise-ns-not-addr', noun='springbox', panel='Timeplus', needle='tplus_up', lie_core='http leftover http.listen 127.0.0.1 so Grafana is empty while SQL still 8463', false_lead='Timeplus ns leftover', avoided=BAN, knob='.http.listen', old='listen: 127.0.0.1:3218', new='listen: 0.0.0.0:3218', wrong_knob='.namespace', wrong_old='namespace: sandbox', wrong_new='namespace: hangar', wrong2_old='data_dir: /tmp', wrong2_new='data_dir: /var/lib/timeplus', prefix='tplus'),
    dict(vendor='Firebolt', ok_slug='fbolt-engine-remap-leftover', bad_slug='fbolt-eng-raise-db-not-remap', noun='seep', panel='Firebolt', needle='fbolt_up', lie_core='engine leftover FIREBOLT_ENGINE sandbox so Grafana is the wrong dashboard while queries still SUCCESS', false_lead='Firebolt db leftover', avoided=BAN, knob='.FIREBOLT_ENGINE', old='FIREBOLT_ENGINE: sandbox', new='FIREBOLT_ENGINE: hangar', wrong_knob='.FIREBOLT_DATABASE', wrong_old='FIREBOLT_DATABASE: sandbox', wrong_new='FIREBOLT_DATABASE: hangar', wrong2_old='FIREBOLT_ACCOUNT: sandbox', wrong2_new='FIREBOLT_ACCOUNT: hangar', prefix='fbolt'),
    dict(vendor='Consul', ok_slug='consul-telemetry-off-leftover', bad_slug='consul-tel-raise-dc-not-enable', noun='brook2', panel='Consul metrics', needle='consul_up', lie_core='telemetry leftover prometheus_retention_time 0 so Grafana is empty while catalog still 8500', false_lead='Consul dc leftover', avoided=BAN, knob='.telemetry.prometheus_retention_time', old='prometheus_retention_time: 0', new='prometheus_retention_time: 60s', wrong_knob='.datacenter', wrong_old='datacenter: sandbox', wrong_new='datacenter: hangar', wrong2_old='bind_addr: 127.0.0.1', wrong2_new='bind_addr: 0.0.0.0', prefix='consul'),
    dict(vendor='Vault', ok_slug='vaultx-prometheus-off-leftover', bad_slug='vaultx-prom-raise-ns-not-enable', noun='rill2', panel='Vault metrics', needle='vaultx_up', lie_core='prometheus leftover unauthenticated_metrics_access=false plus retention 0 so Grafana is empty', false_lead='Vault ns leftover', avoided=BAN, knob='.telemetry.prometheus_retention_time', old='prometheus_retention_time: 0', new='prometheus_retention_time: 24h', wrong_knob='.namespace', wrong_old='namespace: sandbox', wrong_new='namespace: hangar', wrong2_old='listener.tcp.address: 127.0.0.1:8200', wrong2_new='listener.tcp.address: 0.0.0.0:8200', prefix='vaultx'),
    dict(vendor='Boundary', ok_slug='boundx-metrics-off-leftover', bad_slug='boundx-met-raise-ctrl-not-enable', noun='beck2', panel='Boundary metrics', needle='boundx_up', lie_core='metrics leftover prometheus_retention_time 0 so Grafana is empty while sessions still active', false_lead='Boundary controller leftover', avoided=BAN, knob='.telemetry.prometheus_retention_time', old='prometheus_retention_time: 0', new='prometheus_retention_time: 24h', wrong_knob='.controller.public_cluster_addr', wrong_old='public_cluster_addr: sandbox', wrong_new='public_cluster_addr: hangar', wrong2_old='listener.purpose: sandbox', wrong2_new='listener.purpose: api', prefix='boundx'),
    dict(vendor='Pulumi', ok_slug='pulumi-tracing-off-leftover', bad_slug='pulumi-trc-raise-stack-not-enable', noun='wadi2', panel='Pulumi', needle='pulumi_up', lie_core='tracing leftover PULUMI_TRACING empty so Grafana is empty while up still succeeds', false_lead='Pulumi stack leftover', avoided=BAN, knob='.PULUMI_TRACING', old='PULUMI_TRACING: ', new='PULUMI_TRACING: file:/var/log/pulumi.trace', wrong_knob='.stack', wrong_old='stack: sandbox', wrong_new='stack: hangar', wrong2_old='PULUMI_BACKEND_URL: file:///tmp', wrong2_new='PULUMI_BACKEND_URL: s3://hangar', prefix='pulumi'),
    dict(vendor='Crossplane', ok_slug='xplane-metrics-bind-drop-leftover', bad_slug='xplane-bind-raise-ns-not-addr', noun='arroyo2', panel='Crossplane metrics', needle='xplane_up', lie_core='metrics leftover --metrics-bind-address 127.0.0.1 so Grafana is empty while XRDs still Established', false_lead='Crossplane ns leftover', avoided=BAN, knob='.metrics-bind-address', old='metrics-bind-address: 127.0.0.1:8080', new='metrics-bind-address: 0.0.0.0:8080', wrong_knob='.namespace', wrong_old='namespace: sandbox', wrong_new='namespace: crossplane-system', wrong2_old='leader-elect: false', wrong2_new='leader-elect: true', prefix='xplane'),
    dict(vendor='Flux CD', ok_slug='fluxcd-metrics-bind-drop-leftover', bad_slug='fluxcd-bind-raise-ns-not-addr', noun='nullah2', panel='Flux metrics', needle='fluxcd_up', lie_core='metrics leftover --metrics-addr 127.0.0.1 so Grafana is empty while kustomizations still Ready', false_lead='Flux ns leftover', avoided=BAN, knob='.metrics-addr', old='metrics-addr: 127.0.0.1:8080', new='metrics-addr: 0.0.0.0:8080', wrong_knob='.namespace', wrong_old='namespace: sandbox', wrong_new='namespace: flux-system', wrong2_old='watch-all-namespaces: false', wrong2_new='watch-all-namespaces: true', prefix='fluxcd'),
    dict(vendor='Helm', ok_slug='helm-debug-off-leftover', bad_slug='helm-dbg-raise-ns-not-enable', noun='yazoo2', panel='Helm', needle='helmx_up', lie_core='debug leftover HELM_DEBUG=0 plus history max 0 so Grafana is empty while releases still deployed', false_lead='Helm ns leftover', avoided=BAN, knob='.HELM_DEBUG', old='HELM_DEBUG: 0', new='HELM_DEBUG: 1', wrong_knob='.namespace', wrong_old='namespace: sandbox', wrong_new='namespace: hangar', wrong2_old='HELM_DRIVER: memory', wrong2_new='HELM_DRIVER: secret', prefix='helmx'),
    dict(vendor='Dask', ok_slug='dask-dashboard-bind-drop-leftover', bad_slug='dask-dash-raise-sched-not-addr', noun='gill2', panel='Dask dashboard', needle='daskx_up', lie_core='dashboard leftover dashboard_address 127.0.0.1 so Grafana is empty while workers still run', false_lead='Dask scheduler leftover', avoided=BAN, knob='.dashboard_address', old='dashboard_address: 127.0.0.1:8787', new='dashboard_address: 0.0.0.0:8787', wrong_knob='.scheduler_address', wrong_old='scheduler_address: tcp://sandbox:8786', wrong_new='scheduler_address: tcp://hangar:8786', wrong2_old='local_directory: /tmp', wrong2_new='local_directory: /var/lib/dask', prefix='daskx'),
    dict(vendor='Ray', ok_slug='ray-metrics-export-off-leftover', bad_slug='ray-met-raise-ns-not-enable', noun='burn2', panel='Ray metrics', needle='rayx_up', lie_core='metrics leftover RAY_METRIC_EXPORT=false so Grafana is empty while jobs still SUCCEEDED', false_lead='Ray ns leftover', avoided=BAN, knob='.RAY_METRIC_EXPORT', old='RAY_METRIC_EXPORT: false', new='RAY_METRIC_EXPORT: true', wrong_knob='.namespace', wrong_old='namespace: sandbox', wrong_new='namespace: hangar', wrong2_old='RAY_ADDRESS: sandbox:6379', wrong2_new='RAY_ADDRESS: hangar:6379', prefix='rayx'),
    dict(vendor='Guild AI', ok_slug='guild-off-leftover', bad_slug='guild-off-raise-user-not-enable', noun='killn2', panel='Guild AI', needle='guildx_run', lie_core='guild leftover GUILD_OFF=1 so Grafana is empty while runs still finish', false_lead='Guild user leftover', avoided=BAN, knob='.GUILD_OFF', old='GUILD_OFF: 1', new='GUILD_OFF: 0', wrong_knob='.user', wrong_old='user: sandbox', wrong_new='user: hangar', wrong2_old='GUILD_HOME: /tmp', wrong2_new='GUILD_HOME: ~/.guild', prefix='guildx'),
    dict(vendor='Sacred', ok_slug='sacred-observer-off-leftover', bad_slug='sacred-obs-raise-db-not-enable', noun='headwat2', panel='Sacred', needle='sacred_run', lie_core='observer leftover MongoObserver off so Grafana is empty while experiments still COMPLETE', false_lead='Sacred db leftover', avoided=BAN, knob='.MongoObserver', old='MongoObserver: false', new='MongoObserver: true', wrong_knob='.db_name', wrong_old='db_name: sandbox', wrong_new='db_name: hangar', wrong2_old='url: mongodb://sandbox', wrong2_new='url: mongodb://hangar', prefix='sacred'),
    dict(vendor='Terragrunt', ok_slug='tgrunt-log-drop-leftover', bad_slug='tgrunt-log-raise-env-not-level', noun='mouthb2', panel='Terragrunt', needle='tgrunt_up', lie_core='log leftover TERRAGRUNT_LOG_LEVEL=error plus log /dev/null so Grafana is empty while apply still succeeds', false_lead='Terragrunt env leftover', avoided=BAN, knob='.TERRAGRUNT_LOG_LEVEL', old='TERRAGRUNT_LOG_LEVEL: error', new='TERRAGRUNT_LOG_LEVEL: info', wrong_knob='.TERRAGRUNT_SOURCE', wrong_old='TERRAGRUNT_SOURCE: sandbox', wrong_new='TERRAGRUNT_SOURCE: hangar', wrong2_old='TERRAGRUNT_DOWNLOAD: /tmp', wrong2_new='TERRAGRUNT_DOWNLOAD: .terragrunt-cache', prefix='tgrunt'),
    dict(vendor='Spacelift', ok_slug='spacelift-endpoint-remap-leftover', bad_slug='spacef-ep-raise-stack-not-remap', noun='levee3', panel='Spacelift', needle='spacef_up', lie_core='endpoint leftover SPACELIFT_API_ENDPOINT sandbox so Grafana is the wrong dashboard while stacks still 200', false_lead='Spacelift stack leftover', avoided=BAN, knob='.SPACELIFT_API_ENDPOINT', old='SPACELIFT_API_ENDPOINT: https://sandbox', new='SPACELIFT_API_ENDPOINT: https://hangar.app.spacelift.io', wrong_knob='.stack', wrong_old='stack: sandbox', wrong_new='stack: hangar', wrong2_old='SPACELIFT_API_KEY_ID: sandbox', wrong2_new='SPACELIFT_API_KEY_ID: hangar', prefix='spacef'),
    dict(vendor='Atlantis', ok_slug='atlantis-bind-drop-leftover', bad_slug='atlant-bind-raise-repo-not-addr', noun='oxbow3', panel='Atlantis', needle='atlant_up', lie_core='bind leftover ATLANTIS_ATLANTIS_URL 127.0.0.1 so Grafana is empty while plans still succeed', false_lead='Atlantis repo leftover', avoided=BAN, knob='.ATLANTIS_ATLANTIS_URL', old='ATLANTIS_ATLANTIS_URL: http://127.0.0.1:4141', new='ATLANTIS_ATLANTIS_URL: http://0.0.0.0:4141', wrong_knob='.ATLANTIS_REPO_ALLOWLIST', wrong_old='ATLANTIS_REPO_ALLOWLIST: sandbox/*', wrong_new='ATLANTIS_REPO_ALLOWLIST: hangar/*', wrong2_old='ATLANTIS_GH_USER: sandbox', wrong2_new='ATLANTIS_GH_USER: hangar', prefix='atlant'),
    dict(vendor='Terraform Cloud', ok_slug='tfc-hostname-remap-leftover', bad_slug='tfc-host-raise-org-not-remap', noun='chute3', panel='TFC', needle='tfcx_up', lie_core='hostname leftover TFC_HOSTNAME sandbox so Grafana is the wrong dashboard while runs still applied', false_lead='TFC org leftover', avoided=BAN, knob='.TFC_HOSTNAME', old='TFC_HOSTNAME: sandbox', new='TFC_HOSTNAME: app.terraform.io', wrong_knob='.TFC_ORGANIZATION', wrong_old='TFC_ORGANIZATION: sandbox', wrong_new='TFC_ORGANIZATION: hangar', wrong2_old='TFC_WORKSPACE: sandbox', wrong2_new='TFC_WORKSPACE: hangar', prefix='tfcx'),
    dict(vendor='Cluster API', ok_slug='capi-metrics-bind-drop-leftover', bad_slug='capi-bind-raise-ns-not-addr', noun='pool2', panel='CAPI metrics', needle='capix_up', lie_core='metrics leftover --metrics-bind-address 127.0.0.1 so Grafana is empty while machines still Running', false_lead='CAPI ns leftover', avoided=BAN, knob='.metrics-bind-address', old='metrics-bind-address: 127.0.0.1:8080', new='metrics-bind-address: 0.0.0.0:8080', wrong_knob='.namespace', wrong_old='namespace: sandbox', wrong_new='namespace: capi-system', wrong2_old='watch-filter: sandbox', wrong2_new='watch-filter: ', prefix='capix'),
    dict(vendor='Kustomize', ok_slug='kustomize-load-restrictor-drop-leftover', bad_slug='kustom-lr-raise-ns-not-restrict', noun='glide2', panel='Kustomize', needle='kustom_up', lie_core='restrict leftover loadRestrictor LoadRestrictionsRootOnly plus build metadata off so Grafana is empty', false_lead='Kustomize ns leftover', avoided=BAN, knob='.loadRestrictor', old='loadRestrictor: LoadRestrictionsRootOnly', new='loadRestrictor: LoadRestrictionsNone', wrong_knob='.namespace', wrong_old='namespace: sandbox', wrong_new='namespace: hangar', wrong2_old='buildMetadata: []', wrong2_new='buildMetadata: [originAnnotations]', prefix='kustom'),
    dict(vendor='Skaffold', ok_slug='skaffold-cleanup-log-drop-leftover', bad_slug='skaff-log-raise-ns-not-level', noun='pocket2', panel='Skaffold', needle='skaff_up', lie_core='log leftover --verbosity error plus event-log-file /dev/null so Grafana is empty while deploys still succeed', false_lead='Skaffold ns leftover', avoided=BAN, knob='.verbosity', old='verbosity: error', new='verbosity: info', wrong_knob='.namespace', wrong_old='namespace: sandbox', wrong_new='namespace: hangar', wrong2_old='event-log-file: /dev/null', wrong2_new='event-log-file: /var/log/skaffold.events', prefix='skaff'),
    dict(vendor='Elasticsearch', ok_slug='es-http-bind-drop-leftover', bad_slug='es-bind-raise-cluster-not-addr', noun='eddy2', panel='ES metrics', needle='esrch_up', lie_core='http leftover network.host 127.0.0.1 so Grafana is empty while search still 9200', false_lead='Elasticsearch cluster leftover', avoided=BAN, knob='.network.host', old='network.host: 127.0.0.1', new='network.host: 0.0.0.0', wrong_knob='.cluster.name', wrong_old='name: sandbox', wrong_new='name: hangar', wrong2_old='path.data: /tmp', wrong2_new='path.data: /var/lib/elasticsearch', prefix='esrch'),
]

assert len(SPECS) == 88, len(SPECS)
for i, spec in enumerate(SPECS):
    _l15(1348 + i, **spec)
