"""Observability plants r175-r182."""

from mill_plants import _fail, _ok

MORE = []

# r175 Grafana Faro session vs Tempo trace
MORE.append(
    (
        _ok(
            slug="faro-session-vs-tempo-tid",
            service="web-checkin-svc",
            dashboard_uid="checkin-faro-04",
            panel="RUM to backend",
            query='{resource.service.name="web-checkin-svc"}',
            lie="Grafana Faro session_id is used as Tempo traceId; Faro session is not W3C trace_id",
            false_lead="Sentry event_id leftover on the same dashboard",
            config_path="grafana/dashboards/checkin-faro-04.json",
            lie_path="grafana/dashboards/checkin-faro-04.json",
            truth_name="Faro payload otel.trace_id",
            reload_name="grafana",
            side="Faro session replay still keys on session_id",
            surfaces="Grafana Faro session_id vs Tempo trace_id",
            avoided="r162 Sentry event_id; Tempo missing dim",
            this_is="Faro session_id looked up in Tempo",
            step_note="False lead Sentry var 4-5; Faro session vs otel.trace_id 6-8; patch var 9-12.",
            search_cmd="curl -sS $GRAFANA/api/search?query=checkin-faro-04 | jq -c '.[]|{uid,title}'",
            dash_cmd="curl -sS $GRAFANA/api/dashboards/uid/checkin-faro-04 | jq '.dashboard.templating.list[]|{name,query}'",
            query_cmd="curl -sS $TEMPO/api/traces/sess_7f3a9c | jq .message",
            false_cmd="jq '.dashboard.templating.list[].name' grafana/dashboards/checkin-faro-04.json",
            truth_cmd="curl -sS $FARO/collect | jq '{session:.[0].session.id,trace:.[0].traces[0].trace_id}'",
            confirm_cmd="jq '.dashboard.panels[]|select(.type==\"traces\")' grafana/dashboards/checkin-faro-04.json",
            reload_cmd="kubectl -n grafana rollout restart deploy/grafana && kubectl -n grafana rollout status deploy/grafana --timeout=90s",
            requery_cmd="curl -sS $TEMPO/api/traces/4bf92f3577b34da6a3ce929d0e0e4736 | jq '{rootServiceName,spanCount}'",
            grafana_ok_cmd="curl -sS $GRAFANA/api/ds/query -d @/tmp/faro-join.json | jq '.results.A.frames[0].schema'",
            side_cmd="curl -sS $FARO/api/sessions/sess_7f3a9c | jq '{id,hasReplay}'",
            final_cmd="jq '.dashboard.templating.list[]|{name,query}' grafana/dashboards/checkin-faro-04.json",
            patch_old='"query": "faro_session_id"',
            patch_new='"query": "faro_otel_trace_id"',
            runbook_path="runbooks/web-checkin-faro-tempo.md",
            runbook="# web-checkin-svc Faro vs Tempo\nUse Faro otel.trace_id, not session.id, as Tempo traceId.\n",
            goal="web-checkin-svc dashboard checkin-faro-04 RUM to backend is empty. Faro has sessions. Fix the id join.",
            plan="Dashboard var → Tempo 404 on session_id → not Sentry event_id → switch to Faro otel.trace_id.",
            outcome="Templating uses faro_otel_trace_id. Trace panel loads. Session replay still uses session_id.",
            obs1='[{"uid":"checkin-faro-04","title":"web checkin RUM join"}]',
            obs2='{"name":"faro_session_id","query":"faro_session_id"}\n{"name":"sentry_event_id","query":"unused"}',
            obs3='"trace not found"',
            obs4='"faro_session_id"\n"sentry_event_id"\n# sentry var unused; not r162',
            obs5="sentry_event_id present but panel traces uses faro_session_id",
            obs6='traces panel queryType=traceId query=${faro_session_id}',
            obs7='{"session":"sess_7f3a9c","trace":"4bf92f3577b34da6a3ce929d0e0e4736"}',
            obs8='{"type":"traces","targets":[{"query":"${faro_session_id}"}]}',
            obs9="patched templating faro_session_id → faro_otel_trace_id",
            obs10='deployment "grafana" successfully rolled out',
            obs11='{"rootServiceName":"web-checkin-svc","spanCount":22}',
            obs12='{"name":"Trace"}',
            obs13='{"id":"sess_7f3a9c","hasReplay":true}',
            obs14="wrote runbooks/web-checkin-faro-tempo.md",
            obs15='{"name":"faro_otel_trace_id","query":"faro_otel_trace_id"}',
        ),
        _fail(
            slug="faro-copy-session-into-resource",
            service="web-upgrade-svc",
            dashboard_uid="upgrade-faro-sess",
            panel="upgrade RUM join",
            query='{resource.service.name="web-upgrade-svc"}',
            lie="Writing Faro session_id into resource.service.instance.id does not make Tempo accept it as traceId",
            false_lead="missing resource attribute on Faro spans",
            config_path="faro/web-upgrade.js",
            lie_path="grafana/dashboards/upgrade-faro-sess.json",
            wrong_path="faro/web-upgrade.js",
            reload_name="web-upgrade-svc",
            ticket="OBS-4435",
            xfail="tests/test_upgrade_faro.py",
            surfaces="Faro session copied to resource vs Tempo traceId var",
            avoided="r162 Sentry event_id as the RCA",
            this_is="fail/handoff: session_id as resource, Tempo still 404s",
            step_note="resource attr 6-10; still 404 11; late dashboard var 12; handoff 14-15.",
            next_note="Next: Grafana Adaptive Metrics dropping instance vs log join.",
            search_cmd="curl -sS $GRAFANA/api/search?query=upgrade-faro-sess | jq -c '.[]|{uid,title}'",
            dash_cmd="curl -sS $GRAFANA/api/dashboards/uid/upgrade-faro-sess | jq '.dashboard.panels[0]'",
            query_cmd="curl -sS $TEMPO/api/traces/sess_upgrade_9 | jq .message",
            false_cmd="rg -n 'session|resource' faro/web-upgrade.js | head",
            reload_cmd="kubectl -n web rollout restart deploy/web-upgrade-svc && kubectl -n web rollout status deploy/web-upgrade-svc --timeout=90s",
            requery_cmd="curl -sS $TEMPO/api/traces/sess_upgrade_9 | jq .message",
            denied_cmd="kubectl -n grafana auth can-i patch configmap/grafana-dashboards --as=sre-bot",
            xfail_cmd="printf '%s\\n' '@pytest.mark.xfail(reason=\"faro dashboard owned by web-obs\")\\ndef test_upgrade_faro():\\n    assert False' > tests/test_upgrade_faro.py",
            wrong_old="faro.init({ app: 'web-upgrade' })",
            wrong_new="faro.init({ app: 'web-upgrade', sessionTracking: { persist: true } })\n  faro.api.setSession({ id: sid })",
            wrong2_old="instrumentations: [new TracingInstrumentation()]",
            wrong2_new="instrumentations: [new TracingInstrumentation({ resourceAttributes: { 'service.instance.id': sid } })]",
            ticket_path="tickets/OBS-4435.md",
            ticket_body="OBS-4435: web-upgrade-svc Tempo 404s ${faro_session_id}. Resource attrs do not change the dashboard var. Need templating patch; no RBAC.\n",
            goal="web-upgrade-svc dashboard upgrade-faro-sess RUM join is empty. Make Tempo return the tree.",
            plan="Copy Faro session_id onto OTel resource so Tempo finds it.",
            outcome="sessionTracking + service.instance.id set; Tempo still 404s sess_upgrade_9. Late dashboard var. Handoff OBS-4435.",
            obs1='[{"uid":"upgrade-faro-sess","title":"web upgrade Faro"}]',
            obs2='{"title":"upgrade RUM join","targets":[{"query":"${faro_session_id}"}]}',
            obs3='"trace not found"',
            obs4="faro.init({ app: 'web-upgrade' })\n# blamed missing resource",
            obs5="faro/web-upgrade.js no session persist",
            obs6="same faro sdk — treated as RCA",
            obs7="patched sessionTracking persist",
            obs8='deployment "web-upgrade-svc" successfully rolled out',
            obs9='"trace not found"',
            obs10="patched resourceAttributes service.instance.id=sid",
            obs11='"trace not found"',
            obs12="grafana/dashboards/upgrade-faro-sess.json traces query=${faro_session_id}",
            obs13="no",
            obs14="wrote tickets/OBS-4435.md",
            obs15="xfail tests/test_upgrade_faro.py",
        ),
    )
)

# r176 Grafana Adaptive Metrics dropping instance
MORE.append(
    (
        _ok(
            slug="adaptive-metrics-drop-instance",
            service="kiosk-print-svc",
            dashboard_uid="kiosk-ametrics-2",
            panel="print errors by instance",
            query='sum by (instance) (rate(print_errors_total{service="kiosk-print-svc"}[5m]))',
            lie="Grafana Adaptive Metrics aggregation drops instance so join with Loki {instance} is empty",
            false_lead="Mimir max_label_names_per_series rejecting instance",
            config_path="mimir/limits.yaml",
            lie_path="grafana/adaptive-metrics/kiosk.json",
            truth_name="raw Mimir series before aggregation",
            reload_name="mimir-adaptive-metrics",
            side="other labels (pod) still aggregated",
            surfaces="Grafana Adaptive Metrics vs instance join",
            avoided="r109-r158 Mimir max_label_names_per_series",
            this_is="Adaptive Metrics drop instance, not label-name cap",
            step_note="False lead max_label_names 4-5; recommendations drop instance 6-8; keep instance 9-12.",
            search_cmd="curl -sS $GRAFANA/api/search?query=kiosk-ametrics-2 | jq -c '.[]|{uid,title}'",
            dash_cmd="curl -sS $GRAFANA/api/dashboards/uid/kiosk-ametrics-2 | jq '.dashboard.panels[0].targets'",
            query_cmd="curl -sS -G $MIMIR/prometheus/api/v1/query --data-urlencode 'query=sum by (instance) (rate(print_errors_total{service=\"kiosk-print-svc\"}[5m]))'",
            false_cmd="curl -sS $MIMIR/config | yq '.limits.max_label_names_per_series'",
            truth_cmd="curl -sS -G $MIMIR/prometheus/api/v1/series --data-urlencode 'match[]=print_errors_total{service=\"kiosk-print-svc\"}' | jq '[.data[].instance]|unique'",
            confirm_cmd="jq '.recommendations[]|{metric,drop_labels}' grafana/adaptive-metrics/kiosk.json",
            reload_cmd="kubectl -n mimir rollout restart deploy/adaptive-metrics && kubectl -n mimir rollout status deploy/adaptive-metrics --timeout=90s",
            requery_cmd="curl -sS -G $MIMIR/prometheus/api/v1/query --data-urlencode 'query=sum by (instance) (rate(print_errors_total{service=\"kiosk-print-svc\"}[5m]))'",
            grafana_ok_cmd="curl -sS $GRAFANA/api/ds/query -d @/tmp/kiosk-print.json | jq '.results.A.frames[0].schema.fields'",
            side_cmd="curl -sS -G $MIMIR/prometheus/api/v1/query --data-urlencode 'query=count by (pod) (print_errors_total{service=\"kiosk-print-svc\"})' | jq '.data.result|length'",
            final_cmd="jq '.recommendations[]|{metric,drop_labels}' grafana/adaptive-metrics/kiosk.json",
            patch_old='"drop_labels": ["instance", "pod_template_hash"]',
            patch_new='"drop_labels": ["pod_template_hash"]',
            runbook_path="runbooks/kiosk-adaptive-metrics.md",
            runbook="# kiosk-print-svc Adaptive Metrics\nDo not drop instance when dashboards join logs on instance.\nNot a max_label_names_per_series cap.\n",
            goal="kiosk-print-svc dashboard kiosk-ametrics-2 print errors by instance is empty after Adaptive Metrics. Restore the join key.",
            plan="Empty by(instance) → max_label_names (false, 30) → recommendations drop instance → keep instance.",
            outcome="drop_labels no longer includes instance. Panel has 6 instances. pod_template_hash still dropped.",
            obs1='[{"uid":"kiosk-ametrics-2","title":"kiosk print errors"}]',
            obs2='[{"expr":"sum by (instance) (rate(print_errors_total{service=\\"kiosk-print-svc\\"}[5m]))"}]',
            obs3='{"status":"success","data":{"result":[]}}',
            obs4="30\n# well above current label count",
            obs5="max_label_names_per_series=30 — banned plant not this",
            obs6='{"metric":"print_errors_total","drop_labels":["instance","pod_template_hash"]}',
            obs7='[null]\n# aggregated series have instance="" ',
            obs8="print_errors_total drops instance",
            obs9="patched drop_labels removed instance",
            obs10='deployment "adaptive-metrics" successfully rolled out',
            obs11='{"status":"success","data":{"result":[{"metric":{"instance":"kiosk-3"},"value":[1710000600,"0.4"]}]}}',
            obs12='[{"name":"instance"},{"name":"Value"}]',
            obs13="3",
            obs14="wrote runbooks/kiosk-adaptive-metrics.md",
            obs15='{"metric":"print_errors_total","drop_labels":["pod_template_hash"]}',
        ),
        _fail(
            slug="adaptive-metrics-raise-label-cap",
            service="gate-display-svc",
            dashboard_uid="gate-ametrics-cap",
            panel="fps by instance",
            query='sum by (instance) (rate(display_frames_total{service="gate-display-svc"}[5m]))',
            lie="Raising max_label_names_per_series does not restore instance dropped by Adaptive Metrics",
            false_lead="Mimir max_label_names_per_series too low",
            config_path="mimir/gate-limits.yaml",
            lie_path="grafana/adaptive-metrics/gate.json",
            wrong_path="mimir/gate-limits.yaml",
            reload_name="mimir-ingester",
            ticket="OBS-4436",
            xfail="tests/test_gate_ametrics.py",
            surfaces="label-cap leftover vs Adaptive Metrics drop",
            avoided="using max_label_names as the actual RCA",
            this_is="fail/handoff: raised label cap, instance still dropped",
            step_note="label cap 6-10; still empty 11; late recommendations 12; handoff 14-15.",
            next_note="Next: Grafana Alloy prometheus.relabel vs Prom agent.",
            search_cmd="curl -sS $GRAFANA/api/search?query=gate-ametrics-cap | jq -c '.[]|{uid,title}'",
            dash_cmd="curl -sS $GRAFANA/api/dashboards/uid/gate-ametrics-cap | jq '.dashboard.panels[0]'",
            query_cmd="curl -sS -G $MIMIR/prometheus/api/v1/query --data-urlencode 'query=sum by (instance) (rate(display_frames_total{service=\"gate-display-svc\"}[5m]))'",
            false_cmd="yq '.limits.max_label_names_per_series' mimir/gate-limits.yaml",
            reload_cmd="kubectl -n mimir rollout restart statefulset/ingester && kubectl -n mimir rollout status statefulset/ingester --timeout=120s",
            requery_cmd="curl -sS -G $MIMIR/prometheus/api/v1/query --data-urlencode 'query=sum by (instance) (rate(display_frames_total{service=\"gate-display-svc\"}[5m]))'",
            denied_cmd="kubectl -n grafana auth can-i patch configmap/adaptive-metrics --as=sre-bot",
            xfail_cmd="printf '%s\\n' '@pytest.mark.xfail(reason=\"adaptive-metrics owned by metrics-platform\")\\ndef test_gate_ametrics():\\n    assert False' > tests/test_gate_ametrics.py",
            wrong_old="max_label_names_per_series: 30",
            wrong_new="max_label_names_per_series: 60",
            wrong2_old="max_label_value_length: 2048",
            wrong2_new="max_label_value_length: 4096",
            ticket_path="tickets/OBS-4436.md",
            ticket_body="OBS-4436: gate-display-svc instance still missing. Adaptive Metrics drop_labels includes instance. Label cap change irrelevant. No RBAC.\n",
            goal="gate-display-svc dashboard gate-ametrics-cap fps by instance is empty. Restore instance.",
            plan="Raise max_label_names_per_series so instance survives ingest.",
            outcome="Cap 60 and longer values; by(instance) still empty. Late drop_labels instance. Handoff OBS-4436.",
            obs1='[{"uid":"gate-ametrics-cap","title":"gate display fps"}]',
            obs2='{"title":"fps by instance","targets":[{"expr":"sum by (instance) (rate(display_frames_total{service=\\"gate-display-svc\\"}[5m]))"}]}',
            obs3='{"status":"success","data":{"result":[]}}',
            obs4="30",
            obs5="mimir/gate-limits.yaml max_label_names_per_series 30 — treated as RCA",
            obs6="same limits file",
            obs7="patched 30→60",
            obs8='statefulset "ingester" successfully rolled out',
            obs9='{"status":"success","data":{"result":[]}}',
            obs10="patched max_label_value_length",
            obs11='{"status":"success","data":{"result":[]}}',
            obs12='grafana/adaptive-metrics/gate.json drop_labels=["instance","pod_template_hash"]',
            obs13="no",
            obs14="wrote tickets/OBS-4436.md",
            obs15="xfail tests/test_gate_ametrics.py",
        ),
    )
)

# r177 Grafana Alloy prometheus.relabel vs Prom agent
MORE.append(
    (
        _ok(
            slug="alloy-relabel-vs-prom-agent",
            service="jetway-plc-svc",
            dashboard_uid="jetway-alloy-3",
            panel="plc up",
            query='up{job="jetway-plc-svc"}',
            lie="Alloy prometheus.relabel keep regex job=jetway-plc drops the series Grafana still scrapes via leftover Prom agent job name jetway_plc",
            false_lead="Prometheus agent mode empty local TSDB",
            config_path="k8s/prom-agent-jetway/statefulset.yaml",
            lie_path="alloy/jetway.alloy",
            truth_name="Alloy live debug scrape",
            reload_name="alloy",
            side="other Alloy jobs still keep",
            surfaces="Grafana Alloy relabel vs Prom agent job name",
            avoided="r160 agent no TSDB; r169 agent rules",
            this_is="Alloy keep regex vs leftover agent job underscore",
            step_note="False lead agent TSDB 4-5; relabel keep 6-8; regex 9-12.",
            search_cmd="curl -sS $GRAFANA/api/search?query=jetway-alloy-3 | jq -c '.[]|{uid,title}'",
            dash_cmd="curl -sS $GRAFANA/api/dashboards/uid/jetway-alloy-3 | jq '.dashboard.panels[0]'",
            query_cmd="curl -sS -G $MIMIR/prometheus/api/v1/query --data-urlencode 'query=up{job=\"jetway-plc-svc\"}'",
            false_cmd="kubectl -n obs get pod prom-agent-jetway-0 -o jsonpath='{.spec.containers[0].args}'",
            truth_cmd="curl -sS http://alloy.obs:12345/debug/prometheus.scrape.jetway | jq '.targets[:2]'",
            confirm_cmd="rg -n 'prometheus.relabel|keep' alloy/jetway.alloy",
            reload_cmd="kubectl -n alloy rollout restart daemonset/alloy && kubectl -n alloy rollout status daemonset/alloy --timeout=90s",
            requery_cmd="curl -sS -G $MIMIR/prometheus/api/v1/query --data-urlencode 'query=up{job=~\"jetway-plc.*\"}'",
            grafana_ok_cmd="curl -sS $GRAFANA/api/ds/query -d @/tmp/jetway-up.json | jq '.results.A.frames[0].data.values'",
            side_cmd="curl -sS -G $MIMIR/prometheus/api/v1/query --data-urlencode 'query=up{job=\"bagtag-print-svc\"}' | jq '.data.result|length'",
            final_cmd="rg 'source_labels|regex' alloy/jetway.alloy",
            patch_old='regex      = "jetway-plc-svc"',
            patch_new='regex      = "jetway[-_]plc[-_]svc"',
            runbook_path="runbooks/jetway-alloy-relabel.md",
            runbook="# jetway-plc-svc Alloy relabel\nAgent job was jetway_plc; Alloy keep required hyphen name. Broaden regex.\nNot agent-mode empty TSDB.\n",
            goal="jetway-plc-svc dashboard jetway-alloy-3 plc up is empty after Alloy cutover. Restore up.",
            plan="Empty up → agent TSDB (false, Grafana uses Mimir) → Alloy keep regex vs underscore job → broaden.",
            outcome="Alloy keep regex matches hyphen and underscore. up=1. Other jobs unchanged.",
            obs1='[{"uid":"jetway-alloy-3","title":"jetway PLC"}]',
            obs2='{"title":"plc up","targets":[{"expr":"up{job=\\"jetway-plc-svc\\"}"}]}',
            obs3='{"status":"success","data":{"result":[]}}',
            obs4='["--enable-feature=agent"]\n# leftover agent exists but Grafana datasource is Mimir',
            obs5="agent still running; not the r160 empty-query plant (Grafana does not hit it)",
            obs6='prometheus.relabel "keep_jetway" { rule { source_labels = ["job"] regex = "jetway-plc-svc" action = "keep" } }',
            obs7='[{"discoveredLabels":{"job":"jetway_plc"},"health":"up"}]\n# scrape works; relabel drops underscore job',
            obs8='regex = "jetway-plc-svc"  # no underscore variant',
            obs9="patched regex jetway[-_]plc[-_]svc",
            obs10='daemonset "alloy" successfully rolled out',
            obs11='{"status":"success","data":{"result":[{"metric":{"job":"jetway_plc"},"value":[1710000600,"1"]}]}}',
            obs12="[[1710000600],[1]]",
            obs13="1",
            obs14="wrote runbooks/jetway-alloy-relabel.md",
            obs15='source_labels = ["job"]\nregex      = "jetway[-_]plc[-_]svc"',
        ),
        _fail(
            slug="alloy-point-grafana-at-agent",
            service="bridge-load-svc",
            dashboard_uid="bridge-alloy-agent",
            panel="bridge up",
            query='up{job="bridge-load-svc"}',
            lie="Pointing Grafana at leftover Prom agent does not restore series Alloy relabel already dropped",
            false_lead="Grafana still querying Prom agent after Alloy cutover",
            config_path="grafana/datasources/prom-bridge.yaml",
            lie_path="alloy/bridge.alloy",
            wrong_path="grafana/datasources/prom-bridge.yaml",
            reload_name="grafana",
            ticket="OBS-4437",
            xfail="tests/test_bridge_alloy.py",
            surfaces="Grafana URL leftover vs Alloy keep drop",
            avoided="r160 as the actual RCA",
            this_is="fail/handoff: retargeted Grafana to agent, series still dropped in Alloy",
            step_note="datasource URL 6-10; still empty 11; late Alloy keep 12; handoff 14-15.",
            next_note="Next: Honeycomb Refinery vs Tempo sampling.",
            search_cmd="curl -sS $GRAFANA/api/search?query=bridge-alloy-agent | jq -c '.[]|{uid,title}'",
            dash_cmd="curl -sS $GRAFANA/api/dashboards/uid/bridge-alloy-agent | jq '.dashboard.panels[0]'",
            query_cmd="curl -sS -G $MIMIR/prometheus/api/v1/query --data-urlencode 'query=up{job=\"bridge-load-svc\"}'",
            false_cmd="cat grafana/datasources/prom-bridge.yaml",
            reload_cmd="kubectl -n grafana rollout restart deploy/grafana && kubectl -n grafana rollout status deploy/grafana --timeout=90s",
            requery_cmd="curl -sS -G http://prom-agent-bridge.obs:9090/api/v1/query --data-urlencode 'query=up{job=\"bridge-load-svc\"}'",
            denied_cmd="kubectl -n alloy auth can-i patch daemonset/alloy --as=sre-bot",
            xfail_cmd="printf '%s\\n' '@pytest.mark.xfail(reason=\"alloy config owned by collector-platform\")\\ndef test_bridge_alloy():\\n    assert False' > tests/test_bridge_alloy.py",
            wrong_old="url: http://mimir-query.obs:8080/prometheus",
            wrong_new="url: http://prom-agent-bridge.obs:9090",
            wrong2_old="isDefault: false",
            wrong2_new="isDefault: true",
            ticket_path="tickets/OBS-4437.md",
            ticket_body="OBS-4437: bridge-load-svc still empty. Alloy keep regex job=bridge-load-svc drops job=bridge_load. Grafana URL change is r160 leftover. No Alloy RBAC.\n",
            goal="bridge-load-svc dashboard bridge-alloy-agent bridge up is empty after Alloy cutover. Restore up.",
            plan="Point Grafana back at Prom agent because Alloy cutover broke queries.",
            outcome="Grafana hits agent (empty TSDB). Late Alloy keep regex vs underscore job. Handoff OBS-4437.",
            obs1='[{"uid":"bridge-alloy-agent","title":"bridge load"}]',
            obs2='{"title":"bridge up","targets":[{"expr":"up{job=\\"bridge-load-svc\\"}"}]}',
            obs3='{"status":"success","data":{"result":[]}}',
            obs4="url: http://mimir-query.obs:8080/prometheus\n# treated as wrong datasource",
            obs5="grafana/datasources/prom-bridge.yaml points at Mimir",
            obs6="same datasource yaml — treated as RCA (r160 clone attempt)",
            obs7="patched url → prom-agent-bridge",
            obs8='deployment "grafana" successfully rolled out',
            obs9='{"status":"success","data":{"result":[]}}\n# agent mode empty',
            obs10="patched isDefault true",
            obs11='{"status":"success","data":{"result":[]}}',
            obs12='alloy/bridge.alloy prometheus.relabel keep regex = "bridge-load-svc"  discovered job=bridge_load',
            obs13="no",
            obs14="wrote tickets/OBS-4437.md",
            obs15="xfail tests/test_bridge_alloy.py",
        ),
    )
)

# r178 Honeycomb Refinery vs Tempo
MORE.append(
    (
        _ok(
            slug="refinery-dynsample-vs-tempo",
            service="pnr-search-svc",
            dashboard_uid="pnr-refinery-6",
            panel="search traces",
            query='{resource.service.name="pnr-search-svc"}',
            lie="Honeycomb Refinery dynsampler Keyed by http.status_code drops 200s so Tempo only has errors; dashboard 'all traces' looks empty",
            false_lead="Tempo metrics-generator filter_policies skip",
            config_path="tempo/pnr-mg.yaml",
            lie_path="refinery/rules.yaml",
            truth_name="Refinery peek sampler log",
            reload_name="refinery",
            side="error traces still in Tempo",
            surfaces="Honeycomb Refinery dynsample vs Tempo",
            avoided="r164 filter_policies skip; tailsampling cache",
            this_is="Refinery keeps only non-200 so Tempo search looks empty",
            step_note="False lead Tempo filter 4-5; Refinery key 6-8; sample all 9-12.",
            search_cmd="curl -sS $GRAFANA/api/search?query=pnr-refinery-6 | jq -c '.[]|{uid,title}'",
            dash_cmd="curl -sS $GRAFANA/api/dashboards/uid/pnr-refinery-6 | jq '.dashboard.panels[0]'",
            query_cmd="curl -sS -G $TEMPO/api/search --data-urlencode 'q={resource.service.name=\"pnr-search-svc\"}' | jq '{n:(.traces|length),status:[.traces[].rootTraceName]}'",
            false_cmd="yq '.metrics_generator.processor.span_metrics.filter_policies' tempo/pnr-mg.yaml",
            truth_cmd="kubectl -n honeycomb logs deploy/refinery --tail=30 | rg 'pnr-search|dynsampler|drop'",
            confirm_cmd="yq '.Samplers.pnr-search-svc' refinery/rules.yaml",
            reload_cmd="kubectl -n honeycomb rollout restart deploy/refinery && kubectl -n honeycomb rollout status deploy/refinery --timeout=90s",
            requery_cmd="curl -sS -G $TEMPO/api/search --data-urlencode 'q={resource.service.name=\"pnr-search-svc\"}' | jq '.traces|length'",
            grafana_ok_cmd="curl -sS $GRAFANA/api/ds/query -d @/tmp/pnr-tr.json | jq '.results.A.frames[0].schema'",
            side_cmd="curl -sS -G $TEMPO/api/search --data-urlencode 'q={resource.service.name=\"pnr-search-svc\" && status=error}' | jq '.traces|length'",
            final_cmd="yq '.Samplers.pnr-search-svc.SampleRate' refinery/rules.yaml",
            patch_old="Sampler: EMADynamicSampler\n      FieldList: [http.status_code]\n      GoalSampleRate: 1",
            patch_new="Sampler: DeterministicSampler\n      SampleRate: 1",
            runbook_path="runbooks/pnr-refinery-tempo.md",
            runbook="# pnr-search-svc Refinery vs Tempo\nEMADynamicSampler keyed on status kept only 5xx. Use DeterministicSampler 1 for this service.\nNot Tempo filter_policies.\n",
            goal="pnr-search-svc dashboard pnr-refinery-6 search traces is nearly empty. Errors exist. Fix the sampler lie.",
            plan="Few traces → Tempo filter_policies (none) → Refinery dynsample on status → sample all.",
            outcome="DeterministicSampler 1. Tempo search 120 traces. Errors still present.",
            obs1='[{"uid":"pnr-refinery-6","title":"PNR search traces"}]',
            obs2='{"title":"search traces","targets":[{"query":"{resource.service.name=\\"pnr-search-svc\\"}"}]}',
            obs3='{"n":3,"status":["GET /search","GET /search","GET /search"]}\n# only 3 error traces',
            obs4="null\n# no filter_policies on this tenant",
            obs5="tempo/pnr-mg.yaml no skip — not r164",
            obs6="Sampler: EMADynamicSampler\nFieldList: [http.status_code]\nGoalSampleRate: 1  # 1 kept per status key; 200s collapsed",
            obs7='msg="dropping trace" sampler=EMADynamic key=200 service=pnr-search-svc',
            obs8="EMADynamicSampler FieldList http.status_code GoalSampleRate 1",
            obs9="patched DeterministicSampler SampleRate 1",
            obs10='deployment "refinery" successfully rolled out',
            obs11="120",
            obs12='{"name":"Traces"}',
            obs13="3",
            obs14="wrote runbooks/pnr-refinery-tempo.md",
            obs15="1",
        ),
        _fail(
            slug="refinery-tempo-filter-copy",
            service="fare-rules-svc",
            dashboard_uid="fare-refinery-skip",
            panel="rules traces",
            query='{resource.service.name="fare-rules-svc"}',
            lie="Removing Tempo filter_policies does not undo Refinery dynsample keyed on http.route",
            false_lead="Tempo metrics-generator filter_policies skip",
            config_path="tempo/fare-mg.yaml",
            lie_path="refinery/fare-rules.yaml",
            wrong_path="tempo/fare-mg.yaml",
            reload_name="tempo-metrics-generator",
            ticket="OBS-4438",
            xfail="tests/test_fare_refinery.py",
            surfaces="Tempo filter leftover vs Refinery route sampler",
            avoided="r164 as actual RCA",
            this_is="fail/handoff: cleared Tempo filter, Refinery still drops 200s",
            step_note="filter_policies 6-10; still 2 traces 11; late Refinery 12; handoff 14-15.",
            next_note="Next: Jaeger query vs Tempo query-frontend.",
            search_cmd="curl -sS $GRAFANA/api/search?query=fare-refinery-skip | jq -c '.[]|{uid,title}'",
            dash_cmd="curl -sS $GRAFANA/api/dashboards/uid/fare-refinery-skip | jq '.dashboard.panels[0]'",
            query_cmd="curl -sS -G $TEMPO/api/search --data-urlencode 'q={resource.service.name=\"fare-rules-svc\"}' | jq '.traces|length'",
            false_cmd="yq '.metrics_generator.processor.span_metrics.filter_policies' tempo/fare-mg.yaml",
            reload_cmd="kubectl -n tempo rollout restart deploy/metrics-generator && kubectl -n tempo rollout status deploy/metrics-generator --timeout=90s",
            requery_cmd="curl -sS -G $TEMPO/api/search --data-urlencode 'q={resource.service.name=\"fare-rules-svc\"}' | jq '.traces|length'",
            denied_cmd="kubectl -n honeycomb auth can-i patch deploy/refinery --as=sre-bot",
            xfail_cmd="printf '%s\\n' '@pytest.mark.xfail(reason=\"refinery owned by tracing-platform\")\\ndef test_fare_refinery():\\n    assert False' > tests/test_fare_refinery.py",
            wrong_old="filter_policies:\n        - include:\n            match_type: strict\n            attributes:\n              - key: http.status_code\n                value: \"200\"",
            wrong_new="filter_policies: []",
            wrong2_old="enable_target_info: false",
            wrong2_new="enable_target_info: true",
            ticket_path="tickets/OBS-4438.md",
            ticket_body="OBS-4438: fare-rules-svc still 2 traces. Refinery EMADynamicSampler FieldList http.route. Tempo filter was a red herring. No Refinery RBAC.\n",
            goal="fare-rules-svc dashboard fare-refinery-skip rules traces nearly empty. Restore traces.",
            plan="Clear Tempo filter_policies so 200s generate and appear.",
            outcome="filter_policies []. Still 2 traces. Late Refinery http.route sampler. Handoff OBS-4438.",
            obs1='[{"uid":"fare-refinery-skip","title":"fare rules traces"}]',
            obs2='{"title":"rules traces","targets":[{"query":"{resource.service.name=\\"fare-rules-svc\\"}"}]}',
            obs3="2",
            obs4='include http.status_code=200  # treated as skip of others, r164 clone',
            obs5="tempo/fare-mg.yaml has filter_policies",
            obs6="same tempo yaml — treated as RCA",
            obs7="patched filter_policies []",
            obs8='deployment "metrics-generator" successfully rolled out',
            obs9="2",
            obs10="patched enable_target_info",
            obs11="2",
            obs12="refinery/fare-rules.yaml Sampler EMADynamicSampler FieldList [http.route] GoalSampleRate 1",
            obs13="no",
            obs14="wrote tickets/OBS-4438.md",
            obs15="xfail tests/test_fare_refinery.py",
        ),
    )
)

# r179 Jaeger query vs Tempo query-frontend
MORE.append(
    (
        _ok(
            slug="jaeger-query-vs-tempo-qf",
            service="ssr-seat-svc",
            dashboard_uid="ssr-jaeger-7",
            panel="seat traces",
            query="service=ssr-seat-svc",
            lie="Grafana Jaeger datasource still hits jaeger-query while traces now live only in Tempo; jaeger-query storage is empty cassandra",
            false_lead="Tempo query-frontend max_outstanding too low",
            config_path="tempo/query-frontend.yaml",
            lie_path="grafana/datasources/jaeger-ssr.yaml",
            truth_name="Tempo TraceQL",
            reload_name="grafana",
            side="Tempo Explore still works for other services",
            surfaces="Jaeger query vs Tempo query-frontend",
            avoided="r162 Sentry event_id; Tempo missing dim",
            this_is="Grafana Jaeger datasource vs Tempo-only storage",
            step_note="False lead qf outstanding 4-5; jaeger cassandra empty 6-8; switch Tempo 9-12.",
            search_cmd="curl -sS $GRAFANA/api/search?query=ssr-jaeger-7 | jq -c '.[]|{uid,title}'",
            dash_cmd="curl -sS $GRAFANA/api/dashboards/uid/ssr-jaeger-7 | jq '.dashboard.panels[0].datasource'",
            query_cmd="curl -sS 'http://jaeger-query.obs:16686/api/traces?service=ssr-seat-svc' | jq '.data|length'",
            false_cmd="yq '.query_frontend.max_outstanding_per_tenant' tempo/query-frontend.yaml",
            truth_cmd="curl -sS -G $TEMPO/api/search --data-urlencode 'q={resource.service.name=\"ssr-seat-svc\"}' | jq '.traces|length'",
            confirm_cmd="cat grafana/datasources/jaeger-ssr.yaml",
            reload_cmd="kubectl -n grafana rollout restart deploy/grafana && kubectl -n grafana rollout status deploy/grafana --timeout=90s",
            requery_cmd="curl -sS $GRAFANA/api/ds/query -d @/tmp/ssr-tr.json | jq '.results.A.frames[0].schema'",
            grafana_ok_cmd="curl -sS $GRAFANA/api/datasources/uid/tempo-ssr | jq '{type,url}'",
            side_cmd="curl -sS -G $TEMPO/api/search --data-urlencode 'q={resource.service.name=\"ssr-meal-svc\"}' | jq '.traces|length'",
            final_cmd="jq '.dashboard.panels[0].datasource' grafana/dashboards/ssr-jaeger-7.json",
            patch_old="type: jaeger\n    url: http://jaeger-query.obs:16686",
            patch_new="type: tempo\n    url: http://tempo-query.obs:3200\n    uid: tempo-ssr",
            runbook_path="runbooks/ssr-jaeger-tempo.md",
            runbook="# ssr-seat-svc Jaeger vs Tempo\nCassandra jaeger-query is empty after collector cutover to Tempo. Point Grafana at Tempo.\n",
            goal="ssr-seat-svc dashboard ssr-jaeger-7 seat traces is empty after the Tempo cutover. Restore the panel.",
            plan="Jaeger API empty → query-frontend outstanding (false) → empty cassandra → Tempo datasource.",
            outcome="Panel uses tempo-ssr. Trace schema renders. Other Tempo services unchanged.",
            obs1='[{"uid":"ssr-jaeger-7","title":"SSR seat traces"}]',
            obs2='{"type":"jaeger","uid":"jaeger-ssr"}',
            obs3="0",
            obs4="2000\n# not saturated",
            obs5="max_outstanding_per_tenant 2000 — not the lie",
            obs6="type: jaeger\nurl: http://jaeger-query.obs:16686",
            obs7="48\n# Tempo has the traces",
            obs8="jaeger-query storage cassandra keyspace jaeger_v1 empty for ssr-seat-svc",
            obs9="patched datasource type jaeger→tempo url tempo-query",
            obs10='deployment "grafana" successfully rolled out',
            obs11='{"name":"Trace"}',
            obs12='{"type":"tempo","url":"http://tempo-query.obs:3200"}',
            obs13="40",
            obs14="wrote runbooks/ssr-jaeger-tempo.md",
            obs15='{"type":"tempo","uid":"tempo-ssr"}',
        ),
        _fail(
            slug="jaeger-raise-tempo-outstanding",
            service="ssr-wheelchair-svc",
            dashboard_uid="ssr-jaeger-qf",
            panel="wheelchair traces",
            query="service=ssr-wheelchair-svc",
            lie="Raising Tempo query-frontend max_outstanding does not fill a Grafana Jaeger datasource backed by empty cassandra",
            false_lead="Tempo query-frontend max_outstanding too low",
            config_path="tempo/ssr-qf.yaml",
            lie_path="grafana/datasources/jaeger-wheel.yaml",
            wrong_path="tempo/ssr-qf.yaml",
            reload_name="tempo-query-frontend",
            ticket="OBS-4439",
            xfail="tests/test_ssr_jaeger.py",
            surfaces="qf outstanding leftover vs Jaeger empty storage",
            avoided="Tempo missing dim; r162",
            this_is="fail/handoff: raised qf outstanding, Jaeger still 0",
            step_note="max_outstanding 6-10; still 0 11; late jaeger yaml 12; handoff 14-15.",
            next_note="Next: Elastic APM transaction.name vs OTel span.name.",
            search_cmd="curl -sS $GRAFANA/api/search?query=ssr-jaeger-qf | jq -c '.[]|{uid,title}'",
            dash_cmd="curl -sS $GRAFANA/api/dashboards/uid/ssr-jaeger-qf | jq '.dashboard.panels[0]'",
            query_cmd="curl -sS 'http://jaeger-query.obs:16686/api/traces?service=ssr-wheelchair-svc' | jq '.data|length'",
            false_cmd="yq '.query_frontend.max_outstanding_per_tenant' tempo/ssr-qf.yaml",
            reload_cmd="kubectl -n tempo rollout restart deploy/query-frontend && kubectl -n tempo rollout status deploy/query-frontend --timeout=90s",
            requery_cmd="curl -sS 'http://jaeger-query.obs:16686/api/traces?service=ssr-wheelchair-svc' | jq '.data|length'",
            denied_cmd="kubectl -n grafana auth can-i patch configmap/grafana-datasources --as=sre-bot",
            xfail_cmd="printf '%s\\n' '@pytest.mark.xfail(reason=\"grafana datasource owned by ssr-obs\")\\ndef test_ssr_jaeger():\\n    assert False' > tests/test_ssr_jaeger.py",
            wrong_old="max_outstanding_per_tenant: 2000",
            wrong_new="max_outstanding_per_tenant: 8000",
            wrong2_old="max_retries: 2",
            wrong2_new="max_retries: 8",
            ticket_path="tickets/OBS-4439.md",
            ticket_body="OBS-4439: ssr-wheelchair-svc Jaeger still 0. Traces are in Tempo. Need Grafana datasource type tempo. No RBAC.\n",
            goal="ssr-wheelchair-svc dashboard ssr-jaeger-qf wheelchair traces is empty. Restore traces.",
            plan="Raise Tempo query-frontend outstanding so Jaeger-through-Tempo works.",
            outcome="max_outstanding 8000; Jaeger API still 0. Late jaeger-wheel.yaml. Handoff OBS-4439.",
            obs1='[{"uid":"ssr-jaeger-qf","title":"SSR wheelchair"}]',
            obs2='{"title":"wheelchair traces","datasource":{"type":"jaeger","uid":"jaeger-wheel"}}',
            obs3="0",
            obs4="2000",
            obs5="tempo/ssr-qf.yaml max_outstanding 2000 — treated as RCA",
            obs6="same qf yaml",
            obs7="patched 2000→8000",
            obs8='deployment "query-frontend" successfully rolled out',
            obs9="0",
            obs10="patched max_retries 2→8",
            obs11="0",
            obs12="grafana/datasources/jaeger-wheel.yaml type: jaeger url: http://jaeger-query.obs:16686",
            obs13="no",
            obs14="wrote tickets/OBS-4439.md",
            obs15="xfail tests/test_ssr_jaeger.py",
        ),
    )
)

# r180 Elastic APM transaction.name vs OTel span.name
MORE.append(
    (
        _ok(
            slug="elastic-txn-vs-otel-span",
            service="ancillary-shop-svc",
            dashboard_uid="ancillary-apm-5",
            panel="shop traces",
            query='{span.name="GET /shop/offers"}',
            lie="Elastic APM transaction.name stays GET /shop/offers while OTel span.name is shop.offers after spanmetrics connector; Grafana Tempo panel uses Elastic name",
            false_lead="OTel spanmetrics connector metric rename",
            config_path="otelcol/ancillary-collector.yaml",
            lie_path="grafana/dashboards/ancillary-apm-5.json",
            truth_name="Tempo span names",
            reload_name="grafana",
            side="Elastic APM UI still shows transaction.name",
            surfaces="Elastic APM transaction.name vs OTel span.name",
            avoided="r166 connector vs processor names; r163 DD tid",
            this_is="Elastic transaction.name vs OTel span.name join",
            step_note="False lead connector metric 4-5; span.name 6-8; panel query 9-12.",
            search_cmd="curl -sS $GRAFANA/api/search?query=ancillary-apm-5 | jq -c '.[]|{uid,title}'",
            dash_cmd="curl -sS $GRAFANA/api/dashboards/uid/ancillary-apm-5 | jq '.dashboard.panels[0].targets'",
            query_cmd="curl -sS -G $TEMPO/api/search --data-urlencode 'q={span.name=\"GET /shop/offers\"}' | jq '.traces|length'",
            false_cmd="yq '.connectors.spanmetrics' otelcol/ancillary-collector.yaml",
            truth_cmd="curl -sS -G $TEMPO/api/search --data-urlencode 'q={resource.service.name=\"ancillary-shop-svc\"}' | jq '[.traces[:3][].rootTraceName]'",
            confirm_cmd="jq '.dashboard.panels[0].targets[0].query' grafana/dashboards/ancillary-apm-5.json",
            reload_cmd="kubectl -n grafana rollout restart deploy/grafana && kubectl -n grafana rollout status deploy/grafana --timeout=90s",
            requery_cmd="curl -sS -G $TEMPO/api/search --data-urlencode 'q={span.name=\"shop.offers\"}' | jq '.traces|length'",
            grafana_ok_cmd="curl -sS $GRAFANA/api/ds/query -d @/tmp/anc.json | jq '.results.A.frames[0].schema'",
            side_cmd="curl -sS $ELASTIC/api/apm/services/ancillary-shop-svc/transactions | jq '.[0].name'",
            final_cmd="jq '.dashboard.panels[0].targets[0].query' grafana/dashboards/ancillary-apm-5.json",
            patch_old='{span.name="GET /shop/offers"}',
            patch_new='{span.name="shop.offers"}',
            runbook_path="runbooks/ancillary-elastic-span.md",
            runbook="# ancillary-shop-svc Elastic vs OTel names\nTempo stores OTel span.name shop.offers. Elastic UI keeps GET /shop/offers. Do not mix.\nNot a connector metric rename.\n",
            goal="ancillary-shop-svc dashboard ancillary-apm-5 shop traces is empty. Elastic APM shows transactions. Fix the name lie.",
            plan="Empty TraceQL → connector names (metrics exist) → Tempo rootTraceName shop.offers → patch panel.",
            outcome="Panel queries span.name=shop.offers. 64 traces. Elastic UI name unchanged.",
            obs1='[{"uid":"ancillary-apm-5","title":"ancillary shop traces"}]',
            obs2='[{"query":"{span.name=\\"GET /shop/offers\\"}"}]',
            obs3="0",
            obs4="namespace: traces.span.metrics\n# connector present; metrics not the panel query",
            obs5="spanmetrics connector exists but panel is TraceQL not PromQL — not r166",
            obs6='"{span.name=\\"GET /shop/offers\\"}"',
            obs7='["shop.offers","shop.offers","shop.checkout"]',
            obs8="panel uses Elastic transaction.name",
            obs9="patched span.name GET /shop/offers → shop.offers",
            obs10='deployment "grafana" successfully rolled out',
            obs11="64",
            obs12='{"name":"Traces"}',
            obs13='"GET /shop/offers"',
            obs14="wrote runbooks/ancillary-elastic-span.md",
            obs15='"{span.name=\\"shop.offers\\"}"',
        ),
        _fail(
            slug="elastic-reenable-spanmetrics-proc",
            service="lounge-pass-svc",
            dashboard_uid="lounge-apm-proc",
            panel="lounge traces",
            query='{span.name="POST /lounge/pass"}',
            lie="Re-enabling spanmetrics processor does not restore Elastic transaction.name as Tempo span.name",
            false_lead="spanmetrics connector hid the Elastic names",
            config_path="otelcol/lounge-collector.yaml",
            lie_path="grafana/dashboards/lounge-apm-proc.json",
            wrong_path="otelcol/lounge-collector.yaml",
            reload_name="otelcol-lounge",
            ticket="OBS-4440",
            xfail="tests/test_lounge_elastic.py",
            surfaces="processor leftover vs Elastic vs OTel names",
            avoided="r166 as actual RCA",
            this_is="fail/handoff: re-enabled processor, TraceQL still uses Elastic name",
            step_note="processor 6-10; still 0 11; late dashboard 12; handoff 14-15.",
            next_note="Next: Pyroscope musl symbolizer skip, not max_profile_size.",
            search_cmd="curl -sS $GRAFANA/api/search?query=lounge-apm-proc | jq -c '.[]|{uid,title}'",
            dash_cmd="curl -sS $GRAFANA/api/dashboards/uid/lounge-apm-proc | jq '.dashboard.panels[0]'",
            query_cmd="curl -sS -G $TEMPO/api/search --data-urlencode 'q={span.name=\"POST /lounge/pass\"}' | jq '.traces|length'",
            false_cmd="yq '.connectors,.processors' otelcol/lounge-collector.yaml",
            reload_cmd="kubectl -n lounge rollout restart deploy/otelcol-lounge && kubectl -n lounge rollout status deploy/otelcol-lounge --timeout=90s",
            requery_cmd="curl -sS -G $TEMPO/api/search --data-urlencode 'q={span.name=\"POST /lounge/pass\"}' | jq '.traces|length'",
            denied_cmd="kubectl -n grafana auth can-i patch configmap/grafana-dashboards --as=sre-bot",
            xfail_cmd="printf '%s\\n' '@pytest.mark.xfail(reason=\"lounge dashboard owned by loyalty-obs\")\\ndef test_lounge_elastic():\\n    assert False' > tests/test_lounge_elastic.py",
            wrong_old="processors:\n  batch: {}",
            wrong_new="processors:\n  batch: {}\n  spanmetrics:\n    metrics_exporter: prometheus",
            wrong2_old="exporters: [otlp/tempo, spanmetrics]",
            wrong2_new="exporters: [otlp/tempo, spanmetrics]\n        processors: [spanmetrics, batch]",
            ticket_path="tickets/OBS-4440.md",
            ticket_body="OBS-4440: lounge-pass-svc Tempo span.name is lounge.pass not POST /lounge/pass. Processor re-enable is r166 leftover. Need dashboard query patch. No RBAC.\n",
            goal="lounge-pass-svc dashboard lounge-apm-proc lounge traces is empty. Restore traces.",
            plan="Re-enable spanmetrics processor so Elastic names return.",
            outcome="Processor re-enabled; TraceQL still 0. Late dashboard Elastic name. Handoff OBS-4440.",
            obs1='[{"uid":"lounge-apm-proc","title":"lounge pass traces"}]',
            obs2='{"title":"lounge traces","targets":[{"query":"{span.name=\\"POST /lounge/pass\\"}"}]}',
            obs3="0",
            obs4="connectors.spanmetrics present; processors batch only — treated as r166",
            obs5="otelcol/lounge-collector.yaml",
            obs6="same collector — treated as RCA",
            obs7="patched added spanmetrics processor",
            obs8='deployment "otelcol-lounge" successfully rolled out',
            obs9="0",
            obs10="patched traces processors include spanmetrics",
            obs11="0",
            obs12="grafana/dashboards/lounge-apm-proc.json query={span.name=\"POST /lounge/pass\"}; Tempo rootTraceName lounge.pass",
            obs13="no",
            obs14="wrote tickets/OBS-4440.md",
            obs15="xfail tests/test_lounge_elastic.py",
        ),
    )
)

# r181 Pyroscope musl symbolizer skip (NOT max size, NOT eBPF mix)
MORE.append(
    (
        _ok(
            slug="pyro-musl-buildid-skip",
            service="cargo-manifest-svc",
            dashboard_uid="cargo-pyro-sym-8",
            panel="CPU flame",
            query='process_cpu:cpu:nanoseconds{service_name="cargo-manifest-svc"}',
            lie="Pyroscope symbolizer skip_missing_buildid true drops musl Go binary with empty Build-ID so flame is unknown",
            false_lead="max_profile_size dropping the pprof",
            config_path="pyroscope/cargo-values.yaml",
            lie_path="pyroscope/cargo-values.yaml",
            truth_name="symbolizer skip log",
            reload_name="pyroscope-querier",
            side="glibc services still symbolize",
            surfaces="Pyroscope musl Build-ID skip vs max_profile_size",
            avoided="r167 max_profile_size; eBPF+Java mix; godeltaprof",
            this_is="musl empty Build-ID symbolizer skip",
            step_note="False lead max size 4-5; skip_missing_buildid 6-8; disable skip 9-12.",
            search_cmd="curl -sS $GRAFANA/api/search?query=cargo-pyro-sym-8 | jq -c '.[]|{uid,title}'",
            dash_cmd="curl -sS $GRAFANA/api/dashboards/uid/cargo-pyro-sym-8 | jq '.dashboard.panels[0]'",
            query_cmd="curl -sS -G $PYRO/pyroscope/render --data-urlencode 'query=process_cpu:cpu:nanoseconds{service_name=\"cargo-manifest-svc\"}' | jq '{names:(.flamebearer.names[:4]),n:(.flamebearer.names|length)}'",
            false_cmd="yq '.pyroscope.structuredConfig.ingestion.max_profile_size_bytes' pyroscope/cargo-values.yaml",
            truth_cmd="kubectl -n pyro logs deploy/pyroscope-querier --tail=20 | rg 'build-id|symbol|cargo-manifest'",
            confirm_cmd="yq '.pyroscope.structuredConfig.querier.symbolizer' pyroscope/cargo-values.yaml",
            reload_cmd="kubectl -n pyro rollout restart deploy/pyroscope-querier && kubectl -n pyro rollout status deploy/pyroscope-querier --timeout=90s",
            requery_cmd="curl -sS -G $PYRO/pyroscope/render --data-urlencode 'query=process_cpu:cpu:nanoseconds{service_name=\"cargo-manifest-svc\"}' | jq '{n:(.flamebearer.names|length),sample:(.flamebearer.names[2])}'",
            grafana_ok_cmd="curl -sS $GRAFANA/api/ds/query -d @/tmp/cargo-cpu.json | jq '.results.A.frames[0].schema'",
            side_cmd="curl -sS -G $PYRO/pyroscope/render --data-urlencode 'query=process_cpu:cpu:nanoseconds{service_name=\"checkin-core-svc\"}' | jq '.flamebearer.names[2]'",
            final_cmd="yq '.pyroscope.structuredConfig.querier.symbolizer.skip_missing_buildid' pyroscope/cargo-values.yaml",
            patch_old="skip_missing_buildid: true",
            patch_new="skip_missing_buildid: false\n        use_debuginfod: true",
            runbook_path="runbooks/cargo-pyro-musl.md",
            runbook="# cargo-manifest-svc musl Build-ID\nmusl Go binaries often have empty Build-ID. skip_missing_buildid drops all frames to unknown.\nNot max_profile_size.\n",
            goal="cargo-manifest-svc dashboard cargo-pyro-sym-8 CPU flame is only unknown. Profiles ingest. Fix the symbolizer skip.",
            plan="unknown frames → max_profile_size (16MiB, not dropping) → skip_missing_buildid → disable skip.",
            outcome="skip_missing_buildid false. Flame shows cargo/manifest.go. glibc service still named.",
            obs1='[{"uid":"cargo-pyro-sym-8","title":"cargo manifest CPU"}]',
            obs2='{"title":"CPU flame","datasource":"pyroscope-cargo"}',
            obs3='{"names":["unknown","total"],"n":2}',
            obs4="16777216\n# 16MiB; profiles 1.1MiB — not r167",
            obs5="max_profile_size 16MiB not the drop",
            obs6="symbolizer:\n  skip_missing_buildid: true",
            obs7='msg="skip symbolize missing build-id" service=cargo-manifest-svc build_id="" libc=musl',
            obs8="skip_missing_buildid: true",
            obs9="patched skip_missing_buildid false; use_debuginfod true",
            obs10='deployment "pyroscope-querier" successfully rolled out',
            obs11='{"n":140,"sample":"cargo/manifest.go:scan"}',
            obs12='{"name":"Flamegraph"}',
            obs13='"checkin/main.go:serve"',
            obs14="wrote runbooks/cargo-pyro-musl.md",
            obs15="false",
        ),
        _fail(
            slug="pyro-musl-raise-size-again",
            service="uld-planner-svc",
            dashboard_uid="uld-pyro-size",
            panel="uld CPU",
            query='process_cpu:cpu:nanoseconds{service_name="uld-planner-svc"}',
            lie="Raising max_profile_size again does not symbolize musl empty Build-ID frames",
            false_lead="max_profile_size still too small",
            config_path="pyroscope/uld-values.yaml",
            lie_path="pyroscope/uld-values.yaml",
            wrong_path="pyroscope/uld-values.yaml",
            reload_name="pyroscope-distributor",
            ticket="OBS-4441",
            xfail="tests/test_uld_pyro_sym.py",
            surfaces="size leftover vs musl Build-ID skip",
            avoided="r167 as actual RCA",
            this_is="fail/handoff: bigger size, flame still unknown",
            step_note="max size 6-10; still unknown 11; late symbolizer 12; handoff 14-15.",
            next_note="Next: Grafana IRM heartbeat vs AM wait.",
            search_cmd="curl -sS $GRAFANA/api/search?query=uld-pyro-size | jq -c '.[]|{uid,title}'",
            dash_cmd="curl -sS $GRAFANA/api/dashboards/uid/uld-pyro-size | jq '.dashboard.panels[0]'",
            query_cmd="curl -sS -G $PYRO/pyroscope/render --data-urlencode 'query=process_cpu:cpu:nanoseconds{service_name=\"uld-planner-svc\"}' | jq '.flamebearer.names'",
            false_cmd="yq '.pyroscope.structuredConfig.ingestion.max_profile_size_bytes' pyroscope/uld-values.yaml",
            reload_cmd="kubectl -n pyro rollout restart deploy/pyroscope-distributor && kubectl -n pyro rollout status deploy/pyroscope-distributor --timeout=90s",
            requery_cmd="curl -sS -G $PYRO/pyroscope/render --data-urlencode 'query=process_cpu:cpu:nanoseconds{service_name=\"uld-planner-svc\"}' | jq '.flamebearer.names'",
            denied_cmd="kubectl -n pyro auth can-i patch deploy/pyroscope-querier --as=sre-bot",
            xfail_cmd="printf '%s\\n' '@pytest.mark.xfail(reason=\"pyroscope symbolizer owned by profiling-platform\")\\ndef test_uld_pyro_sym():\\n    assert False' > tests/test_uld_pyro_sym.py",
            wrong_old="max_profile_size_bytes: 16777216",
            wrong_new="max_profile_size_bytes: 33554432",
            wrong2_old="pprof_strip: true",
            wrong2_new="pprof_strip: false",
            ticket_path="tickets/OBS-4441.md",
            ticket_body="OBS-4441: uld-planner-svc flame still unknown. skip_missing_buildid=true musl empty Build-ID. Size bump is r167 leftover. No querier RBAC.\n",
            goal="uld-planner-svc dashboard uld-pyro-size CPU is unknown. Restore symbols.",
            plan="Raise max_profile_size so the musl pprof is not stripped.",
            outcome="32MiB and pprof_strip false; names still unknown. Late skip_missing_buildid. Handoff OBS-4441.",
            obs1='[{"uid":"uld-pyro-size","title":"ULD planner CPU"}]',
            obs2='{"title":"uld CPU","datasource":"pyroscope-uld"}',
            obs3='["unknown","total"]',
            obs4="16777216",
            obs5="pyroscope/uld-values.yaml size 16MiB — treated as r167",
            obs6="same values — treated as RCA",
            obs7="patched 16MiB→32MiB",
            obs8='deployment "pyroscope-distributor" successfully rolled out',
            obs9='["unknown","total"]',
            obs10="patched pprof_strip false",
            obs11='["unknown","total"]',
            obs12="querier.symbolizer.skip_missing_buildid=true  logs: skip symbolize missing build-id libc=musl",
            obs13="no",
            obs14="wrote tickets/OBS-4441.md",
            obs15="xfail tests/test_uld_pyro_sym.py",
        ),
    )
)

# r182 Grafana IRM heartbeat vs AM wait (third IRM plant)
MORE.append(
    (
        _ok(
            slug="irm-heartbeat-vs-am-wait",
            service="deice-queue-svc",
            dashboard_uid="deice-irm-hb-9",
            panel="heartbeat gaps",
            query='oncall_heartbeat_failed{service="deice-queue-svc"}',
            lie="Grafana IRM heartbeat integration pages on missed POST while AM group_wait never sees a firing alert because no Grafana rule exists",
            false_lead="IRM wait vs AM group_wait mismatch",
            config_path="helm/grafana-irm/deice-chain.yaml",
            lie_path="helm/grafana-irm/deice-heartbeat.yaml",
            truth_name="IRM heartbeat last_ok",
            reload_name="grafana-irm",
            side="AM routes for deice still quiet",
            surfaces="Grafana IRM heartbeat vs AM wait",
            avoided="r159 group_by silence; r168 wait vs group_wait; AM inhibit",
            this_is="IRM heartbeat miss pages without an AM alert",
            step_note="False lead IRM wait 4-5; heartbeat endpoint 6-8; align interval 9-12.",
            search_cmd="curl -sS $GRAFANA/api/search?query=deice-irm-hb-9 | jq -c '.[]|{uid,title}'",
            dash_cmd="curl -sS $GRAFANA/api/dashboards/uid/deice-irm-hb-9 | jq '.dashboard.panels[0]'",
            query_cmd="curl -sS -G $MIMIR/prometheus/api/v1/query --data-urlencode 'query=oncall_heartbeat_failed{service=\"deice-queue-svc\"}'",
            false_cmd="yq '.escalation.wait,.grafana_rule.for' helm/grafana-irm/deice-chain.yaml",
            truth_cmd="curl -sS $IRM/api/v1/heartbeats/deice-queue | jq '{last_ok,interval,failed}'",
            confirm_cmd="cat helm/grafana-irm/deice-heartbeat.yaml",
            reload_cmd="kubectl -n irm rollout restart deploy/grafana-oncall && kubectl -n irm rollout status deploy/grafana-oncall --timeout=90s",
            requery_cmd="curl -sS -G $MIMIR/prometheus/api/v1/query --data-urlencode 'query=oncall_heartbeat_failed{service=\"deice-queue-svc\"}'",
            grafana_ok_cmd="curl -sS $GRAFANA/api/ds/query -d @/tmp/deice-hb.json | jq '.results.A.frames[0].data.values'",
            side_cmd="amtool query --alertmanager.url=$AM service=deice-queue-svc | jq 'length'",
            final_cmd="yq '.heartbeat.interval,.heartbeat.grace' helm/grafana-irm/deice-heartbeat.yaml",
            patch_old="interval: 30s\n  grace: 0s",
            patch_new="interval: 5m\n  grace: 2m",
            runbook_path="runbooks/deice-irm-heartbeat.md",
            runbook="# deice-queue-svc IRM heartbeat\nHeartbeat interval 30s/grace 0 raced the 1m cron POST. Not wait vs group_wait and not silences.\n",
            goal="deice-queue-svc dashboard deice-irm-hb-9 heartbeat gaps page every minute while AM is quiet. Stop the false pages.",
            plan="Pages with AM quiet → wait vs group_wait (already aligned) → heartbeat interval/grace → widen.",
            outcome="Heartbeat interval 5m grace 2m. Gaps 0. AM still 0 fires.",
            obs1='[{"uid":"deice-irm-hb-9","title":"deice heartbeat"}]',
            obs2='{"title":"heartbeat gaps","targets":[{"expr":"oncall_heartbeat_failed{service=\\"deice-queue-svc\\"}"}]}',
            obs3='{"status":"success","data":{"result":[{"value":[1710000000,"12"]}]}}',
            obs4="30s\n1m\n# already aligned with AM group_wait — not r168",
            obs5="escalation wait 30s matches AM; not the wait plant",
            obs6="heartbeat:\n  endpoint: /integrations/heartbeat/deice-queue\n  interval: 30s\n  grace: 0s",
            obs7='{"last_ok":"12:00:58Z","interval":"30s","failed":true}\n# cron POST every 60s misses 30s interval',
            obs8="interval 30s grace 0s vs cron 60s",
            obs9="patched interval 5m grace 2m",
            obs10='deployment "grafana-oncall" successfully rolled out',
            obs11='{"status":"success","data":{"result":[{"value":[1710000600,"0"]}]}}',
            obs12="[[1710000600],[0]]",
            obs13="0",
            obs14="wrote runbooks/deice-irm-heartbeat.md",
            obs15="5m\n2m",
        ),
        _fail(
            slug="irm-heartbeat-patch-groupwait",
            service="hold-bag-svc",
            dashboard_uid="holdbag-irm-hb",
            panel="hb gaps",
            query='oncall_heartbeat_failed{service="hold-bag-svc"}',
            lie="Lengthening AM group_wait does not stop IRM heartbeat misses which never create AM alerts",
            false_lead="IRM wait vs AM group_wait",
            config_path="helm/alertmanager/holdbag-route.yaml",
            lie_path="helm/grafana-irm/holdbag-heartbeat.yaml",
            wrong_path="helm/alertmanager/holdbag-route.yaml",
            reload_name="alertmanager",
            ticket="OBS-4442",
            xfail="tests/test_holdbag_hb.py",
            surfaces="AM group_wait leftover vs IRM heartbeat",
            avoided="r168 as actual RCA",
            this_is="fail/handoff: longer AM wait, heartbeat still pages",
            step_note="group_wait 6-10; still 8 fails 11; late heartbeat yaml 12; handoff 14-15.",
            next_note="Catalog next: Beyla vs OTel, New Relic vs Tempo, Loki pattern vs bloom.",
            search_cmd="curl -sS $GRAFANA/api/search?query=holdbag-irm-hb | jq -c '.[]|{uid,title}'",
            dash_cmd="curl -sS $GRAFANA/api/dashboards/uid/holdbag-irm-hb | jq '.dashboard.panels[0]'",
            query_cmd="curl -sS -G $MIMIR/prometheus/api/v1/query --data-urlencode 'query=oncall_heartbeat_failed{service=\"hold-bag-svc\"}'",
            false_cmd="yq '.group_wait' helm/alertmanager/holdbag-route.yaml",
            reload_cmd="kubectl -n am rollout restart statefulset/alertmanager && kubectl -n am rollout status statefulset/alertmanager --timeout=90s",
            requery_cmd="curl -sS -G $MIMIR/prometheus/api/v1/query --data-urlencode 'query=oncall_heartbeat_failed{service=\"hold-bag-svc\"}'",
            denied_cmd="kubectl -n irm auth can-i patch deploy/grafana-oncall --as=sre-bot",
            xfail_cmd="printf '%s\\n' '@pytest.mark.xfail(reason=\"IRM heartbeat owned by oncall-platform\")\\ndef test_holdbag_hb():\\n    assert False' > tests/test_holdbag_hb.py",
            wrong_old="group_wait: 30s",
            wrong_new="group_wait: 5m",
            wrong2_old="group_interval: 5m",
            wrong2_new="group_interval: 15m",
            ticket_path="tickets/OBS-4442.md",
            ticket_body="OBS-4442: hold-bag-svc still heartbeat-pages. AM group_wait is irrelevant; no AM alert exists. Need heartbeat interval/grace. No IRM RBAC.\n",
            goal="hold-bag-svc dashboard holdbag-irm-hb hb gaps keep paging while AM is quiet. Stop pages.",
            plan="Lengthen AM group_wait so IRM pages wait (r168 leftover).",
            outcome="AM group_wait 5m; heartbeat_failed still 8. Late holdbag-heartbeat.yaml interval 20s. Handoff OBS-4442.",
            obs1='[{"uid":"holdbag-irm-hb","title":"hold bag heartbeat"}]',
            obs2='{"title":"hb gaps","targets":[{"expr":"oncall_heartbeat_failed{service=\\"hold-bag-svc\\"}"}]}',
            obs3='{"status":"success","data":{"result":[{"value":[1710000000,"8"]}]}}',
            obs4="30s",
            obs5="AM group_wait 30s — treated as r168",
            obs6="helm/alertmanager/holdbag-route.yaml",
            obs7="patched group_wait 30s→5m",
            obs8='statefulset "alertmanager" successfully rolled out',
            obs9='{"status":"success","data":{"result":[{"value":[1710000300,"8"]}]}}',
            obs10="patched group_interval 5m→15m",
            obs11='{"status":"success","data":{"result":[{"value":[1710000400,"8"]}]}}',
            obs12="helm/grafana-irm/holdbag-heartbeat.yaml interval: 20s grace: 0s  # cron POST 60s",
            obs13="no",
            obs14="wrote tickets/OBS-4442.md",
            obs15="xfail tests/test_holdbag_hb.py",
        ),
    )
)
