"""Observability plants r357-r388. Do not clone r109-r356.

BAN r163 tid128, r172 inferred db, r190 DD UST,
r244 loki-querier-max-concurrent / loki-qconc-rebuild-blooms.
Not a r292 Tempo max-bytes-per-tag-values clone.
"""

from mill_plants_t import _leftover_pair

MORE = []

ROWS = [
    ("357", "loki", "loki-parallelise-shardable-queries-false", "loki-pshard-raise-qpar-not-flag",
     "slide-girt-pin-svc", "overwing-assist-svc", "sgirt-pshard-1", "owasst-pshard-qpar",
     "girt pin logs 30d", "", "pin_open",
     "query_range parallelise_shardable_queries false plus Grafana 30d LogQL 504s so the Stat is empty while 5m still returns 8",
     "Raising max_query_parallelism does not finish a 30d LogQL when parallelise_shardable_queries is false",
     "max_query_parallelism 1",
     "r271 max_query_parallelism; r309 split_queries_by_interval; r286 align_queries_with_step",
     "parallelise_shardable_queries false 504s 30d",
     "OBS-5425", ".query_range.parallelise_shardable_queries",
     "parallelise_shardable_queries: false", "parallelise_shardable_queries: true",
     ".limits_config.max_query_parallelism", "max_query_parallelism: 1", "max_query_parallelism: 32",
     "split_queries_by_interval: 0", "split_queries_by_interval: 30m",
     "query-frontend", "loki/sgirt-qpar.yaml", "loki/sgirt-pshard.yaml",
     "loki/owasst-qpar.yaml", "loki/owasst-pshard.yaml"),
    ("358", "tempo", "tempo-max-bytes-per-span-256", "tempo-spanb-raise-trbytes-not-span",
     "psu-speaker-svc", "cabin-chime-svc", "pspeak-spanb-2", "cchime-spanb-trbytes",
     "psu speaker traces", "", "",
     "ingester max_bytes_per_span 256 drops fat events so Grafana Search is empty while tiny health spans still GET by-id",
     "Raising max_bytes_per_trace does not keep fat events dropped by max_bytes_per_span 256",
     "max_bytes_per_trace 2048",
     "r318 max_bytes_per_trace; r292 tag-values; r254 max_spans",
     "max_bytes_per_span 256 drops fat events; not tag-values",
     "OBS-5426", ".ingester.max_bytes_per_span",
     "max_bytes_per_span: 256", "max_bytes_per_span: 100000",
     ".ingester.max_bytes_per_trace", "max_bytes_per_trace: 2048", "max_bytes_per_trace: 5000000",
     "max_bytes_per_tag_values_query: 64", "max_bytes_per_tag_values_query: 1048576",
     "ingester", "tempo/pspeak-trbytes.yaml", "tempo/pspeak-spanb.yaml",
     "tempo/cchime-trbytes.yaml", "tempo/cchime-spanb.yaml"),
    ("359", "mimir", "mimir-max-fetched-chunks-per-query-one", "mimir-fchunks-raise-lookback-not-chunks",
     "lav-call-svc", "galley-call-svc", "lcall-fchunks-3", "gcall-fchunks-lookback",
     "lav call C 24h", "lav_call_count", "",
     "limits max_fetched_chunks_per_query 1 400s Grafana 24h so the Stat is empty while 5m still returns 3",
     "Raising max_query_lookback does not fetch a 24h range when max_fetched_chunks_per_query is 1",
     "max_query_lookback 7d",
     "r210 lookback; r258 max_total_query_length; r279 Loki max_chunks",
     "max_fetched_chunks_per_query 1 400s 24h",
     "OBS-5427", ".limits.max_fetched_chunks_per_query",
     "max_fetched_chunks_per_query: 1", "max_fetched_chunks_per_query: 2000000",
     ".limits.max_query_lookback", "max_query_lookback: 7d", "max_query_lookback: 30d",
     "max_total_query_length: 7d", "max_total_query_length: 32d",
     "query-frontend", "mimir/lcall-lookback.yaml", "mimir/lcall-fchunks.yaml",
     "mimir/gcall-lookback.yaml", "mimir/gcall-fchunks.yaml"),
    ("360", "otel", "otel-failoverconnector-retry-zero", "otel-failov-raise-mem-not-retries",
     "handset-cradle-svc", "oxygen-door-svc", "hcradle-failov-4", "odox-failov-mem",
     "handset traces", "", "",
     "failoverconnector max_retries 0 plus the primary OTLP exporter 429s so Grafana Search is empty while the debug exporter still saw spans",
     "Raising memory_limiter does not failover OTLP when failoverconnector max_retries is 0",
     "memory_limiter limit_mib 32",
     "r224 memory_limiter; r204 loadbalancing; r174 routing vs filter",
     "failoverconnector retries 0 drops on primary 429",
     "OBS-5428", ".connectors.failover.max_retries",
     "max_retries: 0", "max_retries: 5",
     ".processors.memory_limiter.limit_mib", "limit_mib: 32", "limit_mib: 1024",
     "timeout: 1ms", "timeout: 200ms",
     "otelcol-hcradle", "otelcol/hcradle-mem.yaml", "otelcol/hcradle-failov.yaml",
     "otelcol/odox-mem.yaml", "otelcol/odox-failov.yaml"),
    ("361", "prom", "prom-exemplars-max-exemplars-zero", "prom-exemp-enable-classic-not-cap",
     "mask-drop-tube-svc", "raft-painter-svc", "mdrop-exemp-5", "rpaint-exemp-classic",
     "mask drop heatmap", "mask_drop_seconds", "",
     "storage.exemplars.max_exemplars 0 so Grafana heatmap exemplars are empty while the _bucket series still exist",
     "Enabling classic histograms does not restore exemplars when max_exemplars is 0",
     "always_scrape_classic_histograms false",
     "r187 native vs classic; r287 exponential hist; r205 OpenMetrics _created",
     "max_exemplars 0 blanks heatmap exemplars",
     "OBS-5429", ".storage.exemplars.max_exemplars",
     "max_exemplars: 0", "max_exemplars: 100000",
     ".scrape_configs[].always_scrape_classic_histograms", "always_scrape_classic_histograms: false", "always_scrape_classic_histograms: true",
     "scrape_native_histograms: false", "scrape_native_histograms: true",
     "prom-scrape", "prom/mdrop-classic.yaml", "prom/mdrop-exemp.yaml",
     "prom/rpaint-classic.yaml", "prom/rpaint-exemp.yaml"),
    ("362", "loki", "loki-max-concurrent-tail-requests-zero", "loki-tails-raise-maxconn-not-tail",
     "life-line-svc", "torch-hold-svc", "lline-tails-6", "thold-tails-live",
     "life line live logs", "", "line_cut",
     "querier max_concurrent_tail_requests 0 429s Grafana Live tail so the panel is empty while query_range still has 11 lines",
     "Raising Grafana live.max_connections does not tail Loki when max_concurrent_tail_requests is 0",
     "live.max_connections 0",
     "r315 live.max_connections; r350 allowed_origins; r247 Tempo search.enabled leftover",
     "max_concurrent_tail_requests 0 429s Live tail",
     "OBS-5430", ".querier.max_concurrent_tail_requests",
     "max_concurrent_tail_requests: 0", "max_concurrent_tail_requests: 32",
     ".live.max_connections", "max_connections = 0", "max_connections = 100",
     "allowed_origins =", "allowed_origins = *",
     "querier", "grafana/lline-live.ini", "loki/lline-tails.yaml",
     "grafana/thold-live.ini", "loki/thold-tails.yaml"),
    ("363", "tempo", "tempo-mg-max-active-series-one", "tempo-mgseries-drop-filter-not-cap",
     "firstaid-fwd-svc", "aed-aft-svc", "faidf-mgseries-7", "aedaft-mgseries-filter",
     "firstaid fwd calls", "", "",
     "metrics_generator max_active_series 1 evicts http.route so Grafana {http_route=} is empty while unfiltered calls_total exists",
     "Clearing MG filter_policies does not keep route series when max_active_series is 1",
     "MG filter skip 404",
     "r164 MG filter; r283 dim cache; r299 intrinsic status_code",
     "max_active_series 1 evicts route series",
     "OBS-5431", ".metrics_generator.max_active_series",
     "max_active_series: 1", "max_active_series: 100000",
     ".metrics_generator.processor.span_metrics.filter_policies", "filter_policies: [{include: {match_type: strict}}]", "filter_policies: []",
     "dimensions_cache_size: 1", "dimensions_cache_size: 1000",
     "metrics-generator", "tempo/faidf-filter.yaml", "tempo/faidf-mgseries.yaml",
     "tempo/aedaft-filter.yaml", "tempo/aedaft-mgseries.yaml"),
    ("364", "mimir", "mimir-ingester-replication-factor-one", "mimir-rf-raise-gseries-not-rf",
     "pbe-fwd-svc", "demo-lifevest-svc", "pbef-rf-8", "dlvest-rf-gseries",
     "PBE fwd C", "pbe_fwd_count", "",
     "ingester ring replication_factor 1 plus one zone outage so Grafana is empty while /metrics on the remaining replica still shows 6",
     "Raising max_global_series_per_user does not survive a zone outage when replication_factor is 1",
     "max_global_series_per_user 1",
     "r303 max_global_series; r327 ingestion_rate; r221 Thanos receive",
     "replication_factor 1 blanks Grafana on zone loss",
     "OBS-5432", ".ingester.ring.replication_factor",
     "replication_factor: 1", "replication_factor: 3",
     ".limits.max_global_series_per_user", "max_global_series_per_user: 1", "max_global_series_per_user: 150000",
     "ingestion_rate: 1", "ingestion_rate: 10000",
     "ingester", "mimir/pbef-gseries.yaml", "mimir/pbef-rf.yaml",
     "mimir/dlvest-gseries.yaml", "mimir/dlvest-rf.yaml"),
    ("365", "otel", "otel-metricsgeneration-count-rule", "otel-mgen-drop-countconn-not-rule",
     "safety-video-svc", "ife-server-svc", "svid-mgen-1", "ifesrv-mgen-count",
     "safety video calls", "", "",
     "metricsgeneration processor count rule name safety_video_spans so Grafana still queries traces_spanmetrics_calls_total and the panel is empty",
     "Dropping the count connector does not restore spanmetrics when metricsgeneration still emits a custom count",
     "count connector vs spanmetrics",
     "r325 count connector; r166 connector name; r283 dim cache",
     "metricsgeneration count rule replaces spanmetrics name",
     "OBS-5433", ".processors.metricsgeneration.rules",
     "name: safety_video_spans", "name: traces.spanmetrics.calls",
     ".service.pipelines.traces.exporters", "exporters: [count, otlp]", "exporters: [spanmetrics, otlp]",
     "namespace: traces.custom", "namespace: traces.spanmetrics",
     "otelcol-svid", "otelcol/svid-count.yaml", "otelcol/svid-mgen.yaml",
     "otelcol/ifesrv-count.yaml", "otelcol/ifesrv-mgen.yaml"),
    ("366", "grafana", "grafana-alerting-init-timeout-1ms", "grafana-initt-patch-minint-not-timeout",
     "seat-power-svc", "usb-outlet-svc", "spow-initt-2", "uout-initt-minint",
     "seat power pages", "", "usb_fail",
     "unified_alerting initialization_timeout 1ms so Grafana never loads 1m rules and the pages Stat is empty while raw 5xx is 0.15",
     "Lowering min_interval does not load rules when initialization_timeout is 1ms",
     "unified_alerting.min_interval 1h",
     "r324 min_interval; r340 alerting.enabled; r159 IRM group_by",
     "initialization_timeout 1ms blocks rule load",
     "OBS-5434", ".unified_alerting.initialization_timeout",
     "initialization_timeout = 1ms", "initialization_timeout = 30s",
     ".unified_alerting.min_interval", "min_interval = 1h", "min_interval = 10s",
     "enabled = false", "enabled = true",
     "grafana", "grafana/spow-minint.ini", "grafana/spow-initt.ini",
     "grafana/uout-minint.ini", "grafana/uout-initt.ini"),
    ("367", "loki", "loki-chunk-encoding-mismatch", "loki-enc-raise-chunk-age-not-codec",
     "bassinet-strap-svc", "bulkhead-latch-svc", "bstrap-enc-3", "blatch-enc-age",
     "bassinet logs", "", "strap_loose",
     "ingester chunk_encoding snappy plus querier expecting gzip so Grafana is empty while ingester memory_streams still show lines",
     "Raising max_chunk_age does not decode snappy chunks when the querier still expects gzip",
     "max_chunk_age 5m",
     "r235 max_chunk_age; r346 sync_period; r279 max_chunks_per_query",
     "chunk_encoding snappy vs querier gzip",
     "OBS-5435", ".ingester.chunk_encoding",
     "chunk_encoding: snappy", "chunk_encoding: gzip",
     ".ingester.max_chunk_age", "max_chunk_age: 5m", "max_chunk_age: 2h",
     "sync_period: 24h", "sync_period: 15s",
     "loki-ingester", "loki/bstrap-chunk.yaml", "loki/bstrap-enc.yaml",
     "loki/blatch-chunk.yaml", "loki/blatch-enc.yaml"),
    ("368", "tempo", "tempo-ingester-concurrent-flushes-zero", "tempo-cflush-raise-flushr-not-conc",
     "closet-light-svc", "curtain-magnet-svc", "clight2-cflush-4", "cmag-cflush-retries",
     "closet traces", "", "",
     "ingester concurrent_flushes 0 so complete blocks never ship and Grafana Search is empty while /status lists complete blocks",
     "Raising max_flush_retries does not ship complete blocks when concurrent_flushes is 0",
     "max_flush_retries 0",
     "r344 max_flush_retries; r328 flush_check_period; r308 max_block_duration",
     "concurrent_flushes 0 stalls complete-block ship",
     "OBS-5436", ".ingester.concurrent_flushes",
     "concurrent_flushes: 0", "concurrent_flushes: 4",
     ".ingester.max_flush_retries", "max_flush_retries: 0", "max_flush_retries: 10",
     "flush_check_period: 24h", "flush_check_period: 10s",
     "ingester", "tempo/clight2-flushr.yaml", "tempo/clight2-cflush.yaml",
     "tempo/cmag-flushr.yaml", "tempo/cmag-cflush.yaml"),
    ("369", "mimir", "mimir-ha-tracker-enable-drop-replica", "mimir-hatrack-raise-rf-not-ha",
     "jumpseat-oxy-svc", "ram-inlet-svc", "joxy-hatrack-5", "rinlet-hatrack-rf",
     "jumpseat oxy C", "jumpseat_oxy_psi", "",
     "distributor ha_tracker enable_ha_tracker true plus replica label mismatch so Grafana is empty while the elected replica still has 14",
     "Raising replication_factor does not elect a replica when ha_tracker drops the cluster label",
     "replication_factor 1",
     "r364 replication_factor; r327 ingestion_rate; r177 alloy relabel",
     "ha_tracker drops the unelected replica",
     "OBS-5437", ".distributor.ha_tracker.enable_ha_tracker",
     "enable_ha_tracker: true", "enable_ha_tracker: false",
     ".ingester.ring.replication_factor", "replication_factor: 1", "replication_factor: 3",
     "ha_tracker.ha_replica_label: replica", "ha_tracker.ha_replica_label: __replica__",
     "distributor", "mimir/joxy-rf.yaml", "mimir/joxy-hatrack.yaml",
     "mimir/rinlet-rf.yaml", "mimir/rinlet-hatrack.yaml"),
    ("370", "prom", "prom-query-timeout-1ms", "prom-qto1-raise-scrape-to-not-query",
     "isol-duct-svc", "bleed-hp-svc", "iduct-qto1-6", "bhp-qto1-scrape",
     "isol duct C", "isol_duct_celsius", "",
     "prometheus.yml query.timeout 1ms 504s Grafana so the panel is empty while a 5s query still returns 9",
     "Raising scrape_timeout does not finish PromQL when query.timeout is 1ms",
     "scrape_timeout 1s",
     "r233 scrape timeout; r300 Grafana dataproxy; r317 Loki query_timeout",
     "query.timeout 1ms 504s Grafana PromQL",
     "OBS-5438", ".query.timeout",
     "timeout: 1ms", "timeout: 2m",
     ".scrape_configs[].scrape_timeout", "scrape_timeout: 1s", "scrape_timeout: 10s",
     "scrape_interval: 15s", "scrape_interval: 15s",
     "prom-scrape", "prom/iduct-scrape.yaml", "prom/iduct-qto1.yaml",
     "prom/bhp-scrape.yaml", "prom/bhp-qto1.yaml"),
    ("371", "loki", "loki-max-query-lookback-for-labels-1s", "loki-lablook-raise-qingw-not-labels",
     "bleed-pr-svc", "cowl-antiice-svc", "bpr-lablook-7", "cowl-lablook-qingw",
     "PR bleed label values", "", "pr_open",
     "limits_config max_query_lookback_for_labels 1s so Grafana label dropdown is empty while query_range still has 7 lines",
     "Raising query_ingesters_within does not fill label values when max_query_lookback_for_labels is 1s",
     "query_ingesters_within 1s",
     "r293 query_ingesters_within; r292 Tempo tag-values; r298 max_query_series",
     "max_query_lookback_for_labels 1s empties dropdowns",
     "OBS-5439", ".limits_config.max_query_lookback_for_labels",
     "max_query_lookback_for_labels: 1s", "max_query_lookback_for_labels: 30d",
     ".querier.query_ingesters_within", "query_ingesters_within: 1s", "query_ingesters_within: 3h",
     "max_query_series: 1", "max_query_series: 500",
     "querier", "loki/bpr-qingw.yaml", "loki/bpr-lablook.yaml",
     "loki/cowl-qingw.yaml", "loki/cowl-lablook.yaml"),
    ("372", "tempo", "tempo-compactor-compaction-window-24h", "tempo-cwin-cut-blkdur-not-window",
     "lip-antiice-svc", "probe-aoa-heat-svc", "lipai-cwin-8", "paoa-cwin-dur",
     "lip anti-ice traces", "", "",
     "compactor compaction_window 24h so backend blocks never compact and Grafana 5m Search is empty while ingester /status still lists traces",
     "Cutting max_block_duration does not compact backend blocks when compaction_window is 24h",
     "max_block_duration 24h",
     "r308 max_block_duration; r328 flush_check; r236 complete_block_timeout",
     "compaction_window 24h starves 5m Search",
     "OBS-5440", ".compactor.compaction_window",
     "compaction_window: 24h", "compaction_window: 1h",
     ".ingester.max_block_duration", "max_block_duration: 24h", "max_block_duration: 5m",
     "flush_check_period: 24h", "flush_check_period: 10s",
     "compactor", "tempo/lipai-blkdur.yaml", "tempo/lipai-cwin.yaml",
     "tempo/paoa-blkdur.yaml", "tempo/paoa-cwin.yaml"),
    ("373", "otel", "otel-k8sattributes-extract-annotations", "otel-k8sann-disable-k8sattr-not-ann",
     "boiler-temp-svc", "soap-pump-svc", "btemp2-k8sann-1", "spump-k8sann-k8s",
     "boiler traces", "", "",
     "k8sattributes extract annotations service.grafana.com/name overwrites resource.service.name so Tempo search by app is empty",
     "Disabling k8sattributes extract metadata does not restore service.name when annotations still overwrite it",
     "k8sattributes overwrite from deployment",
     "r186 k8sattributes; r243 resourcedetection; r330 resource delete",
     "annotation extract overwrites service.name",
     "OBS-5441", ".processors.k8sattributes.extract.annotations",
     "from: service.grafana.com/name", "from: ''",
     ".processors.k8sattributes.extract.metadata", "metadata: [k8s.deployment.name]", "metadata: []",
     "detectors: [gcp]", "detectors: [env]",
     "otelcol-btemp2", "otelcol/btemp2-k8s.yaml", "otelcol/btemp2-k8sann.yaml",
     "otelcol/spump-k8s.yaml", "otelcol/spump-k8sann.yaml"),
    ("374", "prom", "prom-native-hist-max-bucket-number-one", "prom-nhmaxb-raise-factor-not-number",
     "towel-disp-svc", "tissue-disp-svc", "tdisp-nhmaxb-2", "tiss-nhmaxb-factor",
     "towel heatmap", "towel_disp_seconds", "",
     "scrape native_histogram_max_bucket_number 1 collapses the native hist so Grafana heatmap is empty while classic _bucket still exists on a sibling job",
     "Lowering native_histogram_min_bucket_factor does not restore buckets when max_bucket_number is 1",
     "native_histogram_min_bucket_factor 100",
     "r284 min_bucket_factor; r262 bucket_limit; r329 min_reset_duration",
     "max_bucket_number 1 collapses native hist",
     "OBS-5442", ".scrape_configs[].native_histogram_max_bucket_number",
     "native_histogram_max_bucket_number: 1", "native_histogram_max_bucket_number: 160",
     ".scrape_configs[].native_histogram_min_bucket_factor", "native_histogram_min_bucket_factor: 100", "native_histogram_min_bucket_factor: 1.1",
     "native_histogram_bucket_limit: 1", "native_histogram_bucket_limit: 160",
     "prom-scrape", "prom/tdisp-nhfactor.yaml", "prom/tdisp-nhmaxb.yaml",
     "prom/tiss-nhfactor.yaml", "prom/tiss-nhmaxb.yaml"),
    ("375", "loki", "loki-unordered-writes-ingester-window-0s", "loki-uowin-enable-unord-not-window",
     "air-fresh-svc", "baby-bass-svc", "afresh-uowin-3", "bbass-uowin-flag",
     "air fresh logs", "", "spray_fail",
     "ingester unordered_writes true plus unordered_writes_ingester_time_window 0s still drops OOO pax-phone lines so Grafana is empty",
     "Enabling unordered_writes does not ingest OOO lines when unordered_writes_ingester_time_window is 0s",
     "unordered_writes false",
     "r302 unordered_writes; r342 reject_old_samples_max_age; r235 max_chunk_age",
     "unordered window 0s still drops OOO",
     "OBS-5443", ".ingester.unordered_writes_ingester_time_window",
     "unordered_writes_ingester_time_window: 0s", "unordered_writes_ingester_time_window: 10m",
     ".ingester.unordered_writes", "unordered_writes: false", "unordered_writes: true",
     "reject_old_samples_max_age: 1m", "reject_old_samples_max_age: 168h",
     "loki-ingester", "loki/afresh-unord.yaml", "loki/afresh-uowin.yaml",
     "loki/bbass-unord.yaml", "loki/bbass-uowin.yaml"),
    ("376", "mimir", "mimir-store-gateway-max-query-lookback-1h", "mimir-sglook-raise-blkret-not-sg",
     "pet-hold-svc", "umnr-lanyard-svc", "phold-sglook-4", "ulany-sglook-ret",
     "pet hold 24h", "pet_hold_count", "",
     "store-gateway max_query_lookback 1h so Grafana 24h is empty while ingester 30m still queries",
     "Raising blocks_retention_period does not surface 24h blocks when store-gateway max_query_lookback is 1h",
     "blocks_retention_period 2h",
     "r312 blocks_retention; r249 ignore_blocks_within; r210 lookback",
     "store-gateway lookback 1h hides 24h",
     "OBS-5444", ".store_gateway.max_query_lookback",
     "max_query_lookback: 1h", "max_query_lookback: 30d",
     ".compactor.blocks_retention_period", "blocks_retention_period: 2h", "blocks_retention_period: 31d",
     "ignore_blocks_within: 10h", "ignore_blocks_within: 0s",
     "store-gateway", "mimir/phold-blkret.yaml", "mimir/phold-sglook.yaml",
     "mimir/ulany-blkret.yaml", "mimir/ulany-sglook.yaml"),
    ("377", "tempo", "tempo-search-hide-nested-spans-true", "tempo-hnest-enable-search-not-hide",
     "crew-bunk-lt-svc", "bunk-call-svc", "cbunklt-hnest-5", "bcall-hnest-search",
     "crew bunk nested traces", "", "",
     "search hide_nested_spans true so Grafana nested child spans are empty while GET by-id still shows the parent",
     "Enabling search.enabled does not show nested children when hide_nested_spans is true",
     "search.enabled false",
     "r247 search.enabled; r254 max_spans_per_span_set; r292 tag-values",
     "hide_nested_spans true blanks child Search",
     "OBS-5445", ".query_frontend.search.hide_nested_spans",
     "hide_nested_spans: true", "hide_nested_spans: false",
     ".query_frontend.search.enabled", "enabled: false", "enabled: true",
     "max_spans_per_span_set: 1", "max_spans_per_span_set: 100",
     "query-frontend", "tempo/cbunklt-searchoff.yaml", "tempo/cbunklt-hnest.yaml",
     "tempo/bcall-searchoff.yaml", "tempo/bcall-hnest.yaml"),
    ("378", "grafana", "grafana-datasources-limit-one", "grafana-dslim-reprovision-uid-not-limit",
     "rest-fan-svc", "cart-power-svc", "rfan-dslim-6", "cpow-dslim-uid",
     "rest fan C", "rest_fan_rpm", "",
     "grafana.ini datasources.limit 1 hides the Mimir datasource so Grafana panels are empty while direct Mimir still has 8",
     "Reprovisioning dashboard uid does not restore a panel when datasources.limit 1 hid Mimir",
     "provisioned dashboard uid collision",
     "r216 public dashboard; r109 provisioned uid; r189 ClickHouse SQL vs Tempo",
     "datasources.limit 1 hides Mimir",
     "OBS-5446", ".datasources.limit",
     "limit = 1", "limit = 0",
     ".dashboard.uid", "uid: rfan-old", "uid: rfan-dslim-6",
     "enabled = false", "enabled = true",
     "grafana", "grafana/rfan-uid.yaml", "grafana/rfan.ini",
     "grafana/cpow-uid.yaml", "grafana/cpow.ini"),
    ("379", "otel", "otel-memory-limiter-check-interval-24h", "otel-mlchk-raise-limit-not-interval",
     "chiller-temp-svc", "waste-svc-pnl-svc", "ctemp2-mlchk-7", "wspnl-mlchk-limit",
     "chiller traces", "", "",
     "memory_limiter check_interval 24h so a spike never trips the limiter until traces are already dropped and Grafana Search is empty",
     "Raising limit_mib does not check memory when check_interval is 24h",
     "memory_limiter limit_mib 32",
     "r224 memory_limiter; r275 probabilisticsampler; r237 batch timeout",
     "check_interval 24h delays memory_limiter",
     "OBS-5447", ".processors.memory_limiter.check_interval",
     "check_interval: 24h", "check_interval: 1s",
     ".processors.memory_limiter.limit_mib", "limit_mib: 32", "limit_mib: 1024",
     "sampling_percentage: 0", "sampling_percentage: 100",
     "otelcol-ctemp2", "otelcol/ctemp2-mem.yaml", "otelcol/ctemp2-mlchk.yaml",
     "otelcol/wspnl-mem.yaml", "otelcol/wspnl-mlchk.yaml"),
    ("380", "loki", "loki-frontend-tail-max-duration-1s", "loki-taildur-raise-tails-not-duration",
     "vac-filter-svc", "grey-valve-svc", "vfilt-taildur-8", "gvalve-taildur-tails",
     "vac filter live logs", "", "filter_clog",
     "frontend tail_max_duration 1s closes Grafana Live after one second so the tail panel looks empty while query_range has 13 lines",
     "Raising max_concurrent_tail_requests does not keep Live open when tail_max_duration is 1s",
     "max_concurrent_tail_requests 0",
     "r362 max_concurrent_tail_requests; r315 live.max_connections; r350 allowed_origins",
     "tail_max_duration 1s closes Live immediately",
     "OBS-5448", ".frontend.tail_max_duration",
     "tail_max_duration: 1s", "tail_max_duration: 1h",
     ".querier.max_concurrent_tail_requests", "max_concurrent_tail_requests: 0", "max_concurrent_tail_requests: 32",
     "max_connections = 0", "max_connections = 100",
     "query-frontend", "loki/vfilt-tails.yaml", "loki/vfilt-taildur.yaml",
     "loki/gvalve-tails.yaml", "loki/gvalve-taildur.yaml"),
    ("381", "mimir", "mimir-compactor-split-and-merge-shards-zero", "mimir-sms-zero-deldelay-not-shards",
     "blue-qty-svc", "fill-port-svc", "bqty-sms-1", "fport-sms-delay",
     "blue qty 24h", "blue_qty_liters", "",
     "compactor split_and_merge_shards 0 so 24h compacted blocks never appear and Grafana is empty while 30m still queries",
     "Raising deletion_delay does not compact 24h blocks when split_and_merge_shards is 0",
     "deletion_delay 0s",
     "r348 deletion_delay; r312 blocks_retention; r335 query_sharding_total_shards",
     "split_and_merge_shards 0 stalls 24h compact",
     "OBS-5449", ".compactor.split_and_merge_shards",
     "split_and_merge_shards: 0", "split_and_merge_shards: 8",
     ".compactor.deletion_delay", "deletion_delay: 0s", "deletion_delay: 12h",
     "blocks_retention_period: 2h", "blocks_retention_period: 31d",
     "compactor", "mimir/bqty-deldelay.yaml", "mimir/bqty-sms.yaml",
     "mimir/fport-deldelay.yaml", "mimir/fport-sms.yaml"),
    ("382", "tempo", "tempo-ingester-max-block-retention-1h", "tempo-blkret-cut-cwin-not-retention",
     "overflow-valve-svc", "tank-qty-svc", "ovalve-blkret-2", "tqty-blkret-cwin",
     "overflow traces 24h", "", "",
     "ingester complete_block_timeout 30m plus max_block_retention 1h deletes backend traces Grafana 24h Search needs while 15m still works",
     "Cutting compaction_window does not keep 24h traces deleted by max_block_retention 1h",
     "compaction_window 24h",
     "r372 compaction_window; r236 complete_block_timeout; r312 Mimir blocks_retention",
     "max_block_retention 1h deletes 24h traces",
     "OBS-5450", ".ingester.max_block_retention",
     "max_block_retention: 1h", "max_block_retention: 14d",
     ".compactor.compaction_window", "compaction_window: 24h", "compaction_window: 1h",
     "complete_block_timeout: 1s", "complete_block_timeout: 30m",
     "ingester", "tempo/ovalve-cwin.yaml", "tempo/ovalve-blkret.yaml",
     "tempo/tqty-cwin.yaml", "tempo/tqty-blkret.yaml"),
    ("383", "prom", "prom-tsdb-max-block-chunk-segment-1", "prom-seg-raise-minblk-not-segment",
     "service-door-svc", "wiper-park-svc", "sdoor-seg-3", "wpark-seg-minblk",
     "service door C", "service_door_open", "",
     "storage.tsdb.max_block_chunk_segment_size 1 so compacted blocks are unreadable and Grafana range is empty while /metrics still shows 1",
     "Cutting min_block_duration does not read blocks when max_block_chunk_segment_size is 1",
     "min_block_duration 24h",
     "r356 min_block_duration; r332 ooo window; r223 WAL replay",
     "max_block_chunk_segment_size 1 corrupts compacted blocks",
     "OBS-5451", ".storage.tsdb.max_block_chunk_segment_size",
     "max_block_chunk_segment_size: 1", "max_block_chunk_segment_size: 10485760",
     ".storage.tsdb.min_block_duration", "min_block_duration: 24h", "min_block_duration: 2h",
     "out_of_order_time_window: 0", "out_of_order_time_window: 10m",
     "prom-scrape", "prom/sdoor-minblk.yaml", "prom/sdoor-seg.yaml",
     "prom/wpark-minblk.yaml", "prom/wpark-seg.yaml"),
    ("384", "otel", "otel-forward-connector-drop-pipeline", "otel-fwd-restore-otlp-not-forward",
     "ife-seatback-svc", "seat-recline-svc", "ifesb-fwd-4", "srecl-fwd-otlp",
     "IFE seatback traces", "", "",
     "forward connector traces/in to a dead traces/out pipeline so Grafana Search is empty while the app still exports OTLP to the collector",
     "Pointing Grafana at a second Tempo tenant does not restore traces dropped by a dead forward connector pipeline",
     "OTel routing connector vs filter",
     "r174 routing vs filter; r204 loadbalancing; r360 failoverconnector",
     "forward connector into a dead pipeline",
     "OBS-5452", ".connectors.forward",
     "traces/in: [traces/out]", "traces/in: [traces]",
     ".exporters.otlp.endpoint", "endpoint: tempo-dead:4317", "endpoint: tempo:4317",
     "exporters: [count, otlp]", "exporters: [otlp]",
     "otelcol-ifesb", "otelcol/ifesb-route.yaml", "otelcol/ifesb-fwd.yaml",
     "otelcol/srecl-route.yaml", "otelcol/srecl-fwd.yaml"),
    ("385", "loki", "loki-max-cache-freshness-already-used", "loki-index-stats-cache-24h",
     "wait-this-is-wrong", "skip-me-svc", "skip-1", "skip-2",
     "skip", "", "skip",
     "placeholder",
     "placeholder",
     "placeholder",
     "r314",
     "placeholder",
     "OBS-5453", ".x",
     "x: 1", "x: 2",
     ".y", "y: 1", "y: 2",
     "z: 1", "z: 2",
     "querier", "loki/a.yaml", "loki/b.yaml",
     "loki/c.yaml", "loki/d.yaml"),
]

# Drop the placeholder last row; emit 357-384 only.
ROWS = [row for row in ROWS if row[4] != "wait-this-is-wrong"]

for row in ROWS:
    _leftover_pair(
        n=row[0],
        kind=row[1],
        ok_slug=row[2],
        bad_slug=row[3],
        ok_svc=row[4],
        bad_svc=row[5],
        ok_dash=row[6],
        bad_dash=row[7],
        panel=row[8],
        metric=row[9],
        needle=row[10],
        lie=row[11],
        bad_lie=row[12],
        false_lead=row[13],
        avoided=row[14],
        this_is=row[15],
        ticket=row[16],
        knob=row[17],
        old=row[18],
        new=row[19],
        wrong_knob=row[20],
        wrong_old=row[21],
        wrong_new=row[22],
        wrong2_old=row[23],
        wrong2_new=row[24],
        reload=row[25],
        config_path=row[26],
        lie_path=row[27],
        bad_config=row[28],
        bad_lie_path=row[29],
        dest=MORE,
    )
