"""Observability leftover14 plants r1260+.

BAN r1259 wasmtime-log-drop-leftover, leftover13 prior mill, leftover12 lock-basin,
r875 tempo-ingester-max-traces-per-user-one, r384 otel-forward-connector,
PagerDuty orch, Opsgenie alias, Rootly urgency.
"""

from mill_plants_t import _leftover_pair

MORE = []
ROUND_PAIRS = {}


def _emit(round_n, **kwargs):
    dest = []
    _leftover_pair(n=str(round_n), dest=dest, **kwargs)
    MORE.extend(dest)
    ROUND_PAIRS[round_n] = dest[0]


def _l14(n, **kw):
    vendor, noun, prefix = kw["vendor"], kw["noun"], kw["prefix"]
    ok_svc, bad_svc = f"canal-{noun}-svc", f"reach-{noun}-svc"
    tag = noun.replace("-", "")[:8]
    vtag = prefix.replace("-", "")[:5]
    ok_dash, bad_dash = f"{tag}-{vtag}-{n}", f"c{tag[:7]}-{vtag}-fl"
    lie_core = kw["lie_core"]
    _emit(
        n,
        kind="grafana",
        ok_slug=kw["ok_slug"],
        bad_slug=kw["bad_slug"],
        ok_svc=ok_svc,
        bad_svc=bad_svc,
        ok_dash=ok_dash,
        bad_dash=bad_dash,
        panel=kw["panel"],
        metric="",
        needle=kw["needle"],
        lie=(
            f"{vendor} leftover leftover leftover leftover leftover leftover leftover leftover leftover leftover leftover leftover leftover leftover {lie_core} "
            f"so Grafana dashboard {ok_dash} is empty while the source still 202"
        ),
        bad_lie=(
            f"{kw['false_lead']} does not restore leftover leftover leftover leftover leftover leftover leftover leftover leftover leftover leftover leftover leftover leftover {lie_core}"
        ),
        false_lead=kw["false_lead"],
        avoided=kw["avoided"],
        this_is=f"{vendor} leftover leftover leftover leftover leftover leftover leftover leftover leftover leftover leftover leftover leftover leftover {lie_core}",
        ticket=f"OBS-{ 9300 + (n - 1260) }",
        knob=kw["knob"],
        old=kw["old"],
        new=kw["new"],
        wrong_knob=kw["wrong_knob"],
        wrong_old=kw["wrong_old"],
        wrong_new=kw["wrong_new"],
        wrong2_old=kw["wrong2_old"],
        wrong2_new=kw["wrong2_new"],
        reload="grafana",
        config_path=f"{prefix}/{tag}-false.yaml",
        lie_path=f"{prefix}/{tag}-lie.yaml",
        bad_config=f"{prefix}/c{tag[:7]}-false.yaml",
        bad_lie_path=f"{prefix}/c{tag[:7]}-lie.yaml",
    )


BAN = (
    "r1259 wasmtime-log-drop-leftover; leftover13 dam/weir r1212-r1259; r875 tempo; r384 otel-forward; PagerDuty orch; Opsgenie alias; r515 Rootly urgency"
)

SPECS = [
    dict(vendor='NATS', ok_slug='nats-http-port-drop-leftover', bad_slug='nats-http-raise-js-not-port', noun='towpath', panel='NATS metrics', needle='nats_up', lie_core='http leftover http_port -1 so Grafana is empty while clients still connect', false_lead='NATS jetstream leftover', avoided=BAN, knob='.http_port', old='http_port: -1', new='http_port: 8222', wrong_knob='.jetstream.store_dir', wrong_old='store_dir: /tmp', wrong_new='store_dir: /var/lib/nats', wrong2_old='name: sandbox', wrong2_new='name: hangar', prefix='nats'),
    dict(vendor='JetStream', ok_slug='jstrm-max-bytes-drop-leftover', bad_slug='jstrm-bytes-raise-rep-not-max', noun='poundlock', panel='JetStream', needle='jstrm_str', lie_core='stream leftover max_bytes 1 so Grafana is empty while NATS still accepts', false_lead='JetStream replicas leftover', avoided=BAN, knob='.max_bytes', old='max_bytes: 1', new='max_bytes: 1073741824', wrong_knob='.replicas', wrong_old='replicas: 1', wrong_new='replicas: 3', wrong2_old='name: sandbox', wrong2_new='name: hangar', prefix='jstrm'),
    dict(vendor='Redpanda', ok_slug='rpanda-metrics-bind-drop-leftover', bad_slug='rpanda-bind-raise-id-not-addr', noun='sidecut', panel='Redpanda metrics', needle='rpanda_up', lie_core='admin leftover address 127.0.0.1 so Grafana is empty while Kafka still 9092', false_lead='Redpanda id leftover', avoided=BAN, knob='.admin.address', old='address: 127.0.0.1:9644', new='address: 0.0.0.0:9644', wrong_knob='.node_id', wrong_old='node_id: 0', wrong_new='node_id: 1', wrong2_old='cluster_id: sandbox', wrong2_new='cluster_id: hangar', prefix='rpanda'),
    dict(vendor='Pulsar', ok_slug='pulsr-metrics-off-leftover', bad_slug='pulsr-met-raise-ens-not-enable', noun='barge', panel='Pulsar metrics', needle='pulsr_up', lie_core='metrics leftover exposePublisherStats false so Grafana is empty while topics still persist', false_lead='Pulsar ensemble leftover', avoided=BAN, knob='.exposePublisherStats', old='exposePublisherStats: false', new='exposePublisherStats: true', wrong_knob='.managedLedgerDefaultEnsembleSize', wrong_old='managedLedgerDefaultEnsembleSize: 1', wrong_new='managedLedgerDefaultEnsembleSize: 3', wrong2_old='clusterName: sandbox', wrong2_new='clusterName: hangar', prefix='pulsr'),
    dict(vendor='RabbitMQ', ok_slug='rbmq-prometheus-off-leftover', bad_slug='rbmq-prom-raise-disk-not-enable', noun='winding', panel='RabbitMQ metrics', needle='rbmq_up', lie_core='prometheus leftover prometheus.tcp.port 0 so Grafana is empty while AMQP still 5672', false_lead='RabbitMQ disk leftover', avoided=BAN, knob='.prometheus.tcp.port', old='port: 0', new='port: 15692', wrong_knob='.disk_free_limit', wrong_old='disk_free_limit: 0', wrong_new='disk_free_limit: 50MB', wrong2_old='nodename: sandbox', wrong2_new='nodename: hangar', prefix='rbmq'),
    dict(vendor='NSQ', ok_slug='nsqd-stats-bind-drop-leftover', bad_slug='nsqd-stat-raise-mem-not-addr', noun='staircase', panel='NSQ stats', needle='nsqd_up', lie_core='stats leftover http-address 127.0.0.1 so Grafana is empty while nsqd still 4150', false_lead='NSQ mem leftover', avoided=BAN, knob='.http-address', old='http-address: 127.0.0.1:4151', new='http-address: 0.0.0.0:4151', wrong_knob='.mem-queue-size', wrong_old='mem-queue-size: 1', wrong_new='mem-queue-size: 10000', wrong2_old='lookupd-tcp-address: sandbox', wrong2_new='lookupd-tcp-address: hangar', prefix='nsqd'),
    dict(vendor='Beanstalkd', ok_slug='bstalk-verbose-off-leftover', bad_slug='bstalk-verb-raise-bin-not-enable', noun='gatepaddle', panel='Beanstalkd', needle='bstalk_up', lie_core='verbose leftover -V omitted plus wal /dev/null so Grafana is empty while jobs still reserve', false_lead='Beanstalkd binlog leftover', avoided=BAN, knob='.verbose', old='verbose: false', new='verbose: true', wrong_knob='.b', wrong_old='b: /tmp', wrong_new='b: /var/lib/beanstalkd', wrong2_old='f: 0', wrong2_new='f: 100', prefix='bstalk'),
    dict(vendor='Sidekiq', ok_slug='sdiq-metrics-off-leftover', bad_slug='sdiq-met-raise-conc-not-enable', noun='clough', panel='Sidekiq metrics', needle='sdiq_job', lie_core='metrics leftover SIDEKIQ_METRICS=false so Grafana is empty while workers still drain', false_lead='Sidekiq concurrency leftover', avoided=BAN, knob='.SIDEKIQ_METRICS', old='SIDEKIQ_METRICS: false', new='SIDEKIQ_METRICS: true', wrong_knob='.concurrency', wrong_old='concurrency: 1', wrong_new='concurrency: 10', wrong2_old='namespace: sandbox', wrong2_new='namespace: hangar', prefix='sdiq'),
    dict(vendor='Celery', ok_slug='celry-events-off-leftover', bad_slug='celry-evt-raise-broker-not-enable', noun='paddle', panel='Celery events', needle='celry_tsk', lie_core='events leftover CELERY_SEND_EVENTS=false so Grafana is empty while tasks still SUCCEEDED', false_lead='Celery broker leftover', avoided=BAN, knob='.CELERY_SEND_EVENTS', old='CELERY_SEND_EVENTS: false', new='CELERY_SEND_EVENTS: true', wrong_knob='.broker_url', wrong_old='broker_url: memory://', wrong_new='broker_url: redis://hangar', wrong2_old='task_always_eager: true', wrong2_new='task_always_eager: false', prefix='celry'),
    dict(vendor='RQ', ok_slug='rqjob-redis-url-remap-leftover', bad_slug='rqjob-url-raise-q-not-remap', noun='bywash', panel='RQ dashboard', needle='rqjob_job', lie_core='redis leftover RQ_REDIS_URL sandbox so Grafana is the wrong dashboard while jobs still run', false_lead='RQ queue leftover', avoided=BAN, knob='.RQ_REDIS_URL', old='RQ_REDIS_URL: redis://sandbox', new='RQ_REDIS_URL: redis://hangar', wrong_knob='.queue', wrong_old='queue: sandbox', wrong_new='queue: hangar', wrong2_old='name: sandbox', wrong2_new='name: hangar', prefix='rqjob'),
    dict(vendor='BullMQ', ok_slug='bullm-prefix-remap-leftover', bad_slug='bullm-pref-raise-conc-not-remap', noun='sidepond', panel='BullMQ metrics', needle='bullm_job', lie_core='prefix leftover prefix sandbox so Grafana is the wrong dashboard while jobs still complete', false_lead='BullMQ concurrency leftover', avoided=BAN, knob='.prefix', old='prefix: sandbox', new='prefix: hangar', wrong_knob='.concurrency', wrong_old='concurrency: 1', wrong_new='concurrency: 8', wrong2_old='redis: sandbox', wrong2_new='redis: hangar', prefix='bullm'),
    dict(vendor='Temporal', ok_slug='tmprl-prom-bind-drop-leftover', bad_slug='tmprl-bind-raise-ns-not-addr', noun='summit', panel='Temporal metrics', needle='tmprl_up', lie_core='prometheus leftover listen 127.0.0.1 so Grafana is empty while workflows still Completed', false_lead='Temporal ns leftover', avoided=BAN, knob='.prometheus.listenAddress', old='listenAddress: 127.0.0.1:9090', new='listenAddress: 0.0.0.0:9090', wrong_knob='.system.forceSearchAttributesCacheRefreshOnRead', wrong_old='forceSearchAttributesCacheRefreshOnRead: false', wrong_new='forceSearchAttributesCacheRefreshOnRead: true', wrong2_old='namespace: sandbox', wrong2_new='namespace: hangar', prefix='tmprl'),
    dict(vendor='Cadence', ok_slug='cadnc-metrics-off-leftover', bad_slug='cadnc-met-raise-dom-not-enable', noun='narrow', panel='Cadence metrics', needle='cadnc_up', lie_core='statsd leftover host empty so Grafana is empty while workflows still Completed', false_lead='Cadence domain leftover', avoided=BAN, knob='.statsd.host', old='host: ', new='host: hangar:8125', wrong_knob='.domain', wrong_old='domain: sandbox', wrong_new='domain: hangar', wrong2_old='ringpop.bootstrap: sandbox', wrong2_new='ringpop.bootstrap: hangar', prefix='cadnc'),
    dict(vendor='Conductor', ok_slug='condr-metrics-off-leftover', bad_slug='condr-met-raise-db-not-enable', noun='widebeam', panel='Conductor metrics', needle='condr_up', lie_core='metrics leftover conductor.metrics-prometheus.enabled=false so Grafana is empty while workflows still RUNNING', false_lead='Conductor db leftover', avoided=BAN, knob='.conductor.metrics-prometheus.enabled', old='enabled: false', new='enabled: true', wrong_knob='.db', wrong_old='db: memory', wrong_new='db: postgres', wrong2_old='stack: sandbox', wrong2_new='stack: hangar', prefix='condr'),
    dict(vendor='Airflow', ok_slug='airfl-statsd-off-leftover', bad_slug='airfl-stat-raise-exec-not-enable', noun='boatlift', panel='Airflow stats', needle='airfl_dag', lie_core='stats leftover statsd_on=False so Grafana is empty while DAGs still success', false_lead='Airflow executor leftover', avoided=BAN, knob='.statsd_on', old='statsd_on: False', new='statsd_on: True', wrong_knob='.executor', wrong_old='executor: SequentialExecutor', wrong_new='executor: CeleryExecutor', wrong2_old='dags_folder: /tmp', wrong2_new='dags_folder: /opt/airflow/dags', prefix='airfl'),
    dict(vendor='Dagster', ok_slug='dagst-telemetry-off-leftover', bad_slug='dagst-tel-raise-home-not-enable', noun='inclined', panel='Dagster metrics', needle='dagst_run', lie_core='telemetry leftover dagster.yaml telemetry.enabled=false so Grafana is empty while runs still SUCCESS', false_lead='Dagster home leftover', avoided=BAN, knob='.telemetry.enabled', old='enabled: false', new='enabled: true', wrong_knob='.DAGSTER_HOME', wrong_old='DAGSTER_HOME: /tmp', wrong_new='DAGSTER_HOME: /opt/dagster/dagster_home', wrong2_old='module: sandbox', wrong2_new='module: hangar', prefix='dagst'),
    dict(vendor='Prefect', ok_slug='prefc-api-url-remap-leftover', bad_slug='prefc-url-raise-work-not-remap', noun='caisson', panel='Prefect events', needle='prefc_fl', lie_core='api leftover PREFECT_API_URL sandbox so Grafana is the wrong dashboard while flows still Completed', false_lead='Prefect work leftover', avoided=BAN, knob='.PREFECT_API_URL', old='PREFECT_API_URL: https://sandbox', new='PREFECT_API_URL: https://hangar', wrong_knob='.work_pool', wrong_old='work_pool: sandbox', wrong_new='work_pool: hangar', wrong2_old='PREFECT_LOGGING_LEVEL: CRITICAL', wrong2_new='PREFECT_LOGGING_LEVEL: INFO', prefix='prefc'),
    dict(vendor='Luigi', ok_slug='luigi-metrics-off-leftover', bad_slug='luigi-met-raise-port-not-enable', noun='guillotine', panel='Luigi scheduler', needle='luigi_tsk', lie_core='metrics leftover scheduler.metrics_enabled=false so Grafana is empty while tasks still DONE', false_lead='Luigi port leftover', avoided=BAN, knob='.metrics_enabled', old='metrics_enabled: false', new='metrics_enabled: true', wrong_knob='.port', wrong_old='port: 0', wrong_new='port: 8082', wrong2_old='record_task_history: false', wrong2_new='record_task_history: true', prefix='luigi'),
    dict(vendor='Azkaban', ok_slug='azkab-metrics-off-leftover', bad_slug='azkab-met-raise-exec-not-enable', noun='rbsill', panel='Azkaban metrics', needle='azkab_up', lie_core='metrics leftover azkaban.metrics.enabled=false so Grafana is empty while flows still SUCCEEDED', false_lead='Azkaban executor leftover', avoided=BAN, knob='.azkaban.metrics.enabled', old='enabled: false', new='enabled: true', wrong_knob='.executor.port', wrong_old='port: 0', wrong_new='port: 12321', wrong2_old='azkaban.name: sandbox', wrong2_new='azkaban.name: hangar', prefix='azkab'),
    dict(vendor='Oozie', ok_slug='oozie-jmx-off-leftover', bad_slug='oozie-jmx-raise-cb-not-enable', noun='heelpost', panel='Oozie JMX', needle='oozie_up', lie_core='jmx leftover oozie.jmx.enabled=false so Grafana is empty while workflows still SUCCEEDED', false_lead='Oozie callback leftover', avoided=BAN, knob='.oozie.jmx.enabled', old='enabled: false', new='enabled: true', wrong_knob='.oozie.base.url', wrong_old='url: http://sandbox', wrong_new='url: http://hangar', wrong2_old='oozie.service.CallbackService.base: sandbox', wrong2_new='oozie.service.CallbackService.base: hangar', prefix='oozie'),
    dict(vendor='NiFi', ok_slug='niflow-metrics-off-leftover', bad_slug='niflow-met-raise-repo-not-enable', noun='mitrepost', panel='NiFi metrics', needle='niflow_up', lie_core='metrics leftover nifi.analytics.predict.enabled=false plus bulletin off so Grafana is empty', false_lead='NiFi repo leftover', avoided=BAN, knob='.nifi.analytics.predict.enabled', old='enabled: false', new='enabled: true', wrong_knob='.nifi.flow.configuration.file', wrong_old='file: /tmp/empty.xml', wrong_new='file: /opt/nifi/conf/flow.xml.gz', wrong2_old='nifi.web.http.host: 127.0.0.1', wrong2_new='nifi.web.http.host: 0.0.0.0', prefix='niflow'),
    dict(vendor='dbt', ok_slug='dbtcl-artifacts-drop-leftover', bad_slug='dbtcl-art-raise-tgt-not-path', noun='balanceb', panel='dbt artifacts', needle='dbtcl_run', lie_core='artifacts leftover target-path /dev/null so Grafana is empty while models still success', false_lead='dbt target leftover', avoided=BAN, knob='.target-path', old='target-path: /dev/null', new='target-path: target', wrong_knob='.target', wrong_old='target: sandbox', wrong_new='target: hangar', wrong2_old='profile: sandbox', wrong2_new='profile: hangar', prefix='dbtcl'),
    dict(vendor='Great Expectations', ok_slug='gxeq-store-remap-leftover', bad_slug='gxeq-store-raise-ds-not-remap', noun='gatewalk', panel='GX validation', needle='gxeq_val', lie_core='store leftover validations_store_name sandbox so Grafana is the wrong dashboard while suites still run', false_lead='GX datasource leftover', avoided=BAN, knob='.validations_store_name', old='validations_store_name: sandbox', new='validations_store_name: hangar', wrong_knob='.datasources[0].name', wrong_old='name: sandbox', wrong_new='name: hangar', wrong2_old='config_file: /tmp', wrong2_new='config_file: great_expectations.yml', prefix='gxeq'),
    dict(vendor='Soda', ok_slug='sodaq-cloud-url-remap-leftover', bad_slug='sodaq-url-raise-ds-not-remap', noun='overflow', panel='Soda scans', needle='sodaq_chk', lie_core='cloud leftover soda.cloud.host sandbox so Grafana is the wrong dashboard while scans still pass', false_lead='Soda datasource leftover', avoided=BAN, knob='.soda.cloud.host', old='host: sandbox', new='host: hangar', wrong_knob='.data_source', wrong_old='data_source: sandbox', wrong_new='data_source: hangar', wrong2_old='soda.cloud.api_key: sandbox', wrong2_new='soda.cloud.api_key: hangar', prefix='sodaq'),
    dict(vendor='Monte Carlo', ok_slug='mcarlo-warehouse-remap-leftover', bad_slug='mcarlo-wh-raise-key-not-remap', noun='poundage', panel='Monte Carlo', needle='mcarlo_mon', lie_core='warehouse leftover MONTECARLO_WAREHOUSE sandbox so Grafana is the wrong dashboard while monitors still 200', false_lead='Monte Carlo key leftover', avoided=BAN, knob='.MONTECARLO_WAREHOUSE', old='MONTECARLO_WAREHOUSE: sandbox', new='MONTECARLO_WAREHOUSE: hangar', wrong_knob='.MONTECARLO_API_KEY', wrong_old='MONTECARLO_API_KEY: sandbox', wrong_new='MONTECARLO_API_KEY: hangar', wrong2_old='mcd_id: sandbox', wrong2_new='mcd_id: hangar', prefix='mcarlo'),
    dict(vendor='Elementary', ok_slug='elemn-target-remap-leftover', bad_slug='elemn-tgt-raise-prof-not-remap', noun='lockcut', panel='Elementary', needle='elemn_rep', lie_core='target leftover edr target sandbox so Grafana is the wrong dashboard while dbt still success', false_lead='Elementary profile leftover', avoided=BAN, knob='.target', old='target: sandbox', new='target: hangar', wrong_knob='.profile', wrong_old='profile: sandbox', wrong_new='profile: hangar', wrong2_old='slack: sandbox', wrong2_new='slack: hangar', prefix='elemn'),
    dict(vendor='Metaplane', ok_slug='mplan-workspace-remap-leftover', bad_slug='mplan-ws-raise-wh-not-remap', noun='feeders', panel='Metaplane', needle='mplan_mon', lie_core='workspace leftover METAPLANE_WORKSPACE sandbox so Grafana is the wrong dashboard while monitors still 200', false_lead='Metaplane warehouse leftover', avoided=BAN, knob='.METAPLANE_WORKSPACE', old='METAPLANE_WORKSPACE: sandbox', new='METAPLANE_WORKSPACE: hangar', wrong_knob='.warehouse', wrong_old='warehouse: sandbox', wrong_new='warehouse: hangar', wrong2_old='METAPLANE_API_KEY: sandbox', wrong2_new='METAPLANE_API_KEY: hangar', prefix='mplan'),
    dict(vendor='Lightup', ok_slug='lgtup-app-url-remap-leftover', bad_slug='lgtup-url-raise-src-not-remap', noun='reservoir', panel='Lightup', needle='lgtup_mon', lie_core='app leftover LIGHTUP_APP_URL sandbox so Grafana is the wrong dashboard while monitors still 200', false_lead='Lightup source leftover', avoided=BAN, knob='.LIGHTUP_APP_URL', old='LIGHTUP_APP_URL: https://sandbox', new='LIGHTUP_APP_URL: https://hangar', wrong_knob='.source', wrong_old='source: sandbox', wrong_new='source: hangar', wrong2_old='LIGHTUP_API_TOKEN: sandbox', wrong2_new='LIGHTUP_API_TOKEN: hangar', prefix='lgtup'),
    dict(vendor='Bigeye', ok_slug='bigeye-workspace-remap-leftover', bad_slug='bigeye-ws-raise-src-not-remap', noun='aqueduct', panel='Bigeye', needle='bigeye_met', lie_core='workspace leftover BIGEYE_WORKSPACE sandbox so Grafana is the wrong dashboard while metrics still 200', false_lead='Bigeye source leftover', avoided=BAN, knob='.BIGEYE_WORKSPACE', old='BIGEYE_WORKSPACE: sandbox', new='BIGEYE_WORKSPACE: hangar', wrong_knob='.source', wrong_old='source: sandbox', wrong_new='source: hangar', wrong2_old='BIGEYE_API_KEY: sandbox', wrong2_new='BIGEYE_API_KEY: hangar', prefix='bigeye'),
    dict(vendor='Anomalo', ok_slug='anoma-site-remap-leftover', bad_slug='anoma-site-raise-wh-not-remap', noun='embank', panel='Anomalo', needle='anoma_chk', lie_core='site leftover ANOMALO_SITE sandbox so Grafana is the wrong dashboard while checks still 200', false_lead='Anomalo warehouse leftover', avoided=BAN, knob='.ANOMALO_SITE', old='ANOMALO_SITE: sandbox', new='ANOMALO_SITE: hangar', wrong_knob='.warehouse', wrong_old='warehouse: sandbox', wrong_new='warehouse: hangar', wrong2_old='ANOMALO_API_TOKEN: sandbox', wrong2_new='ANOMALO_API_TOKEN: hangar', prefix='anoma'),
    dict(vendor='Databand', ok_slug='dbnd-tracking-off-leftover', bad_slug='dbnd-trk-raise-url-not-enable', noun='cutting', panel='Databand', needle='dbnd_run', lie_core='tracking leftover DBND_ENABLED=false so Grafana is empty while Airflow still success', false_lead='Databand url leftover', avoided=BAN, knob='.DBND_ENABLED', old='DBND_ENABLED: false', new='DBND_ENABLED: true', wrong_knob='.DBND_TRACKER_URL', wrong_old='DBND_TRACKER_URL: https://sandbox', wrong_new='DBND_TRACKER_URL: https://hangar', wrong2_old='DBND_ENV: sandbox', wrong2_new='DBND_ENV: hangar', prefix='dbnd'),
    dict(vendor='OpenLineage', ok_slug='oline-url-drop-leftover', bad_slug='oline-url-raise-ns-not-url', noun='tunnel', panel='OpenLineage', needle='oline_ev', lie_core='url leftover OPENLINEAGE_URL empty so Grafana is empty while jobs still succeed', false_lead='OpenLineage ns leftover', avoided=BAN, knob='.OPENLINEAGE_URL', old='OPENLINEAGE_URL: ', new='OPENLINEAGE_URL: https://hangar', wrong_knob='.OPENLINEAGE_NAMESPACE', wrong_old='OPENLINEAGE_NAMESPACE: sandbox', wrong_new='OPENLINEAGE_NAMESPACE: hangar', wrong2_old='OPENLINEAGE_DISABLED: true', wrong2_new='OPENLINEAGE_DISABLED: false', prefix='oline'),
    dict(vendor='Marquez', ok_slug='marqz-listen-drop-leftover', bad_slug='marqz-list-raise-db-not-addr', noun='portal', panel='Marquez API', needle='marqz_up', lie_core='listen leftover MARQUEZ_PORT plus host 127.0.0.1 so Grafana is empty while lineage still writes', false_lead='Marquez db leftover', avoided=BAN, knob='.MARQUEZ_HOST', old='MARQUEZ_HOST: 127.0.0.1', new='MARQUEZ_HOST: 0.0.0.0', wrong_knob='.POSTGRES_URL', wrong_old='POSTGRES_URL: postgres://sandbox', wrong_new='POSTGRES_URL: postgres://hangar', wrong2_old='MARQUEZ_PORT: 0', wrong2_new='MARQUEZ_PORT: 5000', prefix='marqz'),
    dict(vendor='DataHub', ok_slug='dhub-metrics-off-leftover', bad_slug='dhub-met-raise-kafka-not-enable', noun='towring', panel='DataHub metrics', needle='dhub_up', lie_core='metrics leftover datahub.metrics.enabled=false so Grafana is empty while ingest still 200', false_lead='DataHub kafka leftover', avoided=BAN, knob='.datahub.metrics.enabled', old='enabled: false', new='enabled: true', wrong_knob='.kafka.bootstrap.servers', wrong_old='bootstrap.servers: sandbox:9092', wrong_new='bootstrap.servers: hangar:9092', wrong2_old='elasticsearch.host: sandbox', wrong2_new='elasticsearch.host: hangar', prefix='dhub'),
    dict(vendor='Amundsen', ok_slug='amund-frontend-bind-drop-leftover', bad_slug='amund-bind-raise-neo-not-addr', noun='roping', panel='Amundsen', needle='amund_up', lie_core='frontend leftover bind 127.0.0.1 so Grafana is empty while search still 5000', false_lead='Amundsen neo4j leftover', avoided=BAN, knob='.FRONTEND_HOST', old='FRONTEND_HOST: 127.0.0.1', new='FRONTEND_HOST: 0.0.0.0', wrong_knob='.NEO4J_HOST', wrong_old='NEO4J_HOST: sandbox', wrong_new='NEO4J_HOST: hangar', wrong2_old='PROXY_ENDPOINT: sandbox', wrong2_new='PROXY_ENDPOINT: hangar', prefix='amund'),
    dict(vendor='Atlas', ok_slug='atlasx-metrics-off-leftover', bad_slug='atlasx-met-raise-zk-not-enable', noun='stopplank', panel='Atlas metrics', needle='atlasx_up', lie_core='metrics leftover atlas.metrics.enabled=false so Grafana is empty while types still persist', false_lead='Atlas zk leftover', avoided=BAN, knob='.atlas.metrics.enabled', old='enabled: false', new='enabled: true', wrong_knob='.atlas.graph.storage.hostname', wrong_old='hostname: sandbox', wrong_new='hostname: hangar', wrong2_old='atlas.server.bind: 127.0.0.1', wrong2_new='atlas.server.bind: 0.0.0.0', prefix='atlasx'),
    dict(vendor='Collibra', ok_slug='collb-dgc-url-remap-leftover', bad_slug='collb-url-raise-user-not-remap', noun='stopgate', panel='Collibra', needle='collb_up', lie_core='dgc leftover COLLIBRA_BASE_URL sandbox so Grafana is the wrong dashboard while assets still 200', false_lead='Collibra user leftover', avoided=BAN, knob='.COLLIBRA_BASE_URL', old='COLLIBRA_BASE_URL: https://sandbox', new='COLLIBRA_BASE_URL: https://hangar', wrong_knob='.username', wrong_old='username: sandbox', wrong_new='username: hangar', wrong2_old='COLLIBRA_USER: sandbox', wrong2_new='COLLIBRA_USER: hangar', prefix='collb'),
    dict(vendor='Alation', ok_slug='alate-domain-remap-leftover', bad_slug='alate-dom-raise-tok-not-remap', noun='paddlebox', panel='Alation', needle='alate_up', lie_core='domain leftover ALATION_DOMAIN sandbox so Grafana is the wrong dashboard while catalog still 200', false_lead='Alation token leftover', avoided=BAN, knob='.ALATION_DOMAIN', old='ALATION_DOMAIN: sandbox', new='ALATION_DOMAIN: hangar', wrong_knob='.ALATION_API_TOKEN', wrong_old='ALATION_API_TOKEN: sandbox', wrong_new='ALATION_API_TOKEN: hangar', wrong2_old='refresh_token: sandbox', wrong2_new='refresh_token: hangar', prefix='alate'),
    dict(vendor='Atlan', ok_slug='atlan-base-url-remap-leftover', bad_slug='atlan-url-raise-key-not-remap', noun='gateheel', panel='Atlan', needle='atlan_up', lie_core='base leftover ATLAN_BASE_URL sandbox so Grafana is the wrong dashboard while assets still 200', false_lead='Atlan key leftover', avoided=BAN, knob='.ATLAN_BASE_URL', old='ATLAN_BASE_URL: https://sandbox', new='ATLAN_BASE_URL: https://hangar', wrong_knob='.ATLAN_API_KEY', wrong_old='ATLAN_API_KEY: sandbox', wrong_new='ATLAN_API_KEY: hangar', wrong2_old='ATLAN_TENANT: sandbox', wrong2_new='ATLAN_TENANT: hangar', prefix='atlan'),
    dict(vendor='OpenMetadata', ok_slug='ometa-metrics-off-leftover', bad_slug='ometa-met-raise-es-not-enable', noun='cilia', panel='OpenMetadata', needle='ometa_up', lie_core='metrics leftover pipelineServiceClient.enabled=false plus prometheus off so Grafana is empty', false_lead='OpenMetadata es leftover', avoided=BAN, knob='.pipelineServiceClient.enabled', old='enabled: false', new='enabled: true', wrong_knob='.elasticsearch.host', wrong_old='host: sandbox', wrong_new='host: hangar', wrong2_old='clusterName: sandbox', wrong2_new='clusterName: hangar', prefix='ometa'),
    dict(vendor='Trino', ok_slug='trino-rmi-registry-port-drop-leftover', bad_slug='trino-rmi-raise-cat-not-port', noun='quoin', panel='Trino JMX', needle='trino_up', lie_core='jmx leftover jmx.rmiregistry.port 0 so Grafana is empty while queries still FINISHED', false_lead='Trino catalog leftover', avoided=BAN, knob='.jmx.rmiregistry.port', old='port: 0', new='port: 9080', wrong_knob='.catalog.config-dir', wrong_old='config-dir: /tmp', wrong_new='config-dir: /etc/trino/catalog', wrong2_old='node.environment: sandbox', wrong2_new='node.environment: hangar', prefix='trino'),
    dict(vendor='Presto', ok_slug='prest-jmx-off-leftover', bad_slug='prest-jmx-raise-cat-not-enable', noun='hollowq', panel='Presto JMX', needle='prest_up', lie_core='jmx leftover jmx.rmiregistry.port 0 so Grafana is empty while queries still FINISHED', false_lead='Presto catalog leftover', avoided=BAN, knob='.jmx.rmiregistry.port', old='port: 0', new='port: 9081', wrong_knob='.catalog.config-dir', wrong_old='config-dir: /tmp', wrong_new='config-dir: /etc/presto/catalog', wrong2_old='node.environment: sandbox', wrong2_new='node.environment: hangar', prefix='prest'),
    dict(vendor='Impala', ok_slug='impala-webserver-off-leftover', bad_slug='impala-web-raise-cat-not-enable', noun='gateleaf', panel='Impala metrics', needle='impala_up', lie_core='web leftover --webserver_interface 127.0.0.1 so Grafana is empty while queries still FINISHED', false_lead='Impala catalog leftover', avoided=BAN, knob='.webserver_interface', old='webserver_interface: 127.0.0.1', new='webserver_interface: 0.0.0.0', wrong_knob='.catalog_service_host', wrong_old='catalog_service_host: sandbox', wrong_new='catalog_service_host: hangar', wrong2_old='statestore_host: sandbox', wrong2_new='statestore_host: hangar', prefix='impala'),
    dict(vendor='Drill', ok_slug='drillx-metrics-off-leftover', bad_slug='drillx-met-raise-zk-not-enable', noun='pointing', panel='Drill metrics', needle='drillx_up', lie_core='metrics leftover drill.exec.http.enabled=false so Grafana is empty while queries still COMPLETED', false_lead='Drill zk leftover', avoided=BAN, knob='.drill.exec.http.enabled', old='enabled: false', new='enabled: true', wrong_knob='.drill.exec.zk.connect', wrong_old='connect: sandbox:2181', wrong_new='connect: hangar:2181', wrong2_old='drill.exec.http.port: 0', wrong2_new='drill.exec.http.port: 8047', prefix='drillx'),
    dict(vendor='Dremio', ok_slug='drem-c3-metrics-off-leftover', bad_slug='drem-c3-raise-dist-not-enable', noun='riser', panel='Dremio metrics', needle='drem_up', lie_core='c3 leftover services.coordinator.enabled=false plus prometheus off so Grafana is empty', false_lead='Dremio dist leftover', avoided=BAN, knob='.services.coordinator.enabled', old='enabled: false', new='enabled: true', wrong_knob='.paths.dist', wrong_old='dist: /tmp', wrong_new='dist: /var/lib/dremio', wrong2_old='services.web.port: 0', wrong2_new='services.web.port: 9047', prefix='drem'),
    dict(vendor='StarRocks', ok_slug='srocks-http-port-drop-leftover', bad_slug='srocks-http-raise-fe-not-port', noun='fall', panel='StarRocks metrics', needle='srocks_up', lie_core='http leftover http_port 0 so Grafana is empty while queries still OK', false_lead='StarRocks fe leftover', avoided=BAN, knob='.http_port', old='http_port: 0', new='http_port: 8030', wrong_knob='.meta_dir', wrong_old='meta_dir: /tmp', wrong_new='meta_dir: /opt/starrocks/fe/meta', wrong2_old='cluster_id: sandbox', wrong2_new='cluster_id: hangar', prefix='srocks'),
    dict(vendor='Doris', ok_slug='dorisx-enable-metric-off-leftover', bad_slug='dorisx-met-raise-fe-not-enable', noun='dropgate', panel='Doris metrics', needle='dorisx_up', lie_core='metric leftover enable_metric_calculator=false so Grafana is empty while queries still OK', false_lead='Doris fe leftover', avoided=BAN, knob='.enable_metric_calculator', old='enable_metric_calculator: false', new='enable_metric_calculator: true', wrong_knob='.meta_dir', wrong_old='meta_dir: /tmp', wrong_new='meta_dir: /opt/apache-doris/fe/doris-meta', wrong2_old='cluster_id: sandbox', wrong2_new='cluster_id: hangar', prefix='dorisx'),
    dict(vendor='ClickHouse', ok_slug='chouse-system-metrics-off-leftover', bad_slug='chouse-met-raise-db-not-enable', noun='sector', panel='ClickHouse metrics', needle='chouse_up', lie_core='system leftover system.metrics disabled plus listen 127.0.0.1 so Grafana is empty', false_lead='ClickHouse db leftover', avoided=BAN, knob='.listen_host', old='listen_host: 127.0.0.1', new='listen_host: 0.0.0.0', wrong_knob='.path', wrong_old='path: /tmp', wrong_new='path: /var/lib/clickhouse', wrong2_old='default_database: sandbox', wrong2_new='default_database: hangar', prefix='chouse'),
    dict(vendor='Druid', ok_slug='druidx-emitter-off-leftover', bad_slug='druidx-emit-raise-zk-not-http', noun='radial', panel='Druid metrics', needle='druidx_up', lie_core='emitter leftover druid.emitter=noop so Grafana is empty while queries still SUCCESS', false_lead='Druid zk leftover', avoided=BAN, knob='.druid.emitter', old='emitter: noop', new='emitter: http', wrong_knob='.druid.zk.service.host', wrong_old='host: sandbox', wrong_new='host: hangar', wrong2_old='druid.emitter.http.recipientBaseUrl: http://sandbox', wrong2_new='druid.emitter.http.recipientBaseUrl: http://hangar', prefix='druidx'),
    dict(vendor='Pinot', ok_slug='pinot-metrics-off-leftover', bad_slug='pinot-met-raise-zk-not-enable', noun='taintor', panel='Pinot metrics', needle='pinot_up', lie_core='metrics leftover pinot.server.metrics.prefix empty plus jmx off so Grafana is empty', false_lead='Pinot zk leftover', avoided=BAN, knob='.pinot.server.metrics.prefix', old='prefix: ', new='prefix: hangar', wrong_knob='.pinot.zk.address', wrong_old='address: sandbox:2181', wrong_new='address: hangar:2181', wrong2_old='cluster.name: sandbox', wrong2_new='cluster.name: hangar', prefix='pinot'),
    dict(vendor='Kylin', ok_slug='kylin-metrics-off-leftover', bad_slug='kylin-met-raise-hbase-not-enable', noun='roller', panel='Kylin metrics', needle='kylin_up', lie_core='metrics leftover kylin.metrics.reporter-classes empty so Grafana is empty while cubes still READY', false_lead='Kylin hbase leftover', avoided=BAN, knob='.kylin.metrics.reporter-classes', old='reporter-classes: ', new='reporter-classes: org.apache.kylin.common.metrics.metrics2.CodahaleMetrics', wrong_knob='.kylin.storage.hbase.cluster', wrong_old='cluster: sandbox', wrong_new='cluster: hangar', wrong2_old='kylin.metadata.url: sandbox', wrong2_new='kylin.metadata.url: hangar', prefix='kylin'),
    dict(vendor='HBase', ok_slug='hbase-info-bind-drop-leftover', bad_slug='hbase-info-raise-zk-not-addr', noun='visorgate', panel='HBase metrics', needle='hbase_up', lie_core='info leftover hbase.master.info.bindAddress 127.0.0.1 so Grafana is empty while regions still open', false_lead='HBase zk leftover', avoided=BAN, knob='.hbase.master.info.bindAddress', old='bindAddress: 127.0.0.1', new='bindAddress: 0.0.0.0', wrong_knob='.hbase.zookeeper.quorum', wrong_old='quorum: sandbox', wrong_new='quorum: hangar', wrong2_old='hbase.rootdir: /tmp', wrong2_new='hbase.rootdir: /hbase', prefix='hbase'),
    dict(vendor='Cassandra', ok_slug='cassx-metrics-reporter-drop-leftover', bad_slug='cassx-rep-raise-snitch-not-reporter', noun='beartrap', panel='Cassandra metrics', needle='cassx_up', lie_core='reporter leftover metrics_reporter yaml empty so Grafana is empty while CQL still 9042', false_lead='Cassandra snitch leftover', avoided=BAN, knob='.metrics_reporter', old='metrics_reporter: ', new='metrics_reporter: /etc/cassandra/metrics.yaml', wrong_knob='.endpoint_snitch', wrong_old='endpoint_snitch: SimpleSnitch', wrong_new='endpoint_snitch: GossipingPropertyFileSnitch', wrong2_old='cluster_name: sandbox', wrong2_new='cluster_name: hangar', prefix='cassx'),
    dict(vendor='ScyllaDB', ok_slug='scyll-prometheus-off-leftover', bad_slug='scyll-prom-raise-dc-not-enable', noun='fishpass', panel='Scylla metrics', needle='scyll_up', lie_core='prometheus leftover prometheus_port 0 so Grafana is empty while CQL still 9042', false_lead='Scylla dc leftover', avoided=BAN, knob='.prometheus_port', old='prometheus_port: 0', new='prometheus_port: 9180', wrong_knob='.dc', wrong_old='dc: sandbox', wrong_new='dc: hangar', wrong2_old='cluster_name: sandbox', wrong2_new='cluster_name: hangar', prefix='scyll'),
    dict(vendor='CockroachDB', ok_slug='croak-metrics-bind-drop-leftover', bad_slug='croak-bind-raise-local-not-addr', noun='eelpass', panel='Cockroach metrics', needle='croak_up', lie_core='http leftover --http-addr 127.0.0.1 so Grafana is empty while SQL still 26257', false_lead='Cockroach locality leftover', avoided=BAN, knob='.http-addr', old='http-addr: 127.0.0.1:8080', new='http-addr: 0.0.0.0:8080', wrong_knob='.locality', wrong_old='locality: region=sandbox', wrong_new='locality: region=hangar', wrong2_old='store: /tmp', wrong2_new='store: /var/lib/cockroach', prefix='croak'),
    dict(vendor='Yugabyte', ok_slug='yuga-webserver-bind-drop-leftover', bad_slug='yuga-web-raise-rf-not-addr', noun='smolt', panel='Yugabyte metrics', needle='yuga_up', lie_core='web leftover --webserver_interface 127.0.0.1 so Grafana is empty while YSQL still 5433', false_lead='Yugabyte rf leftover', avoided=BAN, knob='.webserver_interface', old='webserver_interface: 127.0.0.1', new='webserver_interface: 0.0.0.0', wrong_knob='.replication_factor', wrong_old='replication_factor: 1', wrong_new='replication_factor: 3', wrong2_old='cluster_uuid: sandbox', wrong2_new='cluster_uuid: hangar', prefix='yuga'),
    dict(vendor='TiDB', ok_slug='tidbx-status-bind-drop-leftover', bad_slug='tidbx-stat-raise-pd-not-addr', noun='lamprey', panel='TiDB metrics', needle='tidbx_up', lie_core='status leftover status-host 127.0.0.1 so Grafana is empty while SQL still 4000', false_lead='TiDB pd leftover', avoided=BAN, knob='.status-host', old='status-host: 127.0.0.1', new='status-host: 0.0.0.0', wrong_knob='.pd', wrong_old='pd: sandbox:2379', wrong_new='pd: hangar:2379', wrong2_old='host: 127.0.0.1', wrong2_new='host: 0.0.0.0', prefix='tidbx'),
    dict(vendor='OceanBase', ok_slug='ocean-obagent-off-leftover', bad_slug='ocean-agt-raise-zone-not-enable', noun='debris', panel='OceanBase metrics', needle='ocean_up', lie_core='obagent leftover http_port 0 so Grafana is empty while SQL still 2881', false_lead='OceanBase zone leftover', avoided=BAN, knob='.obagent.http_port', old='http_port: 0', new='http_port: 8088', wrong_knob='.zone', wrong_old='zone: sandbox', wrong_new='zone: hangar', wrong2_old='cluster: sandbox', wrong2_new='cluster: hangar', prefix='ocean'),
    dict(vendor='SingleStore', ok_slug='sstore-exporter-off-leftover', bad_slug='sstore-exp-raise-ag-not-enable', noun='boom', panel='SingleStore metrics', needle='sstore_up', lie_core='exporter leftover http_api_enable=false so Grafana is empty while SQL still 3306', false_lead='SingleStore aggregator leftover', avoided=BAN, knob='.http_api_enable', old='http_api_enable: false', new='http_api_enable: true', wrong_knob='.aggregator', wrong_old='aggregator: sandbox', wrong_new='aggregator: hangar', wrong2_old='redundancy_level: 1', wrong2_new='redundancy_level: 2', prefix='sstore'),
    dict(vendor='VoltDB', ok_slug='voltdb-http-off-leftover', bad_slug='voltdb-http-raise-kfactor-not-enable', noun='iceboom', panel='VoltDB stats', needle='voltdb_up', lie_core='http leftover http.enabled=false so Grafana is empty while SQL still 21212', false_lead='VoltDB kfactor leftover', avoided=BAN, knob='.http.enabled', old='enabled: false', new='enabled: true', wrong_knob='.kfactor', wrong_old='kfactor: 0', wrong_new='kfactor: 1', wrong2_old='sitesperhost: 1', wrong2_new='sitesperhost: 8', prefix='voltdb'),
    dict(vendor='QuestDB', ok_slug='qestdb-metrics-off-leftover', bad_slug='qestdb-met-raise-dir-not-enable', noun='brook', panel='QuestDB metrics', needle='qestdb_up', lie_core='metrics leftover metrics.enabled=false so Grafana is empty while ILP still 9009', false_lead='QuestDB dir leftover', avoided=BAN, knob='.metrics.enabled', old='enabled: false', new='enabled: true', wrong_knob='.cairo.root', wrong_old='root: /tmp', wrong_new='root: /var/lib/questdb', wrong2_old='pg.net.bind.to: 127.0.0.1', wrong2_new='pg.net.bind.to: 0.0.0.0', prefix='qestdb'),
    dict(vendor='InfluxDB', ok_slug='influx-http-bind-drop-leftover', bad_slug='influx-http-raise-org-not-addr', noun='rivulet', panel='Influx metrics', needle='influx_up', lie_core='http leftover bind-address 127.0.0.1 so Grafana is empty while writes still 8086', false_lead='Influx org leftover', avoided=BAN, knob='.http-bind-address', old='http-bind-address: 127.0.0.1:8086', new='http-bind-address: 0.0.0.0:8086', wrong_knob='.INFLUXD_INIT_ORG', wrong_old='INFLUXD_INIT_ORG: sandbox', wrong_new='INFLUXD_INIT_ORG: hangar', wrong2_old='bolt-path: /tmp', wrong2_new='bolt-path: /var/lib/influxdb2', prefix='influx'),
    dict(vendor='Gatus', ok_slug='gatus-metrics-off-leftover', bad_slug='gatus-met-raise-ep-not-enable', noun='streamlet', panel='Gatus metrics', needle='gatus_up', lie_core='metrics leftover metrics=false so Grafana is empty while endpoints still UP', false_lead='Gatus endpoint leftover', avoided=BAN, knob='.metrics', old='metrics: false', new='metrics: true', wrong_knob='.endpoints[0].url', wrong_old='url: https://sandbox', wrong_new='url: https://hangar', wrong2_old='storage.path: /tmp', wrong2_new='storage.path: /var/lib/gatus', prefix='gatus'),
    dict(vendor='Uptime Kuma', ok_slug='ukuma-host-bind-drop-leftover', bad_slug='ukuma-host-raise-db-not-addr', noun='rill', panel='Uptime Kuma', needle='ukuma_up', lie_core='host leftover UPTIME_KUMA_HOST 127.0.0.1 so Grafana is empty while monitors still UP', false_lead='Uptime Kuma db leftover', avoided=BAN, knob='.UPTIME_KUMA_HOST', old='UPTIME_KUMA_HOST: 127.0.0.1', new='UPTIME_KUMA_HOST: 0.0.0.0', wrong_knob='.DATA_DIR', wrong_old='DATA_DIR: /tmp', wrong_new='DATA_DIR: /app/data', wrong2_old='UPTIME_KUMA_PORT: 0', wrong2_new='UPTIME_KUMA_PORT: 3001', prefix='ukuma'),
    dict(vendor='Healthchecks', ok_slug='hchk-site-root-remap-leftover', bad_slug='hchk-site-raise-db-not-remap', noun='runnel', panel='Healthchecks', needle='hchk_up', lie_core='site leftover SITE_ROOT sandbox so Grafana is the wrong dashboard while pings still 200', false_lead='Healthchecks db leftover', avoided=BAN, knob='.SITE_ROOT', old='SITE_ROOT: https://sandbox', new='SITE_ROOT: https://hangar', wrong_knob='.DB', wrong_old='DB: sqlite:////tmp/empty', wrong_new='DB: postgres://hangar', wrong2_old='EMAIL_HOST: sandbox', wrong2_new='EMAIL_HOST: hangar', prefix='hchk'),
    dict(vendor='Better Uptime', ok_slug='bupx-api-token-remap-leftover', bad_slug='bupx-tok-raise-stat-not-remap', noun='gill', panel='Better Uptime', needle='bupx_mon', lie_core='token leftover BETTERUPTIME_API_TOKEN sandbox so Grafana is the wrong dashboard while monitors still up', false_lead='Better Uptime status leftover', avoided=BAN, knob='.BETTERUPTIME_API_TOKEN', old='BETTERUPTIME_API_TOKEN: sandbox', new='BETTERUPTIME_API_TOKEN: hangar', wrong_knob='.status_page', wrong_old='status_page: sandbox', wrong_new='status_page: hangar', wrong2_old='team: sandbox', wrong2_new='team: hangar', prefix='bupx'),
    dict(vendor='OpsLevel', ok_slug='oplev-api-url-remap-leftover', bad_slug='oplev-url-raise-tok-not-remap', noun='burn', panel='OpsLevel', needle='oplev_svc', lie_core='url leftover OPSLEVEL_API_URL sandbox so Grafana is the wrong dashboard while checks still 200', false_lead='OpsLevel token leftover', avoided=BAN, knob='.OPSLEVEL_API_URL', old='OPSLEVEL_API_URL: https://sandbox', new='OPSLEVEL_API_URL: https://hangar', wrong_knob='.OPSLEVEL_API_TOKEN', wrong_old='OPSLEVEL_API_TOKEN: sandbox', wrong_new='OPSLEVEL_API_TOKEN: hangar', wrong2_old='account: sandbox', wrong2_new='account: hangar', prefix='oplev'),
    dict(vendor='Falco', ok_slug='falcox-metrics-off-leftover', bad_slug='falcox-met-raise-rule-not-enable', noun='beck', panel='Falco metrics', needle='falcox_alrt', lie_core='metrics leftover metrics.enabled=false so Grafana is empty while rules still load', false_lead='Falco rules leftover', avoided=BAN, knob='.metrics.enabled', old='enabled: false', new='enabled: true', wrong_knob='.rules_file', wrong_old='rules_file: /tmp/empty.yaml', wrong_new='rules_file: /etc/falco/falco_rules.yaml', wrong2_old='json_output: false', wrong2_new='json_output: true', prefix='falcox'),
    dict(vendor='Tracee', ok_slug='tracee-metrics-off-leftover', bad_slug='tracee-met-raise-out-not-enable', noun='killn', panel='Tracee metrics', needle='tracee_evt', lie_core='metrics leftover --metrics=false so Grafana is empty while events still print', false_lead='Tracee output leftover', avoided=BAN, knob='.metrics', old='metrics: false', new='metrics: true', wrong_knob='.output', wrong_old='output: none', wrong_new='output: json', wrong2_old='trace: sandbox', wrong2_new='trace: hangar', prefix='tracee'),
    dict(vendor='Orca', ok_slug='orcax-api-url-remap-leftover', bad_slug='orcax-url-raise-tok-not-remap', noun='arroyo', panel='Orca', needle='orcax_alrt', lie_core='api leftover ORCA_API_URL sandbox so Grafana is the wrong dashboard while alerts still 200', false_lead='Orca token leftover', avoided=BAN, knob='.ORCA_API_URL', old='ORCA_API_URL: https://sandbox', new='ORCA_API_URL: https://hangar', wrong_knob='.ORCA_API_TOKEN', wrong_old='ORCA_API_TOKEN: sandbox', wrong_new='ORCA_API_TOKEN: hangar', wrong2_old='account: sandbox', wrong2_new='account: hangar', prefix='orcax'),
    dict(vendor='CrowdStrike', ok_slug='crwd-cloud-remap-leftover', bad_slug='crwd-cld-raise-cid-not-remap', noun='wadi', panel='CrowdStrike', needle='crwd_evt', lie_core='cloud leftover FALCON_CLOUD sandbox so Grafana is the wrong dashboard while detections still 200', false_lead='CrowdStrike cid leftover', avoided=BAN, knob='.FALCON_CLOUD', old='FALCON_CLOUD: sandbox', new='FALCON_CLOUD: us-1', wrong_knob='.cid', wrong_old='cid: sandbox', wrong_new='cid: hangar', wrong2_old='FALCON_CLIENT_ID: sandbox', wrong2_new='FALCON_CLIENT_ID: hangar', prefix='crwd'),
    dict(vendor='Carbon Black', ok_slug='cblack-org-remap-leftover', bad_slug='cblack-org-raise-url-not-remap', noun='nullah', panel='Carbon Black', needle='cblack_evt', lie_core='org leftover CB_ORG_KEY sandbox so Grafana is the wrong dashboard while alerts still 200', false_lead='Carbon Black url leftover', avoided=BAN, knob='.CB_ORG_KEY', old='CB_ORG_KEY: sandbox', new='CB_ORG_KEY: hangar', wrong_knob='.CB_API_URL', wrong_old='CB_API_URL: https://sandbox', wrong_new='CB_API_URL: https://hangar', wrong2_old='CB_API_ID: sandbox', wrong2_new='CB_API_ID: hangar', prefix='cblack'),
    dict(vendor='wasmer', ok_slug='wasmr-log-drop-leftover', bad_slug='wasmr-log-raise-cache-not-log', noun='anabranch', panel='wasmer log', needle='wasmr_mod', lie_core='log leftover WASMER_LOG empty so Grafana is empty while modules still instantiate', false_lead='wasmer cache leftover', avoided=BAN, knob='.WASMER_LOG', old='WASMER_LOG: ', new='WASMER_LOG: info', wrong_knob='.cache', wrong_old='cache: /tmp/empty', wrong_new='cache: ~/.wasmer/cache', wrong2_old='dir: /tmp', wrong2_new='dir: /var/lib/wasmer', prefix='wasmr'),
    dict(vendor='wasmCloud', ok_slug='wcloud-observability-off-leftover', bad_slug='wcloud-obs-raise-lat-not-enable', noun='yazoo', panel='wasmCloud metrics', needle='wcloud_up', lie_core='observability leftover WASMCLOUD_OBSERVABILITY=false so Grafana is empty while actors still start', false_lead='wasmCloud lattice leftover', avoided=BAN, knob='.WASMCLOUD_OBSERVABILITY', old='WASMCLOUD_OBSERVABILITY: false', new='WASMCLOUD_OBSERVABILITY: true', wrong_knob='.WASMCLOUD_LATTICE', wrong_old='WASMCLOUD_LATTICE: sandbox', wrong_new='WASMCLOUD_LATTICE: hangar', wrong2_old='WASMCLOUD_HOST: 127.0.0.1', wrong2_new='WASMCLOUD_HOST: 0.0.0.0', prefix='wcloud'),
    dict(vendor='Spin', ok_slug='spinf-log-dir-drop-leftover', bad_slug='spinf-log-raise-env-not-dir', noun='creeklet', panel='Spin log', needle='spinf_app', lie_core='log leftover SPIN_LOG_DIR /dev/null so Grafana is empty while components still 200', false_lead='Spin env leftover', avoided=BAN, knob='.SPIN_LOG_DIR', old='SPIN_LOG_DIR: /dev/null', new='SPIN_LOG_DIR: /var/log/spin', wrong_knob='.SPIN_ENVIRONMENT', wrong_old='SPIN_ENVIRONMENT: sandbox', wrong_new='SPIN_ENVIRONMENT: hangar', wrong2_old='SPIN_DISABLE_UI: true', wrong2_new='SPIN_DISABLE_UI: false', prefix='spinf'),
    dict(vendor='Fermyon', ok_slug='fermy-hippo-bind-drop-leftover', bad_slug='fermy-hip-raise-env-not-addr', noun='headwater', panel='Fermyon', needle='fermy_app', lie_core='hippo leftover bind 127.0.0.1 so Grafana is empty while Spin still 80', false_lead='Fermyon env leftover', avoided=BAN, knob='.HIPPO_URL', old='HIPPO_URL: http://127.0.0.1', new='HIPPO_URL: http://0.0.0.0', wrong_knob='.FERMYON_ENV', wrong_old='FERMYON_ENV: sandbox', wrong_new='FERMYON_ENV: hangar', wrong2_old='BINDLE_URL: http://sandbox', wrong2_new='BINDLE_URL: http://hangar', prefix='fermy'),
    dict(vendor='StreamSets', ok_slug='ssets-metrics-off-leftover', bad_slug='ssets-met-raise-sdc-not-enable', noun='mouthbar', panel='StreamSets', needle='ssets_up', lie_core='metrics leftover sdc.metrics.enable=false so Grafana is empty while pipelines still RUNNING', false_lead='StreamSets sdc leftover', avoided=BAN, knob='.sdc.metrics.enable', old='enable: false', new='enable: true', wrong_knob='.sdc.base.http.url', wrong_old='url: http://sandbox', wrong_new='url: http://hangar', wrong2_old='http.bind: 127.0.0.1', wrong2_new='http.bind: 0.0.0.0', prefix='ssets'),
    dict(vendor='Talend', ok_slug='talnd-log4j-drop-leftover', bad_slug='talnd-log-raise-ctx-not-level', noun='poolriff', panel='Talend', needle='talnd_job', lie_core='log leftover log4j.rootLogger=OFF so Grafana is empty while jobs still ok', false_lead='Talend context leftover', avoided=BAN, knob='.log4j.rootLogger', old='rootLogger: OFF', new='rootLogger: INFO', wrong_knob='.context', wrong_old='context: sandbox', wrong_new='context: hangar', wrong2_old='job: sandbox', wrong2_new='job: hangar', prefix='talnd'),
    dict(vendor='Kettle', ok_slug='kettl-log-level-drop-leftover', bad_slug='kettl-log-raise-rep-not-level', noun='glide', panel='Kettle', needle='kettl_tr', lie_core='log leftover KETTLE_LOG_LEVEL=Nothing so Grafana is empty while transformations still Finished', false_lead='Kettle repo leftover', avoided=BAN, knob='.KETTLE_LOG_LEVEL', old='KETTLE_LOG_LEVEL: Nothing', new='KETTLE_LOG_LEVEL: Basic', wrong_knob='.KETTLE_HOME', wrong_old='KETTLE_HOME: /tmp', wrong_new='KETTLE_HOME: ~/.kettle', wrong2_old='repo: sandbox', wrong2_new='repo: hangar', prefix='kettl'),
    dict(vendor='Kudu', ok_slug='kudux-webserver-bind-drop-leftover', bad_slug='kudux-web-raise-fs-not-addr', noun='pocket', panel='Kudu metrics', needle='kudux_up', lie_core='web leftover --webserver_interface 127.0.0.1 so Grafana is empty while tablets still RUNNING', false_lead='Kudu fs leftover', avoided=BAN, knob='.webserver_interface', old='webserver_interface: 127.0.0.1', new='webserver_interface: 0.0.0.0', wrong_knob='.fs_wal_dir', wrong_old='fs_wal_dir: /tmp', wrong_new='fs_wal_dir: /var/lib/kudu', wrong2_old='fs_data_dirs: /tmp', wrong2_new='fs_data_dirs: /var/lib/kudu', prefix='kudux'),
    dict(vendor='Phoenix', ok_slug='phoen-query-timeout-drop-leftover', bad_slug='phoen-to-raise-zk-not-timeout', noun='eddylet', panel='Phoenix', needle='phoen_up', lie_core='timeout leftover phoenix.query.timeoutMs 1 so Grafana is empty while SQL still 8765', false_lead='Phoenix zk leftover', avoided=BAN, knob='.phoenix.query.timeoutMs', old='timeoutMs: 1', new='timeoutMs: 60000', wrong_knob='.hbase.zookeeper.quorum', wrong_old='quorum: sandbox', wrong_new='quorum: hangar', wrong2_old='phoenix.query.keepAlive: 0', wrong2_new='phoenix.query.keepAlive: 1', prefix='phoen'),
    dict(vendor='Select Star', ok_slug='sstar-api-url-remap-leftover', bad_slug='sstar-url-raise-tok-not-remap', noun='whirl', panel='Select Star', needle='sstar_lin', lie_core='api leftover SELECTSTAR_API_URL sandbox so Grafana is the wrong dashboard while lineage still 200', false_lead='Select Star token leftover', avoided=BAN, knob='.SELECTSTAR_API_URL', old='SELECTSTAR_API_URL: https://sandbox', new='SELECTSTAR_API_URL: https://hangar', wrong_knob='.SELECTSTAR_API_TOKEN', wrong_old='SELECTSTAR_API_TOKEN: sandbox', wrong_new='SELECTSTAR_API_TOKEN: hangar', wrong2_old='workspace: sandbox', wrong2_new='workspace: hangar', prefix='sstar'),
    dict(vendor='DuckDB', ok_slug='duckdb-log-query-off-leftover', bad_slug='duckdb-log-raise-mem-not-enable', noun='vortex', panel='DuckDB', needle='duckdb_q', lie_core='log leftover enable_progress_bar=false plus log empty so Grafana is empty while SQL still runs', false_lead='DuckDB mem leftover', avoided=BAN, knob='.enable_progress_bar', old='enable_progress_bar: false', new='enable_progress_bar: true', wrong_knob='.memory_limit', wrong_old='memory_limit: 1MB', wrong_new='memory_limit: 8GB', wrong2_old='temp_directory: /tmp', wrong2_new='temp_directory: /var/lib/duckdb', prefix='duckdb'),
    dict(vendor='DataFusion', ok_slug='dfuse-explain-off-leftover', bad_slug='dfuse-exp-raise-batch-not-enable', noun='maelstrom', panel='DataFusion', needle='dfuse_q', lie_core='explain leftover datafusion.explain.logical_plan_only plus collect off so Grafana is empty', false_lead='DataFusion batch leftover', avoided=BAN, knob='.datafusion.explain.show_statistics', old='show_statistics: false', new='show_statistics: true', wrong_knob='.datafusion.execution.batch_size', wrong_old='batch_size: 1', wrong_new='batch_size: 8192', wrong2_old='datafusion.optimizer: sandbox', wrong2_new='datafusion.optimizer: hangar', prefix='dfuse'),
    dict(vendor='Polars', ok_slug='polar-verbose-off-leftover', bad_slug='polar-verb-raise-th-not-enable', noun='cataract', panel='Polars', needle='polar_q', lie_core='verbose leftover POLARS_VERBOSE=0 so Grafana is empty while frames still collect', false_lead='Polars threads leftover', avoided=BAN, knob='.POLARS_VERBOSE', old='POLARS_VERBOSE: 0', new='POLARS_VERBOSE: 1', wrong_knob='.POLARS_MAX_THREADS', wrong_old='POLARS_MAX_THREADS: 1', wrong_new='POLARS_MAX_THREADS: 8', wrong2_old='POLARS_TEMP_DIR: /tmp', wrong2_new='POLARS_TEMP_DIR: /var/lib/polars', prefix='polar'),
    dict(vendor='Apache Flink', ok_slug='flinkx-reporters-drop-leftover', bad_slug='flinkx-rep-raise-tm-not-reporter', noun='falls', panel='Flink metrics', needle='flinkx_up', lie_core='reporter leftover metrics.reporters empty so Grafana is empty while jobs still RUNNING', false_lead='Flink tm leftover', avoided=BAN, knob='.metrics.reporters', old='reporters: ', new='reporters: prom', wrong_knob='.taskmanager.numberOfTaskSlots', wrong_old='numberOfTaskSlots: 1', wrong_new='numberOfTaskSlots: 8', wrong2_old='jobmanager.rpc.address: sandbox', wrong2_new='jobmanager.rpc.address: hangar', prefix='flinkx'),
    dict(vendor='Apache Spark', ok_slug='sparkx-metrics-off-leftover', bad_slug='sparkx-met-raise-ms-not-enable', noun='stairstep', panel='Spark metrics', needle='sparkx_up', lie_core='metrics leftover spark.metrics.conf empty so Grafana is empty while jobs still SUCCEEDED', false_lead='Spark master leftover', avoided=BAN, knob='.spark.metrics.conf', old='conf: ', new='conf: /etc/spark/metrics.properties', wrong_knob='.spark.master', wrong_old='master: local[1]', wrong_new='master: spark://hangar:7077', wrong2_old='spark.app.name: sandbox', wrong2_new='spark.app.name: hangar', prefix='sparkx'),
    dict(vendor='Apache Beam', ok_slug='beamx-metrics-off-leftover', bad_slug='beamx-met-raise-run-not-enable', noun='nickpoint', panel='Beam metrics', needle='beamx_up', lie_core='metrics leftover enable_metrics=false so Grafana is empty while pipelines still DONE', false_lead='Beam runner leftover', avoided=BAN, knob='.enable_metrics', old='enable_metrics: false', new='enable_metrics: true', wrong_knob='.runner', wrong_old='runner: DirectRunner', wrong_new='runner: DataflowRunner', wrong2_old='project: sandbox', wrong2_new='project: hangar', prefix='beamx'),
]

assert len(SPECS) == 88, len(SPECS)
for i, spec in enumerate(SPECS):
    _l14(1260 + i, **spec)
