"""Observability plants r211+ (4 pad pairs occupy already-published r207–r210 indices).

Ban r163 tid128, r172 inferred db, r190 UST/namespace/peer.service leftover.
"""

from mill_plants import _fail, _ok

MORE = []


def _okp(**kw):
    dash = kw["dashboard_uid"]
    kw.setdefault(
        "search_cmd",
        f"curl -sS $GRAFANA/api/search?query={dash} | jq -c '.[]|{{uid,title}}'",
    )
    kw.setdefault(
        "dash_cmd",
        f"curl -sS $GRAFANA/api/dashboards/uid/{dash} | jq '.dashboard.panels[0]'",
    )
    return _ok(**kw)


def _failp(**kw):
    dash = kw["dashboard_uid"]
    ticket = kw["ticket"]
    xfail = kw["xfail"]
    py = kw["slug"].replace("-", "_")
    kw.setdefault(
        "search_cmd",
        f"curl -sS $GRAFANA/api/search?query={dash} | jq -c '.[]|{{uid,title}}'",
    )
    kw.setdefault(
        "dash_cmd",
        f"curl -sS $GRAFANA/api/dashboards/uid/{dash} | jq '.dashboard.panels[0]'",
    )
    kw.setdefault("ticket_path", f"tickets/{ticket}.md")
    kw.setdefault(
        "xfail_cmd",
        (
            "printf '%s\\n' "
            f"'@pytest.mark.xfail(reason=\"{ticket}\")\\n"
            f"def test_{py}():\\n    assert False' > {xfail}"
        ),
    )
    return _fail(**kw)


# Pad r207–r210 indices (already published as asserts/alloy/vparquet/exemplar).
MORE.append(
    (
        _okp(
            slug="otel-arrow-vs-otlp-proto",
            service="arrow-encode-svc",
            dashboard_uid="arrow-otlp-31",
            panel="ingest errors",
            query='sum(rate(otelcol_exporter_send_failed_spans_total{service="arrow-encode-svc"}[5m]))',
            lie="collector exporter is otlphttp/protobuf but downstream gateway only accepts otlparrow so send_failed_spans climbs and Grafana ingest is empty",
            false_lead="memory_limiter refused_spans",
            config_path="otelcol/arrow-mem.yaml",
            lie_path="otelcol/arrow-exporter.yaml",
            truth_name="exporter protocol vs gateway",
            reload_name="otelcol-arrow",
            side="otlparrow-native collectors still succeed",
            surfaces="OTel otlp protobuf vs arrow gateway",
            avoided="r198 memory_limiter; r221 loadbalancing",
            this_is="otlphttp/protobuf into an arrow-only gateway",
            step_note="False lead limiter 4-5; exporter proto 6-8; arrow 9-12.",
            query_cmd="curl -sS -G $MIMIR/prometheus/api/v1/query --data-urlencode 'query=sum(rate(otelcol_exporter_send_failed_spans_total{service=\"arrow-encode-svc\"}[5m]))'",
            false_cmd="yq '.processors.memory_limiter' otelcol/arrow-mem.yaml",
            truth_cmd="yq '.exporters.otlphttp.encoding, .exporters.otlphttp.endpoint' otelcol/arrow-exporter.yaml",
            confirm_cmd="curl -sS $GATEWAY/health | jq '.accepted_encodings'",
            reload_cmd="kubectl -n otel rollout restart deploy/otelcol-arrow && kubectl -n otel rollout status deploy/otelcol-arrow --timeout=90s",
            requery_cmd="curl -sS -G $MIMIR/prometheus/api/v1/query --data-urlencode 'query=sum(rate(traces_span_metrics_calls_total{service_name=\"arrow-encode-svc\"}[5m]))'",
            grafana_ok_cmd="curl -sS $GRAFANA/api/ds/query -d @/tmp/arrow.json | jq '.results.A.frames[0].data.values'",
            side_cmd="curl -sS -G $MIMIR/prometheus/api/v1/query --data-urlencode 'query=sum(rate(traces_span_metrics_calls_total{service_name=\"ssr-meal-svc\"}[5m]))' | jq '.data.result[0].value'",
            final_cmd="yq '.exporters.otlphttp.encoding' otelcol/arrow-exporter.yaml",
            patch_old="encoding: proto",
            patch_new="encoding: arrow",
            runbook_path="runbooks/arrow-otlp.md",
            runbook="# arrow-encode-svc protobuf vs arrow\nGateway accepts otlparrow only. Set exporter encoding arrow.\nNot memory_limiter.\n",
            goal="arrow-encode-svc dashboard arrow-otlp-31 ingest errors climb. Fix exporter encoding.",
            plan="send_failed → not limiter → proto vs arrow → encoding arrow.",
            outcome="encoding arrow. Ingest fills. other collectors unchanged.",
            obs1='[{"uid":"arrow-otlp-31","title":"arrow ingest"}]',
            obs2='{"title":"ingest errors","targets":[{"expr":"sum(rate(otelcol_exporter_send_failed_spans_total{service=\\"arrow-encode-svc\\"}[5m]))"}]}',
            obs3='{"status":"success","data":{"result":[{"value":[1710000000,"40"]}]}}',
            obs4="limit_mib: 512\n# limiter healthy",
            obs5="not limiter",
            obs6="encoding: proto\nendpoint: gateway:4318",
            obs7='{"accepted_encodings":["arrow"]}',
            obs8="protobuf into arrow-only gateway",
            obs9="patched encoding arrow",
            obs10='deployment "otelcol-arrow" successfully rolled out',
            obs11='{"status":"success","data":{"result":[{"value":[1710000600,"42.0"]}]}}',
            obs12="[[1710000600],[42.0]]",
            obs13='["1710000600","19.4"]',
            obs14="wrote runbooks/arrow-otlp.md",
            obs15="arrow",
        ),
        _failp(
            slug="otel-arrow-raise-memlimiter",
            service="arrow-encode-bag-svc",
            dashboard_uid="arrow-mem-raise",
            panel="bag ingest errors",
            query='sum(rate(otelcol_exporter_send_failed_spans_total{service="arrow-encode-bag-svc"}[5m]))',
            lie="Raising memory_limiter does not fix otlp protobuf into an arrow-only gateway",
            false_lead="memory_limiter too small",
            config_path="otelcol/arrow-bag-mem.yaml",
            lie_path="otelcol/arrow-bag-exporter.yaml",
            wrong_path="otelcol/arrow-bag-mem.yaml",
            reload_name="otelcol-arrow-bag",
            ticket="OBS-4491",
            xfail="tests/test_arrow_bag.py",
            surfaces="limiter leftover vs protobuf/arrow",
            avoided="memory_limiter as actual RCA",
            this_is="fail/handoff: limiter 1024, still proto vs arrow",
            step_note="limiter 6-10; still failed 11; late encoding 12; handoff 14-15.",
            next_note="Next: PagerDuty CEF vs AM labels.",
            query_cmd="curl -sS -G $MIMIR/prometheus/api/v1/query --data-urlencode 'query=sum(rate(otelcol_exporter_send_failed_spans_total{service=\"arrow-encode-bag-svc\"}[5m]))'",
            false_cmd="yq '.processors.memory_limiter.limit_mib' otelcol/arrow-bag-mem.yaml",
            reload_cmd="kubectl -n otel rollout restart deploy/otelcol-arrow-bag && kubectl -n otel rollout status deploy/otelcol-arrow-bag --timeout=90s",
            requery_cmd="curl -sS -G $MIMIR/prometheus/api/v1/query --data-urlencode 'query=sum(rate(otelcol_exporter_send_failed_spans_total{service=\"arrow-encode-bag-svc\"}[5m]))'",
            denied_cmd="kubectl -n otel auth can-i patch configmap/arrow-bag-exporter --as=sre-bot",
            wrong_old="limit_mib: 128",
            wrong_new="limit_mib: 1024",
            wrong2_old="spike_limit_mib: 32",
            wrong2_new="spike_limit_mib: 256",
            ticket_body="OBS-4491: arrow-encode-bag-svc still send_failed. encoding proto vs arrow gateway. Need encoding arrow. No exporter RBAC.\n",
            goal="arrow-encode-bag-svc dashboard arrow-mem-raise bag ingest errors stay high. Restore ingest.",
            plan="Raise memory_limiter.",
            outcome="1024MiB; still failed. Late encoding proto. Handoff OBS-4491.",
            obs1='[{"uid":"arrow-mem-raise","title":"arrow bag"}]',
            obs2='{"title":"bag ingest errors","targets":[{"expr":"sum(rate(otelcol_exporter_send_failed_spans_total{service=\\"arrow-encode-bag-svc\\"}[5m]))"}]}',
            obs3='{"status":"success","data":{"result":[{"value":[1710000000,"33"]}]}}',
            obs4="128",
            obs5="limiter 128 — treated as RCA",
            obs6="otelcol/arrow-bag-mem.yaml",
            obs7="patched 1024",
            obs8='deployment "otelcol-arrow-bag" successfully rolled out',
            obs9='{"status":"success","data":{"result":[{"value":[1710000600,"33"]}]}}',
            obs10="patched spike 256",
            obs11='{"status":"success","data":{"result":[{"value":[1710000900,"33"]}]}}',
            obs12="otelcol/arrow-bag-exporter.yaml encoding proto; gateway arrow",
            obs13="no",
            obs14="wrote tickets/OBS-4491.md",
            obs15="xfail tests/test_arrow_bag.py",
        ),
    )
)

MORE.append(
    (
        _okp(
            slug="pd-cef-vs-am-labels",
            service="pd-cef-svc",
            dashboard_uid="pd-cef-32",
            panel="pages by service",
            query='sum by (service) (count_over_time(pagerduty_incidents{service="pd-cef-svc"}[1h]))',
            lie="PagerDuty event orchestration CEF payload has routing_key but not service so Grafana {service=} is empty while PD UI shows incidents",
            false_lead="AM inhibit / IRM group_by omitting service",
            config_path="am/pd-inhibit.yaml",
            lie_path="pd/orchestration-cef.yaml",
            truth_name="PD CEF fields vs AM labels",
            reload_name="pd-events-orchestration",
            side="AM-native routes still labeled by service",
            surfaces="PagerDuty CEF vs AM service label",
            avoided="AM inhibit; r159 IRM group_by; r193 slack grouping",
            this_is="PD CEF missing service field",
            step_note="False lead inhibit 4-5; CEF fields 6-8; add service 9-12.",
            query_cmd="curl -sS -G $MIMIR/prometheus/api/v1/query --data-urlencode 'query=sum by (service) (count_over_time(pagerduty_incidents{service=\"pd-cef-svc\"}[1h]))'",
            false_cmd="amtool inhibit query service=pd-cef-svc --alertmanager.url=$AM",
            truth_cmd="curl -sS $PD/incidents?service=pd-cef-svc | jq '.[0]|{id,cef}'",
            confirm_cmd="yq '.cef.fields, .routing_key' pd/orchestration-cef.yaml",
            reload_cmd="kubectl -n pd rollout restart deploy/pd-events-orchestration && kubectl -n pd rollout status deploy/pd-events-orchestration --timeout=90s",
            requery_cmd="curl -sS -G $MIMIR/prometheus/api/v1/query --data-urlencode 'query=sum by (service) (count_over_time(pagerduty_incidents{service=\"pd-cef-svc\"}[10m]))'",
            grafana_ok_cmd="curl -sS $GRAFANA/api/ds/query -d @/tmp/pd.json | jq '.results.A.frames[0].schema'",
            side_cmd="amtool query alertname=PDNative --alertmanager.url=$AM | jq '.[0].labels.service'",
            final_cmd="yq '.cef.fields[]' pd/orchestration-cef.yaml",
            patch_old="fields: [severity, routing_key]",
            patch_new="fields: [severity, routing_key, service]",
            runbook_path="runbooks/pd-cef.md",
            runbook="# pd-cef-svc CEF fields\nCEF omitted service. Add service to CEF fields.\nNot AM inhibit.\n",
            goal="pd-cef-svc dashboard pd-cef-32 pages by service is empty while PD has incidents. Fix CEF fields.",
            plan="Empty by-service → not inhibit → CEF missing service → add field.",
            outcome="CEF includes service. Panel series fills. AM-native routes unchanged.",
            obs1='[{"uid":"pd-cef-32","title":"pd cef pages"}]',
            obs2='{"title":"pages by service","targets":[{"expr":"sum by (service) (count_over_time(pagerduty_incidents{service=\\"pd-cef-svc\\"}[1h]))"}]}',
            obs3='{"status":"success","data":{"result":[]}}',
            obs4="0 rows (no inhibit)",
            obs5="inhibit empty",
            obs6="fields: [severity, routing_key]\nrouting_key: RXXXX",
            obs7='{"id":"PXXXX","cef":{"severity":"error","routing_key":"RXXXX"}}',
            obs8="CEF has no service field",
            obs9="patched fields += service",
            obs10='deployment "pd-events-orchestration" successfully rolled out',
            obs11='{"status":"success","data":{"result":[{"metric":{"service":"pd-cef-svc"},"value":[1710000600,"7"]}]}}',
            obs12='{"name":"pages by service"}',
            obs13='"pd-native-svc"',
            obs14="wrote runbooks/pd-cef.md",
            obs15="service",
        ),
        _failp(
            slug="pd-patch-irm-group-not-cef",
            service="pd-cef-bag-svc",
            dashboard_uid="pd-irm-grp",
            panel="bag pages by service",
            query='sum by (service) (count_over_time(pagerduty_incidents{service="pd-cef-bag-svc"}[1h]))',
            lie="Adding service to IRM group_by does not label PagerDuty CEF payloads that omit service",
            false_lead="IRM group_by missing service",
            config_path="helm/grafana-irm/pd-bag.yaml",
            lie_path="pd/bag-cef.yaml",
            wrong_path="helm/grafana-irm/pd-bag.yaml",
            reload_name="grafana-irm",
            ticket="OBS-4492",
            xfail="tests/test_pd_bag.py",
            surfaces="IRM group_by leftover vs PD CEF",
            avoided="r159 as actual RCA",
            this_is="fail/handoff: IRM group_by patched, CEF still omits service",
            step_note="IRM 6-10; still empty 11; late CEF 12; handoff 14-15.",
            next_note="Next: NR Infinite Tracing vs Tempo.",
            query_cmd="curl -sS -G $MIMIR/prometheus/api/v1/query --data-urlencode 'query=sum by (service) (count_over_time(pagerduty_incidents{service=\"pd-cef-bag-svc\"}[1h]))'",
            false_cmd="yq '.escalation.group_by' helm/grafana-irm/pd-bag.yaml",
            reload_cmd="kubectl -n irm rollout restart deploy/grafana-oncall && kubectl -n irm rollout status deploy/grafana-oncall --timeout=90s",
            requery_cmd="curl -sS -G $MIMIR/prometheus/api/v1/query --data-urlencode 'query=sum by (service) (count_over_time(pagerduty_incidents{service=\"pd-cef-bag-svc\"}[10m]))'",
            denied_cmd="kubectl -n pd auth can-i patch configmap/bag-cef --as=sre-bot",
            wrong_old="group_by: [alertname, cluster]",
            wrong_new="group_by: [alertname, cluster, service]",
            wrong2_old="source: grafana_alerting",
            wrong2_new="source: alertmanager",
            ticket_body="OBS-4492: pd-cef-bag-svc still empty. CEF omits service. Need CEF fields. No PD RBAC.\n",
            goal="pd-cef-bag-svc dashboard pd-irm-grp bag pages by service is empty. Restore series.",
            plan="Patch IRM group_by (r159 leftover).",
            outcome="IRM has service; CEF still omits it. Handoff OBS-4492.",
            obs1='[{"uid":"pd-irm-grp","title":"pd bag cef"}]',
            obs2='{"title":"bag pages by service","targets":[{"expr":"sum by (service) (count_over_time(pagerduty_incidents{service=\\"pd-cef-bag-svc\\"}[1h]))"}]}',
            obs3='{"status":"success","data":{"result":[]}}',
            obs4="[alertname, cluster]",
            obs5="IRM omits service — treated as r159",
            obs6="helm/grafana-irm/pd-bag.yaml",
            obs7="patched group_by += service",
            obs8='deployment "grafana-oncall" successfully rolled out',
            obs9='{"status":"success","data":{"result":[]}}',
            obs10="patched source alertmanager",
            obs11='{"status":"success","data":{"result":[]}}',
            obs12="pd/bag-cef.yaml fields [severity, routing_key]",
            obs13="no",
            obs14="wrote tickets/OBS-4492.md",
            obs15="xfail tests/test_pd_bag.py",
        ),
    )
)

MORE.append(
    (
        _okp(
            slug="nr-infinite-vs-tempo-tail",
            service="nr-infinite-svc",
            dashboard_uid="nr-infinite-33",
            panel="nr traces",
            query='{resource.service.name="nr-infinite-svc"}',
            lie="New Relic Infinite Tracing trace-observer holds spans until 20s so Tempo 5m Grafana search is empty while NR UI shows complete traces",
            false_lead="OTel tail sampling decision_wait / Tempo service_graphs wait",
            config_path="otelcol/nr-tail.yaml",
            lie_path="k8s/nr/infinite.yaml",
            truth_name="Infinite Tracing flush vs Tempo",
            reload_name="nr-trace-observer",
            side="non-Infinite NR APM still in Tempo immediately",
            surfaces="NR Infinite Tracing hold vs Tempo 5m search",
            avoided="OTel tail decision_wait; r200 service_graphs wait; r184 NR spanId",
            this_is="Infinite Tracing 20s hold empties a 5m Tempo panel",
            step_note="False lead tail wait 4-5; infinite flush 6-8; 500ms 9-12.",
            query_cmd="curl -sS -G $TEMPO/api/search --data-urlencode 'q={resource.service.name=\"nr-infinite-svc\"}' | jq '.traces|length'",
            false_cmd="yq '.processors.tail_sampling.decision_wait' otelcol/nr-tail.yaml",
            truth_cmd="yq '.infiniteTracing.flushInterval, .infiniteTracing.traceObserver.host' k8s/nr/infinite.yaml",
            confirm_cmd="curl -sS $NR/v1/traces?app=nr-infinite-svc | jq '.[0]|{spanCount,heldMs}'",
            reload_cmd="kubectl -n nr rollout restart deploy/nr-trace-observer && kubectl -n nr rollout status deploy/nr-trace-observer --timeout=90s",
            requery_cmd="curl -sS -G $TEMPO/api/search --data-urlencode 'q={resource.service.name=\"nr-infinite-svc\"}' | jq '.traces|length'",
            grafana_ok_cmd="curl -sS $GRAFANA/api/ds/query -d @/tmp/nri.json | jq '.results.A.frames[0].schema'",
            side_cmd="curl -sS -G $TEMPO/api/search --data-urlencode 'q={resource.service.name=\"lounge-wifi-svc\"}' | jq '.traces|length'",
            final_cmd="yq '.infiniteTracing.flushInterval' k8s/nr/infinite.yaml",
            patch_old="flushInterval: 20s",
            patch_new="flushInterval: 500ms",
            runbook_path="runbooks/nr-infinite.md",
            runbook="# nr-infinite-svc Infinite Tracing\nflushInterval 20s hid traces from a 5m Tempo panel. Set 500ms.\nNot tail decision_wait and not NR spanId join.\n",
            goal="nr-infinite-svc dashboard nr-infinite-33 nr traces is empty in Tempo. NR UI is full. Fix flush.",
            plan="Empty Tempo → not tail wait → Infinite 20s → 500ms.",
            outcome="flush 500ms. Tempo 40 traces. non-Infinite NR unchanged.",
            obs1='[{"uid":"nr-infinite-33","title":"nr infinite traces"}]',
            obs2='{"title":"nr traces","targets":[{"query":"{resource.service.name=\\"nr-infinite-svc\\"}"}]}',
            obs3="0",
            obs4="decision_wait: 10s\n# already long — not tail RCA",
            obs5="tail wait fine",
            obs6="flushInterval: 20s\nhost: nr-observer.nr:443",
            obs7='{"spanCount":22,"heldMs":19800}',
            obs8="Infinite hold 20s vs 5m panel pairing miss on recent traces",
            obs9="patched flushInterval 500ms",
            obs10='deployment "nr-trace-observer" successfully rolled out',
            obs11="40",
            obs12='{"name":"Traces"}',
            obs13="18",
            obs14="wrote runbooks/nr-infinite.md",
            obs15="500ms",
        ),
        _failp(
            slug="nr-infinite-raise-tail-wait",
            service="nr-infinite-bag-svc",
            dashboard_uid="nr-inf-tail",
            panel="bag nr traces",
            query='{resource.service.name="nr-infinite-bag-svc"}',
            lie="Raising OTel tail decision_wait does not flush New Relic Infinite Tracing's 20s hold",
            false_lead="tail sampling decision_wait too short",
            config_path="otelcol/nr-bag-tail.yaml",
            lie_path="k8s/nr/bag-infinite.yaml",
            wrong_path="otelcol/nr-bag-tail.yaml",
            reload_name="otelcol-nr-bag",
            ticket="OBS-4493",
            xfail="tests/test_nr_inf_bag.py",
            surfaces="tail wait leftover vs Infinite Tracing flush",
            avoided="tail decision_wait as actual RCA",
            this_is="fail/handoff: decision_wait 30s, Infinite still 20s",
            step_note="tail wait 6-10; still 0 11; late infinite yaml 12; handoff 14-15.",
            next_note="Next: Mimir query-frontend max_query_lookback vs Grafana.",
            query_cmd="curl -sS -G $TEMPO/api/search --data-urlencode 'q={resource.service.name=\"nr-infinite-bag-svc\"}' | jq '.traces|length'",
            false_cmd="yq '.processors.tail_sampling.decision_wait' otelcol/nr-bag-tail.yaml",
            reload_cmd="kubectl -n otel rollout restart deploy/otelcol-nr-bag && kubectl -n otel rollout status deploy/otelcol-nr-bag --timeout=90s",
            requery_cmd="curl -sS -G $TEMPO/api/search --data-urlencode 'q={resource.service.name=\"nr-infinite-bag-svc\"}' | jq '.traces|length'",
            denied_cmd="kubectl -n nr auth can-i patch deploy/nr-trace-observer --as=sre-bot",
            wrong_old="decision_wait: 2s",
            wrong_new="decision_wait: 30s",
            wrong2_old="expected_new_traces_per_sec: 100",
            wrong2_new="expected_new_traces_per_sec: 10",
            ticket_body="OBS-4493: nr-infinite-bag-svc still 0. Infinite flushInterval 20s. Need 500ms. No NR RBAC.\n",
            goal="nr-infinite-bag-svc dashboard nr-inf-tail bag nr traces is empty. Restore Tempo search.",
            plan="Raise tail decision_wait (banned tail RCA).",
            outcome="30s wait; still 0. Late Infinite 20s. Handoff OBS-4493.",
            obs1='[{"uid":"nr-inf-tail","title":"nr bag infinite"}]',
            obs2='{"title":"bag nr traces","targets":[{"query":"{resource.service.name=\\"nr-infinite-bag-svc\\"}"}]}',
            obs3="0",
            obs4="2s",
            obs5="decision_wait 2s — treated as tail RCA",
            obs6="otelcol/nr-bag-tail.yaml",
            obs7="patched 30s",
            obs8='deployment "otelcol-nr-bag" successfully rolled out',
            obs9="0",
            obs10="patched expected_new_traces 10",
            obs11="0",
            obs12="k8s/nr/bag-infinite.yaml flushInterval 20s",
            obs13="no",
            obs14="wrote tickets/OBS-4493.md",
            obs15="xfail tests/test_nr_inf_bag.py",
        ),
    )
)

MORE.append(
    (
        _okp(
            slug="mimir-lookback-vs-grafana-range",
            service="mimir-lookback-svc",
            dashboard_uid="mimir-lookback-34",
            panel="30d p99",
            query='histogram_quantile(0.99, sum by (le) (rate(http_req_seconds_bucket{service="mimir-lookback-svc"}[30d])))',
            lie="Mimir query-frontend max_query_lookback is 7d so Grafana 30d p99 is empty while 24h panel is full",
            false_lead="Mimir max_label_names_per_series / native vs classic histogram",
            config_path="mimir/lookback-limits.yaml",
            lie_path="mimir/lookback-frontend.yaml",
            truth_name="max_query_lookback vs dashboard range",
            reload_name="mimir-query-frontend",
            side="24h panels still work",
            surfaces="Mimir max_query_lookback vs Grafana 30d range",
            avoided="Mimir max_label_names_per_series; r187 native hist",
            this_is="max_query_lookback 7d vs 30d panel",
            step_note="False lead label cap 4-5; lookback 6-8; 40d 9-12.",
            query_cmd="curl -sS -G $MIMIR/prometheus/api/v1/query --data-urlencode 'query=histogram_quantile(0.99, sum by (le) (rate(http_req_seconds_bucket{service=\"mimir-lookback-svc\"}[30d])))'",
            false_cmd="yq '.limits.max_label_names_per_series' mimir/lookback-limits.yaml",
            truth_cmd="yq '.query_frontend.max_query_lookback, .query_frontend.max_query_length' mimir/lookback-frontend.yaml",
            confirm_cmd="curl -sS -G $MIMIR/prometheus/api/v1/query --data-urlencode 'query=histogram_quantile(0.99, sum by (le) (rate(http_req_seconds_bucket{service=\"mimir-lookback-svc\"}[24h])))'",
            reload_cmd="kubectl -n mimir rollout restart deploy/mimir-query-frontend && kubectl -n mimir rollout status deploy/mimir-query-frontend --timeout=90s",
            requery_cmd="curl -sS -G $MIMIR/prometheus/api/v1/query --data-urlencode 'query=histogram_quantile(0.99, sum by (le) (rate(http_req_seconds_bucket{service=\"mimir-lookback-svc\"}[30d])))'",
            grafana_ok_cmd="curl -sS $GRAFANA/api/ds/query -d @/tmp/look.json | jq '.results.A.frames[0].data.values'",
            side_cmd="curl -sS $GRAFANA/api/ds/query -d @/tmp/look24.json | jq '.results.A.frames[0].data.values[1][0]'",
            final_cmd="yq '.query_frontend.max_query_lookback' mimir/lookback-frontend.yaml",
            patch_old="max_query_lookback: 7d",
            patch_new="max_query_lookback: 40d",
            runbook_path="runbooks/mimir-lookback.md",
            runbook="# mimir-lookback-svc lookback\nmax_query_lookback 7d blocked 30d p99. Set 40d.\nNot max_label_names.\n",
            goal="mimir-lookback-svc dashboard mimir-lookback-34 30d p99 is empty. 24h is full. Fix lookback.",
            plan="Empty 30d → not label cap → lookback 7d → 40d.",
            outcome="lookback 40d. 30d p99 fills. 24h unchanged.",
            obs1='[{"uid":"mimir-lookback-34","title":"mimir 30d p99"}]',
            obs2='{"title":"30d p99","targets":[{"expr":"histogram_quantile(0.99, sum by (le) (rate(http_req_seconds_bucket{service=\\"mimir-lookback-svc\\"}[30d])))"}]}',
            obs3='{"status":"error","error":"the query time range exceeds the limit (query length: 720h, limit: 168h)"}',
            obs4="max_label_names_per_series: 30\n# not the cap RCA",
            obs5="label cap fine",
            obs6="max_query_lookback: 7d\nmax_query_length: 7d",
            obs7='{"status":"success","data":{"result":[{"value":[1710000000,"0.19"]}]}}',
            obs8="24h works; 30d exceeds 7d lookback",
            obs9="patched lookback 40d",
            obs10='deployment "mimir-query-frontend" successfully rolled out',
            obs11='{"status":"success","data":{"result":[{"value":[1710000600,"0.21"]}]}}',
            obs12="[[1710000600],[0.21]]",
            obs13="0.19",
            obs14="wrote runbooks/mimir-lookback.md",
            obs15="40d",
        ),
        _failp(
            slug="mimir-raise-label-cap-not-lookback",
            service="mimir-lookback-bag-svc",
            dashboard_uid="mimir-label-cap",
            panel="bag 30d p99",
            query='histogram_quantile(0.99, sum by (le) (rate(http_req_seconds_bucket{service="mimir-lookback-bag-svc"}[30d])))',
            lie="Raising max_label_names_per_series does not extend max_query_lookback of 7d",
            false_lead="max_label_names_per_series too low",
            config_path="mimir/bag-limits.yaml",
            lie_path="mimir/bag-frontend.yaml",
            wrong_path="mimir/bag-limits.yaml",
            reload_name="mimir-ingester",
            ticket="OBS-4494",
            xfail="tests/test_mimir_look_bag.py",
            surfaces="label cap leftover vs lookback",
            avoided="Mimir max_label_names as actual RCA",
            this_is="fail/handoff: label cap 60, lookback still 7d",
            step_note="label cap 6-10; still error 11; late lookback 12; handoff 14-15.",
            next_note="Next: Vector remap VRL vs Loki (published path).",
            query_cmd="curl -sS -G $MIMIR/prometheus/api/v1/query --data-urlencode 'query=histogram_quantile(0.99, sum by (le) (rate(http_req_seconds_bucket{service=\"mimir-lookback-bag-svc\"}[30d])))'",
            false_cmd="yq '.limits.max_label_names_per_series' mimir/bag-limits.yaml",
            reload_cmd="kubectl -n mimir rollout restart sts/mimir-ingester && kubectl -n mimir rollout status sts/mimir-ingester --timeout=180s",
            requery_cmd="curl -sS -G $MIMIR/prometheus/api/v1/query --data-urlencode 'query=histogram_quantile(0.99, sum by (le) (rate(http_req_seconds_bucket{service=\"mimir-lookback-bag-svc\"}[30d])))'",
            denied_cmd="kubectl -n mimir auth can-i patch configmap/bag-frontend --as=sre-bot",
            wrong_old="max_label_names_per_series: 15",
            wrong_new="max_label_names_per_series: 60",
            wrong2_old="max_metadata_length: 1024",
            wrong2_new="max_metadata_length: 4096",
            ticket_body="OBS-4494: mimir-lookback-bag-svc 30d still exceeds lookback. Need max_query_lookback 40d. No frontend RBAC.\n",
            goal="mimir-lookback-bag-svc dashboard mimir-label-cap bag 30d p99 errors. Restore 30d.",
            plan="Raise max_label_names_per_series (banned cap RCA).",
            outcome="cap 60; still lookback error. Late 7d. Handoff OBS-4494.",
            obs1='[{"uid":"mimir-label-cap","title":"mimir bag lookback"}]',
            obs2='{"title":"bag 30d p99","targets":[{"expr":"histogram_quantile(0.99, sum by (le) (rate(http_req_seconds_bucket{service=\\"mimir-lookback-bag-svc\\"}[30d])))"}]}',
            obs3='{"status":"error","error":"the query time range exceeds the limit"}',
            obs4="15",
            obs5="label cap 15 — treated as RCA",
            obs6="mimir/bag-limits.yaml",
            obs7="patched 60",
            obs8='statefulset "mimir-ingester" successfully rolled out',
            obs9='{"status":"error","error":"the query time range exceeds the limit"}',
            obs10="patched metadata 4096",
            obs11='{"status":"error","error":"the query time range exceeds the limit"}',
            obs12="mimir/bag-frontend.yaml max_query_lookback 7d",
            obs13="no",
            obs14="wrote tickets/OBS-4494.md",
            obs15="xfail tests/test_mimir_look_bag.py",
        ),
    )
)

# r211 Vector remap drop vs Loki (not OS, not VL, not Adaptive Logs)
MORE.append(
    (
        _okp(
            slug="vector-remap-drop-vs-loki",
            service="vector-remap-svc",
            dashboard_uid="vector-remap-25",
            panel="remap errors",
            query='sum(count_over_time({app="vector-remap-svc"} |= "error" [15m]))',
            lie="Vector remap VRL drops .level==error before Loki; Grafana thinks a Loki drop stage is the cause",
            false_lead="Loki pipeline drop / Adaptive Logs sampler",
            config_path="loki/vector-pipeline.yaml",
            lie_path="vector/remap.toml",
            truth_name="Vector remap dropped vs Loki ingested",
            reload_name="vector",
            side="error lines from other Vector sinks still in Loki",
            surfaces="Vector remap VRL drop vs Loki drop stage",
            avoided="r199 Adaptive Logs; Loki line_format drop; r191 OS vs Loki",
            this_is="Vector VRL drops error before Loki",
            step_note="False lead Loki drop 4-5; VRL abort 6-8; keep error 9-12.",
            query_cmd="curl -sS -G $LOKI/loki/api/v1/query --data-urlencode 'query=sum(count_over_time({app=\"vector-remap-svc\"} |= \"error\" [15m]))'",
            false_cmd="yq '.pipeline_stages[] | select(.drop)' loki/vector-pipeline.yaml",
            truth_cmd="curl -sS $VECTOR/graphql -d '{\"query\":\"{componentErrors}\"}' | jq '.data'",
            confirm_cmd="rg -n 'abort|level' vector/remap.toml",
            reload_cmd="kubectl -n vector rollout restart ds/vector && kubectl -n vector rollout status ds/vector --timeout=90s",
            requery_cmd="curl -sS -G $LOKI/loki/api/v1/query --data-urlencode 'query=sum(count_over_time({app=\"vector-remap-svc\"} |= \"error\" [15m]))'",
            grafana_ok_cmd="curl -sS $GRAFANA/api/ds/query -d @/tmp/vremap.json | jq '.results.A.frames[0].data.values'",
            side_cmd="curl -sS -G $LOKI/loki/api/v1/query --data-urlencode 'query=count_over_time({app=\"gate-board-svc\"} |= \"error\" [15m])' | jq '.data.result[0].value'",
            final_cmd="rg -n 'abort' vector/remap.toml || true",
            patch_old='if .level == "error" { abort }',
            patch_new='if .level == "debug" { abort }',
            runbook_path="runbooks/vector-remap-drop.md",
            runbook="# vector-remap-svc VRL\nremap aborted error lines. Keep errors; drop debug only.\nNot Loki drop and not Adaptive Logs.\n",
            goal="vector-remap-svc dashboard vector-remap-25 remap errors is empty. App logs errors. Find the VRL lie.",
            plan="Empty Loki → not pipeline drop → Vector abort on error → keep errors.",
            outcome="VRL drops debug only. Error lines in Loki. other sinks unchanged.",
            obs1='[{"uid":"vector-remap-25","title":"vector remap errors"}]',
            obs2='{"title":"remap errors","targets":[{"expr":"sum(count_over_time({app=\\"vector-remap-svc\\"} |= \\"error\\" [15m]))"}]}',
            obs3='{"status":"success","data":{"result":[]}}',
            obs4="[]\n# no Loki drop stage",
            obs5="pipeline clean",
            obs6='[transforms.remap]\nsource = """\nif .level == "error" { abort }\n"""',
            obs7='{"dropped":902,"reason":"abort"}',
            obs8="VRL abort on error; Loki never saw them",
            obs9="patched abort on debug only",
            obs10='daemonset "vector" successfully rolled out',
            obs11='{"status":"success","data":{"result":[{"value":[1710000600,"88"]}]}}',
            obs12="[[1710000600],[88]]",
            obs13='["1710000600","41"]',
            obs14="wrote runbooks/vector-remap-drop.md",
            obs15="no abort on error",
        ),
        _failp(
            slug="vector-remove-loki-drop-not-vrl",
            service="vector-remap-bag-svc",
            dashboard_uid="vector-loki-drop",
            panel="bag remap errors",
            query='sum(count_over_time({app="vector-remap-bag-svc"} |= "error" [15m]))',
            lie="Removing a Loki drop stage does not restore lines Vector VRL already aborted",
            false_lead="Loki pipeline drop on error",
            config_path="loki/vector-bag-pipeline.yaml",
            lie_path="vector/bag-remap.toml",
            wrong_path="loki/vector-bag-pipeline.yaml",
            reload_name="loki-distributor",
            ticket="OBS-4485",
            xfail="tests/test_vector_bag.py",
            surfaces="Loki drop leftover vs Vector VRL abort",
            avoided="Adaptive Logs as RCA; Loki line_format as RCA",
            this_is="fail/handoff: Loki drop gone, VRL still aborts error",
            step_note="Loki drop 6-10; still empty 11; late VRL 12; handoff 14-15.",
            next_note="Next: Coralogix traces vs Tempo.",
            query_cmd="curl -sS -G $LOKI/loki/api/v1/query --data-urlencode 'query=sum(count_over_time({app=\"vector-remap-bag-svc\"} |= \"error\" [15m]))'",
            false_cmd="yq '.pipeline_stages' loki/vector-bag-pipeline.yaml",
            reload_cmd="kubectl -n loki rollout restart deploy/loki-distributor && kubectl -n loki rollout status deploy/loki-distributor --timeout=90s",
            requery_cmd="curl -sS -G $LOKI/loki/api/v1/query --data-urlencode 'query=sum(count_over_time({app=\"vector-remap-bag-svc\"} |= \"error\" [15m]))'",
            denied_cmd="kubectl -n vector auth can-i patch configmap/bag-remap --as=sre-bot",
            wrong_old="- drop:\n      expression: 'level == \"error\"'",
            wrong_new="- json: {}",
            wrong2_old="- regex:\n      expression: 'level=(?P<level>\\w+)'",
            wrong2_new="- output:\n      source: message",
            ticket_body="OBS-4485: vector-remap-bag-svc still empty. VRL aborts error. Need remap patch. No Vector RBAC.\n",
            goal="vector-remap-bag-svc dashboard vector-loki-drop bag remap errors is empty. Restore errors.",
            plan="Remove Loki drop stage.",
            outcome="Loki drop gone; still empty. Late VRL abort. Handoff OBS-4485.",
            obs1='[{"uid":"vector-loki-drop","title":"vector bag remap"}]',
            obs2='{"title":"bag remap errors","targets":[{"expr":"sum(count_over_time({app=\\"vector-remap-bag-svc\\"} |= \\"error\\" [15m]))"}]}',
            obs3='{"status":"success","data":{"result":[]}}',
            obs4="- drop: {expression: 'level == \"error\"'}",
            obs5="drop stage — treated as RCA",
            obs6="loki/vector-bag-pipeline.yaml",
            obs7="patched drop → json",
            obs8='deployment "loki-distributor" successfully rolled out',
            obs9='{"status":"success","data":{"result":[]}}',
            obs10="patched output source",
            obs11='{"status":"success","data":{"result":[]}}',
            obs12='vector/bag-remap.toml if .level == "error" { abort }',
            obs13="no",
            obs14="wrote tickets/OBS-4485.md",
            obs15="xfail tests/test_vector_bag.py",
        ),
    )
)

# r212 Coralogix traces vs Tempo (not HC dataset, not NR, not AppD)
MORE.append(
    (
        _okp(
            slug="cx-spanid-vs-tempo-tid",
            service="cx-trace-svc",
            dashboard_uid="cx-trace-26",
            panel="cx traces",
            query='{resource.service.name="cx-trace-svc"}',
            lie="Grafana traces panel looks up Coralogix spanId as Tempo traceId so the tree is 404 while CX UI shows traces",
            false_lead="Honeycomb dataset-as-tenant / NR spanId / AppD BT GUID",
            config_path="k8s/cx/trace.env",
            lie_path="grafana/dashboards/cx-trace-26.json",
            truth_name="CX traceId vs spanId",
            reload_name="grafana",
            side="CX UI still uses spanId",
            surfaces="Coralogix spanId vs Tempo traceId",
            avoided="r193 HC dataset; r184 NR spanId; r205 AppD BT; r163 tid128",
            this_is="Coralogix spanId used as Tempo traceId",
            step_note="False lead HC/NR 4-5; CX span vs trace 6-8; dashboard var 9-12.",
            query_cmd="curl -sS $TEMPO/api/traces/cafef00ddeadbeef | jq .message",
            false_cmd="kubectl -n cx exec deploy/cx-trace-svc -- env | rg 'HONEYCOMB|NEW_RELIC|CORALOGIX|DD_TRACE'",
            truth_cmd="curl -sS $CX/api/traces?app=cx-trace-svc | jq '.[0].{spanId,traceId}'",
            confirm_cmd="jq '.dashboard.templating.list[]|{name,query}' grafana/dashboards/cx-trace-26.json",
            reload_cmd="kubectl -n grafana rollout restart deploy/grafana && kubectl -n grafana rollout status deploy/grafana --timeout=90s",
            requery_cmd="curl -sS $TEMPO/api/traces/4bf92f3577b34da6a3ce929d0e0e4736 | jq '{rootServiceName,spanCount}'",
            grafana_ok_cmd="curl -sS $GRAFANA/api/ds/query -d @/tmp/cx.json | jq '.results.A.frames[0].schema'",
            side_cmd="curl -sS $CX/api/spans/cafef00ddeadbeef | jq '{id,traceId}'",
            final_cmd="jq -r '.dashboard.templating.list[].name' grafana/dashboards/cx-trace-26.json",
            patch_old='"query": "cx_span_id"',
            patch_new='"query": "cx_trace_id"',
            runbook_path="runbooks/cx-trace-tempo.md",
            runbook="# cx-trace-svc Coralogix vs Tempo\nUse CX traceId (32 hex), not spanId, as Tempo lookup.\nNot HC dataset and not NR spanId.\n",
            goal="cx-trace-svc dashboard cx-trace-26 cx traces is empty. CX shows spans. Fix the id join.",
            plan="Tempo 404 on 16-hex → not HC/NR → CX spanId vs traceId → switch var.",
            outcome="Templating cx_trace_id. Tempo tree loads. CX UI still span-centric.",
            obs1='[{"uid":"cx-trace-26","title":"cx traces"}]',
            obs2='{"name":"cx_span_id","query":"cx_span_id"}',
            obs3='"trace not found"',
            obs4="CORALOGIX_APPLICATION=cx-trace-svc\n# no HONEYCOMB/NEW_RELIC/DD — not r193/r184/r163",
            obs5="CX only",
            obs6='traces panel query=${cx_span_id}',
            obs7='{"spanId":"cafef00ddeadbeef","traceId":"4bf92f3577b34da6a3ce929d0e0e4736"}',
            obs8="CX spanId is not Tempo traceId",
            obs9="patched templating cx_trace_id",
            obs10='deployment "grafana" successfully rolled out',
            obs11='{"rootServiceName":"cx-trace-svc","spanCount":19}',
            obs12='{"name":"Trace"}',
            obs13='{"id":"cafef00ddeadbeef","traceId":"4bf92f3577b34da6a3ce929d0e0e4736"}',
            obs14="wrote runbooks/cx-trace-tempo.md",
            obs15="cx_trace_id",
        ),
        _failp(
            slug="cx-enable-hc-dataset-not-tid",
            service="cx-trace-bag-svc",
            dashboard_uid="cx-hc-ds",
            panel="bag cx traces",
            query='{resource.service.name="cx-trace-bag-svc"}',
            lie="Setting Honeycomb dataset as Tempo tenant does not map Coralogix spanId to Tempo traceId",
            false_lead="Honeycomb dataset-as-tenant",
            config_path="tempo/cx-bag-tenant.yaml",
            lie_path="grafana/dashboards/cx-hc-ds.json",
            wrong_path="tempo/cx-bag-tenant.yaml",
            reload_name="tempo-querier",
            ticket="OBS-4486",
            xfail="tests/test_cx_bag.py",
            surfaces="HC dataset leftover vs CX spanId",
            avoided="r193 as actual RCA",
            this_is="fail/handoff: HC tenant set, Tempo still 404s CX spanId",
            step_note="HC tenant 6-10; still 404 11; late dashboard 12; handoff 14-15.",
            next_note="Next: Chronosphere collector vs Prom agent.",
            query_cmd="curl -sS $TEMPO/api/traces/beefcafedead0001 | jq .message",
            false_cmd="yq '.multitenancy_enabled, .querier.tenant' tempo/cx-bag-tenant.yaml",
            reload_cmd="kubectl -n tempo rollout restart deploy/tempo-querier && kubectl -n tempo rollout status deploy/tempo-querier --timeout=90s",
            requery_cmd="curl -sS $TEMPO/api/traces/beefcafedead0001 | jq .message",
            denied_cmd="kubectl -n grafana auth can-i patch configmap/grafana-dashboards --as=sre-bot",
            wrong_old="tenant: airline-obs",
            wrong_new="tenant: cx-trace-bag",
            wrong2_old="multitenancy_enabled: false",
            wrong2_new="multitenancy_enabled: true",
            ticket_body="OBS-4486: cx-trace-bag-svc Tempo 404s cx_span_id. Need dashboard var cx_trace_id. No Grafana RBAC.\n",
            goal="cx-trace-bag-svc dashboard cx-hc-ds bag cx traces is empty. Restore Tempo join.",
            plan="Set Tempo tenant to HC dataset name (r193 leftover).",
            outcome="tenant cx-trace-bag; Tempo still 404s spanId. Handoff OBS-4486.",
            obs1='[{"uid":"cx-hc-ds","title":"cx bag traces"}]',
            obs2='{"title":"bag cx traces","targets":[{"query":"${cx_span_id}"}]}',
            obs3='"trace not found"',
            obs4="tenant: airline-obs",
            obs5="tenant airline-obs — treated as r193",
            obs6="tempo/cx-bag-tenant.yaml",
            obs7="patched tenant cx-trace-bag",
            obs8='deployment "tempo-querier" successfully rolled out',
            obs9='"trace not found"',
            obs10="patched multitenancy true",
            obs11='"trace not found"',
            obs12="grafana/dashboards/cx-hc-ds.json query=${cx_span_id}",
            obs13="no",
            obs14="wrote tickets/OBS-4486.md",
            obs15="xfail tests/test_cx_bag.py",
        ),
    )
)

# r213 Chronosphere collector vs Prom agent (not r160 agent TSDB)
MORE.append(
    (
        _okp(
            slug="chrono-collector-vs-prom-agent",
            service="chrono-coll-svc",
            dashboard_uid="chrono-coll-27",
            panel="chrono up",
            query='up{job="chrono-coll-svc"}',
            lie="Grafana Prom datasource still points at the in-cluster Prom agent while Chronosphere collector is the only scrape that sees chrono-coll-svc",
            false_lead="Prom agent has no local TSDB",
            config_path="prom/chrono-agent.yaml",
            lie_path="grafana/datasources/chrono.yaml",
            truth_name="Chronosphere query vs agent /metrics",
            reload_name="grafana",
            side="in-cluster jobs still on the agent datasource",
            surfaces="Chronosphere collector vs Prom agent datasource",
            avoided="r160 agent TSDB; r177 Alloy vs agent; r202 EMF vs Prom",
            this_is="Grafana still queries Prom agent, series live in Chronosphere",
            step_note="False lead agent TSDB 4-5; Chronosphere URL 6-8; switch ds 9-12.",
            query_cmd="curl -sS -G $AGENT/api/v1/query --data-urlencode 'query=up{job=\"chrono-coll-svc\"}'",
            false_cmd="yq '.storage.tsdb.path, .agent' prom/chrono-agent.yaml",
            truth_cmd="curl -sS -G $CHRONO/api/v1/query --data-urlencode 'query=up{job=\"chrono-coll-svc\"}'",
            confirm_cmd="yq '.url, .uid' grafana/datasources/chrono.yaml",
            reload_cmd="kubectl -n grafana rollout restart deploy/grafana && kubectl -n grafana rollout status deploy/grafana --timeout=90s",
            requery_cmd="curl -sS -G $CHRONO/api/v1/query --data-urlencode 'query=up{job=\"chrono-coll-svc\"}'",
            grafana_ok_cmd="curl -sS $GRAFANA/api/ds/query -d @/tmp/chrono.json | jq '.results.A.frames[0].data.values'",
            side_cmd="curl -sS -G $AGENT/api/v1/query --data-urlencode 'query=up{job=\"ssr-meal-svc\"}' | jq '.data.result[0].value'",
            final_cmd="yq '.url' grafana/datasources/chrono.yaml",
            patch_old="url: http://prom-agent.obs:9090",
            patch_new="url: https://chrono.airline.observability/prometheus",
            runbook_path="runbooks/chrono-coll.md",
            runbook="# chrono-coll-svc Chronosphere vs agent\nScrape is Chronosphere collector. Grafana still pointed at Prom agent. Switch datasource URL.\nNot missing local TSDB.\n",
            goal="chrono-coll-svc dashboard chrono-coll-27 chrono up is empty on Grafana. Chronosphere has up=1. Fix datasource.",
            plan="Empty agent → not TSDB path → Chronosphere has series → switch URL.",
            outcome="Grafana queries Chronosphere. up=1. in-cluster jobs still on agent.",
            obs1='[{"uid":"chrono-coll-27","title":"chrono collector up"}]',
            obs2='{"title":"chrono up","datasource":{"uid":"prom-agent"},"targets":[{"expr":"up{job=\\"chrono-coll-svc\\"}"}]}',
            obs3='{"status":"success","data":{"result":[]}}',
            obs4="storage.tsdb.path: null\nagent: true\n# expected — not r160 RCA",
            obs5="agent has no local TSDB by design",
            obs6="url: http://prom-agent.obs:9090\nuid: prom-agent",
            obs7='{"status":"success","data":{"result":[{"value":[1710000000,"1"]}]}}',
            obs8="Chronosphere has up=1; Grafana queries agent",
            obs9="patched Grafana URL Chronosphere",
            obs10='deployment "grafana" successfully rolled out',
            obs11='{"status":"success","data":{"result":[{"value":[1710000600,"1"]}]}}',
            obs12="[[1710000600],[1]]",
            obs13='["1710000600","1"]',
            obs14="wrote runbooks/chrono-coll.md",
            obs15="https://chrono.airline.observability/prometheus",
        ),
        _failp(
            slug="chrono-enable-agent-tsdb",
            service="chrono-coll-bag-svc",
            dashboard_uid="chrono-agent-tsdb",
            panel="bag chrono up",
            query='up{job="chrono-coll-bag-svc"}',
            lie="Enabling a local TSDB on the Prom agent does not scrape a Chronosphere-only job",
            false_lead="Prom agent missing local TSDB",
            config_path="prom/chrono-bag-agent.yaml",
            lie_path="grafana/datasources/chrono-bag.yaml",
            wrong_path="prom/chrono-bag-agent.yaml",
            reload_name="prom-agent-chrono",
            ticket="OBS-4487",
            xfail="tests/test_chrono_bag.py",
            surfaces="agent TSDB leftover vs Chronosphere collector",
            avoided="r160 as actual RCA",
            this_is="fail/handoff: agent TSDB on, Chronosphere job still missing",
            step_note="TSDB 6-10; still empty 11; late Grafana URL 12; handoff 14-15.",
            next_note="Next: k6 browser tracing vs Tempo.",
            query_cmd="curl -sS -G $AGENT/api/v1/query --data-urlencode 'query=up{job=\"chrono-coll-bag-svc\"}'",
            false_cmd="yq '.storage.tsdb' prom/chrono-bag-agent.yaml",
            reload_cmd="kubectl -n chrono rollout restart deploy/prom-agent-chrono && kubectl -n chrono rollout status deploy/prom-agent-chrono --timeout=90s",
            requery_cmd="curl -sS -G $AGENT/api/v1/query --data-urlencode 'query=up{job=\"chrono-coll-bag-svc\"}'",
            denied_cmd="kubectl -n grafana auth can-i patch configmap/chrono-bag-ds --as=sre-bot",
            wrong_old="storage.tsdb.path: null",
            wrong_new="storage.tsdb.path: /prometheus",
            wrong2_old="agent: true",
            wrong2_new="agent: false",
            ticket_body="OBS-4487: chrono-coll-bag-svc still empty on agent. Need Grafana Chronosphere URL. No ds RBAC.\n",
            goal="chrono-coll-bag-svc dashboard chrono-agent-tsdb bag chrono up is empty. Restore up.",
            plan="Enable agent local TSDB (r160 leftover).",
            outcome="TSDB on; still empty. Late Chronosphere URL. Handoff OBS-4487.",
            obs1='[{"uid":"chrono-agent-tsdb","title":"chrono bag"}]',
            obs2='{"title":"bag chrono up","targets":[{"expr":"up{job=\\"chrono-coll-bag-svc\\"}"}]}',
            obs3='{"status":"success","data":{"result":[]}}',
            obs4="path: null",
            obs5="no local TSDB — treated as r160",
            obs6="prom/chrono-bag-agent.yaml",
            obs7="patched tsdb path",
            obs8='deployment "prom-agent-chrono" successfully rolled out',
            obs9='{"status":"success","data":{"result":[]}}',
            obs10="patched agent false",
            obs11='{"status":"success","data":{"result":[]}}',
            obs12="grafana/datasources/chrono-bag.yaml still url prom-agent",
            obs13="no",
            obs14="wrote tickets/OBS-4487.md",
            obs15="xfail tests/test_chrono_bag.py",
        ),
    )
)

# r214 k6 browser tracing vs Tempo (not k6 Cloud test_run_id r192)
MORE.append(
    (
        _okp(
            slug="k6-browser-span-vs-tempo",
            service="k6-browser-svc",
            dashboard_uid="k6-browser-28",
            panel="browser traces",
            query='{resource.service.name="k6-browser-svc"}',
            lie="Grafana k6 browser extension joins page.url as Tempo traceId so traces panel is empty while k6 browser spans exist under trace_id",
            false_lead="k6 Cloud test_run_id ULID used as Tempo traceId",
            config_path="grafana/dashboards/k6-browser-28.json",
            lie_path="k6/browser.js",
            truth_name="k6 browser trace_id vs page.url",
            reload_name="grafana",
            side="k6 Cloud test_run_id panels unchanged",
            surfaces="k6 browser page.url vs Tempo traceId",
            avoided="r192 k6 test_run_id; r184 NR spanId",
            this_is="k6 browser page.url used as Tempo traceId",
            step_note="False lead test_run_id 4-5; page.url 6-8; trace_id var 9-12.",
            query_cmd="curl -sS $TEMPO/api/traces/https://gate.example/checkin | jq .message",
            false_cmd="jq '.dashboard.templating.list[]|{name}' grafana/dashboards/k6-browser-28.json",
            truth_cmd="curl -sS $K6/v1/browser/spans?app=k6-browser-svc | jq '.[0]|{url,trace_id}'",
            confirm_cmd="rg -n 'page.url|trace_id' k6/browser.js grafana/dashboards/k6-browser-28.json",
            reload_cmd="kubectl -n grafana rollout restart deploy/grafana && kubectl -n grafana rollout status deploy/grafana --timeout=90s",
            requery_cmd="curl -sS $TEMPO/api/traces/4bf92f3577b34da6a3ce929d0e0e4736 | jq '{rootServiceName,spanCount}'",
            grafana_ok_cmd="curl -sS $GRAFANA/api/ds/query -d @/tmp/k6b.json | jq '.results.A.frames[0].schema'",
            side_cmd="jq '.dashboard.templating.list[]|select(.name==\"k6_trace_id\")' grafana/dashboards/loadgen-k6-tempo-2.json | jq '.name'",
            final_cmd="jq -r '.dashboard.templating.list[].name' grafana/dashboards/k6-browser-28.json",
            patch_old='"query": "${k6_page_url}"',
            patch_new='"query": "${k6_browser_trace_id}"',
            runbook_path="runbooks/k6-browser-tempo.md",
            runbook="# k6-browser-svc browser tracing\nUse browser span trace_id, not page.url, as Tempo lookup.\nNot Cloud test_run_id.\n",
            goal="k6-browser-svc dashboard k6-browser-28 browser traces is empty. k6 has browser spans. Fix the join.",
            plan="Tempo 404 on URL → not test_run_id → page.url vs trace_id → switch var.",
            outcome="Templating k6_browser_trace_id. Tempo tree loads. Cloud panels unchanged.",
            obs1='[{"uid":"k6-browser-28","title":"k6 browser traces"}]',
            obs2='{"title":"browser traces","targets":[{"query":"${k6_page_url}"}]}',
            obs3='"trace not found"',
            obs4='{"name":"k6_page_url"}\n# not k6_test_run_id — not r192',
            obs5="var is page url not test_run_id",
            obs6='traces panel query=${k6_page_url}',
            obs7='{"url":"https://gate.example/checkin","trace_id":"4bf92f3577b34da6a3ce929d0e0e4736"}',
            obs8="page.url is not Tempo traceId",
            obs9="patched templating k6_browser_trace_id",
            obs10='deployment "grafana" successfully rolled out',
            obs11='{"rootServiceName":"k6-browser-svc","spanCount":11}',
            obs12='{"name":"Trace"}',
            obs13='"k6_trace_id"',
            obs14="wrote runbooks/k6-browser-tempo.md",
            obs15="k6_browser_trace_id",
        ),
        _failp(
            slug="k6-browser-switch-testrun-var",
            service="k6-browser-bag-svc",
            dashboard_uid="k6-browser-run",
            panel="bag browser traces",
            query='{resource.service.name="k6-browser-bag-svc"}',
            lie="Switching the Grafana var from page.url to k6 Cloud test_run_id does not join browser spans to Tempo",
            false_lead="k6 Cloud test_run_id join",
            config_path="grafana/dashboards/k6-browser-run.json",
            lie_path="k6/bag-browser.js",
            wrong_path="grafana/dashboards/k6-browser-run.json",
            reload_name="grafana",
            ticket="OBS-4488",
            xfail="tests/test_k6_browser_bag.py",
            surfaces="test_run_id leftover vs k6 browser trace_id",
            avoided="r192 as actual RCA",
            this_is="fail/handoff: test_run_id var, Tempo still 404s URL/ULID",
            step_note="test_run_id 6-10; still 404 11; late browser.js 12; handoff 14-15.",
            next_note="Next: OTel filelog vs Loki.",
            query_cmd="curl -sS $TEMPO/api/traces/01HQBROWSERUN000000000000 | jq .message",
            false_cmd="jq '.dashboard.templating.list[].name' grafana/dashboards/k6-browser-run.json",
            reload_cmd="kubectl -n grafana rollout restart deploy/grafana && kubectl -n grafana rollout status deploy/grafana --timeout=90s",
            requery_cmd="curl -sS $TEMPO/api/traces/01HQBROWSERUN000000000000 | jq .message",
            denied_cmd="kubectl -n k6 auth can-i patch configmap/bag-browser --as=sre-bot",
            wrong_old='"query": "${k6_page_url}"',
            wrong_new='"query": "${k6_test_run_id}"',
            wrong2_old='"name": "k6_page_url"',
            wrong2_new='"name": "k6_test_run_id"',
            ticket_body="OBS-4488: k6-browser-bag-svc still 404. Need k6_browser_trace_id from span. No k6 CM RBAC.\n",
            goal="k6-browser-bag-svc dashboard k6-browser-run bag browser traces is empty. Restore Tempo join.",
            plan="Switch var to test_run_id (r192 leftover).",
            outcome="test_run_id var; still 404. Late browser trace_id. Handoff OBS-4488.",
            obs1='[{"uid":"k6-browser-run","title":"k6 bag browser"}]',
            obs2='{"title":"bag browser traces","targets":[{"query":"${k6_page_url}"}]}',
            obs3='"trace not found"',
            obs4='"k6_page_url"',
            obs5="page.url var — treated as r192 style id join",
            obs6="grafana/dashboards/k6-browser-run.json",
            obs7="patched query test_run_id",
            obs8='deployment "grafana" successfully rolled out',
            obs9='"trace not found"',
            obs10="patched name k6_test_run_id",
            obs11='"trace not found"',
            obs12="k6/bag-browser.js spans have trace_id 32-hex, not test_run_id",
            obs13="no",
            obs14="wrote tickets/OBS-4488.md",
            obs15="xfail tests/test_k6_browser_bag.py",
        ),
    )
)

# r215 OTel filelog vs Loki (not VL, not OS)
MORE.append(
    (
        _okp(
            slug="otel-filelog-vs-loki-push",
            service="filelog-app-svc",
            dashboard_uid="filelog-loki-29",
            panel="file errors",
            query='sum(count_over_time({app="filelog-app-svc"} |= "error" [15m]))',
            lie="collector filelog receiver writes OTLP logs to Tempo-logs exporter while Grafana Loki panel queries {app=filelog-app-svc} which is empty",
            false_lead="OpenSearch index / VictoriaLogs LogSQL",
            config_path="grafana/datasources/filelog-os.yaml",
            lie_path="otelcol/filelog.yaml",
            truth_name="filelog exporter vs Loki",
            reload_name="otelcol-filelog",
            side="native Loki apps unchanged",
            surfaces="OTel filelog vs Loki push",
            avoided="r191 OS vs Loki; r161 VL LogSQL",
            this_is="filelog exporter is otlp/logs not loki",
            step_note="False lead OS/VL 4-5; filelog exporter 6-8; loki exporter 9-12.",
            query_cmd="curl -sS -G $LOKI/loki/api/v1/query --data-urlencode 'query=sum(count_over_time({app=\"filelog-app-svc\"} |= \"error\" [15m]))'",
            false_cmd="yq '.url, .type' grafana/datasources/filelog-os.yaml; curl -sS $VL/select/logsql/query -d 'q=app:filelog-app-svc' | head",
            truth_cmd="yq '.exporters, .service.pipelines.logs' otelcol/filelog.yaml",
            confirm_cmd="ls /var/log/filelog-app/*.log | wc -l; yq '.receivers.filelog.include' otelcol/filelog.yaml",
            reload_cmd="kubectl -n otel rollout restart deploy/otelcol-filelog && kubectl -n otel rollout status deploy/otelcol-filelog --timeout=90s",
            requery_cmd="curl -sS -G $LOKI/loki/api/v1/query --data-urlencode 'query=sum(count_over_time({app=\"filelog-app-svc\"} |= \"error\" [15m]))'",
            grafana_ok_cmd="curl -sS $GRAFANA/api/ds/query -d @/tmp/flog.json | jq '.results.A.frames[0].data.values'",
            side_cmd="curl -sS -G $LOKI/loki/api/v1/query --data-urlencode 'query=count_over_time({app=\"gate-board-svc\"}[5m])' | jq '.data.result[0].value'",
            final_cmd="yq '.exporters.loki.endpoint, .service.pipelines.logs.exporters' otelcol/filelog.yaml",
            patch_old="exporters: [otlp/logs]",
            patch_new="exporters: [loki]\n    # loki:\n    #   endpoint: http://loki.obs:3100/loki/api/v1/push",
            runbook_path="runbooks/filelog-loki.md",
            runbook="# filelog-app-svc filelog vs Loki\nfilelog exported OTLP logs, not Loki push. Grafana Loki panel empty. Switch exporter.\nNot OS and not VL.\n",
            goal="filelog-app-svc dashboard filelog-loki-29 file errors is empty. Files have errors. Fix exporter.",
            plan="Empty Loki → not OS/VL → filelog otlp/logs → loki exporter.",
            outcome="loki exporter. Error count fills. native Loki apps unchanged.",
            obs1='[{"uid":"filelog-loki-29","title":"filelog errors"}]',
            obs2='{"title":"file errors","targets":[{"expr":"sum(count_over_time({app=\\"filelog-app-svc\\"} |= \\"error\\" [15m]))"}]}',
            obs3='{"status":"success","data":{"result":[]}}',
            obs4="type: grafana-opensearch-datasource\nVL empty too — not r191/r161 RCA (files never went there)",
            obs5="OS/VL empty; this service is filelog",
            obs6="exporters: [otlp/logs]\npipelines.logs.exporters: [otlp/logs]",
            obs7="include: [/var/log/filelog-app/*.log]\n12 files",
            obs8="filelog writes OTLP not Loki",
            obs9="patched exporters loki",
            obs10='deployment "otelcol-filelog" successfully rolled out',
            obs11='{"status":"success","data":{"result":[{"value":[1710000600,"140"]}]}}',
            obs12="[[1710000600],[140]]",
            obs13='["1710000600","41"]',
            obs14="wrote runbooks/filelog-loki.md",
            obs15="[loki]",
        ),
        _failp(
            slug="filelog-recreate-os-index",
            service="filelog-bag-svc",
            dashboard_uid="filelog-os-idx",
            panel="bag file errors",
            query='index=logs-filelog-* AND app:filelog-bag-svc',
            lie="Recreating the OpenSearch index does not ingest OTel filelog OTLP logs",
            false_lead="missing OpenSearch index",
            config_path="opensearch/templates/filelog.json",
            lie_path="otelcol/filelog-bag.yaml",
            wrong_path="opensearch/templates/filelog.json",
            reload_name="opensearch",
            ticket="OBS-4489",
            xfail="tests/test_filelog_bag.py",
            surfaces="OS index leftover vs filelog OTLP exporter",
            avoided="r191 as actual RCA",
            this_is="fail/handoff: OS template recreated, filelog still otlp/logs",
            step_note="OS tpl 6-10; still 0 11; late filelog exporter 12; handoff 14-15.",
            next_note="Next: Grafana public dashboard vs auth.",
            query_cmd="curl -sS $OS/_count -d '{\"query\":{\"term\":{\"app.keyword\":\"filelog-bag-svc\"}}}'",
            false_cmd="curl -sS $OS/_index_template/logs-filelog | jq '.index_templates|length'",
            reload_cmd="kubectl -n os rollout restart sts/opensearch && kubectl -n os rollout status sts/opensearch --timeout=180s",
            requery_cmd="curl -sS $OS/_count -d '{\"query\":{\"term\":{\"app.keyword\":\"filelog-bag-svc\"}}}'",
            denied_cmd="kubectl -n otel auth can-i patch configmap/filelog-bag --as=sre-bot",
            wrong_old='"index_patterns": ["logs-filelog-old-*"]',
            wrong_new='"index_patterns": ["logs-filelog-*"]',
            wrong2_old='"number_of_shards": 1',
            wrong2_new='"number_of_shards": 3',
            ticket_body="OBS-4489: filelog-bag-svc OS still 0. filelog exporter otlp/logs. Need Loki exporter. No collector RBAC.\n",
            goal="filelog-bag-svc dashboard filelog-os-idx bag file errors is 0. Restore hits.",
            plan="Recreate OS index template (r191 leftover).",
            outcome="Template recreated; still 0. Late otlp/logs. Handoff OBS-4489.",
            obs1='[{"uid":"filelog-os-idx","title":"filelog bag"}]',
            obs2='{"title":"bag file errors","targets":[{"index":"logs-filelog-*"}]}',
            obs3='{"count":0}',
            obs4="0",
            obs5="missing template — treated as r191",
            obs6="opensearch/templates/filelog.json",
            obs7="patched index_patterns",
            obs8='statefulset "opensearch" successfully rolled out',
            obs9='{"count":0}',
            obs10="patched shards 3",
            obs11='{"count":0}',
            obs12="otelcol/filelog-bag.yaml exporters [otlp/logs]",
            obs13="no",
            obs14="wrote tickets/OBS-4489.md",
            obs15="xfail tests/test_filelog_bag.py",
        ),
    )
)

# r216 Grafana public dashboard vs auth
MORE.append(
    (
        _okp(
            slug="grafana-public-dash-vs-auth",
            service="pub-dash-svc",
            dashboard_uid="pub-dash-30",
            panel="public p99",
            query='histogram_quantile(0.99, sum by (le) (rate(http_req_seconds_bucket{service="pub-dash-svc"}[5m])))',
            lie="Grafana public dashboard token is bound to a snapshot of pub-dash-30 that still queries the old recording rule so anonymous viewers see empty while logged-in Explore is full",
            false_lead="provisioned dashboard uid collision / SQL expr stale uid",
            config_path="grafana/provisioning/dashboards/pub.yaml",
            lie_path="grafana/public-dashboards/pub-dash.yaml",
            truth_name="public token vs live dashboard",
            reload_name="grafana",
            side="authenticated users of uid pub-dash-30 still see live data",
            surfaces="Grafana public dashboard snapshot vs live uid",
            avoided="provisioned dashboard uid collision; Grafana SQL expr stale uid",
            this_is="public dashboard token pinned to stale snapshot query",
            step_note="False lead uid 4-5; public token snapshot 6-8; reissue token 9-12.",
            query_cmd="curl -sS $GRAFANA/api/public/dashboards/tok_pub_old/panels/2 | jq '.results[0].frames[0].data.values'",
            false_cmd="jq '.dashboard.uid, .meta.provisioned' grafana/provisioning/dashboards/pub.yaml",
            truth_cmd="curl -sS -H \"Authorization: Bearer $GRAFANA_TOKEN\" $GRAFANA/api/dashboards/uid/pub-dash-30 | jq '.dashboard.panels[0].targets[0].expr'",
            confirm_cmd="yq '.publicDashboard.uid, .publicDashboard.timeSelectionEnabled, .annotations' grafana/public-dashboards/pub-dash.yaml",
            reload_cmd="kubectl -n grafana rollout restart deploy/grafana && kubectl -n grafana rollout status deploy/grafana --timeout=90s",
            requery_cmd="curl -sS $GRAFANA/api/public/dashboards/tok_pub_new/panels/2 | jq '.results[0].frames[0].data.values'",
            grafana_ok_cmd="curl -sS $GRAFANA/api/ds/query -d @/tmp/pub.json | jq '.results.A.frames[0].data.values'",
            side_cmd="curl -sS -H \"Authorization: Bearer $GRAFANA_TOKEN\" $GRAFANA/api/ds/query -d @/tmp/pub-auth.json | jq '.results.A.frames[0].data.values[1][0]'",
            final_cmd="yq '.publicDashboard.accessToken' grafana/public-dashboards/pub-dash.yaml",
            patch_old="accessToken: tok_pub_old\n  uid: pub-dash-30-snap",
            patch_new="accessToken: tok_pub_new\n  uid: pub-dash-30",
            runbook_path="runbooks/pub-dash.md",
            runbook="# pub-dash-svc public dashboard\nPublic token bound to snapshot uid pub-dash-30-snap with stale recording rule. Reissue against live uid.\nNot provisioned uid collision.\n",
            goal="pub-dash-svc dashboard pub-dash-30 public p99 is empty for anonymous. Logged-in Explore is full. Fix public token.",
            plan="Empty public → not uid collision → snapshot token → reissue live uid.",
            outcome="new public token on live uid. Anonymous p99 fills. auth users unchanged.",
            obs1='[{"uid":"pub-dash-30","title":"public p99"}]',
            obs2='{"title":"public p99","targets":[{"expr":"histogram_quantile(0.99, sum by (le) (rate(http_req_seconds_bucket{service=\\"pub-dash-svc\\"}[5m])))"}]}',
            obs3="[[],[]]",
            obs4='"pub-dash-30"\ntrue\n# uid unique — not provisioned collision',
            obs5="uid stable",
            obs6="accessToken: tok_pub_old\nuid: pub-dash-30-snap",
            obs7='"slo:latency:p99"  # live panel uses histogram_quantile raw',
            obs8="public token pinned to snapshot with old recording rule",
            obs9="patched token tok_pub_new uid pub-dash-30",
            obs10='deployment "grafana" successfully rolled out',
            obs11="[[1710000600],[0.18]]",
            obs12="[[1710000600],[0.18]]",
            obs13="0.18",
            obs14="wrote runbooks/pub-dash.md",
            obs15="tok_pub_new",
        ),
        _failp(
            slug="pub-dash-reprovision-uid",
            service="pub-dash-bag-svc",
            dashboard_uid="pub-dash-uid",
            panel="bag public p99",
            query='histogram_quantile(0.99, sum by (le) (rate(http_req_seconds_bucket{service="pub-dash-bag-svc"}[5m])))',
            lie="Re-provisioning a new dashboard uid does not refresh the public dashboard token still bound to the snapshot",
            false_lead="provisioned dashboard uid collision",
            config_path="grafana/provisioning/dashboards/pub-bag.yaml",
            lie_path="grafana/public-dashboards/pub-bag.yaml",
            wrong_path="grafana/provisioning/dashboards/pub-bag.yaml",
            reload_name="grafana",
            ticket="OBS-4490",
            xfail="tests/test_pub_bag.py",
            surfaces="provisioned uid leftover vs public token snapshot",
            avoided="provisioned uid as actual RCA",
            this_is="fail/handoff: new uid provisioned, public token still snapshot",
            step_note="uid 6-10; still empty 11; late public yaml 12; handoff 14-15.",
            next_note="Next: Mimir ingest-storage vs classic TSDB.",
            query_cmd="curl -sS $GRAFANA/api/public/dashboards/tok_bag_old/panels/2 | jq '.results[0].frames'",
            false_cmd="jq '.dashboard.uid' grafana/provisioning/dashboards/pub-bag.yaml",
            reload_cmd="kubectl -n grafana rollout restart deploy/grafana && kubectl -n grafana rollout status deploy/grafana --timeout=90s",
            requery_cmd="curl -sS $GRAFANA/api/public/dashboards/tok_bag_old/panels/2 | jq '.results[0].frames'",
            denied_cmd="kubectl -n grafana auth can-i patch configmap/pub-bag-public --as=sre-bot",
            wrong_old='"uid": "pub-dash-uid"',
            wrong_new='"uid": "pub-dash-uid-v2"',
            wrong2_old='"title": "bag public p99"',
            wrong2_new='"title": "bag public p99 v2"',
            ticket_body="OBS-4490: pub-dash-bag-svc public still empty. Token tok_bag_old on snapshot. Need reissue. No public CM RBAC.\n",
            goal="pub-dash-bag-svc dashboard pub-dash-uid bag public p99 is empty anonymously. Restore public panel.",
            plan="Re-provision new uid (collision leftover).",
            outcome="uid v2; public token still snapshot. Handoff OBS-4490.",
            obs1='[{"uid":"pub-dash-uid","title":"bag public"}]',
            obs2='{"title":"bag public p99","targets":[{"expr":"histogram_quantile(0.99, sum by (le) (rate(http_req_seconds_bucket{service=\\"pub-dash-bag-svc\\"}[5m])))"}]}',
            obs3="[]",
            obs4='"pub-dash-uid"',
            obs5="uid pub-dash-uid — treated as collision RCA",
            obs6="grafana/provisioning/dashboards/pub-bag.yaml",
            obs7="patched uid v2",
            obs8='deployment "grafana" successfully rolled out',
            obs9="[]",
            obs10="patched title v2",
            obs11="[]",
            obs12="grafana/public-dashboards/pub-bag.yaml accessToken tok_bag_old uid pub-dash-uid-snap",
            obs13="no",
            obs14="wrote tickets/OBS-4490.md",
            obs15="xfail tests/test_pub_bag.py",
        ),
    )
)
