"""Observability leftover8 plants r876+.

BAN r875 tempo-ingester-max-traces-per-user-one / tempo-mtpu-raise-idle-not-max,
r384 otel-forward-connector, PagerDuty orch, Opsgenie alias, Rootly urgency,
and r163-r875 tempo/rootly/otel clones plus r778-r875 r401-catalog replay.
Leftover8 lie: silent remap, wrong dashboard, dropped label, filter drop.
"""

from mill_plants_t import _leftover_pair

MORE = []
ROUND_PAIRS = {}


def _emit(round_n, **kwargs):
    dest = []
    _leftover_pair(n=str(round_n), dest=dest, **kwargs)
    MORE.extend(dest)
    ROUND_PAIRS[round_n] = dest[0]


def _l8(n, **kw):
    vendor, noun, prefix = kw["vendor"], kw["noun"], kw["prefix"]
    ok_svc, bad_svc = f"dock-{noun}-svc", f"apron-{noun}-svc"
    tag = noun.replace("-", "")[:8]
    vtag = prefix.replace("-", "")[:5]
    ok_dash, bad_dash = f"{tag}-{vtag}-{n}", f"a{tag[:7]}-{vtag}-fl"
    lie_core = kw["lie_core"]
    _emit(
        n,
        kind="grafana",
        ok_slug=kw["ok_slug"],
        bad_slug=kw["bad_slug"],
        ok_svc=ok_svc,
        bad_svc=bad_svc,
        ok_dash=ok_dash,
        bad_dash=bad_dash,
        panel=kw["panel"],
        metric="",
        needle=kw["needle"],
        lie=(
            f"{vendor} leftover {lie_core} so Grafana dashboard {ok_dash} is empty "
            f"while the source still 202"
        ),
        bad_lie=(
            f"{kw['false_lead']} does not restore leftover leftover leftover leftover "
            f"leftover leftover leftover leftover {lie_core}"
        ),
        false_lead=kw["false_lead"],
        avoided=kw["avoided"],
        this_is=f"{vendor} leftover leftover leftover leftover leftover leftover leftover leftover {lie_core}",
        ticket=f"OBS-{8100 + (n - 876)}",
        knob=kw["knob"],
        old=kw["old"],
        new=kw["new"],
        wrong_knob=kw["wrong_knob"],
        wrong_old=kw["wrong_old"],
        wrong_new=kw["wrong_new"],
        wrong2_old=kw["wrong2_old"],
        wrong2_new=kw["wrong2_new"],
        reload="grafana",
        config_path=f"{prefix}/{tag}-false.yaml",
        lie_path=f"{prefix}/{tag}-lie.yaml",
        bad_config=f"{prefix}/a{tag[:7]}-false.yaml",
        bad_lie_path=f"{prefix}/a{tag[:7]}-lie.yaml",
    )


BAN = (
    "r875 tempo-ingester-max-traces-per-user-one; r384 otel-forward-connector; "
    "PagerDuty orch; Opsgenie alias; r515 Rootly urgency; r778-r875 r401 replay"
)

SPECS = [
    dict(vendor="Cloudflare Logpush", ok_slug="cf-logpush-filter-drop-leftover", bad_slug="cflp-filt-raise-batch-not-filter", noun="chock", panel="CF Logpush", needle="cf_drop", lie_core="filter leftover drops ClientRequestHost dock-chock-svc so Grafana is empty", false_lead="Cloudflare Logpush batch leftover", avoided=BAN, knob=".logpush.filter", old="filter: ClientRequestHost!=dock-chock-svc", new="filter: ", wrong_knob=".logpush.max_lines", wrong_old="max_lines: 1", wrong_new="max_lines: 100000", wrong2_old="destination: r2://sandbox", wrong2_new="destination: r2://hangar", prefix="cflp"),
    dict(vendor="Fastly Realtime", ok_slug="fastly-rt-service-remap-leftover", bad_slug="fastrt-svc-raise-window-not-remap", noun="cone", panel="Fastly realtime", needle="fastly_rt", lie_core="service leftover remaps dock-cone-svc into sandbox so Grafana is the wrong dashboard", false_lead="Fastly window leftover", avoided=BAN, knob=".realtime.service_id", old="service_id: sandbox", new="service_id: dock-cone-svc", wrong_knob=".realtime.window", wrong_old="window: 1", wrong_new="window: 120", wrong2_old="token: sandbox", wrong2_new="token: hangar", prefix="fastrt"),
    dict(vendor="Akamai DataStream", ok_slug="akamai-ds-dataset-remap-leftover", bad_slug="akds-set-raise-sample-not-remap", noun="wand", panel="Akamai DataStream", needle="akamai_ds", lie_core="dataset leftover remaps dock-wand-svc into sandbox so Grafana is the wrong dashboard", false_lead="Akamai sample leftover", avoided=BAN, knob=".datastream.dataset", old="dataset: sandbox", new="dataset: dock-wand-svc", wrong_knob=".datastream.samplePercent", wrong_old="samplePercent: 1", wrong_new="samplePercent: 100", wrong2_old="destination: splunk-sandbox", wrong2_new="destination: grafana", prefix="akds"),
    dict(vendor="CloudFront realtime", ok_slug="cfront-rt-log-filter-drop-leftover", bad_slug="cfrt-filt-raise-buf-not-filter", noun="gpu", panel="CloudFront RT", needle="cfrt_drop", lie_core="realtime leftover filter cs-host!=dock-gpu-svc so Grafana is empty while S3 still 200", false_lead="CloudFront buffer leftover", avoided=BAN+"; r506 CW metric math", knob=".realtime.filter", old="filter: cs-host!=dock-gpu-svc", new="filter: ", wrong_knob=".realtime.samplingRate", wrong_old="samplingRate: 1", wrong_new="samplingRate: 100", wrong2_old="kinesis: sandbox", wrong2_new="kinesis: hangar", prefix="cfrt"),
    dict(vendor="Bunny CDN", ok_slug="bunny-pullzone-stats-drop-leftover", bad_slug="bunny-pz-raise-cache-not-stats", noun="asu", panel="Bunny pullzone", needle="bunny_stat", lie_core="pullzone leftover EnableLogging=false so Grafana is empty while the edge still 200", false_lead="Bunny cache leftover", avoided=BAN, knob=".pullzone.EnableLogging", old="EnableLogging: false", new="EnableLogging: true", wrong_knob=".pullzone.CacheExpirationTime", wrong_old="CacheExpirationTime: 0", wrong_new="CacheExpirationTime: 3600", wrong2_old="ZoneId: sandbox", wrong2_new="ZoneId: hangar", prefix="bunny"),
    dict(vendor="Vercel Analytics", ok_slug="vercel-logdrain-filter-drop-leftover", bad_slug="verc-drain-raise-sample-not-filter", noun="pca", panel="Vercel logs", needle="verc_log", lie_core="log drain leftover filter env=preview so Grafana is empty while /_logs still 202", false_lead="Vercel sample leftover", avoided=BAN+"; r168 Faro session", knob=".logDrain.filter", old="filter: env=preview", new="filter: env=production", wrong_knob=".analytics.sampleRate", wrong_old="sampleRate: 0.01", wrong_new="sampleRate: 1.0", wrong2_old="project: sandbox", wrong2_new="project: hangar", prefix="verc"),
    dict(vendor="Netlify logs", ok_slug="netlify-log-drain-drop-leftover", bad_slug="ntl-drain-raise-func-not-drain", noun="water", panel="Netlify logs", needle="ntl_log", lie_core="log drain leftover disabled so Grafana is empty while the deploy still 200", false_lead="Netlify functions leftover", avoided=BAN+"; Vercel logdrain plant", knob=".log_drain.enabled", old="enabled: false", new="enabled: true", wrong_knob=".functions.timeout", wrong_old="timeout: 1", wrong_new="timeout: 26", wrong2_old="site_id: sandbox", wrong2_new="site_id: hangar", prefix="ntl"),
    dict(vendor="Render logs", ok_slug="render-logstream-filter-drop-leftover", bad_slug="rend-stream-raise-retain-not-filter", noun="lav", panel="Render logs", needle="rend_log", lie_core="log stream leftover service!=dock-lav-svc so Grafana is empty", false_lead="Render retain leftover", avoided=BAN, knob=".logstream.filter", old="filter: service!=dock-lav-svc", new="filter: ", wrong_knob=".logs.retentionDays", wrong_old="retentionDays: 1", wrong_new="retentionDays: 30", wrong2_old="serviceId: sandbox", wrong2_new="serviceId: hangar", prefix="rend"),
    dict(vendor="Fly.io metrics", ok_slug="flyio-metrics-token-remap-leftover", bad_slug="fly-tok-raise-interval-not-remap", noun="belt", panel="Fly metrics", needle="fly_met", lie_core="metrics leftover token remaps dock-belt-svc into sandbox so Grafana is the wrong dashboard", false_lead="Fly interval leftover", avoided=BAN, knob=".metrics.token", old="token: sandbox", new="token: dock-belt-svc", wrong_knob=".metrics.interval", wrong_old="interval: 5m", wrong_new="interval: 15s", wrong2_old="app: sandbox", wrong2_new="app: hangar", prefix="fly"),
    dict(vendor="Railway obs", ok_slug="railway-obs-filter-drop-leftover", bad_slug="rail-filt-raise-retain-not-filter", noun="cargo", panel="Railway logs", needle="rail_log", lie_core="observability leftover filter service=sandbox so Grafana is empty while the deploy still 200", false_lead="Railway retain leftover", avoided=BAN, knob=".observability.filter", old="filter: service=sandbox", new="filter: service=dock-cargo-svc", wrong_knob=".logs.retention", wrong_old="retention: 1d", wrong_new="retention: 30d", wrong2_old="project: sandbox", wrong2_new="project: hangar", prefix="rail"),
    dict(vendor="Heroku Logplex", ok_slug="heroku-logplex-drain-drop-leftover", bad_slug="hroku-drain-raise-dyno-not-drain", noun="udl", panel="Heroku logs", needle="hroku_log", lie_core="logplex leftover drain disabled so Grafana is empty while `heroku logs` still works", false_lead="Heroku dyno leftover", avoided=BAN, knob=".logplex.drain", old="drain: disabled", new="drain: https://grafana/loki", wrong_knob=".dyno.size", wrong_old="size: hobby", wrong_new="size: standard-2x", wrong2_old="app: sandbox", wrong2_new="app: hangar", prefix="hroku"),
    dict(vendor="DO Insights", ok_slug="do-insights-tag-drop-leftover", bad_slug="doins-tag-raise-alert-not-tag", noun="mdl", panel="DO Insights", needle="do_ins", lie_core="insights leftover drop tag service so Grafana is the wrong dashboard", false_lead="DO alert leftover", avoided=BAN+"; r177 Alloy relabel", knob=".insights.drop_tags", old="drop_tags: [service]", new="drop_tags: []", wrong_knob=".alerts.enabled", wrong_old="enabled: false", wrong_new="enabled: true", wrong2_old="droplet: sandbox", wrong2_new="droplet: hangar", prefix="doins"),
    dict(vendor="Linode Longview", ok_slug="linode-longview-filter-drop-leftover", bad_slug="lview-filt-raise-int-not-filter", noun="nose", panel="Longview", needle="lview_cpu", lie_core="Longview leftover apps filter excludes dock-nose-svc so Grafana is empty", false_lead="Longview interval leftover", avoided=BAN, knob=".longview.apps.exclude", old="exclude: [dock-nose-svc]", new="exclude: []", wrong_knob=".longview.interval", wrong_old="interval: 300", wrong_new="interval: 15", wrong2_old="api_key: sandbox", wrong2_new="api_key: hangar", prefix="lview"),
    dict(vendor="Vultr metrics", ok_slug="vultr-metrics-disable-leftover", bad_slug="vultr-met-raise-alert-not-enable", noun="main", panel="Vultr metrics", needle="vultr_cpu", lie_core="metrics leftover enabled=false so Grafana is empty while the instance still 200", false_lead="Vultr alert leftover", avoided=BAN, knob=".metrics.enabled", old="enabled: false", new="enabled: true", wrong_knob=".alerts.cpu", wrong_old="cpu: 99", wrong_new="cpu: 80", wrong2_old="instance: sandbox", wrong2_new="instance: hangar", prefix="vultr"),
    dict(vendor="Hetzner metrics", ok_slug="hetzner-metrics-token-drop-leftover", bad_slug="hetz-tok-raise-int-not-token", noun="tiller2", panel="Hetzner metrics", needle="hetz_cpu", lie_core="metrics leftover token sandbox so Grafana is the wrong dashboard while hcloud still 200", false_lead="Hetzner interval leftover", avoided=BAN, knob=".metrics.token", old="token: sandbox", new="token: dock-tiller2-svc", wrong_knob=".metrics.interval", wrong_old="interval: 5m", wrong_new="interval: 15s", wrong2_old="server: sandbox", wrong2_new="server: hangar", prefix="hetz"),
    dict(vendor="OVH metrics", ok_slug="ovh-metrics-project-remap-leftover", bad_slug="ovh-proj-raise-retain-not-remap", noun="parkbrk", panel="OVH metrics", needle="ovh_cpu", lie_core="project leftover remaps dock-parkbrk-svc into sandbox so Grafana is the wrong dashboard", false_lead="OVH retain leftover", avoided=BAN, knob=".metrics.project", old="project: sandbox", new="project: dock-parkbrk-svc", wrong_knob=".metrics.retention", wrong_old="retention: 1d", wrong_new="retention: 13m", wrong2_old="region: GRA", wrong2_new="region: BHS", prefix="ovh"),
    dict(vendor="Scaleway Cockpit", ok_slug="scw-cockpit-datasource-remap-leftover", bad_slug="scw-ds-raise-token-not-remap", noun="autobrk", panel="Scaleway Cockpit", needle="scw_cpu", lie_core="datasource leftover remaps dock-autobrk-svc into sandbox so Grafana is the wrong dashboard", false_lead="Scaleway token leftover", avoided=BAN+"; r503 Grafana folder ACL", knob=".cockpit.datasource", old="datasource: sandbox", new="datasource: dock-autobrk-svc", wrong_knob=".cockpit.token", wrong_old="token: sandbox", wrong_new="token: hangar", wrong2_old="region: fr-par", wrong2_new="region: nl-ams", prefix="scw"),
    dict(vendor="UpCloud metrics", ok_slug="upcloud-metrics-disable-leftover", bad_slug="upcl-met-raise-alert-not-enable", noun="spoiler", panel="UpCloud metrics", needle="upcl_cpu", lie_core="metrics leftover enabled=false so Grafana is empty while the server still 200", false_lead="UpCloud alert leftover", avoided=BAN, knob=".metrics.enabled", old="enabled: false", new="enabled: true", wrong_knob=".alerts.disk", wrong_old="disk: 99", wrong_new="disk: 80", wrong2_old="uuid: sandbox", wrong2_new="uuid: hangar", prefix="upcl"),
    dict(vendor="Alibaba ARMS", ok_slug="aliarms-app-remap-wrong-dash-leftover", bad_slug="alarms-app-raise-sample-not-remap", noun="slat", panel="ARMS traces", needle="arms_txn", lie_core="app leftover remaps dock-slat-svc into sandbox so Grafana is the wrong dashboard", false_lead="ARMS sample leftover", avoided=BAN+"; leftover3 NR span-event; r163 tid128", knob=".arms.applicationName", old="applicationName: sandbox", new="applicationName: dock-slat-svc", wrong_knob=".arms.sampleRate", wrong_old="sampleRate: 0.01", wrong_new="sampleRate: 1.0", wrong2_old="region: cn-hangzhou", wrong2_new="region: cn-shanghai", prefix="alarms"),
    dict(vendor="Tencent CLS", ok_slug="tencent-cls-topic-drop-leftover", bad_slug="tcls-topic-raise-index-not-drop", noun="flap", panel="Tencent CLS", needle="tcls_log", lie_core="topic leftover exclude dock-flap-svc so Grafana is empty while PutLogs still 200", false_lead="Tencent CLS index leftover", avoided=BAN+"; leftover3 Splunk frozen", knob=".cls.exclude_topics", old="exclude_topics: [dock-flap-svc]", new="exclude_topics: []", wrong_knob=".cls.index", wrong_old="index: false", wrong_new="index: true", wrong2_old="region: ap-guangzhou", wrong2_new="region: ap-shanghai", prefix="tcls"),
    dict(vendor="Huawei LTS", ok_slug="huawei-lts-filter-drop-leftover", bad_slug="hlts-filt-raise-ttl-not-filter", noun="aileron", panel="Huawei LTS", needle="hlts_log", lie_core="filter leftover service!=dock-aileron-svc so Grafana is empty", false_lead="Huawei LTS TTL leftover", avoided=BAN, knob=".lts.filter", old="filter: service!=dock-aileron-svc", new="filter: ", wrong_knob=".lts.ttl", wrong_old="ttl: 1", wrong_new="ttl: 30", wrong2_old="group: sandbox", wrong2_new="group: hangar", prefix="hlts"),
    dict(vendor="Yandex Monitoring", ok_slug="yandex-mon-folder-remap-leftover", bad_slug="yam-fold-raise-int-not-folder", noun="rudder", panel="Yandex Monitoring", needle="yam_cpu", lie_core="folder leftover remaps dock-rudder-svc into sandbox so Grafana is the wrong dashboard", false_lead="Yandex interval leftover", avoided=BAN, knob=".monitoring.folder", old="folder: sandbox", new="folder: dock-rudder-svc", wrong_knob=".monitoring.interval", wrong_old="interval: 5m", wrong_new="interval: 15s", wrong2_old="cloud: sandbox", wrong2_new="cloud: hangar", prefix="yam"),
    dict(vendor="CF Analytics Engine", ok_slug="cf-ae-dataset-drop-leftover", bad_slug="cfae-ds-raise-index-not-drop", noun="elev", panel="CF AE", needle="cfae_sql", lie_core="dataset leftover write dock-elev-svc into sandbox so Grafana is the wrong dashboard", false_lead="CF AE index leftover", avoided=BAN+"; Cloudflare Logpush plant", knob=".analytics_engine.dataset", old="dataset: sandbox", new="dataset: dock-elev-svc", wrong_knob=".analytics_engine.index", wrong_old="index: off", wrong_new="index: on", wrong2_old="account: sandbox", wrong2_new="account: hangar", prefix="cfae"),
    dict(vendor="Fastly Origin Inspector", ok_slug="fastly-oi-service-drop-leftover", bad_slug="fsoi-svc-raise-sample-not-enable", noun="stab", panel="Fastly OI", needle="fsoi_orig", lie_core="origin inspector leftover service disabled so Grafana is empty while Fastly still 200", false_lead="Fastly OI sample leftover", avoided=BAN+"; Fastly realtime plant", knob=".origin_inspector.enabled", old="enabled: false", new="enabled: true", wrong_knob=".origin_inspector.sample", wrong_old="sample: 1", wrong_new="sample: 100", wrong2_old="service: sandbox", wrong2_new="service: hangar", prefix="fsoi"),
    dict(vendor="Akamai GTM", ok_slug="akamai-gtm-liveness-filter-leftover", bad_slug="akgtm-live-raise-ttl-not-filter", noun="yaw", panel="Akamai GTM", needle="akgtm_live", lie_core="liveness leftover filter datacenter=sandbox so Grafana is empty while the property still 200", false_lead="Akamai GTM TTL leftover", avoided=BAN+"; Akamai DataStream plant", knob=".gtm.liveness.filter", old="filter: datacenter=sandbox", new="filter: datacenter=hangar", wrong_knob=".gtm.ttl", wrong_old="ttl: 3600", wrong_new="ttl: 30", wrong2_old="property: sandbox", wrong2_new="property: hangar", prefix="akgtm"),
    dict(vendor="NS1 Insights", ok_slug="ns1-insights-filter-drop-leftover", bad_slug="ns1-ins-raise-int-not-filter", noun="pfd", panel="NS1 Insights", needle="ns1_qps", lie_core="insights leftover filter zone=sandbox so Grafana is empty while DNS still answers", false_lead="NS1 interval leftover", avoided=BAN, knob=".insights.filter", old="filter: zone=sandbox", new="filter: zone=dock-pfd-svc", wrong_knob=".insights.interval", wrong_old="interval: 1h", wrong_new="interval: 60s", wrong2_old="api_key: sandbox", wrong2_new="api_key: hangar", prefix="ns1"),
    dict(vendor="Route53 query logs", ok_slug="r53-querylog-filter-drop-leftover", bad_slug="r53ql-filt-raise-retain-not-filter", noun="nd", panel="R53 query logs", needle="r53_q", lie_core="query log leftover filter hostedzone=sandbox so Grafana is empty while Route53 still 200", false_lead="R53 retain leftover", avoided=BAN+"; r506 CW metric math; CW Logs r660", knob=".query_log.filter", old="filter: hostedzone=sandbox", new="filter: hostedzone=dock-nd-svc", wrong_knob=".query_log.retention", wrong_old="retention: 1", wrong_new="retention: 30", wrong2_old="log_group: sandbox", wrong2_new="log_group: hangar", prefix="r53ql"),
    dict(vendor="Cloudflare Spectrum", ok_slug="cf-spectrum-logs-drop-leftover", bad_slug="cfspec-log-raise-proxy-not-logs", noun="eicas", panel="CF Spectrum", needle="cfspec_tcp", lie_core="spectrum leftover logs disabled so Grafana is empty while the TCP proxy still 200", false_lead="Cloudflare Spectrum proxy leftover", avoided=BAN+"; Cloudflare Logpush plant", knob=".spectrum.logs", old="logs: false", new="logs: true", wrong_knob=".spectrum.proxy_protocol", wrong_old="proxy_protocol: off", wrong_new="proxy_protocol: v1", wrong2_old="app: sandbox", wrong2_new="app: hangar", prefix="cfspec"),
    dict(vendor="Cloudflare Gateway", ok_slug="cf-gateway-logs-drop-leftover", bad_slug="cfgw-log-raise-policy-not-logs", noun="cdu", panel="CF Gateway", needle="cfgw_dns", lie_core="gateway leftover activity log off so Grafana is empty while DNS still resolves", false_lead="Cloudflare Gateway policy leftover", avoided=BAN+"; Cloudflare Logpush plant", knob=".gateway.activity_log", old="activity_log: off", new="activity_log: on", wrong_knob=".gateway.policy", wrong_old="policy: block-all", wrong_new="policy: allow-hangar", wrong2_old="account: sandbox", wrong2_new="account: hangar", prefix="cfgw"),
    dict(vendor="Zscaler NSS", ok_slug="zscaler-nss-filter-drop-leftover", bad_slug="zscaler-nss-raise-feed-not-filter", noun="fmc", panel="Zscaler NSS", needle="zscaler_web", lie_core="NSS leftover filter user=sandbox so Grafana is empty while the cloud still 200", false_lead="Zscaler NSS feed leftover", avoided=BAN, knob=".nss.filter", old="filter: user=sandbox", new="filter: user=dock-fmc-svc", wrong_knob=".nss.feed", wrong_old="feed: web", wrong_new="feed: web,fw,dns", wrong2_old="cloud: zscalerthree", wrong2_new="cloud: zscloud", prefix="zscaler"),
    dict(vendor="Cortex XDR", ok_slug="panw-xdr-filter-drop-leftover", bad_slug="pxdr-filt-raise-sev-not-filter", noun="irs", panel="Cortex XDR", needle="pxdr_alert", lie_core="XDR leftover filter endpoint=sandbox so Grafana is empty while the agent still 202", false_lead="Cortex XDR severity leftover", avoided=BAN+"; leftover3 Falco; Wiz r628", knob=".xdr.filter", old="filter: endpoint=sandbox", new="filter: endpoint=dock-irs-svc", wrong_knob=".xdr.severity", wrong_old="severity: informational", wrong_new="severity: medium", wrong2_old="tenant: sandbox", wrong2_new="tenant: hangar", prefix="pxdr"),
    dict(vendor="SentinelOne", ok_slug="s1-ranger-filter-drop-leftover", bad_slug="s1-rang-raise-site-not-filter", noun="adiru", panel="SentinelOne", needle="s1_alert", lie_core="Ranger leftover filter site=sandbox so Grafana is empty while the agent still 202", false_lead="SentinelOne site leftover", avoided=BAN+"; leftover3 Falco; CrowdSec r676", knob=".ranger.filter", old="filter: site=sandbox", new="filter: site=dock-adiru-svc", wrong_knob=".ranger.site_id", wrong_old="site_id: sandbox", wrong_new="site_id: hangar", wrong2_old="console: usea1", wrong2_new="console: apne1", prefix="s1"),
    dict(vendor="Defender XDR", ok_slug="defender-xdr-table-drop-leftover", bad_slug="defxdr-tbl-raise-retain-not-table", noun="radalt", panel="Defender XDR", needle="defxdr_alert", lie_core="advanced hunting leftover tables drop DeviceNetworkEvents so Grafana is empty", false_lead="Defender retain leftover", avoided=BAN+"; Azure diag r662", knob=".hunting.tables.drop", old="drop: [DeviceNetworkEvents]", new="drop: []", wrong_knob=".retention.days", wrong_old="days: 1", wrong_new="days: 30", wrong2_old="workspace: sandbox", wrong2_new="workspace: hangar", prefix="defxdr"),
    dict(vendor="XSOAR", ok_slug="xsoar-playbook-filter-drop-leftover", bad_slug="xsoar-pb-raise-sla-not-filter", noun="tcas", panel="XSOAR incidents", needle="xsoar_inc", lie_core="playbook leftover filter type=Phishing-only so Grafana is empty while incidents still 202", false_lead="XSOAR SLA leftover", avoided=BAN+"; PagerDuty orch; r515 Rootly", knob=".playbooks.filter", old="filter: type=Phishing", new="filter: type=all", wrong_knob=".sla.ack_minutes", wrong_old="ack_minutes: 120", wrong_new="ack_minutes: 5", wrong2_old="server: sandbox", wrong2_new="server: hangar", prefix="xsoar"),
    dict(vendor="TheHive", ok_slug="thehive-alert-filter-drop-leftover", bad_slug="thive-alrt-raise-case-not-filter", noun="xpdr", panel="TheHive alerts", needle="thive_alert", lie_core="alert leftover status=Ignored so Grafana is empty while Cortex still 201", false_lead="TheHive case leftover", avoided=BAN+"; leftover3 Falco; XSOAR playbook plant", knob=".alerts.status_filter", old="status_filter: Ignored", new="status_filter: New,Updated,Ignored", wrong_knob=".cases.severity", wrong_old="severity: 1", wrong_new="severity: 3", wrong2_old="org: sandbox", wrong2_new="org: hangar", prefix="thive"),
    dict(vendor="MISP", ok_slug="misp-feed-filter-drop-leftover", bad_slug="misp-feed-raise-pub-not-filter", noun="dme", panel="MISP events", needle="misp_ioc", lie_core="feed leftover filter published=0 so Grafana is empty while /events still 200", false_lead="MISP publish leftover", avoided=BAN, knob=".feeds.filter.published", old="published: 0", new="published: 1", wrong_knob=".feeds.publish", wrong_old="publish: false", wrong_new="publish: true", wrong2_old="orgc: sandbox", wrong2_new="orgc: hangar", prefix="misp"),
    dict(vendor="OpenCTI", ok_slug="opencti-connector-drop-leftover", bad_slug="octi-conn-raise-ingest-not-drop", noun="vor", panel="OpenCTI connectors", needle="octi_ind", lie_core="connector leftover disabled grafana so Grafana is empty while GraphQL still 200", false_lead="OpenCTI ingest leftover", avoided=BAN+"; MISP feed plant", knob=".connectors.grafana.enabled", old="enabled: false", new="enabled: true", wrong_knob=".ingest.workers", wrong_old="workers: 0", wrong_new="workers: 4", wrong2_old="url: http://sandbox", wrong2_new="url: http://opencti", prefix="octi"),
    dict(vendor="OSSEC", ok_slug="ossec-decoder-drop-leftover", bad_slug="ossec-dec-raise-email-not-decoder", noun="ils", panel="OSSEC alerts", needle="ossec_alert", lie_core="decoder leftover drop hangar so Grafana is empty while ossec.log still has lines", false_lead="OSSEC email leftover", avoided=BAN+"; leftover3 Falco; Wazuh r593", knob=".decoders.drop", old="drop: [hangar]", new="drop: []", wrong_knob=".global.email_alert_level", wrong_old="email_alert_level: 16", wrong_new="email_alert_level: 7", wrong2_old="logall: no", wrong2_new="logall: yes", prefix="ossec"),
    dict(vendor="Suricata", ok_slug="suricata-eve-filter-drop-leftover", bad_slug="suri-eve-raise-flow-not-filter", noun="marker", panel="Suricata eve", needle="suri_alert", lie_core="eve leftover types omit alert so Grafana is empty while eve.json still grows", false_lead="Suricata flow leftover", avoided=BAN+"; leftover3 Falco", knob=".outputs.eve-log.types", old="types: [stats]", new="types: [alert, http, dns, tls, flow]", wrong_knob=".outputs.eve-log.community-id", wrong_old="community-id: false", wrong_new="community-id: true", wrong2_old="default-log-dir: /tmp", wrong2_new="default-log-dir: /var/log/suricata", prefix="suri"),
    dict(vendor="Zeek", ok_slug="zeek-log-filter-drop-leftover", bad_slug="zeek-log-raise-rotate-not-filter", noun="wxrad", panel="Zeek logs", needle="zeek_conn", lie_core="filter leftover Log::disable_stream Conn so Grafana is empty while traffic still flows", false_lead="Zeek rotate leftover", avoided=BAN+"; Suricata eve plant", knob=".logs.disable_stream", old="disable_stream: [Conn]", new="disable_stream: []", wrong_knob=".logs.rotation_interval", wrong_old="rotation_interval: 1 day", wrong_new="rotation_interval: 1 hr", wrong2_old="LogAscii::use_json: F", wrong2_new="LogAscii::use_json: T", prefix="zeek"),
    dict(vendor="Snort", ok_slug="snort-alert-filter-drop-leftover", bad_slug="snort-alrt-raise-bpf-not-filter", noun="satcom", panel="Snort alerts", needle="snort_gid", lie_core="output leftover alert_syslog disabled so Grafana is empty while snort still -A console", false_lead="Snort BPF leftover", avoided=BAN+"; Suricata eve plant", knob=".output.alert_syslog", old="alert_syslog: off", new="alert_syslog: LOG_AUTH LOG_ALERT", wrong_knob=".ipvar.HOME_NET", wrong_old="HOME_NET: any", wrong_new="HOME_NET: 10.0.0.0/8", wrong2_old="config disable_decode_alerts", wrong2_new="config enable_decode_alerts", prefix="snort"),
    dict(vendor="ntopng", ok_slug="ntopng-interface-drop-leftover", bad_slug="ntop-if-raise-redis-not-iface", noun="acars", panel="ntopng ifaces", needle="ntop_if", lie_core="interface leftover -i none so Grafana is empty while ntopng still 3000", false_lead="ntopng redis leftover", avoided=BAN, knob=".interfaces", old="interfaces: []", new="interfaces: [eth0]", wrong_knob=".redis", wrong_old="redis: 127.0.0.1:0", wrong_new="redis: 127.0.0.1:6379", wrong2_old="community: ntop", wrong2_new="community: hangar", prefix="ntop"),
    dict(vendor="Elastiflow", ok_slug="elastiflow-codec-drop-leftover", bad_slug="eflow-codec-raise-ecs-not-codec", noun="adsb", panel="Elastiflow", needle="eflow_ipfix", lie_core="codec leftover netflow disabled so Grafana is empty while UDP/9995 still 200", false_lead="Elastiflow ECS leftover", avoided=BAN+"; leftover3 OpenSearch blocks", knob=".EF_FLOW_DECODER_NETFLOW", old="EF_FLOW_DECODER_NETFLOW: false", new="EF_FLOW_DECODER_NETFLOW: true", wrong_knob=".EF_OUTPUT_ELASTICSEARCH_ECS_ENABLE", wrong_old="ECS_ENABLE: false", wrong_new="ECS_ENABLE: true", wrong2_old="EF_FLOW_SERVER_UDP_PORT: 0", wrong2_new="EF_FLOW_SERVER_UDP_PORT: 9995", prefix="eflow"),
    dict(vendor="Akvorado", ok_slug="akvorado-inlet-filter-drop-leftover", bad_slug="akvo-inlet-raise-kafka-not-filter", noun="elac", panel="Akvorado flows", needle="akvo_sflow", lie_core="inlet leftover filter exporter=sandbox so Grafana is empty while sFlow still arrives", false_lead="Akvorado kafka leftover", avoided=BAN+"; Elastiflow codec plant", knob=".inlet.filter", old="filter: exporter=sandbox", new="filter: exporter=dock-elac-svc", wrong_knob=".kafka.topic", wrong_old="topic: sandbox-flows", wrong_new="topic: flows", wrong2_old="http.listen: 127.0.0.1:8080", wrong2_new="http.listen: 0.0.0.0:8080", prefix="akvo"),
    dict(vendor="pmacct", ok_slug="pmacct-plugin-drop-leftover", bad_slug="pmacct-plug-raise-nfacctd-not-plugin", noun="sec", panel="pmacct flows", needle="pmacct_nf", lie_core="plugins leftover print only so Grafana is empty while nfacctd still listens", false_lead="pmacct nfacctd leftover", avoided=BAN, knob=".plugins", old="plugins: print", new="plugins: kafka[hangar]", wrong_knob=".nfacctd_port", wrong_old="nfacctd_port: 0", wrong_new="nfacctd_port: 2100", wrong2_old="aggregate: none", wrong2_new="aggregate: src_host,dst_host", prefix="pmacct"),
    dict(vendor="sFlow-RT", ok_slug="sflowrt-app-disable-leftover", bad_slug="sflow-app-raise-thresh-not-enable", noun="fac", panel="sFlow-RT", needle="sflow_app", lie_core="app leftover mininet-dashboard disabled so Grafana is empty while sFlow still 6343", false_lead="sFlow-RT threshold leftover", avoided=BAN+"; ntopng interface plant", knob=".app.mininet-dashboard", old="mininet-dashboard: off", new="mininet-dashboard: on", wrong_knob=".flow.threshold", wrong_old="threshold: 0", wrong_new="threshold: 1000000", wrong2_old="http.port: 0", wrong2_new="http.port: 8008", prefix="sflow"),
    dict(vendor="nfdump", ok_slug="nfdump-filter-drop-leftover", bad_slug="nfd-filt-raise-ident-not-filter", noun="sfcc", panel="nfdump", needle="nfd_nfcapd", lie_core="filter leftover proto tcp and port 0 so Grafana is empty while nfcapd still writes", false_lead="nfdump ident leftover", avoided=BAN, knob=".nfdump.filter", old="filter: proto tcp and port 0", new="filter: any", wrong_knob=".nfcapd.ident", wrong_old="ident: sandbox", wrong_new="ident: dock-sfcc-svc", wrong2_old="datadir: /tmp", wrong2_new="datadir: /data/nfdump", prefix="nfd"),
    dict(vendor="goflow2", ok_slug="goflow2-transport-drop-leftover", bad_slug="gflow-tr-raise-listen-not-transport", noun="lgciu", panel="goflow2", needle="gflow_ipfix", lie_core="transport leftover file=/dev/null so Grafana is empty while UDP still 2055", false_lead="goflow2 listen leftover", avoided=BAN+"; Elastiflow codec plant", knob=".transport", old="transport: file /dev/null", new="transport: kafka hangar/flows", wrong_knob=".listen", wrong_old="listen: :0", wrong_new="listen: :2055", wrong2_old="format: binary", wrong2_new="format: json", prefix="gflow"),
    dict(vendor="MaxMind GeoIP", ok_slug="maxmind-mmdb-path-drop-leftover", bad_slug="mmdb-path-raise-edition-not-path", noun="bscu", panel="GeoIP", needle="mmdb_cc", lie_core="mmdb leftover path /tmp/empty so Grafana country panels are empty while nginx still 200", false_lead="MaxMind edition leftover", avoided=BAN, knob=".mmdb.path", old="path: /tmp/empty.mmdb", new="path: /usr/share/GeoIP/GeoLite2-City.mmdb", wrong_knob=".mmdb.edition", wrong_old="edition: GeoLite2-ASN", wrong_new="edition: GeoLite2-City", wrong2_old="account_id: 0", wrong2_new="account_id: 8842", prefix="mmdb"),
    dict(vendor="Cloudflare Workers AE SQL", ok_slug="cf-workers-sql-dataset-drop-leftover", bad_slug="cfwsql-ds-raise-bind-not-dataset", noun="cscu", panel="Workers SQL", needle="cfw_sql", lie_core="dataset leftover binding SANDBOX so Grafana is the wrong dashboard while wrangler still 200", false_lead="Workers bind leftover", avoided=BAN+"; CF Analytics Engine plant", knob=".analytics_engine_datasets.binding", old="binding: SANDBOX", new="binding: hangar", wrong_knob=".workers.compatibility_date", wrong_old="compatibility_date: 2022-01-01", wrong_new="compatibility_date: 2026-01-01", wrong2_old="name: sandbox", wrong2_new="name: hangar", prefix="cfwsql"),
    dict(vendor="Fastly WAF", ok_slug="fastly-waf-owasp-paranoia-drop-leftover", bad_slug="fwaf-par-raise-mode-not-paranoia", noun="fcdc", panel="Fastly WAF", needle="fwaf_block", lie_core="OWASP leftover paranoia=0 plus disabled so Grafana is empty while the site still 200", false_lead="Fastly WAF mode leftover", avoided=BAN+"; Fastly realtime plant", knob=".waf.owasp.paranoia_level", old="paranoia_level: 0", new="paranoia_level: 1", wrong_knob=".waf.mode", wrong_old="mode: log", wrong_new="mode: block", wrong2_old="prefetch: off", wrong2_new="prefetch: on", prefix="fwaf"),
    dict(vendor="Akamai WAF", ok_slug="akamai-waf-policy-disable-leftover", bad_slug="akwaf-pol-raise-mode-not-enable", noun="fwc", panel="Akamai WAF", needle="akwaf_deny", lie_core="security policy leftover enabled=false so Grafana is empty while the property still 200", false_lead="Akamai WAF mode leftover", avoided=BAN+"; Akamai GTM plant", knob=".securityPolicy.enabled", old="enabled: false", new="enabled: true", wrong_knob=".securityPolicy.mode", wrong_old="mode: evaluation", wrong_new="mode: enforcement", wrong2_old="configId: 0", wrong2_new="configId: 88421", prefix="akwaf"),
    dict(vendor="AWS WAF logs", ok_slug="awswaf-log-filter-drop-leftover", bad_slug="awaf-log-raise-sample-not-filter", noun="sdatc", panel="AWS WAF", needle="awaf_block", lie_core="logging leftover redactedFields plus filter DROP so Grafana is empty while GetSampledRequests still 200", false_lead="AWS WAF sample leftover", avoided=BAN+"; r506 CW metric math", knob=".logging.filter", old="filter: DROP", new="filter: ", wrong_knob=".logging.sampledRequestsEnabled", wrong_old="sampledRequestsEnabled: false", wrong_new="sampledRequestsEnabled: true", wrong2_old="logDestinationConfigs: []", wrong2_new="logDestinationConfigs: [arn:aws:logs:hangar]", prefix="awaf"),
    dict(vendor="GCP Armor", ok_slug="gcparmor-log-off-leftover", bad_slug="garmor-log-raise-preview-not-enable", noun="cpc", panel="Cloud Armor", needle="garmor_deny", lie_core="logConfig leftover enable=false so Grafana is empty while the backend still 200", false_lead="Cloud Armor preview leftover", avoided=BAN+"; GCP log exclusion r661", knob=".logConfig.enable", old="enable: false", new="enable: true", wrong_knob=".preview", wrong_old="preview: true", wrong_new="preview: false", wrong2_old="action: deny(404)", wrong2_new="action: allow", prefix="garmor"),
    dict(vendor="Azure Front Door WAF", ok_slug="afd-waf-log-drop-leftover", bad_slug="afdwaf-log-raise-mode-not-enable", noun="agcu", panel="AFD WAF", needle="afdwaf_block", lie_core="WAF leftover diagnostics logs=false so Grafana is empty while Front Door still 200", false_lead="AFD WAF mode leftover", avoided=BAN+"; Azure diag r662", knob=".diagnostics.logs", old="logs: false", new="logs: true", wrong_knob=".policySettings.mode", wrong_old="mode: Detection", wrong_new="mode: Prevention", wrong2_old="sku: Standard_AzureFrontDoor", wrong2_new="sku: Premium_AzureFrontDoor", prefix="afdwaf"),
    dict(vendor="Kong", ok_slug="kong-prometheus-plugin-off-leftover", bad_slug="kong-prom-raise-status-not-plugin", noun="idg", panel="Kong metrics", needle="kong_up", lie_core="prometheus plugin leftover enabled=false so Grafana is empty while /status still 200", false_lead="Kong status leftover", avoided=BAN+"; Traefik metrics r707", knob=".plugins.prometheus.enabled", old="enabled: false", new="enabled: true", wrong_knob=".status_listen", wrong_old="status_listen: off", wrong_new="status_listen: 0.0.0.0:8100", wrong2_old="database: off", wrong2_new="database: postgres", prefix="kong"),
    dict(vendor="APISIX", ok_slug="apisix-prometheus-off-leftover", bad_slug="apisix-prom-raise-admin-not-enable", noun="gcu", panel="APISIX metrics", needle="apisix_up", lie_core="plugin leftover prometheus disabled so Grafana is empty while the gateway still 9080", false_lead="APISIX admin leftover", avoided=BAN+"; Kong prometheus plant", knob=".plugins.prometheus", old="prometheus: false", new="prometheus: true", wrong_knob=".admin.listen", wrong_old="listen: 127.0.0.1:9180", wrong_new="listen: 0.0.0.0:9180", wrong2_old="enable_admin: false", wrong2_new="enable_admin: true", prefix="apisix"),
    dict(vendor="Tyk", ok_slug="tyk-enable-analytics-off-leftover", bad_slug="tyk-an-raise-pump-not-enable", noun="tru", panel="Tyk analytics", needle="tyk_api", lie_core="analytics leftover enable_analytics=false so Grafana is empty while the gateway still 8080", false_lead="Tyk pump leftover", avoided=BAN+"; Kong prometheus plant", knob=".enable_analytics", old="enable_analytics: false", new="enable_analytics: true", wrong_knob=".pump.enable", wrong_old="enable: false", wrong_new="enable: true", wrong2_old="listen_port: 0", wrong2_new="listen_port: 8080", prefix="tyk"),
    dict(vendor="KrakenD", ok_slug="krakend-telemetry-off-leftover", bad_slug="krak-tel-raise-timeout-not-enable", noun="bat", panel="KrakenD metrics", needle="krak_up", lie_core="telemetry leftover opencensus disabled so Grafana is empty while the gateway still 8080", false_lead="KrakenD timeout leftover", avoided=BAN+"; r384 OTel forward", knob=".extra_config.telemetry/opencensus", old="opencensus: {}", new="opencensus: {exporters: {prometheus: {port: 9091}}}", wrong_knob=".timeout", wrong_old="timeout: 1ms", wrong_new="timeout: 2s", wrong2_old="port: 0", wrong2_new="port: 8080", prefix="krak"),
    dict(vendor="Caddy", ok_slug="caddy-metrics-off-leftover", bad_slug="caddy-met-raise-admin-not-enable", noun="hotbat", panel="Caddy metrics", needle="caddy_up", lie_core="metrics leftover off so Grafana is empty while :443 still 200", false_lead="Caddy admin leftover", avoided=BAN+"; nginx exporter r690", knob=".metrics", old="metrics off", new="metrics /metrics", wrong_knob=".admin", wrong_old="admin off", wrong_new="admin 0.0.0.0:2019", wrong2_old="auto_https off", wrong2_new="auto_https on", prefix="caddy"),
    dict(vendor="Traefik Mesh", ok_slug="traefikmesh-metrics-off-leftover", bad_slug="tmesh-met-raise-acl-not-enable", noun="apugen", panel="Traefik Mesh", needle="tmesh_up", lie_core="metrics leftover prometheus disabled so Grafana is empty while the mesh still 80", false_lead="Traefik Mesh ACL leftover", avoided=BAN+"; Traefik metrics r707; Linkerd tap r592", knob=".metrics.prometheus", old="prometheus: false", new="prometheus: true", wrong_knob=".acl", wrong_old="acl: true", wrong_new="acl: false", wrong2_old="logLevel: ERROR", wrong2_new="logLevel: INFO", prefix="tmesh"),
    dict(vendor="Consul Envoy", ok_slug="consul-envoy-stats-drop-leftover", bad_slug="cenv-stats-raise-admin-not-stats", noun="apubleed", panel="Consul Envoy", needle="cenv_up", lie_core="proxy leftover local_connect_timeout plus prometheus bind 127.0.0.1 so Grafana is empty", false_lead="Consul Envoy admin leftover", avoided=BAN+"; Consul Connect r747; leftover3 envoy", knob=".proxy.prometheus.bind_addr", old="bind_addr: 127.0.0.1:9102", new="bind_addr: 0.0.0.0:9102", wrong_knob=".proxy.config.admin_bind_address", wrong_old="admin_bind_address: 127.0.0.1:19000", wrong_new="admin_bind_address: 0.0.0.0:19000", wrong2_old="protocol: tcp", wrong2_new="protocol: http", prefix="cenv"),
    dict(vendor="Gloo Edge", ok_slug="gloo-stats-bind-drop-leftover", bad_slug="gloo-bind-raise-debug-not-addr", noun="packvlv", panel="Gloo stats", needle="gloo_up", lie_core="stats leftover bindAddress 127.0.0.1 so Grafana is empty while the gateway still 80", false_lead="Gloo debug leftover", avoided=BAN+"; Kong prometheus plant", knob=".stats.bindAddress", old="bindAddress: 127.0.0.1:9091", new="bindAddress: 0.0.0.0:9091", wrong_knob=".debug", wrong_old="debug: false", wrong_new="debug: true", wrong2_old="gatewayProxies.Default.disabled: true", wrong2_new="gatewayProxies.Default.disabled: false", prefix="gloo"),
    dict(vendor="Ambassador Emissary", ok_slug="emissary-metrics-off-leftover", bad_slug="emis-met-raise-diag-not-enable", noun="trimair", panel="Emissary metrics", needle="emis_up", lie_core="AMBASSADOR leftover DIAGD_ONLY plus metrics off so Grafana is empty", false_lead="Emissary diag leftover", avoided=BAN+"; Traefik metrics r707", knob=".AMBASSADOR_DISABLE_METRICS", old="AMBASSADOR_DISABLE_METRICS: true", new="AMBASSADOR_DISABLE_METRICS: false", wrong_knob=".AMBASSADOR_DIAGD_ONLY", wrong_old="AMBASSADOR_DIAGD_ONLY: true", wrong_new="AMBASSADOR_DIAGD_ONLY: false", wrong2_old="AMBASSADOR_ID: sandbox", wrong2_new="AMBASSADOR_ID: hangar", prefix="emis"),
    dict(vendor="HAProxy Kubernetes", ok_slug="haproxyk8s-prometheus-off-leftover", bad_slug="hapk8s-prom-raise-sync-not-enable", noun="recirc", panel="HAProxy K8s", needle="hapk8s_up", lie_core="controller leftover prometheus=false so Grafana is empty while Ingress still 200", false_lead="HAProxy K8s sync leftover", avoided=BAN+"; haproxy_exporter r691; ingress-nginx r713", knob=".controller.stats.prometheus", old="prometheus: false", new="prometheus: true", wrong_knob=".controller.sync.period", wrong_old="period: 1h", wrong_new="period: 5s", wrong2_old="ingress.class: sandbox", wrong2_new="ingress.class: haproxy", prefix="hapk8s"),
    dict(vendor="NGINX Ingress snippets", ok_slug="ngxing-server-snippet-drop-leftover", bad_slug="ngxing-snip-raise-class-not-snippet", noun="outflow", panel="NGINX Ingress", needle="ngxing_up", lie_core="server-snippet leftover stub_status off so Grafana is empty while Ingress still 200", false_lead="NGINX Ingress class leftover", avoided=BAN+"; ingress-nginx r713; nginx exporter r690", knob=".controller.config.server-snippet", old="server-snippet: stub_status off;", new="server-snippet: location /nginx_status { stub_status on; }", wrong_knob=".controller.ingressClass", wrong_old="ingressClass: sandbox", wrong_new="ingressClass: nginx", wrong2_old="metrics.enabled: false", wrong2_new="metrics.enabled: true", prefix="ngxing"),
    dict(vendor="Skipper", ok_slug="skipper-metrics-path-drop-leftover", bad_slug="skip-path-raise-proxy-not-path", noun="cabin", panel="Skipper metrics", needle="skip_up", lie_core="metrics leftover -metrics-path /missing so Grafana is empty while routes still 200", false_lead="Skipper proxy leftover", avoided=BAN+"; Traefik metrics r707", knob=".metrics-path", old="metrics-path: /missing", new="metrics-path: /metrics", wrong_knob=".proxy-preserve-host", wrong_old="proxy-preserve-host: false", wrong_new="proxy-preserve-host: true", wrong2_old="address: :0", wrong2_new="address: :9090", prefix="skip"),
    dict(vendor="Voyager", ok_slug="voyager-stats-off-leftover", bad_slug="voy-stats-raise-ha-not-enable", noun="potable", panel="Voyager stats", needle="voy_up", lie_core="stats leftover enableStats=false so Grafana is empty while Ingress still 200", false_lead="Voyager HA leftover", avoided=BAN+"; haproxy_exporter r691", knob=".enableStats", old="enableStats: false", new="enableStats: true", wrong_knob=".haProxy.enabled", wrong_old="enabled: false", wrong_new="enabled: true", wrong2_old="ingress.class: sandbox", wrong2_new="ingress.class: voyager", prefix="voy"),
    dict(vendor="Contour HTTPProxy", ok_slug="contour-httpproxy-metrics-off-leftover", bad_slug="chp-met-raise-tls-not-enable", noun="waste", panel="Contour HTTPProxy", needle="chp_up", lie_core="httpproxy leftover metrics disabled so Grafana is empty while HTTPProxy still 200", false_lead="Contour TLS leftover", avoided=BAN+"; Contour metrics r708", knob=".httpproxy.metrics.enabled", old="enabled: false", new="enabled: true", wrong_knob=".httpproxy.tls.secretName", wrong_old="secretName: sandbox", wrong_new="secretName: hangar-tls", wrong2_old="ingressClassName: sandbox", wrong2_new="ingressClassName: contour", prefix="chp"),
    dict(vendor="Falco Sidekick UI", ok_slug="falcosideui-source-drop-leftover", bad_slug="fsui-src-raise-ttl-not-source", noun="gray", panel="Falco Sidekick UI", needle="fsui_evt", lie_core="source leftover filter priority=emergency so Grafana is empty while Falco still 202", false_lead="Falco Sidekick UI TTL leftover", avoided=BAN+"; leftover3 Falco; falcosidekick r774", knob=".ui.source.filter", old="filter: priority=emergency", new="filter: priority=warning", wrong_knob=".ui.ttl", wrong_old="ttl: 1s", wrong_new="ttl: 1h", wrong2_old="listen: 127.0.0.1:2802", wrong2_new="listen: 0.0.0.0:2802", prefix="fsui"),
    dict(vendor="Trivy Operator Grafana", ok_slug="trivyop-grafana-folder-drop-leftover", bad_slug="tgraf-fold-raise-dash-not-folder", noun="blue", panel="Trivy Grafana", needle="tgraf_cve", lie_core="grafana leftover folder=sandbox so Grafana is the wrong dashboard while VulnerabilityReport still 200", false_lead="Trivy dashboard leftover", avoided=BAN+"; Trivy Operator r633; r503 Grafana folder ACL", knob=".grafana.folder", old="folder: sandbox", new="folder: hangar", wrong_knob=".grafana.defaultDashboardEnabled", wrong_old="defaultDashboardEnabled: false", wrong_new="defaultDashboardEnabled: true", wrong2_old="namespace: trivy-dev", wrong2_new="namespace: trivy", prefix="tgraf"),
    dict(vendor="Falco Talon", ok_slug="falcotalon-rule-disable-leftover", bad_slug="ftalon-rule-raise-action-not-enable", noun="galley", panel="Falco Talon", needle="ftalon_act", lie_core="rule leftover enable=false so Grafana is empty while Falco still 202", false_lead="Falco Talon action leftover", avoided=BAN+"; leftover3 Falco; falcosidekick r774", knob=".rules.enabled", old="enabled: false", new="enabled: true", wrong_knob=".actions.default", wrong_old="default: none", wrong_new="default: kubernetes:label", wrong2_old="listen: 127.0.0.1:2801", wrong2_new="listen: 0.0.0.0:2801", prefix="ftalon"),
    dict(vendor="Cilium Tetragon Grafana", ok_slug="tetragongraf-dashboard-uid-drop-leftover", bad_slug="tgraf-uid-raise-cm-not-uid", noun="oven", panel="Tetragon Grafana", needle="tgraf_exec", lie_core="dashboard leftover uid=sandbox so Grafana is the wrong dashboard while Tetragon still 202", false_lead="Tetragon ConfigMap leftover", avoided=BAN+"; Tetragon export r605; r503 Grafana folder ACL", knob=".grafana.dashboard.uid", old="uid: sandbox", new="uid: dock-oven-svc", wrong_knob=".grafana.configMap.enabled", wrong_old="enabled: false", wrong_new="enabled: true", wrong2_old="namespace: kube-system", wrong2_new="namespace: tetragon", prefix="tgraf"),
    dict(vendor="Pixie", ok_slug="pixie-cluster-id-remap-leftover", bad_slug="pixie-cid-raise-pem-not-remap", noun="coffee", panel="Pixie", needle="pixie_http", lie_core="cluster leftover PxClusterID sandbox so Grafana is the wrong dashboard while PxL still runs", false_lead="Pixie PEM leftover", avoided=BAN+"; leftover3 Pixie prefix; leftover3 eBPF map", knob=".cluster.id", old="id: sandbox", new="id: dock-coffee-svc", wrong_knob=".pem.memory_limit", wrong_old="memory_limit: 1Mi", wrong_new="memory_limit: 2Gi", wrong2_old="cloud_addr: sandbox.withpixie.ai", wrong2_new="cloud_addr: work.withpixie.ai", prefix="pixie"),
    dict(vendor="Parca Agent", ok_slug="parcaagent-relabel-drop-leftover", bad_slug="parcaa-rel-raise-store-not-drop", noun="trolley", panel="Parca Agent", needle="parcaa_cpu", lie_core="relabel leftover drop keep=false for dock-trolley-svc so Grafana is empty while pprof still 200", false_lead="Parca Agent store leftover", avoided=BAN+"; leftover3 parca relabel; leftover3 pyro scrape", knob=".relabel_configs[].action", old="action: drop", new="action: keep", wrong_knob=".remote_store.address", wrong_old="address: http://sandbox:7070", wrong_new="address: http://parca:7070", wrong2_old="debuginfo.disable_upload: true", wrong2_new="debuginfo.disable_upload: false", prefix="parcaa"),
    dict(vendor="Pyroscope Agent", ok_slug="pyroagent-scrape-disable-leftover", bad_slug="pyroa-scrape-raise-period-not-enable", noun="ifehead2", panel="Pyroscope Agent", needle="pyroa_cpu", lie_core="scrape leftover enabled=false so Grafana is empty while pprof still 200", false_lead="Pyroscope Agent period leftover", avoided=BAN+"; leftover3 pyro scrape 24h; Pyroscope operator r682", knob=".scrape_configs[].enabled", old="enabled: false", new="enabled: true", wrong_knob=".scrape_configs[].scrape_interval", wrong_old="scrape_interval: 1h", wrong_new="scrape_interval: 10s", wrong2_old="server.address: http://sandbox:4040", wrong2_new="server.address: http://pyroscope:4040", prefix="pyroa"),
    dict(vendor="Grafana Beyla", ok_slug="beyla-export-mode-drop-leftover", bad_slug="beyla-mode-raise-disco-not-export", noun="seatpdu", panel="Beyla traces", needle="beyla_http", lie_core="export leftover traces=false so Grafana is empty while the process still 200", false_lead="Beyla discovery leftover", avoided=BAN+"; leftover3 Beyla exclude; r384 OTel forward", knob=".export.traces", old="traces: false", new="traces: true", wrong_knob=".discovery.instrument", wrong_old="instrument: []", wrong_new="instrument: [dock-seatpdu-svc]", wrong2_old="open_port: 0", wrong2_new="open_port: 80", prefix="beyla"),
    dict(vendor="OpenLIT", ok_slug="openlit-otlp-endpoint-drop-leftover", bad_slug="olit-ep-raise-sample-not-endpoint", noun="usbpow", panel="OpenLIT", needle="olit_span", lie_core="OTLP leftover endpoint empty so Grafana is empty while the SDK still 200", false_lead="OpenLIT sample leftover", avoided=BAN+"; r384 OTel forward; leftover3 elastic sample", knob=".otlp.endpoint", old="endpoint: ", new="endpoint: http://otelcol:4318", wrong_knob=".tracing.sample_rate", wrong_old="sample_rate: 0", wrong_new="sample_rate: 1.0", wrong2_old="application_name: sandbox", wrong2_new="application_name: dock-usbpow-svc", prefix="olit"),
    dict(vendor="Langfuse", ok_slug="langfuse-project-remap-leftover", bad_slug="lfuse-proj-raise-sample-not-remap", noun="readlt", panel="Langfuse traces", needle="lfuse_gen", lie_core="project leftover remaps dock-readlt-svc into sandbox so Grafana is the wrong dashboard", false_lead="Langfuse sample leftover", avoided=BAN+"; leftover3 honeycomb dynsample", knob=".project.public_key", old="public_key: sandbox", new="public_key: dock-readlt-svc", wrong_knob=".sample_rate", wrong_old="sample_rate: 0.01", wrong_new="sample_rate: 1.0", wrong2_old="host: https://sandbox.langfuse.com", wrong2_new="host: https://cloud.langfuse.com", prefix="lfuse"),
    dict(vendor="Helicone", ok_slug="helicone-property-filter-drop-leftover", bad_slug="heli-prop-raise-cache-not-filter", noun="attpnl", panel="Helicone", needle="heli_llm", lie_core="property leftover Helicone-Property-User sandbox so Grafana is the wrong dashboard", false_lead="Helicone cache leftover", avoided=BAN+"; Langfuse project plant", knob=".Helicone-Property-User", old="Helicone-Property-User: sandbox", new="Helicone-Property-User: dock-attpnl-svc", wrong_knob=".Helicone-Cache-Enabled", wrong_old="Helicone-Cache-Enabled: false", wrong_new="Helicone-Cache-Enabled: true", wrong2_old="Helicone-Auth: Bearer sandbox", wrong2_new="Helicone-Auth: Bearer hangar", prefix="heli"),
    dict(vendor="Phoenix Arize", ok_slug="phoenix-project-remap-leftover", bad_slug="phx-proj-raise-launch-not-remap", noun="paxcall", panel="Phoenix traces", needle="phx_span", lie_core="project leftover remaps dock-paxcall-svc into sandbox so Grafana is the wrong dashboard", false_lead="Phoenix launch leftover", avoided=BAN+"; Langfuse project plant", knob=".phoenix.project_name", old="project_name: sandbox", new="project_name: dock-paxcall-svc", wrong_knob=".phoenix.launch_app", wrong_old="launch_app: false", wrong_new="launch_app: true", wrong2_old="endpoint: http://sandbox:6006", wrong2_new="endpoint: http://phoenix:6006", prefix="phx"),
    dict(vendor="Weights & Biases", ok_slug="wandb-entity-remap-leftover", bad_slug="wandb-ent-raise-mode-not-remap", noun="oxymask", panel="W&B runs", needle="wandb_run", lie_core="entity leftover remaps dock-oxymask-svc into sandbox so Grafana is the wrong dashboard", false_lead="W&B mode leftover", avoided=BAN, knob=".wandb.entity", old="entity: sandbox", new="entity: dock-oxymask-svc", wrong_knob=".wandb.mode", wrong_old="mode: disabled", wrong_new="mode: online", wrong2_old="project: sandbox", wrong2_new="project: hangar", prefix="wandb"),
    dict(vendor="MLflow", ok_slug="mlflow-experiment-remap-leftover", bad_slug="mlf-exp-raise-store-not-remap", noun="lifevest", panel="MLflow runs", needle="mlf_run", lie_core="experiment leftover remaps dock-lifevest-svc into sandbox so Grafana is the wrong dashboard", false_lead="MLflow store leftover", avoided=BAN, knob=".experiment.name", old="name: sandbox", new="name: dock-lifevest-svc", wrong_knob=".tracking.uri", wrong_old="uri: file:///tmp", wrong_new="uri: http://mlflow:5000", wrong2_old="registry: sandbox", wrong2_new="registry: hangar", prefix="mlf"),
    dict(vendor="Neptune.ai", ok_slug="neptune-project-remap-leftover", bad_slug="nept-proj-raise-mode-not-remap", noun="slideraft", panel="Neptune runs", needle="nept_run", lie_core="project leftover remaps dock-slideraft-svc into sandbox so Grafana is the wrong dashboard", false_lead="Neptune mode leftover", avoided=BAN+"; W&B entity plant", knob=".neptune.project", old="project: sandbox/sandbox", new="project: hangar/dock-slideraft-svc", wrong_knob=".neptune.mode", wrong_old="mode: debug", wrong_new="mode: async", wrong2_old="api_token: sandbox", wrong2_new="api_token: hangar", prefix="nept"),
    dict(vendor="ClearML", ok_slug="clearml-project-remap-leftover", bad_slug="cml-proj-raise-out-not-remap", noun="megaphone", panel="ClearML tasks", needle="cml_task", lie_core="project leftover remaps dock-megaphone-svc into sandbox so Grafana is the wrong dashboard", false_lead="ClearML output leftover", avoided=BAN, knob=".clearml.project", old="project: sandbox", new="project: dock-megaphone-svc", wrong_knob=".clearml.output_uri", wrong_old="output_uri: /tmp", wrong_new="output_uri: s3://hangar", wrong2_old="task_name: sandbox", wrong2_new="task_name: hangar", prefix="cml"),
    dict(vendor="DVC Studio", ok_slug="dvcstudio-repo-remap-leftover", bad_slug="dvc-repo-raise-remote-not-remap", noun="crashaxe", panel="DVC Studio", needle="dvc_exp", lie_core="repo leftover remaps dock-crashaxe-svc into sandbox so Grafana is the wrong dashboard", false_lead="DVC remote leftover", avoided=BAN, knob=".studio.repo", old="repo: sandbox/sandbox", new="repo: hangar/dock-crashaxe-svc", wrong_knob=".core.remote", wrong_old="remote: sandbox", wrong_new="remote: hangar-s3", wrong2_old="studio.token: sandbox", wrong2_new="studio.token: hangar", prefix="dvc"),
    dict(vendor="Feast", ok_slug="feast-registry-remap-leftover", bad_slug="feast-reg-raise-online-not-remap", noun="eltbeac", panel="Feast registry", needle="feast_fv", lie_core="registry leftover path sandbox so Grafana is the wrong dashboard while materialize still 0", false_lead="Feast online leftover", avoided=BAN, knob=".registry.path", old="path: s3://sandbox", new="path: s3://hangar/registry.pb", wrong_knob=".online_store.type", wrong_old="type: null", wrong_new="type: redis", wrong2_old="project: sandbox", wrong2_new="project: hangar", prefix="feast"),
    dict(vendor="Tecton", ok_slug="tecton-workspace-remap-leftover", bad_slug="tect-ws-raise-cluster-not-remap", noun="cvrs", panel="Tecton features", needle="tect_fv", lie_core="workspace leftover remaps dock-cvrs-svc into sandbox so Grafana is the wrong dashboard", false_lead="Tecton cluster leftover", avoided=BAN+"; Feast registry plant", knob=".workspace", old="workspace: sandbox", new="workspace: dock-cvrs-svc", wrong_knob=".cluster.name", wrong_old="name: sandbox", wrong_new="name: hangar", wrong2_old="api_key: sandbox", wrong2_new="api_key: hangar", prefix="tect"),
]


assert len(SPECS) == 88, len(SPECS)
for i, spec in enumerate(SPECS):
    _l8(876 + i, **spec)
