"""Observability plants r289-r292. Do not clone r109-r288.

BAN r163 tid128, r172 inferred db, r190 DD UST,
r244 loki-querier-max-concurrent / loki-qconc-rebuild-blooms.
"""

from mill_plants_h import _failp
from mill_plants_l import _okx

MORE = []

# r289 Loki ingestion_rate_strategy local
MORE.append(
    (
        _okx(
            slug="loki-ingestion-rate-strategy-local",
            service="cargo-door-svc",
            dashboard_uid="cdoor-ingrate-1",
            panel="cargo door logs",
            query='{job="cargo-door-svc"} |= "door_jam"',
            lie="limits_config ingestion_rate_strategy local plus ingestion_rate_mb 0.01 429s the door-jam stream on one ingester while Grafana shows empty and other replicas still accept",
            false_lead="max_streams_per_user 1 / max_concurrent 429",
            config_path="loki/cdoor-streams.yaml",
            lie_path="loki/cdoor-ingest.yaml",
            truth_name="ingestion_rate_strategy vs discarded",
            reload_name="loki-ingester",
            side="tenants with global strategy still ingest",
            surfaces="Loki ingestion_rate_strategy local vs Grafana empty 429",
            avoided="r260 max_streams; r244 max_concurrent; r149 burst limit",
            this_is="local strategy 0.01MB/s 429s one ingester shard",
            step_note="False lead streams/qconc 4-5; local 0.01 6-8; global 4 9-12.",
            query_cmd="curl -sS -G $LOKI/loki/api/v1/query_range --data-urlencode 'query={job=\"cargo-door-svc\"} |= \"door_jam\"' | jq '{status,error,n:(.data.result|length)}'",
            false_cmd="yq '.limits_config.max_streams_per_user, .querier.max_concurrent' loki/cdoor-streams.yaml",
            truth_cmd="curl -sS $LOKI/metrics | rg 'loki_discarded_samples_total|ingestion_rate'",
            confirm_cmd="yq '.limits_config.ingestion_rate_strategy, .limits_config.ingestion_rate_mb' loki/cdoor-ingest.yaml",
            reload_cmd="kubectl -n loki rollout restart sts/loki-ingester && kubectl -n loki rollout status sts/loki-ingester --timeout=120s",
            requery_cmd="curl -sS -G $LOKI/loki/api/v1/query_range --data-urlencode 'query={job=\"cargo-door-svc\"} |= \"door_jam\"' | jq '.data.result|length'",
            side_cmd="curl -sS -G $LOKI/loki/api/v1/query_range --data-urlencode 'query={job=\"ssr-meal-svc\"} |= \"error\"' | jq '.data.result|length'",
            final_cmd="yq -r '.limits_config.ingestion_rate_strategy' loki/cdoor-ingest.yaml",
            patch_old="ingestion_rate_strategy: local\n  ingestion_rate_mb: 0.01",
            patch_new="ingestion_rate_strategy: global\n  ingestion_rate_mb: 4",
            runbook_path="runbooks/cdoor-ingrate.md",
            runbook="# cargo-door-svc ingestion_rate_strategy\nlocal 0.01MB/s 429s one shard. Use global 4. Not max_streams.\n",
            goal="cargo-door-svc dashboard cdoor-ingrate-1 cargo door logs empty. discarded rate_limited. Find the strategy lie.",
            plan="Empty → streams/qconc (false) → local 0.01 → global 4.",
            outcome="strategy global. 6 streams. ssr-meal-svc unchanged.",
            obs1='[{"uid":"cdoor-ingrate-1","title":"cargo door logs"}]',
            obs2='{"title":"cargo door logs","targets":[{"expr":"{job=\\"cargo-door-svc\\"} |= \\"door_jam\\""}]}',
            obs3='{"status":"success","error":null,"n":0}',
            obs4="max_streams_per_user: 0\nmax_concurrent: 16  # not r260/r244",
            obs5="streams unlimited; no 429 query",
            obs6="ingestion_rate_strategy: local\ningestion_rate_mb: 0.01",
            obs7='loki_discarded_samples_total{reason="rate_limited"} 440',
            obs8="local 0.01MB/s on this ingester; other shards green",
            obs9="patched global 4",
            obs10='statefulset "loki-ingester" successfully rolled out',
            obs11="6",
            obs12='{"name":"Logs"}',
            obs13="1",
            obs14="wrote runbooks/cdoor-ingrate.md",
            obs15="global",
        ),
        _failp(
            slug="loki-ingrate-raise-streams-not-strategy",
            service="potty-flush-svc",
            dashboard_uid="pflush-ingrate-streams",
            panel="flush logs",
            query='{job="potty-flush-svc"} |= "flush_fail"',
            lie="Raising max_streams_per_user does not ingest lines 429d by ingestion_rate_strategy local 0.01MB/s",
            false_lead="max_streams_per_user 1 drops new streams",
            config_path="loki/pflush-streams.yaml",
            lie_path="loki/pflush-ingest.yaml",
            wrong_path="loki/pflush-streams.yaml",
            reload_name="loki-ingester",
            ticket="OBS-5357",
            xfail="tests/test_pflush_ingrate.py",
            surfaces="max_streams leftover vs ingestion_rate_strategy local",
            avoided="r260 as actual RCA",
            this_is="fail/handoff: max_streams 0, local rate still 0.01",
            step_note="streams 6-10; still 0 11; late local rate 12; handoff 14-15.",
            next_note="Next: OTel transform flatten_data.",
            query_cmd="curl -sS -G $LOKI/loki/api/v1/query_range --data-urlencode 'query={job=\"potty-flush-svc\"} |= \"flush_fail\"' | jq '{status,n:(.data.result|length)}'",
            false_cmd="yq '.limits_config.max_streams_per_user' loki/pflush-streams.yaml",
            reload_cmd="kubectl -n loki rollout restart sts/loki-ingester && kubectl -n loki rollout status sts/loki-ingester --timeout=120s",
            requery_cmd="curl -sS -G $LOKI/loki/api/v1/query_range --data-urlencode 'query={job=\"potty-flush-svc\"} |= \"flush_fail\"' | jq '{status,n:(.data.result|length)}'",
            denied_cmd="kubectl -n loki auth can-i patch configmap/pflush-ingest --as=sre-bot",
            wrong_old="max_streams_per_user: 1",
            wrong_new="max_streams_per_user: 0",
            wrong2_old="max_concurrent: 1",
            wrong2_new="max_concurrent: 16",
            ticket_body="OBS-5357: potty-flush-svc still 0. streams leftover. ingestion_rate_strategy local 0.01. Need global 4. No ingest RBAC.\n",
            goal="potty-flush-svc dashboard pflush-ingrate-streams flush logs empty. Restore lines.",
            plan="Raise max_streams (r260 leftover).",
            outcome="max_streams 0; still 0. Late local 0.01. Handoff OBS-5357.",
            obs1='[{"uid":"pflush-ingrate-streams","title":"flush logs"}]',
            obs2='{"title":"flush logs","targets":[{"expr":"{job=\\"potty-flush-svc\\"} |= \\"flush_fail\\""}]}',
            obs3='{"status":"success","n":0}',
            obs4="max_streams_per_user: 1",
            obs5="treated as r260",
            obs6="loki/pflush-streams.yaml",
            obs7="patched 0",
            obs8='statefulset "loki-ingester" successfully rolled out',
            obs9='{"status":"success","n":0}',
            obs10="patched max_concurrent 16",
            obs11='{"status":"success","n":0}',
            obs12="loki/pflush-ingest.yaml ingestion_rate_strategy local ingestion_rate_mb 0.01 discarded rate_limited 310",
            obs13="no",
            obs14="wrote tickets/OBS-5357.md",
            obs15="xfail tests/test_pflush_ingrate.py",
        ),
    )
)

# r290 OTel transform flatten_data
MORE.append(
    (
        _okx(
            slug="otel-transform-flatten-data",
            service="coffee-brew-svc",
            dashboard_uid="cbrew-flatten-2",
            panel="brew traces",
            query='{span.http.request.header.x-brew-id="b-441"}',
            lie="transform processor flatten_data true collapses nested http.request.header so TraceQL span.http.request.header.x-brew-id is empty while the flat attr lives at http_request_header_x_brew_id",
            false_lead="attributes hash / groupbyattrs",
            config_path="otelcol/cbrew-hash.yaml",
            lie_path="otelcol/cbrew-flatten.yaml",
            truth_name="flatten_data vs nested TraceQL",
            reload_name="otelcol-cbrew",
            side="pipelines without flatten still match nested keys",
            surfaces="OTel transform flatten_data vs TraceQL nested header",
            avoided="r269 attributes hash; r248 groupbyattrs; r155 truncate",
            this_is="flatten_data true rewrites nested header keys",
            step_note="False lead hash/gbattr 4-5; flatten_data 6-8; false 9-12.",
            query_cmd="curl -sS -G $TEMPO/api/search --data-urlencode 'q={span.http.request.header.x-brew-id=\"b-441\"}' | jq '.traces|length'",
            false_cmd="yq '.processors.attributes, .processors.groupbyattrs' otelcol/cbrew-hash.yaml",
            truth_cmd="curl -sS $TEMPO/api/traces/d7189abcdef012345670123456789abc | jq '[.batches[].scopeSpans[].spans[].attributes[]?|select(.key|test(\"brew\"))]'",
            confirm_cmd="yq '.processors.transform' otelcol/cbrew-flatten.yaml",
            reload_cmd="kubectl -n otel rollout restart deploy/otelcol-cbrew && kubectl -n otel rollout status deploy/otelcol-cbrew --timeout=90s",
            requery_cmd="curl -sS -G $TEMPO/api/search --data-urlencode 'q={span.http.request.header.x-brew-id=\"b-441\"}' | jq '.traces|length'",
            side_cmd="curl -sS -G $TEMPO/api/search --data-urlencode 'q={span.http.route=\"/meals\"}' | jq '.traces|length'",
            final_cmd="yq -r '.processors.transform.flatten_data' otelcol/cbrew-flatten.yaml",
            patch_old="flatten_data: true",
            patch_new="flatten_data: false",
            runbook_path="runbooks/cbrew-flatten.md",
            runbook="# coffee-brew-svc transform flatten_data\ntrue flattens nested headers. Set false. Not attributes hash.\n",
            goal="coffee-brew-svc dashboard cbrew-flatten-2 brew traces empty on nested header. Find the flatten_data lie.",
            plan="Empty nested → hash/gbattr (false) → flatten_data true → false.",
            outcome="flatten false. 10 traces. /meals unchanged.",
            obs1='[{"uid":"cbrew-flatten-2","title":"brew traces"}]',
            obs2='{"title":"brew traces","targets":[{"query":"{span.http.request.header.x-brew-id=\\"b-441\\"}"}]}',
            obs3="0",
            obs4="actions: []\nkeys: []  # not r269/r248",
            obs5="hash/gbattr off",
            obs6="flatten_data: true",
            obs7='[{"key":"http_request_header_x_brew_id","value":{"stringValue":"b-441"}}]',
            obs8="nested path gone; flat key present",
            obs9="patched flatten false",
            obs10='deployment "otelcol-cbrew" successfully rolled out',
            obs11="10",
            obs12='{"name":"Traces"}',
            obs13="19",
            obs14="wrote runbooks/cbrew-flatten.md",
            obs15="false",
        ),
        _failp(
            slug="otel-flatten-drop-hash-not-flag",
            service="oven-galley-svc",
            dashboard_uid="oven-flatten-hash",
            panel="oven traces",
            query='{span.http.request.header.x-oven-id="o-12"}',
            lie="Dropping attributes hash does not restore nested TraceQL when transform flatten_data is still true",
            false_lead="attributes processor hash http.route",
            config_path="otelcol/oven-hash.yaml",
            lie_path="otelcol/oven-flatten.yaml",
            wrong_path="otelcol/oven-hash.yaml",
            reload_name="otelcol-oven",
            ticket="OBS-5358",
            xfail="tests/test_oven_flatten.py",
            surfaces="hash leftover vs flatten_data true",
            avoided="r269 as actual RCA",
            this_is="fail/handoff: hash dropped, flatten still true",
            step_note="hash 6-10; still 0 11; late flatten_data 12; handoff 14-15.",
            next_note="Next: Prom scrape enable_compression.",
            query_cmd="curl -sS -G $TEMPO/api/search --data-urlencode 'q={span.http.request.header.x-oven-id=\"o-12\"}' | jq '.traces|length'",
            false_cmd="yq '.processors.attributes' otelcol/oven-hash.yaml",
            reload_cmd="kubectl -n otel rollout restart deploy/otelcol-oven && kubectl -n otel rollout status deploy/otelcol-oven --timeout=90s",
            requery_cmd="curl -sS -G $TEMPO/api/search --data-urlencode 'q={span.http.request.header.x-oven-id=\"o-12\"}' | jq '.traces|length'",
            denied_cmd="kubectl -n otel auth can-i patch configmap/oven-flatten --as=sre-bot",
            wrong_old="actions:\n      - key: http.route\n        action: hash",
            wrong_new="actions: []",
            wrong2_old="keys: [http.route]",
            wrong2_new="keys: []",
            ticket_body="OBS-5358: oven-galley-svc nested header still 0. hash leftover. flatten_data true. Need false. No transform RBAC.\n",
            goal="oven-galley-svc dashboard oven-flatten-hash oven traces empty. Restore nested header search.",
            plan="Drop attributes hash (r269 leftover).",
            outcome="hash off; still 0. Late flatten_data true. Handoff OBS-5358.",
            obs1='[{"uid":"oven-flatten-hash","title":"oven traces"}]',
            obs2='{"title":"oven traces","targets":[{"query":"{span.http.request.header.x-oven-id=\\"o-12\\"}"}]}',
            obs3="0",
            obs4="actions:\n  - key: http.route\n    action: hash",
            obs5="treated as r269",
            obs6="otelcol/oven-hash.yaml",
            obs7="patched actions []",
            obs8='deployment "otelcol-oven" successfully rolled out',
            obs9="0",
            obs10="patched keys []",
            obs11="0",
            obs12="otelcol/oven-flatten.yaml flatten_data true; attr http_request_header_x_oven_id=o-12",
            obs13="no",
            obs14="wrote tickets/OBS-5358.md",
            obs15="xfail tests/test_oven_flatten.py",
        ),
    )
)

# r291 Prom scrape enable_compression
MORE.append(
    (
        _okx(
            slug="prom-scrape-enable-compression-gzip",
            service="ice-drawer-svc",
            dashboard_uid="icedrw-comp-3",
            panel="ice drawer C",
            query='avg(ice_drawer_celsius{job="ice-drawer-svc"})',
            lie="scrape enable_compression true plus the app /metrics is identity (no gzip) so Prometheus 400s the body and Grafana is empty while curl --raw shows the gauge",
            false_lead="body_size_limit / fallback_scrape_protocol",
            config_path="prom/icedrw-body.yaml",
            lie_path="prom/icedrw-comp.yaml",
            truth_name="enable_compression vs Content-Encoding",
            reload_name="prom-scrape",
            side="jobs that gzip /metrics still scrape",
            surfaces="Prometheus enable_compression vs identity /metrics empty",
            avoided="r238 body_size; r138 protobuf on text; r260 not protobuf",
            this_is="enable_compression expects gzip; app sends identity",
            step_note="False lead body/proto 4-5; enable_compression 6-8; false 9-12.",
            query_cmd="curl -sS -G $MIMIR/prometheus/api/v1/query --data-urlencode 'query=avg(ice_drawer_celsius{job=\"ice-drawer-svc\"})'",
            false_cmd="yq '.scrape_configs[]|select(.job_name==\"ice-drawer-svc\")|{body_size_limit,fallback_scrape_protocol}' prom/icedrw-body.yaml",
            truth_cmd="curl -sS -D- http://ice-drawer-svc:8080/metrics | rg -i 'content-encoding|ice_drawer_celsius' | head",
            confirm_cmd="yq '.scrape_configs[]|select(.job_name==\"ice-drawer-svc\").enable_compression' prom/icedrw-comp.yaml",
            reload_cmd="kubectl -n prom rollout restart deploy/prom-scrape && kubectl -n prom rollout status deploy/prom-scrape --timeout=90s",
            requery_cmd="curl -sS -G $MIMIR/prometheus/api/v1/query --data-urlencode 'query=avg(ice_drawer_celsius{job=\"ice-drawer-svc\"})'",
            side_cmd="curl -sS -G $MIMIR/prometheus/api/v1/query --data-urlencode 'query=avg(ice_drawer_celsius{job=\"ssr-meal-svc\"})' | jq '.data.result|length'",
            final_cmd="yq -r '.scrape_configs[]|select(.job_name==\"ice-drawer-svc\").enable_compression' prom/icedrw-comp.yaml",
            patch_old="enable_compression: true",
            patch_new="enable_compression: false  # app Content-Encoding: identity",
            runbook_path="runbooks/icedrw-compression.md",
            runbook="# ice-drawer-svc enable_compression\ntrue expects gzip; app identity. Set false. Not body_size.\n",
            goal="ice-drawer-svc dashboard icedrw-comp-3 ice drawer C empty. curl shows -18. Find the compression lie.",
            plan="Empty → body/proto (false) → enable_compression true → false.",
            outcome="compression false. C=-18. ssr-meal-svc unchanged.",
            obs1='[{"uid":"icedrw-comp-3","title":"ice drawer"}]',
            obs2='{"title":"ice drawer C","targets":[{"expr":"avg(ice_drawer_celsius{job=\\"ice-drawer-svc\\"})"}]}',
            obs3='{"status":"success","data":{"result":[]}}',
            obs4="body_size_limit: 8MB  # not r238",
            obs5="body unlimited",
            obs6="enable_compression: true",
            obs7="content-encoding: identity\nice_drawer_celsius -18",
            obs8="identity body; scrape asked gzip",
            obs9="patched false",
            obs10='deployment "prom-scrape" successfully rolled out',
            obs11='{"status":"success","data":{"result":[{"value":[1710000600,"-18"]}]}}',
            obs12='{"name":"Timeseries"}',
            obs13="1",
            obs14="wrote runbooks/icedrw-compression.md",
            obs15="false",
        ),
        _failp(
            slug="prom-comp-raise-body-not-gzip",
            service="wine-chill-svc",
            dashboard_uid="wine-comp-body",
            panel="wine C",
            query='avg(wine_chill_celsius{job="wine-chill-svc"})',
            lie="Raising body_size_limit does not ingest identity /metrics while enable_compression is true",
            false_lead="scrape body_size_limit drops the /metrics body",
            config_path="prom/wine-body.yaml",
            lie_path="prom/wine-comp.yaml",
            wrong_path="prom/wine-body.yaml",
            reload_name="prom-scrape",
            ticket="OBS-5359",
            xfail="tests/test_wine_comp.py",
            surfaces="body leftover vs enable_compression gzip",
            avoided="r238 as actual RCA",
            this_is="fail/handoff: body 8MB, enable_compression still true",
            step_note="body 6-10; still empty 11; late enable_compression 12; handoff 14-15.",
            next_note="Next: Tempo max_bytes_per_tag_values_query.",
            query_cmd="curl -sS -G $MIMIR/prometheus/api/v1/query --data-urlencode 'query=avg(wine_chill_celsius{job=\"wine-chill-svc\"})'",
            false_cmd="yq '.scrape_configs[]|select(.job_name==\"wine-chill-svc\").body_size_limit' prom/wine-body.yaml",
            reload_cmd="kubectl -n prom rollout restart deploy/prom-scrape && kubectl -n prom rollout status deploy/prom-scrape --timeout=90s",
            requery_cmd="curl -sS -G $MIMIR/prometheus/api/v1/query --data-urlencode 'query=avg(wine_chill_celsius{job=\"wine-chill-svc\"})'",
            denied_cmd="kubectl -n prom auth can-i patch configmap/wine-comp --as=sre-bot",
            wrong_old="body_size_limit: 256KB",
            wrong_new="body_size_limit: 8MB",
            wrong2_old="sample_limit: 2000",
            wrong2_new="sample_limit: 0",
            ticket_body="OBS-5359: wine-chill-svc still empty. body leftover. enable_compression true vs identity. Need false. No scrape RBAC.\n",
            goal="wine-chill-svc dashboard wine-comp-body wine C empty. Restore series.",
            plan="Raise body_size_limit (r238 leftover).",
            outcome="body 8MB; still empty. Late enable_compression true. Handoff OBS-5359.",
            obs1='[{"uid":"wine-comp-body","title":"wine chill"}]',
            obs2='{"title":"wine C","targets":[{"expr":"avg(wine_chill_celsius{job=\\"wine-chill-svc\\"})"}]}',
            obs3='{"status":"success","data":{"result":[]}}',
            obs4="body_size_limit: 256KB",
            obs5="treated as r238",
            obs6="prom/wine-body.yaml",
            obs7="patched 8MB",
            obs8='deployment "prom-scrape" successfully rolled out',
            obs9='{"status":"success","data":{"result":[]}}',
            obs10="patched sample_limit 0",
            obs11='{"status":"success","data":{"result":[]}}',
            obs12="prom/wine-comp.yaml enable_compression true; /metrics Content-Encoding identity wine_chill_celsius 8",
            obs13="no",
            obs14="wrote tickets/OBS-5359.md",
            obs15="xfail tests/test_wine_comp.py",
        ),
    )
)

# r292 Tempo max_bytes_per_tag_values_query
MORE.append(
    (
        _okx(
            slug="tempo-max-bytes-per-tag-values",
            service="amenity-kit-svc",
            dashboard_uid="akit-tagbytes-4",
            panel="amenity traces",
            query='{resource.service.name="amenity-kit-svc"}',
            lie="query_frontend.search.max_bytes_per_tag_values_query 64 so Grafana service dropdown is empty and Search never sends a service.name while GET by-id still works",
            false_lead="search.enabled false / default_result_limit 0",
            config_path="tempo/akit-searchoff.yaml",
            lie_path="tempo/akit-tagbytes.yaml",
            truth_name="max_bytes_per_tag_values_query vs by-id",
            reload_name="tempo-query-frontend",
            side="frontends with 1MiB tag values still populate dropdowns",
            surfaces="Tempo max_bytes_per_tag_values_query vs Grafana empty service dropdown",
            avoided="r247 search.enabled; r281 default_result_limit; r254 max_spans",
            this_is="64-byte tag-values cap empties the service dropdown",
            step_note="False lead enabled/dlimit 4-5; tag bytes 64 6-8; 1MiB 9-12.",
            query_cmd="curl -sS $TEMPO/api/search/tag/resource.service.name/values | jq '{n:(.tagValues|length),error}'",
            false_cmd="yq '.query_frontend.search.enabled, .query_frontend.search.default_result_limit' tempo/akit-searchoff.yaml",
            truth_cmd="curl -sS $TEMPO/api/traces/e829abcdef012345670123456789abcd | jq '.batches|length'",
            confirm_cmd="yq '.query_frontend.search.max_bytes_per_tag_values_query' tempo/akit-tagbytes.yaml",
            reload_cmd="kubectl -n tempo rollout restart deploy/query-frontend && kubectl -n tempo rollout status deploy/query-frontend --timeout=90s",
            requery_cmd="curl -sS $TEMPO/api/search/tag/resource.service.name/values | jq '.tagValues|length'",
            side_cmd="curl -sS -G $TEMPO/api/search --data-urlencode 'q={resource.service.name=\"ssr-meal-svc\"}' | jq '.traces|length'",
            final_cmd="yq -r '.query_frontend.search.max_bytes_per_tag_values_query' tempo/akit-tagbytes.yaml",
            patch_old="max_bytes_per_tag_values_query: 64",
            patch_new="max_bytes_per_tag_values_query: 1048576",
            runbook_path="runbooks/akit-tagbytes.md",
            runbook="# amenity-kit-svc max_bytes_per_tag_values_query\n64 empties Grafana service dropdown. Raise 1MiB. Not search.enabled.\n",
            goal="amenity-kit-svc dashboard akit-tagbytes-4 amenity traces empty dropdown. by-id works. Find the tag-values lie.",
            plan="Empty dropdown → enabled/dlimit (false) → tag bytes 64 → 1MiB.",
            outcome="tag bytes 1MiB. 40 names. ssr-meal-svc unchanged.",
            obs1='[{"uid":"akit-tagbytes-4","title":"amenity traces"}]',
            obs2='{"title":"amenity traces","targets":[{"query":"{resource.service.name=\\"amenity-kit-svc\\"}"}]}',
            obs3='{"n":0,"error":"response exceeded max bytes"}',
            obs4="enabled: true\ndefault_result_limit: 20  # not r247/r281",
            obs5="search on; limit 20",
            obs6="max_bytes_per_tag_values_query: 64",
            obs7="2",
            obs8="by-id works; tag-values 64B cap",
            obs9="patched 1MiB",
            obs10='deployment "query-frontend" successfully rolled out',
            obs11="40",
            obs12='{"name":"Traces"}',
            obs13="19",
            obs14="wrote runbooks/akit-tagbytes.md",
            obs15="1048576",
        ),
        _failp(
            slug="tempo-tagbytes-enable-search-not-cap",
            service="blanket-inv-svc",
            dashboard_uid="blkt-tagbytes-search",
            panel="blanket traces",
            query='{resource.service.name="blanket-inv-svc"}',
            lie="Flipping search.enabled true does not populate Grafana service dropdown when max_bytes_per_tag_values_query is 64",
            false_lead="query_frontend.search.enabled false",
            config_path="tempo/blkt-searchoff.yaml",
            lie_path="tempo/blkt-tagbytes.yaml",
            wrong_path="tempo/blkt-searchoff.yaml",
            reload_name="tempo-query-frontend",
            ticket="OBS-5360",
            xfail="tests/test_blkt_tagbytes.py",
            surfaces="search.enabled leftover vs max_bytes_per_tag_values_query",
            avoided="r247 as actual RCA",
            this_is="fail/handoff: search on, tag-values still 64B",
            step_note="search.enabled 6-10; still 0 names 11; late tag bytes 12; handoff 14-15.",
            next_note="Catalog r289-r292. Keep unique vs r109-r288.",
            query_cmd="curl -sS $TEMPO/api/search/tag/resource.service.name/values | jq '{n:(.tagValues|length),error}'",
            false_cmd="yq '.query_frontend.search.enabled' tempo/blkt-searchoff.yaml",
            reload_cmd="kubectl -n tempo rollout restart deploy/query-frontend && kubectl -n tempo rollout status deploy/query-frontend --timeout=90s",
            requery_cmd="curl -sS $TEMPO/api/search/tag/resource.service.name/values | jq '{n:(.tagValues|length),error}'",
            denied_cmd="kubectl -n tempo auth can-i patch configmap/blkt-tagbytes --as=sre-bot",
            wrong_old="enabled: false",
            wrong_new="enabled: true",
            wrong2_old="default_result_limit: 0",
            wrong2_new="default_result_limit: 20",
            ticket_body="OBS-5360: blanket-inv-svc dropdown still empty. search.enabled leftover. max_bytes_per_tag_values_query 64. Need 1MiB. No tag-values RBAC.\n",
            goal="blanket-inv-svc dashboard blkt-tagbytes-search blanket traces empty dropdown. Restore names.",
            plan="Enable search (r247 leftover).",
            outcome="search on; still 0 names. Late tag bytes 64. Handoff OBS-5360.",
            obs1='[{"uid":"blkt-tagbytes-search","title":"blanket traces"}]',
            obs2='{"title":"blanket traces","targets":[{"query":"{resource.service.name=\\"blanket-inv-svc\\"}"}]}',
            obs3='{"n":0,"error":"response exceeded max bytes"}',
            obs4="enabled: false",
            obs5="treated as r247",
            obs6="tempo/blkt-searchoff.yaml",
            obs7="patched enabled true",
            obs8='deployment "query-frontend" successfully rolled out',
            obs9='{"n":0,"error":"response exceeded max bytes"}',
            obs10="patched default_result_limit 20",
            obs11='{"n":0,"error":"response exceeded max bytes"}',
            obs12="tempo/blkt-tagbytes.yaml max_bytes_per_tag_values_query 64; GET by-id 2 batches",
            obs13="no",
            obs14="wrote tickets/OBS-5360.md",
            obs15="xfail tests/test_blkt_tagbytes.py",
        ),
    )
)
