"""Observability plants r309-r316. Do not clone r109-r308.

BAN r163 tid128, r172 inferred db, r190 DD UST,
r244 loki-querier-max-concurrent / loki-qconc-rebuild-blooms.
Not a r292 Tempo max-bytes-per-tag-values clone.
"""

from mill_plants_q import _badfull, _okfull

MORE = []


# r309 Loki split_queries_by_interval 0
MORE.append(
    (
        _okfull(
            slug="loki-split-queries-by-interval-zero",
            service="elec-acbus-svc",
            dashboard_uid="acbus-splitq-1",
            panel="AC bus logs 30d",
            query='sum(count_over_time({job="elec-acbus-svc"} |= "bus_tie_open"[30d]))',
            lie="query_range split_queries_by_interval 0 plus Grafana 30d range 504s so the Stat is empty while 5m unsplit returns 9",
            false_lead="max_query_parallelism / align_queries_with_step",
            config_path="loki/acbus-qpar.yaml",
            lie_path="loki/acbus-splitq.yaml",
            truth_name="split_queries_by_interval vs 5m",
            reload_name="loki-query-frontend",
            side="5m unsplit still returns lines",
            surfaces="Loki split_queries_by_interval 0 vs Grafana 30d 504",
            avoided="r271 max_query_parallelism; r286 align_queries_with_step; r270 Mimir split_instant",
            this_is="split interval 0 504s 30d; 5m works",
            step_note="False lead qpar/align 4-5; split 0 6-8; 30m 9-12.",
            query_cmd="curl -sS -G $LOKI/loki/api/v1/query_range --data-urlencode 'query=sum(count_over_time({job=\"elec-acbus-svc\"} |= \"bus_tie_open\"[30d]))' | jq '{status,error}'",
            false_cmd="yq '.limits_config.max_query_parallelism, .query_range.align_queries_with_step' loki/acbus-qpar.yaml",
            truth_cmd="curl -sS -G $LOKI/loki/api/v1/query --data-urlencode 'query=sum(count_over_time({job=\"elec-acbus-svc\"} |= \"bus_tie_open\"[5m]))' | jq '.data.result'",
            confirm_cmd="yq '.query_range.split_queries_by_interval' loki/acbus-splitq.yaml",
            reload_cmd="kubectl -n loki rollout restart deploy/query-frontend && kubectl -n loki rollout status deploy/query-frontend --timeout=90s",
            requery_cmd="curl -sS -G $LOKI/loki/api/v1/query_range --data-urlencode 'query=sum(count_over_time({job=\"elec-acbus-svc\"} |= \"bus_tie_open\"[30d]))' | jq '.data.result[0].values|length'",
            side_cmd="curl -sS -G $LOKI/loki/api/v1/query --data-urlencode 'query=sum(count_over_time({job=\"ssr-meal-svc\"} |= \"error\"[5m]))' | jq '.data.result|length'",
            final_cmd="yq -r '.query_range.split_queries_by_interval' loki/acbus-splitq.yaml",
            patch_old="split_queries_by_interval: 0",
            patch_new="split_queries_by_interval: 30m",
            runbook_path="runbooks/acbus-splitq.md",
            runbook="# elec-acbus-svc split_queries_by_interval\n0 504s 30d. Set 30m. Not Mimir split_instant or qpar.\n",
            goal="elec-acbus-svc dashboard acbus-splitq-1 AC bus logs 30d 504. 5m=9. Find the split-interval lie.",
            plan="504 30d → qpar/align (false) → split 0 → 30m.",
            outcome="split 30m. 30d series. ssr-meal-svc unchanged.",
            obs=[
                '[{"uid":"acbus-splitq-1","title":"ac bus logs"}]',
                '{"title":"AC bus logs 30d","targets":[{"expr":"sum(count_over_time({job=\\"elec-acbus-svc\\"} |= \\"bus_tie_open\\"[30d]))"}]}',
                '{"status":"error","error":"context deadline exceeded"}',
                "max_query_parallelism: 32\nalign_queries_with_step: false  # not r271/r286",
                "qpar 32; align off",
                "split_queries_by_interval: 0",
                '[{"value":[1710000000,"9"]}]',
                "5m=9; 30d unsplit 504",
                "patched 30m",
                'deployment "query-frontend" successfully rolled out',
                "48",
                '{"name":"Number"}',
                "1",
                "wrote runbooks/acbus-splitq.md",
                "30m",
            ],
        ),
        _badfull(
            slug="loki-splitq-raise-qpar-not-split",
            service="idg-disc-svc",
            dashboard_uid="idg-splitq-qpar",
            panel="IDG disc logs 30d",
            query='sum(count_over_time({job="idg-disc-svc"} |= "idg_off"[30d]))',
            lie="Raising max_query_parallelism does not finish a 30d range when split_queries_by_interval is 0",
            false_lead="max_query_parallelism 1",
            config_path="loki/idg-qpar.yaml",
            lie_path="loki/idg-splitq.yaml",
            wrong_path="loki/idg-qpar.yaml",
            reload_name="loki-query-frontend",
            ticket="OBS-5377",
            xfail="tests/test_idg_splitq.py",
            surfaces="qpar leftover vs split_queries_by_interval 0",
            avoided="r271 as actual RCA; not r270 Mimir split",
            this_is="fail/handoff: qpar 32, split still 0",
            step_note="qpar 6-10; still 504 11; late split 12; handoff 14-15.",
            next_note="Next: Prom sample_limit 1.",
            query_cmd="curl -sS -G $LOKI/loki/api/v1/query_range --data-urlencode 'query=sum(count_over_time({job=\"idg-disc-svc\"} |= \"idg_off\"[30d]))' | jq '{status,error}'",
            false_cmd="yq '.limits_config.max_query_parallelism' loki/idg-qpar.yaml",
            reload_cmd="kubectl -n loki rollout restart deploy/query-frontend && kubectl -n loki rollout status deploy/query-frontend --timeout=90s",
            requery_cmd="curl -sS -G $LOKI/loki/api/v1/query_range --data-urlencode 'query=sum(count_over_time({job=\"idg-disc-svc\"} |= \"idg_off\"[30d]))' | jq '{status,error}'",
            denied_cmd="kubectl -n loki auth can-i patch configmap/idg-splitq --as=sre-bot",
            wrong_old="max_query_parallelism: 1",
            wrong_new="max_query_parallelism: 32",
            wrong2_old="align_queries_with_step: true",
            wrong2_new="align_queries_with_step: false",
            ticket_body="OBS-5377: idg-disc-svc 30d still 504. qpar leftover. split_queries_by_interval 0. Need 30m. No frontend RBAC.\n",
            goal="idg-disc-svc dashboard idg-splitq-qpar IDG disc logs 30d 504. Restore range.",
            plan="Raise max_query_parallelism (r271 leftover).",
            outcome="qpar 32; still 504. Late split 0. Handoff OBS-5377.",
            obs=[
                '[{"uid":"idg-splitq-qpar","title":"idg disc logs"}]',
                '{"title":"IDG disc logs 30d","targets":[{"expr":"sum(count_over_time({job=\\"idg-disc-svc\\"} |= \\"idg_off\\"[30d]))"}]}',
                '{"status":"error","error":"context deadline exceeded"}',
                "max_query_parallelism: 1",
                "treated as r271",
                "loki/idg-qpar.yaml",
                "patched 32",
                'deployment "query-frontend" successfully rolled out',
                '{"status":"error","error":"context deadline exceeded"}',
                "patched align false",
                '{"status":"error","error":"context deadline exceeded"}',
                "loki/idg-splitq.yaml split_queries_by_interval 0; 5m count=6",
                "no",
                "wrote tickets/OBS-5377.md",
                "xfail tests/test_idg_splitq.py",
            ],
        ),
    )
)

# r310 Prom sample_limit 1
MORE.append(
    (
        _okfull(
            slug="prom-scrape-sample-limit-one",
            service="hyd-edp-svc",
            dashboard_uid="hedp-slim-2",
            panel="EDP psi",
            query='avg(hyd_edp_psi{job="hyd-edp-svc"})',
            lie="scrape sample_limit 1 keeps only process_cpu_seconds and drops hyd_edp_psi so Grafana is empty while curl /metrics shows 3000",
            false_lead="body_size_limit / enable_compression",
            config_path="prom/hedp-body.yaml",
            lie_path="prom/hedp-slim.yaml",
            truth_name="sample_limit vs /metrics",
            reload_name="prom-scrape",
            side="jobs without sample_limit still scrape hyd_edp_psi",
            surfaces="Prometheus sample_limit 1 vs Grafana empty hyd_edp_psi",
            avoided="r238 body_size; r291 enable_compression; r297 label_limit",
            this_is="sample_limit 1 keeps cpu and drops the gauge",
            step_note="False lead body/gzip 4-5; sample_limit 1 6-8; 0 9-12.",
            query_cmd="curl -sS -G $MIMIR/prometheus/api/v1/query --data-urlencode 'query=avg(hyd_edp_psi{job=\"hyd-edp-svc\"})'",
            false_cmd="yq '.scrape_configs[]|select(.job_name==\"hyd-edp-svc\")|{body_size_limit,enable_compression}' prom/hedp-body.yaml",
            truth_cmd="curl -sS http://hyd-edp-svc:8080/metrics | rg 'hyd_edp_psi|process_cpu' | head",
            confirm_cmd="yq '.scrape_configs[]|select(.job_name==\"hyd-edp-svc\").sample_limit' prom/hedp-slim.yaml",
            reload_cmd="kubectl -n prom rollout restart deploy/prom-scrape && kubectl -n prom rollout status deploy/prom-scrape --timeout=90s",
            requery_cmd="curl -sS -G $MIMIR/prometheus/api/v1/query --data-urlencode 'query=avg(hyd_edp_psi{job=\"hyd-edp-svc\"})'",
            side_cmd="curl -sS -G $MIMIR/prometheus/api/v1/query --data-urlencode 'query=avg(hyd_edp_psi{job=\"ssr-meal-svc\"})' | jq '.data.result|length'",
            final_cmd="yq -r '.scrape_configs[]|select(.job_name==\"hyd-edp-svc\").sample_limit' prom/hedp-slim.yaml",
            patch_old="sample_limit: 1",
            patch_new="sample_limit: 0",
            runbook_path="runbooks/hedp-slim.md",
            runbook="# hyd-edp-svc sample_limit\n1 keeps process_cpu only. Set 0. Not body_size.\n",
            goal="hyd-edp-svc dashboard hedp-slim-2 EDP psi empty. curl=3000. Find the sample_limit lie.",
            plan="Empty → body/gzip (false) → sample_limit 1 → 0.",
            outcome="sample_limit 0. psi=3000. ssr-meal-svc unchanged.",
            obs=[
                '[{"uid":"hedp-slim-2","title":"edp psi"}]',
                '{"title":"EDP psi","targets":[{"expr":"avg(hyd_edp_psi{job=\\"hyd-edp-svc\\"})"}]}',
                '{"status":"success","data":{"result":[]}}',
                "body_size_limit: 8MB\nenable_compression: false  # not r238/r291",
                "body unlimited; gzip off",
                "sample_limit: 1",
                "hyd_edp_psi 3000\nprocess_cpu_seconds_total 12",
                "only first sample ingested; gauge dropped",
                "patched 0",
                'deployment "prom-scrape" successfully rolled out',
                '{"status":"success","data":{"result":[{"value":[1710000600,"3000"]}]}}',
                '{"name":"Timeseries"}',
                "1",
                "wrote runbooks/hedp-slim.md",
                "0",
            ],
        ),
        _badfull(
            slug="prom-slim-raise-body-not-samples",
            service="aileron-trim-svc",
            dashboard_uid="atrim-slim-body",
            panel="aileron trim deg",
            query='avg(aileron_trim_deg{job="aileron-trim-svc"})',
            lie="Raising body_size_limit does not ingest hyd-style gauges dropped by sample_limit 1",
            false_lead="scrape body_size_limit 256KB",
            config_path="prom/atrim-body.yaml",
            lie_path="prom/atrim-slim.yaml",
            wrong_path="prom/atrim-body.yaml",
            reload_name="prom-scrape",
            ticket="OBS-5378",
            xfail="tests/test_atrim_slim.py",
            surfaces="body leftover vs sample_limit 1",
            avoided="r238 as actual RCA",
            this_is="fail/handoff: body 8MB, sample_limit still 1",
            step_note="body 6-10; still empty 11; late sample_limit 12; handoff 14-15.",
            next_note="Next: OTel groupbytrace wait 10ms.",
            query_cmd="curl -sS -G $MIMIR/prometheus/api/v1/query --data-urlencode 'query=avg(aileron_trim_deg{job=\"aileron-trim-svc\"})'",
            false_cmd="yq '.scrape_configs[]|select(.job_name==\"aileron-trim-svc\").body_size_limit' prom/atrim-body.yaml",
            reload_cmd="kubectl -n prom rollout restart deploy/prom-scrape && kubectl -n prom rollout status deploy/prom-scrape --timeout=90s",
            requery_cmd="curl -sS -G $MIMIR/prometheus/api/v1/query --data-urlencode 'query=avg(aileron_trim_deg{job=\"aileron-trim-svc\"})'",
            denied_cmd="kubectl -n prom auth can-i patch configmap/atrim-slim --as=sre-bot",
            wrong_old="body_size_limit: 256KB",
            wrong_new="body_size_limit: 8MB",
            wrong2_old="enable_compression: true",
            wrong2_new="enable_compression: false",
            ticket_body="OBS-5378: aileron-trim-svc still empty. body leftover. sample_limit 1. Need 0. No scrape RBAC.\n",
            goal="aileron-trim-svc dashboard atrim-slim-body aileron trim deg empty. Restore gauge.",
            plan="Raise body_size_limit (r238 leftover).",
            outcome="body 8MB; still empty. Late sample_limit 1. Handoff OBS-5378.",
            obs=[
                '[{"uid":"atrim-slim-body","title":"aileron trim"}]',
                '{"title":"aileron trim deg","targets":[{"expr":"avg(aileron_trim_deg{job=\\"aileron-trim-svc\\"})"}]}',
                '{"status":"success","data":{"result":[]}}',
                "body_size_limit: 256KB",
                "treated as r238",
                "prom/atrim-body.yaml",
                "patched 8MB",
                'deployment "prom-scrape" successfully rolled out',
                '{"status":"success","data":{"result":[]}}',
                "patched compression false",
                '{"status":"success","data":{"result":[]}}',
                "prom/atrim-slim.yaml sample_limit 1; curl aileron_trim_deg 0.4",
                "no",
                "wrote tickets/OBS-5378.md",
                "xfail tests/test_atrim_slim.py",
            ],
        ),
    )
)

# r311 OTel groupbytrace wait 10ms
MORE.append(
    (
        _okfull(
            slug="otel-groupbytrace-wait-10ms",
            service="elevator-trim-svc",
            dashboard_uid="etrim-gbtr-3",
            panel="elevator error traces",
            query='{resource.service.name="elevator-trim-svc" && status=error}',
            lie="groupbytrace wait_duration 10ms plus num_traces 1 evicts the error span that arrives late so Grafana error search is empty while 200s remain",
            false_lead="batch timeout / probabilisticsampler",
            config_path="otelcol/etrim-batch.yaml",
            lie_path="otelcol/etrim-gbtr.yaml",
            truth_name="groupbytrace wait vs sent spans",
            reload_name="otelcol-etrim",
            side="collectors without groupbytrace still keep errors",
            surfaces="OTel groupbytrace wait 10ms vs Grafana error traces empty",
            avoided="r237 batch timeout; r275 probabilisticsampler; r224 memory_limiter",
            this_is="groupbytrace 10ms drops the late error span",
            step_note="False lead batch/sampler 4-5; groupbytrace 10ms 6-8; drop processor 9-12.",
            query_cmd="curl -sS -G $TEMPO/api/search --data-urlencode 'q={resource.service.name=\"elevator-trim-svc\" && status=error}' | jq '.traces|length'",
            false_cmd="yq '.processors.batch, .processors.probabilisticsampler' otelcol/etrim-batch.yaml",
            truth_cmd="curl -sS -G $TEMPO/api/search --data-urlencode 'q={resource.service.name=\"elevator-trim-svc\" && status=ok}' | jq '.traces|length'",
            confirm_cmd="yq '.processors.groupbytrace' otelcol/etrim-gbtr.yaml",
            reload_cmd="kubectl -n otel rollout restart deploy/otelcol-etrim && kubectl -n otel rollout status deploy/otelcol-etrim --timeout=90s",
            requery_cmd="curl -sS -G $TEMPO/api/search --data-urlencode 'q={resource.service.name=\"elevator-trim-svc\" && status=error}' | jq '.traces|length'",
            side_cmd="curl -sS -G $TEMPO/api/search --data-urlencode 'q={resource.service.name=\"ssr-meal-svc\" && status=error}' | jq '.traces|length'",
            final_cmd="yq -r '.service.pipelines.traces.processors[]' otelcol/etrim-gbtr.yaml",
            patch_old="processors:\n      - groupbytrace\n      - batch",
            patch_new="processors:\n      - batch",
            runbook_path="runbooks/etrim-gbtr.md",
            runbook="# elevator-trim-svc groupbytrace\nwait 10ms drops late errors. Drop groupbytrace. Not batch timeout.\n",
            goal="elevator-trim-svc dashboard etrim-gbtr-3 elevator error traces empty. 200s exist. Find the groupbytrace lie.",
            plan="Empty errors → batch/sampler (false) → groupbytrace 10ms → drop it.",
            outcome="groupbytrace dropped. 8 error traces. ssr-meal-svc unchanged.",
            obs=[
                '[{"uid":"etrim-gbtr-3","title":"elevator errors"}]',
                '{"title":"elevator error traces","targets":[{"query":"{resource.service.name=\\"elevator-trim-svc\\" && status=error}"}]}',
                "0",
                "timeout: 200ms\nsampling_percentage: 100  # not r237/r275",
                "batch 200ms; sampler 100",
                "wait_duration: 10ms\nnum_traces: 1",
                "14",
                "200s kept; late error span evicted",
                "patched drop groupbytrace",
                'deployment "otelcol-etrim" successfully rolled out',
                "8",
                '{"name":"Traces"}',
                "4",
                "wrote runbooks/etrim-gbtr.md",
                "batch",
            ],
        ),
        _badfull(
            slug="otel-gbtr-raise-batch-not-wait",
            service="smoke-hood-svc",
            dashboard_uid="shood-gbtr-batch",
            panel="hood error traces",
            query='{resource.service.name="smoke-hood-svc" && status=error}',
            lie="Raising batch timeout does not keep late error spans when groupbytrace wait_duration is 10ms",
            false_lead="batch processor timeout 1ms",
            config_path="otelcol/shood-batch.yaml",
            lie_path="otelcol/shood-gbtr.yaml",
            wrong_path="otelcol/shood-batch.yaml",
            reload_name="otelcol-shood",
            ticket="OBS-5379",
            xfail="tests/test_shood_gbtr.py",
            surfaces="batch leftover vs groupbytrace wait 10ms",
            avoided="r237 as actual RCA",
            this_is="fail/handoff: batch 200ms, groupbytrace still 10ms",
            step_note="batch 6-10; still 0 11; late groupbytrace 12; handoff 14-15.",
            next_note="Next: Mimir blocks_retention_period 2h.",
            query_cmd="curl -sS -G $TEMPO/api/search --data-urlencode 'q={resource.service.name=\"smoke-hood-svc\" && status=error}' | jq '.traces|length'",
            false_cmd="yq '.processors.batch.timeout' otelcol/shood-batch.yaml",
            reload_cmd="kubectl -n otel rollout restart deploy/otelcol-shood && kubectl -n otel rollout status deploy/otelcol-shood --timeout=90s",
            requery_cmd="curl -sS -G $TEMPO/api/search --data-urlencode 'q={resource.service.name=\"smoke-hood-svc\" && status=error}' | jq '.traces|length'",
            denied_cmd="kubectl -n otel auth can-i patch configmap/shood-gbtr --as=sre-bot",
            wrong_old="timeout: 1ms",
            wrong_new="timeout: 200ms",
            wrong2_old="sampling_percentage: 0",
            wrong2_new="sampling_percentage: 100",
            ticket_body="OBS-5379: smoke-hood-svc errors still 0. batch leftover. groupbytrace wait 10ms. Need drop processor. No pipeline RBAC.\n",
            goal="smoke-hood-svc dashboard shood-gbtr-batch hood error traces empty. Restore errors.",
            plan="Raise batch timeout (r237 leftover).",
            outcome="batch 200ms; still 0. Late groupbytrace 10ms. Handoff OBS-5379.",
            obs=[
                '[{"uid":"shood-gbtr-batch","title":"hood errors"}]',
                '{"title":"hood error traces","targets":[{"query":"{resource.service.name=\\"smoke-hood-svc\\" && status=error}"}]}',
                "0",
                "timeout: 1ms",
                "treated as r237",
                "otelcol/shood-batch.yaml",
                "patched 200ms",
                'deployment "otelcol-shood" successfully rolled out',
                "0",
                "patched sampler 100",
                "0",
                "otelcol/shood-gbtr.yaml wait_duration 10ms num_traces 1; 200s=10",
                "no",
                "wrote tickets/OBS-5379.md",
                "xfail tests/test_shood_gbtr.py",
            ],
        ),
    )
)

# r312 Mimir blocks_retention_period 2h
MORE.append(
    (
        _okfull(
            slug="mimir-blocks-retention-period-2h",
            service="pbe-stow-svc",
            dashboard_uid="pbe-blkret-4",
            panel="PBE stow 24h",
            query='avg_over_time(pbe_stow_count{job="pbe-stow-svc"}[24h])',
            lie="compactor blocks_retention_period 2h deletes the 24h blocks Grafana needs so the panel is empty while the last 30m still query",
            false_lead="ignore_blocks_within / max_query_lookback",
            config_path="mimir/pbe-ignore.yaml",
            lie_path="mimir/pbe-blkret.yaml",
            truth_name="blocks_retention_period vs 30m",
            reload_name="mimir-compactor",
            side="30m still has samples",
            surfaces="Mimir blocks_retention_period 2h vs Grafana 24h empty",
            avoided="r249 ignore_blocks_within; r210 lookback; r258 max_total_query_length",
            this_is="2h block retention deletes the 24h range",
            step_note="False lead ignore/lookback 4-5; retention 2h 6-8; 31d 9-12.",
            query_cmd="curl -sS -G $MIMIR/prometheus/api/v1/query --data-urlencode 'query=avg_over_time(pbe_stow_count{job=\"pbe-stow-svc\"}[24h])'",
            false_cmd="yq '.limits.ignore_blocks_within, .limits.max_query_lookback' mimir/pbe-ignore.yaml",
            truth_cmd="curl -sS -G $MIMIR/prometheus/api/v1/query --data-urlencode 'query=avg_over_time(pbe_stow_count{job=\"pbe-stow-svc\"}[30m])' | jq '.data.result'",
            confirm_cmd="yq '.compactor.blocks_retention_period' mimir/pbe-blkret.yaml",
            reload_cmd="kubectl -n mimir rollout restart deploy/compactor && kubectl -n mimir rollout status deploy/compactor --timeout=90s",
            requery_cmd="curl -sS -G $MIMIR/prometheus/api/v1/query --data-urlencode 'query=avg_over_time(pbe_stow_count{job=\"pbe-stow-svc\"}[24h])'",
            side_cmd="curl -sS -G $MIMIR/prometheus/api/v1/query --data-urlencode 'query=avg_over_time(pbe_stow_count{job=\"ssr-meal-svc\"}[30m])' | jq '.data.result|length'",
            final_cmd="yq -r '.compactor.blocks_retention_period' mimir/pbe-blkret.yaml",
            patch_old="blocks_retention_period: 2h",
            patch_new="blocks_retention_period: 31d",
            runbook_path="runbooks/pbe-blkret.md",
            runbook="# pbe-stow-svc blocks_retention_period\n2h deletes 24h blocks. Set 31d. Not ignore_blocks_within.\n",
            goal="pbe-stow-svc dashboard pbe-blkret-4 PBE stow 24h empty. 30m=2. Find the blocks_retention lie.",
            plan="Empty 24h → ignore/lookback (false) → retention 2h → 31d.",
            outcome="retention 31d. 24h=2. ssr-meal-svc unchanged.",
            obs=[
                '[{"uid":"pbe-blkret-4","title":"pbe stow"}]',
                '{"title":"PBE stow 24h","targets":[{"expr":"avg_over_time(pbe_stow_count{job=\\"pbe-stow-svc\\"}[24h])"}]}',
                '{"status":"success","data":{"result":[]}}',
                "ignore_blocks_within: 0s\nmax_query_lookback: 30d  # not r249/r210",
                "ignore 0s; lookback 30d",
                "blocks_retention_period: 2h",
                '[{"value":[1710000000,"2"]}]',
                "30m=2; 24h blocks deleted",
                "patched 31d",
                'deployment "compactor" successfully rolled out',
                '{"status":"success","data":{"result":[{"value":[1710000600,"2"]}]}}',
                '{"name":"Number"}',
                "1",
                "wrote runbooks/pbe-blkret.md",
                "31d",
            ],
        ),
        _badfull(
            slug="mimir-blkret-zero-ignore-not-retention",
            service="fire-ext-halon-svc",
            dashboard_uid="halon-blkret-ignore",
            panel="halon 24h",
            query='avg_over_time(halon_ext_count{job="fire-ext-halon-svc"}[24h])',
            lie="Clearing ignore_blocks_within does not restore a 24h range deleted by blocks_retention_period 2h",
            false_lead="ignore_blocks_within 10h",
            config_path="mimir/halon-ignore.yaml",
            lie_path="mimir/halon-blkret.yaml",
            wrong_path="mimir/halon-ignore.yaml",
            reload_name="mimir-query-frontend",
            ticket="OBS-5380",
            xfail="tests/test_halon_blkret.py",
            surfaces="ignore leftover vs blocks_retention_period 2h",
            avoided="r249 as actual RCA",
            this_is="fail/handoff: ignore 0s, retention still 2h",
            step_note="ignore 6-10; still empty 11; late retention 12; handoff 14-15.",
            next_note="Next: Tempo storage.trace.pool.max_workers 0.",
            query_cmd="curl -sS -G $MIMIR/prometheus/api/v1/query --data-urlencode 'query=avg_over_time(halon_ext_count{job=\"fire-ext-halon-svc\"}[24h])'",
            false_cmd="yq '.limits.ignore_blocks_within' mimir/halon-ignore.yaml",
            reload_cmd="kubectl -n mimir rollout restart deploy/query-frontend && kubectl -n mimir rollout status deploy/query-frontend --timeout=90s",
            requery_cmd="curl -sS -G $MIMIR/prometheus/api/v1/query --data-urlencode 'query=avg_over_time(halon_ext_count{job=\"fire-ext-halon-svc\"}[24h])'",
            denied_cmd="kubectl -n mimir auth can-i patch deploy/compactor --as=sre-bot",
            wrong_old="ignore_blocks_within: 10h",
            wrong_new="ignore_blocks_within: 0s",
            wrong2_old="max_query_lookback: 7d",
            wrong2_new="max_query_lookback: 30d",
            ticket_body="OBS-5380: fire-ext-halon-svc 24h still empty. ignore leftover. blocks_retention_period 2h. Need 31d. No compactor RBAC.\n",
            goal="fire-ext-halon-svc dashboard halon-blkret-ignore halon 24h empty. Restore range.",
            plan="Clear ignore_blocks_within (r249 leftover).",
            outcome="ignore 0s; still empty. Late retention 2h. Handoff OBS-5380.",
            obs=[
                '[{"uid":"halon-blkret-ignore","title":"halon 24h"}]',
                '{"title":"halon 24h","targets":[{"expr":"avg_over_time(halon_ext_count{job=\\"fire-ext-halon-svc\\"}[24h])"}]}',
                '{"status":"success","data":{"result":[]}}',
                "ignore_blocks_within: 10h",
                "treated as r249",
                "mimir/halon-ignore.yaml",
                "patched 0s",
                'deployment "query-frontend" successfully rolled out',
                '{"status":"success","data":{"result":[]}}',
                "patched lookback 30d",
                '{"status":"success","data":{"result":[]}}',
                "mimir/halon-blkret.yaml blocks_retention_period 2h; 30m=1",
                "no",
                "wrote tickets/OBS-5380.md",
                "xfail tests/test_halon_blkret.py",
            ],
        ),
    )
)

# r313 Tempo storage.trace.pool.max_workers 0
MORE.append(
    (
        _okfull(
            slug="tempo-trace-pool-max-workers-zero",
            service="pillow-inv-svc",
            dashboard_uid="pillow-poolw-5",
            panel="pillow traces",
            query='{resource.service.name="pillow-inv-svc"}',
            lie="storage.trace.pool.max_workers 0 so Search iterators never run and Grafana traces are empty while GET by-id still works",
            false_lead="query_frontend api_timeout / search.enabled",
            config_path="tempo/pillow-apitime.yaml",
            lie_path="tempo/pillow-poolw.yaml",
            truth_name="pool.max_workers vs by-id",
            reload_name="tempo-querier",
            side="queriers with 100 workers still search",
            surfaces="Tempo pool.max_workers 0 vs Grafana empty Search",
            avoided="r274 api_timeout; r247 search.enabled; r292 tag-values bytes",
            this_is="pool workers 0 blocks iterators; by-id ok",
            step_note="False lead timeout/enabled 4-5; max_workers 0 6-8; 100 9-12.",
            query_cmd="curl -sS -G $TEMPO/api/search --data-urlencode 'q={resource.service.name=\"pillow-inv-svc\"}' | jq '{n:(.traces|length),error}'",
            false_cmd="yq '.query_frontend.api_timeout, .query_frontend.search.enabled' tempo/pillow-apitime.yaml",
            truth_cmd="curl -sS $TEMPO/api/traces/c23abcdef012345670123456789abcde | jq '.batches|length'",
            confirm_cmd="yq '.storage.trace.pool.max_workers' tempo/pillow-poolw.yaml",
            reload_cmd="kubectl -n tempo rollout restart deploy/querier && kubectl -n tempo rollout status deploy/querier --timeout=90s",
            requery_cmd="curl -sS -G $TEMPO/api/search --data-urlencode 'q={resource.service.name=\"pillow-inv-svc\"}' | jq '.traces|length'",
            side_cmd="curl -sS -G $TEMPO/api/search --data-urlencode 'q={resource.service.name=\"ssr-meal-svc\"}' | jq '.traces|length'",
            final_cmd="yq -r '.storage.trace.pool.max_workers' tempo/pillow-poolw.yaml",
            patch_old="max_workers: 0",
            patch_new="max_workers: 100",
            runbook_path="runbooks/pillow-poolw.md",
            runbook="# pillow-inv-svc pool.max_workers\n0 blocks Search iterators. Raise 100. Not api_timeout or tag-values.\n",
            goal="pillow-inv-svc dashboard pillow-poolw-5 pillow traces empty. by-id works. Find the pool workers lie.",
            plan="Empty Search → timeout/enabled (false) → max_workers 0 → 100.",
            outcome="workers 100. 12 traces. ssr-meal-svc unchanged.",
            obs=[
                '[{"uid":"pillow-poolw-5","title":"pillow traces"}]',
                '{"title":"pillow traces","targets":[{"query":"{resource.service.name=\\"pillow-inv-svc\\"}"}]}',
                '{"n":0,"error":"worker pool exhausted"}',
                "api_timeout: 30s\nenabled: true  # not r274/r247",
                "timeout 30s; search on",
                "max_workers: 0",
                "2",
                "by-id works; Search iterators have 0 workers",
                "patched 100",
                'deployment "querier" successfully rolled out',
                "12",
                '{"name":"Traces"}',
                "19",
                "wrote runbooks/pillow-poolw.md",
                "100",
            ],
        ),
        _badfull(
            slug="tempo-poolw-raise-apitime-not-workers",
            service="headset-inv-svc",
            dashboard_uid="headset-poolw-apitime",
            panel="headset traces",
            query='{resource.service.name="headset-inv-svc"}',
            lie="Raising query_frontend api_timeout does not run Search iterators when pool.max_workers is 0",
            false_lead="query_frontend api_timeout 10ms",
            config_path="tempo/headset-apitime.yaml",
            lie_path="tempo/headset-poolw.yaml",
            wrong_path="tempo/headset-apitime.yaml",
            reload_name="tempo-query-frontend",
            ticket="OBS-5381",
            xfail="tests/test_headset_poolw.py",
            surfaces="api_timeout leftover vs pool.max_workers 0",
            avoided="r274 as actual RCA; not r292 tag-values",
            this_is="fail/handoff: api_timeout 30s, max_workers still 0",
            step_note="timeout 6-10; still 0 11; late max_workers 12; handoff 14-15.",
            next_note="Next: Loki max_cache_freshness_per_query 24h.",
            query_cmd="curl -sS -G $TEMPO/api/search --data-urlencode 'q={resource.service.name=\"headset-inv-svc\"}' | jq '{n:(.traces|length),error}'",
            false_cmd="yq '.query_frontend.api_timeout' tempo/headset-apitime.yaml",
            reload_cmd="kubectl -n tempo rollout restart deploy/query-frontend && kubectl -n tempo rollout status deploy/query-frontend --timeout=90s",
            requery_cmd="curl -sS -G $TEMPO/api/search --data-urlencode 'q={resource.service.name=\"headset-inv-svc\"}' | jq '{n:(.traces|length),error}'",
            denied_cmd="kubectl -n tempo auth can-i patch configmap/headset-poolw --as=sre-bot",
            wrong_old="api_timeout: 10ms",
            wrong_new="api_timeout: 30s",
            wrong2_old="enabled: false",
            wrong2_new="enabled: true",
            ticket_body="OBS-5381: headset-inv-svc Search still empty. api_timeout leftover. pool.max_workers 0. Need 100. No querier RBAC.\n",
            goal="headset-inv-svc dashboard headset-poolw-apitime headset traces empty. Restore Search.",
            plan="Raise api_timeout (r274 leftover).",
            outcome="timeout 30s; still empty. Late max_workers 0. Handoff OBS-5381.",
            obs=[
                '[{"uid":"headset-poolw-apitime","title":"headset traces"}]',
                '{"title":"headset traces","targets":[{"query":"{resource.service.name=\\"headset-inv-svc\\"}"}]}',
                '{"n":0,"error":"worker pool exhausted"}',
                "api_timeout: 10ms",
                "treated as r274",
                "tempo/headset-apitime.yaml",
                "patched 30s",
                'deployment "query-frontend" successfully rolled out',
                '{"n":0,"error":"worker pool exhausted"}',
                "patched search enabled true",
                '{"n":0,"error":"worker pool exhausted"}',
                "tempo/headset-poolw.yaml storage.trace.pool.max_workers 0; GET by-id 2 batches",
                "no",
                "wrote tickets/OBS-5381.md",
                "xfail tests/test_headset_poolw.py",
            ],
        ),
    )
)

# r314 Loki max_cache_freshness_per_query 24h
MORE.append(
    (
        _okfull(
            slug="loki-max-cache-freshness-24h",
            service="cabin-temp-zone-svc",
            dashboard_uid="ctz-cachef-6",
            panel="cabin zone logs",
            query='{job="cabin-temp-zone-svc"} |= "zone_alarm"',
            lie="query_range results_cache max_cache_freshness_per_query 24h serves yesterday's empty window so Grafana is empty while an uncached now-query has 10 lines",
            false_lead="align_queries_with_step / split_queries_by_interval",
            config_path="loki/ctz-align.yaml",
            lie_path="loki/ctz-cachef.yaml",
            truth_name="max_cache_freshness vs Cache-Control no-cache",
            reload_name="loki-query-frontend",
            side="no-cache queries still see new lines",
            surfaces="Loki max_cache_freshness_per_query 24h vs Grafana stale empty",
            avoided="r286 align_queries_with_step; r309 split_queries_by_interval; r270 Mimir split",
            this_is="24h cache freshness serves yesterday empty",
            step_note="False lead align/split 4-5; cache freshness 24h 6-8; 5m 9-12.",
            query_cmd="curl -sS -G $LOKI/loki/api/v1/query_range --data-urlencode 'query={job=\"cabin-temp-zone-svc\"} |= \"zone_alarm\"' | jq '{status,n:(.data.result|length)}'",
            false_cmd="yq '.query_range.align_queries_with_step, .query_range.split_queries_by_interval' loki/ctz-align.yaml",
            truth_cmd="curl -sS -G $LOKI/loki/api/v1/query_range -H 'Cache-Control: no-cache' --data-urlencode 'query={job=\"cabin-temp-zone-svc\"} |= \"zone_alarm\"' | jq '.data.result|length'",
            confirm_cmd="yq '.query_range.results_cache.max_cache_freshness_per_query' loki/ctz-cachef.yaml",
            reload_cmd="kubectl -n loki rollout restart deploy/query-frontend && kubectl -n loki rollout status deploy/query-frontend --timeout=90s",
            requery_cmd="curl -sS -G $LOKI/loki/api/v1/query_range --data-urlencode 'query={job=\"cabin-temp-zone-svc\"} |= \"zone_alarm\"' | jq '.data.result|length'",
            side_cmd="curl -sS -G $LOKI/loki/api/v1/query_range --data-urlencode 'query={job=\"ssr-meal-svc\"} |= \"error\"' | jq '.data.result|length'",
            final_cmd="yq -r '.query_range.results_cache.max_cache_freshness_per_query' loki/ctz-cachef.yaml",
            patch_old="max_cache_freshness_per_query: 24h",
            patch_new="max_cache_freshness_per_query: 5m",
            runbook_path="runbooks/ctz-cachef.md",
            runbook="# cabin-temp-zone-svc max_cache_freshness_per_query\n24h serves yesterday empty. Set 5m. Not align_queries_with_step.\n",
            goal="cabin-temp-zone-svc dashboard ctz-cachef-6 cabin zone logs empty. no-cache=10. Find the cache-freshness lie.",
            plan="Empty → align/split (false) → freshness 24h → 5m.",
            outcome="freshness 5m. 10 streams. ssr-meal-svc unchanged.",
            obs=[
                '[{"uid":"ctz-cachef-6","title":"cabin zone logs"}]',
                '{"title":"cabin zone logs","targets":[{"expr":"{job=\\"cabin-temp-zone-svc\\"} |= \\"zone_alarm\\""}]}',
                '{"status":"success","n":0}',
                "align_queries_with_step: false\nsplit_queries_by_interval: 30m  # not r286/r309",
                "align off; split 30m",
                "max_cache_freshness_per_query: 24h",
                "10",
                "no-cache 10; cached window empty yesterday",
                "patched 5m",
                'deployment "query-frontend" successfully rolled out',
                "10",
                '{"name":"Logs"}',
                "1",
                "wrote runbooks/ctz-cachef.md",
                "5m",
            ],
        ),
        _badfull(
            slug="loki-cachef-disable-align-not-freshness",
            service="duct-leak-svc",
            dashboard_uid="duct-cachef-align",
            panel="duct leak logs",
            query='{job="duct-leak-svc"} |= "bleed_leak"',
            lie="Disabling align_queries_with_step does not bypass a 24h results-cache freshness window",
            false_lead="align_queries_with_step true",
            config_path="loki/duct-align.yaml",
            lie_path="loki/duct-cachef.yaml",
            wrong_path="loki/duct-align.yaml",
            reload_name="loki-query-frontend",
            ticket="OBS-5382",
            xfail="tests/test_duct_cachef.py",
            surfaces="align leftover vs max_cache_freshness_per_query 24h",
            avoided="r286 as actual RCA",
            this_is="fail/handoff: align false, freshness still 24h",
            step_note="align 6-10; still 0 11; late freshness 12; handoff 14-15.",
            next_note="Next: Grafana live.max_connections 0.",
            query_cmd="curl -sS -G $LOKI/loki/api/v1/query_range --data-urlencode 'query={job=\"duct-leak-svc\"} |= \"bleed_leak\"' | jq '{status,n:(.data.result|length)}'",
            false_cmd="yq '.query_range.align_queries_with_step' loki/duct-align.yaml",
            reload_cmd="kubectl -n loki rollout restart deploy/query-frontend && kubectl -n loki rollout status deploy/query-frontend --timeout=90s",
            requery_cmd="curl -sS -G $LOKI/loki/api/v1/query_range --data-urlencode 'query={job=\"duct-leak-svc\"} |= \"bleed_leak\"' | jq '{status,n:(.data.result|length)}'",
            denied_cmd="kubectl -n loki auth can-i patch configmap/duct-cachef --as=sre-bot",
            wrong_old="align_queries_with_step: true",
            wrong_new="align_queries_with_step: false",
            wrong2_old="split_queries_by_interval: 0",
            wrong2_new="split_queries_by_interval: 30m",
            ticket_body="OBS-5382: duct-leak-svc still empty. align leftover. max_cache_freshness_per_query 24h. Need 5m. No frontend RBAC.\n",
            goal="duct-leak-svc dashboard duct-cachef-align duct leak logs empty. Restore fresh lines.",
            plan="Disable align_queries_with_step (r286 leftover).",
            outcome="align false; still 0. Late freshness 24h. Handoff OBS-5382.",
            obs=[
                '[{"uid":"duct-cachef-align","title":"duct leak logs"}]',
                '{"title":"duct leak logs","targets":[{"expr":"{job=\\"duct-leak-svc\\"} |= \\"bleed_leak\\""}]}',
                '{"status":"success","n":0}',
                "align_queries_with_step: true",
                "treated as r286",
                "loki/duct-align.yaml",
                "patched false",
                'deployment "query-frontend" successfully rolled out',
                '{"status":"success","n":0}',
                "patched split 30m",
                '{"status":"success","n":0}',
                "loki/duct-cachef.yaml max_cache_freshness_per_query 24h; no-cache n=8",
                "no",
                "wrote tickets/OBS-5382.md",
                "xfail tests/test_duct_cachef.py",
            ],
        ),
    )
)

# r315 Grafana live.max_connections 0
MORE.append(
    (
        _okfull(
            slug="grafana-live-max-connections-zero",
            service="avionics-cool-svc",
            dashboard_uid="avcool-live-7",
            panel="avionics live logs",
            query='{job="avionics-cool-svc"} |= "fan_stall"',
            lie="grafana.ini live max_connections 0 so the Live tail panel is empty while Loki query_range still has 16 fan_stall lines",
            false_lead="Loki ingestion_rate_strategy / pattern metric_aggregation",
            config_path="loki/avcool-ingrate.yaml",
            lie_path="grafana/avcool.ini",
            truth_name="live.max_connections vs query_range",
            reload_name="grafana",
            side="Explore query_range still works",
            surfaces="Grafana live.max_connections 0 vs Loki lines exist",
            avoided="r289 ingestion_rate_strategy; r282 pattern aggregation; r300 dataproxy.timeout",
            this_is="live max_connections 0 blanks Live tail; range ok",
            step_note="False lead ingest/patagg 4-5; live 0 6-8; 100 9-12.",
            query_cmd="curl -sS $GRAFANA/api/live/ws?stream=avcool | jq '{ok:.connected,error}'",
            false_cmd="yq '.limits_config.ingestion_rate_strategy, .pattern_ingester.metric_aggregation.enabled' loki/avcool-ingrate.yaml",
            truth_cmd="curl -sS -G $LOKI/loki/api/v1/query_range --data-urlencode 'query={job=\"avionics-cool-svc\"} |= \"fan_stall\"' | jq '.data.result|length'",
            confirm_cmd="awk '/\\[live\\]/{p=1} p&&/max_connections/{print; exit}' grafana/avcool.ini",
            reload_cmd="kubectl -n grafana rollout restart deploy/grafana && kubectl -n grafana rollout status deploy/grafana --timeout=90s",
            requery_cmd="curl -sS $GRAFANA/api/live/ws?stream=avcool | jq '.connected'",
            side_cmd="curl -sS -G $LOKI/loki/api/v1/query_range --data-urlencode 'query={job=\"ssr-meal-svc\"} |= \"error\"' | jq '.data.result|length'",
            final_cmd="awk '/\\[live\\]/{p=1} p&&/max_connections/{print; exit}' grafana/avcool.ini",
            patch_old="max_connections = 0",
            patch_new="max_connections = 100",
            runbook_path="runbooks/avcool-live.md",
            runbook="# avionics-cool-svc live.max_connections\n0 blanks Live tail. Set 100. Not Loki ingest.\n",
            goal="avionics-cool-svc dashboard avcool-live-7 avionics live logs empty. query_range=16. Find the live.max_connections lie.",
            plan="Empty Live → ingest/patagg (false) → max_connections 0 → 100.",
            outcome="max_connections 100. Live connected. ssr-meal-svc unchanged.",
            obs=[
                '[{"uid":"avcool-live-7","title":"avionics live"}]',
                '{"title":"avionics live logs","targets":[{"expr":"{job=\\"avionics-cool-svc\\"} |= \\"fan_stall\\""}]}',
                '{"ok":false,"error":"live connections exhausted"}',
                "ingestion_rate_strategy: global\nenabled: false  # not r289/r282",
                "ingest global; patagg off",
                "max_connections = 0",
                "16",
                "query_range 16; Live cap 0",
                "patched 100",
                'deployment "grafana" successfully rolled out',
                "true",
                '{"name":"Live"}',
                "1",
                "wrote runbooks/avcool-live.md",
                "max_connections = 100",
            ],
        ),
        _badfull(
            slug="grafana-live-switch-global-not-live",
            service="ram-air-door-svc",
            dashboard_uid="ramair-live-ingrate",
            panel="ram air live logs",
            query='{job="ram-air-door-svc"} |= "door_skew"',
            lie="Switching Loki ingestion_rate_strategy to global does not open Grafana Live when live.max_connections is 0",
            false_lead="ingestion_rate_strategy local",
            config_path="loki/ramair-ingrate.yaml",
            lie_path="grafana/ramair.ini",
            wrong_path="loki/ramair-ingrate.yaml",
            reload_name="loki-ingester",
            ticket="OBS-5383",
            xfail="tests/test_ramair_live.py",
            surfaces="ingest leftover vs live.max_connections 0",
            avoided="r289 as actual RCA",
            this_is="fail/handoff: strategy global, live still 0",
            step_note="strategy 6-10; still disconnected 11; late live 12; handoff 14-15.",
            next_note="Next: Prom honor_labels true vs job matcher.",
            query_cmd="curl -sS $GRAFANA/api/live/ws?stream=ramair | jq '{ok:.connected,error}'",
            false_cmd="yq '.limits_config.ingestion_rate_strategy' loki/ramair-ingrate.yaml",
            reload_cmd="kubectl -n loki rollout restart sts/loki-ingester && kubectl -n loki rollout status sts/loki-ingester --timeout=120s",
            requery_cmd="curl -sS $GRAFANA/api/live/ws?stream=ramair | jq '{ok:.connected,error}'",
            denied_cmd="kubectl -n grafana auth can-i patch configmap/grafana-ini --as=sre-bot",
            wrong_old="ingestion_rate_strategy: local",
            wrong_new="ingestion_rate_strategy: global",
            wrong2_old="enabled: true",
            wrong2_new="enabled: false",
            ticket_body="OBS-5383: ram-air-door-svc Live still down. ingest leftover. live.max_connections 0. Need 100. No grafana RBAC.\n",
            goal="ram-air-door-svc dashboard ramair-live-ingrate ram air live logs empty. Restore Live.",
            plan="Switch strategy global (r289 leftover).",
            outcome="strategy global; still disconnected. Late live 0. Handoff OBS-5383.",
            obs=[
                '[{"uid":"ramair-live-ingrate","title":"ram air live"}]',
                '{"title":"ram air live logs","targets":[{"expr":"{job=\\"ram-air-door-svc\\"} |= \\"door_skew\\""}]}',
                '{"ok":false,"error":"live connections exhausted"}',
                "ingestion_rate_strategy: local",
                "treated as r289",
                "loki/ramair-ingrate.yaml",
                "patched global",
                'statefulset "loki-ingester" successfully rolled out',
                '{"ok":false,"error":"live connections exhausted"}',
                "patched patagg false",
                '{"ok":false,"error":"live connections exhausted"}',
                "grafana/ramair.ini [live] max_connections = 0; query_range n=9",
                "no",
                "wrote tickets/OBS-5383.md",
                "xfail tests/test_ramair_live.py",
            ],
        ),
    )
)

# r316 Prom honor_labels true vs job matcher
MORE.append(
    (
        _okfull(
            slug="prom-honor-labels-job-mismatch",
            service="pa-chime-svc",
            dashboard_uid="pchime-honor-8",
            panel="PA chime count",
            query='avg(pa_chime_total{job="pa-chime-svc"})',
            lie="scrape honor_labels true plus the app exposes job=debug so Grafana {job=\"pa-chime-svc\"} is empty while job=debug has 22",
            false_lead="honor_timestamps / alloy prometheus.relabel",
            config_path="prom/pchime-honorts.yaml",
            lie_path="prom/pchime-honor.yaml",
            truth_name="honor_labels vs job=debug",
            reload_name="prom-scrape",
            side="jobs with honor_labels false still attach scrape job",
            surfaces="Prometheus honor_labels true vs Grafana job matcher empty",
            avoided="r234 honor_timestamps; r177 alloy relabel; r297 label_limit",
            this_is="honor_labels true keeps app job=debug",
            step_note="False lead honorts/alloy 4-5; honor_labels true 6-8; false 9-12.",
            query_cmd="curl -sS -G $MIMIR/prometheus/api/v1/query --data-urlencode 'query=avg(pa_chime_total{job=\"pa-chime-svc\"})'",
            false_cmd="yq '.scrape_configs[]|select(.job_name==\"pa-chime-svc\")|{honor_timestamps,relabel_configs}' prom/pchime-honorts.yaml",
            truth_cmd="curl -sS -G $MIMIR/prometheus/api/v1/query --data-urlencode 'query=pa_chime_total{job=\"debug\"}' | jq '.data.result'",
            confirm_cmd="yq '.scrape_configs[]|select(.job_name==\"pa-chime-svc\").honor_labels' prom/pchime-honor.yaml",
            reload_cmd="kubectl -n prom rollout restart deploy/prom-scrape && kubectl -n prom rollout status deploy/prom-scrape --timeout=90s",
            requery_cmd="curl -sS -G $MIMIR/prometheus/api/v1/query --data-urlencode 'query=avg(pa_chime_total{job=\"pa-chime-svc\"})'",
            side_cmd="curl -sS -G $MIMIR/prometheus/api/v1/query --data-urlencode 'query=avg(pa_chime_total{job=\"ssr-meal-svc\"})' | jq '.data.result|length'",
            final_cmd="yq -r '.scrape_configs[]|select(.job_name==\"pa-chime-svc\").honor_labels' prom/pchime-honor.yaml",
            patch_old="honor_labels: true",
            patch_new="honor_labels: false",
            runbook_path="runbooks/pchime-honor.md",
            runbook="# pa-chime-svc honor_labels\ntrue keeps job=debug. Set false. Not honor_timestamps.\n",
            goal="pa-chime-svc dashboard pchime-honor-8 PA chime count empty on job=. job=debug=22. Find the honor_labels lie.",
            plan="Empty job → honorts/alloy (false) → honor_labels true → false.",
            outcome="honor_labels false. count=22. ssr-meal-svc unchanged.",
            obs=[
                '[{"uid":"pchime-honor-8","title":"pa chime"}]',
                '{"title":"PA chime count","targets":[{"expr":"avg(pa_chime_total{job=\\"pa-chime-svc\\"})"}]}',
                '{"status":"success","data":{"result":[]}}',
                "honor_timestamps: false\nrelabel_configs: []  # not r234/r177",
                "honorts off; no alloy relabel",
                "honor_labels: true",
                '[{"metric":{"job":"debug"},"value":[1710000000,"22"]}]',
                "app job=debug honored; scrape job dropped",
                "patched false",
                'deployment "prom-scrape" successfully rolled out',
                '{"status":"success","data":{"result":[{"value":[1710000600,"22"]}]}}',
                '{"name":"Timeseries"}',
                "1",
                "wrote runbooks/pchime-honor.md",
                "false",
            ],
        ),
        _badfull(
            slug="prom-honor-disable-ts-not-labels",
            service="lav-occupied-svc",
            dashboard_uid="lavocc-honor-ts",
            panel="lav occupied",
            query='avg(lav_occupied{job="lav-occupied-svc"})',
            lie="Disabling honor_timestamps does not restore {job=} when honor_labels still keeps job=debug",
            false_lead="honor_timestamps true drops future samples",
            config_path="prom/lavocc-honorts.yaml",
            lie_path="prom/lavocc-honor.yaml",
            wrong_path="prom/lavocc-honorts.yaml",
            reload_name="prom-scrape",
            ticket="OBS-5384",
            xfail="tests/test_lavocc_honor.py",
            surfaces="honor_timestamps leftover vs honor_labels true",
            avoided="r234 as actual RCA",
            this_is="fail/handoff: honorts false, honor_labels still true",
            step_note="honorts 6-10; still empty 11; late honor_labels 12; handoff 14-15.",
            next_note="Catalog r309-r316. Keep unique vs r109-r308. Not r292 tag-values clone.",
            query_cmd="curl -sS -G $MIMIR/prometheus/api/v1/query --data-urlencode 'query=avg(lav_occupied{job=\"lav-occupied-svc\"})'",
            false_cmd="yq '.scrape_configs[]|select(.job_name==\"lav-occupied-svc\").honor_timestamps' prom/lavocc-honorts.yaml",
            reload_cmd="kubectl -n prom rollout restart deploy/prom-scrape && kubectl -n prom rollout status deploy/prom-scrape --timeout=90s",
            requery_cmd="curl -sS -G $MIMIR/prometheus/api/v1/query --data-urlencode 'query=avg(lav_occupied{job=\"lav-occupied-svc\"})'",
            denied_cmd="kubectl -n prom auth can-i patch configmap/lavocc-honor --as=sre-bot",
            wrong_old="honor_timestamps: true",
            wrong_new="honor_timestamps: false",
            wrong2_old="relabel_configs:\n      - source_labels: [job]\n        replacement: debug\n        target_label: job",
            wrong2_new="relabel_configs: []",
            ticket_body="OBS-5384: lav-occupied-svc still empty on job=. honorts leftover. honor_labels true keeps job=debug. Need false. No scrape RBAC.\n",
            goal="lav-occupied-svc dashboard lavocc-honor-ts lav occupied empty. Restore job matcher.",
            plan="Disable honor_timestamps (r234 leftover).",
            outcome="honorts false; still empty. Late honor_labels true. Handoff OBS-5384.",
            obs=[
                '[{"uid":"lavocc-honor-ts","title":"lav occupied"}]',
                '{"title":"lav occupied","targets":[{"expr":"avg(lav_occupied{job=\\"lav-occupied-svc\\"})"}]}',
                '{"status":"success","data":{"result":[]}}',
                "honor_timestamps: true",
                "treated as r234",
                "prom/lavocc-honorts.yaml",
                "patched false",
                'deployment "prom-scrape" successfully rolled out',
                '{"status":"success","data":{"result":[]}}',
                "patched relabel []",
                '{"status":"success","data":{"result":[]}}',
                "prom/lavocc-honor.yaml honor_labels true; lav_occupied{job=\"debug\"}=1",
                "no",
                "wrote tickets/OBS-5384.md",
                "xfail tests/test_lavocc_honor.py",
            ],
        ),
    )
)
