"""Observability leftover leftover leftover leftover leftover plants r605+.

BAN r515 rootly-urgency-filter-silent-drop-leftover / rootly-urg-raise-page-not-filter,
r384 otel-forward-connector-drop-pipeline / otel-fwd-restore-otlp-not-forward,
PagerDuty orch, Opsgenie alias, r163-r604 clones including mill_plants_w leftover4.
Leftover5 lie: silent remap, wrong index, dropped attribute, filter drop.
"""

from mill_plants_t import _leftover_pair

MORE = []
ROUND_PAIRS = {}


def _emit(round_n, **kwargs):
    dest = []
    _leftover_pair(n=str(round_n), dest=dest, **kwargs)
    MORE.extend(dest)
    ROUND_PAIRS[round_n] = dest[0]


def _l5(
    n,
    *,
    vendor,
    ok_slug,
    bad_slug,
    noun,
    panel,
    needle,
    lie_core,
    false_lead,
    avoided,
    knob,
    old,
    new,
    wrong_knob,
    wrong_old,
    wrong_new,
    wrong2_old,
    wrong2_new,
    prefix,
):
    ok_svc = f"cell-{noun}-svc"
    bad_svc = f"lab-{noun}-svc"
    tag = noun.replace("-", "")[:8]
    vtag = prefix.replace("-", "")[:5]
    ok_dash = f"{tag}-{vtag}-{n}"
    bad_dash = f"l{tag[:7]}-{vtag}-fl"
    _emit(
        n,
        kind="grafana",
        ok_slug=ok_slug,
        bad_slug=bad_slug,
        ok_svc=ok_svc,
        bad_svc=bad_svc,
        ok_dash=ok_dash,
        bad_dash=bad_dash,
        panel=panel,
        metric="",
        needle=needle,
        lie=(
            f"{vendor} leftover {lie_core} so Grafana dashboard {ok_dash} is empty "
            f"while the source still 202"
        ),
        bad_lie=(
            f"{false_lead} does not restore leftover leftover leftover leftover leftover "
            f"{lie_core}"
        ),
        false_lead=false_lead,
        avoided=avoided,
        this_is=f"{vendor} leftover leftover leftover leftover leftover {lie_core}",
        ticket=f"OBS-{7800 + (n - 605)}",
        knob=knob,
        old=old,
        new=new,
        wrong_knob=wrong_knob,
        wrong_old=wrong_old,
        wrong_new=wrong_new,
        wrong2_old=wrong2_old,
        wrong2_new=wrong2_new,
        reload="grafana",
        config_path=f"{prefix}/{tag}-false.yaml",
        lie_path=f"{prefix}/{tag}-lie.yaml",
        bad_config=f"{prefix}/l{tag[:7]}-false.yaml",
        bad_lie_path=f"{prefix}/l{tag[:7]}-lie.yaml",
    )


SPECS = [
    dict(vendor="Tetragon", ok_slug="tetragon-export-allowlist-drop-leftover", bad_slug="tetragon-allow-raise-rate-not-filter", noun="n2boost", panel="Tetragon events", needle="n2_exec", lie_core="export allowlist leftover drops process exec for cell-n2boost-svc", false_lead="Tetragon export rate leftover", avoided="leftover3 Falco; leftover3 eBPF map; Sysdig filter r596; PagerDuty orch; Opsgenie alias", knob=".export.allowlist", old="allowlist: [sandbox]", new="allowlist: [cell-n2boost-svc]", wrong_knob=".export.rate_limit", wrong_old="rate_limit: 1", wrong_new="rate_limit: 10000", wrong2_old="mode: observe", wrong2_new="mode: enforce", prefix="tetragon"),
    dict(vendor="Kepler", ok_slug="kepler-metric-allowlist-drop-leftover", bad_slug="kepler-allow-raise-sample-not-list", noun="oxyboost", panel="Kepler joules", needle="oxy_joule", lie_core="metric allowlist leftover keeps only cpu so Grafana job=cell-oxyboost-svc is empty", false_lead="Kepler sample leftover", avoided="r504 Prom honor_labels; DCGM field plant; leftover3 VM relabel; Opsgenie alias", knob=".metrics.allowlist", old="allowlist: [cpu]", new="allowlist: [*]", wrong_knob=".sample.interval", wrong_old="interval: 5m", wrong_new="interval: 5s", wrong2_old="exporter: stdout", wrong2_new="exporter: prometheus", prefix="kepler"),
    dict(vendor="OpenCost", ok_slug="opencost-etl-drop-namespace-leftover", bad_slug="ocost-etl-raise-window-not-drop", noun="hydmule", panel="OpenCost ETL", needle="hyd_cost", lie_core="ETL leftover drops namespace hangar so Grafana is the wrong dashboard", false_lead="OpenCost window leftover", avoided="Kubecost later; r504 Prom honor_labels; PagerDuty orch; Opsgenie alias", knob=".etl.drop_namespaces", old="drop_namespaces: [hangar]", new="drop_namespaces: []", wrong_knob=".etl.window", wrong_old="window: 1h", wrong_new="window: 1d", wrong2_old="cloud: none", wrong2_new="cloud: aws", prefix="opencost"),
    dict(vendor="Kubecost", ok_slug="kubecost-allocation-filter-drop-leftover", bad_slug="kcost-alloc-raise-res-not-filter", noun="idgrig", panel="Kubecost allocation", needle="idg_cost", lie_core="allocation leftover filter namespace!=hangar so Grafana is empty", false_lead="Kubecost resolution leftover", avoided="OpenCost ETL plant; leftover3 VM relabel; PagerDuty orch; Opsgenie alias", knob=".allocation.filter", old="filter: namespace!=hangar", new="filter: namespace=hangar", wrong_knob=".allocation.resolution", wrong_old="resolution: 1d", wrong_new="resolution: 10m", wrong2_old="shareIdle: false", wrong2_new="shareIdle: true", prefix="kubecost"),
    dict(vendor="Goldilocks", ok_slug="goldilocks-vpa-exclude-drop-leftover", bad_slug="goldi-vpa-raise-recommender-not-exclude", noun="tensio", panel="Goldilocks VPAs", needle="ten_cpu", lie_core="vpa leftover exclude cell-tensio-svc so Grafana is empty while the controller still 200", false_lead="Goldilocks recommender leftover", avoided="VPA later; prometheus-adapter r580; PagerDuty orch; Opsgenie alias", knob=".vpa.exclude", old="exclude: [cell-tensio-svc]", new="exclude: []", wrong_knob=".recommender.interval", wrong_old="interval: 24h", wrong_new="interval: 1h", wrong2_old="onByDefault: false", wrong2_new="onByDefault: true", prefix="goldilocks"),
    dict(vendor="metrics-server", ok_slug="metricsserver-metric-resolution-drop-leftover", bad_slug="msrv-res-raise-scrape-not-window", noun="tqwbox", panel="metrics-server", needle="tqw_cpu", lie_core="metric-resolution leftover 30m so Grafana HPA panel is empty while kubectl top still works", false_lead="metrics-server scrape leftover", avoided="prometheus-adapter r580; Goldilocks VPA plant; leftover3 VM relabel", knob=".metric-resolution", old="metric-resolution: 30m", new="metric-resolution: 15s", wrong_knob=".kubelet.preferredAddressTypes", wrong_old="preferredAddressTypes: [Hostname]", wrong_new="preferredAddressTypes: [InternalIP,Hostname]", wrong2_old="kubelet-insecure-tls: false", wrong2_new="kubelet-insecure-tls: true", prefix="msrv"),
    dict(vendor="KEDA", ok_slug="keda-scaledobject-paused-drop-leftover", bad_slug="keda-pause-raise-cooldown-not-flag", noun="borovid", panel="KEDA scalers", needle="boro_hpa", lie_core="ScaledObject leftover paused:true so Grafana replica panel is empty while metrics still 200", false_lead="KEDA cooldown leftover", avoided="prometheus-adapter r580; metrics-server plant; PagerDuty orch; Opsgenie alias", knob=".scaledobject.paused", old="paused: true", new="paused: false", wrong_knob=".cooldownPeriod", wrong_old="cooldownPeriod: 3600", wrong_new="cooldownPeriod: 30", wrong2_old="minReplicaCount: 0", wrong2_new="minReplicaCount: 1", prefix="keda"),
    dict(vendor="VPA", ok_slug="vpa-update-mode-off-drop-leftover", bad_slug="vpa-mode-raise-evict-not-off", noun="ndtut", panel="VPA recommendations", needle="ndt_cpu", lie_core="updateMode leftover Off plus recommendation missing so Grafana is empty", false_lead="VPA eviction leftover", avoided="Goldilocks VPA plant; KEDA pause plant; PagerDuty orch; Opsgenie alias", knob=".updatePolicy.updateMode", old="updateMode: Off", new="updateMode: Auto", wrong_knob=".eviction.minReplicas", wrong_old="minReplicas: 99", wrong_new="minReplicas: 1", wrong2_old="recommender: none", wrong2_new="recommender: default", prefix="vpa"),
    dict(vendor="Grafana Sift", ok_slug="grafanasift-check-disable-drop-leftover", bad_slug="gsift-chk-raise-window-not-enable", noun="paintmix", panel="Grafana Sift", needle="mix_error", lie_core="Sift leftover checks.enabled=false so Grafana investigations panel is empty", false_lead="Grafana Sift window leftover", avoided="r496 Grafana dataproxy timeout; r503 folder ACL; PagerDuty orch; Opsgenie alias; r515 Rootly", knob=".sift.checks.enabled", old="enabled: false", new="enabled: true", wrong_knob=".sift.window", wrong_old="window: 1m", wrong_new="window: 1h", wrong2_old="datasource: prometheus-sandbox", wrong2_new="datasource: prometheus", prefix="gsift"),
    dict(vendor="Grafana Asserts", ok_slug="grafanaasserts-entity-filter-drop-leftover", bad_slug="gassert-ent-raise-graph-not-filter", noun="stripbath", panel="Grafana Asserts", needle="bath_assert", lie_core="entity filter leftover env=sandbox so Grafana is the wrong dashboard", false_lead="Grafana Asserts graph leftover", avoided="Grafana Sift plant; r503 folder ACL; PagerDuty orch; Opsgenie alias", knob=".asserts.entities.env", old="env: sandbox", new="env: hangar", wrong_knob=".asserts.graph.enabled", wrong_old="enabled: false", wrong_new="enabled: true", wrong2_old="metric: none", wrong2_new="metric: RED", prefix="gassert"),
    dict(vendor="Grafana ML", ok_slug="grafanaml-outlier-job-drop-leftover", bad_slug="gml-out-raise-interval-not-job", noun="wheelpress", panel="Grafana ML outliers", needle="press_spike", lie_core="outlier job leftover metric never-matches cell-wheelpress-svc so Grafana is empty", false_lead="Grafana ML interval leftover", avoided="Grafana Sift plant; r496 dataproxy timeout; PagerDuty orch; Opsgenie alias", knob=".ml.outlier.metric", old='metric: up{job="none"}', new='metric: up{job="cell-wheelpress-svc"}', wrong_knob=".ml.outlier.interval", wrong_old="interval: 24h", wrong_new="interval: 5m", wrong2_old="sensitivity: 0", wrong2_new="sensitivity: 0.8", prefix="grafanaml"),
    dict(vendor="Pyrra", ok_slug="pyrra-slo-objective-drop-leftover", bad_slug="pyrra-obj-raise-window-not-ratio", noun="brakepress", panel="Pyrra SLOs", needle="brake_slo", lie_core="SLO leftover target=0 so Grafana error budget is empty while Prometheus still has ratios", false_lead="Pyrra window leftover", avoided="r504 Prom honor_labels; Grafana ML plant; PagerDuty orch; Opsgenie alias; r515 Rootly", knob=".slo.target", old="target: 0", new="target: 0.999", wrong_knob=".slo.window", wrong_old="window: 1h", wrong_new="window: 28d", wrong2_old="indicator: dummy", wrong2_new="indicator: ratio", prefix="pyrra"),
    dict(vendor="Sloth", ok_slug="sloth-slo-disable-drop-leftover", bad_slug="sloth-dis-raise-pageslo-not-enable", noun="battcap", panel="Sloth SLOs", needle="batt_slo", lie_core="Sloth leftover disable=true so Grafana recording rules are empty", false_lead="Sloth page SLO leftover", avoided="Pyrra SLO plant; leftover3 Prom remote_write ban; PagerDuty orch; Opsgenie alias", knob=".slos[].disable", old="disable: true", new="disable: false", wrong_knob=".slos[].pageAlert.enabled", wrong_old="enabled: false", wrong_new="enabled: true", wrong2_old="objective: 0", wrong2_new="objective: 99.9", prefix="sloth"),
    dict(vendor="OpenSLO", ok_slug="openslo-service-remap-wrong-dash-leftover", bad_slug="oslo-svc-raise-window-not-remap", noun="seatfoam", panel="OpenSLO services", needle="foam_slo", lie_core="service leftover remaps cell-seatfoam-svc into sandbox so Grafana is the wrong dashboard", false_lead="OpenSLO window leftover", avoided="Pyrra SLO plant; Sloth disable plant; PagerDuty orch; Opsgenie alias", knob=".spec.service", old="service: sandbox", new="service: cell-seatfoam-svc", wrong_knob=".spec.window", wrong_old="window: 1h", wrong_new="window: 28d", wrong2_old="budgetingMethod: Occurrences", wrong2_new="budgetingMethod: Timeslices", prefix="openslo"),
    dict(vendor="Nobl9", ok_slug="nobl9-slo-project-remap-leftover", bad_slug="nobl9-proj-raise-budget-not-remap", noun="galleycart", panel="Nobl9 SLOs", needle="cart_slo", lie_core="project leftover remaps cell-galleycart-svc into demo so Grafana is the wrong dashboard", false_lead="Nobl9 budget leftover", avoided="OpenSLO remap plant; Pyrra SLO; PagerDuty orch; Opsgenie alias; r515 Rootly", knob=".project.remap", old="remap: demo", new="remap: cell-galleycart-svc", wrong_knob=".budgeting.target", wrong_old="target: 0", wrong_new="target: 0.999", wrong2_old="agent: sandbox", wrong2_new="agent: hangar", prefix="nobl9"),
    dict(vendor="Blameless", ok_slug="blameless-severity-filter-drop-leftover", bad_slug="blame-sev-raise-sla-not-filter", noun="ifehead", panel="Blameless incidents", needle="ife_sev", lie_core="severity leftover filter=SEV5-only silently drops SEV1 so Grafana is empty", false_lead="Blameless SLA leftover", avoided="PagerDuty orch; Opsgenie alias; r515 Rootly urgency; r513 incidentio source", knob=".incidents.severity_filter", old="severity_filter: SEV5", new="severity_filter: SEV1,SEV2,SEV3,SEV4,SEV5", wrong_knob=".sla.ack_minutes", wrong_old="ack_minutes: 120", wrong_new="ack_minutes: 5", wrong2_old="type: test", wrong2_new="type: prod", prefix="blameless"),
    dict(vendor="Jeli", ok_slug="jeli-insight-source-drop-leftover", bad_slug="jeli-src-raise-retro-not-source", noun="radiotest", panel="Jeli insights", needle="radio_insight", lie_core="insight source leftover drops grafana so Grafana is empty while Slack still 202", false_lead="Jeli retro leftover", avoided="PagerDuty orch; Opsgenie alias; Blameless severity; r515 Rootly urgency", knob=".insights.sources.drop", old="drop: [grafana]", new="drop: []", wrong_knob=".retros.enabled", wrong_old="enabled: false", wrong_new="enabled: true", wrong2_old="team: default", wrong2_new="team: hangar", prefix="jeli"),
    dict(vendor="Statuspage", ok_slug="statuspage-component-hide-drop-leftover", bad_slug="spage-comp-raise-page-not-hide", noun="gyrocal", panel="Statuspage components", needle="gyro_status", lie_core="component leftover hidden=true so Grafana status panel is empty while the page still 200", false_lead="Statuspage page leftover", avoided="PagerDuty orch; Opsgenie alias; r512 OnCall team; r515 Rootly urgency", knob=".components.hidden", old="hidden: true", new="hidden: false", wrong_knob=".page.subdomain", wrong_old="subdomain: sandbox", wrong_new="subdomain: hangar", wrong2_old="notifications: off", wrong2_new="notifications: on", prefix="statuspage"),
    dict(vendor="Cachet", ok_slug="cachet-component-group-remap-leftover", bad_slug="cachet-grp-raise-visible-not-group", noun="altcal", panel="Cachet components", needle="alt_status", lie_core="group leftover remaps cell-altcal-svc into archive so Grafana is the wrong dashboard", false_lead="Cachet visible leftover", avoided="Statuspage hide plant; PagerDuty orch; Opsgenie alias; r515 Rootly", knob=".components.group", old="group: archive", new="group: hangar", wrong_knob=".components.visible", wrong_old="visible: 0", wrong_new="visible: 1", wrong2_old="status: 4", wrong2_new="status: 1", prefix="cachet"),
    dict(vendor="Instatus", ok_slug="instatus-component-filter-drop-leftover", bad_slug="instatus-comp-raise-page-not-filter", noun="xpdrcal", panel="Instatus components", needle="xpdr_status", lie_core="component leftover filter=maintenance-only so Grafana is empty while the page still 200", false_lead="Instatus page leftover", avoided="Statuspage hide; Cachet group; PagerDuty orch; Opsgenie alias", knob=".components.filter", old="filter: maintenance", new="filter: all", wrong_knob=".page.slug", wrong_old="slug: sandbox", wrong_new="slug: hangar", wrong2_old="branding: off", wrong2_new="branding: on", prefix="instatus"),
    dict(vendor="Site24x7", ok_slug="site24x7-monitor-tag-drop-leftover", bad_slug="s247-tag-raise-freq-not-drop", noun="tcascal", panel="Site24x7 monitors", needle="tcas_http", lie_core="monitor tag leftover drops service so Grafana is the wrong dashboard", false_lead="Site24x7 frequency leftover", avoided="Checkly tag r569; Pingdom tag r570; PagerDuty orch; Opsgenie alias", knob=".monitors.tags.drop", old="drop: [service]", new="drop: []", wrong_knob=".monitors.frequency", wrong_old="frequency: 60", wrong_new="frequency: 1", wrong2_old="locations: [us]", wrong2_new="locations: [us,eu]", prefix="site24x7"),
    dict(vendor="Freshping", ok_slug="freshping-check-pause-drop-leftover", bad_slug="fping-pause-raise-int-not-flag", noun="wxcal", panel="Freshping checks", needle="wx_http", lie_core="check leftover paused=true so Grafana is empty while the URL still 200", false_lead="Freshping interval leftover", avoided="UptimeRobot type r572; StatusCake group; PagerDuty orch; Opsgenie alias", knob=".checks.paused", old="paused: true", new="paused: false", wrong_knob=".checks.interval", wrong_old="interval: 300", wrong_new="interval: 60", wrong2_old="regions: [us]", wrong2_new="regions: [us,eu,ap]", prefix="freshping"),
    dict(vendor="Lacework", ok_slug="lacework-policy-filter-drop-leftover", bad_slug="lace-pol-raise-sev-not-filter", noun="eltcal", panel="Lacework events", needle="elt_exec", lie_core="policy leftover filter account=sandbox so Grafana is empty while the agent still 202", false_lead="Lacework severity leftover", avoided="leftover3 Falco; Wazuh rule r593; Sysdig r596; PagerDuty orch; Opsgenie alias", knob=".policies.account", old="account: sandbox", new="account: hangar", wrong_knob=".policies.severity", wrong_old="severity: info", wrong_new="severity: high", wrong2_old="enabled: false", wrong2_new="enabled: true", prefix="lacework"),
    dict(vendor="Wiz", ok_slug="wiz-sensor-filter-drop-leftover", bad_slug="wiz-sens-raise-scan-not-filter", noun="oxycyl", panel="Wiz issues", needle="oxy_cve", lie_core="sensor leftover filter cluster=sandbox so Grafana is empty while the sensor still 202", false_lead="Wiz scan leftover", avoided="Aqua runtime r597; Lacework policy; leftover3 Falco; PagerDuty orch; Opsgenie alias", knob=".sensor.cluster", old="cluster: sandbox", new="cluster: hangar", wrong_knob=".scanner.interval", wrong_old="interval: 7d", wrong_new="interval: 1h", wrong2_old="enforce: off", wrong2_new="enforce: on", prefix="wiz"),
    dict(vendor="Prisma Cloud", ok_slug="prisma-policy-disable-drop-leftover", bad_slug="prisma-pol-raise-alert-not-enable", noun="fabriccut", panel="Prisma alerts", needle="cut_cve", lie_core="policy leftover enabled=false so Grafana is empty while twistlock still 200", false_lead="Prisma alert leftover", avoided="Wiz sensor plant; Aqua r597; leftover3 Falco; PagerDuty orch; Opsgenie alias", knob=".policies.enabled", old="enabled: false", new="enabled: true", wrong_knob=".alerts.email", wrong_old="email: none", wrong_new="email: mro@hangar.local", wrong2_old="console: sandbox", wrong2_new="console: hangar", prefix="prisma"),
    dict(vendor="Qualys", ok_slug="qualys-asset-group-remap-leftover", bad_slug="qualys-ag-raise-scan-not-group", noun="sheetbend", panel="Qualys assets", needle="bend_cve", lie_core="asset group leftover remaps cell-sheetbend-svc into sandbox so Grafana is the wrong dashboard", false_lead="Qualys scan leftover", avoided="Prisma policy; Wiz sensor; leftover3 Falco; PagerDuty orch; Opsgenie alias", knob=".asset_groups.remap", old="remap: sandbox", new="remap: hangar", wrong_knob=".scans.interval", wrong_old="interval: 30d", wrong_new="interval: 1d", wrong2_old="scanner: external", wrong2_new="scanner: internal", prefix="qualys"),
    dict(vendor="Rapid7", ok_slug="rapid7-insight-source-drop-leftover", bad_slug="r7-src-raise-retain-not-source", noun="millcnc", panel="Rapid7 insights", needle="cnc_auth", lie_core="insight source leftover drops grafana so Grafana is empty while the collector still 202", false_lead="Rapid7 retain leftover", avoided="Lacework policy; Wiz sensor; leftover3 Falco; PagerDuty orch; Opsgenie alias", knob=".insights.sources.drop", old="drop: [grafana]", new="drop: []", wrong_knob=".retain.days", wrong_old="days: 1", wrong_new="days: 90", wrong2_old="region: us", wrong2_new="region: eu", prefix="rapid7"),
    dict(vendor="Tenable", ok_slug="tenable-tag-filter-drop-leftover", bad_slug="tenable-tag-raise-scan-not-filter", noun="weldtig", panel="Tenable assets", needle="tig_cve", lie_core="tag leftover include=legacy so Grafana is the wrong dashboard", false_lead="Tenable scan leftover", avoided="Qualys asset group; Prisma policy; leftover3 Falco; PagerDuty orch; Opsgenie alias", knob=".tags.include", old="include: [legacy]", new="include: [hangar]", wrong_knob=".scans.interval", wrong_old="interval: 30d", wrong_new="interval: 1d", wrong2_old="network: default", wrong2_new="network: hangar", prefix="tenable"),
    dict(vendor="Trivy Operator", ok_slug="trivyop-report-filter-drop-leftover", bad_slug="trivy-rep-raise-scan-not-filter", noun="platetank", panel="Trivy reports", needle="plate_cve", lie_core="report leftover severity=UNKNOWN-only so Grafana is empty while trivy still found CRITICAL", false_lead="Trivy scan leftover", avoided="leftover3 Falco; Wiz sensor; Aqua r597; PagerDuty orch; Opsgenie alias", knob=".reports.severity", old="severity: UNKNOWN", new="severity: UNKNOWN,LOW,MEDIUM,HIGH,CRITICAL", wrong_knob=".operator.scanJobTimeout", wrong_old="scanJobTimeout: 1s", wrong_new="scanJobTimeout: 5m", wrong2_old="namespace: trivy-dev", wrong2_new="namespace: trivy", prefix="trivyop"),
    dict(vendor="New Relic Browser", ok_slug="nrbrowser-app-rename-wrong-dash-leftover", bad_slug="nrbrow-app-raise-sample-not-rename", noun="fpitank", panel="NR Browser", needle="fpi_js", lie_core="app leftover rename cell-fpitank-svc to sandbox so Grafana is the wrong dashboard", false_lead="NR Browser sample leftover", avoided="leftover3 NR span-event; r168 Faro session; PagerDuty orch; Opsgenie alias", knob=".browser.application_name", old="application_name: sandbox", new="application_name: cell-fpitank-svc", wrong_knob=".browser.sample_rate", wrong_old="sample_rate: 0.01", wrong_new="sample_rate: 1.0", wrong2_old="distributed_tracing: false", wrong2_new="distributed_tracing: true", prefix="nrbrowser"),
    dict(vendor="Datadog RUM", ok_slug="ddrum-application-id-remap-leftover", bad_slug="ddrum-app-raise-session-not-id", noun="mpicoil", panel="DD RUM", needle="mpi_js", lie_core="applicationId leftover remaps to sandbox so Grafana is the wrong dashboard while intake still 202", false_lead="DD RUM session leftover", avoided="r500 DD log pipeline; r190 DD UST; r163 tid128; r168 Faro session", knob=".rum.applicationId", old="applicationId: sandbox", new="applicationId: cell-mpicoil-svc", wrong_knob=".rum.sessionSampleRate", wrong_old="sessionSampleRate: 1", wrong_new="sessionSampleRate: 100", wrong2_old="trackFrustrations: false", wrong2_new="trackFrustrations: true", prefix="ddrum"),
    dict(vendor="Elastic RUM", ok_slug="elasticrum-service-name-remap-leftover", bad_slug="erum-svc-raise-sample-not-name", noun="cmmprobe", panel="Elastic RUM", needle="cmm_js", lie_core="serviceName leftover remaps cell-cmmprobe-svc into sandbox so Grafana is the wrong dashboard", false_lead="Elastic RUM sample leftover", avoided="leftover3 elastic-apm sample rate; r168 Faro; Datadog RUM plant; Opsgenie alias", knob=".rum.serviceName", old="serviceName: sandbox", new="serviceName: cell-cmmprobe-svc", wrong_knob=".rum.transactionSampleRate", wrong_old="transactionSampleRate: 0.01", wrong_new="transactionSampleRate: 1.0", wrong2_old="serverUrl: http://localhost:8200", wrong2_new="serverUrl: https://apm.hangar", prefix="elasticrum"),
    dict(vendor="AppDynamics EUM", ok_slug="appdeum-app-key-remap-leftover", bad_slug="appdeum-key-raise-beacon-not-key", noun="engstand", panel="AppD EUM", needle="eng_js", lie_core="appKey leftover remaps to sandbox so Grafana is the wrong dashboard", false_lead="AppD beacon leftover", avoided="leftover3 AppD bt-exclude; r168 Faro; Datadog RUM; PagerDuty orch; Opsgenie alias", knob=".eum.appKey", old="appKey: sandbox", new="appKey: cell-engstand-svc", wrong_knob=".eum.beaconUrl", wrong_old="beaconUrl: https://sandbox.eum-appdynamics.com", wrong_new="beaconUrl: https://col.eum-appdynamics.com", wrong2_old="adrumExtUrlHttp: off", wrong2_new="adrumExtUrlHttp: on", prefix="appdeum"),
    dict(vendor="Dynatrace RUM", ok_slug="dtrum-application-filter-drop-leftover", bad_slug="dtrum-app-raise-cost-not-filter", noun="apustand", panel="Dynatrace RUM", needle="apu_js", lie_core="application leftover filter=dev so Grafana is empty while the beacon still 202", false_lead="Dynatrace cost leftover", avoided="leftover3 Dynatrace mgmt zone; r168 Faro; AppD EUM plant; Opsgenie alias", knob=".rum.application", old="application: dev", new="application: production", wrong_knob=".rum.costControl", wrong_old="costControl: capture-off", wrong_new="costControl: capture-full", wrong2_old="injection: manual", wrong2_new="injection: auto", prefix="dtrum"),
    dict(vendor="Sentry Replay", ok_slug="sentryreplay-session-sample-zero-leftover", bad_slug="sreplay-samp-raise-error-not-session", noun="pumpbench", panel="Sentry replays", needle="pump_js", lie_core="replaysSessionSampleRate leftover 0 so Grafana is empty while /envelope still 200", false_lead="Sentry error sample leftover", avoided="r501 Sentry inbound-filter; r386 Sentry ignore-errors; r168 Faro; Opsgenie alias", knob=".replay.replaysSessionSampleRate", old="replaysSessionSampleRate: 0", new="replaysSessionSampleRate: 1.0", wrong_knob=".replay.replaysOnErrorSampleRate", wrong_old="replaysOnErrorSampleRate: 0", wrong_new="replaysOnErrorSampleRate: 1.0", wrong2_old="maskAllText: true", wrong2_new="maskAllText: false", prefix="sreplay"),
    dict(vendor="Playwright traces", ok_slug="playwright-trace-dir-drop-leftover", bad_slug="pwtrace-dir-raise-video-not-dir", noun="actbench", panel="Playwright traces", needle="act_trace", lie_core="trace leftover outputDir=/tmp/empty so Grafana is empty while the test still passed", false_lead="Playwright video leftover", avoided="k6cloud test remap r579; Grafana SM allowlist ban; PagerDuty orch; Opsgenie alias", knob=".use.trace.outputDir", old="outputDir: /tmp/empty", new="outputDir: /data/traces", wrong_knob=".use.video", wrong_old="video: off", wrong_new="video: on", wrong2_old="screenshot: off", wrong2_new="screenshot: on", prefix="playwright"),
    dict(vendor="Cypress Cloud", ok_slug="cypress-project-id-remap-leftover", bad_slug="cypress-id-raise-parallel-not-id", noun="cablebench", panel="Cypress recordings", needle="cable_spec", lie_core="projectId leftover remaps to sandbox so Grafana is the wrong dashboard", false_lead="Cypress parallel leftover", avoided="Playwright trace plant; k6cloud remap; PagerDuty orch; Opsgenie alias", knob=".projectId", old="projectId: sandbox", new="projectId: cell-cablebench-svc", wrong_knob=".parallel", wrong_old="parallel: 1", wrong_new="parallel: 8", wrong2_old="record: false", wrong2_new="record: true", prefix="cypress"),
    dict(vendor="Karma", ok_slug="karma-alertmanager-uri-drop-leftover", bad_slug="karma-uri-raise-filter-not-uri", noun="fcbench", panel="Karma silences", needle="fc_alert", lie_core="alertmanager leftover uri points at sandbox so Grafana is empty while AM still 200", false_lead="Karma filter leftover", avoided="r505 AM continue; r457 AM group_interval; PagerDuty orch; Opsgenie alias", knob=".alertmanager.uri", old="uri: http://am-sandbox:9093", new="uri: http://alertmanager:9093", wrong_knob=".filters.default", wrong_old='default: ["alertname=~sandbox"]', wrong_new='default: []', wrong2_old="silenceForm.author: none", wrong2_new="silenceForm.author: mro", prefix="karma"),
    dict(vendor="Alerta", ok_slug="alerta-environment-filter-drop-leftover", bad_slug="alerta-env-raise-key-not-filter", noun="gearbench", panel="Alerta events", needle="gear_alert", lie_core="environment leftover filter=dev so Grafana is empty while /alert still 201", false_lead="Alerta key leftover", avoided="Karma AM plant; r505 AM continue; PagerDuty orch; Opsgenie alias; r515 Rootly", knob=".AUTH_REQUIRED environment", old="ALLOWED_ENVIRONMENTS: [dev]", new="ALLOWED_ENVIRONMENTS: [dev,hangar,prod]", wrong_knob=".SECRET_KEY", wrong_old="SECRET_KEY: sandbox", wrong_new="SECRET_KEY: hangar", wrong2_old="AUTH_REQUIRED: False", wrong2_new="AUTH_REQUIRED: True", prefix="alerta"),
    dict(vendor="Bosun", ok_slug="bosun-template-unknown-drop-leftover", bad_slug="bosun-unk-raise-tsdb-not-unknown", noun="n2skid", panel="Bosun alerts", needle="n2_alert", lie_core="unknown leftover ignore so Grafana is empty while scollector still 200", false_lead="Bosun TSDB leftover", avoided="Alerta env plant; r505 AM continue; leftover3 VM relabel; Opsgenie alias", knob=".unknown.ignore", old="ignore: true", new="ignore: false", wrong_knob=".tsdbHost", wrong_old="tsdbHost: localhost:0", wrong_new="tsdbHost: opentsdb:4242", wrong2_old="checkFrequency: 1h", wrong2_new="checkFrequency: 1m", prefix="bosun"),
    dict(vendor="Kapacitor", ok_slug="kapacitor-task-disabled-drop-leftover", bad_slug="kapac-task-raise-dbrp-not-enable", noun="tirepress", panel="Kapacitor tasks", needle="tire_alert", lie_core="task leftover status=disabled so Grafana is empty while Influx still has points", false_lead="Kapacitor DBRP leftover", avoided="Bosun unknown plant; leftover3 Influx prefix; PagerDuty orch; Opsgenie alias", knob=".tasks.status", old="status: disabled", new="status: enabled", wrong_knob=".dbrp.db", wrong_old="db: sandbox", wrong_new="db: hangar", wrong2_old="rp: autogen", wrong2_new="rp: hangar", prefix="kapacitor"),
    dict(vendor="Sensu", ok_slug="sensu-filter-action-drop-leftover", bad_slug="sensu-filt-raise-ttl-not-action", noun="carbonpress", panel="Sensu events", needle="carbon_check", lie_core="filter leftover action=deny for cell-carbonpress-svc so Grafana is empty", false_lead="Sensu TTL leftover", avoided="Nagios servicegroup r537; Icinga filter r538; PagerDuty orch; Opsgenie alias", knob=".filters.action", old="action: deny", new="action: allow", wrong_knob=".checks.ttl", wrong_old="ttl: 1", wrong_new="ttl: 120", wrong2_old="namespace: default", wrong2_new="namespace: hangar", prefix="sensu"),
    dict(vendor="LibreNMS", ok_slug="librenms-device-group-remap-leftover", bad_slug="lnms-grp-raise-poll-not-group", noun="heatpress", panel="LibreNMS devices", needle="heat_if", lie_core="device group leftover remaps cell-heatpress-svc into sandbox so Grafana is the wrong dashboard", false_lead="LibreNMS poll leftover", avoided="SolarWinds property r541; PRTG channel r540; PagerDuty orch; Opsgenie alias", knob=".device_groups.remap", old="remap: sandbox", new="remap: hangar", wrong_knob=".poller.interval", wrong_old="interval: 3600", wrong_new="interval: 60", wrong2_old="snmp.community: public", wrong2_new="snmp.community: hangar", prefix="librenms"),
    dict(vendor="Observium", ok_slug="observium-ignore-os-drop-leftover", bad_slug="obsium-os-raise-poll-not-ignore", noun="uldpress", panel="Observium ports", needle="uld_if", lie_core="ignore leftover os=linux so Grafana is empty while snmpwalk still has cell-uldpress-svc", false_lead="Observium poll leftover", avoided="LibreNMS group plant; snmp_exporter r584; PagerDuty orch; Opsgenie alias", knob=".config.bad_os", old="bad_os: [linux]", new="bad_os: []", wrong_knob=".poller.interval", wrong_old="interval: 3600", wrong_new="interval: 60", wrong2_old="rancid: off", wrong2_new="rancid: on", prefix="observium"),
    dict(vendor="Cacti", ok_slug="cacti-graph-template-hide-leftover", bad_slug="cacti-tpl-raise-rrd-not-hide", noun="palletpress", panel="Cacti graphs", needle="pallet_rrd", lie_core="graph template leftover disabled so Grafana is empty while rrdtool still has files", false_lead="Cacti RRD leftover", avoided="Observium ignore; Graphite carbon r534; PagerDuty orch; Opsgenie alias", knob=".graph_templates.disabled", old="disabled: 1", new="disabled: 0", wrong_knob=".rrd.step", wrong_old="step: 3600", wrong_new="step: 60", wrong2_old="boost: off", wrong2_new="boost: on", prefix="cacti"),
    dict(vendor="Munin", ok_slug="munin-plugin-disable-drop-leftover", bad_slug="munin-plug-raise-int-not-enable", noun="igloocell", panel="Munin plugins", needle="igloo_cpu", lie_core="plugin leftover [cell-igloocell-svc:*] ignore so Grafana is empty", false_lead="Munin interval leftover", avoided="Cacti graph plant; node_exporter r582; leftover3 VM relabel; Opsgenie alias", knob=".plugins.ignore", old="ignore: cell-igloocell-svc", new="ignore: none", wrong_knob=".timeouts.update", wrong_old="update: 3600", wrong_new="update: 60", wrong2_old="graph_strategy: cgi", wrong2_new="graph_strategy: cron", prefix="munin"),
    dict(vendor="Ganglia", ok_slug="ganglia-grid-remap-wrong-dash-leftover", bad_slug="ganglia-grid-raise-ttl-not-remap", noun="firecell", panel="Ganglia grids", needle="fire_cpu", lie_core="grid leftover remaps cell-firecell-svc into sandbox so Grafana is the wrong dashboard", false_lead="Ganglia TTL leftover", avoided="Munin plugin plant; Graphite carbon r534; leftover3 VM relabel", knob=".grid.name", old="name: sandbox", new="name: hangar", wrong_knob=".gmetad.ttl", wrong_old="ttl: 1", wrong_new="ttl: 60", wrong2_old="rrd_rootdir: /tmp", wrong2_new="rrd_rootdir: /var/lib/ganglia", prefix="ganglia"),
    dict(vendor="Diamond", ok_slug="diamond-collector-disable-drop-leftover", bad_slug="diamond-col-raise-int-not-enable", noun="hydrocell", panel="Diamond collectors", needle="hydro_cpu", lie_core="collector leftover enabled=False so Grafana is empty while /metrics still 200", false_lead="Diamond interval leftover", avoided="Munin plugin; Telegraf namepass r532; leftover3 VM relabel; Opsgenie alias", knob=".collectors.CPUCollector.enabled", old="enabled: False", new="enabled: True", wrong_knob=".collectors.CPUCollector.interval", wrong_old="interval: 300", wrong_new="interval: 10", wrong2_old="handlers: []", wrong2_new="handlers: [graphite]", prefix="diamond"),
    dict(vendor="Brubeck", ok_slug="brubeck-sampler-drop-metric-leftover", bad_slug="brubeck-samp-raise-port-not-drop", noun="vestcell", panel="Brubeck stats", needle="vest_stat", lie_core="sampler leftover drop ^cell-vestcell so Grafana is empty while statsd still 200", false_lead="Brubeck port leftover", avoided="r statsd prefix clones; Telegraf namepass; leftover3 VM relabel; Opsgenie alias", knob=".sampler.drop", old="drop: ^cell-vestcell", new="drop: none", wrong_knob=".sampler.port", wrong_old="port: 0", wrong_new="port: 8126", wrong2_old="backend: carbon-sandbox", wrong2_new="backend: carbon", prefix="brubeck"),
    dict(vendor="DogStatsD", ok_slug="dogstatsd-tag-blocklist-drop-leftover", bad_slug="dsd-block-raise-buf-not-list", noun="maskcell", panel="DogStatsD tags", needle="mask_stat", lie_core="tag blocklist leftover drops service so Grafana is the wrong dashboard", false_lead="DogStatsD buffer leftover", avoided="r190 DD UST; r500 DD log pipeline; Telegraf namepass; Opsgenie alias", knob=".dogstatsd.tag_blocklist", old="tag_blocklist: [service]", new="tag_blocklist: []", wrong_knob=".dogstatsd.buffer_size", wrong_old="buffer_size: 1", wrong_new="buffer_size: 8192", wrong2_old="origin_detection: false", wrong2_new="origin_detection: true", prefix="dogstatsd"),
    dict(vendor="TimescaleDB", ok_slug="timescaledb-cagg-view-drop-leftover", bad_slug="tsdb-cagg-raise-chunk-not-view", noun="megacell", panel="Timescale continuous aggs", needle="mega_cagg", lie_core="cagg leftover materialized_only plus view dropped so Grafana is empty while hypertable still has rows", false_lead="Timescale chunk leftover", avoided="leftover3 ClickHouse rows; leftover3 QuestDB wal; PagerDuty orch; Opsgenie alias", knob=".caggs.materialized_only", old="materialized_only: true", new="materialized_only: false", wrong_knob=".chunks.interval", wrong_old="interval: 1 year", wrong_new="interval: 1 day", wrong2_old="compression: off", wrong2_new="compression: on", prefix="timescaledb"),
    dict(vendor="Azure Data Explorer", ok_slug="kusto-database-remap-wrong-dash-leftover", bad_slug="kusto-db-raise-cache-not-remap", noun="axecell", panel="ADX queries", needle="axe_kql", lie_core="database leftover remaps cell-axecell-svc into sandbox so Grafana is the wrong dashboard", false_lead="ADX cache leftover", avoided="r510 AzMon KQL workspace; leftover3 ClickHouse rows; PagerDuty orch; Opsgenie alias", knob=".kusto.database", old="database: sandbox", new="database: hangar", wrong_knob=".kusto.cache", wrong_old="cache: off", wrong_new="cache: hot", wrong2_old="cluster: adx-dev", wrong2_new="cluster: adx-hangar", prefix="kusto"),
    dict(vendor="Snowflake", ok_slug="snowflake-view-filter-drop-leftover", bad_slug="snow-view-raise-wh-not-filter", noun="aidcell", panel="Snowflake views", needle="aid_sql", lie_core="view leftover WHERE service!='cell-aidcell-svc' so Grafana is empty while the table still has rows", false_lead="Snowflake warehouse leftover", avoided="Kusto database plant; leftover3 ClickHouse; Tinybird pipe r559; Opsgenie alias", knob=".views.filter", old="filter: service != 'cell-aidcell-svc'", new="filter: 1=1", wrong_knob=".warehouse.size", wrong_old="size: XSMALL", wrong_new="size: LARGE", wrong2_old="role: PUBLIC", wrong2_new="role: HANGAR", prefix="snowflake"),
    dict(vendor="Databricks SQL", ok_slug="databricks-sql-warehouse-stop-leftover", bad_slug="dbricks-wh-raise-auto-not-stop", noun="aedcell", panel="Databricks SQL", needle="aed_sql", lie_core="warehouse leftover state=STOPPED so Grafana is empty while the table still has rows", false_lead="Databricks autoscaling leftover", avoided="Snowflake view plant; leftover3 ClickHouse; PagerDuty orch; Opsgenie alias", knob=".warehouses.state", old="state: STOPPED", new="state: RUNNING", wrong_knob=".warehouses.min_num_clusters", wrong_old="min_num_clusters: 0", wrong_new="min_num_clusters: 1", wrong2_old="spot: true", wrong2_new="spot: false", prefix="databricks"),
    dict(vendor="BigQuery", ok_slug="bigquery-dataset-remap-wrong-dash-leftover", bad_slug="bq-ds-raise-slot-not-remap", noun="pbecell", panel="BigQuery datasets", needle="pbe_sql", lie_core="dataset leftover remaps cell-pbecell-svc into sandbox so Grafana is the wrong dashboard", false_lead="BigQuery slots leftover", avoided="r507 Stackdriver descriptor; Kusto remap; leftover3 ClickHouse; Opsgenie alias", knob=".datasets.remap", old="remap: sandbox", new="remap: hangar", wrong_knob=".slots.reservation", wrong_old="reservation: 0", wrong_new="reservation: 100", wrong2_old="location: US", wrong2_new="location: EU", prefix="bigquery"),
    dict(vendor="Redshift", ok_slug="redshift-schema-search-drop-leftover", bad_slug="rshift-sch-raise-wlm-not-schema", noun="torchcell", panel="Redshift schemas", needle="torch_sql", lie_core="search_path leftover omits hangar so Grafana is empty while the table still exists", false_lead="Redshift WLM leftover", avoided="BigQuery dataset plant; leftover3 ClickHouse; Snowflake view; Opsgenie alias", knob=".search_path", old="search_path: sandbox", new="search_path: hangar, public", wrong_knob=".wlm.slots", wrong_old="slots: 1", wrong_new="slots: 50", wrong2_old="concurrency: 1", wrong2_new="concurrency: 15", prefix="redshift"),
    dict(vendor="CloudWatch Logs", ok_slug="cwlogs-subscription-filter-drop-leftover", bad_slug="cwlogs-sub-raise-retain-not-filter", noun="calcell", panel="CW Logs", needle="cal_log", lie_core="subscription leftover filter-pattern NEVER so Grafana is empty while /filter still 200", false_lead="CW Logs retention leftover", avoided="r506 CW metric math; r508 wait r508 is CW math; leftover3 Splunk frozen; Opsgenie alias", knob=".subscription.filterPattern", old="filterPattern: NEVER", new="filterPattern: ", wrong_knob=".retentionInDays", wrong_old="retentionInDays: 1", wrong_new="retentionInDays: 30", wrong2_old="kms: none", wrong2_new="kms: hangar", prefix="cwlogs"),
    dict(vendor="Cloud Logging", ok_slug="gcplog-exclusion-drop-leftover", bad_slug="gcplog-excl-raise-sink-not-filter", noun="torqcell", panel="GCP logs", needle="torq_log", lie_core="exclusion leftover protoPayload.service=cell-torqcell-svc so Grafana is empty", false_lead="GCP log sink leftover", avoided="r507 SD metric descriptor; CW Logs plant; leftover3 Splunk frozen; Opsgenie alias", knob=".exclusions.filter", old="filter: protoPayload.serviceName=cell-torqcell-svc", new="filter: none", wrong_knob=".sinks.destination", wrong_old="destination: logging.googleapis.com/projects/sandbox", wrong_new="destination: logging.googleapis.com/projects/hangar", wrong2_old="includeChildren: false", wrong2_new="includeChildren: true", prefix="gcplog"),
    dict(vendor="Azure Diagnostics", ok_slug="azdiag-category-drop-leftover", bad_slug="azdiag-cat-raise-dest-not-drop", noun="presscell", panel="Azure diagnostics", needle="press_log", lie_core="category leftover logs=false so Grafana is empty while the resource still 200", false_lead="Azure dest leftover", avoided="r510 AzMon KQL workspace; CW Logs plant; GCP log exclusion; Opsgenie alias", knob=".logs.categoryGroup.logs", old="logs: false", new="logs: true", wrong_knob=".workspaceId", wrong_old="workspaceId: sandbox", wrong_new="workspaceId: hangar", wrong2_old="metrics: false", wrong2_new="metrics: true", prefix="azdiag"),
    dict(vendor="OCI Logging", ok_slug="ocilog-log-group-remap-leftover", bad_slug="ocilog-grp-raise-search-not-group", noun="tempcell", panel="OCI logs", needle="temp_log", lie_core="log group leftover remaps cell-tempcell-svc into sandbox so Grafana is the wrong dashboard", false_lead="OCI search leftover", avoided="Azure diag plant; CW Logs; GCP log exclusion; PagerDuty orch; Opsgenie alias", knob=".logGroups.remap", old="remap: sandbox", new="remap: hangar", wrong_knob=".search.time", wrong_old="time: 1m", wrong_new="time: 1h", wrong2_old="compartment: sandbox", wrong2_new="compartment: hangar", prefix="ocilog"),
    dict(vendor="Cloud Trace", ok_slug="gcptrace-attribute-drop-leftover", bad_slug="gtrace-attr-raise-sample-not-drop", noun="eleccell", panel="GCP traces", needle="elec_span", lie_core="attribute leftover drops /http/path so Grafana is empty while spans still 200", false_lead="Cloud Trace sample leftover", avoided="r384 OTel forward; leftover3 k8sattributes; Dash0 attribute r564; Opsgenie alias", knob=".trace.attributes.drop", old="drop: [/http/path]", new="drop: []", wrong_knob=".trace.sampling.rate", wrong_old="rate: 0.0001", wrong_new="rate: 1.0", wrong2_old="project: sandbox", wrong2_new="project: hangar", prefix="gcptrace"),
    dict(vendor="App Insights", ok_slug="appinsights-sampling-zero-leftover", bad_slug="ainsight-samp-raise-ikey-not-rate", noun="avicell", panel="App Insights", needle="avi_req", lie_core="sampling leftover percentage=0 so Grafana is empty while the SDK still 200", false_lead="App Insights iKey leftover", avoided="Azure diag plant; Dynatrace RUM plant; leftover3 AppD bt-exclude; Opsgenie alias", knob=".sampling.percentage", old="percentage: 0", new="percentage: 100", wrong_knob=".instrumentationKey", wrong_old="instrumentationKey: sandbox", wrong_new="instrumentationKey: hangar", wrong2_old="enableDebug: false", wrong2_new="enableDebug: true", prefix="appinsights"),
    dict(vendor="ADOT", ok_slug="adot-exporter-drop-pipeline-leftover", bad_slug="adot-exp-raise-mem-not-pipeline", noun="swcell", panel="ADOT traces", needle="sw_span", lie_core="exporter leftover traces/otlp/hangar missing from traces pipeline so Grafana is empty", false_lead="ADOT memory leftover", avoided="r384 OTel forward connector; leftover3 memory_limiter; Dash0 attribute; Opsgenie alias", knob=".service.pipelines.traces.exporters", old="exporters: [logging]", new="exporters: [otlp/hangar]", wrong_knob=".processors.memory_limiter.limit_mib", wrong_old="limit_mib: 1", wrong_new="limit_mib: 512", wrong2_old="receivers: [otlp]", wrong2_new="receivers: [otlp,awsxray]", prefix="adot"),
    dict(vendor="Fluent Operator", ok_slug="fluentop-clusterfilter-drop-leftover", bad_slug="fop-filt-raise-buffer-not-drop", noun="pincell", panel="Fluent Operator", needle="pin_log", lie_core="ClusterFilter leftover grep -v cell-pincell-svc so Grafana is empty", false_lead="Fluent Operator buffer leftover", avoided="r398 fluentbit mem-buf; Fluentd match r525; r177 Alloy relabel; Opsgenie alias", knob=".clusterFilters.grep", old="grep: -v cell-pincell-svc", new="grep: none", wrong_knob=".clusterInputs.buffer", wrong_old="buffer: 1k", wrong_new="buffer: 8m", wrong2_old="flush: 60s", wrong2_new="flush: 1s", prefix="fluentop"),
    dict(vendor="Logging Operator", ok_slug="loggingop-flow-drop-leftover", bad_slug="logop-flow-raise-buffer-not-drop", noun="magcell", panel="Logging Operator", needle="mag_log", lie_core="Flow leftover exclude cell-magcell-svc so Grafana is empty while fluentd still 200", false_lead="Logging Operator buffer leftover", avoided="Fluent Operator filter; Fluentd match r525; r398 fluentbit; Opsgenie alias", knob=".flows.exclude", old="exclude: [cell-magcell-svc]", new="exclude: []", wrong_knob=".buffer.timekey", wrong_old="timekey: 1h", wrong_new="timekey: 1m", wrong2_old="flush_mode: lazy", wrong2_new="flush_mode: immediate", prefix="loggingop"),
    dict(vendor="Loki Operator", ok_slug="lokiop-ruler-enable-false-leftover", bad_slug="lokiop-ruler-raise-wal-not-enable", noun="usbcell", panel="Loki Operator rules", needle="usb_rule", lie_core="ruler leftover enabled=false so Grafana recording panel is empty while logs still ingest", false_lead="Loki Operator WAL leftover", avoided="r402 Loki ruler evaluation_interval; r467 ruler remote_write; leftover3 max_query_series", knob=".ruler.enabled", old="enabled: false", new="enabled: true", wrong_knob=".ruler.wal", wrong_old="wal: /tmp", wrong_new="wal: /data/ruler", wrong2_old="replicas: 0", wrong2_new="replicas: 1", prefix="lokiop"),
    dict(vendor="prometheus-operator", ok_slug="promop-servicemonitor-drop-leftover", bad_slug="promop-sm-raise-int-not-select", noun="pmdtcell", panel="ServiceMonitors", needle="pmdt_up", lie_core="ServiceMonitor leftover selector matchLabels never-match cell-pmdtcell-svc so Grafana is empty", false_lead="prometheus-operator interval leftover", avoided="r504 Prom honor_labels; prometheus-adapter r580; leftover3 VM relabel; Opsgenie alias", knob=".serviceMonitor.selector", old="selector: {app: sandbox}", new="selector: {app: cell-pmdtcell-svc}", wrong_knob=".serviceMonitor.interval", wrong_old="interval: 5m", wrong_new="interval: 15s", wrong2_old="scrapeTimeout: 1ms", wrong2_new="scrapeTimeout: 10s", prefix="promop"),
    dict(vendor="Tempo vulture", ok_slug="tempovulture-search-disable-leftover", bad_slug="tvulture-srch-raise-qps-not-search", noun="ammcell", panel="Tempo vulture", needle="amm_trace", lie_core="vulture leftover search.enabled=false so Grafana is empty while traces still ingest", false_lead="Tempo vulture QPS leftover", avoided="r247 Tempo search.enabled; r292 tag-values; r384 OTel forward; Opsgenie alias", knob=".vulture.search.enabled", old="enabled: false", new="enabled: true", wrong_knob=".vulture.qps", wrong_old="qps: 0", wrong_new="qps: 10", wrong2_old="tempo_addr: http://tempo-sandbox:3200", wrong2_new="tempo_addr: http://tempo:3200", prefix="tvulture"),
    dict(vendor="Loki canary", ok_slug="lokicanary-label-drop-leftover", bad_slug="lcanary-lbl-raise-int-not-drop", noun="ipccell", panel="Loki canary", needle="ipc_canary", lie_core="canary leftover label drop stream so Grafana is empty while Loki still ingest", false_lead="Loki canary interval leftover", avoided="r244 Loki max_concurrent; leftover3 max_query_series; r177 Alloy relabel; Opsgenie alias", knob=".canary.labelname", old="labelname: dropped", new="labelname: stream", wrong_knob=".canary.interval", wrong_old="interval: 1h", wrong_new="interval: 1s", wrong2_old="addr: http://loki-sandbox:3100", wrong2_new="addr: http://loki:3100", prefix="lcanary"),
    dict(vendor="Mimir continuous-test", ok_slug="mimirctest-write-disable-leftover", bad_slug="mctest-wr-raise-query-not-write", noun="taskcell", panel="Mimir continuous-test", needle="task_ctest", lie_core="continuous-test leftover write.enabled=false so Grafana is empty while Mimir still ready", false_lead="Mimir continuous-test query leftover", avoided="r499 Mimir remote_timeout; leftover3 max_label_value_length; PagerDuty orch; Opsgenie alias", knob=".continuous_test.write.enabled", old="enabled: false", new="enabled: true", wrong_knob=".continuous_test.query.enabled", wrong_old="enabled: false", wrong_new="enabled: true", wrong2_old="endpoint: http://mimir-sandbox:8080", wrong2_new="endpoint: http://mimir:8080", prefix="mctest"),
    dict(vendor="Grafana SLO", ok_slug="grafanaslo-folder-remap-wrong-dash-leftover", bad_slug="gslo-fold-raise-window-not-folder", noun="jobcell", panel="Grafana SLOs", needle="job_slo", lie_core="folder leftover remaps cell-jobcell-svc into sandbox so Grafana is the wrong dashboard", false_lead="Grafana SLO window leftover", avoided="r503 Grafana folder ACL; Pyrra SLO plant; r496 dataproxy timeout; Opsgenie alias", knob=".slo.folder", old="folder: sandbox", new="folder: hangar", wrong_knob=".slo.window", wrong_old="window: 1h", wrong_new="window: 28d", wrong2_old="objective: 0", wrong2_new="objective: 0.999", prefix="gslo"),
    dict(vendor="CrowdSec", ok_slug="crowdsec-scenario-disable-drop-leftover", bad_slug="csec-scen-raise-bouncer-not-enable", noun="toolcell", panel="CrowdSec alerts", needle="tool_ban", lie_core="scenario leftover enabled=false so Grafana is empty while the log still has 401s", false_lead="CrowdSec bouncer leftover", avoided="leftover3 Falco; Wazuh r593; Sysdig r596; PagerDuty orch; Opsgenie alias", knob=".scenarios.enabled", old="enabled: false", new="enabled: true", wrong_knob=".bouncers.enabled", wrong_old="enabled: false", wrong_new="enabled: true", wrong2_old="api: http://sandbox:8080", wrong2_new="api: http://lapi:8080", prefix="crowdsec"),
    dict(vendor="Thanos Ruler", ok_slug="thanosruler-query-endpoints-empty-leftover", bad_slug="truler-qe-raise-resend-not-query", noun="caltcell", panel="Thanos Ruler", needle="calt_rule", lie_core="query leftover endpoints=[] so Grafana is empty while Store still has blocks", false_lead="Thanos Ruler resend leftover", avoided="leftover3 Thanos store denylist; r407 Thanos hashrings empty; PagerDuty orch; Opsgenie alias", knob=".query.endpoints", old="endpoints: []", new="endpoints: [http://thanos-query:10902]", wrong_knob=".rule.resendDelay", wrong_old="resendDelay: 24h", wrong_new="resendDelay: 1m", wrong2_old="evalInterval: 1h", wrong2_new="evalInterval: 30s", prefix="truler"),
    dict(vendor="vmalert", ok_slug="vmalert-notifier-url-empty-leftover", bad_slug="vmalert-nf-raise-eval-not-url", noun="quarcell", panel="vmalert rules", needle="quar_alert", lie_core="notifier leftover url empty so Grafana is empty while vmselect still has series", false_lead="vmalert eval leftover", avoided="leftover3 VM relabel; r505 AM continue; PagerDuty orch; Opsgenie alias; r515 Rootly", knob=".notifier.url", old="url: ", new="url: http://alertmanager:9093", wrong_knob=".evaluationInterval", wrong_old="evaluationInterval: 1h", wrong_new="evaluationInterval: 15s", wrong2_old="datasource.url: http://vm-sandbox:8481", wrong2_new="datasource.url: http://vmselect:8481", prefix="vmalert"),
    dict(vendor="Grafana Incident", ok_slug="grafanaincident-declare-filter-drop-leftover", bad_slug="ginc-decl-raise-slack-not-filter", noun="bondcell", panel="Grafana Incident", needle="bond_inc", lie_core="declare leftover filter=drill-only so Grafana is empty while IRM still 202", false_lead="Grafana Incident Slack leftover", avoided="r159 IRM vs AM ban; r512 OnCall team; PagerDuty orch; Opsgenie alias; r515 Rootly", knob=".incident.declare.filter", old="filter: drill", new="filter: all", wrong_knob=".slack.enabled", wrong_old="enabled: false", wrong_new="enabled: true", wrong2_old="chat: sandbox", wrong2_new="chat: hangar", prefix="gincident"),
    dict(vendor="OpenTelemetry Operator", ok_slug="otelop-targetallocator-off-leftover", bad_slug="otelop-ta-raise-replicas-not-alloc", noun="rotcell", panel="OTel Operator", needle="rot_scrape", lie_core="targetAllocator leftover enabled=false so Grafana is empty while the CR still 200", false_lead="OTel Operator replicas leftover", avoided="r384 OTel forward; leftover3 memory_limiter; ADOT pipeline plant; Opsgenie alias", knob=".spec.targetAllocator.enabled", old="enabled: false", new="enabled: true", wrong_knob=".spec.replicas", wrong_old="replicas: 0", wrong_new="replicas: 2", wrong2_old="mode: deployment", wrong2_new="mode: statefulset", prefix="otelop"),
    dict(vendor="k6 operator", ok_slug="k6op-testrun-paused-drop-leftover", bad_slug="k6op-pause-raise-vus-not-flag", noun="conscell", panel="k6 operator", needle="cons_http", lie_core="TestRun leftover paused=true so Grafana is empty while the script still exists", false_lead="k6 operator VUs leftover", avoided="k6cloud test remap r579; Grafana SM allowlist ban; PagerDuty orch; Opsgenie alias", knob=".spec.paused", old="paused: true", new="paused: false", wrong_knob=".spec.parallelism", wrong_old="parallelism: 0", wrong_new="parallelism: 4", wrong2_old="arguments: --quiet", wrong2_new="arguments: --out influxdb", prefix="k6op"),
    dict(vendor="Pyroscope operator", ok_slug="pyroop-tenant-drop-leftover", bad_slug="pyroop-ten-raise-store-not-tenant", noun="aogcell", panel="Pyroscope operator", needle="aog_prof", lie_core="tenant leftover drop cell-aogcell-svc so Grafana is empty while pprof still 200", false_lead="Pyroscope operator store leftover", avoided="leftover3 pyro scrape 24h; r408 pyro max_flamegraph_nodes; PagerDuty orch; Opsgenie alias", knob=".tenants.drop", old="drop: [cell-aogcell-svc]", new="drop: []", wrong_knob=".store.bucket", wrong_old="bucket: sandbox", wrong_new="bucket: hangar", wrong2_old="replicas: 0", wrong2_new="replicas: 2", prefix="pyroop"),
]


assert len(SPECS) == 78, len(SPECS)
for i, spec in enumerate(SPECS):
    _l5(605 + i, **spec)
