"""Plants r330+: unique leftover leftover leftover rails (not r311–r329 twins).

Banned: UnionPay leftover already skip. Distinct rail + leftover leftover leftover
idempotency. Skip used Interac Autodeposit, PIX DOC, UPI RTGS, SEPA Instant TARGET2,
BLIK PayPo, Swish MobilePay, Vipps Twint, Bizum MB WAY, Klarna Afterpay, Affirm Zip,
Apple Pay Google Pay.
"""

import mill_plants_o as _o
from mill_plants_o import leftover3

MORE = []


def pair(ok, bad):
    MORE.append((ok, bad))


_o.pair = pair

leftover3(
    ok_slug="paynow-leftover-vs-fast",
    fail_slug="paynow-after-fast",
    stem="pnfs_ll",
    fail_stem="pnfs_lt",
    event="PayNow leftover leftover leftover",
    fail_event="PayNow leftover leftover leftover",
    pk="paynow_id",
    fail_pk="late_paynow_id",
    ctor="pnfs",
    rid="pn",
    rg="paynow_leftover|fast_leftover|paynow",
    fail_rg="late_paynow|fast_posted|paynow",
    avoided="r278 UnionPay leftover already skip; r329 Trustly leftover leftover leftover vs Sofort",
    fail_avoided="r330 PayNow leftover leftover leftover bind. This is late PayNow after leftover leftover leftover FAST",
    token_col="paynow",
    result_val="PNW01",
    leftover_check="pnfs_leftover_open",
    extra_col="  paynow text UNIQUE",
    fail_extra="  leftover_id text NOT NULL",
    surfaces="PayNow leftover leftover leftover vs leftover leftover leftover FAST same paynow",
    fail_surfaces="late PayNow leftover leftover leftover after leftover leftover leftover FAST posted",
    this_is="leftover leftover leftover bind; PayNow posts leftover_id; leftover leftover leftover FAST binds only",
    fail_this="late leftover leftover leftover flags; leftover leftover leftover FAST stays",
    seed="PayNow leftover leftover leftover + leftover leftover leftover FAST same paynow",
    fail_seed="leftover leftover leftover FAST posted then late PayNow leftover leftover leftover",
    counterpart="leftover leftover leftover FAST",
    key_name="paynow",
)

leftover3(
    ok_slug="duitnow-ll3-vs-rpp",
    fail_slug="duitnow-ll3-after-rpp",
    stem="dtrp_ll",
    fail_stem="dtrp_lt",
    event="DuitNow leftover leftover leftover",
    fail_event="DuitNow leftover leftover leftover",
    pk="rpp_id",
    fail_pk="late_rpp_id",
    ctor="dtrp",
    rid="rp",
    rg="duitnow_leftover|rpp_leftover|rpp",
    fail_rg="late_duitnow|rpp_posted|rpp",
    avoided="r278 UnionPay leftover already skip; leftover leftover leftover DuitNow vs FPX already skip; r330 PayNow leftover leftover leftover",
    fail_avoided="r331 DuitNow leftover leftover leftover bind. This is late DuitNow after leftover leftover leftover RPP",
    token_col="rpp",
    result_val="RPP01",
    leftover_check="dtrp_leftover_open",
    extra_col="  rpp text UNIQUE",
    fail_extra="  leftover_id text NOT NULL",
    surfaces="DuitNow leftover leftover leftover vs leftover leftover leftover RPP same rpp",
    fail_surfaces="late DuitNow leftover leftover leftover after leftover leftover leftover RPP posted",
    this_is="leftover leftover leftover bind; DuitNow posts leftover_id; leftover leftover leftover RPP binds only",
    fail_this="late leftover leftover leftover flags; leftover leftover leftover RPP stays",
    seed="DuitNow leftover leftover leftover + leftover leftover leftover RPP same rpp",
    fail_seed="leftover leftover leftover RPP posted then late DuitNow leftover leftover leftover",
    counterpart="leftover leftover leftover RPP",
    key_name="rpp",
)

leftover3(
    ok_slug="mbway-ll3-vs-sibs",
    fail_slug="mbway-ll3-after-sibs",
    stem="mbsb_ll",
    fail_stem="mbsb_lt",
    event="MB WAY leftover leftover leftover",
    fail_event="MB WAY leftover leftover leftover",
    pk="sibs_id",
    fail_pk="late_sibs_id",
    ctor="mbsb",
    rid="sb",
    rg="mbway_leftover|sibs_leftover|sibs",
    fail_rg="late_mbway|sibs_posted|sibs",
    avoided="r278 UnionPay leftover already skip; leftover leftover leftover MB WAY vs Multibanco already skip; r318 Bizum leftover leftover leftover vs MB WAY; r331 DuitNow leftover leftover leftover",
    fail_avoided="r332 MB WAY leftover leftover leftover bind. This is late MB WAY after leftover leftover leftover SIBS",
    token_col="sibs",
    result_val="SIB01",
    leftover_check="mbsb_leftover_open",
    extra_col="  sibs text UNIQUE",
    fail_extra="  leftover_id text NOT NULL",
    surfaces="MB WAY leftover leftover leftover vs leftover leftover leftover SIBS same sibs",
    fail_surfaces="late MB WAY leftover leftover leftover after leftover leftover leftover SIBS posted",
    this_is="leftover leftover leftover bind; MB WAY posts leftover_id; leftover leftover leftover SIBS binds only",
    fail_this="late leftover leftover leftover flags; leftover leftover leftover SIBS stays",
    seed="MB WAY leftover leftover leftover + leftover leftover leftover SIBS same sibs",
    fail_seed="leftover leftover leftover SIBS posted then late MB WAY leftover leftover leftover",
    counterpart="leftover leftover leftover SIBS",
    key_name="sibs",
)

leftover3(
    ok_slug="afterpay-leftover-vs-clearpay",
    fail_slug="afterpay-after-clearpay",
    stem="afcl_ll",
    fail_stem="afcl_lt",
    event="Afterpay leftover leftover leftover",
    fail_event="Afterpay leftover leftover leftover",
    pk="afterpay_id",
    fail_pk="late_afterpay_id",
    ctor="afcl",
    rid="cl",
    rg="afterpay_leftover|clearpay_leftover|afterpay",
    fail_rg="late_afterpay|clearpay_posted|afterpay",
    avoided="r278 UnionPay leftover already skip; r315 Klarna leftover leftover leftover vs Afterpay; r332 MB WAY leftover leftover leftover",
    fail_avoided="r333 Afterpay leftover leftover leftover bind. This is late Afterpay after leftover leftover leftover Clearpay",
    token_col="afterpay",
    result_val="AFP01",
    leftover_check="afcl_leftover_open",
    extra_col="  afterpay text UNIQUE",
    fail_extra="  leftover_id text NOT NULL",
    surfaces="Afterpay leftover leftover leftover vs leftover leftover leftover Clearpay same afterpay",
    fail_surfaces="late Afterpay leftover leftover leftover after leftover leftover leftover Clearpay posted",
    this_is="leftover leftover leftover bind; Afterpay posts leftover_id; leftover leftover leftover Clearpay binds only",
    fail_this="late leftover leftover leftover flags; leftover leftover leftover Clearpay stays",
    seed="Afterpay leftover leftover leftover + leftover leftover leftover Clearpay same afterpay",
    fail_seed="leftover leftover leftover Clearpay posted then late Afterpay leftover leftover leftover",
    counterpart="leftover leftover leftover Clearpay",
    key_name="afterpay",
)

leftover3(
    ok_slug="zip-leftover-vs-humm",
    fail_slug="zip-after-humm",
    stem="zphm_ll",
    fail_stem="zphm_lt",
    event="Zip leftover leftover leftover",
    fail_event="Zip leftover leftover leftover",
    pk="zip_id",
    fail_pk="late_zip_id",
    ctor="zphm",
    rid="hm",
    rg="zip_leftover|humm_leftover|zip",
    fail_rg="late_zip|humm_posted|zip",
    avoided="r278 UnionPay leftover already skip; r316 Affirm leftover leftover leftover vs Zip; r333 Afterpay leftover leftover leftover",
    fail_avoided="r334 Zip leftover leftover leftover bind. This is late Zip after leftover leftover leftover Humm",
    token_col="zip",
    result_val="ZIP01",
    leftover_check="zphm_leftover_open",
    extra_col="  zip text UNIQUE",
    fail_extra="  leftover_id text NOT NULL",
    surfaces="Zip leftover leftover leftover vs leftover leftover leftover Humm same zip",
    fail_surfaces="late Zip leftover leftover leftover after leftover leftover leftover Humm posted",
    this_is="leftover leftover leftover bind; Zip posts leftover_id; leftover leftover leftover Humm binds only",
    fail_this="late leftover leftover leftover flags; leftover leftover leftover Humm stays",
    seed="Zip leftover leftover leftover + leftover leftover leftover Humm same zip",
    fail_seed="leftover leftover leftover Humm posted then late Zip leftover leftover leftover",
    counterpart="leftover leftover leftover Humm",
    key_name="zip",
)

leftover3(
    ok_slug="klarna-leftover-vs-billie",
    fail_slug="klarna-after-billie",
    stem="klbi_ll",
    fail_stem="klbi_lt",
    event="Klarna leftover leftover leftover",
    fail_event="Klarna leftover leftover leftover",
    pk="klarna_id",
    fail_pk="late_klarna_id",
    ctor="klbi",
    rid="bi",
    rg="klarna_leftover|billie_leftover|klarna",
    fail_rg="late_klarna|billie_posted|klarna",
    avoided="r278 UnionPay leftover already skip; r315 Klarna leftover leftover leftover vs Afterpay; r334 Zip leftover leftover leftover",
    fail_avoided="r335 Klarna leftover leftover leftover bind. This is late Klarna after leftover leftover leftover Billie",
    token_col="klarna",
    result_val="KLN01",
    leftover_check="klbi_leftover_open",
    extra_col="  klarna text UNIQUE",
    fail_extra="  leftover_id text NOT NULL",
    surfaces="Klarna leftover leftover leftover vs leftover leftover leftover Billie same klarna",
    fail_surfaces="late Klarna leftover leftover leftover after leftover leftover leftover Billie posted",
    this_is="leftover leftover leftover bind; Klarna posts leftover_id; leftover leftover leftover Billie binds only",
    fail_this="late leftover leftover leftover flags; leftover leftover leftover Billie stays",
    seed="Klarna leftover leftover leftover + leftover leftover leftover Billie same klarna",
    fail_seed="leftover leftover leftover Billie posted then late Klarna leftover leftover leftover",
    counterpart="leftover leftover leftover Billie",
    key_name="klarna",
)

leftover3(
    ok_slug="affirm-leftover-vs-sezzle",
    fail_slug="affirm-after-sezzle",
    stem="afsz_ll",
    fail_stem="afsz_lt",
    event="Affirm leftover leftover leftover",
    fail_event="Affirm leftover leftover leftover",
    pk="affirm_id",
    fail_pk="late_affirm_id",
    ctor="afsz",
    rid="sz",
    rg="affirm_leftover|sezzle_leftover|affirm",
    fail_rg="late_affirm|sezzle_posted|affirm",
    avoided="r278 UnionPay leftover already skip; r316 Affirm leftover leftover leftover vs Zip; r335 Klarna leftover leftover leftover vs Billie",
    fail_avoided="r336 Affirm leftover leftover leftover bind. This is late Affirm after leftover leftover leftover Sezzle",
    token_col="affirm",
    result_val="AFM01",
    leftover_check="afsz_leftover_open",
    extra_col="  affirm text UNIQUE",
    fail_extra="  leftover_id text NOT NULL",
    surfaces="Affirm leftover leftover leftover vs leftover leftover leftover Sezzle same affirm",
    fail_surfaces="late Affirm leftover leftover leftover after leftover leftover leftover Sezzle posted",
    this_is="leftover leftover leftover bind; Affirm posts leftover_id; leftover leftover leftover Sezzle binds only",
    fail_this="late leftover leftover leftover flags; leftover leftover leftover Sezzle stays",
    seed="Affirm leftover leftover leftover + leftover leftover leftover Sezzle same affirm",
    fail_seed="leftover leftover leftover Sezzle posted then late Affirm leftover leftover leftover",
    counterpart="leftover leftover leftover Sezzle",
    key_name="affirm",
)

leftover3(
    ok_slug="afterpay-leftover-vs-laybuy",
    fail_slug="afterpay-after-laybuy",
    stem="aflb_ll",
    fail_stem="aflb_lt",
    event="Afterpay leftover leftover leftover",
    fail_event="Afterpay leftover leftover leftover",
    pk="laybuy_id",
    fail_pk="late_laybuy_id",
    ctor="aflb",
    rid="lb",
    rg="afterpay_leftover|laybuy_leftover|laybuy",
    fail_rg="late_afterpay|laybuy_posted|laybuy",
    avoided="r278 UnionPay leftover already skip; r333 Afterpay leftover leftover leftover vs Clearpay; r336 Affirm leftover leftover leftover vs Sezzle",
    fail_avoided="r337 Afterpay leftover leftover leftover bind. This is late Afterpay after leftover leftover leftover Laybuy",
    token_col="laybuy",
    result_val="LYB01",
    leftover_check="aflb_leftover_open",
    extra_col="  laybuy text UNIQUE",
    fail_extra="  leftover_id text NOT NULL",
    surfaces="Afterpay leftover leftover leftover vs leftover leftover leftover Laybuy same laybuy",
    fail_surfaces="late Afterpay leftover leftover leftover after leftover leftover leftover Laybuy posted",
    this_is="leftover leftover leftover bind; Afterpay posts leftover_id; leftover leftover leftover Laybuy binds only",
    fail_this="late leftover leftover leftover flags; leftover leftover leftover Laybuy stays",
    seed="Afterpay leftover leftover leftover + leftover leftover leftover Laybuy same laybuy",
    fail_seed="leftover leftover leftover Laybuy posted then late Afterpay leftover leftover leftover",
    counterpart="leftover leftover leftover Laybuy",
    key_name="laybuy",
)

leftover3(
    ok_slug="applepay-leftover-vs-samsungpay",
    fail_slug="applepay-after-samsungpay",
    stem="apsm_ll",
    fail_stem="apsm_lt",
    event="Apple Pay leftover leftover leftover",
    fail_event="Apple Pay leftover leftover leftover",
    pk="wallet_id",
    fail_pk="late_wallet_id",
    ctor="apsm",
    rid="sm",
    rg="applepay_leftover|samsungpay_leftover|wallet",
    fail_rg="late_applepay|samsungpay_posted|wallet",
    avoided="r278 UnionPay leftover already skip; r317 Apple Pay leftover leftover leftover vs Google Pay; r337 Afterpay leftover leftover leftover vs Laybuy",
    fail_avoided="r338 Apple Pay leftover leftover leftover bind. This is late Apple Pay after leftover leftover leftover Samsung Pay",
    token_col="wallet",
    result_val="WLT01",
    leftover_check="apsm_leftover_open",
    extra_col="  wallet text UNIQUE",
    fail_extra="  leftover_id text NOT NULL",
    surfaces="Apple Pay leftover leftover leftover vs leftover leftover leftover Samsung Pay same wallet",
    fail_surfaces="late Apple Pay leftover leftover leftover after leftover leftover leftover Samsung Pay posted",
    this_is="leftover leftover leftover bind; Apple Pay posts leftover_id; leftover leftover leftover Samsung Pay binds only",
    fail_this="late leftover leftover leftover flags; leftover leftover leftover Samsung Pay stays",
    seed="Apple Pay leftover leftover leftover + leftover leftover leftover Samsung Pay same wallet",
    fail_seed="leftover leftover leftover Samsung Pay posted then late Apple Pay leftover leftover leftover",
    counterpart="leftover leftover leftover Samsung Pay",
    key_name="wallet",
)

leftover3(
    ok_slug="pix-ll3-vs-spi",
    fail_slug="pix-ll3-after-spi",
    stem="pxsp_ll",
    fail_stem="pxsp_lt",
    event="PIX leftover leftover leftover",
    fail_event="PIX leftover leftover leftover",
    pk="spi_id",
    fail_pk="late_spi_id",
    ctor="pxsp",
    rid="sp",
    rg="pix_leftover|spi_leftover|spi",
    fail_rg="late_pix|spi_posted|spi",
    avoided="r278 UnionPay leftover already skip; leftover leftover leftover PIX vs Boleto already skip; r299 Pix Automático leftover leftover leftover vs TED; r322 PIX leftover leftover leftover vs DOC",
    fail_avoided="r339 PIX leftover leftover leftover bind. This is late PIX after leftover leftover leftover SPI",
    token_col="spi",
    result_val="SPI01",
    leftover_check="pxsp_leftover_open",
    extra_col="  spi text UNIQUE",
    fail_extra="  leftover_id text NOT NULL",
    surfaces="PIX leftover leftover leftover vs leftover leftover leftover SPI same spi",
    fail_surfaces="late PIX leftover leftover leftover after leftover leftover leftover SPI posted",
    this_is="leftover leftover leftover bind; PIX posts leftover_id; leftover leftover leftover SPI binds only",
    fail_this="late leftover leftover leftover flags; leftover leftover leftover SPI stays",
    seed="PIX leftover leftover leftover + leftover leftover leftover SPI same spi",
    fail_seed="leftover leftover leftover SPI posted then late PIX leftover leftover leftover",
    counterpart="leftover leftover leftover SPI",
    key_name="spi",
)

leftover3(
    ok_slug="upi-ll3-vs-neft",
    fail_slug="upi-ll3-after-neft",
    stem="upne_ll",
    fail_stem="upne_lt",
    event="UPI leftover leftover leftover",
    fail_event="UPI leftover leftover leftover",
    pk="neft_id",
    fail_pk="late_neft_id",
    ctor="upne",
    rid="nf",
    rg="upi_leftover|neft_leftover|neft",
    fail_rg="late_upi|neft_posted|neft",
    avoided="r278 UnionPay leftover already skip; leftover leftover leftover UPI vs IMPS already skip; r313 UPI leftover leftover leftover vs RTGS; r339 PIX leftover leftover leftover vs SPI",
    fail_avoided="r340 UPI leftover leftover leftover bind. This is late UPI after leftover leftover leftover NEFT",
    token_col="neft",
    result_val="NFT01",
    leftover_check="upne_leftover_open",
    extra_col="  neft text UNIQUE",
    fail_extra="  leftover_id text NOT NULL",
    surfaces="UPI leftover leftover leftover vs leftover leftover leftover NEFT same neft",
    fail_surfaces="late UPI leftover leftover leftover after leftover leftover leftover NEFT posted",
    this_is="leftover leftover leftover bind; UPI posts leftover_id; leftover leftover leftover NEFT binds only",
    fail_this="late leftover leftover leftover flags; leftover leftover leftover NEFT stays",
    seed="UPI leftover leftover leftover + leftover leftover leftover NEFT same neft",
    fail_seed="leftover leftover leftover NEFT posted then late UPI leftover leftover leftover",
    counterpart="leftover leftover leftover NEFT",
    key_name="neft",
)

leftover3(
    ok_slug="sepa-dd-leftover-vs-elv",
    fail_slug="sepa-dd-after-elv",
    stem="sdel_ll",
    fail_stem="sdel_lt",
    event="SEPA Direct Debit leftover leftover leftover",
    fail_event="SEPA Direct Debit leftover leftover leftover",
    pk="sdd_id",
    fail_pk="late_sdd_id",
    ctor="sdel",
    rid="sd",
    rg="sepa_dd_leftover|elv_leftover|sdd",
    fail_rg="late_sepa_dd|elv_posted|sdd",
    avoided="r278 UnionPay leftover already skip; r312 SEPA Instant leftover leftover leftover vs TARGET2; r323 TIPS leftover leftover leftover vs SEPA CT",
    fail_avoided="r341 SEPA Direct Debit leftover leftover leftover bind. This is late SEPA Direct Debit after leftover leftover leftover ELV",
    token_col="sdd",
    result_val="SDD01",
    leftover_check="sdel_leftover_open",
    extra_col="  sdd text UNIQUE",
    fail_extra="  leftover_id text NOT NULL",
    surfaces="SEPA Direct Debit leftover leftover leftover vs leftover leftover leftover ELV same sdd",
    fail_surfaces="late SEPA Direct Debit leftover leftover leftover after leftover leftover leftover ELV posted",
    this_is="leftover leftover leftover bind; SEPA Direct Debit posts leftover_id; leftover leftover leftover ELV binds only",
    fail_this="late leftover leftover leftover flags; leftover leftover leftover ELV stays",
    seed="SEPA Direct Debit leftover leftover leftover + leftover leftover leftover ELV same sdd",
    fail_seed="leftover leftover leftover ELV posted then late SEPA Direct Debit leftover leftover leftover",
    counterpart="leftover leftover leftover ELV",
    key_name="sdd",
)

leftover3(
    ok_slug="blik-leftover-vs-przelewy24",
    fail_slug="blik-after-przelewy24",
    stem="blp4_ll",
    fail_stem="blp4_lt",
    event="BLIK leftover leftover leftover",
    fail_event="BLIK leftover leftover leftover",
    pk="p24_id",
    fail_pk="late_p24_id",
    ctor="blp4",
    rid="p4",
    rg="blik_leftover|przelewy24_leftover|p24",
    fail_rg="late_blik|przelewy24_posted|p24",
    avoided="r278 UnionPay leftover already skip; r321 BLIK leftover leftover leftover vs PayPo; r341 SEPA Direct Debit leftover leftover leftover",
    fail_avoided="r342 BLIK leftover leftover leftover bind. This is late BLIK after leftover leftover leftover Przelewy24",
    token_col="p24",
    result_val="P2401",
    leftover_check="blp4_leftover_open",
    extra_col="  p24 text UNIQUE",
    fail_extra="  leftover_id text NOT NULL",
    surfaces="BLIK leftover leftover leftover vs leftover leftover leftover Przelewy24 same p24",
    fail_surfaces="late BLIK leftover leftover leftover after leftover leftover leftover Przelewy24 posted",
    this_is="leftover leftover leftover bind; BLIK posts leftover_id; leftover leftover leftover Przelewy24 binds only",
    fail_this="late leftover leftover leftover flags; leftover leftover leftover Przelewy24 stays",
    seed="BLIK leftover leftover leftover + leftover leftover leftover Przelewy24 same p24",
    fail_seed="leftover leftover leftover Przelewy24 posted then late BLIK leftover leftover leftover",
    counterpart="leftover leftover leftover Przelewy24",
    key_name="p24",
)

leftover3(
    ok_slug="swish-leftover-vs-bankgirot",
    fail_slug="swish-after-bankgirot",
    stem="swbg_ll",
    fail_stem="swbg_lt",
    event="Swish leftover leftover leftover",
    fail_event="Swish leftover leftover leftover",
    pk="bg_id",
    fail_pk="late_bg_id",
    ctor="swbg",
    rid="bg",
    rg="swish_leftover|bankgirot_leftover|bg",
    fail_rg="late_swish|bankgirot_posted|bg",
    avoided="r278 UnionPay leftover already skip; r319 Swish leftover leftover leftover vs MobilePay; r342 BLIK leftover leftover leftover vs Przelewy24",
    fail_avoided="r343 Swish leftover leftover leftover bind. This is late Swish after leftover leftover leftover Bankgirot",
    token_col="bg",
    result_val="BGR01",
    leftover_check="swbg_leftover_open",
    extra_col="  bg text UNIQUE",
    fail_extra="  leftover_id text NOT NULL",
    surfaces="Swish leftover leftover leftover vs leftover leftover leftover Bankgirot same bg",
    fail_surfaces="late Swish leftover leftover leftover after leftover leftover leftover Bankgirot posted",
    this_is="leftover leftover leftover bind; Swish posts leftover_id; leftover leftover leftover Bankgirot binds only",
    fail_this="late leftover leftover leftover flags; leftover leftover leftover Bankgirot stays",
    seed="Swish leftover leftover leftover + leftover leftover leftover Bankgirot same bg",
    fail_seed="leftover leftover leftover Bankgirot posted then late Swish leftover leftover leftover",
    counterpart="leftover leftover leftover Bankgirot",
    key_name="bg",
)

leftover3(
    ok_slug="vipps-leftover-vs-bankaxept",
    fail_slug="vipps-after-bankaxept",
    stem="vpba_ll",
    fail_stem="vpba_lt",
    event="Vipps leftover leftover leftover",
    fail_event="Vipps leftover leftover leftover",
    pk="axept_id",
    fail_pk="late_axept_id",
    ctor="vpba",
    rid="ba",
    rg="vipps_leftover|bankaxept_leftover|axept",
    fail_rg="late_vipps|bankaxept_posted|axept",
    avoided="r278 UnionPay leftover already skip; r320 Vipps leftover leftover leftover vs Twint; r343 Swish leftover leftover leftover vs Bankgirot",
    fail_avoided="r344 Vipps leftover leftover leftover bind. This is late Vipps after leftover leftover leftover BankAxept",
    token_col="axept",
    result_val="BXP01",
    leftover_check="vpba_leftover_open",
    extra_col="  axept text UNIQUE",
    fail_extra="  leftover_id text NOT NULL",
    surfaces="Vipps leftover leftover leftover vs leftover leftover leftover BankAxept same axept",
    fail_surfaces="late Vipps leftover leftover leftover after leftover leftover leftover BankAxept posted",
    this_is="leftover leftover leftover bind; Vipps posts leftover_id; leftover leftover leftover BankAxept binds only",
    fail_this="late leftover leftover leftover flags; leftover leftover leftover BankAxept stays",
    seed="Vipps leftover leftover leftover + leftover leftover leftover BankAxept same axept",
    fail_seed="leftover leftover leftover BankAxept posted then late Vipps leftover leftover leftover",
    counterpart="leftover leftover leftover BankAxept",
    key_name="axept",
)

leftover3(
    ok_slug="interac-leftover-vs-lynx",
    fail_slug="interac-after-lynx",
    stem="inlx_ll",
    fail_stem="inlx_lt",
    event="Interac leftover leftover leftover",
    fail_event="Interac leftover leftover leftover",
    pk="lynx_id",
    fail_pk="late_lynx_id",
    ctor="inlx",
    rid="lx",
    rg="interac_leftover|lynx_leftover|lynx",
    fail_rg="late_interac|lynx_posted|lynx",
    avoided="r278 UnionPay leftover already skip; r311 Interac leftover leftover leftover vs Autodeposit; r344 Vipps leftover leftover leftover vs BankAxept",
    fail_avoided="r345 Interac leftover leftover leftover bind. This is late Interac after leftover leftover leftover Lynx",
    token_col="lynx",
    result_val="LNX01",
    leftover_check="inlx_leftover_open",
    extra_col="  lynx text UNIQUE",
    fail_extra="  leftover_id text NOT NULL",
    surfaces="Interac leftover leftover leftover vs leftover leftover leftover Lynx same lynx",
    fail_surfaces="late Interac leftover leftover leftover after leftover leftover leftover Lynx posted",
    this_is="leftover leftover leftover bind; Interac posts leftover_id; leftover leftover leftover Lynx binds only",
    fail_this="late leftover leftover leftover flags; leftover leftover leftover Lynx stays",
    seed="Interac leftover leftover leftover + leftover leftover leftover Lynx same lynx",
    fail_seed="leftover leftover leftover Lynx posted then late Interac leftover leftover leftover",
    counterpart="leftover leftover leftover Lynx",
    key_name="lynx",
)
