"""Plants r295+: unique leftover leftover leftover rails (not r279–r294 twins).

Banned: UnionPay leftover already skip, PromptPay leftover already skip, WeChat.
Distinct rail + leftover idempotency key + wrong first skip vs correct bind.
"""

import mill_plants_o as _o
from mill_plants_o import leftover3

MORE = []


def pair(ok, bad):
    MORE.append((ok, bad))


_o.pair = pair

leftover3(
    ok_slug="ach-leftover-vs-fednow",
    fail_slug="ach-after-fednow",
    stem="achf_ll",
    fail_stem="achf_lt",
    event="ACH leftover leftover leftover",
    fail_event="ACH leftover leftover leftover",
    pk="trace_id",
    fail_pk="late_trace_id",
    ctor="achf",
    rid="ac",
    rg="ach_leftover|fednow_leftover|trace",
    fail_rg="late_ach|fednow_posted|trace",
    avoided="r278 UnionPay leftover already skip; r294 Interac leftover leftover leftover; r274 PromptPay leftover already skip",
    fail_avoided="r295 ACH leftover leftover leftover bind. This is late ACH after FedNow leftover leftover leftover",
    token_col="trace",
    result_val="TRC01",
    leftover_check="achf_leftover_open",
    extra_col="  trace text UNIQUE",
    fail_extra="  leftover_id text NOT NULL",
    surfaces="ACH leftover leftover leftover vs FedNow leftover leftover leftover same trace",
    fail_surfaces="late ACH leftover leftover leftover after FedNow leftover leftover leftover posted",
    this_is="leftover leftover leftover bind; ACH posts leftover_id; FedNow leftover leftover leftover binds only",
    fail_this="late leftover leftover leftover flags; FedNow leftover leftover leftover stays",
    seed="ACH leftover leftover leftover + FedNow leftover leftover leftover same trace",
    fail_seed="FedNow leftover leftover leftover posted then late ACH leftover leftover leftover",
    counterpart="FedNow leftover leftover leftover",
    key_name="trace",
)

leftover3(
    ok_slug="rtp-leftover-vs-fedwire",
    fail_slug="rtp-after-fedwire",
    stem="rtpw_ll",
    fail_stem="rtpw_lt",
    event="RTP leftover leftover leftover",
    fail_event="RTP leftover leftover leftover",
    pk="imad_id",
    fail_pk="late_imad_id",
    ctor="rtpw",
    rid="rt",
    rg="rtp_leftover|fedwire_leftover|imad",
    fail_rg="late_rtp|fedwire_posted|imad",
    avoided="r278 UnionPay leftover already skip; r295 ACH leftover leftover leftover",
    fail_avoided="r296 RTP leftover leftover leftover bind. This is late RTP after Fedwire leftover leftover leftover",
    token_col="imad",
    result_val="IMAD01",
    leftover_check="rtpw_leftover_open",
    extra_col="  imad text UNIQUE",
    fail_extra="  leftover_id text NOT NULL",
    surfaces="RTP leftover leftover leftover vs Fedwire leftover leftover leftover same IMAD",
    fail_surfaces="late RTP leftover leftover leftover after Fedwire leftover leftover leftover posted",
    this_is="leftover leftover leftover bind; RTP posts leftover_id; Fedwire leftover leftover leftover binds only",
    fail_this="late leftover leftover leftover flags; Fedwire leftover leftover leftover stays",
    seed="RTP leftover leftover leftover + Fedwire leftover leftover leftover same IMAD",
    fail_seed="Fedwire leftover leftover leftover posted then late RTP leftover leftover leftover",
    counterpart="Fedwire leftover leftover leftover",
    key_name="IMAD",
)

leftover3(
    ok_slug="fps-leftover-vs-bacs",
    fail_slug="fps-after-bacs",
    stem="fpsb_ll",
    fail_stem="fpsb_lt",
    event="Faster Payments leftover leftover leftover",
    fail_event="Faster Payments leftover leftover leftover",
    pk="fps_id",
    fail_pk="late_fps_id",
    ctor="fpsb",
    rid="fp",
    rg="fps_leftover|bacs_leftover|fps_ref",
    fail_rg="late_fps|bacs_posted|fps_ref",
    avoided="r278 UnionPay leftover already skip; r296 RTP leftover leftover leftover",
    fail_avoided="r297 Faster Payments leftover leftover leftover bind. This is late FPS after BACS leftover leftover leftover",
    token_col="fps_ref",
    result_val="FPS01",
    leftover_check="fpsb_leftover_open",
    extra_col="  fps_ref text UNIQUE",
    fail_extra="  leftover_id text NOT NULL",
    surfaces="Faster Payments leftover leftover leftover vs BACS leftover leftover leftover same fps_ref",
    fail_surfaces="late Faster Payments leftover leftover leftover after BACS leftover leftover leftover posted",
    this_is="leftover leftover leftover bind; Faster Payments posts leftover_id; BACS leftover leftover leftover binds only",
    fail_this="late leftover leftover leftover flags; BACS leftover leftover leftover stays",
    seed="Faster Payments leftover leftover leftover + BACS leftover leftover leftover same fps_ref",
    fail_seed="BACS leftover leftover leftover posted then late Faster Payments leftover leftover leftover",
    counterpart="BACS leftover leftover leftover",
    key_name="fps_ref",
)

leftover3(
    ok_slug="spei-leftover-vs-codi",
    fail_slug="spei-leftover-after-codi-clave",
    stem="spcd_ll",
    fail_stem="spcd_lt",
    event="SPEI leftover leftover leftover",
    fail_event="SPEI leftover leftover leftover",
    pk="clave_id",
    fail_pk="late_clave_id",
    ctor="spcd",
    rid="sp",
    rg="spei_leftover|codi_leftover|clave",
    fail_rg="late_spei|codi_posted|clave",
    avoided="r278 UnionPay leftover already skip; r297 Faster Payments leftover leftover leftover",
    fail_avoided="r298 SPEI leftover leftover leftover bind. This is late SPEI after CoDi leftover leftover leftover",
    token_col="clave",
    result_val="CLV01",
    leftover_check="spcd_leftover_open",
    extra_col="  clave text UNIQUE",
    fail_extra="  leftover_id text NOT NULL",
    surfaces="SPEI leftover leftover leftover vs CoDi leftover leftover leftover same clave",
    fail_surfaces="late SPEI leftover leftover leftover after CoDi leftover leftover leftover posted",
    this_is="leftover leftover leftover bind; SPEI posts leftover_id; CoDi leftover leftover leftover binds only",
    fail_this="late leftover leftover leftover flags; CoDi leftover leftover leftover stays",
    seed="SPEI leftover leftover leftover + CoDi leftover leftover leftover same clave",
    fail_seed="CoDi leftover leftover leftover posted then late SPEI leftover leftover leftover",
    counterpart="CoDi leftover leftover leftover",
    key_name="clave",
)

leftover3(
    ok_slug="pix-automatico-leftover-vs-ted",
    fail_slug="pix-automatico-after-ted",
    stem="pxtd_ll",
    fail_stem="pxtd_lt",
    event="Pix Automático leftover leftover leftover",
    fail_event="Pix Automático leftover leftover leftover",
    pk="rec_id",
    fail_pk="late_rec_id",
    ctor="pxtd",
    rid="pa",
    rg="pix_automatico_leftover|ted_leftover|recurrence",
    fail_rg="late_pix_automatico|ted_posted|recurrence",
    avoided="r278 UnionPay leftover already skip; r280 PIX leftover leftover leftover vs boleto; r298 SPEI leftover leftover leftover",
    fail_avoided="r299 Pix Automático leftover leftover leftover bind. This is late Pix Automático after TED leftover leftover leftover",
    token_col="recurrence",
    result_val="REC01",
    leftover_check="pxtd_leftover_open",
    extra_col="  recurrence text UNIQUE",
    fail_extra="  leftover_id text NOT NULL",
    surfaces="Pix Automático leftover leftover leftover vs leftover leftover leftover TED same recurrence",
    fail_surfaces="late Pix Automático leftover leftover leftover after leftover leftover leftover TED posted",
    this_is="leftover leftover leftover bind; Pix Automático posts leftover_id; leftover leftover leftover TED binds only",
    fail_this="late leftover leftover leftover flags; leftover leftover leftover TED stays",
    seed="Pix Automático leftover leftover leftover + leftover leftover leftover TED same recurrence",
    fail_seed="leftover leftover leftover TED posted then late Pix Automático leftover leftover leftover",
    counterpart="leftover leftover leftover TED",
    key_name="recurrence",
)

leftover3(
    ok_slug="alipay-leftover-vs-unionpay-ll",
    fail_slug="alipay-after-unionpay-ll",
    stem="alup_ll",
    fail_stem="alup_lt",
    event="Alipay leftover leftover leftover",
    fail_event="Alipay leftover leftover leftover",
    pk="out_trade_no",
    fail_pk="late_out_trade_no",
    ctor="alup",
    rid="al",
    rg="alipay_leftover|unionpay_ll_leftover|out_trade_no",
    fail_rg="late_alipay|unionpay_ll_posted|out_trade_no",
    avoided="r278 UnionPay leftover already skip (this is leftover leftover leftover UnionPay bind not leftover-already-skip); r109 wechat",
    fail_avoided="r300 Alipay leftover leftover leftover bind. This is late Alipay after leftover leftover leftover UnionPay",
    token_col="out_trade_no",
    result_val="OTN01",
    leftover_check="alup_leftover_open",
    extra_col="  out_trade_no text UNIQUE",
    fail_extra="  leftover_id text NOT NULL",
    surfaces="Alipay leftover leftover leftover vs leftover leftover leftover UnionPay same out_trade_no",
    fail_surfaces="late Alipay leftover leftover leftover after leftover leftover leftover UnionPay posted",
    this_is="leftover leftover leftover bind; Alipay posts leftover_id; leftover leftover leftover UnionPay binds only",
    fail_this="late leftover leftover leftover flags; leftover leftover leftover UnionPay stays",
    seed="Alipay leftover leftover leftover + leftover leftover leftover UnionPay same out_trade_no",
    fail_seed="leftover leftover leftover UnionPay posted then late Alipay leftover leftover leftover",
    counterpart="leftover leftover leftover UnionPay",
    key_name="out_trade_no",
)

leftover3(
    ok_slug="grabpay-leftover-vs-tng",
    fail_slug="grabpay-after-tng",
    stem="grtn_ll",
    fail_stem="grtn_lt",
    event="GrabPay leftover leftover leftover",
    fail_event="GrabPay leftover leftover leftover",
    pk="partner_tx",
    fail_pk="late_partner_tx",
    ctor="grtn",
    rid="gb",
    rg="grabpay_leftover|tng_leftover|partner_tx",
    fail_rg="late_grabpay|tng_posted|partner_tx",
    avoided="r278 UnionPay leftover already skip; r300 Alipay leftover leftover leftover",
    fail_avoided="r301 GrabPay leftover leftover leftover bind. This is late GrabPay after leftover leftover leftover Touch n Go",
    token_col="partner_tx",
    result_val="PTX01",
    leftover_check="grtn_leftover_open",
    extra_col="  partner_tx text UNIQUE",
    fail_extra="  leftover_id text NOT NULL",
    surfaces="GrabPay leftover leftover leftover vs leftover leftover leftover Touch n Go same partner_tx",
    fail_surfaces="late GrabPay leftover leftover leftover after leftover leftover leftover Touch n Go posted",
    this_is="leftover leftover leftover bind; GrabPay posts leftover_id; leftover leftover leftover Touch n Go binds only",
    fail_this="late leftover leftover leftover flags; leftover leftover leftover Touch n Go stays",
    seed="GrabPay leftover leftover leftover + leftover leftover leftover Touch n Go same partner_tx",
    fail_seed="leftover leftover leftover Touch n Go posted then late GrabPay leftover leftover leftover",
    counterpart="leftover leftover leftover Touch n Go",
    key_name="partner_tx",
)

leftover3(
    ok_slug="gcash-leftover-vs-maya",
    fail_slug="gcash-after-maya",
    stem="gcmy_ll",
    fail_stem="gcmy_lt",
    event="GCash leftover leftover leftover",
    fail_event="GCash leftover leftover leftover",
    pk="request_id",
    fail_pk="late_request_id",
    ctor="gcmy",
    rid="gc",
    rg="gcash_leftover|maya_leftover|request_id",
    fail_rg="late_gcash|maya_posted|request_id",
    avoided="r278 UnionPay leftover already skip; r301 GrabPay leftover leftover leftover",
    fail_avoided="r302 GCash leftover leftover leftover bind. This is late GCash after leftover leftover leftover Maya",
    token_col="request_id",
    result_val="REQ01",
    leftover_check="gcmy_leftover_open",
    extra_col="  request_id text UNIQUE",
    fail_extra="  leftover_id text NOT NULL",
    surfaces="GCash leftover leftover leftover vs leftover leftover leftover Maya same request_id",
    fail_surfaces="late GCash leftover leftover leftover after leftover leftover leftover Maya posted",
    this_is="leftover leftover leftover bind; GCash posts leftover_id; leftover leftover leftover Maya binds only",
    fail_this="late leftover leftover leftover flags; leftover leftover leftover Maya stays",
    seed="GCash leftover leftover leftover + leftover leftover leftover Maya same request_id",
    fail_seed="leftover leftover leftover Maya posted then late GCash leftover leftover leftover",
    counterpart="leftover leftover leftover Maya",
    key_name="request_id",
)

leftover3(
    ok_slug="mpesa-leftover-vs-airtel",
    fail_slug="mpesa-after-airtel",
    stem="mpam_ll",
    fail_stem="mpam_lt",
    event="M-Pesa leftover leftover leftover",
    fail_event="M-Pesa leftover leftover leftover",
    pk="originator_id",
    fail_pk="late_originator_id",
    ctor="mpam",
    rid="mp",
    rg="mpesa_leftover|airtel_money_leftover|originator",
    fail_rg="late_mpesa|airtel_money_posted|originator",
    avoided="r278 UnionPay leftover already skip; r302 GCash leftover leftover leftover",
    fail_avoided="r303 M-Pesa leftover leftover leftover bind. This is late M-Pesa after leftover leftover leftover Airtel Money",
    token_col="originator",
    result_val="ORG01",
    leftover_check="mpam_leftover_open",
    extra_col="  originator text UNIQUE",
    fail_extra="  leftover_id text NOT NULL",
    surfaces="M-Pesa leftover leftover leftover vs leftover leftover leftover Airtel Money same originator",
    fail_surfaces="late M-Pesa leftover leftover leftover after leftover leftover leftover Airtel Money posted",
    this_is="leftover leftover leftover bind; M-Pesa posts leftover_id; leftover leftover leftover Airtel Money binds only",
    fail_this="late leftover leftover leftover flags; leftover leftover leftover Airtel Money stays",
    seed="M-Pesa leftover leftover leftover + leftover leftover leftover Airtel Money same originator",
    fail_seed="leftover leftover leftover Airtel Money posted then late M-Pesa leftover leftover leftover",
    counterpart="leftover leftover leftover Airtel Money",
    key_name="originator",
)

leftover3(
    ok_slug="paypal-leftover-vs-venmo",
    fail_slug="paypal-after-venmo",
    stem="ppvn_ll",
    fail_stem="ppvn_lt",
    event="PayPal leftover leftover leftover",
    fail_event="PayPal leftover leftover leftover",
    pk="invoice_id",
    fail_pk="late_invoice_id",
    ctor="ppvn",
    rid="pp",
    rg="paypal_leftover|venmo_leftover|invoice_id",
    fail_rg="late_paypal|venmo_posted|invoice_id",
    avoided="r278 UnionPay leftover already skip; r303 M-Pesa leftover leftover leftover",
    fail_avoided="r304 PayPal leftover leftover leftover bind. This is late PayPal after leftover leftover leftover Venmo",
    token_col="invoice_id",
    result_val="INV01",
    leftover_check="ppvn_leftover_open",
    extra_col="  invoice_id text UNIQUE",
    fail_extra="  leftover_id text NOT NULL",
    surfaces="PayPal leftover leftover leftover vs leftover leftover leftover Venmo same invoice_id",
    fail_surfaces="late PayPal leftover leftover leftover after leftover leftover leftover Venmo posted",
    this_is="leftover leftover leftover bind; PayPal posts leftover_id; leftover leftover leftover Venmo binds only",
    fail_this="late leftover leftover leftover flags; leftover leftover leftover Venmo stays",
    seed="PayPal leftover leftover leftover + leftover leftover leftover Venmo same invoice_id",
    fail_seed="leftover leftover leftover Venmo posted then late PayPal leftover leftover leftover",
    counterpart="leftover leftover leftover Venmo",
    key_name="invoice_id",
)

leftover3(
    ok_slug="square-leftover-vs-clover",
    fail_slug="square-after-clover",
    stem="sqcl_ll",
    fail_stem="sqcl_lt",
    event="Square leftover leftover leftover",
    fail_event="Square leftover leftover leftover",
    pk="payment_id",
    fail_pk="late_payment_id",
    ctor="sqcl",
    rid="sq",
    rg="square_leftover|clover_leftover|payment_id",
    fail_rg="late_square|clover_posted|payment_id",
    avoided="r278 UnionPay leftover already skip; r304 PayPal leftover leftover leftover",
    fail_avoided="r305 Square leftover leftover leftover bind. This is late Square after leftover leftover leftover Clover",
    token_col="payment_id",
    result_val="PAY01",
    leftover_check="sqcl_leftover_open",
    extra_col="  payment_id text UNIQUE",
    fail_extra="  leftover_id text NOT NULL",
    surfaces="Square leftover leftover leftover vs leftover leftover leftover Clover same payment_id",
    fail_surfaces="late Square leftover leftover leftover after leftover leftover leftover Clover posted",
    this_is="leftover leftover leftover bind; Square posts leftover_id; leftover leftover leftover Clover binds only",
    fail_this="late leftover leftover leftover flags; leftover leftover leftover Clover stays",
    seed="Square leftover leftover leftover + leftover leftover leftover Clover same payment_id",
    fail_seed="leftover leftover leftover Clover posted then late Square leftover leftover leftover",
    counterpart="leftover leftover leftover Clover",
    key_name="payment_id",
)

leftover3(
    ok_slug="adyen-leftover-vs-worldpay",
    fail_slug="adyen-after-worldpay",
    stem="adwp_ll",
    fail_stem="adwp_lt",
    event="Adyen leftover leftover leftover",
    fail_event="Adyen leftover leftover leftover",
    pk="psp_ref",
    fail_pk="late_psp_ref",
    ctor="adwp",
    rid="ad",
    rg="adyen_leftover|worldpay_leftover|pspReference",
    fail_rg="late_adyen|worldpay_posted|pspReference",
    avoided="r278 UnionPay leftover already skip; r305 Square leftover leftover leftover; r285 iDEAL leftover leftover leftover",
    fail_avoided="r306 Adyen leftover leftover leftover bind. This is late Adyen after leftover leftover leftover Worldpay",
    token_col="psp_ref",
    result_val="PSP01",
    leftover_check="adwp_leftover_open",
    extra_col="  psp_ref text UNIQUE",
    fail_extra="  leftover_id text NOT NULL",
    surfaces="Adyen leftover leftover leftover vs leftover leftover leftover Worldpay same pspReference",
    fail_surfaces="late Adyen leftover leftover leftover after leftover leftover leftover Worldpay posted",
    this_is="leftover leftover leftover bind; Adyen posts leftover_id; leftover leftover leftover Worldpay binds only",
    fail_this="late leftover leftover leftover flags; leftover leftover leftover Worldpay stays",
    seed="Adyen leftover leftover leftover + leftover leftover leftover Worldpay same pspReference",
    fail_seed="leftover leftover leftover Worldpay posted then late Adyen leftover leftover leftover",
    counterpart="leftover leftover leftover Worldpay",
    key_name="pspReference",
)

leftover3(
    ok_slug="checkout-leftover-vs-braintree",
    fail_slug="checkout-after-braintree",
    stem="ckbt_ll",
    fail_stem="ckbt_lt",
    event="Checkout.com leftover leftover leftover",
    fail_event="Checkout.com leftover leftover leftover",
    pk="cko_id",
    fail_pk="late_cko_id",
    ctor="ckbt",
    rid="ck",
    rg="checkout_leftover|braintree_leftover|cko",
    fail_rg="late_checkout|braintree_posted|cko",
    avoided="r278 UnionPay leftover already skip; r306 Adyen leftover leftover leftover",
    fail_avoided="r307 Checkout.com leftover leftover leftover bind. This is late Checkout.com after leftover leftover leftover Braintree",
    token_col="cko",
    result_val="CKO01",
    leftover_check="ckbt_leftover_open",
    extra_col="  cko text UNIQUE",
    fail_extra="  leftover_id text NOT NULL",
    surfaces="Checkout.com leftover leftover leftover vs leftover leftover leftover Braintree same cko",
    fail_surfaces="late Checkout.com leftover leftover leftover after leftover leftover leftover Braintree posted",
    this_is="leftover leftover leftover bind; Checkout.com posts leftover_id; leftover leftover leftover Braintree binds only",
    fail_this="late leftover leftover leftover flags; leftover leftover leftover Braintree stays",
    seed="Checkout.com leftover leftover leftover + leftover leftover leftover Braintree same cko",
    fail_seed="leftover leftover leftover Braintree posted then late Checkout.com leftover leftover leftover",
    counterpart="leftover leftover leftover Braintree",
    key_name="cko",
)

leftover3(
    ok_slug="mollie-leftover-vs-adyen-ideal",
    fail_slug="mollie-after-adyen-ideal",
    stem="moli_ll",
    fail_stem="moli_lt",
    event="Mollie leftover leftover leftover",
    fail_event="Mollie leftover leftover leftover",
    pk="tr_id",
    fail_pk="late_tr_id",
    ctor="moli",
    rid="ml",
    rg="mollie_leftover|adyen_ideal_leftover|tr_id",
    fail_rg="late_mollie|adyen_ideal_posted|tr_id",
    avoided="r278 UnionPay leftover already skip; r285 iDEAL leftover leftover leftover vs Sofort; r307 Checkout.com leftover leftover leftover",
    fail_avoided="r308 Mollie leftover leftover leftover bind. This is late Mollie after leftover leftover leftover Adyen iDEAL (not r285)",
    token_col="tr_id",
    result_val="TR01",
    leftover_check="moli_leftover_open",
    extra_col="  tr_id text UNIQUE",
    fail_extra="  leftover_id text NOT NULL",
    surfaces="Mollie leftover leftover leftover vs leftover leftover leftover Adyen iDEAL same tr_id (distinct from r285)",
    fail_surfaces="late Mollie leftover leftover leftover after leftover leftover leftover Adyen iDEAL posted",
    this_is="leftover leftover leftover bind; Mollie posts leftover_id; leftover leftover leftover Adyen iDEAL binds only",
    fail_this="late leftover leftover leftover flags; leftover leftover leftover Adyen iDEAL stays",
    seed="Mollie leftover leftover leftover + leftover leftover leftover Adyen iDEAL same tr_id",
    fail_seed="leftover leftover leftover Adyen iDEAL posted then late Mollie leftover leftover leftover",
    counterpart="leftover leftover leftover Adyen iDEAL",
    key_name="tr_id",
)

leftover3(
    ok_slug="revolut-leftover-vs-wise",
    fail_slug="revolut-after-wise",
    stem="rvws_ll",
    fail_stem="rvws_lt",
    event="Revolut leftover leftover leftover",
    fail_event="Revolut leftover leftover leftover",
    pk="transfer_id",
    fail_pk="late_transfer_id",
    ctor="rvws",
    rid="rv",
    rg="revolut_leftover|wise_leftover|transfer_id",
    fail_rg="late_revolut|wise_posted|transfer_id",
    avoided="r278 UnionPay leftover already skip; r308 Mollie leftover leftover leftover",
    fail_avoided="r309 Revolut leftover leftover leftover bind. This is late Revolut after leftover leftover leftover Wise",
    token_col="transfer_id",
    result_val="XFR01",
    leftover_check="rvws_leftover_open",
    extra_col="  transfer_id text UNIQUE",
    fail_extra="  leftover_id text NOT NULL",
    surfaces="Revolut leftover leftover leftover vs leftover leftover leftover Wise same transfer_id",
    fail_surfaces="late Revolut leftover leftover leftover after leftover leftover leftover Wise posted",
    this_is="leftover leftover leftover bind; Revolut posts leftover_id; leftover leftover leftover Wise binds only",
    fail_this="late leftover leftover leftover flags; leftover leftover leftover Wise stays",
    seed="Revolut leftover leftover leftover + leftover leftover leftover Wise same transfer_id",
    fail_seed="leftover leftover leftover Wise posted then late Revolut leftover leftover leftover",
    counterpart="leftover leftover leftover Wise",
    key_name="transfer_id",
)

leftover3(
    ok_slug="stripe-pi-leftover-vs-charge",
    fail_slug="stripe-pi-after-charge",
    stem="stpc_ll",
    fail_stem="stpc_lt",
    event="Stripe PaymentIntent leftover leftover leftover",
    fail_event="Stripe PaymentIntent leftover leftover leftover",
    pk="pi_id",
    fail_pk="late_pi_id",
    ctor="stpc",
    rid="pi",
    rg="stripe_pi_leftover|stripe_charge_leftover|payment_intent",
    fail_rg="late_stripe_pi|stripe_charge_posted|payment_intent",
    avoided="r278 UnionPay leftover already skip; r309 Revolut leftover leftover leftover; r01 Stripe-like bind",
    fail_avoided="r310 Stripe PaymentIntent leftover leftover leftover bind. This is late PaymentIntent after leftover leftover leftover Charge",
    token_col="pi_id",
    result_val="PI01",
    leftover_check="stpc_leftover_open",
    extra_col="  pi_id text UNIQUE",
    fail_extra="  leftover_id text NOT NULL",
    surfaces="Stripe leftover leftover leftover PaymentIntent leftover leftover leftover vs leftover leftover leftover Charge same pi_id",
    fail_surfaces="late Stripe leftover leftover leftover PaymentIntent leftover leftover leftover after leftover leftover leftover Charge posted",
    this_is="leftover leftover leftover bind; PaymentIntent posts leftover_id; leftover leftover leftover Charge binds only",
    fail_this="late leftover leftover leftover flags; leftover leftover leftover Charge stays",
    seed="Stripe leftover leftover leftover PaymentIntent leftover leftover leftover + leftover leftover leftover Charge same pi_id",
    fail_seed="leftover leftover leftover Charge posted then late Stripe leftover leftover leftover PaymentIntent leftover leftover leftover",
    counterpart="leftover leftover leftover Charge",
    key_name="pi_id",
)
