"""Plants r311+: unique leftover leftover leftover rails (not r295–r310 twins).

Banned: UnionPay leftover already skip, PromptPay leftover already skip, WeChat.
Search/docker ids never. Distinct rail + leftover leftover leftover idempotency.
"""

import mill_plants_o as _o
from mill_plants_o import leftover3

MORE = []


def pair(ok, bad):
    MORE.append((ok, bad))


_o.pair = pair

leftover3(
    ok_slug="interac-ll3-vs-etransfer",
    fail_slug="interac-ll3-after-etransfer",
    stem="inad_ll",
    fail_stem="inad_lt",
    event="Interac leftover leftover leftover",
    fail_event="Interac leftover leftover leftover",
    pk="ref_id",
    fail_pk="late_ref_id",
    ctor="inad",
    rid="in",
    rg="interac_leftover|autodeposit_leftover|ref",
    fail_rg="late_interac|autodeposit_posted|ref",
    avoided="r278 UnionPay leftover already skip; r294 Interac leftover leftover leftover; r310 Stripe PaymentIntent leftover leftover leftover",
    fail_avoided="r311 Interac leftover leftover leftover bind. This is late Interac after leftover leftover leftover Autodeposit",
    token_col="ref",
    result_val="REF01",
    leftover_check="inad_leftover_open",
    extra_col="  ref text UNIQUE",
    fail_extra="  leftover_id text NOT NULL",
    surfaces="Interac leftover leftover leftover vs leftover leftover leftover Autodeposit same ref",
    fail_surfaces="late Interac leftover leftover leftover after leftover leftover leftover Autodeposit posted",
    this_is="leftover leftover leftover bind; Interac posts leftover_id; leftover leftover leftover Autodeposit binds only",
    fail_this="late leftover leftover leftover flags; leftover leftover leftover Autodeposit stays",
    seed="Interac leftover leftover leftover + leftover leftover leftover Autodeposit same ref",
    fail_seed="leftover leftover leftover Autodeposit posted then late Interac leftover leftover leftover",
    counterpart="leftover leftover leftover Autodeposit",
    key_name="ref",
)

leftover3(
    ok_slug="sepa-instant-leftover-vs-target2",
    fail_slug="sepa-instant-after-target2",
    stem="sitg_ll",
    fail_stem="sitg_lt",
    event="SEPA Instant leftover leftover leftover",
    fail_event="SEPA Instant leftover leftover leftover",
    pk="e2e_id",
    fail_pk="late_e2e_id",
    ctor="sitg",
    rid="si",
    rg="sepa_instant_leftover|target2_leftover|e2e",
    fail_rg="late_sepa_instant|target2_posted|e2e",
    avoided="r278 UnionPay leftover already skip; r311 Interac leftover leftover leftover",
    fail_avoided="r312 SEPA Instant leftover leftover leftover bind. This is late SEPA Instant after leftover leftover leftover TARGET2",
    token_col="e2e",
    result_val="E2E01",
    leftover_check="sitg_leftover_open",
    extra_col="  e2e text UNIQUE",
    fail_extra="  leftover_id text NOT NULL",
    surfaces="SEPA Instant leftover leftover leftover vs leftover leftover leftover TARGET2 same e2e",
    fail_surfaces="late SEPA Instant leftover leftover leftover after leftover leftover leftover TARGET2 posted",
    this_is="leftover leftover leftover bind; SEPA Instant posts leftover_id; leftover leftover leftover TARGET2 binds only",
    fail_this="late leftover leftover leftover flags; leftover leftover leftover TARGET2 stays",
    seed="SEPA Instant leftover leftover leftover + leftover leftover leftover TARGET2 same e2e",
    fail_seed="leftover leftover leftover TARGET2 posted then late SEPA Instant leftover leftover leftover",
    counterpart="leftover leftover leftover TARGET2",
    key_name="e2e",
)

leftover3(
    ok_slug="upi-ll3-vs-rtgs",
    fail_slug="upi-ll3-after-rtgs",
    stem="upim_ll",
    fail_stem="upim_lt",
    event="UPI leftover leftover leftover",
    fail_event="UPI leftover leftover leftover",
    pk="rrn_id",
    fail_pk="late_rrn_id",
    ctor="upim",
    rid="up",
    rg="upi_leftover|rtgs_leftover|rrn",
    fail_rg="late_upi|rtgs_posted|rrn",
    avoided="r278 UnionPay leftover already skip; r312 SEPA Instant leftover leftover leftover",
    fail_avoided="r313 UPI leftover leftover leftover bind. This is late UPI after leftover leftover leftover RTGS",
    token_col="rrn",
    result_val="RRN01",
    leftover_check="upim_leftover_open",
    extra_col="  rrn text UNIQUE",
    fail_extra="  leftover_id text NOT NULL",
    surfaces="UPI leftover leftover leftover vs leftover leftover leftover RTGS same rrn",
    fail_surfaces="late UPI leftover leftover leftover after leftover leftover leftover RTGS posted",
    this_is="leftover leftover leftover bind; UPI posts leftover_id; leftover leftover leftover RTGS binds only",
    fail_this="late leftover leftover leftover flags; leftover leftover leftover RTGS stays",
    seed="UPI leftover leftover leftover + leftover leftover leftover RTGS same rrn",
    fail_seed="leftover leftover leftover RTGS posted then late UPI leftover leftover leftover",
    counterpart="leftover leftover leftover RTGS",
    key_name="rrn",
)

leftover3(
    ok_slug="zelle-leftover-vs-sameday-ach",
    fail_slug="zelle-after-sameday-ach",
    stem="zlsa_ll",
    fail_stem="zlsa_lt",
    event="Zelle leftover leftover leftover",
    fail_event="Zelle leftover leftover leftover",
    pk="zelle_id",
    fail_pk="late_zelle_id",
    ctor="zlsa",
    rid="zl",
    rg="zelle_leftover|sameday_ach_leftover|zelle",
    fail_rg="late_zelle|sameday_ach_posted|zelle",
    avoided="r278 UnionPay leftover already skip; r295 ACH leftover leftover leftover vs FedNow; r313 UPI leftover leftover leftover",
    fail_avoided="r314 Zelle leftover leftover leftover bind. This is late Zelle after leftover leftover leftover Same Day ACH",
    token_col="zelle",
    result_val="ZEL01",
    leftover_check="zlsa_leftover_open",
    extra_col="  zelle text UNIQUE",
    fail_extra="  leftover_id text NOT NULL",
    surfaces="Zelle leftover leftover leftover vs leftover leftover leftover Same Day ACH same zelle",
    fail_surfaces="late Zelle leftover leftover leftover after leftover leftover leftover Same Day ACH posted",
    this_is="leftover leftover leftover bind; Zelle posts leftover_id; leftover leftover leftover Same Day ACH binds only",
    fail_this="late leftover leftover leftover flags; leftover leftover leftover Same Day ACH stays",
    seed="Zelle leftover leftover leftover + leftover leftover leftover Same Day ACH same zelle",
    fail_seed="leftover leftover leftover Same Day ACH posted then late Zelle leftover leftover leftover",
    counterpart="leftover leftover leftover Same Day ACH",
    key_name="zelle",
)

leftover3(
    ok_slug="klarna-leftover-vs-afterpay",
    fail_slug="klarna-after-afterpay",
    stem="klap_ll",
    fail_stem="klap_lt",
    event="Klarna leftover leftover leftover",
    fail_event="Klarna leftover leftover leftover",
    pk="order_id",
    fail_pk="late_order_id",
    ctor="klap",
    rid="kl",
    rg="klarna_leftover|afterpay_leftover|order",
    fail_rg="late_klarna|afterpay_posted|order",
    avoided="r278 UnionPay leftover already skip; r314 Zelle leftover leftover leftover",
    fail_avoided="r315 Klarna leftover leftover leftover bind. This is late Klarna after leftover leftover leftover Afterpay",
    token_col="order_id",
    result_val="ORD01",
    leftover_check="klap_leftover_open",
    extra_col="  order_id text UNIQUE",
    fail_extra="  leftover_id text NOT NULL",
    surfaces="Klarna leftover leftover leftover vs leftover leftover leftover Afterpay same order_id",
    fail_surfaces="late Klarna leftover leftover leftover after leftover leftover leftover Afterpay posted",
    this_is="leftover leftover leftover bind; Klarna posts leftover_id; leftover leftover leftover Afterpay binds only",
    fail_this="late leftover leftover leftover flags; leftover leftover leftover Afterpay stays",
    seed="Klarna leftover leftover leftover + leftover leftover leftover Afterpay same order_id",
    fail_seed="leftover leftover leftover Afterpay posted then late Klarna leftover leftover leftover",
    counterpart="leftover leftover leftover Afterpay",
    key_name="order_id",
)

leftover3(
    ok_slug="affirm-leftover-vs-zip",
    fail_slug="affirm-after-zip",
    stem="afz3_ll",
    fail_stem="afz3_lt",
    event="Affirm leftover leftover leftover",
    fail_event="Affirm leftover leftover leftover",
    pk="loan_id",
    fail_pk="late_loan_id",
    ctor="afzp",
    rid="af",
    rg="affirm_leftover|zip_leftover|loan",
    fail_rg="late_affirm|zip_posted|loan",
    avoided="r278 UnionPay leftover already skip; r315 Klarna leftover leftover leftover",
    fail_avoided="r316 Affirm leftover leftover leftover bind. This is late Affirm after leftover leftover leftover Zip",
    token_col="loan",
    result_val="LN01",
    leftover_check="afz3_leftover_open",
    extra_col="  loan text UNIQUE",
    fail_extra="  leftover_id text NOT NULL",
    surfaces="Affirm leftover leftover leftover vs leftover leftover leftover Zip same loan",
    fail_surfaces="late Affirm leftover leftover leftover after leftover leftover leftover Zip posted",
    this_is="leftover leftover leftover bind; Affirm posts leftover_id; leftover leftover leftover Zip binds only",
    fail_this="late leftover leftover leftover flags; leftover leftover leftover Zip stays",
    seed="Affirm leftover leftover leftover + leftover leftover leftover Zip same loan",
    fail_seed="leftover leftover leftover Zip posted then late Affirm leftover leftover leftover",
    counterpart="leftover leftover leftover Zip",
    key_name="loan",
)

leftover3(
    ok_slug="applepay-leftover-vs-googlepay",
    fail_slug="applepay-after-googlepay",
    stem="apgp_ll",
    fail_stem="apgp_lt",
    event="Apple Pay leftover leftover leftover",
    fail_event="Apple Pay leftover leftover leftover",
    pk="dp_id",
    fail_pk="late_dp_id",
    ctor="apgp",
    rid="ap",
    rg="applepay_leftover|googlepay_leftover|dp",
    fail_rg="late_applepay|googlepay_posted|dp",
    avoided="r278 UnionPay leftover already skip; r316 Affirm leftover leftover leftover",
    fail_avoided="r317 Apple Pay leftover leftover leftover bind. This is late Apple Pay after leftover leftover leftover Google Pay",
    token_col="dp",
    result_val="DP01",
    leftover_check="apgp_leftover_open",
    extra_col="  dp text UNIQUE",
    fail_extra="  leftover_id text NOT NULL",
    surfaces="Apple Pay leftover leftover leftover vs leftover leftover leftover Google Pay same dp",
    fail_surfaces="late Apple Pay leftover leftover leftover after leftover leftover leftover Google Pay posted",
    this_is="leftover leftover leftover bind; Apple Pay posts leftover_id; leftover leftover leftover Google Pay binds only",
    fail_this="late leftover leftover leftover flags; leftover leftover leftover Google Pay stays",
    seed="Apple Pay leftover leftover leftover + leftover leftover leftover Google Pay same dp",
    fail_seed="leftover leftover leftover Google Pay posted then late Apple Pay leftover leftover leftover",
    counterpart="leftover leftover leftover Google Pay",
    key_name="dp",
)

leftover3(
    ok_slug="bizum-leftover-vs-mbway",
    fail_slug="bizum-after-mbway",
    stem="bzmw_ll",
    fail_stem="bzmw_lt",
    event="Bizum leftover leftover leftover",
    fail_event="Bizum leftover leftover leftover",
    pk="biz_id",
    fail_pk="late_biz_id",
    ctor="bzmw",
    rid="bz",
    rg="bizum_leftover|mbway_leftover|biz",
    fail_rg="late_bizum|mbway_posted|biz",
    avoided="r278 UnionPay leftover already skip; r317 Apple Pay leftover leftover leftover",
    fail_avoided="r318 Bizum leftover leftover leftover bind. This is late Bizum after leftover leftover leftover MB WAY",
    token_col="biz",
    result_val="BIZ01",
    leftover_check="bzmw_leftover_open",
    extra_col="  biz text UNIQUE",
    fail_extra="  leftover_id text NOT NULL",
    surfaces="Bizum leftover leftover leftover vs leftover leftover leftover MB WAY same biz",
    fail_surfaces="late Bizum leftover leftover leftover after leftover leftover leftover MB WAY posted",
    this_is="leftover leftover leftover bind; Bizum posts leftover_id; leftover leftover leftover MB WAY binds only",
    fail_this="late leftover leftover leftover flags; leftover leftover leftover MB WAY stays",
    seed="Bizum leftover leftover leftover + leftover leftover leftover MB WAY same biz",
    fail_seed="leftover leftover leftover MB WAY posted then late Bizum leftover leftover leftover",
    counterpart="leftover leftover leftover MB WAY",
    key_name="biz",
)

leftover3(
    ok_slug="swish-leftover-vs-mobilepay",
    fail_slug="swish-after-mobilepay",
    stem="swmp_ll",
    fail_stem="swmp_lt",
    event="Swish leftover leftover leftover",
    fail_event="Swish leftover leftover leftover",
    pk="swish_id",
    fail_pk="late_swish_id",
    ctor="swmp",
    rid="sw",
    rg="swish_leftover|mobilepay_leftover|swish",
    fail_rg="late_swish|mobilepay_posted|swish",
    avoided="r278 UnionPay leftover already skip; r318 Bizum leftover leftover leftover",
    fail_avoided="r319 Swish leftover leftover leftover bind. This is late Swish after leftover leftover leftover MobilePay",
    token_col="swish",
    result_val="SWS01",
    leftover_check="swmp_leftover_open",
    extra_col="  swish text UNIQUE",
    fail_extra="  leftover_id text NOT NULL",
    surfaces="Swish leftover leftover leftover vs leftover leftover leftover MobilePay same swish",
    fail_surfaces="late Swish leftover leftover leftover after leftover leftover leftover MobilePay posted",
    this_is="leftover leftover leftover bind; Swish posts leftover_id; leftover leftover leftover MobilePay binds only",
    fail_this="late leftover leftover leftover flags; leftover leftover leftover MobilePay stays",
    seed="Swish leftover leftover leftover + leftover leftover leftover MobilePay same swish",
    fail_seed="leftover leftover leftover MobilePay posted then late Swish leftover leftover leftover",
    counterpart="leftover leftover leftover MobilePay",
    key_name="swish",
)

leftover3(
    ok_slug="vipps-leftover-vs-twint",
    fail_slug="vipps-after-twint",
    stem="vptw_ll",
    fail_stem="vptw_lt",
    event="Vipps leftover leftover leftover",
    fail_event="Vipps leftover leftover leftover",
    pk="vipps_id",
    fail_pk="late_vipps_id",
    ctor="vptw",
    rid="vp",
    rg="vipps_leftover|twint_leftover|vipps",
    fail_rg="late_vipps|twint_posted|vipps",
    avoided="r278 UnionPay leftover already skip; r319 Swish leftover leftover leftover",
    fail_avoided="r320 Vipps leftover leftover leftover bind. This is late Vipps after leftover leftover leftover Twint",
    token_col="vipps",
    result_val="VPS01",
    leftover_check="vptw_leftover_open",
    extra_col="  vipps text UNIQUE",
    fail_extra="  leftover_id text NOT NULL",
    surfaces="Vipps leftover leftover leftover vs leftover leftover leftover Twint same vipps",
    fail_surfaces="late Vipps leftover leftover leftover after leftover leftover leftover Twint posted",
    this_is="leftover leftover leftover bind; Vipps posts leftover_id; leftover leftover leftover Twint binds only",
    fail_this="late leftover leftover leftover flags; leftover leftover leftover Twint stays",
    seed="Vipps leftover leftover leftover + leftover leftover leftover Twint same vipps",
    fail_seed="leftover leftover leftover Twint posted then late Vipps leftover leftover leftover",
    counterpart="leftover leftover leftover Twint",
    key_name="vipps",
)

leftover3(
    ok_slug="blik-ll3-vs-paypo",
    fail_slug="blik-ll3-after-paypo",
    stem="blp2_ll",
    fail_stem="blp2_lt",
    event="BLIK leftover leftover leftover",
    fail_event="BLIK leftover leftover leftover",
    pk="blik_id",
    fail_pk="late_blik_id",
    ctor="blp2",
    rid="bl",
    rg="blik_leftover|paypo_leftover|blik",
    fail_rg="late_blik|paypo_posted|blik",
    avoided="r278 UnionPay leftover already skip; r320 Vipps leftover leftover leftover",
    fail_avoided="r321 BLIK leftover leftover leftover bind. This is late BLIK after leftover leftover leftover PayPo",
    token_col="blik",
    result_val="BLK01",
    leftover_check="blp2_leftover_open",
    extra_col="  blik text UNIQUE",
    fail_extra="  leftover_id text NOT NULL",
    surfaces="BLIK leftover leftover leftover vs leftover leftover leftover PayPo same blik",
    fail_surfaces="late BLIK leftover leftover leftover after leftover leftover leftover PayPo posted",
    this_is="leftover leftover leftover bind; BLIK posts leftover_id; leftover leftover leftover PayPo binds only",
    fail_this="late leftover leftover leftover flags; leftover leftover leftover PayPo stays",
    seed="BLIK leftover leftover leftover + leftover leftover leftover PayPo same blik",
    fail_seed="leftover leftover leftover PayPo posted then late BLIK leftover leftover leftover",
    counterpart="leftover leftover leftover PayPo",
    key_name="blik",
)

leftover3(
    ok_slug="pix-ll3-vs-doc",
    fail_slug="pix-ll3-after-doc",
    stem="pxbl_ll",
    fail_stem="pxbl_lt",
    event="PIX leftover leftover leftover",
    fail_event="PIX leftover leftover leftover",
    pk="txid",
    fail_pk="late_txid",
    ctor="pxbl",
    rid="px",
    rg="pix_leftover|doc_leftover|txid",
    fail_rg="late_pix|doc_posted|txid",
    avoided="r278 UnionPay leftover already skip; r299 Pix Automático leftover leftover leftover vs TED; r321 BLIK leftover leftover leftover",
    fail_avoided="r322 PIX leftover leftover leftover bind. This is late PIX after leftover leftover leftover DOC",
    token_col="txid",
    result_val="TX01",
    leftover_check="pxbl_leftover_open",
    extra_col="  txid text UNIQUE",
    fail_extra="  leftover_id text NOT NULL",
    surfaces="PIX leftover leftover leftover vs leftover leftover leftover DOC same txid",
    fail_surfaces="late PIX leftover leftover leftover after leftover leftover leftover DOC posted",
    this_is="leftover leftover leftover bind; PIX posts leftover_id; leftover leftover leftover DOC binds only",
    fail_this="late leftover leftover leftover flags; leftover leftover leftover DOC stays",
    seed="PIX leftover leftover leftover + leftover leftover leftover DOC same txid",
    fail_seed="leftover leftover leftover DOC posted then late PIX leftover leftover leftover",
    counterpart="leftover leftover leftover DOC",
    key_name="txid",
)

leftover3(
    ok_slug="tips-leftover-vs-sepa-ct",
    fail_slug="tips-after-sepa-ct",
    stem="tpsc_ll",
    fail_stem="tpsc_lt",
    event="TIPS leftover leftover leftover",
    fail_event="TIPS leftover leftover leftover",
    pk="tips_id",
    fail_pk="late_tips_id",
    ctor="tpsc",
    rid="tp",
    rg="tips_leftover|sepa_ct_leftover|tips",
    fail_rg="late_tips|sepa_ct_posted|tips",
    avoided="r278 UnionPay leftover already skip; r312 SEPA Instant leftover leftover leftover; r322 PIX leftover leftover leftover",
    fail_avoided="r323 TIPS leftover leftover leftover bind. This is late TIPS after leftover leftover leftover SEPA CT",
    token_col="tips",
    result_val="TIP01",
    leftover_check="tpsc_leftover_open",
    extra_col="  tips text UNIQUE",
    fail_extra="  leftover_id text NOT NULL",
    surfaces="TIPS leftover leftover leftover vs leftover leftover leftover SEPA CT same tips",
    fail_surfaces="late TIPS leftover leftover leftover after leftover leftover leftover SEPA CT posted",
    this_is="leftover leftover leftover bind; TIPS posts leftover_id; leftover leftover leftover SEPA CT binds only",
    fail_this="late leftover leftover leftover flags; leftover leftover leftover SEPA CT stays",
    seed="TIPS leftover leftover leftover + leftover leftover leftover SEPA CT same tips",
    fail_seed="leftover leftover leftover SEPA CT posted then late TIPS leftover leftover leftover",
    counterpart="leftover leftover leftover SEPA CT",
    key_name="tips",
)

leftover3(
    ok_slug="paytm-leftover-vs-phonepe",
    fail_slug="paytm-after-phonepe",
    stem="ptpp_ll",
    fail_stem="ptpp_lt",
    event="Paytm leftover leftover leftover",
    fail_event="Paytm leftover leftover leftover",
    pk="paytm_id",
    fail_pk="late_paytm_id",
    ctor="ptpp",
    rid="pt",
    rg="paytm_leftover|phonepe_leftover|paytm",
    fail_rg="late_paytm|phonepe_posted|paytm",
    avoided="r278 UnionPay leftover already skip; r313 UPI leftover leftover leftover; r323 TIPS leftover leftover leftover",
    fail_avoided="r324 Paytm leftover leftover leftover bind. This is late Paytm after leftover leftover leftover PhonePe",
    token_col="paytm",
    result_val="PTM01",
    leftover_check="ptpp_leftover_open",
    extra_col="  paytm text UNIQUE",
    fail_extra="  leftover_id text NOT NULL",
    surfaces="Paytm leftover leftover leftover vs leftover leftover leftover PhonePe same paytm",
    fail_surfaces="late Paytm leftover leftover leftover after leftover leftover leftover PhonePe posted",
    this_is="leftover leftover leftover bind; Paytm posts leftover_id; leftover leftover leftover PhonePe binds only",
    fail_this="late leftover leftover leftover flags; leftover leftover leftover PhonePe stays",
    seed="Paytm leftover leftover leftover + leftover leftover leftover PhonePe same paytm",
    fail_seed="leftover leftover leftover PhonePe posted then late Paytm leftover leftover leftover",
    counterpart="leftover leftover leftover PhonePe",
    key_name="paytm",
)

leftover3(
    ok_slug="razorpay-leftover-vs-payu",
    fail_slug="razorpay-after-payu",
    stem="rzpu_ll",
    fail_stem="rzpu_lt",
    event="Razorpay leftover leftover leftover",
    fail_event="Razorpay leftover leftover leftover",
    pk="rzp_id",
    fail_pk="late_rzp_id",
    ctor="rzpu",
    rid="rz",
    rg="razorpay_leftover|payu_leftover|rzp",
    fail_rg="late_razorpay|payu_posted|rzp",
    avoided="r278 UnionPay leftover already skip; r324 Paytm leftover leftover leftover",
    fail_avoided="r325 Razorpay leftover leftover leftover bind. This is late Razorpay after leftover leftover leftover PayU",
    token_col="rzp",
    result_val="RZP01",
    leftover_check="rzpu_leftover_open",
    extra_col="  rzp text UNIQUE",
    fail_extra="  leftover_id text NOT NULL",
    surfaces="Razorpay leftover leftover leftover vs leftover leftover leftover PayU same rzp",
    fail_surfaces="late Razorpay leftover leftover leftover after leftover leftover leftover PayU posted",
    this_is="leftover leftover leftover bind; Razorpay posts leftover_id; leftover leftover leftover PayU binds only",
    fail_this="late leftover leftover leftover flags; leftover leftover leftover PayU stays",
    seed="Razorpay leftover leftover leftover + leftover leftover leftover PayU same rzp",
    fail_seed="leftover leftover leftover PayU posted then late Razorpay leftover leftover leftover",
    counterpart="leftover leftover leftover PayU",
    key_name="rzp",
)

leftover3(
    ok_slug="mercadopago-leftover-vs-nequi",
    fail_slug="mercadopago-after-nequi",
    stem="mpnq_ll",
    fail_stem="mpnq_lt",
    event="Mercado Pago leftover leftover leftover",
    fail_event="Mercado Pago leftover leftover leftover",
    pk="mp_id",
    fail_pk="late_mp_id",
    ctor="mpnq",
    rid="mp",
    rg="mercadopago_leftover|nequi_leftover|mp",
    fail_rg="late_mercadopago|nequi_posted|mp",
    avoided="r278 UnionPay leftover already skip; r325 Razorpay leftover leftover leftover",
    fail_avoided="r326 Mercado Pago leftover leftover leftover bind. This is late Mercado Pago after leftover leftover leftover Nequi",
    token_col="mp",
    result_val="MP01",
    leftover_check="mpnq_leftover_open",
    extra_col="  mp text UNIQUE",
    fail_extra="  leftover_id text NOT NULL",
    surfaces="Mercado Pago leftover leftover leftover vs leftover leftover leftover Nequi same mp",
    fail_surfaces="late Mercado Pago leftover leftover leftover after leftover leftover leftover Nequi posted",
    this_is="leftover leftover leftover bind; Mercado Pago posts leftover_id; leftover leftover leftover Nequi binds only",
    fail_this="late leftover leftover leftover flags; leftover leftover leftover Nequi stays",
    seed="Mercado Pago leftover leftover leftover + leftover leftover leftover Nequi same mp",
    fail_seed="leftover leftover leftover Nequi posted then late Mercado Pago leftover leftover leftover",
    counterpart="leftover leftover leftover Nequi",
    key_name="mp",
)

leftover3(
    ok_slug="konbini-leftover-vs-payeasy",
    fail_slug="konbini-after-payeasy",
    stem="kbpe_ll",
    fail_stem="kbpe_lt",
    event="Konbini leftover leftover leftover",
    fail_event="Konbini leftover leftover leftover",
    pk="konbini_id",
    fail_pk="late_konbini_id",
    ctor="kbpe",
    rid="kb",
    rg="konbini_leftover|payeasy_leftover|konbini",
    fail_rg="late_konbini|payeasy_posted|konbini",
    avoided="r278 UnionPay leftover already skip; r326 Mercado Pago leftover leftover leftover",
    fail_avoided="r327 Konbini leftover leftover leftover bind. This is late Konbini after leftover leftover leftover Pay-easy",
    token_col="konbini",
    result_val="KNB01",
    leftover_check="kbpe_leftover_open",
    extra_col="  konbini text UNIQUE",
    fail_extra="  leftover_id text NOT NULL",
    surfaces="Konbini leftover leftover leftover vs leftover leftover leftover Pay-easy same konbini",
    fail_surfaces="late Konbini leftover leftover leftover after leftover leftover leftover Pay-easy posted",
    this_is="leftover leftover leftover bind; Konbini posts leftover_id; leftover leftover leftover Pay-easy binds only",
    fail_this="late leftover leftover leftover flags; leftover leftover leftover Pay-easy stays",
    seed="Konbini leftover leftover leftover + leftover leftover leftover Pay-easy same konbini",
    fail_seed="leftover leftover leftover Pay-easy posted then late Konbini leftover leftover leftover",
    counterpart="leftover leftover leftover Pay-easy",
    key_name="konbini",
)

leftover3(
    ok_slug="ideal-leftover-vs-bancontact",
    fail_slug="ideal-after-bancontact",
    stem="idbc_ll",
    fail_stem="idbc_lt",
    event="iDEAL leftover leftover leftover",
    fail_event="iDEAL leftover leftover leftover",
    pk="ideal_id",
    fail_pk="late_ideal_id",
    ctor="idbc",
    rid="id",
    rg="ideal_leftover|bancontact_leftover|ideal",
    fail_rg="late_ideal|bancontact_posted|ideal",
    avoided="r278 UnionPay leftover already skip; r285 iDEAL leftover leftover leftover vs Sofort; r308 Mollie leftover leftover leftover vs Adyen iDEAL; r327 Konbini leftover leftover leftover",
    fail_avoided="r328 iDEAL leftover leftover leftover bind. This is late iDEAL after leftover leftover leftover Bancontact",
    token_col="ideal",
    result_val="IDL01",
    leftover_check="idbc_leftover_open",
    extra_col="  ideal text UNIQUE",
    fail_extra="  leftover_id text NOT NULL",
    surfaces="iDEAL leftover leftover leftover vs leftover leftover leftover Bancontact same ideal",
    fail_surfaces="late iDEAL leftover leftover leftover after leftover leftover leftover Bancontact posted",
    this_is="leftover leftover leftover bind; iDEAL posts leftover_id; leftover leftover leftover Bancontact binds only",
    fail_this="late leftover leftover leftover flags; leftover leftover leftover Bancontact stays",
    seed="iDEAL leftover leftover leftover + leftover leftover leftover Bancontact same ideal",
    fail_seed="leftover leftover leftover Bancontact posted then late iDEAL leftover leftover leftover",
    counterpart="leftover leftover leftover Bancontact",
    key_name="ideal",
)

leftover3(
    ok_slug="trustly-leftover-vs-sofort",
    fail_slug="trustly-after-sofort",
    stem="trsf_ll",
    fail_stem="trsf_lt",
    event="Trustly leftover leftover leftover",
    fail_event="Trustly leftover leftover leftover",
    pk="trustly_id",
    fail_pk="late_trustly_id",
    ctor="trsf",
    rid="tr",
    rg="trustly_leftover|sofort_leftover|trustly",
    fail_rg="late_trustly|sofort_posted|trustly",
    avoided="r278 UnionPay leftover already skip; r285 iDEAL leftover leftover leftover vs Sofort; r328 iDEAL leftover leftover leftover vs Bancontact",
    fail_avoided="r329 Trustly leftover leftover leftover bind. This is late Trustly after leftover leftover leftover Sofort",
    token_col="trustly",
    result_val="TRS01",
    leftover_check="trsf_leftover_open",
    extra_col="  trustly text UNIQUE",
    fail_extra="  leftover_id text NOT NULL",
    surfaces="Trustly leftover leftover leftover vs leftover leftover leftover Sofort same trustly",
    fail_surfaces="late Trustly leftover leftover leftover after leftover leftover leftover Sofort posted",
    this_is="leftover leftover leftover bind; Trustly posts leftover_id; leftover leftover leftover Sofort binds only",
    fail_this="late leftover leftover leftover flags; leftover leftover leftover Sofort stays",
    seed="Trustly leftover leftover leftover + leftover leftover leftover Sofort same trustly",
    fail_seed="leftover leftover leftover Sofort posted then late Trustly leftover leftover leftover",
    counterpart="leftover leftover leftover Sofort",
    key_name="trustly",
)
